= Inequalities

@lesson-description{Students apply knowledge of inequalities to create compound inequalities}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Describe the solution set of a compound @vocab{inequality}
* Explain the 'Boolean' datatype

|Student-Facing Lesson Goals
|
* I can use two or more inequalities together and describe the area they enclose.
* I can explain to someone else what a Boolean is.

|Key Points for the Facilitator
|
* The new Boolean datatype, while simple to explain, can be confusing for some students as parts of a Contract.  Remind students that @vocab{Boolean} is just another datatype, like Number, or Image, but it can only be one of two choices: true or false.   
* Functions that produce Booleans are typically questions, hence the ? part of the function names in this lesson (safe-left?, onscreen?).
* Role-playing can help students understand the jobs of `safe-left?`, `safe-right?`, and `onscreen?`.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.

|Materials
|
* https://docs.google.com/presentation/d/1hAgZUfSdRS_6_IQEGOU5ZT8YC4v1CQ6J8u2ub07FsrI/edit?usp=sharing[Google Slides]
* @link{https://docs.google.com/document/d/1WvlflsKM28IOwgyV2HttnGxul3sAUnL0-KOZhvb6C2s/edit, Inequalities Warmup}

Bootstrap Formative Assessments

* https://quizizz.com/admin/quiz/5a15ddbc4cfd311100865126?from=quizEditor[Unit 6 Quiz - Bootstrap: Algebra] (Quizizz)
* https://teacher.desmos.com/activitybuilder/custom/5a2de279b263be77d88f0e54[Unit 6 Bootstrap Algebra Review] (Desmos Activity)

Connection Activities

* https://teacher.desmos.com/inequalities[Inequalities Bundle] (Desmos Activities)
* https://quizizz.com/admin/quiz/56cf6ac2bb56dfc267b35f94/inequalities-and-graphing-inequali[Inequalities & Graphing Inequalities] (Quizizz)
* https://www.geogebra.org/m/Huq24Spq[Inequality Graph Illustrator] (Geogebra)
* https://quizizz.com/admin/quiz/5846cda05c74a6041c47566b/graphing-compound-inequalities[Graphing Compound Inequalities] (Quizizz)

|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Reinforcing (CCSSM)
|
* @std{6.EE.B.5}
* @std{7.EE.B.4}

|Approaching (CCSSM)
|
* @std{HSF.IF.A.2}

|Standards of Mathematical Practice
|
* @std{MP.1}
* @std{MP.4}

|Bootstrap Benchmarks
|
* @std{BS-DR.2}
* @std{BS-DR.3}
|===


== Get Ready:

Students should have their computer, contracts page, and pencil.

== Launch: (5 min)

Hand out, or have students open, the @link{https://docs.google.com/document/d/1WvlflsKM28IOwgyV2HttnGxul3sAUnL0-KOZhvb6C2s/edit, Inequalities Warmup} and complete with a partner.    

== Explore: (5 min)

Have students open the @link{https://www.wescheme.org/openEditor?publicId=48low6MazC&, Sam The Butterfly starter file}, _workbook page_, and investigate the program with their partner.  Let students figure out that they need to press "Run" to see what the program does, and that the arrow keys control Sam. 

== Discuss: (5 min)

* *What is something you noticed about this program?* 
+
_Sam can be moved with the arrow keys, the coordinates are displayed at the top of the screen, the coordinates are all in the 1st quadrant, etc._
* *What do you see when Sam is at (0,0)?  Why is that?* 
+
_You only see part of Sam's wing.  Sam's position is based on the center of Sam's image._
* *How far can Sam go to the left and stay within Mom's view?*  
+
_Up to, but not beyond, an x of -40._
* *How can we state this boundary mathematically?* 
+
_x >= -40 or x > -50_

=== Every time Sam moves, we want to check and see if Sam is safe.  This is a repetitive job, so it would make an excellent function!  Let's focus on keeping Sam safe on the left side first.

* *What will the contract for `safe-left?` look like?  What does it need to take in?  What will it give back?*  
+
_`safe-left?` should take in a Number (the x-coordinate) and return a Boolean (true if Sam is safe, false if not)_

== Practice: (10 min)

With their partners, students complete @worksheet-link{workbook-pages/Inequalities-EX1.adoc} to fix the `safe-left?` function and @worksheet-link{workbook-pages/Inequalities-EX2.adoc} to fix the `safe-right?` function and type them into their file to test.  

Students will notice that their `safe-left?` function keeps Sam from disappearing off the left, but `safe-right?` doesn't keep Sam from disappearing off the right side!  When students run into this, encourage them to look through the code to try and figure out why.

== Discuss II: (10 min)

* *What does `safe-left?` do?*  
+
_Checks to see if x is greater than -50_
* *What does `safe-right?` do?*
+
_Checks to see if x is less than 490_
* *What does `onscreen?` do?* 
+
_Answers may vary, let students drive the discussion!_

*Recruit some student volunteers to roleplay the functions `safe-left?`, `safe-right?` and `onscreen?` while giving function calls to `onscreen?`*

=== Role Play Example

*To visually demonstrate why `onscreen?` isn't preventing Sam from going off the right side, have students act it out!  The student who plays `onscreen?` will only ask the student playing `safe-left?` if Sam is safe, ignoring `safe-right?` at this point.  Have students watching discuss and explain what is happening and brainstorn how to fix `onscreen?`.*

These cues can be printed on the back of notecards to help student volunteers with their part.

* *Facilitator*: "onscreen-huh 70"
* *onscreen?*: "safe-left-huh 70"
* *safe-left?*: "true"
* *onscreen?*: "true"


* *Facilitator*: "onscreen-huh -100"
* *onscreen?*: "safe-left-huh -100"
* *safe-left?*: "false"
* *onscreen?*: "false"


* *Facilitator*: "onscreen-huh 600"
* *onscreen?*: "safe-left-huh 600"
* *safe-left?*: "true"
* *onscreen?*: "true"

* What is the problem with `onscreen?`? _It's only talking to `safe-left?`, it's not checking with `safe-right?`_
* How can `onscreen?` check with both?  _By using `and`_

*Guide students through examples of `and` and `or` with various statements, such as "I'm wearing a red shirt AND I'm a math teacher, true or false?" or "I'm an NBA basketball star OR I'm having pizza for lunch, true or false?".*  

* What is the contract for `and`? _``and: Boolean Boolean -> Boolean``_
* What functions did we create that return Boolean values? _``safe-left?`` and ``safe-right?``_

Have students complete @worksheet-link{workbook-pages/Inequalities-EX3.adoc} with their partner before moving on.

== Apply: (10 min)

Students use what they've learned to fix the `onscreen?` function and should now see that Sam cannot move off of the left or right sides of the screen.

[.strategy-box]
.Extension Option
****
What if we wanted to keep Sam safe on the top and bottom edges of the screen as well?  What additional functions would we need?  What functions would need to change?
****
