= Scatter Plots

@lesson-description{Students investigate scatter plots as a method of visualizing the relationship between two variables.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-plotting}
| Lesson Goals
| Students will be able to...

* make scatter plots by hand, given a list of (x,y) pairs
* make scatter plots using Pyret
* identify a possible correlation by looking at a point cloud

| Student-Facing Lesson Goals
| I can...

| Materials
|
* Lesson Slides (@link{https://docs.google.com/presentation/d/1RgRT61h69EHUDvpUKMPlnbjFv9D3rB7DZCqDWQ4CqiQ/, Google Slides})
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs
* All students should log into @link{https://code.pyret.org, CPO} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can @link{https://code.pyret.org/editor#share=1Z8ncVGKqWiED_wHl8TlNF3D9AGBb7awm, open a new one}

| Supplemental Resources
|

| Relevant Standards
|
@include{xtra/lang-prereq.adoc}
|===

== Relationships _Between_ Columns @duration{15 minutes}

=== Overview
Students are finally introduced to _Relate Questions_, which ask about the relationship between one quantitative column and another.

=== Launch
Why are some animals adopted quickly, while others take a long time? What factors explain why one pet gets adopted right away, and others wait months?

[.lesson-point]
Theory 1: Smaller animals get adopted faster because they’re easier to care for.

How could we test that theory? Bar and pie charts are great for showing us how the frequencies of values in a categorical column. Histograms and box plots are great for showing us the shape, center, and spread of a quantitative column. But none of these displays will help us see connections between two columns.

=== Investigate
[.lesson-instruction]
* Take a few minutes to look through the whole dataset, and see if you agree with the statement. 
* Could any of our visualizations or measures of center help us answer this question? 
* Write down your hypothesis on @workbook-link{pages/disproving-claim.adoc}, and how we could use this dataset to see if you’re right.


=== Synthesize
We’ve got a lot of tools in our toolkit that help us think about an entire _column_ of a dataset:

- We have ways to find measures of center and spread for a given column.
- We have visualizations that let us see the shape of values in a quantitative column.
- We have visualizations that let us see the frequencies a categorical column.

What column is this question asking about?

== Making Scatter Plots @duration{20 minutes}

=== Overview
Students are introduced to scatter plots, which are visualizations tailored to Relate Questions. They learn how to construct scatter plots by hand, and in Pyret.

=== Launch
This question is asking about _two columns_ in our dataset. Specifically, it’s asking *if there is a relationship* between `pounds` and `weeks`.

For each animal in the shelter, there are two data points we care about: how many `pounds` they weigh, and the number of `weeks` it took to be adopted.

=== Investigate
We can use these points to plot each animal as a point on a coordinate plane.

[.lesson-instruction]
Complete @workbook-link{pages/creating-scatterplot.adoc} in your Student Workbook.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Teaching Tip}

Divide the full table up into sub-lists, and have a few student plot 3-4 animals on the board. This can be done collaboratively, resulting in a whole-class scatterplot!
|===

[.lesson-instruction]
* Open your “Animals Starter File”. (If you do not have this file, or if something has happened to it, you can always make a @link{https://code.pyret.org/editor#share=1Z8ncVGKqWiED_wHl8TlNF3D9AGBb7awm, new copy}.)
* Make a scatter plot that displays the relationship between weight and adoption time.
* Are there any patterns or trends that you see here?
* Try making a few other scatter plots, looking for relationships between other columns in the `animals-table`.

=== Synthesize
Have students share their observations. What trends do they see? Are there any points that seem unusual? Why?

== Looking for Trends @duration{20 minutes}

=== Overview
Students are asked to identify patterns in their scatter plots. This activity builds towards the idea of correlations, but does not go into depth (as the following lesson does).

=== Launch

[.lesson-instruction]
* Can you see a “cloud” around which the points are clustered?
* Are there places where the “cloud” is denser than others?
* Does the number of weeks to adoption seem to go up or down as the age increases?
* Are there any points that “stray from the pack”? Which ones? 

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Teaching Tip}

Project the scatter plot at the front of the room, and have students come up to the plot to point out their patterns.
|===

@span{.right}{@centered-image{images/visualizing-relationships-1.png, "", 400}}
A straight-line pattern in the cloud of scatter plot points suggests that there is a linear relationship between two columns. In other words, there seems to be a straight-line relationship between `pounds` and `weeks`. There are data science methods to calculate the @vocab{line of best fit}, which can be useful for making predictions. For example, the line of best fit might predict how long a new dog would wait at the shelter, if the dog weighs 68 pounds.

Do any data points that seem unusually far above or below from the line? Which animals are those? These points are called @vocab{outliers}, meaning that they fall very far in a vertical direction from the line of best fit.

Outliers are always interesting:

* Sometimes they’re just random. Maybe Felix just met the right family early, or maybe we find out he lives nearby, got lost and his family came to get him. In that case, we might need to do some deep thinking about whether or not it’s appropriate to remove him from our dataset.
* Sometimes they can give you a deeper insight into your data. Maybe Felix is a special, popular breed of cat, and we discover that our dataset is missing an important column for breed!
* Sometimes outliers are the points we are looking for! What if we wanted to know which restaurants are a good value, and which are rip-offs? We could make a scatterplot of restaurant prices vs. reviews, an outlier that’s high above the rest of the points would be a restaurant whose reviews are _unusually good_ for the price. An outlier way below the cloud would be a really bad deal.

=== Investigate
[.lesson-instruction]
--
For practice, try making scatter plots for each of the following relationships. If you see any outliers, try to explain them!

* The `age` of an animal vs the `pounds` of the animal
* The `legs` of an animal vs the number of `weeks` to be adopted
* The `age` vs the number of `legs` it has.
* Do you see a correlation in any of these? Are there any outliers?
--

=== Synthesize
Debrief, showing the plots on the board. Make sure students see plots for which there is no relationship, like the last one!

[.lesson-point]
Theory 2: Younger animals get adopted faster because they are cuter.

It might be tempting to go straight into making a scatter plot to compare `age` and `weeks`. But different animals have very different lifespans! A 5yr-old tarantula is still really young, while a 5yr old rabbit is fully grown. With differences like this, it doesn’t make sense to put them all on the same scatter plot. By mixing them together, we may be  _hiding_ a real correlation! We might want to make several displays, one for each species.
