[.beta]
= Categorical Decision Trees

@description{Students explore an approach to recommending videos and predicting election outcomes. They develop and analyze decision trees to predict individuals’ purchasing decisions.}

@lesson-prereqs{data-driven-algorithms, dot-plots}


@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|

- Let's create, use, and understand decision trees, a model used to make recommendations and predict outcomes 

| Materials
|[.materials-links]
@material-links


|===

== Predicting Categories @duration{25 minutes}

@objective{ai-create-tree}

=== Overview

Students consider technologies that make predictions and recommendations, and then play a game to help them build a frame of reference for diagramming the decision-making process. By the end of this section, students should know:

- What a decision tree is
- That more than one tree can be constructed for a given dataset
- That decision trees can be "good" or "not good" depending on their shape
- That decision trees can be "good" or "not good" depending on the frequency of categories

=== Launch
@slidebreak{Launch}

Consider each of the three situations described below:

- You take an online quiz, which guesses your hairstyle.
- Two individuals who work for the same company and earn the same salary apply for a loan by filling out the same online form at the local bank. One of them is granted a loan, but the other is not.
- A news anchor displays a map with some states colored blue and others colored red. She explains that the map's predictions for the upcoming election were developed using historical census data.
- A camera at the bank captures a picture of your face, immediately identifying who you are.

What do all of these examples have in common?

@slidebreak{Launch}

On the surface, these situations may not seem to have a lot in common. But all of these are examples of @vocab{classifiers}, a family of @vocab{machine learning} algorithms that:

@indented{
(1) Take in some data

(2) Ask questions about that data

(2) Use the answers to predict an outcome from a list of categories
}

@QandA{
@Q{What data do you think is used for *guessing your hairstyle*?}
@A{Viewing history, search history, channel subscriptions, likes, dislikes, google activity, "not interested" feedback}

@Q{What data do you think is used for *approving loan requests*?}
@A{Debt, assets, payment history, number of open accounts, delinquent accounts, income/revenue, expenses, overdrafts in the last 90 days}

@Q{What data do you think is used to *predict election outcomes*?}
@A{Census data including voter race, gender, income level, party affiliation, and age, as well as prior years' results}
}

@slidebreak{Launch}

All categorical classifiers map various inputs to a specific set of categories.

[.data-table, cols="1a, 2a, 3a", options="header"]
|===
| Example 			| Input Data _(known)_				| Categories _(unknown)_
| Hairstyle Quiz	| Sex, age, race, music, ZIP... 	| Ponytail vs. Pixie cut vs. Dreadlocks vs. Mohawk...
| Bank Loan 		| Income, job, age, credit score... | Approved vs. Not-Approved
| Elections 		| Past voting, recent polls...	 	| Red vs. Blue
| Facial Recognition| Your face 						| Every person in America
|===

For example, the hairstyle quiz can probably rule out "ponytail" if the sex of the person taking the quiz is "male".  A classifier's job to make the best guess possible, and it won't always be right! After all, some people with ponytails are male!

@lesson-point{No classifier is perfect. _Some_ are useful.}

=== Investigate
@slidebreak{Investigate}

@vocab{Classifiers} use something called a @vocab{Decision Tree}, asking questions in order to narrow down the possible outcome categories until it reaches a single, predicted outcome.

If you've ever played the game "I spy", you've already got some practice building decision trees!

The rules are pretty simple:

- A player comes up with something they is visible to everyone playing
- They come up with a hint, to help narrow the possible answers. For example: "I spy with my little eye...something blue!"
- The other players ask yes-or-no questions to help them guess what it is

@slidebreak{Investigate}

@lesson-instruction{
@right{@image{images/tree-1.png}}
We're going to play a version of "I Spy", called "Classify"...

- Everyone will stand a their desks (or front of the room, etc)
- I'm going to choose one student as the secret, but keep the choice to myself
- All of you will take turns asking yes-or-no questions. For example, "are they wearing glasses?"
    - If I answer "yes", every student wearing glasses stays up, while the others return to their seats
    - If I answer "no", every student *not* wearing glasses stays up, while the others return to their seats
- I'll keep track of our progress on the board
}

@slidebreak{Investigate}

*Classify...a student in this class.* Who am I thinking of?

@teacher{
@right{@image{images/tree-2.png}}

- Let your students ask questions one at a time. Write each question on the board in the form of a flow-chart, with "yes edges" and "no edges" (lines labeled with "yes" or "no") branching out to the left and right.
- On each edge, write the number of students for whom each answer is "yes" and "no".
- For now, most of the tree will be empty: your students won't need to ask questions about those who already sat down!
}

@slidebreak{Investigate}

Congratulations! You were able to classify the student I had in mind, by asking just a few questions.

@QandA{
@Q{How many questions did it take for you to classify this student?}
@Q{Suppose you all just asked "are they named XYZ?" over and over, until we classified the student? Would you eventually have found the answer?}
@A{Yes}
@Q{Why didn't we do that?}
@A{It probably would have taken longer! Asking about groups helped us eliminate students and narrow down our choices faster.}
}

Let's play a few more rounds. This time, however, we can only _add_ to our @vocab{Decision Tree}: for everything else, we need to ask the same questions in the same order.

@teacher{
Play a few more rounds. Try to pick students that will force the class to add to their tree! For each student they classify, ask the class how many questions it took to find them.
[cols="^.3a,^2a,3a", grid="none", frame="none", stripes="none"]
|===
| @hspace{7em}**Round 1**
|
| @hspace{6em}**Round 2**

| @image{images/tree-2.png}
| @image{images/arrow.png, 50}
| @image{images/tree-3.png}
|===
}

@slidebreak{Synthesize}

@QandA{
@Q{In this game, what were our "categories"?}
@A{Students in the class}
@Q{How many categories did we have?}
@A{The number of students in the class}
@Q{If you could start over, how would you change this @vocab{decision tree}?}
@A{This is a big question! Give students some time to discuss}
@Q{How do you know if a question is a good one to start with or not?}
@A{Good questions help us eliminate many of the remaining categories whether the answer is yes _or_ no}
@Q{Suppose our first question was "has glasses?", and all but one student in the class wore glasses. How many questions would it take if I was thinking of the student who wears glasses?}
@A{Just one! If the answer is "yes", we know exactly who it is!}
@Q{Would that be the best question to start with, if we were going to play the game many times?}
@A{No, because if the answer is "no" we're basically still starting at the beginning}
}
@slidebreak{Synthesize}

@QandA{
@Q{How does someone use a decision tree to make predictions?}
@A{Ask the question at the root of the tree, then follow the branches to ask additional questions until we get to a category at the end of a path.}
@Q{Suppose we were playing "Classify", but now you have to guess which *country* I'm thinking of. What might be a good starting question?}
@A{Answers will vary, but look for answers that eliminate groups of countries quickly.}
@A{Is it a country in North America?}
@A{Is it a country where people speak Spanish?}
@A{etc...}
@Q{If we want to get to the correct categorization as quickly as possible, what would we want to be true about the first question we ask?}
@A{We would want it to split the list of options as evenly as possible to guarantee eliminating a significant number of options right off the bat.}
}


== Decision Trees and Confusion Matrices @duration{25 minutes}

@objective{ai-create-tree}

=== Overview
Students refine their intuition for building decision trees, discovering how they are constructed from training datasets.

=== Launch

@slidebreak{Launch}

A @vocab{decision tree} is a tree-shaped @vocab{model} that shows decisions and their predicted outcomes. The diagram of our "Classify" game is a partial decision tree. The examples we talked about at the beginning (Guess-the-haircut, Loan approvals, Election predictions, and facial recognition) all use decision trees.

You've learned that some @vocab{decision trees} are better than others. For example, the _frequency of each category_ affects the "best node" ("if everyone has glasses...").

@slidebreak{Launch}

@right{@image{images/terminology-tree.png, 300}}

- A @vocab{decision node} splits a dataset around the values in one of its columns. The attribute in the column serves as the "question" that is being asked.
- The @vocab{root node} is the very top @vocab{decision node}. It represents an entire dataset.
- @vocab{Splitting} is the process of creating branches and additional nodes corresponding to subsets of a dataset based on values in one column. (We're sticking to splits that only create two branch nodes, but some decisions trees use splits that create more than two.)
- A @vocab{leaf node} is a node that contains the predicted outcome. These outcomes come from a designated column in the original dataset. Leaf nodes have no outgoing branches.
- The sequence of questions from the root node to an outcome is called a path.

@teacher{Discuss the decision tree you made during your "Classify" game to help students identify the root node, decision nodes, leaf nodes, and paths on the tree so far.
}

=== Investigate
@slidebreak{Investigate}

Machine-learning algorithms generate decision trees from training @vocab{datasets}, using the column headers as questions.

[cols="3a, 2a", frame="none", border="none", grid="none"]
|===
|
[.data-table, cols="1,^1,^1,^1,^1,^1", stripes="none", options="header"]
!===
! name      ! species   ! sex         ! tail    ! mammal ! swims
! Firepaw   ! cat       ! male        ! TRUE    ! TRUE   ! FALSE
! Frisky    ! dog       ! female      ! TRUE    ! TRUE   ! TRUE
! Socks     ! dog       ! female      ! TRUE    ! TRUE   ! TRUE
! Stripe    ! dog       ! male        ! TRUE    ! TRUE   ! TRUE
! Snickers  ! dog       ! male        ! TRUE    ! TRUE   ! TRUE
! Leafpool  ! cat       ! female      ! TRUE    ! TRUE   ! FALSE
! Shadestar ! cat       ! female      ! TRUE    ! TRUE   ! TRUE
! Bramble   ! cat       ! female      ! TRUE    ! TRUE   ! FALSE
! Brick     ! cat       ! male        ! TRUE    ! TRUE   ! FALSE
! Bruni     ! lizard    ! female      ! TRUE    ! FALSE  ! TRUE
! Jesús     ! lizard    ! male        ! TRUE    ! FALSE  ! TRUE
! Gary      ! snail     !hermaphrodite! FALSE   ! FALSE  ! FALSE
! Turbo     ! snail     !hermaphrodite! FALSE   ! FALSE  ! FALSE
! Charlotte ! tarantula ! male        ! FALSE   ! FALSE  ! FALSE
! Webs      ! tarantula ! female      ! FALSE   ! FALSE  ! FALSE
!===

|
@image{images/animal-tree-1.png}
|===

@lesson-instruction{
- Turn to @printable-exercise{decision-tree-and-confusion-matrix.adoc}, and complete *the first section*. At this point, just make some observations about the dataset.
- Be ready to share your observations with the class!
}

@teacher{
Have the class discuss this dataset. It's important to note that there are Strings and Booleans in this dataset, and that there's one cat (`"Shadestar"`) who swims.
}

@slidebreak{InvestigateR}

@ifslide{
[cols="3a, 2a", frame="none", border="none", grid="none"]
|===
|
[.data-table, cols="1,^1,^1,^1,^1,^1", stripes="none", options="header"]
!===
! name      ! species   ! sex         ! tail    ! mammal ! swims
! Firepaw   ! cat       ! male        ! TRUE    ! TRUE   ! FALSE
! Frisky    ! dog       ! female      ! TRUE    ! TRUE   ! TRUE
! Socks     ! dog       ! female      ! TRUE    ! TRUE   ! TRUE
! Stripe    ! dog       ! male        ! TRUE    ! TRUE   ! TRUE
! Snickers  ! dog       ! male        ! TRUE    ! TRUE   ! TRUE
! Leafpool  ! cat       ! female      ! TRUE    ! TRUE   ! FALSE
! Shadestar ! cat       ! female      ! TRUE    ! TRUE   ! TRUE
! Bramble   ! cat       ! female      ! TRUE    ! TRUE   ! FALSE
! Brick     ! cat       ! male        ! TRUE    ! TRUE   ! FALSE
! Bruni     ! lizard    ! female      ! TRUE    ! FALSE  ! TRUE
! Jesús     ! lizard    ! male        ! TRUE    ! FALSE  ! TRUE
! Gary      ! snail     !hermaphrodite! FALSE   ! FALSE  ! FALSE
! Turbo     ! snail     !hermaphrodite! FALSE   ! FALSE  ! FALSE
! Charlotte ! tarantula ! male        ! FALSE   ! FALSE  ! FALSE
! Webs      ! tarantula ! female      ! FALSE   ! FALSE  ! FALSE
!===

|
@image{images/animal-tree-1.png}
|===
}
@QandA{
@Q{Which column from the table does the tree predict?}
@A{"species"}

@Q{Which columns are used as nodes for splitting this tree? Which are left out?}
@A{"sex" and "swims" are the only columns used for splitting}

@Q{Why do you think "name" is left out of tree?}
@A{It isn't part of the tree because that column doesn't have information that helps us predict the species of an animal.}

@Q{Where do the values in the "species" column end up in the tree?}
@A{They are in the leaf nodes.}

@Q{What rows of the table are we thinking about when the tree asks `mammal == true`?}
@A{The rows that are cats or dogs.}
}

@lesson-instruction{
- Complete *the second section* on @printable-exercise{decision-tree-and-confusion-matrix.adoc}.
}

@teacher{Have students share their findings. It's important to note that the tree doesn't include lizards or tarantulas, so Bruni, Jésus, Charlotte, and Webs will be mis-classified.}

@slidebreak{Investigate}

How do we know if a @vocab{decision tree} makes a good @vocab{classifier} or not?

@lesson-instruction{
Data Scientists and Machine Language Engineers don't just give classifiers a single score. Instead, they score them based on how many items in the dataset were _correctly_ classified, and how many were _mis_-classified as other categories.

Complete the last section on @printable-exercise{decision-tree-and-confusion-matrix.adoc}
}

@slidebreak{Investigate}
Data Scientists and Machine Language Engineers call this "report card" a @vocab{Confusion Matrix}. Confusion matrices typically work in terms of _percentages:_ 4-out-of-5 cats becomes 80%, 2-out-of-2 lizards becomes 100%, and so on:

[.data-table, cols="1a,^1a,^1a,^1a,^1a,^1a", options="header"]
|===
|actual-species	|predicted-cat|predicted-dog|predicted-lizard|predicted-snail|predicted-tarantula
|"cat"			|80% 		  |20% 			|0 				 |0 			 |0
|"dog" 			|0 			  |100%			|0 				 |0 			 |0
|"lizard"		|0 			  |100% 		|0	 			 |0 			 |0
|"snail"		|0  		  |0 			|0 				 |100%	 		 |0
|"tarantula"	|0 			  |0 			|0 				 |100%	 		 |0
|===

@slidebreak{Investigate}

@lesson-instruction{
- What are some ways this decision tree could be improved?
- Turn to @printable-exercise{building-decision-trees.adoc}
}

@slidebreak{Investigate}

You just observed that a decision tree

- can accurately categorize items that were represented in the training dataset
- can falter when offered inputs that were **not** represented

We can add more training data to improve the accuracy, but encountering new objects or situations is common in real-world settings. But these examples emphasize the importance of having a good representation (set of questions) of the objects or situations that we want to make predictions about!

@slidebreak{Investigate}

When we were playing 20 Questions, we could draw on everything we know about knives, spoons, sporks, plates, bowls or mugs to generate questions. We could always add new questions if we hadn't yet identified an object.

@slidebreak{Investigate}

@lesson-point{
Computers build decision trees from datasets. The columns in a dataset are **fixed before the tree gets generated**. Since the questions can't change on the fly, it is important that we start from robust training data that

- has columns for enough attributes to distinguish between outcomes, and
- has enough rows to capture different combinations of those attributes.  
}

@QandA{
Let's think about this issue of having enough training data.
@Q{What might determine whether we can create a training dataset with at least one row per combination of attributes?}
@A{There are two key factors:
  * How many columns are there?
  * How many values are possible in each column?
}

@Q{How many variables do you think a recommendation system like YouTube uses?}
@A{YouTube considers roughly one billion variables!}
}

=== Synthesize

@slidebreak{Synthesize}

@QandA{
@Q{Will a decision tree always have the same number of leaf nodes as there were rows in the training dataset? Why or why not?}
@A{No. Generally multiple rows of a training dataset will have the same prediction. The training dataset we saw in this lesson section contained multiple knives, for example.}

@Q{Explain how the decision tree and training dataset correspond to each other.}
@A{The column headers from the table are the questions that will get asked in the decision nodes of the decision tree.}
@A{The data in each column are the answers to those questions which become the arrow labels of the decision tree ("yes" and "no", for this dataset).}
@A{The output categories from the table are the leaf nodes in the decision tree.}
}


== Decision Stumps: Optimizing Predictions @duration{25 minutes}

=== Overview

Students build a decision tree that predicts whether someone will purchase a video game.

=== Launch
@slidebreak{Launch}

Have you ever done some online shopping—say, for a new pair of sneakers—only to discover that, for the next several days, you encounter _advertisements for sneakers_ lurking in every corner of the internet that you visit?!

@slidebreak{Launch}

Websites can store small data files called "cookies" on your device that can be used to remember details like where you were the last time you visited the site. One particular kind of cookie, the tracking cookie, helps companies compile large datasets about visitors. They then use machine learning to decide which ads to display.

*How do decision trees built from large datasets decide — at every level and every node — which attributes are the most informative ones to ask questions about,* so that they can make relatively accurate predictions, recommendations, and diagnoses?!

It turns out, there's an algorithm for that, and it's relatively straightforward.

=== Investigate
@slidebreak{Investigate}

We're going to create a decision tree that predicts whether customers at a particular online store will purchase a video game. We will use a training dataset of 14 different shoppers that indicates whether or not each one purchased a video game. 

@QandA{
@Q{With your partner, look over the @handout{decision-tree-data.adoc, Training Dataset}. What do you Notice? What do you wonder?}
@A{Possible responses:}
@A{Individuals in their twenties always buy the video game.} 
@A{There are only three new customers; two out of three times, new customers buy the video game.}
@Q{Can you foresee any problems with making predictions based on this dataset? If so, what are they?}
@A{Responses will vary.}
@A{We only have data on 14 visitors.}
@A{All of the visitors are between 14 and 38 years old.}
@A{We don't know a lot about their gaming habits.}
}

Our model will predict the value in the "buys game" column using the other columns as the questions.

@slidebreak{Investigate}

@lesson-instruction{
Before we process any dataset, we should consider whether the data are at a good level of specificity for the problem. For video game purchases, do we expect the difference between 17 and 18 year olds to matter, or is a general "teenager" category sufficient? If our data are too fine-grained, our models might not detect patterns that would otherwise be meaningful. 

For now, let's agree to create three groups: teens, twenties, and thirties. We can compute a new column in our dataset with these categories (and will see that on the next worksheet, @printable-exercise{part-1.adoc}).
}

@slidebreak{Investigate}

When we drew a decision tree for 20 Questions, we discussed starting with questions that might distinguish among the possible outcomes. Which variable in our training set might do this? The "age" column has three possible values, whereas "shopping history" and "interest in game" each have only two ("yes" or "no"). This suggests that "age" might be a good variable to put at the root of our tree.


@slidebreak{InvestigateR}


What does that initial node look like? For starters, we draw a decision node and label it with "age" (the column name we are exploring). We then add one branch for each of the possible values in the column (here, "teens", "twenties", and "thirties"). At the end of the arrows for each branch, we will build additional nodes for the subset of the dataset with the corresponding "age" value. Specifically:

@center{@image{images/age-stump-with-names.png, 350}}

@slidebreak{InvestigateR}

Before we create additional decision nodes, we want to explore the accuracy of prediction that we would get up to this point in the tree. To do this, we adapt our previous diagram to summarize the prediction and accuracy at each branch. We call this new diagram a @vocab{decision stump}. In the following picture, we have filled in the values from the "buys game" column for the dataset that remains within each "age" category.

@center{@image{images/stump.png, 350}}

@QandA{
@Q{What else do you Notice and Wonder about the decision stump?}
@A{Everyone in their twenties bought the game.}
@A{Three out of 5 people in their thirties bought the game.}
@A{On the other decision trees we've seen the arrows were labeled "yes" and "no", but here they're labeled "teens", "twenties", "thirties".}
@A{Our decision stumps include nodes labeled like N N N Y Y.}
}

@slidebreak{Investigate}

Now, we need to determine two things:

- What decision would we currently predict at each node, based on the training data? 
  * We use whichever outcome appears most frequently in the remaining dataset (summarized by our N N N Y Y labels).
- For what percentage of the rows at each branch is that prediction accurate?

@lesson-instruction{
Let's complete the first section of @printable-exercise{part-1.adoc} together to work out these details.
}

@slidebreak{InvestigateR}

This stump has three branches because there are three values in the "age" column:

- The left-most leaf node ("teens") represents the five teens in our training dataset: Jan, Jose, Jillian, Ariella, and Danial.
  * Jan, Jose, and Jillian did *not* purchase the game, so they are represented by the letter N (for "no").
  * Ariella and Danial *did* purchase the game, so they are represented by the letter Y (for "yes").
  * We illustrate the teens' decisions with the following shorthand: N N N Y Y
- The other leaf nodes similarly summarize the purchasing habits of the individuals in their age groups.

@ifslide{@image{images/stump.png, 350}}

@slidebreak{InvestigateR}

We need to replace each outcome label (like N N N Y Y) with a predicted outcome.

@QandA{
@Q{What prediction should we make for teens? Why?}
@A{They won't buy the game. We predict this because the majority of teens in the training data didn't buy the game.}
@Q{What predictions should we make for the other age groups? Why?}
@A{People in their twenties and thirties will buy the game. Everyone in their twenties bought the game, and a majority of those in their thirties bought the game.}

@ifslide{@image{images/stump.png, 350}}

}

@slidebreak{Investigate}

@lesson-instruction{
Now that we have our predictions, we need to calculate how accurate they are for each of our age groups. We'll start by placing checkmarks beneath each outcome (Y or N) that we would have correctly predicted.
}

@slidebreak{Investigate}

We predicted that individuals in their teens would *not* purchase the game, so:

- We place checkmarks by the Ns that represent Jan, Jose, and Jillian. Our prediction was correct for them.
- We leave the Ys without checkmarks; our prediction was wrong for Danial and Ariella.

Our prediction was correct for 3 out of 5 individuals or 60% of the time.

@lesson-instruction{
- Add checkmarks to the decision tree on @printable-exercise{part-1.adoc} to indicate when our prediction was successful for customers in their twenties and thirties.
- Calculate how effectively we predicted outcomes for each age group and the dataset as a whole (Question 4).
- Finish the remaining questions in the first section.
}

@slidebreak{InvestigateR}

@center{@image{images/age-stump-checks.png, 350}}

Our prediction was pretty effective! It was correct 10 out of 14 times! And for people in their twenties it was 100% accurate. Can we make the predictions more accurate for the other two groups? Yes! We still have two columns of data to consider:

- Is the individual a previous customer, or a new customer?
- Has the individual expressed interest in a particular video game?

@slidebreak{Investigate}

As we move down the tree, our job is to figure out _which column to use next_.

@lesson-point{
Decision stumps help us decide how columns would impact our predictions.
}

@slidebreak{Investigate}

@lesson-instruction{
- Complete the last section of @printable-exercise{part-1.adoc}
- Then complete @printable-exercise{part-2.adoc}.
** You will create and compare different decision stumps for these columns of data.
** The stumps will help you determine which question will produce the biggest improvement in accuracy.
}

@slidebreak{Investigate}

@QandA{
@Q{Which attributes do you plan to utilize for the second level of the decision tree?}
@A{Interest in Games for Teens}
@A{Shopping History for People in their Thirties}
@A{Since our prediction for people in their Twenties was 100% accurate, we insert a leaf node with a decision to buy the game!}
}

@slidebreak{Investigate}

@lesson-instruction{
Complete the first section @printable-exercise{build-and-test.adoc}.
}

@slidebreak{Investigate}

@QandA{
@Q{What predictions did you make?}
@A{Interested teens will buy the game}
@A{Everyone in their twenties will buy the game.} 
@A{Previous customers in their thirties will buy the game.}
}

@slidebreak{Investigate}

@lesson-instruction{
Complete the second and third sections of @printable-exercise{build-and-test.adoc} to try making predictions about customers who were not in the training dataset.
}

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{What are some reasons that a decision tree might produce an inaccurate prediction or recommendation?}
@A{The prediction might represent closer to 50% of the training population rather than 100% of the population.}
@A{The training dataset might not completely represent the broader population, either in not having enough variables (columns) or enough samples (rows).}
@A{The training dataset could be inconsistent, in that the labeled outcomes for two rows are different while the rest of the columns have the same values.}

@Q{After testing our tree, we discovered that it was not as accurate as we had expected or hoped. Can you think of concrete, real-world examples of how a training dataset might under represent a population?}
@A{Responses will vary.}
@A{Medical systems being trained on only adults, but not children.}
@A{Tutoring systems trained on only native speakers of a language.}
@A{Music recommendation systems being trained on a narrow set of genres.}

@Q{We collapsed specific ages into categories (teenager, etc) to align the specificity of our data with the specificity of recommendations that we wanted from the decision tree. What if we had not done that, and instead created a branch for each individual age? How would individual branches have affected the decision tree and its recommendations?}
@A{The tree would have had many more branches and decision nodes.}
@A{We would likely have needed more training data with more samples at each age to get to acceptable accuracy.}

@Q{You have learned that @vocab{supervised learning} includes three steps: (1) demonstration of the learning process, (2) function abstraction, and (3) using the function. Describe what each step includes for the @vocab{supervised learning} of a @vocab{decision tree}.}
@A{Demonstration: For decision trees, the demonstration is the labeling of the data so that the computer learns the desired outcome (or "correct answer") for each data point. During the lesson, we knew whether the individuals in our training set would buy the video game.}
@A{Function abstraction: Creating the decision tree yields a model of how variables affect outcomes.}
@A{Use: Follow the decision tree to find the predicted outcome for a new input (set of values for the question variables).}

@Q{What are the key differences between building a decision tree and playing a game of 20 Questions?}
@A{In 20 Questions, we generate new questions as we play, whereas a decision tree is built from a fixed dataset.}
@A{In 20 Questions, the answers are all yes/no, whereas there can be multiple answers to a question in a decision tree.}
@A{In 20 Questions, we generate new questions each time we play the game. A decision tree is a model that will be used to make multiple predictions over the same input variables.}
}

@scrub{
In AI, efficiency and accuracy are often in conflict:

- AI is *efficient* when the computer performs a task with minimal time, memory, energy or data.
- AI is *accurate* when the computer performs its task with correct, relevant, and consistent results.

Striking the perfect balance is an ongoing challenge for computer scientists, and it is a challenge with far-reaching implications.

@QandA{
@Q{Why is it advantageous for AI to be efficient?}
@A{Responses will vary.}
@A{reduced delays}
@A{an improved user experience}
@A{greater scalability}
@A{decreased environmental impact}

@Q{Can you think of any reasons *not* to maximize an AI's efficiency?}
@A{Responses will vary.}
@A{an increase in efficiency leads to a decrease in accuracy.}
}
}


Creating a decision tree is a form of @vocab{supervised learning}, because the training data already contains the desired outcomes (as one column), and the algorithm just learns a function that maps from input to outcomes.
