= Variability

@description{Variability }

@ifproglang{pyret}{
@lesson-prereqs{contracts-tables-visualizations, ds-intro, dot-plots}
}

@ifproglang{codap}{
@lesson-prereqs{codap-dot-plots-bar-charts}
}

@keywords{variability}

@add-to-lang{histogram}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives


| Student-facing Lesson Goals
|


| Materials
|[.materials-links]

@material-links

| Preparation
|


|===



== Variability Two Ways

@objective{variability-define}

=== Overview

Students define variability two ways, and then apply that understanding to describe the variability of categorical and quantitative data.

=== Launch

So far, we have a few tools that we can use to describe a dataset. We can characterize the distribution of the data (outliers, clusters, peaks, and gaps). We can also characterize a dataset by thinking about its typicality, or what is expected. A third way to describe a dataset is by considering its @vocab{variability}. There are lots of different ways to think about variability!

In fact, if you spent any time learning about different question types (like during our lesson on @lesson-link{data-cycle}, you know that a @vocab{statistical question} is one that anticipates variability.

@QandA{

@Q{Which question anticipates variability: _How many minutes are in an hour?_ or _How many minutes does it take to drive to school?_ Explain your response.}

@A{Question A anticipates variability, but Question B does not. The answer Question A will always be 60. The answer to the Question B, however, will vary based on who you ask, road conditions, traffic, etc.}
}

@strategy{There are Many Ways to Assess Variability!}{

Research indicates that students often have an oversimplified and underdeveloped view of variability (@citation{cooper-2018}, @citation{cooper-shore-2008}).

In this lesson, we intentionally begin our conversation by developing intuitive ideas about variability, for instance:

- Variability requires us to consider the data as an entity, rather than as individual points.
- We can try to understand why things vary and try to identify reasons for variability.
- Some things vary a little, and some vary a lot.
- We see variability in both quantitative and categorical datasets.

This last recommendation is an important one: research indicates that "unlikeability" of a categorical dataset is a more natural concept than "variation about the mean" @citation{kade-perry-2007}, therefore can act as a natural starting point.

That said, we urge you to explicitly emphasize that unlikeability is just one of many ways to think about variability. Fixating on this definition of variability can result in students developing the misconception that levelness of bars indicates little variability (@citation{cooper-2008}).
}

In a categorical dataset, we can judge variability based on how different or alike the data points are. In other words, high variability comes from high "unlikeability" of data points.

Let's think about the variability of some categorical datasets.

@QandA{

The following questions are printed on @printable-exercise{variability-two-ways.adoc}. Complete the questions on your page first. Be prepared to share your responses with the class.

@Q{In Sana's grocery bag, she has 12 apples and 1 banana. In Juliette's grocery bag, she has 4 peaches, 4 kiwis, 4 oranges, and 1 limes. Which dataset - Sana's groceries or Juliette's groceries - has greater variability?}

@A{Sample response: Juliette's grocery bag has greater variability, as the items in her bag are more different from one another than the items in Sana's bag. If students are inclined to consider the amount of each item, remind them that this is a categorical dataset.}

@Q{You ask a group of sixth grade students to respond to two different statements with either "true" or "false." Statement A is _I am in sixth grade_, and statement B is _I am wearing blue today._ Which statement do you predict will produce greater variability?}

@A{Sample response: Given that the students you are sampling are in sixth grade, there will not be any variability in their responses to statement A. Everyone will choose "true". For statement B, however, it is likely that some students will be wearing blue and some will not; we can conclude that the resulting responses will have some "unlikeability".}
}

=== Investigate


@QandA{

Someone looks at a roster of students in your class, and says, "In general, the students in this class all have the same number of letters in their first names." Do you agree or disagree? Explain your reasoning.

@Q{Do you agree or disagree? Explain your reasoning on @printable-exercise{variability-two-ways.adoc}. Be prepared to share your response with the class.}

@A{Sample response: I disagree. The data spreads out from 3 letters to 14 letters. If all students had the generally same number of letters in their names, most or all of name lengths would be equivalent.}
}

@lesson-instruction{
Complete @printable-exercise{variability-two-ways.adoc}.
}

@teacher{

Another misconception is that students often believe that variability can be judged based solely on the *range* of a dataset. Although we will focus on range for the remainder of this lesson, it is important to acknowledge that there are *many* other ways to quantify variability. The dialogue about variability that begins in this lesson will continue during @lesson-link{histograms-variability}, @lesson-link{box-plots}, and  @lesson-link{standard-deviation}.
}

=== Synthesize

@QandA{

@Q{Make up two categorical datasets with five items, each. One dataset must have high variability, and the other must have low variability. Exchange datasets with a partner and discuss your strategy for categorizing the datasets.}

@Q{Make up two quantitative datasets with ten quantities, each. One dataset must have high variability, and the other must have low variability. Exchange datasets with a partner and discuss your strategy for categorizing the datasets.}

@Q{How did your strategies for assessing variability change, if at all, when you looked at a categorical dataset versus a quantitative dataset?}

@Q{If two datasets have the same range, how can we decide which one has greater variability?}

@A{Although students will likely be able to answer this question concretely (e.g. use interquartile range, mean absolute deviation, or standard deviation), it is a good opportunity to see if they are developing intuition about variability as deviation from the center.}
}



== Dot Plots and Variability

@objective{variability-describe}


=== Overview



=== Launch

To create a dot plot by in @proglang, we @ifproglang{pyret}{use this contract:


@show{(contract 'dot-plot '((table-name Table) (labels String) (column-name String)) "Image")}
}

Using the expanded animals dataset, create three dot plots for three different mystery animals by typing in the code provided on WORKSHEET.



Rabbits generally weigh less than cats. Dogs’ weights vary more than cats’ weights. Label the three histograms below to correspond with cats, dogs, and rabbits.


=== Investigate

FINISH THE WORKSHEET


wake up times on school days / wake up times on weekends
Which dot plot represents ages of all sixth graders at a K-12 school? Which dot plots represents ages of all students at a K-12 school? Is the data more alike in sixth grade or more alike in the entire school?
Weights of cats in a shelter / weights of dogs in a shelter
# of TVs per household / # of TVs per room
Distances of students from school A: 10 mi, 10 mi, 10 mi, 10.7 mi, 10.5 mi, 10.3 mi, 10.8 mi // Distances of students from school B: 5 mi, 3 mi, 1 mi, 8 mi, 4 mi, 9 mi, 3 mi
# of minutes that it takes to get ready for school / # of minutes that it takes to brush your teeth
Students hours on the phone per week or students hours spent on homework each week



=== Synthesize
