= Variability

@description{Variability }

@ifproglang{pyret}{
@lesson-prereqs{contracts-tables-visualizations, ds-intro, dot-plots}
}

@ifproglang{codap}{
@lesson-prereqs{codap-dot-plots-bar-charts}
}

@keywords{variability}

@add-to-lang{histogram}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives


| Student-facing Lesson Goals
|


| Materials
|[.materials-links]

@material-links

| Preparation
|


|===



== Variability Two Ways

@objective{variability-define}
@objective{variability-describe}

=== Overview

Students define variability two ways, and then apply that understanding to describe the variability of categorical and quantitative data.

=== Launch

So far, we have a few tools that we can use to describe a dataset. We can characterize the distribution of the data (outliers, clusters, peaks, and gaps). We can also characterize a dataset by thinking about its typicality, or what is expected. A third way to describe a dataset is by considering its @vocab{variability}. There are lots of different ways to think about variability! In this lesson, we will consider two different ways.

@strategy{There are Many Ways to Assess Variability!}{

Research indicates that students often have an oversimplified and underdeveloped view of variability (Cooper, 2018; Cooper & Shore, 2008; Garfield & Ben-Zvi, 2005).

In this lesson, we intentionally begin our conversation by developing intuitive ideas about variability, for instance:

- Some things vary a little, and some vary a lot.
- Variability requires us to consider the data as an entity, rather than as individual points.
- We can try to understand why things vary and try to identify reasons for variability.
- We see variability in both quantitative and categorical datasets.

This last recommendation is an important one: research indicates that "unlikeability" of a categorical dataset is a more natural concept than "variation about the mean" (Kade & Perry, 2007), therefore can act as a natural starting point.

That said, we urge you to explicitly emphasize that unlikeability is just one of many ways to think about variability. Fixating on this definition of variability can cause students to trouble when they later interpret histograms and conclude that levelness of bars indicates little variability (delMaas et al, 2007).
}

In a categorical dataset, we can judge variability based on how different or alike the data points are. In other words, high variability comes from high "unlikeability" of data points.

Let's think about the variability of some categorical datasets.

@QandA{

The following questions are printed on @printable-exercise{variability-two-ways.adoc}. Complete the questions on your page first. Be prepared to share your responses with the class.

@Q{In Sana's grocery bag, she has 12 apples and 1 banana. In Juliette's grocery bag, she has 4 peaches, 4 kiwis, 4 oranges, and 1 limes. Which dataset - Sana's groceries or Juliette's groceries - has greater variability?}

@A{Sample response: Juliette's grocery bag has greater variability, as the items in her bag are more different from one another than the items in Sana's bag. If students are inclined to consider the amount of each item, remind them that this is a categorical dataset.}

@Q{You ask a group of sixth grade students to respond to two different statements with either "true" or "false." Statement A is _I am in sixth grade_, and statement B is _I am wearing blue today._ Which statement do you predict will produce greater variability?}

@A{Sample response: Given that the students you are sampling are in sixth grade, there will not be any variability in their responses to statement A. Everyone will choose "true". For statement B, however, it is likely that some students will be wearing blue and some will not; we can conclude that the resulting responses will have some "unlikeability".}
}

=== Investigate


@QandA{

Someone looks at a roster of students in your class, and says, "In general, the students in our class all have the same number of letters in their first names." Do you agree or disagree? Explain your reasoning.

@Q{Do you agree or disagree? Explain your reasoning on @printable-exercise{variability-two-ways.adoc}. Be prepared to share your response with the class.}
@A{Sample response: I disagree. We can see the data spreads out from 3 letters to 14 letters. If all students had the same number of letters in their names, most or all of name lengths would be equivalent.}
}

@lesson-instruction{
Complete @printable-exercise{variability-two-ways.adoc}.
}

@teacher{

Another misconception is that students often believe that variability can be judged based solely on the *range* of a dataset. Although we will focus on range for the remainder of this lesson, it is important to acknowledge that there are *many* other ways to quantify variability. The dialogue about variability that begins in this lesson will continue during @lesson-link{histograms-variability}, @lesson-link{box-plots}, and  @lesson-link{standard-deviation}.
}

=== Synthesize





== Dot Plots and Variability



=== Overview

=== Launch



=== Investigate



=== Synthesize
