= Variability

@description{Students define variability multiple ways, and then describe different levels of variability on dot plots.}

@ifproglang{pyret}{
@lesson-prereqs{contracts-tables-visualizations, ds-intro, dot-plots}
}

@ifproglang{codap}{
@lesson-prereqs{codap-dot-plots-bar-charts}
}

@keywords{variability}

@add-to-lang{histogram}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives


| Student-facing Lesson Goals
|

Let's think about variability of categorical and quantitative data.

| Materials
|[.materials-links]

@material-links

| Preparation
|


|===



== Variability Two Ways

@objective{variability-define}

=== Overview

Students define variability two ways, and then apply that understanding to describe the variability of categorical and quantitative data.

=== Launch

When we learned about @lesson-link{dot-plots}, we acquired some useful vocabulary that we can use to describe a dataset. We can identify outliers, clusters, peaks, and gaps to characterize a dataset's distribution. We can also estimate what's typical--or what is expected in the data. A third way to describe a dataset is discussing its @vocab{variability}. *There are lots of different ways to think about variability!*

If you have already learned about different _question types_ (perhaps during our lesson on @lesson-link{data-cycle}), you should be familiar with the concept of variability: a @vocab{statistical question} is a question that anticipates @vocab{variability}.

@QandA{

@Q{Which question anticipates variability: _How many minutes are in an hour?_ or _How many minutes does it take to drive to school?_ Explain your response.}

@A{Question A anticipates variability, but Question B does not. The answer Question A will always be 60. The answer to the Question B, however, will vary based on who you ask, road conditions, traffic, etc.}
}

@strategy{There are Many Ways to Think about Variability!}{

Research indicates that students often have an oversimplified and underdeveloped view of variability (@citation{cooper-2018}; @citation{cooper-shore-2008}).

In this lesson, we intentionally begin our conversation by developing intuitive ideas about variability, for instance:

- Variability requires us to consider the data as an entity, rather than as individual points.
- We can try to understand why things vary and try to identify reasons for variability.
- Some things vary a little, and some vary a lot.
- We see variability in both quantitative and categorical datasets.

This last recommendation is an important one: research indicates that "unlikeability" of a categorical dataset is a more natural concept than "variation about the mean" (@citation{kade-perry-2007}), therefore can act as a natural starting point.

That said, we urge you to explicitly emphasize that unlikeability is just one of many ways to think about variability. Fixating on this definition of variability can result in students developing the common misconception that levelness of histogram bars indicates low variability (@citation{cooper-shore-2008}).
}


=== Investigate

In a categorical dataset, we can judge variability based on how different or alike the data points are. In other words, high variability comes from high "unlikeability" of data points.

Let's think about the variability of some categorical datasets.

@QandA{

The following questions are printed on @printable-exercise{variability-two-ways.adoc}. Complete the questions on your page first. Be prepared to share your responses with the class.

@Q{In Sana's grocery bag, she has 12 apples and 1 banana. In Juliette's grocery bag, she has 4 peaches, 4 kiwis, 4 oranges, and 1 limes. Which dataset - Sana's groceries or Juliette's groceries - has greater variability?}

@A{Sample response: Juliette's grocery bag has greater variability, as the items in her bag are more different from one another than the items in Sana's bag. If students are inclined to consider the amount of each item, remind them that this is a categorical dataset.}

@Q{You ask a group of sixth grade students to respond to two different statements with either "true" or "false." Statement A is _I am in sixth grade_, and statement B is _I am wearing blue today._ Which statement do you predict will produce greater variability?}

@A{Sample response: Given that the students you are sampling are in sixth grade, there will not be any variability in their responses to statement A. Everyone will choose "true". For statement B, however, it is likely that some students will be wearing blue and some will not; we can conclude that the resulting responses will have some "unlikeability".}
}

@QandA{

Someone looks at a roster of students in your class, and says, "In general, the students in this class all have the same number of letters in their first names." Do you agree or disagree? Explain your reasoning.

@Q{Do you agree or disagree? Explain your reasoning on @printable-exercise{variability-two-ways.adoc}. Be prepared to share your response with the class.}

@A{Sample response: I disagree. The data spreads out from 3 letters to 14 letters. If all students had the generally same number of letters in their names, most or all of name lengths would be equivalent.}
}

@lesson-instruction{
Complete @printable-exercise{variability-two-ways.adoc}.
}

@teacher{

Students often believe that variability can be judged based solely on the *range* of a dataset (@citation{cooper-shore-2008}). Although we will focus on range for the remainder of this lesson, acknowledge to students that there are *many* other ways to quantify variability. The dialogue about variability that begins in this lesson will continue (and gain nuance) during @lesson-link{histograms-visualize}, @lesson-link{box-plots}, and  @lesson-link{standard-deviation}.
}

=== Synthesize

@QandA{

@Q{Make up two categorical datasets with five items, each. One dataset must have high variability, and the other must have low variability. Exchange datasets with a partner and discuss your strategy for categorizing the datasets.}

@Q{Make up two quantitative datasets with ten quantities, each. One dataset must have high variability, and the other must have low variability. Exchange datasets with a partner and discuss your strategy for categorizing the datasets.}

@Q{How did your strategies for assessing variability change, if at all, when you looked at a categorical dataset versus a quantitative dataset?}

@Q{If two datasets have the same range, how can we decide which one has greater variability?}

@A{Although students will likely be able to answer this question concretely (e.g. use interquartile range, mean absolute deviation, or standard deviation), it is a good opportunity to see if they are developing intuition about variability as deviation from the center.}
}



== Dot Plots and Variability

@objective{variability-describe}


=== Overview



=== Launch

Let's investigate how variability shows up on dot plots.

@lesson-instruction{
- With a partner, complete @printable-exercise{variability-dot-plots-2.adoc}.
- For each row of the table, fill in the blank with either "A" (for dot plot A) or "B" (for dot plot B), depending on which data visualization makes the most sense for the given scenario. Explain your choice.
}




=== Investigate

Let's return to our beloved animal shelter...

To create a dot plot in @proglang, we @ifproglang{pyret}{use this contract:

@show{(contract 'dot-plot '((table-name Table) (labels String) (column-name String)) "Image")}
}

Let's build some dot plots
Using the expanded animals dataset, create three dot plots for three different mystery animals by typing in the code provided on WORKSHEET.



Rabbits generally weigh less than cats. Dogs’ weights vary more than cats’ weights. Label the three histograms below to correspond with cats, dogs, and rabbits.






=== Synthesize
