= Identifying Form, Direction and Strength

++++
<style>
#content table table {background: transparent; margin: 0px;}
#content td {padding: 0px !important;}
#content table table { margin-top: 1em; }
#content table table td p {white-space: pre-wrap;}
img { width: 250px !important; }
</style>
++++

What do your eyes tell you about the Form, Direction, & Strength of these displays?

*Note:* If the form is nonlinear, we shouldn’t report direction - a curve may rise and then fall.

[.FillVerticalSpace, cols="^.^1a,^.^15a,^.^1a,^.^15a", frame="none"]
|===
|*A*
| @centered-image{../images/A.gif}
[cols="2a,2a,2a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! @ifsoln-choice{Linear} 	! Nonlinear 	! None
! *Direction*: 	! Positive 	! @ifsoln-choice{Negative} 		! N/A
! *Strength*: 	! @ifsoln-choice{Strong} 	! Weak 			! N/A
!===

|*B*
| @centered-image{../images/B.gif}
[cols="2a,2a,2a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! Nonlinear 	! @ifsoln-choice{None}
! *Direction*: 	! Positive 	! Negative 		! @ifsoln-choice{N/A}
! *Strength*: 	! Strong 	! Weak 			! @ifsoln-choice{N/A}
!===

|*C*
| @centered-image{../images/C.gif}
[cols="2a,2a,2a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! @ifsoln-choice{Linear} 	! Nonlinear 	! None
! *Direction*: 	! @ifsoln-choice{Positive} 	! Negative 		! N/A
! *Strength*: 	! @ifsoln-choice{Strong} 	! Weak 			! N/A
!===

|*D*
| @centered-image{../images/D.gif}
[cols="2a,2a,2a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! @ifsoln-choice{Linear} 	! Nonlinear 	! None
! *Direction*: 	! @ifsoln-choice{Positive} 	! Negative 		! N/A
! *Strength*: 	! Strong 	! @ifsoln-choice{Weak} 			! N/A
!===

|*E*
| @centered-image{../images/E.gif}
[cols="2a,2a,2a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! @ifsoln-choice{Nonlinear} 	! None
! *Direction*: 	! Positive 	! Negative 		! @ifsoln-choice{N/A}
! *Strength*: 	! @ifsoln-choice{Strong} 	! Weak 			! N/A
!===

|*F*
| @centered-image{../images/F.gif}
[cols="2a,2a,2a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! @ifsoln-choice{Linear} 	! Nonlinear 	! None
! *Direction*: 	! Positive 	! @ifsoln-choice{Negative} 		! N/A
! *Strength*: 	! Strong 	! @ifsoln-choice{Weak} 			! N/A
!===

|===
