= Reflection on Form, Direction and Strength

@n What has to be true about the _shape_ of a relationship in order to start talking about the correlation's _direction_ being positive or negative?

@fitb{}{@ifsoln{It must be linear}}

@fitb{}{}

@fitb{}{}


@n What is the difference between a _weak_ relationship and a _negative_ relationship? 


@fitb{}{@ifsoln{If a relationship is *negative*, it means that one variable decreases as the other increases. }}

@fitb{}{@ifsoln{A *weak* relationship is one in which knowing the x-value does not allow us to predict the y-value very well,  }}

@fitb{}{@ifsoln{and the points are not clustered tightly around a line.}}


@n What is the difference between a _strong_ relationship and a _positive_ relationship?

@fitb{}{@ifsoln{If a relationship is *positive*, it means that the variables increase together.}}

@fitb{}{@ifsoln{A *strong* relationship is one in which (1) knowing the x-value allows us to predict the y-value very well, and (2) the points are clustered tightly}}

@fitb{}{@ifsoln{around a line. }}



@n If we find a strong relationship in a sample from a larger population, will that relationship _always hold_ for the whole population? Why or why not?

@fitb{}{@ifsoln{No. Maybe the sample was biased, or maybe it was random but we *just happened* to choose points for which there is a correlation.}}

@fitb{}{@ifsoln{}}

@fitb{}{}


@n If two correlations are both positive, is the stronger one _more positive_ (steeper slope) than the other?

@fitb{}{@ifsoln{No. Direction and Strength are unrelated}}

@fitb{}{}

@fitb{}{}



@n A news report claims that after surveying _10 million people_, a positive correlation was found between how much chocolate a person eats and how happy they are. Does this mean eating chocolate almost certainly makes you happier? Why or why not?

@fitb{}{@ifsoln{No. A correlation drawn from a giant sample can still be a weak correlation! Sample size is not connected to strength.}}

@fitb{}{}

@fitb{}{}

