= How could we Measure Whether a Model is a Good Fit?

++++
<style>
p.tableblock { margin: 0; }
.lizard td { padding: 0 5px !important; }
table .autonum::after { content: ')' !important; }
</style>
++++

[cols="1a,1a", frame="none", grid="none", stripes="none"]
|===
|
Below is a sample of lizards from the Animals Dataset.

[.lizard, cols="1a,1a,1a", stripes="none", options="header"]
!===
!  name 		! pounds ! weeks
!  Amy 			!  5 	! 7
!  Aries 		!  4  	! 7
!  Boss 		!  6  	! 5
!  Brittany 	!  3  	! 8
!  Buck			!  7  	! 4
!  Butterscotch	!  1  	! 6
!  Chico 		!  8  	! 4
!  Coconut		!  6  	! 6
!  Dodger 		!  5  	! 8
!  Dylan 		!  7  	! 3
!===
| 

@centered-image{../images/scatter-plot-lizard-sample-weeks-v-pounds.png}
|===

@n Use a straightedge to draw the @vocab{line of best fit} that best summarizes the relationship you see in the data on the scatter plot above.

@n Some other students drew the two lines below. Do you think `f(x)` or `g(x)` is a better model for this data? Why?

[cols="1a,1a", frame="none", grid="none", stripes="none"]
|===
| @centered-image{../images/which-model.png}
|


@fitb{}{@ifsoln{f - reasoning will vary.}}

@fitb{}{@ifsoln{It splits the data points more evenly}.}

@fitb{}{@ifsoln{More points are closer to the line.}}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

|=== 

@n What could we measure, to calculate _how much better of a model_ it is? @fitb{}{}

@fitb{}{@ifsoln{Answers will vary.}}

@fitb{}{@ifsoln{The distance between each of the points and the line.}}


@n _Neither of these models is the best possible model!_ What would have to be true of a third model, for us to know that it was a better fit than these two? @fitb{}{}

@fitb{}{@ifsoln{Answers will vary.}}

@fitb{}{@ifsoln{If the average distance between the points and the line is smaller.}}
