= How could we Measure Whether a Model is a Good Fit? (Lizards)

++++
<style>
p.tableblock { margin: 0; }
.lizard td { padding: 0 5px !important; }
</style>
++++

== Summarize the Relationship You See

[cols=".^1a,^1a", frame="none", grid="none", stripes="none"]
|===
|
Below is a sample of lizards from the Animals Dataset.

[.lizard, cols="1a,^1a,^1a", stripes="none", options="header"]
!===
!  name 		! pounds ! weeks
!  Amy 			!  5 	! 7
!  Aries 		!  4  	! 7
!  Boss 		!  6  	! 5
!  Brittany 	!  3  	! 8
!  Buck			!  7  	! 4
!  Butterscotch	!  1  	! 6
!  Chico 		!  8  	! 4
!  Coconut		!  6  	! 6
!  Dodger 		!  5  	! 8
!  Dylan 		!  7  	! 3
!===

| @image{../images/sp2.png, 350}
|===

@n Use a straightedge to draw the @vocab{line of best fit} that best summarizes the relationship you see in the data on the scatter plot.

@n Describe how you decided where to draw the line. @fitb{}{}

@fitb{}{}

== Comparing Models

@n Cy and Jo drew the two lines below. Do you think `cy(x)` or `jo(x)` is a better model for this data? Why?

[cols="^1a,1a", frame="none", grid="none", stripes="none"]
|===
| @image{../images/which-model2-fun.png}
|


@fitb{}{@ifsoln{Answers and reasoning will vary.}}

@fitb{}{@ifsoln{`cy(x)` splits the data points so there are four to the right of the model... }}

@fitb{}{@ifsoln{...and four to the left of the model.}}

@fitb{}{}

@fitb{}{@ifsoln{`jo(x)` is closer to the outlier}}

@fitb{}{}

@fitb{}{}

|=== 

@n What could we measure, to calculate _how much better of a model_ it is? @fitb{}{}

@fitb{}{@ifsoln{Answers will vary.}}

@fitb{}{@ifsoln{The distance between each of the points and the line.}}


@n _Neither of these models is the best possible model!_ What would have to be true of a third model, for us to know that it was a better fit than these two? @fitb{}{}

@fitb{}{@ifsoln{Answers will vary.}}

@fitb{}{@ifsoln{If the average distance between the points and the line is smaller.}}
