= Completing Partial Code from Circles of Evaluation

++++
<style>
  td * {text-align: left;}
</style>
++++

@vspace{2ex}

For each Circle of Evaluation on the left, finish the Code on the right by filling in the blanks.

@do{
  (define expr1 '(+ 16 (* 6 -3)))
  (define expr2 '(- (+ 25 13) (* 2 4)))
  (define expr3 '(* (+ 10 4) 28))
  (define expr4 '(* 13 (/ 7 (+ 2 -4))))
  (define expr5 '(+ (/ (+ 8 1) 3) (- 5 3)))
  (define expr6 '(/ (+ 7 9) (* 2 4)))

  (define code1 (if *solutions-mode?* expr1 `(+ BSLeaveAHoleHere (* 6 BSLeaveAHoleHere))))
  (define code2 (if *solutions-mode?* expr2 `(BSLeaveAHoleHere (+ BSLeaveAHoleHere 13) (BSLeaveAHoleHere BSLeaveAHoleHere 4))))
  (define code3 (if *solutions-mode?* expr3 `(BSLeaveAHoleHere (+ BSLeaveAHoleHere 4) BSLeaveAHoleHere)))
  (define code4 (if *solutions-mode?* expr4 `(BSLeaveAHoleHere 13 (BSLeaveAHoleHere 7 (BSLeaveAHoleHere 2 -4)))))
  (define code5 (if *solutions-mode?* expr5 `(BSLeaveAHoleHere (BSLeaveAHoleHere (BSLeaveAHoleHere 8 1) 3) (BSLeaveAHoleHere 5 3))))
  (define code6 (if *solutions-mode?* expr6 '(/ (+ BSLeaveAHoleHere BSLeaveAHoleHere) (* BSLeaveAHoleHere BSLeaveAHoleHere))))

}

[cols=".^1a,^8a,^12a",options="header",stripes="none"]
|===
|   | Circle of Evaluation        | Code
|*1*| @show{(sexp->coe expr1)}    | @show{(sexp->code code1)}
|*2*| @show{(sexp->coe expr2)}    | @show{(sexp->code code2)}
|*3*| @show{(sexp->coe expr3)}    | @show{(sexp->code code3)}
|*4*| @show{(sexp->coe expr4)}    | @show{(sexp->code code4)}
|*5*| @show{(sexp->coe expr5)}    | @show{(sexp->code code5)}
|*6*| @show{(sexp->coe expr6)}    | @show{(sexp->code code6)}
|=== 