= Arithmetic Expressions to Circles of Evaluation & Code

++++
<style>
  td {height: 175pt;}
</style>
++++

@vspace{2ex}

Translate each of the arithmetic expressions below into Circles of Evaluation, then translate them to Code.

@do{
  (define expr1 '(- (* 3 7) (+ 1 2)))
  (define expr2 '(- 3 (+ 1 2)))
  (define expr3 '(- 3 (+ 1 (* 5 6))))
  (define expr4 '(- (+ 1 (* 5 6)) 3))

  (define coe1 (if *solutions-mode?* (sexp->coe expr1) ""))
  (define coe2 (if *solutions-mode?* (sexp->coe expr2) ""))
  (define coe3 (if *solutions-mode?* (sexp->coe expr3) ""))
  (define coe4 (if *solutions-mode?* (sexp->coe expr4) ""))

  (define code1 (if *solutions-mode?* (sexp->code expr1) ""))
  (define code2 (if *solutions-mode?* (sexp->code expr1) ""))
  (define code3 (if *solutions-mode?* (sexp->code expr1) ""))
  (define code4 (if *solutions-mode?* (sexp->code expr1) ""))
}


[cols=".^1a,^10a,^20a,^15a",options="header",stripes="none"]
|===
|   | Arithmetic				          | Circle of Evaluation	| Code
|*1*| @math{3 \times 7 - (1+ 2)}	| @show{coe1}			      | @show{code1}
|*2*| @show{(sexp->math expr2)}	  | @show{coe2}			      | @show{code2}
|*3*| @math{3 - (1 + 5 \times 6)}	| @show{coe3}			      | @show{code3}
|*4*| @math{1 + 5 \times 6 - 3}	  | @show{coe4}			      | @show{code4}
|===