= Converting Between Angles

@n In the circle below, fill in the blanks to label the number of degrees and radians at each point.

@ifnotsoln{@center{@image{../images/convert-circle.png, 500}}}
@ifsoln{@center{@image{../images/convert-circle-soln.png, 500}}}

@define{leg}{@math{\sqrt{2} \over 2}}

@n *Use Pyret's `sin` and `cos` functions* to complete the table below. +
@hspace{1em} _Note: These function use radians not degrees._

[.FillVerticalSpace, cols="^.^1a, ^.^2a, ^.^2a", options="header"]
|===
| Angle (θ)					| 	`sin(θ)`									| 	`cos(θ)`
|	0° / @math{0  \pi}		| @ifsoln{0}									| @ifsoln{1}
|  45° / @math{0.25\pi}		| `sin(0.25 * PI)` = @ifsoln{~ 0.7071}			| @ifsoln{~ 0.7071}
|  90° / @math{0.50\pi}		| @ifsoln{1}									| @ifsoln{0}
| 135° / @math{0.75\pi}		| @ifsoln{~ 0.7071}								| @ifsoln{~ - 0.7071}
| 180° / @math{1.00\pi}		| @ifsoln{0}									| @ifsoln{-1}
| 225° / @math{1.25\pi}		| @ifsoln{~ - 0.7071}							| @ifsoln{~ - 0.7071}
| 270° / @math{1.50\pi}		| @ifsoln{-1}									| @ifsoln{0}
| 315° / @math{1.75\pi}		| @ifsoln{~ - 0.7071}							| @ifsoln{~ 0.7071}
|===

@n Which function computes the *horizontal* leg of the right triangle (@math{A})? @fitb{}{@ifsoln{`cos`}}

@n Which function computes the *vertical* leg of the right triangle (@math{B})? @fitb{}{@ifsoln{`sin`}}
