= Challenge: Character Movement in Two Dimensions

++++
<style>
/* add a dotted border around specialized directions */
.myCustomClass { 
  border: dotted 1px black; 
  p {margin-left: .25em !important; }
}
</style>
++++

[.myCustomClass]
--
You have all the tools you need to begin this challenge if:

- your game is working
- both the `Danger` and `Target` return to the screen
- your `Player` moves up and down with the arrow keys

--

@vspace{1ex}

@show{
  (contract "update-danger" '("Number") "Number"
	"consumes danger's x-coordinate and produces the next x-coordinate")
}

@vspace{1ex}

The `update-danger` function only moves our `DANGER` left or right. 

@vspace{1ex}

*Suppose we wanted to write a new function, `update-danger-2` that moves the `DANGER` _diagonally_...*

@n What, if anything will have to change about the Domain? @fitb{}{@ifsoln{It will need two Numbers!}}

@n What, if anything, will have to change about the Range? @fitb{}{@ifsoln{It will need a second Number.}}

@vspace{1ex}

[.myCustomClass]
--
_Since an (x, y) coordinate has two Numbers, one idea might be to write the Contract this way:_

@vspace{1ex}

@show{
  (contract "update-danger-2" '("Number Number") "Number Number"
	"consumes danger's x- and y-coordinate, and produces the next x- and next y-coordinate")
}

@vspace{1ex}

_...But that Contract breaks an important rule about functions: Given an input, all functions must produce one output!_

@vspace{1ex}

_We need some way to package two Numbers together into a single value..._

--

@vspace{1ex}

Fortunately, @proglang has another @vocab{data type}, called a *__Posn__*. +
The Posn data type utilizes two Numbers to describe a _single_ "position"!

@vspace{1ex}

We can make a Posn to represent the position (100, 200) with the following code: 

@indented{@show{ (code '(make-posn 100 200)) }}

@n What expression will make a Posn representing the origin? @fitb{}{@showsoln{(code '(make-posn 0 0))}}

@n Write the Contract for the @show{(code 'make-posn)} function on the line below.

@fitb{}{@showsoln{(contract "make-posn" '("Number Number") "Posn")}}

