= Challenge: Character Movement in Two Dimensions

_If your game is working and..._

* _both the `Danger` and `Target` return to the screen_
* _your `Player` moves up and down with the arrow keys_

_... then you have all the tools you need to begin this challenge!_

@vspace{1ex}

[.indentedpara]
@ifproglang{wescheme}{
@show{
  (contract "update-danger" '("Number") "Number"
	"consumes danger's x-coordinate and produces the next one")
}
}
@ifproglang{pyret}{
@show{
  (contract "update-danger" '("Number" "Number") "Number"
	"consumes danger's x and y-coordinates and produces the next x-coordinate")
}
}

The `update-danger` function only moves our `DANGER` left or right... because it doesn't do anything with the y-coordinate!

Suppose we wanted to write a new function, `update-danger-2` that moves the `DANGER` _diagonally_...

@vspace{1ex}

@ifproglang{wescheme}{
@n What will have to change about the Domain? @fitb{}{@ifsoln{It will need two Numbers!}}
}


@ifproglang{pyret}{
@n What is the `update-danger` function doing with the second input in its Domain? @fitb{}{@ifsoln{Nothing! It takes in the y-coordinate, but ignores it.}}
}

@n What, if anything, will have to change about the Range if we want to get our character moving diagonally? @fitb{}{@ifsoln{It will need a second Number.}}

@vspace{1ex}

Since an (x, y) coordinate has two Numbers, one idea might be to write the Contract this way:

[.indentedpara]
@show{
  (contract "update-danger-2" '("Number Number") "Number Number"
	"consumes danger's x- and y-coordinate, and produces the next x- and next y-coordinate")
}

...But that Contract breaks an important rule about functions:

Given an input, all functions must produce one output!

We need some way to package two Numbers together into a single value.

@vspace{1ex}

Fortunately, our programming language has another data type, called a Posn, which utilizes two Numbers to describe a single "position"!

We can make a Posn to represent the position (100, 200) with the following code: @show{ (code '(make-posn 100 200)) }

@vspace{1ex}

@n What expression will make a Posn representing the origin? @fitb{}{@showsoln{(code '(make-posn 0 0))}}

@n Write the Contract for the @show{(code 'make-posn)} function on the line below.

@fitb{}{@showsoln{(contract "make-posn" '("Number Number") "Posn")}}

