[.landscape]
= Contracts

Contracts tell us how to use a function. For example: `num-min {two-colons} (a {two-colons} Number, b {two-colons} Number) -> Number` tells us that the name of the function is  `num-min`, it takes two inputs (both Numbers), and it evaluates to a  `Number`. From the Contract, we know  `num-min(4, 6)` will evaluate to a  `Number`. *Use the blank line under each Contract for notes or sample code for that function!*

[.contracts-table, cols="4,1,10,1,2", options="header", grid="rows"]
|===
|Name||Domain||Range

| `overlay`
| `{two-colons}`
| `Image, Image`
| `->`
| `Image`
5+|`_overlay(star(30, "solid", "gold"),circle(30, "solid", "blue"))_`

| `pie-chart`
| `{two-colons}`
| `Table, String`
| `->`
| `Image`
5+|`_pie-chart(animals-table, "species"_`)

| `pie-chart-summarized`
| `{two-colons}`
| `(t {two-colons} Table, labels {two-colons} String, values {two-colons} String)`
| `->`
| `Image`
5+|`_pie-chart-summarized(animals-table, "age", "pounds")_`

| `put-image`
| `{two-colons}`
| `Image, Number, Number, Image`
| `->`
| `Image`
5+|`_put-image(star(30, "solid", "red"), 50, 150, rectangle(300, 200, "outline", "black"))_`

| `radial-star`
| `{two-colons}`
| `Number, Number, Number, String, String`
| `->`
| `Image`
5+| `_radial-star(17, 50, 10, "solid", "orange")_`

| `random-rows`
| `{two-colons}`
| `(t {two-colons} Table, num-rows {two-colons} Number)`
| `->`
| `Table`
5+|`_random-rows(animals-table, 5)_`

| `rectangle`
| `{two-colons}`
| `Number, Number, String, String`
| `->`
| `Image`
5+| `_rectangle(20, 80, "solid", "gold")_`

| `regular-polygon`
| `{two-colons}`
| `Number, Number, String, String`
| `->`
| `Image`
5+| `_regular-polygon(40, 8, "solid", "red")_`

| `rhombus`
| `{two-colons}`
| `Number, Number, String, String`
| `->`
| `Image`
5+| `_rhombus(20, 50, "solid", "turquoise")_`

|===
