[.landscape]
= Contracts

Contracts tell us how to use a function. For example: `num-min {two-colons} (a {two-colons} Number, b {two-colons} Number) -> Number` tells us that the name of the function is  `num-min`, it takes two inputs (both Numbers), and it evaluates to a  `Number`. From the contract, we know  `num-min(4, 6)` will evaluate to a  `Number`. *Use the blank line under each contract for notes or sample code for that function!*

[.contracts-table, cols="4,1,10,1,2", options="header", grid="rows"]
|===
|Name||Domain||Range

| `grouped-bar-chart`
| `{two-colons}`
| `(t {two-colons} Table, group {two-colons} String, subgroup {two-colons} String)`
| `->`
| `Image`
5+|`_grouped-bar-chart(animals-table, "sex", "species")_`

| `stacked-bar-chart`
| `{two-colons}`
| `(t {two-colons} Table, group {two-colons} String, subgroup {two-colons} String)`
| `->`
| `Image`
5+|`_grouped-bar-chart(animals-table, "sex", "species")_`

|
| `{two-colons}`
|
|`->`
|
5+|

|
| `{two-colons}`
|
|`->`
|
5+|

|
| `{two-colons}`
|
|`->`
|
5+|

|
| `{two-colons}`
|
|`->`
|
5+|

|
| `{two-colons}`
|
|`->`
|
5+|

|
| `{two-colons}`
|
|`->`
|
5+|

|
| `{two-colons}`
|
|`->`
|
5+|

|===
