= Which Ones Belong? (Absolute Value & Negate)

For each row, place a check mark by each Circle of Evaluation that meets the condition stated on the left.

++++
<style>
div.circleevalsexp { width: auto; }

/* for table cells with immediate .content children, which have immediate
 * .paragraph children: use flex to space them evenly and center vertically
*/
td > .content > .paragraph {
  display: flex;
  align-items: center;
  justify-content: space-around;
}
</style>
++++

[.FillVerticalSpace, cols="<.^1a,^.^3a,^.^10a",stripes="none", options="header"]
|===
| 	 | Value | Circles of Evaluation

| @n
| Which Circles evaluate to @math{20}?

@ifsoln{Circles 1 and 3.}
| @show{(coe '(negate (negate 20)))}
@show{(coe '(negate (negate -20)))}
@show{(coe '(num-abs (negate 20)))}
@show{(coe '(negate (num-abs 20)))}

| @n
| Which Circles evaluate to @math{-3}?

@ifsoln{Circles 1 and 2.}

| @show{(coe '(negate (num-abs 3)))}
@show{(coe '(negate (num-abs -3)))}
@show{(coe '(num-abs (negate 3)))}
@show{(coe '(num-abs (negate -3)))}

| @n
| Let @math{h=9}. Which Circles evaluate to @math{9}?

@ifsoln{Circles 1 and 3.}
| @show{(coe '(negate -h))}
@show{(coe '(negate (num-abs h)))}
@show{(coe '(num-abs -h))}
@show{(coe '(negate (negate -h)))}

| @n
| Let @math{h=6}. Which Circles evaluate to @math{6}?

@ifsoln{Circles 1 and 3.}
| @show{(coe '(+ (num-abs h) (- h h)))}
@show{(coe '(+ (negate h) (- h h)))}
@show{(coe '(* (/ h h) (num-abs h)))}

| @n
| Let @math{k=99}. Which Circles evaluate to @math{0}?

@ifsoln{All Circles!}
| @show{(coe '(+ k (negate k)))}
@show{(coe '(+ (negate k) k))}
@show{(coe '(+ (num-abs (+ 45 44)) (negate k)))}

| @n
| Let @math{a=11} and @math{b=20}. Which Circles evaluate to @math{31}?
@ifsoln{Circles 1, 2, and 3.}
| @show{(coe '(num-abs (+ a b)))}
@show{(coe '(num-abs (+ b a)))}
@show{(coe '(num-abs (negate (+ b a))))}
@show{(coe '(negate (num-abs (+ a b))))}

|===

