= Displaying Categorical Data: Pie Charts

++++
<style>
#content td { height: 20pt; }
#content p { font-size: 0.9rem; margin: 0;}
#content div.circleevalsexp, .editbox, .cm-s-scheme {font-size: .75rem;}
#content img { width: 55%; }
#content .listingblock .highlight { padding: 0; }
#content .forceShading { background-color: #f7f7f8; }
td.tableblock:nth-of-type(2) p.tableblock { text-align: left; }
.data-table td { margin: 0; padding: 0; }
</style>
++++

Here is a different way to present the proportions from the Hat Styles table:

@centered-image{../images/hats.png, "pie chart with a large blue wedge: 40% baseball caps, smaller red wedge: 30% cowboy hats, small yellow wedge: 10% fedora, slightly larger green wedge: 20% sombrero", 700}

This representation is called a @vocab{pie chart}. Contrast the pie chart with the table it was generated from.

[.data-table, cols="^.^1a, ^.^1a, ^.^1a, ^.^1a", options="header"]
|===
| Hat style 	| Count 	| Proportion (Fraction) | Proportion (Decimal)
| Baseball		| 4			| 4/10					| 0.4
| Cowboy		| 3 		| 3/10					| 0.3
| Fedora 		| 1			| 1/10					| 0.1
| Sombrero		| 2			| 2/10					| 0.2
| Total			| 10 		| -						|  -
|===

What do you notice?  

@fitb{}{}

@fitb{}{}

@fitb{}{}

What do you wonder?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

[.forceShading]
[.data-table, cols="1", grid="none", stripes="none"]
|===
|

@center{*To build your own pie chart from a table in Google Sheets:*}
|
1) Highlight the column of interest, including column title.
|
2) Go to the menu and click on “Insert” > “Chart”.
|
_If something other than a Pie Chart is generated, make sure Pie Chart is selected under “Chart Type” in the “Chart Editor” window on the right._
|===
