= Hour of Code

++++
<style>
	/* Hide the "all the lessons" dd and dt, as well as the "other resources" section */
	#lesson-list dd:last-child, #lesson-list dt:last-of-type, .sect1 { display: none; }
	.sect1:nth-child(2), .sect1:nth-child(3), .sect1:nth-child(4), .sect1:nth-child(5) {
		display: block; clear: both;
	}
	img, .image { width: 150px; float: right; margin-left: 10px; }
</style>
++++

Looking for a gentle, self-paced introduction to Bootstrap? Try the Hours of Code below. No prior programming experience required!

@span{.blankline}{}

== Hour of Data
@image{images/moose.png, moose}
@lesson-link{hoc-data/index.html, This Hour of Data lesson} is a self-guided Desmos activity. Students explore data visualization, introductory programming using The Pyret Programming Language, and the application of Data Science to solve real problems. Students will investigate a data set of vehicle-wildlife collisions in Vermont and make recommendations about where to build wildlife overpasses.

== Image Composition!
@image{../../lessons/hoc-winter/images/complete-snowman.png, snowman}
@link{../../lessons/hoc-winter-parley/index.html, This Hour of Code lesson} introduces students to image-producing functions, defining values and image placement using coordinates. A series of scaffolded student-paced activities in our Parley editor build student skills to the point that they'll be ready to modify code in a Pyret starter file to build a snowman scene at the end!

== Computing Needs All Voices!
@image{images/pioneers.png, computing pioneers}
@lesson-link{computing-needs-all-voices/index.html, In this lesson} students learn about a diverse group of programmers through a short film and a gallery walk of our Pioneers in Computing and Mathematics Poster series, then consider the problem solving advantages that diverse teams foster. There is no coding involved in this lesson.

== Intro to Graphics
@image{images/overlay.png, overlay}
@link{../../lessons/hoc-wescheme-intro/, This Hour of Code lesson} is a great, self-paced activity to introduce students to Bootstrap. Students explore simple function composition and order of operations in WeScheme, and then build on that knowledge to create simple computer graphics.

@span{.blankline}{}
