= Info for Families


++++
<style>
	.vocab {
    font-weight: bold;
    font-style: italic;
    color: #75328A;
	}
</style>
++++

@right{@image{algebra-logo.png}}

== My Child is learning Computer Science in Math Class?

Yes! @link{https://bootstrapworld.org/materials/algebra, Bootstrap:Algebra} is a series of integrated computer science modules that have been specially designed to reinforce and deepen math competency while building fluency with programming. We've been road-testing, researching, and improving upon these materials since 2005.

By introducing students to rigorous and engaging computing content in the classes that every student takes - regardless of gender, race, or background - Bootstrap is one of the largest providers of formal Computer Science education to girls and underrepresented students nationwide: nearly 50% of our students self-identify as African-American or Latin(x), and nearly 45% are girls and young women.

Through Bootstrap:Algebra your child will have the opportunity to:

- see the math behind animating characters on a screen
- learn to write code in a functional programming language, opening doors to future study of Computer Science
- use their creativity and math skills to customize a video game
- answer the question, "When am I ever going to use this?!" about many topics covered in Algebra class
- learn about a diverse set of pioneers and role models in computing and mathematics

@link{https://bootstrapworld.org/impact/, Evaluations of the curriculum} show that students perform better on "standard, pencil-and-paper word problems" after using Bootstrap:Algebra in their math classes. For students who apply their math skills to create a video game, we've found that "students feel a strong sense of ownership, originality, and pride in their creations". We also find that females find videogame creation just as satisfying as males, which may reflect the nature of games created in this curriculum and the opportunities it offers for self-expression.

== What supports are in the materials to help my child succeed?

Our programming environments have been developed with student learning as their top priority! A lot of research has been dedicated to designing the learning environment to:
 
- catch typical student mistakes and explain them in terms that students understand, so that students can debug their code independently
- develop student understanding of @vocab{functions} and @vocab{variables} in programming in such a way that it transfers to increased understanding of these concepts in Algebra
- integrate scaffolds that support students in solving word problems 
- make visible the structure behind the order of operations, such that students develop deeper understanding than the typical push to rely on mnemonic devices

== What can my student do to be successful in this course?

Although this is a computer science course, we do lots of work with paper and pencil! 

- Your child will benefit from preparing for time with hands on keys in the programming environment by working through the paper & pencil exercises assigned by their teacher.

Sometimes students get so excited about creating a video game, that they focus exclusively on making the game work.  Good computer programmers write code that not only works, but can be made sense of by others, whether to learn from it, debug it, or expand upon it as goals shift. 

- Encourage your student to make sure that they are learning how to write code that can be understood by another programmer.

== More About Bootstrap

The Bootstrap team brings decades of research and classroom experience to our work, with deep roots in middle, high school, undergraduate, and graduate classrooms. Our team is comprised of computer scientists, education researchers, and K-12 practicioners. Our research is group is based at Brown University, and we are grateful to the National Science Foundation for their continued support of this work. Our research involves statewide partnerships and numerous smaller collaborations with schools and districts, which continues to inform our work and improve our materials.

In addition to our work integrating Algebra and Computer Science, we are a leading provider of curriculum for @link{https://bootstrapworld.org/materials/data-science, Data Science} (with integration across many subject areas), and also develop materials for upper elementary Math and Physics.
