[.landscape]
= Contracts

Contracts tell us how to use a function. For example:  `ellipse {two-colons} (Number, Number, String, String) -> Image` tells us that the name of the function is  `ellipse`, it takes four inputs (two Numbers and two Strings), and it evaluates to an `Image`. From the contract, we know  `ellipse(100, 50, "outline", "red")` will evaluate to an `Image`.

[.contracts-table, cols="4,1,10,1,2", options="header", grid="rows"]
|===
| Name    			|	 | Domain      							|     	| Range

| `# num-sqr`
| `{two-colons}`
| `Number`
| `->`
| `Number`
5+|`_num-sqr(9)_`

| `# num-sqrt`
| `{two-colons}`
| `Number`
| `->`
| `Number`
5+|`_num-sqrt(25)_`

|`# string-length`
| `{two-colons}`
| `String`
|`->`
| `Number`
5+|`_string-length("Rainbow"}_`

|`# string-contains`
| `{two-colons}`
|`String, String`
|`->`
|`Boolean`
5+|`string-contains("catnap", "cat")`

| `# triangle`
| `{two-colons}`
| `Number, String, String`
| `->`
| `Image`
5+|`_triangle(80, "solid", "darkgreen")_`

| `# star`
| `{two-colons}`
| @ifsoln{`Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_star(50, "solid", "teal")_`}

| `# circle`
| `{two-colons}`
| @ifsoln{`Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_circle(30, "outline", "fuchsia")_`}

| `# square`
| `{two-colons}`
| @ifsoln{`Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_square(10, "outline", "red")_`}

| `# rectangle`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_rectangle(20, 80, "solid", "gold")_`}

|===
