= Variables and Code (Commutative Property)

@n Open @starter-file{variables-code}. On the table below, record your Noticings and Wonderings about what you see there.

[.FillVerticalSpace,cols="^1, ^1", stripes="none", options="header"]
|===

| Notice | Wonder
|
|

|===

@n Hit "Run." A message appears that says, "Looks shipshape, all 4 tests passed, mate!"

@n Click "Show Details" on the right side of the green `examples-block-1` rectangle. Describe what you see. @fitb{}{@ifsoln{Each of the four examples}}

@fitb{}{@ifsoln{is listed in green, and above each example we can see if it passed.}}

@n In lines 4-5 of the Definitions Area (left side of the screen), change the variable definitions. This time, use `a = 6` and `b = 10`. What do you predict will happen when you hit "Run"? @fitb{}{}

@fitb{}{}

@n Was your prediction correct? @fitb{4em}{} In your own words, explain what happened and why. If you need help, click "Show Details". @fitb{}{}

@fitb{}{}

@n Was your prediction correct? @fitb{5em}{} In your own words, explain what happened and why. If you need help, click "Show Details". @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n Give three additional pairs of values for `a` and `b` that will cause _both_ example 3 and example 4 to fail. Try them out!

@hspace{2em} `a` = @fitb{4em}{} @hspace{1em} `b` = @fitb{4em}{} @hspace{6em}
`a` = @fitb{4em}{} @hspace{1em} `b` = @fitb{4em}{} @hspace{6em}
`a` = @fitb{4em}{} @hspace{1em} `b` = @fitb{4em}{}

@n Are there any pairs of values for `a` and `b` that will cause example 1 or example 2 to fail? If so, list them here: @fitb{}{@ifsoln{No.}}

@n Are any of the examples true *every time*, no matter what values we use for `a` and `b`? If so, which ones? @fitb{}{@ifsoln{Examples 1 and 2 are always true.}}

@n Are any of the examples true *some of the time*, depending on what values we use for `a` and `b`? If so, which ones? @fitb{}{@ifsoln{Yes, examples 3 and 4.}}

@n Maria says, "The Commutative Property applies for every operation. I know because sometimes I can change the order of the numbers being subtracted or divided and the result remains the same." Is she correct? Explain. @fitb{}{}

@blanklines{3}{
@ifsoln{Maria is incorrect. The Commutative Property only applies for addition and multiplication. Two expressions are only equivalent if they always produce the same value, no matter what numbers we use for the variables.}
}

