= Completing Circles of Evaluation from Arithmetic Expressions

@vspace{2ex}

For each expression on the left, finish the Circle of Evaluation on the right by filling in the blanks.

@do{
  (define expr1 '(- (+ 4 2) (frac 10 5)))
  (define expr2 '(+ (- 7 1) (* 5 8)))
  (define expr3 '(frac -15 (+ 5 -8)))
  (define expr4 '(* (+ 4 (- 9 8)) 5))
  (define expr5 '(+ (* 6 4) (frac (- 9 -6) 5) ))
  (define expr6 '(- (frac 20 (+ 6 4))(frac (* 5 9) (- -12 3))))

  (define mat1 (sexp->math expr1))
  (define mat2 (sexp->math expr2))
  (define mat3 (sexp->math expr3 #:parens #t))
  (define mat4 (sexp->math expr4 #:parens #t))
  (define mat5 (sexp->math expr5))
  (define mat6 (sexp->math expr6 #:parens #t))

  (define coe1 '((?ANS -) ((?ANS +) 4 2) (/ (?ANS 10) 5)))
  (define coe2 '(+ ((?ANS -) 7 1) (* (?ANS 5) (?ANS 8))))
  (define coe3 '(/ (?ANS -15) (+ 5 (?ANS -8))))
  (define coe4 '(* ((?ANS +) 4 ((?ANS -) 9 8))
                   (?ANS 5)))
  (define coe5 '((?ANS +) ((?ANS *) (?ANS 6) 4)
                                   (/ ((?ANS -) 9 (?ANS -6)) (?ANS 5))))
  (define coe6 '((?ANS -) ((?ANS /) 20 (+ (?ANS 6) 4))
                                   ((?ANS /) ((?ANS *) (?ANS 5) (?ANS 9))
                                                      (- (?ANS -12) 3))))

}

[cols=".^1a,^4a,^.^12a",options="header",stripes="none"]
|===
|           | Arithmetic Expression     | Circle of Evaluation
|*1*        | @show{mat1}    	          | @show{(sexp->coe coe1)}
|*2*        | @show{mat2}   		        | @show{(sexp->coe coe2)}
|*3*        | @show{mat3}               | @show{(sexp->coe coe3)}
|*4*        | @show{mat4}               | @show{(sexp->coe coe4)}
|*5*        | @show{mat5}               | @show{(sexp->coe coe5)}
|★          | @show{mat6}               | @show{(sexp->coe coe6)}
|===
