= Translating Circles of Evaluation to Code

++++
<style>
  #content td {height: 250pt;}
</style>
++++

@vspace{2ex}

Translate the Circles of Evaluation into Code.
@ifsoln{*Teachers:* the answers below are shown with _all_ parentheses included. There are also correct solutions in which the unecessary parens are left out.}

@do{
  (define expr1 '(+ 4 -9))
  (define expr2 '(- -1 14))
  (define expr3 '(* -5 6.2))
  (define expr4 '(/ 0 (* 12 -9)))
  (define expr5 '(* (+ 9.1 -1) 7))
  (define expr6 '(+ 3 (* 8 -8)))
  (define expr7 '(- (* 6 -2) (+ 0 1)))
  (define expr8 '(+ -13 (/ 100 (+ 3 6))))
  (define expr9 '(- (* (- 15 7) 7) 6.5))
}

[cols="^1a,^1a,^1a",stripes='none']
|===

|@n @show{(sexp->coe expr1)}
@showsoln{(sexp->code expr1 #:parens true) }

|@n @show{(sexp->coe expr2)}
@showsoln{(sexp->code expr2 #:parens true) }

|@n @show{(sexp->coe expr3)}
@showsoln{(sexp->code expr3 #:parens true) }

|@n @show{(sexp->coe expr4)}
@showsoln{(sexp->code expr4 #:parens true) }

|@n @show{(sexp->coe expr5)}
@showsoln{(sexp->code expr5 #:parens true) }

|@n @show{(sexp->coe expr6)}
@showsoln{(sexp->code expr6 #:parens true) }

|@n @show{(sexp->coe expr7)}
@showsoln{(sexp->code expr7 #:parens true) }

|@n @show{(sexp->coe expr8)}
@showsoln{(sexp->code expr8 #:parens true) }

|@n @show{(sexp->coe expr9)}
@showsoln{(sexp->code expr9 #:parens true) }
|===
