= Translating Circles of Evaluation to Code - w/Square Roots

++++
<style>
<<<<<<< HEAD
    table { height: 95%; }
=======
  table { height: 95%; }
>>>>>>> master
</style>
++++

Translate each of the arithmetic expressions below into Circles of Evaluation, then translate them to Code. 
@ifsoln{*Teachers:* the solution code below is shown with only the _necessary_ parentheses. If a student chooses to add additional (correct) parentheses, they will still have the correct answer.}

@ifproglang{wescheme}{*HINT:* The function name is `sqrt`.}
@ifproglang{pyret}{*HINT:* The function name is `num-sqrt`.}

@do{
  (define expr1 '(sqrt 9))
  (define expr2 '(sqrt (+ 5 1)))
  (define expr3 '(+ (sqrt 4) 1))
  (define expr4 '(+ (* 3 (sqrt 3)) (sqrt 7)))
}

[cols="^.^1a,^.^8a,^.^15,^.^15a",options="header",stripes="none"]
|===
|
| Arithmetic
| Circle of Evaluation
| Code

|*@n*
| @show{    (sexp->math expr1)}
| @showsoln{(sexp->coe  expr1)}
| @showsoln{(sexp->code expr1)}

|*@n*
| @show{    (sexp->math expr2)}
| @showsoln{(sexp->coe  expr2)}
| @showsoln{(sexp->code expr2)}

|*@n*
| @show{    (sexp->math expr3)}
| @showsoln{(sexp->coe  expr3)}
| @showsoln{(sexp->code expr3)}

|*@n*
| @show{    (sexp->math expr4)}
| @showsoln{(sexp->coe  expr4)}
| @showsoln{(sexp->code expr4)}

|===
