= Translate Arithmetic Expressions to Circles of Evaluation & Code

++++
<style>
  td {height: 175pt;}
</style>
++++

@vspace{2ex}

Translate each of the arithmetic expressions below into Circles of Evaluation, then translate them to Code.

@do{
  (define expr1 '(+ (- 7 8) (* 3 2)))
  (define expr2 '(+ (- 5 (/ 8 2)) 1))
  (define expr3 '(- (* 9 6) (* 7 (/ 8 2))))
  (define expr4 '(- 6 (* (+ 5 3)2)))

  (define coe1 (if *solutions-mode?* (sexp->coe expr1) ""))
  (define coe2 (if *solutions-mode?* (sexp->coe expr2) ""))
  (define coe3 (if *solutions-mode?* (sexp->coe expr3) ""))
  (define coe4 (if *solutions-mode?* (sexp->coe expr4) ""))

  (define code1 (if *solutions-mode?* (sexp->code expr1) ""))
  (define code2 (if *solutions-mode?* (sexp->code expr2) ""))
  (define code3 (if *solutions-mode?* (sexp->code expr3) ""))
  (define code4 (if *solutions-mode?* (sexp->code expr4) ""))
}


[cols=".^1a,^10a,^20a,^15a",options="header",stripes="none"]
|===
|   | Arithmetic				                        | Circle of Evaluation	| Code
|*1*| @math{7 - 8 + 3 \times 2}                 | @show{coe1}			      | @show{code1}
|*2*| @math{5 - 8 \div 2 + 1}	                  | @show{coe2}			      | @show{code2}
|*3*| @math{9 \times 6 - 7 \times (8 \div 2)}   | @show{coe3}			      | @show{code3}
|*4*| @math{6 - (5 + 3) \times 2}               | @show{coe4}			      | @show{code4}
|===