= Maya History and Culture

@description{In this lesson students will use human sacrifice as an entry point for learning about Maya society, but will recognize that learning about one practice of the Maya is not enough information to make a broader conclusion about who the Maya were as a people and what led to their downfall.}

@lesson-prereqs{}

@keywords{}

@add-to-lang{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* analyze a variety of sources in order to learn more about Maya society and explore different theories and portrayals of the Maya civilization.
* predict why the Maya civilization ended based on a variety of primary and secondary sources.
* use a timeline to grasp chronology of events in history
* understand that information can be collected with a survey.

| Student-facing Lesson Goals
|

*

| Materials
|[.materials-links]

@material-links

| Preparation
|

| Supplemental Resources
| * @link{https://www.sciencealert.com/guatemala-maya-civilisation-lidar-vast-megalopolis-hidden-for-centuries, Science Alert: Laser Survey Has Revealed Vast Network of Hidden Maya Structures}

|===

== What Happened to the Maya? @duration{10 minutes}

=== Overview

=== Launch

[.lesson-instruction]
A few thousand years before Europeans began settling the northeast corner of North America, the highly sophisticated Maya civilization took root throughout most of the region that is now Mexico and Central America. At its peak, around 20 million Maya people lived in highly advance cities... and then, suddenly, about a thousand years ago, they practically disappeared. Imagine if 9 out of every 10 people living in our cities just disappeared! How many people would be left in this classroom?!

* _Divide the number of the people in the room by 10._
* _Or, for a quick kinesthetic visualization, have everyone stand. Direct them to count off... and sit down as they say their number unless they are number 10, 20, 30 or 40... eg 1 to 9 sit down... 10 stays standing... 11 to 19 sit down... 20 stays standing..._

[.lesson-instruction]
Turn to the map on @printable-exercise{map.adoc} and consider the geographical advantages and disadvantages of building a civilization on the Yucatan Peninsula?

To get data about Native Americans and settlers in the Northeast, scientists can rely heavily on written sources, such as books containing individual people’s reports on their dealings with the Native Americans, as well as records like ships’ logs and town ledgers about the colonists who came from Europe.

[.lesson-instruction]
How do we learn about societies like the Maya, whose @vocab{hieroglyphic} writings were not only difficult to decipher, but were also almost completely destroyed during the Spanish invasion in the 1500s?

@vocab{Archaeology} is the study of physical remains and the things that people made, used, and left behind. By analyzing data about the Maya provided by archaeologists, we can solve many of the mysteries of their civilization.

Before we look at some of these archaeological discoveries, it helps to orient ourselves with a timeline that roughly sketches out the rise and fall of the Maya civilization.

[.lesson-instruction]
Turn to @printable-exercise{timeline.adoc} and answer the questions.

Note that population sizes over the past three thousand years can only be educated guesses because until recently there was no such thing as Census data for the Maya.

== The Spanish Invasion

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{BACKGROUND KNOWLEDGE:}

After Cortes conquered the Aztecs in the early 1500s, the Spanish moved to the Yucatán. This created major conflict between the Spanish and the Maya, who, though not nearly as numerous or powerful as they used to be, had a uniquely sophisticated civilization in the Americas, including a written language, a number system, a calendar, an understanding of astronomy (the positions of stars, planets, etc.), and a religion.
|
In 1549, a Franciscan friar named Diego de Landa was sent to the Yucatán, as part of Spain’s mission to convert the Maya to Catholicism. In the years to come, he tortured and killed countless Maya in his quest to locate and destroy their idols and temples. He also destroyed thousands of their hieroglyphic books (called codices), so that only three remain in the world today. These three codices give us a glimpse at the wisdom and beauty of the ancient Maya culture. The Maya god of maize (corn) appeared in many of their writings and art. Corn was so important to the Maya that humans are depicted as having been created from an ear of corn!
|
There are different ways to define the word “Historic.” One of its meanings has to do with whether or not there are written records from a time period. This definition explains why experts on the Maya civilization (which starts with “Pre-Classic” in about 1250 BCE) use the word “Historic” for the period beginning in 1520. This is referring to records written by the Spanish, not by the Maya.
|===

[.lesson-instruction]
Turn to @printable-exercise{spanish-on-maya.adoc} and read the descriptions of the Maya written by Diego de Landa and Bartolome de Las Casas, two Spanish missionaries who worked in the Yucatán in the 1500s.

== Discovery of Remains of Human Sacrifice Victims

In modern day, archaeologists have learned a lot about the Maya civilization from uncovering human remains in cenotes, which were believed to be holy sites. Archaeologists currently believe that human remains were from human sacrifice to various gods.

[.lesson-instruction]
Turn to @printable-exercise{research-on-maya.adoc}.


== Maya Gods

To get a better glimpse at the exotic Maya culture, it helps to understand what was important to them by learning about the gods they worshipped.

To avoid confusion, experts assign letter names to the Maya gods. Here are some tips on how to identify the first five gods from their pictures:

- God A typically has a skeletal appearance
- God B is often associated with a serpent
- God C is sometimes shown rising out of a turtle or toad
- God D may be holding a peccary (type of pig)
- God E usually has some resemblance to an ear of corn

[.lesson-instruction]
Turn to @printable-exercise{gods.adoc} and see if you can match the descriptions to the images.

Possible discussion:

Before embarking on a study of the Maya civilization with the help of data science tools, have students guess which two of the above symbols (turtle, skeleton, pig, corn, snake) will turn out to represent answers to the Unit's two big questions:

. How do we learn about societies like the Maya, whose @vocab{hieroglyphic} writings were not only difficult to decipher, but were also almost completely destroyed during the Spanish invasion in the 1500s?

. What can past civilizations teach us about the environment’s role in a society’s survival?

== Gathering Data

Before the next social studies class period, students are to survey 6 people who are older than them (parents, older siblings, other relatives, neighbors…) to see what they know or think about the Maya, and circle each Respondent’s answer. (The 1st Respondent’s  answers all get circled below R1, the 6th Respondent’s answers all get circled below R6; and so on.) For practice, students get a partner’s responses to complete the first (R1) column. After completing the survey with 5 more respondents for homework, they turn the sheet in to the teacher next time class meets.  The teacher will tally responses by the end of this Unit, so after they try answering all the questions again themselves, the class can discuss the overall results of their survey.  [For example, maybe 75/150 = 0.50 respondents knew that the Maya civilization began about 3,000 years ago…]

_Possible Discussion: To preview data science ideas, imagine that you’ve found Maya necklaces, some made of jade and others made of jaguar teeth. The necklaces have different numbers of beads. In other words, the necklaces vary. In this case, there are two variables of interest: type of bead and how many beads. Type of bead is categorical, summarized by reporting fractions or proportions: for instance, maybe 4/10 = 0.40 of the necklaces are jade and 6/10 = 0.60 are made of jaguar teeth. Number of beads is quantitative, summarized by reporting the average: for instance, maybe the average number of beads on the necklaces is 35._

== Synthesize

What theories do you have for why the Maya empire collapsed? List at least 3 and star the one you believe in the most!

