= Count and Proportion

++++
<style>
#content td { height: 20pt; }
#content p { font-size: 0.9rem; margin: 0;}
#content div.circleevalsexp, .editbox, .cm-s-scheme {font-size: .75rem;}
#content img { width: 55%; }
#content .listingblock .highlight { padding: 0; }
#content .forceShading { background-color: #f7f7f8; }
td.tableblock:nth-of-type(2) p.tableblock { text-align: left; }
.data-table td { margin: 0; padding: 0; }
</style>
++++

[.forceShading]
--
@vocab{count}: the number of items in a certain category

@vocab{proportion}: a fraction, decimal, or percent that equals count divided by total

@vocab{pie chart}: a display that uses areas of a circular pie's slices to show proportions in each category
--

We'll talk through this example dataset together...

[cols="^1a, ^1a", options="header"]
|===
| Raw Data	| Count

|
[.data-table, cols="^.^1a, ^.^1a", options="header"]
!===
! Head Size ! Hat style
! 20.5		! Baseball Cap
! 21		! Baseball Cap
! 22		! Baseball Cap
! 25		! Baseball Cap
! 21.5		! Cowboy Hat
! 23		! Cowboy Hat
! 24.5		! Cowboy Hat
! 21.5		! Fedora
! 23		! Sombrero
! 23		! Sombrero	
!===

|
[cols="^.^1a, ^.^1a, ^.^1a, ^.^1a", options="header"]
!===
! Hat style 	! Count 		! Proportion (Fraction) ! Proportion (Decimal)
! Baseball		! @ifsoln{4}	! @ifsoln{4/10}			! @ifsoln{0.4}
! Cowboy		! @ifsoln{3}	! @ifsoln{3/10}			! @ifsoln{0.3}
! Fedora 		! @ifsoln{1}	! @ifsoln{1/10}			! @ifsoln{0.1}
! Sombrero		! @ifsoln{2}	! @ifsoln{2/10}			! @ifsoln{0.2}
! Total			! @ifsoln{10}	! -						!  -
!===
|===

@vspace{1ex}

Make a copy of the @online-exercise{https://docs.google.com/spreadsheets/d/1Finl40MSuZ32MKnpK0hnKuFPYYwNGsHmU9LDQFqvOVk/edit?usp=sharing, Skulls Google Sheet}. We'll use the data in the `Skulls by Sex` tab to complete this table.

[cols="^.^1a, ^.^1a, ^.^1a, ^.^1a", options="header"]
|===
| Sex 		| Count 		| Proportion (Fraction) |Proportion (Decimal)
| Female 	| @ifsoln{1}	| @ifsoln{1/20}			|@ifsoln{0.05}
| Male		| @ifsoln{11}	| @ifsoln{11/20}		|@ifsoln{0.55}
| Unsure	| @ifsoln{8}	| @ifsoln{8/20}			|@ifsoln{0.4}
| Total		| @ifsoln{20}	| -						| -
|===

@vspace{1ex}

We'll use the data from the `Skulls by Age Group` tab to complete this table.

[cols="^.^1a, ^.^1a, ^.^1a, ^.^1a", options="header"]
|===
| Age Group 	| Count 		| Proportion (Fraction) |Proportion (Decimal)
| Adult 		| @ifsoln{14} 	| @ifsoln{14/20}  		| @ifsoln{0.7}
| Child			| @ifsoln{4} 	| @ifsoln{4/20} 		| @ifsoln{0.2}
| Unsure	 	| @ifsoln{2} 	| @ifsoln{2/20} 		| @ifsoln{0.1}
| Total			| @ifsoln{20} 	| -						| -
|===
