= Writing Purpose Statements

Decide whether filter, build, or transform changed the original table. Then, write a Purpose Statement that describes what the Transformer's expression does.

@vspace{1ex}

*Scenario 1*

[cols="1a,1a", options="header"]
|===
| Original Table
| Transformed Table
|
!===
! Name 		! Species
! Felix 	! cat
! Sheba		! cat
! Billie	! snail
!===
|  [cols="1a,1a"]
!===
! Name 		! Species
! Billie	! snail
!===
|===

- *Purpose Statement:* Checks the row to see whether the @fitb{15em}{@ifsoln{species}} is a @fitb{15em}{@ifsoln{snail}}.

- *What would be a good name for this Transformer?* @fitb{25em}{@ifsoln{`filter-if-dog`}}

@vspace{1ex}

*Scenario 2*


[cols="1a,1a", options="header"]
|===
| Original Table
| Transformed Table
|
!===
! Name	 	! Species
! Daisy		! dog
! Ada 		! dog
! Miaulis 	! cat
!===
|  [cols="1a,1a"]
!===
! Name	 	! Species
! Daisy		! dog
! Ada 		! dog
!===
|===

- *Purpose Statement:* @fitb{}{@ifsoln{Checks the row to see whether the species is a dog.}}

- *What would be a good name for this Transformer?* @fitb{25em}{@ifsoln{`filter-if-dog`}}

@vspace{1ex}

*Scenario 3*

[cols="1a,1a", options="header"]
|===
| Original Table
| Transformed Table
|
!===
! Name 	! Pounds
! Sasha 	! 6.5
! Snuffles 	! 3.5
! Mittens 	! 7.4
!===
|  [cols="1a,1a,1a"]
!===
! Name 		! Pounds	! Kilos
! Sasha 	! 6.5 		! 2.9
! Snuffles 	! 3.5 		! 1.6
! Mittens 	! 7.4 		! 3.4
!===
|===

- *Purpose Statement:* @fitb{}{@ifsoln{Checks the row to see whether the species is a dog.}}

- *What would be a good name for this Transformer?* @fitb{25em}{@ifsoln{`filter-if-dog`}}

@vspace{1ex}

*Scenario 4*


[cols="1a,1a", options="header"]
|===
| Original Table
| Transformed Table
|
!===
! this 	! part
! is 	! nested
! this 	! part
! is 	! nested
!===
|  [cols="1a,1a"]
!===
! this 	! part
! is 	! nested
!===
|===

