= Numbers and Strings

Make sure you’ve loaded the @ifproglang{wescheme}{wescheme.org} @ifproglang{pyret}{code.pyret.org, (CPO)} editor, clicked “Run”, and are working in the @vocab{Interactions Area}.

== Numbers

@n Try typing `42` into the Interactions Area and hitting “Enter”.  What is the largest number the editor can handle?
 @span{.blankline}{@ifsoln{_I didn't find a number that was too big!_}}

@n Try typing `0.5`. Then try typing `.5`. Then try clicking on the answer. Experiment with other decimals. Explain what you understand about how decimals work in this programming language.
 @ifproglang{wescheme}{@span{.blankline}{@ifsoln{_Regardless of how we type it in, the editor returns it with a zero in front of the decimal._}}}
@ifproglang{pyret}{@span{.blankline}{@ifsoln{_In pyret, decimals need to be typed with a zero in front of the decimal point._}}}
 @span{.blankline}{}

@n What happens if you try a fraction like `1/3`?
 @span{.blankline}{@ifsoln{_The editor will return the decimal equivalent. It even does repeating decimals!}}

@n Try writing negative integers, fractions and decimals.

== Strings

String values are always in quotes.

@n Is `42` the same as `"42"`? Why or why not? Write your answer below:
 @span{.blankline}{}

@n Try typing your name _(in quotes!)_.

@n Try typing a sentence like "I'm excited to learn to code!" _(in quotes!)_.

@n Try typing your name with the opening quote, but _without the closing quote._ Read the error message!

@n Now try typing your name _without any quotes._ Read the error message!

@n Explain what you understand about how strings work in this programming language.
 @span{.blankline}{@ifsoln{_strings require quotes_}}
 @span{.blankline}{}

@ifproglang{pyret}{

== Operators

@n Just like math, Pyret has @vocab{operators} like `+`, `-`, `*` and `/`. Try typing in `4 + 2`, and then `4+2` (without the spaces). What can you conclude from this?
@span{.blankline}{@ifsoln{_operators require spaces._}}

@n Type in the following expressions, one at a time: `4 + 2 + 6`, `4 + 2 * 6`, `4 + (2 * 6)`. What do you notice?
@span{.blankline}{@ifsoln{_If you use more than one operator you have to insert parentheses to tell the computer which operation to apply first_}}

@n Try typing in `4 + "cat"`, and then `"dog" + "cat"`. What can you conclude from this? +
@span{.blankline}{@ifsoln{_you can combine two strings, but you can't combine a number and a string_}}

}
