
= Function Composition -- f of g of h

[cols="1,1,1",stripes="none"]
|===
|  
``
f :: Number -> Number
consumes a number, multiplies it by 3, and produces the result
``
|
``
g :: Number -> Number
consumes a number, adds six, and produces the result
``
|
``
h :: Number -> Number
consumes a number, subtracts one, and produces the result
``
|
`f(x) = 3x`
|
`g(x) = x + 6`
|
`h(x) = x - 1`
|===

For each Circle of Evaluation below, draw the equivalent Circle of Evaluation. Then write expressions for both versions of the Circle of Evaluation and evaluate them for `x = 4`.

@do{
  (define expr1 '(-  (+ (* 3 x) 6) 1))
  (define expr2 '(+ (* 3 (- x 1)) 6))
  (define expr3 '(- (* 3 (+ x 6)) 1))

  (define expr4 '(?ANS  (?ANS(?ANS ?ANS ?ANS) ?ANS) ?ANS))
  (define code2 '(?ANS (?ANS ?ANS (?ANS ?ANS ?ANS)) ?ANS))
  (define code3 '(?ANS (?ANS ?ANS (?ANS ?ANS ?ANS)) ?ANS))
}

[cols="1,2,2",stripes="none"]
|===

|  						| Equivalent Circle of Evaluation  		| Code & Math
| *Example:* @show{(sexp->coe `(f (g (h x))))} 		| @show{(sexp->coe `(* 3 (+ 6 (- x 1))))} 	| 

[cols="1,1"] 
!=== 
! 1st expression: 		! @fitb{10em}{@show{(sexp->code `(f (g (h x))))}}
! 2nd expression: 		! @fitb{10em}{@show{(sexp->code `(* 3 (+ 6 (- x 1))))}} 
! Evaluate for x = 4 	! @fitb{10em}{*@math{f(g(h(4)))} Evaluates to:* 27} 
!===

| @n  @show{(sexp->coe `(h (g (f x))))}  			| @show{(sexp->coe expr4)} | 

[cols="1,1"] 
!=== 
! 1st expression: 		! @fitb{10em}{}
! 2nd expression: 		! @fitb{10em}{} 
! Evaluate for x = 4 	! @fitb{10em}{} 
!===

| @n  @show{(sexp->coe `(g (f (h x))))}  			| @show{(sexp->coe code2)} | 

[cols="1,1"] 
!=== 
! 1st expression: 		! @fitb{10em}{}
! 2nd expression: 		! @fitb{10em}{} 
! Evaluate for x = 4 	! @fitb{10em}{} 
!===

| @n  @show{(sexp->coe `(h (f (g x))))}  			| @show{(sexp->coe code3)} |

[cols="1,1"] 
!=== 
! 1st expression: 		! @fitb{10em}{}
! 2nd expression: 		! @fitb{10em}{} 
! Evaluate for x = 4 	! @fitb{10em}{} 
!===

|===


