[.landscape]

= More than one way to Compose an Image!

++++
<style>
.forceShading { background: #f7f7f8; }
</style>
++++


For each image below, identify 2 expressions could be used to compose it. _The bank of expressions at the bottom of the page includes one possible option for each image._

[cols="1,^.^6,24", stripes="none"]																	
|===
a| @n
a| @image{../images/vert-rect.png} 
a|
* @show{(sexp->code '(rotate 90 (rectangle 200 100 "solid" "black")))}	
* @span{.blankline}{}
* @span{.blankline}{}

a| @n
a| @image{../images/square.png}
a| 
* @show{(sexp->code '(above (rectangle 200 100 "solid" "black")(rectangle 200 100 "solid" "black")))}	
* @span{.blankline}{}
* @span{.blankline}{}

a| @n
a| @image{../images/hor-rect.png}
a| 
* @show{(sexp->code '(scale 0.5 (rectangle 600 200 "solid" "black")))}	
* @span{.blankline}{}
* @span{.blankline}{}

a| ★
a|  @image{../images/black-cross.png}
a| 
* @show{(sexp->code '(overlay (rectangle 100 200 "solid" "black")(rectangle 200 100 "solid" "black")))}
* @span{.blankline}{}
* @span{.blankline}{}

a| ★
a|  @image{../images/t.png}
a| 
* @span{.blankline}{}
* @span{.blankline}{}

|===

[.forceShading]
--

@show{(sexp->code '(beside (rectangle 200 100 "solid" "black")(square 100 "solid" "black")))}		

@show{(sexp->code '(above (rectangle 200 100 "solid" "black")(square 100 "solid" "black")))}

@show{(sexp->code '(scale-xy 1 2(square 100 "solid" "black")))}

@show{(sexp->code '(scale 2 (rectangle 100 100 "solid" "black")))}

@show{(sexp->code '(above(rectangle 100 50 "solid" "black") (above(rectangle 200 100  "solid" "black") (rectangle 100 50 "solid" "black"))))}

--