
= More than one way to Compose an Image!

++++
<style>
.lesson-section-1 { border: 0px !important;	}
.big 			  { font-size: 60pt;		}
</style>
++++

For each expression below, identify another expressions that would compose the same image. 

- The bank of expressions at the bottom of the page includes one option for each. 
- If you have time, try to think of a second expression that would work!																				

@n @image{../images/vert-rect.png} @quad{2em} @show{(sexp->code '(rotate 90 (rectangle 200 100 "solid" "black")))}	

- A: @fitb{35em}{}
- B: @fitb{35em}{}

@n @image{../images/square.png} @quad{2em} @show{(sexp->code '(above (rectangle 100 50 "solid" "black")(rectangle 100 50 "solid" "black")))}	

- A: @fitb{35em}{}
- B: @fitb{35em}{}

@n @image{../images/t.png} @quad{2em}@show{(sexp->code '(scale 4 (rectangle 50 100 "solid" "black")))}		

- A: @fitb{35em}{}
- B: @fitb{35em}{}

@n @image{../images/hor-rect.png} @quad{2em}@show{(sexp->code '(rotate 90 (rectangle 50 100 "solid" "black")))}	

- A: @fitb{35em}{}
- B: @fitb{35em}{}

@n @show{(sexp->code '(beside (square 50 "solid" "black")(square 50 "solid" "black")))}	

- A: @fitb{35em}{}
- B: @fitb{35em}{}

@n @show{(sexp->code '(beside (rectangle 25 100 "solid" "black")(rectangle 25 100 "solid" "black")))}	

- A: @fitb{35em}{}
- B: @fitb{35em}{}

@n @show{(sexp->code '(scale-xy 1 0.5 (square 50 "solid" "black")))}

- A: @fitb{35em}{}
- B: @fitb{35em}{}									

@span{.blankline}{}

@show{(sexp->code '(rectangle 100 200 "solid" "black"))}
@show{(sexp->code '(scale 2 (rectangle 100 200 "solid" "black")))}
@show{(sexp->code '(scale 0.5 (rectangle 200 100 "solid" "black")))}
@show{(sexp->code '(beside (rectangle 50 100 "solid" "black")(rectangle 50 100 "solid" "black")))}		
@show{(sexp->code '(rotate 90 (rectangle 50 100 "solid" "black")))}
@show{(sexp->code '(above (square 50 "solid" "black")(square 50 "solid" "black")))}
@show{(sexp->code '(scale-xy 2 1 (square 25 "solid" "black")))}