= Bar and Pie Charts

@description{Students use data displays like bar and pie charts to create 1- and 2-level groupings to visualize the distribution of categorical data.}

@lesson-prereqs{ds-intro, contracts-tables-displays}

@keywords{bar chart, pie chart, stacked bar chart, multi bar chart, categorical, visualization, display}

@add-to-lang{bar-chart, pie-chart, pie-chart-summarized, bar-chart-summarized, multi-bar-chart, stacked-bar-chart}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* Read and create pie and bar charts
* Explain the difference between pie and bar charts
* Read and create stacked and multi bar charts
* Explain the difference between pie and bar charts

| Student-facing Lesson Goals
|

* Let's use functions to create pie and bar charts to visualize categorical data
* Let's visualize categorical data grouped in different ways

| Materials
|[.materials-links]

@material-links

| Preparation
|
* All students should log into @starter-file{program-list} and open their saved "Animals Starter File". If they don't have the file, they can open a new one from @starter-file{animals}.
|===

== Grouping by Value @duration{25 minutes}

=== Overview
Students learn one way of grouping data, showing the @vocab{frequency} of values in a dataset using bar and pie charts.

=== Launch

Open the @starter-file{animals}, click "Run" and test the expressions @show{(code '(count animals-table "species"))} and @show{(code '(bar-chart animals-table "species"))} in the Interactions Area.

=== Investigate

@lesson-instruction{
Turn to Part A of @printable-exercise{count-bar-pie.adoc}.
}

@QandA{
@Q{How do the count table and bar chart you just made compare?}
@A{The height of each bar matches the count of each species.}
@Q{How does this pie chart compare to the bar chart you just made?}
@A{The wedges show percentages, whereas the bar chart was labeled with the count. We could figure out how many animals were in the sample from the bar chart. With the pie chart we see how the categories compare to each other, but we have no way of knowing how many animals each wedge represents.}
}


@image{images/count-table.png, 160} @image{images/bar-chart-popout.png, 385}

Both `bar-chart` and `count` *group the data in one column by value*, creating "buckets" for each unique value and counting the number of rows in each bucket, one uses a picture and one uses a table.

When you first build a bar chart or pie chart in pyret, they are interactive displays. That means that you can mouse over a bar to reveal the label, as well as the number of animals in that species. We can also resize the window by dragging its borders. This allows us to experiment with the data before closing the window and generating the final, non-interactive image.

@lesson-point{
Bar charts group data _by value_ to show frequency as a count. 
}

@right{@image{images/pie-species-popout.png, 275}}Pie charts show us the @vocab{percentage} of the data points that fall in each category. Hovering over a pie slice reveals the label, as well as the count and the percentage of the whole. In this example we see that there is 1 animal that is a snail, representing 3.1% of the population.

@lesson-point{
Pie charts group data _by value_ to show frequency as a percentage.
}

If our data is based on sample data from a larger population, we can use these charts to _infer_ the proportion of a whole population that might belong to each category. For example, the distribution of species in our shelter might help us make guesses about the distribution of species in other shelters.

While bars in some bar charts should follow some logical order (alphabetical, small-medium-large, etc), the pie slices and bars can really be placed in _any_ order, without changing the meaning of the chart.

////
- Now test the expressions @show{(code '(count animals-table "pounds"))} and @show{(code '(bar-chart animals-table "pounds"))}. Which do you prefer and why?
** __Answers will vary, but a bar chart with many equally-sized bars representing the number of animals having each specific weight is less useful than the last.__
////

@lesson-instruction{
Complete B & C of @printable-exercise{count-bar-pie.adoc}.
}

@QandA{

@Q{Why isn't it useful to group the `pounds` column using these functions?}
@A{Grouping by value works well for @vocab{categorical data}, when lots of different data points can be sorted into a smaller number of buckets. But for @vocab{quantitative data} - which can have lots of different values - the number of buckets is too large to be useful.}

@Q{Look at the list of columns in the Definitions Area. For which columns do you expect pie charts to be most useful?}
@A{Species, Sex, Fixed, and Legs}

}



@lesson-point{
Grouping by value works well when lots of different data points can be sorted into a smaller number of buckets.
}

@lesson-instruction{
* Turn to @printable-exercise{bar-and-pie-notice.adoc} and take two minutes to notice and wonder about the displays.
* Then complete @printable-exercise{matching-bar-to-pie.adoc}.
}
=== Common Misconceptions

* Pie charts and bar charts can show _counts_ or _percentages_ of categorical data. If there are more people with brown hair than blond hair, for example, a pie chart of hair color will have a larger slice or longer bar for "brown" than for "blond". In Pyret, pie charts show percentages, and bar charts show counts.
* Pie charts have a wedge for each represented category. Unlike in bar charts, empty categories will not be included in a pie chart. 
* The percentages on pie charts will always add to 100%, so if there are 5 subgroups of a population and we're only going to look at data from 2 of the subgroups, it wouldn't make sense to use a pie chart to compare them!
* When comparing bar charts, it is important to read the scales on the y-axes. If the scales do not match, a taller bar may not represent a larger value.
* Bar charts look a lot like another kind of chart - called a "histogram" - which are actually quite different because they display _quantitative_ data, not categorical. This lesson focuses entirely on pie- and bar charts.

=== Synthesize
@teacher{Confirm that students have correctly matched the displays on @printable-exercise{matching-bar-to-pie.adoc}.}

- What did you Notice? What did you Wonder? +
- How is `pie-chart` similar to `bar-chart`? How is it different?
- When would you want to use one chart instead of another?
- What strategies did you use to match the bar charts to the pie charts?
- Which displays do you find it easier to interpret? Why?
- What information is provided in bar charts that is hidden in pie charts? Why might this sometimes be problematic?
[.indentedpara]
_Categories containing 0% of the data aren't represented on a pie chart. If, for example, a sector of the population is unrepresented in positions of power, it's easier to ignore the issue if that population doesn't get represented in the display._

@strategy{
@span{.title}{Optional Extension}

Sometimes we want to visualize data that is _already summarized:_

[.pyret-table,cols="1,1",options="header"]
!===
! Hair Color		! Number of Students
! "Black"			! 5
! "Brown"			! 13
! "Blond"			! 4
! "Red"				! 2
! "Pink"			! 1
!===

In this situation, we want to use the values in the _first_ column for the labels of our pie slices or bars, and the values in the _second_ column for the size. We have contracts for those, too:
@show{(contract 'pie-chart-summarized '((table-name Table) (labels String) (values String)) "Image" )}
@show{(contract 'bar-chart-summarized '((table-name Table) (labels String) (values String)) "Image" )}

Open the @opt-starter-file{hair} to try them out!

}


== Groups and Subgroups @duration{20 minutes}

=== Overview
Students learn how to create __groups within groups__, showing the relative frequency of one variable across values of another variable using stacked and multi bar charts.

=== Launch

@lesson-instruction{Turn to @printable-exercise{intro-stacked-multi.adoc} and complete Part A now.
}

Comparing groups is great, but sometimes we want to compare __sub-groups across groups__. In this example, we want to compare the distribution of sexes across each species.

@lesson-instruction{
* Let's step away from the Animals Dataset for a moment to learn about some new kinds of displays that would make answering questions like these easier to answer by revealing the subgroups in a column. Turn to @printable-exercise{stacked-and-multi-notice.adoc}.
* What do you Notice? What do you Wonder?
}

=== Investigate

Pyret has two functions that let us specify both a group and a subgroup:

@show{(contract 'stacked-bar-chart '((table-name Table) (group String) (subgroup String)) "Image")}

@show{(contract 'multi-bar-chart '((table-name Table) (group String) (subgroup String)) "Image")}

@lesson-instruction{
Complete Part B of @printable-exercise{intro-stacked-multi.adoc}
}

[cols="^1a,^1a", options="header"]
|===
| Stacked Bar Chart
| Multi Bar Chart
| @image{images/stacked-species-sex.png, 300}
| @image{images/multi-species-sex.png, 300}
|===

Stacked Bar Charts (left) put the _totals_ side by side, so it's easy to answer whether there are more dogs than cats in the shelter. But it's a little more difficult to see whether there are more male dogs than female dogs, because the bars are _on top of one another._

Multi Bar Charts (right) put the _subgroups_ side by side, so it's easy to answer whether there are more male dogs than female dogs in the shelter. But it's a little more difficult to see whether there are more dogs than cats, because there aren't any bars showing the totals.

@lesson-point{
Stacked bar charts make it easy to compare _groups_. Multi bar charts make it easy to compare _subgroups_.
}

@lesson-instruction{
Complete @printable-exercise{matching-stacked-to-multi.adoc}
}

=== Synthesize
All of the charts we've looked at in this lesson work with @vocab{categorical data}, showing us the frequency of values in one or two groups.

- What kinds of questions need stacked or multi bar charts, rather than pie or bar charts?
- What kinds of questions are better answered by stacked bar charts?
- What kinds of questions are better answered by multi bar charts?


@strategy{
@span{.title}{Optional Project: Making Infographics}

Infographics are a powerful tool for communicating information, especially when made by people who actually understand how to connect visuals to data in meaningful ways. @opt-project{infographic.adoc, rubric-infographic.adoc} is an opportunity for students to become more flexible math thinkers while tapping into their creativity. This project can be made on the computer or with pencil and paper. 
}

== Additional Exercises

- @opt-printable-exercise{bar-chart-notice.adoc}
- @opt-printable-exercise{pie-chart-notice.adoc}
- If you are looking to offer your students more practice making and interpreting these chart types in Pyret, we have a second teaching dataset on @opt-starter-file{food} for you to work with!


