= Domain and Range

@lesson-description{Students encounter String and Image datatypes and use "contracts" to make sense of the domain and range of functions.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-order-of-operations}
| Lesson Goals
| Students will be able to:

* Demonstrate understanding of @vocab{Domain} and @vocab{Range} and how they relate to @vocab{functions}

| Student-facing Goals
|
* I can identify the domain and range of a function.
* I can identify the data types @vocab{Number}, @vocab{String}, and @vocab{Image}

| Materials
|
@ifproglang{wescheme}{
* Lesson slides template (@link{https://docs.google.com/presentation/d/1-G2RiCc20dGiexnPqIjLDdvPJWeSlBj_bTKEhngmqL0/edit?usp=sharing, Google Slides})
}

@ifproglang{pyret}{
* Lesson slides template (@link{https://docs.google.com/presentation/d/1t765w-UJAHFCzvkE1YRYgHHBQ0MzegUUKKDtkxdY8KI/edit?usp=sharing, Google Slides})
}

* Exploring Image Functions (@workbook-link{pages/exploring-image-functions.adoc, original}, @link{solution-pages/exploring-image-functions.adoc, solutions})

* Domain and Range Frayer Model (@exercise-link{pages/frayer-model.pdf, PDF})

* Reading for Domain and Range (@workbook-link{pages/reading-for-domain-and-range.adoc, original}, @link{solution-pages/reading-for-domain-and-range.adoc, solution})

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|
@ifproglang{wescheme}{
* Functions Review (@link{https://quizizz.com/admin/quiz/5d9919776c6f17001a9dc6a0, Quizizz})
* Domain and Range Review (@link{https://teacher.desmos.com/activitybuilder/custom/5d991ae71172d473178c9816, Desmos Activity})
}

@ifproglang{pyret}{
* Contracts Review #1 (@link{https://quizizz.com/admin/quiz/5d69763f62e850001a0b0433, Quizizz})
}

| Key Points For The Facilitator
|
* Check frequently for understanding of @vocab{data types} and @vocab{contract}s during this lesson and throughout subsequent lessons.

* Students will use their Contracts page frequently, so it should be kept in an accessible, convenient location.
|===

== Warmup

Students should be logged into
@ifproglang{wescheme}{ @link{https://www.wescheme.org, WeScheme     } }
@ifproglang{pyret}{    @link{https://code.pyret.org, code.pyret.org } }
and have their @vocab{Contracts} page ready.

== Contracts @duration{15 minutes}

=== Overview
Students have seen arithmetic operators like `+`,`-`,`*` and `/`, as well as functions for taking the square root or squaring a number. Some of them take one input, and others take two. Remembering all of these can be challenging! This activity introduces the notion of @vocab{Contracts}, which are a simple notation (found in algebra) for keeping track of the set all of possible inputs and outputs for a function.

=== Launch
Functions are a lot like machines: values go in, something happens, and new values come out. Addition, for example, is like a machine that takes in pairs of numbers and produces a sum. Whenever we use any machine, we always think about what goes in and what comes out. A coffee maker takes in coffee beans and water, and produces coffee. A toaster takes in bread and produces toast.

We don't have to know exactly how coffee makers or toasters work in order to _use_ them. All we need to know is what goes in and what comes out!

We use something called a @vocab{Contract} to keep track of what goes in and out of functions. Contracts are like a "cheat sheet" for using functions. Once you know how to read one, you can quickly figure out how to use a function just by looking at its contract!

[.lesson-point]
The Contract for a function has three parts: the Name, the @vocab{Domain}, and the @vocab{Range}

- The Name is simply how we refer to the function: 
@ifproglang{wescheme}{`*`, `+`, `sqrt`, etc.}
@ifproglang{pyret}{`num-sqrt`, `num-sqr`, etc.}
- The @vocab{Domain} tells us what the function "takes in", or _consumes_. These also known as the _arguments_ to the function.
- The @vocab{Range} tells us what the function "gives back", _produces_.

[.lesson-instruction]
@ifproglang{wescheme}{
- Write the contracts for `+`, `-`, `*`, `/`, `sqr`, and `sqrt` into the Contracts page.
}
@ifproglang{pyret}{
- Write the contracts for `num-sqr`, and `num-sqrt` into the Contracts page.
}

[.text-center]
*A Sample Contracts Table*

++++
<style>
.inlineContractTable {width: 60%; margin: auto;}
.inlineContractTable tbody .tableblock{ padding: 0px; margin: 0px; }
</style>
++++

[.inlineContractTable, cols="4,1,10,1,2", options="header", grid="rows"]
|===
| Name 			|	| Domain				|		| Range
@ifproglang{wescheme}{
|`;` `+`		| :	| `Number Number` 		|	->	| `Number`
|`;` `-` 		| :	| `Number Number` 		|	->	| `Number`
|`;` `sqr`		| :	| `Number`  			|	->	| `Number`
|`;` `sqrt`		| :	| `Number` 				|	->	| `Number`
}
@ifproglang{pyret}{
|`#` `+`		| ::| `Number Number` 		|	->	| `Number`
|`#` `-` 		| ::| `Number Number` 		|	->	| `Number`
|`#` `num-sqr`	| ::| `Number`  			|	->	| `Number`
|`#` `num-sqrt`	| ::| `Number` 				|	->	| `Number`
}
|===

[.lesson-instruction]
*Optional:* Have students turn to the @workbook-link{pages/frayer-model.pdf, Domain and Range Frayer model} in their workbooks and use the visual organizer to explain the concepts of domain and range in their own words.

=== Synthesize
Knowing the Domain and Range of our functions also tells us how they can fit together. For example:
@ifproglang{wescheme}{`(sqrt (sqr 16))`}
@ifproglang{pyret}{`num-sqrt(num-sqr(16))`}

We know from it's @vocab{Domain} that the square-root function needs a number. And we know from the square function's @vocab{Range} that it will produce that number. We can be pretty confident that this code will work, even before we run it.

== Exploring Image Functions @duration{25 minutes}

=== Overview
Students explore functions that go beyond numbers, producing all sorts of simple geometric shapes and images in the process. Making images is highly motivating, and encourages students to get better at both reading error messages and persisting in catching bugs.

=== Launch
Students have already seen Number values like Integers, Decimals and Fractions, but computer programs can work with a much larger set of data types. Show students String values, by having them typing various things in quotation marks:

- `"hello"`
- `"many words, one string"`
- `"42"`
- `"1/3"`
- Something students come up with on their own...

[.lesson-point]
A String is anything in quotation marks. _Anything_.
String values evaluate to themselves, the same way Numbers do.

Here are two Circles of Evaluation. One of them is familiar, but the other very different from what students have seen before. Have them identify what looks strange about that circle.

[cols="1,1", grid="none", frame="none"]
|===
| @span{.right}{@show{(sexp->coe `(* 10 -4))}}
|@show{(sexp->coe `(star 50 “solid” “blue”))}
|===

Possible responses:

- We've never seen the function `star` before
- We've never seen Strings used in a Circle of Evaluation before
- We've never seen a function take in three inputs
- We've never seen a function take in a mix of Numbers and Strings

Have students see if they can figure out the Name and @vocab{Domain} for the function in the second Circle. This is a chance to look for and make use of structure in deciphering a novel expression.

- We know the name of the function is `star`, because that's what is at the top of the circle
- We know it has three things in its Domain
- We know the Domain consists of a Number and two Strings

But what about the @vocab{Range}? Have students share some guesses, and then convert the Circle to code and try it out!

- What happened?
- What does the `50` mean to the computer? Try replacing it with different values, and see what you get.
- What does the `"solid"` mean to the computer? Try replacing it with different values, and see what you get.
- What does the `"blue"` mean to the computer? Try replacing it with different values, and see what you get.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Error Messages}

The error messages in this environment are _designed_ to be as student-friendly as possible. Encourage students to read these messages aloud to one another, and ask them what they think the error message _means_. By explicitly drawing their attention to errors, you will be setting them up to be more independent in the next activity!
|===

Suppose we had never seen `star` before. How could we figure out how to use it?

- Have students type `star` into the Interactions Area and hit "Enter". What did they get back? What do they think it means? _Students learn that there is a function called_ `star`.

- If it's a function, we know that it will need an open parentheses and at least one input. Have students try
@ifproglang{wescheme}{
`(star 50)`
}
@ifproglang{pyret}{
`star(50)`
}

- What error did we get? What _hint_ does it give us about how to use this function?

=== Investigate
[.lesson-instruction]
- Have students turn to @workbook-link{pages/exploring-image-functions.adoc, "Exploring Image Functions"}.
- Have students open a new program file and name it "Exploring Images".
@ifproglang{pyret}{
- On Line 1 of the @vocab{Definitions area} (left side), type the words *include image* and press "Run". (This loads the *image* library.)
}

Give students time to investigate image functions and see how many they can discover, using the Contracts page to organize their findings.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Strategies for English Language Learners}

MLR 2 - Collect and Display: As students explore, walk the room and record student language relating to functions, domain, range, contracts, or what they perceive from @vocab{error messages}.  This output can be used for a concept map, which can be updated and built upon, bridging student language with disciplinary language while increasing sense-making.
|===

=== Synthesize
- *What image functions did you and your partner discover?*
``rectangle``, `triangle`, `ellipse`, `circle`, etc.
- *How did you decide what to try?*
- *What error messages did you see?*
_Input mismatches, missing parentheses, etc._
- *How did you figure out what to do after seeing an error message?*
_Read the error message, think about what the computer is trying to tell us, etc._

== Making Sense of Contracts @duration{10 minutes}

=== Overview
This activity digs deeper into Contracts, and has students create their own Contracts trackers to take ownership of the concept and create an artifact they can refer back to.

=== Launch

- `star` has three elements in its Domain: A Number, a String, and another String.  What do these elements represent?
_The Number is the radius, the first String is the style (either `outline` or `solid`), the second String is the color._

- *What happens if I don't give it those things?*
_We won't get the star we want, we'll probably get an error!_

- *If I give `star` what it needs, what do I get in return?*
_An Image of the star that matches the arguments_

- *`square` has the same Domain as `star`.  What do the arguments in `square` represent?*
_length, style, color_

- *Can different functions have the same Domain?  The same Range?  Are they still different functions?*
_Yes, yes, and yes!_

- *Can we up with an example of two math functions that have the same Domain and Range?*

[.lesson-point]
When the input matches what the function consumes, the function produces the output we expect.

*Where else have you heard the word "contract"?  How can you connect that meaning to contracts in programming?*

_An actor signs a contract agreeing to perform in a film in exchange for compensation, a contractor makes an agreement with a homeowner to build or repair something in a set amount of time for compensation, or a parent agrees to pizza for dinner in exchange for the child completing their chores. Similarly, a contract in programming is an *agreement* between what the function is given and what it produces._

@ifproglang{wescheme}{
- *What does the contract for `star` look like?*
`star : Number String String -> Image`
}
@ifproglang{pyret}{
- *What does the contract for `star` look like?*
`star {two-colons} Number, String, String -> Image`
}

=== Investigate
[.lesson-instruction]
- Students complete @workbook-link{pages/reading-for-domain-and-range.adoc, "Domain and Range - Practice"} with their partner.

[.lesson-instruction]
Students create a visual "Contracts page" either digitally or physically.  Ask students to think about how they visualize contracts in their own minds and how they could use that imagery to explain functions and their contracts to others.


== Additional Exercises:

@ifproglang{wescheme}{

- @link{https://quizizz.com/admin/quiz/5cdcb3907f8c98001a203c1b, Bootstrap:Algebra - Contracts, Domain/Range, Data Types, & Functions } (Quizizz)

- @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb288f41b366950eba1e1, Bootstrap:Algebra - Data Types & Circles of Evaluation} (Desmos Activity)

- @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb3f555e3fb606a1f1ba2, Bootstrap:Algebra - Data Types, Circles of Evaluation, and Contracts} (Desmos Activity)

- Converting Circles of Evaluation to Code (1)
(@exercise-link{pages/many-types-coe-to-code1.adoc, original} ,
@exercise-link{solution-pages/many-types-coe-to-code1.adoc, answers})

- Converting Circles of Evaluation to Code (2)
(@exercise-link{pages/many-types-coe-to-code2.adoc, original} ,
@exercise-link{solution-pages/many-types-coe-to-code2.adoc, answers})

- Identifying Parts of Expressions (1)
(@exercise-link{pages/id-expr-pieces1.adoc, original} ,
@exercise-link{solution-pages/id-expr-pieces1.adoc, answers})

- Identifying Parts of Expressions (2)
(@exercise-link{pages/id-expr-pieces2.adoc, original} ,
@exercise-link{solution-pages/id-expr-pieces2.adoc, answers})

- Matching Expressions & Contracts
(@exercise-link{pages/match-contracts-exprs1.adoc, original} ,
@exercise-link{solution-pages/match-contracts-exprs1.adoc, answers})
}
