= Quadratic Models - Sense Making from Vertex Form: @math{f(x) = a(x − h)^2 + k}

The quadratic model we've defined is: @fitb{}{}

It tries to predict @fitbruby{20em}{}{y-variable} from @fitbruby{}{}{x-variable}

== Direction of Opening (@math{a})

Since @math{a} is @fitbruby{8em}{}{negative / positive}, we know that our quadratic model opens @fitbruby{6em}{}{up / down} and the inflection point will be a @fitbruby{}{}{maximum / minimum} 

Because a = @fitb{6em}{}, the graph will be @fitbruby{6em}{}{how many times} @hspace{3em} @fitbruby{6em}{}{steeper / less steep} than the parent function.

== Vertex @math{(h, k)}

Because @math{h =} @fitb{6em}{} and k = @fitb{6em}{}:

- the vertex of the parabola is at (@fitb{6em}{}, @fitb{6em}{}) 
- the @vocab{axis of symmetry} of our parabola will be at @fitbruby{2em}{}{x / y} @math{=} @fitb{6em}{} 

@vspace{1ex}

This means that:

- before @math{x =} @fitb{6em}{}, the @fitbruby{6em}{}{y-variable} @fitbruby{}{}{increases / decreases} 
- when @math{x =} @fitb{6em}{}, the @fitbruby{6em}{}{y-variable} @fitb{}{} 
- after @math{x =} @fitb{6em}{}, the @fitbruby{6em}{}{y-variable} @fitbruby{}{}{increases / decreases} 

== S-value in Context

This model was built using data about 
@fitbruby{6em}{}{how many?}
@fitbruby{}{}{what?} +
whose 
@fitbruby{10em}{}{x-variable} ranged from
@fitbruby{10em}{}{x-min} to
@fitbruby{10em}{}{x-max}
@fitbruby{}{}{x-variable units} 

@vspace{1ex}

Possible limitations of this model include @fitb{}{}
@fitbruby{80em}{}{uneven distribution, high variability, small sample size, etc.}

@vspace{1ex}

*The error in the model* is described by an @vocab{S-value} of about
@fitbruby{5em}{}{S}
@fitbruby{8em}{}{y-units}. @hspace{1em} I
@fitbruby{18em}{}{strongly agree, agree, disagree, strongly disagree} that this model is a good fit considering that
@fitbruby{10em}{}{y-variable units} in this dataset range from
@fitbruby{10em}{}{lowest y-value} to
@fitbruby{}{}{highest y-value}