= Project: Research Capstone

@description{This project can be used as a capstone for Bootstrap: Data Science. It is designed to give students a deep dive into a dataset and use everything they've learned throughout the course, not only about making and interpreting visualizations, but about the practice of refining our questions through the Data Cycle and deciding which visualizations are most useful in telling the data's story.  _This project is an extension of the @lesson-link{project-data-exploration}._ }

@lesson-prereqs{linear-regression, project-data-exploration}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives
@objective{develop-statistical-question}
@objective{sensible-grouped-samples}
- use the Data Cycle _repeatedly_ when answering their research question, with each set of findings leading to new questions
- articulate the series of steps they took with the Data Cycle
- identify threats to validity.

| Student-facing Lesson Goals
|

- Let's investigate our questions to tell the story of our dataset using all of the tools we've learned in Bootstrap:Data Science.

| Materials
|[.materials-links]

@material-links

| Preparation
|
@preparation{
- Prior to launching this project, you'll want to consider your project timeline. _This capstone project is designed to span several days or weeks!_
- Consider checkpoints to make sure students are on track, and to identify bottlenecks or problems early:
  * Will you check progress intermittently?
  * Will students submit a rough draft before they submit a final draft?
  * If you're having students do both the slides _and_ a written paper, do they have separate deadlines?
  * Will students present their projects to the class on a certain date?
- Teachers are welcome and encouraged to edit and adapt the @starter-file{research-paper} and @starter-file{research-project}, as well as the student-facing @handout{research-project-rubric.adoc, Project Overview Rubric} and @handout{research-project-rubric-visualizations.adoc, Visualizations Rubric}, for their unique classroom context.
- We recommend distributing rubrics at the outset to help students understand the scope of the project -- and your expectations -- at the outset.
}

| Key Points for the Facilitator
|
- This project builds on our @lesson-link{project-data-exploration} (in which students practice making visualizations from a real world dataset, develop familiarity with that dataset and generate a list of questions about the dataset), but is much more rigorous, pushing students to decide which of the visualizations they are able to make actually tell interesting stories and which grouped samples need to be made in order to dig into answering their most interesting questions.
- This project can be framed to address _domain-specific learning goals_ that are appropriate for your classroom. For example, students in a Physics class might write their paper about data they collected from an experiment.

|===

== Dataset Research Project

=== Overview

In this capstone project, students use the data cycle to ask questions, consider, analyze, and interpret their dataset.  Building on preliminary work for @lesson-link{project-data-exploration}, students dig deeper into their questions, selecting relevant visualizations and making more to craft a compelling data story.

@strategy{What's the Finished Product?}{

Students can create a formal research paper, a slide deck or both! We've created a @starter-file{research-project, "slide template"} and a @starter-file{research-paper, "paper template"} to help scaffold these products.

Note: Many teachers have students create the slide deck first, as it offers more scaffolding and allows students to present their findings and get feedback, _before_ writing a formal research paper.
}

=== Launch

Choosing a *good research question* is the first step toward a successful research project! 

Your question should produce new insights and rich discussion -- that means it can't be too vague, too broad, or too specific!

@lesson-instruction{
- Take a minute to look at the questions you developed in your @lesson-link{project-data-exploration} and identify a few that you think could be answered using your dataset and might be interesting to pursue further. 
  * Perhaps you have a broad question that could be clarified through a list of subquestions? 
  * Or perhaps you notice that you have several questions that could support exploration of an overarching question?
- Share and discuss your questions with your partner or small group.
  * Which of your questions do they find most compelling?
  * What subquestions would you want to explore for each of your questions?
  * Can all of your questions actually be answered using the data available in your dataset?
- It's ok to improve upon one of your questions or develop a new question about your dataset that wasn't on the original list!
}

@teacher{
Some students will likely be confident in their question(s), while others will need to revise and rethink their question(s). This discussion is intended to be an open conversation, allowing students the opportunity to pick the best question for them.

Students who need more scaffolding may benefit from comparing the data work they are about to embark on to the structure of a 5-paragraph essay, with an introduction and conclusion sandwiching three supporting paragraphs, each of which has its own topic sentence.

Applied to Data Science, they will want an overarching question that can be explored through a collection of sub-questions, which might look like something like the following: 

- Overarching Question: What factors best predict the number of weeks animals spend at the shelter?
- Subquestions:
  * How does an animal's species effect adoption time?
  * How does an animal's weight effect adoption time?
  * How does an animal's sex effect adoption time?
  * How does an animal's age effect adoption time?
- Conclusion: In general animals spend between @fitb{1em}{} and @fitb{1em}{} weeks at the shelter before being adopted. @fitb{1em}{} doesn't appear to have any impact on adoption time, while @fitb{1em}{} seems to dramatically lengthen/shorten the number of weeks to adoption. Animals who are @fitb{1em}{} and @fitb{1em}{} are most likely to be adopted quickly. And animals who are @fitb{1em}{} and @fitb{1em}{} seem to be adopted slowly.

Another example of an overarching question we could ask about the animals might be: 

- "Does gender bias impact which animals are fixed?"
}


=== Investigate

Let's make sure the research task is clear before we dig in.

@teacher{
If you are also requiring students to submit a written research report, we recommend introducing this component _after_ students have completed and submitted their slide decks. When introducing the @starter-file{research-project}, you can share the @starter-file{research-paper} with students, so they know what to expect when it's time to write up their findings.
}

@lesson-instruction{
- There are *four* sections of the @starter-file{research-project}: 
  * (1) About this Dataset -- you can reuse what you wrote for your @lesson-link{project-data-exploration} and improve upon it, if necessary.
  * (2) Research Questions -- you just came up with these!
  * (3) Analysis -- This is where the bulk of your work will happen. In telling your data story, you can reuse visualizations from the exploration project... but some will likely not be worth including! And you will likely need to make more visualizations in order to tell the best story you can.  Plan to include a wide array of visualizations to tell your story, although there is no requirement to include each type of display.
  * (4) Discussion -- This is where you'll summarize your findings, address threats to validity and ethical implications, and identify questions for future study.
- You will be assessed on your work using this rubric: @handout{research-project-rubric.adoc, page 1} and @handout{research-project-rubric-visualizations.adoc, page 2}
- Take a few minutes to read through the slide deck and the rubrics in parallel and identify any questions you may have about what you're being asked to do.  You may want to use a highlighter to identify anything that seems especially important on the rubric.
}

@teacher{Teachers: It is up to you how much work students do at home versus in class. Providing work time during class is beneficial because it encourages students to ask questions and collaborate with peers.

Pacing of this project will vary from classroom to classroom. Some students will need more structure and deadlines from you, while others will thrive with individual freedom. Do what works best for your students -- but have a clear idea of how much time will be needed for your students to meet your expectations. Share any pertinent deadlines, for check-ins, status updates, submission dates for drafts, slides, papers and/or presentations, etc.
}

@lesson-instruction{
- Whereas the focus of the @lesson-link{project-data-exploration} was to keep a record of your explorations, the goal of this project is to produce a polished final product that tells a compelling data story.  
- Just as with any polished paper, you should expect it to take several drafts to arrive at the final product. 
- When you are finished with your first draft, use the rubrics to self-assess and revise your work. 
  * This will likely involve editing, deleting and adding to what you've written to come up with a more polished product. 
  * Some of your edits may focus on the text you've written.
  * Some of your edits may focus on refining the visualizations, by editing titles or making additional visualizations for the purpose of comparison.
- You are also welcome to customize your slides, add graphics, and beautify the slide deck template!
}

=== Synthesize

- Peer review is a powerful tool if time allows, and, ideally, it would be followed by a round of revisions.
- Celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.



