= Project: Write a Research Paper

@description{This project can be used as the capstone for Bootstrap:Data Science, and is designed to provide real-world and engaging connections to the following a wide variety of math, computing, and data science.}

@lesson-prereqs{choosing-your-dataset}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* use the Data Cycle to develop new questions from the findings their initial questions lead them to.
* identify and explore grouped samples from within their dataset.
* identify threats to validity.

| Student-facing Lesson Goals
|

* Let's use data to answer a question.

| Materials
|[.materials-links]

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
|
* This project an extension of @lesson-link{project-data-exploration}. In @lesson-link{project-data-exploration}, students gain familiarity with a dataset. In this project, students respond to that question by analyzing statistics and displays. We encourage you to modify @starter-file{research-paper} to meet your students needs.
* This project can also address _domain-specific learning goals_ that are appropriate for your classroom. For example, students in a Physics class might write their paper about data they collected from an experiment.


|===

== Dataset Research Project  @duration{flexible}

=== Overview

In this capstone project, students respond to a chosen question about their dataset. They use the data cycle to ask questions, consider, analyze, and interpret their data. They apply

Prior to embarking on this project, students should complete @lesson-link{project-data-exploration}, where they gain familiarity with a dataset and consider worthwhile questions to investigate.

=== Launch

Data Science is the process of learning from data. Any learning that _you_ do from _your_ data needs to be motivated by a *good question* - one that will produce new insights and rich discussion. That means it can't be too vague, too broad, or too specific!

[.lesson-instruction]
- While working on @starter{project-data-exploration}, you honed in on a few questions worth further investigation.
- In small groups, share and discuss the questions you've landed on. Let your peers share their gut reactions to your questions. Talk to your partners about advantages and disadvantages to pursuing various questions.

@teacher{Some students will likely be confident in their questions, while others will need to revise and rethink their questions. This discussion is intended to be an open conversation, allowing students the opportunity to pick the best question for them. Choosing an appropriate question is the first step toward a successful research project!}

=== Investigate

[.lesson-instruction]
- We are going to spend a lot of class time working on our research projects.
** _It is up to you how much work students do at home versus in class. Providing work time during class is of tremendous benefit to students so that they have space to ask questions and collaborate with peers._
- To ensure that everyone completes the project, there are some intermittent deadlines you should know about.
** Share with student any pertinant deadlines, e.g.: Will you check  progress intermittently? Will students submit a rough draft before the submit a final draft? Is there a deadline for the slides, and another deadline for the paper (if you are opting to do both}? Will students present their projects to the class on a certain date?_

@teacher{We recommend printing and distributing the student-facing rubric to help students understand the scope of the project and your expectations at the outset.

The next set of lesson instructions involves a walk-through of the slide deck template, with periodic discussion the relevant rubric rows. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context.}

[.lesson-instruction]
- To give you a sense of *what* you will be creating, let's preview the Research Project slide deck template.
- Take out your rubric! As we move through the template, ask questions about the rubric descriptors if they are unclear or confusing to you!
- There are *four* sections of the project: (1) About this Dataset, (2) Research Questions, (3) Analysis, and (4) Discussion.

@teacher{Walk students through sections 1 and 2, inviting questions and conversation along the way.}

[.lesson-instruction]
- The bulk of your analysis will happen in the third section of the template - which is where you tell your "data story".
- In telling your data story, you can use displays from your exploration paper... but some will likely not be very interesting!
- You will likely need to make more displays in order to tell the best story that you can!
- The template includes every single type of graph that we made during our Data Exploration Project. Some displays will be relevant to answering your research question, and some may not be. Plan to include a wide array of charts and displays to tell your story.


=== Synthesize

* Invite students to customize their slides, add graphics, and beautify their slide decks.

* Encourage students to self-assess and revise their work. Peer review is a powerful tool if time allows!

* Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.



