= Project: Create a Research Project

@description{This project can be used as the capstone for Bootstrap:Data Science, and is designed to provide real-world and engaging connections to math, computing, and data science.}

@lesson-prereqs{project-data-exploration}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* develop a research question about a real-world dataset
* use the Data Cycle _repeatedly_ when answering their research question, with each set of findings leading to new questions
* articulate the series of steps they took with the Data Cycle
* identify and explore grouped samples from within their dataset
* identify threats to validity.

| Student-facing Lesson Goals
|

* Let's use data to answer a question.

| Materials
|[.materials-links]

@material-links

| Supplemental Materials
|[.material-links]
@opt-material-links

| Preparation
|
* Prior to launching this project, you'll want to consider your project timeline. _This capstone project is designed to span several days or weeks!_
* Consider checkpoints to make sure students are on track, and to identify bottlenecks or problems early:
** Will you check progress intermittently?
** Will students submit a rough draft before they submit a final draft?
** If you're having students do both the slides _and_ a written paper, do they have separate deadlines?
** Will students present their projects to the class on a certain date?
* We encourage you to modify the @starter-file{research-paper} to meet your students' needs.

| Key Points for the Facilitator
|
* This project an extension of @lesson-link{project-data-exploration}, where students gain familiarity with a dataset brainstorm interesting questions to study. In this project, students respond to one question (or possibly 2-3) by analyzing statistics and displays.
* This project can also address _domain-specific learning goals_ that are appropriate for your classroom. For example, students in a Physics class might write their paper about data they collected from an experiment.


|===

== Dataset Research Project  @duration{flexible}

=== Overview

In this capstone project, students investigate a dataset to answer to a chosen question about that dataset. They use the data cycle to ask questions, consider, analyze, and interpret their data.

Prior to embarking on this project, students should complete @lesson-link{project-data-exploration}, where they gain familiarity with a dataset and consider worthwhile questions to investigate.

@strategy{
@span{.title}{What's the Finished Product?}

Students can create a formal research paper, a slide deck or both! We've created a @starter-file{research-project, "slide template"} and a @starter-file{research-paper, "paper template"} to help scaffold these products.

Note: Many teachers have students create the slide deck first, as it offers more scaffolding and allows students to present their findings and get feedback, _before_ writing a formal research paper.
}

=== Launch

Data Science is the process of learning from data. Any learning that _you_ do from _your_ data needs to be motivated by a *good question* - one that will produce new insights and rich discussion. That means it can't be too vague, too broad, or too specific!

@lesson-instruction{
- While working on your Data Exploration, you honed in on a few questions worth further investigation.
- In small groups, share and discuss the questions that you found most interesting. Let your peers share their gut reactions to your questions, then discuss the advantages and disadvantages of pursuing each question.
}

@teacher{Choosing an appropriate question is the first step toward a successful research project! Some students will likely be confident in their question(s), while others will need to revise and rethink their question(s). This discussion is intended to be an open conversation, allowing students the opportunity to pick the best question for them.}

=== Investigate

We are going to spend a lot of class time working on our research projects.

@teacher{
It is up to you how much work students do at home versus in class. Providing work time during class is beneficial because it encourages students to ask questions and collaborate with peers.

Share any pertinent deadlines, for check-ins, status updates, submission dates for drafts, slides, papers and/or presentations, etc.

Pacing of this project will vary from classroom to classroom. Some students will need more structure and deadlines from you, while others will thrive with individual freedom. Do what works best for your students - but have a clear idea of how much time will be needed for your students to meet your expectations.

We recommend printing and distributing the @handout{research-project-rubric.adoc, "student-facing rubric"} to help students understand the scope of the project and your expectations at the outset.

The next set of lesson instructions involves a walk-through of the slide deck template, with interwoven discussion the relevant rubric rows. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context.
}

@lesson-instruction{
- Let's preview the @starter-file{research-project} to give you a sense of *what* you will be creating.
- But first, take out @opt-printable-exercise{research-project-rubric.adoc, "both"} @opt-printable-exercise{research-project-rubric-2.adoc, "pages"} of your rubric.
- As we move through the template, ask questions about the rubric descriptors if they are unclear or confusing to you. Use a highlighter to indicate if anything seems especially important on the rubric.
- There are *four* sections of the project: (1) About this Dataset, (2) Research Questions, (3) Analysis, and (4) Discussion.
- Let's talk through the first two sections together.
}

@teacher{Walk students through sections 1 and 2 of the @starter-file{research-project}, inviting questions and conversation along the way. We've offered some talking points for Sections 3 and 4, as the bulk of student work takes place there.}


The bulk of your analysis will happen in the third section of the template - which is where you tell your data story. In telling your data story, you can use displays from your exploration paper... but some will likely not be worth including! You will likely need to make more displays in order to tell the best story that you can.

The @starter-file{research-project} includes every single type of graph that we made during the Data Exploration. You should use the ones that are relevant to answering your research question - you may not need all of them! Plan to include a wide array of charts and displays to tell your story. You are not required to include each type of display.

@teacher{If you are also requiring students to submit a written research report, we recommend introducing this component _after_ students have completed and submitted their slide decks. When introducing the @starter-file{research-project}, you can share with students @starter-file{research-paper}, so they know what to expect when it's time to write up their findings.}

=== Synthesize

* Invite students to customize their slides, add graphics, and beautify their slide decks.

* Encourage students to self-assess and revise their work. Peer review is a powerful tool if time allows!

* Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.



