= Project: Write a Research Paper

@description{This project can be used as the capstone for Bootstrap:Data Science, and is designed to provide real-world and engaging connections to the following a wide variety of math, computing, and data science.}

@lesson-prereqs{choosing-your-dataset}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* use the Data Cycle to develop new questions from the findings their initial questions lead them to.
* identify and explore grouped samples from within their dataset.
* identify threats to validity.

| Student-facing Lesson Goals
|

* Let's use data to answer a question.

| Materials
|[.materials-links]

@material-links

| Preparation
|
* This project an extension of @lesson-link{project-data-exploration}. In @lesson-link{project-data-exploration}, students gain familiarity with a dataset. In this project, students respond to that question by analyzing statistics and displays. We encourage you to modify @starter-file{research-project} to meet your students needs.
* This project can also address _domain-specific learning goals_ that are appropriate for your classroom. For example, students in a Physics class might write their paper about data they collected from an experiment.


|===

== Dataset Exploration Project  @duration{flexible}

=== Overview

In this capstone project, students respond to a chosen question about their chosen dataset. They use the data cycle to ask questions, consider, analyze, and interpret their data. They apply

Prior to embarking on this project, students should complete @lesson-link{project-data-exploration}, where they gain familiarity with a dataset and consider worthwhile questions to investigate.

=== Launch




We recommend printing and distributing both @opt-printable-exercise{exploration-paper-rubric.adoc, "page 1"} and @opt-printable-exercise{exploration-paper-rubric-2.adoc, "page 2"} of the student-facing rubric to help students understand the scope of the project and your expectations at the outset. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context.

=== Investigate


=== Synthesize

* Invite students to customize their slides, add graphics, and beautify their slide decks.

* Encourage students to self-assess and revise their work. Peer review is a powerful tool if time allows! The rubric (both @opt-printable-exercise{exploration-paper-rubric.adoc, "page 1"} and @opt-printable-exercise{exploration-paper-rubric-2.adoc, "page 2"}) is a useful resource for facilitating self and peer review.

* Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.






Many Bootstrap teachers arrange publishing parties or data fairs, complete with tri-fold posters explaining their findings.

=== Students will be able to...

* Use the Data Cycle to develop new questions from the findings their initial questions lead them to
* Identify and explore grouped samples from within their dataset
* Identify Threats to Validity

=== Assessment and Grading
We provide a student-facing @opt-printable-exercise{research-paper-rubric.html, rubric for the paper}, but teachers should always feel free to edit and adapt it for their classroom.
