= Project: Write a Research Paper

++++
<style>
h3 { margin-top: 3ex; }
.autonum:after { content: '.'; }
th { text-align: center !important; }
table * { line-height: 1.2rem; }
.ulist p { margin: 0; }
</style>
++++

@description{Students come up with an original research question, conduct the analysis to find results, and share their findings.}

@lesson-prereqs{ds-intro, simple-data-types, contracts, bar-and-pie-charts, data-cycle, probability-inference, choosing-your-dataset, histograms, visualizing-the-shape-of-data, measures-of-center, box-plots, standard-deviation, scatter-plots, ethics-privacy-and-bias}

== Overview

This project can be used as the capstone for Bootstrap:Data Science, and is designed to provide real-world and engaging connections to the following math, computing, and data science concepts:

[cols="1a,1a", grid="none", frame="none"]
|===
|
- Bar and Pie Charts
- Histograms and Box Plots
- Skew and Symmetry
- Measures of Center & Spread
- Strength and Direction of Correlations
- Linear Regression
- Random and Grouped Sampling

|
- Outliers and Extreme Values
- Data Types and Representations of Data
- Functions and Variables
- Looping and Iteration
- Sorting, Filtering and Transforming Tables
- Importing Data
- Ethics, Privacy and Bias
|===

In addition, this project can address _domain-specific learning goals_ that are appropriate for your classroom. For example, students in a Physics class, might write their paper about data they collected from an experiment.

Many Bootstrap teachers arrange publishing parties or data fairs, complete with tri-fold posters explaining their findings.

=== Students will be able to...

* Use the Data Cycle to develop new questions from the findings their initial questions lead them to
* Identify and explore grouped samples from within their dataset
* Identify Threats to Validity

=== Assessment and Grading
We provide a student-facing @opt-printable-exercise{research-paper-rubric.html, rubric for the paper}, but teachers should always feel free to edit and adapt it for their classroom.


== Where Does it Fit?

The project is constructed over a series of lessons, which reinforce concepts learned in earlier lessons. Taken together, these lessons form the scope and sequence for the project. There are two options for implementation:

[.implementation-options, cols="1a,1a", options="header"]
|===
| Integrated
| All at Once

| The default lesson order for Bootstrap:Data Science has paper-focused lessons sprinkled throughout the curriculum, with students writing sections of their paper throughout the course sequence.

@vspace{1ex}

*Pros:* (1) Breaking a long paper down into pieces can be less intimidating for students, (2) provides more opportunities for formative assessment and revision, and (3) students get a learning-applying-writing cycle for each concept.

*Cons:* Some students may lose interest in the research paper after such a long time. Harder for the project to serve as a summative assessment.

| Students can go through the earlier lessons without worrying about the paper at all, focusing purely on the computing and math content. At the end of the year (for example), they shift gears to focus on writing.

@vspace{1ex}

*Pros:* (1) Satisfying "captsone" for students, (2) terrific summative assessment, (3) easier to focus on statistical writing without switching back and forth to math/code.

*Cons:* Without a narrative project to tie everything together, students are less likely to see the "big picture" throughout the year.
|===


