= Interpreting Models
++++
<style>
.studentAnswerMedium { min-width: 8em !important; }
td { padding: 0 !important; }
</style>
++++

For this page, you'll need to the @online-exercise{https://code.pyret.org/editor#share=10bWYM4rOq_ZshtX6_M-xf-bPbfz61rd1, State Demographics Starter File} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you.

**We started with a model based on Alabama and Alaska. We can interpret the slope and @math{R^2} value below:**

__The @fitbruby{20em}{Alabama-Alaska}{sensible name} model predicts that a 1 @fitbruby{10em}{percent}{[x-axis units]} increase in @fitbruby{20em}{percent college degrees}{[x-axis]} is associated with a @fitbruby{15em}{5613 dollar}{[slope, y-units]} @fitbruby{10em}{@ifsoln{increase}}{increase / decrease} in @fitbruby{20em}{median household income}{[y-axis]}. Based on the @math{R^2} of @fitbruby{10em}{-15.63}{R^2^ value}, this model fits @fitbruby{15em}{really, really poorly}{really well, decently, poorly, etc.}.__

@n Describe the optimal model YOU created via linear regression:

__The @fitbruby{20em}{linear-regression}{sensible name} model predicts that a 1 @fitbruby{10em}{percent}{[x-axis units]} increase in @fitbruby{20em}{percent college degrees}{[x-axis]} is associated with a @fitbruby{15em}{@ifsoln{1142 dollar}}{[slope, y-units]} @fitbruby{10em}{@ifsoln{increase}}{increase / decrease} in @fitbruby{20em}{median household income}{[y-axis]}. With an @math{R^2} of @fitbruby{10em}{@ifsoln{.585}}{R^2^ value}, this model fits @fitbruby{15em}{@ifsoln{pretty well}}{really well, decently, poorly, etc.}.__

@vspace{5ex}
@span{.sectionbreak}{}
@vspace{1ex}

@n Describe another model you created:

__The @fitbruby{20em}{}{sensible name} model predicts that a 1 @fitbruby{10em}{@ifsoln{percent}}{[x-axis units]} increase in @fitbruby{20em}{@ifsoln{percent college degrees}}{[x-axis]} is associated with a @fitbruby{15em}{@ifsoln{1142 dollar}}{[slope, y-units]} @fitbruby{10em}{@ifsoln{increase}}{increase / decrease} in @fitbruby{20em}{@ifsoln{median household income}}{[y-axis]}. With an @math{R^2} of @fitbruby{10em}{}{R^2^ value}, model fits @fitbruby{15em}{}{really well, decently, poorly, etc.}.__

@vspace{5ex}
@span{.sectionbreak}{}
@vspace{1ex}

If you explored other models, write up your findings using the templates below:

a. __The @fitbruby{20em}{}{sensible name} model predicts that a 1 @fitbruby{10em}{}{[x-axis units]} increase in @fitbruby{20em}{}{[x-axis]} is associated with a @fitbruby{15em}{}{[slope, y-units]} @fitbruby{10em}{}{increase / decrease} in @fitbruby{20em}{}{[y-axis]}. With an @math{R^2} of @fitbruby{10em}{}{R^2^ value}, this model fits @fitbruby{15em}{}{really well, decently, poorly, etc.}.__

b. __The @fitbruby{20em}{}{sensible name} model predicts that a 1 @fitbruby{10em}{}{[x-axis units]} increase in @fitbruby{20em}{}{[x-axis]} is associated with a @fitbruby{15em}{}{[slope, y-units]} @fitbruby{10em}{}{increase / decrease} in @fitbruby{20em}{}{[y-axis]}. With an @math{R^2} of @fitbruby{10em}{}{R^2^ value}, this model fits @fitbruby{15em}{}{really well, decently, poorly, etc.}.__
