= Modeling College Degrees v. Income
++++
<style>
.studentAnswerMedium { min-width: 10em !important; }
td { padding: 0 !important; }
</style>
++++

For this page, you'll need to the @online-exercise{https://code.pyret.org/editor#share=10bWYM4rOq_ZshtX6_M-xf-bPbfz61rd1, State Demographics Starter File} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you.

@n Make a scatter plot showing the relationship between `college-or-higher` and `median-household-income`. Let's estimate a linear model for this data!

@n Find the rows for Alabama and Alaska, and record their x- and y- values below:

[cols="^1a, ^1a", options="header"]
|===
| Alabama
| Alaska
| @fitbruby{10em}{@ifsoln{22.6}}{college-or-higher}, @fitbruby{10em}{@ifsoln{43253}}{median-household-income}
| @fitbruby{10em}{@ifsoln{27.5}}{college-or-higher}, @fitbruby{10em}{@ifsoln{70760}}{median-household-income}
|===

@n Using the two points above, define your linear model by filling in the blanks in the table below.

[cols="^1a, ^1a", options="header"]
|===
| Function Notation
| Pyret Notation
| @math{f(x) =} @fitb{10em}{@ifsoln{@math{5613.67}}}x + @fitb{10em}{@ifsoln{-83613}}
| @show{(code '(define (f x) (+ (* (?ANS 5613.76) x) (?ANS -83613))))}
|===

@n Type it into the Definitions Area on the left, and click "Run". Make sure you fix any errors or warnings. In the Interactions Area, make sure `f(22.6)` and `f(27.5)` predict the correct median income for Alabama and Alaska!

@n Try plugging in different `college-or-higher` values from _other_ states, to see how well a model based only on Alabama and Alaska fits the country.

@vspace{1ex}

**In Pyret, we can graph that function on top of the scatter plot using the `fit-model` function.** Find this function in your Contracts page!

@n What is the fifth argument in the Domain? @fitb{}{}

@n How do you think `fit-model` will use this argument? @fitb{}{}

@fitb{}{}

@n Type `fit-model(states-table, "state", "college-or-higher", "median-household-income", f)` into the Interactions Area, to see how well the model fits. Find Alaska and Alabama in the plot, then discuss the resulting display with someone else.

@n How closely does your model fit the data? Could a different line be closer to more of the points? Try changing the slope and y-intercept of your model to get a better fit, then write down the best model you came up with:

@math{f(x) =} @fitbruby{15em}{}{Slope}@math{x} @hspace{2em} @math{+} @hspace{2em} @fitbruby{15em}{}{y-intercept}

@n What do you think R-squared tells us? @fitb{}{}

@star **What does this model actually mean? Try completing the sentence below:**

__This model predicts that a 1 @fitbruby{10em}{percent}{[x-axis units]} increase in @fitbruby{20em}{college degrees}{[x-axis]} is associated with a @fitbruby{20em}{@ifsoln{$5613}}{[slope, y-units]} @fitbruby{10em}{increase}{increase / decrease} in @fitbruby{20em}{@ifsoln{median household income}}{[y-axis]}. Based on the @math{R^2} of @fitbruby{10em}{}{@math{R^2 value}}, I would say this model fits @fitbruby{30em}{}{real well / not great / poorly / terribly}.__

