[[questions]]
type = "ShortAnswer"
# The prompt we want to use (can be a multi-line string!)
prompt.prompt = """
The chart on the left shows some restaurant data. Describe the relationship between dollars spent and dollars tipped.
"""

prompt.image = "restaurant-lr-plot.png"

# This will add an extra string of text at the bottom of the question.
# Some questions might need some extra explanation
context = """
"""
