= Slope & y-Intercept from Tables (Intro)

++++
<style>
.sideways-pyret-table td { text-align: center; }
</style>
++++

[.center]
--
*slope (rate)*: _how much y changes as x-increases by 1_

*y-intercept*: _the y-value when @math{x = 0}_
--

[.sideways-pyret-table]
|===

| x | -1 | 0 | 1 | 2 | 3 | 4
| y | -1 | 1 | 3 | 5 | 7 | 9
|===

@n Compute the slope: @fitb{}{@ifsoln{2}}

@n Compute the y-intercept:  @fitb{}{@ifsoln{1}}

@n What strategies did you use to compute the slope and y-intercept?

@fitb{}{}

@fitb{}{}

@vspace{8ex}

The slope and y-intercept in this table are harder to find, because the x-values don't go up by 1 and we can't see a value for @math{x = 0}. *Try filling in the points that have been skipped to compute the slope and y-intercept.*

[.sideways-pyret-table]
|===

| x |  2 | 5 | 8  | 11
| y |  3 | 9 | 15 | 21
|===

@n Compute the slope: @fitb{}{2}

@n Compute the y-intercept: @fitb{}{@ifsoln{-1}}

@vspace{8ex}

The slope and y-intercept in this table are even harder to find, because the x-values are out of order!

*Calculate the slope and y-intercept from _any_ two points!* Be sure to show your work.

[.sideways-pyret-table]
|===

| x | 3 | 20 | 5  |  9 | 1
| y | 5 | 56 | 11 | 23 | -1
|===

@n Compute the slope: @fitb{}{@ifsoln{3}}

@n Compute the y-intercept: @fitb{}{@ifsoln{-4}}

