= Slope & y-Intercept from Tables (Practice)

++++
<style>
.sideways-pyret-table { margin-top: 3ex; }
.sideways-pyret-table td { text-alignment: center; }
.autonum { padding-top: 0 !important; }
</style>
++++

[.sideways-pyret-table]
|===
| x | -1 | 0 | 1 | 2 | 3  | 4
| y | -1 | 2 | 5 | 8 | 11 | 14
|===

@n slope: @fitb{20em}{@ifsoln{3}} {nbsp} y-intercept: @fitb{20em}{@ifsoln{2}}

[.sideways-pyret-table]
|===
| x | -2  | -1 | 0 | 1  | 2  | 3  
| y | 17  | 11 | 5 | -1 | -7 | -13
|===

@n slope: @fitb{20em}{@ifsoln{-6}} {nbsp} y-intercept: @fitb{20em}{@ifsoln{5}}


[.sideways-pyret-table]
|===
| x | -3 | -2   | -1 | 0   | 1 | 2   
| y | 0  |@math{{2}\over{3}} | 1@math{{1}\over{3}} | 2 | 2@math{{2}\over{3}} | 3@math{{1}\over{3}} 
|===

@n slope: @fitb{20em}{@ifsoln{@math{\frac{2}{3}}}} {nbsp} y-intercept: @fitb{20em}{@ifsoln{2}}

[.sideways-pyret-table]
|===
| x | -1 | 0  | 1 | 2 | 3 | 4
| y | -7 | -3 | 1 | 5 | 9 | 13
|===

@n slope: @fitb{20em}{@ifsoln{4}} {nbsp} y-intercept: @fitb{20em}{@ifsoln{-3}}

[.sideways-pyret-table]
|===
| x | -5 |  -4 | -3 |  -2 | -1 |   0
| y |  1 | 2.5 |  4 | 5.5 |  7 | 8.5
|===

@n slope: @fitb{20em}{@ifsoln{1.5}} {nbsp} y-intercept: @fitb{20em}{@ifsoln{8.5}}


[.sideways-pyret-table]
|===
| x | -4 | -3   |- 2  | -1  | 0   | 1   
| y | 0  | 0.6  | 1.2 | 1.8 | 2.4 | 3
|===

@n slope: @fitb{20em}{@ifsoln{0.6 or @math{\frac{3}{5}}}} {nbsp} y-intercept: @fitb{20em}{@ifsoln{2.4}}
@teacher{The table above lends itself to previewing that we can find the slope from any 2 points. Ask: How are the first and last points connected to @math{\frac{3}{5}}?}

[.sideways-pyret-table]
|===
| x | 1 | 2  | 3  |  4  |  5 |  6
| y | 5 | 3  | 1  | -1  | -3 | -5
|===

@n slope: @fitb{20em}{@ifsoln{-2}} {nbsp} y-intercept: @fitb{20em}{@ifsoln{7}}

[.sideways-pyret-table]
|===

| x | -4 | -2 | 0 |  2 |  4 |  6
| y |  0 |  4 | 8 | 12 | 16 | 20
|===

@star slope: @fitb{20em}{@ifsoln{2}} {nbsp} y-intercept: @fitb{20em}{@ifsoln{8}}
