= Standard Deviation

@description{Students learn how standard deviation serves as Data Scientists' most common measure of "spread": how far all the values in a dataset tend to be from their mean. When we looked at box plots, we visualized spread based on range and interquartile range. Now we'll return to histograms and picture the spread in terms of standard deviation.}

@lesson-prereqs{box-plots}

@keywords{Standard Deviation, StdDev}
@add-to-lang{st-dev}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

- apply one approach to measuring and displaying spread of a dataset
- compare and contrast information displayed in a box plot and a histogram

| Student-facing Lesson Goals
|

* Let’s compare different uses for box plots and histograms when talking about data.

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
| All students should log into @starter-file{program-list} and open their saved "Animals Starter File". If they don't have the file, they can open a new one from @starter-file{animals}.


|===

== Measuring "Deviance" @duration{30 minutes}

=== Overview
Students review the notion of @vocab{spread} itself, and build up to the formula by annotating @vocab{histograms}.

=== Launch
**The Animal Shelter Bureau reports that the @vocab{mean} age of shelter cats is 3 years.**

@QandA{
Take a look at the The Animals Dataset on @link{https://docs.google.com/spreadsheets/d/1VeR2_bhpLvnRUZslmCAcSRKfZWs_5RNVujtZgEl6umA/edit, the spreadsheet} or on @printable-exercise{ds-intro/pages/animals-dataset.adoc, this page} (for those using a printed workbook, you'll find it at the front).
@Q{Does a mean age of 3 years translate to all of the cats being close to 3 years old? Why or why not?}
@A{No, we cannot assume all cats are close to 3 years old. There are some outliers in the dataset.}
}

@teacher{In the activity that follows, students will look at ten cats from the shelter to consider the distribution of their ages.}

@QandA{
Turn to @printable-exercise{computing-stdev.adoc}, and complete numbers 1-3.
@Q{What did you get for the mean? Does it match what the Animal Shelter Bureau says?}
@A{The mean is 3; yes, it matches what the Animal Shelter Bureau says.}
@Q{Can you think of four ages, such that the mean age for all of them is 3?}
@A{Some possibilities include: {3,3,3,3}, {1,2,4,5}, {1,1,4,6}... any four ages that add up to 12 will work!}
@Q{Can you think of a _different_ spread of four ages that would have the same mean?}
@A{See above.}
@Q{How many different sets of four ages can you think of, which all have a mean of 3?}
@A{See above.}
}

Without a measure of @vocab{spread}, just knowing the mean doesn't tell us enough about the shape of the data.

When summarizing a column, we'd like to use a measure that gathers data from every value. We already have one method of measuring spread: calculating the Five Number Summary and using it to generate a box-plot.

Unfortunately, that measure comes from only a small number of data points! If possible, we'd like to have a measure that summarizes the spread across _all_ the points.

@lesson-point{
@vocab{Standard deviation} is the most useful way to summarize @vocab{spread} of a quantitative column.
}

Instead of focusing on the handful of data points used in our Five Number Summary, another way to measure spread is to focus on _the "typical" distance from the mean_. In other words, we want to know what kind of deviation is "standard" for all the points.

=== Investigate

@right{@image{images/histogram-w-mean.png, 450}} We could imagine a shelter where every cat is between 2 and 4, so *each cat only deviates from the mean by 1 year*! But we could also imagine a shelter with only kittens and very old cats, where *cats deviate by as much as 10 years from the mean!*


How far away is each data point from 3?

@right{@image{images/histogram-w-arrows.png, 450}} In this image, we've draw an arrow for each of the 1-year-old cats. That means there are four arrows running from the mean at 3 to the interval at 1, and each arrow has the label 2.

@lesson-instruction{
Next, complete numbers 4 to 6 of @printable-exercise{computing-stdev.adoc}.
}

@strategy{
@span{.title}{Mean Average Deviation?}

In this section of the worksheet, students will need to stretch their visual imaginations a bit! In problem number 6, they are asked to summarize all 10 distances from the mean into a single number. The goal here is for students to make an educated guess about standard deviation (SD) _before_ learning the algorithm for computing it. Invite and encourage discussion about students' different approaches for guessing at the best summary number _before_ sharing the key idea about standard deviation!

Students are likely to hone in on the __Mean Average Deviation__, or MAD. Both SD and MAD measure variability or "spread" by computing individual deviations from the mean, but MAD averages these deviations and SD transforms them via square/square-root.
}

@lesson-point{
To compute the standard deviation we add the squares of all _N_ distances, divide by _N-1_, then take the square root of the result.
}

@teacher{The process of finding standard deviation manually is a bit laborious. Keeping organized is crucial; a partially-completed table is provided on the bottom half of worksheet to support students in doing so.}

@lesson-instruction{
- Complete numbers 7-10 of @printable-exercise{computing-stdev.adoc}, where you will utilize the algorithm for computing standard deviation.
}

Now that you know how to compute standard deviation on your own, here is the Contract for `stdev`, along with an example that will calculate the standard deviation for the `pounds` column in the animals-table:

```
# stdev :: (t :: Table, col :: String) -> Number
stdev(animals-table, "pounds")
```

@QandA{
@Q{What is the standard deviation for the weights of _all_ the animals at our dataset?}
@A{Approximately 48.5}
}

@optional For additional practice, have students complete @opt-printable-exercise{computing-stdev-2.adoc}.

=== Synthesize
- Can you explain why two datasets can have the same mean, but different standard deviations?
** _Mean is a measure of *central tendency*, whereas standard deviation measures the *variation* of some sample._
- What kind of dataset would have a standard deviation of zero?
** _A standard deviation of zero means that every number in the sample is exactly the same._

== Comparing Standard Deviations @duration{20 minutes}

=== Overview
Students compare centers and (more importantly) spreads - of two quantitative datasets by comparing their histograms. Both @vocab{mean} and @vocab{standard deviation} can be affected by @vocab{outliers} and/or @vocab{skewness}.

=== Launch

Take a look at the histogram below. It is the same histogram we saw in the previous section, but now with an 11th cat that is 16 years old. That's quite an outlier!

@center{@image{images/histogram-with-outlier.png, 500}}

@QandA{
@Q{What is the shape of this histogram?}
@A{The histogram has high outliers, therefore it is skewed right.}
@Q{How does it differ from the one we just looked at?}
@Q{The previous histogram - with the 16-year-old cat omitted - was roughly symmetric.}

Turn to @printable-exercise{pages/effect-of-an-outlier.adoc} to explore the extent to which the inclusion of an outlier will affect the center and spread of a quantitative dataset.

@Q{What did this outlier do to the mean? Refer back to @printable-exercise{computing-stdev.adoc} to help you.}
@A{Previously, the mean was ~2.45; now it is ~5.83.}
@Q{What did this outlier do to the standard deviation?}
@A{The outlier caused the standard deviation to increase by ~3.38.}

@optional To see how changes in data values affect the mean and standard deviation, complete @opt-printable-exercise{pages/match-mean-stdev-to-dataset.adoc}.
}

=== Investigate

The mean and standard deviation tell us where the data is centered and how far the data strays from that center. For example, when writing about the ages of cats in our shelter, we might say "the mean age is 3 and the standard devation is 2.45, so most cats are between the ages of 1 and 5 years old."

@lesson-instruction{
- The mean time-to-adoption is 5.75 weeks. Does that mean most animals generally get adopted in 4-6 weeks? _Solicit students' ideas, but do not reveal the answer._
- Turn to @printable-exercise{pages/analysis-stdev-animals.adoc} to get some practice using the Data Cycle to answer this question, then write your findings in the space at the bottom.
}

@strategy{
@span{.title}{Mean Average v. Standard Deviation}

MAD and SD are both measures of a certain kind of _distance_, literally asking "how are far from the mean are all the points in the dataset?". With each point being independent from the other, we can imagine a dataset with two points as a right triangle with two legs: how far apart are these points?

Before learning the distance formula, students might guess at a number of ways to compute the hypotenuse. They can quickly rule out the sum of the legs, and the difference between them. At some point they might suggest _averaging_ the lengths of the legs. Mean Average Deviation (MAD) does exactly that, by flattening each points' deviation into a single "dimension".

Of course, these legs exist on separate axes - so we need a formula for distances in more than one dimension. Computing the SD involves the _square root of a sum of squares_. That should sound suspiciously like the distance formula! Indeed, computing the SD for a dataset with two points is basically finding the (normalized) length of the hypoteneuse!

The pythagorean distance works in 3-dimensions as well (right pyramids!) - or for any number of dimensions - as does the formula for standard deviation. By treating each point as a separate dimension, DS allows each deviation to be considered independantly.

Why use one measure of spread instead the other? The answer is closely related to the difference between two measures of _center_! `Mean` incorporates data from every point, while `median` does not. However, `mean` is sensitive to the effect of extreme outliers or @vocab{skew}. In those cases, `median` is considered to be the better measure of center.

Treating each point independantly allows each deviation to contribute to the measure of spread, just as `mean` computes the measure of center. This is why SD is used most often, but like `mean` it is sensitive to extreme outliers or skew. In those cases, the MAD is considered a better measure of spread.
}

=== Synthesize
- How much did adding an outlier change the mean? The standard deviation?
- Extreme values affect both the mean and standard deviation of a dataset.
- Unusually low values _decrease_ the mean, while unusually high values _increase_ it. Unusually low or high values increase the standard deviation, because it summarizes distance from the mean in either direction.


== Data Exploration Project (Standard Deviation) @duration{flexible}

=== Overview

Students apply what they have learned about standard deviation to their chosen dataset. In their @starter-file{exploration-project}, they will complete the final row of the "Measures of Center and Spread" table, adding the standard deviation for two quantitative columns. They will also interpret the standard deviations they found, and record any interesting questions that emerge. To learn more about the sequence and scope of the Exploration Project, visit @lesson-link{project-data-exploration}. For teachers with time and interest, @lesson-link{project-research-paper} is an extension of the Dataset Exploration, where students select a single question to investigate via data analysis.

=== Launch

Let’s review what we have learned about standard deviation.

@QandA{
@Q{Do we compute standard deviation with categorical data or quantitative data? How many columns of data does standard deviation tell us about?}
@A{Standard deviation is a measure that tells us about the spread of a single quantitative column of data.}
@Q{Standard deviation is a measure of @vocab{spread}. In your own words, what does @vocab{spread} mean?}
@A{Spread is the extent to which values in a dataset vary, either from one another or from the center.}
@Q{How can two datasets have the same mean, but different standard deviations?}
@A{Mean is a measure of central tendency, whereas standard deviation measures the variation of some sample.}
@Q{Both unusually low and unusually high values (outliers) *increase* the standard deviation. Explain why.}
@AStandard deviation summarizes distance from the mean in *either* direction.}
}

=== Investigate
Let’s connect what we know about standard deviation to your chosen dataset.

@teacher{
Reminder: Students have the opportunity to choose a dataset that interests them from our @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "List of Datasets"} in the @lesson-link{choosing-your-dataset} lesson.
}

@lesson-instruction{
- Open your chosen dataset starter file in Pyret.
- Remind yourself which two columns you investigated in the @lesson-link{measures-of-center} lesson and use Pyret to compute the standard deviation for one of them.
** _Note: Consider recommending that students choose the same column they used when they found their @lesson-link{measures-of-center}. If students use a different column, they will need to copy/paste additional slides into their slide deck._
- What question does your computation answer?
** _Possible responses: How is the data for a certain column distributed? How does the standard deviation compare to the mean?_
- Write down that question in the top section of the @printable-exercise{analysis-stdev-my-dataset.adoc}.
- Complete the rest of the data cycle, recording how you considered, analyzed and interpreted the question.
- Repeat this process for the other column you explored before (and any others you are curious about).
** _Note: If students want to investigate new columns from their dataset, they will need to copy/paste additional Measures of Center and Spread slides into their Explorartion Project and calculate the mean, median, modes and 5-number summaries for the new columns._
}

@teacher{Invite students to discuss their results and consider how to interpret them.}

@lesson-instruction{
- *It’s time to add to your @starter-file{exploration-project}.*
- Locate the "Measures of Center and Spread" section of your Exploration Project. Type the standard deviations you just identified into the tables for the corresponding columns.
- Now, add your interpretations of the standard deviations and record any questions that emerged in the "My Questions" section at the end of the slide deck.
}

=== Synthesize
Share your findings with the class!

Did you discover anything surprising or interesting about your dataset?

What questions did the standard deviations inspire you to ask?

When your compared their findings with other students, did they make any interesting discoveries?

