= Coordinates and Game Design

@description{Students learn that characters' positions in video games can be described using coordinates, then brainstorm the context and characters for the games they will design.}

@lesson-prereqs{}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:
@objectives

@objective{coord-estimate}
@objective{coord-explain}

| Student-Facing Lesson Goals
|
- Let's estimate the positions of objects using coordinates.
- Let's collaborate to brainstorm a video game and create a sample mock-up (proof of concept) of our game.

| Materials
|[.materials-links]
@material-links

| Preparation
| 
@preparation{
- Decide whether you'd prefer to draw or project a number-line from 0 to 1000 on the board.
- Open our @starter-file{ninja-cat-desmos, Ninja Cat slider activity} in Desmos and make a code or link to share with students.
- If you're new to teaching with Desmos, we encourage you to check out these three short guides to familiarize yourself with how to make the most of its potential in both this and future Bootstrap lessons.
  * @link{https://my.amplify.com/help/en/articles/6684337-getting-started-desmos-classroom-activities, Getting Started with Desmos Classroom Activities}
  * @link{https://my.amplify.com/help/en/articles/6684323-using-the-teacher-dashboard, Using the Teacher Dashboard}
  * @link{https://my.amplify.com/help/en/articles/6763511-classroom-conversations, Classroom Conversations}
- Print and cutout @handout{dog-cat-ruby.adoc, the image of the dog}. _Use of the included cat and ruby images is optional_.
}

| Key Points for the Facilitator
|
- The launch activity should create and reinforce the need for coordinates and the importance of attending to precision.
- Continue to use the same "Estimating Coordinates" page so students can track their pattern of estimation over time.
|===

== Navigating a Grid

=== Overview
Students are asked to come up with a way of identifying location on a grid, which provides the justification for coordinates.

=== Launch
@ifnotslide{@right{image{images/1dPosition.png}}}
@ifslide{@center{@image{images/1dPosition.png}}}
Computers use numbers to represent a character’s position onscreen, using number lines as rulers to measure the distance from the bottom-left corner of the screen. 

If we placed the image of a dog on a screen and drew a number line running from 0 (on the left) to 1000 (on the right), it would look like this.

We could then measure the distance back to the left-hand edge. If we shared that number with anyone else who knows about our number line, they would be able to duplicate the exact position of the Dog.

@slidebreak

@ifslide{@center{@image{images/1dPosition.png}}}

@QandA{
@Q{What is the coordinate of the Dog, if it's on the left-hand edge of the screen?}
@A{The Dog's coordinate would be zero.}
@Q{What is the coordinate of the Dog, if it's on the right-hand edge of the screen?}
@A{The Dog's coordinate would be 1000.}
@Q{What is the coordinate of the Dog, if it's in the center of the screen?}
@A{The Dog's coordinate would be 500.}
@Q{What coordinate would place the Dog beyond the left-hand edge of the screen?}
@A{The Dog's coordinate would be less than zero (negative).}
@Q{What coordinate would place the Dog beyond the right-hand edge of the screen?}
@A{The Dog's coordinate would be greater than 1000.}
}

@opt{Select a volunteer to leave the room for a moment. Place the printed Dog image somewhere on the number line you've drawn on the board, and have the class quietly choose the number that represents the Dog's location. Remove the Dog and invite the student back into the room. Can they position the Dog at the right place, based on the number chosen by the class?}

@slidebreak

@ifslide{@center{@image{images/1dPosition.png}}}

This number line lets us communicate the position of the Dog using a single number! Unfortunately, it only represents the distance from the left-hand edge of the screen. That means the dog could be at any _height_ in the center of the screen, and it would always have the same number to represent its position.

=== Investigate

@ifslide{@right{@image{images/2dPosition.png}}}
By adding a second number line, we can locate a character _anywhere_ on the screen in either direction.

- The first line we drew runs from left to right and is called the @vocab{x-axis}.  
- The second line, which runs up and down, is called the @vocab{y-axis}. 

A 2-dimensional @vocab{coordinate} consists of both the x- and y-locations on the axes.

@slidebreak

@right{@image{images/2dPosition.png}}
Suppose we wanted to locate NinjaCat’s position on the screen. We can find the x-coordinate by dropping a line down from NinjaCat and read the position on the number line, then find the y-coordinate by running a line to the y-axis.

A coordinate pair is always written in the form of (x, y) with the x before the y (just like in the alphabet!). 

@slidebreak

@ifslide{@right{@image{images/2dPosition.png}}}
The coordinate pair @math{(200, 50)}, for example, indicates that the x-coordinate is 200 and the y-coordinate is 50.

@slidebreak

@lesson-instruction{
To develop an intuition for coordinates, complete @printable-exercise{Estimation.adoc}.
}

=== Common Misconceptions

Math-phobic students often fail to realize that _common sense_ and _intuition_ can be helpful in exercises where the answer is a number! The first two prompts in the "Synthesize" section directly get at this misconception, but you may want to pay special attention to those students while they are working.

=== Synthesize

@QandA{
@Q{Should any of the characters have x-coordinates that are very similar? How come?}
@A{Ninja Cat and the cloud have similar x-coordinates. They have the same horizontal position.}
@Q{Should any of the characters have y-coordinates that are very similar? How come?}
@A{The Ruby and the Dog have similar y-coordinates. They have the same vertical position.}
@Q{How do you think this concept relates to a video game?}
@A{Answers vary: we need to know where characters are on the screen, we need a way for players to interact with certain parts of the screen, etc.}
}

== Bridging to video games

=== Overview
Students explore a coordinate activity in which a Cartesian point is used to compute the position of a character in a game. From there, they brainstorm a game of their own.

=== Launch

@QandA{
@Q{In pairs, explore @starter-file{ninja-cat-desmos}.}
@Q{What happens when you adjust the first slider in the side panel?}
@A{Adjusting the first slider changes the horizontal position (x-coordinate) of Ninja Cat.}
@Q{What happens when you adjust the second slider in the side panel?}
@A{Adjusting the second slider changes the vertical position (y-coordinate) of Ninja Cat.}
}

=== Investigate

@lesson-instruction{
- Complete @printable-exercise{BrainstormGame.adoc} and decide on a Player, Target, Danger, and Background for your game!
- Then, use a @online-exercise{https://docs.google.com/drawings/d/1xXNWcbJ7KOgTClFQeHq-tIy0xmeZds9N3OktvEBaO4c/copy, Google Draw template} (click "Make a copy" when prompted) to create a sample "screenshot" of your game by inserting images via Google Search.
- Make sure your Screenshot includes:
  * Labeled estimates of coordinates for each character.
  * 2 characters that have the same x-coordinate.
  * 2 different characters that have the same y-coordinate.
}

=== Synthesize
@QandA{
@Q{When the "Game Over" screen is supposed to be off screen, what coordinates might hide it?}
@Q{What would be the coordinate of the dog _before it gets onscreen?_}
@A{The dog would have a negative x-coordinate before getting on screen.}
@Q{Why do we estimate?}
@A{We estimate to practice number sense and make approximations that we can later refine.}
@Q{What constitutes a good estimate?}
@A{A good estimate is a rough guess that makes sense given the limited information available to us.}
@Q{How can we improve our estimation skills?}
@A{Practice! Estimation skills will improve as we get more comfortable with numbers and with making guesses.}
}
