= Coordinates and Game Design

@description{Students learn that characters' positions in video games can be described using coordinates, then brainstorm the context and characters for the games they will design.}

@lesson-prereqs{}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* Explain the need for @vocab{coordinates} in a given situation.
* Estimate coordinates in a bounded area.

| Student-Facing Lesson Goals
|
* Let's estimate the positions of objects using coordinates.
* Let's collaborate to brainstorm a video game and create a sample mock-up (proof of concept) of our game.

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.material-links]
@opt-material-links

| Preparation
| 
* Decide whether you'd prefer to draw or project a numberline from 0 to 1000 on the board.
* Print and cutout @handout{dog-cat-ruby.adoc, images of the dog, cat and ruby}.

| Key Points for the Facilitator
|
* The launch activity should create and reinforce the need for coordinates and to attend to precision.
* Continue to use the same "Estimating Coordinates" page so students can track their pattern of estimation over time.
|===

== Navigating a Grid @duration{20 minutes}

=== Overview
Students are asked to come up with a way of identifying location on a grid, which provides the justification for coordinates.

=== Launch
@right{@image{images/1dPosition.png}}
Computers use numbers to represent a character’s position onscreen, using number lines as rulers to measure the distance from the bottom-left corner of the screen. For this example, we will draw the number line so that the screen runs from 0 (on the left) to 1000 (on the right).

We can take the image of the Dog, stick it anywhere on the line, and measure the distance back to the left-hand edge. Anyone else who knows about our number line will be able to duplicate the exact position of the Dog, as long as they know the number.

@lesson-instruction{
* What is the coordinate of the Dog, if it's on the left-hand edge of the screen?
** _The Dog's coordinate would be zero._
* What is the coordinate of the Dog, if it's on the right-hand edge of the screen?
** _The Dog's coordinate would be 1000._
* What is the coordinate of the Dog, if it's in the center of the screen?
** _The Dog's coordinate would be 500._
* What coordinate would place the Dog beyond the left-hand edge of the screen?
** _The Dog's coordinate would be less than zero (negative)._
* What coordinate would place the Dog beyond the right-hand edge of the screen?
** _The Dog's coordinate would be greater than 1000._
}

@optional Select a volunteer to leave the room for a moment. Place the printed Dog image somewhere on the number line you've drawn on the board, and have the class quietly choose the number that represents the Dog's location. Remove the Dog and invite the student back into the room. Can they position the Dog at the right place, based on the number chosen by the class?

This number line lets us communicate the position of the Dog using a single number! Unfortunately, it only represents the distance from the left-hand edge of the screen. That means the dog could be at any _height_ in the center of the screen, and it would always have the same number to represent its position.

=== Investigate

By adding a second number line, we can locate a character _anywhere_ on the screen in either direction. The first line we drew is called the @vocab{x-axis}, which runs from left to right. The second line, which runs up and down, is called the @vocab{y-axis}. A 2-dimensional @vocab{coordinate} consists of both the x- and y-locations on the axes.

@right{@image{images/2dPosition.png}}
Suppose we wanted to locate NinjaCat’s position on the screen. We can find the x-coordinate by dropping a line down from NinjaCat and read the position on the number line. The y-coordinate is found by running a line to the y-axis.

A coordinate pair is always written in the form of (x, y). When we write down these coordinates, we always put the x before the y (just like in the alphabet!). Most of the time, you’ll see coordinates written like this: @math{(200, 50)} meaning that the x-coordinate is 200 and the y-coordinate is 50.

@lesson-instruction{
To develop an intuition for coordinates, complete @printable-exercise{pages/Estimation.adoc}.
}

=== Common Misconceptions

Math-phobic students often fail to realize that _common sense_ and _intuition_ can be helpful in exercises where the answer is a number! The first two prompts in the "Synthesize" section directly get at this misconception, but you may want to pay special attention to those students while they are working.

=== Synthesize

* Should any of the characters have x-coordinates that are very similar? How come?
** _Ninja Cat and the cloud have similar x-coordinates. They have the same horizontal position._
* Should any of the characters have y-coordinates that are very similar? How come?
** _The Ruby and the Dog have similar y-coordinates. They have the same vertical position._
* How do you think this concept relates to a video game?
** _Answers vary: we need to know where characters are on the screen, we need a way for players to interact with certain parts of the screen, etc_

== Bridging to video games @duration{30 minutes}

=== Overview
Students explore a coordinate activity in which a cartesian point is used to compute the position of a character in a game. From there, they brainstorm a game of their own.

=== Launch

@lesson-instruction{
* In pairs, explore the @starter-file{ninja-cat-desmos}.
* What happens when you adjust the first slider in the side panel?
** _Adjusting the first slider changes the horizontal position (x-coordinate) of Ninja Cat._
* What happens when you adjust the second slider in the side panel?
** _Adjusting the second slider changes the vertical position (y-coordinate) of Ninja Cat._
}

=== Investigate

@lesson-instruction{
 - Complete @printable-exercise{pages/BrainstormGame.adoc} and decide on a Player, Target, Danger, and Background for your game!
 - Then, use a @online-exercise{https://docs.google.com/drawings/d/1xXNWcbJ7KOgTClFQeHq-tIy0xmeZds9N3OktvEBaO4c/copy, Google Draw template} (click "Make a copy" when prompted) to create a sample "screenshot" of your game by inserting images via Google Search.
 }

Screenshot should include:

- Labeled estimates of coordinates for each character.
- 2 characters that have the same x-coordinate.
- 2 different characters that have the same y-coordinate.

=== Synthesize
* When the "Game Over" screen is supposed to be off screen, what coordinates might hide it?
* What would be the coordinate of the dog _before it gets onscreen?_
** _The dog would have a negative x-coordinate before getting on screen._
* Why do we estimate?
** _We estimate to practice number sense and make approximations that we can later refine._
* What constitutes a good estimate?
** _A good estimate is a rough guess that makes sense given the limited information available to us._
* How can we improve our estimation skills?
** _Practice! Estimation skills will improve as we get more comfortable with numbers and with making guesses_
