= The Additive Inverse Property

@description{Students develop a more nuanced interpretation of the Commutative and Associative Properties as a result of their exploration of the inverse relationship between addition and subtraction.}

@lesson-prereqs{associative-property}

@keywords{Associative Property, Commutative Property}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* nothing

| Student-facing Lesson Goals
|

* nothing

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
* nothing
|===

== The Additive Inverse Property @duration{10 minutes}

=== Investigate

Taking the first two pairs of values in the the last table on @printable-exercise{slope-int-tables-intro.adoc, the page}, gives us:

@indented{@math{{56 - 5}\over{20 - 3}}}
@indented{We can simplify that to @math{{51}\over{17}}, for a slope of @math{3}.}

We would get the same answer for this example if we subtracted the coordinates in the opposite order...

@indented{@math{{5 - 56} \over {3 - 20}} = @math{{-51} \over {-17}} = 3}

But if we mixed subtracted the x values in a different order than we subtracted the y-values, we'd get the wrong answer!

@indented{@math{{56 - 5} \over {3 - 20}} = @math{{51} \over {-17}} = -3}

@slidebreak

@lesson-instruction{
Complete Part 1 of printable-exercise{notice-wonder-linearity.adoc} and Notice and Wonder about this table and graph.
}

[cols="^.^1a,^.^1a", grid="none", frame="none"]
|===

|

[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! 0
! 1 ! 2
! 2 ! 4
! 3 ! 6
! 4 ! 8
!===
| @image{images/2x.png}
|===

@QandA{
@Q{What do you *Notice?*}
@A{_Answers will vary._}
@A{each (x, y) pair on the table corresponds to a point on the graph}
@A{both the x and y values in the table are increasing by consistent intervals}
@A{the points on the graph are connected by a straight line.}
@Q{What do you *Wonder?*}
@A{_Answers will vary._}
}

@slidebreak

@lesson-instruction{
Complete Part 2 of printable-exercise{notice-wonder-linearity.adoc} and consider the questions about these two data tables.
}

[cols="^.^1a,^.^1a", frame="none"]
|===
|

[.pyret-table.first-table,cols="^1,^1",options="header"]
!===
! x ! y
! 1   ! 2
! 2   ! 3
! 3   ! 4
! 4   ! 5
! 5   ! 6
!===

|
[.pyret-table.first-table,cols="^1,^1",options="header"]
!===
! independent ! dependent
! 1 ! 20
! 2 ! 17
! 3 ! 14
! 4 ! 11
! 5 ! 8
!===

|===

@lesson-instruction{
- What would the next pair be for each of these tables?
- What would the y-values be when x is 0?
}

@slidebreak

- At each point in our linear model, @math{y} is the _predicted median lifespan_, and @math{x} is the _log of per-capita gdp_.

- We want @math{x} to represent the **original, un-transformed** value, simply using _per-capita gdp_ as-is...

- We've learned that:

** the *slope* in the transformed, linear model is the same as the *log coefficient* in the un-transformed logarithmic model

** the *vertical shift* in the transformed, linear model is the same as the *vertical shift* in the un-transformed logarithmic model

@ifproglang{pyret}{

@slidebreak

pyret aaaa

@slidebreak

pyret bbbb

}

=== Synthesize

- Using @proglang allows us to evaluate arithmetic expressions easily and efficiently. In your own words, describe _how_ you tested the equivalence of different expression - and how you interpreted the results that @proglang produced.
- In @proglang, what does it mean for a test to pass? What does it mean for a test to fail?
- What did this programming exploration teach you about the additive inverse?
