= The Additive Inverse Property

@description{Students develop a more nuanced interpretation of the Commutative and Associative Properties as a result of their exploration of the inverse relationship between addition and subtraction.}

@lesson-prereqs{associative-property}

@keywords{Associative Property, Commutative Property}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* nothing

| Student-facing Lesson Goals
|

* nothing

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
* nothing
|===

== The Additive Inverse Property @duration{10 minutes}



=== Investigate

For the remainder of the activity, we will examine examples blocks. The first one includes only examples that pass. The second one has some errors! And the third one includes just one examples... *you* will be responsible for providing additional examples!


@teacher{
@opt{If you would like to offer students additional practice with the additive inverse in @proglang, two optional activities include @opt-printable-exercise{are-they-identical.adoc} and @opt-printable-exercise{writing-equivalent-code-additive.adoc}.}
}


=== Synthesize

- Using @proglang allows us to evaluate arithmetic expressions easily and efficiently. In your own words, describe _how_ you tested the equivalence of different expression - and how you interpreted the results that @proglang produced.
- In @proglang, what does it mean for a test to pass? What does it mean for a test to fail?
- What did this programming exploration teach you about the additive inverse?
