= Exploring Linear Models

@description{Students investigate linear relationships in demographic data about US States, using an inquiry-based model of sense-making, hypothesizing, modeling and testing.}

@lesson-prereqs{contracts-tables-displays}

@keywords{linear, slope, intercept, slope-intercept, general normal form, point-slope}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Read and interpret real-world data, presented in a scatter plot
* Describe correlations as Strong, Moderate, or Weak
* Model linear relationships using linear functions

| Student-facing Lesson Goals
|

* Let's use Pyret to make predictions with linear models


| Materials
|[.materials-links]
@material-links

| Preparation
|
* All students should log into @starter-file{program-list} and, open the @starter-file{alg2-states}.

| Key Points For The Facilitator
|
This lesson focuses on _linear relationships_, and the math content of the lesson is primarily a review of those concepts from Algebra 1 (the third section includes topics that may be new to some students). That being said, the bulk of the new learning serves two objectives:

* This lesson establishes a structure for exploring relationships in data, which students will repeat in subsequent explorations.
* The lesson also includes some programming content, allowing students to learn necessary programming skills while practicing the math they already know.
|===

== Looking for Patterns @duration{15 minutes}

=== Overview
Students explore the State Demographics dataset, and create scatter plots to search for relationships between columns. They share and discuss their findings with the class.

=== Launch

- Do you think that younger animals get adopted faster? Why or why not?
** _The goal here is to have an open discussion and draw students in. Allow students to share their opinions freely. (For example: Yes, baby animals get adopted quickly because they're so cute! No, animals require too much work when they are young.)_
- What kind of data is `age`? What kind of data is `weeks`?
** _Both `age` and `weeks` are quantitative._
- What kind of display would help us analyze the relationship between age and adoption time?
** _Again, solicit students ideas and discuss why each display type would or would not work._

Pie and Bar charts help us see the _frequency_ of values in a _categorical_ column. There are other displays, like histograms and box plots, that help us explore the _distribution_ of values in a _quantitative_ column.

But what we really want is a display that will help us search for *a relationship between two quantitative columns*, and that's exactly what scatter plots do.

[.lesson-point]
Scatter plots reveal the relationship between two columns by plotting one on the x-axis and the other on the y-axis.

* What is the Contract for `scatter-plot`?
 @show{(contract 'scatter-plot '("Table" (labels String) (explanatory String) (response String)) "Image")}

Before we can draw a @vocab{scatter plot}, we have to make an important decision: which variable is @vocab{explanatory} and which is the @vocab{response}? In this case, are we suspecting that an animal’s weight can explain how long it takes to be adopted, or that how long it takes to be adopted can explain how much an animal weighs? The first one makes sense, and reflects our suspicion that age plays a role in adoption time.

It's customary to use the horizontal axis for our explanatory variable and the vertical axis for the response variable. Each row in the dataset will be a point on the scatter plot with `age` for x and `weeks` for y.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Why not Independent/Dependent?}

When modeling with functions, we typically use terms like @vocab{dependent variable} and @vocab{independent variable}. But even in the presence of a strong correlation, the y-values in a scatter plot are __never__ fully dependant on the x-values. Plenty of scatter plots have no correlation: the y-coordinates do not depend on the x-coordinates at all!

Statisticians commonly use the words @vocab{explanatory variable} and @vocab{response variable}, to more accurately describe the role one column of data plays in _explaining_ another when searching for a relationship.
|===

[.lesson-instruction]
- Today we'll be looking at data from each state in the US, and searching for possible relationships within the data!
- Open the @starter-file{alg2-states}
- From the File menu, select "Save a Copy", and click "Run".
- Working in pairs or small groups, complete @printable-exercise{exploring-states.adoc}

@teacher{Have students share back what they Notice and Wonder about the dataset.}

=== Investigate

The code on lines 13 and 14 show us how Pyret defines values:

```
alabama = row-n(states-table, 0)
alaska  = row-n(states-table, 1)
```

@teacher{In math, `x = 4` will define a variable `x` to be the value `4`. Any time we use `x` after that, we can substitute in the value of `4`. This works in Pyret, too. But in Pyret, values can be more than just numbers! On lines 13 and 14 of this file, the variables `alabama` and `alaska` are _rows_ from the table.}

* What columns in this dataset have to do with wealth?
** _Examples:_ `pct-in-poverty`, `poverty-rate`, `median-income`, `per-capita-income`
* What columns might be related to wealth?
** _Examples:_ `college-or-higher`, `hs-or-higher`

[.lesson-instruction]
- Working in pairs or small groups, complete questions 1 through 4 (making displays and suggesting possible relationships) in @printable-exercise{looking-for-patterns.adoc}.
- **Do not go on to question 5.** We'll be returning to that later in the lesson.

@teacher{Note: During this activity, don't let students just make scatter plot for random pairs of columns. Instead, encourage them to first _think about which columns might be related_, and then create the scatter plot to search for this relationship. The dataset is designed so that students will quickly begin searching for relationships between varying levels of education and income, and there are linear relationships in each of these.}

=== Synthesize

- Share your scatter-plots with one another (copying and pasting scatter plot displays into a shared document, for example, and then labeling those displays). What possible relationships did you find in question 3?
- Did you and your classmates commonly use any words to describe the relationships you observed?

@teacher{Teacher note: the next section of the lesson is all about identifying form, direction, and strength. Students will acquire the formal vocabulary that data scientists use to assess relationships.}

== Describing Patterns @duration{15 minutes}

=== Overview
Students identify and make use of correlations in scatter plots, learning to characterize their form as being linear, curved, or showing no clear pattern. They learn how to describe the @vocab{strength} of correlations, and that linear patterns have direction.

=== Launch

Scatter plots let us visualize the relationship between two columns. If no relationship exists, the points in the scatter plot just appear as a shapeless cloud. But if there _is_ a relationship, the points will form some kind of pattern. When we build scatter plots, we are searching for patterns - or @vocab{correlations} between two quantitative variables.

These patterns can be described using three qualities: form, direction, and strength.

[.lesson-point]
Form indicates whether a relationship is linear, non-linear or undefined.

[cols="^1a,^1a,^1a", stripes="none"]
|===
| @image{images/1b1.gif, 250}
| @image{images/2NL.gif, 250}
| @image{images/B.gif, 250}

| Some patterns are @vocab{linear}, and cluster around a straight line sloping up or down.
| Some patterns are **non-linear**, and may look like a curve or an arc.
| And sometimes there is **no relationship** or pattern at all!
|===

[.lesson-point]
Linear relationships have direction

If the relationship clusters around a straight line, we can talk about _direction._

@right{@image{images/C.gif, 200 }}**Positive**: The line slopes up as we look from left-to-right. Positive relationships are by far the most common because of natural tendencies for variables to increase in tandem. For example, “the older the animal, the more it tends to weigh”.

@clear

@right{@image{images/A.gif, 200}}**Negative**: The line slopes _down_ as we look from left-to-right. For example, “the older a child gets, the fewer new words he or she learns each day.”

Note: Not every shape has a direction! For example, a curve can start out sloping upwards, but then peak and slope downwards.

[.lesson-point]
Strength indicates how closely the two variables are correlated.

How well does knowing the x-value allow us to predict what the y-value will be?

@right{@image{images/A.gif, 200}}**A relationship is strong if knowing the x-value of a data point gives us a very good idea of what its y-value will be** (knowing a student's age gives us a very good idea of what grade they're in). A strong linear relationship means that the points in the scatter plot are all clustered _tightly_ around an invisible line.

@clear

@right{@image{images/1a.gif, 200}}**A relationship is weak if x tells us little about y** (a student's age doesn't tell us much about their number of siblings). A weak linear relationship means that the cloud of points is scattered very _loosely_ around the line.

@clear


=== Investigate

Now that you've dug into the role that form, direction and strength play in quantifying a correlation, it's time to put those concepts to work!

[.lesson-instruction]
In pairs or small groups, complete @printable-exercise{pages/identifying-form-matching.adoc}.

@teacher{Review student answers, and have students _explain their thinking_ for this activity. For students who are struggling, hearing what their peers are looking for is especially helpful at this stage.}

[.lesson-instruction]
In pairs or small groups, complete @printable-exercise{pages/identifying-form.adoc}

@teacher{Review student answers. Some of the answers are not so clear-cut, and students may disagree about what constitutes a "strong" vs. "weak" correlation. We've tried to choose scatter plots that clearly fall into one category or the other, but without diving into the algorithm for linear regression students may find this exercise somewhat subjective.}

[.lesson-instruction]
Return to @printable-exercise{looking-for-patterns.adoc}, and complete the rest of the page.


=== Common Misconceptions
- Students often conflate strength and direction, thinking that a strong correlation _must_ be positive and a weak one _must_ be negative.
- Students may also falsely believe that there is ALWAYS a correlation between any two variables in their dataset.
- Students often believe that strength and sample size are interchangeable, leading to mistaken assumptions like "any correlation found in a million data points _must_ be strong!"


=== Synthesize

- What relationships did you find in the states dataset?
- What was their form, direction, and strength?
- Were any of these relationships a surprise? Why or why not?


== Fitting Linear Models @duration{25 minutes}

=== Overview

The line of best fit is framed as a _predictor function_, which attempts to predict where a new point would fall on the plane based on the relationship in the data. Students define their predictors (linear functions) to find the line of best fit, using @vocab{R-squared} to determine goodness of fit and making predictions with the result. They explore the impact that slope and and y-intercept have on goodness of it.

=== Launch

[.lesson-instruction]
In Pyret, make a scatter plot showing the the relationship between `college-or-higher` and `median-income`.

@center{@image{images/college-v-income.png}}

This scatter plot appears to show a positive, linear relationship: states with higher percentages of college graduates tend to have higher median household incomes.

[.lesson-instruction]
Suppose the United States were to add a new state. **Based on the data for the existing 50 states (plus DC!), what median household income would you predict, if exactly 50% of the new state's citizens had attended college?** What about 20%? 60%

@teacher{Let students discuss, and explain their thinking. If possible, mark off a single point for each of the hypothetical percentages, then connect those points to show a straight line. Note that some of these new points would require changing the x- and y-axes of our display.}

When we see patterns in data, we can use those patterns to __make predictions__ based on that data. We can even draw a line to show all the possible predictions at once! These predictions represent our "best guess" at the underlying relationship in the data, as we try to model that relationship using math.

These models are just functions being graphed on top of the scatter plot, with the goal of minimizing the distance between the line and all the points on the plot. For straight-line relationships, these are _linear functions_ or "linear models". The straight-line graph of these models is sometimes called the "regression line" or the "predictor function", but you may have heard it called the @vocab{line of best fit}.

When we make a model, we want it to be the closest possible approximation of all the points. A "good fit" has most of the points very close to the line, and a "bad fit" has the points very far away.

What's the best fit we can make for this dataset?

=== Investigate

[.lesson-instruction]
- Complete the first section ("Build a Model from Samples") in @printable-exercise{model-college-v-income.adoc}.
- How well did your model work for Alabama and Alaska? Why didn't it work as well for other states?
- How can we measure "how well a model fits"?

@teacher{
@optional If students need more scaffolding defining a function from two points, use @opt-printable-exercise{def-2-points.adoc}

Before students complete the remainder of the workbook page, confirm that they were able to successfully compute slope and y-intercept, define and test `f(x)` in Pyret, and evaluate the predictive value of `f(x)`.
}

Pyret includes a function called `fit-model`. Find its Contract on the @dist-link{Contracts.shtml, Contracts Page}. @pathway-only{_If you're working with a printed workbook, the contracts pages are included in the back._} Like `scatter-plot`, it consumes columns for our _labels_, our @math{x}s and our @math{y}s. However, it __also consumes a function!__ It produces a scatter plot, with the function graphed on top of it.

[.lesson-instruction]
- Complete the second section ("Fit the Model") in @printable-exercise{model-college-v-income.adoc}.
- Based on the @math{R^2} values and plots you created on this page, what do you think @math{R^2} means?

@math{R^2} describes the _percentage of the variation in the y-variable that is explained by the x variable_ in our model. In other words, an @math{R^2} value of 0.20 could mean that “20% of the variation in median household income is explained by the percentage of college degrees in a state, according to our linear model”. Better models will explain a higher percentage of that variation.

If the model is perfect, the @math{R^2} value will be 1.00, meaning the @math{y}-values can be perfectly predicted by the @math{x}-values. Of course in the real world, no model is perfect! The @math{R^2} value for no correlation at all is *zero*. If we just drew a horizontal predictor line _in the middle of the data_, it would mean that we expect a median income somewhere in that range but with no connection whatsoever to the percentage of people who finish college.

But sometimes models make predictions that are _even worse than useless_ - they trend in the wrong direction altogether. Did you see any models with a negative @math{R^2} value?

[.lesson-instruction]
- Complete the first section ("Build a Model through Trial and Error") on @printable-exercise{model-college-v-income-2.adoc}.
- What was the best model you could come up with?

But how do we find the __best__ model? In Statistics, an algorithm called linear regression is used to derive the slope and y-intercept of the best possible model by taking every datapoint into account. Pyret has a function that will do just that, called `lr-plot`.

[.lesson-instruction]
- Complete the last section ("Build a Model Computationally") in @printable-exercise{model-college-v-income-2.adoc}.
- How close did you come to the optimal model? Did anything about the model surprise you?
- @optional For each of the three models on @printable-exercise{model-college-v-income.adoc} and @printable-exercise{model-college-v-income-2.adoc}, and graph the line on @opt-printable-exercise{graphing-models.adoc}.

@teacher{Sometimes the slope or y-intercept of a linear model have too many digits to be displayed clearly. When this happens, Pyret will convert them to scientific notation. While students have encountered scientific notation before, they may not recognize @math{8.23e5} as @math{8.23 \times 10^5}. You should make sure they understand how to translate this notation into numbers before proceeding.}

[.strategy-box, cols="1a", grid="none", stripes="none"]
|===
|
@span{.title}{More `lr-plot` material}

If you'd like to have students dig deeper into linear regression, there's an @lesson-link{linear-regression, entire lesson} you can use that spends more time interpreting results and writing about findings. Deeper discussion of @math{R^2} and least-squares regression may be appropriate for older students, or in a dedicated statistics class.
|===

When we interpret a model, we try to make sense of the slope, the axes, the @math{R^2} value, and the real data behind them. In this example, __a model built from Alaska and Alabama predicts that a 1 percent increase in college degrees is associated with a **$5613** increase in median household income. Based on the @math{R^2} value of **-15.63**, this is a pretty terrible model and shouldn't be trusted.__

[.lesson-instruction]
--
These models are useless if we can't make sense of them!

- For practice building other relationships in the data, complete @printable-exercise{interpreting-linear-models.adoc}.
- @optional For more practice, build linear models for **other** relationships in the data. You can use @opt-printable-exercise{building-linear-models.adoc}, and write up your findings in the extra space on @printable-exercise{interpreting-linear-models.adoc}.
--

=== Synthesize

- How could we use scatter plots and linear models to find out if taller NBA players tend to make more three-pointers?
- How could we use them to find out if wealthier people live longer?
- How could we use them to find answers to _other_ questions?

== Other Forms of Linear Models @duration{flexible}

=== Overview

Students explore other forms of linear models, and consider why it's useful to have more than one form.

=== Launch

You may already be familiar with the different forms of linear models:

[cols="^1,^1,^1", options="header"]
|===
| Slope-Intercept Form    |Point-Slope Form				| Standard Form
| @math{y = mx+b}		  | @math{y-y_1 = m(x-x_1)}		| @math{Ax+By = C}
|===

Depending on what part of the model we care about most, we might choose to use one display over another.

- Slope-Intercept Form makes it really easy to read the slope and y-intercept
- Point-Slope Form makes it easy to find the equation of the line given a single point and slope
- Standard Form makes it easy to find the x- and y-intercepts of the line

* Suppose our scatterplot had data for a state with 0% college enrollment, and another with 0% median income. Would one form make the model easier to build than another? Why or why not?
** Standard Form
* Suppose we only knew the slope of a model, and but we know the college graduation rate _and_ median income for Rhode Island. Which form would make it easy to figure out the rest of the model?
** Point-Slope Form
* Another researcher asks for the slope and y-intercept of our model. Which form make it as easy as possible to communicate them?
* Slope-Intercept Form

=== Investigate

When trying to fit a piece into a puzzle, sometimes we rotate the piece to see it from a different angle. When fitting a model to a dataset, we might prefer to look at the linear relationship from different angles as well!

[.lesson-instruction]
- @optional To get some practice reading these models, try your hand at @opt-printable-exercise{match-graph-ps.adoc}, @opt-printable-exercise{match-graph-sf.adoc}, and @opt-printable-exercise{match-graph-si.adoc}.
- Challenge yourself with @opt-printable-exercise{match-graph-def.adoc}.

@teacher{
Have students share their answers and discuss.

@optional For more practice working with the math of linear models, students can work on either/both of the two exercises below.
}

[.lesson-instruction]
- @optional Practice working with other forms, by translating your models on @opt-printable-exercise{other-forms-linear-models.adoc}.
- @optional Linear models can be shifted in a number of ways, both horizontally and vertically. Explore this concept in @opt-printable-exercise{horizontal-shift.adoc}, @opt-printable-exercise{hor-vert-shift-positive.adoc}, and @opt-printable-exercise{hor-vert-shift-negative.adoc}

=== Synthesize
If you needed to draw the graph of a linear model, which form would you like to start from? Why?

== Additional Exercises

- @opt-printable-exercise{other-forms-linear-models.adoc}
- @opt-printable-exercise{match-graph-ps.adoc}
- @opt-printable-exercise{match-graph-sf.adoc}
- @opt-printable-exercise{match-graph-si.adoc}
- @opt-printable-exercise{hor-vert-shift-positive.adoc}
- @opt-printable-exercise{hor-vert-shift-negative.adoc}
- @opt-printable-exercise{other-forms-linear-models.adoc}
- @opt-printable-exercise{horizontal-shift.adoc}
- @opt-printable-exercise{match-graph-def.adoc}
