= The Distance Formula

@lesson-description{Students apply their knowledge of the Pythagorean Theorem and Circles of Evaluation to develop a function for the distance formula.}

[@lesson-intro-table]
|===
@prereqs-stds{restating-the-problem}

| Lesson Goals
|Students will be able to:

* Explain how the distance formula is related to the Pythagorean theorem.
* Write a function for the distance formula.

| Student-Facing Lesson Goals
|
* I can explain how the distance formula is connected to the Pythagorean theorem.
* I can write a function that takes in 2 points and returns the distance between them.

| Materials
|[.materials-links]

@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/1qGx7kJSqxoX-2u8I_MAd-sganrwaXuWlWnUfjR4w5Uk/, Lesson Slides}
}

@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/198S74IxlOVJWS6kll2XJKqGda8AwfV4R89gqiwiTOlA/, Lesson slides}
}
@material-links

| Supplemental Resources
|
* @link{https://www.youtube.com/watch?v=i9-ZPGp1AJE&feature=youtu.be, This short video} introduces viewers to the nearly 4000 year old Babylonian tablet known as Plimpton 322, which contains a table of Pythagorean Triples that long predates Pythagoras, as well as to Babylonians use of the base 60 system.

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Key Points for the Facilitator
|
* The distance formula is an excellent review of @vocab{Circles of Evaluation}. Have students work out the expression in small groups to foster discussion.

@lang-prereq

|===

[.old-materials]
Click here to see the @link{https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/units/unit8/index.html, prior unit-based version}

== Distance in 1 Dimension @duration{15 minutes}

=== Overview
Students discover the need for distance calculation (first in one dimension, then in two) in video games.

=== Launch

Students should have their workbook, pencil, and be logged into
@ifproglang{wescheme}{ @link{https://www.wescheme.org, WeScheme     } }
@ifproglang{pyret}{    @link{https://code.pyret.org, code.pyret.org } }
on their computer.

[.lesson-instruction]
Open your saved Game File, which should have the Target and Danger moving on their own. Your Player should respond to keypresses, and the Target and Danger should re-appear after they leave the screen. It's almost fully-playable!

{empty}

- What seems to be missing from this game?
+
_The characters aren't doing anything when they collide._

- What does it mean for characters to 'hit' one another? To collide?
+
_They have to be close enough to touch._

- How will the computer know when the characters have collided?
+
_When the coordinates of the characters are really close to each other._

@span{.right}{@image{images/screenshot.jpg}}
[.lesson-instruction]
Scroll down to the `distances-color` definition (look for `; 4. Collisions` in the file). Right now this value is defined to be the __empty string__ `""`. Change this to a color that will show up on your background, and click "Run".

This setting will draw lines from your Player to each of the other characters, and then use those lines as the hypotenuse of right triangles!

The legs of these triangles show the distance in 1 dimension each (on the x- and y-axis). How is this calculated?

@span{.clear}

[.lesson-instruction]
--
Role-Play: Ask a volunteer to help role-play two characters colliding!

- Identify a "number line" on the floor (this can be done just by pointing, or with a visual aid).
- Make sure that you and your volunteer stand with feet as close together as possible, representing the infinitely small point that identifies your center.
- Raise your arms to form a "T shape", representing the outer edges of the characters.
- Emphasize that this represents _one dimension_ (perhaps the x- or y-axis).
- With the volunteer, stand about 10 steps away from one another and side-step towards each other one step at a time, while asking the class, "True or False? We are colliding!" __Be sure to only accept "true" and "false" as responses - not "yes" and "no"!__
- Ask the class how far apart you and your volunteer are, and then ask them how they would calculate this if you were standing on a number line and they could see the actual coordinates under your feet.
- After a few iterations, try switching places and repeating. _Point out that students always subtract the smaller number from the larger one, regardless of the character order!_
- Do this until students can clearly see it's when the two characters are 'touching' or 'overlapping' in some way - NOT when they are 'at the same point.'
--

=== Investigate

Let's explore how the program computes the length of these lines...

[.lesson-instruction]
Have students find the `line-length` function in their game files, click Run, and practice using it in the @vocab{Interactions area} with different values for `a` and `b`.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Extension}

`line-length` is essentially the way students conceptualize distance in one dimension.

You can extend this `line-length` activity into a lesson on absolute value and have students program `line-length` themselves. Computing 1-dimensional distance - and absolute value - are in fact piecewise functions!
|===

[.lesson-instruction]
- What does this function _do?_
- Why does it use conditionals?

=== Synthesize
Make absolutely certain that students understand that this function _always returns the positive distance_ between two points on a number line.

What if we have points that are not on the same line? What if instead they differ by both the x- and y-coordinate?

== Distance in 2 Dimensions @duration{30 minutes}

=== Overview
Students extend their understanding of _distance_ from one dimension to two, using a geometric proof of the Pythagorean Theorem to compute the distance between two points.

=== Launch
@span{.right}{@image{images/2d-distance.png}}
Bring your volunteer (or choose a different one!) back up to the front of the class, and have them squat down on the floor to represent a difference in the y-coordinate between the player and a character. Repeat the role-play activity.

[.lesson-instruction]
Suppose the Player is at (0, 4), and another game character is at (3, 0). Now there is a difference in both dimensions. How could we calculate distance _now?_

Computing the distance in 1-dimension is great, as long as the Player and Danger have the same x- or y-coordinate. In that case, the difference between the coordinates is exactly the distance between the two characters. But how do we compute the distance between two points when both the x- _and_ y-coordinates are different?

Have students watch @link{https://www.youtube.com/watch?v=Ln7myXQx8TM, video of this problem} [Credit: Tova Brown], and try explaining the proof to one another. In our case, the lengths A and B are computed by the `line-length` function we already have!

Have students write code to find the distance between these game characters @printable-exercise{pages/distance-write-code-from-lengths.adoc}.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Why line-length?}
Students learn early on that distance in 1-dimension is computed via @math{\lvert x_2 - x_1 \rvert}, and that distance is always a positive value. The Pythagorean Theorem teaches students that the length of the hypotenuse is computed based on the distance in the x- and y-dimension. However, most math textbooks show the distance formula without connecting back to that formula:

@math{\sqrt{{(x_2 - x_1)}^2 + {(y_2 - y_1)}^2}}

A student who asks whether it's a problem when @math{x_2 - x_1} is negative is displaying a deep understanding of what's going on. Unfortunately, the response to this student relies on a computational artifact of squaring to force a number to be positive (rather than the purpose of squaring in the Pythagorean Theorem). Using the `line-length` function explicitly connects the distance formula back to the 1-dimensional distance students know, allowing them to apply prior knowledge and better connecting back to the Pythagorean Theorem itself. This effectively rewrites the distance formula as:

@math{\sqrt{{\lvert x_2 - x_1 \rvert}^2 + {\lvert y_2 - y_1 \rvert}^2}}

|===

=== Investigate

[.lesson-instruction]
Turn to @printable-exercise{pages/distance-on-coordinate-plane.adoc} and look at how line-length is used in the code. See if you can figure out how to write the code for the second problem.

[.lesson-instruction]
Turn to @printable-exercise{pages/distance-scaffold.adoc} in your student workbook. Convert this expression to a Circle of Evaluation, and then to code.

Optional: Have students use this @printable-exercise{pages/Distance-bw-Two-Points-Multiple-Representations.pdf, Multiple Representations: Distance between two points} to model the distance formula for these coordinates with the Circles of Evaluation. +

[.lesson-instruction]
Practice computing the distance between two _different_ points, by completing @printable-exercise{pages/distance-from-game-coordinates.adoc}.

Optional: Have students complete another pair of these problems using @opt-printable-exercise{pages/distance-from-game-coordinates-2.adoc}

Debrief these workbook pages - or have students pair-and-share - before moving on to writing the full distance function.

[.lesson-instruction]
Using @printable-exercise{pages/distance.adoc}, write a function that takes in two @vocab{coordinate} pairs (four numbers) of two characters (@math{x_1, y_1}) and (@math{x_2, y_2}) and returns the distance between those two points. __HINT:__ the code you wrote in @printable-exercise{pages/distance-scaffold.adoc} can be used to give you your first example! +

Students can test their `distance` function using *Pythagorean triples*, such as (3, 4, 5) or (5, 12, 13), to make sure the function is calculating the distance correctly. Finally, students fix the broken `distance` function in their game files. When they click "Run", the right triangles will appear with proper distances for the hypotenuse.

If we knew the lengths of the hypotenuse and one leg of the triangle, could we use the formula @math{A^2 + B^2 = C^2} to compute the length of the other leg?

[.lesson-instruction]
Take a look at the two examples on @printable-exercise{pages/distance-comparing-code.adoc}. There's a subtle difference between the two examples! What is it? Can you explain why they need to be written differently?

=== Common Misconceptions
It is _extremely common_ for students to put variables in the *wrong order*. In other words, their program looks like
@ifproglang{wescheme}{ `...(sqrt (+ (sqr (line-length x1 y1)) (sqr (line-length x2 y2))))...`
instead of `...(sqrt (+ (sqr (line-length x2 x1)) (sqr (line-length y2 y1))))...` }
@ifproglang{pyret}{ `...num-sqrt(num-sqr(line-length(x1,y1)) + num-sqr(line-length(x2, y2)))...`
instead of `...num-sqrt(num-sqr(line-length(x2 - x1)) + num-sqr(line-length(y2 - y1)))...` }

In this situation, remind students to look back at what they circled and labeled in the examples step. _This is why we label!_


