= 🎮 Player Animation

@description{Students apply their knowledge of piecewise functions to write a function that will move the player in their game in different directions and at different speeds depending on which key is pressed.}

@lesson-prereqs{piecewise-functions-conditionals}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to:
@objectives

@objective{apply-piecewise}

| Student-Facing Lesson Goals
|
- Let's write a piecewise function to get our player moving using the arrow keys!

| Materials
|[.materials-links]


@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Key Points for the Facilitator
|
- Encourage students to challenge themselves when creating update-player by completing one of the extension activities.
- The update-player function is one of the main places where students can set their game apart and make it theirs.  Encourage exploration and experimentation!
- Adding comments to code - if you have to ask a student "What are you trying to do there?", then they probably need more comments!

|===

== Defining Piecewise Functions

=== Overview
Students _define_ a piecewise function. This is a challenging task, which is motivated by introducing key events in their video game.

=== Launch

@lesson-instruction{
Sign in to @starter-file{program-list} and open your saved game starter files.

You've already defined functions to move your `DANGER` and `TARGET`. Take a moment to look at your code or the Design Recipe page focused on `DANGER` and `TARGET`, and refresh your memory on how they work.
}

@QandA{
@Q{What controlled the speed of your characters?}
@Q{What controlled the _direction_ of your characters?}
}

@slidebreak

- If we wanted our `PLAYER` to go up all the time, we would already know how to do that. 
- If we wanted our `PLAYER` to go _down_ all the time, we would already know how to do that.
- But we want the player to go up _only_ when the "up" arrow is pressed, and down _only_ when the "down" arrow is pressed... 

@QandA{
@Q{Do we know how to make a function behave differently, based on its input?}
}

=== Investigate

@strategy{Strategies for English Language Learners}{


MLR 6 - Three Reads: Have students read through the problem statement three times, looking for different information.  What is the problem asking me?  What is the @vocab{Contract} for this @vocab{function}?  What information do I need to create that function?
}

@QandA{
@Q{What is the Contract for `update-player`?}
@A{The Name is `update-player`, the Domain consists of a Number and String, and Range is a Number.}
@Q{What does each part of the domain represent?}
@A{The Number is the y-coordinate of `PLAYER`.}
@A{The String is the key that the user pressed (either "up" or "down").}
@Q{What does the Range represent?}
@A{The Number is the new y-coordinate of ``PLAYER``.}
@Q{How does the y-coordinate of `PLAYER` change when the user presses the "up" key?}
@A{It should increase, the program should add something to it.}
}

@center{@image{images/player-move.png,  400}}

@slidebreak

@lesson-instruction{
Complete @printable-exercise{update-player.adoc} with a partner, then type your code into your game starter file and test it out.
}

@strategy{2-D Game Movement}{


If your students have their games working and you are ready to support them in delving into the Posn data type that will support 2-d movement in the game...

The first step is to complete @opt-printable-exercise{2d-character-movement.adoc} and @opt-printable-exercise{2d-character-movement-cont.adoc}. 

Once they've gotten their danger moving diagonally, they're ready to build upon their understanding of Posn and piecewise functions to tackle @opt-printable-exercise{update-player-2.adoc}.
}


=== Common Misconceptions
- Students often think of this function as returning a _relative distance_ (e.g. "it adds 20"), instead of an absolute coordinate (e.g. "the new y-coordinate is the old y plus 20")

=== Synthesize
- How is this function similar to the piecewise functions you've seen before? How is it different?
- How could we change this function so that the "W" key makes the player go up, instead of the arrow key?
- How could we change this function so that the "W" key makes the player go up, _in addition to_ the arrow key?
- Suppose your little brother or sister walks by and hits a random key. What should happen if you hit a random key that doesn’t have a meaning in your function? What happens now?

== Cheat Codes and Customizations

=== Overview
Students choose one or more features to make their game more unique. These features can be quite simple, such as adding another key that does the same thing that "up" or "down" does. But they can also be extremely sophisticated, requiring students to exploit properties of the number line in conjunction with function composition and @vocab{compound inequalities}!

=== Launch
Right now, all of your games allow the player to move up and down at a constant speed. But what if we wanted to add a special key that made the player warp to the top of the screen, or move down twice as fast? What if we wanted the player to _wrap_, so going off one side of the screen would make it reappear on the other?

=== Investigate

@lesson-instruction{
Complete at least one of the @printable-exercise{challenges.adoc} before turning to your computer to customize your game.
}

@teacher{
Some possible features students might include are:

- *Warping* - program one key to "warp" the player to a set location, such as the center of the screen

- *Boundaries* - change `update-player` such that `PLAYER` cannot move off the top or bottom of the screen

- *Wrapping* - add code to `update-player` such that when `PLAYER` moves to the top of the screen, it reappears at the bottom, and vice versa

- *Hiding* - add a key that will make `PLAYER` seem to disappear, and reappear when the same key is pressed again
}

==== Reminder: Use @ifproglang{wescheme}{`;`}@ifproglang{pyret}{`#`} to add comments to code!

Adding useful @vocab{comments} to code is an important part of programming. It lets us leave messages for other programmers or our future selves and "turn off" pieces of code that we either don't want or need to @vocab{debug} later.

=== Synthesize

- What features did you add to customize your games?
- What would it take to make the player move left and right? 
- Why can't we do this without changing the Contract?

@strategy{Pedagogy Note}{


It's likely that once they hear other students' ideas, they will want more time to try them out. If time allows, give students additional _slices_ of "hacking time", bringing them back to share each other's ideas and solutions before sending them off to program some more. This dramatically ramps up the creativity and engagement in the classroom, giving better results than having one long stretch of programming time.
}
