= Domain and Range (Contracts)

*Students encounter String and Image datatypes and use "contracts" to make sense of the domain and range of functions*

[.left-header, cols="20a, 80a", stripes=none]
|===
| Lesson Goals 
| Students will be able to:

* Demonstrate understanding of @vocab{domain} and @vocab{range} and how they relate to @vocab{functions}

|Student-facing Goals
|
* I can identify the domain and range of a function.
* I can identify the datatypes Number, String, and Image

|Key Points For The Facilitator
|
* Check frequently for understanding of @vocab{datatype}s and @vocab{contract}s during this lesson and throughout subsequent lessons.

* Students will use their Contracts page frequently, so it should be kept in an accessible, convenient location.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.


|Materials
|
* _Materials_
|===

[.left-header, cols="20a, 80a", stripes=none]
|===
|Math Standards(CCSS)
|
* 8.NS.A.2 @std{8.NS.A.2}

|CS Standards(CSTA)
|
* CS Standards here
|===


== Get Ready: 

Students should be logged into WeScheme and have their Contracts page ready.

== Launch: (5 mins)
Have a Circle of Evaluation up in front of students.  What will this evaluate to?

Show a line of code: `(* 10 -4)`.  What will this evaluate to?

Show another line of code: `(star 50 “solid” “blue”)`.  What will this evaluate to? 

== Explore: (10 mins)
Give students time to investigate image functions and see how many they can discover.  Students should fill out the contract for any new functions they discover.

[.strategy-box]
.Strategies for English Language Learners
****
MLR 2 - Collect and Display: As students explore, walk the room and record student language relating to functions,
domain, range, contracts, or what they perceive from error messages.  This output can be used for a concept map, which 
can be updated and built upon, bridging student language with disciplinary language while increasing sense-making.
****

== Discuss: (10 mins)
* What image functions did you and your partner discover? _Answers will vary: `rectangle`, `triangle`, `ellipse`, `circle`, etc.
* How did you decide what to try? _Answers will vary_
* What error messages did you see? _Answers will vary: Input mismatches, missing parentheses, etc._
* How did you figure out what to do after seeing an error message? _Answers will vary: Read the error message, think about what the computer is trying to tell us, etc._

*Every function has three important parts: the function's name, what it consumes, and what it produces.*

* How else could we refer to what a function consumes? _Answers vary: Input, what it 'takes in', arguments_

* How else could we refer to what a function produces? _Answers vary: Output, what it 'gives back', what the function evaluates to_

*Functions have different requirements, so we need to be able to keep track of them.  We can refer to what a function expects as the "domain" and what the function produces as the "range", just like we do for math functions.* 

// Copy to the workbook page
* Group together the image functions you discovered by elements in their domain. _``star``, `circle`, and `triangle` have the same domain, `rectangle` and `ellipse` have the same domain, etc._


// Copy to workbook page
* Star has three elements in its domain: A Number, a String, and another String.  What do these elements represent?
* What does star need in order to work?  What happens if I don't give it those things?
* If I give star what it needs, what do I get in return?

*When the input matches what the function expects, the function gives back the output we expect.  We call this agreement a "contract".*

== Practice: (10 mins)

Students complete _workbook page_ with their partner.

== Create: (10 mins) 

Students create a visual "Contracts page" either digitally or physically.  Ask students to think about how they visualize contracts in their own minds and how they could use that imagery to explain functions and their contracts to others.

