= Identifying Form, Direction and Strength

++++
<style>
table table {background: transparent; margin: 0px;}
td {padding: 0px !important;}
table table td p {white-space: pre-wrap;}
</style>
++++

Can you identify the Form, Direction, & Strength of these displays? *Note:* If the form is non-linear, there is no direction!

[cols="^.^1a,^.^15a,^.^1a,^.^15a", frame="none"]
|===
|*A*
| @centered-image{../images/A.gif, "", 350} 
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! *Linear* 	! Non-Linear 	! None
! *Direction*: 	! Positive 	! *Negative*	! None
! *Strength*: 	! *Strong* 	! Weak 			! None
!===

|*B*
| @centered-image{../images/B.gif, "", 350}
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! Non-Linear 	! *None*
! *Direction*: 	! Positive 	! Negative 		! *None*
! *Strength*: 	! Strong 	! Weak 			! None
!===

|*C*
| @centered-image{../images/C.gif, "", 350} 
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! *Linear* 	! Non-Linear 	! None
! *Direction*: 	! *Positive*! Negative 		! None
! *Strength*: 	! *Strong* 	! Weak 			! None
!===

|*D*
| @centered-image{../images/D.gif, "", 350}
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! *Linear* 	! Non-Linear 	! None
! *Direction*: 	! *Positive*! Negative 		! None
! *Strength*: 	! Strong 	! *Weak* 		! None
!===

|*E*
| @centered-image{../images/E.gif, "", 350}
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! *Non-Linear* 	! None
! *Direction*: 	! Positive 	! Negative 		! *None*
! *Strength*: 	! *Strong* 	! Weak 			! None
!===

|*F*
| @centered-image{../images/F.gif, "", 350}
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! *Linear* 	! Non-Linear 	! None
! *Direction*: 	! Positive 	! *Negative*	! None
! *Strength*: 	! Strong 	! *Weak* 		! None
!===

|===
