= Comparing Native American Food to That of Settlers and Modern Americans

@description{Students learn about differences in the diets of Northeastern Native Americans and modern Americans. Settlers ate mostly domestic animals and a few wild animals, while early Native Americans usually ate only wild animals. Students interpret data to make claims about these differences, and begin to consider whether the differences are more or less healthy. Later lessons will explore some causes of these differences.}

@lesson-prereqs{}

@keywords{}

@add-to-lang{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* analyze data and create pie charts to identify and explain some of the similarities and differences in the diets of early Native Americans, European settlers, and modern day Americans.
* Compare 4 quantitative data sets to see which have higher values.
* Compare two categorical datasets by displaying them.
* Review construction and interpretation of pie charts.

| Student-facing Lesson Goals
|

* Let's compare datasets using pie charts!

| Materials
|[.materials-links]

@material-links

|===

== Review

[.lesson-instruction]
Complete the @printable-exercise{do-now.adoc}

Prompt students to complete a turn and talk to share answers with their neighbor.

Call on select students to share out while revealing correct answers under the document camera.

== Comparing Food Habits

=== Overview

=== Launch

Yesterday we learned a lot about some of the things Native Americans in New England ate in the 1600s by looking at two primary sources from the National Archives. We then learned how Native Americans named land by how they used it instead of by who owned the land. Today, we will be learning even more!”

[.lesson-instruction]
Before we move on, let’s find out what you learned in your homework! What patterns did you discover from your interviews? Anything interesting?”

Have a few students share out.

“We will come back to these on Day 6 of our unit to discover the right answers! I can’t wait to see who can find them all!”

Today you will be investigating some findings from archaeological digs and reporting on the following questions:

- What did early American settlers in the Northeast eat and how did they get their food?
- How was this similar to Native American diets in that region from that time? How was it different?
- How does the average modern US American diet compare to that of Northeastern Native Americans in the 1600s?

Looking at the table from our @printable-exercise{do-now.adoc, Do Now}, we see that in the 1600s most of the New England Native Americans’ sources of protein were wild animals that they hunted on the land. They believed that the land was to be shared by everyone, rather than to be split into small parts (such as farms) owned by individuals.

We know from accounts that the settlers were different: they brought farm animals with them from Europe and set up individual farms. It makes sense that what settlers ate was different from what Native Americans ate.

////
How do the commons figure into this description?
////

=== Investigate

We are going to look at the findings from 5 archaeological dig sites to find out:

- How much of the settlers’ diets came from farm protein instead of wild protein?

[lesson-instruction]
Turn to @printable-exercise{data-inv1.adoc} and following along as I read the instructions.

After about 8 minutes, call on select students to share answers while revealing correct answers under the document camera.

[.lesson-instruction]
We are now going to complete @printable-exercise{data-inv2.adoc} to learn more about how the diets of New England Native Americans in 1600s differ from average modern US American diets.

The table focuses on calories, which measure how much energy someone gets from eating a particular food. A ten-year-old needs fewer than 2000 calories a day, while a grown man needs close to 2500.

Use the data presented here to answer the questions with your partner.


=== Synthesize

Call on select students to share answers while revealing correct answers under the document camera.

== Comparing Pie Charts

=== Overview

=== Launch

There’s a lot of data in the table on the last page. We would like to display the data visually. This will help us compare foods eaten by Northeastern Native Americans in the 1600s and foods eaten by modern US Americans. In particular, we want to compare the proportions of each kind of food for those two groups of people.

////
Do we want to be referring back to the Maya unit? Or do we want to re-teach how to create pie charts in Google Sheets?
////

[.lesson-instruction]
When we studied the Maya, we learned about two displays: pie charts and line charts. Which chart do you think we should use?

A @vocab{pie chart} is good for showing @vocab{proportions} of values taken by a @vocab{categorical variable}.

Which pie chart slice for the Native American diet will be larger: the one for grains or for proteins? (GRAINS!)

=== Investigate

[.lesson-instruction]
--
- Make a copy of the @starter-file{food-groups} and create pie charts for each dataset provided.
- Use your pie charts to fill in the missing labels on @printable-exercise{pie-chart-compare.adoc}.
- Answer the questions on @printable-exercise{pie-chart-compare2.adoc} with your partner.
--

=== Synthesize
Call on select students to share answers while revealing correct answers under the document camera.

Have students reflect on the following questions from the @opt-printable-exercise{journal.adoc}

- What did early European settlers eat and how did they get their food?
- How is our modern day diet similar to or different from that of Northeastern Native Americans in the past?
- Name at least 2 pieces of evidence we examined today:

== Homework

@printable-exercise{homework.adoc} tonight is to record what you ate yesterday to see how similar or different your food habits are in comparison with the Northeastern Native Americans of the 1600s! Enjoy!

