= Brainstorm Your Own Game

++++
<style>
#content h2 {
	text-align: left !important; 
	font-size: 	1rem !important;
	padding:	5px !important;
}
#content table, td {height: 305pt; width: 400pt; margin: auto; }
</style>
++++

Created by: @fitb{}{}

== Background

Our game takes place: @fitbruby{60ex}{}{In space? The desert? A mall?}

== Player

The Player is a @fitb{}{}
@vspace{3ex}

The Player moves only up and down.

== Target

Your Player GAINS points when they hit The Target.
@vspace{3ex}

The Target is a @fitb{}{}
@vspace{3ex}

The Target moves only to the left or right.

== Danger

Your Player LOSES points when they hit The Danger.
@vspace{3ex}

The Danger is a @fitb{}{}
@vspace{3ex}

The Danger moves only to the left or right.

== Artwork/Sketches/Proof of Concept
Below is a *640x480 rectangle*, representing your game screen.

- Label the bottom-left corner (0,0).
- Label the other three corners with their corresponding coordinates.
- In the rectangle, sketch a picture of your game!

[.FillVerticalSpace, options="frame",stripes="none"]
!===
|
!===
