[.beta]
= Introduction to Artificial Intelligence

@description{Students explore the "AI effect", think about measuring similarity, and then consider characterizations of AI in popular culture. }

@lesson-prereqs{}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|
- Let's think about the "AI effect."
- Let's consider the relationship between Machine Learning and Artificial Intelligence.
- Let's think about similarity.

| Materials
|[.materials-links]
@material-links
|===

== What is AI?
@objective{ai-different-kinds}

=== Overview
Students explore different examples of how people use AI every day, including a mix of recommendation systems and classifiers. Students discover the challenges of defining AI, and think about whether AI is just an algorithm, or something more.

=== Launch
@slidebreak{Launch}

Who here has ever used AI? Raise your hand if you've used an AI tool, or know someone who has.

@QandA{
@Q{What are some examples of AI tools you've seen?}
@A{Gemini, ChatGPT, etc}
@A{When Spotify or YouTube recommends a song or video}
@A{When I play video games against the computer}
@A{Self-driving cars}
@A{Facial recognition}
}

@slidebreak{LaunchR}
@right{@image{images/flow-chart.gif, 400}}

@lesson-point{Is it _thinking_, or is it just _following an algorithm_?}

The first spell-checker was written in 1961. It had a 10,000 word dictionary, and it would check every word you typed to see if it was in the dictionary. It wasn't really _thinking_. It was just following an @vocab{algorithm} -- a series of steps that tell a computer how to perform a task -- in this case mechanically comparing strings of letters against a long list. And all it could do was tell you if a word _was_ or _wasn't_ spelled correctly.


@slidebreak{Launch}
In 1971, however, a new spell-checker arrived from the Stanford Artificial Intelligence Laboratory called SPELL. SPELL wouldn't just tell you if a word was misspelled - it would _suggest alternative words_ that you might have intended! People were *floored*, and swore that AI had arrived. After all, "how did the computer know what we intended to write?"

Was SPELL _thinking_, or was it, too, just _following an algorithm_?

@lesson-instruction{
- Form groups of 2-3.
- How do you think SPELL knew what words to suggest?
- Be ready to share your ideas with the class!
}

@teacher{Give time for productive discussion about possible algorithms.}

@slidebreak{Launch}

Here's SPELL's algorithm for checking a word:

@indented{
(1) If the word is in the dictionary, we're done!

(2) If it's _not_ in the dictionary, find words that are "near" the misspelled word (one letter off, two letters swapped by accident, etc.)

(3) See if any of _those_ words are in the dictionary, and suggest them as alternatives
}
SPELL had no idea what those alternative words meant. It didn't even know what a word _was!_ And it definitely didn't know what people were thinking when they typed. *It was just an algorithm.*

@slidebreak{LaunchR}
@right{@image{images/mccarthy.png, 200}}

After a while, most people stopped calling spell checkers AI. But in the early 2000s, cell phones introduced a feature called "predictive text": when you start typing a sentence, the phone makes suggestions about what the next word should be. People were *floored*, and swore that AI had arrived...but eventually they stopped calling predictive text AI, too.

Computer scientist @link{https://en.wikipedia.org/wiki/John_McCarthy_(computer_scientist), John McCarthy} developed the term "AI effect" to describe this phenomenon: humans keep _moving the goalposts_ for what counts as "Artificial Intelligence" and what counts as "Human Intelligence"! In other words, "As soon as it works, no one calls it AI anymore."


=== Investigate
@slidebreak{Investigate}
@lesson-point{Is it _thinking_, or is it _following an algorithm_?}

Which of these technologies falls into which category?

@indented{
[cols="1a,1a", grid="none", frame="none"]
|===
|
- Talking to Gemini, ChatGPT, etc
- Uploading a photo to a "What bird is this?" app
- Getting a music recommendation from Spotify
- Getting a video recommendation from YouTube
- A spam filter in you email program
- A self-driving car
- Spell Checkers
|
- A computer-opponent in a game like Tic-Tac-Toe, Call of Duty, etc.
- Facial Recognition
- Dating apps that recommend matches
- A program that does your homework
- Predictive Text (suggestions as-you-type)
|===
}

@lesson-instruction{
- With your group, see if you can sort this list into "thinking" or "following an algorithm".
- Can you describe the rules you're using to decide which is which?
- Be ready to share back and discuss with the class!
}

=== Synthesize

@QandA{
@Q{What did the class mostly agree were examples of *thinking*?}

@Q{What did the class mostly agree were examples of *following an algorithm*?}

@Q{What kinds of criteria did you come up with, to tell them apart}

@Q{Are you starting to wonder if AI does any thinking at all?}
}

@teacher{The point of this section is *not* to claim that AI isn't anything new, or that it's not a really impressive advancement. It is! Instead, the purpose of this section is to dispel the misconception that AI is "thinking", rather than following a prescribed algorithm.}


== Different Kinds of AI
@objective{ai-machines-v-people}

=== Overview
Students learn that AI is actually a collection of technologies involving Machine Learning, and begin thinking about how they might work.

=== Launch
@slidebreak{Launch}

Modern AI is largely driven by a set of techniques called @vocab{Machine Learning} (ML for short). AI relies so deeply on Machine Learning that many computer scientists just call it "AI/ML".

There are many kinds of Machine Learning algorithms out there, and nearly every example we've come up with falls into one of three categories:

[cols="^1a,^1a,^1a"]
|===
| @image{images/prediction-bots.webp, 250}
| @image{images/recommendation-bot.png, 200}
| @image{images/chat-bot.png, 250}

| *Prediction* +
"Given an input, predict an output" +
Facial recognition, Credit Scores, etc. +

| *Similarity* +
"Given an input, find likely matches" +
Spotify, dating apps, etc.

| *Generation* +
"Make up a story - with pictures! - about an elephant" +
ChatGPT, Stable Diffusion, Gemini, etc.
|===

@slidebreak{Launch}

In Machine Learning, the computer analyzes lots of @vocab{data}, and then identifies patterns in that data using statistics. Machine Learning can be applied to an incredibly diverse set of data (text, maps, pictures, movies, songs, etc), to make predictions, find similarity, and even generate new images, stories, etc.

While AI is often spoken about as if it's something "magical", Machine Learning is actually very concrete: it is just a collection of @vocab{algorithms}!

Let's play with some real tools that use AI, and see if we can make sense of how they might be working...

=== Investigate
@slidebreak{InvestigateR}
@right{@image{images/classifier-bot.png, 250}}

There are several kinds of *predictive models* you probably interact with every day!

@vocab{Classification Models} - also called @vocab{classifiers} - are all about *predicting categories*:

- Is this junk mail or not?
- Is this person a kid, a teenager, or an adult?
- Is this customer likely to buy a video game or not?
- Which Harry Potter house would I be in?

@slidebreak{InvestigateR}
@ifslide{@right{@image{images/classifier-bot.png, 250}}}
@lesson-instruction{
@online-exercise{https://www.nyckel.com/pretrained-classifiers/flowers-identifier/, This link } will take you to an example of a Machine Learning tool that consumes an image of a flower, and tries to predict what *category* of flower it really is.

- Find an image of a flower, and drag it into the box
- What part(s) of the image do you think it's looking at, to make its prediction?
}


@slidebreak{Investigate}
@lesson-instruction{
- Let's think a little about how classifiers might work!
- With a partner, complete the first section on @printable-exercise{predictive-models-classifiers.adoc}
- Be ready to share back!
}

@slidebreak{InvestigateR}
@QandA{
@ifslide{@right{@image{images/classifier-bot.png, 250}}}
@Q{Did the classifier do a good job identifying the flowers?}
@A{Yes}

@Q{What did you notice about the differences between the two flower images?}
@A{Shape...tint...smooth v. ruffled edges on the petals}

@Q{How do you think it's reporting "confidence?"}
@A{Maybe it some definition of "rose-ness", and it's just computing how far off the definition of *this rose* is from the one it knows}
}

@slidebreak{Investigate}
@lesson-instruction{
- You just looked at a _categorical_ classification problem: every flower image belongs to one category of flower.
- Sometimes a classifier is just choosing between *two* categories: 
  * "Is this animal a dog or a cat?"
  * "Is this photo of a young or old person?", etc.
- Let's explore a classifier with more than two outputs, by completing the last section on @printable-exercise{predictive-models-classifiers.adoc}
- Be ready to share back!
}

@slidebreak{InvestigateR}
@QandA{
@ifslide{@right{@image{images/classifier-bot.png, 250}}}
@Q{What were your predictions for each row?}
@A{There's no right answer here - the important part is to see how much agreement or disagreement there is in the class}

@Q{Why didn't we all make the same predictions?}
@A{We made different decisions about which columns we valued most}

@Q{Which column was the *most helpful* in classifying the species? Why?}
@A{...answers will vary...}
@A{`legs` immediately classifies snails (0), tarantulas (8), and everything else (4)}
@A{`pounds` immediately classifies dogs (generally heaviest), cats (generally in the middle), and everything else (very light)}
}

@slidebreak{InvestigateR}
@right{@image{images/prediction-bots.webp, 250}}

But Classifiers aren't the only kind of prediction system out there!

@vocab{Regression} is all about *predicting values*:

- How many 3-pointers do we predict for player who is 6'5"?
- How long do we predict a person will live, based on an income of $95,000?
- How likely is it a student will do well in college, based on an SAT score of 1028?

@slidebreak{InvestigateR}
@ifslide{@right{@image{images/prediction-bots.webp, 250}}}

@lesson-instruction{
- Let's think a little about how regression models might work!
- Have you ever taken one of those silly online quizzes, which claims to predict how long you'll live or how much money you'll make based on a few questions?
- With a partner, complete the first section of @printable-exercise{predictive-models-regression.adoc}.
- Be ready to share back!
}

@slidebreak{Investigate}
@QandA{
@Q{What variables did you come up with?}

@Q{Were any of your slopes negative? What would be an example of a negative slope?}
@A{Example: Number of packs of cigarettes smoked per week}

@Q{If all the variables are zero, how long does your quiz predict someone will live?}

@Q{Why is that called y-intercept?}
}

Humans try to come up with formulas to help us make predictions about everything from when it will rain to how likely it is that you'll pay back a loan. These predictions are based on *data*, rather than guesses like "cats make a person live longer". Let's look at some real data and try to make a prediction...

@lesson-instruction{
- Complete the rest of @printable-exercise{predictive-models-regression.adoc}.
}

@slidebreak{InvestigateR}

@QandA{
@right{@image{images/pounds-v-weeks.png, 250}}
@Q{What did you notice about the scatter plot?}
@A{There seemed to be a pattern}
@A{Some dots were really far away from the others!}
@A{A lot of dots were clustered on the left}

@Q{What kind of pattern did you see?}
@A{A line sloping up as we go to the right}
}

@teacher{If you have a projector and a whiteboard, this is a great time to have students draw their different lines of best fit on the board!}

Pretty much everyone saw a line with a positive slope, but they didn't necessarily see the _exact same_ line.
@lesson-instruction{
- Complete the first section of @printable-exercise{predictive-models-regression.adoc}
- Be ready to share back!
}

@slidebreak{InvestigateR}

@QandA{
@ifslide{@right{@image{images/pounds-v-weeks.png, 250}}}
@Q{How long did you predict it would take Daisy to be adopted? Maple?}
@A{Answers will vary}
@A{Could we write the equation for this line?}
@A{Right now we're drawing our line based on a scatter plot of every kind of animal. Would we get a better fit if we just looked at each species separately?}
@A{Probably! Each species must have a growth rate that can be graphed, but by combining all of them we get a line that's a mix of all the different species, and not good at predicting any individual one.}

@Q{Is there another column of numbers we could use to predict adoption time?}
@A{Age}
}

@slidebreak{InvestigateR}
@right{@image{images/recommendation-bot.png, 200}}

Similarity and Recommendation Models are all about *measuring differences*:

- Which songs are most like this one?
- Which people on a dating site are the best matches for this person?
- Which essays are the most similar to this one?

@link{https://open.spotify.com/, Let's try out an example in Spotify!}

@teacher{Search for a song that your students will recognize, making sure to filter by "songs". When you hover over any of the songs in the search results, you'll see a three dots (`...`) appear on the right. Click these dots and select "Go to Song Radio"}

@slidebreak{InvestigateR}
@ifslide{@right{@image{images/recommendation-bot.png, 200}}}

How similar were Spotify's recommendations to the original song?

@lesson-instruction{
- Let's think a little about how similarity models might work!
- With a partner, complete @printable-exercise{similarity-learning.adoc}
- Be ready to share back!
}

@slidebreak{InvestigateR}
@right{@image{images/recommendation-bot.png, 200}}

@QandA{
@Q{What do you think Spotify was paying attention to, when it recommended similar songs to the one we chose?}
@A{Answers will vary (volume, duration, speed...)}

@Q{When you upload an image to @link{https://www.google.com, Google Search}, what does it pay attention to when recommending similar images?}
@A{Answers will vary (brightness, color, symmetry...)}
}

@slidebreak{InvestigateR}
@right{@image{images/chat-bot.png, 250}}

*Generative Models* look for *patterns and frequency in language*. In fact, they are often called "language models"

- LMs trained on _English_ can be "chat bots", and generate English responses to questions
- LMs trained on _Spanish_ can be "chat bots", and generate Spanish responses to questions
- LMs trained on _Music_ can be "music bots", and generate music
- LMs trained on _Drawings_ can be "art bots", and generate images
- LMs trained on _Tic Tac Toe_ can be "tic tac Toe tots", and generate moves in the game

@slidebreak{InvestigateR}
@ifslide{@right{@image{images/chat-bot.png, 250}}}

@link{https://duck.ai/, Here's an example of an ML tool} in the form of a chatbot: it generates text in response to what you write, based on patterns it has picked up by processing trillions of examples.

@teacher{Give students 1-2m to try chatting}

We'll get to Language Models in a later lesson, but for now the important thing is to realize that this is yet another kind of @vocab{Machine Learning}.

=== Synthesize
TBD - give students examples of use-cases, and have them identify the kind of ML at work



== What _is_ a Model, Anyway?

=== Overview
Students begin to think about the meaning of the term "model", which is a broad term that different disciplines use in subtly different ways. Note that the goal of this section is to give them the beginning of an intuition for thinking about models, _not_ a rigorous definition!

=== Launch
@slidebreak{Launch}
In this lesson, you've already seen the word "model" being used when it comes to AI. We've talked about Prediction Models such as Classification Models and Regression Models. We've talked about Generative/Language Models, and you probably know some famous ones like GPT, Gemini, or Claude.

But what IS a model, anyway?

@slidebreak{Launch}
@lesson-point{A model is a mathematical summary of a dataset}

Defining the term "Model" is actually pretty hard, because different disciplines would define the same word in slightly different ways! But what they all have in common is that models are used to _represent a dataset_, and to do so in a more compact way. When we summarize an essay, we're trying to *identify the main ideas* and *leave the rest behind* - models do the same thing with data, identifying the most important patterns or structures and leaving the rest behind.

@slidebreak{Launch}
All Models summarize features of a dataset, and all models leave some details out!

You may already be familiar with some simple mathematical models:

- Mean, median, and mode are different ways of summarizing the "center" of a list of numbers, but they leave out the original list
- A line of best fit summarizes the relationship between points in a scatter plot, but they leave out the original points

Both of these tell us something about a feature of the original dataset, and leave out the less important details.


@strategy{Not all Definitions are Black and White!}{
Someone with a background in Machine Learning would argue that the average of a list of numbers isn't a models at all! In Machine Learning, models are typically used to _make predictions_. A mathematician would disagree.

The fact is that these lines are somewhat blurry, and for an introductory class we've tried to use a least-common-denominator approach by focusing on two main ideas that are common across every discipline: (a) models summarize the features of a dataset, and (b) that summary leaves out parts of the dataset.
}

=== Investigate
@slidebreak{Investigate}
@lesson-point{All models are wrong. Some are useful.}

By definition, a model leaves out some details about the original dataset.

- Rush hour is generally between 4:30-6:30pm (but not on holiday weekends!)
- White is the most common color of car in the world (but millions of cars are not white!)

The goal of a model is not to be right every time, but to be _right enough to be useful_. Both of the generalizations above are wrong sometimes. But if you're planning a road trip, only one is useful.


@slidebreak{Investigate}

@QandA{
@Q{Can you come up with your own example of a model?}
@A{Some ideas:
- A height, weight, or BMI chart at the doctors office (a summary of the growth of a population)
- Weather prediction (a summary of environmental trends and relationships)
}

@Q{When is your model wrong?}
@A{A bodybuilder has a dangerously high BMI, but they're not actually unhealthy}
@A{Weather reports might misjudge how hot it will get, or whether it'll rain}

@Q{Is your model useful?}
@A{Responses will vary}
}


=== Synthesize
@slidebreak{Synthesize}
Models summarize the features of a dataset, and leave out the details

@QandA{
@Q{What features do you think our flower classifier was looking at, when comparing a picture to different species of flower? What was it ignoring?}
@Q{What features do you think Spotify looks at, when comparing a songs? What does it ignore?}
@Q{What features did YOU look at when predicting adoption time for animals in our shelter? What did you ignore?}
}