= Permutations

++++
<!--

Visme URLs for tree diagrams: 
- https://my.visme.co/view/epd0w63y-permutation-and-combination-2
- https://my.visme.co/view/8rerg1ee-permutation-and-combination
-->
++++

@lesson-description{Students compute the possible number of outcomes using combinations and permutations.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-defining-functions}
| Lesson Goals
| Students will be able to...

* 
* 
* 

| Student-facing Lesson Goals
|

* 

| Materials
|[.materials-links]
* @link{TODO, Lesson Slides}

@material-links

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Supplemental Resources
| 

@include{xtra/lang-prereq.adoc}
|===

== Permutation with Replacement

=== Overview
Students are introduced to the concept of @vocab{permutation} (with replacement). They  compute a number of permutations by hand using tree diagrams, then learn the formula for computing permutations with replacement.

=== Launch
@span{.right}{@image{images/Pizza.png}}
Luigi's Family Restaurant is about to open, and it's going to be the hottest restaurant in town. They have a menu with six different dishes, and they plan to offer a four-course "Italian Safari" dinner for the low-low price of $9.95 per person. The gimmick is that diners can __choose the order of the courses:__ you might start with lasagna, but your friend can start with the Chicken parmesan, and so on. And if your friend happens to really, *really* like Chicken parmesan, they can choose to eat it for all four courses!

They advertise "an almost-endless number of dining experiences". In fact, Luigi himself guarantees free food for life for anyone who can eat every possible configuration. If you ate dinner there every night, how long would it take to try each one? In other words, __how many ways can you reshuffle those four courses__?

[.lesson-point]
In Permutations, order matters!

Luigi isn't going to give away free food just because you order four courses - he wants you to order four courses _in every possible order_! In situations where order matters, the set of possible options is called @vocab{permutations}. 

[.lesson-point]
With or without replacement?

In some restaurants, you're not allowed to order the same item for more than one course. In other words, __once you've picked lasagna, it's no longer on the menu for your next course!__ This is called *permutation _without_ replacement*.

Luigi is a nice guy, so once you order lasagna it is "replaced" with the option to order it again for the next course! This is called *permutation _with_ replacement*.

With six dishes to choose from and four courses to eat, how many @vocab{permutations} are there? How many meals would we have to eat, to get free food for life?

=== Investigate

[.lesson-instruction]
--
Luigi has six possible dishes to choose from. Discuss:

- How many permutations could there be for a 1-course dinner?
- How many permutations could there be for a 2-course dinner?
- How many permutations could there be for a 3-course dinner?
- Is there a pattern here?
--

It's useful to use __tree diagrams__, so we can see what our possible choices are.

Let's diagram the permutations for a 1-course meal. With six menu items, a 1-course meal could be Lasagna, Pizza, Chicken, etc... That means the set of all possible 1-course @vocab{permutations} has six different meals. In less than a week, we'd have tried all the possibilities!

@span{.center}@image{images/6-1-course-permute-w-replacement.png}

But what about a 2-course meal? Each of our 1st-course choices has __another tree__ underneath it! After we've picked our first course, how many options do we have for the second? If we choose Lasagna for our first course... we can choose it again for the second course or we can choose any of the other options, which means we still have six choices. In other words, someone could order Lasagna & Lasagna, Lasagna & Pizza, Lasagna & Chicken, Lasagna & Ravioli, Lasagna & Soup, or Lasagna & Ziti.  That's six possible orders with Lasagna as the first course. Each of the other first course options also comes with six possible second course order options... that's @math{6 \times 6} ! So, instead of taking six days to try all the permutations, now it takes __36 days__ - more than a month!

@span{.center}@image{images/6-2-course-permute-w-replacement.png}

Every time we get to make a choice, each endpoint in our tree sprouts six more branches. 

[.lesson-instruction]
How many permutations would there be in a 3-course meal?

We had 36 possible 2-course meals, so choosing a third course means that each "endpoint" of our 2-course meal tree now has six possible branches! @math{6 \times 6  \times 6 = 6^3 = 216} possible 3-course meals.

For a 4-course meal, we have a _four-level_ tree with six branches at every level! That's @math{6 \times 6 \times 6 \times 6} - or @math{6^4} possible permutations!

The number of @vocab{permutations} is computed based on two things:
. The number of possible menu __items__ (lasagna? Chicken? Soup?)
. How many times we get to __choose__. (1-course meal? 3-course meal?)

Let's see this as a function:

@math{permute\mbox{-}w\mbox{-}replace(items, choose) = choose^{items}}

@math{permute\mbox{-}w\mbox{-}replace(6, 1) = 6^{1} = 6}
We have 6 possible one-course meals...


@math{permute\mbox{-}w\mbox{-}replace(6, 2) = 6^{2} = 36}
We have 36 possible two-course meals...

@math{permute\mbox{-}w\mbox{-}replace(6, 3) = 6^{3} = 216}
We have 216 possible three-course meals...

How many permutations are there for a 4-course meal chosen from Luigi's 6-item menu?

@math{permute\mbox{-}w\mbox{-}replace(6, 4) = 6^{4} = 1296}

With four courses, it would take more than __3.5 years__ to try them all -- if we ate dinner at Luigi's every night!

=== Synthesis

What are some other examples of permutation? (Password strength, guessing combination locks...)



== Permutation without Replacement

=== Overview
Students build on their understanding of @vocab{permutation}, now extending it to situations _without_ replacement. They compute a number of permutations by hand using tree diagrams, then learn the formula for computing permutations without replacement.

=== Launch
After a few months, Luigi realizes that he's losing money. He could either raise his prices, or streamline the cooking process. His daughter observes that there's no way to predict how many ingredients to buy, since some people might want four courses of Soup and others might want four courses of ziti. Without being able to predict the ingredients, Luigi winds up buying too much of one thing and not enough of another - resulting in a lot of wasted food and unhappy customers!

Luigi proposes an important change to his "Italian Safari deal": **No item can be ordered twice.**

He also decides to simplify his menu even further, down to just **four different options**.

With no one ordering four of the same thing and far fewer choices to make, it's a lot easier to predict what to buy, so it will waste less food and save Luigi a lot of money.

Now how long would it take to try every permutation?

Let's start by drawing the tree diagram for 1st place:

@span{.center}@image{images/4-1-course-permute-wo-replacement.png}

There are *four* possible items we could eat for our first course, so we have 4 possible branches. After we eat that course, it's time to order the second course! How many branches are there for the second course, under each first course choice?

@span{.center}@image{images/4-2-course-permute-wo-replacement.png}

We can't order the same thing twice so, once we've eaten Pizza for the first course, there are only _three_ possible items left to choose from: Chicken, Ravioli and Soup. If we start with Chicken, we can't order Chicken again, but we can choose from Pizza, Ravioli & Soup for our second course. No matter what we choose for our first course, we still have three choices left for our second course. This is called @vocab{permutation} *without replacement*. Now there are only @math{4 \times 3 = 12} permutations, instead of the 16 we'd have with replacement.

We can visualize our four courses as a four-level tree, with each set of branches getting smaller and smaller until there's only one option left. In the tree diagram below, you can see a _partial_ drawing of all four courses.

@span{.center}@image{images/4-4-course-permute-wo-replacement.png}

If we start with Chicken, we can order: 

- Chicken, Pizza, Ravioli & Soup
- Chicken, Pizza, Soup & Ravioli
- Chicken, Ravioli, Pizza & Soup
- Chicken, Ravioli, Soup & Pizza
- Chicken, Soup, Ravioli & Pizza
- Chicken, Soup, Pizza & Ravioli

That's six different orders starting with one first course option and we have four different first course options.

We can compute the number of permutations-without-replacement with the factorial function. @math{4 \times 3 \times 2 \times 1 = 4! = 24}

Now we could try all the permutations in just under a month!

**Luigi decides this makes it too easy, and now that his kitchen is running smoothly he decides to bring back the original six-item menu.**

In this situation, there might be six items on the menu, but we want to __stop multiplying after the first four items are chosen__.

@math{6 \times 5 \times 4 \times 3 = 360} 

We can write this by starting with our factorial notation from before (where every number from 6 to 1 is multiplied), and then "undoing" the @math{2 \times 1}. This takes the form of __dividing__:

@math{\frac{6 \times 5 \times 4 \times 3 \times 2 \times 1}{2 \times 1} = \frac{6!}{2!} = 360}

With this number of possible combinations, it would take almost a year to try them all! And with less wasted food and a faster kitchen, Luigi has a lot of happy customers and a lot of money in the bank.

We can write this relationship as a function:

@math{permute\mbox{-}no\mbox{-}replace(items, choose) = \frac{items!}{(items - choose)!}}

[.lesson-instruction]
For practice, complete the @opt-printable-exercise{permutation.adoc} worksheet.

=== Synthesize

- What is the difference between permutation with or without replacement?

- What are some real-world examples of each?

== Additional Exercises:
TODO