= Function Notation

@description{Students learn to read function notation.}

@lesson-prereqs{functions-make-life-easier}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* Identify the value that an expression such as f(3) produces from a function definition, table, or graph.

| Student-Facing Lesson Goals
|
* I can find the value of an expression such as f(3), given a table, graph or equation defining f(x).

| Materials
|[.materials-links]
@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/1uDxsuY87FFkeMowOOU6WImTdfeQLaJm8iEroE6nDsmY/, Lesson Slides}
}
@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/10mZzi6_jEIcAd4v9zdFiGHij_PNc98d3myeoLNUuuYM/, Lesson Slides}
}

@material-links

| Preparation
| @preparation

|===

== Function Notation (Definitions) @duration{15 minutes}

=== Overview

Students connect their understanding of functions definitions in Pyret to function definitions in math.

=== Launch

We've seen how functions like `gt` can be defined, and then @vocab{applied} to a number to create a green triangle. And once `gt` is defined, we can use it with many different numbers to create many different triangles - all without having to write out `"solid"`, `"green"`, etc.

But how does this function _work?_

When we apply a function to the inputs it needs, we *substitute* those inputs for the variables in the definition.

@show{(code '(define (gt size)(triangle size "solid" "green")))}

[cols="^.^2,^.^3,^.^1", options="header"]
|===
| Function Application 		| Substituted Input				| Final Product
| @show{(code '(gt 10))}	| @show{(code '(triangle 10 "solid" "green"))} 		| @image{images/gt10.png, green triangle 10}
| @show{(code '(gt 20))}	| @show{(code '(triangle 20 "solid" "green"))} 		| @image{images/gt20.png, green triangle 20}
| @show{(code '(gt 30))}	| @show{(code '(triangle 30 "solid" "green"))} 		| @image{images/gt30.png, green triangle 30}
| @show{(code '(gt 40))}	| @show{(code '(triangle 40 "solid" "green"))} 		| @image{images/gt40.png, green triangle 40}
| @show{(code '(gt 50))}	| @show{(code '(triangle 50 "solid" "green"))} 		| @image{images/gt50.png, green triangle 50}
|===

@vspace{1ex}

Math books use Function Notation to define functions, too, though most of the time their functions only work with numbers - and certainly not images! Just as in programming, *we compute the value of the expression for any specific input by substituting numbers for the variable(s) used in the definition*, just as we did with `gt`.

@show{(code '(define (f x) (+ x 8)))}

[cols="^.^2,^.^3,^.^1", options="header"]
|===
| Function Application 	| Substituted Input 		| Final Product
| @math{f(10)} 			| @show{(code '(+ 10 8))} 	| 18
| @math{f(20)} 			| @show{(code '(+ 20 8))} 	| 28
| @math{f(30)} 			| @show{(code '(+ 30 8))} 	| 38
| @math{f(40)} 			| @show{(code '(+ 40 8))} 	| 48
| @math{f(50)} 			| @show{(code '(+ 50 8))} 	| 58
|===

=== Investigate

Have students turn to @printable-exercise{pages/match-examples-definitions-math.adoc} and @printable-exercise{pages/function-notation-substitution.adoc}.

[.lesson-instruction]
- Start by looking at each table and highlighting what is changing from the first row to the following rows.
- Then, match each table to the function that defines it.

You may also want to have students complete @opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/60aa5c452505ed0802bfff38, Matching Examples & Function Definitions (Math)}

=== Synthesize

[.lesson-instruction]
You can think of @math{f(3)} as a question.
* What question is it asking you to evaluate?
** _What is the value of @math{x + 8} when @math{x} is 3?_
* What is another way you can ask it?
** _What is @math{3 + 8}?_

== Function Notation (Graphs) @duration{15 minutes}

=== Overview

Students will learn to connect function definitions to Graphs.

=== Launch

[.lesson-instruction]
--
If @math{f(x) = x - 5}, what is the value of @math{f(7)}, and why?

** _@math{2}. Because if we substitute 7 for x we get @math{7 - 5 = 2}_

Let's take a look at the graph of @math{f(x) = x - 5}...
--

@centered-image{images/gr1.png, "graph of the line f(x) = x - 5", 350}

[.lesson-instruction]
* How could we have determined that @math{f(7) = 2} from looking at the graph, if we hadn't started with the function definition?
** _We could have looked for a point whose x-coordinate was 2 and found the point (7, 2), the y-value is 2, which tells us that the output of the function when x is 7 is 2._
* From looking at the graph, what is the value of @math{f(3)}?
** _-2_
* What other values on this graph could we describe using function notation?
** _Answers will vary... for example, @math{f(0) = -5} ...or... @math{f(0.5) = -4.5}_

We don't need to know a function definition in order to use function notation to describe a value with an expression! Let's take a look at the scatterplot below.

@centered-image{images/sp.png, "scatterplot: (-4,1), (-2,-4), (-1,4), (-3,-3), (1,2), (2,4), (4,-1)", 350}

[.lesson-instruction]
* From looking at the graph, what is the value of @math{f(-2)}?
** _-4_
* What is the value of @math{f(1)}?
** _2_
* What is the value of @math{f(3)}?
** _There isn't one! It's undefined._
* What other values on this graph could we describe using function notation?
** _Answers will vary... for example, @math{f(-1) = 4} ...or... @math{f(2) = 4}_

[.lesson-point]
This works for even more complex functions, which we haven't seen yet!

When evaluating an expression for a piecewise function, points on the graph marked with hollow circles are boundary points, but not part of the solution set, so we ignore them and focus on the solid points. For example, on the graph below, when evaluating @math{f(2)}, we ignore the hollow point at @math{(2, 4)} and focus on the solid point at @math{(2,3)}, so @math{f(2) = 3}.

@centered-image{images/pw.png, "graph of a piecewise function with 4 separate curvy and linear sections. Hollow endpoints at (0,2.5) and (2,4). solid endpoints at (0,3) and (2,3)"}

[.lesson-instruction]
* What is the value of @math{f(0)} in the graph above?
** _3_

=== Investigate

Have students complete @printable-exercise{function-notation-graphs.adoc}.
If you're ready to engage them with piecewise functions, have them complete @opt-printable-exercise{function-notation-graphs-pw.adoc}.

=== Synthesize
[.lesson-instruction]
* Can you think of any values that it would be difficult to determine from one of these graphs?
** _It would be hard to be precise for many of the points on the graphs that curve. For example, @math{f(4)} on the second graph would have to be a decimal value and it's hard to know exactly what the decimal should be without a function definition to evaluate..._

== Function Notation (Tables) @duration{15 minutes}

=== Overview

Students will learn to connect function definitions to input-output Tables.

=== Launch

[.lesson-instruction]
* Let's take a look at a table of input-output pairs that satisfy the function @math{f(x) = x - 5}, and think about how could we have determined the value of @math{f(7)} from looking at the table.
** _We would just look for 7 in the x-column and see that the value beside it is 2._
* Looking at the table, what is the value of @math{f(-10)}?

@vspace{1ex}

[.sideways-pyret-table]
|===
| x | -10 | -5  | 5 | 7 | 13
| y | -15 | -10 | 0 | 2 | 8
|===

=== Investigate

Have students complete @printable-exercise{function-notation-tables.adoc}

=== Synthesize

[.lesson-instruction]
* What did you Notice?
* What did you Wonder?
* A few of the tables did not represent functions. Which ones?
** _the last one in the top row, the last one in the middle row and the 3rd one in the bottom row._
* How did the fact that those tables weren't functions impact our ability to describe a value using function notation?
** _When x appeared more than once in the table and was associated with different outputs, it wasn't clear what number the expression should evaluate to._

