= Exploring Image Functions

++++
<style>
.lesson-section-1 { border: 0px !important;	}
.big 			  { font-size: 60pt;		}
</style> 
++++

By now you know how to make stars in this programming language. Can you figure out how to make triangles, based on what you know about making stars? Rectangles? What other shapes might we be able to make? When you've discovered code to make a new shape, draw the Circle of Evaluation in the table below, along with a sketch of the shape. Then add the function to your contracts page.

@vspace{1ex}

1) Use the space below to draw the Circles of Evaluation for the new functions, and draw a picture of what the function produces.

[cols="^.^24,^.^8,^.^8", options="header", stripes="none"]
|===
|Circle of Evaluation 							|				 | Image
|@show{(sexp->coe '(star 50 "solid" "black"))}	| produces &rarr;|@span{.big}{&#9733;}
|@vspace{3ex}									| produces &rarr;|
|@vspace{3ex}									| produces &rarr;|
|@vspace{3ex}									| produces &rarr;|
|@vspace{3ex}									| produces &rarr;|
|===

== Mystery Functions!

2) There is a function called `regular-polygon` with 4 inputs. What do they mean?

@span{.blankline}{The first input is the size. The second input is the number of sides of the regular polygon.}

@span{.blankline}{The third input is whether the figure is solid or outline. The fourth input is the color.}

@vspace{1ex}

3) There is a function called `radial-star` with 5 inputs. What do they mean?

@span{.blankline}{The first input is the number of points in the star. }

@span{.blankline}{The second and third inputs are the outer and inner radius of the star.}

@span{.blankline}{The fourth input is whether the star is solid or outline. The fifth input is the color.}

@vspace{1ex}


4) There is a function called `text`. Try to figure out how to use it! What do the inputs mean?

@span{.blankline}{The first input (a String) is the string we want to display.}

@span{.blankline}{The second input (a Number) tells us how big to print that string.}

@span{.blankline}{The third input tells us what the color will be.}

