= The Associative Property

@description{This lesson introduces students to the Associative Property by way of Circle Transformations.}

@lesson-prereqs{commutative-property}

@keywords{Associative Property}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Recognize that, no matter how we group numbers being either added or multiplied, the end result will always be the same.
* Demonstrate their understanding of the Associative Property via transformations of Circles, numeric expressions, and words.

| Student-facing Lesson Goals
|

* Let's explore the Associative Property via Circles of Transformation.

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
* Just as when we introduced the Commutative Property, we asked students exclusively to manipulate the order of the values... when we introduce the Associative Property, we will ask students exclusively to manipulative the groupings of the values.
* Students will encounter opportunities to apply both properties at the end of this lesson, and in future lessons.
|===

== The Associative Property @duration{30 minutes}

=== Overview

Students analyze pairs of Circles to determine if they have been manipulated in a valid way. The Circles make visible the structural changes that occur when we apply the Associative Property.

=== Launch

The Associative Property defines an equivalence relation over structures, such that "adding 4 to the sum of 3 and 2" is equivalent to "adding the sum of 4 and 3 to 2." In the short term, familiarity with the Associative Property enables students to make mental computations more efficiently. In the long term, comfort with the laws of arithmetic will provide a strong foundation for more complex algebraic reasoning.

[.lesson-instruction]
- Turn to Discover the Associative Property. Look at the first problem. What do you Notice about the two Circles? What do you Wonder?
** _Possible noticings: They both have the same numbers, 2, 5, and 10. They both have a circle within a circle. The operator is multiplication. Both circles evaluate to 50._
** _Possible wonderings: Could I use different numbers and still get the same outcome for both circles? Could I use different operators and still get the same outcome for both circles?
Work through the remaining problems with your partner. Be sure to evaluate the circles to confirm if they produce equivalent outcomes._
- What did you observe about the Associative Property?
** _Possible responses: In each of the examples, the values were the same but they were grouped differently (in different circles). The Associative Property holds for multiplication and addition, but not subtraction or division._

=== Investigate

[.lesson-instruction]
Turn to Associative Property Table. How many different ways can you apply the Associative Property? Draw as many different Circles of Evaluation as you can.

Note that each of these Circles can be represented in at least one alternative way, as they all include exclusively addition or multiplication.

=== Synthesize

- For which operations does the Associative Property hold?
** _The Associative Property holds for multiplication and addition, but not division or subtraction._
- When applying the Associative Property, did the order of the numbers ever change?
** _No - when we apply the Associative Property on its own, the order of the numbers should always remain the same._
- When applying the Associative Property, did you ever change the architecture of the Circles? (For instance, did you ever change “circle-inside-circle-inside-circle” to “two-circles-in-a-circle”?) When was that necessary? Why? How did you know that you were doing a valid Circle transformation?

== Circles, the Associative Property, and Mental Math @duration{20 minutes}

=== Overview
Students discover how the Associative Property and Circles make mental computation simpler.

=== Launch

[.lesson-instruction]
- Alecia and Jill are trying to solve this multiplication problem: @math{2.5 \times 4 \times 36}
- Jill takes out a paper and pencil and is hard at work using the multiplication standard algorithm.
- Alecia looks at the problem for a few seconds and announces that she knows the answer.
- What is Alecia’s strategy?
** _Solicit students' ideas. Share one possible path - involving Circles and Transformations - below._

Alecia envisioned a Circle of Evaluation in her head.

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===

|@show{(coe '(* (* 2.5 4) 36))}	| &rarr; | @show{(coe  '(* 10 36)) }
| First, she grouped together the first two factors in their own Circle. |  | Then, she applied Computation as a Circle Transformation.

|===

She then applied Computation as a Circle Transformation. Alecia knows that @math{2.5 \times 4} is @math{10}. She also is confident multiplying by powers of 10. Circles helped her to literally see that the final product is @math{3,642}.

=== Investigate

[.lesson-instruction]
- Complete Which Circle Makes the Math Easier? to practice applying the Associative Property to expressions involving three addends or three factors.
- We can also combine the Associative Property with the Commutative Property to mentally compute more efficiently! Try Which Circles Makes the Math Easier, Part 2 to experiment with applying two properties to the same expression.

=== Synthesize

How can the Associative Property help you do mental math more efficiently?
