= The Vertical Line Test
@description{Students learn to distinguish functions from other relations.}

@lesson-prereqs{}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:
@objectives

@objective{Generate points for a graph from a rule.}
@objective{Test whether or not a graph represents a function using the vertical line test.}
@objective{Identify whether or not a table represents a function.}

| Student-Facing Lesson Goals
|

- Let's identify which graphs are functions and which aren't using the vertical line test.
- Let's identify whether or not a table represents a function.
- Let's learn how to generate points for a graph from a rule.

| Materials
|[.materials-links]
@material-links

| Preparation
|
@preparation{
- Decide whether or not you want students to work through the @starter-file{interactive-functions} at their own pace or would prefer to sync students and project it on the board.
- Decide how you will share @starter-file{interactive-functions} with students and, if you are using our Google Slides, add the appropriate link to the slide deck. _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}
- Rulers or straight edges might be useful in supporting students during the section of the lesson that focuses on the vertical line test.
}


|===

== Functions Are Reliable

=== Overview

Students work collaboratively to generate visual representations of functions, using rules to make coordinate pairs.

=== Launch
@slidebreak{Launch}

@vocab{Functions} are a way of describing a certain kind of relationship.

@lesson-point{
Functions are reliable. If we give them what they need, they produce the same thing with that same collection of inputs every time.
}

@slidebreak{Launch}

You are already familiar with lots of relationships. 

- Time worked is related to money earned. 
- The speed of a car is related to the gas it consumes per miles driven. 

But not all relationships are functions. 

Let's find out exactly what kind of relationships are functions...

=== Investigate
@slidebreak{Investigate}

Just as we can give the `rectangle` function inputs and it will produce an image, we can make @vocab{graphs} of functions that describe the relationship between @vocab{independent variable} (x) and @vocab{dependent variable} (y).

- We feed inputs (x-values) into a rule that produces outputs (y-values). 
- The resulting x-y pairs describe the location of points that will satisfy the rule. 
- We can repeat the process with an infinite number of inputs.
- When we plot the input-output pairs as a line or curve on a graph it will show the relationship between the @vocab{independent variable} (x) and @vocab{dependent variable} (y).

@slidebreak{Investigate-DN}

@teacher{Be sure you've opened @starter-file{interactive-functions} and made a link or code to share with your students!}

@lesson-instruction{
- Open the link to your class' copy of @starter-file{interactive-functions} on your computer.
- On each slide, you'll see a coordinate grid and a rule.
- Choose an x-value that is within the domain of the graph, apply the rule to your x-value to get a y-value.
- Then drag the dot onto the point on the graph whose coordinates are the @math{x} you put in and the @math{y} you got back.
- Challenge yourself to think of points that nobody else will!
- After you submit your own dot, you will see everyone else's dots appear on the grid, revealing a visual representation of the function!

}

@teacher{You might just want to do a few of these slides, or you might do lots of them. Make sure students get a chance to see the completed graphs.}

@strategy{Limitations of the Vertical Line Test}{
Use of the vertical line test is contingent upon restricting ourselves to functions where the domain is composed of x-values and the range is composed of y-values. Once students are exploring questions about whether ‘x is a function of y’ (an important question for Algebra 2 students thinking about inverse functions), they will need to make use of other strategies.

We recommend urging students to pay special attention to the @vocab{domain} and @vocab{range} of each function, noting that the domain is not necessarily the horizontal axis.
}

=== Synthesize
@slidebreak{Synthesize}
- How can we make a graph of a function from its rule?
- Are there curves or lines that a function could not make? Why or why not?

== Identifying Functions from Graphs

=== Overview

Students learn to use the @vocab{vertical line test} to determine whether or not a graph is a function. Students have already seen all kinds of functions! The subset of functions that are `Number -> Number` can be graphed in 2 dimensions, with the Domain along the x-axis and the Range along the y-axis. The Vertical Line Test is a special trick that only works for this subset of functions.

=== Launch
@slidebreak{Launch}

We know that we can write functions that take in an x-value and produce a y-value. 

- Sometimes two different inputs can yield the same outputs. 
- But inputs can only be associated with one output - otherwise how would we know what do with the input?!

@slidebreak{Launch}

We can test a graph to see whether or not it's a function using the "vertical line test". Imagine overlaying a series of vertical lines on the graph. 

- The graph represents a function if each vertical line we draw will either pass through one of the function's points or zero of its points. 
- The relationship is not a function if there is any vertical line that can be drawn that would intersect more than one point on the graph (indicating more than one output for an input).

[cols="^1,^1"]
|===
| *Passes the Vertical Line Test -> Is a Function*
| *Fails the Vertical Line Test -> Is Not a Function*
|@image{images/pass-test.png}
|@image{images/fail-test.png}
|===

=== Investigate
@slidebreak{Investigate}

@lesson-instruction{
- Turn to @printable-exercise{functions-graphs.adoc} and use a straightedge and a pencil to draw vertical lines on each of the graphs to help you determine whether or not they are functions.
- When you finish, go on to @printable-exercise{functions-graphs-2.adoc}.
- Once everyone has completed the first page, we will turn to @printable-exercise{notice-wonder-functions.adoc}.
}

@teacher{
As students work, circulate around the room and make sure that they are actually drawing vertical lines on the graphs. Some students may benefit from circling the point where each vertical line intersects the graph.

Be sure to confirm that students have correctly identified which graphs could represent functions before moving on.
}

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@A{What did you Notice?}
@A{Functions could be lines, curves, v-shaped or scatter plots! Answers will vary.}
@Q{What did you Wonder?}
@A{Why might some scatter plots represent functions and others not? Are there other forms that functions can take? How do you end up with a circle on a graph? Answers will vary.}
}

== Identifying Functions from Tables

=== Overview

Students apply their understanding of how to use the vertical line test on graphs to learn to recognize whether or not tables are functions.

=== Launch
@slidebreak{Launch}

@lesson-instruction{
Turn to @printable-exercise{how-tables-fail-vertical-line-test.adoc} and follow the directions.
}

@teacher{
Circulate around the room verifying that students are remembering how to use the vertical line test and correctly identifying which tables represent functions.}

@slidebreak{Launch}

@QandA{
@Q{How can we identify whether or not a table of values represents a function?}
@A{If a table has more than one y-value (or output) for the same x-value (or input), it cannot represent a function.}
}

=== Investigate
@slidebreak{Investigate}

@lesson-instruction{
- Turn to @printable-exercise{functions-tables.adoc}.
- Look at the values in each table carefully to determine whether or not the table could represent a function.
- If it's not a function, circle or highlight the points that let you know it can't be a function.
- When you're done, turn to @printable-exercise{notice-wonder-functions.adoc} and add any new Notices or Wonderings you may have.
- Then turn to @printable-exercise{functions-tables-graphs.adoc}.
}

@teacher{
As students work, circulate around the room and make sure that they are actually circling or highlighting the points on the tables that tell them that the table doesn't represent a function. 
}

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{What did you Notice?}
@A{Answers will vary. It can still be a function if y-values repeat. It didn't matter whether or not the x-values followed a pattern. It was easier for me to read the tables when the x-values were in order.}
@Q{What did you Wonder?}
@A{Answers will vary. Why weren't the x-values always in order? If the points were on a graph, would they be connected? Can there ever be decimal values for x and y? What would these tables look like on a graph?}
}

