= Compound Inequalities

@lesson-description{Students build upon their understanding of booleans and simple inequalities to compose compound inequalities using the concepts of union and intersection.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-inequalities}

| Lesson Goals
| Students will be able to:

* Understand how the conjunctions `and` and `or` differ
* Describe how functions can work together
* Describe the solution set of a compound inequality

| Student-Facing Lesson Goals
|
* I can explain the difference between how `and` and `or` are used in programming
* I can use two or more inequalities together and describe the area they enclose
//* I can tell someone else how two or more @vocab{function}s work together

| Materials
|[.materials-links]

@ifproglang{wescheme}{
* Lesson Slides
}
@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1U3HfIJ1I-vyVQCa3ModXrqf1M41EcBciWdTnaj2u394/edit?usp=sharing, Lesson Slides}
}

@material-links

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

|===

== Introducing Compound Inequalities

=== Overview
Students consider the need to _compose_ inequalities, and think about how to write them.

=== Launch

We use inequalities for lots of things:

- Is it hot out? (@math{temperature \gt 80°})
- Did I get paid enough for painting that fence? (@math{paid \ge $100})
- Are the cookies finished baking? (@math{timer = 0})

[.lesson-instruction]
Have students come up with other examples.

Many times we need to _combine_ inequalities:

- Should I go to the beach? (@math{temperature \gt 80°} and @math{weather = "sunny"})
- Was this burrito worth the price? (@math{taste = "delicious"} and @math{price \leq $15})

[.lesson-instruction]
Have students come up with other examples.

Guide students through other examples of `and` and `or` with various statements, such as "I'm wearing a red shirt AND I'm a math teacher, true or false?" or "I'm an NBA basketball star OR I'm having pizza for lunch, true or false?". This can make for a good sit-down, stand-up activity, where students take turns saying compound boolean statements and everyone stands if that statement is true for them.

=== Investigate
Both mathematics and programming have ways of combining - or _composing_ - inequalities.

[.lesson-instruction]
Complete @opt-printable-exercise{pages/boolean-coe-to-code1.adoc} and @opt-printable-exercise{pages/and-or.adoc}.

=== Synthesize
Be really careful to check for understanding here. 

- Expressions using `and` only produce `true` if both of their sub-expressions are `true`. 
- Expressions using `or` produce `true` if *either* of their sub-expressions are `true`.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Strategies for English Language Learners}

When describing compound inequalities, be careful not to use "english shortcuts". For example, we might say "I am holding a marker _and_ an eraser" instead of "I am holding a marker _and_ I am holding an eraser." These sentences mean the same thing, but the first one obscures the fact that "and" joins two complete phrases. For ELL/ESL students, this is unecessarily adds to cognitive load!
|===

== Solutions and Non-Solutions of Compound Inequalities

=== Launch
Have students identify 4 solutions and 4 non-solutions for each of the following inequalities.

* @math{x \gt 5}
* @math{x \le 15}

What about the solution set of @math{x \gt 5} `and` @math{x \le 15}?  What numbers make both of these inequality expressions true?

How would that be different from @math{x \gt 5} `or` @math{x \le 15}?  What numbers make at least one of these inequality expressions true?

=== Investigate

[.lesson-instruction]
Have students log in to the 
@ifproglang{wescheme}{ 
@online-exercise{https://www.wescheme.org/view?publicId=yFnDbsSnR7, Compound Inequalities Starter File), read the code carefully and click run to see the graphs they've just considered} 
}
@ifproglang{pyret}{@online-exercise{https://code.pyret.org/editor#share=1ErJCa-wrr4zdV5U4lhUhIXvcup8R6_5y&v=8c4da7d, Compound Inequalities Starter File), read the code carefully and click run to see the graphs they've just considered.} 
}

This starter file includes two special functions.

`and-intersection` takes in two functions and a list of numbers and produces a graph with the points and the shaded @vocab{intersection} of values that make both of the inequalities true. 

`fun gt5(x): x > 5 end`

`fun lte15(x):` @math{x \le 15} `end`

`and-intersection( gt5, lte15, [list: -5, -2.1, 0, 5, 10,` @math{\frac{39}{5}},` 15, 20] )`

@span{.center}{@image{images/intersection1.png,"" ,""}}

`fun lt5(x): x < 5 end`

`fun gte15(x):` @math{x \ge 15} `end`

`and-intersection(lt5, gte15, [list: -5, -2.1, 0, 5, 10,` @math{\frac{39}{5}}, `15, 20] )`

 
_Note: Some pairs of inequalities do not intersect at all and therefore have *no solutions*._

@span{.center}{@image{images/intersection-no-solution1.png,"" ,""}}

`or-union`takes in two functions and a list of numbers and produces a graph with the points and the shaded @vocab{union} of values that make either or both of the inequalities true. 

`fun lt5(x): x < 5 end`

`fun gte15(x):` @math{x \le 15} `end`

`or-union(lt5, gte15, [list: -5, -2.1, 0, 5, 10, 12, 15, 20] )`

@span{.center}{@image{images/union1.png,"" ,""}}

`fun gt5(x): x > 5 end`

`fun lte15(x):`@math{x \le 15} `end`

`or-union(gt5, lte15, [list: -5, -2.1, 0, 5, 10, 12, 15, 20] )`

_Note: Some @vocab{unions}, like the one below, include *all real numbers*; they have have *infinite solutions* that satisfy at least one of the inequalities._

@span{.center}{@image{images/union-infinite1.png,"" ,""}}

[.lesson-instruction]
Turn to @opt-printable-exercise{compound-inequalities.adoc, Compound Inequalities} and explore the compound inequalities listed using the @ifproglang{pyret}{@link{https://code.pyret.org/editor#share=1ErJCa-wrr4zdV5U4lhUhIXvcup8R6_5y&v=8c4da7d, Compound Inequalities Starter File} @ifproglang{wescheme}{https://www.wescheme.org/view?publicId=yFnDbsSnR7}, identifying solutions and non-solutions for each.

Instead of defining two functions as simple inequalities, we could produce the same graph by defining one function to be a compound inequality. 

@ifproglang{pyret}{
`fun fiveto15(x): (x > 5) and (x <= 15) end`
`inequality(fiveto15, [list: -5, -2.1, 0, 5, 10.2, 12, 15, 20])`
}
@ifproglang{wescheme}{
	`(define (fiveto15 x)(and (> x 5) (<= x 15)))`
	`(inequality fiveto15 (list -5 -2.1 0 5 10 12 15 20))`
}

[.lesson-instruction]
 Turn to @opt-printable-exercise{compound-inequality-functions.adoc, Compound Inequality Functions} and have students write code to describe the compound inequalities pictured. 

@ifproglang{pyret}{If you have time, have students open to @online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fdf8618945cb549d457fb85, Matching Compound Inequality Functions and plots}
}
=== Synthesize
- How did the graphs of intersections and unions differ?

== Additional Exercises:

- @opt-printable-exercise{pages/boolean-coe-to-code2.adoc} 

