= Inequalities 2

@lesson-description{Students use what they've learned about Booleans and inequalities to set screen boundaries in their game.}


[@lesson-intro-table]
|===
@prereqs-stds{alg-inequalities}

| Lesson Goals
| Students will be able to:

* Describe how functions can work together.
* Make mathematical adjustments relevant to their game.

| Student-Facing Lesson Goals
|
* I can tell someone else how two or more @vocab{function}s work together.
* I can make adjustments to a program based on how the program behaves.

| Materials
|
ifeval::["{proglang}" == "wescheme"]
* Lesson slides template (@link{https://docs.google.com/presentation/d/1-Ey-m1iwpwIQt_nMbWrobg8b8AGFPBokM68U-lEgANA/edit?usp=sharing, Google Slides})
endif::[]
ifeval::["{proglang}" == "pyret"]
* Lesson slides template (@link{https://drive.google.com/open?id=1kKYXX9tdZhYDjRYrrJU0TXajLVdnEcs5HSOgkqCZIcE, Google Slides})
endif::[]

Bootstrap Formative Assessments

* Booleans Review (@link{https://quizizz.com/admin/quiz/5d9919516dbee7001e08a4a0, Quizizz}, @link{https://teacher.desmos.com/activitybuilder/custom/5d991ac49b9b292020c18108, Desmos Activity})

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|
- https://teacher.desmos.com/inequalities[Inequalities Bundle] (Desmos Activities)
- https://quizizz.com/admin/quiz/56cf6ac2bb56dfc267b35f94/inequalities-and-graphing-inequali[Inequalities & Graphing Inequalities] (Quizizz)
- https://www.geogebra.org/m/Huq24Spq[Inequality Graph Illustrator] (Geogebra)
- https://quizizz.com/admin/quiz/5846cda05c74a6041c47566b/graphing-compound-inequalities[Graphing Compound Inequalities] (Quizizz)

| Key Points for the Facilitator
|
* If a student's `TARGET` and `DANGER` image seem to be "getting stuck" on the edge of the screen, the student may have to adjust the side boundaries depending on the size of their images.
* The code for the boundary functions in the game is exactly the same as in Sam the Butterfly. 
* This activity should be as closely as possible to Inequalities 1 (Sam the Butterfly) as the two lessons are connected.
|===

== Warmup

Students should have their computer, contracts page, and pencil and be logged in to 
ifeval::["{proglang}" == "wescheme"]
@link{https://www.wescheme.org, WeScheme }
endif::[]
ifeval::["{proglang}" == "pyret"]
@link{https://code.pyret.org, code.pyret.org }
endif::[]
with their Game Project file open.

== Applying to the Game @duration{25 minutes}

=== Overview
Students identify common patterns between 2-dimensional boundary detection and detecting whether a player is onscreen. They apply the same problem-solving and narrow mathematical concept from the previous lesson to a more general problem.

=== Launch

Have students open their in-progress game file and press Run.  

- How are the `TARGET` and `DANGER` behaving right now? +
_They move across the screen._

- What do we want to change? +
_We want them to come back after they leave one side of the screen._

- How do we know when an image has moved off the screen? +
_We can see it._

- How can we make the computer understand when an image has moved off the screen? +
_We can teach the computer to compare the image's @vocab{coordinates} to a numeric boundary, just like we did with Sam the Butterfly!_

=== Investigate

ifeval::["{proglang}" == "wescheme"]
Students apply what they learned from Sam the Butterly to fix the `safe-left?`, `safe-right?`, and `onscreen?` functions in their own code.
endif::[]
ifeval::["{proglang}" == "pyret"]
Students apply what they learned from Sam the Butterly to fix the `is-safe-left`, `is-safe-right`, and `is-onscreen` functions in their own code.
endif::[]  
Since the screen dimensions for their game are 640x480, just like Sam, they can use their code from Sam as a starting point.

Students will need to test their code with their images to see if the boundaries are correct for them.  Students with large images may need to use slightly wider boundaries, or vice versa for small images.  In some cases, students may have to go back and rescale their images if they are too large or too small for the game.

== Additional Exercises:
