= A Pyret Spell Checker
++++
<style>
/* Shrink vertical spacing on fitbruby */
.fitbruby{padding-top: 0.5rem;}

/* Cut the padding under each section */
.sect1 { padding: 0 !important; }

td { padding: 3px !important; }
</style>
++++
@link-instructions{Open the @starter-file{spell-checker} and click "Run".} Follow each of the instructions below to discover how our very own Pyret spell checker works.

== Suggestions for 1 Edit-Distance
`deletions`, `insertions`, `swaps`, and `subs` consume a word, and suggest a list of words that can be reached by making a *single change*.

@n Fill in the 2nd column of table below by evaluating each expression, and recording the *number of suggestions* Pyret returns.

[cols="<1a,^1a,4a", options="header"]
|===
| Expression 	| # Suggestions | Did Pyret find all your suggestions?
| `deletions("wello")`
| @ifsoln{4}
| @hspace{1em} *Yes* @hspace{3em} *No*, it missed:

| `insertions("wello")`
| @ifsoln{151}
| @hspace{1em} *Yes* @hspace{3em} *No*, it missed:

| `swaps("wello")`
| @ifsoln{4}
| @hspace{1em} *Yes* @hspace{3em} *No*, it missed:

| `subs("wello")`
| @ifsoln{125}
| @hspace{1em} *Yes* @hspace{3em} *No*, it missed:
|===

@n *Flip back to @printable-exercise{first-spell-checker.adoc}.* How many of YOUR suggestions are in Pyret's list? Fill in the 3rd column of the table above.

== Suggestions for Larger Edit-Distances

@n Evaluate `swaps(swaps("wello"))`. What does it do? @fitb{}{} +
@fitb{}{@ifsoln{it will compute all possible swaps for "wello", then compute every swap for _those_ swaps!, resulting in a list with an edit-distance of 2.}}

@n Evaluate `swaps(subs("wello"))`. What does it do?: @fitb{}{} +
@fitb{}{@ifsoln{For every possible 1-letter substitution, find every possible swap, resulting in a list with an edit-distance of 2.}}

== Removing "Junk" Words
Pyret has a function `only-real`, that takes in a table of suggested words and a dictionary.

@n Evaluate `insertions("flt")`. How many suggestions does it return? @fitb{}{@ifsoln{101}}

@n Evaluate the three expressions below and record the words they return

[cols="1a,1a"]
|===
|`only-real(insertions("flt"), WORDS-S)`| @ifsoln{flat}
|`only-real(insertions("flt"), WORDS-M)`| @ifsoln{felt, flat}
|`only-real(insertions("flt"), WORDS-L)`| @ifsoln{felt, flat, flit}
|===

@n What does `only-real` do? Why do we get different results? @fitb{}{@ifsoln{It removes any word that isn't in the dictionary}} +
@fitb{}{@ifsoln{The size of the dictionary determines what words the algorithm will return. Larger dictionaries contain more "real words."}}

== Putting it All Together

The `alt-words` function combines all 5 of these functions. It takes in a "word", a dictionary, and a maximum edit-distance.

@n If you had to guess, what word did the author mean to type when they wrote `crosswrd`? @fitb{}{}

@n Evaluate `alt-words("crosswrd", WORDS-L, 2)`. Record the first 3 results. Describe the edit(s) to get here from "crosswrd".

[.FillVerticalSpace, cols="^2a, ^1a, ^5a", options="header", stripes="none"]
|===
| Alternative Word	| # Edits 									| Edits from "crosswrd"
| @ifsoln{crosser}	| @ifsoln{2} @ifnotsoln{@vspace{1ex}}		| @ifsoln{delete the "d". replace "w" with "e"}
| @ifsoln{crossed}	| @ifsoln{2} @ifnotsoln{@vspace{1ex}}		| @ifsoln{replace the "w" with an "e", and delete "r"}
| @ifsoln{crossword}| @ifsoln{1} @ifnotsoln{@vspace{1ex}}		| @ifsoln{insert an "o"}
|===

@n If the spellchecker were to take the number of edits into consideration, which of these suggestions do you think it would propose first? Why? 
@fitb{}{@ifsoln{"crossword" because it has the smallest edit-distance, so is the most similar to the input}}