= A Pyret Spell Checker: The Algorithm

@link-instructions{Open the @starter-file{spell-checker} and click "Run".} Follow each of the instructions below to discover how our very own Pyret spell checker works.


In the @starter-file{spell-checker}, we've created a special function for you to use. Here's the contract:

@show{(contract "alt-words" '(list "String" "Dictionary") "Table")}

@n The name of the functions is @fitb{2em}{@ifsoln{alt-words}}. Its Domain includes @fitb{2em}{@ifsoln{2}} arguments and its Range is a @fitb{}{@ifsoln{Table}}

@n Evaluate `alt-words("maple", WORDS-S)` in the Interactions Area. What comes back?

- Record the results in the left column of the table below.
- In the second column, describe how each option differs from the input string ("straw").
- In the third column, record how many edits to the string "straw" this algorithm makes. _(A single edit could entail replacing one letter with a different one, for instance.)_

@vspace{1ex}

[.FillVerticalSpace, cols="^2a, ^1a, ^5a", options="header", stripes="none"]
|===
| Suggestion  		| # Edits 			| How it's different from the string "straw"
| @ifsoln{cheese}	| @ifsoln{1} 		| @ifsoln{remove the 6th letter}
| @ifsoln{cheek}	| @ifsoln{2} 		| @ifsoln{remove the 6th and change the 5th letter}
| @ifsoln{cheer}	| @ifsoln{2} 		| @ifsoln{remove the 6th and change the 5th letter}
| @ifsoln{cherry}	| @ifsoln{2} 		| @ifsoln{change the 5th and 6th letters}
| @ifsoln{chest}	| @ifsoln{2} 		| @ifsoln{remove the 6th, and change the 4th and 5th letters}
|===

@n Test `alt-words("planet", WORDS-S)` in the Interactions Area.

@vspace{1ex}

*Experiment with the `alt-words` function to answer the questions below, testing what it produces using Strings from your imagination.*

@n We have seen multiple two-edit changes. Does the program propose words that include three edits? @fitb{}{@ifsoln{No.}}

@n What is the maximum length string that this spell checker will accept? @fitb{}{@ifsoln{7 letters}}

- Why does that maximum length make sense with what we know about the algorithm? @fitb{}{} +
@fitb{}{@ifsoln{A 7-letter word would require two deletions, using both of the available edits.}}

@n What else do you notice? @fitb{}{@ifsoln{There are words for which the spellchecker offers no suggestions (e.g. "octagon").}} +
@fitb{}{@ifsoln{And there are words for which it proposes long lists.}}

@n *Edit distance* is a word programmers use to describe the number of operations needed to transform one string into another string. How can *edit distance* help us measure similarity? @fitb{}{@ifsoln{A low edit distance indicates that two strings are very similar,}}

@fitb{}{@ifsoln{and a high edit distance indicates that two strings are very different.}}

@n Test `alt-words("crosswrd", WORDS-S)` in the Interactions Area. Then try larger dictionaries like `WORDS-M` and `WORDS-L`. Why does the same algorithm produce different results?
@fitb{}{@ifsoln{The larger the dictionary, the more suggestions the algorithm can make!}}
