= A Pyret Spell Checker
++++
<style>
/* Make the last content section (ignore acknowledgement) grow "faster",
 * in order to take up more of the available space than the other sections
 */
.sect1:nth-last-child(2) { flex-grow: 6 !important; }
</style>
++++
@link-instructions{Open the @starter-file{spell-checker} and click "Run".} Follow each of the instructions below to discover how our very own Pyret spell checker works.

== 1-Edit Operations

@n In the Interactions Area, evaluate `subs("hello")`. What does this function do? @fitb{}{}
@fitb{}{@ifsoln{It produces every possible 1-letter substitution}}

(Look back at your *substitutions* in @printable-exercise{first-spell-checker.adoc}. How many of them are in this list?)

@n Evaluate `swaps("hello")`. What does this function do? @fitb{}{@ifsoln{Produces every possible swap of two adjacent letters}}
@fitb{}{}

(Look back at your *swaps* in @printable-exercise{first-spell-checker.adoc}. How many of them are in this list?)

@n Evaluate `insertions("hello")`. What does this function do? @fitb{}{@ifsoln{Produces every possible insertion of a single letter into the word}}
@fitb{}{}

@n Evaluate `deletions("hello")`. What does this function do? @fitb{}{@ifsoln{Produces every possible deletion of a single letter from the word}}
@fitb{}{}

== 2-Edit Operations, 3-Edit Operations, and more!
You can also combine these functions to produce alternatives that are more than 1 edit from the original.

@scrub{SCHANZER the functions below don't exist in pyret.}
@n In your own words, what do you think `swap-letters(swap-letters("hello"))` will do? @fitb{}{}
@blanklines{2}{@ifsoln{it will compute all possible swaps for "hello", then compute every swap for _those_ swaps!}}

@n In your own words, what do you think `swap-letters(sub-letters("hello"))` will do? @fitb{}{}
@blanklines{2}{@ifsoln{For every possible 1-letter substitution, find every possible swap}}

== Removing "Junk" Words

@n Evaluate `only-real(sub-letters("hello"), WORDS-L)`. What does `only-real` do? @fitb{}{@ifsoln{It removes any word that isn't in the dictionary}}
@fitb{}{}

@n Try other dictionaries. For example, Evaluate `only-real(sub-letters("hello"), WORDS-M)`. Why do we get different results? +
@fitb{}{The size of the dictionary determines what words the algorithm will return. Smaller dictionaries mean more "unknown words."}

== Finding Real, Alternate Words

The `alt-words` function combines all of the functions you've seen so far. It also lets you decide _how many edits_ to consider. (WARNING: edits above 2 might grind your computer to a halt!)

@n Evaluate `alt-words("maple", WORDS-S)`, and record the first 3 results. In the last column, write what edit(s) were needed to go from "maple" to that word.

[.FillVerticalSpace, cols="^2a, ^1a, ^5a", options="header", stripes="none"]
|===
| Alternative Word	| # Edits 			| Edits from "maple"
| @ifsoln{male}		| @ifsoln{1} 		| @ifsoln{delete the "p"}
| @ifsoln{able}		| @ifsoln{2} 		| @ifsoln{delete the "m", sub the "b" in for the "p"}
| @ifsoln{apple}	| @ifsoln{2} 		| @ifsoln{delete the "m", sub the "b" in for the "p", and insert another "p"}
| @ifsoln{cable}	| @ifsoln{2} 		| @ifsoln{sub "c" for "m", and "b" for "p"}
|===


@n How does the "edit distance" between two words help us measure similarity? @fitb{}{@ifsoln{A low edit distance indicates that two strings are very similar,}} +
@fitb{}{@ifsoln{and a high edit distance indicates that two strings are very different.}}