= Spell Checker Results
++++
<style>
/* Push content to the top (instead of the default vertical distribution), which was leaving empty space at the top. */
#content { display: block !important; }
</style>
++++

@link-instructions{Open the @starter-file{spell-checker} and click "Run".} Follow each of the instructions below to explore the output of the Pyret Spell Checker

To refresh your memory, here are the contracts you'll need for this page:

[cols="1a,1a", frame="none"]
|===
|
@show{(contract "first-n-rows" '("Table" "Number") "Table")}
@show{(contract "dot-plot" '("Table" "String" "String") "Image")}
@show{(contract "count" '("Table" "String") "Table")}
|
@show{(contract "bar-chart" '("Table" "String") "Image")}
@show{(contract "row-n" '("Table" "Number") "Row")}
|===

== Analyzing Results

@link-instructions{Start by defining a table. At the bottom of the *Definitions Area*, type `results = alt-words("wello", WORDS-M, 3)`. Click "Run".}

@n Describe the data contained in the `results` table. @fitb{}{}+
@fitb{}{@ifsoln{193 words suggested as alternatives to "wello" by making up to 3 edits and then removing any results that weren't found in the `WORDS-M` library.}}

@n Use the `count` or `bar-chart` function to see how the results are distibuted by `edit-distance`:

@hspace{6em} @fitbruby{10em}{@ifsoln{3}}{edit-distance = 1} @hspace{6em} @fitbruby{10em}{@ifsoln{21}}{edit-distance = 2} @hspace{6em} @fitbruby{10em}{@ifsoln{169}}{edit-distance = 3}

@n Complete the expression to extract just the first 3 rows. Then record them below. `first-n-rows(` @fitb{8em}{@ifsoln{`results, 3`}} `)` 

@vspace{1ex}
@indented{
[cols="1a,1a", options="header"]
|===
|word 	|edit-distance
| 		|@vspace{1ex}	
|		|@vspace{1ex}	
|		|@vspace{1ex}	
|===
}

== Real Spell Checkers Don't Return a Table...

@link-instructions{Let's define a row. At the bottom of the *Definitions Area*, type `row2 = row-n(results, 1)`. Click "Run".""} 

@n Evaluate `row2` in the *Interactions Area*. What do you get back? @fitb{}{@ifsoln{The second row}}

@vspace{1ex}

++++
<style>
/* add a dotted border around specialized directions */
.myCustomClass { 
  border: dotted 1px black; 
  p {position: center !important;}
}
</style>
++++

[.myCustomClass]
*Now that we know how to extract a single row from our table, we need to extract the specific information that we want from that row.*

@n Evaluate `row2["word"]`. What do you get back? @fitb{}{@ifsoln{}} 

@n Evaluate `row2["edit-distance"]`? @fitb{}{@ifsoln{}}

@n Evaluate `row-n(results, 1)["word"]`. What did you get back? @fitb{8em}{@ifsoln{}}

@vspace{1ex}

[.myCustomClass]
*Code like this (`["word"]` or `["edit-distance"]`) is called a @vocab{row accessor}.* 

@n In your own words, what do row accessors do? @fitb{}{}
@blanklines{2}{@ifsoln{Given a row and the title of a column, they try to access the value stored in that cell of the table.}}

@n What code will produce the first suggested word from our table? @fitb{}{@ifsoln{`row-n(results, 0)["word"]`}}

@n What code will produce the edit-distance of the fifth suggested word from our table? @fitb{}{@ifsoln{`row-n(results, 4)["edit-distance"]`}}

@n What code will produce the seventy-fifth suggested word from our table? @fitb{}{@ifsoln{`row-n(results, 74)["word"]`}}

@n What is the seventy-fifth suggested word? @fitb{}{}

