= Our Class' Name Length Data

== Create a Dot Plot: Length of First Names in My Class

@n Your class just created a communal dot plot. Copy all of its dots onto the number line below.

@vspace{10ex}

@center{@image{../images/number-line.png, 500}}

== Reading a Dot Plot

@n What is the difference (in letters) between the longest name and the shortest name? @fitb{}{}

@n What is/are the most common name length(s)?  @fitb{}{}

@n What fraction of students have first names that are 5 letters long? @fitb{}{}

== Peaks, Clusters, Gaps, and Outliers in Name Length Data

@n Label any peaks, clusters, gaps, and outliers on the class dot plot (above).

@n Describe what you can conclude about students' name lengths in your class, based on those peaks, clusters, gaps, and outliers. @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

== Typicality of Name Length Data


@n What is one possible typical value for class name length? @fitb{5em}{} Explain. @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n Give another possible typical value: @fitb{5em}{}. Explain why it is appropriate. @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

== Compare

@n Compare and contrast your class dataset with either Group A or Group B from @printable-exercise{interpret-dot-plots.adoc}. Give at least one way that the distributions are alike, and at least one way that they are different. @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}





