= Limits of Computational Modeling

[.linkInstructions]
Make sure you are working in your copy of the @starter-file{alg2-covid}.

== Exponentiation and RoughNums in Pyret

@n In Pyret, evaluate the following exponents:

@hspace{4em} a. @math{10^2} +
@hspace{4em} b. @math{10^{1/2}} +
@hspace{4em} c. @math{10^{200}}

@n In Pyret, evaluate the following expressions:

@hspace{4em} a. @show{(code '(= 1 1))} +
@hspace{4em} b. @show{(code '(= ~1 ~1))}

@n Read the error message carefully. What do you think is going on?

== Fitting Exponential Models in Pyret

@n In the space below, define `exponential` for one of the models you fit in Desmos.

@ifsoln{@vspace{1ex}}

@ifsoln{*Answers will vary.* If @math{a = 31.6}, @math{b = 1.047} and @math{k = 119000}, you would get the following:}

`fun exponential(x): (` @fitbruby{8em}{@ifsoln{31.6}}{a} `* num-expt(` @fitbruby{10em}{@ifsoln{1.047}}{b} `, (~1 * x))) +` @fitbruby{10em}{@ifsoln{119000}}{k} `end`

@n Update the definition for `exponential` in the Definitions Area and click "Run" to reload it. +
@hspace{1em}Then use `fit-model` to determine how closely `exponential` fits the `MA-table` and fill in the blanks below to interpret the model. +
@ifsoln{*Answers will vary. Numbers below are provided for reference only!*} @ifnotsoln{@hspace{1em}}_Hint: If you forgot the contract for `fit-model`, look it up in the @dist-link{Contracts.shtml, Contracts Pages}!_

@indented{
According to this exponential model, on @fitbruby{6em}{June 9, 2020}{day zero} there were about 
@fitbruby{1em}{@ifsoln{32}}{a} + @fitbruby{5em}{@ifsoln{119,000}}{k} @fitbruby{10em}{@ifsoln{positive covid cases}}{y-units} in MA, for a total of about 
@fitbruby{7em}{@ifsoln{119,032}}{a + k}. This number grew exponentially, increasing by a factor of @fitbruby{6em}{@ifsoln{1.047}}{Growth Factor: b} or 
@fitbruby{9em}{@ifsoln{4.7}}{Growth Rate: (b - 1) &times; 100} % every day. The error in the model is described by an @vocab{S-value} of about
@fitbruby{3em}{@ifsoln{13,374}}{S}@fitbruby{11em}{@ifsoln{positive COVID cases}}{units}, which is a(n) @fitbruby{8em}{@ifsoln{moderate}}{bad, ok, good} model considering that
@fitbruby{10em}{@ifsoln{positive cases}}{y-units} in this dataset range from @fitbruby{6em}{@ifsoln{104156}}{lowest y-value} to @fitbruby{6em}{@ifsoln{341925}}{highest y-value}. 
}

@vspace{1ex}

You know that the pros of using `~1` involve speed. *What are the potential downsides of using `~1` to speed up a calculation?*

@ifnotsoln{
@fitb{}{} +
@fitb{}{}
}

@ifsoln{
- When calculating a path over an extremely long distance, missing decimal places could result in the Mars Rover missing its destination.
- For an extremely large population like China, rounding to 10 decimal places might result in discounting an entire sub-population!
}

