= Exponential Models of Covid in Massachusetts
++++
<style>
/* Keep the preamble from growing to fill up space */
#preamble_disabled { flex-grow: 0 !important; }

/* Make sure autonums that appear inside tables have the closing paren */
.autonum { padding-top: 0.8em !important; }
.autonum:after { content: ')' !important; }

/* Position mathjax and scatterplot image in table cells at the top */
td:first-child p { position: absolute; top: 0.2in; left: 0.2in; background: rgba(255,255,255,0.55); }
td:first-child .mathunicode { min-width: 25px !important; font-weight: bold !important; }
</style>
++++

@link-instructions{
You'll need to have *Slide 4: Exponential Model for MA* of *Modeling Covid Spread (Desmos)* open on your computer.
}

@vspace{1ex}

Change the values of @math{k}, then @math{a}, then @math{b} to find three promising exponential models. +
Graph each one and label your values on the graphs below. @hspace{1em} __@vocab{growth rate} (@math{r}) can be calculated from the base:__ {nbsp} @math{\textit{base} = (1 + \textit{rate})}

== Exponential Model 1

[.FillVerticalSpace, cols="2a,<.^5a", frame="none", stripes="none", grid="none"]
|===
| @image{../images/covid-scatterplot.png, 175}

@math{a=}@fitb{1em}{} +
@math{b=}@fitb{1em}{} +
@math{k=}@fitb{1em}{}

|
@n What is the initial value (# infections as of June 9th) of this model? @fitb{}{} +
@n What is the @vocab{growth rate} of this model? @fitb{}{} +
@n What is the y-intercept (and horizontal asymptote) of this model? @fitb{}{} +
@n For what range of dates is this model _most_ accurate? @fitb{}{} +
@n For what range of dates is this model _least_ accurate? @fitb{}{} +
|===

== Exponential Model 2

[.FillVerticalSpace, cols="2a,<.^5a", frame="none", stripes="none", grid="none"]
|===
| @image{../images/covid-scatterplot.png, 175}

@math{a=}@fitb{1em}{} +
@math{b=}@fitb{1em}{} +
@math{k=}@fitb{1em}{}

|
@n What is the initial value (# infections as of June 9th) of this model? @fitb{}{} +
@n What is the @vocab{growth rate} of this model? @fitb{}{} +
@n What is the y-intercept (and horizontal asymptote) of this model? @fitb{}{} +
@n For what range of dates is this model _most_ accurate? @fitb{}{} +
@n For what range of dates is this model _least_ accurate? @fitb{}{} +
|===

== Exponential Model 3

[.FillVerticalSpace, cols="2a,<.^5a", frame="none", stripes="none", grid="none"]
|===
| @image{../images/covid-scatterplot.png, 175}

@math{a=}@fitb{1em}{} +
@math{b=}@fitb{1em}{} +
@math{k=}@fitb{1em}{}

|
@n What is the initial value (# infections as of June 9th) of this model? @fitb{}{} +
@n What is the @vocab{growth rate} of this model? @fitb{}{} +
@n What is the y-intercept (and horizontal asymptote) of this model? @fitb{}{} +
@n For what range of dates is this model _most_ accurate? @fitb{}{} +
@n For what range of dates is this model _least_ accurate? @fitb{}{} +
|===


== Selecting a Model

@n Choose the model that you think best fits the data, and write it in function notation below:

@ifsoln{*Answers will vary.* If @math{a = 31.6}, @math{b = 1.047} and @math{k = 119000}, you would get the following:}
@center{
@math{\text{exponential}(x) = } @fitbruby{30em}{@ifsoln{@math{31.6^{1.047} + 119000}}}{@math{a(b)^x + k}}
}
