= Making Predictions about Exponential Growth
++++
<style>
/* In solutions mode, make the math larger */
.fitbruby .solution .mathunicode { font-size: larger !important; }

/* Shrink vertical spacing on fitbruby */
.fitbruby{padding-top: 0.5rem !important;}
.fitb.stretch::after{padding-top: 0.5rem !important;}

td { padding: 0em !important; }
</style>
++++

== Our Exponential Model

@n In the space below, define `exponential` as your best model from @printable-exercise{exponential-models-MI.adoc}.

@ifsoln{*Answers will vary.* If @math{a = 7800}, @math{b = 1.012} and @math{k = 0}, you would get the following:}
@center{
@math{\text{exponential}(x) = } @fitbruby{8em}{@ifsoln{7800}}{a} @math{(} @fitbruby{10em}{@ifsoln{1.012}}{b} @math{)^x +} @fitbruby{10em}{@ifsoln{0}}{k} 
}

== Estimating with our Model

@n *Using only mental math and your eyes, ESTIMATE* the number of positive cases after X days to complete the table below. _It is not important to get the right answer here. The point is to record how our brains make sense of this exponential model._ You can look at the formula you wrote above, the graphs where you recorded your models, or the Desmos graph on your screen, but leave the window range set - do not zoom out. *Do NOT use a calculator, keyboard, or mouse*


[cols=".>3a,2a,2a,2a,2a,2a", frame="none", grid="none", stripes="none" options="header"]
|===
| After...   	|  50 days 	|  150 days | 250 days 	| 350 days 	|  450 days 
| *My Estimate*	|@fitb{}{} 	|@fitb{}{} 	|@fitb{}{} 	|@fitb{}{} 	|@fitb{}{} 

| How confident are you? +
_1=Not at all, 5=Very confident_
^.>|@vspace{1ex}
1   2   3  4  5
^.>|@vspace{1ex}
1   2   3  4  5
^.>|@vspace{1ex}
1   2   3  4  5
^.>|@vspace{1ex}
1   2   3  4  5
^.>|@vspace{1ex}
1   2   3  4  5
|===

== Computing Predictions Using Pyret Models

@link-instructions{Open the @starter-file{alg2-covid-mi}, complete the `exponential` template using the function defined at the top of this page. And click "Run".}

@n *Use Pyret* to compute your model's predictions for the number of positive cases after each specified number of days. Record them below.

[cols=".>3a,2a,2a,2a,2a,2a", frame="none", grid="none", stripes="none" options="header"]
|===
| `exponential(x)`   	
|  50 days |  150 days | 250 days 	| 350 days 	|  450 days 

| *The Model Predicts* 				|@fitb{}{} 	|@fitb{}{} 	|@fitb{}{} 	|@fitb{}{} 	|@fitb{}{} 
| How far off was your estimate?  	|@fitb{}{} 	|@fitb{}{} 	|@fitb{}{} 	|@fitb{}{} 	|@fitb{}{} 
|===

@n Compare the predictions you computed to the estimates you made before. How close were you for each?

@n If your predictions got _worse_ as the number of days increased, why do you think that is? @fitb{}{} +
@ifnotsoln{@fitb{}{}} 

== Fitting and Interpreting our Model

@n Use `fit-model` to determine how closely `exponential` fits the `MI-table`. Then complete the sentences below. +
@ifnotsoln{@hspace{1em}_Hint: If you forgot the contract for `fit-model`, look it up in the @dist-link{Contracts.shtml, Contracts Pages}!_}
@teacher{*Answers will vary. Numbers below are provided for reference only!*} 

@n This model was built using data about 
@fitbruby{6em}{@ifsoln{51}}{how many?}
@fitbruby{33em}{@ifsoln{covid case counts in Michigan}}{what?} whose +
@fitbruby{15em}{@ifsoln{day reported}}{x-variable} ranged from
@fitbruby{7em}{@ifsoln{15}}{x-min} to
@fitbruby{7em}{@ifsoln{365}}{x-max}
@fitbruby{20em}{@ifsoln{days into 2020}}{x-variable units}. +

@n Possible limitations of this model include @fitbruby{}{@ifsoln{Data is all from one year. Not all cases were reported. }}{uneven distribution, high variability, small sample size, etc.}

@n According to this exponential model, on @fitbruby{10em}{Jan. 1, 2020}{day zero} there were a total of about 
(@fitbruby{2em}{@ifsoln{7800}}{a} + @fitbruby{1em}{@ifsoln{0}}{k}) = 
@fitbruby{2em}{@ifsoln{7800}}{a + k} @fitbruby{10em}{@ifsoln{positive covid cases}}{y-units} in MI. This number increased by a factor of 
@fitbruby{8em}{@ifsoln{1.012}}{Growth Factor: b} or 
@fitbruby{12em}{@ifsoln{1.2}}{Growth Rate: (b - 1) &times; 100} % every day. 

@n The error in the model is described by an @vocab{S-value} of ~
@fitbruby{3em}{@ifsoln{30291}}{S}@fitbruby{11em}{@ifsoln{positive COVID cases}}{units}. I
@fitbruby{20em}{agree}{strongly agree, agree, disagree, strongly disagree} that this model is a good fit considering that
@fitbruby{10em}{@ifsoln{positive cases}}{y-units} in this dataset range from 
@fitbruby{9em}{@ifsoln{0}}{lowest y-value} to 
@fitbruby{9em}{@ifsoln{551498}}{highest y-value}. 

