= Measures of Center

@description{Students are introduced to mean, median and mode(s) and consider which of these measures of center best describes various quantitative data.}

@lesson-prereqs{visualizing-the-shape-of-data}

@keywords{mean, median, mode, modes}

@add-to-lang{mean, median, modes}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Students explore the concept of center of a distribution, learning how to compute the mean, median and mode(s) of a dataset
* Students find the mean, median and mode(s) of various columns in the Animals table

| Student-facing Lesson Goals
|

* Let's use mean, median, and modes to describe our data.

| Materials
|[.materials-links]

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
|
* The kinesthetic activity in this lesson requires a ruler and 4-8 pennies for each group of 3. 
* There is an optional activity in this that would require you to print an extra datacycle for your students. 
* If you are using the slide deck, adjust it based on which of these activities you will be doing with your students.

|===

== Mean @duration{15 minutes}

=== Overview
Students learn about @vocab{mean} (or "average") as one way (among others!) to summarize a @vocab{quantitative} column, and how to compute it using Pyret.

=== Launch

One of the ways that Data Scientists summarize quantitative data is by talking about its _center_ - literally asking "what is a typical value in this sample?", in the hopes of inferring something about a larger population.  But there are many different ways to define "center", and each method has strengths and weaknesses. The shape of the data can play a huge role in whether or not one kind of summary is appropriate!

@lesson-instruction{
Let's take a moment to consider what values might be typical for the weight of our animals by completing @printable-exercise{typical.adoc}.
}

@center{@image{images/pounds.png}}

@QandA{
@Q{Do you think there is a midpoint of this sample?}
@A{There are 32 animals - meaning that there is not one point in the middle.}

@Q{Is there a value that shows up most often in this sample?}
@A{Since we see that dots are stacked up, it seems likely that there is some repetition in the animals' weights.}

@Q{What value did you decide was typical? Why?}
@A{There isn't one right answer here! The point is for students to hear each other's thinking, recognize that it's hard to summarize the data with a single number, and understand that there are different logical frameworks for doing so.}

}

Each of these are different ways of “measuring center”.

=== Investigate

The Animal Shelter Bureau used a method of summary, called the @vocab{mean}, or "average" to report about the typical weight of pets.

@QandA{
@Q{What do you already know about averages? _Answers will vary._}
@A{To find the @vocab{mean} of a dataset we add all of the values and then divide their sum by the number of values in the dataset.} 
@A{The @vocab{mean} is the number that "balances" all the other numbers in the sample.}

@Q{We are going to learn to let Pyret compute the mean for us, but let's first make sure we understand what we're asking Pyret to do! How would we find the mean weight of five animals who weigh 17, 25, 23, 23 and 22 pounds?}
@A{First add @math{17 + 25 + 23 + 23 + 22 = 110} and then divide @math{110 \div 5 = 27}}

@optional Complete the Mean section of @opt-printable-exercise{pages/mean-median-modes.adoc}, which has 5 problems including the one listed above.
}

@teacher{If you have time, we recommend completing this kinesthetic activity with your students to give them a deeper understanding!
}

@strategy{
@span{.title}{Kinesthetic Activity - Finding the Value of the Balancing Point}

The arithmetic mean is the number that "balances" all the other numbers in the sample. So let's do some real balancing!

__Divide the class into groups of three. Supply each group with a ruler and 4-8 pennies. Make sure every group has at least one pen or pencil.__

1. The ruler represents a number line with values (weight) distributed equally across the line. If there's values at every inch from 0 to 12, where should the pencil be placed in order to balance the ruler on top of it?
2. Place a penny at 1 and 11. Where must the pencil be placed to balance those two values? What is the mean of the values [1, 11]?
3. Place pennies at 1, 9 and 11. Where must the pencil be placed to balance those two values? What is the mean of of the values [1, 9, 11]?
4. Suppose you were to place two pennies at 2, and a third penny at 8. Can you _predict_ where the pencil should be placed?
}

Pyret has a function that will compute the mean -- or average -- of any quantitative column in a Table. 

@hspace{2em} @show{ (contract "mean" '("Table" "String") "Number" )}

Let's test it out!

@lesson-instruction{
* Log into @starter-file{program-list}, open your saved "Animals Starter File" and click "Run". 
** _If students don't have the file, they can open a new one from @starter-file{animals}._
* Turn to @printable-exercise{summarizing-columns-moc.adoc} and use the provided code to compute and record the @vocab{mean} weight.
}

@QandA{
@Q{How did your calculation compare to the Animal Shelter Bureau's claim that the average pet weighs nearly 40 pounds?}
@A{39.715625 is very close to 40!}

@Q{When might it be useful to know the average weight of the animals? _Answers will vary._}
@A{If we were transporting them to a different shelter, knowing the average weight might help us confirm that a truck, boat or plane could support their collective weight.}

@Q{When might it be risky to describe the weight of these animals using the average? _Answers will vary._}
@A{If one of them were sick and we wanted to give it medicine, basing the dosage on the average would likely be way too little medicine for a big animal or a dangerously large amount of medicine for a little animal.}
}

=== Possible Misconceptions

Just because a column contains numbers doesn't mean the data is quantitative. We could sum and divide a collection of zipcodes, for example, but the output wouldn’t correspond to some “center” zip code.

=== Synthesize

- If you heard that the mean age of students in a kindergarten class was 21, would you be surprised? Why or why not?

== Median @duration{15 minutes}

=== Overview
Students learn the algorithm and code for a second measure of center: the @vocab{median} and consider situations where taking the median is more appropriate than the mean. 

=== Launch
You computed the mean of that column to be almost exactly 40 pounds. That IS the average, but if we scan the dataset we'll quickly see that most of the animals weigh less than 40 pounds! In fact, more than half of the animals weigh less than just 15 pounds. Why is the average so high?

_Kujo and Mr. Peanutbutter!_

The mean is being thrown off by a few extreme data points, called @vocab{outliers} because they fall far outside of the rest of the dataset. 

The mean may also be thrown off by the presence of @vocab{skewness}: a lopsided shape due to values trailing off to the left or right.

Another measure of center is the @vocab{median}, or “middle” value of a list. 
To find it we line up all of the data points -- in order -- and find a point in the center where half of the values are smaller and the other half are larger.

As an example, consider this list of ages:

`25, 26, 28, 28, 28, 29, 29, 30, 30, 31, 32`

Here 29 is the @vocab{median}, because it separates the "bottom half” (5 values below it) from the top half” (5 values above it).

The algorithm for finding the median of a quantitative column is:

1. Sort the numbers
2. Cross out the highest and lowest number
3. Repeat until there is only one number left...
4. When there are an even number of numbers in the list, as in the example below, there will be two numbers left at the end. Take the _mean_ of those two numbers.

`3, 7, 9, 21`

The median of this list is 8, because 8 is the mean of 7 and 9, the two middle numbers. (@math{7 + 9 = 16 and 16 \div 2 = 8})

@lesson-instruction{
Find the @vocab{median} value of each of these two lists:

* 11, 3, 7 ,4, 5 
* 11, 3, 7, 4

@optional Turn to the Median section of @opt-printable-exercise{pages/mean-median-modes.adoc}, which has space to complete these problems and three others.
}
@teacher{

* The median of 11, 3, 7 ,4, 5 is 5, 
** because it's the middle value of 3, 4, 5, 7, 11.
* The median of 11, 3, 7, 4 is 5.5 
** because it's the mean of 4 and 7, which are the middle values in the ordered list 3, 4, 7, 11

}
=== Investigate
@lesson-instruction{
* Turn back to @printable-exercise{summarizing-columns-moc.adoc} and use the provided code to compute and record the median for the `pounds` column in the Animals Dataset.}

@QandA{
@Q{How do the mean and median compare?}
@A{The median (11.3) is very different from the mean (39.7)!}

@Q{Here we see the median (red) and mean (blue). @image{images/num-line-pounds2.png} Which do you think better represents the data?}
@A{The median} 

@Q{If the median were much higher than the mean, what would we expect to be true about the distribution of the dataset?}
@A{The dataset is skewed left or has some very low outliers.}
}

@lesson-point{
The @vocab{mean} is a useful calculation when all of the points are fairly balanced on either side of the middle, but it distorts things for datasets with imbalance and extreme outliers. For skewed datasets, the @vocab{median} is a better summary.}

=== Synthesize
Looking at the shape of the data (via a histogram, for example), helps us determine whether it's probably better to use the mean or median.

Strong left skewness and/or low outliers can pull the mean down below the median, while right skewness and/or high outliers can pull it up above the median.

Mean is generally the best measure of center, because it includes information from every single point. But it's misleading for highly-skewed datasets, so statisticians fall back to the median.

== Modes @duration{10 minutes}

=== Overview
Students learn about the mode(s) of a dataset, how to compute them, and when it is appropriate to use them as a measure of center.

=== Launch
The third measure of center is called the @vocab{modes} of a dataset. The @vocab{modes} of a dataset are the values that appear _most often_.

Median and Mean always produce one number and many datasets are what we call “unimodal”, having just one mode. But sometimes there are exceptions!

* If two or more values are equally common, there can be more than one mode.
* If all values are equally common, then there is no mode at all!

Consider the following three datasets:

  1, 2, 3, 4
  1, 2, 2, 3, 4
  1, 1, 2, 3, 4, 4

- The first dataset has _no mode at all!_
- The mode of the second dataset is 2, since 2 appears more than any other number.
- The modes (plural!) of the last dataset are 1 and 4, because 1 and 4 both appear more often than any other element, and because they appear equally often.

@lesson-point{
Modes are rarely used to summarize quantitative data. It is very common as a summary of _categorical_ data, telling us which category occurs most often.}

@lesson-instruction{
Take a minute to identify the mode(s) for each of the following datasets:

* 11, 3, 7, 4, 5  
* 5, 7, 11, 11, 7, 7    
* 2, 3, 5, 4, 3, 7, 4

@optional Turn to the Mode(s) section of @opt-printable-exercise{pages/mean-median-modes.adoc} to complete these problems along with two others.
}

@ifproglang{pyret}{
Pyret has a function that will compute the modes of any quantitative column in a Table. 

@hspace{2em} @show{ (contract "modes" '("Table" "String") "List<Number>" )}

_Note: `List` is a new data type!_

Let's test it out!
}

@ifproglang{codap}{
The easiest way to determine modes in CODAP is to sort a column. Do this by clicking on the column name and then selecting from the drop-down menu either Sort option. Scan the column to see which values are the most common.}

=== Investigate
@lesson-instruction{
- Turn to @printable-exercise{summarizing-columns-moc.adoc} and use the code provided to compute and record the `modes` of the `pounds` column. 
- Then complete the remaining questions in the *Summarizing the `Pounds` Column* section.
}

@QandA{
@Q{What did you learn from calculating the modes?}
@A{The most common animal weights are 0.1 and 6.5! That’s well below our mean and even our median, which is further evidence of outliers or skewness.}

@Q{Can we find the mean, median and modes for any column?}
@A{No! Measures of Center only make sense with @vocab{quantitative} data.} 
@A{Note: Not all columns that contain numbers are quantitative! Taking the average of a list of zip codes doesn’t tell us anything at all!}

}

=== Synthesize

* What must be true about a dataset for the modes to do a good job of describing what is typical?
* What can we learn from the modes of a dataset?

== The Risk of Summarizing Data with a Single Number @duration{15 minutes}

=== Overview

Students consider the complexity of summarizing with a single number and learn how to decide which measure of center to use when. They then choose a column, compute all of its measures of center in Pyret, and interpret the results. Finally, they practice computing measures of center for a small dataset by hand and use their findings to critique misleading statements.

=== Launch

Summarizing a big dataset means that some information gets lost, so it’s important to pick an appropriate summary. Picking the wrong summary can have serious implications! Here are just a few examples of summary data being used for important things:

- Students are sometimes summarized by two numbers -- their GPA and SAT scores -- which can impact where they go to college or how much financial aid they get.
- Schools are sometimes summarized by a few numbers -- student pass rates and attendance, for example -- which can determine whether or not a school gets shut down.
- Adults are often summarized by a single number -- like their credit score -- which determines their ability to get a job or a home loan.
- When buying uniforms for a sports team, a coach might look for the most common size that the players wear.

@lesson-instruction{
What examples can you think of where a number or two are used to summarize something complex?
}

=== Investigate

You now have three different ways to measure center in a dataset. Every kind of summary has situations in which it does a good job of reporting what’s typical, and others where it doesn’t really do justice to the data. But how do you know which one to use? Depending on the shape of the dataset, a measure could be really useful or totally misleading! 

@QandA{
@Q{"In 2003, the average American family earned $43,000 a year -- well above the poverty line! +
@hspace{1em} Therefore, very few Americans were living in poverty." +
Do you trust this statement? Why or why not?}
@A{Sample response: The mean is sensitive to outliers, and billionaires like Elon Musk, Jeff Bezos, etc. pull the mean heavily to the right. This makes it appear that the "average" American family earns far more than they actually do. That's why the conclusion "very few Americans were living in poverty" cannot be drawn based on the mean.}

@Q{Given the extreme income inequality in the United States, what measure of center would best represent a typical family income?}
@A{The median}
}

Consider how many policies or laws are informed by statistics like this! Knowing about measures of center helps us see through misleading statements.


*Here are some guidelines for when to use which measure of center:*

- If the data doesn’t show much skewness or have outliers, @vocab{mean} is the best summary because it incorporates information from every value.
- If the data has noticeable outliers or skewness, @vocab{median} gives a better summary of center than the mean.
- If there are very few possible values, such as AP Scores (1–5), @vocab{modes} could be a useful way to summarize the dataset.

@lesson-instruction{
* Choose a column from the Animals dataset and complete the second half of @printable-exercise{summarizing-columns-moc.adoc}. As you work, think about what the measures of center tell you about the shape of the dataset.
* Then complete @printable-exercise{critiquing-findings.adoc}. (You will be computing these measures of center without Pyret.)
* Practice the Data Cycle with measures of center, using @printable-exercise{data-cycle-practice.adoc}. 
}

=== Synthesize

* What did you learn?
* What questions surfaced?
* How did you know whether the questions on @printable-exercise{data-cycle-practice.adoc} were Arithmetic or Statistical?


== Data Exploration Project (Measures of Center) @duration{flexible}

=== Overview
Students apply what they have learned about measures of center to their chosen dataset. In their @starter-file{exploration-project}, they will complete the first four rows of the "Measures of Center and Spread" table. They will also interpret those measures of center, and record any interesting questions that emerge. To learn more about the sequence and scope of the Exploration Project, visit @lesson-link{project-data-exploration}. For teachers with time and interest, @lesson-link{project-research-paper} is an extension of the Dataset Exploration, where students select a single question to investigate via data analysis.

=== Launch
Let’s review what we have learned about computing and interpreting three measures of center - mean, median, and modes.

@QandA{
@Q{Describe how to compute mean, median, and modes.}
@Q{When does @vocab{mean} provide the best summary?}
@A{It includes information from every single point, so it is useful when the data doesn't show much skewness or have outliers.}
@Q{When does @vocab{median} provide the best summary?}
@A{Statisticians fall back to the median when working with highly skewed datasets.}
@Q{When are @vocab{mode(s)} a useful way to summarize a dataset?}
@A{Mode(s) are most useful when a dataset has very few values.}
}

=== Investigate

Let’s connect what we know about measures of center to your chosen dataset.

@teacher{Students have the opportunity to choose a dataset that interests them from our @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "List of Datasets"} in the @lesson-link{choosing-your-dataset} lesson.
}

@lesson-instruction{
- Open your chosen dataset @ifproglang{pyret}{starter file in Pyret.}@ifproglang{codap}{in CODAP.}
- Choose two quantitative columns that you'd like to analyze.
- Use @proglang to compute the mean, median and modes of one of them.
- *It’s time to add to your @starter-file{exploration-project}.*
- Locate the "Measures of Center and Spread" section of your Exploration Project and, in the slide following the example, replace `Column A` with the title of the column you just investigated.
- Then type in the mean, median and modes that you just identified. Leave the other rows blank. We will come back to them another day.
- On the next slide, repeat with `Column B` using the second column you're interested in.
}

@teacher{Invite students to discuss their results and consider how to interpret them.}

@lesson-instruction{
Add your interpretations to the two "Measures of Center and Spread" slides and record any questions that emerged in the "My Questions" section at the end of the slide deck.
}

=== Synthesize

@teacher{Have students share their findings.}

- Did you discover anything surprising or interesting about your dataset?

- Which measures of center do you think were the most useful for the quantitative columns you chose?

- What questions did the measures of center inspire you to ask about your dataset?

- When you compared your findings with other students, did you make any interesting discoveries? (For instance: Did everyone find mode(s)? Did anyone have a measure of center that was dramatically influenced by an outlier?)

== Additional Exercises
- @opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fca8f6a3d4e1f382a33f56e, Mode(s)}
