= Boolean Functions
++++
<style>
	.studentAnswerShort, .studentAnswerMedium { min-width: 8em;}
</style>
++++

Make a prediction about what each function in the @starter-file{boolean} does.

@fitb{}{}

@vspace{1ex}

@fitb{}{}

@vspace{1ex}

@fitb{}{}

@vspace{1ex}

@fitb{}{}

@vspace{1ex}

@fitb{}{}

@vspace{5ex}

Now, experiment with the functions. Fill in the blanks below so that each of the five functions returns `true`.

@ifsoln{_These are sample values; answers will vary._}

@n @show{(code '(odd? (?ANS 5)))}

@n @show{(code '(even? (?ANS 4)))}

@n @show{(code '(less-than-one? (?ANS 0)))}

@n @show{(code '(continent? (?ANS "Africa")))}

@n @show{(code '(primary-color? (?ANS "red")))}

@vspace{5ex}

Fill in the blanks below so that each of the five functions returns `false`.

@n @show{(code '(odd? (?ANS 4)))}

@n @show{(code '(even? (?ANS 3)))}

@n @show{(code '(less-than-one? (?ANS 4)))}

@n @show{(code '(continent? (?ANS "apple")))}

@n @show{(code '(primary-color? (?ANS "orange")))}
