= What Kind of Model? (Tables with Gaps)

++++
<style>
/* Shrink Images */
#content img {width: 75%; height: 75%;}

table > tbody > tr > td {
	position: relative;
	text-align: right !important;
	padding: 0.1em 0.5em !important;
}

/* Separate spacing for tables to be done as a group or independent */
.group { flex-basis: 33%; }
.independant { flex-basis: 67%; }
</style>
++++

Decide whether each representation is best described by a linear model, a quadratic model, some _other_ model, or no model at all! Record how you decided by showing any work that you feel is useful or writing an explanation.

@vspace{1ex}

*For Class Discussion:*

[.FillVerticalSpace.group, cols="^.^1a,^.^15a,<.^15a", frame="none", stripes="none"]
|===
| @n
|
[.sideways-pyret-table]
!===
! x !  0 ! 3 ! 6  !  9 ! 12 ! 15  ! 18
! y !  3 ! 5 ! 11 ! 21 ! 35 ! 53  ! 75
!===
|
Linear +
@ifsoln-choice{Quadratic}@ifsoln{@hspace{1em}growth of the growth is +4} +
Some other model/pattern +
No model

| @n
|
[.sideways-pyret-table]
!===
! x !  0 ! 2 ! 4  ! 6  !  8 ! 10 ! 12
! y !  1 ! 5 ! 9  ! 13 ! 17 ! 21 ! 25
!===
|
@ifsoln-choice{Linear}@ifsoln{@hspace{1em}constant growth +4} +
Quadratic +
Some other model/pattern +
No model
|===

*For Independent Practice:*

[.FillVerticalSpace.independent, cols="^.^1a,^.^15a,<.^15a", frame="none", stripes="none"]
|===
|@n
|
[.sideways-pyret-table]
!===
! x ! 1 ! 6 ! 11 ! 16 ! 21 ! 26 ! 31
! y ! 2 ! 5 ! 8  ! 11 ! 14 ! 17 ! 20
!===
|
@ifsoln-choice{Linear}@ifsoln{@hspace{1em}constant growth +3} +
Quadratic +
Some other model/pattern +
No model

| @n
|
[.sideways-pyret-table]
!===
! x ! -12 ! -8  ! -4  ! 0   !  4  ! 8   ! 12
! y ! -12 ! -22 ! -28 ! -30 ! -28 ! -22 ! -12
!===
|
Linear +
@ifsoln-choice{Quadratic}@ifsoln{@hspace{1em}growth of the growth is -2 then +2} +
Some other model/pattern +
No model

| @n
|
[.sideways-pyret-table]
!===
! x ! -9 ! -6 ! -3 ! 0 ! 3 ! 6 ! 9
! y ! 2  ! 3  ! 2  ! 3 ! 2 ! 2 ! 2
!===
|
Linear +
Quadratic +
Some other model/pattern +
@ifsoln-choice{No model}@ifsoln{@hspace{1em}it goes up, down, up, down and then holds steady.}

| @n
|
[.sideways-pyret-table]
!===
! x ! 1 ! 3 ! 5 ! 7  ! 9  ! 11 ! 13
! y ! 3 ! 4 ! 7 ! 12 ! 19 ! 28 ! 39
!===
|
Linear +
@ifsoln-choice{Quadratic}@ifsoln{@hspace{1em}growth of the growth is +2} +
Some other model/pattern +
No model

| @n
|
[.sideways-pyret-table]
!===
! x !  1 !  6 !  11 !  16 !   21 !    26
! y !  5 ! 25 ! 125 ! 625 ! 3125 ! 15625
!===
|
Linear +
Quadratic +
@ifsoln-choice{Some other model/pattern}@ifsoln{@hspace{1em}growth keeps increasing! each y-value is 5x the last} +
No model

| @n
|
[.sideways-pyret-table]
!===
! x ! 1  ! 5  ! 9  ! 13 ! 17 ! 21 ! 25
! y ! 50 ! 53 ! 57 ! 62 ! 68 ! 75 ! 83
!===
|
Linear +
@ifsoln-choice{Quadratic}@ifsoln{@hspace{1em}growth of the growth is +1} +
Some other model/pattern +
No model
|===
