= Graphing Quadratic Models
++++
<style>
/* Make autonums inside tables look consistent with those outside */
.autonum { font-weight: bold; padding-top: 2px !important; }
.autonum:after { content: ')' !important; }

/* Custom graph settings and axis labels */
.graph td {
	background-size: 100px 100px, 100px 100px, 20px 20px, 20px 20px !important;
	background-position: -3px 74px !important;
	height: 1.5in !important;
	width: 2in !important;
	background-image:
		linear-gradient(270deg, lightblue 2px, transparent 2px),
		linear-gradient(lightblue 2px, transparent 2px)
		!important;
}

}
</style>
++++

[.linkInstructions]
For this page, you'll need to have *Exploring Quadratic Functions(Desmos)* open on your computer. +

The parabola you'll see is the graph of @math{g(x) = x^2}. Another, *identical* parabola is hiding behind it. +
This second parabola is written in Vertex Form: @math{f(x) = a(x - h)^2 + k}. Each coefficient starts at values to make @math{f(x)} equivalent to @math{g(x)}.

@n Using the starting values of @math{a}, @math{h}, and @math{k} you see for @math{f(x)} in Desmos, rewrite @math{g(x) = x^2 } in Vertex Form. @hspace{1em} @math{g(x) =}@fitb{}{@ifsoln{@math{1(x - 0)^2 + 0}}}

== Magnitude @math{a}
@n Try changing the value of @math{a} to -4, 0, and 2, graphing each parabola in the squares below. *Label the vertex "V" and any roots with "R"!*


[.FillVerticalSpace.graph, cols="1,1,1", frame="none"]
|===
| @math{a = -4}	| @math{a = 0}	| @math{a = 2}
|===

@n What does @math{a} tell us about a parabola? @fitb{}{@ifsoln{The parabola opens "up" if it's positive, and "down" if negative}} +
@fitb{}{@ifsoln{The larger the magnitude, the "tighter" the parabola. If it's zero, the graph is a straight line}}

== Horizontal Translation @math{h}
@n Set @math{a} back to 1. Change the value of @math{h} to -5, 0, and 5, graphing each parabola in the squares below. *Label the vertex "V" and any roots "R"!*


[.FillVerticalSpace.graph, cols="1,1,1", frame="none"]
|===
| @math{h=-5}	| @math{h=0}	| @math{h=5}
|===

@n What does @math{h} tell us about a parabola? @fitb{}{@ifsoln{How far the parabola is shifted left (negative h) or right (positive h)}} +


== Vertical Translation @math{k}
@n Set @math{h} back to 0. Change the value of @math{k} to -5, 0, and 5, graphing each parabola in the squares below. *Label the vertex "V" and any roots "R"!*


[.FillVerticalSpace.graph, cols="1,1,1", frame="none"]
|===
| @math{k=-5}	| @math{k=0}	| @math{k=5}
|===

@n What does @math{k} tell us about a parabola? @fitb{}{@ifsoln{How far the parabola is shifted up (positive k) or down (negative k)}} +

