= Function Applications 2 (Animation with Functions)

@lesson-description{Students create the functions that will control animation in parts of their game.}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Apply the Design Recipe to create a function with given parameters
* Explain the basics of animation

|Student-Facing Lesson Goals
|
* I can use the Design Recipe to make a function.
* I can describe how animation works.

|Key Points for the Facilitator
|
* Encourage students to take their time in understanding _why_ we want to fix `update-danger` and `update-target`.  
* Students might be confused as to _how_ the animation is working.  The `make-game` function at the bottom of the file has many inputs - including `update-danger` and `update-target`.  `make-game` takes in all those inputs, including the functions we'll write, and creates the interactive window that we see when we press the Run button!  

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.
* Students should be familiar with the Design Recipe.

|Materials
|
* Lesson slides template (@link{https://docs.google.com/presentation/d/1s0pJgX0YEjM70wLPtJVAKikK3jv8AfNwZ30fxVBANhY/view, Google Slides})
* Design Recipe: update-danger (@worksheet-link{workbook-pages/FunctionApplications2-WB1.adoc, PDF})
* Design Recipe: update-target (@worksheet-link{workbook-pages/FunctionApplications2-WB2.adoc, PDF})

|===

[.left-header,cols="20a,80a", stripes=none]
|===

|Addressing (CCSSM)
|
* @std{8.F.B}

|Approaching (CCSSM)
|
* @std{HSF.LE.B}

|Standards for Mathematical Practice (CCSSM)
|
* @std{MP.2}

|Bootstrap Benchmarks
|
* @std{BS-PL.3}
|===


== Get Ready:

Students should have their computer, contracts page, and pencil.  Students should have their own *game file* open in a separate window or tab.

== Launch: (5 min)

* How does animation work?
* Why do we see movement from still images? 
+
_Our eyes fill in the gaps between rapidly changing images._
* How might this apply to our game? _If we change image coordinates a little bit at a time, they will appear to move._

== Discuss: (15 min)

=== Role Play:

Select 2 student volunteers - one to be TARGET, one to be DANGER.  Start with just TARGET.

* TARGET moves a step to the left when they hear "update target" followed by a number.
* We make TARGET move by calling out `(update-target 10)`, `(update-target 11)`, etc.  

*How quickly could I get TARGET to move across the classroom?*

After practicing with TARGET, add DANGER in.

* DANGER takes a step to the right when they hear "update danger" followed by a number.
* We make DANGER move by calling out `(update-danger 40)`, `(update-danger 39)`, etc.

*How quickly could I get TARGET and DANGER to move across the room?*

You'll have to call quickly to TARGET and DANGER, but it is very repetitive and tedious, and TARGET and DANGER won't be moving very fast!

* *What did you notice about the movement of TARGET and DANGER?  What was changing about them?* 
+
_Answers will vary: they were moving horizontally, their x-coordinates were changing, they were not moving smoothly, etc._

* *What would have happened if we'd added PLAYER?* 
+
_It would have been more difficult to move them all simultaneously._

* *What jobs could we hand over to the computer to make it possible for us to play the game?* 
+
_The computer could handle automatically moving TARGET and DANGER, then we could control the movement of PLAYER._

== Practice (15 min)

Have students examine the `update-danger` function in their Game Template file, identify the contract, and interpret what the function is currently doing.  

Guide students as they complete @worksheet-link{workbook-pages/FunctionApplications2-WB1.adoc, Design Recipe: update-danger} and transfer the code to their Game Template file.  

When students press the Run button, the working `update-danger` function should automatically move the `DANGER` image across the screen!  

== Apply (15 min)

Have students complete @worksheet-link{workbook-pages/FunctionApplications2-WB2.adoc, Design Recipe: update-target} with their partner and transfer the code to their Game Template file.  Press Run to see `DANGER` and `TARGET` move across the screen independently!

[.strategy-box]
.Extension Activities
****
Once students have successfully gotten `update-target` and `update-danger` working, they can change the functions to make the characters move in whichever direction and whatever speed they want!  They should be sure to modify their purpose statements and examples if they change their functions.
ifeval::["{proglang}" == "wescheme"]
Want 2-D movement?  A supplemental lesson @link{https://www.bootstrapworld.org/materials/fall2019/courses/algebra/en-us/units/Supplemental/index.html#lesson_Structs, linked here} provides information on how to modify these functions to allow movement in the x _and_ y directions!
endif::[]
****


