= Function Notation

@description{Students learn to read function notation and evaluate expressions using function definitions, tables, and graphs. Students also describe the order of operations involved in algebraic function compositions such as f(g(h(x)))}

@lesson-prereqs{functions-make-life-easier, defining-values}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:
@objectives

@objective{function-application}
@objective{function-comp-ooo}

| Student-Facing Lesson Goals
|

- Let's learn how to find the value of an expression such as f(3), from a table, a graph or a symbolic definition.

| Materials
|[.materials-links]

*This lesson is _unplugged_, and does not require a computer.*

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
| 
@preparation{
- There is an optional interactive Desmos activity in the lesson. If you would like to use it, decide how you will share it with students and, if you are using our Google Slides, add the appropriate link to the slide deck. _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}
}

|===

== Function Notation (Definitions)

=== Overview

Students connect their understanding of function definitions in @proglang to function definitions in math.

=== Launch
@slidestyle{Launch}

We've seen how functions like `gt` can be defined, and then @vocab{applied} to a number to create a green triangle. And once `gt` is defined, we can use it with many different numbers to create many different triangles - all without having to write out `"solid"`, `"green"`, etc.

But how does this function _work?_

@slidebreak{LaunchC}

When we apply a function to some inputs, we @vocab{substitute} those inputs for the @vocab{variables} in the definition. In the example below, the inputs are @vocab{substituted} for the variable `size` in the body of the `gt` function.

@center{*@show{(code '(define (gt size)(triangle size "solid" "green")))}*}
[cols="^.^2,^.^3,^.^2", options="header"]
|===
| Apply the Function 	| Substitute the Input(s) 	| Compute the Answer
| @show{(code '(gt 10))}	| @show{(code '(triangle 10 "solid" "green"))} 		| @image{images/gt10.png}
| @show{(code '(gt 20))}	| @show{(code '(triangle 20 "solid" "green"))} 		| @image{images/gt20.png}
| @show{(code '(gt 30))}	| @show{(code '(triangle 30 "solid" "green"))} 		| @image{images/gt30.png}
| @show{(code '(gt 40))}	| @show{(code '(triangle 40 "solid" "green"))} 		| @image{images/gt40.png}
| @show{(code '(gt 50))}	| @show{(code '(triangle 50 "solid" "green"))} 		| @image{images/gt50.png}
|===

@vspace{1ex}

@slidebreak{LaunchC}

Let's take a look at a @vocab{function} that works with Numbers:

@center{*@show{(code '(define (f x) (+ x 8)))}*}
[cols="^.^2,^.^3,^.^2", options="header"]
|===
| Apply the Function 	| Substitute the Input(s) 	| Compute the Answer
| @math{f(10)} 			| @show{(code '(+ 10 8))} 	| 18
| @math{f(20)} 			| @show{(code '(+ 20 8))} 	| 28
| @math{f(30)} 			| @show{(code '(+ 30 8))} 	| 38
| @math{f(40)} 			| @show{(code '(+ 40 8))} 	| 48
| @math{f(50)} 			| @show{(code '(+ 50 8))} 	| 58
|===

@vspace{1ex}

Once again, the input is @vocab{substituted} for the variable.

@slidebreak{Launch}

You've already seen that @proglang looks a little different from traditional math, even if it behaves the same way.

Math books use something called @vocab{Function Notation} to define functions. Here's a side-by-side comparison of the same function, in @proglang and in function notation:

[cols="^1a,^1a", options="header"]
|===
| Defining Functions in @proglang
| Defining Functions in Function Notation
| @show{(code '(define (f x) (+ x 8)))}
| @math{f(x) = x + 8}
|===

@QandA{
@Q{What do these forms have in common?}
@A{Both forms show the *name of the function*, as well as the *names of the variables*. They also show *what the function does with those variables*.}
@Q{How are these forms different from one another?}
@A{In Pyret, we use a colon instead of an equals sign. In Pyret, we see `fun` at the beginning and `end` at the end.}
}

@ifproglang{pyret}{
@ifnotslide{
In math - just as in programming - we *compute the value* of the expression *for any specific input by substituting* numbers for the variable(s) used in the definition, just as we did with `gt`.
}
}

@ifproglang{wescheme}{

@slidebreak{LaunchC}

In math - just as in programming - we *compute the value* of the expression *for any specific input by substituting* numbers for the variable(s) used in the definition, just as we did with `gt`.

@center{*@math{f(x) = x + 8}*}
[cols="^.^2,^.^3,^.^2", options="header"]
|===
| Apply the Function 	| Substitute the Input(s) 	| Compute the Answer
| @math{f(10)} 			| @math{10 + 8} 			| 18
| @math{f(20)} 			| @math{20 + 8} 			| 28
| @math{f(30)} 			| @math{30 + 8} 			| 38
| @math{f(40)} 			| @math{40 + 8} 			| 48
| @math{f(50)} 			| @math{50 + 8} 			| 58
|===

}

=== Investigate
@slidestyle{Investigate}

@lesson-instruction{
- Turn to @printable-exercise{match-examples-definitions-math.adoc} 
- Start by looking at each table and highlighting what is changing from the first row to the following rows.
- Then, match each table to the function that defines it.
}

@opt{
You may also want to have students complete @opt-starter-file{function-notation-match}
}

@lesson-instruction{
- Turn to @printable-exercise{function-notation-substitution.adoc}.
}

@teacher{
@star For more challenging function notation evaluation exercises direct students to @opt-printable-exercise{function-notation-challenge.adoc}.
}

=== Synthesize
@slidestyle{Synthesize}

You can think of @math{f(3)} as a question.
@QandA{
@Q{What question is it asking you to @vocab{evaluate}?}
@A{What is the value of @math{x + 8} when @math{x} is 3?}
@Q{What is another way you can ask it?}
@A{What is @math{3 + 8}?}
}

== Function Notation (Graphs)

=== Overview

Students will learn to connect function definitions to Graphs.

=== Launch
@slidestyle{Launch}

@QandA{
@Q{If @math{f(x) = x - 5}, what is the value of @math{f(7)}, and why?}
@A{@math{2}. Because if we substitute 7 for x we get @math{7 - 5 = 2}}
@Q{What is the value of @math{f(8)}?}
@A{@math{3}. Because if we substitute 8 for x we get @math{8 - 5 = 2}}
@Q{What is the value of @math{f(9)}?}
@A{@math{4}}
}

For each of these inputs, we have an output. If we graph each input-output pair on the @vocab{coordinate plane}, we can "see" the function as a @vocab{line} on a graph.

@slidebreak{LaunchR}

Let's take a look at the graph of @math{f(x) = x - 5}.

@ifnotslide{
@centered-image{images/gr1.png, 350}
}

@ifslide{@image{images/gr1.png, 350}}

@QandA{
@Q{How could we have determined that @math{f(7) = 2} from looking at the graph, if we hadn't started with the function definition?}
@A{We could have looked for a point whose y-coordinate was 2. This would lead us to the point (7, 2), which tells us that the output of the function when x is 7 is 2.}
@Q{From looking at the graph, what is the value of @math{f(3)}?}
@A{-2}
@Q{What other values on this graph could we describe using function notation?}
@A{Answers will vary. For example: @math{f(0) = -5} or @math{f(0.5) = -4.5}}
}

@slidebreak{LaunchR}

Even if we can't see the _definition_ of a function, we can reason about it just by looking at the graph!

Let's look at the graph below, which shows only a few points on the line drawn by a function:

@ifnotslide{@centered-image{images/sp.png, 350}}
@ifslide{@image{images/sp.png, 350}}

@QandA{
@Q{From looking at the graph, what is the value of @math{f(-2)}?}
@A{-4}
@Q{What is the value of @math{f(1)}?}
@A{2}
@Q{What is the value of @math{f(3)}?}
@A{There isn't one! It's undefined.}
@Q{What other values on this graph could we describe using function notation?}
@A{Answers will vary. For example, @math{f(-1) = 4} or @math{f(2) = 4}}
}

@strategy{Optional: Piecewise Functions}{


When evaluating an expression for a piecewise function, points on the graph marked with hollow circles are boundary points, but not part of the solution set, so we ignore them and focus on the solid points. For example, on the graph below, when evaluating @math{f(2)}, we ignore the hollow point at @math{(2, 4)} and focus on the solid point at @math{(2,3)}, so @math{f(2) = 3}.

@ifnotslide{@centered-image{images/pw.png}}
@ifslide{@image{images/pw.png}}

What is the value of @math{f(0)} in the graph above? _3_
}

=== Investigate
@slidestyle{Investigate}
@lesson-instruction{
Complete @printable-exercise{function-notation-graphs.adoc}.
}

@opt{If your students are ready for a challenge (piecewise functions!), have them work on @opt-printable-exercise{function-notation-graphs-pw.adoc}.}


=== Synthesize
@slidestyle{Synthesize}
@QandA{
@Q{Can you think of any values that it would be difficult to determine from one of these graphs?}
@A{It would be hard to be precise for many of the points on the graphs that curve. For example, @math{f(4)} on the second graph would have to be a decimal value and it's hard to know exactly what the decimal should be without a function definition to evaluate...}
}

== Function Notation (Tables)

=== Overview

Students will learn to connect function definitions to input-output Tables.

=== Launch
@slidestyle{Launch}

@lesson-instruction{
Take a look at the table of input-output pairs that satisfy the function @math{f(x) = x - 5}.
[.sideways-pyret-table]
|===
| x | -10 | -5  | 5 | 7 | 13
| y | -15 | -10 | 0 | 2 | 8
|===
}
@QandA{
@Q{How could we use the table to determine the value of @math{f(7)}?}
@A{We would just look for 7 in the x-column and see that the value beside it is 2.}
@Q{What is the value of @math{f(-10)}?}
@A{-15}
}


=== Investigate
@slidestyle{Investigate}
@lesson-instruction{
Complete @printable-exercise{function-notation-tables.adoc}.
}

=== Synthesize
@slidestyle{Synthesize}

@QandA{
@Q{What did you Notice?}
@Q{What did you Wonder?}
@Q{A few of the tables did not represent functions. Which ones?}
@A{The last one in the top row, the last one in the middle row and the 3rd one in the bottom row.}
@Q{How did the fact that those tables weren't functions impact our ability to describe a value using function notation?}
@A{When x appeared more than once in the table and was associated with different outputs, it wasn't clear what number the expression should evaluate to.}
}

== Diagramming Function Composition

=== Overview
The Circles of Evaluation are extended to provide a visual-spatial metaphor for function composition, in addition to Order of Operations.

=== Launch
@slidestyle{Launch}

Suppose we had the following three function cards for the functions `f`, `g`, and `h`:

- `f` multiplied its input by 3
- `g` added six to its input
- `h` subtracted one from its input

We can compose those functions in any order. If we composed them as `f(g(h(x)))` and evaluated them for `x = 4` what would happen?

We can diagram the function composition using Circles of Evaluation (see first column, below). In the second column, we've replaced the function names in each Circle of Evaluation with _what each function does_:

[cols="^1,^2", options="header", stripes="none"]
|===

| Function Composition
| Order of Operations
| @show{(coe `(f (g (h x))))}
| @show{(coe `(* 3 (+ (- x 1) 6)))}
|===

@slidebreak{Launch}

@ifslide{
[cols="^1,^2", options="header", stripes="none"]
|===

| Function Composition
| Order of Operations
| @show{(coe `(f (g (h x))))}
| @show{(coe `(* 3 (+ (- x 1) 6)))}
|===

}

The circles show us that in order to evaluate @math{f(g(h(4))))}

- First we would have to evaluate @math{h(4)}, subtracting `1` from `4` to get `3`
- Then we would evaluate @math{g(3)}, adding `6` to `3` to get `9`
- Then we would evaluate @math{f(9)}, tripling `9` to get `27`

=== Investigate
@slidestyle{Investigate}

@lesson-instruction{
Turn to @printable-exercise{diagramming-function-composition.adoc} to practice writing, translating and evaluating Circles of Evaluation of composed functions.
}

@teacher{
More practice is available on @opt-printable-exercise{function-comp-matching.adoc} and @opt-printable-exercise{diagramming-function-composition-2.adoc}.
}

=== Synthesize
@slidestyle{Synthesize}

@QandA{
@Q{Do @math{f(g(h(x)))} and @math{g(h(f(x)))} evaluate to the same thing? Why or why not?}
@A{No, they do not. Order matters!}
}

@pd-slide{
*Diagramming Function Composition Worksheet Debrief*

What is the utility of this activity?

- Students visualize composing functions.
- They get to see two dimensions and not focus exclusively on going left to right.
- There are many ways to scaffold.
- Building conceptual (not procedural) understanding.
}

@pd-slide{
*Diagramming Function Composition Worksheet Debrief*

The circles give students something to fall back on if they need it.

Circles also allow us to ask some interesting questions - like, do @math{f(g(h(x)))} and @math{g(h(f(x)))} give you the same thing?

We can hold up the circles on the board and say, "draw the first one for me," - then, "draw the second one for me?" to discover if the structures are doing the same work or not.
}
