= Reading Histograms

Using the histogram below, respond to the questions about the distribution of dogs weights at a small local animal shelter.

[cols="^.^3a,3a"]

|===


| @image{../images/dog-pounds-small.png, 350}

|
@n) How many dogs are represented on the histogram? @fitb{5em}{}

@n) How many dogs weigh less than 100 pounds? @fitb{5em}{}

@vspace{1ex}

@n) True or False? The majority of dogs weigh between 40 and 60 pounds.

@vspace{1ex}

@n) True or False? More than half of the dogs weigh less than 80 pounds.

@vspace{1ex}

@n) True or False? The dogs weigh between 20 and 180 pounds.

@vspace{1ex}

@n) True or False? The heaviest dog weighs between 40 and 60 pounds.

|===


@vspace{1ex}

Using the histogram below, respond to the questions about dogs' weights at a different (much larger) animal shelter.


[cols="^.^3a,3a"]

|===

|
@image{../images/dog-pounds.png, 350}

|

@n) True or False? There are two dogs that weigh 160 pounds or more.

@vspace{1ex}

@n) True or False? The majority of the dogs weigh between 40 and 60 pounds.

@vspace{1ex}

@n) True or False? The lightest dog weighs zero pounds.

@vspace{1ex}

@n) True or False? The most common weight is between 50 pounds.

@vspace{1ex}

@n) True or False? There are 180 dogs at this animal shelter.

@vspace{1ex}

@n True or False? There are more than 150 dogs at this animal shelter.

|===

@vspace{1ex}



Using the histogram below, write three statements about the cats' weights and their distribution at the large animal shelter.

[cols="^.^3a,3a"]

|===

|
@image{../images/cat-pounds.png, 350}

|

@n) @fitb{}{}

@fitb{}{}

@fitb{}{}

@n) @fitb{}{}

@fitb{}{}

@fitb{}{}

@n) @fitb{}{}

@fitb{}{}

@fitb{}{}


|===
