= Create Your Own Logo
++++
<style>
body.workbookpage .autonum { padding-top: 1rem; }
</style>
++++
Let's think more deeply about the logo we are going to create. You'll want to refer to the sketch you have already drawn.

@n Now that you've gotten feedback from a friend on your logo design, are there any changes or updates you'd like to make? Describe those changes below. @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Put a checkmark by each of the shapes that you are going to include in your logo. You must choose at least two. If you plan to use one image multiple times, you can add additional checkmarks next to it.

[.FillVerticalSpace, cols="2a,2a,2a,2a"]
|===

|
* [ ] circle |
* [ ] ellipse |
* [ ] text	|
* [ ] rectangle |
* [ ] rhombus |
* [ ] triangle |
* [ ] radial-star | |

|===

@n Put a checkmark by each of the functions you will use to transform the selected images. You must choose at least two functions. If you plan to use one function multiple times, you can add additional checkmarks next to it.


[.FillVerticalSpace, cols="2a,2a,2a,2a"]
|===

|
* [ ] above |
* [ ] beside |
* [ ] flip-horizontal	|
* [ ] flip-vertical |
* [ ] rotate |
* [ ] scale |
* [ ] overlay ||

|===

@n Draw a Circle of Evaluation to show how you will compose the functions you selected (above) in order to create your logo. If you need more space, use a separate sheet of paper.

@vspace{25ex}

@n Open Pyret. Log in. Translate your circle into code, then type that code into the Interactions Area and hit Enter. Did it work? @fitb{}{}

@n If your logo doesn't look how you envisioned it, try again until your logo resembles your sketch. On the lines below, describe one adjustment that you made.@fitb{}{}

@fitb{}{}

@fitb{}{}

@n Now, we're going to define `my-logo` so that typing `my-logo` produces _your logo_!

- Copy/paste your code from the Interactions Area into the Definitions Area. (In other words, move your code from the right side of the screen to the left side.)
- In front of your code, type `my-logo =`
- Hit “Run”.
- Type `my-logo` into the interactions area to make sure everything is working as it should! (You should see your logo!)

@n Add a comment to the Definitions Area describing (1) why you designed your logo the way you did, and (2) one thing you learned from completing this project.

@n Save your program. Select "File", then "Save a Copy."

@n Now, go to "Publish", and copy the link that appears. Follow your teacher’s instructions and submit the link via email, google classroom, or some other method.
