= Designing Your Logo

== Design Your Logo

@n It's your turn! In the space below (or on a separate page), draw the logo of your dreams. You can make a logo or design to represent yourself, a friend, an activity or an artist that you love… the possibilities are endless.

@vspace{30ex}

@n Choose specific @link{https://pyret.org/docs/latest/color.html, "Pyret colors"} for your logo! If something is "cornflower-blue" or "fire-brick", draw an area to the appropriate region and label it with the color's name.


== Plan Your Logo's Code

Let's think more deeply about the logo we are going to create. Refer to your logo drawing in order to respond to the prompts below.

@n Put a checkmark by each of the **shape functions** that you are going to include in your logo. **You must choose at least two!** If you plan to use a function multiple times, you can add additional checkmarks next to it.

[cols="2a,2a,2a,2a", stripes="none", frame="none"]
|===
| * [ ] circle
| * [ ] ellipse
| * [ ] square
| * [ ] rectangle
| * [ ] text
| * [ ] rhombus
| * [ ] triangle
| * [ ] radial-star

|===

@n Put a checkmark by each of the **transformation functions** that you are going to use in your logo. **You must choose at least two!** If you plan to use a function multiple times, you can add additional checkmarks next to it.


[cols="2a,2a,2a,2a", stripes="none", frame="none"]
|===
| * [ ] above
| * [ ] beside
| * [ ] flip-horizontal
| * [ ] flip-vertical
| * [ ] rotate
| * [ ] scale
| * [ ] overlay
|
|
|===


== Peer Review

@n Swap papers with a partner. Write your name on the line so that your teacher knows who is reviewing this design. @fitb{}{}

@n What do you like about this logo? @fitb{}{}

@fitb{}{}

@n What suggestions do you have to make the logo even better? @fitb{}{}

@fitb{}{}

@n Did you partner correctly label all colors and shapes? If no, explain what they missed. @fitb{}{}

@fitb{}{}

@n Did your partner correctly choose their shape functions? How about their transformation functions? @fitb{}{}

@fitb{}{}

@n Return this paper to its owner! Verbally share any additional feedback.
