= Sample Logo Study

Respond to the questions below using @starter-file{logos}.

@n First, we're going to look at three different sample logos.

- Click "Run".
- Type `sample-logo-1` in the Interactions Area (right side) and hit enter.
- Now type `sample-logo-2` in the Interactions Area.
- Finally, make `sample-logo-3` appear in your Interactions Area.

@n Which logo was your favorite? @fitb{10em}{} What did you like about it? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n Look at the code for the logo you choose in the previous question. Does it use the color blue? Green? Red? List all of the colors that the programmer used to create this logo.

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n Does the code use the `triangle` function? The `circle` function? List all of the _image-producing functions_ that the programmer used to create this logo.

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n Does the code use the `rotate` function? The `overlay` function? List all of the _image-transforming functions_ that the programmer used to create this logo.

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n It's your turn! In the space below (or on a separate page), draw the logo of your dreams. You can make a logo to represent yourself, a friend, an activity or an artist that you love… the possibilities are endless.

@vspace{30ex}

@n If you used a rhombus (or any other shape!), label it "rhombus". If one shape is a combination of a few shapes, label those. If something is "cornflower-blue" or "fire-brick" (or @link{https://pyret.org/docs/latest/color.html, "any other color!"}), make a note of that too.
