= Collaboration

@description{Students practice using the Design Recipe through a variety of collaborative exercises that allow them to interact with each other's work and receive feedback from peers, ultimately helping them to internalize the importance of attending to precision at each step of the way.}

@lesson-prereqs{functions-solving-word-problems}

@keywords{design recipe}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* Understand how to use the @vocab{Design Recipe} to break down simple word problems.
* Create a strong @vocab{purpose statement} that details in their own words what the @vocab{function} is doing.

| Student-Facing Lesson Goals
|
* I can use the Design Recipe to break down word problem when writing a function.
* I can identify @vocab{domain} and @vocab{range} and other quantities in a word problem when writing a function.
* I can create and revise a strong purpose statement that explains what the function is doing.

| Materials
|[.materials-links]

@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/12z55qWiqNIqwfR7kj8P6WUFRo9L8F7wkQZ65AkQRY1w/, Lesson Slides}
}
@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1JnoyCyDqbCXDXIl1r324WPmQBNvp7XRCMj3mexFo28o/, Lesson Slides}
}

@material-links

| Preparation
| Decide on groups of 3 and print copies of the word problems that you will be using for Design Recipe Telephone

* The purpose statement, like the contract, is a comment - something that the computer doesn't read.  It's important for readability of their code - there may be other people looking at their code and using their functions!
* The domain and range of a function are described as @vocab{data types}, such as Number, String, or Image.
* This activity can work well as a formative review.
* This activity is a good time to get students working with someone other than their usual coding partner.
|===

== Design Recipe Telephone @duration{45 minutes}

@n Divide the class into groups of three.

@n Choose which set of word problems you are going to start with and give each student within each group a different word problem.

[cols="4a,5a,3a", options="header"]
|===
|Word Problem Set 1:
|Word Problem Set 2:
|Option 3:
|
@opt-printable-exercise{dr-g.adoc}

@opt-printable-exercise{dr-h.adoc}

@opt-printable-exercise{dr-r.adoc}

_★ Once completed, the set of functions generated from these word problems can be used to fix the code in this @opt-starter-file{collaboration}, which will then generate a cool image._
|
@opt-printable-exercise{dr-symmetry.adoc}

@opt-printable-exercise{dr-l-rect.adoc}

@opt-printable-exercise{dr-right-trapezoid.adoc}
| Use any of the practice word problems in the workbook that students haven't solved before.

_★ There is a large collection of math problems that would work well with the Design Recipe in our @link{bootstrapworld.org/materials/latest/en-us/functions-solving-word-problems, Solving Word Problems Using the Design Recipe} lesson._
|===

@vspace{1ex}

[.lesson-instruction]
--
In this activity, each person in your group will start with a different word problem.

* You will each be doing one step of each Design Recipe problem.
* When you complete that step, you will fold your paper to hide the part that you were looking at so that only your work and the rest of the recipe is visible.
* Then you will pass your work to the person to your right so that they can complete the next step based solely on what you write down.
* The student who continues working the problem you start will be dependent on your work, so pay careful attention to making your part as precisely as possible.
* If you don't provide enough information, they may have to hand the paper back to you for revision.
--

@vspace{1ex}
[.indentedpara]
--
[cols="1a", options="header"]
|===
|Who's Doing What During Each Round of Design Recipe Telephone?
|*Round 1 - Writing Contract and Purpose Statements from the Word Problem*

[cols="1a,1a,1a"]
!===
! Student 1 - Problem A  ! Student 2 - Problem B! Student 3 - Problem C
!===
| *Round 2 - Writing Examples _based solely on the Purpose Statement_*
[cols="1a,1a,1a"]
!===
! Student 1 - Problem C  ! Student 2 - Problem A! Student 3 - Problem B
!===
|  *Round 3 - Writing Function Definitions _based solely on the Examples_*
[cols="1a,1a,1a"]
!===
! Student 1 - Problem B  ! Student 2 - Problem C! Student 3 - Problem A
!===
|===
--
This activity can be repeated several times, or done as a timed competition between teams. The goal is to emphasize that each step - if done correctly - makes the following step incredibly simple.




=== Synthesize
The Design Recipe is a way of slowing down and thinking through each step of a problem. If we already know how to get the answer, why would it ever be important to know how to do each step the slow way?

_Sample Responses:_

- Someday we won't be able to get the answer, and knowing the steps will help
- So we can help someone else who is stuck
- So we can work with someone else and share our thinking
- So we can check our work

Which step in the Design Recipe are students feeling the most confident about? The least? At this stage, it is normal for students to feel most confident about the Contract and Examples, and the least confident about Purpose Statements and Definitions.

*Optional:* Ask students to create their own appropriately challenging word problem (with a solution) and collect the responses for later use as "Do Now" tasks or formative assessment.
