= Human Spell Checking

Respond to the questions to consider your process for locating and correcting spelling errors in the sentence below. @big{
_"Before beginning the lesson, the teacher said wello to her students and asked them how thay were doing."_
}

@n What is the first word that is spelled incorrectly? @fitb{10em}{@ifsoln{wello}} How did you know that that word was misspelled? Explain in as much detail as you can. @fitb{}{}

@fitb{}{}

@fitb{}{}

@n What correctly spelled word do you think the author intended to put in place of the misspelled word? @fitb{10em}{@ifsoln{hello}}  How did you choose that word in particular, rather than another close option  (perhaps "cello", or "fellow")? @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Do you think a 6-year old would be able to identify and correct the first misspelled word in this sentence? Explain.  @fitb{}{}

@fitb{}{}

@fitb{}{}

@n What is the second word that is spelled incorrectly? @fitb{10em}{@ifsoln{thay}} How did you know that that word was misspelled? Explain in as much detail as you can. @fitb{}{}

@fitb{}{}

@fitb{}{}


@n What correctly spelled word do you think the author intended to put in place of the misspelled word? @fitb{10em}{@ifsoln{they}} How did you choose that word in particular, rather than another close option  (perhaps "that", "thaw", or "stay")? @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Do you think a 6-year old would be able to identify and correct the second misspelled word in this sentence? Explain. @fitb{}{}

@fitb{}{}

@fitb{}{}

@n You probably did *not* need to look in a dictionary at all to correct the two errors above. In what sort of situations, or for what sort of words, might consulting a dictionary be a part of your spell checking process? Explain. @fitb{}{}

@fitb{}{}

@fitb{}{}

