= A Pyret Spell Checker: Exploring Different Dataset Sizes

The player of the partially-completed Wordle game that we reviewed wants some Pyret "assistance". Follow each of the instructions below to discover how they can use the spell checker to their advantage. @link-instructions{Open the @starter-file{spell-checker} and click "Run".}


@n In the Interactions Area, test each of the three lines of code (below). Review the matches that Pyret produces, then record the _number_ of matches produced in the second row of the table.

@vspace{1ex}

[cols="2,^3,^3,^3", stripes="none"]
|===

|| `go("games", WORDS-100)` 	|	`go("games", WORDS-1000)` | `go("games", WORDS-ALL)`
| # matches found | @ifsoln{1} | @ifsoln{5}| @ifsoln{10}
|===

@n Which of three lines of code (above) would you encourage them to enter into Pyret? Why? @fitb{}{}

@fitb{}{@ifsoln{I would encourage them to use `go("games", WORDS-ALL)` because it produced 10 options, whereas `WORDS-1000` produced}

@fitb{}{@ifsoln{5 options, and `WORDS-100` produced 1 option.}}

@fitb{}{}

@fitb{}{}

@n Check out @link{https://docs.google.com/spreadsheets/d/1XD726tuYLW_WQqbEdhKo22Xt3gJumQ6vfJ1PVMkwmYA/edit?usp=sharing, "this spreadsheet"}, clicking on each of the spreadsheet's tabs. What do you Notice? What do you Wonder? @fitb{}{}

@fitb{}{@ifsoln{Possible responses: All-Words has 2315 words listed. Words-1000 has 1000 words, Words-100 has 100 words. Some words appear on all three sheets, }}

@fitb{}{@ifsoln{and some are only on one or two sheets. I notice that all words have 5 letters. I wonder how the words were selected for each sheet. }}

@fitb{}{@ifsoln{I wonder where the words come from. Are these all of the five letter words in the dictionary?}}

@fitb{}{}

@n In question 1, we used the very same function (`go`) for each entry. The code didn't change! Why were the results different? (e.g., we received _more_ matches with `WORDS-ALL` than we did with `WORDS-100`) @fitb{}{@}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n The solution to the partially-completed game is in fact "camel". Which dictionaries included the solution? Which did not? Why? @fitb{}{}

@fitb{}{@ifsoln{The solution only appears in the Words-All dictionary.}}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@star Can you produce an input that matches more than one word in the @link{https://docs.google.com/spreadsheets/d/1XD726tuYLW_WQqbEdhKo22Xt3gJumQ6vfJ1PVMkwmYA/edit?usp=sharing, "third (100-word) dictionary"}? If so, what is it? @fitb{}{}

@star "W1" and "W2" represent two different five-letter words. If `go("W1", WORDS-ALL)` produces a list that includes "W2", will `go("W2", WORDS-ALL)` produce a list that includes "W1"? @fitb{}{}
