= A Pyret Spell Checker: The Data

@link-instructions{Open the @starter-file{spell-checker} and click "Run".} Follow each of the instructions below how the spell checker is _data-driven_.

@n Test the code below. Review the matches that Pyret produces, then record the _number_ of matches in the second row of the table.

@vspace{1ex}

[cols="2,^3,^3,^3", stripes="none"]
|===

|| `go("games", WORDS-100)` 	|	`go("games", WORDS-1000)` | `go("games", WORDS-ALL)`
| # matches found | | |
|===

@n The player of the partially-completed game that we reviewed wants some "assistance". Which command (above) would you encourage them to use? Why? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n Check out @link{https://docs.google.com/spreadsheets/d/1XD726tuYLW_WQqbEdhKo22Xt3gJumQ6vfJ1PVMkwmYA/edit?usp=sharing, "this spreadsheet"}, clicking on each of the spreadsheet's tabs. What do you Notice? What do you Wonder? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n The solution to the partially-completed game is in fact "camel". Which dictionaries included the solution? Which did not? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n The code didn't change... so why did the results? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}



@star Can you produce an input that matches more than one word in the @link{https://docs.google.com/spreadsheets/d/1XD726tuYLW_WQqbEdhKo22Xt3gJumQ6vfJ1PVMkwmYA/edit?usp=sharing, "third (100-word) dictionary"}? If so, what is it? @fitb{}{}

@star "W1" and "W2" represent two different five-letter words. If `go("W1", WORDS-ALL)` produces a list that includes "W2", will `go("W2", WORDS-ALL)` produce a list that includes "W1"? @fitb{}{}
