= Histograms

*From Dot Plots to Histograms*

A *histogram*, like a dot plot, is data visualization that displays quantitative data.

[cols="^.>8a,1,^.>8a", frame="none", grid="none"]
|===
| @image{../images/dot-plot-pounds.png, 250}
|
| @image{../images/pounds.png, 250}
|===


- The displays both represent the distribution and frequency of animals' weights at the shelter. Both displays show the total number of values.

- The two data visualizations are different in a few ways, too. We can see individual points on the dot plot, but on the histogram, we just get a collective overview of the data. For instance, there is no way to single out one particular animal's weight on the histogram.

@vspace{1ex}


*Histograms*

*Histograms* show the number of rows that fall within certain intervals, or “bins”, on a horizontal axis. The more rows that fall within a particular “bin”, the taller the bar.

- Histograms provide a visual representation of the frequencies (or relative frequencies) of values in a *quantitative* column.

- Quantitative data *can always be ordered*, so the bars of a histogram always progress from smallest (on the left) to largest (on the right), resulting in *shape*.

- Some histograms are balanced. Others trail off to the left or to the right. Statisticians refer to this trailing as "skew".

[cols="^.^1a,^.^1a,^.^1a", options="header"]
|===
| Symmetric
| Skew-left
| Skew-right

| @image{../images/symmetric.png, 150 }
| @image{../images/left-w-foot.png, 150}
| @image{../images/right-w-foot.png, 150}

| Values are balanced on either side of the center.
| Values are clumped around what's typical, but trail off to the right.
| Values are clumped around what's typical, but trail off to the left.
|===

- One way to visualize the difference between a histogram of data that is skewed left or skewed right is to think about the lengths of our toes on our left and right feet.

- When dealing with histograms, it's important to select a good bin size. If the bins are too small or too large, it is difficult to see the shape of the dataset. Choosing a good bin size can take some trial and error!



