= Defining Functions 1

@lesson-description{Students learn why and how to create their own functions.}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Describe the usefulness of functions
* Create their own functions and examples given the parameters


|Student-Facing Lesson Goals
|
* I can explain why a function is useful.
* I can plan and create my own function with examples.


|Key Points for the Facilitator
|
* This lesson represents a big shift in thinking.  After some practice, students will not be limited to pre-existing functions!
* Take plenty of time for the Design Recipe as students will return to it frequently in future lessons. 


|Prerequisites
|

* Students should be familiar with Circles of Evaluation.
* Students should be familiar with defining values.

|Materials
|

* @link{https://docs.google.com/presentation/d/1gPY40bnT1J8Or147mcUd6oPh_W_Ugf-gJs5Va3FN4vk/view, Google Slides} template for this lesson.

* Circles of Evaluation Mapping worksheet (@worksheet-link{workbook-pages/MappingExamplesWithCoE.pdf, PDF}, @link{https://docs.google.com/document/d/1EDLbNC9C62Z-kf9jGZzbaRRRj8Ni_Gbz2f14kp30COU/edit?usp=sharing, Google Doc})

ifeval::["{proglang}" == "wescheme"]
* Fast Functions worksheet (@worksheet-link{workbook-pages/FastFunctions.pdf, PDF}, @link{https://docs.google.com/document/d/1zxq7TYX76y6DFwdF2DCuN1nnLAmbD33Sua1QhhmOYH8/edit?usp=sharing, Google Doc})
endif::[]

ifeval::["{proglang}" == "pyret"]
* Fast Functions worksheet (@worksheet-link{workbook-pages/FastFunctions.pdf, PDF}, @link{https://docs.google.com/document/d/19zlI9LU1u3xOfC7CQ2OHznaiJJNwbWJD9mm-7QtEXVQ/edit?usp=sharing, Google Doc})
endif::[]

ifeval::["{proglang}" == "wescheme"]
*Bootstrap Formative Assessments*

* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcaea0b4b8576069fdca4f, Bootstrap Algebra: Define Values & Fast Functions}
endif::[]

////

*Connecting Activities*

* @link{https://teacher.desmos.com/expressions, Expression Bundle} (Desmos Activities)
* @link{https://quizizz.com/admin/quiz/576d1e5f91cb32ef5fc67529/variables-and-expressions, Variables and Expressions} (Quizizz)
* @link{https://teacher.desmos.com/functions, Functions Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/polygraph/custom/560ad28e9e65da5615091edb,
Functions & Relations} (Desmos Polygraph Activity)
* @link{https://quizizz.com/admin/quiz/582b7390e8e0c0c201647d9d/functions, Functions} (Quizizz)
* @link{https://quizizz.com/admin/quiz/582f0e34b805cc5c6608d326/function-notation, Function Notation} (Quizizz)
 
////

|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Reinforcing (CCSSM)
|
* @std{7.EE.B.4}

|Addressing (CCSSM)
|
* @std{8.F.B}

|Approaching (CCSSM)
|
* @std{HSA.SSE.A.1}

|Bootstrap Benchmarks
|
* @std{BS-DR.1}
|===


== Get Ready:

Students should have their workbook, pencil, and be logged into 
ifeval::["{proglang}" == "wescheme"]
@link{https://www.wescheme.org, WeScheme} 
endif::[]
ifeval::["{proglang}" == "pyret"] 
@link{https://code.pyret.org, code.pyret.org} 
endif::[]
on their computer.

== Launch: (5 min)

@image{images/ILoveGreenTriangles.jpg, I Love Green Triangles, 400, align="center"}

@image{images/GreenTriangle.jpg, I Love Green Triangles, 400, align="center"}

Confess to your students, "I LOVE green triangles." Challenge them to use the Definitions window to make as many DIFFERENT solid green triangles as they can in 2 minutes. +
{empty} +

Walk around the room and give positive feedback on the green triangles.  After the 2 minutes, ask for some examples of green triangles that they wrote and copy them to the board.  Be specific and attend to precision with the syntax such that students can visually spot the pattern between the different lines of code. +
{empty} +

For example:
ifeval::["{proglang}" == "wescheme"]
`(triangle 30  "solid" "green")` +
`(triangle 12  "solid" "green")` +
`(triangle 500 "solid" "green")` +
endif::[]

ifeval::["{proglang}" == "pyret"]
`triangle(30,  "solid", "green")` +
`triangle(12,  "solid", "green")` +
`triangle(500, "solid", "green")` +
endif::[]
{empty} +

[.notice-box]
.Notice and Wonder
****
Direct students to the various lines of code they came up with.
What do you notice?  What do you wonder?
****

== Discuss: (15 min)

* *Is there a pattern?* +
_Yes, the code mostly stayed the same with one change each time_
* *What stayed the same?* +
_The function name (`triangle`), "solid", "green"_
* *What changed?* +
_The number being given to `triangle`, or the Number input_
* *What strategy did you use to create many different triangles?* +
_Answers vary: Pattern matching, copy and paste_
* *What shortcut did we use before when we wanted to use the same code over and over?* +
_We defined values in the Definitions window_

=== Inquiry Based Instruction  
We've learned how to define *values* when we want to create a shortcut to reuse the same code over and over. +
{empty} + 

For example:
ifeval::["{proglang}" == "wescheme"]
`(define myStar (star 50 "solid" "gold"))` +
endif::[]

ifeval::["{proglang}" == "pyret"]
`myStar = star(50, "solid", "gold")` +
endif::[]
{empty} +

=== We can define a _function_ when we want the program to perform a task repeatedly, such as creating solid, green triangles.
{empty} +

ifeval::["{proglang}" == "pyret"]
The keyword *fun* is used to define a new function.  At the _end_ of a function definition, we use the keyword *end*. + 
endif::[]
{empty} +

*Word Problem: Write a function called `gt` that takes in a Number and produces a solid, green triangle of that given size.*

Have students follow along on the @worksheet-link{workbook-pages/FastFunctions.pdf, Fast Functions} handout. +
{empty} + 

* *1. Write the contract for this new function by looking at the word problem.* +
** What does `gt` take in? +
_A Number_
** What does `gt` give back? +
_An Image. Students may say "a triangle", follow up by asking what data type that triangle will be (Number, String, or Image)_
* *2. Write some examples of how this function should work.*
** If I typed 
ifeval::["{proglang}" == "wescheme"]
`(gt 40)`
endif::[]
ifeval::["{proglang}" == "pyret"]
`gt(40)` 
endif::[]
, what would I want the program to do? +
_I'd want the computer the execute the code 
ifeval::["{proglang}" == "wescheme"]
`(triangle 40 "solid" "green")`._ +
endif::[]
ifeval::["{proglang}" == "pyret"]
`triangle(40, "solid", "green")`._ +
endif::[]
_This is a tough question at first.  If students are unsure, remind them that we're just writing a shortcut for making green triangles so we don't have to type `triangle`, "solid", and "green" every time!_ +
{empty} +
** Have students complete the @worksheet-link{workbook-pages/MappingExamplesWithCoE1.pdf, Circle of Evaluation mapping} worksheet showing how their function examples are working.
* *3. Find what is changing between the examples. Circle it and label it with a name that describes it.* +
_The number is changing in each example.  We could name it "x", but "size" is a more accurate name._ +

ifeval::["{proglang}" == "wescheme"]
@image{images/WhatChanges.png, Circle and label what is changing, 400, align="center"}
endif::[]

ifeval::["{proglang}" == "pyret"]
@image{images/WhatChanges-Pyret.png, Circle and label what is changing, 400, align="center"}
endif::[]

* *4. Write the function definition.* +
_Look to the examples.  The function definition will follow the same pattern, but it will use the variable name `size` in place of the Number input._
ifeval::["{proglang}" == "wescheme"]
_``(define (gt size) (triangle size, "solid", "green"))``_
endif::[]
ifeval::["{proglang}" == "pyret"]
_``fun gt(size): triangle(size, "solid", "green") end``_
endif::[]

*Key Points:*

* Writing the examples is like "showing your work" in math class.
* Have students circle what is changing and label it with a proper variable name.  The name of the variable should reflect what it represents, such as `size`.  
* Writing examples and identifying the variables lays the groundwork for writing the function, which is especially important as the functions get more complex.  Don't skip this step!

Now that students have defined `gt` have them save their program as 'Defining Functions' and test out their newly created function in the Interactions window.

*Synthesis Questions* +

* *What is the domain for `gt`?* +
_Number_
* *Why might someone think the domain for `gt` is 
ifeval::["{proglang}" == "wescheme"]
`Number String String`?* +
endif::[]
ifeval::["{proglang}" == "pyret"]
`Number, String, String`?* +
endif::[]
_Because that's the domain of `triangle`.  The function `gt` uses `triangle`, but only needs one Number input because that's the only part that's changing._
* *Why is defining functions useful to us as programmers?*

== Practice: (10 min)

*Word Problem: Write a function called `gold-star` that takes in number and produces a solid, gold star of that given size.*

* Write 2 examples and the definition of `gold-star` on the 'Fast Functions' handout.
* Complete the `gold-star` example on the @worksheet-link{workbook-pages/FastFunctions.pdf, Fast Functions} worksheet.

== Create/Apply: (15 min)

*Design a problem for a function that takes in one input and returns a shape that uses that input.* +
Your function's input could be a Number, as in the two examples, or a String.  
{empty} +

* Write two examples and a definition for your function
* Complete the Circles of Evaluation mapping for the examples of your function.



