= Horizontal Shifts in Linear Function Definitions

Open the @online-exercise{https://www.desmos.com/calculator/hong7gv82k, Exploring Horizontal and Linear Shifts in Linear Functions} file. 

There are three exercise folders in the file. You will be directed to focus on one folder at a time.

== Exploration 1

_Click on the triangle to open the folder, and the circle to turn "on" the graphs it contains._

@n Move the slider to change the value of @math{h}, paying attention to the x-intercepts of the lines.

*Subtracting* from @math{x}, shifts the line (and x-intercepts) the @fitb{3em}{@ifsoln{right}}. *Adding* to @math{x} (by subtracting negatives) shifts the line to the @fitb{}{@ifsoln{left}}

@n Why does subtracting move the line right, and adding move left? @fitb{}{@ifsoln{Shifting @math{x} by @math{h} plots the line relative to a shifted *plane*!}}

@fitb{}{@ifsoln{Subtracting *moves that plane left*, which makes the line appear to move right. Adding *moves the plane right*.}}

@fitb{}{}

@n *Turn "off" @math{g(x)} so that only the red line is visible.* Move the slider to change the value of @math{h}, paying attention to the y-intercept of the line.

The slope of @math{f} is positive. *Subtracting* from @math{x} shifts the y-intercept of @math{f} @fitb{4em}{@ifsoln{up}}, while *adding* to @math{x} (subtracting negatives) shifts it @fitb{4em}{@ifsoln{down}}

@n *Turn @math{g(x)} back "on" and turn "off" @math{f(x)} so that only the blue line is visible.* Move the slider to change the value of @math{h}.

The slope of @math{g} is negative. *Subtracting* from @math{x} shifts the y-intercept of @math{g} @fitb{4em}{@ifsoln{down}}, while *adding* to @math{x} (subtracting negatives) shifts it @fitb{4em}{@ifsoln{up}}

@n Explain the relationship between slope, horizontal shift, and y-intercept. @fitb{}{@ifsoln{Shifting the relative y-axis to the left moves the graph of a line}}

@fitb{}{@ifsoln{ to the right, which means negative-sloped functions "fall" from a greater height and positively-sloped functions "rise" from a greater depth}}

@fitb{}{}

== Exploration 2

_Close and turn "off" Exploration 1. Then open and turn "on" Exploration 2._

@n *If you leave the slider at @math{b = 0},* what is the y-intercept of the purple line? @fitb{}{@ifsoln{-4}} 

@n How could we find the y-intercept from looking at the function definition: @math{j(x) = 2x - 4}? @fitb{}{@ifsoln{The function definition ends with @math{-4}.}}

@n *When @math{b = 0},* what is the y-intercept of the green line? @fitb{}{@ifsoln{-8}}

@n How could we find the y-intercept from looking at the function definition:  @math{k(x) = 2(x - 4) + 0} ?

@fitb{}{@ifsoln{We could multiply 2 times -4 to get -8}}

@n Slide @math{b} until the green line lands on top of the purple line. What is the value of @math{b}? @fitb{}{@ifsoln{4}}

@n How could we have found this value of @math{b} without using the slider?

@fitb{}{@ifsoln{@math{b = 4} is the value that we add to @math{-8} (the starting y-intercept of the green line) to get @math{-4} (the y-intercept of the purple line)}}

@fitb{}{}

== Exploration 3

_Close and turn "off" Exploration 2. Then open and turn "on" Exploration 3._

@n Using the strategy you articulated in question 9, what value of @math{c} would make this pair of lines land on top of each other? @fitb{}{@ifsoln{@math{3}}} 

_Show your work._ 

@ifsoln{@math{0.25 \times 4 = 1} @hspace{7em} @math{4 -1 = 3}}
