= Associativity Makes Computation Easier (2)

Apply the Associative Property to draw the Circle of Evaluation that will make the computation the simplest. Evaluate the expression. The first one is done for you.

++++
<style>
  div#body.workbookpage table.FillVerticalSpace {
    grid-template-rows: unset !important; grid-auto-rows: 1fr;
  }
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

[.FillVerticalSpace, cols="^4a,^4a"]
|===

| @math{12.76 + \frac{20}{5} + 7.24 + 6}

@vspace{2ex}

@show{(coe '(+ (+ 12.76 7.24) (+ 20/5 6)))}

@vspace{2ex}

_30_

| @math{22.5 + 31.2 + 17.5 + 14.8}

@vspace{2ex}

@showsoln{(coe '(+ (+ 22.5 17.5) (+ 31.2 14.8)))}

@vspace{2ex}

@ifsoln{@math{86}}


| @math{1.25 \times 27.34 \times 80}

@vspace{2ex}

@showsoln{(coe '(* (* 1.25 80) 27.34))}

@vspace{2ex}

@ifsoln{@math{2734}}

| @math{800 + (9 \times 74.6 \times \frac{1}{9})}

@vspace{2ex}

@showsoln{(coe '(+ 800 (* (* 1/9 9) 74.6)))}

@vspace{2ex}

@ifsoln{@math{874.6}}


| @math{(13 \times 18 \times \frac{1}{13}) \div ( 6 \times .25 \times 4)}

@vspace{2ex}

@showsoln{(coe '(/ (* 18 (* 13 1/13)) (* 6 (* .25 4))))}

@vspace{2ex}

@ifsoln{@math{3}}

| @math{\frac{8.4 \times 200 \times \frac{1}{20}}{2 \times 3 \times 7}}

@vspace{2ex}

@showsoln{(coe '(/ (* 8.4 (* 200 1/20)) (* 2 (*  3 7))))}

@vspace{2ex}

@ifsoln{@math{2}}

| @math{33 \times \frac{1}{2} \times 200 \times 3}

@vspace{2ex}

@showsoln{(coe '(* (* 1/2 200) (*  3 33.3)))}

@vspace{2ex}

@ifsoln{@math{9990}}

| @math{\frac{7}{9} + \frac{5}{6} + \frac{2}{9} + \frac{1}{6} + 23.8}

@vspace{2ex}

@showsoln{(coe '(+ (+ 7/9 2/9) (+ 5/6 1/6) 23.8 ))}

@vspace{2ex}

@ifsoln{@math{25.8}}

|===
