= Associativity Makes Computation Easier (1)

Apply the Associative Property to draw the Circle of Evaluation that will make the computation the simplest. Evaluate the expression. The first one is done for you.

++++
<style>
  div#body.workbookpage table.FillVerticalSpace {
    grid-template-rows: unset !important; grid-auto-rows: 1fr;
  }
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

[.FillVerticalSpace, cols="^4a,^4a"]
|===


| @math{13 + 7 + 4 + 6}

@vspace{2ex}

@show{(coe '(+ (+ 13 7) (+ 4 6)))}

@vspace{2ex}

_20 + 10_

@vspace{2ex}

_30_

| @math{23 + 17 + 31 + 14}

@vspace{2ex}

@showsoln{(coe '(+ (+ 23 17) (+ 31 14)))}

@vspace{2ex}

@ifsoln{@math{86}}


| @math{13 \times 125 \times 8}

@vspace{2ex}

@showsoln{(coe '(* (* 125 8) 13))}

@vspace{2ex}

@ifsoln{@math{1300}}

| @math{60 + (74 \times 5 \times 2)}

@vspace{2ex}

@showsoln{(coe '(+ 60 (* (* 5 2) 74)))}

@vspace{2ex}

@ifsoln{@math{800}}


| @math{(15 \times 25 \times 4) + 13 \times 20 \times 5}

@vspace{2ex}

@showsoln{(coe '(+ (* 15 (* 25 4)) (* 13 (* 20 5))))}

@vspace{2ex}

@ifsoln{@math{2800}}

| @math{2 + (33 \times 5 \times 2)}

@vspace{2ex}

@showsoln{(coe '(+ 2 (* 33 (* 5 2))))}

@vspace{2ex}

@ifsoln{@math{332}}

| @math{468 \times 0.5 \times 20}

@vspace{2ex}

@showsoln{(coe '(* 468 (* 0.5 20)))}

@vspace{2ex}

@ifsoln{@math{4680}}

| @math{\frac{7}{9} + \frac{2}{9} + 223 + 7}

@vspace{2ex}

@showsoln{(coe '(+ (+ 7/9 2/9) (+ 223 7)))}

@vspace{2ex}

@ifsoln{@math{231}}

|===
