= Categorizing Functions

++++
<style>
div.circleevalsexp { width: auto; }

/* Make autonums inside tables look consistent with those outside */
table .autonum::after { content: ')' !important;}

</style>
++++

Discuss each function with a partner before categorizing as: Associative, Commutative, Both or Neither.

[.FillVerticalSpace,cols="^.^1a,^.^4a,^.^4a,^.^4a,^.^4a,^.^4a", stripes="none", options="header"]
|===
|	 | Function | Associative | Commutative | Both | Neither

| @n | @show{(code 'overlay)}| @ifsoln{x}|||
| @n | @show{(code 'beside)}| @ifsoln{x}|||
| @n | @show{(code 'above)}| @ifsoln{x} |||
| @n | @show{(code 'blend-images)}||@ifsoln{x}||
| @n | @show{(code 'string-contains)}|||| @ifsoln{x}
| @n | @show{(code 'min)}|||@ifsoln{x}|
| @n | @show{(code 'rectangle)}||||@ifsoln{x}
| @n | @show{(code 'triangle)}||||@ifsoln{x}
| @n | `+` |||@ifsoln{x}|
| @n | `-` ||||@ifsoln{x}
| @n | `*` |||@ifsoln{x}|
| @n | `/` ||||@ifsoln{x}


|===


@n Which functions were _only_ commutative? @fitb{}{@ifsoln{@show{(code 'blend-images)}}}

@fitb{}{}

@n Which functions were _only_ associative? @fitb{}{@ifsoln{@show{(code 'overlay)}, @show{(code 'beside)}, @show{(code 'above)} }}

@fitb{}{}

@n Which functions were _both_ commutative and associative? @fitb{}{@ifsoln{@show{(code 'min)}, `+`, `*`}}

@fitb{}{}

@n Which functions were _neither_ commutative nor associative? @fitb{}{@ifsoln{@show{(code 'string-contains)}, @show{(code 'rectangle)}, @show{(code 'triangle)}, `-`, and `\`.}}

@fitb{}{}


@n Consider the operators listed in rows 9-12 of the table. Do these operators have different categorizations (Associative, Commutative, Both, Neither) in @proglang versus in math? @fitb{}{@ifsoln{No, they behave the same in math and in @proglang.}}

@n What else did you Notice while completing the above table? What did you Wonder? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


