= Discover the Associative Property (2)

++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  .circleevalsexp .value,
  .circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

*The Associative Property is true for any operation where _all groupings_ of the numbers produce the same result.*

== Is Multiplication Associative?

@n Kris thinks that multiplication is associative and draws the Circles of Evaluation below as proof. Translate the Circles of Evaluation into expressions and compute their values. 

[cols="^.^3,^.^3"]
|===
| @show{(coe '(* (* 2 5) 10))}
| @show{(coe  '(* 2 (* 5 10)))}
| @math{(2 \times 5) \times 10 =}@fitb{5em}{@ifsoln{100}}
| @fitb{28em}{@ifsoln{@math{2 \times (5 \times 10) = 100}}}
|===

@vspace{1ex}

Can you think of any multiplication problems where groupings matters? Write at least three more examples and see if they evaluate to the same thing. _(We've provided the start of one example.)_

[cols="^1a,^1a", options="header"]
|===
| Grouping 1
| Grouping 2

|@math{(4 \times 3) \times 8 =} @fitb{3em}{@ifsoln{96}} 
|@ifsoln{@math{4 \times (3 \times 8) = 96}}

|| @vspace{1ex}

|| @vspace{1ex}
|===

@vspace{1ex}

Then decide:  *Does the Associative Property hold for problems involving multiplication*?    @ifsoln-choice{Yes}    No


== Is Division Associative?

@n Jesse thinks that division is associative and draws the Circles of Evaluation below as proof. Translate them into expressions and evaluate them. 

[cols="^.^3,^.^3"]
|===
| @show{(coe '(/ (/ 20 10) 1))}
| @show{(coe  '(/ 20 (/ 10 1)))}
| @math{(20 \div 10) \div 1 =} @fitb{5em}{@ifsoln{2}}  
| @fitb{28em}{@ifsoln{@math{20 \div (10 \div 1) = 2}}}
|===

@vspace{1ex}

Can you think of any division problems where groupings matters? Write at least three more examples and see if they evaluate to the same thing. _(We've provided the start of one example.)_

[cols="^1a,^1a", options="header"]
|===
| Grouping 1
| Grouping 2

|@math{(300 \div 10) \div 5 =} @fitb{3em}{@ifsoln{30 \div 5 = 6}} 
|@ifsoln{@math{300 \div (10 \div 5) = 300 \div 2 = 150}}

|| @vspace{1ex}

|| @vspace{1ex}
|===

@vspace{1ex}

Then decide:   *Does the Associative Property hold for problems involving division*?    Yes    @ifsoln-choice{No}