= Discover the Associative Property (1)

++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

@n Evaluate the Circles of Evaluation below to help you decide if the Associative Property holds for problems involving *addition*.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @show{(coe '(+ (+ 10 8) 3))}
| @show{(coe  '(+ 10 (+ 8 3)))}
| @ifnotsoln{@math{(10 + 8) +3 = ?}}   @ifsoln{@math{(10 + 8) + 3 = 21}}
| @ifnotsoln{@math{10 + (8 + 3) = ?}}  @ifsoln{@math{10 + (8 + 3) = 21}}
|===

What do you notice? @fitb{}{@ifsoln{All expressions evaluate to 21. The first Circle has the sum of 10 and 8 in a nested Circle, while the second}}

@fitb{}{@ifsoln{Circle has the sum of 8 and 3 in a group.}}

@vspace{1ex}

These Circles of Evaluation represent the Associative Property of Addition, which tells us that *when you add three numbers, it does not matter whether you start by adding the first pair of numbers or the last pair of numbers.* Draw another example of the Associative Property of Addition with any *three* numbers, below. Evaluate each expression to confirm that they are equivalent.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @showsoln{(coe '(+ (+ 14 9) 6))}
| @showsoln{(coe  '(+ 14 (+ 9 6)))}
| @ifsoln{@math{(14 + 9) + 6 = 29}}
| @ifsoln{@math{(14 + 6) + 9 = 29}}
|===


@n Evaluate the Circles of Evaluation below to help you decide if the Associative Property holds for problems involving *subtraction*.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @show{(coe '(- (- 9 5) 4))}
| @show{(coe  '(- 9 (- 5 4)))}
| @ifnotsoln{@math{(9 - 5) - 4 = ?}} @ifsoln{@math{(9 - 5) - 4 = 0}}
| @ifnotsoln{@math{9 - (5 - 4) = ?}} @ifsoln{@math{9 - (5 - 4) = 8}}
|===


Explain your response. @fitb{}{@ifsoln{No, the Associative Property does not hold for subtraction. I know because the first Circle evaluates to 0, }}

@fitb{}{@ifsoln{while the second Circles evaluates to 8. These Circles are not equivalent after I change the groupings.}}

@vspace{1ex}

Draw another example like the one above to confirm what you observed about the Associative Property and subtraction. Evaluate each Circle to confirm your response.


[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @showsoln{(coe '(- (- 30 2) 1))}
| @showsoln{(coe  '(- 30 (- 2 1)))}
| @ifsoln{@math{(30 - 2) - 1 = 27}}
| @ifsoln{@math{30 - (2 - 1) = 29}}
|===


