= Discover the Associative Property (2)

++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

@n Evaluate the three Circles of Evaluation below to help you decided if the Associative Property holds for problems involving *multiplication*:

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @show{(coe '(* (* 2 5) 10))}
| @show{(coe  '(* 2 (* 5 10)))}
| @ifnotsoln{@math{(2 \times 5) \times 10 = ?}} @ifsoln{@math{(2 \times 5) \times 10 = 100}}
| @ifnotsoln{@math{2 \times (5 \times 10) = ?}} @ifsoln{@math{2 \times (5 \times 10) = 100}}
|===

What do you notice? @fitb{}{@ifsoln{All Circles of Evaluation lead to 100. The first Circle has the product of 2 and 5 in a group, while the second}}

@fitb{}{@ifsoln{Circle has the product of 5 and 10 in a group.}

@vspace{1ex}

These Circles of Evaluation illustrate the Associative Property of Multiplication, which tells us that *when you multiply three numbers, it does not matter whether you start by multiplying the first pair of numbers or the last pair of numbers*. Draw another example of the Associative Property of Multiplication with any three numbers, below. Make sure that each expression includes a _different_ pair of numbers grouped together. Evaluate your expressions to confirm that they are equivalent.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @showsoln{(coe '(* (* 4 3) 8))}
| @showsoln{(coe  '(* 4 (* 3 8)))}
| @ifsoln{@math{(4 \times 3) \times 8 = ?}}
| @ifsoln{@math{4 \times (3 \times 8) = ?}}
|===

@n Evaluate the Circles of Evaluation below to help you decide whether or not the Associative Property holds for problems involving *division*.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @show{(coe '(/ (/ 20 10) 2))}
| @show{(coe  '(/ 20 (/ 10 2)))}
| @ifnotsoln{@math{(20 \div 10) \div 2 = ?}} @ifsoln{@math{(20 \div 10) \div 2 = 1}}  | @ifnotsoln{@math{20 \div (10 \div 2) = ?}} @ifsoln{@math{(20 \div 10) \div 2 = 4}}
|===


Explain your response. @fitb{}{@ifsoln{No, the Associative Property does not hold for division. I know because the first Circle of Evaluation returns 1, }}

@fitb{}{@ifsoln{while the second Circle of Evaluation yields 4. These Circles are not equivalent after I change the groupings.}}

@vspace{1ex}

Draw another example like the one above to confirm what you observed about the Associative Property and division.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @showsoln{(coe '(/ (/ 30 5) 6))}
| @showsoln{(coe  '(/ 30 (/ 5 6)))}
| @ifsoln{@math{(30 \div 5) \div 6}}
| @ifsoln{@math{30 \div (5 \div 6)}}
|===
