= Discover the Associative Property (2)

++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  .circleevalsexp .value,
  .circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

*The Associative Property is true for any operation where _all groupings_ of the numbers produce the same result.*

== Is Multiplication Associative?

@n Kris thinks that multiplication is associative and draws the Circles of Evaluation below as proof. Translate them into expressions and evaluate them. 

[cols="^.^3,^.^3"]
|===
| @show{(coe '(* (* 2 5) 10))}
| @show{(coe  '(* 2 (* 5 10)))}
| @math{(2 \times 5) \times 10 =}@fitb{5em}{@ifsoln{100}}
| @fitb{28em}{@ifsoln{@math{2 \times (5 \times 10) = 100}}}
|===

Complete this second table by drawing another Circle of Evaluation with different groupings, translating both Circles of Evaluation into expressions and evaluating them. Then decide:  *Does the Associative Property hold for problems involving multiplication*?    @ifsoln-choice{Yes}    No

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @show{(coe '(* (* 4 3) 8))}
| @showsoln{(coe  '(* 4 (* 3 8)))}
| @fitb{28em}{@ifsoln{@math{(4 \times 3) \times 8 = 96}}}
| @fitb{28em}{@ifsoln{@math{4 \times (3 \times 8) = 96}}}
|===

== Is Division Associative?

@n Jesse thinks that division is associative and draws the Circles of Evaluation below as proof. Translate them into expressions and evaluate them. 

[cols="^.^3,^.^3"]
|===
| @show{(coe '(/ (/ 20 10) 1))}
| @show{(coe  '(/ 20 (/ 10 1)))}
| @math{(20 \div 10) \div 1 =} @fitb{5em}{@ifsoln{2}}  
| @fitb{28em}{@ifsoln{@math{20 \div (10 \div 1) = 2}}}
|===

Complete this second table by drawing another Circle of Evaluation with different groupings, translating both Circles of Evaluation into expressions and evaluating them. Then decide:  *Does the Associative Property hold for problems involving division*?    Yes    @ifsoln-choice{No}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @show{(coe '(/ (/ 300 10) 5))}
| @showsoln{(coe  '(/ 300 (/ 10 5)))}
| @fitb{28em}{@ifsoln{@math{(300 \div 10) \div 5 = 30 \div 5 = 6}}}
| @fitb{28em}{@ifsoln{@math{300 \div (10 \div 5) = 300 \div 2 = 150}}}
|===
