[.beta]
= Exploring Logarithmic Models

@description{Students investigate logarithmic relationships in demographic data about world countries, using an inquiry-based model of sense-making, hypothesizing, modeling and testing.}

@lesson-prereqs{exploring-exponential-models, lookups}

@keywords{logarithm, base}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Model logarithmic and exponential relationships using functions

| Student-facing Lesson Goals
|

* Let's use Pyret to model logarithmic relationships in data


| Materials
|[.materials-links]
@material-links

| Preparation
|
* All students should log into @starter-file{program-list} and, open the @starter-file{alg2-countries}.

| Key Points For The Facilitator
|
* This lesson assumes that students have been introduced to logarithms before, and are familiar with computation involving logarithmic functions.
* The focus of this lesson is about _applications_ of log functions, and builds an intuition for logarithmic computation by motivating substantial trial and error.
|===

== Looking for Patterns  @duration{30 minutes}

=== Overview
Students explore the @starter-file{alg2-countries}, and find a relationship between wealth and median life expectancy. They also learn how to build a new column for a table in Pyret.

=== Launch

[.lesson-instruction]
--
@right{@image{images/questions.png, 250}}

- Do people who make more money generally live longer?
- Open the @starter-file{alg2-countries}
- From the File menu, select "Save a Copy", and click "Run".
- Working in pairs or small groups, complete questions 1-6 on @printable-exercise{exploring-countries.adoc}.
- Be ready to discuss your answers.
--

@teacher{
Discuss students' findings. Pay special attention to the @vocab{form} that students use to describe the pattern in the scatter plot. Is it linear, or something else? Is it strong or weak? If there's some disagreement among the students, that's a good thing!

Be attentive to sense-making: If a wealthy country is suffering heavy causalties in a war, where would we expect to see the datapoint? Why? What other conditions would cause a point to shift up, down, left or right?
}
=== Investigate

[.lesson-instruction]
--
Working in pairs or small groups, complete the rest of @printable-exercise{exploring-countries.adoc} using @online-exercise{https://teacher.desmos.com/activitybuilder/custom/646f99970cc6898a9d87ef95, Fitting Wealth-v-Health} to try fitting linear, quadratics, and exponential models for this dataset
--

@teacher{
Note: This worksheet involves lots of trial and error, as students try to come up with a good linear, quadratic, or exponential model. The goal is to __discover that a new kind of  model is necessary__.
}
=== Synthesize

- What's the best model you came up with?
- What kinds of lines or curves did you draw?

== Logarithmic Functions	@duration{45 minutes}

=== Overview
Having identified that the wealth-v-lifespan scatter plot is neither linear, nor quadratic, nor exponential, students learn about characteristics of logarithmic functions in graphical, tabular, and function notation form.

=== Launch
@center{@image{images/wealth-v-life-linear.png}}

There definitely appears to be a relationship here, but it's not one we've seen before. Using `lr-plot` only shows a moderate correlation, because the straight line doesn't really fit the curve. The shape of this starts out rising fast on the left, before tapering off as `pc-gdp` increases to the right.

[.lesson-instruction]
How well did our linear, quadratic, and exponential models fit this data? Is there another kind of function that starts off rising fast, but then levels off quickly?

None of the kinds of functions we've seen so far exhibit the behavior we see here. In some ways, this behavior is the exact opposite of exponentials: instead of starting slow and taking off like a rocket, this curve explodes up the y-axis right away, before leveling off.

++++
<style>
.growth td { padding: 0; }
</style>
++++

Let's review what we know about the behavior of the models we've seen so far:

[.growth, cols=".^15a,^.^5a", grid="none", frame="none", stripes="none"]
|===
| We know that exponentials grow by _equal factors over the same interval_, so instead of calculating "what is added to y", we calculate "what is multiplied by y" to produce the next value over a constant interval.
| @image{images/difference-table-exponential-2.png}

| This behavior is almost the reverse of exponential growth: instead of multiplying y to find the next value, we need to _multiply the size of our interval_ by a constant factor just to get a constant growth in y!
|@image{images/difference-table-logarithmic.png}
|===

The shape of this relationship is _logarithmic_, meaning it can be modeled using a @vocab{logarithmic function}.

Logarithmic relationships grow or decay very quickly at first, but then level out as @math{x} increases. Our intervals need to grow longer and longer just to reach a small change in y. On a graph, this shows up as a horizontal line (an @vocab{asymptote}). Logarithmic functions will always get closer and closer to the asymptote as @math{x} increases, but never get all the way there.

Logarithmic relationships are often used to help humans get a handle on quantities in nature that grow so quickly we can barely imagine them. For example, our ears can hear incredibly quiet sounds (like a pin dropping), but also process incredibly loud sounds (like a fog horn). A fire alarm, for example, is thousands of times louder than a dog barking, but it's difficult for our brains to process that much more "loudness". As a result, we _perceive_ loudness on a logarithmic scale: for us to percieve a sound as being twice as loud as another, it actually has to be _a hundred times as loud_.

[.lesson-instruction]
- Complete @printable-exercise{classifying-descriptions.adoc}
- Be ready to discuss your answers with the class!

@teacher{Have students share their answers. Be especially attentive to students who mis-label logarithmic relationships as "exponential" -- they're on to something! Logarithmic relationships are used to "linearize" exponential ones, which will explore more deeply later in this lesson.}

=== Investigate
You've identified one logarithmic pattern in a graph: it grows really fast right away, then levels off. Can you tell the difference between quadratic, exponential, and logarithmic graphs?

[.lesson-instruction]
- Complete @printable-exercise{classifying-plots.adoc}
- Be ready to discuss your answers with the class!

@teacher{Have students share their answers. Encourage them to talk about where the logarithmic functions level out shoot up, asking them to identify the approximate x-value where that occurs.}

Logarithmic sequences grow more slowly the farther out you get, so that it takes many more steps just to grow by the same amount. For example, it might take 10 steps to go from `1` to `2`, but then a hundred more to get to `3` and a _thousand_ more to get to `4`. In some ways, this kind of growth is the exact opposite of exponential functions, which grow by increasing factors for every step! Can you tell the difference between linear, quadratic, and exponential growth of a sequence?

[.lesson-instruction]
- Complete @printable-exercise{classifying-tables.adoc}
- Be ready to discuss your answers with the class!

@teacher{Have students share their answers. For logarithmic functions, it's especially important to have students talk about how much `x` needs to increase just to get a fix increase in `y`. This foreshadows the idea of _base_ for logarithmic relationships.}

[.lesson-point]
Logarithmic models have the form @math{f(x) = b \times log(x) + c}

- The term @math{b} is the _base_ of the logarithm. Look back to your answers on @printable-exercise{classifying-tables.adoc}. For tables that represent logarithmic functions, by what factor does @math{x} need to grow in order to get a constant increase in @math{y}?
- The term @math{a} is the _scaling factor_, which amplifies or reduces the growth or decay of the function as @math{x} increases
- The term @math{c} is something we've seen before: it's the _vertical shift_ of the function, which moves the curve up or down (in other kinds of functions, this is often given the name @math{k}). It's also the y-value of the @vocab{asymptote} for the function.

=== Synthesize
- What _similarities_ do you see between exponential and logarithmic functions?
- What _differences_ do you see between exponential and logarithmic functions?

== Transforming the x-Axis @duration{30 minutes}

=== Overview
Students discover that by transforming the x-axis with an exponential function, they can fit a linear model to a logarithmic relationship.

=== Launch
We need to find @math{b} and @math{c}, such that the model fits the data as closely as possible.

[.lesson-instruction]
Complete the first section of @printable-exercise{transforming-axis.adoc}, using @online-exercise{https://www.desmos.com/calculator/cbtooos3of, Wealth-v-Health - Logarithmic}.

@teacher{Crowdsource the values students came up with for @math{b} and @math{c} in their best-guess logarithmic model. Were they very similar or very different? What were the @math{R^2} values?}

Trial-and-error only gets us so far, and it's not clear that we would ever stumble upon the optimal model. **We need something like Pyret's `lr-plot` function, which uses computational methods to find the best possible model.** Unfortunately, `lr-plot` only finds linear models. If only we could _transform_ this data to make it appear linear. Then we could use `lr-plot` to fit the optimal model, and then reverse the transformation to get the optimal logarithmic model!

=== Investigate
Imagine that the scatter plot is printed on a sheet of rubber, and can be stretched or squashed in any way we want. Data Scientists often use *transformations* to stretch their data into shapes that are easier to use, and then reverse the transformation when they are done.

[.lesson-instruction]
Complete the last section of @printable-exercise{transforming-axis.adoc}, using @online-exercise{https://www.desmos.com/calculator/cbtooos3of, Wealth-v-Health - Logarithmic}.


By __transforming the x-axis__ to grow exponentially, we are "squashing" the coordinate plane so that each interval on the x-axis represents 10x the growth in `pc-gdp` as the one before it. This balances  the logarithmic growth in `median-lifespan`, makes the curved relationship appear linear, and warps our logarithmic model so it looks like a straight line-of-best-fit.

Here's a metaphor that might help students make sense of this.

* A person running on a treadmill is still standing in the same place. Why?
** Their forward movement is balanced by the backwards movement of the treadmill.
* If they run faster and faster, what needs to happen to the treadmill to keep them in the same place?
** The treadmill needs to go faster as well - As long as the treadmill speed increases at the same rate as the runner, they will _balance one another's growth_. That's the same thing that's happening in our transformed graph.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Going Deeper: Connecting to Inverse Functions}

While this doesn't cover inverses in any real depth, the treadmill analogy opens the door to discussing how one kind of change can "cancel out" or "undo" another. A person running at a constant speed is adding distance per unit time, which is inverted by the treadmill subtracting that same distance per unit time.

In Desmos, the tick marks on the Desmos axis increased exponentially when we switched to a log scale. If that person were accelerating exponentially, the treadmill would need to do so as well.

We are working to add additional lessons on inverse functions to our Algebra 2 materials, and hope to release them by fall 2024!
|===

=== Synthesize

- How does seeing the point cloud as linear help us think about logarithmic growth?
- What if we wanted to change the axis to show a quadratic scale? Or something more complicated?
- Transforming the axes only makes things _look_ linear - the actual points haven't changed at all, and we still can't use linear regression to find the best logarithimic model... Can you think of a way we could we transform the _data_, instead of the axes?

== Transforming the Data @duration{45 minutes}

=== Overview

Students learn to transform the data into a linear shape, building a new column by applying a function to each row. This new data can be fit with a linear model. By applying the _inverse_ of this transformation to their linear model, they retrieve the logarithmic model.

=== Launch

Instead of transforming the x-axis, another strategy is to _transform the x-coordinates themselves_. Instead of plotting `pc-gdp` on a *logarithmic* x-axis, we could plot `log(gdp)` on a *linear* x-axis.

[.lesson-instruction]
Complete @printable-exercise{transforming-data.adoc}, using @starter-file{alg2-wealth-transformed-desmos}.

Transforming the points instead of the axis has the same visual effect: the dots appear to fall in a straight line. But now we can plot them on a linear-scale axis, and use linear regression to find the best-possible model!

@teacher{
Crowdsource the coefficients (slope and y-intercept) of the linear models students come up with. How close are they to one another? How close are they to the coefficients from the best-guess logarithmic model?

They will discover that they match the coefficients of the logarithmic model as well.
}

[.lesson-instruction]
As a class: why are these coefficients similar to one another?

=== Investigate

We transformed the `pc-gdp` column in three steps:

1. We defined a transformation function: @math{g(x)}, which produces the log of whatever it's given (the `pc-gdp` column).
2. We defined a new column to use as our x-values, populating it by applying the transformation to each of our original x-values.
3. We displayed these transformed datapoints as a scatterplot.

**It's easy to do the same thing in Pyret**

[.lesson-instruction]
Turn to @printable-exercise{logarithmic-models.adoc}.

Find the definition of `g(r)` in your copy of the @starter-file{alg2-countries}.

* What does this function do?
** `g` produces the log of the `pc-gdp` column, which it gets from the country it's given
* Find the Contract for `build-column` on the @dist-link{Contracts.shtml, Contracts Page}. @pathway-only{_If you're working with a printed workbook, the contracts pages are included in the back._} What is its Range?
** Table
* What is its Domain?
** A Table, A String, and a Function

At the end of the program, you'll find this code:

@show{(code '(define countries-transformed (build-column countries-table "log(pc-gdp)" g)))}

Click "Run", and evaluate `countries-transformed` in the Interactions Area on the right.

* What did you get back?
** A Table
* What is different about this Table?
** It has an extra column called "log(pc-gdp)".
* Where did the column on the right come from?
** It was created by `build-column`, which named it `"log(pc-gdp)` and filled it using the function `g`.
* What does that line of code at the end of the program do?
** It defines a new table called `countries-transformed`, which is the result of building our new column.


@right{@image{images/lr-plot-transformed.png, 550}}
Just like in Desmos, transforming the `pc-gdp` column with a log function produces a scatter plot showing a linear pattern in the data! Pyret's `lr-plot` tool computes the best possible linear model for our transformed data, determining it to have a slope of `11.9011` and a y-intercept of `24.2636`. Our @math{R^2} has jumped to 0.66311, showing a vastly better correlation than before.

@clear

With the transformation applied, our linear model (in both function and Pyret notation) is:

- @math{f(x) = 11.9011x + 24.2636}
- @show{(code '(define (f x) (+ (* 11.9011 x) 24.2636)))}

At each point in our linear model, @math{f} is the _predicted median lifespan_, and @math{x} is the _log of per-capita gdp_. But we want @math{x} to represent the **original, un-transformed** value, simply using _per-capita gdp_ as-is.

From @printable-exercise{transforming-data.adoc}, we know that the coefficients used in the transformed, linear model are the same ones used in the logarithmic, un-transformed model:

- @math{h(x) = 11.9011 \times log(x) + 24.2636}
- @show{(code '(define (h x) (+ (* 11.9011 (log x)) 24.2636)))}

The resulting logarithmic model can be fit to our original scatter plot, showing a much better fit than our 2-point-derived estimates.

@center{@image{images/logarithmic-model.png, 550}}

@star Optional Exploration: Is the relationship between lifespan and income different for countries with universal healthcare than without it? Have students `filter` this dataset into grouped samples for each, and find out.

=== Synthesize

- Why is the @math{R^2} value for our logarithmic model the same as the value for our linear model after transforming?
- Why were our coefficients for linear and logarithmic models the same, even though they were for different terms?
- How do you interpret this model?
- Why do you think the relationship between wealth is logarithmic?
- Are there other relationships you can think of, which might be logarithmic?

@comment{
== Additional Exercises

- @opt-printable-exercise{grading-models.adoc}
}

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{Coming Soon!}

We are working on collecting more datasets that can be modeled with logarithmic functions so that we can offer students more practice with using linear regression to build logarithmic models.  
|===
