= Simple Inequalities

@lesson-description{Students discover the Boolean data type, and apply knowledge of inequalities to simple programming problems.}


[@lesson-intro-table]
|===
@prereqs-stds{alg-problem-decomposition}
| Lesson Goals
| Students will be able to:

* Describe the solution set of a simple inequality
* Explain the 'Boolean' datatype

| Student-Facing Lesson Goals
|
* I can use two or more inequalities together and describe the area they enclose.
* I can explain to someone else what a Boolean is.

| Materials
|
@ifproglang{wescheme}{
* Lesson slides (@link{https://docs.google.com/presentation/d/1jaMxaWc7XHlR7jf3RMPHU1mSsCetBmxp-52XiZq7HGo/edit?usp=sharing, Google Slides})
* Sam the Butterfly Starter File (@link{https://www.wescheme.org/view?publicId=AR6ndpC5s9, WeScheme})
}
@ifproglang{pyret}{
* Lesson slides (@link{https://docs.google.com/presentation/d/1akxlsl3LQkdtPwrbBarDFn8J96SvI-4l6qa4e1Ndrkg/edit?usp=sharing, Google Slides})
* Sam the Butterfly Starter File (@link{https://code.pyret.org/editor#share=1B5T5dTyRPb3rKJBZOgbYbQcFcsDeYZAA&v=f1d3c87, Pyret})
}

* Inequalities Launch worksheet (@workbook-link{pages/booleans-intro.adoc, original}, @link{solution-pages/booleans-intro.adoc, solutions})
* Inequalities Explore worksheet (@workbook-link{pages/sam-intro.adoc, original}, @link{solution-pages/sam-intro.adoc, solutions})

* Design Recipe: safe-left? (@workbook-link{pages/safe-left.adoc, original}, @link{solution-pages/safe-left.adoc, solution})
* Design Recipe: safe-right? (@workbook-link{pages/safe-right.adoc, original}, @link{solution-pages/safe-right.adoc, solution})

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|
@ifproglang{wescheme}{
* Booleans Review (@link{https://quizizz.com/admin/quiz/5d9919516dbee7001e08a4a0, Quizizz})
* Booleans Activity (@link{https://teacher.desmos.com/activitybuilder/custom/5d991ac49b9b292020c18108, Desmos Activity})
}
* Inequalities Bundle (@link{https://teacher.desmos.com/inequalities, Desmos Activities })
* Inequalities & Graphing Inequalities (@link{https://quizizz.com/admin/quiz/56cf6ac2bb56dfc267b35f94/inequalities-and-graphing-inequali, Quizizz })
* Inequality Graph Illustrator (@link{https://www.geogebra.org/m/Huq24Spq, Geogebra })

| Key Points for the Facilitator
|
* A @vocab{Boolean} is just another @vocab{data type}, like Number, or Image, but unlike the others there are only two values: `true` and `false`. While simple to explain, this different behavior can be confusing for some students.
* Functions that produce Booleans are typically questions, so the names of the functions in this lesson read like questions.
@ifproglang{wescheme}{
For example, `safe-left?`, `onscreen?` are both functions that are asking if a condition, such as an image being on the screen, is true or false.
* Role-playing can help students understand the jobs of `safe-left?` and `safe-right?`. 
}
@ifproglang{pyret}{
For example, `is-safe-left`, `is-onscreen` are both functions that are asking if a condition, such as an image being on the screen, is true or false.
* Role-playing can help students understand the jobs of `is-safe-left` and `is-safe-right`.
}
|===

[.old-materials]
For a textbook-like version of materials similar to these, you may wish to see the @link{https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/units/unit6/index.html, prior unit-based version}

== Warmup
Students should have their workbook, pencil, and be logged into
@ifproglang{wescheme}{ @link{https://www.wescheme.org, WeScheme     } }
@ifproglang{pyret}{    @link{https://code.pyret.org, code.pyret.org } }
and have their workbooks with a pen or pencil.

== Introducing Booleans @duration{15 minutes}

=== Overview
Students discover the concept of inequalities (or apply it, if they've seen it before) in programming, and extend their knowledge of data types, Contracts, and Circles of Evaluation.

=== Launch
Ask students to evaluate Circles of Evaluation for simple expressions they've seen before, and ask them to convert them into code.

- @show{(sexp->coe '(+ 1 2))}
- @show{(sexp->coe '(- 4 5))}
- @show{(sexp->coe '(* 8 0))}

Then show them unfamiliar Circles of Evaluation, and ask them to hypothesize what they think they means, what they will evaluate to, and what the code would look like.

- @show{(sexp->coe '(> 1 2))}
- @show{(sexp->coe '(< 4 5))}
- @show{(sexp->coe '(= 8 0))}

Have student type in these expressions. What did they get?

=== Investigate
[.lesson-instruction]
Have students open to the @workbook-link{pages/booleans-intro.adoc} worksheet and complete with a partner.

=== Synthesize
- Students will see functions on the worksheet that they've never encountered before! But instead of answering their questions, encourage them to make a _guess_ about they do, and then type it in to discover for themselves.
- Explicitly point out that _everything they know still works!_ They can use their reasoning about Circles of Evaluation and Contracts to figure things out.

== Introducing Sam @duration{30 minutes}

=== Overview
Students are introduced to Sam the Butterfly: a simple activity in which they must write 1-step inequalities to detect when Sam has gone too far in one dimension.

=== Launch
Have students open the 
@ifproglang{wescheme}{ @link{https://www.wescheme.org/view?publicId=AR6ndpC5s9, Sam The Butterfly starter file}  and click "Save." }
@ifproglang{pyret}{ @link{https://code.pyret.org/editor#share=1B5T5dTyRPb3rKJBZOgbYbQcFcsDeYZAA&v=f1d3c87, Sam The Butterfly starter file} and click "Save A Copy." }

Have students turn to the @workbook-link{pages/sam-intro.adoc, Introducing Sam} and investigate the program with their partner. 

__Let students figure out that they need to press "Run" to see what the program does, and that the arrow keys control Sam.__

- *What is something you noticed about this program?* 
_Sam can be moved with the arrow keys, the @vocab{coordinates} are displayed at the top of the screen, the coordinates are all in the 1st quadrant, etc._

- *What do you see when Sam is at (0,0)?  Why is that?* 
_You only see part of Sam's wing.  Sam's position is based on the center of Sam's image._

- *How far can Sam go to the left and stay on the screen?*  
_Up to, but not beyond, an x of -40._

- *How could we write this as an @vocab{expression}?* 
@math{x \geq -40}, or @math{x \gt -50}

[.lesson-point]
Every time Sam moves, we want to check and see if Sam is safe. 

- There are three functions defined in this file. What are they?

[.lesson-instruction]
@ifproglang{wescheme}{
*Note:* In this programming language, question marks are prounced "huh?". So `safe-left?` would be prounounced "safe left huh?" This can be a source of some amusement for students!
}

*Optional: For extra scaffolding...*

- *What _should_ our left-checking function do?*  
_Check to see if x is greater than -50_

- *What _should_ our right-checking function do?*
_Check to see if x is less than 490_

- *What should `onscreen?` do?* 
_Answers may vary, let students drive the discussion, and don't give away the answer_

=== Investigate
With their partners, students complete @workbook-link{pages/safe-left.adoc} and @workbook-link{pages/safe-right.adoc}.  Once finished, students can fix the corresponding functions in their Sam the Butterly file, and test them out.

@ifproglang{wescheme}{
Students will notice that fixing `safe-left?` keeps Sam from disappearing off the left, but fixing `safe-right?` doesn't seem to keep Sam from disappearing off the right side!  When students encounter this, encourage them to look through the code to try and figure out why. The answer will be revealed in the next lesson.
}

@ifproglang{pyret}{
Students will notice that fixing `is-safe-left` keeps Sam from disappearing off the left, but fixing `is-safe-right` doesn't seem to keep Sam from disappearing off the right side!  When students encounter this, encourage them to look through the code to try and figure out why. The answer will be revealed in the next lesson.
}

- Recruit three new student volunteers to roleplay those same functions, which have now been _corrected_. Make sure students provide correct answers, testing both `true` and `false` conditions using coordinates where Sam is onscreen and offscreen.

=== Common Misconceptions
- Many students - especially traditionally high-achieving ones - will be very concerned about writing examples that are "wrong." The misconception here is that an expression that produces `false` is somehow _incorrect_. You can preempt this in advance, by explaining that our Boolean-producing functions _should sometimes return false_, such as when Sam is offscreen.
- Push students to think carefully about corner-cases, such as when Sam is _exactly_ at -50 or 690.

=== Synthesize
@ifproglang{wescheme}{
- Recruit three student volunteers to roleplay the functions `safe-left?`, `safe-right?` and `onscreen?`. Give them 1 minute to read the contract and code, as written in the program.
- For each of them, ask the volunteers what their name, Domain and Range are, and then test them out by calling out their name, followed by a number. (For example, "(safe-left? 20)!", "(safe-right? -100)!") *Note:* Do not ask `onscreen?` to roleplay beyond their contract! They'll get involved in the next lesson... 
}
@ifproglang{pyret}{
- Recruit three student volunteers to roleplay the functions `is-safe-left`, `is-safe-right` and `is-onscreen`. 
- For each of them, ask the volunteers what their name, Domain and Range are, and then test them out by calling out their name, followed by a number. (For example, "is-safe-left(20)!", "is-safe-right(-100)!") *Do not ask `is-onscreen` to roleplay beyond their contract!* 
}

=== Additional Exercises
- Keeping Ninjacat in the Game
(@exercise-link{pages/keeping-ninjacat-in-the-game.adoc, original} ,
@exercise-link{solution-pages/keeping-ninjacat-in-the-game.adoc, answers})

- Converting Circles of Evaluation with Booleans to Code
(@exercise-link{pages/boolean-coe-to-code1.adoc, original} ,
@exercise-link{solution-pages/boolean-coe-to-code1.adoc, answers})

- Converting Circles of Evaluation with Booleans to Code
(@exercise-link{pages/boolean-coe-to-code2.adoc, original} ,
@exercise-link{solution-pages/boolean-coe-to-code2.adoc, answers})
