= Exploring Displays

For each type of display, fill in the information below.

[cols="^.>1a,^.>1a",stripes="none",options="header"]
|===
| Pie Charts | Bar Charts
| @vspace{30ex} Sketch a pie chart here. | @vspace{30ex} Sketch a bar chart here.

| @span{.left}{Pie charts are constructed from @fitb{1ex}{_1_} column(s).}
| @span{.left}{Bar charts are constructed from @fitb{3ex}{_1_} column(s).}

| @span{.left}{They show @fitb{30ex}{_categorical_} data.} 
| @span{.left}{They show @fitb{30ex}{_categorical_} data.}

| @span{.left}{What does this display tell us?}
@fitb{50ex}{_The proportion in which values in a categorical column_}
@fitb{50ex}{_are represented_}
@fitb{50ex}{}

| @span{.left}{What does this display tell us?}
@fitb{50ex}{_The proportion in which values in a categorical column_}
@fitb{50ex}{_arerepresented - including categories that are_}
@fitb{50ex}{_not represented_}
|
|===

@vspace{3ex}

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Box Plots | Histograms
| @vspace{38ex} Sketch a box plot here | @vspace{38ex} Sketch a histogram here
|
--
@span{.left}{
Box plots are constructed from @fitb{3ex}{_1_} column(s), and show @fitb{28ex}{_quantitative_} data.
What do you think this display tells us?
@fitb{55ex}{_The range of quantitative values in the bottom quarter, top_}
@fitb{55ex}{_quarter, and the middle quarters. This tells us something about_}
@fitb{55ex}{_the spread of the data_}
}
--

|
--
@span{.left}{
Histograms are constructed from @fitb{3ex}{_1_} column(s), and show @fitb{28ex}{_quantitative_} data.
What do you think this display tells us?
@fitb{55ex}{_How many values in a quantitative column fall into_}
@fitb{55ex}{_equally-sized bins. This tells us something about_}
@fitb{55ex}{_the spread of the data_}
}
--
|===
