= (More) Exploring Displays 

For each type of display, fill in the information below.

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Scatter Plot | Linear Regression Plot
| @vspace{38ex} Sketch a pie chart here | @vspace{38ex} Sketch a bar chart here
| 
--
@span{.left}{
Scatter Plots are constructed from @fitb{3ex}{2} column(s), and show @fitb{28ex}{quantitative} data.
What do you think this display tells us?
@fitb{55ex}{something about the relationship between two quantitative}
@fitb{55ex}{columns, graphing all pairs of values as points on a plane.}
@fitb{55ex}{This allows us to look for patterns, clusters, trends, etc.}
}
--

| 
--
@span{.left}{
LR Plots are constructed from @fitb{3ex}{2} column(s), and show @fitb{28ex}{quantitative} data.
What do you think this display tells us?
@fitb{55ex}{something about the relationship between two quantitative}
@fitb{55ex}{columns, graphing all pairs of values as points on a plane,}
@fitb{55ex}{drawing the line of best fit, and showing correlation stats}
}
--
|===