= Choosing Your Dataset

@lesson-description{Students summarize their dataset by exploring the 
data and identifying categorical and quantitative columns, datatypes, 
and more. They also define a few sample rows, random subsets, and
logical subsets.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-grouped-samples}
| Lesson Goals
| Students will be able to...

* Explain why they chose their dataset
* Describe their dataset
* Make subsets from their dataset

| Student-facing Lesson Goals
|

* Let's all choose an interesting dataset to investigate.

| Materials
|
* Lesson Slides (@link{https://docs.google.com/presentation/d/1SRZ9xk69gfUrKvreqX7hf8BiYEmr7ZyuUHIk779fieU/, Google Slides})
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs
* All students should log into @link{https://code.pyret.org, CPO} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can @link{https://code.pyret.org/editor#share=1Z8ncVGKqWiED_wHl8TlNF3D9AGBb7awm, open a new one}

| Supplemental Resources
|

@include{xtra/lang-prereq.adoc}
|===

== The Data Cycle @duration{20 minutes}

=== Overview
Students learn about the _Data Cycle_, which helps them get situated in the process of analyzing the datasets they will select in this lesson. They browse through the library of provided datasets, and choose one they want to work with. NOTE: the selection process can also be done as a homework assignment, if all students have internet access at home.

=== Launch
Zoom out a little and help students reflect on what they've done so far. Students began by exploring the Animals Dataset, formulating questions and exploring them with data displays. This led to further questions, making subsets, and asking more questions.

@span{.right}{@image{images/data-cycle.png, "", 400}}
The Data Cycle[*] is a _roadmap_, which helps guide us in the process of data analysis.

(Step 1) We start by *Asking Questions* - statistical questions that can be answered with data. 

(Step 2) Then we *Consider Data*. This could be done by conducting a survey, observing and recording data, or finding a dataset that meets our needs. 

(Step 3) Then it's on to *Analyzing the Data*, in which we produce data displays and new tables of filtered or transformed data in order to identify patterns and relationships. 

(Step 4) Finally, we *Interpret the Data*, in which we answer our questions and summarize the results. As we've already seen from the Animals Dataset, these interpretations often lead to _new_ questions....and the cycle begins again.

@span{.clear}{}

Explain to students that they will now select a dataset for them to work with for the remainder of the course. Make sure they understand that it genuinely has to be something they are interested in - their engagement with the data is critical to engaging with the class.

_Students can also find their own dataset_, and use this (@link{https://code.pyret.org/editor#share=12v7kzbxHt2LaSe2uI2d_OnssxtTNF0A8, Blank Starter file}). See this @link{https://youtu.be/K4n9hTSqcyw, tutorial video} for help importing your own data into Pyret.

[.lesson-point]
Students must have at least 2 questions that are both _interesting_ and _answerable_ using their dataset.

=== Investigate
[.lesson-instruction]
--
Choose a dataset that is interesting to you! You should have at least two questions that the dataset can help you answer. Write these questions down on @workbook-link{pages/whats-on-your-mind.adoc}.

[.TwoColumnDD_DT]
Movies:: 
  @link{https://docs.google.com/spreadsheets/d/1ldK-Xte5xCAPd6hz2wreBaJzuw-voe4q6ui9QkFGz8w, Dataset}
  @link{https://code.pyret.org/editor#share=1xke6yN2gkn_q-Bf2yC7772i6NNezyjbk, Starter File}
Schools::
  @link{https://docs.google.com/spreadsheets/d/1XeeyAuF_mtpeCw2HVCKjvwW1rreNvztoQ3WeBlEaDl0/, Dataset}
  @link{https://code.pyret.org/editor#share=1Xu0ket-eDCeU-Uuxl82OCCGJQRW_ghWV, Starter File}
US Income::
  @link{https://docs.google.com/spreadsheets/d/1cIxBSQebGejWK7S_Iy6cDFSIpD-60x8oG7IvrfCtHbw, Dataset}
  @link{https://code.pyret.org/editor#share=1qSK5KX7cfwM4c6XtJFg5gPcVp9OBSbOU, Starter File}
US Presidents::
  @link{https://docs.google.com/spreadsheets/d/1Frt37-nBHHxvJVBKzKLRD3kbjPLhc8CYUaIlNeNWl94, Dataset}
  @link{https://code.pyret.org/editor#share=1prkKxnGrGJJAab7XBXTqiysRli0xFEbL, Starter File}
Countries of the World::
  @link{https://docs.google.com/spreadsheets/d/19VoYxPw0tmuSViN1qFIkyUoepjNSRsuQCe0TZZDmrZs, Dataset}
  @link{https://code.pyret.org/editor#share=1wEHqx0f9VOxmRUVqDjnPCECOmvPWyQdS, Starter File}
Music::
  @link{https://docs.google.com/spreadsheets/d/1Yzo8GuGhMDVNyAI5OacmKZ53xJplZbXF5FT6Lwitp0w, Dataset}
  @link{https://code.pyret.org/editor#share=1UIYszUXHA0gx7jmFhEitvKxqa7MDmcxO, Starter File}
NYC Restaurant Health Inspections::
  @link{https://docs.google.com/spreadsheets/d/1inK0kq8bNeN1vYbx0HpNZ8xHOp5pmP2FoLcfK9pQhJI, Dataset}
  @link{https://code.pyret.org/editor#share=1LMziboHPlgtATfwpOUEDJzMPW2MVIp6o, Starter File}
Pokemon Characters::
  @link{https://docs.google.com/spreadsheets/d/1S8jf4Qf94TJKGLCcTA-Fqn4YXE7dGf_PIxv5MUeUPVo, Dataset}
  @link{https://code.pyret.org/editor#share=1Nxhiw46EFfNhmMBvUQK0NosbFnaBCQJy, Starter File}
IGN Video Game Reviews::
  @link{https://docs.google.com/spreadsheets/d/1Ss221kjz2WJUsTlxK7TcnsXLPoSbnfUKv-JP8gCiGRw, Dataset}
  @link{https://code.pyret.org/editor#share=1IVnp6-NCuvbk1cQH6CRly_6I6-OEBOVI, Starter File}
2016 Presidential Primary Election::
  @link{https://docs.google.com/spreadsheets/d/1fgIREXT5lAaAPWqrNP3S191ID_ecoXDjBe_gAC00-M4, Dataset}
  @link{https://code.pyret.org/editor#share=1pPF0KjcjM7C82wpShDmQ5D_CD39lE7AE, Starter File}
US Cancer Rates::
  @link{https://docs.google.com/spreadsheets/d/1deL-6Xh9WUN2fTcV95V7RLseAcplGNA6BHTnpHCMgME, Dataset}
  @link{https://code.pyret.org/editor#share=1qJxOMxULihXhtrIVaLPboFtYpUiLnFct, Starter File}
US State Demographics::
  @link{https://docs.google.com/spreadsheets/d/14fRmjAiCqGNI5Zr5kGSDjMavln7ILqhSX3N3zGd8CAU/edit, Dataset}
  @link{https://code.pyret.org/editor#share=1IzvOGVQdhi-QMKJdl7IBpM1vGSjaV_P_, Starter File}
Sodas::
  @link{https://docs.google.com/spreadsheets/d/15n0dLqBWffE2JNOmYHcvavqMwvHXpy5_UyZfT3Q7pfs, Dataset}
  @link{https://code.pyret.org/editor#share=12AFxlJuNjmxYTUV0FWa7z3D5CHRYBXoG, Starter File}
Cereals::
  @link{https://docs.google.com/spreadsheets/d/1y3AoywSnyGpu-QmmEwKvW-xstZ6B9JhH5gTUx5XYTo4, Dataset}
  @link{https://code.pyret.org/editor#share=1syDC8qoFjO4EdqycRAfWlKMHanzrqTSH, Starter File}
Summer Olympic Medals::
  @link{https://docs.google.com/spreadsheets/d/1ee30kHpV35zAO5MNQKk_nXP6iym2mX-bv_cgt-8q_oo, Dataset}
  @link{https://code.pyret.org/editor#share=1bkI_WiWZvLlS5x3A0vx6C-m-fJonIPW4, Starter File}
Winter Olympic Medals::
  @link{https://docs.google.com/spreadsheets/d/1-xYW4C0IRB7cDI2K8dMyVTlsQjFmB_Z4XBsHsB-TAbs, Dataset}
  @link{https://code.pyret.org/editor#share=1kFV_BmSDTSAbNDdm-IFZrGdI1I6K4-aL, Starter File}
MLB Hitting Stats::
  @link{https://docs.google.com/spreadsheets/d/1xjC1XZWACvQtfwHdGk_BlE2jm4aleMADHTt6PEocCjg, Dataset}
  @link{https://code.pyret.org/editor#share=1X80kXcexm4kriNFTJXLVr_8m2TZOvhzr, Starter File}
Spotify Top Songs::
  @link{https://docs.google.com/spreadsheets/d/18Yb3zWIIensRdz1C1iqqtZ4aXjbKOD7z2SSL09Zm1Xc, Dataset}
  @link{https://code.pyret.org/editor#share=1x6-ckp0F1nN2SwoXtqYyxRKbT8ZgRfs9, Starter File}

Open the @link{https://docs.google.com/document/d/1_ZEIgM4zvxI7JizViVFZojnpd3Yr2rYe8puPk8pjOcs/copy, Research Paper template}, and save a copy.

- Students fill in their first and last name(s), the teacher name on the first page of the Research Paper.
- Students should also copy the link to the dataset (spreadsheet), and paste it into the first page of the Research Paper.
- Students should click "Publish" in their Pyret Starter File, then copy/paste the resulting link into the first page of the Research Paper.
--


=== Synthesize
Have students share their datasets and their questions.

For the rest of this course, students will be learning new programming and Data Science skills, practicing them with the Animals Dataset and then applying them to their own data.

== Exploring Your Dataset @duration{flexible}

=== Overview
Students apply what they've learned about describing and making subsets from the Animals Dataset to their own dataset. *Note: this activity can be done briefly as a homework assignment, but we recommend giving students an _additional class period_ to work on this.*

=== Launch
By now you've already learned what to do when you approach a new dataset. With the Animals Dataset, you first read the data itself, and wrote down your Notice and Wonders. You described the columns in the Animals Dataset, identifying which were categorical and which were quantitative, and whether they were Numbers, Strings, Booleans, etc. Finally, you used the Design Recipe and table methods to make random and logical subsets.

Now, you're doing to do the same thing _with your own dataset._

=== Investigate
[.lesson-instruction]
- Have students look at the spreadsheet for their dataset. What do they *Notice*? What do they *Wonder*? Have them complete @workbook-link{pages/my-dataset.adoc}, making sure to have at least two Lookup Questions, two Compute Questions, and two Relate Questions.
- In the Definitions Area, students use `random-rows` to define *at least three* tables of different sizes: `tiny-sample`, `small-sample`, and `medium-sample`. 
- In the Definitions Area, students use `.row-n` to define *at least three* values, representing different rows in your table.
- Have students think about subsets that might be useful for their dataset. Name these subsets and write the Pyret code to test an individual row from your dataset on @workbook-link{pages/samples-from-my-dataset.adoc}.
- Students should fill in @link{https://docs.google.com/document/d/1_ZEIgM4zvxI7JizViVFZojnpd3Yr2rYe8puPk8pjOcs/edit#heading=h.6cy9t2stox4e, My Dataset} portion of their Research Paper.
- Students should fill in @link{https://docs.google.com/document/d/1_ZEIgM4zvxI7JizViVFZojnpd3Yr2rYe8puPk8pjOcs/edit#heading=h.h6dvbsrt7r00, Categorical Visualizations} portion of their Research Paper, by generating pie and bar charts for their dataset and explaining what they show.

[.lesson-instruction]
Turn to @workbook-link{pages/design-recipe-helper-funs.adoc}, and use the Design Recipe to write the filter functions that you planned out on @workbook-link{pages/samples-from-my-dataset.adoc}. When the teacher has checked your work, type them into the Definitions Area and use the `.filter` method to define your new sample tables.

[.lesson-instruction]
Choose one categorical column from your dataset, and try making a bar or pie-chart for the whole table. Now try making the same display for each of your subsets. Which is most representative of the entire column in the table?

=== Synthesize

Have students share which subsets they created for their datasets.


[*] From the @link{http://introdatascience.org/, Mobilizing IDS project} and @link{https://www.amstat.org/asa/files/pdfs/GAISE/GAISEPreK12_Intro.pdf, GAISE}