= The Additive Inverse Property

@description{Students develop a more nuanced interpretation of the Commutative and Associative Properties as a result of their exploration of the inverse relationship between addition and subtraction.}

@lesson-prereqs{associative-property}

@keywords{Associative Property, Commutative Property}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

@objectives
@objective{Recognize that subtracting @math{x} is the same as adding @math{-x}.}
@objective{Acknowledge _flexibility_ in the Order of Operations.}

| Student-facing Lesson Goals
|

* Let's explore the inverse relationship between addition and subtraction.

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
* This lesson is all about _mathematical flexibility_, and may challenge preexisting ideas about arithmetic. For students who've had a mostly procedural introduction to mathematics - or who have high math anxiety - the flexibility introduced by this lesson can be intimidating!
* Embrace an open mind and expect the same of your students, and be attentive to their emotional response as the lesson progresses. If students are getting anxious, they will not be able to concentrate and focus on the content.
* There is no expectation that students will master operations with integers. Rather, the lesson is designed to get students thinking about how every number has an additive inverse.
|===

== The Additive Inverse Property

=== Overview

Students discover the Additive Inverse Property, which tells us that adding a number and its opposite always produces zero.

=== Launch
@slidestyle{Launch}

We’ve learned that the @vocab{Commutative Property} and @vocab{Associative Property} apply to addition... but not division. What if there was a way to rewrite subtraction as addition? Then we could apply the Commutative and Associative Properties to subtraction expressions, too! Let’s explore this idea.


@slidebreak{Launch}

I'm going to draw a two-column table on the board. I'm labeling the left-hand side "Starting Value," and I'm labeling the right-hand side "Additive Inverse".

I'm going to write a number in the left-hand column. You are going to tell me what value I should add to that number, to get a sum of zero. I'll record your response in the right-hand column.

[cols="^1,^1", options="header"]
|===
| Starting Value		| Additive Inverse
| @vspace{3ex}			|
|===

@slidebreak{Launch}


@QandA{
@Q{The first number is @math{5}. What do I need to add to @math{5} to get @math{0}?}
@A{@math{-5}. If this is students' first exposure to negative numbers, consider modeling a few examples.}

@Q{The next number is @math{20}. What do I need to add to @math{20} to get @math{0}?}

@Q{How about @math{\frac{1}{2}}?}

@Q{How about @math{-45}?}

@Q{Can someone offer me another pair of numbers that add up to @math{0}?}
}

@teacher{Allow a variety of students to share. Record responses on the table.}

@slidebreak{Launch}

These number pairs all represent @vocab{opposites}.

@lesson-point{
The @vocab{Additive Inverse Property} tells us that adding a number and its opposite always produces zero.
}

Every number has an additive inverse.

@teacher{
Ensure that students are comfortable with this concept before moving onto the next activity.
}

=== Investigate
@slidestyle{Investigate}

@lesson-instruction{
- Turn to @printable-exercise{additive-inverse.adoc}.
- In the first section, determine the additive inverses and write them in the spaces provided.
- Then, fill in the missing number to complete the equations. Some equations use mathematical notation and some use Circles of Evaluation.
}

=== Synthesize
@slidestyle{Synthesize}

- Can you think of a way to visually represent that adding a number and its opposite always produces zero?
- How would you explain the concept of the Additive Inverse Property to another student?
- Looking forward: Can you predict what effect the Multiplicative Inverse Property might have?

== Addition and Subtraction: Inverse Operations

=== Overview

Students rewrite addition expressions as subtraction, and subtraction expressions as addition by applying their knowledge of the @vocab{Additive Inverse Property}.


=== Launch
@slidestyle{Launch}

Now that we understand what the additive inverse is, we are ready to think about how we can put it to use... perhaps it can make some computations simpler?

@lesson-instruction{
- Complete @printable-exercise{discover-inverse.adoc}.
- When you're done, complete @printable-exercise{discover-inverse-cont.adoc}.
- What did you observe about the additive inverse?
}

@slidebreak{Launch}

During this exploration, you should have discovered that:

- Subtraction is equivalent to adding the @vocab{opposite}.
- We can rewrite any subtraction expression as addition, and any addition expression as subtraction!

One powerful advantage emerges when we write subtraction as addition: we now can apply the Commutative and Associative Properties to a much broader set of expressions!

=== Investigate
@slidestyle{Investigate}

@teacher{
Now, students are ready to continue their exploration of subtraction as the inverse of addition. Note: To complete this worksheet, students do not need to be fluent at integer addition and subtraction. We just want students thinking about when expressions are @vocab{equivalent} based on what they have learned about the additive inverse.
}

@lesson-instruction{
Complete @printable-exercise{wodb.adoc}.
}

@teacher{
Have students share strategies for determining equivalence. What are the different ways that they thought about the Additive Inverse Property?
}

=== Synthesize
@slidestyle{Synthesize}

- Claire and Soraya want to write an equivalent expression for @math{22 - 30}. Claire studies the expression and announces that, because it involves subtraction, the Commutative Property cannot be applied. Is she correct?
- Soraya grabs a pencil and writes the following: @math{22 + -30}. She says, "There! I fixed it. Now we can apply the Commutative Property." Explain what Soraya did. Is she correct?
- Use the Additive Inverse Property to simplify this expression using mental computation: @math{3 + 96.8 - 42.74 - 96.8 + 7 - 3 + 42.74}

== The "Left-to-Right" Rule

=== Overview

Students examine whether rigid adherence to the "left-to-right" rule is needed when adding and subtracting.

=== Launch
@slidestyle{LaunchR}

@QandA{
@Q{Consider this expression: @math{10 + 9 - 4}. What do we get when we simplify it to a single value?}
@A{15}
@Q{How did you arrive at your answer?}
}

Did you work from left to right to arrive your result? This solving strategy can be represented by the Circle of Evaluation, below.

@show{(coe '(- (+ 10 9) 4))}

@slidebreak{LaunchR}

*Is it essential to solve from left to right?*

@teacher{Ask if anyone opted to subtract _before_ adding. If so, invite them to share their method and then invite other students to weigh in.}

Evaluate the Circle of Evaluation below. Is it equivalent to the previous Circle of Evaluation?

@show{(coe '(+ 10 (- 9 4)))}

@slidebreak{Launch}

We’ve learned that the Associative Property applies for expressions with only addition... not addition _and_ subtraction. Many of us have also learned that when an expression includes addition and subtraction, we must work from left to right. *So… what’s going on!?* It appears that we get the same result regardless of how we simplify this expression.

=== Investigate
@slidestyle{Investigate}

Does subtracting _first_ work every time? Can we rearrange the groupings of any expression with both addition and subtraction? Let's investigate.

@slidebreak{Investigate}

@lesson-instruction{
- Turn to @printable-exercise{subtract-first-or-left-to-right.adoc}.
- There, you will test out the this algorithm on several different expressions to see if subtracting and then adding produces the correct result every time.
- What do you Notice? What do you Wonder?
- Why are we able to change the groupings for an expression like @math{10 + 9 - 4} ... but _not_ for an expression like @math{10 - 9 - 4}?
- Describe why the this "subtraction first" algorithm works. (Hint: Think about the @vocab{Additive Inverse Property}!)
}

@slidebreak{Investigate}

@teacher{
Encourage students to think deeply about why this algorithm works – and if you’d like, invite them to consider and discuss why students all across the country are typically taught just one algorithm when, typically, there are an abundance to choose from!}

Let's put our new knowledge to use!

@teacher{Project the problems below one at a time, and invite students to solve using mental math.}

@QandA{

Scan each problem to identify any additive inverses, then solve using mental computation.

@Q{@math{4 + 5 + 97 - 4 + 3}}
@A{@math{105}}

@Q{@math{9 + 17 + 41 - 17}}
@A{@math{50}}

@Q{@math{67 - 104 + 937 - 67 + 104}}
@A{@math{937}}
}

=== Synthesize
@slidestyle{Synthesize}

- How did it feel to scan the problem, find any additive inverses, and then solve mentally?
- Did you like this new approach, or do you prefer solving left to right?
- How would you explain to another student why they do _not_ always need to solve from left to right when evaluating expressions with addition and subtraction.
- What are some advantages of solving left to right? What are some disadvantages?


== Programming Exploration: The Additive Inverse

=== Overview

Students learn about examples in @proglang, and use their new knowledge to think about addition and subtraction as inverse operations.

=== Launch
@slidestyle{Launch-DN}

@lesson-instruction{
- Open the @starter-file{additive-inverse}, but *do not click "Run" yet!*
- On @printable-exercise{examples-additive.adoc}, record what you Notice and what you Wonder about the starter file.
- Let's share out some of our Noticings and Wonderings.
}

@slidebreak{Launch}

Here are some common Noticings. Is there anything on this list that you _didn't_ notice?

- Sections 1 and 2 each include five examples.
- Some words are in bold.
- Some words are in different colors and have @ifproglang{pyret}{hashes}@ifproglang{wescheme}{semicolons} in front of them.
@ifproglang{pyret}{
- The examples end with `end`.}

@slidebreak{Launch}

@lesson-point{Comments let programmers write notes.}

Lines and lines of code can be difficult to read! Sometimes programmers want to write down their thinking, or leave notes to help others understand what the code is doing. That's what @vocab{comments} are for: a @ifproglang{pyret}{hash}@ifproglang{wescheme}{semicolon} at the start of a line tells the computer that the rest of the line is a @vocab{comment} instead of code. To make comments stand out, they are colored @ifproglang{pyret}{dark orange}@ifproglang{wescheme}{purple}.

The comments in lines 2, 14, and 26 are used to break up the code into sections that make the starter file easier for users to interpret.

@slidebreak{Launch}

@lesson-point{Examples let programmers test their code.}

Sometimes a comment isn't enough. A programmer might want to write down their thoughts so _that the computer can test their thinking_. These are called @vocab{examples}.

Take a look at the first _examples block_ (lines 4-12). We start @ifproglang{pyret}{by typing `examples:`, then} writing one or more _examples_ of how we want some code to work@ifproglang{pyret}{ before closing with with `end`}.@ifproglang{pyret}{ Notice that all of the examples are indented slightly, grouping them together between the bolded words.} When we click "Run", @proglang will test each of our examples, and report back which ones are correct and which ones are not.

@slidebreak{Launch}

@lesson-instruction{
- Return to your starter file and click "Run".
- With your partner, respond to questions 2 through 3 on @printable-exercise{examples-additive.adoc}.
}

@teacher{Debrief with students to ensure that they are looking at the messages that appear in @proglang. This activity not only provides practice thinking about the additive inverse; it also gives students exposure to tests - bits of code used to verify that code is working as we would expect. Examples and tests are widely used in programming! We explore examples in greater depth in @lesson-link{functions-examples-definitions}.}

=== Investigate
@slidestyle{Investigate}

For the remainder of the activity, we will examine examples blocks. The first one includes only examples that pass. The second one has some errors! And the third one includes just one examples... *you* will be responsible for providing additional examples!

@lesson-instruction{With your partner, complete @printable-exercise{examples-additive.adoc}.}

@teacher{
@opt{If you would like to offer students additional practice with the additive inverse in @proglang, two optional activities include @opt-printable-exercise{are-they-identical.adoc} and @opt-printable-exercise{writing-equivalent-code-additive.adoc}.}
}


=== Synthesize
@slidestyle{Synthesize}

- Using @proglang allows us to evaluate arithmetic expressions easily and efficiently. In your own words, describe _how_ you tested the equivalence of different expression - and how you interpreted the results that @proglang produced.
- In @proglang, what does it mean for a test to pass? What does it mean for a test to fail?
- What did this programming exploration teach you about the additive inverse?
