= Function Composition 2

@lesson-description{Students explore scaling images and how scale factor affects the measurements of a figure.}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Explain ‘center’ and ‘scale factor’ as related to dilations
* Demonstrate understanding that scaling changes lengths of a figure proportionally


|Student-Facing Lesson Goals
|
* I can describe what a dilation is using words or actions.
* I can predict, given the scale factor, if the dilation will be larger or smaller than the original image.
* I can figure out what the sides of a shape will measure after a dilation.


|Key Points for the Facilitator
|
* Students should discover independently that a scale factor of <1 creates a smaller image (reduction) and a scale factor of >1 creates a larger image (enlargement).  
* Students should connect the scale factor to previous knowledge of percentages.
* The scale function in WeScheme will not allow for negative scale factors.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.

|Materials
|
* https://docs.google.com/presentation/d/1SwGJFpXMAfnl_fnyhTf-0rKQvWd6PyslSGcRbzJDJ0M/edit?usp=sharing[Google Slides]

Bootstrap Formative Assessments

* https://quizizz.com/admin/quiz/5a146afd3b4ad115000fcb57?from=quizEditor[Unit 1 Quiz Bootstrap Algebra] (Quizizz)
* https://teacher.desmos.com/activitybuilder/custom/5a15e2388c08800a6024c091[Unit 1 Circles of Evaluation And Code Practice] (Desmos Activity)
* https://teacher.desmos.com/activitybuilder/custom/5a1c805bbfc8c40614d3904a[Unit 1 Circles of Evaluation And Code Practice - Blank Template] (Desmos Activity)
* https://quizizz.com/admin/quiz/5a15d1a82b65d91100dc2055?from=quizEditor[Unit 2 Quiz Bootstrap: Algebra] (Quizizz)
* https://teacher.desmos.com/activitybuilder/custom/5a15e268dcb86b2b9fda3ce0[Unit 2 Bootstrap Algebra Review] (Desmos Activity)

Connection Activities

* https://www.geogebra.org/m/nqymeFc4[Function Composition Dynamic Illustrator I ] (Geogebra)
* https://www.geogebra.org/m/h3qdzW3W[Composition of Function] (Geogebra Quiz)
* https://quizizz.com/admin/quiz/58a61a2cf0b089151011ef50/composition-of-functions[Composite Functions] (Quizizz)

|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Previous Math Standard (CCSS)
|
* Building on @std{7.RP.A.1}

|Corresponding Math Standard (CCSS)
|
* Building towards @std{8.G.A.1}

|Standards of Mathematical Practice
|
* @std{MP.1}
|===


== Get Ready:

Students should have their computer, contracts page, and pencil.

== Launch: (10 min)

[.notice-box]
.Notice and Wonder
****
Notice and Wonder 
****

Launch task

== Explore: (10 min)

Using Google Image Search, students search for an image that interests them and bring it in to WeScheme with the new function bitmap/url.  The bigger, the better! 

== Discuss: (10 min)

* Students discuss the large images and the need to scale them down to make them workable.  Introduce the contract for dilate and let students figure out how it works.
* How can I add an image from the Internet to my code?
* Give me a number that will make my image larger.  Smaller?  What do you notice about these numbers?
* Could we write a rule about the relationship between the scale factor and the resulting image?
* Why do we want height and width to change by the same factor in these exercises?  What would happen if we changed them by different factors?

[.strategy-box]
.Strategies for English Language Learners
****
MLR 8 - Discussion Supports: As students discuss the guiding questions, rephrase responses as questions and encourage precision in the words being used to reinforce the meanings behind some of the programming-specific language.
****

== Practice: (10 min)

Workbook page

== Create/Apply: (20 min)

Students search for images for their game, using the plan they laid out with their partner previously.  Students need to find images for:

* PLAYER
* DANGER
* TARGET
* BACKGROUND

_Add more here_
