= Evaluating Exponents

@description{Students use Circles of Evaluation analyze the structure of expressions that include exponents.}

@lesson-prereqs{absolute-value-and-opposites-more}

@keywords{exponent, base}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Translate between words, mathematical expressions, and Circles of Evaluation.
* Evaluate expressions involving exponents and one other operation.
* Evaluate expressions involving exponents and negations.


| Student-facing Lesson Goals
|

* Let's use Circles of Evaluation to analyze the structure of expressions with exponents.

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
* Circles of Evaluation will not help students to visualize or understand the meaning of exponents as repeated multiplication. Rather, they will help students parse expressions that involve exponents. We recommend ensuring that students are comfortable evaluating exponents before jumping into this lesson.

|===

== Expressions with Exponents and One Operation @duration{30 minutes}

=== Overview

Sudents use Circles, words, and mathematical notation to analyze the structure of expressions with exponents and one operation.

=== Launch

[.lesson-instruction]
- Show students the following expression: @math{2^3}
- One way of reading this expression is "two raised to the power of three." Do you know any other ways of reading this expression with an exponent?
** _Two to the third power; two to the third; two cubed._
- What does it mean to _cube_ a number?
** We multiply it by itself three times.
- What does this expression evaluate to?
** @math{2^3 = 2 \times 2 \times 2 = 8}

Clarify and reinforce some key concepts about exponents via class discussion:

- The number on the left is called the _base_; that number is multiplied by itself when we apply the exponent.

- The number next to the base is called the _exponent_; it indicates how many times to multiply the base.

- "Cubing" is the same as "raising to the third power", and "squaring" is the same as raising to the second power.

- There is no special terminology for any other exponents. (The subsequent lesson will address why two and three are referred to as "squaring" and "cubing.")

Explain to students that we can represent expressions with exponents as Circles of Evaluation. The expression we used is called `num-expt`; when we use `num-expt`, the value on the left is the _base_, and the value on the right is the exponent. The Circle of Evaluation for @math{2^3} looks like this:

[.centered-image]
@show{(coe '(num-expt 2 3))}
@clear

Now, have students analyze the two Circles below.

[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===
|@math{5^2}							| @math{2^5}
|@show{(coe  '(num-expt 5 2))}		| @show{(coe  '(num-expt 2 5))}
|===

[.lesson-instruction]
- Can we switch the order of the exponent and the base, as we could when adding or multiplying values?
** _No; the first Circle evaluates to 25, while the second Circle evaluates to 32._

At first, Circles of Evaluation with exponents might seem like more trouble than they're worth. After all, exponents are a shorthand for repeated addition; to see the structure of an exponential expression, students can use expanded form. As students will soon discover, Circles become a useful tool when dealing with exponential expressions involving additional operations and negations.

=== Investigate

Invite students to examine the two Circles below:

[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===

|@show{(coe  '(* 9 (num-expt 3 2)))}		| @show{(coe  '(num-expt (* 9 3) 2))}
|===

[.lesson-instruction]
- How would you translate each of these Circles into words? Why are their translations different?
** _The Circle on the left is "nine multiplied by three squared," while the Circle on the right is "find the product of nine and three, then square it." Their translations differ because the Circles are organized differently._
- How would you translate each of these Circles into mathematical expressions?
** The Circle on the left is @math{9 \times 3^2} while the Circle on the right is @math{(9 \times 3)^2}.

Students will likely suggest @math{9 \times (3^2)} as a translation for the Circle on the right. This response is of course, correct - but it is valuable for students to recognize that expressions with exponents are often written _without_ the parentheses. Still, every time they create a Circle representation of an expression including a base and exponent, it will be drawn inside of its own Circle.

After students understand that, in an expression with no grouping symbols, we evaluate the exponent before the other operations, they are ready to continue their exploration of expressions with exponents.

[.lesson-instruction]
- Translate between Circles, mathematical expressions, and words on Translating Expressions with Exponents.
- Next, try the Matching Exponents activity, connecting Circles with their appropriate mathematical expressions.
- Finally, practice Evaluating Expressions with Exponents using computation. There are no Circles on this worksheet - but drawing them might help if you get stuck.


=== Synthesize

- Is @math{2 + (6^2)} equivalent to @math{2 + 6^2}? Why or why not?
** _Yes, these expressions are equivalent. Applying an exponent is a function separate from addition, regardless of whether we put it in parentheses or not._
- Is @math{2 + 6^2} equivalent to @math{(2 + 6)^2}? Why or why not?
** _No, these expressions are not equivalent. For the first expression, we apply the exponent and then multiply. For the second expression, we multiply and then apply the exponent._


== Expressions with Exponents and Negatives @duration{20 minutes}

=== Overview

THIS LESSON IS ALIGNED TO SEVENTH GRADE STANDARDS - MAYBE NOT APPROPRIATE FOR THIS SEQUENCE?

=== Launch

[.lesson-instruction]
--
- Analyze these expressions: @math{-3^2}, @math{(-3)^2}, and @math{-(3^2)}
- Are any of these three expressions equivalent? How do you know? Draw Circles to help you.
** _We know that in an expression with no grouping symbols, we evaluate the exponent first - before the negation. Therefore, the first and third expression are equivalent; they both evaluate to @math{-9}. The second expression evaluates to @math{9}. See Circles below._
[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===
|@math{-3^2} or @math{-(3^2)}				| @math{(-3)^2}
|@show{(coe  '(negate (num-expt 3 2)))}		| @show{(coe  '(num-expt (negate 3) 2) )}
|===
--

=== Investigate

[.lesson-instruction]
- First, complete the first column by drawing Circles of Evaluation to represent the expressions with exponents and negations.
- Next, complete the final column by evaluating the Circles.

=== Synthesize

- If an expression has no grouping symbols, which do we apply first: `num-expt` or
`negate`?
** _First, we apply `num-expt`, then `negate`._
