= Custom Scatter Plot - Explore

Make sure you have @starter-file{custom-scatter-plot} open on your computer. Save a copy, and click *Run*.

`image-scatter-plot(animals-table, "pounds", "weeks", species-tag)`

__Let's think about this expression before we evaluate it...__

@n What is the data type of `species-tag`? @fitb{}{@ifsoln{_a function!_}}

In the program, define a row called `sasha`, which is the first row in the table (index 0).

Then define a row called `snuffles`, which is the second row in the table (index 1).

@n Click *Run*. What happens when you evaluate `species-tag(sasha)`?

@fitb{}{}

@n Take a moment to think about what you expect the `image-scatter-plot` expression above to produce. Then click "Run" and type the expression into the Interactions Area to test it out.  Describe the image you see.

@fitb{}{@ifsoln{_Each of the points on the plot is labeled with its species name in red._}}

@fitb{}{}

@n What can you learn from this new display that you could not learn from the original image?

@fitb{}{@ifsoln{_All of the heavy animals are dogs and the other species weigh under 10 pounds._}}

@n What ideas do you have for how else we could draw the dots in a scatter plot of the animals, so that it would be even more useful?

@fitb{}{@ifsoln{_Sample responses: Use more than one color? Use different symbols?_}}

@fitb{}{}

@n Find the other two "Helper Functions" in the file (`legs-tag` and `age-tag`). How are their definitions similar to `species-tag`?

@fitb{}{@ifsoln{_They also consume a row and look up a specific variable._}}

@n How are their definitions _different_ from `species-tag`?

@fitb{}{@ifsoln{_The lookup information is used as a size rather than converted to a text image._}}

@n Make a custom scatter plot using `legs-tag`. Then make another using `age-tag`. What is most interesting to you about the plots you just made?

@fitb{}{@ifsoln{_Student responses will vary!_}}

@fitb{}{}

@n Suppose we wanted to make a custom scatter plot where each point is labeled with the _name_ of the animal. What would we need to define, to use in our custom scatter plot expression?

@fitb{}{@ifsoln{_a_ `name-tag` _helper function._}}


@n Make the new custom scatter plot described above. Write the definition of your helper function, and the custom scatter plot expression here:

@fitb{}{@ifsoln{ `fun name-tag(r): text(r["name"], 15, "red") end`}}

@fitb{}{@ifsoln{ `image-scatter-plot(animals-table, "pounds", "weeks", name-tag)`}}

