= Defining Row-Consuming Functions
++++
<style>
/* Hide DR elements we want hidden */
#content .recipe_purpose_statement, table.recipe_title {
 	display: none !important;
}
/* Make the instructions more prominent, to take the place of headers */
#content .recipe_instructions * {
	font-style: italic;
    font-size: 1rem;
    font-weight: bold;
    background: lightgray;
}
.pyret .recipe_name {
    text-align: center;
}

</style>
++++

@n How could we define `animalA` to be the first row in the table?

@fitb{}{@ifsoln{`animalA = animals-table.row-n(0)`}}

@n How could we look up the `species` column from `animalA`? @fitb{}{@ifsoln{`animalA["species"]`}}

@n How could we use the `text` function to show the species of `animalA` in red, 15px letters?

@fitb{}{@ifsoln{`text(animalA["species"], 15, "red")`}}

But why bother writing this out over and over for each animal, when we can define a function to do it for us?

== Species Tag

@design-recipe-exercise{ "species-tag"
"Define a function called `species-tag`, which takes in a row from the Animals Table and draws its name in red, 15px letters. __HINT: Use `animalA` and `animalB` as inputs in your examples!__"
#:assess-design-recipe #f
#:headless? #t
#:show-funname-contract? #t
#:domain-list '(Row)
#:show-domains? #f
#:range "Image"
#:show-range? #f
#:purpose "Consumes an animal Row, and draws the species of the animal in red, 15px letters."
#:show-purpose? #f
#:num-examples 2
#:example-list '(("animalA" "text(animalA[\"species\"], 15, \"red\")")
                 ("animalB" "text(animalB[\"species\"], 15, \"red\")"))
#:show-examples #f
#:param-list '(r)
#:show-funname-defn? #t
#:show-params? #f
#:body "text(r[\"species\"], 15, \"red\")"
#:show-body? #f
#:grid-lines? #f
}
