#!/bin/bash

SEMESTER=fall
YEAR=2021

DEPLOY_DIR=/gpfs/main/authen/sys/web/cs/web/sites/bootstrapworld.org/materials/$SEMESTER$YEAR

echo start...

cd
cd tmp;
echo starting rm deployables
rm -fr deployables;
echo finished rm deployables
echo starting untar deployables
tar jxf deployables.tar.bz2;
echo finished untar deployables
echo starting chgrp
chgrp -R cs-plt deployables;
echo finished chgrp
echo starting chmod
find deployables -type d|xargs chmod g+rwx,o+rx;
find deployables -type f|xargs chmod g+rw,o+r;
echo finished chmod
cp -pr deployables/* $DEPLOY_DIR
