#! /usr/bin/env bash
course=
nomake=
pd=
otheropts="--nomake"
while test $# -ne 0; do
  opt="$1"
  if test "$opt" = --nomake; then
    nomake=1; shift
  elif test "$opt" = --skipnode; then
    otheropts="$otheropts $opt"; shift
  elif test "$opt" = --pd; then
    pd=1; otheropts="$otheropts --pd"; shift
  elif test "$opt" = --rebuild -o "$opt" = -f; then
    otheropts="$otheropts $opt"; shift
  else
    course="$opt"; shift
    course=${course%/}
    course=${course##*/}
  fi
done
if test -z "nomake"; then
  make
fi
function build_slide() {
  local lesson=$1
  echo calling build-slide $otheropts $lesson
  ./build-slide $otheropts $lesson
}
if test -n "$pd"; then
  seen_lessons=""
  pd_lessons=()
  while IFS= read -r adoc; do
    grep -qF '@pd-slide{' "$adoc" || continue
    lesson=${adoc#*/lessons/}
    lesson=${lesson%%/*}
    if ! echo "$seen_lessons" | grep -qx "$lesson"; then
      seen_lessons="$seen_lessons"$'\n'"$lesson"
      pd_lessons+=("$lesson")
    fi
  done < <(find distribution/en-us/lessons -name index.adoc)
  echo "Found ${#pd_lessons[@]} lesson(s) with PD slides:"
  for lesson in "${pd_lessons[@]}"; do
    echo "  $lesson"
  done
  for lesson in "${pd_lessons[@]}"; do
    build_slide "$lesson"
  done
elif test -z "$course"; then
  for lesson in distribution/en-us/lessons/*; do
    build_slide $lesson
  done
else
  seen_lessons=""
  IFS=',' read -ra courses <<< "$course"
  for c in "${courses[@]}"; do
    courselessonlist=distribution/en-us/courses/$c/.cached/.workbook-lessons.rkt.kp
    if test ! -f "$courselessonlist"; then
      echo "Warning: course '$c' not found, skipping"
      continue
    fi
    for lesson in $(sed 's/"//g' $courselessonlist); do
      if ! echo $lesson | grep -q "[()]"; then
        if ! echo "$seen_lessons" | grep -qx "$lesson"; then
          seen_lessons="$seen_lessons"$'\n'"$lesson"
          build_slide $lesson
        fi
      fi
    done
  done
fi
