#!/bin/bash

export SEASON=fall2023

bootstraproot=https://bootstrapworld.org/materials/$SEASON

SED=sed

if which gsed|grep -q .; then
  SED=gsed
fi

regenid=
experimental=
proglang=
lsn=

if test $# -eq 0; then
  echo build-slide needs a lesson argument
  exit
else
  while test $# -ne 0; do
    if test "$1" = -f; then
      regenid=1; shift
    elif test "$1" = -z; then
      experimental=1; regenid=1; shift
    elif test "$1" = --proglang; then
      shift; proglang="$1"; shift
    else
      lsn="$1"; shift
    fi
  done
fi

if test "$proglang" = wescheme; then
  lsn=$(echo $lsn|$SED -e 's/-wescheme$//')
  lsn=$lsn-wescheme
elif test "$proglang" = codap; then
  lsn=$(echo $lsn|$SED -e 's/-codap$//')
  lsn=$lsn-codap
fi

if echo $lsn|grep -q "\-wescheme$"; then
  proglang=wescheme
elif echo $lsn|grep -q "\-codap$"; then
  proglang=codap
fi

if test -z "$proglang"; then
  proglang=pyret
fi

export topdir=$(pwd)

templateSlidesId=1vFGtTzhTlc1p8VJECRucj5DO83skm4wMI1BU3QbHE5k
parentFolderId=1AP4vk0XwLSl9cU8HIHjmSTFK7dG3CrGn

export PROGLANG=$proglang

make

if test ! -d distribution; then
  echo WARNING: Did not find any built pathways
  exit
else
  cd distribution
fi

for natlang in *; do
  test -d $natlang || continue
  export PROGDIR=$topdir/distribution/.prog-$natlang
  if test ! -d $natlang/lessons; then
    echo Missing lessons diry in distribution -- did you call build-pathway\?
    continue
  fi
  if test ! -d  $natlang/lessons/$lsn; then
    echo Lesson $natlang/lessons/$lsn not found in distribution
    continue
  fi
  cd $natlang/lessons/$lsn
  export BOOTSTRAPPREFIX="$bootstraproot/$natlang"
  export LESSON="$lsn"
  # echo Doing $LESSON
  repoLESSON=$(cat .repodir.txt.kp)

  # echo repoLESSON is $repoLESSON

  idfile=slides-$PROGLANG.id

  if test ! $regenid; then
    if test -f "$idfile"; then
      read -p "This will REPLACE A PUBLIC FILE! Are you *sure* you want to rebuild slides for $lsn? (If not, use build-slide -f to make a new file id.) [yn] " goahead
      if test "$goahead" != y; then
        exit
      fi
    fi
  fi

  slidesmd=slides.md
  slidesmkd=slides.mkd

  if test $experimental; then
    slidesmd=zlides.md
    slidesmkd=zlides.mkd
  fi

  if test $regenid; then
    rm -f $idfile
  fi
  if test -f $slidesmd; then
    $topdir/lib/slides-preproc.rkt $slidesmd
    if test -f $slidesmkd; then
      title=$(grep '^# ' $slidesmkd|$SED -e 1q|$SED -e 's/^#  *//')
      title="AUTO-GEN:$title"
      if test -s "$idfile"; then
        id=$(cat "$idfile"|$SED -e 1q)
        # echo md2gslides with id $id
        node $topdir/node_modules/md2googleslides/bin/md2gslides.js $slidesmkd -a "$id" -e -n -t "$title" -c $templateSlidesId -p $parentFolderId --use-fileio > .tmp.txt
        # node $topdir/node_modules/md2googleslides/bin/md2gslides.js $slidesmkd -a "$id" -e -n -t "$title" --use-fileio > .tmp.txt 2>.tmpe.txt
        if grep -q 'Unable to generate slides' .tmp.txt; then
          echo Slides failed for $LESSON/$slidesmkd
          if grep -q 'must be less than the endIndex' .tmp.txt; then
            echo You likely have a slide with text preceding table
          fi
          cat .tmp.txt
        fi
        # rm .tmp.txt
      else
        # echo md2gslides without id
        $topdir/node_modules/md2googleslides/bin/md2gslides.js $slidesmkd -n -t "$title" -c $templateSlidesId -p $parentFolderId --use-fileio > .tmp.txt
        if grep -q 'Unable to generate slides' .tmp.txt; then
          echo Slides failed for $LESSON/$slidesmkd
          if grep -q 'must be less than the endIndex' .tmp.txt; then
            echo You likely have a slide with text preceding table
          fi
          cat .tmp.txt
        else
          grep 'View your presentation at' .tmp.txt | $SED -e 's/.*docs\.google\.com\/presentation\/d\///' > "$idfile"
          cp "$idfile" $topdir/$repoLESSON/
          echo Remember to push $repoLESSON/$idfile to Git repo
        fi
      fi
      if test -f "$idfile"; then
        cat "$idfile"|$SED -e 1q|$SED -e 's/^/<a target="_blank" href="https:\/\/docs.google.com\/presentation\/d\//' > slides-$PROGLANG.html
        timestamp=$(date +%c)
        $SED -i -e 's/$/">Google Slides generated INSERTTIMESTAMP<\/a>/' slides-$PROGLANG.html
        $SED -i -e "s/INSERTTIMESTAMP/$timestamp/" slides-$PROGLANG.html
      fi
    else
      echo WARNING: $slidesmd failed preprocessing
    fi
  else
    echo WARNING: Lesson \'$LESSON\' doesn\'t have $slidesmd
  fi
  cd ../../..
done
