#!/bin/bash
# build-pathway
# build script for curriculum
# Type build-pathway --help for help.

export BOOK=
export DEBUG=
export FORCE=
export SUPERFORCE=
export LANGUAGE=en-us
export LINT=
export NOPDF=
export PROGLANG=
export TOPDIR=$(pwd)
export EXPANDEDWARNINGS=

#SEMESTER=spring
#MONTH=$(date +%m)
#test "$MONTH" -gt 7 && SEMESTER=fall
#export SEMESTER_YEAR=$SEMESTER$(date +%Y)

eval $(grep '^SEMESTER=' ./deploy-to-brown)
eval $(grep '^YEAR=' ./deploy-to-brown)
export SEMESTER YEAR
SEMESTER_YEAR=$SEMESTER$YEAR
#JAVASCRIPTDELAY="--javascript-delay 5000"
#JAVASCRIPTDELAY="--window-status ready_to_print"
#JAVASCRIPTDELAY="--javascript-delay 100000 --window-status ready_to_print"
JAVASCRIPTDELAY="--run-script 'MathJax.Hub.Queue(function(){window.status=\"ready_to_print\"})' --window-status ready_to_print"

ARGS=
HELP=
LASTMOD=2021-10-18 # last modified
PDFMARGIN=0mm
SED=sed
MDV=md5sum
VERSION=
NOPARALLEL=

if test -f ./.build-pathway.rc; then
  . ./.build-pathway.rc
fi

while test $# -ne 0; do
  arg=$1; shift
  if test "$arg" = --add-exercises -o "$arg" = -e; then
    :
  elif test "$arg" = --book -o "$arg" = -b; then
    BOOK=1
  elif test "$arg" = --debug -o "$arg" = -d; then
    DEBUG=1
  elif test "$arg" = --expanded-warnings -o "$arg" = -w; then
    EXPANDEDWARNINGS=1
  elif test "$arg" = --force -o "$arg" = -f; then
    FORCE=1
  elif test "$arg" = --help -o "$arg" = -h; then
    HELP=1
  elif test "$arg" = --language; then
    LANGUAGE=$1; shift
  elif test "$arg" = --lint -o "$arg" = -l -o "$arg" = --verify-links; then
    LINT=1
  elif test "$arg" = --no-pdf -o "$arg" = --nopdf -o "$arg" = -n; then
    NOPDF=1
  elif test "$arg" = --no-parallel -o "$arg" = --noparallel; then
    NOPARALLEL=1
  elif test "$arg" = --proglang; then
    PROGLANG=$1; shift
  elif test "$arg" = --superforce -o "$arg" = --super-force -o "$arg" = -F; then
    SUPERFORCE=1
  elif test "$arg" = --version -o "$arg" = -v; then
    VERSION=1
    #
    # some common combos
  elif test "$arg" = -df; then
    DEBUG=1; FORCE=1
  elif test "$arg" = -dfl; then
    DEBUG=1; FORCE=1; LINT=1
  elif test "$arg" = -dfln; then
    DEBUG=1; FORCE=1; LINT=1; NOPDF=1
  elif test "$arg" = -dfn; then
    DEBUG=1; FORCE=1; NOPDF=1
  elif test "$arg" = -dn; then
    DEBUG=1; NOPDF=1
  else
    arg1=${arg#--}
    if test "$arg1" != "$arg"; then
      echo Mistyped option \'$arg\'?
    fi
    ARGS="$ARGS $arg"
  fi
done

#echo ARGS is $ARGS

test $BOOK && NOPDF= || NOPDF=1

test $SUPERFORCE && FORCE=1

TMPTMP=$(mktemp); rm -f $TMPTMP
TMPAFX=$(basename $TMPTMP)

export ABYSS=page-not-found

WKH2P_PFX=.wkh2p-tmp

export NUMCORES=$(getconf _NPROCESSORS_ONLN)

export WORKBOOKPAGE=
export DATASHEETPAGE=
export ALLPATHWAYLESSONS=

function displayhelp() {
  echo Usage: build-pathway [--language L] [--proglang P] [--debug] [--force] [--no-pdf] [--lint] [--help] [--version] pathway ...
  echo
  echo Builds a document tree for the given pathway argument\(s\)
  echo under the \'distribution\' directory. If no pathway arg supplied,
  echo builds for all pathways in the \'pathways\' directory.
  echo
  echo Options:
  echo "  " --language L: Build doctree for natural language L. Default: en-us
  echo "  " --proglang P: Build doctree for programming language P.
  echo "                " P is one of wescheme, pyret.
  echo "                " An appropriate default is used depending on the pathway.
  echo "  " --debug: Keep around for inspection/debugging various temp files
  echo "           " in the \'distribution\' directory.
  echo "  " --force, -f: Regenerate doctree from scratch without relying on previous runs.
  echo "  " --superforce, -F: Regenerate doctree from scratch after updating code.
  echo "  " --book, -b: Generate workbook PDFs.
  echo "  " --no-pdf: Don\'t generate PDF files. This is to speed things up
  echo "            " during debugging when PDF output isn\'t necessary.
  echo "  " --lint: \(1\) Ensure the summary tables in lesson plans have the required rows.
  echo "          " \(2\) Verify all the links used in the doctree.
  echo "          " in the pathway doctree\'s top directory.
  echo "  " --help: Display this help and exit.
  echo "  " --version: Display build-way version and exit.
  echo
  echo Order of arguments/options doesn\'t matter.
  exit
}

if test $HELP; then displayhelp; fi

if test $VERSION; then
  echo build-pathway version $LASTMOD
  exit
fi

if which gsed | grep -q .; then
  SED=gsed
fi

if which md5 | grep -q .; then
  MDV=md5
fi

if ! which curl | grep -q .; then
  echo
  echo WARNING: Missing \'curl\' tool; can\'t do --lint
  LINT=
fi

if ! which wkhtmltopdf|grep -q .; then
  echo
  echo WARNING: Missing wkhtmltopdf: PDF workbooks can\t be created
fi

NOARGSGIVEN=

if test "$ARGS" = ""; then
  NOARGSGIVEN=1
  ARGS=$(ls -d pathways/*)
fi

#echo ARGS is $ARGS

echo '== Generated Documentation' > index.adoc
echo >> index.adoc
echo link:README.html[Authoring Guide] >> index.adoc
echo >> index.adoc
echo https://github.com/bootstrapworld/curriculum[\`curriculum\` Repo] >> index.adoc

mkdir -p distribution/$LANGUAGE/courses

echo '== Generated Documentation' > distribution/index.adoc

if test $SUPERFORCE; then
  rm -fr prog distribution/$LANGUAGE/lib distribution/$LANGUAGE/extlib
fi

mkdir -p prog
mkdir -p distribution/$LANGUAGE/lib
mkdir -p distribution/$LANGUAGE/extlib

function checkmd5nochange() {
  local distDir=$1
  local repoDir=$2
  #echo doing checkmd5nochange $distDir $repoDir
  test -d $distDir/.cached || mkdir -p $distDir/.cached
  local savef=$distDir/.cached/.checksum.md5txt
  local currdir=$(pwd)
  cd $repoDir
  newchecksum=$(find . -type f -exec $MDV {} \; | $MDV | cut -d " " -f 1)
  cd $currdir
  if test -f $savef; then
    savedchecksum=$(cat $savef)
    if test "$newchecksum" = "$savedchecksum"; then
      return 0
    else
      #echo saving I $savef
      echo $newchecksum > $savef
      return 1
    fi
  else
    #echo saving II $savef
    echo $newchecksum > $savef
    return 1
  fi
}

export PROGDIR=$TOPDIR/prog

if ! checkmd5nochange $PROGDIR $TOPDIR/shared/langs; then
  # if $LANGUAGE != en-us, and
  # shared/langs/$LANGUAGE isn't sufficiently populated,
  # we'll put in the en-us files first and shadow them later
  #
  cp -pr $TOPDIR/shared/langs/en-us/* $PROGDIR
  cp -p $TOPDIR/shared/langs/en-us/*.css distribution/$LANGUAGE/lib
  #
  if test $LANGUAGE != en-us -a -d $TOPDIR/shared/langs/$LANGUAGE; then
    cp -pr $TOPDIR/shared/langs/$LANGUAGE/* $PROGDIR
  fi
  cp -pr $PROGDIR/docroot/* distribution/$LANGUAGE
  mkdir -p distribution/$LANGUAGE/lib/Badges
  mkdir -p distribution/$LANGUAGE/lib/images
  cp -pr $PROGDIR/Badges/* distribution/$LANGUAGE/lib/Badges
  cp -pr $PROGDIR/images/* distribution/$LANGUAGE/lib/images
  # TODO: may need to revisit for unforced LANGUAGE != en-us
fi

# escaped characters are: (1) go to beginning of line, (2) erase to
# end of line, and (3) truncate the argument to terminal width
function overwrite() {
  if test  $EXPANDEDWARNINGS; then
    echo $@
  else
    echo $'\e[1A\e[K\033[?7l'$@
  fi
}

if test ! -d distribution/$LANGUAGE/extlib/MathJax*; then
  cp -pr $TOPDIR/extlib/MathJax* distribution/$LANGUAGE/extlib
fi

if ! checkmd5nochange distribution/$LANGUAGE/lib $TOPDIR/lib; then
  overwrite copying distribution/$LANGUAGE/lib
  cp -p $TOPDIR/shared/langs/en-us/*.css distribution/$LANGUAGE/lib
  cp -p $TOPDIR/lib/*.rkt $TOPDIR/lib/ano* $TOPDIR/lib/.hta* $PROGDIR
  cp -p $TOPDIR/lib/*.png $TOPDIR/lib/*.css $TOPDIR/lib/*.js distribution/$LANGUAGE/lib
fi

function insertbodyid() {
  local f=$1
  #echo doing insertbodyid $f
  $SED -i \
    -e 's/<body[^>]*>/\0\n<div id="body">/' \
    -e 's/<\/body>/<\/div>\n\0/' \
    $f
}

function insertgdrivesave() {

  local f=$1
  #echo doing insertgdrivesave $f in $(pwd)
  local f_head=${f%.*}
  local f_ext=${f##*.}
  local other_f=$f_head-gdrive-import.html
  local pageTitle=
  if test -f $f_head.adoc; then
    pageTitle=$(grep '^= ' $f_head.adoc|head -n 1|$SED -e 's/^= *//' -e 's/  *$//')
  fi

  if test ! "$pageTitle"; then
    pageTitle=$f_head
  fi

  pageTitle=$(echo $pageTitle|$SED -e 's/[“”]/\\\\"/g')
  pageTitle=$(echo $pageTitle|$SED -e 's/\//\\\//g')

  #echo pageTitle of $f_head.adoc is $pageTitle
  #FIXME: pathname should be corrected, again
  local hrefPrefix=https://www.bootstrapworld.org/materials/$SEMESTER_YEAR/$LANGUAGE/courses/$TGTPATHWAY/$LESSONSUBDIR

  hrefPrefix=$(echo $hrefPrefix|$SED -e 's/\/$//'|$SED -e 's/\//\\\//g')

  local TMPFILE=$f_head.$TMPAFX

  #echo TMPFILE is $TMPFILE

  cat > $TMPFILE-1.txt <<EOF
  <script>
  window.status = window.status || 'ready_to_print';
  window.___gcfg = {
  parsetags: 'explicit'
  };
  </script>
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <script>function renderSaveToDrive() {
    var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
    gapi.savetodrive.render('savetodrive-div', {
    src:%INSERTGDRIVEURL,
    filename:"%INSERTGDRIVELESSONTITLE",
    sitename:"Bootstrap, Brown University"
  });
  if(isSafari){
    var warning = document.createElement("div");
    warning.id = "safariWarning";
    warning.innerHTML = "You appear to be using Safari, which interferes with Google's Save-to-Drive button. You can fix it by going to Preferences, clicking 'Privacy', and making sure that 'Prevent cross-site tracking' is <b>not</b> checked."
    var button = document.getElementById("savetodrive-div");
    button.parentNode.insertBefore(warning, warning.nextSibling);
  }
}
</script>
EOF
  cat > $TMPFILE-2.txt <<EOF
  <div id="savetodrive-div"></div>

EOF
  $SED -i \
    -e 's/^\(<body  *[^>]*\)>/\1 onload="renderSaveToDrive()">/' \
    -e 's/<\/head>/%INSERTGDRIVESAVE1\n\0/' \
    -e 's/<\/h1>.*/\0\n%INSERTGDRIVESAVE2/' \
    -e '/^<div id="body"/ s/id="body"/\0 onload="renderSaveToDrive()"/' \
    $f

  if test $WORKBOOKPAGE; then
    $SED -i \
      -e 's/^<body class="/\0workbookpage /' \
      $f
  elif test $DATASHEETPAGE; then
    $SED -i \
      -e 's/^<body class="/\0datasheetpage /' \
      $f
  fi

  if ! grep -q %INSERTGDRIVESAVE2 $f; then
    $SED -i \
      -e 's/<div id="header">/\0\n%INSERTGDRIVESAVE2/' \
      $f
  fi

  $SED -i \
    -e '/%INSERTGDRIVESAVE1/r '$TMPFILE-1.txt \
    -e '/%INSERTGDRIVESAVE2/r '$TMPFILE-2.txt \
    -e 's/%INSERTGDRIVESAVE[12]//' \
    $f

  #echo deleting $TMPFILE 12 .txt
  rm -f $TMPFILE-[12].txt

  $SED -i \
    -e 's/%INSERTGDRIVELESSONTITLE/'"$pageTitle"'/' \
    $f

  cp -p $f $other_f

  $SED -i \
    -e "s/%INSERTGDRIVEURL/(window.location.href.match(\/\\\\\/$\/)?(window.location.href+'index-gdrive-import.html'):(window.location.href.replace(\/([^\\\\\/]+)\\\\.([^.\\\\\/]+)$\/, '\$1-gdrive-import.html')))/" \
    $f

  $SED -i \
    -e 's/%INSERTGDRIVEURL/window.location.href/' \
    $other_f

  modifygdrivepage $other_f $f
}

function adjustgdrivecolgroup() {
  local f=$1

  local CTEMP=$(mktemp); rm -f $CTEMP

  local CTEMPFILE=$(basename $CTEMP)-cols.txt

  grep '^<col style.*> *$' $f > $CTEMPFILE

  local num=$(wc -l $CTEMPFILE|$SED -e 's/^ *\([^ ]*\).*/\1/')

  if test $num -eq 0; then
    rm -f $CTEMPFILE
    return
  fi

  $SED -i \
    -e 's/^<col //' \
    -e 's/> *$//' \
    $CTEMPFILE

  local i=1

  local cline
  local flnum

  while test $i -le $num; do
    cline=$($SED -ne "$i p" $CTEMPFILE)

    flnum=$(grep -n '^<th ' $f|$SED -e 1q|$SED -e 's/^\([^:]*\).*/\1/')

    $SED -i \
      -e "$flnum s/^<th /<th%GDRIVE $cline /" \
      $f

    i=$(expr $i + 1)

  done

  rm -f $CTEMPFILE

  $SED -i \
    -e 's/^<th%GDRIVE /<th /' \
    $f

}

function modifygdrivepage() {
  local f=$1
  local h=$2

  $SED -i \
    -e '/include virtual=".menubar.ssi"/d' \
    -e 's/^<p>Relevant Standards<select.*<\/select><\/p> *$/<p>Standards<\/p>/' \
    -e '/^<p><em>Select one or more standards from the menu on the left.*<\/p> *$/d' \
    -e 's/\(class="paragraph \)alignedStandardsIntro/\1/' \
    -e 's/\(class="dlist \)alignedStandards /\1/' \
    -e 's/href=\("\(https\|http\):\/\/\)/href%GDRIVEEXTERNALHREF=\1/g' \
    -e 's/<div/<span/g' \
    -e 's/<\/div>/<\/span>/g' \
    -e 's/<dt class="hdlist1">/\0<br\/>/g' \
    -e 's/<span class="sect1 lesson-section-1">/\0<hr\/>/g' \
    -e 's/<span class="openblock acknowledgment">/\0<hr\/>/g' \
    -e 's/<h2.*>\(.*\)<span class="duration">\(.*\)<\/span><\/h2>/<table class="grid-none frame-none section-heading"><tr><td width="65%">\1<\/td><td width="35%">\2<\/td><\/tr><\/table>/g' \
    -e 's/<tt\(.*\)>\(.*\)<\/tt>/<span\1>\2<\/span>/g' \
    $f
  $SED -i \
    -e 's/^\(.*\)<span\(  *class="paragraph lesson-point"\)/%GDRIVESPANDIV\1<div\2/g' \
    $f
  $SED -i \
    -e '/^%GDRIVESPANDIV/,/^<\/span>/ s/^<\/span>/<\/div>/' \
    -e 's/^%GDRIVESPANDIV//' \
    $f
  $SED -i \
    -e 's/href="/\0'$hrefPrefix'\//g' \
    $f
  $SED -i \
    -e 's/%GDRIVEEXTERNALHREF//g' \
    -e '/^ *<link rel="stylesheet".*\.css/d' \
    -e '/^ *<script .*\(codemirror\|runmode\|scheme2\|pyret-mode\|bootstraplesson\)/d' \
    -e '/<span class="tooltiptext">.*<\/span>/d' \
    $f
  echo "<style>" > $TMPFILE.css
  #echo doing gdrive-import: PWD is $(pwd)
  #echo cat $DISTROOTDIR/lib/gdrive-import.css
  cat lib/gdrive-import.css >> $TMPFILE.css
  echo "</style>" >> $TMPFILE.css
  $SED -i \
    -e '/<\/title>/r '$TMPFILE.css \
    $f

  $SED -i \
    -e 's/<span class="begin-ignore-for-gdrive">/<!--\0/g' \
    -e 's/<span class="end-ignore-for-gdrive"><\/span>/\0-->/g' \
    $f

  $SED -i \
    -e '/studentAnswer/ s/&#x5f;/\0\0/g' \
    $f

  rm -f $TMPFILE.css

  adjustgdrivecolgroup $f

  $SED -i \
    -e 's/<span class="\(begin\|end\)-ignore-for-gdrive"><\/span>//g' \
    $h

}

function removelogos() {
  local f=$1
  $SED -i \
    -e '/^<h2 .*<img src="bootstraplogo.png"/d' \
    $f
}

function removecodetags() {
  local f=$1
  $SED -i \
    -e 's/<code>\(<tt\)/\1/g' \
    -e 's/\(<\/tt>\)<\/code>/\1/g' \
    $f
}

function cleanuptitle() {
  local f=$1
  $SED -i \
    -e '/^<title>/ s/<\/*span[^>]*>//g' \
    $f
}

function cleanupduration() {
  # cleans up a long-winded autogenerated h2 id
  local f=$1
  $SED -i \
    -e '/^<h2 id/ s/\(begin\|end\)curriculumspan/_/g' \
    -e '/^<h2 id/ s/curriculumspan_class//g' \
    $f
}

function insertsectionselfie() {
  local f=$1
  $SED -i \
    -e '/^<h2 id=/s/^<h2 id="\([^>]*\)>\(.*\)<\/h2>/<h2 id="\1><span class="section-link"><a href="#\1><span class="section-link-symbol">\&#128279;<\/span><\/a><\/span>\2<\/h2>/' \
    $f
}

function lintlesson() {
  local f=$1

  test $LINT || return

  for g in Prerequisites 'Lesson Goals' Materials Preparation 'Relevant Standards'; do
    if ! grep -q "^<p>$g\>" $f; then
      echo
      echo WARNING: Lesson $LESSONPLAN missing summary-table row for \"$g\"
    fi
  done

}

function addanalytics() {
  local f=$1
  $SED -i \
    -e '/^<body/r $TOPDIR/lib/analytics.txt' \
    $f
}

function bumpcsspathdir() {
  local f=$1
  local localDISTROOTDIR=$2

  local f_head=${f%.*}
  local TMPFILE=$f_head.$TMPAFX

  cat > $TMPFILE-3.txt <<EOF
  <link rel="stylesheet" href="${localDISTROOTDIR}lib/curriculum.css" />
EOF
  $SED -i \
    -e '/^<link.*curriculum\.css/s/<link\(.*\)>/%INSERTLIBCURRICULUMCSS<link DISCARD \1>/' \
    -e '/%INSERTLIBCURRICULUMCSS/r '$TMPFILE-3.txt \
    -e 's/%INSERTLIBCURRICULUMCSS//' \
    -e 's/<link DISCARD .*curriculum\.css.*>//' \
    $f

  #echo deleting $TMPFILE-3.txt
  rm -f $TMPFILE-3.txt
}

function resolveabbrevs() {
  local f=$1
  local localDISTROOTDIR=$2
  #echo doing resolveabbrevs $f $localDISTROOTDIR
  local mathjaxneeded=
  local codemirrorneeded=
  if grep -q %CURRICULUMSCRIPT $f; then
    mathjaxneeded=1
  fi
  CODELANG=pyret
  if test "$PROGLANG" = wescheme; then
    CODELANG=racket
  fi
  $SED -i \
    -e 's/<pre>/<pre><code class="'$CODELANG'">/g' \
    -e 's/<\/pre>/<\/code><\/pre>/g' \
    -e 's/<code>/<code class="'$CODELANG'">/g' \
    $f
  if grep -q 'class=\"\(pyret\|racket\)\"' $f || grep -q 'class=\"circleevalsexp\"' $f; then
    codemirrorneeded=1
  fi
  $SED -i \
    -e 's/%PYRETKEYWORD%\([^%]*\)%END%/<span class="pyretkeyword">\1<\/span>/g' \
    \
    -e 's/%CURRICULUMCOMMA%/,/g' \
    \
    -e 's/<p>\(%CURRICULUMCOMMENT%\)/\1/' \
    -e 's/\(%ENDCURRICULUMCOMMENT%\)<.p>/\1/' \
    -e 's/%CURRICULUMCOMMENT%/<!-- /' \
    -e 's/%ENDCURRICULUMCOMMENT%/\n-->/' \
    \
    -e 's/%CURRICULUMSCRIPT%/<script type="math\/tex"/g' \
    -e 's/%BEGINCURRICULUMSCRIPT%/>/g' \
    -e 's/%ENDCURRICULUMSCRIPT%/<\/script>/g' \
    \
    -e 's/%CURRICULUMPMMATH%/<!--CURRICULUMPMMATH<tt>/g' \
    -e 's/%ENDCURRICULUMPMMATH%/<\/tt>CURRICULUMPMMATH-->/g' \
    \
    -e 's/%CURRICULUM\([^%]*\)%/<\1/g' \
    -e 's/%BEGINCURRICULUM\([^%]*\)%/>/g' \
    -e 's/%ENDCURRICULUM\([^%]*\)%/<\/\1>/g' \
    \
    -e 's/&#8656;/\&lt;=/g' \
    -e 's/&#8594;/-\&gt;/g' \
    \
    -e 's/^\(<div id="preamble\)">/\1_disabled" class="lessonSummary">/' \
    $f
  $SED -i \
    -e '/%SIDEBARSECTION%/,/%ENDSIDEBARSECTION%/s/\(<\/div>\)<\/p>/\1/' \
    $f
  $SED -i \
    -e '/%SIDEBARSECTION%/,/%ENDSIDEBARSECTION%/s/<p>\(<div\)/\1/' \
    $f
  $SED -i \
    -e 's/%SIDEBARSECTION%/--><\/div><div class="sidebar"><div class="sidebartitle">Lesson Pathway, Standards and Practices<\/div><div class="paragraph"><!--/' \
    $f
  $SED -i \
    -e 's/%SIDEBARLESSONSCHECKBOX%/<br\/><input class="sidebarinput" type="checkbox" onchange="toggleNonPrereqDisplay()">\Prerequisites only (★) /' \
    $f
  $SED -i \
    -e 's/%ENDSIDEBARSECTION%/--><\/div><!--/' \
    $f
  if test "$mathjaxneeded"; then
    cat > .cached/.mathjax.txt <<EOF
      <script src="${PATHWAYROOTDIR}../../extlib/MathJax-2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML%2Clocal%2Fmathjaxlocal.js"></script>
      <script>window.status = "not_ready_to_print";</script>
EOF
    $SED -i \
      -e '/^ *<link.*curriculum\.css/s/^/%INSERTMATHJAX\0/' \
      -e '/%INSERTMATHJAX/r .cached/.mathjax.txt' \
      -e 's/%INSERTMATHJAX//' \
      $f
  fi
  if test "$codemirrorneeded"; then
    #FIXME: is codemirror.css needed?
    cat > .cached/.codemirror.txt <<EOF
    <link rel="stylesheet" href="${localDISTROOTDIR}lib/codemirror.css" />
    <script src="${localDISTROOTDIR}lib/codemirror.js"></script>
    <script src="${localDISTROOTDIR}lib/runmode.js"></script>
    <script src="${localDISTROOTDIR}lib/scheme2.js"></script>
    <script src="${localDISTROOTDIR}lib/pyret-mode.js"></script>
    <script src="${localDISTROOTDIR}lib/bootstraplesson.js"></script>
    <script src="${localDISTROOTDIR}dependency-graph.js"></script>
    <script src="${localDISTROOTDIR}pathway-tocs.js"></script>
    <script>var pathway='${PATHWAY}';</script>
EOF
$SED -i \
  -e '/^ *<link.*curriculum\.css/s/^/%INSERTCODEMIRROR\0/' \
  -e '/%INSERTCODEMIRROR/r .cached/.codemirror.txt' \
  -e 's/%INSERTCODEMIRROR//' \
  $f
  fi
  tif=.cached/${f%.*}-comment.txt
  if test ! -f $tif; then
    tif=.cached/.${f%.*}-comment.txt
  fi
  if test -f $tif; then
    #echo tif for $f is $tif
    $SED -i \
      -e '/^<body[^>]*>/s/<body[^>]*>/\0%INSERTCURRICULUMCOMMENT/' \
      -e '/%INSERTCURRICULUMCOMMENT/r '$tif \
      -e 's/%INSERTCURRICULUMCOMMENT//' \
      $f
  fi
  if test ! $WORKBOOKPAGE -a ! $DATASHEETPAGE; then
    $SED -i \
      -e 's/^<body class="/\0narrativepage /' \
      $f
  fi
}

function adjustproglangsubdirs() {
  local d=$1
  local pl=$2
  #echo doing adjustproglangsubdirs $d $pl
  #echo PROGLANG is $PROGLANG

  test -d "$d" || return

  if test -d "$d"/"$pl"; then
    cp -p "$d"/"$pl"/* "$d"
  fi

  for lang in pyret wescheme; do
    if test -d "$d"/$lang; then
      rm -fr "$d"/$lang
    fi
  done

  for subdir in "$d"/*; do
    if test -d "$subdir"; then
      adjustproglangsubdirs "$subdir" "$pl"
    fi
  done
}

function shadowcopydir() {
  # srcdir = solution-pages from (previous run + repo)
  # targetdir = pages from repo
  local srcdir=$1
  local targetdir=$2
  #echo doing shadowcopydir from $srcdir to $targetdir
  mkdir -p "$targetdir"

  for f in "$srcdir"/*; do
    if test -f "$f"; then
      g=$(basename "$f")
      targetfile="$targetdir/$g"
      cp -p "$f" "$targetdir"
    elif test -d "$f"; then
      g=$(basename "$f")
      shadowcopydir "$f" "$targetdir"/"$g"
    fi
  done
}

function checkifsinglepdfpage() {
  local fpdf="$1"

  NUMPAGES=$(pdftk $fpdf dump_data|grep NumberOfPages|$SED -e 's/NumberOfPages:  *\([0-9][0-9]*\).*/\1/')

  test "$NUMPAGES" = 1 || (echo;echo WARNING: $fpdf has $NUMPAGES pages)
}

function checkeachinternallink() {
  local f="$1"
  local containingf="$2"

  if ! test -f "$f"; then
    export BROKEN_INTERNAL_LINKS=1
    test $EXPANDEDWARNINGS || echo $'\033[?7h'
    echo
    echo WARNING: Invalid internal link $f in $LESSONSUBDIR/$containingf
  fi
}

function checkeachexternallink() {
  local f="$1"

  local invalid=

  # possible alternative? wget -q --spider $f
  curl -Is $f > .temp.txt

  if test ! -s .temp.txt; then
    invalid=1
  elif ! cat .temp.txt|head -n 1|grep -q 302; then
    :
  elif cat .temp.txt|head -n 1|grep -q 200; then
    if cat .temp.txt|grep -q '^Connection: close'; then
      invalid=1
    fi
  fi

  rm .temp.txt

  if test $invalid; then
    export BROKEN_EXTERNAL_LINKS=1
    echo
    echo WARNING: Invalid external link $f
  fi

}

function checklinks() {
  test "$LINT" || return

  local g="$1"
  local f=.cached/.${g%.*}.external-links.txt.kp

  if test -s "$f"; then
    for h in $(cat "$f"); do
      checkeachexternallink "$h"
    done
  fi

  f=.${g%.*}.internal-links.txt.kp

  if test -s "$f"; then
    for h in $(cat "$f"); do
      checkeachinternallink "$h" "$g"
    done
  fi
}

function doadoc() {
  local f="$1"
  #echo doing doadoc "$@"
  #echo PROGLANG Is $PROGLANG
  local fbase=${f%.a*doc}
  local fasc=.cached/.$fbase.asc
  local fhtml=$fbase.html
  #echo using $fasc $fhtml
  test -d .cached || mkdir -p .cached

  if test $LESSONPLAN; then
    touch .cached/.index-sidebar.asc
    touch .cached/.pathway-standards.asc
    echo "(\"$f\" #:containing-directory \"lessons/$LESSONPLAN\" #:dist-root-dir \"$DISTROOTDIR\" #:lesson-plan \"$LESSONPLAN\")" >> $ADOCABLES_INPUT
    echo lessons/$LESSONPLAN/.cached/.${f%.adoc}.asc >> $ADOC_INPUT
    echo lessons/$LESSONPLAN/.cached/.${f%.adoc}.html >> $ADOC_POSTPROC_LESSONPLAN_INPUT
  elif test $NARRATIVE; then
    echo "(\"$f\" #:containing-directory \"courses/$TGTPATHWAY\" #:narrative #t #:target-pathway \"$TGTPATHWAY\")" >> $ADOCABLES_INPUT
    echo courses/$TGTPATHWAY/.cached/.${f%.adoc}.asc >> $ADOC_INPUT
    echo courses/$TGTPATHWAY/.cached/.${f%.adoc}.html >> $ADOC_POSTPROC_NARRATIVE_INPUT
  elif test $TEACHER_RESOURCES; then
    echo "(\"$f\" #:containing-directory \"courses/$TGTPATHWAY/resources\" #:resources #t #:target-pathway \"$TGTPATHWAY\")" >> $ADOCABLES_INPUT
    echo courses/$TGTPATHWAY/resources/.cached/.${f%.adoc}.asc >> $ADOC_INPUT
    echo courses/$TGTPATHWAY/resources/.cached/.${f%.adoc}.html >> $ADOC_POSTPROC_RESOURCES_INPUT
  elif test $ALLPATHWAYLESSONS; then
    echo "(\"$f\" #:containing-directory \"courses/$TGTPATHWAY\" #:all-pathway-lessons #t)" >> $ADOCABLES_INPUT
    echo courses/$TGTPATHWAY/.cached/.${f%.adoc}.asc >> $ADOC_INPUT
    echo courses/$TGTPATHWAY/.cached/.${f%.adoc}.html >> $ADOC_POSTPROC_ALLPATHWAYS_INPUT
  fi

}

function doadocs() {
  local ff="$@"
  #echo doing doadocs $ff
  #echo PROGLANG is $PROGLANG

  if test $# -eq 0; then
    return
  elif test $# -eq 1 -a ! -f $1; then
    return
  fi

  test -d .cached || mkdir -p .cached

  overwrite building  /$LESSONSUBDIR

  for f in $ff; do
    if test $TGTPATHWAY; then
      if test $OTHERDIR; then
        echo "(\"$f\" #:containing-directory \"courses/$TGTPATHWAY/$LESSONSUBDIR\" #:other-dir #t #:target-pathway \"$TGTPATHWAY\")" >> $ADOCABLES_INPUT
      else
        echo "(\"$f\" #:containing-directory \"courses/$TGTPATHWAY/$LESSONSUBDIR\" #:target-pathway \"$TGTPATHWAY\")" >> $ADOCABLES_INPUT
        echo courses/$TGTPATHWAY/$LESSONSUBDIR/.cached/.${f%.adoc}.asc >> $ADOC_INPUT
        echo courses/$TGTPATHWAY/$LESSONSUBDIR/${f%.adoc}.html >> $ADOC_POSTPROC_NONOTHERDIR_INPUT
      fi
      echo courses/$TGTPATHWAY/$LESSONSUBDIR/.cached/.${f%.adoc}.html >> $ADOC_POSTPROC_WORKBOOKPAGE_INPUT
    else
      if test $OTHERDIR; then
        echo "(\"$f\" #:containing-directory \"lessons/$LESSONSUBDIR\" #:lesson \"$LESSON\" #:other-dir #t)" >> $ADOCABLES_INPUT
      else
        echo "(\"$f\" #:containing-directory \"lessons/$LESSONSUBDIR\" #:lesson \"$LESSON\")" >> $ADOCABLES_INPUT
        echo lessons/$LESSONSUBDIR/.cached/.${f%.adoc}.asc >> $ADOC_INPUT
        echo lessons/$LESSONSUBDIR/${f%.adoc}.html >> $ADOC_POSTPROC_NONOTHERDIR_INPUT
      fi
      echo lessons/$LESSONSUBDIR/.cached/.${f%.adoc}.html >> $ADOC_POSTPROC_WORKBOOKPAGE_INPUT
    fi
  done

  #echo DISTROOTDIR is $DISTROOTDIR

  for f in $ff; do
    fbase=${f%.adoc}
    fhtml=$fbase.html
    fpdf=$fbase.pdf
    if test -f "$fpdf"; then
      rm -f "$fpdf"
    fi
    #echo doadocs LESSONSUBDIR is $LESSONSUBDIR, $fhtml
    if test "$RESOURCEDOCS" = 1 -o \
      "$LESSONSUBDIR" = front-matter/pages -o "$LESSONSUBDIR" = front-matter/solution-pages -o \
      "$LESSONSUBDIR" = back-matter/pages -o "$LESSONSUBDIR" = back-matter/solution-pages; then
          #echo doing it!
          echo ", { \"input\": \"courses/$TGTPATHWAY/$LESSONSUBDIR/$fhtml\", \"debug\": \"vii\" }" >> $PUPPETEER_INPUT
    fi
  done

}

function processadocs() {
  if test $# -eq 0; then
    if test "$dir" = pages; then
      echo No adoc files in $LESSONSUBDIR
    fi
    return
  fi

  local ff_given="$@"
  local ff=

  for f in $ff_given; do
    if test ! -f $f; then
      #echo Not a valid adoc file $f in $(pwd)
      continue
    fi
    if echo $f|grep -q ' '; then
      echo Discarding file \'$f\' with space in its name
      rm "$f"
      continue
    fi
    DOIT=
    fbase=${f%.adoc}
    fhtml=$fbase.html
    fasc=.cached/.$fbase.asc
    if test $FORCE; then
      DOIT=1
    else
      if test $OTHERDIR; then
        if test $f -nt $fasc; then DOIT=1; fi
      else
        if test $f -nt $fhtml; then DOIT=1; fi
      fi
    fi
    if test $DOIT; then
      ff="$ff $f"
      rm -f .cached/.$fbase-comment.txt
    fi
  done

  doadocs $ff

  for f in $ff; do
    checklinks $f
  done

}

function recursiveadoc() {
  local dir="$1"
  local oldPATHWAYROOTDIR="$2"
  local oldDISTROOTDIR="$3"
  local oldLESSONSUBDIR="$4"
  local oldSOLUTION="$SOLUTION"
  local oldOTHERDIR="$OTHERDIR"

  #echo doing recursiveadoc "$@"

  if test "$dir" = solution-pages; then export SOLUTION=1; fi

  cd "$dir"
  export PATHWAYROOTDIR="$oldPATHWAYROOTDIR../"
  export DISTROOTDIR="$oldDISTROOTDIR../"
  if test "$oldLESSONSUBDIR" = "."; then
    export LESSONSUBDIR="$dir"
  else
    export LESSONSUBDIR="$oldLESSONSUBDIR/$dir"
  fi

  #echo LESSONSUBDIR is $LESSONSUBDIR

  for d in *; do
    if test -d "$d"; then
      #echo recursively calling recursivadoc
      recursiveadoc "$d" "$PATHWAYROOTDIR" "$DISTROOTDIR" "$LESSONSUBDIR"
    fi
  done

  export OTHERDIR=
  if test "$dir" = fragments -o "$dir" = xtra -o "$dir" = xtras; then
    export OTHERDIR=1
  fi

  export NOCOLOPHON=
  if test "$dir" = about-datasets; then
    export NOCOLOPHON=1
  fi

  if test $LINT; then
    if test ! $OTHERDIR; then
      if test -f .cached/.workbook-pages-ls.txt.kp; then
        for wbp in $(cat .cached/.workbook-pages-ls.txt.kp); do
          if test ! -f $wbp; then
            wbpadoc=${wbp%.*}.adoc
            if test ! -f $wbpadoc; then
              BROKEN_WORKBOOK_PAGES=1
              echo
              echo WARNING: Missing workbook page $wbp in $LESSONSUBDIR
            fi
          fi
        done
      fi
    fi
  fi

  processadocs *.adoc

  #test $DEBUG || rm -f *.adoc

  cd ..
  export PATHWAYROOTDIR="$oldPATHWAYROOTDIR"
  export DISTROOTDIR="$oldDISTROOTDIR"
  export LESSONSUBDIR="$oldLESSONSUBDIR"
  export SOLUTION="$oldSOLUTION"
  export OTHERDIR="$oldOTHERDIR"
}

function mkdirsolutionversion() {
  #echo doing mkdirsolutionversion
  test -d pages || return

  #echo PWD is $(pwd)

  test -d pages/.cached || mkdir -p pages/.cached

  if test -d solution-pages-2; then
    #echo DEADC0DE: solution-pages-2 shouldn\'t exist
    rm -fr solution-pages-2
  fi

  cp -pr pages solution-pages-2

  cp -p $PROGDIR/.hta* solution-pages-2

  if test -d solution-pages; then
    shadowcopydir solution-pages solution-pages-2
    rm -fr solution-pages
  fi
  mv solution-pages-2 solution-pages

  test -d solution-pages/.cached || mkdir -p solution-pages/.cached
}

function checksinglelessonplan() {
  local L=$1
  local copacetic=1
  for f in *.adoc; do
    if test ! -f $f; then
      copacetic=
    fi
  done
  if ! test $copacetic; then
    if test ! -f index.shtml; then
      echo
      echo WARNING: No lesson plan in $L
    fi
  elif ls *.adoc | wc -l | grep -vq '^ *1$'; then
    echo
    echo WARNING: Too many lesson plans in $L
  elif test -f index.adoc; then
    :
  else
    for f in *.adoc; do
      mv $f index.adoc
    done
  fi
}

function checklessonplan() {
  local L=$1
  #echo doing checklessonplan $L
  checksinglelessonplan $L
  test -d .cached || mkdir -p .cached

  test -f index.adoc || return

  grep '^= ' index.adoc|head -n 1|$SED -e 's/^= *//' -e 's/  *$//' > .cached/.index.titletxt

  if test -f index.adoc; then
    #echo collecting exercises in $L
    $PROGDIR/collect-exercises.rkt index.adoc
    exerflist=pages/.cached/.exercise-pages-ls.txt.kp
    if test -f $exerflist; then
      #echo checklessonplan I
      exerfA=pages/.cached/.exercise-pages.txt.kp
      rm -f $exerfA
      for f in $(cat $exerflist); do
        #echo checklessonplan II $f
        aspect=portrait
        g=$f
        if test ${f%.adoc} = $f; then
          echo $f >> $exerfA
        elif head -5 pages/$f|grep -q '^ *\[\.landscape\] *$'; then
          echo $f landscape >> $exerfA
        else
          echo $f >> $exerfA
        fi
        #echo g is $g
        gext=${g##*.}
        #echo gext is $gext
        if test "$gext" = adoc; then
          g=${g%.adoc}.html
          gext=html
        fi
        #echo g is $g gext is $gext
        if test "$gext" = html; then
          echo ", { \"input\": \"lessons/$L/pages/$g\", \"aspect\": \"$aspect\", \"debug\": \"iii\" }" >> $PUPPETEER_INPUT
          echo ", { \"input\": \"lessons/$L/solution-pages/$g\", \"aspect\": \"$aspect\", \"debug\": \"iv\" }" >> $PUPPETEER_INPUT
        fi
      done
    fi
  fi

}

function buildworkbookpages() {
  local L=$1
  #echo doing buildworkbookpages $L in $(pwd)
  export oldDISTROOTDIR="$DISTROOTDIR"
  local oldPROGLANG="$PROGLANG"
  cd $L
  export LESSON=$L
  export LESSONSUBDIR=$L
  #
  repoDir="$TOPDIR/lessons/$LESSONSUBDIR/langs/$LANGUAGE"

  export PROGLANG=pyret
  if test -f .cached/.wescheme; then
    export PROGLANG=wescheme
  fi

  DORECURSIVEADOC=

  if test -f .cached/.redo; then
    DORECURSIVEADOC=1
    rm -f .cached/.redo
  fi

  if test $DORECURSIVEADOC; then
    #echo !!! doing buildworkbookpages $L $DORECURSIVEADOC

    if test ! -d pages; then
      echo
      echo WARNING: $L missing pages
      mkdir pages
    fi

  #echo calling mkdirsolutionversion in buildworkbookpages
  mkdirsolutionversion

  #
  export PATHWAYROOTDIR="../../"
  export DISTROOTDIR="$DISTROOTDIR../"
  export SOLUTION=
  export WORKBOOKPAGE=1

  for d in *; do
    if test -d "$d"; then
      #echo calling recursiveadoc from buildworkbookpages
      recursiveadoc "$d" "$PATHWAYROOTDIR" "$DISTROOTDIR" "$LESSONSUBDIR"
    fi
  done

  export WORKBOOKPAGE=

  fi

  cd ..

  export PROGLANG="$oldPROGLANG"
  export DISTROOTDIR="$oldDISTROOTDIR"
}

function collapseadjtables() {
  local f=$1
  local x=$(grep -n '^<\/*tbody>' "$f"|$SED -e 's/^\([^:]*\):.*/\1/'|$SED -ne '2,3p')
  if test -z "$x"; then
    return
  fi
  local xi=$(echo $x|$SED -e 's/^\([^ ]*\) .*/\1/')
  local xii=$(echo $x|$SED -e 's/^[^ ]* \([^ ]*\).*/\1/')
  if test -z "$xi" -o -z "$xii"; then
    return
  fi
  $SED -i -e "$xi,${xii}d" "$f"
}

function buildlessonplan() {
  local L=$1
  #echo doing buildlessonplan $L in $(pwd)

  local oldLESSONSUBDIR=$LESSONSUBDIR
  local oldPROGLANG="$PROGLANG"

  cd $L
  export DISTROOTDIR=../../
  export LESSONSUBDIR=$L
  export LESSON=$L
  export LESSONPLAN=$(basename $LESSONSUBDIR)

  export PROGLANG=pyret
  if test -f .cached/.wescheme; then
    export PROGLANG=wescheme
  fi

  if test -f index.adoc; then
    #export PATHWAYROOTDIR="../../"
    export PATHWAYROOTDIR="../courses/$TGTPATHWAY/"
    # there should be only one?
    if test index.adoc -nt index.shtml; then
      overwrite building lesson plan: $L
      rm -f .cached/.index-comment.txt
      test $EXPANDEDWARNINGS || echo -n $'\033[?7h'
      doadoc index.adoc 0
      #$PROGDIR/adoc-preproc.rkt index.adoc
      if test -f index.html; then
        mv index.html index.shtml
        insertbodyid index.shtml
        addanalytics index.shtml
        resolveabbrevs index.shtml
        cleanuptitle index.shtml
        cleanupduration index.shtml
        insertsectionselfie index.shtml
        lintlesson index.shtml
        #echo calling insertgdrivesave from buildlessonplan
        insertgdrivesave index.shtml
      fi
    else
      if test -f pathway-missing-glossary-items.rkt.kp; then
        $PROGDIR/glossary-warnings.rkt
      fi
    fi
    if test -f index.shtml; then
      checklinks index.shtml

      if test ! $NOPDF; then
        if test index.shtml -nt index.pdf; then
          #echo PUPPETEER_INPUT is x $PUPPETEER_INPUT x
          echo ", { \"input\": \"lessons/$LESSONSUBDIR/index.shtml\", \"aspect\": \"portrait\", \"debug\": \"ix\" }" >> $PUPPETEER_INPUT
        fi
      fi
    fi
    if test ! $DEBUG; then
      rm -f *.asc
    fi
  fi
  cd ..

  export LESSONPLAN=
  export LESSONSUBDIR=$oldLESSONSUBDIR
  export PROGLANG="$oldPROGLANG"
  export LESSON=
}

function buildcommonlessons() {
  #echo doing buildcommonlessons
  cd $TOPDIR
  cd $DESTLANGDIR
  cd lessons
  export DISTROOTDIR=../
  local L
  # process lesson directories in parallel
  for L in *; do
    export LESSON=$L
    if test $NOPARALLEL; then
      buildworkbookpages $L
    else
      buildworkbookpages $L &
    fi
  done

  test ! $NOPARALLEL && wait

  #echo starting collectworkbookpages in $(pwd)

  export DOINGLESSON=1
  for d in *; do
    collectworkbookpages "$d"
  done
  export DOINGLESSON=

  cd $TOPDIR
  cd $DESTLANGDIR
  export PATHWAYROOTDIR=./
  export DISTROOTDIR=./
  export LESSON=
  export LESSONSUBDIR=.
}

# Must be done sequentially, to handle prerequisite calculation
function builddependencyjson() {
  #echo doing builddependencyjson
  cd $TOPDIR/distribution/$LANGUAGE/lessons
  export DISTROOTDIR=../
  GRAPHFILE=$TOPDIR/distribution/$LANGUAGE/dependency-graph.js
  echo "var graph = {" > $GRAPHFILE
  first=1
  for L in *; do
    #echo L is $L
    Lbasename=$L
    # the following sanity checks shdnt be needed
    #test -d "$L" || continue
    #if test "$L" = lib; then continue; fi
    if ! grep -q "^ *\"$Lbasename\"" $GRAPHFILE; then
      if test $first; then
        first=
      else
        echo "," >> $GRAPHFILE
      fi
      titletxt=$(cat $L/.cached/.index.titletxt|$SED -e 's/"/\\"/g')
      desctxt=$(cat $L/.cached/.index-desc.txt.kp|$SED -e 's/"/\\"/g')
      pagestxt=$(cat $L/pages/.cached/.workbook-pages-ls.txt.kp|$SED -e ':a' -e 'N' -e '$!ba' -e 's/\n/\", \"/g'|$SED -e 's/.*/\"\0\"/')
      exerpagestxt=
      if test -f $L/pages/.cached/.exercise-pages-ls.txt.kp; then
        exerpagestxt=$(cat $L/pages/.cached/.exercise-pages-ls.txt.kp|$SED -e ':a' -e 'N' -e '$!ba' -e 's/\n/\", \"/g'|$SED -e 's/.*/\"\0\"/')
      fi
      primstxt=
      if test -f $L/.cached/.index-primitives.txt.kp; then
        primstxt=$(cat $L/.cached/.index-primitives.txt.kp|$SED -e ':a' -e 'N' -e '$!ba' -e 's/\n/\", \"/g'|$SED -e 's/.*/\"\0\"/')
      fi
      echo "  \"$Lbasename\" : {" >> $GRAPHFILE
      echo "    title: \"$titletxt\"," >> $GRAPHFILE
      echo "    description: \"$desctxt\"," >> $GRAPHFILE
      echo "    pages: [$pagestxt]," >> $GRAPHFILE
      echo "    exercisePages: [$exerpagestxt]," >> $GRAPHFILE
      echo "    primitives: [$primstxt]," >> $GRAPHFILE
      if test -f $L/.cached/.lesson-keywords.txt.kp; then
        cat $L/.cached/.lesson-keywords.txt.kp >> $GRAPHFILE
      fi
      echo -n "    prerequisites: [" >> $GRAPHFILE
      pfirst=1
      for p in $(cat $L/.cached/.lesson-prereq.txt.kp); do
        if test $pfirst; then
          pfirst=
        else
          echo -n ", " >> $GRAPHFILE
        fi
        echo -n "\"$p\"" >> $GRAPHFILE
      done
      echo "]," >> $GRAPHFILE
      if test -f $L/.cached/.lesson-standards-w-prose.txt.kp; then
        cat $L/.cached/.lesson-standards-w-prose.txt.kp >> $GRAPHFILE
      fi
      echo "  }" >> $GRAPHFILE
    fi
  done
  echo "}" >> $GRAPHFILE
  # convert to UTF-16 to handle curlyquotes
  iconv -f UTF-8 -t UTF-16 $GRAPHFILE > tmp.txt
  mv -f tmp.txt $GRAPHFILE
  #rm tmp.txt
}

function buildlessonplans() {
  start=`date +%s`
  cd $TOPDIR/distribution/$LANGUAGE/lessons
  export DISTROOTDIR=../
  local L
  local copacetic
  #local prevL=/dev/null
  for L in *; do
    # needed?
    #cat $prevL/.cached/.*primtxt > $L/.cached/.prevlesson.primtxt 2> /dev/null
    buildlessonplan $L
    copacetic=1
    for f in $L/.cached/.*primtxt; do
      if test ! -f $f; then
        copacetic=
      fi
    done
    if test $copacetic; then
      cat $L/.cached/.*primtxt | sort -u > $L/.cached/.index-primitives.txt.kp
    fi
    #prevL=$L
  done
  export LESSONSUBDIR=
  cd $TOPDIR/$DESTLANGDIR
  end=`date +%s`
  runtime=$((end-start))
  #echo \ Completed in $runtime s
  #echo \ 
}

function makeglossaryandstandards() {
  if test -f .cached/.pathway-glossary.asc; then
    asciidoctor -a linkcss -a proglang=$PROGLANG \
      -a stylesheet=${DISTROOTDIR}/lib/curriculum.css \
      -a pathwayrootdir=$PATHWAYROOTDIR \
      -a distrootdir=$DISTROOTDIR \
      -a title='Glossary' \
      -B . \
      -o pathway-glossary.shtml \
      .cached/.pathway-glossary.asc
    insertbodyid pathway-glossary.shtml
    resolveabbrevs pathway-glossary.shtml
  fi
  if test -f .cached/.pathway-standards.asc; then
    asciidoctor -a linkcss -a proglang=$PROGLANG \
      -a stylesheet=${DISTROOTDIR}/lib/curriculum.css \
      -a pathwayrootdir=$PATHWAYROOTDIR \
      -a distrootdir=$DISTROOTDIR \
      -a title='Standards' \
      -B . \
      -o pathway-standards.shtml \
      .cached/.pathway-standards.asc
    insertbodyid pathway-standards.shtml
    resolveabbrevs pathway-standards.shtml
  fi
}

function buildpathwaynarrative() {
  #echo doing buildpathwaynarrative
  local copacetic=1
  if test ! -f index.adoc; then
    for f in *.adoc; do
      if test ! -f $f; then copacetic=
      fi
    done
  fi
  #echo copacetic I $copacetic
  if test ! "$copacetic" -a ! -f index.shtml; then
    echo
    echo WARNING: No narrative in pathway $PATHWAY\; creating one
    echo "= $PATHWAY" > index.adoc
  fi
  if ls *.adoc 2> /dev/null | wc -l | grep -vq '^ *[01]$'; then
    echo
    echo WARNING: Too many narratives in pathway $PATHWAY
  else
    #cp -p $PROGDIR/*.css .
    export PATHWAYROOTDIR=./
    export LESSONSUBDIR=
    if test ! -f index.adoc; then
      for f in *.adoc; do
        if test -f $f; then
          mv $f index.adoc
        fi
      done
    fi
    if test index.adoc -nt index.shtml; then
      echo building pathway narrative: $PATHWAY
      export NARRATIVE=1
      rm -f .cached/.index-comment.txt
      test $EXPANDEDWARNINGS || echo -n $'\033[?7h'
      doadoc index.adoc
      export NARRATIVE=
    fi

    checklinks index.shtml
    #verifylinks

  fi
}

function makeworkbookjson() {

  #echo doing makeworkbookjson "$@" in $(pwd)

  local tgt=$1

  local filesvar=

  local wbpnf=
  local includesolutions=
  local includeoptexercises=

  if test "$tgt" = bm-contracts -o "$tgt" = bm-contracts-sols; then
    wbpnf=.cached/.back-matter-contracts-index.rkt
  elif test "$tgt" = workbook -o "$tgt" = pd-workbook -o "$tgt" = workbook-sols; then
    wbpnf=.cached/.workbook-page-index.rkt
  elif test "$tgt" = opt-exercises -o "$tgt" = opt-exercises-sols; then
    wbpnf=.cached/.opt-exercises-index.rkt
  else
    wbpnf=.cached/.workbook-long-page-index.rkt
  fi

  if test "$tgt" = workbook; then
    filesvar=workbookFiles
  elif test "$tgt" = pd-workbook; then
    filesvar=pdWorkbookFiles
  elif test "$tgt" = bm-contracts; then
    filesvar=bmContractsFiles
  elif test "$tgt" = bm-contracts-sols; then
    filesvar=bmContractsSolsFiles
  elif test "$tgt" = workbook-sols; then
    filesvar=workbookSolsFiles
  elif test "$tgt" = workbook-long; then
    filesvar=workbookLongFiles
  elif test "$tgt" = pd-workbook-long; then
    filesvar=pdWorkbookLongFiles
  elif test "$tgt" = workbook-long-sols; then
    filesvar=workbookLongSolsFiles
  elif test "$tgt" = opt-exercises; then
    filesvar=optExercisesFiles
  elif test "$tgt" = opt-exercises-sols; then
    filesvar=optExercisesSolsFiles
  fi

  if test "$tgt" = workbook-sols -o "$tgt" = bm-contracts-sols -o "$tgt" = workbook-long-sols -o "$tgt" = opt-exercises-sols; then
    includesolutions=1
  fi

  if test "$tgt" = workbook-long -o "$tgt" = pd-workbook-long -o "$tgt" = workbook-long-sols -o "$tgt" = opt-exercises -o "$tgt" = opt-exercises-sols; then
    includeoptexercises=1
  fi

  #echo Initializing $WORKBOOKINPUT_$tgt

  echo "{ \"fileList\": [ \"ignoreElement\" " > $WORKBOOKINPUT-$tgt.json

  local currlesson=

  cat $wbpnf |
    while read -r pdfpagespec; do
      if echo $pdfpagespec|grep -qv '\(lessons\|front-matter\|back-matter\)'; then
        continue
      fi
      lessondir=$(echo $pdfpagespec|$SED -e 's/^("\([^"]*\).*/\1/')
      workbookpage=$(echo $pdfpagespec|$SED -e 's/^("[^"]*" *"\([^"]*\).*/\1/')
      aspect=$(echo $pdfpagespec|$SED -e 's/^("[^"]*" *"[^"]*" *"\([^"]*\).*/\1/')
      pageno=$(echo $pdfpagespec|$SED -e 's/^("[^"]*" *"[^"]*" *"[^"]*" *"\?\([^")]*\).*/\1/')

      if test "$pageno" = no -o "$pageno" = No -o "$pageno" = NO; then
        pageno=false
      fi

      if test "$pageno" != false; then
        pageno=true
      fi

      freshlesson=
      if test "$lessondir" != "$currlesson"; then
        freshlesson=1
      fi

      if test "$freshlesson"; then
        currlesson=$lessondir
        docfile=$currlesson/index.shtml
        if test -f "$docfile"; then
          if test "$tgt" = pd-workbook -o "$tgt" = pd-workbook-long; then
            echo $currlesson/index.pdf >> $WORKBOOKINPUT-$tgt
          fi
        fi
      fi

      if test $includesolutions; then
        docfile=$lessondir/solution-pages/$workbookpage
      else
        docfile=$lessondir/pages/$workbookpage
      fi

      docfileext=${docfile##*.}

      if test "$docfileext" = adoc; then
        docfile=${docfile%.adoc}.html
        docfileext=html
      elif test "$docfileext" = pdf; then
        htmlfile=${docfile%.pdf}.html
        if test -f $htmlfile; then
          docfile=$htmlfile
          docfileext=html
        fi
      fi

      #echo docfile= $docfile
      #echo docfileext= $docfileext

      if test "$docfileext" = html; then
        if test -f "$docfile"; then
          localpdffile=${docfile%.html}.pdf

          echo ", { \"file\": \"$localpdffile\", \"paginate\": $pageno }" >> $WORKBOOKINPUT-$tgt.json

        else
          echo ", { \"file\": \"../../lib/$ABYSS.pdf\", \"paginate\": $pageno }" >> $WORKBOOKINPUT-$tgt.json
        fi

      elif test ! -f $docfile; then
        echo ", { \"file\": \"../../lib/$ABYSS.pdf\", \"paginate\": $pageno }" >> $WORKBOOKINPUT-$tgt.json

      else
        echo ", { \"file\": \"$docfile\", \"paginate\": $pageno }" >> $WORKBOOKINPUT-$tgt.json

      fi

    done

    echo "] }" >> $WORKBOOKINPUT-$tgt.json

}

function buildteacherresource() {
  #echo doing buildteacherresource
  cd resources
  export PATHWAYROOTDIR=../
  export DISTROOTDIR=../../../
  export LESSONSUBDIR=resources
  #cp -p $PROGDIR/*.css $PROGDIR/.hta* .
  cp -p $PROGDIR/.hta* .
  local copacetic=1
  if test ! -f index.adoc; then
    for f in *.adoc; do
      if test ! -f $f; then copacetic=
      fi
    done
  fi
  if test ! "$copacetic" -a ! -f index.shtml; then
    echo
    echo WARNING: No teacher resource files in pathway $PATHWAY
  elif ls *.adoc 2> /dev/null | wc -l | grep -vq '^ *[01]$'; then
    echo
    echo WARNING: Too many teacher resource files in pathway $PATHWAY
  else
    #export PATHWAYROOTDIR=../
    # there should be only one?
    if test ! -f index.adoc; then
      for f in *.adoc; do
        if test -f $f; then
          mv $f index.adoc
        fi
      done
    fi
    if test index.adoc -nt index.shtml; then
      overwrite building teacher resources: $PATHWAY "→" "resources" "→" *.adoc
      export TEACHER_RESOURCES=1
      rm -f .cached/.index-comment.txt
      test $EXPANDEDWARNINGS || echo -n $'\033[?7h'
      doadoc index.adoc
      #$PROGDIR/adoc-preproc.rkt index.adoc
    fi
    #checklinks index.shtml
  fi
  cd ..
  export PATHWAYROOTDIR=./
  export LESSONSUBDIR=

}

function batchhtmltopdf() {
  cd $TOPDIR/distribution/$LANGUAGE
  #echo doing batchhtmltopdf in $(pwd)
  echo "] }" >> $PUPPETEER_INPUT

  # use --trace-warnings to debug

  #echo in $(pwd) doing node ../../lib/html2pdf.js $PUPPETEER_INPUT
  if grep -q input $PUPPETEER_INPUT; then
    node lib/html2pdf.js $PUPPETEER_INPUT
  fi
}

function rmtmpfiles() {

  test $DEBUG && return
  #echo doing rmtmpfiles

  for f in adoc aux log rkt tex title; do
    find . -name \*.$f -delete
  done

  for f in txt; do
    find . -name \*.$f | grep -v '\(lesson-order\|workbook-pages\)\.txt' | xargs rm -f
  done

  find . -name $WKH2P_PFX-\* -delete
}

function copylessondir() {
  lessonDir=$1
  #echo doing copylessondir $lessonDir
  repoLessonDir=$TOPDIR/lessons/$lessonDir/langs/$LANGUAGE
  #echo repoLessonDir is $repoLessonDir
  if test -d "$repoLessonDir"; then
    mkdir -p $lessonDir
    #echo $repoLessonDir is a diry
    DOCOPYDIR=1
    #echo calling checkmd5nochange $lessonDir $repoLessonDir
    if checkmd5nochange $lessonDir $repoLessonDir; then
      #echo $lessonDir doesnt need copying
      DOCOPYDIR=
    fi
    #echo checkmd5nochange done
    if test $DOCOPYDIR; then
      #echo do copydir into $(pwd)
      overwrite preparing $lessonDir
      cp -pr $repoLessonDir/* $lessonDir
      cd $lessonDir
      #echo I currently in $(pwd)
      # we'll set it again when we do the adoc'ing
      mkdir -p .cached
      #echo III deleting checksum.md5txt
      #rm -f .cached/.checksum.md5txt
      touch .cached/.redo
      for subdir in *; do
        if test "$subdir" = pages -o "$subdir" = solution-pages; then
          test -d $subdir/.cached || mkdir $subdir/.cached
        fi
      done
      checklessonplan $lessonDir
      #echo checklessonplan done
      for subdir in *; do
        if test -d "$subdir"; then
          adjustproglangsubdirs "$subdir" pyret
        fi
      done
      cd ..
      if test -f $lessonDir/proglang.txt; then
        for pl in $(cat $lessonDir/proglang.txt); do
          if test "$pl" != pyret; then
            cp -pr $lessonDir $lessonDir-$pl
            cd $lessonDir-$pl
            mkdir -p .cached
            touch .cached/.$pl
            touch .cached/.redo
            for subdir in *; do
              if test -d "$subdir"; then
                adjustproglangsubdirs "$subdir" "$pl"
              fi
            done
            cd ..
          fi
        done
      fi
    fi
  fi
  #echo done copylessondir
}

function collectworkbookpages() {
  d="$1"
  test ! -d "$d" && return
  #echo doing collectworkbookpages $d
  cd "$d"
  if test -d pages; then
    cd pages
    if test -f workbook-pages.txt; then
      #echo workbook-pages.txt found
      test -d .cached || mkdir .cached
      cd .cached
      rm -f .workbook-pages.txt.kp .workbook-pages-ls.txt.kp
      #ensure workbook-pages.txt ends in newline, or while isn't happy
      $SED -i -e '$a\' ../workbook-pages.txt

      touch .workbook-pages-ls.txt.kp

      while read -r f; do
        #echo finding aspect of "$f"
        aspect=portrait
        g=$f
        if echo "$f"|grep -q landscape; then
          echo $f >> .workbook-pages.txt.kp
          g=$(echo $f|$SED -e 's/^ *\([^ ]\+\).*/\1/')
          echo $g >> .workbook-pages-ls.txt.kp
          aspect=landscape
        elif echo "$f"|grep -q portrait; then
          echo $f >> .workbook-pages.txt.kp
          g=$(echo $f|$SED -e 's/^ *\([^ ]\+\).*/\1/')
          echo $g >> .workbook-pages-ls.txt.kp
        elif test "${f%.adoc}" = "$f"; then
          echo $f >> .workbook-pages.txt.kp
          echo $f >> .workbook-pages-ls.txt.kp
        else
          g=${f%.adoc}.html
          if test -f $f && head -n 5 ../"$f"|grep -q '^ *\[\.landscape\] *$'; then
            echo $f landscape >> .workbook-pages.txt.kp
            echo $f >> .workbook-pages-ls.txt.kp
            aspect=landscape
          elif test -f $g && head -n 60 ../"$g"|grep -q 'body.*landscape'; then
            echo $f landscape >> .workbook-pages.txt.kp
            echo $f >> .workbook-pages-ls.txt.kp
            aspect=landscape
          else
            echo $f >> .workbook-pages.txt.kp
            echo $f >> .workbook-pages-ls.txt.kp
          fi
        fi
        if test $DOINGLESSON; then
          gext=${g##*.}
          if test "$gext" = adoc; then
            g=${g%.adoc}.html
            gext=html
          fi
          #echo g is $g gext is $gext
          if test "$gext" = html; then
            echo ", { \"input\": \"lessons/$d/pages/$g\", \"aspect\": \"$aspect\", \"debug\": \"iii\" }" >> $PUPPETEER_INPUT
            echo ", { \"input\": \"lessons/$d/solution-pages/$g\", \"aspect\": \"$aspect\", \"debug\": \"iv\" }" >> $PUPPETEER_INPUT
          fi
        fi
      done < ../workbook-pages.txt

      cd ..
    fi
    cd ..
  fi
  cd ..
}

function buildpathwayworkbooks() {
  #echo building pathway workbooks for $TGTPATHWAY $SRCPATHWAY

  cd $TOPDIR/distribution/$LANGUAGE/courses/$TGTPATHWAY

  #echo topdir is $TOPDIR

  #mkdir -p $TOPDIR/distribution/$LANGUAGE/courses/$TGTPATHWAY/resources/pages
  #mkdir -p $TOPDIR/distribution/$LANGUAGE/courses/$TGTPATHWAY/resources/solution-pages

  node $TOPDIR/distribution/$LANGUAGE/lib/makeWorkbook.js
}

function copycommonlessons() {
  start=`date +%s`
  echo 📁 PREPARING LESSONS
  echo $'-----------------------------------------------------------\n'

  cd $TOPDIR

  export DESTLANGDIR=distribution/$LANGUAGE

  mkdir -p $DESTLANGDIR

  if test $FORCE; then
    rm -fr $DESTLANGDIR/lessons
  fi

  mkdir -p $DESTLANGDIR/lessons

  cd $DESTLANGDIR/lessons

  #echo currently in $(pwd)

  if test $NOARGSGIVEN; then
    for lessonDir in $TOPDIR/lessons/*; do
      lessonDir=${lessonDir#*lessons/}
      copylessondir $lessonDir
    done
  else
    for pwy in $ARGS; do
      for lessonDir in $(cat $TOPDIR/pathways/$pwy/langs/$LANGUAGE/lesson-order.txt|grep -v '^ *$'|grep -v '^ *;'); do
        copylessondir $lessonDir
      done
    done
  fi

  cd $TOPDIR

  end=`date +%s`
  runtime=$((end-start))
  echo \ Completed in $runtime s
  echo \ 
}

function buildworkbookjsons() {
  cd $TOPDIR/distribution/$LANGUAGE/courses/$TGTPATHWAY

  if test $BOOK; then
    for wbf in workbook pd-workbook bm-contracts bm-contracts-sols workbook-sols workbook-long \
      pd-workbook-long workbook-long-sols opt-exercises opt-exercises-sols ; do
          if test $NOPARALLEL; then
            makeworkbookjson $wbf
          else
            makeworkbookjson $wbf &
          fi
        done
        test ! $NOPARALLEL && wait
  fi

}

function buildpathway() {
  start=`date +%s`
  #echo doing buildpathway $TGTPATHWAY
  cd $TOPDIR

  PATHWAY=$TGTPATHWAY

  export LESSONSUBDIR=.
  export SOLUTION=
  export BROKEN_WORKBOOK_PAGES=
  export BROKEN_INTERNAL_LINKS=
  export BROKEN_EXTERNAL_LINKS=

  langicon=💀

  if test "$PROGLANG" = wescheme; then
    langicon=🥾
  fi

  echo

  if test ! -d pathways/$SRCPATHWAY/langs/$LANGUAGE; then
    echo
    echo WARNING: No pathway $PATHWAY/$LANGUAGE
  else
    echo $langicon BUILDING PATHWAY: $LANGUAGE/$PATHWAY 
    echo $'-----------------------------------------------------------\n'

    export DESTPATHWAYDIR=distribution/$LANGUAGE/courses/$PATHWAY

    if test $FORCE; then
      rm -fr $DESTPATHWAYDIR
    fi

    mkdir -p $DESTPATHWAYDIR

    repoDir="$TOPDIR/pathways/$SRCPATHWAY/langs/$LANGUAGE"
    distDir="$TOPDIR/$DESTPATHWAYDIR"

    if ! checkmd5nochange $DESTPATHWAYDIR $repoDir; then
      #echo copying pathway I $repoDir
      cp -pr pathways/$SRCPATHWAY/langs/$LANGUAGE/* $DESTPATHWAYDIR
    fi

    #echo copy pathway $SRCPATHWAY done

    REFRESHFRONTMATTER=1
    REFRESHBACKMATTER=1
    REFRESHRESOURCES=1

    test -d $repoDir/front-matter || REFRESHFRONTMATTER=
    test -d $repoDir/back-matter || REFRESHBACKMATTER=
    test -d $repoDir/resources || REFRESHRESOURCES=

      #TODO parallelize
      if test -d $distDir/front-matter -a -d $repoDir/front-matter; then
        if checkmd5nochange $distDir/front-matter $repoDir/front-matter; then
          REFRESHFRONTMATTER=
        fi
      fi

      if test -d $distDir/back-matter -a -d $repoDir/back-matter; then
        if checkmd5nochange $distDir/back-matter $repoDir/back-matter; then
          REFRESHBACKMATTER=
        fi
      fi

      if test -d $distDir/resources -a -d $repoDir/resources; then
        if checkmd5nochange $distDir/resources $repoDir/resources; then
          REFRESHRESOURCES=
        fi
      fi

    rm -f $PROGDIR/pathway-local.rkt
    if test -f $repoDir/pathway-local.rkt; then
      cp -p $repoDir/pathway-local.rkt $PROGDIR
    fi

    cd $DESTPATHWAYDIR
    mkdir -p .cached

    export PATHWAYROOTDIR=./
    export DISTROOTDIR=../../

    export WORKBOOKINPUT=$TOPDIR/$DESTPATHWAYDIR/.cached/.filelist

    #mkdir -p lessons workbook
    mkdir -p  workbook

    if test ! -f lesson-order.txt; then
      echo
      echo WARNING: No lesson-order.txt in pathway $PATHWAY/$LANGUAGE
    else
      export PATHWAYLESSONS=\"$(cat lesson-order.txt|$SED -e ':a' -e 'N' -e '$!ba' -e 's/\n/\",\"/g')\"
      grep -v '^ *;' lesson-order.txt |
        grep -v '^ *$' |
        $SED -e 's/^ *\(.*\)/..\/..\/lessons\/\1/' > .cached/.workbook-lessons.txt.kp
    fi

    if test $REFRESHFRONTMATTER; then
      cd front-matter
      mkdirsolutionversion
      cd ..
      adjustproglangsubdirs front-matter $PROGLANG
    fi

    if test $REFRESHBACKMATTER; then
      cd back-matter
      mkdirsolutionversion
      cd ..
      adjustproglangsubdirs back-matter $PROGLANG
    fi

    mkdir -p resources/protected
    cp -p $PROGDIR/.hta* resources/protected

    if test $REFRESHRESOURCES; then
      cd resources
      test -d pages || mkdir -p pages
      mkdirsolutionversion
      for d in *; do
        if test -d $d; then
          cd $d
          mkdirsolutionversion
          cd ..
          #adjustproglangsubdirs $d
        fi
      done
      cd ..
      adjustproglangsubdirs resources $PROGLANG
    fi

    for d in front-matter back-matter; do
      collectworkbookpages "$d"
    done

    #echo calling collect-workbook-pages.rkt in $(pwd)

    $PROGDIR/collect-workbook-pages.rkt

    export WORKBOOKPAGE=1
    export BOILERPLATE=1

    if test $REFRESHFRONTMATTER; then
      if test -d front-matter; then
        #echo calling recursiveadoc from REFRESHFRONTMATTER
        recursiveadoc front-matter "$PATHWAYROOTDIR" "$DISTROOTDIR" "$LESSONSUBDIR"
        touch front-matter #why?
      fi
    fi

    if test $REFRESHBACKMATTER; then
      if test -d back-matter; then
        #echo calling recursiveadoc from refreshbackmatter
        recursiveadoc back-matter "$PATHWAYROOTDIR" "$DISTROOTDIR" "$LESSONSUBDIR"
        touch back-matter
      fi
    fi

    export WORKBOOKPAGE=

    cd resources

    export PATHWAYROOTDIR=../
    export DISTROOTDIR=../../../
    export LESSONSUBDIR=resources

    if test $REFRESHRESOURCES; then
      export RESOURCEDOCS=1
      for d in *; do
        if test -d "$d"; then
          if test "$d" = datasheets; then
            export DATASHEETPAGE=1
          else
            export DATASHEETPAGE=
          fi
          #echo calling recursiveadoc from refreshresources
          recursiveadoc "$d" "$PATHWAYROOTDIR" "$DISTROOTDIR" "$LESSONSUBDIR"
        fi
      done
      export RESOURCEDOCS=
    fi

    cd ..

    if test $REFRESHRESOURCES; then touch resources; fi

    export BOILERPLATE=
    export PATHWAYROOTDIR=./
    export DISTROOTDIR=../../
    export LESSONSUBDIR=

    #DEBUG
    buildpathwaynarrative

    cd $TOPDIR; cd $DESTPATHWAYDIR

    #echo PWD is $(pwd)

    if test ! $NOPDF; then
      if test ! -f .cached/.workbook-page-index.rkt; then
        echo
        echo WARNING: No workbook index file in pathway $PATHWAY/$LANGUAGE
      else
        #cd ../courses/$PATHWAY

        cd $TOPDIR/distribution/$LANGUAGE
        #batchhtmltopdf

        cd courses/$PATHWAY

        #TODO:  ↓ not needed?
        export PATHWAYROOTDIR=./

        fi
      fi
    fi

    buildteacherresource

    #rmtmpfiles

    #echo PWD 3 is $(pwd)

  cd $TOPDIR/distribution/$LANGUAGE

  if test $LINT; then

    if test $BROKEN_WORKBOOK_PAGES; then
      echo 👎 Broken workbook pages in $PATHWAY
    else
      echo 👍 No broken workbook pages in $PATHWAY
    fi

    if test $BROKEN_INTERNAL_LINKS; then
      echo 👎 Broken internal links in $PATHWAY
    else
      echo 👍 No broken internal links in $PATHWAY
    fi

    if test $BROKEN_EXTERNAL_LINKS; then
      echo 👎 Broken external links in $PATHWAY
    else
      echo 👍 No broken external links in $PATHWAY
    fi
  fi
  test $EXPANDEDWARNINGS || echo $'\033[?7h'
  end=`date +%s`
  runtime=$((end-start))
  echo \ Completed in $runtime s
  echo \ 
}

function buildpathwaytocs() {
  cd $TOPDIR/distribution/$LANGUAGE/courses
  export DISTROOTDIR=../
  TOCSFILE=$TOPDIR/distribution/$LANGUAGE/pathway-tocs.js
  echo "var pathwayTocs = {" > $TOCSFILE
  first=1
  for C in *; do
    if test $first; then
      first=
    else
      echo "," >> $TOCSFILE
    fi
    echo -n "   \"$C\": [" >> $TOCSFILE
    thisPathwayLessons=
    if test -f $C/.cached/.workbook-lessons.txt.kp; then
      thisPathwayLessons=$(cat $C/.cached/.workbook-lessons.txt.kp|$SED -e 's/.*\/lessons\///'|$SED -e ':a' -e 'N' -e '$!ba' -e 's/\n/\", \"/g'|$SED -e 's/.*/\"\0\"/')
    fi
    echo -n $thisPathwayLessons >> $TOCSFILE
    echo "]" >> $TOCSFILE
  done
  echo "}" >> $TOCSFILE
}

function allthestandards() {
  cd $TOPDIR
  cd distribution/$LANGUAGE
  export LANGROOTDIR=./
  #echo doing allthestandards in $(pwd)
  test -d .cached || mkdir -p .cached
  rm -f .cached/.all-standards.txt
  for d in courses/*; do
    test -d $d || continue
    db=${d%/}
    db=${db##*/}
    f=$d/.cached/.standards-in-pathway.txt.kp
    if test -f $f; then
      $SED -e "s/)\$/ \"$db\")/" $f >> .cached/.all-standards.txt
    fi
  done
  $PROGDIR/make-standards.rkt
  asciidoctor -a linkcss -a proglang=$PROGLANG \
    -a stylesheet=lib/curriculum.css \
    -a title='Standards' \
    -o Standards.shtml \
    -B . \
    .cached/Standards.asc
  insertbodyid Standards.shtml
  resolveabbrevs Standards.shtml

  if test ! $DEBUG; then rm -f *.asc *.txt; fi

  cd $TOPDIR
}

function calculatedistrootdir() {
  local f=$1
  #echo doing calculatedistrootdir $f
  local doubledots=$(echo $f|$SED -e 's/\/\.\//\//g')
  #echo I doubledots= $doubledots
  doubledots=$(echo $doubledots|$SED -e 's/[^\/]//g')
  #echo II doubledots= $doubledots
  doubledots=$(echo $doubledots|$SED -e 's/^\///')
  #echo III doubledots= $doubledots
  doubledots=$(echo $doubledots|$SED -e  's/\//..\//g')
  #echo calculatedistrootdir for $f is $DISTROOTDIR
  echo $doubledots
}

function postproc_workbookpage() {
  local fhtmlcached=$1
  if test -f "$fhtmlcached"; then
    local localDISTROOTDIR=$(calculatedistrootdir $fhtmlcached)
    local fdir=${fhtmlcached%/.cached/.*html}
    #echo  fdir= $fdir
    local fbase=${fhtmlcached##*/.}
    #echo fbase= $fbase
    local fhtml=$fdir/$fbase
    #echo fhtml= $fhtml
    #echo moving $fhtmlcached to $fhtml
    cp -p $fhtmlcached $fhtml
    bumpcsspathdir $fhtml $localDISTROOTDIR
    resolveabbrevs $fhtml $localDISTROOTDIR
  fi
}

function postproc_nonotherdir() {
  local f=$1
  if test -f "$fhtml"; then
    #echo fhtml= $fhtml
    insertgdrivesave $fhtml
  fi
}

function postproc_lessonplan() {
  local fhtmlcached=$1
  if test -f "$fhtmlcached"; then
    localDISTROOTDIR=$(calculatedistrootdir $fhtmlcached)
    fdir=${fhtmlcached%/.cached/.*html}
    #echo  fdir= $fdir
    fbase=${fhtmlcached##*/.}
    fbase=${fbase%.html}.shtml
    #echo fbase= $fbase
    fshtml=$fdir/$fbase
    #echo fhtml= $fhtml
    #echo moving $fhtmlcached to $fshtml
    mv $fhtmlcached $fshtml
    #echo doing insertbodyid
    insertbodyid $fshtml
    #echo doing addanalytics
    addanalytics $fshtml
    #echo doing resolveabbrevs
    bumpcsspathdir $fshtml $localDISTROOTDIR
    resolveabbrevs $fshtml $localDISTROOTDIR
    #echo cleanuptitle
    cleanuptitle $fshtml
    #echo cleanupduration
    cleanupduration $fshtml
    #echo insertsectionselfie
    insertsectionselfie $fshtml
    #echo lintlesson
    lintlesson $fshtml
    #echo insertgdrivesave
    insertgdrivesave $fshtml
  fi
}

function postproc_narrative() {
  local fhtmlcached=$1
  if test -f "$fhtmlcached"; then
    localDISTROOTDIR=$(calculatedistrootdir $fhtmlcached)
    fdir=${fhtmlcached%/.cached/.*html}
    fbase=${fhtmlcached##*/.}
    fbase=${fbase%.html}.shtml
    fshtml=$fdir/$fbase
    mv $fhtmlcached $fshtml
    insertbodyid $fshtml
    addanalytics $fshtml
    bumpcsspathdir $fshtml $localDISTROOTDIR
    resolveabbrevs $fshtml $localDISTROOTDIR
    insertgdrivesave $fshtml
  fi
}

function postproc_resources() {
  local fhtmlcached=$1
  if test -f "$fhtmlcached"; then
    localDISTROOTDIR=$(calculatedistrootdir $fhtmlcached)
    fdir=${fhtmlcached%/.cached/.*html}
    fbase=${fhtmlcached##*/.}
    fbase=${fbase%.html}.shtml
    fshtml=$fdir/$fbase
    mv $fhtmlcached $fshtml
    insertbodyid $fshtml
    bumpcsspathdir $fshtml $localDISTROOTDIR
    resolveabbrevs $fshtml $localDISTROOTDIR
    cleanuptitle $fshtml
    insertgdrivesave $fshtml
  fi
}

function postproc_allpathways() {
  local fhtmlcached=$1
  if test -f "$fhtmlcached"; then
    localDISTROOTDIR=$(calculatedistrootdir $fhtmlcached)
    fdir=${fhtmlcached%/.cached/.*html}
    fbase=${fhtmlcached##*/.}
    fbase=${fbase%.html}.shtml
    fshtml=$fdir/$fbase
    mv $fhtmlcached $fshtml
    removelogos $fshtml
    bumpcsspathdir $fshtml $localDISTROOTDIR
    resolveabbrevs $fshtml $localDISTROOTDIR
  fi
}

function doadocpostproc() {
  #echo doing doadocpostproc
  cd $TOPDIR/distribution/$LANGUAGE

  start=`date +%s`
  echo 👨‍💻CALLING ASCIIDOCTOR IN BATCH MODE
  echo '-----------------------------------------------------------'
  if test -s $ADOC_INPUT; then
    asciidoctor -a linkcss -a stylesheet=lib/curriculum.css -a cachedir=.cached/ -B . $(cat $ADOC_INPUT)
  else
    echo No adoc files need conversion!
  fi
  end=`date +%s`
  runtime=$((end-start))
  echo \ Completed in $runtime s
  echo \ 

  start=`date +%s`
  echo 👨‍💻POST-PROCESSING HTML
  echo '-----------------------------------------------------------'

  for fhtmlcached in $(cat $ADOC_POSTPROC_WORKBOOKPAGE_INPUT); do
    postproc_workbookpage $fhtmlcached &
  done
  wait

  #echo Postprocessing wkbkpages done

  for fhtml in $(cat $ADOC_POSTPROC_NONOTHERDIR_INPUT); do
    postproc_nonotherdir $fhtml &
  done
  wait

  #echo Postprocessing nonotherdir done

  #echo DOING LESSONPLANs
  #echo doing $ADOC_POSTPROC_LESSONPLAN_INPUT

  for fhtmlcached in $(cat $ADOC_POSTPROC_LESSONPLAN_INPUT); do
    postproc_lessonplan $fhtmlcached &
  done
  wait

  #echo Postprocessing lessonplans done

  for fhtmlcached in $(cat $ADOC_POSTPROC_NARRATIVE_INPUT); do
    postproc_narrative $fhtmlcached &
  done
  wait

  #echo Postprocessing narratives done

  for fhtmlcached in $(cat $ADOC_POSTPROC_RESOURCES_INPUT); do
    postproc_resources $fhtmlcached &
  done
  wait

  #echo Postprocessing teacherresources done

  for fhtmlcached in $(cat $ADOC_POSTPROC_ALLPATHWAYS_INPUT); do
    postproc_allpathways $fhtmlcached &
  done
  wait

  #echo Postprocessing allpathways done

  end=`date +%s`
  runtime=$((end-start))
  echo \ Completed in $runtime s
  echo \ 
}

function doconversions() {
  #echo doing doconversions
  start=`date +%s`
  cd $TOPDIR/distribution/$LANGUAGE

  echo 👨‍💻CALLING RACKET IN BATCH MODE
  echo '-----------------------------------------------------------'
  $PROGDIR/adocables-preproc.rkt $ADOCABLES_INPUT
  end=`date +%s`
  runtime=$((end-start))
  echo \ Completed in $runtime s
  echo \ 

  doadocpostproc $ADOC_INPUT

  if test ! $NOPDF; then
    if test ! -f lib/$ABYSS.pdf; then
      echo '= PAGE NOT FOUND!' > lib/$ABYSS.adoc
      echo >> lib/$ABYSS.adoc
      asciidoctor -a linkcss -a stylesheet=lib/asciidoctor.css lib/$ABYSS.adoc
      echo ", { \"input\": \"lib/$ABYSS.html\" }" >> $PUPPETEER_INPUT
    fi

  fi
}

function callonARGS() {
  local subroutine=$1

  for f in $ARGS; do
    #echo I doing $f
    export SRCPATHWAY=$f
    export SRCPATHWAY=${SRCPATHWAY#pathways/}
    export SRCPATHWAY=${SRCPATHWAY%/}
    export TGTPATHWAY="$SRCPATHWAY"
    #echo SRCPATHWAY is $SRCPATHWAY
    #echo TGTPATHWAY is $TGTPATHWAY
    if test "$PROGLANG" = ""; then
      if test "$SRCPATHWAY" = algebra; then
        export PROGLANG=wescheme
        export TGTPATHWAY=algebra-wescheme
        $subroutine
        export PROGLANG=pyret
        export TGTPATHWAY=algebra
        $subroutine
      else
        export PROGLANG=pyret
        $subroutine
      fi
      export PROGLANG=
    else
      if test "$SRCPATHWAY" = algebra; then
        if test "$PROGLANG" != pyret; then
          export TGTPATHWAY=algebra-$PROGLANG
        fi
      fi
      $subroutine
    fi
  done
}

mkdir -p $TOPDIR/distribution/$LANGUAGE/.cached
export PUPPETEER_INPUT=$TOPDIR/distribution/$LANGUAGE/.cached/.do-puppeteer.json
echo "{\"htmlFileSpecs\": [ \"ignoreElement\"" > $PUPPETEER_INPUT

export ADOCABLES_INPUT=$TOPDIR/distribution/$LANGUAGE/.cached/.do-adocables.rkt
echo '(' > $ADOCABLES_INPUT

export ADOC_INPUT=$TOPDIR/distribution/$LANGUAGE/.cached/.do-asciidoctor.txt.kp
rm -f $ADOC_INPUT
touch $ADOC_INPUT

export ADOC_POSTPROC_WORKBOOKPAGE_INPUT=$TOPDIR/distribution/$LANGUAGE/.cached/.do-adoc-postproc-workbookpage.txt.kp
export ADOC_POSTPROC_NONOTHERDIR_INPUT=$TOPDIR/distribution/$LANGUAGE/.cached/.do-adoc-postproc-nonotherdir.txt.kp
export ADOC_POSTPROC_LESSONPLAN_INPUT=$TOPDIR/distribution/$LANGUAGE/.cached/.do-adoc-postproc-lessonplan.txt.kp
export ADOC_POSTPROC_NARRATIVE_INPUT=$TOPDIR/distribution/$LANGUAGE/.cached/.do-adoc-postproc-narrative.txt.kp
export ADOC_POSTPROC_RESOURCES_INPUT=$TOPDIR/distribution/$LANGUAGE/.cached/.do-adoc-postproc-resources.txt.kp
export ADOC_POSTPROC_ALLPATHWAYS_INPUT=$TOPDIR/distribution/$LANGUAGE/.cached/.do-adoc-postproc-allpathways.txt.kp

rm -f $ADOC_POSTPROC_WORKBOOKPAGE_INPUT $ADOC_POSTPROC_NONOTHERDIR_INPUT \
  $ADOC_POSTPROC_LESSONPLAN_INPUT $ADOC_POSTPROC_NARRATIVE_INPUT \
  $ADOC_POSTPROC_RESOURCES_INPUT $ADOC_POSTPROC_ALLPATHWAYS_INPUT

touch $ADOC_POSTPROC_WORKBOOKPAGE_INPUT $ADOC_POSTPROC_NONOTHERDIR_INPUT \
  $ADOC_POSTPROC_LESSONPLAN_INPUT $ADOC_POSTPROC_NARRATIVE_INPUT \
  $ADOC_POSTPROC_RESOURCES_INPUT $ADOC_POSTPROC_ALLPATHWAYS_INPUT

copycommonlessons

mkdir -p distribution/$LANGUAGE/.cached

buildcommonlessons

export PROGLANG=pyret #fixme

#echo PWDi is $(pwd)

buildlessonplans

#echo PWDii is $(pwd)

#echo calling Racket on $PROGDIR/adocables-preproc.rkt

#$PROGDIR/adocables-preproc.rkt .cached/.do-adocables.rkt #fixme

#echo !!! calling buildpathway s

#echo PWD 1 is $(pwd)

callonARGS buildpathway

#echo !!! buildpathway s done

echo ')' >> $ADOCABLES_INPUT

#echo PWD 2 is $(pwd)

#$PROGDIR/adocables-preproc.rkt $ADOCABLES_INPUT

doconversions

callonARGS buildworkbookjsons

builddependencyjson

buildpathwaytocs

#echo !!! building workbooks

if test ! $NOPDF; then

  cd $TOPDIR/distribution/$LANGUAGE
  batchhtmltopdf

  callonARGS buildpathwayworkbooks

fi

# only to shush now-benign error
export PROGLANG=pyret

allthestandards

echo >> index.adoc
echo .{nbsp} >> index.adoc

for f in distribution/*/*; do
  f=${f%/}
  g=${f#distribution/}
  pwy=${g%/*}
  lang=${g#*/}
  docf=$f/index.shtml
  if test -f $docf; then
    echo >> index.adoc
    echo \* link:pass:[$docf][$pwy Narrative \($lang\)] >> index.adoc
  fi
done

if test README.html -ot README.adoc; then
  asciidoctor README.adoc
fi

asciidoctor index.adoc

cd distribution

echo >> index.adoc
echo .{nbsp} >> index.adoc

for f in */*; do
  f=${f%/}
  pwy=${f%/*}
  lang=${f#*/}
  docf=$f/index.shtml
  if test -f $docf; then
    echo >> index.adoc
    echo \* link:pass:[$docf][$pwy Narrative \($lang\)] >> index.adoc
  fi
done

asciidoctor index.adoc
