#! /usr/bin/env bash

test ! -d distribution && 
  echo ERROR: distribution/ dir not found && 
  exit

while IFS= read -r authoring_dir; do
  pyret_file=$authoring_dir/generate-pyret-images.arr
  if test -f $pyret_file; then
    (cd $authoring_dir; pyret generate-pyret-images.arr >/dev/null)
  fi
done < <(find distribution/en-us/lessons -type d -name authoring)
