#!/bin/bash

shared/langs/en-us/coverage-report.rkt
asciidoctor -a linkcss -a stylesheet=lib/asciidoctor.css coverage-report.adoc

SED=sed

if which gsed|grep -q .; then
  SED=gsed
fi

$SED -i \
  -e 's/<p><span class="unused">/<p class="unused"><span>/g' \
  coverage-report.html
