#!/bin/bash

# last modified 2023-02-28

# env vars HOSTINGER_PORT, HOSTINGER_USER, HOSTINGER_IPADDR *must* be set!
# but don't set them here, for security reasons

exitp=false

test -z "$HOSTINGER_PORT" && echo Please set HOSTINGER_PORT && exitp=true
test -z "$HOSTINGER_USER" && echo Please set HOSTINGER_USER && exitp=true
test -z "$HOSTINGER_IPADDR" && echo Please set HOSTINGER_IPADDR && exitp=true

$exitp && exit

# set env vars SEMESTER and YEAR to reflect where you want the
# curriculum pages to be deployed on the server.

test -z "$SEMESTER" && SEMESTER=fall
test -z "$YEAR" && YEAR=2023-debug

############################################################################

lib=

while test $# -ne 0; do
  arg=$1; shift
  if test "$arg" = -lib; then
    lib=lib
  fi
done

if test ! -d distribution; then
  echo distribution/ not found; exit
fi

cd distribution

test -d deployables && rm -fr deployables

mkdir deployables

ALL_THE_LANGS="en-us es-mx"

for lang in $ALL_THE_LANGS; do
  mkdir -p deployables/$lang/courses
  mkdir -p deployables/$lang/lessons
done

SEMESTER_YEAR=$SEMESTER$YEAR

SED=sed

(which gsed | grep -q .) && SED=gsed

function correctgdriveurl_1() {
  local f=$1
  $SED -i -e '/href=/s/\(spring\|fall\)[0-9][0-9][0-9][0-9]/'$SEMESTER_YEAR'/g' $f
}

function correctgdriveurls() {
  local d=$1
  for f in $(find $d -name \*gdrive-import.shtml); do
    correctgdriveurl_1 $f
  done
}

function copyCourse() {
  local dir=$1
  for lang in $ALL_THE_LANGS; do
    test -d $lang/courses/$dir || continue
    cp -pr $lang/courses/$dir deployables/$lang/courses/$dir
    correctgdriveurls deployables/$lang/courses/$dir
  done
}

for lang in $ALL_THE_LANGS; do
  if test $lib; then
    if test -d $lang/extlib; then
      cp -pr $lang/extlib deployables/$lang
    fi
  fi
  for f in $lang/*; do
    if test -f $f; then
      cp -p $f deployables/$lang
    fi
  done
  if test -d $lang/lib; then
    cp -pr $lang/lib deployables/$lang
  fi
  if test -d $lang/lessons; then
    cp -pr $lang/lessons deployables/$lang
    correctgdriveurls deployables/$lang/lessons
  fi
  if test -d $lang/courses; then
    cp -pr $lang/courses deployables/$lang
    correctgdriveurls deployables/$lang/courses
  fi
done

for f in adoc asc aux md id rkt rkt.kp titletxt txt txt.kp; do
  find deployables -name \*.$f -delete
done

find deployables -name workbook\*.pdf -delete
find deployables -name opt-exercises\*.pdf -delete
find deployables -name lesson-images.json -delete

find deployables -name .cached -type d -exec rm -fr {} \; > /dev/null 2>&1

test -f deployables.tar.bz2 && rm deployables.tar.bz2

echo Tarring up deployables...
tar jcf deployables.tar.bz2 deployables

cat > deploy-to-public_html.sh <<EOF
SEMESTER=$SEMESTER
YEAR=$YEAR
DEPLOY_DIR=\$HOME/public_html/materials/\$SEMESTER\$YEAR
mkdir -p \$DEPLOY_DIR
cd
cd tmp
rm -fr deployables
tar jxf deployables.tar.bz2
cp -pr deployables/* \$DEPLOY_DIR
EOF

echo Copying deployables.tar.bz2 to hostinger...
scp -p -P $HOSTINGER_PORT deployables.tar.bz2 deploy-to-public_html.sh $HOSTINGER_IPADDR:tmp/.

exitstatus=$?

test $exitstatus -ne 0 && echo scp failed! 🙁 && exit

echo Unpacking files under public_html/materials/$SEMESTER$YEAR...
ssh -p $HOSTINGER_PORT $HOSTINGER_IPADDR 'bash ~/tmp/deploy-to-public_html.sh'

exitstatus=$?

test $exitstatus -ne 0 && echo ssh failed! 🙁 && exit

echo Deployment done! 🙂
