= Read me

== Building

The top directory contains the subdirectories `lessons`,
`pathways`, which between them contain the curriculum content.
Explore them to see where things are.

  build-pathway
  /lib/*.css
  /shared
    /langs/en-us/glossary-terms.rkt
                 standards-dictionary.rkt
                 adoc-preproc.rkt
                 form-elements.rkt
                 function-directives.rkt
                 make-workbook.rkt
  /lessons
    /lessonX/langs/en-us/jened.adoc
                         exercises/<recipe>.adoc
                         images/<picture>.jpg
                         workbook-pages/lesson-index.rkt
                         workbook-pages/<page>.pdf
  /pathways
    /pathwayX/langs/en-us/narrative.adoc
                          workbook-index.rkt
                          resources/<teacher-index>.adoc

In particular, “lesson A” is in subdirectory `lessonA` inside
`lessons`. The lesson plan is an `.adoc` file in
`lessons/lessonA/langs/en-us` (it can have any filename, here
`jened.adoc`).

The exercises associated with lesson A are alongside the lesson
plan adoc file, in subdirectory `exercises`. Images are in
subdir `images`. Single workpages are in subdir `workbook-pages`
(some of these can be static PDFs). The index of these lesson
pages, in correct order, is in `lesson-index.rkt`.

Only one pathway P is shown in the repo for now. It is `pathways/pathwayP`.
In that directory, the pathway’s narrative is in
`langs/en-us/main.adoc` (name can be anything). Alongside it, its
index of lessons, in correct order, is in `workbook-index.rkt`.
These lessons are drawn from the `lessons`
tree.

The top dir contains the script `build-pathway`.

Call it with a pathway spec (e.g., `pathwayP`) to build a
`distribution` directory containing a subtree for each
`pathwayP`.

   distribution/
     pathwayX/langs/en-us/narrative.html
                          lessons/
                                 jened.html
                                 exercises/*.{html,pdf}
                                 workbook-pages/*.{html.pdf}
                          resources/<teacher-index>.html
                          workbook/workbook.pdf

(For now, as a convenience, calling `build-pathway` without an arg builds
`pathwayP`.)

== jened sample doc

The following was reverse-engineered from the latest Google Docs
mock-up of a lesson from Jen/Ed. Change this to reflect
experience.

link:distribution/lessons/lessonA/langs/en-us/jened.html[Sample
lesson plan]

== Git stuff

Fork this repo to your GitHub account (say, `jrandomuser`). (This is done using
obvious clickety click on the GitHub page.)

In your terminal, clone your fork thusly:

   git clone https://github.com/jrandomuser/curr-reorg

This will create a local repo where you can try things, change
things, etc. But first, to retain connection with the original do:

  git remote add upstream https://github.com/ds26gte/curr-reorg

Every time the original changes, update like so:

  git fetch upstream
  git merge upstream/master

You are probably in your own `master` branch. Even if you’re
“branching out” to other new branches, the above merge will
mostly work.  “Mostly” because merge often triggers conflicts
depending on how far you have diverged from the original. At the
very least, make sure you’ve checked in all your changes that you
care about, before you attempt a merge. For changes you aren’t
ready to check in, save the concerned files somewhere else, and
make sure there are no “modified” files in your directory.

=== To make your fetch/merge experience easier

The directory `distribution` contains generated files which can
always be re-generated. Before you merge, delete its contents and re-create
its default so the merge doesn't get snagged in it:

  cd distribution
  rm -fr *
  git checkout -- \*

Create your own lesson directories under `lessons` and your own
pathways under `pathways`.  Work exclusively there, rather than
the supplied lessons `lessonA`, `lessonB`, `lessonC` and supplied
pathway `pathwayP` -- which are there purely for illustration.
As the original repo doesn't know about your lessons and
pathways, there will be no conflicts from that regard.

NB: When you create a pathway, named `pathwayQ` say, use

  `./build-pathway pathwayQ`

to generate its files. Without an argument, `build-pathway` uses
`pathwayP`.

== Glossary and standards

Glossary items are annotated with the directive `@vocab`. E.g.,

  @vocab{function}

Standards are annotated with `@std`. E.g.,

  @std{2-AP-10 , 3A-NI-06 , N-Q&1&2, N-Q&1&3}

Such items are searched in
`shared/langs/en-us/{glossary-terms.rkt,standards-dictionary.rkt}`,
and are inserted as lists at the head of the document. In
addition, glossary items for a set of files in a directory are
collected into a file `summary.html`.

== Exercises

Exercise files are typically recipes and have calls to one of two
directives

  @design-recipe-exercise{...}

  @assess-design-recipe{...}

The former is used to specify a correct recipe; the latter to
introduce a recipe to be debugged. See examples of such files,
`exercise*.adoc`, in the repo.

== Cross-references and pagination

Both lesson plans and pathway narratives can refer to exercises
or particular
pages in a pathway workbook.  The relevant directive
calls look like

  @worksheet-link{lessonA/exercises/exerciseA1.html, link-text}
  @worksheet-link{lessonA/workpages/pageA2.pdf, link-text}
  @worksheet-link{lessonA/jened.adoc, link-text}

The final argument for link text is optional.

If called from a lesson plan for `lessonA`, the `lessonA/` may be
dropped. Thus the first two examples can be rewritten:

  @worksheet-link{exercises/exerciseA1.html, link-text}
  @worksheet-link{workpages/pageA2.pdf, link-text}

Except for exercises (which don't feature in the workbook unless
you created a workbook page for them), the rendered link has its
link text (if any) augmented with a reference to the specific
page number in the pathway worksheet.

=== Generic cross reference

Use `@link{URL, link-text}` to refer to a generic cross-reference
not part of the curriculum hierarchy.  The second argument for
the link text is optional.

== Some useful classes and directives

Some standard CSS classes to emphasize certain regions of text.

Use

  [.strategy-box]
  .Header
  ****
  Rem suscipit soluta quas recusandae dolor culpa non. Iste aut
  ipsum qui eos quidem et. Debitis omnis ipsam cupiditate ut vero
  odio.
  ****

to generate a “strategy box”, a boxed text with a blue border.

Use

   [.notice-box]

to generate a “notice & wonder box”, a boxed text with a purple
border.

Add the class `.physics-table` to a table attribute to generate a
single-arg function
table, e.g., one that maps miles driven to cost.

Use the directive `@lessons-in-pathway` in a pathway narrative to
insert a list of all the lessons referred to by the pathway
(these are picked from the `workbook-index.rkt` file).

== Prereqs

Needed:

* Asciidoctor, a Ruby program, to generate HTML from AsciiDoc.
(The format is AsciiDoc, the program that converts it is
Asciidoctor. I wish we had this neat nomenclatural separation for
other programs too.) To install it,
+
  sudo apt-get install asciidoctor
+
on Linux machines, and
+
  brew install asciidoctor
+
on macOS.
+

* Racket, to do preprocessing for metadata and other
bookkeeping. Any version should do. I’m using very conservative
Racket.

* PDF manipulators wktohtmltopdf and pdftk.  Standard
installation as for Asciidoctor.

=== A brief AsciiDoc intro

An AsciiDoc source file typically as the extension `.adoc`, at
least in our setup.

A title (aka “level 1”) header has its line preceded by a single
equal sign.

Level 2 headers (“sections”) are preceded by two equal signs.
Similarly for “subsections” at level 3, 4, 5, 6.

  = Title at level 1

  == Section at level 2

  === Subsection at level 3

  ==== Et cetera

Itemized lists have each item paragraph preceded by a ``*`` or
``-`` and space.

Emphasized text is set within by +_..._+.

Bold text within +*...*+.

In-text code fragment within +`...`+.

Code displays are on contiguous lines that are indented (amount
of indentation doesn't matter as long it's non-0).

Please see the
https://asciidoctor.org/docs/user-manual[Asciidoctor manual] for
the whole story. Learn just the bare minimum to get started writing,
and then learn more as needed, either from the online manual, or by bugging
me. (If something seems too tedious to learn or input, I could
add it as a Racket directive.)
