:toc:
:toclevels: 4

= READ ME

We describe here the directories and files in the `curriculum`
directory, and how to use the programs provided.

For a generated
document tree, please see
https://bootstrapworld.org/materials/spring2020/courses.

== Structure of the `curriculum` directory

The top directory contains a bunch of scripts and subdirectories.

The curriculum content is placed in the subdirectories `lessons`
and `pathways`. `lessons` contains individual lessons, including
the lesson plan, exercises, and workbook pages. `pathways`
contains pathway directories, each of which defines a collection
of lessons. (It is possible for a lesson to occur in multiple
pathways.)

The subdirectories `lib` and `shared` contain the components of
the program used to generate web pages and PDFs from the
`lessons` and `pathways`. `shared` contains directories named for
the various natural languages used for instruction, e.g., `en-us`
for US English, and `es-mx` for Mexican Spanish. Inside these
dwell centralized educational-standards dictionaries, e.g.,
`csta-standards-dictionary.rkt` for a list of standards defined
by the CSTA. Also present is a general glossary of terms used in
the lessons: `glossary-terms.rkt`.

The main script is `build-pathway` which takes a pathway name and
constructs the web pages and PDFs for it in a directory called
`distribution`.

Here is a skeleton of the `curriculum` tree, showing the salient
files, with a sample lesson and sample pathway:

  curriculum/
    build-pathway
    lib/
      <language-independent implementation files>
    shared/langs/
      en-us/
        <language-dependent implementation files>
        glossary-terms.rkt
        *-standards-dictionary.rkt
    lessons/
      sample-lesson/
        langs/
          en-us/
            index.adoc
            images/
            pyret/
            wescheme/
            pages/
              *.{adoc,pdf}
              workbook-pages.txt
              pyret/
              wescheme/
            solution-pages/
              *.{adoc,pdf}
              pyret/
              wescheme/
            xtra/
              *.{adoc,pdf}
              pyret/
              wescheme/
    pathways/
      sample-pathway/
        langs/
          en-us/
            index.adoc
            lesson-order.txt
            external-index.rkt
            front-matter/
              pages/
                *.{adoc,pdf}
                workbook-pages.txt
              solution-pages/
                *.adoc
                workbook-pages.txt
            back-matter/
              pages/
              solution-pages/
            resources/
              index.adoc

Some standard subdirectory names are used to separate and shadow
content based on (natural) language of instruction, the
programming language used, or whether content is being built for
student or teacher. Thus:

- The `langs` subdirectory uses further subdirectories, e.g.,
`en-us` for US English and `es-mx` for Mexican Spanish. Source
documents from the relevant natural language are chosen based on
the `--language` option chosen during build. The default is
`en-us`. In order to ease transition, if a language other than
`en-us` is chosen, any content unavailable in the new language is
filled in by what’s in `en-us`.

- Some of the directories have `pyret` and `wescheme`
subdirectories or both. These contain content that should shadow
the default content (one directory level up) if that
programming language is used. Specify this choice via the
`--proglang` option during build. The default is usually `pyret`,
but in some cases content is built for both `pyret` and
`wescheme`.

- The directory `solution-pages` is used to house source
that will shadow `pages`, when the pages meant only for
teacher use are created.  Similarly,

In all these cases, it is important that the shadowing content
have the same file basename as the content that is being
shadowed. Extensions can vary; thus it is possible for
`filename.pdf` to shadow `filename.adoc` and vice versa.

=== Structure of a lesson directory

Each lesson has a subdirectory, e.g., `sample-lesson`, under the
`lessons` directory.

A lesson plan is specified by an `.adoc` file in the language
directory for that lesson, e.g.,
`sample-lesson/langs/en-us/index.adoc`. While the file basename
doesn’t
have to be `index`, ensure that there is only one `.adoc` file at
this level.

Images are in
subdir `images`.

Single workbook pages are in subdirs `pages`
and `solution-pages` (some of these can be static PDFs
rather than adoc source files).
(The `solution-` versions, as already explained, are meant to supply
shadowing content intended for teacher-only documents.)

The file `pages/workbook-pages.txt` lists
the pages -- one per line -- in the
`pages` directory in the order in which they should show up in the
final workbook.
By default,
these pages are rendered in portrait mode. If you desire a
particular file `file.adoc` to be in landscape, its entry line in
`workbook-pages.txt` should be `file.adoc" landscape` rather
than just `file.adoc`. (The
entry `file.adoc` is convenient shorthand for `file.adoc
portrait`.)  (The words `landscape` and `portrait` may
be in any case.) Supplementary `adoc` files used by these pages
can be stored in subdirectories, typically named `fragments`.

Lesson pages are paginated by default when they show up in the
workbook. If you don’t want a page to be populated, its entry
line in
`workbook-pages.txt` should be `file.adoc portrait
nopagenum`. (The aspect should also be mentioned, even if it’s
the default.)

(Any of the components in an entry line in `workbook-pages.txt`
may be enclosed in double-quotes.)

=== Structure of a pathway directory

Each pathway has a subdirectory, e.g., `sample-pathway`, under the
`pathways` directory.

A pathway narrative is specified by an `.adoc` file in the
language directory for that pathway, e.g.,
`sample-pathway/langs/en-us/index.adoc`. The file basename
doesn’t have to be `index`, but there should be only one `.adoc`
file in this directory.

There can also be a file `external-index.rkt` used to expand
pointers to URLs in the pathway narrative (see below).

In the same directory, the file `lesson-order.txt` lists
the names of the lessons (e.g., `sample-lesson`)
that should be included in the
pathway, in the order in which they should appear in the pathway
workbook. (The filename can be enclosed in double-quotes.)

The pathway directory can also contains a `resources`
subdirectory, where an `.adoc` file describes the “Teacher
Resources” page. There should be only one such `.adoc` file, but
it can be named anything (not necessarily `index.adoc`).

== The `build-pathway` script

The top dir contains the script `build-pathway`. It takes any
number of pathway arguments, and/or any combination of the
options `--add-exercises`, `--debug`, `--force`, `--help`, `--language`,
`--lint`, `--no-pdf`,
`--no-parallel`, `--proglang`, and `--version`.

If called with `--help` (aka `-h`) or `--version` (aka `-v`), the script displays a help message
and version information, respectively, and quits.

Otherwise, the
script creates a document tree under the `distribution` directory
for every pathway argument.
A pathway arg can be either the
pathway name, or its relative pathname from the `build-pathway`
script, with or without a trailing slash, e.g., all of the
following refer to the same pathway:

  sample-pathway
  pathways/sample-pathway
  pathways/sample-pathway/

If no pathway arg is supplied,
`build-pathway` generates doctrees for every pathway in
`pathways`.

If no `--language` option is supplied, the prose language used is
`en-us`. To specify another language, say `es-mx`, use
`--language es-mx`.

The doctree for the built pathway under `distribution` resides
under a subdirectory named for the prose language, e.g., `en-us`,
e.g.,

   distribution/
     sample-pathway/
       en-us/
         index.shtml
         lessons/
         resources/
           protected/
             workbook-sols.pdf
         workbook/
           workbook.pf

Here `index.shtml` is the web page corresponding to the pathway
narrative; `resources/protected/workbook-sols.pdf` is the Teacher
workbook PDF; and `workbook/workbook.pdf` is the student
workbook. These filenames are standard and do not necessarily
mirror the names of the source documents.

If no `--proglang` option is supplied, the progamming language is
assumed to be `pyret`. The other possible value for the option is
`wescheme`. The distribution directory for a pathway built with
`wescheme` has the suffix `-wescheme`.

NOTE: A small number of pathways have both `pyret` and `wescheme`
versions, and they should coexist. To better distinguish the two,
the distribution directories for them currently have the suffix
`-pyret` and `-wescheme` respectively. However, in general,
exclusively `pyret`-based pathways do without the `-pyret`
suffix.

Note that two workbook PDFs can be created, one for the students
in the `workbook` directory; and another for teachers in the
“protected” directory `resources/protected`.

Pages under `resources/protected` may prompt you for a teacher
password, which is available on signing up with Bootstrapworld.

The pathway narrative web page `index.shtml` includes a link to
`pathway-lessons.shtml`, which contains all the lesson plans
associated with the pathway; the student
workbook PDF; a page listing the standards met; and a glossary
page for the terms used in the lessons.

The option `--add-exercises` (aka `-e`) swells the workbooks with
exercises following each lesson.

=== `build-pathway` debugging

The other options of `build-pathway` are predominantly used for
debugging:

- `--check-target` (aka `-c`) checks each file of a previous 
  run to see if it needs to be refreshed. By default, a much more
  lax check is done to save build time. (The default is enough if you
  only alter source files and don't alter the previous output.
  If however you alter output files selectively in order to re-make
  them, you must use `-c`.)

- `--debug` (aka `-d`) retains various temp files in the generated doctree.

- `--expanded-warnings` (aka `--w`) shows the diagnostics as
  long scroll instead of overwriting them.

- `--force` (aka `-f`) forces creating anew the document tree. By default,
  in order to save time,
  conversions are skipped if the `distribution` already contains
  the required target files and they are sufficiently new.

- `--lint` (aka `-l`) reports missing rows in the summary tables of lesson
  plans, and invalid links in the doctree.

- `--no-parallel` (aka `--noparallel`) runs the build script
  strictly sequentially, without exploiting parallelism. This may
  be used to uncover bugs introduced by parallelism.

- `--no-pdf` (aka `--nopdf` or `-n`) avoids PDF generation to speed up the debugging
process.

== Deployment

We currently deploy to:

https://www.bootstrapworld.org/materials/fall2020/courses

(The `fall2020` is in general `<semester><year>` where
`<semester>` is one of `spring` or `fall`, and `<year>` is the
4-digit year.)

After building one or pathways on your local machine, you can
deploy all relevant docs from the `distribution/` directory by typing

  deploy-to-brown jrandomuser

Here `jrandomuser` is your user ID on Brown. You will be prodded for
your Brown password, once to copy the files over and another time
to set it up on the Brown machine. (This may be compressed in the
future.)

If you wish to deploy only a single pathway, e.g.,
`data-science`, add the pathway by name as a second argument:

  deploy-to-brown jrandomuser data-science

(This assumes you've first run some variant of `./build-pathway data-science`, of
course.)

The script `deploy-to-brown` uses SSH to interact with your Brown
account. The connection has been often been flaky, so often the
second SSH fails. If this happens, in order to let you finish, without redoing the
work accomplished with the first SSH, you may type

  deploy-to-brown-perms jrandomuser

(If you used the optional second arg for `deploy-to-brown`, you
don't need to repeat it here.)

*Note:* The `algebra` pathway is an anomaly, since it exists in
both `-wescheme` and `-pyret` variants.
To type just one or the other variant, type one of

  deploy-to-brown jrandomuser algebra-wescheme
  deploy-to-brown jrandomuser algebra-pyret

To deploy both variants (if available), type

  deploy-to-brown jrandomuser algebra

In any case, `deploy-to-brown` only deploys a pathway if the
latter has been built locally first. So if you've built `algebra-wescheme` but
`algebra-pyret`, requesting `algebra` be deployed is equivalent to requesting
`algebra-wescheme`.

== Standards compliance

The file `shared/lang/en-us/lessons-and-standards.rkt` contains
an association of lessons with the educational standards they
comply with. Dictionaries for the various standards are available
in the same directory. For now, these are:

  cc-ela-standards-dictionary.rkt
  cc-math-standards-dictionary.rkt
  csta-standards-dictionary.rkt
  k12cs-standards-dictionary.rkt
  ngss-standards-dictionary.rkt
  ok-standards-dictionary.rkt
  old-standards-dictionary.rkt

The build process creates a menu for finding out the standards
complied with by the lessons and the pathway. The lesson’s menu
is embedded in the lesson plan, whereas the pathway’s (larger)
menu is linked to.

The directive `@prereqs-stds{}` is used as a placeholder in a
table for row(s) that include lesson prerequisites (if any) and
standards. (The mode of inclusion may change in subsequent
versions depending on how predictable lesson-plan formats
become. For now, we need a placeholder.)

== Git basics

Fork this repo to your GitHub account (say, `jrandomuser`). (This is done using
obvious buttons on the GitHub page.)

In your terminal, clone your fork thusly:

   git clone https://github.com/jrandomuser/curriculum

This will create a local repo where you can try things, change
things, etc. But first, to retain connection with the original do:

  git remote add upstream https://github.com/bootstrapworld/curriculum

Every time the original changes, update like so:

  git fetch upstream
  git merge upstream/master

You are probably in your own `master` branch. Even if you’re
“branching out” to other new branches, the above merge will
mostly work.  “Mostly” because merge often triggers conflicts
depending on how far you have diverged from the original. At the
very least, make sure you’ve checked in all your changes that you
care about, before you attempt a merge. For changes you aren’t
ready to check in, save the concerned files somewhere else, and
make sure there are no “modified” files in your directory.

=== Creating your private branch in the original repo

Alternatively -- and this will work only for greenlisted members
-- clone the repo directly and add your own branch, e.g.,

  git clone https://github.com/bootstrapworld/curriculum
  cd curriculum
  git checkout -b jenbranch

You can pull and merge from `master` as needed:

  git checkout master
  git pull
  git checkout jenbranch
  git merge master

If conflicts arise, you will be given a way to resolve them.

== Prerequisites

The following external programs are needed to construct documents from
this repo:

- Asciidoctor, a Ruby program, to generate HTML from AsciiDoc.
(The format is AsciiDoc, the program that converts it is
Asciidoctor. I wish we had this neat nomenclatural separation for
other programs too.) To install it,
+
  sudo apt-get install asciidoctor
+
on Linux machines, and
+
  brew install asciidoctor
+
on macOS.
+

- GNU sed. This is pre-installed on Linux, but may need to be
explicitly installed on macOS, using `brew` as above (i.e., `brew
install gnu-sed`).

- Bash. Keeps all the scripts humming.

- Racket, to do preprocessing and other
bookkeeping. Any version should do. I’m not using any
bleeding-edge features of Racket.

- PDF manipulator `pdftk`.  Standard installation as for Asciidoctor.

- HTML -> PDF generator `puppeteer`, as well as `puppeteer-cluster` to build in parallel.  `sudo npm install puppeteer`
to install the first, `sudo npm install puppeteer-cluster` for the second.

- `puppeteer`, alternative to `wkhtmltopdf`.  `sudo npm i puppeteer`
to install.

- TeX containing `pdflatex`. Install a suitable TeX system for
your OS (for Linux, it’s `texlive`).

- `curl`. Use brew to install.

== Authoring guidelines

The `.adoc` files peppering this curriculum repo are written in
AsciiDoc overlaid with some preprocessing macros written in
Racket. AsciiDoc is a plain-text-based markup that is converted
by the Asciidoctor program into HTML (among other things, but we
don’t use those parts).

=== A brief introduction to AsciiDoc

An AsciiDoc source file typically has the extension `.adoc`, at
least in our setup.

A title (aka “level 0”) header has its line preceded by a single
equal sign.

Level 1 headers (“sections”) are preceded by two equal signs.
Similarly for “subsections” at level 2, 3, 4, 5.

  = Title at level 1

  == Section at level 2

  === Subsection at level 3

  ==== Et cetera

Itemized lists have each item paragraph preceded by a ``*`` or
``-`` and space.

Emphasized text is set within by +_..._+.

Bold text within +*...*+.

In-text code fragment within +`...`+.

Code displays are on contiguous lines that are indented (amount
of indentation doesn’t matter as long it’s non-0).

Please see the
https://asciidoctor.org/docs/user-manual[Asciidoctor manual] for
the whole story. Learn just the bare minimum to get started writing,
and then learn more as needed, either from the online manual, or by bugging
me. (If something seems too tedious to learn or input, I could
perhaps add it as a Racket directive.)

If your Asciidoctor version is at least 2.0.0, you can type

  asciidoctor --help syntax

to get a brief reference guide to the syntax. To create a browsable HTML
file, do

  asciidoctor --help syntax | asciidoctor - -o help.html

and open `help.html` in your browser.

=== Racket preprocessing

The `.adoc` files we author can contain some additional markup,
which we shall call _directives_.  All directives begin with an
`@`, and, if they take arguments, the latter are encased in
braces (`{}`). Here are all the directives:

==== Glossary

Glossary items are annotated with the directive `@vocab`. E.g.,

  @vocab{function}

In a lesson plan, such items are searched in
`shared/langs/en-us/glossary-terms.rkt`,
and are inserted as lists at the head of the document.

For a pathway narrative, the glossary items from all its
constituent lessons are collected into a file
`pathway-standards.shtml` that is linked to in the narrative
page.

==== Lesson descriptions and dependencies

Each lesson plan is strongly advised to start out with a

  @lesson-description{A brief paragraph describing the lesson.}

The description is displayed in the lesson plan, but is also part
of the autogenerated thumbnails used by the pathway narrative for
each of its lessons.

==== Exercises

Exercise files are typically recipes and have calls to one of two
directives

  @design-recipe-exercise{...}

  @assess-design-recipe{...}

The former is used to specify a correct recipe; the latter to
introduce a recipe that needs to be debugged. For examples of
such recipes, please see the `.adoc` files in the various
`fragments` subdirectories in the repo.

Some exercise files are more elaborate than recipes and contain
sketches of solutions and tables that need to be filled. These
use some extra directives like `@do`, `@show`, `@code` that then
use raw Racket code to format the exercise. Examples of
these can be found in the `Supplemental` lesson.

Sometimes, just a contract (part of a recipe) needs to be shown
in the text. Use `@show` to call the Racket procedures `contract`
(for a single contract)
or `contracts` (for multiple).

  @show{(contract "/" '("Number" "Number") "Number")}

This states that the function name is `/`, its domain list is
`("Number" "Number")` and its range is `"Number"`.

  @show{(contract "/" '("Number" "Number") "Number" 
    "divides one number by another")}

adds an optional fourth argument stating the function's purpose.

To show multiple contracts, 

  @show{(contracts
    '("/" '("Number" "Number") "Number" "divides one number by another")
    '("*" '("Number" "Number") "Number" "multiples one number by another")
   }

Note that `contracts` takes a list of arguments. Also note that
quoting each such argument obviates the need for quoting the
domain-list argument.

==== Cross-references and pagination

Both lesson plans and pathway narratives can refer to any files
in any lessons, in particular, exercises
or specific
pages in a pathway workbook.  The relevant directive
calls look like

  @worksheet-link{lessonA/exercises/exerciseA1.html, link-text}
  @worksheet-link{lessonA/workbook-pages/pageA2.pdf, link-text}

The final argument for link text is optional.

If called from a lesson plan for `lessonA`, the `lessonA/` may be
dropped. Thus the first two examples can be rewritten:

  @worksheet-link{exercises/exerciseA1.html, link-text}
  @worksheet-link{workpage-pages/pageA2.pdf, link-text}

Arbitrary pages can be invoked:

  @worksheet-link{lessonA/jened.pdf, link-text}

This refers to `jened.pdf` in `lessonA`. Typically pages within
the same lesson’s directory are used, in which case the `lessonA`
may be replaced by a `.`:

  @worksheet-link{./jened.pdf, link-text}

Subdirectories can also be used:

  @worksheet-link{./resources/jened.pdf, link-text}

The directive `@exercise-link` is a near-synonym of
`@worksheet-link` that is used only for exercises. (It differs
from `@worksheet-link` only in that the exercise directory it
points to is not allowed to be shadowed, e.g., `exercises` in the
path is not replaced by `exercises-sols`.)

The directive `@worksheet-include` uses the same argument
structure as `@worksheet-link` but instead of linking to its file
argument
it includes the contents of the file. E.g.,
a workbook page can include an exercise in the same lesson using

  @worksheet-include{exercises/exerciseA1.adoc}

(It would not make sense to use `@worksheet-link` here, as workbooks are
standalone PDFs that are typically printed, and any links in it
would not be reachable anyway.)

Use `@image{images/pic.png}` to insert the image `pic.png`.

Use commas to add image options, e.g.,

  @image{images/player-move.png, PlayerMovement, 400, align="center"}

==== Generic links

Use `@link{URL, link-text}` to refer to a generic URL
not part of the curriculum hierarchy.  The second argument for
the link text is optional.

===== Generic links with standard names

Use `@worksheet-link{pointer, link-text}` to refer to a pointer
(a standard name) to a possibly volatile URL. E.g.,

  @worksheet-link{demo-page, The Demo Page}

The pointer `demo-page` is resolved using an index file
`external-index.rkt`, which contains an assoc list, with entries
like

  ("demo-page"
       "https://bootstrapworld.github.io/curriculum/index.html")

==== Comments

HTML comments can be inserted anywhere in the `.adoc` file as

  @comment{A comment}

AsciiDoc has its own commenting mechanism with `//` and `////`
(see manual), but these are expunged when the HTML is created. To
have comments that persist as HTML comments, use `@comment`.

==== Programming language specific text

Use the `@ifproglang` directive to conditonally include a
fragment text for a specific programming language, which as
explained earlier, is usually `pyret` by default, but can be set
supplying a `--proglang` option to the build script. E.g.,

  @ifproglang{pyret}{
  This text occurs in the Pyret version of this document.
  }

  @ifproglang{wescheme}{
  This text occurs in the WeScheme version of this document.
  }

==== Adding custom CSS classes

Some standard CSS classes to emphasize certain regions of text.

Use

  [.strategy-box]
  .Header
  ****
  Rem suscipit soluta quas recusandae dolor culpa non. Iste aut
  ipsum qui eos quidem et. Debitis omnis ipsam cupiditate ut vero
  odio.
  ****

to generate a “strategy box”, a boxed text with a blue border.

Use

   [.notice-box]

to generate a “notice & wonder box”, a boxed text with a purple
border.

Add the class `.physics-table` to a table attribute to generate a
single-arg function
table, e.g., one that maps miles driven to cost.

You can add your own CSS classes or IDs. Classes are specified
with an initial dot and IDs with an initial `#`. Note that at
most one ID is meaningful, although any number of classes may be
specified. A combination of classes and ID are simply strung
together, e.g,

   [.class1.class2.class3#onlyid]

The above works for blocks. Use `@span{classes and id}{text}` to
enclose CSS classes and/or an ID around arbitrary (i.e., in-line)
text. ``@span``s may be nested. `@span`’s first argument of
classes and ID is specified in the same way as for blocks,
without the brackets.
