= Decision Trees and Confusion Matrices
++++
<style>
#preamble_disabled { flex-grow: 0 !important; }
.fitb { min-width: 2em !important; }
</style>
++++

[cols="3a, 2a", frame="none", border="none", grid="none"]
|===
|
[.data-table, cols="1,^1,^1,^1,^1,^1", stripes="none", options="header"]
!===
! name      ! species   ! sex         ! tail    ! mammal ! swims
! Firepaw   ! cat       ! male        ! TRUE    ! TRUE   ! FALSE
! Frisky    ! dog       ! female      ! TRUE    ! TRUE   ! TRUE
! Socks     ! dog       ! female      ! TRUE    ! TRUE   ! TRUE
! Stripe    ! dog       ! male        ! TRUE    ! TRUE   ! TRUE
! Snickers  ! dog       ! male        ! TRUE    ! TRUE   ! TRUE
! Leafpool  ! cat       ! female      ! TRUE    ! TRUE   ! FALSE
! Shadestar ! cat       ! female      ! TRUE    ! TRUE   ! TRUE
! Bramble   ! cat       ! female      ! TRUE    ! TRUE   ! FALSE
! Brick     ! cat       ! male        ! TRUE    ! TRUE   ! FALSE
! Bruni     ! lizard    ! female      ! TRUE    ! FALSE  ! TRUE
! Jesús     ! lizard    ! male        ! TRUE    ! FALSE  ! TRUE
! Gary      ! snail     !hermaphrodite! FALSE   ! FALSE  ! FALSE
! Turbo     ! snail     !hermaphrodite! FALSE   ! FALSE  ! FALSE
! Charlotte ! tarantula ! male        ! FALSE   ! FALSE  ! FALSE
! Webs      ! tarantula ! female      ! FALSE   ! FALSE  ! FALSE
!===

|
@image{../images/animal-tree-1.png}
|===

[.no-flex-section]
== The Data
@n Circle all the datatypes you see in this dataset of different animals: @hspace{2em} Numbers @hspace{2em} @ifsoln-choice{Strings} @hspace{2em} @ifsoln-choice{Booleans} @hspace{2em} Images

@n Write least *two things you notice* about the data @fitb{}{}
@blanklines{2}{
@ifsoln{All the snails are hermaphrodites, the last three columns are Booleans, all the dogs swim, one of the cats swims...}
}

== The Tree
@n The tree on the right tries to classify the *species* of an animal based on the other data. Write are least *two things you notice* about the tree.
@blanklines{3}{
@ifsoln{It will never classify anything as a tarantula! All of the nodes compare values to a Boolean (true/false), except for the nodes where `sex` is compared to a String. It never uses the `mammal` column}
}

@n What is the shortest possible path? @fitb{3em}{@ifsoln{2}} The longest? @fitb{3em}{@ifsoln{3}} How would this tree classify Charlotte? @fitb{4em}{@ifsoln{dog}} Shadestar? @fitb{}{@ifsoln{dog}}

== The Results

@n This tree will _correctly_ classify 4 out of 4 dogs in this dataset! It does well with cats, too: 4 out of 5 of the cats will be classified correctly, with 1 classified as a "dog". We've added this information to the first two rows of the table below. Can you complete the rest?

[cols="1a,^1a,^1a,^1a,^1a,^1a", options="header"]
|===
|_actual_ species| predicted cat   | predicted dog   | predicted lizard | predicted snail | predicted tarantula
|"dog"           |0 / 4@hspace{2ex}|4 / 4@hspace{2ex}|0 / 4@hspace{2ex} |0 / 4@hspace{2ex}| 0 / 4@hspace{2ex}
|"cat"           |4 / 4@hspace{2ex}|1 / 5@hspace{2ex}|0 / 5@hspace{2ex} |0 / 5@hspace{2ex}| 0 / 5@hspace{2ex}
|"lizard"        | @ifsoln{0} / 2  | @ifsoln{2} / 2  | @ifsoln{0} / 2   | @ifsoln{0} / 2  | @ifsoln{0} / 2
|"snail"         | @ifsoln{0} / 2  | @ifsoln{2} / 2  | @ifsoln{0} / 2   | @ifsoln{0} / 2  | @ifsoln{0} / 2
|"tarantula"     | @ifsoln{2} / 2  | @ifsoln{0} / 2  | @ifsoln{0} / 2   | @ifsoln{0} / 2  | @ifsoln{0} / 2
|===
