= Computing Standard Deviation

Here are the ages of different cats at the shelter: _1, 7, 1, 1, 2, 2, 3, 1, 5, 7_

@n How many cats are represented in this sample? @fitb{5ex}{@ifsoln{10}}

@vspace{1ex}

The *distribution* of these ages is shown in the @vocab{histogram} below:

@ifnotsoln{@image{../images/stdev-cat-age.png, 100%}}
@ifsoln{@centered-image{../images/histogram-w-arrows.png, 75%}}

@n Describe the shape of this histogram. @fitb{}{@ifsoln{slight right skew}}

@n What is the mean age of the cats in this dataset? @fitb{}{@ifsoln{3}}

@n How many cats are 1 year old? 2 years old? Fill in the table below. The first column has been done for you.

[.sideways-pyret-table, cols=">1,^1,^1,^1,^1,^1,^1,^1"]
|===
| age   |1| 	2    | 	   3    |    4     |    5     |    6     | 	  7
| frequency |4|@ifsoln{2}|@ifsoln{1}|@ifsoln{0}|@ifsoln{1}|@ifsoln{0}|@ifsoln{2}
|===

@n *Draw a star to locate the mean on the x-axis of the histogram above*.

@n For each cat in the histogram above, *draw a horizontal arrow* under the axis from your star to the cat's interval, and *label the arrow with its distance from the mean*. (For example, if the mean is 3 and a cat is in the 1yr interval, your arrow would stretch from 1 to 3, and be labeled with the distance "2")

@vspace{1ex}

*To compute the standard deviation we square each distance and take the average, then take the square root of the average.*


@n We've recorded the ages (N=10) shown in the histogram above in the table below, and listed the distance-from-mean for the four 1-year-old cats for you. As you can see, 1 year-olds are 2 years away from the mean, so their squared distance is 4. Complete the table.


@ifnotsoln{
[.sideways-pyret-table, cols="^3,^1,^1,^1,^1,^1,^1,^1,^1,^1,^1"]
|===
| age of cat  		     | 1 | 1 | 1 | 1 | 2 | 2 | 3 | 5 | 7 | 7
| distance from mean     | 2 | 2 | 2 | 2 |   |   |   |   |   |
| squared distance 	     | 4 | 4 | 4 | 4 |   |   |   |   |   |
|===
}

@ifsoln{
[.sideways-pyret-table, cols="^3,^1,^1,^1,^1,^1,^1,^1,^1,^1, ^1"]
|===
| age of cat  			| 1 | 1 | 1 | 1 | 2 | 2 | 3 | 5	|  7 |  7
| distance from mean (3)| 2 | 2 | 2 | 2 | 1 | 1 | 0 | 2 |  4 |  4
| squared distance 		| 4 | 4 | 4 | 4 | 1 | 1 | 0 | 4 | 16 | 16
|===
}

@n Add all the squared distances. What is their sum? @fitb{}{@ifsoln{54}}

@n There are N=10 distances. What is N-1? @fitb{4rem}{@ifsoln{9}} @hspace{2rem} Divide the sum by _N-1_. What do you get? @fitb{}{@ifsoln{6}}

@n Take the square root to find the *standard deviation*! @fitb{}{@ifsoln{~2.45}}
