= Discover Inverse Operations: Multiplication and Division
++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }

  /* TODO(Emmanuel): after workbooks go to print, investigate
     whether this can be pushed to shared.less  */
  body.workbookpage #preamble_disabled { display: none; }
  body.workbookpage .sect1.lesson-section-1 .sectionbody {
    padding: 0;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    flex-grow: 1;
  }
</style>
++++
== From Multiplying by Fractions to Dividing by Whole Numbers

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@show{(coe  '(* 20 1/4))}                | @show{(coe '(/ 20 4))}
|@ifsoln{@math{20 \times \frac{1}{4}}}    | @ifsoln{@math{20 \div 4}}
|===

@n Under each Circle of Evaluation, write the equivalent arithmetic expression.

@n What will the first Circle evaluate to? @fitb{5em}{5} @hspace{5em} The second Circle? @fitb{5em}{5}

@n What do you Notice? What do you Wonder? @fitb{}{@ifsoln{Both expressions evaluate to 5. One has multiplication and one has division. One has 4 and one has @math{\frac{1}{4}}}}

@fitb{}{}

@center{**Did you know that multiplying by @math{\frac{1}{4}} is the same as dividing by @math{4}?**}

@n In the table below, draw another pair of Circles to demonstrate how _multiplying a fraction_ produces the same result as _dividing by its reciprocal._ Then write the equivalent arithmetic expression for each of your Circles.


[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @showsoln{(coe  '(* 30 1/5))} | @showsoln{(coe '(/ 30 5))}
| @ifsoln{@math{30 \times \frac{1}{5} = 6}} | @ifsoln{@math{30 \div 5 = 6}}
|===

@vspace{1ex}

== From Dividing by Fractions to Multiplying by Whole Numbers

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@show{(coe '(/ 20 1/4))}  | @show{(coe  '(* 20 4))}
| @ifsoln{@math{20 \div \frac{1}{4}}}| @ifsoln{@math{20 \times 4}}
|===

@n What will the first Circle evaluate to? @fitb{5em}{80}  @hspace{5em} The second Circle? @fitb{5em}{80}

@n How is this pair of Circles similar to the first pair on this page? How is it different? @fitb{}{@ifsoln{The same values are being used, but this time we are *dividing* by the fraction,}}

@fitb{}{@ifsoln{rather than dividing by the whole number. As a result, we get a larger outcome.}}

@center{**Did you know that dividing by @math{\frac{1}{4}} is the same as multiplying by @math{4}?**}

@n In the table below, draw another example like the one above to show how dividing by a fraction is the same as multiplying by its reciprocal.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @showsoln{(coe '(/ 10 1/2))} | @showsoln{(coe  '(* 20 2))}
| @ifsoln{@math{10 \div \frac{1}{2} = 20}}| @ifsoln{@math{20 \times 2 = 20}}
|===


