= Programming with the Multiplicative Inverse

== Examples and the Multiplicative Inverse

Use the @starter-file{multiplicative-inverse} to complete this page. *Do not click "Run" yet.*

@n Below, place a checkmark next to each of the examples that you *predict* will pass when you click "Run".

@hspace{2em} @fitb{1em}{} @hspace{1em}  `30 * 1/3 *is* 10`

@hspace{2em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `25 * (1/5) *is* 5`

@hspace{2em} @fitb{2em}{} @hspace{1em} `1/3 * 2 *is* 2`

@hspace{2em} @fitb{2em}{} @hspace{1em} `(2 * 2) * 1/7 *is* 4/7`

@hspace{2em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `1/9 * (2 * 4) *is* 8/9`

@hspace{2em} @fitb{2em}{} @hspace{1em} `9/10 *is* 10/9`

@hspace{2em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `2/5 *is* 2 / (1/5)`

@hspace{2em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `27/20 * 20/27 *is* 20/20`

@n Click "Run." Select "Show Details" to the right of `examples-block-1`. Using the information provided, fill in the blanks below to describe the examples that failed.

- Test # @fitb{3em}{@ifsoln{2}} failed because @fitb{}{}

- Test # @fitb{3em}{@ifsoln{2}} failed because @fitb{}{}

- Test # @fitb{3em}{@ifsoln{2}} failed because @fitb{}{}

- Test # @fitb{3em}{@ifsoln{2}} failed because @fitb{}{}

@n Edit each of the *failing* examples on the left so that _all examples pass_ when you click "Run". Be sure to change *only* the part of the example after the `is`! Describe one of the changes you had to make. @fitb{}{}

@fitb{}{}

@fitb{}{}

== Revisiting "Is the Order of Operations Universal?"



@n *Let's explore examples-block-3.* Below line 26 (`3: My Own Example Block`), create a block of 5 passing examples of your own. @ifproglang{pyret}{Be sure to enter `examples:` at the beginning, and then close by typing in `end`.} Hit "Run" to see if your examples pass. If not, revise them until they do. If you encountered an error message along the way, describe it here: @fitb{}{}

@fitb{}{}

@fitb{}{}
