= Programming with the Multiplicative Inverse

== Examples and the Multiplicative Inverse

Use the @starter-file{multiplicative-inverse} to complete this page. *Do not click "Run" yet.*

@n Below, place a checkmark next to each of the examples that you *predict* will pass when you click "Run".

@hspace{2em} @fitb{1em}{} @hspace{1em}  `30 * 1/3 *is* 10` @hspace{8em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `1/9 * (2 * 4) *is* 8/9`

@hspace{2em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `25 * (1/5) *is* 5` @hspace{7.5em} @fitb{2em}{} @hspace{1em} `9/10 *is* 10/9`


@hspace{2em} @fitb{2em}{} @hspace{1em} `1/3 * 2 *is* 2` @hspace{9em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `2/5 *is* 2 / (1/5)`


@hspace{2em} @fitb{2em}{} @hspace{1em} `(2 * 2) * 1/7 *is* 4/7` @hspace{5em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `27/20 * 20/27 *is* 20/20`

@n Click "Run." Select "Show Details" to the right of `examples-block-1`. Using the information provided, fill in as many of the blanks as needed below to describe the examples that failed.

@hspace{2em} Test # @fitb{3em}{@ifsoln{2}} failed because @fitb{}{}

@hspace{2em} Test # @fitb{3em}{@ifsoln{3}} failed because @fitb{}{}

@hspace{2em} Test # @fitb{3em}{@ifsoln{6}} failed because @fitb{}{}

@hspace{2em} Test # @fitb{3em}{@ifsoln{7}} failed because @fitb{}{}

@n Edit each of the *failing* examples on the left so that _all examples pass_ when you click "Run". Be sure to change *only* the part of the example after the `is`! Describe one of the changes you had to make. @fitb{}{}

@fitb{}{}

@fitb{}{}

== Revisiting "Is the Order of Operations Universal?"

Use the @starter-file{multiplicative-inverse-2} to answer the questions below. *Do not click "Run" yet.*

@n Below, place a checkmark next to each of the examples that you *predict* will pass when you click "Run".

@hspace{2em} @fitb{1em}{} @hspace{1em}  `((40 * 12) / 2) *is* (40 * (12 / 2))`

@hspace{2em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `((6 / 12) * 3) *is* (6 / (12 * 3))
`

@hspace{2em} @fitb{2em}{} @hspace{1em} `((5 * 9) / 15)  *is* (5 * (9 / 15))`

@hspace{2em} @fitb{2em}{} @hspace{1em}  `((8 / 4) * 25) *is* (8 / (4 * 25))`

@hspace{2em} @fitb{2em}{@ifsoln{x}} @hspace{1em} `((90 * 1) / 2) *is* (90 * (1 / 2))`


@n Click "Run." Select "Show Details" to the right of `examples-block-1`. Using the information provided, fill in as many blanks as needed below to describe the examples that failed.

@hspace{2em} Test # @fitb{3em}{@ifsoln{2}} failed because @fitb{}{}

@hspace{2em} Test # @fitb{3em}{@ifsoln{4}} failed because @fitb{}{}

@hspace{2em} Test # @fitb{3em}{} failed because @fitb{}{}


@n Notice that all of the examples appear to follow the same pattern in terms of groupings. Why do you think *some* of the examples passed, but others did not?  @fitb{}{}

@fitb{}{}

@fitb{}{}
