= Correlations in the Animals Dataset

@vspace{1ex}

@n In the Interactions Area, create a scatter plot for the Animals Dataset, using `"pounds"` as the xs and `"weeks"` as the ys.

- *Form:* Does the point cloud appear linear or non-linear? @fitb{}{@ifsoln{_linear_}}
- *Direction:* If it's linear, does it appear to go up or down as you move from left to right?
@fitb{}{@ifsoln{_up_}}
- *Strength:* Is the point cloud tightly packed, or loosely dispersed?
@fitb{}{@ifsoln{_loosely dispersed_}}
- Would you predict that the @math{r}-value is positive or negative? @fitb{}{@ifsoln{_positive_}}
- Will it be closer to zero, closer to ±1, or in between? @fitb{}{@ifsoln{_+1_}}
- What @math{r}-value, does Pyret compute when you type `r-value(animals-table, "pounds", "weeks")`?
@fitb{}{@ifsoln{_0.648_}}
- Does this match your predictions?

@fitb{}{}

@fitb{}{}

@vspace{1ex}

@n In the Interactions Area, create a scatter plot for the Animals Dataset, using `"age"` as the xs and `"weeks"` as the ys.

- *Form:* Does the point cloud appear linear or non-linear? @fitb{}{@ifsoln{_linear_}}
- *Direction:* If it's linear, does it appear to go up or down as you move from left to right?
@fitb{}{@ifsoln{_up_}}
- *Strength:* Is the point cloud tightly packed, or loosely dispersed?
@fitb{}{@ifsoln{_loosely dispersed_}}
- Would you predict that the @math{r}-value is positive or negative? @fitb{}{@ifsoln{_positive_}}
- Will it be closer to zero, closer to ±1, or in between? @fitb{}{@ifsoln{_+1_}}
- What @math{r}-value does Pyret compute? @fitb{}{@ifsoln{_0.448_}}
- Does this match your prediction?
@fitb{}{}
@fitb{}{}

@vspace{1ex}

@n Is this correlation *stronger* or *weaker* than the correlation for `"pounds"`? @fitb{}{@ifsoln{_Weaker._}}
- What does that _mean_?

@fitb{}{@ifsoln{_Weight is a better predictor for adoption time than age of the animal._}}

@fitb{}{}

@fitb{}{}
