= Correlations in the Animals Dataset

@n In the Interactions Area, create a scatter plot for the Animals Dataset, using `"pounds"` as the xs and `"weeks"` as the ys.

- *Form:* Does the point cloud appear linear or non-linear? @fitb{35ex}{@ifsoln{_linear_}}
- *Direction:* If it's linear, does it appear to go up or down as you move from left to right?
@span{.blankline}{@ifsoln{_up_}}
- *Strength:* Is the point cloud tightly packed, or loosely dispersed?
@span{.blankline}{@ifsoln{_loosely disperesed_}}
- Would you predict that the @math{r}-value is positive or negative? @fitb{30ex}{@ifsoln{_positive_}}
- Will it be closer to zero, closer to ±1, or in between? @fitb{35ex}{@ifsoln{_+1_}}
- Have Pyret compute the @math{r}-value, by typing `r-value(animals-table, "pounds", "weeks")`.
@span{.blankline}{@ifsoln{_0.648_}}
- Does this match your prediction?
@span{.blankline}{}


@n In the Interactions Area, create a scatter plot for the Animals Dataset, using `"age"` as the xs and `"weeks"` as the ys.

- *Form:* Does the point cloud appear linear or non-linear? @fitb{35ex}{@ifsoln{_linear_}}
- *Direction:* If it's linear, does it appear to go up or down as you move from left to right?
@span{.blankline}{@ifsoln{_up_}}
- *Strength:* Is the point cloud tightly packed, or loosely dispersed?
@span{.blankline}{@ifsoln{_loosely dispersed_}}
- Would you predict that the @math{r}-value is positive or negative? @fitb{30ex}{@ifsoln{_positive_}}
- Will it be closer to zero, closer to ±1, or in between? @fitb{35ex}{@ifsoln{_+1_}}
- Have Pyret compute the @math{r}-value. @fitb{35ex}{@ifsoln{_0.448_}}
- Does this match your prediction?
@span{.blankline}{}


@n Is this correlation stronger or weaker than the correlation for `"pounds"`? What does that _mean_?

@span{.blankline}{@ifsoln{_Weaker. Weight is a better predictor for adoption time than age of the animal._}}
@span{.blankline}{}
@span{.blankline}{}
