= Correlation Does Not Imply Causation!

Here are some possible correlations and the nonsense headlines a confused journalist might report as a result.  In reality, the correlations have absolutely no causal relationship; they come about because both of them are related to another variable that’s lurking in the background.

*Can you think of another variable for each situation that might be the actual cause of the correlation and explain why the headlines the paper ran based on the correlations are nonsense?*

*Correlation:* For a certain psychology test, the amount of time a student studied was negatively correlated with their score! 
 
*Headline:* "Students who study less do better!"

@span{.blankline}{@ifsoln{Struggling students _needed_ to study more; they would have done even worse if they'd studied less!}}
@span{.blankline}{}


*Correlation:* Weekly data gathered in a city throughout the year showed a positive correlation between ice cream consumption and drowning deaths.

*Headline:* "Drowning Deaths are Good for Ice Cream Sales!"

@span{.blankline}{@ifsoln{Warmer weather affects both; they have no effect on one another.}}
@span{.blankline}{}

*Correlation:* A negative correlation was found between how much time students talked on the phone and how much they weighed.

*Headline:* "Students Lose Weight by Talking on the Phone!"

@span{.blankline}{@ifsoln{Gender is a confounder: women tend to weigh less and talk more than men.}}
@span{.blankline}{}

