= Correlation Does Not Imply Causation!

Here are some possible correlations that have absolutely no causal relationship; they come about either by chance or because both of them are related to another variable that’s (often) lurking in the background. Explain one reason why it might *not make sense* to make the claim in the headline based on the correlation found.



*Correlation:* For a certain psychology test, the amount of time a student studied was negatively correlated with their score! 
 
*Headline:* "Students who study less do better!"

@span{.blankline}{@ifsoln{Struggling students _needed_ to study more; they would have done even worse if they'd studied less!}}
@span{.blankline}{}


*Correlation:* Weekly data gathered in a city throughout the year showed a positive correlation between ice cream consumption and drowning deaths.

*Headline:* "Drowning Deaths are Good for Ice Cream Sales!"

@span{.blankline}{@ifsoln{Warmer weather affects both; they have no effect on one another.}}
@span{.blankline}{}

*Correlation:* A negative correlation was found between how much time students talked on the phone and how much they weighed.

*Headline:* "Students Lose Weight by Talking on the Phone!"

@span{.blankline}{@ifsoln{Gender is a confounder: women tend to weigh less and talk more than men.}}
@span{.blankline}{}

