= Correlations in My Dataset
++++
<style>
body:not(.LessonPlan) .paragraph { min-height: 7ex; }
</style>
++++

@vspace{2ex}

@n There may be a correlation between @fitbruby{20em}{}{column} and
@fitbruby{19em}{}{column}.

I think it is a
@fitbruby{22em}{}{strong/weak}, @fitbruby{22em}{}{positive/negative}
correlation, 

because @fitb{}{}

It might be stronger if I looked at @fitbruby{43em}{}{a sample or extension of my
data}.

@vspace{6ex}
@span{.sectionbreak}{}
@vspace{4ex}

@n There may be a correlation between @fitbruby{20em}{}{column} and
@fitbruby{19em}{}{column}.

I think it is a
@fitbruby{22em}{}{strong/weak}, @fitbruby{22em}{}{positive/negative}
correlation,

because @fitb{}{}

It might be stronger if I looked at @fitbruby{43em}{}{a sample or extension of my
data}.

@vspace{6ex}
@span{.sectionbreak}{}
@vspace{4ex}

@n There may be a correlation between @fitbruby{20em}{}{column} and
@fitbruby{19em}{}{column}.

I think it is a
@fitbruby{22em}{}{strong/weak}, @fitbruby{22em}{}{positive/negative}
correlation,

because @fitb{}{}

It might be stronger if I looked at @fitbruby{43em}{}{a sample or extension of my
data}.
