= Identifying Form, Direction and Strength

++++
<style>
#content table table {background: transparent; margin: 0px;}
#content td {padding: 0px !important;}
#content table table td p {white-space: pre-wrap;}
</style>
++++

Can you identify the Form, Direction, & Strength of these displays? *Note:* If the form is non-linear, we shouldn’t report direction - a curve may rise and then fall

[cols="^.^1a,^.^15a,^.^1a,^.^15a", frame="none"]
|===
|*A*
| @centered-image{../images/A.gif, "", 350} 
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! Non-Linear 	! None
! *Direction*: 	! Positive 	! Negative 		! None
! *Strength*: 	! Strong 	! Weak 			! None
!===

|*B*
| @centered-image{../images/B.gif, "", 350}
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! Non-Linear 	! None
! *Direction*: 	! Positive 	! Negative 		! None
! *Strength*: 	! Strong 	! Weak 			! None
!===

|*C*
| @centered-image{../images/C.gif, "", 350} 
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! Non-Linear 	! None
! *Direction*: 	! Positive 	! Negative 		! None
! *Strength*: 	! Strong 	! Weak 			! None
!===

|*D*
| @centered-image{../images/D.gif, "", 350}
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! Non-Linear 	! None
! *Direction*: 	! Positive 	! Negative 		! None
! *Strength*: 	! Strong 	! Weak 			! None
!===

|*E*
| @centered-image{../images/E.gif, "", 350}
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! Non-Linear 	! None
! *Direction*: 	! Positive 	! Negative 		! None
! *Strength*: 	! Strong 	! Weak 			! None
!===

|*F*
| @centered-image{../images/F.gif, "", 350}
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Form*:		! Linear 	! Non-Linear 	! None
! *Direction*: 	! Positive 	! Negative 		! None
! *Strength*: 	! Strong 	! Weak 			! None
!===

|===
