= Reflection on Form, Direction and Strength

@n What has to be true about the _shape_ of a relationship in order to start talking about a correlation?

@fitb{}{@ifsoln{_It must be linear_}}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n What is the difference between a _weak_ relationship and a _negative_ relationship? 


@fitb{}{@ifsoln{_A weak relationship is one in which knowing the x-value does not allow us to predict the y-value very well, and the points_}}

@fitb{}{@ifsoln{_are not clustered tightly around a line whereas, if a relationship is negative, it means that one_}}

@fitb{}{@ifsoln{_variable decreases as the other increases._}}

@fitb{}{}

@n What is the difference between a _strong_ relationship and a _positive_ relationship?

@fitb{}{@ifsoln{_A strong relationship is one in which knowing the x-value allows us to predict the y-value very well, and the points_}}

@fitb{}{@ifsoln{_are clustered tightly around a line whereas, if a relationship is positive, it means that the_}}

@fitb{}{@ifsoln{_variables increase together._}}

@fitb{}{}

@n If we find a strong relationship in a sample from a larger population, will that relationship _always hold_ for the whole population?

@fitb{}{@ifsoln{_No. Maybe the sample was biased, or maybe it was random but we *just happened* to choose points_}}

@fitb{}{@ifsoln{_for which there is a correlation._}}

@fitb{}{}

@fitb{}{}


@n A news report claims that after surveying __10 million people__, a positive correlation was found between how much chocolate a person eats and how happy they are. Does this mean eating chocolate almost certainly makes you happier?

@fitb{}{@ifsoln{No. A correlation drawn from a giant sample can still be a weak correlation! Sample size is not connected to strength.}}

@fitb{}{}

@fitb{}{}

@fitb{}{}
