= Reflection on Form, Direction and Strength

@n What has to be true about a relationship in order to proceed with looking for a correlation?

@span{.blankline}{@ifsoln{_it must be linear_}}

@n What is the difference between a _weak_ relationship and a _negative_ relationship? 


@span{.blankline}{@ifsoln{_A weak relationship is one in which knowing the x-value does not allow us to predict the y-value very well,_}} 
@span{.blankline}{@ifsoln{_whereas, if a relationship is negative, it means that one variable decreases as the other increases._}}
@span{.blankline}{}

@n What is the difference between a _strong_ relationship and a _positive_ relationship?

@span{.blankline}{@ifsoln{_A strong relationship is one in which knowing the x-value allows us to predict the y-value with relative accuracy,_}} 
@span{.blankline}{@ifsoln{_whereas, if a relationship is positive, it means that the variables increase together._}}
@span{.blankline}{}

@n If we find a strong relationship in a sample, can we always infer that relationship holds for the whole population?

@span{.blankline}{}
@span{.blankline}{}
@span{.blankline}{}

@n Suppose we have two correlations, one drawn from 10 data points and one drawn from 50. If both correlations are identical in direction and strength, should we trust them equally when making an inference about the larger population?

@span{.blankline}{}
@span{.blankline}{}
@span{.blankline}{}
