= Compound Inequalities

@lesson-description{Students learn to compose inequalities using the concepts of union and intersection, and solve problems using compound inequalities. Finally, they apply what they've learned to set screen boundaries in their game.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-simple-inequalities}

| Lesson Goals
| Students will be able to:

* Describe how functions can work together.
* Describe the solution set of a compound inequality
* Make mathematical adjustments relevant to their game.

| Student-Facing Lesson Goals
|
* I can use two or more inequalities together and describe the area they enclose.
* I can tell someone else how two or more @vocab{function}s work together.
* I can make adjustments to a program based on how the program behaves.

| Materials
|
@ifproglang{wescheme}{
* Lesson slides template (@link{https://docs.google.com/presentation/d/1-Ey-m1iwpwIQt_nMbWrobg8b8AGFPBokM68U-lEgANA/edit?usp=sharing, Google Slides})
}
@ifproglang{pyret}{
* Lesson slides template (@link{https://drive.google.com/open?id=1kKYXX9tdZhYDjRYrrJU0TXajLVdnEcs5HSOgkqCZIcE, Google Slides})
}
* Inequalities Explore worksheet (@workbook-link{pages/and-or.adoc, original}, @link{solution-pages/and-or.adoc, solutions})
* Design Recipe: onscreen? (@workbook-link{pages/onscreen.adoc, original}, @link{solution-pages/onscreen.adoc, solution})

Bootstrap Formative Assessments

* Booleans Review (@link{https://quizizz.com/admin/quiz/5d9919516dbee7001e08a4a0, Quizizz}, @link{https://teacher.desmos.com/activitybuilder/custom/5d991ac49b9b292020c18108, Desmos Activity})

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|
- Desmos Inequalities Bundle (@link{https://teacher.desmos.com/inequalities, Desmos Activities})
- Inequalities & Graphing Inequalities (@link{https://quizizz.com/admin/quiz/56cf6ac2bb56dfc267b35f94/inequalities-and-graphing-inequali, Quizizz})
- Inequality Graph Illustrator (@link{https://www.geogebra.org/m/Huq24Spq, Geogebra})
- Graphing Compound Inequalities (@link{https://quizizz.com/admin/quiz/5846cda05c74a6041c47566b/graphing-compound-inequalities, Quizizz})

| Key Points for the Facilitator
|
@ifproglang{wescheme}{
* Role-playing can help students understand the job of `onscreen`?, and how it relates to `safe-left?` and `safe-right?`.
}
@ifproglang{pyret}{
* Role-playing can help students understand the job of `is-onscreen`, and how it relates to `is-safe-left` and `is-safe-right`.
}
* If a student's `TARGET` and `DANGER` image seem to be "getting stuck" on the edge of the screen, the student may have to adjust the side boundaries depending on the size of their images.
* The code for the boundary functions in the game is _exactly the same_ as in Sam the Butterfly.

|===

== Warmup

Students should have their computer, contracts page, and pencil and be logged in to
@ifproglang{wescheme}{ @link{https://www.wescheme.org, WeScheme     } }
@ifproglang{pyret}{    @link{https://code.pyret.org, code.pyret.org } }
with their Game Project file open.

== Compound Inequalities @duration{10 minutes}

=== Overview
Students consider the need to _compose_ inequalities, and think about how to write them.

=== Launch
We use inequalities for lots of things:

- Is it hot out? (@math{temperature \gt 80°})
- Did I get paid enough for painting that fence? (@math{temperature \lt $100})
- Are the cookies finished baking? (@math{timer = 0})

Have students come up with other examples.

But many times we need to _combine_ inequalities:

- Should I go to the beach? (@math{temperature \gt 80°} and @math{weather = "sunny"})
- Was this burrito worth the price? (@math{taste = "delicious"} and @math{price \leq $20})

Have students come up with other examples.

Guide students through other examples of `and` and `or` with various statements, such as "I'm wearing a red shirt AND I'm a math teacher, true or false?" or "I'm an NBA basketball star OR I'm having pizza for lunch, true or false?". This can make for a good sit-down, stand-up activity, where students take turns saying compound boolean statements and everyone stands if that statement is true for them.

=== Investigate
Both mathematics and programming have ways of combining - or _composing_ - inequalities.

Have students complete @workbook-link{pages/and-or.adoc, Compound Inequalities}.

=== Synthesize
- Be really careful to check for understanding here. __Expresions using `and` only produce `true` if both of their sub-expressions are `true`. Expresions using `or` produce `true` if *either* of their sub-expressions are `true`.__

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Strategies for English Language Learners}
When describing compound inequalities, be careful not to use "english shortcuts". For example, we might say "I am holding a marker _and_ an eraser" instead of "I am holding a marker _and_ I am holding an eraser." These sentences mean the same thing, but the first one obscures the fact that "and" joins two complete phrases. For ELL/ESL students, this is unecessarily adds to cognitive load!
|===


== Protecting Sam on Both Sides @duration{30 minutes}

=== Overview
Students solve a word problem involving compound inequalities, using `and` to compose the simpler boundary-checking functions from the previous lesson.

=== Launch
@ifproglang{wescheme}{
*Note:* In this programming language, question marks are prounced "huh?". So `safe-left?` would be prounounced "safe left huh?" This can be a source of some amusement for students!
}

- Recruit three student volunteers to roleplay the functions `safe-left?`, `safe-right?` and `onscreen?`. Give them 1 minute to read the contract and code, as written in the program.

- As in the previous lesson, ask the volunteers what their name, Domain and Range are, and then test them out by calling out their name, followed by a number. (For example, "(safe-left? 20)!", "(safe-right? -100)!", "(onscreen? 829)!") *Note"* the code for `onscreen` _calls the safe-left function!_. So the student roleplaying `onscreen` should turn to `safe-left` and give the input to them.

For example:
@ifproglang{wescheme}{

- *Facilitator*: "onscreen-huh 70"
- *onscreen?* (turns to safe-left?): "safe-left-huh 70"
- *safe-left?*: "true"
- *onscreen?* (turns back to facilitator): "true" +
{empty} +

- *Facilitator*: "onscreen-huh -100"
- *onscreen?* (turns to safe-left?): "safe-left-huh -100"
- *safe-left?*: "false"
- *onscreen?* (turns back to facilitator): "false" +
{empty} +

- *Facilitator*: "onscreen-huh 900"
- *onscreen?* (turns to safe-left?): "safe-left-huh 900"
- *safe-left?*: "true"
- *onscreen?* (turns back to facilitator): "true" +
{empty} +

*Ask the rest of the class*

- What is the problem with `onscreen?`?
+
_It's only talking to `safe-left?`, it's not checking with ``safe-right?``_
- How can `onscreen?` check with both?
+
_It needs to talk to `safe-left?` AND ``safe-right?``_

Have students complete @workbook-link{pages/onscreen.adoc, Design Recipe: onscreen?}. When this functions is entered into WeScheme, students should now see that Sam is protected on _both_ sides of the screen.
}

@ifproglang{pyret}{
- *Facilitator*: "is-onscreen 70"
- *is-onscreen* (turns to is-safe-left): "is-safe-left 70"
- *is-safe-left*: "true"
- *is-onscreen* (turns back to facilitator): "true" +
{empty} +

- *Facilitator*: "onscreen-huh -100"
- *is-onscreen* (turns to is-safe-left): "safe-left-huh -100"
- *is-safe-left*: "false"
- *is-onscreen* (turns back to facilitator): "false" +
{empty} +

- *Facilitator*: "onscreen-huh 900"
- *is-onscreen* (turns to is-safe-left): "safe-left-huh 900"
- *is-safe-left*: "true"
- *is-onscreen* (turns back to facilitator): "true" +
{empty} +

*Ask the rest of the class-* +
* What is the problem with `is-onscreen`?
+
_It's only talking to `is-safe-left`, it's not checking with ``is-safe-right``_
* How can `is-onscreen` check with both?
+
_It needs to talk to `is-safe-left` AND ``is-safe-right``_

Have students complete @workbook-link{pages/onscreen.adoc, Design Recipe: is-onscreen}. When this functions is entered into WeScheme, students should now see that Sam is protected on _both_ sides of the screen.
}

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Extension Option}
What if we wanted to keep Sam safe on the top and bottom edges of the screen as well?  What additional functions would we need?  What functions would need to change?}

|===
== Boundry Detection in the Game @duration{10 minutes}

=== Overview
Students identify common patterns between 2-dimensional boundary detection and detecting whether a player is onscreen. They apply the same problem-solving and narrow mathematical concept from the previous lesson to a more general problem.

=== Launch

Have students open their in-progress game file and press Run.

- How are the `TARGET` and `DANGER` behaving right now? +
_They move across the screen._

- What do we want to change? +
_We want them to come back after they leave one side of the screen._

- How do we know when an image has moved off the screen? +
_We can see it._

- How can we make the computer understand when an image has moved off the screen? +
_We can teach the computer to compare the image's @vocab{coordinates} to a numeric boundary, just like we did with Sam the Butterfly!_

=== Investigate

@ifproglang{wescheme}{
Students apply what they learned from Sam the Butterly to fix the `safe-left?`, `safe-right?`, and `onscreen?` functions in their own code.
}
@ifproglang{pyret}{
Students apply what they learned from Sam the Butterly to fix the `is-safe-left`, `is-safe-right`, and `is-onscreen` functions in their own code.
}
Since the screen dimensions for their game are 640x480, just like Sam, they can use their code from Sam as a starting point.

=== Common Misconceptions
- Students will need to test their code with their images to see if the boundaries are correct for them.  Students with large images may need to use slightly wider boundaries, or vice versa for small images.  In some cases, students may have to go back and rescale their images if they are too large or too small for the game.
- Students may be surprised that the same code that "traps Sam" also "resets the `DANGER` and `TARGET`". It's critical to explain that these functions do _neither_ of those things! All they do is test if a coordinate is within a certain range on the x-axis. There is other code (hidden in the teachpack) that determines _what to do if the coordinate is offscreen_. The ability to re-use function is one of the most powerful features of mathematics - and programming!

== Additional Exercises:
- @exercise-link{pages/is-hot.adoc, Design Recipe: Is it Hot?}
- @exercise-link{pages/is-sunny.adoc, Design Recipe: Is it Sunny?}
- @exercise-link{pages/is-beach-day.adoc, Design Recipe: Is a Beach Day?}
