= Compound Inequalities

@lesson-description{Students learn to compose inequalities using the concepts of union and intersection, and solve problems using compound inequalities. Finally, they apply what they've learned to set screen boundaries in their game.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-simple-inequalities}

| Lesson Goals
| Students will be able to:

* Describe how functions can work together.
* Describe the solution set of a compound inequality

| Student-Facing Lesson Goals
|
* I can use two or more inequalities together and describe the area they enclose.
* I can tell someone else how two or more @vocab{function}s work together.
* I can make adjustments to a program based on how the program behaves.

| Materials
|[.materials-links]

@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/1y9X1iLjGKrpu2SNYjbL_oJWrMycvwwaZQB-PsIQW3rw/, Lesson Slides}
}
@ifproglang{pyret}{Lesson slides template (@link{https://docs.google.com/presentation/d/1_PdCxPiY7j8X5FGyJXVIo1eNJqsCrNIMn9_WgocSblM/, Lesson Slides}
}

@material-links

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|
* @link{https://quizizz.com/admin/quiz/5d9919516dbee7001e08a4a0, Booleans Review - Quizizz}


| Key Points for the Facilitator
|

|===

[.old-materials]
Click here to see the @link{https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/units/unit6/index.html, prior unit-based version}

== Compound Inequalities @duration{10 minutes}

=== Overview
Students consider the need to _compose_ inequalities, and think about how to write them.

=== Launch
Students should have their computer, contracts page, and pencil and be logged in to
@ifproglang{wescheme}{ @link{https://www.wescheme.org, WeScheme     } }
@ifproglang{pyret}{    @link{https://code.pyret.org, code.pyret.org } }
with their Game Project file open.

We use inequalities for lots of things:

- Is it hot out? (@math{temperature \gt 80°})
- Are the cookies finished baking? (@math{timer = 0})

Have students come up with other examples.

But many times we need to _combine_ inequalities:

- Should I go to the beach? (@math{temperature \gt 80°} and @math{weather = "sunny"})
- Was this burrito worth the price? (@math{taste = "delicious"} and @math{price \leq $10})

Have students come up with other examples.

Guide students through other examples of `and` and `or` with various statements, such as "I'm wearing a red shirt AND I'm a math teacher, true or false?" or "I'm an NBA basketball star OR I'm having pizza for lunch, true or false?". This can make for a good sit-down, stand-up activity, where students take turns saying compound boolean statements and everyone stands if that statement is true for them.

=== Investigate
Both mathematics and programming have ways of combining - or _composing_ - inequalities.

Have students complete @workbook-link{pages/and-or.adoc}.

=== Synthesize
- Be really careful to check for understanding here. __Expressions using `and` only produce `true` if both of their sub-expressions are `true`. Expressions using `or` produce `true` if *either* of their sub-expressions are `true`.__

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Strategies for English Language Learners}

When describing compound inequalities, be careful not to use "english shortcuts". For example, we might say "I am holding a marker _and_ an eraser" instead of "I am holding a marker _and_ I am holding an eraser." These sentences mean the same thing, but the first one obscures the fact that "and" joins two complete phrases. For ELL/ESL students, this unecessarily adds to cognitive load!
|===



== Additional Exercises:
- @exercise-link{pages/is-hot.adoc}
- @exercise-link{pages/is-sunny.adoc}
- @exercise-link{pages/is-beach-day.adoc}
- @exercise-link{pages/boolean-coe-to-code1.adoc} 
- @exercise-link{pages/boolean-coe-to-code2.adoc} 
