= Image Scatter Plot - Explore

Before we build `image-scatter-plot(animals-table, "pounds", "weeks", species-tag)` ...

@n What Datatype is `species-tag`? @fitb{30em}{@ifsoln{_a function!_}}

@n What does `species-tag` do when you run the program? (_Hint: look for its definition in the @starter-file{image-scatter-plot}!_)

@span{.blankline}{@ifsoln{_It consumes a row and makes a red image of the species name in size 15._}}

@span{.blankline}{}

@n Think about what you expect this `image-scatter-plot` to look like. Then test it out and describe the image you see.

@span{.blankline}{@ifsoln{_Each of the points on the plot is labeled with its species name in red._}}

@span{.blankline}{}

@n What can you learn from this new display that you could not learn from the original image?

@span{.blankline}{@ifsoln{_All of the heavy animals are dogs and the other species weigh under 10 pounds._}}

@n What ideas do you have for how else we could visually format the information in this display so that it would be even more useful?

@span{.blankline}{@ifsoln{_Sample responses: Use more than one color? Use different symbols?_}}

@span{.blankline}{}

@n Find the other two "Helper Methods" in the file (`legs-tag` and `age-tag`). How is the structure of their definitions similar to `species-tag`?

@span{.blankline}{@ifsoln{_They also consume a row and look up a specific variable._}}

@n How is the structure of their definitions different from `species-tag`?

@span{.blankline}{@ifsoln{_The lookup information is used as a size rather than converted to a text image._}}

@n Make an `image-scatter-plot` using `legs-tag`. Then make an `image-scatter-plot` using `age-tag`. What is most interesting to you about the plots you just made?

@span{.blankline}{@ifsoln{_Student responses will vary!_}}

@span{.blankline}{}

@n What would be the first step to making a new `image-scatter-plot` that compares pounds and weeks to adoption, where each point was labeled with the name of the animal instead of its species?

@span{.blankline}{@ifsoln{_We'd need to make a_ `name-tag` _helper function._}}

@span{.blankline}{}

@n Make the new `image-scatter-plot` described above. Record your new helper function here:

@span{.blankline}{@ifsoln{ `fun name-tag(r): text(r["name"], 15, "red") end`}}


