= Image Scatter Plot - Explore

Let's think about this expression before we evaluate it... `image-scatter-plot(animals-table, "pounds", "weeks", species-tag)`

@n What is the data type of `species-tag`? @fitb{30em}{@ifsoln{_a function!_}}

@n What does `species-tag` do? (_Hint: look for its definition in the @starter-file{image-scatter-plot}!_)

@span{.blankline}{@ifsoln{_It consumes a row and makes a red image of the species name in size 15._}}

@span{.blankline}{}

@n Think about the plot you expect this expression will produce. Then click "Run" and type the expression into the Interactions Area to test it out.  Describe the image you see.

@span{.blankline}{@ifsoln{_Each of the points on the plot is labeled with its species name in red._}}

@span{.blankline}{}

@n What can you learn from this new display that you could not learn from the original image?

@span{.blankline}{@ifsoln{_All of the heavy animals are dogs and the other species weigh under 10 pounds._}}

@n How else we could draw the dots in this display, so that it would be even more useful?

@span{.blankline}{@ifsoln{_Sample responses: Use more than one color? Use different symbols?_}}

@span{.blankline}{}

@n Find the other two "Helper Functions" in the file (`legs-tag` and `age-tag`). How are their definitions similar to `species-tag`?

@span{.blankline}{@ifsoln{_They also consume a row and look up a specific variable._}}

@n How are their definitions _different_ from `species-tag`?

@span{.blankline}{@ifsoln{_The lookup information is used as a size rather than converted to a text image._}}

@n Make an image scatter plot using `legs-tag`. Then make another using `age-tag`. What is most interesting to you about the plots you just made?

@span{.blankline}{@ifsoln{_Student responses will vary!_}}

@span{.blankline}{}

@n Suppose we wanted to make an image scatter plot where each point is labeled with the name of the animal. What would we need to define, to use in our `image-scatter-plot(...)` expression?

@span{.blankline}{@ifsoln{_a_ `name-tag` _helper function._}}


@n Make the new image scatter plot described above. Write the definition of your helper function, and the `image-scatter-plot(...)` expression here:

@span{.blankline}{@ifsoln{ `fun name-tag(r): text(r["name"], 15, "red") end`}}

@span{.blankline}{@ifsoln{ `image-scatter-plot(animals-table, "pounds", "weeks", name-tag)`}}

