= Image Scatter Plot - Explore

Before we build `image-scatter-plot(animals-table, "pounds", "weeks", speciestag)` ...

@n What Datatype is `species-tag`? @fitb{30em}

@n What does `species-tag` do when you run the program? (_Hint: look for its definition in the @starter-file{“image-scatter-plot”}!_)

@span{.blankline}{}

@span{.blankline}{}

@n Think about what you expect this `image-scatter-plot` to look like. Then test it out and describe the image you see.

@span{.blankline}{}

@span{.blankline}{}

@n What can you learn from this new display that you could not learn from the original image?

@span{.blankline}{}

@n What ideas do you have for how else we could visually format the information in this display so that it would be even more useful?

@span{.blankline}{}

@span{.blankline}{}

@n Find the other two "Helper Methods" in the file (`legs-tag` and `age-tag`). How is the structure of their definitions similar to `species-tag`?

@span{.blankline}{}

@n How is the structure of their definitions different from `species-tag`?

@span{.blankline}{}

@n Make an `image-scatter-plot` using `legs-tag`. Then make an `image-scatter-plot` using `age-tag`. What is most interesting to you about the plots you just made?

@span{.blankline}{}

@span{.blankline}{}

@n What would be the first step to making a new `image-scatter-plot` that compares pounds and weeks to adoption, where each point was labeled with the name of the animal instead of its species?

@span{.blankline}{}

@span{.blankline}{}

@n Make the new `image-scatter-plot` described above. Record your new helper function here:

@span{.blankline}{}


