= Surface Area of a Rectangular Prism

@description{Students define the shapes used to build a rectangular prism, print them, cut them out, and build the rectangular prism. Then they use their model to calculate the surface area.}

@lesson-prereqs{defining-values}

@keywords{geometry, solid figures, 3-d, 3-dimensional}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* Demonstrate understanding of @vocab{surface area} and use that understanding to calculate surface area of @vocab{rectangular prisms}

| Student-facing Goals
|
* I can explain what @vocab{surface area} is.
* I can use my understanding of surface area to calculate the surface area of any @vocab{rectangular prism}.

| Materials
|[.materials-links]

@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/1Lrx4A_0-SlUQgJSs0PAS9RtaRxe3fIuO852nGi151Zg/, Lesson Slides}
}

@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1kwn9ke2qd-ZYvumgTluhUFCIlkQmuVLRGO9yJ4qBAYQ/, Lesson Slides}
}

@material-links

| Preparation
|
* This lesson requires a printer, scissors and tape.
* Decide whether students will be printing in black & white or in color.
* If you're printing in black & white, colored pencils may be useful for some students.

| Key Points For The Facilitator
|
* This lesson focuses on developing students' understanding of @vocab{Surface Area} of prisms, such that they can build their own formulas. Instructors are encouraged not to reference any pre-defined formulas during the exploration.
|===

== Surface Area

=== Overview
Students build on their experience with writing code to define shapes.  They will define shapes for all of the @vocab{faces} of a @vocab{rectangular prism}, print them, cut them out, and build the rectangular prism. Then they will use their model to calculate the surface area and write code to do the same.

=== Launch

Have students turn to @printable-exercise{prism-explore.adoc} and give them a moment to complete the first two questions.

[.lesson-instruction]
- What do you picture in your mind when you hear @vocab{rectangular prism}?
- What do you picture in your mind when you hear @vocab{surface area}?

Have students open the @starter-file{prism} in their browser and click run.

[.lesson-instruction]
Type `prism` into the Interactions Area to see an image of a rectangular prism. What do you notice about the prism?

_Be sure students notice that the @vocab{faces} and @vocab{dimensions} (Length, Width, and Height) are labeled._

[.lesson-point]
Faces are the flat surfaces on the outside of a solid figure. Edges are the line segments where the faces meet in each of the three dimensions.

[.lesson-instruction]
- The surface area of a prism is calculated by adding the areas of its faces. How many faces does this prism have? How would you describe the faces of this prism?

@ifproglang{wescheme}{
- Skip down to the code on line 19.  It reads `(define lst (list front))`, which defines `lst` to be a _list_ of values.  This list will include all of the faces of the prism, bu right now it only includes `front`.  Add the names of each of the remaining faces to the list. (Order doesn't matter.)
- Once you complete your list, go back up to line 17 and look at the definition for `front`. Type `front` into the interactions area. What do you get?
- Just as `front` has been defined to draw a rectangle whose dimensions are `width` and `height`, you will need to write definitions for each of the other faces of the prism the you put on your list. Start adding definitions on line 18 and add a line for each definition so that all of the faces are defined between `front` and `lst`. Click "Run" and test each of them in the interactions area to make sure that they match the prism you started with.
}

@ifproglang{pyret}{
- Skip down to PART 2 in the code. Type `print-imgs(faces)` into the interactions area. How many rectangles do you see? _One_
- The code in PART 2 says `faces = [list: front, ]` , which defines `faces` to be a list of values. This list will include all of the faces of the prism, but right now it only includes `front`. Add the names of each of the remaining faces to the list. (Order doesn't matter.)

Ensure that students' lists include all six faces of the rectangular prism. Note that if students enter `print-imgs(faces)` in the interactions area again, they will see a variety of error messages - because each of those six faces has yet to be defined.

[.lesson-instruction]
- Once you complete your list, go back up to PART 1 and look at the definition for `front`. Type `front` into the interactions area. What do you get?
- Just as `front` has been defined to draw a rectangle whose dimensions are `width` and `height`, you will need to write definitions for each of the other faces of the prism that you put on your list.
- Click "Run" and test each of them in the interactions area to make sure that they match the prism you started with.}

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{Facilitation Note}
The sample definition was written to make the image of an outlined rectangle with a black and white printer in mind.  If you have access to a color printer in your classroom, you may want students to change the code of `front` to better match what they see in the image of `prism` and code the remaining faces with solid rectangles to match the image they are looking at. If you do not have access to a color printer, but think that colors would support your students, you can have them color the rectangles on the printout before cutting and assembling the prism.

If you do not have a classroom printer, consider splitting this lesson over two days - the Launch segment on Day 1, and the Investigate and Synthesize segments on Day 2. At the end of Day 1, direct students to share their images to you. Print the images and distribute them before beginning the Investigate segment on Day 2.
|===

[.lesson-instruction]
- When you've finished, click "Run" and type
@ifproglang{pyret}{`print-imgs(faces)`.}
@ifproglang{wescheme}{`(print-imgs faces)`.}
What do you Notice? What do you Wonder?
- Do you have enough shapes to cover all of the faces of the prism?
- Read the comments in PART 3 of the file to learn how to print the faces to build your prism.

=== Investigate

Have students cut out and tape together the images they defined to form a 3-dimensional paper model of a rectangular prism. Students will then use their models to calculate the surface area.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

a|
@span{.title}{Supporting students with learning variations}

- Labeling the shapes with face names and/or area before taping them together may help some students.
- Printing two copies of the file (one to cut and one to write on) might best support other students.

|===

[.lesson-instruction]
- Once you've built your prism, use it to help you calculate the surface area of the figure.
- Then, turn to PART 4 in the @starter-file{prism} and define `surface-area` using `LENGTH`, `WIDTH` and `HEIGHT`.

=== Synthesize

* How many definitions did you write in order to calculate the surface area of the prism?
** _Some students may say 4 and some may say 7._

Have students share the codes they wrote to define `surface-area`. Did students all write the code the same way?  Can anyone see other ways that they could have written the code?

- How did building the prism help you to understand surface area?
- How did writing the code for surface area help you to understand surface area?
