= Building a Predictor for Steering Angle

++++
<style>
div#body sub { position: relative; bottom: 0.3em; }
div#body .studentAnswerMedium { min-width: 35pt; }

#preamble_disabled { flex-grow: 0 !important; }
</style>
++++

@link-instructions{This page is designed for use with the @starter-file{self-driving}}

== Using Linear Regression

@n Evaluate `lr-plot` for each variable (e.g. - `lr-plot(training-data, "id", "curve", "steering-angle")`), and use the result to fill in the table below:

[cols="<, ^, ^, ^",options="header"]
|===
| Explanatory Variable 	| 		Slope 	 | 	Intercept 	| @math{S}-value
| `curve`				| @ifsoln{19.5}  | @ifsoln{-0.4}| @ifsoln{37.0}
| `offset` 				| @ifsoln{-2.8}	 | @ifsoln{1.1}	| @ifsoln{37.9}
| `skew` 				| @ifsoln{-2.2}	 | @ifsoln{0.9} | @ifsoln{43.5}
| `speed` 				| @ifsoln{-2.46} | @ifsoln{7.0} | @ifsoln{47.0}
|===

@n How do Pyret's best-fit lines compare to your estimates on @printable-exercise{steering-angle-scatter-plots.adoc} @fitb{}{} +
@fitb{}{@ifsoln{}}

@n Use the values you calculated with `lr-plot` for `curve` to define `curve-predictor` in math and Pyret notation below. Then complete the template in the starter file and click "Run".

[%autowidth, cols="<, >", frame="none", stripes="none"]
|===
| @math{curve\text{-}predictor(curve) = (}@fitbruby{4em}{@ifsoln{19.5}}{@math{m}}@math{\times curve) + }@fitbruby{4em}{@ifsoln{-0.41}}{@math{b}}
| @show{(code '(define (curve-predictor curve) (+ (* (?ANS 19.5) curve) (?ANS -0.41))))}
|===

@n When `curve = 0` (a perfectly straight road), what does our `curve-predictor` estimate the steering angle to be to the nearest degree? @fitbruby{2em}{@ifsoln{≈ 0}}{intercept} @fitbruby{5.5em}{degrees}{units}. Does this make real-world sense? @fitb{}{} +
@fitb{}{@ifsoln{Yes! If the road is straight and the car is centered, there's no reason to steer.}}

@n If the `curve` of the road increases by 1º, the `curve-predictor` expects the steering angle to @fitbruby{8em}{@ifsoln{increase}}{increase/decrease} by @fitbruby{5em}{@ifsoln{19.5º}}{slope}.

@n To generalize what the model _learned_: "the more sharply the road curves, the @fitbruby{10em}{@ifsoln{more}}{less? more?} sharply you need to steer".

== Driving with the Model

@show{(contract "drive" '((predictor ("Row" "Number"))) "Table"
"runs the driving simulator, using predictor to compute the steering angle at each frame")}

@n Read the Domain of `drive` carefully. What do you Notice? @fitb{}{} +
@fitb{}{}

@n Evaluate `drive(curve-predictor)` and read the error carefully. What do you think it is telling us? @fitb{}{} +
@blanklines{1}{@ifsoln{`drive` needs access to full *Rows* of data, but we defined `curve-predictor` to only take in a Number.}}

@vspace{1ex}

*Evaluate `reg-model-code(training-data, [list: "curve"], "steering-angle")`* and read the resulting code carefully. 

@n How is the resulting code *similar* to your `curve-predictor` function? @fitb{}{} +
@blanklines{1}{
@ifsoln{It seems to use the same slope and intercept that I do. It consumes one thing in the domain, and produces a number.}
}

@n How is it *different*? @fitb{}{@ifsoln{`curve-predictor` took in the curve value. }} +
@blanklines{1}{
@ifsoln{This `predictor` appears to take in a Row, and then grab the curve data from inside that row.}
}