= What Predicts Steering Angle?

@link-instructions{
Make scatter plots of `steering-angle` v. each of the four possible explanatory variables in @starter-file{self-driving}.
}

@vspace{1ex}

For each of the plots below:

- Use the scatter plots you made in Pyret to fill in the titles with the missing variables.
- Draw what you think the model (line of best fit) would look like and estimate its slope and y-intercept.
- Explain why you do or don't think the variable will be a good predictor for `steering-angle`.

@vspace{1ex}

Then rank the plots from 1 to 4 based on which you think will make the best predictor. 

[.FillVerticalSpace, cols="1a,1a", stripes="none", frame="none"]
|===
| @n @hspace{5em} *@fitb{8em}{@ifsoln{`skew`}} v. `steering-angle`* 
@center{`predictor1(x)` &#8776; @fitbruby{3em}{}{m} @math{* x +} @fitbruby{3em}{}{b}}
@image{../images/steering-v-skew.png}
 Is this a good predictor? Why or why not? @fitb{}{} +
@blanklines{2}{}
Rank: @fitbruby{8em}{}{1=best, 4=worst}

| @n @hspace{5em} *@fitb{8em}{@ifsoln{`curve`}} v. `steering-angle`*
@center{`predictor2(x)` &#8776; @fitbruby{3em}{}{m} @math{* x +} @fitbruby{3em}{}{b}}
@image{../images/steering-v-curve.png}
Is this a good predictor? Why or why not? @fitb{}{} +
@blanklines{2}{}
Rank: @fitbruby{8em}{}{1=best, 4=worst}

| @n @hspace{5em} *@fitb{8em}{@ifsoln{`speed`}} v. `steering-angle`*
@center{`predictor3(x)` &#8776; @fitbruby{3em}{}{m} @math{* x +} @fitbruby{3em}{}{b}}
@image{../images/steering-v-speed.png}
Is this a good predictor? Why or why not? @fitb{}{} +
@blanklines{2}{}
Rank: @fitbruby{8em}{}{1=best, 4=worst}

| @n @hspace{5em} *@fitb{8em}{@ifsoln{`offset`}} v. `steering-angle`*
@center{`predictor4(x)` &#8776; @fitbruby{3em}{}{m} @math{* x +} @fitbruby{3em}{}{b}}
@image{../images/steering-v-offset.png}
Is this a good predictor? Why or why not? @fitb{}{} +
@blanklines{2}{}
Rank: @fitbruby{8em}{}{1=best, 4=worst}
|===