= Which One Isn't Equivalent? Absolute Value & Negate 2

Identify the circle of evaluation in each row below that doesn’t evaluate to the same things as the others.

++++
<style>
.circleevalsexp { width: auto; }
.chosen::after { content: '❌' !important; }

/* for table cells with immediate .content children, which have immediate
 * .paragraph children: use flex to space them evenly and center vertically
*/
td > .content > .paragraph:has(.circleevalsexp) {
  display: flex;
  align-items: center;
  justify-content: space-around;
}
/* Allow the parent (.paragraph) to control the display of the child elements */
td > .content > .paragraph > p { display: contents; }
</style>
++++

[.FillVerticalSpace, cols="<.^1a,^.^3a,^.^10a",stripes="none", options="header"]
|===
| 	 | |Circles of Evaluation

| @n |
|
@show{(coe '(negate (negate 20)))}
@ifsoln-choice{@show{(coe '(negate (negate -20)))}}
@show{(coe '(abs (negate 20)))}
@show{(coe '(abs (negate -20)))}

| @n |
|
@show{(coe '(negate (negate 3)))}
@show{(coe '(abs (negate 3)))}
@ifsoln-choice{@show{(coe '(negate (abs -3)))}}
@show{(coe '(abs (abs -3)))}

| @n | Let @math{h = 9}
|
@show{(coe '(negate -h))}
@show{(coe '(abs (negate h)))}
@show{(coe '(abs -h))}
@ifsoln-choice{@show{(coe '(negate (negate -h)))}}

| @n| Let @math{h = 6}
|
@show{(coe '(+ (abs h) (- h h)))}
@ifsoln-choice{@show{(coe '(+ (negate h) (- h h)))}}
@show{(coe '(* (/ h h) (abs h)))}

| @n | Let @math{k = 99}
|
@ifsoln-choice{@show{(coe '(+ (abs k) k))}}
@show{(coe '(+ k (negate k)))}
@show{(coe '(+ (abs (+ 45 44)) (negate k)))}

| @n | Let @math{a = 11} and @math{b = 20}.
|
@show{(coe '(abs (+ a b)))}
@show{(coe '(abs (+ b a)))}
@show{(coe '(abs (negate (+ b a))))}
@ifsoln-choice{@show{(coe '(negate (abs (+ a b))))}}
|===