= Transforming the Data
////
* Import Desmos Styles
*
* This includes some inline CSS which loads the Desmos font,
* which includes special glyphs used for icons on Desmos.com
*
* It also defines the classname '.desmosbutton', which is used
* to style all demos glyphs
*
* Finally, it defines AsciiDoc variables for glyphs we use:
* {points}
* {caret}
* {magnifying}
* {wrench}
*
* Here's an example of using these:
* This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}

++++
<style>
/* Shrink vertical spacing on fitbruby */
.fitbruby{ padding-top: 0.5rem; }
td .fitb { text-align: left; }

/* Add some left-and-right margins to code-style font */
.editbox { margin: 0 3px !important; }

table.nomargin { margin-bottom: 0 !important; }
table.nomargin td { 0 0.5em !important }
</style>
++++

@link-instructions{
For this page, you'll need *Slide 8: Wealth-v-Health (Transformed)* of *Fitting Wealth-v-Health and Exploring Logarithmic Models (Desmos)*.
}

@n Compare the two tables below from the Desmos file we are about to work with.

[cols="1a,1a,3a", options="header", frame="none", grid="none", stripes="none"]
|===
| Wealth vs. Health
| Log(Wealth) vs. Health
| What do you Notice or Wonder?

| @image{../images/cropped-wealth-v-health-table.png, 110}
| @image{../images/cropped-log-wealth-v-health-table.png, 110}
| 
@fitb{}{@ifsoln{The 2nd columns are the same, but the 1st columns are really different.}} +
@fitb{}{@ifsoln{The header for the x-column of the 2nd table is a _function_ that takes in the}} +
@fitb{}{@ifsoln{  @hspace{2em} @math{x_1}-value from the first table.}} +
@fitb{}{@ifsoln{The first table is the same one we've seen before.}} +
@fitb{}{} +
@fitb{}{}

|===

== Fitting a Model

@link-instructions{
This slide contains two tables, a list and a function:

[.nomargin, cols="3a,2a", frame="none"]
|===
| 
- `Wealth vs. Health` -- the same table we've seen before.
- @math{y_2} -- a copy of the table's @math{y_1} column
- @math{g(x)} -- a function that takes in a number @math{x}, and produces @math{log_{10}(x)}

|
- `Log(Wealth) vs. Health` -- a new table!
  * _@math{x_2} uses @math{g(x)} on the @math{x_1} column in the first table._
  * _@math{y_2} is our copy of the @math{y_1} column in the first table._
|===

}
@n Notice how the red dots (representing the data points from the original table) are dispersed on the graph.

- Hide these data points from the graph by clicking on the "points" circle ([.desmosbutton]#{points}#) at the top of the y&#8321; column.
- Then click on the triangle ([.desmosbutton]#{caret}#) in front of the folder name to hide the table.
- Turn ON the points for the `Log(Wealth) vs. Health` table by clicking on the "points" circle ([.desmosbutton]#{points}#) at the top of the y&#8322; column

How does the new graph look different from the original graph? @fitb{}{@ifsoln{All the black datapoints are smashed against the y-axis!}}

@fitb{}{@ifsoln{Our log transformation is *really* drastic!}}

@n Scroll to the bottom of the `Log(Wealth) vs. Health` table and click the [.desmosbutton]#{magnifying}# to rescale the graph.

@n Looking at the point cloud, the best model for this dataset would be (circle one): @hspace{3em} @ifsoln-choice{linear} @hspace{3em} quadratic @hspace{3em} exponential

@n Why do you think transforming the *x-values* makes our data look linear? @fitb{}{@ifsoln{The amount of extra income needed to create an extra year of}}

@fitb{}{@ifsoln{predicted lifespan increased exponentially. By taking the log of that income we are "canceling out" that exponential growth and making it linear.}}

@n Move the sliders for @math{m} and @math{b} at the bottom left to find the best-fitting linear model you can:

[cols="^1a", grid="none", frame="none", stripes="none"]
|===
|@math{f(x) = }@fitbruby{10em}{}{slope (m)}@math{x + }@fitbruby{11em}{}{y-intercept / vertical shift}
|===

[cols=".>2a,^1a,^1a", options="header", grid="none", frame="none", stripes="none"]
|===
3+^| Let's compare the model settings from your linear and logarithmic models.

| *Linear* (From above)
| @fitbruby{10em}{@ifsoln{~12 to ~16}}{slope (m)}
| @fitbruby{11em}{@ifsoln{~8 to ~25}}{y-intercept / vertical shift}

| *Logarithmic* (From @printable-exercise{logarithmic3-changing-scale/pages/fitting-logarithmic-models.adoc})
| @fitbruby{10em}{@ifsoln{~12 to ~16}}{log coefficient (a)}
| @fitbruby{10em}{@ifsoln{~8 to ~25}}{vertical shift (k)}
|===


@n How are they similar? @fitb{}{@ifsoln{The slope and log coefficients are similar... and the vertical shifts are similar. We changed the _kind_ of growth from}} +
@fitb{}{@ifsoln{logarithmic to linear, but not the _amount_.  Instead of increasing logarithmically by @math{a}, our new function increases _linearly_ by the slope.   }}
