#lang racket

(provide *glossary-list*)

#|
Glossary for terminology used in the notes.  The first entry of each entry can be either
a single string or a list of keys that map to the same definition.

If a list of keys is provided, the generated glossary will use the first in the list
when it prints out the glossary for a particular unit
|#

(define *glossary-list*
  '(("accessor functions" "functions to extract values from a data structure")
    ("apply" "use a given function on some inputs")
    ("arguments" "the inputs to a function; expressions for arguments follow the name of a function")
    ("ascending" "an order in which lower values appear first, and higher values appear after")
    ("average" "a number representing the center, or 'typical' value in a set of data")
    (("axis" "axes") "a number line on a scatter plot, used to place points that represent pairs of values in data sets")
    (("bar chart" "bar charts") "a display of categorical data that uses bars positioned over category values; each bar’s height reflects the count or percentage of data values in that category")
    (("bin" "bins") "a range that values from a data set can belong to; there is one bar in a histogram per bin")
    ("Boolean" "a type of data with two values: true and false")
    (("box plot" "box plots") "the box plot (a.k.a. box-and whisker-plot) is a way of displaying a distribution of data based on the five-number summary: minimum, first quartile, median, third quartile, and maximum")
    (("calling" "calls") "using a function by giving it inputs")
    (("category" "categories") "the set of possible values that a value in a categorical data set can have")
    ("categorical data" "data whose values are qualities that are not subject to the laws of arithmetic.")
    (("circle of evaluation" "circles of evaluation") "a diagram of the structure of an expression (arithmetic or code)")
    ("clause" "a question and its corresponding answer in a conditional expression")
    (("chart" "charts") "visual reprsentations of how values in a data set are distributed")
    (("column" "columns") "set of values in a table of a particular type.  Every row has exactly 1 element in every column")
    (("combination" "combinations") "the number of possible arrangements in a collection of items where the order of the selection does not matter")
    ("conditional" "a code expression made of questions and answers")
    ("constructor" "a function that creates instances of a data structure")
    (("contract" "contracts") "a statement of the name, domain, and range of a function")
    (("coordinate" "coordinates") "a number or set of numbers describing an object's location")
    ("coordinate plane" "a grid formed by a pair of intersecting horizontal and vertical number lines") 
    (("correlation" "correlations") "a single number somewhere between -1 and +1 that reports the direction and strength of the linear relationship between two quantitative variables (also known as the r-value)")
    ("data block" "code that lists the name, constructor(s), and field(s) of a data structure")
    (("data row" "data rows") "a structured piece of data in a dataset that typically reports all the information gathered about a given individual")
    ("data science" "the science of collecting, organizing, and drawing general conclusions from data, with the help of computers")
    (("dataset" "datasets") "a collection of related information that is composed of separate elements, but can be manipulated as a unit by a computer")
    ("data structure" "a datatype which packages several datatypes as fields")   
    (("datatypes" "datatype" "data type" "data types") "a way of classifying values, such as: Number, String, Image, Boolean, or any user-defined data structure")
    ( "a way of classifying values, such as: Number, String, Image, Boolean, or any user-defined data structure")
    ("debug" "to find and fix errors in one's code")
    ("define" "to associate a descriptive name with a value")
    ("definitions area" "the left-most text box in the Editor where definitions for values and functions are written")
    ("descending" "an order in which higher values appear first, and lower values appear after")
    ("design recipe" "a sequence of steps that helps people document, test, and write functions")
    ("direction" "of a relationship between two quantitative variables: whether they tend to increase together, or if as one goes up the other tends to go down")
    ("domain" "the type or set of inputs that a function expects")
    ("dot-accessors" "a way to extract the values of fields an instance")
    ("driver" "in pair programming, the person who is doing the typing")
    ("editor" "software in which you can write and evaluate code")
    (("entry" "entries") "a single value in a table, belonging to a particular row and column")
    (("error message" "error messages") "information from the computer about errors in code")
    (("edge" "edges") "the line segments where the faces of solid figures meet in each of the three dimensions.")
    ("evaluate" "perform the computation in an expression, producing an answer")
    ("evaluates to" "the result of computing an expression")
    ("event-based programming" "a style of programming in which every functions are written to respond to mouse-clicks, keypresses, etc.")
    ("event" "something that happens outside of a running program, which the program can respond to")
    ("example" "shows the use of a function on specific inputs and the computation the function should perform on those inputs")
    ("examples block" "code that lists examples starting with 'examples:' and ends with 'end'")
    (("explanatory variable" "explanatory") "the variable in a relationship that is presumed to impact the other variable")
    ("expression" "a computation written in the rules of some language (such as arithmetic, code, or a Circle of Evaluation)")
    (("extend" "extending" "extends") "a table query that creates a table with new column(s), whose entries are computed with an expression")
    ("extract" "to construct a list using data from a particular column in a table")
    (("face" "faces") "the shapes on the outside of a figure")
    ("field" "a part of a data structure that has a name and holds a single value of a specified datatype")
    ("form" "of a relationship between two quantitative variables: whether the two variables together vary linearly or in some other way")
    ("function definition" "code that names a function, lists its variables, and states the expression to compute when the function is used")
    ("function block" "code that names a function, lists its variables, and states the expression to compute when the function is used")
    (("function" "functions") "a mathematical object that consumes inputs and produces an output")
    (("frequency" "frequencies") "how often a particular value appears in a data set")
    (("frequency bar chart" "frequency bar charts") "a bar chart in which each the length of each bar corresponds to the frequency of a particular value")
    (("grouped sample" "grouped samples") "a non-random subset of individuals chosen from a larger set, where the individuals belong to a specific group")
    ("handler" "Connects an event (like a tick or keypress) and a function within a reactor")
    (("header" "header row" "headers" "header rows") "the titles of each column of a table, usually shown at the top")
    ("helper function" "a small function that handles a specific part of another computation, and gets called from other functions")
    ("header" "the part of a table that identifies the names of each column")
    (("histogram" "histograms") "a display of quantitative data that uses vertical bars positioned over bins (sub-intervals); each bar’s height reflects the count or percentage of data values in that bin.")
    (("horizontal axis" "x-axis") "axis on a coordinate plane that runs from left to right")
    ("hypotenuse" "the side opposite the 90-degree angle in a right triangle")
    ("identifier column" "a column of unique values which identify all the individual rows (e.g. - student IDs, SSNs, etc)")
    ("Image" "a type of data for pictures")
    ("instance" "a specific, packaged value of a data structure that contains other values in its fields")
    ("interactions area" "the right-most text box in the Editor, where expressions are entered to evaluate")
    (("interquartile range" "IQR") "(IQR) is one possible measure of spread, based on dividing a data set into four parts. The values that divide each part are called the first quartile (Q1), the median, and third quartile (Q3). IQR is calculated as Q3 minus Q1.")
    (("intersection" "intersections") "the set of values that makes both inequalities true")
    ("legal expression" "code that follows the Code Rules for a language")
    (("library" "libraries") "a collection of functions that can be made available to our program by using include")
    (("linear" "linear relationship") "a rule that computes one quantity from another, which can be graphed as straight line or written as a sequence of numbers that change at a constant rate")
    (("line of best fit" "lines of best fit" "regression line" "regression lines") "summarizes the relationship (if linear) between two quantitative variables")
    ("linear regression" "modeling the relationship between two quantitative variables using a straight line")
    (("list" "lists") "a data structure containing a sequence of values")
    ("mathematical expression" "a computation using the rules of arithmetic")
    ("mean" "average, calculated as the sum of values divided by the number of values")
    ("method" "a function that is only associated with an instance of a datatype, which consumes inputs and produces an output based on that instance")
    ("median" "the middle element of a quantitative data set")
    (("mode" "modes") "the most commonly appearing categorical or quantitative value or values in a data set")
    ("name" "how we refer to a function or value defined in a language (examples: +, *, star, circle)")
    ("navigator" "in pair programming, the person who has their eyes on the screen helping the driver")
    ("negative correlation" "relationship in which one variable increases as the other decreases, and vice versa")
    ("nonlinear" "an pattern that is not a straight line when it is graphed")
    ("number" "a data type representing a real number")
    (("operator" "operators") "a symbol that manipulates two Numbers and produces a result")
    (("order" "orders" "ordering") "an arrangement of data according to some pattern")
    (("outlier" "outliers") "a data point that is unusually far above or below most of the others")
    (("permutation" "permutations") "the number of possible arrangements in a set of items where the order of the selection matters")
    (("piecewise function" "piecewise functions") "a function that computes different expressions based on its input")
    (("pie chart" "pie charts") "a display that uses areas of a circular pie's slices to show percentages in each category")
    (("pixel" "pixels") "the smallest unit that makes up a digital image. The more pixels, the more detailed an image or video can appear.")
    ("positive correlation" "relationship in which one variable increases as the other increases, and vice versa")
    (("predictor function" "predictor") "a function which, given a value from one data set, makes an educated guess at a related value in a different data set")
    ("produce" "to compute a value from an expression")
    ("programming language" "a set of rules for writing code that a computer can evaluate") 
    ("purpose statement" "a brief description of what a function does")
    (("quartiles" "quartile") "three values that divide a data set into four equal-sized groups")
    ("quantitative data" "number values for which arithmetic makes sense")
    (("r" "r-value") "a number between −1 and 1 that measures the direction and strength of a linear relationship between two quantitative variables (also known as correlation value)")
    (("r-squared") "a number between 0 and 1 that measures the strength of association between two variables")
    (("random sample" "random samples") "a subset of individuals chosen from a larger set, such that each individual has the same probability of being chosen")
    ("range" "the type or set of outputs that a function produces")
    ("range of a data set" "the distance between minimum and maximum values")
    ("rate" "A comparison of two related quantities")
    ("reactor" "a value that contains a current state, and functions for updating, drawing, and interacting with that state")
    (("rectangular prism" "rectangular prisms") "a solid figure which has 6 faces, all of which are rectangular")
    (("refactor" "refactoring") "the process of changing the style or structure of a program's code, without changing the program's behavior")
    (("response variable" "response") "the variable in a relationship that is presumed to be affected by the other variable")
    (("row" "rows") "item(s) in a table, which consist of some group of values; each table is a collection of rows")
    (("sample" "samples") "a set of individuals or objects collected or selected from a statistical population by a defined procedure")
    ("sample instances" "a collection of single instances, or also used to describe illustrative instances that we use to provide examples of a data structure")
    (("select" "selects" "selecting") "a query that creates a table containing only a subset of a specified table's columns")
    (("scatter plot" "scatter plots") "a display of the relationship between two quantitative variables, graphing each explanatory value on the x axis and the accompanying response on the y axis")
    ("shape" "The aspect of a dataset that tells which values are more or less common")
    ("sieve" "a table query that creates a table containing only rows that satisfy a boolean expression")
    (("skew" "skewness") "lack of balance in a dataset’s shape, arising from more values that are unusually low or high. Such values tend to trail off, rather than be separated by a gap (as with outliers).")
    (("skewed left" "skew left" "left skew") "A distribution is skewed left if there are a few values that are fairly low compared to the bulk of data values. A display of the data will show a longer tail to the left.")
    (("skewed right" "skew right" "right skew") "A distribution is skewed right if there are a few values that are fairly high compared to the bulk of data values. A display of the data will show a longer tail to the right.")
    ("slope" "the steepness of a straight line on a graph")
    ("spread" "the extent to which values in a data set vary, either from one another or from the center")
    ("state" "the value of a changing system at any point in time (i.e. a stoplight can be in the 'red', 'yellow' or 'green' state). In Pyret, the state of a Reactor is it's current value.")
    ("statistical inference" "using information from a sample to draw conclusions about the larger population from which the sample was taken")
    ("strength" "of a relationship between two quantitative variables: the extent to which knowing the value of one variable tells us something about the value of the other")
    ("String" "a data type for any sequence of characters between quotation marks (examples: \"hello\", \"42\", \"this is a string!\")")
    ("surface area" "the sum of the areas of the faces of a polyhedron or the total area that the surface of a solid object occupies")
    (("symmetric" "symmetric distribution") "A symmetric distribution has a balanced shape, showing that it's just as likely for the variable to take lower values as higher values.")
    (("normal" "normal distribution") "A normal distribution has a particular symmetric shape that bulges in the middle and tapers at the ends.")
    ("syntax" "the set of rules that defines a language, whether it be spoken, written, or programmed.")
    (("table" "tables") "a data structure that stores data as rows, with entries in particular columns")
    ("table plan" "a sequence of steps that helps people write code for several table queries, in order to solve a problem")
    (("table query" "table queries") "an expression that consumes tables and creates a new table object")
    ("threats to validity" "factors that can undermine the conclusion of a study")
    ("type" "refers to a general kind of data, like Number, String, Image, or Boolean")
    ("unit test" "an example showing the use of a function with a specific value or values, and the answer it should produce")
    ("union" "the set of values that makes either or both of a set of inequalities true")
    ("value" "a specific piece of data, like 5 or \"hello\"")
    (("variable" "variables") "a letter, symbol, or term that stands in for a value or expression")
    ("variable name" "name of the information that can be different each time a function is used")
    (("vertical axis" "y-axis") "number line on a coordinate plane that runs from bottom to top, indicating values in that direction")
    ("y-intercept" "The point where a line or curve crosses the y-axis of a graph")
   ))
