#lang racket

(provide *glossary-list*)

#|
Glossary for terminology used in the notes.  The first entry of each entry can be either
a single string or a list of keys that map to the same definition.

If a list of keys is provided, the generated glossary will use the first in the list
when it prints out the glossary for a particular unit
|#

(define *glossary-list*
  '(("accessor functions" "functions to extract values from a data structure")
    ("apply" "use a given function on some inputs")
    ("arguments" "the inputs to a function; expressions for arguments follow the name of a function")
    ("ascending" "an order in which lower values appear first, and higher values appear after")
    ("average" "a number representing the center, or 'typical' value in a set of data")
    (("axis" "axes") "a number line on a scatter plot, used to place points that represent pairs of values in data sets")
    (("bar chart" "bar charts") "a visualization in which a data set is represented by vertical bars, with length proportional to values")
    (("bin" "bins") "a range that values from a data set can belong to; there is one bar in a histogram per bin")
    ("Boolean" "a type of data with two values: true and false")
    (("box plot" "box plots") "the box plot (a.k.a. box and whisker diagram) is a way of displaying the distribution of data based on the five-number summary: minimum, first quartile, median, third quartile, and maximum")
    (("calling" "calls") "using a function by giving it inputs")
    (("category" "categories") "the set of possible values that a value in a categorical data set can have")
    ("categorical data" "kind of data with a value that has a fixed number of possible values")
    (("circle of evaluation" "circles of evaluation") "a diagram of the structure of an expression (arithmetic or code)")
    ("clause" "a question and its corresponding answer in a conditional expression")
    (("chart" "charts") "visual reprsentations of how values in a data set are distributed")
    (("column" "columns") "set of values in a table of a particular type.  Every row has exactly 1 element in every column")
    ("conditional" "a code expression made of questions and answers")
    ("constructor" "a function that creates instances of a data structure")
    ("contract" "a statement of the name, domain, and range of a function")
    (("coordinate" "coordinates") "a number or set of numbers describing an object's location")
    ("coordinate plane" "a grid formed by a pair of intersecting horizontal and vertical number lines") 
    (("correlation" "correlations") "A relationship between two quantitative fields of a data set")
    ("data block" "code that lists the name, constructor(s), and field(s) of a data structure")
    (("data row" "data rows") "an individual, structured piece of data in a dataset")
    ("data science" "the study of using data to answer questions about the world")
    (("dataset" "datasets") "a collection of related information that is composed of separate elements, but can be manipulated as a unit by a computer")
    ("data structure" "a datatype which packages several datatypes as fields")   
    ("data type" "a way of classifying values, such as: Number, String, Image, Boolean, or any user-defined data structure")
    ("datatypes" "a way of classifying values, such as: Number, String, Image, Boolean, or any user-defined data structure")
    ("debug" "to find and fix errors in one's code")
    ("define" "to associate a descriptive name with a value")
    ("definitions area" "the left-most text box in the Editor where definitions for values and functions are written")
    ("descending" "an order in which higher values appear first, and lower values appear after")
    ("design recipe" "a sequence of steps that helps people document, test, and write functions")
    ("domain" "the type or set of inputs that a function expects")
    ("dot-accessors" "a way to extract the values of fields an instance")
    ("driver" "in pair programming, the person who is doing the typing")
    ("editor" "software in which you can write and evaluate code")
    (("entry" "entries") "a single value in a table, belonging to a particular row and column")
    ("error message" "information from the computer about errors in code")
    ("evaluate" "perform the computation in an expression, producing an answer")
    ("evaluates to" "the result of computing an expression")
    ("event-based programming" "a style of programming in which every functions are written to respond to mouse-clicks, keypresses, etc.")
    ("event" "something that happens outside of a running program, which the program can respond to")
    ("example" "shows the use of a function on specific inputs and the computation the function should perform on those inputs")
    ("examples block" "code that lists examples starting with 'examples:' and ends with 'end'")
    ("expression" "a computation written in the rules of some language (such as arithmetic, code, or a Circle of Evaluation)")
    (("extend" "extending" "extends") "a table query that creates a table with new column(s), whose entries are computed with an expression")
    ("extract" "to construct a list using data from a particular column in a table")
    ("field" "a part of a data structure that has a name and holds a single value of a specified datatype")
    ("function definition" "code that names a function, lists its variables, and states the expression to compute when the function is used")
    ("function block" "code that names a function, lists its variables, and states the expression to compute when the function is used")
    ("function" "a mathematical object that consumes inputs and produces an output")
    (("frequency" "frequencies") "how often a particular value appears in a data set")
    (("frequency bar chart" "frequency bar charts") "a bar chart in which each the length of each bar corresponds to the frequency of a particular value")
    ("handler" "Connects an event (like a tick or keypress) and a function within a reactor")
    (("header" "header row" "headers" "header rows") "the titles of each column of a table, usually shown at the top")
    ("helper function" "a small function that handles a specific part of another computation, and gets called from other functions")
    ("header" "the part of a table that identifies the names of each column")
    (("histogram" "histograms") "a special frequency bar chart in which each bar counts the frequency of values appearing that belong to a certain bin")
    ("horizontal axis" "axis on a scatter plot that runs from left to right")
    ("hypotenuse" "the side opposite the 90-degree angle in a right triangle")
    ("identifier column" "a column of unique values which identify a particular row (e.g. - student IDs, SSNs, etc)")
    ("Image" "a type of data for pictures")
    ("interactions area" "the right-most text box in the Editor, where expressions are entered to evaluate")
    ("interquartile range" "(IQR) is a measure of variability, based on dividing a data set into four quartiles. The values that divide each part are called the first (Q1), second (Q2), and third quartiles (Q3)")
    ("instance" "a specific, packaged value of a data structure that contains other values in its fields")
    ("legal expression" "code that follows the Code Rules for a language")
    (("library" "libraries") "a collection of functions that can be made available to our program by using include")
    (("line of best fit" "lines of best fit") "a straight line that best represents the data on a scatter plot")
    ("linear regression" "a linear approach for modeling the relationship between a dependent variable, and one or more explanatory variables")
    (("list" "lists") "a data structure containing a sequence of values")
    ("mathematical expression" "a computation using the rules of arithmetic")
    ("mean" "the arithmetic mean; a number with the smallest total difference between all elements in a quantitative data set")
    ("method" "a function that is only associated with an instance of a datatype, which consumes inputs and produces an output based on that instance")
    ("median" "the middle element of a quantitative data set")
    (("mode" "modes") "the most commonly appearing value or values in a data set")
    ("name" "how we refer to a function or value defined in a language (examples: +, *, star, circle)")
    ("navigator" "in pair programming, the person who has their eyes on the screen helping the driver")
    ("negative correlation" "relationship in which one variable increases as the other decreases, and vice versa")
    ("Number" "a data type representing a real number")
    (("operator" "operators") "a symbol that manipulates two Numbers and produces a result")
    (("order" "orders" "ordering") "an arrangement of data according to some pattern")
    (("outlier" "outliers") "an observation point that is distant from other observations, perhaps due to experimental error or measurement variability.")
    ("piecewise function" "a function that computes different expressions based on its input")
    (("pie chart" "pie charts") "a chart where the size of each pie slice corresponds to a value in the data set")
    (("pixel" "pixels") "the smallest unit that makes up a digital image. The more pixels, the more detailed an image or video can appear.")
    ("positive correlation" "relationship in which one variable increases as the other increases, and vice versa")
    ("predictor" "a function which, given a value from one data set, tries to predict a related value in a different data set")
    ("produce" "to compute a value from an expression")
    ("programming language" "a set of rules for writing code that a computer can evaluate") 
    ("purpose statement" "a brief description of what a function does")
    ("quartile" "each of four equal-sized groups into which a population can be divided, according to the distribution of values of a particular variable")
    ("quantitative data" "data with values that measure some amount or quantity;  may not have a fixed number of possible values")
    ("r" "a number between −1 and 1 that measures the strength and direction of a linear relationship between two variables")
    (("r-squared") "a number between 0 and 1 that measures the strength of association between two variables")
    ("range" "the type or set of outputs that a function produces")
    ("reactor" "a value that contains a current state, and functions for updating, drawing, and interacting with that state")
    ("refactor" "the process of changing the style or structure of a program's code, without changing the program's behavior")
    ("refactoring" "the process of changing the style or structure of a program's code, without changing the program's behavior")
    (("row" "rows") "item(s) in a table, which consist of some group of values; each table is a collection of rows")
    ("sample instances" "a collection of single instances, or also used to describe illustrative instances that we use to provide examples of a data structure")
    (("select" "selects" "selecting") "a query that creates a table containing only a subset of a specified table's columns")
    (("scatter plot" "scatter plots") "a chart where points are placed on axes according to pairs of values")
    ("shape" "The aspect of a dataset that tells which values are more or less common")
    ("sieve" "a table query that creates a table containing only rows that satisfy a boolean expression")
    ("skew" "lack of balance in a dataset’s shape, arising from more values that are unusually low or high. Such values tend to trail off, rather than separated by a gap (as with outliers)")
    ("spread" "how far the values in a dataset are away from the center")
    ("state" "the value of a changing system at any point in time (i.e. a stoplight can be in the 'red', 'yellow' or 'green' state). In Pyret, the state of a Reactor is it's current value.")
    ("String" "a data type for any sequence of characters between quotation marks (examples: \"hello\", \"42\", \"this is a string!\")")
    ("syntax" "the set of rules that defines a language, whether it be spoken, written, or programmed.")
    (("table" "tables") "a data structure that stores data as rows, with entries in particular columns")
    ("table plan" "a sequence of steps that helps people write code for several table queries, in order to solve a problem")
    (("table query" "table queries") "an expression that consumes tables and creates a new table object")
    ("threats to validity" "factors than can invalidate the conclusion of a study")
    ("type" "refers to a general kind of data, like Number, String, Image, or Boolean")
    ("unit test" "an example showing the use of a function with a specific value or values, and the answer it should produce")
    ("value" "a specific piece of data, like 5 or \"hello\"")
    ("variable" "a letter, symbol, or term that stands in for a value or expression")
    ("variable name" "name of the information that can be different each time a function is used")
    ("vertical axis" "number line on a graph that runs from bottom to top, indicating values in that direction")
   ))
