#lang racket

;FIXME what wd be the canonical location of this file?
;      the pathway top dir?

(provide *lessons-and-standards*)

(define *lessons-and-standards*
  '(

    ("alg-game-intro" "BS-M")
    ("alg-game-intro" "MP.2")
    ("alg-coordinates" "BS-M")
    ("alg-coordinates" "MP.2")
    ("alg-creating-functions-1" "7.EE.B.4")
    ("alg-creating-functions-1" "8.F.B")
    ("alg-creating-functions-1" "BS-DR.1")
    ("alg-creating-functions-1" "HSA.SSE.A.1")
    ("alg-defining-functions" "7.EE.B.4")
    ("alg-defining-functions" "8.F.B")
    ("alg-defining-functions" "BS-DR.1")
    ("alg-defining-functions" "HSA.SSE.A.1")
    ("alg-solving-word-problems" "7.EE.B.4")
    ("alg-solving-word-problems" "8.F.B")
    ("alg-solving-word-problems" "BS-DR.2")
    ("alg-solving-word-problems" "HSF.IF.A.2")
    ("alg-restating-the-problem" "8.F.B")
    ("alg-restating-the-problem" "BS-DR.1")
    ("alg-restating-the-problem" "BS-DR.2")
    ("alg-restating-the-problem" "BS-DR.3")
    ("alg-restating-the-problem" "HSF.BF.A.1")
    ("alg-restating-the-problem" "MP.1")
    ("alg-restating-the-problem" "MP.7")
    ("alg-defining-values" "7.EE.B.4")
    ("alg-defining-values" "BS-PL.3")
    ("alg-defining-values" "HSA.SSE.A.1")
    ("alg-defining-values" "MP.2")
    ("alg-defining-values" "MP.7")
    ("alg-distance-formula" "8.G.B.7")
    ("alg-distance-formula" "MP.2")
    ("alg-domain-and-range" "8.F.A.1")
    ("alg-domain-and-range" "BS-PL.2")
    ("alg-domain-and-range" "HSF.IF.A.1")
    ("alg-error-analysis" "MP.2")
    ("alg-making-game-images" "7.RP.A.1")
    ("alg-making-game-images" "8.G.A.1")
    ("alg-making-game-images" "BS-IDE")
    ("alg-making-game-images" "BS-PL.3")
    ("alg-making-game-images" "MP.6")
    ("alg-character-animation" "8.F.B")
    ("alg-character-animation" "BS-PL.3")
    ("alg-character-animation" "HSF.LE.B")
    ("alg-character-animation" "MP.2")
    ("alg-problem-decomposition" "BS-DR.1")
    ("alg-problem-decomposition" "BS-DR.2")
    ("alg-problem-decomposition" "HSF.BF.A.1")
    ("alg-problem-decomposition" "MP.1")
    ("alg-problem-decomposition" "MP.6")
    ("alg-function-composition-1" "8.G.A.1")
    ("alg-function-composition-1" "BS-IDE")
    ("alg-function-composition-1" "MP.1")
    ("alg-function-composition-1" "MP.5")
    ("alg-function-composition-2" "7.RP.A.1")
    ("alg-function-composition-2" "8.G.A.1")
    ("alg-function-composition-2" "MP.1")
    ("alg-function-composition-3" "HSF.BF.A.1.B")
    ("alg-simple-inequalities" "7.EE.B.4")
    ("alg-simple-inequalities" "BS-DR.2")
    ("alg-simple-inequalities" "BS-DR.3")
    ("alg-simple-inequalities" "HSF.IF.A.2")
    ("alg-simple-inequalities" "MP.1")
    ("alg-simple-inequalities" "MP.4")
    ("alg-compound-inequalities" "7.EE.B.4")
    ("alg-compound-inequalities" "BS-DR.2")
    ("alg-compound-inequalities" "BS-DR.3")
    ("alg-compound-inequalities" "HSF.IF.A.2")
    ("alg-order-of-operations" "HSA.SSE.A.2")
    ("alg-order-of-operations" "HSA.SSE.B")
    ("alg-order-of-operations" "MP.1")
    ("alg-order-of-operations" "MP.2")
    ("alg-piecewise-functions" "HSA.SSE.A.1.A")
    ("alg-piecewise-functions" "HSA.SSE.A.1.B")
    ("alg-piecewise-functions" "MP.8")
    ("alg-player-animation" "HSA.SSE.A.1.A")
    ("alg-player-animation" "HSA.SSE.A.1.B")

    ; flags
    ("fl-flags-of-the-world" "N-Q&1&3" "BS-PL.2" "6.NS.5-8" "F-IF.1-3")
    ("fl-image-transformations" "N-Q&1&3" "BS-PL.2" "6.NS.5-8" "F-IF.1-3")
    ("fl-intro-to-dilations" "N-Q&1&3" "BS-PL.2" "6.NS.5-8" "F-IF.1-3")

    ; demo
    ("__sample-lesson" "8.F.1-3&1")
    ("__sample-lesson" "8.NS.A")

    ;data science
    ("ds-intro" "HSS.ID.B.6" "6.SP.1" "6.SP.B.5.A" "7.SP.A.1" "Data 3.1.3" "BS-PL.1" "BS-PL.2")
    ("ds-pyret-intro" "")
    ("ds-applying-functions" "")
    ("ds-displays-and-lookups" "")
    ("ds-defining-functions" "8.SP.A.1")
    ("ds-table-methods" "")
    ("ds-defining-table-functions" "")
    ("ds-grouped-samples" "8.SP.A.1")
    ("ds-histograms" "HSS.ID.B.6.A" "HSS.ID.A.3" "HSS.ID.A.1" 6.SP.A.2" "6.SP.B.4" "6.SP.B.5.B")
    ("ds-histograms2" "HSS.ID.B.6.A" "HSS.ID.A.3" "HSS.ID.A.1" "6.SP.A.2" "6.SP.B.4" "6.SP.B.5.C")
    ("ds-if-expressions" "")
    ("ds-measures-of-center" "HSS.ID.B.6.A" "HSS.ID.A.3" "HSS.ID.A.2" "6.SP.A.2" "6.SP.A.3" "6.SP.B.5.D")
    ("ds-measures-of-spread" "HSS.ID.B.6.A" "HSS.ID.A.3" "HSS.ID.A.1" "6.SP.A.2" "6.SP.B.4" "6.SP.B.5.C")
    ("ds-choosing-your-dataset" "HSS.ID.B.6" "6.SP.A.1")
    ("ds-method-chaining" "")
    ("ds-checking-your-work" "7.SP.A.1")
    ("ds-random-samples" "7.SP.A.1" "7.SP.A.2")
    ("ds-scatter-plots" "8.SP.A.1")
    ("ds-correlations" "HSS.ID.C.9" "HSS.ID.C.8" "8.SP.A.2")
    ("ds-linear-regression" "HSS.ID.C.7" "HSS.ID.B.6.C" "8.SP.A.2" "8.SP.A.3")
    ("ds-threats-to-validity" "7.SP.A.1")
    ("ds-ethics-and-privacy" "")
    ))
