#lang racket

;FIXME what wd be the canonical location of this file?
;      the pathway top dir?

(provide *lessons-and-standards*)

(define *lessons-and-standards*
  '(

    ("alg-coordinate-plane-1" "BS-M")
    ("alg-coordinate-plane-1" "MP.2")
    ("alg-coordinate-plane-2" "BS-M")
    ("alg-coordinate-plane-2" "MP.2")
    ("alg-creating-functions-1" "7.EE.B.4")
    ("alg-creating-functions-1" "8.F.B")
    ("alg-creating-functions-1" "BS-DR.1")
    ("alg-creating-functions-1" "HSA.SSE.A.1")
    ("alg-defining-functions-1" "7.EE.B.4")
    ("alg-defining-functions-1" "8.F.B")
    ("alg-defining-functions-1" "BS-DR.1")
    ("alg-defining-functions-1" "HSA.SSE.A.1")
    ("alg-defining-functions-2" "7.EE.B.4")
    ("alg-defining-functions-2" "8.F.B")
    ("alg-defining-functions-2" "BS-DR.2")
    ("alg-defining-functions-2" "HSF.IF.A.2")
    ("alg-defining-functions-3" "8.F.B")
    ("alg-defining-functions-3" "BS-DR.1")
    ("alg-defining-functions-3" "BS-DR.2")
    ("alg-defining-functions-3" "BS-DR.3")
    ("alg-defining-functions-3" "HSF.BF.A.1")
    ("alg-defining-functions-3" "MP.1")
    ("alg-defining-functions-3" "MP.7")
    ("alg-defining-values-1" "7.EE.B.4")
    ("alg-defining-values-1" "BS-PL.3")
    ("alg-defining-values-1" "HSA.SSE.A.1")
    ("alg-defining-values-1" "MP.2")
    ("alg-defining-values-1" "MP.7")
    ("alg-distance-formula-1" "8.G.B.7")
    ("alg-distance-formula-1" "MP.2")
    ("alg-domain-and-range" "8.F.A.1")
    ("alg-domain-and-range" "BS-PL.2")
    ("alg-domain-and-range" "HSF.IF.A.1")
    ("alg-error-analysis" "MP.2")
    ("alg-function-applications-1" "7.RP.A.1")
    ("alg-function-applications-1" "8.G.A.1")
    ("alg-function-applications-1" "BS-IDE")
    ("alg-function-applications-1" "BS-PL.3")
    ("alg-function-applications-1" "MP.6")
    ("alg-function-applications-2" "8.F.B")
    ("alg-function-applications-2" "BS-PL.3")
    ("alg-function-applications-2" "HSF.LE.B")
    ("alg-function-applications-2" "MP.2")
    ("alg-function-applications-3" "BS-DR.1")
    ("alg-function-applications-3" "BS-DR.2")
    ("alg-function-applications-3" "HSF.BF.A.1")
    ("alg-function-applications-3" "MP.1")
    ("alg-function-applications-3" "MP.6")
    ("alg-function-composition-1" "8.G.A.1")
    ("alg-function-composition-1" "BS-IDE")
    ("alg-function-composition-1" "MP.1")
    ("alg-function-composition-1" "MP.5")
    ("alg-function-composition-2" "7.RP.A.1")
    ("alg-function-composition-2" "8.G.A.1")
    ("alg-function-composition-2" "MP.1")
    ("alg-function-composition-3" "HSF.BF.A.1.B")
    ("alg-inequalities" "7.EE.B.4")
    ("alg-inequalities" "BS-DR.2")
    ("alg-inequalities" "BS-DR.3")
    ("alg-inequalities" "HSF.IF.A.2")
    ("alg-inequalities" "MP.1")
    ("alg-inequalities" "MP.4")
    ("alg-inequalities-2" "7.EE.B.4")
    ("alg-inequalities-2" "BS-DR.2")
    ("alg-inequalities-2" "BS-DR.3")
    ("alg-inequalities-2" "HSF.IF.A.2")
    ("alg-order-of-operations-1" "HSA.SSE.A.2")
    ("alg-order-of-operations-1" "HSA.SSE.B")
    ("alg-order-of-operations-1" "MP.1")
    ("alg-order-of-operations-1" "MP.2")
    ("alg-piecewise-functions" "HSA.SSE.A.1.A")
    ("alg-piecewise-functions" "HSA.SSE.A.1.B")
    ("alg-piecewise-functions" "MP.8")
    ("alg-piecewise-functions-2" "HSA.SSE.A.1.A")
    ("alg-piecewise-functions-2" "HSA.SSE.A.1.B")
    ("flags-of-the-world" "N-Q&1&3" "BS-PL.2" "6.NS.5-8" "F-IF.1-3")
    ("image-transformations" "N-Q&1&3" "BS-PL.2" "6.NS.5-8" "F-IF.1-3")
    ("intro-to-dilations" "N-Q&1&3" "BS-PL.2" "6.NS.5-8" "F-IF.1-3")
    ("lessonA" "8.F.1-3&1")
    ("lessonA" "8.NS.A")

    ;data science
    ("ds-intro" "6.SP.1-3" "Data 3.1.3" "BS-PL.1" "BS-PL.2")
    ("ds-question-types" "Data 3.1.3" "BS-DR.1" "BS-DR.2" "BS-PL.3")
    ("ds-exploring-your-dataset" "Data 3.1.3")
    ("ds-visualizing-shape" "6.SP.4-5" "Data 3.1.2" "Data 3.1.3" "HSS.ID.A" "S-ID.1-4")
    ("ds-measures-of-center" "6.SP.4-5" "Data 3.2.1" "HSS.ID.A" "S-ID.1-4")
    ("ds-method-chaining" "Data 3.1.1" "BS-DR.1" "BS-DR.2" "BS-DR.4" "BS-PL.3")
    ("ds-correlations" "Data 3.1.1" "Data 3.1.2" "Data 3.1.3" "S-ID.5-6" "BS-DR.1" "BS-DR.2" "BS-DR.4")
    ("ds-linear-regression" "Data 3.1.3" "Data 3.2.1" "HSS.ID.B" "HSS.ID.C" "S-ID.7-9")
    ))
