= Graphing Quadratic Models
++++
<style>
.autonum { font-weight: bold; }
.autonum:after { content: ')' !important; }

.FillVerticalSpace { grid-gap: 20px; margin-top: 5px; }

td {
	background-color: rgba(#fff, .5);
	background-image:
		linear-gradient(lightblue 2px, transparent 2px),
		linear-gradient(90deg, lightblue 2px, transparent 2px),
		linear-gradient(rgba(150, 150, 150, .3) 1px, transparent 1px),
		linear-gradient(90deg, rgba(150, 150, 150, .3) 1px, transparent 1px);
	background-size: 100px 100px, 100px 100px, 20px 20px, 20px 20px;
	background-position: -3px 74px;
	min-height: 1.5in;
	max-width: 2in;
}
</style>
++++

For this page, you'll need to have @online-exercise{https://www.desmos.com/calculator/geyx4aetop, the Exploring Quadratics Desmos Activity} open on your computer. The parabola you see is the graph of @math{f(x)=x^2}. Another, *identical* parabola is hiding behind it. This second parabola is written in Vertex Form: @math{g(x)=a(x-h)^2+k}. Each coefficient starts at values to make @math{g(x)} equivalent to @math{f(x)}.

@n Use the values of @math{a}, @math{h}, and @math{k} from Desmos, write the Vertex Form of @math{f(x) = x^2}: @math{f(x)=}@fitb{}{@ifsoln{@math{1(x-0)^2+0}}}

== Magnitude @math{a}
@n Try changing the value of @math{a} to -4, 0, and 2, graphing each parabola in the squares below and labeling the vertex and roots.


[.FillVerticalSpace, cols="1,1,1", frame="none"]
|===
| @math{a=-4}	| @math{a=0}	| @math{a=2}
|===

@n What does @math{a} tell us about a parabola? @fitb{}{@ifsoln{The parabola opens "up" if it's positive, and "down" if negative}} +
@fitb{}{@ifsoln{The larger the magnitude, the "tighter" the parabola. If it's zero, the graph is a straight line}}

== Horizontal Translation @math{h}
@n Set @math{a} back to 1. Change the value of @math{h} to -5, 0, and 5, graphing each parabola in the squares below and labeling the vertex and roots.


[.FillVerticalSpace, cols="1,1,1", frame="none"]
|===
| @math{h=-5}	| @math{h=0}	| @math{h=5}
|===

@n What does @math{h} tell us about a parabola? @fitb{}{@ifsoln{How far the parabola is shifted left (negative h) or right (positive h)}} +


== Vertical Translation @math{k}
@n Set @math{h} back to 0. Change the value of @math{k} to -5, 0, and 5, graphing each parabola in the squares below and labeling the vertex and roots.


[.FillVerticalSpace, cols="1,1,1", frame="none"]
|===
| @math{k=-5}	| @math{k=0}	| @math{k=5}
|===

@n What does @math{k} tell us about a parabola? @fitb{}{@ifsoln{How far the parabola is shifted up (positive k) or down (negative k)}} +

