= Modeling Fuel Efficiency v. Speed
++++
<style>
.studentAnswerMedium { min-width: 10em !important; }
.contract .editbox { width: 100% !important; }
</style>
++++

Open your copy of the @starter-file{alg2-fuel-efficiency} and click "Run". +
Before we try to model our fuel-efficiency data, we need to learn a new Pyret function! 

@n Can you predict what the output of the following expressions will be? Enter them into the Interactions Area, and record the result.

[cols="^1a, ^1a", stripes="none", frame="none", grid="none"]
|===
| @show{(code '(sqr 4))} @fitb{10em}{@ifsoln{16}}
| @show{(code '(sqr (- 6 2)))} @fitb{10em}{@ifsoln{16}}
|===

@n What is the Contract for `num-sqr`? @fitb{}{}

@n What does `num-sqr` _do_? @fitb{}{}

== Interpreting a Quadratic Model

In the Definitions Area of your @starter-file{alg2-fuel-efficiency}, you'll find the definition of a quadratic model `quad1`.

@n In `quad1`, the value of @math{a} is @fitb{10em}{@ifsoln{1}}, the value of @math{h} is @fitb{10em}{@ifsoln{0}}, and the value of @math{k} is @fitb{10em}{@ifsoln{0}}

@n Fit this model to your dataset, using `fit-model`. What @math{R^2} value did you get? @fitb{}{@ifsoln{-10.4996}} 

[.indentedpara]
_Hint: If you forgot the contract for `fit-model`, look it up in the @dist-link{Contracts.shtml, contracts pages}!_

@n In your own words, describe what needs to change about this model to fit the data. @fitb{}{} +
@fitb{}{} +
@fitb{}{}

== Modeling Fuel Efficiency

[cols="2a, 4a"]
|===
| *Vertex Form*: @hspace{2em} @math{y=a(x − h)^2 + k}
|
- @math{a}: determines whether the parabola opens up or down and how steep the curve is
- @math{h}: x-coordinate of the vertex
- @math{k}: y-coordinate of the vertex (in quadratic models, this is also the vertical shift!)
|===

@n We've determined that peak fuel efficiency is around 45 mph. What variable in the equation should we replace with 45? @fitb{}{}

[.indentedpara]
Update the definition of `quad1`, click "Run" and re-fit the model. What @math{R^2} value did you get? @fitb{}{@ifsoln{0.46179}}

@n What y-coordinate of the vertex would best match the shape of the curve? @fitb{5em}{@ifsoln{~32}} 

[.indentedpara]
Update the definition of `quad1`, click "Run" and re-fit the model. What @math{R^2} value did you get?
 @fitb{}{@ifsoln{~0.7}}

@n What value of @math{a} best matches the shape of the curve? @fitb{5em}{@ifsoln{~0.01}} 
[.indentedpara]
Update the definition of `quad1`, click "Run" and re-fit the model. What @math{R^2} value did you get? @fitb{}{@ifsoln{~0.3-0.4}}

@n See any small changes you'd like to make to the definition, trying to get @math{R^2} as close to 1 as you can? Write your final definition below.

`fun f(x) :` @fitb{30em}{} `end` @hspace{5em} @math{R^2}: @fitb{}{}

@vspace{1ex}

@star **What does this model actually mean? Try completing the sentence below:**

After experimenting, I came up with a quadratic model showing that _speed_ explains @fitbruby{8em}{@ifsoln{about 73.3}}{R-squared * 100}% of the variability in _gas mileage_ for cars in this dataset. The vertex of the parabola drawn by this model is @fitbruby{8em}{@ifsoln{about 45}}{(x, y)}, which means that @fitb{}{}

@fitb{}{@ifsoln{It's most efficient to drive at about 45pmh, at which speed cars seem to get about 32 miles per gallon.}}

@star How does the fact that the value of @math{a} is negative impact this parabola? @fitb{}{}
