= Modeling Fuel Efficiency v. Speed
++++
<style>
.studentAnswerMedium { min-width: 10em !important; }
td { padding: 0 !important; }
body.workbookpage .fitb { padding-top: 0.3rem !important; }
</style>
++++

For this page, you'll need to have the @starter-file{alg2-fuel-efficiency} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you and click "Run".

@vspace{1ex}

== Squares and square roots in Pyret
(Contracts for these functions can also be found on your contracts pages):

@vspace{1ex}

[cols="^1a,^1a", stripes="none", frame="none"]
|===
| @math{x^2}
| @math{\sqrt x}

| @show{(contract "num-sqr" '("Num") "Num" "Consumes a number, and produces the square of that number")}
| @show{(contract "num-sqrt" '("Num") "Num" "Consumes a number, and produces the square root of that number")}
|===

@n In the Interactions Area, enter the following expressions, one after the other. Can you predict what the output will be? 

[cols="^1a, ^1a, ^1a, ^1a", stripes="none", frame="none"]
|===
| @show{(code '(sqrt 16))} @fitb{}{@ifsoln{4}}
| @show{(code '(sqr 4))} @fitb{}{@ifsoln{16}}
| @show{(code '(sqrt (+ 10 6)))} @fitb{}{@ifsoln{4}}
| @show{(code '(sqr (* 2 2)))} @fitb{}{@ifsoln{16}}
|===

== Build a Model from Samples

**In this exercise you'll have a chance to build and fit more models to the data, now armed with new tools that let you experiment with squares and square roots.** 

@n The *vertex form* of a quadratic model is shown below. Fill in the vertex using the most-efficient speed from @printable-exercise{exploring-mpg.adoc}:

@center{@math{f(x) = a(x−}@fitbruby{6em}{}{peak efficiency}@math{)^2+k}}

@vspace{1ex}

@center{__But what values of @math{a} and @math{k} will build the best possible model?__}

@center{**In the Definitions Area of your @starter-file{alg2-fuel-efficiency}, you'll find the definition of a quadratic model `quad1`.**}

@n In `quad1`, the value of @math{a} is @fitb{10em}{@ifsoln{1}}, the value of @math{h} is @fitb{10em}{@ifsoln{0}}, and the value of @math{k} is @fitb{10em}{@ifsoln{0}}.

@n Fit this model to your dataset, using `fit-model`. What @math{R^2} value did you get? @fitb{}{}

@n Experiment with different values of @math{a}. Which one draws a parabola that __most closely matches__ the shape of the dots above it? @fitb{}{@ifsoln{About -1/100}}

What @math{R^2} value did you get? @fitb{}{@ifsoln{About -127.455}}

@n Experiment with different values of @math{k}. Which one draws in a parabola that _most closely fits the shape of the data?_ @fitb{}{@ifsoln{about 33}}

What @math{R^2} value did you get? @fitb{}{@ifsoln{About 0.733}}

@star **What does this model actually mean? Try completing the sentence below:**

After experimenting, I came up with a quadratic showing that _speed_ explains @fitbruby{10em}{@ifsoln{about 73.3}}{R-squared * 100}% of the variability in _gas mileage_ for cars in this dataset. The vertex of the parabola drawn by this model is @fitbruby{10em}{@ifsoln{about 45}}{x-value of vertex}, which means that

@fitbruby{}{@ifsoln{45mph is the most efficient speed to drive}}{interpretation of the vertex}.
