= Modeling Fuel Efficiency v. Speed
++++
<style>
.studentAnswerMedium { min-width: 10em !important; }
td { padding: 0 !important; }
body.workbookpage .fitb { padding-top: 0.3rem !important; }
.contract .editbox { width: 100% !important; }
</style>
++++

For this page, you'll need to have the @starter-file{alg2-fuel-efficiency} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you and click "Run".

@vspace{1ex}

== Squaring in Pyret
(This can also be found on your contracts pages):

@vspace{1ex}

[.contract]
@show{(contract "num-sqr" '("Num") "Num" "Consumes a number, and produces the square of that number")}

@n In the Interactions Area, enter the following expressions, one after the other. Can you predict what the output will be? 

[cols="^1a, ^1a", stripes="none", frame="none", grid="none"]
|===
| @show{(code '(sqr 4))} @fitb{10em}{@ifsoln{16}}
| @show{(code '(sqr (- 6 2)))} @fitb{10em}{@ifsoln{16}}
|===

== Fitting a Quadratic Model
Complete the following sentences. You may want to refer back to @printable-exercise{graphing-models.adoc}!

@n When a parabola opens "up", @fitb{15em}{_a_ is positive}. When it opens "down", @fitb{}{@ifsoln{a is negative}}

@n When a parabola is "narrow", @fitb{15em}{@ifsoln{a is large}}. When it is "wide", @fitb{10em}{@ifsoln{a is small}}.

@n What happens when @math{a} is zero? @fitb{}{@ifsoln{The curve is flattened to a straight line}}

@n To shift a parabola right, @fitb{15}{@ifsoln{make h larger}}. To shift it left, @fitb{}{@ifsoln{make h smaller}}

@n To shift a parabola up, @fitb{15em}{@ifsoln{make k larger}}. To shift it down, @fitb{}{@ifsoln{make k smaller}}

== Modeling Fuel Efficiency

@n The *vertex form* of a quadratic model is shown below. Fill in the vertex using the vertex from @printable-exercise{exploring-mpg.adoc}:

@center{@math{f(x) = a(x−}@fitbruby{6em}{@ifsoln{45}}{peak efficiency}@math{)^2+k}}

@vspace{1ex}

@center{__But what values of @math{a} and @math{k} will build the best possible model?__}

@center{**In the Definitions Area of your @starter-file{alg2-fuel-efficiency}, you'll find the definition of a quadratic model `quad1`.**}

@n In `quad1`, the value of @math{a} is @fitb{10em}{@ifsoln{1}}, the value of @math{h} is @fitb{10em}{@ifsoln{0}}, and the value of @math{k} is @fitb{10em}{@ifsoln{0}}

@n Fit this model to your dataset, using `fit-model`. What @math{R^2} value did you get? @fitb{}{@ifsoln{-10.4996}}

@n Change the value of @math{h} to match the *x-value* of your vertex. What @math{R^2} value did you get when you re-fit the model? @fitb{}{@ifsoln{0.46179}}

@n What the value of @math{a} best matches the shape of the curve? @fitb{5em}{@ifsoln{~0.01}} What @math{R^2} value did you get when you re-fit the model? @fitb{}{@ifsoln{~0.3-0.4}}

@n Change the value of @math{k} to match the *y-value* of your vertex. What @math{R^2} value did you get when you re-fit the model? @fitb{}{@ifsoln{~0.7}}

@star **What does this model actually mean? Try completing the sentence below:**

After experimenting, I came up with a quadratic showing that _speed_ explains @fitbruby{20em}{@ifsoln{about 73.3}}{R-squared * 100}% of the variability in _gas mileage_ for cars in this dataset. The vertex of the parabola drawn by this model is @fitbruby{10em}{@ifsoln{about 45}}{x-value of vertex}, which means that

@fitbruby{100%}{@ifsoln{45mph is the most efficient speed to drive}}{interpretation of the vertex}
