= Lesson A


@lesson-description{Lesson A teaches the student how to fly a
kite and jump into a lake while taking a selfie. Prerequisites
are at least 10 hand-release pushups and a 220 pount trap bar
deadlift.
}



This is a @span{.classe}{SPAN @span{.tiny}{ tiny thing} THING} in a sentence.

[.tooltip]
@span{.tooltiptext}{This is the hover text}
My image thingy

@vocab{variable}


Big Idea of lesson goes here.


Look at @worksheet-link{workbook-pages/pageA2.pdf}.

Look at @worksheet-link{lessonB/index.adoc, lesson B}.

Look at @worksheet-link{./extra.adoc, not a workbook page}.

Look at @worksheet-link{pointer-URL, external URL}.

Look at @worksheet-link{exercises/PiecewiseFunctions-EX1.html} for Exercise A2.

Look at @worksheet-link{lessonA/exercises/exerciseA1.html} for Exercise A1.

Look at @worksheet-link{exercises/exerciseA2.html} for Exercise A2.

Look at @worksheet-link{lessonA/workbook-pages/pageA1.pdf}.

@image{images/tbdek.jpg, "Which One Doesn't Belong?, Matt Owen,
Curated by Mary Bourassa's https://wodb.ca", 400, align="center"}

[@lesson-intro-table]
|===
|Lesson Goals
|Students will be able to:

* Goal #1
* Goal #2

|Student-Facing Goals
|
* I can...
* I can...
* I can...

|Key Points for the Facilitator
|
* Common student issues
* Pacing suggestions
* etc

|Prerequisites
|
* Previous lessons linked here

|Materials
|
* Links to printables, activities, etc., go here
|===

[@lesson-intro-table]
|===
|Math Standards (CCSS)
|
* http://www.corestandards.org/Math/Practice/MP1[CCSS.MATH.PRACTICE.MP1],
Make sense of problems and persevere in solving them.
* http://www.corestandards.org/Math/Practice/MP2[CCSS.MATH.PRACTICE.MP2],
Reason abstractly and quantitatively.
* Other math standards.

|CS Standards (CSTA)
|
* CS Standards here.
|===

== Get Ready:

One sentence here.

== Launch: @duration{10 min}

Prose describing student task. About 3-4 sentences.

[.notice-box]
.Notice & Wonder
****
Ask students to take a minute to see what they *notice*.

Discuss as a group.

Ask students to take a minute to see what they *wonder*.

Share and discuss again.
****

2-3 more sentences of prose for the task, endpoint leading into
Explore section.

== Explore: @duration{2 days}

3-4 sentences of prose describing task.

@image{images/tbdek.jpg, tbdek,400,align="center"}

== Discuss: @duration{1 millennium}

* Guiding questions with responses here.
* And here.
* And here.
* etc.

[.strategy-box]
.Strategies for English Language Learners
****
MLR 8 -- Discussion Supports: As students discuss the guiding
questions, rephrase responses as questions and encourage
precision in the words being used to reinforce the meanings
behind some of the programming-specific language.
****

== Practice: @duration{4 months}

3-4 sentences of prose + images describing task.

[.physics-table,width="50%",cols="5a,5a",options="header"]
|===
|Miles drivien (mi)
|Costs ($)

|
|

|
|

|
|

|
|

|
|

|
|
|===

== Create/Apply: @duration{38 years}

3-4 sentences of prose describing task.

== A sample recipe @duration{42 kalpa}

@worksheet-link{exercises/exerciseA1.adoc, "Sample design recipe, etc"}
