= Computation as a Circle Transformation

@description{Students explore _computation_ as a valid way to transform Circles of Evaluation.}

@lesson-prereqs{translating-words-math}

@keywords{Circle Transformation, computation, equivalence}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Develop equivalent Circle representations of a given expression using Computation.
* Diagram solving with Circles using Computation.


| Student-facing Lesson Goals
|

* Let's transform Circles using Computation.


| Materials
|[.materials-links]
@material-links

| Preparation
|
* The activity in the first section is most impactful if students can stand up and draw their individual Circles on the whiteboard. Having a handful of markers for student use is encouraged.

| Key Points For The Facilitator
|
* "Computation" is the first strategy students will employ to develop equivalent expressions, a focal point of this course.
* This lesson foreshadows and exposes students to additional laws of arithmetic that will be delved later. Keep a running list of the "categories" of transformations that students spot to refer to down the road.
|===

== Computation as an Equivalence Relation @duration{30 minutes}

=== Overview

Students transform a simple arithmetic expression to create as many equivalent Circles of Evaluation as they can. They then categorize these Circles to consider different possible transformations and to identify _Computation_ as an equivalence relation.


=== Launch

Invite students to take a look at this Circle of Evaluation:

[.centered-image]
@show{(coe '(+ 10 6))}
@clear

Explain that, to create an equivalent Circle of Evaluation, they could write this:

[.centered-image]
@show{(coe '(+ (+ 8 2) 6))}
@clear

Or they could simply write @math{16}! In this instance, the Circle has been simplified down to just one number; because we can't have Circles without functions, the Circle disappears.

Ensure that students recognize that expressions are @vocab{equivalent} when they simplify to the same value. Solicit a few other student ideas of equivalent Circles (@math{4  \times 4} or @math{15 + 1} or @math{16 \div 1}, etc) before delivering the following instructions:

[.lesson-instruction]
- On a piece of paper, you and your partner are going to create as many equivalent Circles as you can!
- You may use any numbers and any operators.
- You may also use as many numbers, operators, and circles as you’d like! You have 3 minutes.

This activity both offers students an opportunity to practice building and constructing circles and invites them to explore the notion of an equivalence relation.

As students discovered in the previous lesson, circles help us to see the underlying structure of mathematics. They are also, however, a useful tool to analyze how we can (and sometimes cannot) hop from one mathematical structure to another.


=== Investigate

Invite students to stand up and draw their contributions on the whiteboard in your classroom. Emphasize to students that the goal is to include as many unique Circles as possible! (@math{10 + 6}, for instance, is not the same as @math{6 + 10} - even though they compute the same answer.)

Once there is a good assortment of Circles on the board, invite students to take a look! What do they Notice? What do they Wonder?

//NOTICE & WONDER PEDAGOGY BOX//

After students have shared, explain the next element of the activity:

[.lesson-instruction]
- Let’s sort some of these circles into groups (of any size!).
- There is no right or wrong way to sort; in fact, you may choose to put one circle into multiple groups, and you may leave some circles ungrouped.
- You and your partner will record your groupings on a piece of paper. Come up with a name for each group so that someone else could identify what you think makes that group unique.
Who has a category for sorting circles that they see?

Work with students to identify one or two groupings as a class. If students are struggling to sort the circles, you might offer an example: _"I think I’m going to put @math{10 + 6} into a pair with @math{6 + 10} because they seem to have a lot in common... But I’m also going to put @math{10 + 6} and @math{6 + 10} into a group called single circles because they are both examples of expressions with exactly one circle."_

The subsequent lessons in this series introduce students to the Associative Property, the Commutative Property, the Identity Property, and the Distributive Property. Although students likely will not be familiar with these properties by name, it is quite likely that they will see them at play throughout the activity. Try to avoid naming properties today; instead, highlight students’ contributions and probe.

For instance, if a student observes that @math{2 \times 8} is the same as @math{8 \times 2}, you might inquire, “I wonder if that would work with division… is @math{2 \div 8} the same as @math{8 \div 2} ?”

In short: there are no wrong answers here! The goal is to help students develop a deep yet flexible understanding of the language of mathematics.



=== Synthesize

Have pairs share out their category names and make a class list. There is no need to evaluate categories’ names or qualify students’ observations; rather, challenge students to identify and articulate the patterns and transformations they have observed to lay a foundation upon which to formalize the laws of arithmetic.


== Diagramming Solving with Circles @duration{20 minutes}

=== Overview
Students use circles as a means to simplify arithmetic expressions down to one single value, making concrete the notion of computation as a circle transformation.

=== Launch

Because Circles of Evaluation help students visualize the structure of the math, they are a terrific solving tool. They create structure for students while simultaneously offering more flexibility than adhering to a strict sequential solving algorithm.

[.lesson-instruction]
--
Take a look at this example of computation as a tool for solving:

[.embedded, cols="^.^3,^.^1,^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(+ 3 (- 14 5)))} | &rarr; | @show{(coe '(+ 3 9))} | &rarr; | @math{12}
|===


- What sort of transformation happened between the first circle and the second circle? The second and the final result?
** _The first transformation was the computation of @math{5} less than @math{14}. The second computation was @math{3} increased by @math{9}._

Now take a look at this example:


[.embedded, cols="^.^3,^.^1,^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(+ (- 10 8) (* 3 6)))} | &rarr; | @show{(coe '(+ 2 18))} | &rarr; | @math{20}
|===

- Does the order in which we transform the two inner circles (above) matter?  Why or why not?
** _No, the order does not matter! We could solve the circle on the left first, or the circle on the right._

--


=== Investigate


[.lesson-instruction]
- Use what you’ve learned about circles to complete Computation as a Circle Transformation.
- Optional: On Computation as a Circle Transformation - Challenge, fill in blanks that contain addends, factors, divisors, etc, rather than just solutions.


=== Synthesize

// Need some synthesize questions that will link the two sections of the lesson together and that maybe will also foreshadow things to come? //


== Are They Equivalent? @duration{20 minutes}

=== Overview

Throughout this course, students will play two games: "True or False?" and "Which One Doesn't Belong?" Students will demonstrate their understanding of computation as an equivalence relation as they play these games.

=== Launch

Explain to students that they are about to learn to play two different games, which they will revisit periodically throughout this course. The first is "True or False?"

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Pedagogy Note: Viewing the Equal Sign as Relational}
These activities are designed to help students develop a _relational view_ of the equal sign. Students often interpret the equal sign _operationally_, or they perceive of it as meaning "now get the answer." Students with an operational view of the equal sign often solve solve 8 + 4 = ? +5 incorrectly, as either 12 or 17, whereas students who have a relational view of the equal sign are equipped to reason flexibly. Decades of research suggest that students who interpret the equal sign to mean "the same as" are better positioned to think algebraically.
|===

[.lesson-instruction]
- Let's play a round of "True or False?"
- Look at these two Circles. Use computation (or any other strategy) to determine if the statement of equivalence is true or false.
- Now try it on your own on True or False? (Computation).

The Circles in this activity were designed to support students in practicing various strategies for addi

=== Investigate

The second game, "Which One Doesn't Belong," has students analyze four different Circles to determine which Circle is not equivalent. Model your thought process before inviting students to work

=== Synthesize
