= Tree Diagrams

++++
<style>
#content .fitb{ text-align: left; }
</style>
++++

@n The Lopez family loves to go camping. So, each year Grandma buys Savannah and Rosa new gear. This year they’re getting camping mugs. They are available in 5 colors: green, blue, red, silver and copper. Draw the tree-diagram for all possible mug permutations, if Grandma chooses a mug for one girl and then the other.

@span{.center}{@image{../images/tree-practice-permutation-w-replacement.png}}

@vspace{20ex}

@n How many different permutations (with replacement) are there for these mugs?
@ifsoln{ @math{permute\mbox{-}w\mbox{-}replace(5, 2) = 5^2 = 25}  }

@vspace{10ex}

@n Grandma wonders if maybe the mugs should be different colors so that the girls can tell them apart. Draw the tree-diagram for all possible mug permutations, if Grandma chooses a mug for one girl and then the other.

@span{.center}{@image{../images/tree-practice-permutation-wo-replacement.png}}

@vspace{20ex}

@n How many different permutations (without replacement) are there for these mugs?
@ifsoln{ @math{permute\mbox{-}no\mbox{-}replace(5, 2) = \frac{5!}{(5 - 2)!} = 20} }
