= Project: Build a Video Game

@description{Students build a video game of their own design! Every game must have a player (their avatar), a danger (something to avoid), and a target (something to chase). Students build their world using function composition, animate characters through linear functions, handle keypresses with piecewise functions, detect boundaries with compound inequalities, and detect collisions with the distance formula. (Lessons that contribute to this project are marked with "🎮")}

@lesson-prereqs{inequalities-collision}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...
@objectives
@objective{apply-algebra}
@objective{game-design}

| Student-facing Lesson Goals
|

- Let's create a video game!

| Materials
|[.materials-links]

@material-links

| Preparation
|
@preparation{
- Decide if you want to teach concepts first - and culminate with students creating their games... or take an integrated approach, where students gradually add to their games over a longer period of time. It is up to you!
- Teachers are welcome and encouraged to edit and adapt the student-facing @handout{video-game-rubric.adoc} for their unique classroom context and distribute it to help students understand the scope of the project - and your expectations - at the outset.
}

| Key Points for the Facilitator
|
- Students add to their game's code during a variety of lessons in Bootstrap:Algebra. Following the default lesson order for Bootstrap:Algebra (e.g., teaching every lesson) will result in students building video games. That said, some teachers prefer to save all _game-focused lessons_ for the end of the year, allowing students to create games in 1-2 weeks.
- This project can be extended. Students can add their own "cheat codes" (piecewise/conditional functions). They can also add more complex movement (using quadratic, exponential, and trigonometric functions).

|===

== Build Your Own Video Game

=== Overview

The video game project is designed to provide real-world and engaging connections to the following mathematical concepts: 

- Locating Points on the Coordinate Plane 
- Simple and Compound Inequalities
- Domain and Range
- Function Composition
- Rate of Change in Function Definitions
- Transformations: Rotation, Dilation, and Translation
- Distance on the Coordinate Plane using the Pythagorean Theorem
- Piecewise Functions

It can be used as an end of course capstone for Bootstrap:Algebra or be integrated into the course over a longer period of time. 

=== Launch

There are six phases of video game creation. Each phase (except for the first and the last) requires that you teach:

- up to four prerequisite lessons during which students learn relevant coding skills and algebra concepts
- one lesson where students use what they've learned to update the code of their @starter-file{game, "Game Starter File"}

[cols="<.^3,<.^5a,<.^4a", stripes="none", options="header"]
|===
| Phase
| Develop Requisite Competencies
| Work on the Game

| 0 - Brainstorming
| _NA_
| 🎮 @lesson-link{coordinates}

| 1 - Game Imagery
| 

- @lesson-link{order-of-operations}
- @lesson-link{simple-data-types}
- @lesson-link{contracts-strings-images}
- @lesson-link{defining-values}
| @lesson-link{making-game-images}

| 2 - Character Movement
| 
- @lesson-link{functions-examples-definitions}
- @lesson-link{functions-dr}
| @lesson-link{functions-for-character-animation}
 
| 3 -Boundaries
| 
- @lesson-link{problem-decomposition}
- @lesson-link{inequalities1-simple}
- @lesson-link{inequalities2-compound}
| 🎮 @lesson-link{inequalities3-sam}

| 4 - Player Movement
| 
- @lesson-link{piecewise-functions-conditionals}
| @lesson-link{player-animation}

| 5 - Collisions
| _NA_
| 🎮 @lesson-link{inequalities-collision}

|===

In @link{https://bootstrapworld.org/materials/algebra/, "Bootstrap:Algebra"}, we offer many additional lessons where students can develop their math and coding skills. _The lessons outlined above are the ones considered *essential* for video game creation._ We encourage you to integrate additional lessons that meet your students' needs.

=== Synthesize

- Think about the process of creating your own video game. What was the most rewarding part? What was the most challenging part?
- What advice would you offer to someone who was trying to build a video game, like you just did?

@teacher{
- Encourage students to self-assess and revise their work as they progress through the lessons. Peer review is a powerful tool if time allows.

- Celebrate students' work! Many Bootstrap teachers arrange *video game launch parties*, essentially creating a "science fair for the math department", complete with tri-fold posters explaining elements of the game and the math at work behind the scenes.
}











