= Discover the Identity Property
++++
<style>
  table {grid-template-rows: 1fr 3fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

@n Read each verbal expression and translate it into a Circle of Evaluation. The first one has been completed for you.

[.FillVerticalSpace, cols="^.^6a,^.^7a,^.^6a",stripes="none"]
|===
| Find the sum of 12 and 4. | Find the sum of 12 and 4. Multiply it by 1. | Find the sum of 12 and 4. Add 0.

| @show{(coe '(+ 12 4))}
| @showsoln{(coe '(* (+ 12 4) 1))}
| @showsoln{(coe '(+ (+ 12 4) 0))}
|===

Are these circles @vocab{equivalent}? Why or why not? @fitb{}{@ifsoln{All three Circles evaluate to 16. The sum is unchanged when multiplying by 1 or by adding 0 }}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

The second and third Circles of Evaluation illustrate the Identity Property!

- The Identity Property of Multiplication tells us that a value *does not change* when multiplied by 1.
- The Identity Property of Addition tells us that a value *does not change* when added to 0.

@n Take a look at the _counter-examples_ below.

[.FillVerticalSpace, cols="^.^5a,^.^7a,^.^7a" header="none", stripes="none"]
|===
| Find the difference of 10 and 2. | Find the difference of 10 and 2. Multiply it by 0. | Find the difference of 10 and 2. Add one.

| @show{(coe '(- 10 2))}
| @show{(coe '(* (- 10 2) 0))}
| @show{(coe '(+ (- 10 2) 1))}
|===

Explain why each Circle of Evaluation above does *not* represent the Identity Property. @fitb{}{}

@fitb{}{@ifsoln{When we multiply a number by zero, we always get zero. Adding one to a number causes an increase in value.}}

@vspace{1ex}

@n The Identity Property of Addition involves adding zero, and the Identity Property of Multiplication involves multiplying by 1. There are also Identity Properties of _Subtraction_ and _Division_. Take a minute to think about how to complete the sentences below.

- Dividing by @fitb{5em}{@ifsoln{1}} doesn't change the value.
- Subtracting @fitb{5em}{@ifsoln{0}} doesn't change the value. 


@n Find the value that completes each expression below so that its result is identical to the product of the inner circle (@math{130 \times 40}).

[cols="^.^1a,^.^1a,^.^1a,^.^1a" header="none"]
|===

| @show{(coe '(+ (/ 130 40) (?ANS 0)))}
| @show{(coe '(* (/ 130 40) (?ANS 1)))}
| @show{(coe '(- (/ 130 40) (?ANS 0)))}
| @show{(coe '(/ (/ 130 40) (?ANS 1)))}
|===

@n Summarize what you discovered about the Identity Property. @fitb{}{}

@blanklines{2}{@ifsoln{Multiplying or dividing by one results in the same value. Adding or subtracting zero results in the same value. }}