= Discover the Identity Property
++++
<style>
  table {grid-template-rows: 1fr 3fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

@n Read each verbal expression and translate it into a Circle of Evaluation. The first one has been completed for you.

[.FillVerticalSpace, cols="^.^6a,^.^6a,^.^6a",stripes="none"]
|===

| Find the sum of 12 and 4. | Find the sum of 12 and 4. Multiply it by 1. | Find the sum of 12 and 4. Add 0.

| @show{(coe '(+ 12 4))}
| @showsoln{(coe '(* (+ 12 4) 1))}
| @showsoln{(coe '(+ (+ 12 4) 0))}
|===

Are these circles @vocab{equivalent}? Why or why not? @fitb{}{@ifsoln{All three Circles evaluate to 16. The sum is unchanged when multiplying by 1 or by adding 0 }}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

The second and third Circles of Evaluation illustrate the Identity Property!

- The Identity Property of Multiplication tells us that a value *does not change* when multiplied by 1.

- The Identity Property of Addition tells us that a value *does not change* when added to 0.

@n Take a look at the _counter-examples_ below.

[.FillVerticalSpace, cols="^.^6a,^.^6a,^.^6a" header="none", stripes="none"]
|===

| Find the difference of 10 and 2. | Find the difference of 10 and 2. Multiply it by 0. | Find the difference of 10 and 2. Add one.

| @show{(coe '(- 10 2))}
| @show{(coe '(* (- 10 2) 0))}
| @show{(coe '(+ (- 10 2) 1))}
|===

Explain why each Circle of Evaluation above does *not* represent the Identity Property.

@fitb{}{@ifsoln{When we multiply a number by zero, we always get zero. Adding one to a number causes an increase in value.}}

@fitb{}{}

@vspace{1ex}

@n The Identity Property of Addition involves adding zero, and the Identity Property of Multiplication involves multiplying by 1. Is there an Identity Property of _Subtraction_ and _Division_? Complete the Circles of Evaluation below so that the value doesn't change.

[cols="^.^6a,^.^6a,^.^6a,^.^6a" header="none"]
|===

| @show{(coe '(+ (/ 130 40) (?ANS 0)))}
| @show{(coe '(* (/ 130 40) (?ANS 1)))}
| @show{(coe '(- (/ 130 40) (?ANS 0)))}
| @show{(coe '(/ (/ 130 40) (?ANS 1)))}
|===

Summarize what you discovered about the Identity Property. @fitb{}{@ifsoln{Multiplying or dividing by one results in the same value. Adding or subtracting zero results in the same value. Because Commutativity only}}

@fitb{}{@ifsoln{applies to addition and multiplication, we must pay careful attention to the order of the values when dividing or subtracting.}}

@fitb{}{}
