= Identical Images from different Expressions? (continued)

== Warm-up
Use the @starter-file{identity} to respond to the questions below.

@n In the Interactions Area (right), type @show{(code '(circle 60 "solid" "red"))}. Then type @show{(code '(circle 1000 "solid" "red"))}.

[.FillVerticalSpace,cols="<1a,<1a", options="header"]
|===
| @center{What do you Notice?}
| @center{What do you Wonder?}
|
|
|===

@n Test `S1` and `S2` in the Interactions Area. Then, before testing the two lines of code below, make predictions about what they will produce.

- @show{(code '(overlay S1 S2))} @fitb{}{@ifsoln{an aqua square}}
- @show{(code '(overlay S2 S1))} @fitb{}{@ifsoln{an aqua square with a yellow radial star on top}}

Test your predictions.

@n Type `S3` in the Interactions Area.  What happened? Why? @fitb{}{} +
@fitb{}{@ifsoln{the cursor jumped halfway down the screen because a transparent square was drawn.}}


== Are there "Do Nothing" transformations we can write with `overlay` ?

@n With your partner, predict what each of the following expressions will return, and write your prediction in the *middle* column.

[.table1.FillVerticalSpace, cols="^.^1,^.^2,^.^1", grid="none", frame="none", stripes="none", options="header"]
|===
| Expression
| Prediction
| Equivalent to `dog`?

| @show{(code '(overlay S1 dog))}
| @fitb{30em}{@ifsoln{an aqua square}}
| Yes @hspace{3em} @ifsoln-choice{No}

| @show{(code '(overlay S2 dog))}
| @fitb{30em}{@ifsoln{a yellow radial star on top of a dog}}
| Yes @hspace{3em} @ifsoln-choice{No}

| @show{(code '(overlay S3 dog))}
| @fitb{30em}{@ifsoln{a dog}}
| @ifsoln-choice{Yes} @hspace{3em} No
|===

@n Test each line of code, and circle whether or not the result was the same as `dog` in the *third* column. Experiment to answer any questions you may have.

@n What did you discover? @fitb{}{@ifsoln{As long as a transparent shape isn't larger than the original shape, it won't change the image when overlayed.}}