= The Identity Property and Images

++++
<style>
#content td {padding: 0rem 0px !important}
#content th { text-align: center !important; }
.fitb { padding-top: 0.5rem !important; }
</style>
++++

Use the @starter-file{expressions-equations} to respond to the questions below.

== Scale

@n With your partner, predict which expressions are equivalent to `dog` and place a checkmark in front of them.

[.table1, cols="1,15,15", grid="none", frame="none", stripes="none"]
|===
|
| @fitb{1em}{@ifsoln{&#x2705;}} @show{(code '(scale (/ 5 5) dog))}
| @fitb{1em}{@ifsoln{&#x2705;}} @show{(code '(scale (+ -20 20) dog))}}

|
| @fitb{1em}{@ifsoln{&#x2705;}} @show{(code '(scale (* 1/2 2) dog))}
| @fitb{1em}{} @show{(code '(scale 0 dog))}

|
| @fitb{1em}{} @show{(code '(scale -1 dog))}
| @fitb{1em}{@ifsoln{&#x2705;}} @show{(code '(scale (+ 45 -45) dog))}
|===

@n Test each line of code in the starter-file and circle the ones that are equivalent to `dog`.

@n What do all of the equivalent expressions have in common. @fitb{}{@ifsoln{a scale factor of 1... making images 100% of the size of the original.}}

== Overlay

@n In the Interactions Area (right), type `clear-circle`. What happened? Why? @fitb{}{} +
@fitb{}{@ifsoln{the cursor jumped halfway down the screen because a an invisible shape was drawn.}}

@n With your partner, predict what each of the following expressions will return.

[.table1, cols="1,15,15", grid="none", frame="none", stripes="none"]
|===
| 
| @fitb{1em}{}@show{(code '(overlay red-star dog))}
| @fitb{}{We see a red star on the dog's chest.}

| 
| @fitb{1em}{@ifsoln{&#x2705;}} @show{(code '(overlay clear-circle dog))}
| @fitb{}{We see the dog, just as it was before.}
|===

@n Test each line of code and put a check in front of any that are equivalent to `dog`. Experiment to answer any questions you may have.

@n What did you discover? @fitb{}{@ifsoln{As long as a transparent shape isn't larger than the original shape, it won't change the image when overlayed.}}

== Rotate

@n In the Interactions Area (right), type @show{(code '(rotate 90 dog))}. What happened? @fitb{}{@ifsoln{The image rotated counter-clockwise 90°. The dog is on its side.}} 

@n With your partner, predict which expressions are equivalent to `dog` and place a checkmark in front of them.

[.table2, cols="1,15,15", grid="none", frame="none", stripes="none"]
|===
|
| @fitb{1em}{} @show{(code '(rotate 180 dog))}
| @fitb{1em}{} @show{(code '(rotate -90 dog))}

|
| @fitb{1em}{@ifsoln{&#x2705;}} @show{(code '(rotate 360 dog))}
| @fitb{1em}{@ifsoln{&#x2705;}} @show{(code '(rotate -360 dog))}

|
| @fitb{1em}{} @show{(code '(rotate 450 dog))}
| @fitb{1em}{@ifsoln{&#x2705;}} @show{(code '(rotate (* 360 19) dog))}
|===

@n Test each line of code in the starter-file and circle the ones that are equivalent to `dog`.

@n What did you discover? For what degrees did `rotate` produce an identical image? @fitb{}{@ifsoln{360°,   -360°,   360 multiplied by any integer.}}

@n How do these degree numbers relate to "one whole"? @fitb{}{@ifsoln{360° is equivalent to one complete revolution.}}

== Flip

@n In the Interactions Area (right), try out @show{(code '(flip-vertical dog))}, then try @show{(code '(flip-horizontal dog))}. What happened? @fitb{}{} +
@fitb{}{@ifsoln{`flip-vertical` flips the dog upside down. `flip-horizontal` flips the dog to face right instead of left.}} 

@n With your partner, predict which expressions are equivalent to `dog` and place a checkmark in front of them.
[.table3, cols="1,15,15", grid="none", frame="none", stripes="none"]
|===
|
| @fitb{1em}{} @show{(code '(flip-vertical (flip-horizontal dog)))}
| @fitb{1em}{} @show{(code '(flip-horizontal (flip-vertical dog)))}

|
| @fitb{1em}{@ifsoln{&#x2705;}} @show{(code '(flip-vertical (flip-vertical dog)))}
| @fitb{1em}{@ifsoln{&#x2705;}}  @show{(code '(flip-horizontal (flip-horizontal dog)))}
|===

@n Test each line of code in the starter-file and circle the ones that are equivalent to `dog`.

@n What did you discover about which flips produce an identical image? @fitb{}{@ifsoln{A pair of either flip type will complete the flip}} +
@fitb{}{@ifsoln{so that the dog goes all the way around back to where it started.}} 