= Choosing Your Dataset

@description{Students practice making a variety of chart types and then begin to investigate a real world dataset, which they will continue to work with for the remainder of the course. }

@ifproglang{pyret}{
@lesson-prereqs{contracts-tables-displays}}

@ifproglang{codap}{
@lesson-prereqs{}}


@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* Explain why they chose their dataset
* Describe their dataset
* Make subsets from their dataset

| Student-facing Lesson Goals
|

* Let's all choose an interesting dataset to investigate.

| Materials
|[.materials-links]

@material-links

@ifproglang{pyret}{
| Supplemental Materials
|[.materials-links]
@opt-material-links
}

| Preparation
|
- Decide how much choice you're ready to offer your students before you begin. Research shows that choice increases student engagement! But focusing the whole class on a single dataset is also an option.
  * Would focusing your students on a single dataset make this doable for you? Because you teach younger students who might need more scaffolding? Or because you are new to teaching data science and managing fewer moving parts would increase your confidence? We recommend focusing on @opt-starter-file{food}.
  * Are you ready to jump straight into supporting your students in working on a wide range of topics of their choosing? We have a full dataset library!
  * Want to give students choice from a shorter curated list...to shorten the decision-making process, focus on topics related to curriculur goals, or just to have fewer options to manage during class?  We've assembled @opt-online-exercise{about-datasets/for-teachers-about-datasets.html, descriptions of individual datasets here}. For those looking for a precurated shorter list, we've starred a few of them for you.
  * *If you have time*, you may want to complete all of the lessons with everyone getting extra practice analyzing opt-starter-file{food} and then have your students choose a dataset to analyze for their culminating research papers!
- If you decide on anything less than our full dataset library and are using our Google Slides, be sure to update the slide deck to point students to the options you want them to see.
|===

== Review: Consider Data @duration{20 minutes}

=== Overview
Students practice making lots of chart types, focusing specifically on the "Consider Data" step in the Data Cycle and how it can be used alongside Contracts to help go from questions to code.

=== Launch

The Data Cycle is a roadmap that guides us in the process of data analysis. You've learned that the Data Cycle includes four steps. Let's review what those steps entail.

@QandA{

@Q{*Ask Questions* - What are the different types of questions we can ask?}
@A{Lookup, arithmetic, and statistical questions.}

@Q{What's the difference between an arithmetic question question and a statistical question?}
@A{A statistical question does not specify a particular arithmetic process, while an arithmetic question does.}

@Q{*Consider Data* - What does this phase entail?}
@A{We need to determine: "What rows should we investigate?" and "What columns do we need?"}

@Q{*Analyze Data* - We'll choose what kind of display we'll need to answer our question. Which two displays work with categorical data? Why might you choose one over the other?}
@A{@ifproglang{pyret}{Bar and pie charts work}@ifproglang{codap}{Dot plots and bar charts} with categorical data. @ifproglang{pyret}{A pie chart only makes sense when you have the full picture, whereas a bar chart shows the count.} @ifproglang{codap}{A dot plot conveys more precise information than a bar chart, but can be overwhelming if there is a lot of data}.}

@Q{*Interpret the Data* - In your own words, what happens during this phase?}
@A{We answer questions and summarize results, which often leads to new questions.}
}

=== Investigate

In this lesson, we're going to get some practice with the second step of the cycle - Consider Data - identifying the Rows and Columns needed to answer various questions, and using our knowledge of Contracts to help turn those questions into working code!

@lesson-instruction{
Complete @printable-exercise{consider-and-analyze.adoc}.
}

=== Synthesize

- What strategies did you use to determine which columns to use?
- Why do the contracts for some displays require more arguments than others?

== Choosing a Dataset @duration{30 minutes}

=== Overview
Students select a dataset that interests them (or are assigned a realworld dataset to focus on), and do some thinking about _why_ it interests them, _what questions they'd like to answer_ and _what hypotheses they have_. They'll be analyzing this data for a long time, so it's critical to ensure a high degree of buy-in before signing off on a student's choice!

@teacher{
Note: Some teachers opt to focus their classes on a single dataset. We recommend @opt-starter-file{food} for this purpose.
}

=== Launch

**Data Science: it's all about YOU!**

What data matters to *_you?_* What questions do *_you_* care about? 

We live in a world filled with data, gathered about almost every subject you can imagine.

- Climate sensors are gathering data on temperature, humidity, oxygen and more...practically everywhere on the globe.
- Census data tracks the number of different groups of people, as well as their education, income level, and more.
- Companies like Facebook, Amazon, and Google gather massive amounts of data on the websites you visit, what you chat about online, what you purchase, etc.

@slidebreak

Data is used to set public policy, draw voting districts, approve drugs, calculate school funding, decide which advertisements you see, and more.

@lesson-instruction{
* Where else do you see data being gathered?
* What are some other ways data is used in the world around you?
}

@slidebreak

For the rest of this course, you'll be:
- learning new programming and @vocab{Data Science} skills
- practicing them with the Animals Dataset 
- and then applying them to another dataset.

@teacher{
What follows is our *Dataset Library*@ifproglang{pyret}{ with Starter Files that instantly import the (cleaned) data into Pyret}. 

* If you are planning to give students this full list, here's @handout{pages/datasets-and-starter-files.adoc, a direct link to this table}.
* Many teachers opt to offer a smaller curated list that is more tailored to their goals. We've assembled @opt-online-exercise{about-datasets/for-teachers-about-datasets.html, descriptions of individual datasets here} to help you decide which you'd like your students to focus on.
@ifproglang{pyret}{
* _Students can also find their own dataset_ and follow the directions in  @opt-starter-file{blank-ds-tutorial} to import a spreadsheet into @opt-starter-file{blank-ds, a copy of this pyret Dataset Starterfile Template}.
* *Note: If you are opting to focus your whole class on a single dataset, share the links to the @link{https://docs.google.com/spreadsheets/d/1DYVHT7SSjnoDp4MQ80Z1qZSqFdEIlR8Gd20eMx9f1JA/, spreadsheet} and @opt-starter-file{food, starter file} now and skip to the Investigate section.*
}
}

@slidebreak

@lesson-instruction{
- Choose a dataset that is of interest to you@ifslide{ from 
@handout{pages/datasets-and-starter-files.adoc, our Dataset Library}}. 
- Open your dataset's starter file in @proglang @ifproglang{pyret}{and save a copy}.
- Look at the spreadsheet or table for your dataset.
- What do you *Notice*? What do you *Wonder*?}

@ifnotslide{@include{fragments/dataset-table.adoc}}

=== Investigate

@teacher{
By now students will either have chosen a dataset of their own or you will have decided to focus your class on a single dataset (we recommend @opt-starter-file{food} for this purpose.) They will be applying what they learn to this new dataset.
}

@lesson-instruction{
- Using your @proglang starter file, complete @printable-exercise{pages/my-dataset.adoc}.
- Make sure to include at least two questions that __can__ be answered by your dataset and one that __cannot__.
@ifproglang{pyret}{
- In the Definitions Area, use `random-rows` to define *at least three* tables of different sizes: `tiny-sample`, `small-sample`, and `medium-sample`.}
}

=== Synthesize

* Which dataset did you select? And why? 
* What questions are you curious to dig into?

== Dataset Exploration Project @duration{flexible}

=== Overview

Students are introduced to the Dataset Exploration Project, which will be woven into lessons from here on out. 

Today we'll start by adding four items to their @starter-file{exploration-project}: 

1. a description of their dataset, including its source, structure, and relevance
2. at least one bar chart
3. at least one pie chart
4. any interesting questions they develop

@teacher{
To learn more about the scope and sequence of the exploration project, visit @lesson-link{project-data-exploration}.
}

=== Launch

For the rest of this course, each time we learn about a new data science concept, you will add displays, questions, and analyses about your Dataset Exploration Project.

@lesson-instruction{
- Open the @starter-file{exploration-project}.
- Save your own copy of the slide deck.
- Let's get a sense of what this project is all about - take a few minutes to look at the slides.}

@QandA{
@Q{What do you Notice? What do you Wonder?}
@A{Students will likely notice references to many displays they are unfamiliar with.}
@A{They may wonder how there is going to be so much analysis on just one dataset!}
@A{Blue text is included to provide examples.}
@A{Slides can be duplicated if students want to add additional displays or interpretations.}
}

=== Investigate

@lesson-instruction{
- Complete all of the slides you see in the "About this Dataset" portion of the slide deck. 
- It may be helpful to refer to what you wrote on @printable-exercise{pages/my-dataset.adoc}.
}

@slidebreak

@lesson-instruction{
- Choose one categorical column from your dataset that you will represent with a bar chart.
- Turn to the top section of @printable-exercise{data-cycle-categorical.adoc} and record a question that your bar chart could answer.
- Complete the rest of the data cycle, recording how you considered, analyzed, and interpreted the question.
- Repeat this process for at least one more categorical column - but this time, create a pie chart.
- Then, copy/paste at least one bar chart and one pie chart into that section of your slide deck. 
- Be sure to also add any interesting questions that you developed while making and thinking about these displays to the "My Questions" slide at the end of the template.
}

@teacher{
_You may need to help students locate the “Bar Charts” section, “Pie Charts” section, and “My Questions” slide in the template._
}

=== Synthesize

Let's share what we learned about our datasets!

- Did you discover anything surprising or interesting about your dataset?

- What questions did the bar and pie charts inspire?

- Did other students make any discoveries that were surprising or interesting to you?
