= Inequalities 2

*Students use what they've learned about inequalities working together to set screen boundaries in their game*


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Describe how functions can work together
* Make mathematical adjustments relevant to their game

|Student-Facing Lesson Goals
|
* I can tell someone else how two or more functions work together.
* I can make adjustments to a program based on how the program behaves.

|Key Points for the Facilitator
|
* Key points

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.

|Materials
|
* Links to printables, activities, etc., go here
|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Math Standards (CCSS)
|
* http://www.corestandards.org/Math/Practice/MP2[CCSS.MATH.PRACTICE.MP2],
Reason abstractly and quantitatively.


|CS Standards (CSTA)
|
* CS Standards here.
|===


== Get Ready:

Students should have their computer, contracts page, and pencil.

== Launch: (5 min)

Have students open their in-progress Video Game file and press Run.  

...

== Discuss: (10 min)

* How are the `TARGET` and `DANGER` behaving right now? _They move across the screen._
* What do we want to change? _We want them to come back after they leave one side of the screen._
* How do we know when an image has moved off the screen?  _We can see it._
* How can we make the computer understand when an image has moved off the screen? _We can give it a numeric boundary, just like we did with Sam the Butterly!_

== Apply: (20 min)

Students apply what they learned from Sam the Butterly to fix the `safe-left?`, `safe-right?`, and `onscreen?` functions in their own code.  Since the screen dimensions for their game are 640x480, just like Sam, they can use their code from Sam as a starting point.

Students will need to test their code with their images to see if the boundaries are correct for them.  Students with large images may need to use slightly wider boundaries, or vice versa for small images.  In some cases, students may have to go back and rescale their images if they are too large or too small for the game.  
