= How do Horizontal and Vertical Shifts Relate? (Negative Slopes)


[cols="1a,8a,16a",stripes="none"]
|===
| ORIGINAL
| @centered-image{../images/lin-3x.png}  
|
[cols="1a", frame="none", grid="none",stripes="none"]
!===
! @math{y = -3x}     
!===

|@n
| @centered-image{../images/lin-3x-9.png} 
|
[.FillVerticalSpace, cols="1a", frame="none", grid="none",stripes="none"]
!===
! @math{y = -3(x + 3)}
! Horizontal shift from ORIGINAL: @fitb{}{@ifsoln{right 3}}						
! Vertical shift from ORIGINAL:	@fitb{}{@ifsoln{up 9}}
! Distribute to rewrite the equation in slope-intercept form:
@ifsoln{@math{y = -3x + 9}}
!===

|@n
| @centered-image{../images/lin-3x+6.png} 	
|
[.FillVerticalSpace, cols="1a", frame="none", grid="none",stripes="none"]
!===
! @math{y = -3(x + 2)}
! Horizontal shift from ORIGINAL: @fitb{}{@ifsoln{left 2}}					
! Vertical shift from ORIGINAL: @fitb{}{@ifsoln{down 6}}
! Distribute to rewrite the equation in slope-intercept form:
@ifsoln{@math{y = -3x - 6}}

!===
|===

@n What do you notice? What do you wonder?

@ifsoln{
Answers will vary. Students may notice that:
- horizontal shifts can also be thought of as vertical shifts
- shifting a negative line left can be accomplished by shifting the line down
- shifting a negative line right can be accomplished by shifting the line up 
}
