= Solving Word Problems

@description{Students are introduced to the Design Recipe as a scaffold for breaking down word problems into chunks that will support them in writing code.}

[@lesson-intro-table]
|===
@lesson-prereqs{defining-functions}
| Lesson Goals
| Students will be able to:

* Understand how to use the Design Recipe to break down word problems.
* Create a strong purpose statement that details in their own words what the function should do.

| Student-Facing Lesson Goals
|
* I can write my own function in @ifproglang{wescheme}{WeScheme} @ifproglang{pyret}{Pyret}.
* I can use the @vocab{Design Recipe} to break down word problems when writing a @vocab{function}.

| Materials
|[.materials-links]

@ifproglang{wescheme}{
*  @link{https://docs.google.com/presentation/d/1rv1ZBNUP_hq0C-jf8IrjYIBmMH9U36u33Ah61IvorBg/, Lesson slides}
}

@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1yK_PFOVb3K7iysuviOg00qj8vaPtFipoFId_h6TRLME/, Lesson Slides}
}

@material-links

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

@ifproglang{wescheme}{
| Supplemental Resources
|
@link{https://teacher.desmos.com/activitybuilder/custom/5d991b421172d473178c981b, Design Recipe Practice - Desmos Activity}}


| Key Points for the Facilitator
|
* The *purpose statement* is a comment in the code - something the computer doesn't read.  It is important for readability of their code - there may be other people looking at their code and using their functions!
* Remind students that the domain and range of a function must be one or more of the @vocab{data types} (Number, String, Image, Boolean, etc.) they've learned so far.
* If students struggle with creating the examples, use the Circle of Evaluation mapping activity or use role-playing to help students build up their understanding around the concept.

@lang-prereq

|===

[.old-materials]
Click here to see the @link{https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/units/unit4/index.html, prior unit-based version}

== The Design Recipe @duration{10 minutes}

=== Overview
In this lesson students build on what they already know about multiple representations of functions (contracts, examples and definitions) to write purpose statements and gain fluency with the Design Recipe.

=== Launch
Have students turn to @printable-exercise{pages/create-contracts-examples.adoc} and write contracts for the examples provided.


=== Investigate
Of course, solving equations is something that calculators and computers can do for us! That's where word problems come in: a word problem is a description of a situation, and the trick is to figure out the mathematical relationships that describe it. Figuring out the relationships that govern everything from the fuel efficiency of an engine to the best way to build a bridge is where math gets creative, applied, and fun!

But seeing the math behind the words can be challenging! In this lesson, you're going to learn a strategy for breaking down word problems, called the *Design Recipe*.

You've actually seen most of the steps of the Design Recipe, but there's one part you haven't seen: _writing a purpose statement_. On its own, a contract is not enough information to generate examples and write a function definition. We need to know what the @vocab{function} is supposed to do with what it takes in. Programmers and Mathematicians alike find it helpful to restate a problem in their own words. After all, if you can't explain a problem to someone else, you probably don't understand it yourself!

[.lesson-instruction]
Turn to @printable-exercise{pages/create-examples-contracts-purpose-1.adoc} and read the purpose statements. What do you notice? What do you wonder?

Debrief the notice and wonder as a class. Then have students write examples that satisfy each of the contracts and purpose statements on @printable-exercise{pages/create-examples-contracts-purpose-1.adoc}.

OPTIONAL: For more practice, have students complete @opt-printable-exercise{pages/create-examples-contracts-purpose-2.adoc}.

=== Synthesize
What are the important elements of purpose statements?
Why are purpose statements useful?

== Writing Linear Functions @duration{25 minutes}

=== Overview
Students are given a non-working program, which uses a linear function to determine the height of a rocket after a given length of time. The "broken" code is provided to lower cognitive load, allowing students to focus on comprehension (reading the code) and making use of structure (identifying where it's broken).

=== Launch

Students should have their workbook, pencil, and be logged into
@ifproglang{wescheme}{ @link{https://www.wescheme.org, WeScheme     } }
@ifproglang{pyret}{    @link{https://code.pyret.org, code.pyret.org } }
on their computer.

Ask students to open the
@ifproglang{wescheme}{ @online-exercise{https://www.wescheme.org/openEditor?publicId=LGTVNvzrax, rocket-height Starter File} and click "Run". By typing `(start rocket-height)`, they will see the simulation start to run on their computer. }
@ifproglang{pyret}{ @online-exercise{https://code.pyret.org/editor#share=1pkPbRg_xXYum_gTQ-2GmcPa3iL4Eq6Kd&v=7db4b91, rocket-height Starter File} and click "Run". By typing `start(rocket-height)`, they will see the simulation start to run on their computer. }

[.notice-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Notice and Wonder}

What do you notice about this program?  What do you wonder?
|===

Survey the class on their "Notices" and "Wonders" and record on the board before moving on to the discussion.

[.lesson-instruction]
- Is `rocket-height` working?
- Why do you think it's not working?
- What do you think the *purpose* of this function is?  How do you know?

- What is the domain of `rocket-height`?
_Number_

- What is the range of `rocket-height`? How do you know?
_Number, we can tell by looking at the @vocab{contract} for the function._

- As the program is currently written, what happens when I give the function an input of 5?  15?  One million?
_It always returns 0._

=== Investigate

Let's use the Design Recipe to fix `rocket-height`, and get comfortable with writing *purpose statements*.

Have students turn to @printable-exercise{pages/rocket-height.adoc}, read the problem statement with their partner and write down the @vocab{Contract} and @vocab{purpose statement}. Then, given the contract and purpose statement, write two examples of how `rocket-height` should work after two different lengths of time.

[.lesson-instruction]
- Circle and label what's changing in the two examples, just as you did with the green triangle function before.
- Choose a good variable name for what's changing.
- Write the function definition using the variable name.

Once the Design Recipe has been completed in the workbook, students can type the code into the `rocket-height` program, replacing any incorrect code with their own code.

=== Synthesize
- What was the problem?
- What mistake(s) did the programmer make?
- Where in the Design Recipe did they first go astray?

_The Design Recipe allows us to trace mistakes back to the source!_

== More Interesting Functions @duration{flexible}

=== Overview
For teachers who cover quadratic and exponential functions, this activity deepens students' understanding of functions and extends the Design Recipe to include those. This can also be a useful activity for students who finish early, or who need more of a challenge.

=== Launch
Now that `rocket-height` is working correctly, explore the rest of the file and try the following:

- Remove the comment from before the `(start rocket-height)` and test the program.
- Put the comment back in front of `(start rocket-height)`, remove the comment from `(graph rocket-height)`, and test the program.
- Try out `(space rocket-height)`
- Try out `(everything rocket-height)`

=== Investigate
[.lesson-instruction]
- Can you make the rocket fly faster? Slower?
- Can you make the rocket sink down instead of fly up?
- Can you make the rocket _accelerate over time_, so that it moves faster the longer it flies?
- Can you make the rocket blast off _and then land again_?
- Can you make the rocket blast off, _reach a maximum height of exactly 1000 meters_, and then land?
- Can you make the rocket blast off, reach a maximum height of exactly 1000 meters, and then land after exactly 100 seconds?
- Can you make the rocket fly to the edge of the the universe?

=== Synthesize
Debrief - what did students try? Have students share their experiments with one another!

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{The Design Recipe in your Classroom}

The three steps of the Design Recipe are designed to mirror best practices that you may already be using in your classroom. The Design Recipe is merely a collection of those practices, assembled in a structured way.

Writing the Contract and Purpose Statement is where students _understand_ the word problem. If you have your students restate the problem in their own words, draw pictures, or underline the inputs and outputs in the word problem, __you're already using this practice!__

Writing examples and circles-and-and labeling what changes is where students _apply_ their understanding. If you have your students work through some concrete examples before jumping straight to variables and formulas, and ask them "what's the rule?" or "what's the pattern?", __you're already using this practice!__.

The order of the recipe is a recommendation based on years of research about what works for most students, but that doesn't mean this order works best for every student! Some may find it easier to work through a concrete example or two before thinking about Domain and Range, and there's nothing wrong with that. We encourage you to use the Recipe in your classroom as often as possible, teaching students to be flexible with the tools and representations it includes.
|===


== Additional Exercises:
- @opt-printable-exercise{pages/create-examples-contracts-purpose-2.adoc}
- @opt-printable-exercise{pages/examples-same-contracts1.adoc}
- @opt-printable-exercise{pages/examples-same-contracts2.adoc}
- @opt-printable-exercise{pages/match-contracts-examples1.adoc}
- @opt-printable-exercise{pages/match-contracts-examples2.adoc}
