= Describing Relationships (2)

A small sample of people were surveyed about their satisfaction with their most recent purchase using a scale from 1 (very unsatisfied) to 5 (extremely satisfied). +
*NOTE: this data is made up for instructional purposes!*

[cols="^1a, ^1a", grid="none", frame="none"]
|===
|
[.data-table, cols="^.^1, ^.^1", options="header"]
!===
! 	Dollars 	! 	Satisfaction
! 	15.5  		! 		4
! 	280  		! 		5
! 	0.99  		! 		1
! 	2.3  		! 		3
! 	39   		! 		3
! 	82   		! 		4
! 	215  		! 		4
! 	700   		! 		4
! 	25   		! 		3
! 	79   		! 		4
! 	99.99  		! 		5
! 	30  		! 		1
! 	75  		! 		5
! 	13  		! 		4
! 	320   		! 		5
! 	260   		! 		5
! 	150   		! 		1
! 	28   		! 		1
! 	45  		! 		2
! 	65  		! 		2
!===
| @image{../images/purchase-scatter-plot.png, 350 }
|===

Describe the relationship between dollars spent and satisfaction shown in the data above.

@blanklines{8}{
@ifsoln{There is a weak positive relationship (r-value = 0.4) between number of dollars spent on an item and satisfaction with that item. Based on the r-squared value, about 16% of the variation in satisfaction can be explained by amount of money spent. For each extra dollar spent, this data suggests a person will rate their satisfaction 0.004 stars higher. If 0 dollars were spent (item was free) the rating would be ~2.85. However, since 0 is outside our range of data, we are not confident in this.}
}
