= Introduction to Linear Regression

== How much can one point move the line of best fit?

@link-instructions{
Open the @online-exercise{https://www.geogebra.org/m/ZcVIxKtF, Interactive Regression Line}. Move the blue point “P”, and see what effect it has on the red line.
}

@n Move P so that it is *centered amongst* the other points. Now move it all the way to top and bottom of the screen.

@n Move P so that it is *far to the left or right* of the other points. Now move it all the way to top and bottom of the screen. How - if at all - does the x-position of P impact on the line of best fit? @fitb{}{}

@fitb{}{@ifsoln{When P is far to the left or right of the point cloud, changes in the y-value have a much bigger impact}}

@n Could the @vocab{regression line} ever be above or below _all_ the points _(including the blue one you're dragging)_? Why or why not? @fitb{}{}

@fitb{}{@ifsoln{No - the forces acting on the line must be balanced, so at least one point needs to pull the line opposite the other points}}

@n Would it be possible to have a line with more points on one side than the other? Why or why not?  @fitb{}{}

@fitb{}{@ifsoln{Yes - as long as the forces are balanced, it doesn't matter how many points on each side afe exerting them}}

@n What is the highest @math{r}-value you can get? @fitb{10em}{} @hspace{4em} Where did you place @math{P}? @hspace{2em} (@fitb{4em}{}, @fitb{4em}{})

@n What function describes the regression line with this value of @math{P}? @hspace{2em} @math{y =} @fitb{8em}{} @math{x +} @fitb{8em}{}

@n What is the lowest @math{r}-value you can get? @fitb{10em}{} @hspace{4em} Where did you place @math{P}? @hspace{2em} (@fitb{4em}{}, @fitb{4em}{})

@n What function describes the regression line with this value of @math{P}?  @hspace{2em} @math{y =} @fitb{8em}{} @math{x +} @fitb{8em}{}

== Predictions from Scatter Plots

[cols="1,1", frame="none", grid="none", stripes="none"]
|===
| @centered-image{../images/age-v-weeks.gif, 275} | @centered-image{../images/pounds-v-weeks.gif, 275}
|===

@n Use a straight edge to draw what you think would be the line of best fit for *age vs. weeks* (on the left). +
Is this a strong correlation that will allow us to make a good prediction of an animal's adoption time just by knowing how old it is?

@fitb{}{@ifsoln{It is relatively strong. We will be able to make a decent prediction of adoption time based on age.}}

@n Use a straight edge to draw what you think would be the line of best fit for *pounds vs. weeks* (on the right). +
Is this a strong correlation that will allow us to make a good prediction of an animal's adoption time just by knowing how heavy it is?

@fitb{}{@ifsoln{It is relatively strong. We will be able to make a decent prediction of adoption time based on pounds.}}

@n Do either or both of the relationships appear to be linear?

@fitb{}{@ifsoln{They both appear to be linear.}}

@vspace{3ex}
