= Making Predictions

@span{.center}{@image{../images/age-v-height.png, 600}}

@n About how many inches are kids in this dataset expected to grow per year? @fitb{}{@ifsoln{3 inches}}

@vspace{1ex}

@n At that rate, if a child were 45" tall at age eight, how tall would you expect them to be at age twelve? @fitb{}{@ifsoln{57 inches}}

@vspace{1ex}

@n At that rate, if a ten-year-old were 55" tall, how tall would you expect them to have been at age 9? @fitb{}{@ifsoln{49 inches}}

@vspace{1ex}

@n Using the equation, how tall would you expect a seven-year-old child to be? @fitb{}{@ifsoln{46.6 inches}}

@vspace{1ex}

@n How many of the seven-year-olds in this sample are actually that height? @fitb{}{@ifsoln{zero!}}

@vspace{1ex}

@n Using the equation, determine the expected height of someone who is...

[cols="^1,^1,^1,^1,^1", options="header"]
|===
| 7.5 years old 		| 13 years old			| 6 years old				| newborn 					| 90 years old
| @ifsoln{48 in}
@vspace{3ex}			| @ifsoln{65 in} 	| 	@ifsoln{43.5 in}	| @ifsoln{25.2 in}	| @ifsoln{300 in}
|===

@n For which ages is this predictor function likely to be the *most* accurate? Why? @fitb{}{@ifsoln{Only ages within the range of the dataset.}}

@fitb{}{@ifsoln{This function might be incredibly accurate for this population but that doesn't mean it's accurate for other populations!}}

@fitb{}{@ifsoln{A great predictor for the heights of students at a basketball training camp could be a terrible predictor when used with students at a gymnastics camp.}}

@n For which ages is this predictor function likely to be the *least* accurate? Why? @fitb{}{@ifsoln{The regression might still work for extrapolating the height of a}}

@fitb{}{@ifsoln{6-year-old or a 13-year-old, since they are just beyond the range of the dataset, but it makes no sense to use this equation to figure}}

@fitb{}{@ifsoln{out the height of a 90-year-old or babies, because humans don't grow at a constant rate for their entire life!}}
