= Linear Regression in a Nutshell

@vspace{1ex}

* *We compute linear relationships to predict the future!* Well...sort of. Given a dataset, like ages of animals v. how long before they're adopted, we try to compute the relationship between `age` and `weeks` so that we can _predict_ how long a new animal might stay, based on their age.

* When we compute linear relationships, we're talking about *straight-line patterns* that appear on a scatter plot.

* A scatter plot has an x-axis and a y-axis. When looking for relationships, the y-axis is called the @vocab{response variable}, and the x-axis is called the @vocab{explanatory variable}. In our example, we are trying to figure out how much of the `weeks` variable is _explained by_ the `age` variable.

* *Linear Regression* is a way of computing the *line of best fit*, which tries to draw a line as close as possible to all the points. (Want details? It minimizes the _sum of the squares_ of the vertical distances from the points to the line. There's a reason we use computers to do this!)

* *Slope* is how much we predict the @vocab{response variable} will increase or decrease for each unit that the @vocab{explanatory variable} increases. In our example, a slope of 0.5 would mean "we predict that each additional year of age means an extra half-week in the shelter". (What would a slope of 3 mean?)

* *Sample size matters!* The number of data values is also relevant. We'd be more convinced of a positive relationship in general between cat age and time to adoption if a correlation of +0.57 were based on 50 cats instead of 5.
