= Tree Diagrams 2

++++
<style>
#content .fitb{ text-align: left; }

.ulist li { border: solid 1px green; height: 1.5rem; position: relative;}
.ulist li p { border: solid 1px blue; }
.ulist li p .fitb{ border: solid 1px red; }
td { padding: 5px !important; }
tr { height: 25px; }

@media screen {
	.ulist p { min-height: 1.5rem !important; }
}
</style>
++++

@n An ice cream truck sells 2-scoop cones, and each scoop can be Chocolate, Vanilla, or Strawberry. They also let you choose *one* topping: whipped cream or sprinkles. In the space below, draw the tree-diagram for all the possible ice cream cones you can order (with toppings!):

[.FillVerticalSpace, cols="1", frame="none", grid="none"]
|===
| @ifsoln{@image{../images/ice-cream-tree.png}}
|===


@n How many permutations are there for these 2-scoop cones and toppings?
@fitb{}{@ifsoln{ @math{\text{permute-w-replace}(3, 2) \times 2 = 3^2 \times 2 = 27} }}

@n Now the truck adds a 4th-flavor: _Rocky Road_. To get more people trying new flavors, the truck offers $1 off a 2-scoop cone, as long as both scoops are different flavors. In the space below, we've started making a list of every possible 2-scoop cone where both scoops are different. Can you finish the list?

[cols="^1,^1"]
|===
| Bottom Scoop 				| Top Scoop

| Chocolate					| Vanilla
| Chocolate					| Strawberry
| Chocolate					| Rocky Road
| Vanilla 					| Chocolate
| @ifsoln{Vanilla}			| @ifsoln{Strawberry}
| @ifsoln{Vanilla}			| @ifsoln{Rocky Road}
| @ifsoln{Strawberry}		| @ifsoln{Vanilla}
| @ifsoln{Strawberry}		| @ifsoln{Rocky Road}
| @ifsoln{Strawberry}		| @ifsoln{Chocolate}
| @ifsoln{Rocky Road}		| @ifsoln{Vanilla}
| @ifsoln{Rocky Road}		| @ifsoln{Strawberry}
| @ifsoln{Rocky Road}		| @ifsoln{Chocolate}
|===

@n How many different permutations are there for these ice cream cones?

@fitb{}{@ifsoln{ @math{\text{permute-wo-replace}(4, 2) \times 3 = \frac{4!}{(4 2)!} \times 3 = 48} }}

@fitb{}{}
