= Tree Diagrams 2

++++
<style>
#content .fitb{ text-align: left; }

.ulist li { border: solid 1px green; height: 1.5rem; position: relative;}
.ulist li p { border: solid 1px blue; }
.ulist li p .fitb{ border: solid 1px red; }

@media screen {
	.ulist p { min-height: 1.5rem !important; }
}
</style>
++++

@n An ice cream truck sells 2-scoop cones, and each scoop can be Chocolate, Vanilla, or Strawberry. They also let you choose *one* topping: whipped cream or sprinkles. In the space below, draw the tree-diagram for all the possible ice cream cones you can order (with toppings!):

@ifnotsoln{ @vspace{40ex} }

@ifsoln{@image{../images/ice-cream-tree.png}}

@n How many different permutations are there for these ice cream cones?
@ifsoln{ @math{\mbox{permute-w-replace}(4, 2) \times 3 = 4^2 \times 3 = 48} }
@vspace{10ex}

@n Each 2-scoop cone costs $3.99, but if you pick two _different_ flavors you can save $0.50. In the space below, we've started making an organized list of the possibilities for ice cream orders where the two flavors are different, listing the bottom scoop's flavor & the top scoop's flavor.  Complete the list for all possible cone orders if the choices available are Chocolate, Vanilla, and Strawberry.

@fitb{}{Chocolate & Vanilla}

@fitb{}{Chocolate & Strawberry}

@fitb{}{Chocolate & Rocky Road}

@fitb{}{Vanilla & @ifnotsoln{...} @ifsoln{Chocolate}}

@fitb{}{@ifsoln{Vanilla & Strawberry}}

@fitb{}{@ifsoln{Vanilla & Rocky Road}}

@fitb{}{@ifsoln{Strawberry & Vanilla}}

@fitb{}{@ifsoln{Strawberry & Rocky Road}}

@fitb{}{@ifsoln{Strawberry & Chocolate}}

@fitb{}{@ifsoln{Rocky Road & Vanilla}}

@fitb{}{@ifsoln{Rocky Road & Strawberry}}

@fitb{}{@ifsoln{Rocky Road & Chocolate}}

@n How many different permutations are there for these ice cream cones?

@ifnotsoln{
@fitb{}{}

@fitb{}{}
}

@ifsoln{ @math{\mbox{permute-wo-replace}(4, 2) \times 3 = \frac{4!}{(4 2)!} \times 3 = 48} }
