= Exploring State Demographics

@description{Students look for linear relationships in demographic data about US states using scatter plots in Pyret. Emphasis is placed on testing our hypotheses by making scatter plots, rather than making plots before really thinking about them.}

@lesson-prereqs{fitting-models}

@keywords{}

@add-to-lang{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|

- Let's explore demographic data from the US states and Washington, D.C.


| Materials
|[.materials-links]
@material-links


| Key Points For The Facilitator
|
- _Heads up: This lesson opens with an optional QandA for those who have completed our @lesson-link{fitting-models} lesson. If you haven't taught that lesson, open with the states discussion that follows._
- This lesson is the first of four in the linear models sequence, which establishes a structure we will revisit for exploring other kinds of relationships in data:
    * identify possible relationships in a dataset
  	* build a model from samples
  	* fit a model
  	* improve upon the model
|===

== Exploring the Data
@objective{model-explore}
@objective{interpret-real-world-scatter-plot}
@objective{linear-situations}

=== Overview
Students explore relationships between columns in the State Demographics dataset and practice defining rows in Pyret.

=== Launch

@opt-block{

@ifslide{OPTIONAL}Let's think back to our @lesson-link{fitting-models} lesson...

@QandA{

@Q{What kind of data does the `age` variable represent? What about `pounds`?}
@A{Both `age` and `pounds` are quantitative variables.}

@Q{What kind of data visualization helped us to analyze the relationship between weight and adoption time?}
@A{A @vocab{scatter plot}, because it shows the relationship between two quantitative variables}

@Q{When we fit a model to the scatter plot, what measure did we use to determine how well it fit the lizard data?}
@A{We used @math{S} - the Standard Deviation of the Residuals - to measure fitness.}
@A{When comparing models for a given dataset, the model with the lowest @math{S} makes predictions with the least error.}
}
}

@slidebreak

We're going to be working with a dataset about the states in the US. Let's pick a few states to keep an eye out for as we work.

@QandA{
@Q{What states should we focus on besides our own?}
@A{Our neighbors!}
@A{A state we've always wanted to visit!}
@A{Solicit other ideas...}
}

@slidebreak

@QandA{
The dataset we are going to be working with locates each state within a region of the United States. Cartographers aren't in total agreement about how best to describe _regions_ of the U.S.
@Q{What would you call the region we live in?}
@A{Examples: New England, West Coast, Southeast..}
@Q{What other states are in this region?}
@A{Answers will vary...}
}

@teacher{
Come to a consensus about which states your students will explore. When more students are looking into the same data, you'll find much richer class discussions!  If students aren't familiar with neighboring states, @link{https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States#/media/File:Map_of_USA_with_state_and_territory_names_2.png, here's a useful map!}

If your students strongly disagree with how the dataset categorizes what region your state is a part of, @link{mailto:contact@bootstrapworld.org, please let us know}!
}

@slidebreak

@lesson-instruction{
- Open the @starter-file{alg2-states} and save a copy that's just for you. Then click "Run".
- Turn to @printable-exercise{exploring-states.adoc} and take a minute to record your Notices and Wonders in the table at the top.
}

@slidebreak

@QandA{
@Q{What did you Notice?}
@Q{What did you Wonder?}
@Q{Which column in this dataset will we generally use as our identifier column?}
@A{`state`}
@Q{Which columns in this dataset are categorical?}
@A{`region`, `pop-trend`, `poverty-rate`}
@Q{Which columns in this dataset have to do with wealth?}
@A{`pct-in-poverty`, `poverty-rate`, `median-income`, `per-capita-income`}
@Q{Which columns in this dataset are about education levels?}
@A{`pct-college-or-higher`, `pct-hs-or-higher`}
}

@slidebreak

@lesson-instruction{
- With a partner, complete @printable-exercise{exploring-states.adoc}.
}

@slidebreak

@QandA{
@Q{What did you learn about defining rows in Pyret?}
@A{Example: `x = row-n(states-table, 0)` will make the name `x` have the value of the first row in the table (the index starts at zero!).}
@Q{How would you define a name `y` to be the value of the _second_ row in the table? The third?}
@A{`y = row-n(states-table, 1)` for the second row. Change the `1` to a `2` for the third.} 
@Q{Would a @vocab{model} built from two states with low `median-income` be likely to fit the rest of the data well? Why or Why not?}
@A{No! This is a particular subset of the data with shared characteristics (also called a @vocab{grouped sample}) and is unlikely to be representative of the pattern in the full dataset.}
}

@slidebreak

In math, @math{x = 4} will define a variable @math{x} to be the value @math{4}.

@indented{Any time we see @math{x} after it's been defined, we can substitute in the value of @math{4}.}

This works in Pyret, too. But in Pyret, values can be more than just numbers!

@indented{In this file, the variables `alabama` and `alaska` are defined as rows from the table.}

@teacher{Debrief the rest of the page with students.}

=== Investigate

@lesson-instruction{
- With your partner, make a prediction: Identify two pairs of @vocab{quantitative} columns from the list in the Definitions Area of @starter-file{alg2-states} that you think might have a relationship.
- Record your reasoning in questions 1 and 2 of @printable-exercise{looking-for-patterns.adoc}.
}

@strategy{Exploring the States Dataset}{

The @starter-file{alg2-states} has a lot of interesting data, and endless possible combinations of columns to explore. But randomly smashing columns together in a scatter plot is not the habit we want students to cultivate! Instead, make sure students are actually talking with their partners about why two columns may or may not be related.

Making sense: can students predict these relationships, and explain their thinking? +
(If so, probably not worth having them spend time on more than one of them!)

- `pop-2010` vs. `pop-2020`.
- `pop-2020` vs. `num-households`
- `num-housing-units` vs. `num-households`
- `num-households` vs. `num-veterans`

The District of Columbia: DC often shows up as an outlier or extreme value. But why?

The dataset is designed so that students will quickly begin searching for relationships between varying levels of education and income, and there are linear relationships in each of them. Here are a few relationships to spark students' interest.

- `pct-college-or-higher` vs. `pct-in-poverty`
- `median-income` vs. `pct-college-or-higher`
- `median-income` vs. `pct-home-owners`
- `pct-college-or-higher` vs. `pct-home-owners`
- `pct-home-owners` vs. `num-housing-units`
- `median-income` vs. `per-capita-income`

}

@slidebreak

@QandA{
@Q{What columns did you decide might have relationships? Why?}
@A{Ideally students will have identified at least one pair of columns that connect income and education.}
@A{We can only look for relationships between quantitative columns, so make sure students are not trying to work with categorical columns.}
}

@slidebreak

@lesson-instruction{
- Complete @printable-exercise{looking-for-patterns.adoc}
- As you work, keep an eye out for what you can learn about the states we decided to focus on.
}

@slidebreak

@QandA{
@Q{How did your predictions compare to the scatter plots you made in Pyret?}
@Q{Which columns appear to have the strongest relationships?}
@A{Answers will vary. Some contenders include:}
@A{positive relationship: `pct-college-or-higher` and `per-capita-income` }
@A{negative relationship: `pct-in-poverty` and `median-income`}
@A{strong, but not particularly interesting:
  *** `pop-2010` and `pop-2020`
  *** `per-capita-income` and `median-income`
  }
@Q{What did you learn about the states we decided to keep an eye out for?}
}

=== Synthesize

@QandA{
@Q{Why did we use scatter plots for our exploration of this dataset?}
@A{Because we were looking for relationships between columns}
@Q{Share your scatter plots with one another. _(Perhaps by copying and pasting scatter-plots into a shared document and then labeling them?)_}
@Q{Did you and your classmates use similar words to describe the scatter plots you came up with? If so, what were they?}
@Q{What are some of the things we practiced doing in Pyret?}
@A{Building a filtered table}
@A{Making a table to display the count of each category in a categorical column}
@A{Sorting a column}
@A{Defining a row}
@A{Making a scatter plot}
}

@teacher{_Note: Students will acquire the formal vocabulary that data scientists use to assess relationships in @lesson-link{linear2-building-models}, which is all about identifying form, direction, and strength._}

