[.canBeLongerThanAPage]
= Making an Infographic

@description{Students develop a ratio statement from a dataset of their choice, and then illustrate it via a compelling infographic.}

Make an infographic from one of the bar or pie charts you made in Pyret.

Be sure to:

- Make your representations to scale!
- Give your infographic a compelling title. The title could read like a newspaper headline that guides the viewer to pay attention to the information you most want them to notice or it could be a question that you want the viewer to think about while looking at your infographic.
- Credit your sources!
- Review the @link{rubric-infographic.html, Infographics Rubric} before you start.

== Brainstorming for your Project

- Choose one data display that intrigues you.
- Write three ratio statements of interest based on that display.
- Share your ratios with your partner and discuss which one is most compelling and appropriate for making an infographic.

== Strategy 1: Illustrate Ratios using Repeated Images

[.center]
--
@image{../images/teen-pregnancy-infographic.png, 348}, @image{../images/mass-shooting-infographic.png, 522}
--

*Remember: All percentages are ratios!*

[.indentedpara]
--
40% is equivalent to 40 out of 100.  If 40% of students wear baseball hats we can show 100 people, of which 40 are wearing hats. Or we could scale 40/100 down to 2/5 and show 5 people of which 2 are wearing hats.
--

*Avoid Stereotyping!*

[.indentedpara]
--
A tricky thing about making infographics with images of people is that not all images accurately represent the diversity of the communities described by the statistics. We encourage the use of silhouetted images in infographics.
--

== Strategy 2: Scale Images on a Grid, as if they were bars on a Bar Graph

[.center]
--
@image{../images/empire-state-infographic.png, 600}, @image{../images/dollar-infographic-mona-chalabi.png, 270}
--

== Strategy 3: Use an Area Model

[.center]
--
@image{../images/bratz-infographic.png, 620}, @image{../images/space-in-am-mona-chalabi.png, 250}
--




