= Defining Functions 3(Word Problems & Function Composition)

@lesson-description{Students apply their skills in using the Design Recipe and writing purpose statements to a variety of word problems and take a closer look at how functions can work together by investigating the relationship between revenue, cost, and profit}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Understand how to use the @vocab{Design Recipe} to break down simple word problems.
* Create a strong @vocab{purpose statement} that details in their own words what the @vocab{function} is doing.
* Explain the pros and cons of functions that depend on each other
* Write a function that explicitly uses another function

|Student-Facing Lesson Goals
|
* I can use the Design Recipe to break down word problem when writing a function.
* I can identify @vocab{domain} and @vocab{range} and other quantities in a word problem when writing a function.
* I can create and revise a strong purpose statement that explains what the function is doing.
* I can explain the pros and cons of functions that use other functions.
* I can write a function that uses another function.

|Key Points for the Facilitator
|

* The purpose statement, like the contract, is a comment - something that the computer doesn't read.  It's important for readability of their code - there may be other people looking at their code and using their functions!
* Remind students that the domain and range are @vocab{data types}(Number, String, Image).
* If students struggle with creating the examples, go back to the Circle of Evaluation mapping activity in Creating Functions 2
* There are several ways to write the profit function - use this opportunity for discussion and to promote higher-order critical thinking.
* If students are struggling with understanding the basis of the problem, start by coming up with examples of cost and revenue.  If Sally sells one glass, what is her total revenue?  How much does it cost her to produce that one glass?
* Ensure students understand the difference between "revenue" and "profit", and that "cost" refers to the cost of making the lemonade, not the amount Sally is charging.


|Prerequisites
|

* Students should be familiar with Circles of Evaluation.
* Students should be familiar with defining values.
* Students should be familiar wih the Design Recipe.

|Materials
|

* @link{https://docs.google.com/presentation/d/1N3aASr625cyW2SVNsdvCXWGz88XLc7hHNJmQn3GDgwA/view, Google Slides} for this lesson.
* Design Recipe worksheet (@worksheet-link{workbook-pages/DesignRecipe1.pdf, PDF}, @link{https://docs.google.com/document/d/1GQw-EJAw54BK04SMp_4jPtGGt4IojsUA7oXfz9TRm8Y/view, Google Doc})

* Purpose Statement - 3 Reads/Stronger & Clearer(@worksheet-link{workbook-pages/PurposeStatement3ReadsStrongerClearer.pdf, PDF}, @link{https://docs.google.com/document/d/16xiKkaB6GYUv95ug7-o3QubnmX7oZnm03J1AJTtH_2k/view, Google Doc})

* Word Problems - (@worksheet-link{workbook-pages/WordProblems.pdf, PDF}, @link{https://docs.google.com/document/d/1KpmYVJ9LdPyYeg839jEYotvMIbXx3urgIr8ZvRR3flw/view, Google Doc}) 

Bootstrap Formative Assessments


* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcaf7db4b8576069fdccd5, Bootstrap Algebra: Design Recipe} (Desmos Activity)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcaf49b4b8576069fdcc38, Bootstrap Algebra: Design Recipe Practice(Blank Template)} (Desmos Activity)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb07bb4b8576069fdcef1, Bootstrap: Algebra - More Design Recipe Practice} (Desmos Activity)
* @link{https://quizizz.com/admin/quiz/5cdcb223862fd8001a135579, Bootstrap: Algebra - Coordinates, Circles of Evaluation, & Code} (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb288f41b366950eba1e1, Bootstrap:Algebra - Data Types & Circles of Evaluation} (Desmos Activity)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb336f41b366950eba420, Bootstrap:Algebra - Circles of Evaluation Review(Blank Template)} (Desmos Activity)
* @link{https://quizizz.com/admin/quiz/5cdcb3907f8c98001a203c1b, Bootstrap:Algebra - Contracts, Domain/Range, Data Types, & Functions } (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb3f555e3fb606a1f1ba2, Bootstrap:Algebra - Data Types, Circles of Evaluation, and Contracts} (Desmos Activity)

Connecting Activities

* @link{https://teacher.desmos.com/expressions, Expression Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/modeling, Mathematical Modeling Bundle} (Desmos Activities)
* @link{https://quizizz.com/admin/quiz/576d1e5f91cb32ef5fc67529/variables-and-expressions, Variables and Expressions} (Quizizz)
* @link{https://teacher.desmos.com/functions, Functions Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/polygraph/custom/560ad28e9e65da5615091edb, Functions & Relations} (Desmos Polygraph Activity)
* @link{https://quizizz.com/admin/quiz/582b7390e8e0c0c201647d9d/functions, Functions} (Quizizz)
* @link{https://quizizz.com/admin/quiz/582f0e34b805cc5c6608d326/function-notation, Function Notation} (Quizizz)
* @link{https://teacher.desmos.com/linear, Linear Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/quadratic, Quadratics Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/quadratic, Exponential Bundle} (Desmos Activities)
* @link{https://quizizz.com/admin/quiz/5a0f3d001699791000871e2a/linear-equations, Linear Equations} (Quizizz)
* @link{https://quizizz.com/admin/quiz/5ad0d3f700e91d0019307fc3/quadratic-equations, Quadratic Equations} (Quizizz)
* @link{https://quizizz.com/admin/quiz/59024aa95af2ad1000a10719/linear-exponential-and-quadratic-functions, Linear, Quadratic, and Exponential Equations]} (Quizizz)
* https://www.geogebra.org/m/nqymeFc4[Function Composition Dynamic Illustrator I ] (Geogebra)
* https://www.geogebra.org/m/h3qdzW3W[Composition of Function] (Geogebra Quiz)
* https://quizizz.com/admin/quiz/58a61a2cf0b089151011ef50/composition-of-functions[Composite Functions] (Quizizz)

|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Addressing
|
* @std{8.F.B}

|Approaching
|
* @std{HSF.BF.A.1}

|Standards for Mathematical Practice
|
* @std{MP.1}
* @std{MP.7}

|Bootstrap Benchmarks
|
* @std{BS-DR.1}
* @std{BS-DR.2}
* @std{BS-DR.3}

|===


== Get Ready:

Students should have their workbook and contracts page, a pencil, and their computers with a @link{https://www.wescheme.org, WeScheme} tab that they're logged into.

== Practice: (20 min)
This lesson is all about getting more reps and more practice with the Design Recipe and writing Purpose Statements.

Use the @worksheet-link{workbook-pages/PurposeStatement3ReadsStrongerClearer.pdf, Purpose Statement(3 Reads/Stronger And Clearer)} and the @worksheet-link{workbook-pages/DesignRecipe1.pdf, Design Recipe} worksheets to work through several of the Word Problems from this @worksheet-link{workbook-pages/WordProblems.pdf, worksheet}.

[.strategy-box]
.Strategies for English Language Learners
****
MLR 6: 3 Reads 
In pairs, the word problem is read 3 times. Students will document their work in the "3 Reads/Stronger & Clearer" handout.

* 1st Read: Teacher reads the word problem. Without any pencil or pen, students discuss: What is the problem about? 
* 2nd Read: Partner A reads. Students discuss: What are the quantities?
* 3rd Read: Partner B reads. What is a good purpose statement?

MLR 1: Stronger and Clearer Each Time 
Using the "3 Reads/Stronger & Clearer" handout, students will switch partners 3 times.

* 1st new partner: Read their purpose statements to each other & revise the purpose statement to be stronger and clearer.
* 2nd new partner: Repeat.
* 3rd new partner: Repeat.
****


== Launch: (5 min)

"Lemonade" WODB - Have students select one that they want to discuss and group up.  Walk among the groups and encourage mathematical discussion of the image.

== Explore: (10 min)

Students complete "Sally's Lemonade" workbook page and brainstorm their ideas for functions.

[.strategy-box]
.Strategies for English Language Learners
****
MLR 7 - Compare and Connect
There are several correct ways to write the functions needed for Sally's Lemonade.  Have students compare methods and develop understanding and language related to mathematical representation and methods.  What are the advantages of the different solutions?  What are some drawbacks?
****

== Discuss: (10 min)

* *What functions could help Sally better manage her lemonade stand?*
+
_revenue, cost, profit_
* *What is the difference between _revenue_ and _profit_?*
+
_Revenue is the total amount of money that comes in, profit is the remaining money after cost has been subtracted._
* *How could Sally _increase_ her profits?*
+
_By decreasing her costs, raising her prices (which increases revenue), by selling more lemonade_
* *What is the _relationship_ between profit, cost, and revenue?*
+
_Profit = Revenue - Cost_

== Apply (15 min)

Students work with their partners to develop their
function models for
@worksheet-link{FunctionComposition3/workbook-pages/FunctionComposition3-WB1.adoc,
revenue},
@worksheet-link{FunctionComposition3/workbook-pages/FunctionComposition3-WB2.adoc,
cost}, and
@worksheet-link{FunctionComposition3/workbook-pages/FunctionComposition3-WB3.adoc,
profit}, using the Design Recipe.

While students are working, walk the room and gauge student understanding.  There is more than one correct way to write the profit function (see sample responses below).  Encourage discussion between students and push students to develop their thinking on the advantages and disadvantages of each correct solution.






