= Exploring Periodic Data

@description{Students investigate periodic relationships, first by deciphering the patterns in a dataset with perfect periodic (sinusoidal) behavior and then by looking at data about Carbon Dioxide, using an inquiry-based model involving hypothesizing, experimental and computational modeling, and sense-making. }

@lesson-prereqs{fitting-models}

@keywords{periodic, period, amplitude, frequency}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

- Read and interpret real-world data, presented in a scatter plot
- Recognize periodic behavior in tables and graphs
- Model periodic relationships using functions


| Student-facing Lesson Goals
|

- Let's use Pyret to model periodic relationships in data

| Materials
|[.materials-links]
@material-links

| Preparation
|
@preparation{
- Much of the exploration in this lesson hinges on a custom-built interactive Desmos activity. +
You will want to:
 * Open @starter-file{alg2-exploring-periodic-desmos}.
 * Make a link or code to share with your students.
 * Decide how you will share the link or code with students and, if you are using our Google Slides, add the appropriate link to the slide deck.
 * Set the pacing so that students are only able to interact with the first three slides. _(As the lesson progresses you will be directed to adjust the pacing or sync students to you so that they have access to relevant slides.)_
- _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions-alg2.adoc, _Here's what you need to do._}
}
|===

== Looking for Patterns
@objective{model-explore}

=== Overview
Students are introduced to the notion of @vocab{periodic relationships}: related variables where the response variable repeats the same pattern over and over as the explanatory variable increases.

=== Launch

@right{@image{images/state-fair.png, 200}}Your physics teacher comes back from a trip to the state fair, and keeps raving about some amazing ride they took. The class keeps asking them for details: was it a Roller coaster? Bumper cars? Merry-Go-Round?

Being a teacher, of course they decide to turn your casual curiosity into a _learning experience_, and share some data they recorded from their smart watch.

++++
<style>
table.rideData tr * { padding: 0 !important; margin: 2px !important; }
table.rideData { width: 70%; margin: auto; }
</style>
++++
[.rideData, cols="^1a,^1a", options="header"]
|===
| `time` (minutes)  | `altitude` (feet)
|  0				|   5.0
|  5				|  55.0
| 10				| 154.9
| 15				| 205.0
| 20				| 155.2
| 25				|  55.2
| 30				|   5.0
| 35				|  54.7
| 40				| 154.6
| 45				| 205.0
| 50				| 155.5
| 55				|  55.5
| 60				|   5.0
|===

=== Investigate
@lesson-instruction{
Working in pairs or groups, complete questions 1-4 on @printable-exercise{exploring-periodic.adoc}.
}

@QandA{
@Q{What are some of your Noticings, and what did they make you Wonder?}
@A{(Solicit a range of student responses)}
@Q{What kind of ride do you think they were on?}
@A{Answers will vary. Write them all down on the board!}
@Q{What about this data supports your theory?}
}

@lesson-instruction{
Complete the remaining questions on @printable-exercise{exploring-periodic.adoc}.
}

=== Synthesize
This worksheet had you create a *new type of data visualization*, called a @vocab{line graph}.

@lesson-point{Line graphs are often used instead of scatter plots when the explanatory variable is _time_. Time changes continuously, so it makes sense to connect the dots!}

[cols="^1a, ^1a"]
|===
| @image{images/rides-scatter-plot.png} | @image{images/rides-combined-plot.png}
|===

@slidebreak

In this example, we know the Ferris wheel keeps turning, generating data "in between" the times represented in our scatter plot. Connecting those dots with the line gives us an *approximation* of what data is missing between those times, and helps us see the shape of the relationship.

@ifslide{
@right{@image{images/rides-combined-plot.png}}
}

@QandA{
@Q{Was it helpful to connect the dots to form a line graph?}
@A{Yes - it was difficult to see the pattern until we added the line!}
@A{We don't know for sure what the data looks like between those points, and we certainly don't know if it's linear!}
@Q{Do `time` and `altitude` appear to be related?}
@A{(Solicit a range of student responses, guiding the class to there being a relationship)}
@Q{What kind of ride do you think this teacher was on, and why?}
@A{A Ferris wheel, because the ride keeps going up and down over and over, and it takes the same amount of time to go up as it does to go down.}
@Q{But what kind of relationship is it? Is it Linear? Quadratic? Something else?}
@A{(Let students discuss)}
@Q{Why might using straight lines to connect these dots be a problem?}
}

== Thinking in Circles

=== Overview
Students begin to reason about points on the circumference of a circle, with their x- and y-coordinates varying as a function of _rotation_.

=== Launch

@right{@image{images/ferris-wheel.png, 150}}Your teacher's seat on the Ferris Wheel can be thought of as a point on the circumference of a rotating circle.

- The y-value (`altitude`) goes from 5ft to 205ft then back down to 5, then up again, then down again...
- This pattern of y-values repeats at regular intervals (every 30m)

How do we figure out how far off the ground (y-coordinate) the seat is after some length of time?

@slidebreak

Let's consider the models we've studied:

- linear, exponential and logarithmic models either keep increasing forever or keep decreasing forever.
- quadratic relationships grow one way until they reach a maxima or minima _once_, before growing in the other direction.

*None of the tools in our modeling toolkit work for functions that keep repeating, going up and down over time!*

@slidebreak

This is a problem, because modeling cyclical relationships is _incredibly important_, for everyone from farmers to fishermen to healthcare providers! So many things in nature come in cycles:

- The sun rises and sets every day: @math{\text{sun-height}(\text{time})} is periodic
- The moon waxes and wanes: @math{\text{moon}(\text{date})} is periodic
- the tides come in and out each day: @math{\text{tide}(\text{time})} is periodic
- Tulips tend to bloom in the Spring: @math{\text{tulips}(\text{date})} is periodic
- People tend to get sick in the winter: @math{\text{flu-cases}(\text{date})} is periodic

In this lesson we'll explore a new class of functions - _@vocab{periodic functions}_ - that we can use to model cyclical relationships like these.

@strategy{A note on Vocabulary}{

You've probably heard of related terms _sinusoidal functions_ or _trigonometric functions_. We've chosen @vocab{periodic functions} because the term shows up often in both K-12 math _and_ science and engineering classes, in an attempt to balance the two. Note that "periodic" is also a broader term, as there are periodic functions that are _not_ sinusoidal/trigonometric. Science teachers may be quick to point out that periodic functions can be used to model relationships that _cycle_ (smooth ups-and-downs) and those that oscillate (any kind of up-and-down!).

@center{@image{images/non-sinusoidal-graphs.png}}

As always, we advise you to use the term that works best for your classroom context!
}

@slidebreak

==== Unit Clocks

@right{@image{images/unit-circle-clock.png}}Let's think about a simpler case, of a clock with a radius 1 that is centered around the origin. +
 +
We can draw a radius at any "time", on the clock hitting the circumference at some point (A, B).

_For example, when it's 12 o'clock, the radius lands at @math{(A = 0, B = 1)}._

That radius also forms the @vocab{hypotenuse} of a right triangle with sides @math{x} and @math{y}, shown here in green and blue.

@lesson-instruction{
- With a partner, complete questions 1-6 of @printable-exercise{unit-clock.adoc}.
}

@slidebreak

@ifslide{@right{@image{images/unit-circle-clock.png}}}

@QandA{
@math{A} and @math{B} both vary as a function of @math{time}, giving us functions @math{A(time)} and @math{B(time)}.
@Q{At what time does the radius land on the point (0,-1)?}
@A{6pm?}
@Q{When does @math{B(time)=0}, where the radius sits along the x-axis?}
@A{3pm lands on (1,0)}
@A{9pm lands on (-1,0)}
@Q{At which time(s) does @math{A(time)=B(time)}, where the legs @math{x} and @math{y} are equal?}
@A{1:30 and 7:30}
@Q{When @math{A(time) = B(time)}, how could we calculate the length of @math{x} and @math{y} from this right triangle?}
@A{We could use the Pythagorean Theorem: @hspace{1em} @math{x^2 + x^2 = 1^2}}
}

@teacher{
Make sure you have created a link or code for your class to @starter-file{alg2-exploring-periodic-desmos} and paced the class so they only have access to Slide 1: Unit Clocks. Students will be using this slide to check their work on @printable-exercise{unit-clock.adoc}
}

@lesson-instruction{
- With a partner, finish @printable-exercise{unit-clock.adoc}.
- The end of the page will direct you to use the the link I shared to the Desmos File *Exploring Periodic Functions*.}

@slidebreak

@right{@image{images/pizza-slice2.png, 100}}As the point (A, B) travels around the circumference of a circle, it reflects a changing angle @math{θ}. It can be helpful to think of this as a pizza slice, with @math{θ} as the angle at the tip of the slice, and the edge of the crust as the amount of the circumference the point has traveled.

@QandA{
In our clock example, we divide the circle into twelve "slices", each representing one hour. How many slices would represent 15 minutes? An hour and a half? slice?

Of course, there are other ways besides 12 slices of "hours" to measure this angle!
@Q{Can you think of another measure that divides a circle up differently?}
@A{_Minutes_, which divide our circle up into 720 slices instead of 12. We could imagine one-and-a-half of these slices representing 90 seconds, or 2 slices for 120 seconds.
** _Degrees_, divide a circle up into 360 slices instead of 12. How many minutes are represented by 1 degree? 2.5 degrees?
** _Compass Directions_ like North, South, East, and West, which divide our circle up into 4 slices instead of 12. How many slices represent the angle between North and South? West and Southwest?
}
@Q{On our graph, would the shape of the curve change if we labeled the x-axis with 360 degrees instead of 12 hours?}
@A{No -- all the intervals remain constant, so the only change is the *labels* on the x-axis.}
}

@slidebreak

==== Radians

@ifslide{@right{@image{images/pizza-slice2.png, 200}}}Degrees aren't always the best way to divide up a circle.  We often want to use the *radius* of the circle in our calculations, just as we used the radius of the Ferris wheel to talk about altitude. In these cases, it would be nice to have a measurement of circumference that's _expressed in terms of radius_, to make the math cleaner...

@slidebreak

@right{@image{images/pizza-6-equilateral.png, 200}}What if we wanted a pizza slice where the length of the crust is exactly the same as the length of the radius? How many slices would there be in the pie?

- We can start by imagining each slice as an equilateral triangle, where all three sides are exactly one radius.
- This would give us exactly six slices, with the tip of each slice having a 60° angle...
@QandA{
@Q{If each of our six slices were an equilateral triangle, our pizza wouldn't be round anymore.}
@Q{What shape would we get instead?}
@A{A hexagon!}
}

@slidebreak

@ifslide{@right{@image{images/pizza-6.png, 200}}}In order to bend the outer edge of the triangle into a curve that lands on the edge of the circle, while keeping the length of the curve equal to the radius, we'd have to make the angle _just slightly less than 60°_.

@lesson-point{Radian: the measure of the angle formed by carving out a radius's worth of the circumference}

If @math{θ} of each "radian" slice is less than 60°, we can fit just slightly more than 6 of these slices in our pie. In fact, we can fit *exactly @math{2pi}* of these "radius slices"!

@lesson-point{@math{360° = 2pi}}


@slidebreak

@QandA{
@Q{If there are @math{2pi} radians in the whole circle, how many radians are in the _semi-circle_ between 3pm and 9pm on our clock?}
@A{@math{1\pi}}
@Q{How many radians are there in the _quarter-circle_ between 12pm and 3pm?}
@A{@math{\pi \over 2}}
@Q{How many radians are there in a single "hour" of the clock?}
@A{@math{\pi \over 6}}
}

@slidebreak

Pyret knows about @math{\pi}, too!

@lesson-instruction{
- Open @starter-file{editor}
- In the Interactions Area, try evaluating `PI` (all caps!). What do you get back?
- Try computing the value of @math{3\pi}.
- Try computing the value of @math{\pi / 2}.
- Why do we need spaces around the multiplication and division signs?
}

@teacher{Be prepared to remind students to read the error messages when they type `3PI` instead of `3 * PI`  and `PI/2` instead of `PI / 2`}

@slidebreak

As with degrees, switching our unit-clock graph from hours to radians doesn't change the curve of our graph at all. It just changes the tick marks on the x-axis.

*Note:* The conventions for labeling a clock are different from the conventions for labeling circles with Radians or Degrees.
[cols="^5a,^1a,^5a", options="header", grid="none", stripes="none"]
|===

| hours on a clock
| vs
| radians and degrees on a circle

| start from the top +
 (where 12 o'clock is)
|
| start from zero on the right +
(where 3 o'clock would be)

| increase clockwise
|
| increase counter-clockwise
|===

@slidebreak

@ifslide{
[cols="^5a,^1a,^5a", options="header", grid="none", stripes="none"]
|===

| hours on a clock
| vs
| radians and degrees on a circle

| start from the top +
 (where 12 o'clock is)
|
| start from zero on the right +
(where 3 o'clock would be)

| increase clockwise
|
| increase counter-clockwise
|===
}

_These are conventions that people have agreed upon over time to make it easy to collaborate. If somebody wanted to make a clock with the numbers written backwards and have the hands move the other way, it would be possible to learn how to tell time using their clock... but it likely would be more confusing than helpful for most people if we hung a clock like that in our school._

@slidebreak

@lesson-instruction{
Complete the table on @printable-exercise{converting-angles.adoc} with your partner, following the prompts in #1 and #2.
}

=== Synthesize

TBD

