= Data Displays in CODAP

Make sure you’re logged into CODAP, with the Animals Dataset open. Create a graph of randomly generated points by selecting the `Graph` icon, and then respond to the following prompts.

== Creating Bar Charts in CODAP

@n Select the y-axis on your graph (where it says "Click here"). On the drop-down menu that apperas, select `fixed`. (_If you prefer, you may also drag the attribute name from the table to the y-axis_) What do you notice?
 @span{.blankline}{@ifsoln{_A dot plot forms, categorizing animals as fixed (true) and not fixed (false). The labels for the dot plot are on the y-axis. The dots are stacked horizontally._}}

@n Now select the x-axis on your graph and select `fixed`. How does the graph change?
 @span{.blankline}{@ifsoln{_The labels move from the y-axis to the x-axis, and the dots are stacked vertically._}}

@n Select the `configuration` icon (which looks like a bar graph) to the right of the data display. Select `fuse dots into bars`

@n Click the `ruler` icon; test out each of the two options available (count and percentage). What happens?
 @span{.blankline}{@ifsoln{_When I select "count," I see the number of animals represented by each bar. When I select "percentage," the percentage of animals represented by each bar appears._}}

@n Now, make a bar chart showing how many animals there are of each species by changing the variable on the x-axis to `species`. Can you figure out how to reconfigure the bar chart as a dot plot?
@span{.blankline}{@ifsoln{_To reconfigure as a dot plot, select the `configuration` icon and deselect `fuse dots into bars`._}}

== Numerical versus Categorical Displays

@n Create a graph with `weight` on the x-axis. Then, click on `weight` so that a drop-down menu appears. From this drop-down menu, choose `Treat as Categorical`, and observe how the graph changes. What is going on?
@span{.blankline}{@ifsoln{_CODAP is no longer interpreting weight as numerical data. Rather, creating many categories; each weight category contains just 1 or 2 animals._}}

@n Can you `fuse dots into bars` when treating `weight` categorically? Numerically? Why does CODAP _sometimes_ invite you to `fuse dots into bars` - but other times the option does not appear?
@span{.blankline}{@ifsoln{_Bar charts show categories, therefore are conducive to representing categorical data. They classify, rathern than measure_}}

