= Exploring Displays

++++
<style>
#content .fitb{ margin-top: 1ex !important; width: 26em; min-width: 1.5em; }
#content tbody tr:first-child { height: 2.5in; }
#content img { max-height: 2in !important; display: block;}
</style>
++++

Using the @link{https://codap.concord.org/app/static/dg/en/cert/index.html#shared=https%3A%2F%2Fcfm-shared.concord.org%2FeZEwgF1qSm396MC6CNM9%2Ffile.json, Animals Dataset} in CODAP, make each type of display below. Then sketch the displays and answer the questions.

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Bar Charts
| Box Plots

| @ifsoln{@image{bar-chart.png, bar chart}} Sketch a bar chart here.
| @ifsoln{@image{box-plot.png, box plot}} Sketch a box plot here.

|
--
@left{
Displays @fitb{1em}{@ifsoln{1}} column(s)
of @fitb{9em}{@ifsoln{categorical}} data. +
What does this display tell us?
@fitb{}{@ifsoln{The proportion in which values in a categorical}}
@fitb{}{@ifsoln{column are represented - including categories}}
@fitb{}{@ifsoln{that are NOT represented}}
@fitb{}{}
}
--

|--
@left{
Displays @fitb{1em}{@ifsoln{1}} column(s)
of @fitb{9em}{@ifsoln{quantitative}} data. +
What do you think this display tells us?
@fitb{}{@ifsoln{The range of quantitative values in the bottom quarter,}}
@fitb{}{@ifsoln{top quarter, and the middle quarters. This tells}}
@fitb{}{@ifsoln{us something about the spread of the data}}
@fitb{}{}
}
--
|===

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Histogram
| Scatterplot

| @ifsoln{@image{histogram.png, histogram}} Sketch a histogram here
| @ifsoln{@image{scatter-plot.png, scatter plot}} Sketch a scatterplot here

|
--
@left{
Displays @fitb{1em}{@ifsoln{1}} column(s)
of @fitb{9em}{@ifsoln{quantitative}} data. +
What do you think this display tells us?
@fitb{}{@ifsoln{How many values in a quantitative column fall into}}
@fitb{}{@ifsoln{equally-sized bins. This tells us something about}}
@fitb{}{@ifsoln{the spread of the data.}}
@fitb{}{}
}
--

|
--
@left{
Displays @fitb{1em}{@ifsoln{2}} column(s) of
@fitb{9em}{@ifsoln{quantitative}} data. +
What do you think this display tells us?
@fitb{}{@ifsoln{something about the relationship between two}}
@fitb{}{@ifsoln{quantitative columns, graphing all pairs of}}
@fitb{}{@ifsoln{values as points on a plane. This allows us}}
@fitb{}{@ifsoln{to look for patterns, clusters, trends, etc.}}
}
--
|===
