= Absolute Value and Opposites (2)

@description{Students examine expressions and Circles of Evaluation that use _both_ opposite and absolute value.}

@lesson-prereqs{absolute-value-and-opposites}

@keywords{Opposite, Absolute Value}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Students translate expressions with absolute value and opposite, using Circles of Evaluation, words and symbols.
* Students examine equivalence in pairs of Circles of Evaluation with absolute value and equivalence.
* Students compute the result of expressions with absolute value and opposite.

| Student-facing Lesson Goals
|

* Let's translate expressions with absolute value and opposite.
* Let's evaluate expressions with absolute value and opposite.


| Materials
|[.materials-links]
@material-links

| Preparation
|
This activity involves a card sort. The easiest way to prepare for this is to give each pair of students an envelope containing the three sets of cards. Keep each set together with rubber bands or paperclips.

|===


== Translating Absolute Value & Opposite @duration{25 minutes}

=== Overview
Students match Circles of Evaluation to expressions in words with @vocab{absolute value} and @vocab{opposite}, and then they consider how arithmetic expressions correspond to those two representations.

=== Launch

Explain to students that they are going to receive @opt-printable-exercise{pages/translating-card-sort.adoc, three sets of cards}.

The first set of cards includes Circles of Evaluation that use the `negate` and `abs` functions.

The second set of cards translates those Circles of Evaluation into Verbal Expressions.

[.lesson-instruction]
- With your partner, match each Circle of Evaluation card with the corresponding Verbal Expressions card.
- Lay them out on the table in front of you so you can clearly see both the Circle of Evaluation and the Words.
- Some Circles of Evaluation have more than one translation into words.
- Discuss each match that you make.

Circulate as students sort their cards, ensuring that they are carefully examine each card in order to see the connection between the Circle of Evaluation and its translation into words. Students will need to consider if translating the Circle of Evaluation into words involves reading from the outside-in or the inside-out.

[.lesson-instruction]
- Now, you’re going to receive a third set of cards - Arithmetic Expressions.
- One at a time, take turns studying each of these cards. After examining it closely, place it with the appropriate Circle of Evaluation / Verbal Expression pairing.
- Explain to your partner how and why you placed each card.
- You and your partner must agree on each card’s placement before advancing to the next.

Again, circulate during the activity. As students match Verbal Expressions to their Arithmetic Expressions and Circles of Evaluation, invite them to use the Circle of Evaluation as a tool to help them see the structure of the math.

=== Investigate

[.lesson-instruction]
- Each row on @printable-exercise{pages/translating-abs-val-opp.adoc} represents a single @vocab{arithmetic expression}, written in three different forms. Sometimes, you will be provided with a Circle to translate, other times you will start with a verbal or arithmetic expression.
-  Fill in the empty spaces so that all three forms represent the same expression.

=== Synthesize

Here are some key take-aways from this lesson:

- We can find the @vocab{opposite} of an @vocab{absolute value}: @math{- | x |}
- We can find the @vocab{absolute value} of an @vocab{opposite}: @math{ |- x |}
- Thinking about the structure of the expression can help us understand if it is positive or negative.

And here are some questions to consider:

- We did lots of different translations between Circles of Evaluation, verbal expressions, and arithmetic expressions. Was there any type of translation that was more challenging for you?
- Was there any particular representation (Circle, verbal expression, or arithmetic expression) that you found yourself returning to often? Why?

== Evaluating with Absolute Value & Opposite @duration{25 minutes}

=== Overview

Students tackle evaluating expressions that include both `abs` _and_ `negate`.

=== Launch

Circles can be extremely useful in helping students to navigate problems with `abs` and `negate`, which can be quite complicated, otherwise; after all, "negative" and "absolute value" are not typically delegated in the order of operations.

[.lesson-instruction]
--
- Consider this @vocab{equation}: @math{-|4| = |-4|}
- Is it *true* or *false*?
- Jenny says that the equation is _true_ because @vocab{absolute value} makes everything positive, so both sides of the equation evaluate to 4. Is she correct?
** _Jenny is not correct - although students commonly assume that the presence of absolute value indicates a positive outcome._
--

Representing the equation with Circles of Evaluation highlights the structure of these expressions and it becomes clearer that they are not @vocab{equivalent}.

[.embedded, cols=">.^3,^.^1,<.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(negate (abs 4)))} | @math{+≠+} | @show{(coe '(abs (negate 4)))}
|===

[.lesson-instruction]
- Turn to @printable-exercise{pages/true-or-false.adoc} to examine additional pairs of Circles of Evaluation that use both `negate` and `abs`.
- Are the expressions on either side of the equal sign @vocab{equivalent}?
- Evaluate each side of the equation to confirm your response.
- The first one is done for you.

=== Investigate

Students who  can toggle between verbal expressions, Circles of Evaluation, and the standard mathematical notation will feel more confident both completing and discussing the subsequent activities.

[.lesson-instruction]
- Examine the Circles of Evaluation to determine @printable-exercise{pages/wodb-abs-val-negate.adoc}. The page starts with numeric values and then integrates @vocab{variables}. Place a check mark by each Circle of Evaluation that meets the condition stated on the left.
- Next, try @printable-exercise{pages/matching-circles-to-expressions.adoc}, where you will match expressions with their corresponding Circles of Evaluation. Note: some expressions can be matched to more than one correct Circle of Evaluation!
- At the bottom of the page, respond to the open response questions, thinking carefully about each Circle of Evaluation that you encountered.


=== Synthesize

- How do you decide the order in which to apply absolute value and opposite when an expression includes both?

- Did you work from the inside-out or the outside-in when evaluating Circles of Evaluation with absolute value and opposite? Did your strategy change, depending on the Circle of Evaluation? Explain.
