= Zample Page

== test 

=== Synthesize
Confirm that students have correctly matched the displays 

- What did you Notice? What did you Wonder? +

@teacher{_Answers will vary, but here are some important points:_
** _One of the pie charts has more categories for race than the other and the bar charts have more categories for race than we see om either of the pie charts._ 
** _In a pie chart, when there isn't any data in a category it goes unrepresented, but in a bar chart its absence is made visible._
** _The scale is different for each bar chart, whereas for pie charts the percentages will always add to 100%._
}

- How is `pie-chart` similar to `bar-chart`? How is it different?
- When would you want to use one chart instead of another?
- What strategies did you use to match the bar charts to the pie charts?
- Which displays do you find it easier to interpret? Why?
- What information is provided in bar charts that is hidden in pie charts?
** _In a bar chart, every category is visible and those with no values are missing a bar. Categories containing 0% of the data aren't represented on a pie chart._
- Why might this sometimes be problematic?
** _Sample Answer: If a service isn't reaching a sector of the population, it's easier to ignore the issue if that population doesn't get represented in the display._


