= Alice's Restaurant - Explore

++++
<style>
#content :not(.openblock.acknowledgment) p { line-height: 23pt; }
</style>
++++

Alice's code has some new elements we haven't seen before, so let's experiment a bit to figure out how it works!  *Open the “Alice's Restaurant starter file, click “Run”, and try using the `cost` function in the Interactions window.*

@vspace{2ex}

1) What does @show{(sexp->code `(cost "hamburger"))} evaluate to? @fitb{30ex}{}

@vspace{1ex}

2) What does @show{(sexp->code `(cost "pie"))} evaluate to? @fitb{30ex}{}

@vspace{1ex}

3) What if you ask for @show{(sexp->code `(cost "fries"))}? @fitb{30ex}{}

@vspace{1ex}

4) Explain what the function is doing in your own words.
@span{.blankline}{}
@span{.blankline}{}
@span{.blankline}{}

@vspace{1ex}

5) What is the function's name? @fitb{22ex}{} Domain? @fitb{22ex}{} Range? @fitb{22ex}{}

@vspace{1ex}

6) What is the name of its variable? @fitb{30ex}{}

@vspace{1ex}

7) Alice says onion rings have gone up to $3.75. Change the `cost` function to reflect this.

@vspace{1ex}

8) Try adding menu items of your own. What's your favorite?

@vspace{1ex}

9) For an unknown food item, the function produces the String `"That's not on the menu!"`

@vspace{1ex}

Is this a problem? Why or why not?

@span{.blankline}{}
@span{.blankline}{}

@vspace{1ex}

10) Suppose Alice wants to calculate the price of a hamburger, _including a 5% sales tax_. Draw a Circle of Evaluation for the expression below.