= Exploring Baseball Batting Data
++++
<style>
.lesson-instruction table .autonum { font-weight: bold; }
</style>
++++
@description{Students investigate quadratic relationships in Major League Baseball data from Miguel Cabrera's hits between 2020 and 2023.}

@lesson-prereqs{fitting-models}

@keywords{quadratic, square}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|

- Let's use Pyret to build scatter plots and look for relationships between columns.

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

|===

== Exploring the Data
@objective{model-explore}

=== Overview
Students explore the @starter-file{alg2-miguel-cabrera}, and create scatter plots to search for relationships between columns. They share and discuss their findings with the class, discovering the limitations of linear models.

=== Launch
@slidebreak{LaunchR}

@teacher{These questions are intended to spark student interest in the dataset they are about to explore.}

@QandA{
@right{@image{images/miguel-cabrera.jpg, 200}}Among Detroit Tigers fans, Miguel Carbera is considered one of the greatest hitters in franchise history. He won the Hank Aaron award in 2012, and was the American League MVP in 2012 and 2013.
@Q{What factors might influence how many home runs a player hits in a season?}
@A{Possible responses:}
@A{How fast the batter runs.}
@A{How strong the batter is.}
@A{The speed and angle at which the batter swings the bat.}
@A{How calm and focused the player is when they are at bat, perhaps influenced by personality, sleep, diet, stretching, meditation, etc.}
@A{How many hits make it into the bleachers, so they are inaccessible to the outfielders.}
@A{How fans and teammates support the batter.}
@A{How big the fields are where the practice and play -- in some stadiums (like Boston's Fenway Park) a hit of 302 feet will make it past the outfield. Some stadiums have distances exceeding 400 feet to center field.}
}

@slidebreak{Launch-DN}

In this lesson, we'll explore possible relationships between pitch (type and speed) and hit (angle, distance, speed and ball type) in a dataset of Miguel Cabrera's hits between 2020 and 2023.

@lesson-instruction{
- Open the @starter-file{alg2-miguel-cabrera}.
- From the File menu, select "Save a Copy", and click "Run".
- Working in pairs or small groups, complete @printable-exercise{exploring-cabrera-data.adoc}.
}

@slidebreak{LaunchR}

@QandA{
@Q{Which quantitative columns appear to have the strongest relationship?}
@A{hit-angle and hit-distance}
@Q{Would you describe the relationship as linear? Why?}
@A{No. Because it's u-shaped, rather than a straight line.}
}

@teacher{
The resulting scatter plots for `distance v. pitch-speed`, `hit-speed v. pitch-speed`, `hit-angle v. hit-distance` and `hit-angle v. hit-speed` are...
[cols="1,1,1,1"]
|===
| @image{images/cabrera-pitchspeed-distance.png, 200}
| @image{images/cabrera-pitchspeed-speed.png, 200}
| @image{images/cabrera-angle-distance.png, 200}
| @image{images/cabrera-angle-speed.png, 200}
|===
}

@slidebreak{Launch}

@QandA{
@Q{What is happening on lines 23-32 of the Definitions Area?}
@A{Four filtered tables are being defined, focused on subsets of the data for specific hit types}
@Q{How would we make a scatter plot comparing `hit-angle` and `hit-distance` for just the curve balls?}
@A{Exactly like the scatter plots we just made, except we'd use `curve-table` instead of `judge-table`}
@A{`scatter-plot(curve-table, "id", "hit-angle", "hist-distance")`}
@Q{Take a moment to make scatter plots comparing `hit-angle` and `hit-distance` for each of the filtered tables defined in the starter file. How do they compare?
}
@A{They all more or less make an upside down U shape, but they look slightly different and have a different numbers of points.}
}

=== Investigate
@slidebreak{InvestigateC}

Let's focus on just the sliders for now.  There definitely appears to be a relationship here...
@center{@image{images/cabrera-sliders-angle-distance.png, 400}}

@slidebreak{Investigate}

@lesson-instruction{
- Turn to @printable-exercise{cabrera-slider-data.adoc}.
- Complete the first section to find the optimal linear model and see how well it predicts hit distances from bat angles.
}

@QandA{
@Q{Is the best-possible linear model a good fit? Why or why not?}
@A{No. The model does not follow the shape of the data!}
@Q{Use the @math{S}-value to describe the fit of the model.}
@A{The @math{S}-value predicts an error of almost 77 feet, for hit distances with a range of about 350 feet.}
}

@pd-slide{
*Encouraging Students to Trust Their Eyes*

So much of math is about numbers, and we rarely leave time to link back to common sense. When linear regression fails to find a good fit, does that mean there's no relationship at all? This activity forces students to speak up and trust their eyes!
}

@slidebreak{Investigate}

Linear models don't seem to fit very well! No matter which direction we draw the line, many of the points are far away -- and they will make poor predictions for a large subset of x-values.

[cols="^.^1a,^.^1a,^.^1a", frame="none", stripes="none"]
|===
| When we build a linear model to fit the increasing half of the data, it doesn't fit the decreasing half...
| When we build a linear model to fit the decreasing half of the data, it doesn't fit the decreasing half...
| And trying to split the difference, is even worse...

| @image{images/curve-angle-distance-linear1.png}
| @image{images/curve-angle-distance-linear2.png}
| @image{images/curve-angle-distance-linear3.png}
|===

@slidebreak{Investigate}

@lesson-instruction{
- Turn to the *Fitting Curves* section of @printable-exercise{cabrera-slider-data.adoc}.
- Drawing and describe the pattern you actually see. Then use it to make some predictions.
- Discuss your thinking with your partner.
}

@slidebreak{Investigate}
@QandA{
@Q{How would you describe the pattern you see here?}
@A{Miguel Cabrera's hit distance generally increases as his bat angle increases from 0 to 30 degrees. As the angle increases after that, his hit distance generally _decreases!_}
}

@teacher{Review student answers to confirm that students see a _nonlinear_ relationship in the dataset that is fairly strong. Students should generally agree that the relationship is better fit by a curve, with hit distance peaking at a bat angle of _roughly_ 30 degrees.  *Make sure students have agreed on this vertex*, as its location is important for the next activity!

Have students share their "curves of best fit", encouraging them to identify where they "peak" and where they cross the x-axis. These locations will be important anchor concepts on which to build in the next section. (One option for facilitating sharing is to project the scatter plot on a whiteboard and have students come up and draw all of their curves on it).
}

=== Synthesize
@slidebreak{Synthesize}

- Why don't linear models work to model the relationship between bat angle and hit distance?
- What kinds of curves did you draw that fit better?

== Quadratic Relationships
@objective{quadratic-situations}

=== Overview
Students are introduced to quadratic functions. They become familiar with scenarios involving quadratics learn how to identify quadratic sequences.

=== Launch
@slidebreak{Launch}
Linear models work well for fitting simple relationships, but many relationships in the real world are far more complex! +
_Straight-line, linear models are often too primitive_.

The relationship we observe between bat angle and hit distance appears to best be described by a _curve_, where hit distance increases up to a certain bat angle, and then decreases again. This is definitely not linear! There are many kinds of non-linear relationships. The first one we'll learn about is called a @vocab{quadratic relationship}.

@slidebreak{Launch}

Graphs of @vocab{quadratic relationships} are often described as "u-shaped" or "looking like an arch". More formally, mathematicians and data scientists call these kinds of curves @vocab{parabolas}. There are lots of relationships that change direction like this!

@slidebreak{Launch}

[cols="1a,1a", options="header", stripes="none"]
|===
^| Some quadratic curves Peak
^| Other quadratic curves Bottom Out

| A ball thrown in the air will rise quickly, slow down, peak, and then begin to fall.
| The length of a shadow is long in the morning, shortens as the sun rises, and lengthens as the sun sets.

^.^| @image{images/parabola-ball-throw.png, }
^.^| @image{images/shadow-length-curve.png, 200} +
@image{images/boy-shadow.png, 200}

|===


=== Investigate
@slidebreak{Investigate}

@lesson-instruction{
Turn to @printable-exercise{classifying-descriptions.adoc} and practice identifying which scenarios are likely best modeled by linear relationships and which are likely best modeled by quadratic relationships.
}

@slidebreak{Investigate}

@QandA{
@Q{What characteristics did you look for to identify whether a scenario was likely best-modeled by a linear or quadratic relationship?}
@A{When there's either a steady increase or a steady decrease, a linear model will likely fit.}
@A{When there's a high point or a low point at which the change changes direction, a quadratic model will likely be a good fit.}
}


=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{Brainstorm some other real-world relationships that could likely be modeled by a quadratic function.}
@A{Answers will vary.}
@A{Many nutrients are good for you, and the more you take the healthier you are...up to a point. After that, too much of a mineral or vitamin can cause problems. A graph of @math{\text{health}(\text{dose})} will be quadratic.}
@A{When an athlete is young, they improve as they get stronger and more skilled. But as they age, they begin to lose their speed and strength.A graph of @math{\text{height}(\text{time})} will be quadratic.}
@A{The temperature of a puddle will warm and then cool over the course of the day. A graph of @math{\text{temp}(\text{time})} will be quadratic.}
@A{A ball dropped from a tall building will get faster and faster as it falls, so a graph of @math{\text{distance}(\text{time})} will be quadratic.}
}


== Additional Exercises

- For Yankees fans, @opt-printable-exercise{exploring-judge-data.adoc} and @opt-printable-exercise{judge-curve-data.adoc} engage students in exploring the @opt-starter-file{alg2-aaron-judge}.
  * Thinking for this page parallels @printable-exercise{exploring-cabrera-data.adoc} and @printable-exercise{cabrera-slider-data.adoc}.

@vspace{1ex}

- The @opt-printable-exercise{exploring-mpg.adoc} engages students in exploring the @opt-starter-file{alg2-fuel-efficiency}. 
  * Thinking for this page parallels @printable-exercise{cabrera-slider-data.adoc}
  * For students who aren't baseball fans, a chance to practice what they've learned in another context may be welcome. 

@vspace{1ex}

@teacher{
*NOTE*: While the fuel efficiency dataset used in the optional materials we'll be offering throughout our quadratics lessons is based on real data obtained from the @link{https://tedb.ornl.gov/, Transportation Energy Book}, *it has been augmented with fictional data* in order to provide a sufficiently-rich dataset for student modeling. You can find out more about this augmentation in the README tab of @link{https://docs.google.com/spreadsheets/d/1SLm1hDkVgAYxgh12dTD2Z3GXCUO9PrbwIZdqu9FiCGI/edit?gid=0#gid=0, the dataset}.
}



