= Exploring Batting Data from Baseball Player Aaron Judge
++++
<style>
.lesson-instruction table .autonum { font-weight: bold; }
</style>
++++
@description{Students investigate quadratic relationships in Major League Baseball data from Aaron Judge's hits in 2016 and 2017.}

@lesson-prereqs{fitting-models}

@keywords{quadratic, square, coefficient}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

- Read and interpret real-world data, presented in a scatter plot
- Model quadratic relationships using functions

| Student-facing Lesson Goals
|

- Let's use Pyret to model quadratic relationships in data.


| Materials
|[.materials-links]

| Preparation
|
@preparation{
- Much of the exploration in this lesson hinges on a custom-built interactive Desmos activity. +
You will want to:
 * Open @starter-file{alg2-exploring-quadratics-desmos}.
 * Make a link or code to share with your students.
 * Decide how you will share the link or code with students and, if you are using our Google Slides, add the appropriate link to the slide deck.
- _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}
}

| Key Points For The Facilitator
|
- Unlike linear functions, which are governed by slope and y-intercept, quadratic functions are governed by the behavior of _three_ factors.
- Students should gain an intuition for these factors by playing with them first in Desmos, then use them to fit a model in Pyret.
|===

== Exploring the Data
@objective{model-explore}

=== Overview
Students explore the @starter-file{alg2-aaron-judge}, and create scatter plots to search for relationships between columns. They share and discuss their findings with the class, discovering the limitations of linear models.

=== Launch

@teacher{These questions are intended to spark student interest in the dataset they are about to explore.}

@QandA{
@right{@image{images/aaron-judge.jpeg, 200}}Aaron Judge is an American professional baseball outfielder for the New York Yankees. In 2022 he hit 62 home runs, setting the  American League record for most home runs in a season.
@Q{What is a home run?}
@A{When a batter makes it around all of the bases and back to home plate before the other team is able to gain control of the ball and stop them.}
@Q{What factors might influence how many home runs a player hits in a season?}
@A{Possible responses:}
@A{How fast the batter runs.}
@A{The speed and angle at which the batter swings the bat.}
@A{How calm and focused the player is when they are at bat, perhaps influenced by personality, sleep, diet, stretching, meditation, etc.}
@A{How many hits make it into the bleachers, so they are inaccessible to the outfielders.}
@A{How fans and teammates support the batter.}
}
@slidebreak

In this lesson, we'll explore possible relationships between pitch (type and speed), bat angle, and hit (distance, speed and ball type).

First, we'll explore a data set of Aaron Judge's hits in 2016 and 2017 and see if any of the relationships between quantitative columns appear to be linear.

@lesson-instruction{
- Open the @starter-file{alg2-aaron-judge}.
- From the File menu, select "Save a Copy", and click "Run".
- Working in pairs or small groups, complete the first section of @printable-exercise{exploring-judge-data.adoc}.
}

@QandA{
@Q{Which quantitative columns appear to have the strongest relationship?}
@A{bat-angle and hit-distance}
@Q{Would you describe it as a linear relationship?}
@A{No.}
}

=== Investigate

There definitely appears to be a relationship here...
@center{@image{images/curve-angle-distance.png,400}}

@slidebreak

But linear models don't seem to fit very well!

@scrub{MAKE NEW IMAGES ONCE PYRET ISN'T DEFAULTING TO SCINOT}

[cols="^.^1a,^.^1a,^.^1a", frame="none", stripes="none"]
|===
| We could build linear models that fit the increasing half of the data...
| We could build linear models that fit the decreasing half of the data...
| We could build linear models that try to split the difference...

| @image{images/curve-angle-distance-linear1.png}
| @image{images/curve-angle-distance-linear2.png}
| @image{images/curve-angle-distance-linear3.png}
|===

But all of them are far away from so many points, and will make poor predictions for a large subset of x-values.

@slidebreak

@lesson-instruction{
- Complete the rest of @printable-exercise{exploring-judge-data.adoc}. Be ready to share back and describe the curve you drew.
- Is there a function @math{\text{bat-angle}(\text{hit-distance})}, that describes the pattern you see here?
}

@slidebreak

Even though some hits go farther than others, Aaron Judge's hit distance generally increases as his bat angle increases from 0 to 30 degrees. As the angle increases after that, his hit distance generally _decreases!_

@teacher{Review student answers to confirm that students see a _nonlinear_ relationship in the dataset that is fairly strong. Students should generally agree that the relationship is better fit by a curve, with hit distance peaking at a bat angle of _roughly_ 30 degrees.  *Make sure students have agreed on this vertex*, as its location is important for the next activity!

Have students share their curves, encouraging them to identify where they "peak" and where they cross the x-axis. These locations will be important anchor concepts on which to build in the next section. (One option for facilitating sharing is to project the scatter plot on a whiteboard and have students come up and draw all of their curves on it).
}

=== Synthesize

- Why don't linear models work to model the relationship between bat angle and hit distance?
- What kinds of curves did you draw that fit better?
- Are there any mathematical functions that look like those curves?


== Quadratic Relationships
@objective{quadratic-situations}

=== Overview
Students are introduced to quadratic functions. They become familiar with scenarios involving quadratics learn how to identify quadratic sequences.

=== Launch
Linear models work well for fitting simple relationships, but many relationships in the real world are more complex! _Linear models are often too primitive_.

The relationship we observe between bat angle and hit distance appears to best be described by a _curve_, where hit distance increases up to a certain bat angle, and then decreases again.

@slidebreak

Today, we will learn about one kind of curved model called a @vocab{quadratic relationship}.  Graphs of quadratic relationships are often described as "u-shaped" or "looking like an arch". More formally, mathematicians and data scientists call these kinds of curves @vocab{parabolas}.

There are lots of relationships that change direction like this! For example, when an athlete is young, they improve as they get stronger and more skilled. But as they age, they begin to lose their speed and strength.

In some quadratic relationships, the curve goes the other way - decreasing, bottoming out, and then rising again. For example, the graph of an accelerating car's position over time will look like the right-half of a downward-facing parabola, with the car covering more distance each second than last.

=== Investigate

@QandA{
@Q{Can you think of any other real-world relationships that appear to be quadratic?}
@A{A ball dropped from a tall building will get faster and faster as it falls, so a graph of @math{\text{distance}(\text{time})} will be quadratic.}
@A{Many nutrients are good for you, and the more you take the healthier you are...up to a point. After that, too much of a mineral or vitamin can cause problems. A graph of @math{\text{health}(\text{dose})} will be quadratic.}
@A{A ball thrown in the air will rise quickly, slow down, peak, and then begin to fall. A graph of @math{\text{height}(\text{time})} will be quadratic.}
@A{The temperature of a puddle will warm and then cool over the course of the day. A graph of @math{\text{temp}(\text{time})} will be quadratic.}
@A{The length of a shadow is long in the morning and shortens til the sun is overhead, after which it slowly lengthens til the sun sets. A graph of @math{\text{length}(\text{time})} will be quadratic.}
}

@slidebreak

@lesson-instruction{
Turn to @printable-exercise{classifying-descriptions.adoc} and practice identifying whether the scenarios are likely best modeled by linear or quadratic relationships.
}

=== Synthesize

@QandA{
@Q{What characteristics did you look for to identify whether a scenario was likely best-modeled by a linear or quadratic relationship?}
@A{When there's either a steady increase or a steady decrease, a linear model will likely fit.}
@A{When there's a high point or a low point at which the change changes direction, a quadratic model will likely be a good fit.}
}


