= Compound Inequalities: Solutions & Non-Solutions

@description{Students build upon their understanding of Booleans and simple inequalities to compose compound inequalities using the concepts of union and intersection.}

@lesson-prereqs{inequalities1-simple}

@keywords{number line, solution set}

@add-to-lang{and, or}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* Understand how the conjunctions `and` and `or` differ
* Describe how functions can work together
* Describe the solution set of a @vocab{compound inequality}

| Student-Facing Lesson Goals
|
* Let's use two or more inequalities together. 
* Let's learn the difference between how `and` and `or` are used in programming.
* Let's find solutions and non-solutions for compound inequalities.
//* I can tell someone else how two or more @vocab{function}s work together

| Materials
|[.materials-links]


@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
| * There is an optional interactive Desmos activity in the lesson. If you would like to use it, decide how you will share it with students and, if you are using our slides, add the appropriate link to the slide deck. _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}

|===

== Introducing Compound Inequalities

=== Overview
Students consider the need to _compose_ inequalities, and think about how to write them.

=== Launch

We use inequalities for lots of things:

- Is it hot out? (@math{temperature \gt 80°})
- Did I get paid enough for painting that fence? (@math{paid \ge $100})
- Are the cookies finished baking? (@math{timer = 0})

@lesson-instruction{
What other examples can you come up with?
}

Many times we need to _combine_ inequalities:

- Should I go to the beach? (@math{temperature \gt 80°} and @math{weather = "sunny"})
- Was this burrito worth the price? (@math{taste = "delicious"} and @math{price \leq $15})

@lesson-instruction{
Can you think of examples of when we might want to combine inequalities?
}

Guide students through other examples of `and` and `or` with various statements, such as:

- "I'm wearing a red shirt AND I'm a math teacher, true or false?"
- "I'm an NBA basketball star OR I'm having pizza for lunch, true or false?"

This can make for a good sit-down, stand-up activity, where students take turns saying compound Boolean statements and everyone stands if that statement is true for them.

=== Investigate
Both mathematics and programming have ways of combining - or _composing_ - inequalities.

@lesson-instruction{
Complete @printable-exercise{pages/boolean-coe-to-code1.adoc} and @printable-exercise{pages/and-or.adoc}.
}

=== Synthesize
Be really careful to check for understanding here.

- Expressions using `and` only produce `true` if both of their sub-expressions are `true`.
- Expressions using `or` produce `true` if *either* of their sub-expressions are `true`.

@strategy{
@span{.title}{Strategies for English Language Learners}

When describing compound inequalities, be careful not to use "English shortcuts". For example, we might say "I am holding a marker _and_ an eraser" instead of "I am holding a marker _and_ I am holding an eraser." These sentences mean the same thing, but the first one obscures the fact that "and" joins two complete phrases. For ELL/ESL students, this is unecessarily adds to cognitive load!
}

== Solutions and Non-Solutions of Compound Inequalities

=== Launch

@lesson-instruction{
Complete @printable-exercise{compound-warmup.adoc}.
}


=== Investigate

@lesson-instruction{
* Open the @starter-file{inequalities-compound}.
* Click "Run" to see graphs of the inequalities you've just considered.
}

@teacher{
When students click "Run", four graphs will appear. The top two are the simple inequalities they've just discussed. Encourage students to verify that their solutions and non-solutions are correct. 
}

@lesson-instruction{
* The bottom two graphs are produced by the special functions `and-intersection` and `or-union`. 
* Read the comments in the Definitions area with your partner to learn how these functions are supposed to work.
* Then complete @printable-exercise{compound-explore.adoc}.
}

@QandA{
@Q{Why is the circle on 5 red and the circle on 15 green?}
@A{The circle on 5 is red because 5 is not part of the solution - it _is not_ bigger than itself.}
@A{The circle on 15 is green because 15 is part of the solution - it _is_ less than or equal to 15.}
}

@centered-image{images/intersection-ns.png}

@QandA{
@Q{Why isn't there a solution to @math{x \lt 5 and x \ge 15}}
@A{There aren't any numbers that are both smaller than 5 and greater than or equal to 15, so there is no solution!}
}

`or-union` takes in two functions and a list of numbers and produces a graph with the points and the shaded @vocab{union} of values that make either or both of the inequalities true.

@lesson-point{
In order to make an `or` statement true, a value only has to make one of the inequalities true. 
}

@centered-image{images/union1.png}

Sometimes unions are represented by two separate arrows pointing in opposite directions with a gap between their starting points.

@centered-image{images/lt1orlt3.png, 450}

Sometimes unions overlap and appear as a single arrow pointing in one direction.

@centered-image{images/union-infinite1.png}

Sometimes unions overlap and cover the entire number line!

@QandA{
@Q{Why is the whole graph of @math{x \gt 5 or x \le 15} shaded blue?}
@A{Because every number in the universe is either greater than 5 or less than or equal to 15, so there aren't any non-solutions!}
}

@teacher{Once students are familiar with the starter file, they are ready to use it as they practice identifying solutions and non-solutions for compound inequalities.}

@lesson-instruction{
- Turn to @printable-exercise{compound-inequality-solutions.adoc}.
- Explore the compound inequalities listed using the @starter-file{inequalities-compound}, identifying solutions and non-solutions for each.
}

Instead of defining two functions as simple inequalities, we can produce an inequality graph by defining one function to be a @vocab{compound inequality}!

In the following activity, we'll analyze inequality graphs and define a _single_ function that produces the graph.

@teacher{Walk students through the completed first example before they attempt to write this code on their own.}

@lesson-instruction{
- Turn to @printable-exercise{compound-inequality-functions.adoc}.
- Write code to describe the compound inequalities pictured.
}

@ifproglang{pyret}{@optional @opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fdf8618945cb549d457fb85, Match Compound Inequality Functions with Plots of their Solution Sets}.
}

=== Synthesize
- How did the graphs of intersections and unions differ?

== Additional Exercises

- @opt-printable-exercise{pages/boolean-coe-to-code2.adoc}

