= Compound Inequalities: Solutions & Non-Solutions

@description{Students build upon their understanding of Booleans and simple inequalities to compose compound inequalities using the concepts of union and intersection.}

@lesson-prereqs{inequalities1-simple}

@keywords{number line, solution set}

@add-to-lang{and, or}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:
@objectives

@objective{Understand how the conjunctions `and` and `or` differ}
@objective{Describe the solution set of a compound inequality}

| Student-Facing Lesson Goals
|
- Let's use two or more inequalities together. 
- Let's learn the difference between how `and` and `or` are used in programming.
- Let's find solutions and non-solutions for compound inequalities.
//* I can tell someone else how two or more @vocab{function}s work together

| Materials
|[.materials-links]


@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
| 
@preparation{
- There is an optional interactive Desmos activity in the lesson. If you would like to use it, decide how you will share it with students and, if you are using our Google Slides, add the appropriate link to the slide deck. _If you're a first-time Desmos user, fear not!_@dist-link{pages/desmos-instructions.adoc, _Here_'s what you need to do._}
}

|===

== Introducing Compound Inequalities

=== Overview
Students consider the need to _compose_ inequalities, and think about how to write them.

=== Launch
@slidestyle{Launch}

We use inequalities for lots of things:

- Is it hot out? (@math{temperature \gt 80°})
- Did I get paid enough for painting that fence? (@math{paid \ge $100})
- Are the cookies finished baking? (@math{timer = 0})

@lesson-instruction{
What other examples can you come up with?
}

@slidebreak{Launch}

Many times we need to _combine_ inequalities to answer our questions:

- We use `and` when we need *both* inequalities to be `true`.
- We use `or` when we need *at least one* of the inequalities to be `true`.

@slidebreak{Launch}

For Example:

- Could it snow? 
  * @math{temperature \le 32°F} and @math{temperature \ge 10°F}
- Is the baby too big for an infant car seat?
  * @math{height \ge 30"} or @math{weight \ge 30 pounds}
- Should I go swimming outside? 
  * @math{temperature \gt 75°F} and @math{weather <> "lightning"}

@lesson-instruction{
Can you think of examples of when we might want to combine inequalities?
}

@slidebreak{Launch}

@QandA{
We know that it could snow if @math{temperature \le 32°F} and @math{temperature \ge 10°F}.

@Q{Would this expression be true if the temperature was 30°F? How do you know?}
@A{Yes. 30 is both below 32 and higher than 10.}

@Q{Would this expression be true if the temperature was 5°F? How do you know?}
@A{No. While 5 is less than 30, it's not greater than 10. 5°F is too cold to snow.}
}

@slidebreak{Launch}

@QandA{
We know that the baby is too big for an infant seat if @math{height \ge 30"} or @math{weight \ge 30 pounds}

For each baby below, decide whether the baby needs a bigger car seat and explain how you know.
@Q{Baby 1 -   Height: 32", Weight: 35 pounds}
@A{Yes. They are too tall and too heavy an infant car seat.}

@Q{Baby 2 -   Height: 33", Weight: 22 pounds}
@A{Yes. They are too tall for an infant car seat.}

@Q{Baby 3 -   Height: 20", Weight: 15 pounds}
@A{No. They are short enough and light enough for an infant car seat.}

@Q{Baby 4 -   Height: 29", Weight: 35 pounds}
@A{Yes. They are too heavy for an infant car seat.}
}

@strategy{Stand if it's True for you!}{
Practicing whether compound inequalities will be true or false makes for a great sit-down, stand-up activity, where students take turns saying compound Boolean statements and everyone stands if that statement is true for them.

- "I'm wearing a red shirt AND I'm a math teacher, true or false?"
- "I'm an NBA basketball star OR I'm having pizza for lunch, true or false?"

}

@slidebreak{Launch}

@lesson-point{
Expressions using `and` only produce `true` if both of their sub-expressions are `true`. +
Expressions using `or` produce `true` if *either* of their sub-expressions are `true`.
}

=== Investigate
@slidestyle{Investigate}
Both mathematics and programming have ways of combining - or _composing_ - inequalities.

@lesson-instruction{
@ifnotslide{
Complete @printable-exercise{boolean-coe-to-code1.adoc} and @printable-exercise{and-or.adoc}.
}
@ifslide{
Complete:
- @printable-exercise{boolean-coe-to-code1.adoc}
- @printable-exercise{and-or.adoc}
}
}

=== Synthesize
@slidestyle{Synthesize}

@teacher{Be careful to check for understanding here.}

@QandA{
@Q{What is the difference between combining inequalities using `and` and `or`?}
@A{Expressions using `and` only produce `true` if both of their sub-expressions are `true`.}
@A{Expressions using `or` produce `true` if *either* of their sub-expressions are `true`.}
}

@strategy{Strategies for English Language Learners}{
When describing compound inequalities, be careful not to use "English shortcuts". For example, we might say "I am holding a marker _and_ an eraser" instead of "I am holding a marker _and_ I am holding an eraser." These sentences mean the same thing, but the first one obscures the fact that "and" joins two complete phrases. For ELL/ESL students, this is unnecessarily adds to cognitive load!
}

== Solutions and Non-Solutions of Compound Inequalities

=== Launch
@slidestyle{Launch}

@lesson-instruction{
Complete @printable-exercise{compound-warmup.adoc}.
}

=== Investigate
@slidestyle{Investigate-DN}

@lesson-instruction{
- Open the @starter-file{inequalities-compound}.
- Click "Run" to see graphs of the inequalities you've just considered.
}

@teacher{
When students click "Run", four graphs will appear. The top two are the simple inequalities they've just discussed. Encourage students to verify that their solutions and non-solutions are correct. 
}

@lesson-instruction{
- The bottom two graphs are produced by the special functions `and-intersection` and `or-union`. 
- Read the comments in the Definitions area with your partner to learn how these functions are supposed to work.
- Then complete @printable-exercise{compound-explore.adoc}.
}

@slidebreak{InvestigateC}

@centered-image{images/intersection1.png}

@QandA{
@Q{What does it mean that initial circle on 5 is red and the circle on 15 is green?}
@A{The circle on 5 is red because 5 is not part of the solution - it _is not_ bigger than itself.}
@A{The circle on 15 is green because 15 is part of the solution - it _is_ less than or equal to 15.}
}

@slidebreak{InvestigateC}

@centered-image{images/intersection-ns.png}

@QandA{
@Q{Why isn't there a solution to @math{x \lt 5 and x \ge 15}}
@A{There aren't any numbers that are both smaller than 5 and greater than or equal to 15, so there is no solution!}
}

@slidebreak{Investigate}

`or-union` takes in two functions and a list of numbers and produces a graph with the points and the shaded @vocab{union} of values that make either or both of the inequalities true.

@lesson-point{
In order to make an `or` statement true, a value only has to make one of the inequalities true. 
}

@slidebreak{InvestigateC}

@centered-image{images/union1.png}

Sometimes unions are represented by two separate arrows pointing in opposite directions with a gap between their starting points.

@slidebreak{InvestigateC}

@centered-image{images/lt5orlte15.png, 450}

Sometimes unions overlap and appear as a single arrow pointing in one direction.

@slidebreak{InvestigateC}

@centered-image{images/union-infinite1.png}

Sometimes unions overlap and cover the entire number line!

@slidebreak{InvestigateC}

@ifslide{@centered-image{images/union-infinite1.png}}

@QandA{
@Q{Why is the whole graph of @math{x \gt 5 or x \le 15} shaded blue?}
@A{Because every number in the universe is either greater than 5 or less than or equal to 15, so there aren't any non-solutions!}
}

@teacher{Once students are familiar with the starter file, they are ready to use it as they practice identifying solutions and non-solutions for compound inequalities.}

@slidebreak{Investigate-DN}

@lesson-instruction{
- Turn to @printable-exercise{compound-inequality-solutions.adoc}.
- Use the @starter-file{inequalities-compound} to explore the inequalities on the page, identifying solutions and non-solutions for each.
}

@slidebreak{Investigate}

Instead of defining two functions as simple inequalities, we can produce an inequality graph by defining one function to be a @vocab{compound inequality}!

@lesson-instruction{
- Turn to @printable-exercise{compound-inequality-functions.adoc} and take a minute to look at the code in the example and think about what you Notice and Wonder.}
@QandA{

@Q{What do you Notice about how the code works?}
@A{_Answers will vary. Facilitate a conversation to draw out all of the things students will need to understand in order to write definitions for the remaining examples!_}
@A{We see that the left end of the shaded region is at 0 and the dot on zero is red so it's not part of the solution set. +
This tells us that the first inequality is @math{x > 0}.}
@A{We see that the right end of the shaded region is at 8.1 and the dot on zero is green so it is part of the solution set. +
This tells us that the second inequality is @math{x \le 8.1}.}
@A{Since the shaded area is where these two inequalities overlap, we know that it's a union, which means they are linked with `and`.}
@A{Each of the simple inequality expressions is enclosed in a set of parentheses.}
@A{The definition starts with @ifproglang{wescheme}{define.}@ifproglang{pyret}{`fun` and ends with `end`}}

@Q{What do you Wonder?}
@A{_Answers will vary, but make space for questions._}
}

@lesson-instruction{
- With your partner, define compound inequality functions for the remaining graphs on the page.
@ifproglang{pyret}{
- @opt{@opt-starter-file{inequalities-compound-match}}
}
}

=== Synthesize
@slidestyle{Synthesize}

@QandA{
@Q{How did the graphs of intersections and unions differ?}
@A{Intersections were where the two inequalities overlapped. Sometimes they are finite sections of the number line (represented by a segment with dots at both ends) and sometimes they are infinite (represented by an arrow)}
@A{Unions include everything that was part of either inequality. They can look like a segment, a single arrow, or two arrows.}
}

== Additional Exercises
@slidestyle{Supplemental}

@opt-printable-exercise{boolean-coe-to-code2.adoc}

