= Displaying Categorical Data

@description{Students learn to generate and compare bar graphs, explore other plotting & display functions in CODAP, and (optionally) design an infographic.}

@add-to-lang{bar-chart, pie-chart, pie-chart-summarized, bar-chart-summarized, histogram, box-plot, scatter-plot}

[@lesson-intro-table]
|===
@lesson-prereqs{}
| Lesson Goals
| Students will be able to:

* Read bar charts
* Generate bar charts (among other data displays) from the Animals Dataset


| Student-facing Lesson Goals
|

* Let's get to know CODAP by creating bar graphs and other data displays from tables.

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/1MaNFBTVZIBXsvfn8I4f_0IQhoXYQHgEWkqGtQda2DG8/edit?usp=sharing, Lesson slides}

@material-links

| Supplemental Resources
| @link{https://informationisbeautiful.net/, Information is Beautiful}

|===

== Displaying Categorical Variables @duration{10 minutes}
=== Overview

Students use the options on CODAP's _Configuration_ menu to produce displays and plots of the Animals Dataset.

=== Launch
Where have you seen infographics and graphs used to display data in the real world?

Open the @starter-file{animals} in CODAP.

[.lesson-instruction]
--
- Click the `graph` icon from the horizontal toolbar in the upper left. (See toolbar, below.) What appears?

@centered-image{images/codap-upper-left-toolbar.png, CODAP upper left toolbar, 300}

- Select a dot with your mouse. What happens?
- What happens when you select a table row? How about multiple table rows?
- What happens when you click the "eye" icon (to the right of the graph or the table, depending on which is selected)?
--

@right{@image{images/codap-initial-display.png,"An image of the CODAP environment" ,300}}

**If students report that a blank graph appears (rather than a scatterplot), prompt them to whitelist CODAP on their ad-blocker. Ad-blockers do seem to inhibit some of the functionality of CODAP (which will fortunately never advertise to users!).**

Initially, the data points are randomly distributed on the graph. Selecting an orange dot reveals the `name` of that particular animal. Selecting a particular dot causes the table row for that animal to be highlighted in blue. Holding the shift button allows students to select multiple dots in the graphical display, or multiple rows in the table.

Students should observe that when they select a table row (or multiple table rows), the corresponding dots change color. When they set aside selected and / or unselected cases (by using the "eye" icon), they can temporarily alter the amount of pets in the dataset (with the option to restore to the original dataset).

Students can also resize the window by dragging its borders.


=== Investigate

Once we have a graph of randomly distributed data points, we can organize the data by selecting attributes from our _table_ that we want to appear on the axes of our graph.

[.lesson-instruction]
Practice manipulating the data by completing @printable-exercise{pages/codap-displays-intro.adoc}.


Remind students that categorical data is used to classify, rather than to measure. Only when data is being treated categorically will students be invited to fuse data points to create a bar chart. Quantitative (or numeric) data must measure or compare; it is subject to the laws of arithmetic.

To dig deeper into bar charts, have students turn to @opt-printable-exercise{bar-chart-notice.adoc}.


[.strategy-box, cols="1", grid="none", stripes="none"]
|===
a|
@span{.title}{People aren't Hermaphrodite?}
When students make a display of the `sex` of the animals, they will see that some animals are male, some are female and some are hermaphrodites. We use the descriptor _sex_ rather than _gender_ because sex refers to biology, whereas gender refers to identity. Hermaphrodite is the biological term for animals that carry eggs & produce sperm (nearly 1/3 of the non-insect animal species on the planet!). Plants that produce pollen & ovules are also hermaphrodites. While the term was previously used by the medical community to describe intersex people or people who identify as transgender or gender non-binary, it is not biologically accurate. Humans are not able to produce both viable eggs and sperm, so "hermaphrodite" is no longer considered an acceptable term to apply to people.
|===


=== Common Misconceptions

Bar charts look a lot like another kind of display - called a "histogram" - which displays _quantitative_ data, not categorical. Histograms and Bar Charts are very different! In CODAP, however, making a histogram and making a bar chart start the same way: by creating a dot plot that will be modified. This may cause students to think they resulying displays are the same, simply because making them _starts_ the same way.

=== Synthesize
Bar charts display how much of the sample belongs to each category. If they are based on sample data from a larger population, we use them to _infer_ the proportion of a whole population that might belong to each category.

[.lesson-point]
Bar charts are mostly used to _display categorical columns_.

While bars in some bar charts should follow some logical order (alphabetical, small-medium-large, etc), they can technically be placed in _any_ order, without changing the meaning of the chart.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
a|
@span{.title}{Mini Project: Making Infographics}
Infographics are a powerful tool for communicating information, especially when made by people who actually understand how to connect visuals to data in meaningful ways. @opt-project{infographics.adoc, infographic-rubric.adoc} is an opportunity for students to become more flexible math thinkers while tapping into their creativity. This project can be made on the computer or with pencil and paper. There's also an @link{pages/infographic-rubric.html, Infographics Rubric} to highlight for you and your students what an excellent infographic includes.
|===

== Exploring other Displays @duration{30 minutes}

=== Overview
Students explore the CODAP data display options available to them when they select the bar graph icon (also known as the `configuration` menu). In doing so, they experiment with new charts and get comfortable with CODAP as a platform for doing data science.


=== Launch
There are _lots_ of different kinds of charts and plots. To get CODAP to create any type of display, it is important to consider a few key questions.

[.lesson-instruction]
- Let's say we want to create a bar chart show the `sex` breakdown of the animals. We must consider the following: _Which attributes on which axes? What type of data? What configuration?_
- We will use this @printable-exercise{pages/plot-practice.adoc} worksheet to guide our thinking.

Sharing with students your thought process as you create this bar chart will help them to conceptualize the steps they must take to create any data display in CODAP.

After you have guided students through the process of creating a bar chart, direct them to sketch a prediction of what the bar chart will look like. Invite students to share their predictions, before you reveal the actual bar chart produced by CODAP.

=== Investigate
[.lesson-instruction]
Complete @printable-exercise{pages/exploring-displays-1.adoc} and @printable-exercise{pages/exploring-displays-2.adoc}.

=== Common Misconceptions
There are _many_ possible misconceptions about displays that students may encounter here. *But that's ok!* Understanding all those other plots is _not_ a learning goal for this lesson. Rather, the goal is to have them develop some loose familiarity.

=== Synthesize
Today you’ve added more data displays to your toolbox. You can create bar charts to visually display data, and even transform entire tables!

You will have many opportunities to use these concepts in this course, by applying what you've learned to answer data science questions.

== Additional Exercises:
