= Exploring the Model

Use @starter-file{plagiarism} to respond to the questions, below.

== distance-to

@n Type `distance-to(student-essay)`. The table that appears displays the angle difference between `student-essay` and each of the other animal articles in the corpus.

-  Which article is the _most similar_ to student-essay? @fitb{}{@ifsoln{`elephant-article`}}
-  What is the angle difference between `student-essay` and the _most similar_ article in the corpus? @fitb{}{}
- Which article is the _most different_ from `student-essay`? @fitb{}{@ifsoln{`hamster-article`}}
- What is the angle difference between `student-essay` and the _most different_ article? @fitb{}{@ifsoln{77.565°}}

@n Our corpus is made up of eight articles about different animals. Which other animals, aside from elephant and hamster, are represented in the corpus? List them here:
@fitb{}{@ifsoln{polar bear, rhino, blue whale, giraffe, manatee, chimpanzee, badger, snail}}

@fitb{}{}

@fitb{}{}


@n In the Interactions Area, type `distance-to(chimpanzee-article)`.

- One of the angle differences listed in the table is zero. What does that tell you? @fitb{}{}
- Which article is the most similar to `chimpanzee-article`? @fitb{}{@ifsoln{`giraffe-article`}}
- What is the angle difference between `chimpanzee-article` and the _most similar_ article? @fitb{}{@ifsoln{59.2059°}}
- Which article is the most different from chimpanzee-article? @fitb{}{@ifsoln{`rhino-article`}}
- What is the angle difference between `chimpanzee-article` and the _most different_ article? @fitb{}{@ifsoln{72.618°}}

== string-to-bag-cleaned

@n In the Interactions Area, type `string-to-bag(snail-article)`.

- How many unique words are used in the snail article? @fitb{}{@ifsoln{39 words}}
- List each word that is used 2 or more times in the article. We've provided the first three: @fitb{}{a (2), and (3), be (3),}

@fitb{}{@ifsoln{can (2), found (2), greater(2), in (2), of (4), snail (2), snails (3), the (3)}}

- What do you Notice about the commonly used words? What do you Wonder? @fitb{}{}

@fitb{}{}

@fitb{}{}

@n In the Interactions Area, type `string-to-bag-cleaned(snail-article)`.

- Notice that there are fewer unique words listed. How many unique words are on the table now? @fitb{}{@ifsoln{23 words}}
- List each word that appears 2 or more times, now: @fitb{}{@ifsoln{found (2), greater (2), snail (2), snails (3)}}


