= Sampling and Inference


1) Evaluate the `big-animals-table` in the Interactions Area. This is the _complete_ population of animals from the shelter! 

[.lesson-point]
The population is 47.7% fixed and 52.3% unfixed.

2) How close to these percentages do we get with random samples? Type each of the following lines into the Interactions Area and hit “Enter".
----
random-rows(big-animals-table, 10)
random-rows(big-animals-table, 40)
----
3) What do you get? @fitb{95ex}{}

@vspace{2ex}

4) What is the contract for `random-rows`? @fitb{80ex}{}

@vspace{2ex}

5) What does the `random-rows` function do?

@span{.blankline}

@span{.blankline}

@vspace{2ex}

6) In the Definitions Area, define `tiny-sample` and `small-sample` to be these two random samples.

@vspace{2ex}

7) Make a `pie-chart` for the animals in each sample, showing percentages of fixed and unfixed. Note that the percentage of fixed animals in the entire populations is 47.7%.

- The percentage of fixed animals in `tiny-sample` is @fitb{20ex}{}
- The percentage of fixed animals in `small-sample` is @fitb{20ex}{}

@vspace{1ex}

[.lesson-point]
The population is roughly 5% tarantulas.
 
@vspace{1ex}

8) How close to these percentages do we get with random samples? Make a  `pie-chart` for the animals in each sample, showing percentages for each species.

- The percentage of tarantulas in `tiny-sample` is @fitb{20ex}{}
- The percentage of tarantulas in `small-sample` is @fitb{20ex}{}

@vspace{2ex}

9) Which repeated sample gave us a more accurate inference about the whole population? Why?

@span{.blankline}

@span{.blankline}