= Sampling and Inference

1) Evaluate the `big-animals-table` in the Interactions Area. This is the _complete_ population of animals from the shelter! 

[.lesson-point]
The population is roughly 50% male and 50% female.

2) How close to these percentages do we get with random samples? Type each of the following lines into the Interactions Area and hit “Enter".
----
random-rows(big-animals-table, 10)
random-rows(big-animals-table, 40)
----
3) What do you get? @fitb{60ex}{}

@vspace{2ex}

4) What is the contract for `random-rows`? @fitb{60ex}{}

@vspace{2ex}

5) What does the `random-rows` function do?

@span{.blankline}

@span{.blankline}

@vspace{2ex}

6) In the Definitions Area, define `small-sample` and `large-sample` to be these two random samples.

7) Make a `pie-chart` for the animals in each sample, showing percentages of males and females. Note that the percentage of males in the entire population is XX

- The percentage of males in `tiny-sample` is @fitb{20ex}{}
- The percentage of males in `small-sample` is @fitb{20ex}{}

[.lesson-point]
The population is 48.6% fixed and 51.4% unfixed.

8) How close to these percentages do we get with random samples? Make a `pie-chart` for the animals in each sample, showing the percentages of fixed and unfixed.

- The percentage of fixed animals in `tiny-sample` is @fitb{20ex}{}
- The percentage of fixed animals in `small-sample` is @fitb{20ex}{}

9) Which repeated sample gave us a more accurate inference about the whole population? Why?

@span{.blankline}

@span{.blankline}