= Solving Word Problems

@lesson-description{Students discover functions as an abstraction over an arithmetic pattern, applying the Design Recipe to traditional word problems.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-defining-functions}
| Lesson Goals
| Students will be able to:

* Understand how to use the Design Recipe to break down word problems.
* Create a strong purpose statement that details in their own words what the function should do.

| Student-Facing Lesson Goals
|
* I can use the @vocab{Design Recipe} to break down word problem when writing a @vocab{function}.
* I can identify the @vocab{domain} and @vocab{range} and other quantities in a word problem when writing a function.
* I can create and revise a strong @vocab{purpose statement} that explains what the function is doing.

| Materials
|

@ifproglang{wescheme}{
*  @link{https://docs.google.com/presentation/d/1eEBizJfayR_DtmNlrwMioSsbN6-6m4MupPzHflDAhW8/edit?usp=sharing, Lesson slides}
*  @link{https://www.wescheme.org/openEditor?publicId=LGTVNvzrax, Rocket-height starter file}
}

@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/10mSOI3INh4CHp2sy7BPApE4yalaYTWA-SZAtbqSCYBI/edit?usp=sharing, Lesson Slides}
* @link{https://code.pyret.org/editor#share=1pkPbRg_xXYum_gTQ-2GmcPa3iL4Eq6Kd&v=7db4b91, Rocket-height starter file}
}

@material-links

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|

* Design Recipe Practice (@link{https://teacher.desmos.com/activitybuilder/custom/5d991b421172d473178c981b, Desmos Activity})
* Design Recipe Practice - Blank Template (@link{https://teacher.desmos.com/activitybuilder/custom/5d991b939b9b292020c1810d, Desmos Activity})
}

| Key Points for the Facilitator
|
* The *purpose statement* is a comment in the code - something the computer doesn't read.  It is important for readability of their code - there may be other people looking at their code and using their functions!
* Remind students that the domain and range of a function must be one or more of the three @vocab{data types} (Number, String, Image) they've learned so far.
* If students struggle with creating the examples, use the Circle of Evaluation mapping activity or use role-playing to help students build up their understanding around the concept.
|===

[.old-materials]
Click here to see the @link{https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/units/unit4/index.html, prior unit-based version}

== Warmup

Students should have their workbook, pencil, and be logged into
@ifproglang{wescheme}{ @link{https://www.wescheme.org, WeScheme     } }
@ifproglang{pyret}{    @link{https://code.pyret.org, code.pyret.org } }
on their computer.

== Writing Linear Functions @duration{25 minutes}

=== Overview
Students are given a non-working program, which uses a linear function to determine the height of a rocket after a given length of time. The "broken" code is provided to lower cognitive load, allowing students to focus on comprehension (reading the code) and making use of structure (identifying where it's broken).

=== Launch

Ask students to open the 
@ifproglang{wescheme}{ @link{https://www.wescheme.org/openEditor?publicId=LGTVNvzrax, rocket-height Starter File} and click "Run". By typing `(start rocket-height)`, they will see the simulation start to run on their computer. }
@ifproglang{pyret}{ @link{https://code.pyret.org/editor#share=1pkPbRg_xXYum_gTQ-2GmcPa3iL4Eq6Kd&v=7db4b91, rocket-height Starter File} and click "Run". By typing `start(rocket-height)`, they will see the simulation start to run on their computer. }

[.notice-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Notice and Wonder}

What do you notice about this program?  What do you wonder?
|===

Survey the class on their "Notices" and "Wonders" and record on the board before moving on to the discussion.

[.lesson-instruction]
- Is `rocket-height` working?
- Why do you think it's not working?
- What do you think the *purpose* of this function is?  How do you know?

- What is the domain of `rocket-height`?
_Number_

- What is the range of `rocket-height`? How do you know?
_Number, we can tell by looking at the @vocab{contract} for the function._

- As the program is currently written, what happens when I give the function an input of 5?  15?  One million?
_It always returns 0._

You've started to master most of the steps of the Design Recipe, but there's one part you haven't seen yet: _writing a purpose statement_. Programmers and Mathematicians alike find it helpful to restate a problem in their own words. After all, if you can't explain a problem to someone else, you probably don't understand it yourself!

=== Investigate

Let's use the Design Recipe to fix `rocket-height`, and get comfortable with writing *purpose statements*.

[.lesson-instruction]
- Have students turn to @workbook-link{pages/rocket-height.adoc} and read the problem statement with their partner.
- Now that the students have revised and refined their purpose statement, have them write the @vocab{Contract} and @vocab{purpose statement} on @workbook-link{pages/rocket-height.adoc} worksheet.
- Given the contract and purpose statement, write two examples of how `rocket-height` should work after two different lengths of time.
- Circle and label what's changing in the two examples, just as they did with their green triangle function before.
- Choose a good variable name for what's changing.
- Write the function definition using the variable name.
- Once the Design Recipe has been completed in the workbook, students can type the code into the `rocket-height` program, replacing any incorrect code with their own code.

=== Synthesize
- What was the problem?
- What mistake did the programmer make?
- Where in the Design Recipe did they first go astray?

_The Design Recipe allows us to trace mistakes back to the source!_

== More Interesting Functions @duration{flexible}

=== Overview
For teachers who cover quadratic and exponential functions, this activity deepens students' understanding of functions and extends the Design Recipe to include those. This can also be a useful activity for students who finish early, or who need more of a challenge.

=== Launch
Now that `rocket-height` is working correctly, explore the rest of the file and try the following:

- Remove the comment from before the `(start rocket-height)` and test the program.
- Put the comment back in front of `(start rocket-height)`, remove the comment from `(graph rocket-height)`, and test the program.
- Try out `(space rocket-height)`
- Try out `(everything rocket-height)`

=== Investigate
[.lesson-instruction]
- Can you make the rocket fly faster? Slower?
- Can you make the rocket sink down instead of fly up?
- Can you make the rocket _accelerate over time_, so that it moves faster the longer it flies?
- Can you make the rocket blast off _and then land again_?
- Can you make the rocket blast off, _reach a maximum height of exactly 1000 meters_, and then land?
- Can you make the rocket blast off, reach a maximum height of exactly 1000 meters, and then land after exactly 100 seconds?
- Can you make the rocket fly to the edge of the the universe?

=== Synthesize
Debrief - what did students try? Have students share their experiments with one another!

== Additional Exercises:
- @exercise-link{pages/purple-star.adoc}
- @exercise-link{pages/spot.adoc}
- @exercise-link{pages/average.adoc}
- @exercise-link{pages/examples-same-contracts1.adoc} 
- @exercise-link{pages/examples-same-contracts2.adoc} 
- @exercise-link{pages/match-contracts-examples1.adoc} 
- @exercise-link{pages/match-contracts-examples2.html} 
