= Exploring the Fuel Efficiency Dataset
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
</style>
++++
For this page, you'll need to the  @online-exercise{https://code.pyret.org/editor#share=1RESEiKCepBRV3_AbthDydHaq5b9BN2zy&v=4d870d2, Fuel Efficiency Starter File} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you.

@n Click "Run", and evaluate `mpg-table` in the Interactions Area. Do you know what each column means?

[cols="1a,1a", grid="none", frame="none", stripes="none"]
|===
|
- *test* - the number of the fuel efficiency test
- *model* - the car used in the test (A-F)
|
- *speed* - the speed at which the car was tested
- *mpg* - the miles-per-gallon the car achieved at that speed
|===

@n Type `A15`, `A55` and `A75` into the Interactions Area. What model is being tested in all three rows? @fitb{5em}{@ifsoln{`A`}}

@n At what speeds is this model being tested in each of the rows? @fitb{}{15, 55, and 75 miles per hour}

@n Make a scatter plot showing the relationship between `speed` and `mpg`, using `model` as your labels. What **speed** is generally the most efficient? @fitb{5em}{@ifsoln{45-55mpg}}

@n What **model** do you think is generally the _most_ fuel-efficient? @fitb{5em}{@ifsoln{B}}

@n What **model** do you think is generally the _least_ fuel-efficient? @fitb{5em}{@ifsoln{G}}

Sketch the shape of the plot below.

[.FillVerticalSpace, options="frame",stripes="none"]
!===
|
!===

@n Do you see a correlation? Describe it, in terms of linear/nonlinear and strong/weak.

@fitb{}{@ifsoln{There seems to be a somewhat strong, nonlinear correlation}}

@fitb{}{@ifsoln{It looks like a parabola that opens down, with a dimple at the top}}

@center{**Stop here! We'll continue after some discussion.**}

@n The contract for a function representing a linear model is on line 21. What is its name? @fitb{2em}{@ifsoln{f}} Domain? @fitb{5em}{@ifsoln{Number}} Range? @fitb{}{@ifsoln{Number}}

@n Fit the linear model `f` using the `fit-model` function. What is the @math{R^2} value? @fitb{}{@ifsoln{-11.794}}.


@n Change the slope and y-intercept of `f` to be the best linear model you can build. What is the @math{R^2}? @fitb{5em}{} Write the model below.

@center{
 @math{f(x) =} @fitbruby{8em}{}{slope}x + @fitbruby{8em}{}{y-intercept} @hspace{5em} @show{(code '(define (f x) (+ (* (?ANS varies) x) (?ANS varies))))}
}

@n Evaluate @show{(code '(lr-plot mpg-table "model" "speed" "mpg"))} to find the _best-possible_ linear model. What is the @math{R^2}? @fitb{5em}{@ifsoln{0.00426}}  Write the model below.

@center{
 @math{f(x) =} @fitbruby{8em}{@ifsoln{@math{-0.01017}}}{slope}x + @fitbruby{8em}{@ifsoln{29.9459}}{y-intercept} @hspace{5em} @show{(code '(define (f x) (+ (* (?ANS -0.01017) x) (?ANS 29.9459))))}
}

@fitb{}{}

@n Could we get a better fit if we used a non-linear model? In your sketch above, draw a line or curve that you think would fit better.

