= Variables

@description{Students use properties to determine when equations with and without variables are true.}

@lesson-prereqs{associative-property}

@keywords{variable, equation}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Determine if numerical expressions are equivalent.
* Determine if algebraic expressions are equivalent.

| Student-facing Lesson Goals
|

* Let's determine if algebraic expressions are equivalent.


| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links


| Key Points For The Facilitator
|
* This lesson introduces variables. The cognitive leap required when moving from operations with numbers to operations with variables can feel big! In this lesson, Circles of Evaluation can help ease the transition.
|===

== Seeing Equivalence @duration{25 minutes}

=== Overview
Students review what they have learned about computation and equivalence to lay a foundation for work with variables.

=== Launch
As we've observed, Circles and laws of arithmetic can help us understand whether an @vocab{equation} - a mathematical statement of equatility - is true or false.

Invite students to look at Equation 1, represented by these two Circles of Evaluation:

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|@show{(coe '(- (* 22 3) 4))}	| @math{=} | @show{(coe '(- (* 3 22) 4))}
|===

@lesson-instruction{
- What do you Notice? What do you Wonder?
** _Possible responses: The outer circle subtracts @math{4}, the inner circle multiplies 22 and 3. The difference between the two Circles of Evaluation is that @math{22} and @math{3} swap positions._
- Does this equation appear to be _true_ or _false_?
** _True. We see the Commutative Property of multiplication being applied when @math{22 \times 3} is transformed to @math{3 \times 22}._
** _We can also use Computation to verify that both sides evaluate to @math{62}._
}

Next, have students look at Equation 2, represented by these two Circles of Evaluation.

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|@show{(coe '(- (* 22 3) 4))}	| @math{=} | @show{(coe '(- 4 (* 22 3)))}
|===

@lesson-instruction{
- Here, what do you Notice? What do you Wonder?
** _Possible responses: The same numbers and operations are included. This time, the difference between the Circles of Evaluation is that the @math{4} moves from the beginning to the end._
- Does this equation appear to be _true_ or _false_?
** _False. This appears to be a misguided attempted to apply the Commutative Property. The Commutative Property does not hold for subtraction._
** _The equation's left side is @math{62}, but its right side is @math{-62}._
}

As students observe and share out, urge them to justify their ideas about equivalence.

=== Investigate

We have learned that computation is an effective strategy for determining whether or not two expressions are equivalent. Pretty soon we'll be looking at expressions with variables, where our computation strategy won't work as well. Let's see if we can figure out how to determine whether or not two expressions are equivalent without computation! For now, while we're still looking at expressions with numbers, we can double check our thinking with computation.

@lesson-instruction{
- Complete @printable-exercise{true-or-false.adoc} using your knowledge of the Commutative Property and the Associative Property. Try not to rely on computation! Be sure to explain your responses.
- Finally, examine the Circles of Evaluation to decide @printable-exercise{which-one-doesnt-belong.adoc} Again, try to use properties rather than computation. Be sure to explain your thinking.
}

=== Synthesize

- Summarize the Associative Property in your own words. When does it apply?
- Summarize the Commutative Property in your own words. When does it apply?
- How can we use computation to verify equivalence?
- Can you think of any expressions involving subtraction or division when the Associative Property or the Commutative Property would apply?
- What strategies did you use to locate equations that were false, or expressions that did not belong?


== Equivalence with Variables @duration{25 minutes}

=== Overview
Students examine Circles of Evaluation to determine if expressions with variables are equivalent.

=== Launch

@lesson-instruction{
- In this class, sometimes we’ll work with @vocab{variables} - symbols that stand for values we don’t know yet.
- The equation @math{c + a = r} could be true or false.
- What are some values that make the equation true?
** _Sample answer: @math{c = 5}, @math{a = 10}, @math{r = 15}_
- What are some values that make the equation false?
** _Sample answer: @math{c = 1}, @math{a = 2}, @math{r = 900}_
}

We can represent the @vocab{Commutative Property} like this:

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|@show{(coe '(* 5 g))}	| @math{=} | @show{(coe '(* g 5))}
| @math{5 \times g} 	| @math{=} | @math{g \times 5}
|===

Or like this:

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|@show{(coe '(+ 12 h))}	| @math{=} | @show{(coe '(+ h 12))}
| @math{12 + h} 			| @math{=} | @math{h + 12}
|===

It doesn't matter what values we use for @math{g} or for @math{h} - the equations above are _always_ true.

@lesson-point{
The @vocab{Commutative Property} will hold no matter what values we substitute in for @math{c} or for @math{m}.
}

The same goes for the @vocab{Associative Property}! We can represent it with variables, like this:

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|@show{(coe '(* 2 (* 3 c)))}	| @math{=} | @show{(coe '(* (* 2 3) c))}
| @math{2 \times (3 \times c)} 	| @math{=} | @math{(2 \times 3) \times c}
|===

Or like this:

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|@show{(coe '(+ 5 (+ 6 m)))}	| @math{=} | @show{(coe '(+ (+ 5 6) m))}
| @math{5 + (6 + m)} 			| @math{=} | @math{(5 + 6) + m}
|===



These examples above show us that the Commutative and Associative properties are in fact more powerful than sheer computation. We can't use computation to prove that @math{12 + h} and @math{h + 12} are equivalent  – because without knowing what @math{h} is, we can't evaluate the expression! Commutativity lets us prove that these expressions are equivalent even with variables.

=== Investigate

The activities below invite students to apply their knowledge of the Commutative and Associative Properties in equations and Circles of Evaluation _that include variables_. For some students, this cognitive leap can be a challenging one. These pages parallel those in the previous section to make this transition a bit smoother.

Students are also welcome to choose values to represent the variables if they in fact want to evaluate the expressions to confirm if they are equivalent (or not). Early finishers can substitute in numbers of their choosing to confirm that their analyses of the Circles of Evaluation are correct. The ability to make substitutions to check equivalence is an extremely valuable skill.

@lesson-instruction{
- Complete @printable-exercise{true-or-false-variables.adoc} using your knowledge of the Associative Property and the Commutative Property.
- Examine each of the Circles of Evaluation to decide @printable-exercise{which-one-doesnt-belong-variables.adoc}. Be sure to explain your thinking.
}


If students get stuck, ask: What do you notice, at first glance? What makes the Circles of Evaluation alike? What makes them different?


=== Synthesize

- Are equations with variables always true?
** _No. If we see a representation of the Associative Property or the Commutative Property, then yes. An equation such as @math{j - y = y - j} is only sometimes true. And an equation like @math{g \times 0 = 600} is never true._
- What does it mean for two expressions with variables to be equivalent?
** _When two expressions with variables are equivalent, that means that *no matter what number we substitute in,* we will still get the same result._
