= Making Connections
++++
<style>
.paragraph { margin-top: 3ex; }
</style>
++++
This workbook page references the @starter-file{row-functions}. Open that file on your computer, save a copy, and *Click Run*!

@n Find the definition for `cat-row`. What do you get back when you evaluate `cat-row` in the Interactions Area? @fitb{}{@ifsoln{_we see the row for Miaulis_}}

@n How many weeks did it take for `cat-row` to be adopted? @fitb{6em}{@ifsoln{_4_}} How many for `young-row`? @fitb{}{@ifsoln{_1_}}

@n We've defined a few rows for you: `young-row`, `fixed-row`, and `cat-row`. We'd like to you define a few more!

- Define `old-row` to be an animal from the table that is greater than 10 years old
- Define `dog-row` to be an animal from the table that is a dog
- Define `unfixed-row` to be an animal from the table whose `fixed` column is `false`

@n Scroll down in the starter file until you find the Contract, Purpose, Examples and Definition for `weeks-dot`. Discuss with your partner:

- What is the Domain of this function? @fitb{8em}{@ifsoln{_Row_}} The Range? @fitb{}{@ifsoln{_Image_}}
- The @vocab{Purpose Statement} is a way of describing the function in detail. Does the Purpose Statement make it clear what this function should do, when given a Row?
- How many examples do you see defined for this function? @fitb{}{@ifsoln{_4_}}

@n Look at the first two examples. How are they connected to the Contract and Purpose Statement?

@fitb{}{@ifsoln{_Both examples show the function consuming one argument, and the Domain has one thing in it_}}

@fitb{}{@ifsoln{_Both examples make a solid circle using the animal's `weeks` to adoption_, and the purpose says to do that}}

These examples show us exactly what should be produced for `cat-row` and `young-row` - the two Rows representing "Miaulis" and "Nori", based on their `weeks` to adoption. But these examples only tell us part of the story! Where does the computer get the number of `weeks` from?

@n Now look at the _last_ two examples. How are they connected to the first two?

@fitb{}{@ifsoln{_The numbers have been replaced by Row lookups_}}

@n Now look at the definition. How is this connected to our examples?

@fitb{}{}

@n We've learned that representations of functions have to match. Look at the Examples carefully - **there is a mistake!**, where the Examples and Definition don't quite match the Contract and Purpose. What's the mistake? @fitb{}{@ifsoln{_The purpose says purple, but all the examples and definition say green_}}

Fix the mistake in the code!
