= Contracts for Strings and Images

@description{Students encounter a useful representation of functions called a "Contract", which specifies the Name, Domain and Range of a function. Students learn how useful this representation is when trying to apply Functions in the programming environment, using image-producing functions to provide an engaging context for this exploration.}

@lesson-prereqs{simple-data-types}

@keywords{}

@add-to-lang{sqrt, sqr, string-length, string-contains?, triangle, star, circle, square, rectangle, ellipse, text, radial-star, isosceles-triangle, right-triangle, star-polygon, triangle/sas, triangle/asa}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to:
@objectives
@objective{contract-parts}
@objective{contract-use}
@objective{functions-domain-range}

| Student-facing Lesson Goals
|

- Let's write code to make images!
- Let's learn to identify the Domain and Range of a function.
- Let's use Contracts to apply functions.

| Materials
|[.materials-links]

@material-links

- @dist-link{Contracts.shtml, Contracts Pages} (a complete list of all the contracts)

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
| 
@preparation{
- There is an optional interactive Desmos activity in the lesson. If you would like to use it, decide how you will share it with students and, if you are using our Google Slides, add the appropriate link to the slide deck. _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}
}

| Key Points For The Facilitator
|
- Check frequently for understanding of @vocab{data types} and @vocab{contracts} during this lesson and throughout subsequent lessons.

|===

== Applying Functions - Reading Contracts

=== Overview
Students learn how to apply functions in @proglang, and are introduced to the notion of @vocab{Contracts}: a simple notation for keeping track of all possible input and output sets for a function.

=== Launch
@slidebreak{Launch}
In human languages, verbs _do things to nouns_. For example, I can "_throw_ a ball", or "_eat_ a sandwich". "Throw" and "Eat" are verbs, and "ball" and "sandwich" are nouns.

In programming languages, values are like nouns. You've learned about different data types in our programming language, like Number values (`42`, `-8.3`, etc), String values (`"hello!"`), and Boolean values (`true` and `false`). @ifproglang{pyret}{We already know _some_ verbs, like `+`, and `-` ... each of which _does something_ to Number values.}

@slidebreak{Launch}

In programming, most verbs are called @vocab{functions}. A function is like a machine at a factory:

1. It takes in some values (called @vocab{arguments})

2. It _does something_ to those values

3. It produces a new value

@slidebreak{Launch-DN}

Let's play with a function to get the hang of it.

@lesson-instruction{
- Log into @starter-file{editor} and click "Run".
- Then type @show{(code '(string-length "rainbow"))} into the Interactions Area and hit Enter.
- What do you think this function does? Come up with a theory about what `string-length` does, and test that theory by using it with other inputs.
}

Be sure to read any error messages you get back carefully! They might have clues to help you understand what's going on.

@slidebreak{Launch}

@QandA{

@Q{What does the expression @show{(code '(string-length "rainbow"))} evaluate to?}
@A{7}

@Q{What does the function `string-length` do?}
@A{It counts the number of characters in a string and returns the value.}

@Q{How many arguments does `string-length` expect? How do you know?}
@A{One. Giving it more than one produces an error.}

@Q{What type of argument does the function expect? How do you know?}
@A{String. Giving it a different type of data produces an error.}

@Q{What type of data did `string-length` produce?}
@A{Number}
}

@ifproglang{pyret}{
@strategy{Connecting to Function Notation}{

If your students are already familiar with function notation, Pyret mirrors it precisely, so this is a terrific opportunity to make the connection!

@teacher{
If your students are not yet familiar with function notation, no need to introduce it now... it will make more sense to introduce once they are fluent in how Pyret works, and we have an entire @lesson-link{function-notation} lesson devoted to making the connection.
}
}
}

=== Investigate
@slidebreak{Investigate}

@lesson-instruction{
With your partner, complete @printable-exercise{applying-functions.adoc}.
}

@slidebreak{Investigate}
The expressions using the `regular-polygon` function produced a value that wasn't a Number, a String, or a Boolean. In the @proglang programming language, these values are called _Images_.

@QandA{

@Q{What are the three parts of a contract?}
@A{*Name* -- the name of the function, which we type in whenever we want to use it}
@A{*Domain* -- the type(s) of data we give to the function}
@A{*Range* -- the type of data the function produces}

@Q{Why is it helpful to know the *Name* of a function?}
@A{The Name tells us what to write/type, to start using the function}

@Q{Why is it helpful to know the *Domain* of a function?}
@A{The Domain tells us _how many_ arguments the function needs, what data type each one has to be, and in what order.}

@Q{Why is it helpful to know the *Range* of a function?}
@A{The Range tells us what we should expect to _get back_ from a function.}

@Q{Where else have you heard the word "contract" used in the real world? How can you connect that meaning to contracts in programming? _Answers will vary!_}
}

@slidebreak{Investigate}

Contracts are _binding_ agreements! For example, we might sign a contract with a plumber to install a sink for $200. As long as they install the sink, we are obligated to pay them $200. If a parent promises to order pizza if their child does their chores, they'd better order that pizza if the child does those chores!

If one party breaks the contract, bad things can happen. In some programming languages, breaking a function's contract can cause the whole computer to crash, or it can result in a security hole that lets the program be hacked! In @proglang, the contracts are checked every time to use a function, so the only result is a helpful error message.

@lesson-point{
A Contract is an agreement between us and a function: if it gets what it expects, it'll give us what we expect.
}

@slidebreak{Investigate}

@lesson-instruction{
- How much can you figure out about a function just by reading its contract? With your partner, complete @printable-exercise{practicing-contracts.adoc} and @printable-exercise{matching-expressions.adoc}.
- _Note_: These pages use made-up functions that are not built into @proglang. Students who try to type them into the computer will get an error!
}

@teacher{Review students' answers for `is-beach-weather` and `cylinder`.}

@opt{We've just encountered a lot of new vocabulary! Solidify your understanding by working through @opt-printable-exercise{frayer-model.adoc, Domain and Range} and/or @opt-printable-exercise{frayer-model-2.adoc, Function and Variable} to explain these ideas in your own words, using these Frayer Model visual organizers.}

@strategy{Strategies for English Language Learners}{

MLR 2 - Collect and Display: As students explore, walk the room and record student language relating to functions, domain, range, contracts, or what they perceive from error messages.  This output can be used for a concept map, which can be updated and built upon, bridging student language with disciplinary language while increasing sense-making.
}

=== Common Misconception

@vocab{Contracts} don't tell us _specific_ inputs. They tell us the general _@vocab{data type}_ of each input that a function needs.

@lesson-point{
Contracts are general. Expressions are specific.
}

It would be silly for a function to only work on a single, specific input! For example, the Contract for `string-length` says it takes in a `String`, as opposed to a specific string like `"rainbow"`. We could use any value at all...as long as it's a String. When  _writing code_, however, we plug specific values into the expression we are coding. Contracts give us a big hint about what those specific values need to be.

@vocab{Arguments} (or "inputs") are the _values_ passed into a function. This is different from @vocab{variables}, which are the placeholders that get _replaced_ with those arguments!

=== Synthesize
@slidebreak{Synthesize}

- How would you explain Domain and Range to someone who missed today's class?
- What questions do you have about Contracts?

@pd-slide{
*Connect to the Classroom: Contracts*

- Contracts are a major pedagogical technique that is USEFUL to students as they learn to code
- Contracts help students understand domain and range, a neglected algebra topic 
- Contracts help build toward three representations of a function.

@teacher{
Contracts are the second major pedagogical technique in Bootstrap. Circles of Evaluation are the first one, and contracts are the second.

Contracts are really important because just about every single mistake kids make can be solved by looking at their contracts. The answer is always, “Check your contract.”

And that is important, because it reminds students the value of writing stuff down.

Contracts give students a concrete understanding of a math concept that is pretty abstract.

When everything is a number, it's hard to understand domain and range. Kids wonder why they need to learn them, why they matter.

Domain and range is topic that we often squeeze in the week before finals. But once we have rich data types - like strings, Booleans, and images - domain and range become more concrete.

We're building toward an understanding of three different representations for functions and we've already encountered the first one - contracts.

The goal is to get fluent in each representation. Eventually, we're going to talk about how each representation is essentially a tool you can use for solving word problems. If you know how to fit them together, you get a nice road map for attacking virtually any word problem you'll encounter.
}
}

== Bug Hunting

=== Overview
This activity focuses on what we can learn from error messages when a Contract is broken. The error messages in this environment are _specially-designed_ to be as student-friendly as possible.

Encourage students to read these messages aloud to one another, and ask them what they think the error message _means_. By explicitly drawing their attention to errors, you will be setting them up to be more independent in the future.

=== Launch
@slidebreak{Launch-DN}

Mistakes happen, especially if we're just figuring things out! Let's see how error messages in @proglang can help us to figure out the contract for a function we've never seen before.

@lesson-instruction{
- Let's complete the first section of @printable-exercise{catching-bugs.adoc} together. We'll be working in @starter-file{editor}.
- Start by typing `triangle` into the Interactions Area, and hit the "Enter" or "Return" key to run this code.
}

@QandA{
@Q{What do you get back?}
@A{@ifproglang{pyret}{`<function:triangle>`} @ifproglang{wescheme}{`#<function:triangle>`}}
}

@slidebreak{Launch}

@ifslide{
@ifproglang{pyret}{`<function:triangle>`} 
@ifproglang{wescheme}{`#<function:triangle>`}
}

This means that the computer knows about a function called `triangle`.

@lesson-instruction{
- We know that all functions will need an open parentheses and at least one input!
- We don't know the Domain, so we don't know how many inputs or what types they are. But we can always guess, and if we get it wrong we'll use the error message as a clue.
- Type @show{(code '(triangle 80))} in the Interactions Area and read the error message.
}

@slidebreak{LaunchC}

@image{images/triangle80.png, 500}

@QandA{
@Q{What _hint_ does the error message give us about how to use this function?}
@A{`triangle` has three elements in its Domain. And if we don't give it those three things we'll get an error instead of the triangle we want.}
}

@slidebreak{Launch}

@lesson-instruction{
- We know that `triangle` needs 3 arguments. But what kinds of arguments are they?
- Try different inputs to make a triangle, and see if you can figure out the Contract!}

@QandA{
@Q{What is the Contract for `triangle`?}
@A{@show{(contract 'triangle '(Number String String) "Image")} }
}

=== Investigate
@slidebreak{Investigate}

Diagnosing and fixing errors are skills that we will continue developing throughout this course.

@lesson-instruction{
Turn to the second section of @printable-exercise{catching-bugs.adoc} with your partner and try to explain the difference between syntax and contract errors in your own words.
}

@slidebreak{Investigate}

@QandA{
@Q{What is the difference between a _contract_ error and a _syntax_ error?}
@A{@vocab{syntax errors} are  typos (including missing @ifproglang{pyret}{commas,} quotation marks, parentheses, etc.) that prevent the computer from reading our code.}
@A{@vocab{contract errors} are when we don't give the function the arguments it needs - either because we give it the wrong number or type of arguments.}
}

@slidebreak{Investigate}

@lesson-instruction{
- Turn to the third section of @printable-exercise{catching-bugs.adoc}.
- Read each error message carefully, decide whether it's a contract error or a syntax error and work to decipher what it's trying to tell us.
}

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{What kinds of @vocab{syntax errors} did you find?}
@A{missing commas}
@A{a space between the function name and the open parentheses}

@Q{What kinds of @vocab{contract errors} did you find?}
@A{wrong number of arguments given}
}

== Exploring Image Functions

=== Overview

Students explore image functions to take ownership of the concept and create an artifact they can refer back to. Making images is highly motivating, and encourages students to get better at both reading error messages and persisting in catching bugs.

=== Launch
@slidebreak{Launch}

@lesson-instruction{
- Turn to @printable-exercise{image-contracts.adoc} and find `triangle`.
- You'll see that both the contract and a working expression have been recorded for you.
- Take the next 10 minutes to experiment with trying to build other shapes using the functions listed.
- As you figure out these functions, record the contracts and the code!
}

@strategy{Supporting Diverse Learners}{

- Image exploration is a low threshold / high-ceiling activity that should be engaging to all students. 
- Some students may find ALL of the contracts, but most will not! 
- When the first student in your class has successfully used the text function, give directions about which functions to prioritize with the remaining time.

@teacher{
Do not try to keep your students in lock-step. What is important here is for _everyone to have the opportunity to explore._

Later in this lesson students will be guided through more scaffolded and in-depth reflection on `isosceles-triangle`, `right-triangle`, `ellipse`, `rhombus`, `regular-polygon` and more. There are also optional pages for digging deeper into `radial-star`, `star-polygon`, `triangle-asa` and `triangle-sas`.

Students do *not* need to find all of the contracts on this page in order to complete the lesson or the following pages.

In order to make sure that all students both remain engaged and are prepared to engage in productive class discussion, when you become aware that the first student in your class has successfully used the `text` function, give your class directions about which functions to prioritize with the remaining time.
}
}

@teacher{
Make sure students at least find the contracts for `star`, `rectangle` and `text` before moving ahead.
}

=== Investigate
@slidebreak{Investigate}

@QandA{
@Q{Does having the same Domain and Range mean that two functions do the same things?}
@A{No! For instance, `square`, `star`, `triangle` and `circle` all have the same Domain and Range, yet they make very different images because they have different function Names, and each of those functions are defined to do something very different with the inputs!}

@Q{What error messages did you see?}
@A{Error messages include: too few / too many arguments given, missing parentheses, etc.}
@Q{How did you figure out what to do after seeing an error message?}
@A{Reading the error message and thinking about what the computer is trying to tell us can inform next steps.}
}

@strategy{An Option: Empowering Students as Teachers}{

This section of the lesson could be re-framed as an opportunity for students to become experts in an image-producing function and teach their classmates.

How would you orchestrate this activity?

@teacher{
It can be empowering for students to develop expertise on a topic and get to share it with their peers! This section of the lesson could be re-framed as an opportunity for students to become experts in an image-producing function and teach their classmates about it. For example, Pair 1 and pair 4 might focus on `radial-star`, pair 2 and pair 5 might focus on `polygon-star`, pair 3 and pair 6 might focus on `regular-polygon`, etc. First, each pair would explore their function. Perhaps each pair could make a poster, starter-file or slide deck about their function including: the Contract, an explanation of how it works in their own words, a few images that it can generate illustrating the range of possibilities with the expressions that generate them. Next, they might compare their thinking with another pair that focused on the same Contract. Finally, pairs could be grouped with other pairs who focused on different functions and teach each other about what they learned.
}
}

@slidebreak{Investigate}

@lesson-instruction{
- Let's do some more experimenting with some of the more complex image functions from the list we just saw! This time around we'll start with their contracts.
- Complete @printable-exercise{triangle-contracts.adoc}, @printable-exercise{using-contracts.adoc} with your partner.
- @opt{If time allows, complete @opt-printable-exercise{radial-star.adoc} with your partner.}
}

@opt{If your students are ready to dig into more complex triangles, @opt-printable-exercise{triangle-contracts-cont.adoc} will be a good challenge. Another option for further investigation is @opt-printable-exercise{star-polygon.adoc}.}

@teacher{Note: Both `star-polygon` and `radial-star` generate a wide range of really interesting shapes!}

@slidebreak{Investigate}

*If you see an error and you know the syntax is right*, ask yourself these three questions:

1. What is the function that is generating that error?

2. What is the Contract for that function?

3. Is the function getting what it needs, according to its Domain?

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{A lot of the Domains for shape functions are the same, but some are different. Why did some shape functions need more inputs than others?}
@A{Regular polygons only need one Number to define their size, but more inputs are required for:
  * shapes whose side length ratios can vary
  * shapes whose angles are not all the same
}

@Q{Was it harder to find contracts for some of the functions than others? Why?}
@Q{How was it different to code expressions for the shape functions when you started with a Contract?}
}

== Composing with Circles of Evaluation

=== Overview

Students learn to work with more than one function at once, by way of Circles of Evaluation, a visual representation of the underlying structure.

=== Launch
@slidebreak{Launch}

What if we wanted to see your name written on a diagonal?

- We know that we can use the `text` function to make an Image of your name.

@hspace{2em} @show{(contract 'text '((message String) (size Number) (color String)) "Image")}

-  @proglang also has a function called `rotate` that will rotate any Image a specified number of degrees.

@hspace{2em} @show{(contract 'rotate '(Number Image) "Image")}

_But how could the `rotate` and `text` functions work together?_

=== Investigate
@slidebreak{Investigate}

One way to organize our thoughts is to diagram what we want to do, using the Circles of Evaluation. Circles of Evaluation help us think about what we want to do, without worrying about syntax like quotation marks, parentheses, etc. They let us use all our brains for _thinking_, before we use them for _coding_.

The rules are simple:

(1) Every Circle of Evaluation must have one - and only one! - function, written at the top.

(2) The arguments of the function are written left-to-right, in the middle of the Circle.

 * Values like Numbers, String, and Booleans are still written by themselves. It’s only when we want to _use a function_ that we need to draw a nested Circle.

(3) Circles can contain other Circles!

@slidebreak{Investigate}

@lesson-instruction{
- Suppose we want to see the `text` "Diego" written in diagonal yellow letters of size 150.
- Turn to @printable-exercise{composing-coe.adoc} and complete the Notice and Wonder section.
}

@do{
(define expd '(text "Diego" 150 "yellow"))
(define exprd '(rotate 90 (text "Diego" 150 "yellow")))
}

++++
<style>
.circle2 .expression { background: aquamarine !important; }
.circle2 .expression .expression { background: white !important; }
</style>
++++

@slidebreak{Investigate}

_Circles of Evaluation let us see the structure._

[cols="^4a, ^.^1a, ^5a", grid="none", stripes="none", frame="none"]
|===

|We can start by generating the Diego image.
|
|And then use the `rotate` function to rotate it 90 degrees.

| @show{(coe expd)}
| &rarr;
| [.circle2]
@show{(coe exprd)}

| @show{(code expd)}
|
| @show{(code exprd)}

|===

@lesson-instruction{
What do you Notice? What do you Wonder?
}

@slidebreak{Investigate}

@ifslide{
[cols="^4, ^.^1,^5", grid="none", stripes="none", frame="none"]
|===

| @show{(coe expd)}  | &rarr; 	| @show{(coe exprd)}

| @show{(code expd)} | 			| @show{(code exprd)}

|===
}

To convert a Circle of Evaluation into code, we start at the outside and work our way in. After each function, we write a pair of parentheses, and then convert each argument inside the Circle.

@slidebreak{Investigate}

@lesson-instruction{
- Complete @printable-exercise{coe-to-code-scaffolded.adoc}.
- Then turn to the *Let's Rotate an image of your name!* section of @printable-exercise{composing-coe.adoc} and practice converting the Circle of Evaluation you draw into code.
}

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{What did you Notice? What did you wonder?}
@Q{There were a lot of options for how many degrees to rotate your name in order to make it diagonal! What did you choose? Why?}
@Q{What Numbers wouldn't have made your name diagonal? Why?}
@A{0, 180, 360 and other multiples of 180 would make it horizontal}
@A{90, 270 and other multiples of 90 that aren't also mulitples of 180 would make it vertical}
@Q{Why might it be useful to separate the _thinking_ and _coding_ steps? Why not just do them at the same time, all the time?}
}

== Additional Exercises
@slidebreak{Supplemental}

@opt-starter-file{images-code}

