= Exploring Linear Relationships

@description{Students investigate linear relationships in demographic data about US States, using an inquiry-based model of sense-making, hypothesizing, modeling and testing.}

@lesson-prereqs{scatter-plots}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Read and interpret real-world data, presented in a scatter plot
* Describe correlations as Strong, Moderate, or Weak
* Model linear relationships using linear functions

| Student-facing Lesson Goals
|

* Let's use Pyret to model linear relationships in data


| Materials
|[.materials-links]
@material-links

| Preparation
|
* All students should log into @starter-file{program-list} and, open the @online-exercise{https://code.pyret.org/editor#share=10bWYM4rOq_ZshtX6_M-xf-bPbfz61rd1, State Demographics Starter File}.

| Key Points For The Facilitator
|
* TBD
|===

== State Demographics @duration{15 minutes}

=== Overview
Students explore the @online-exercise{https://docs.google.com/spreadsheets/d/14fRmjAiCqGNI5Zr5kGSDjMavln7ILqhSX3N3zGd8CAU, State Demographics dataset}, and create scatter plots to search for relationships between columns. They share and discuss their findings with the class.

=== Launch

--
@right{@image{images/questions.png, 250}}

- Do states with a higher percentage of college-educated people tend to be wealthier?
- Will people commute longer for work if they make more money?
- Do states with more seniors also have veterans?
--

=== Investigate

[.lesson-instruction]
- Open the @online-exercise{https://code.pyret.org/editor#share=10bWYM4rOq_ZshtX6_M-xf-bPbfz61rd1, State Demographics Starter File}
- From the File menu, select "Save a Copy", and click "Run".
- Working in pairs or small groups, complete @printable-exercise{exploring-states.adoc}.


=== Synthesize

- Have students discuss their findings. What did they Notice? What did they Wonder?
- Invite students to share their scatter-plots with one another (copying and pasting scatter plot displays into a shared document, for example, and then labeling those displays).

== Correlations @duration{15 minutes}

=== Overview
Students identify and make use of correlations in scatter plots, learning to characterize their form as being linear, curved, or showing no clear pattern. They learn how to describe the @vocab{strength} of correlations, and that linear patterns have direction.

=== Launch
We can use a histogram or box-plot to analyze a single quantitative variable, such as `hs-or-higher` or `pop-2010` to identify a value that is **typical**, how much the values **vary**, and what kind of values are **usual or unusual**.

But those tell us nothing about the _relationship_ between those variables. In order to understand such relationships, we have to expand our view from one column to two. This goes hand-in-hand with expanding our display from a 1-dimensional histogram or box plot to a 2-dimensional scatter plot.

When we build scatter plots, we are searching for a pattern - or @vocab{correlation} between two quantitative variables. Sometimes a pattern looks like a straight line, or a curve, or a hockey stick. And sometime, there's no clear shape at all! The shape of these patterns is called @vocab{form}.

[.lesson-point]
Form indicates whether a relationship is linear, non-linear or undefined.

@right{@image{images/1b1.gif, 250}} Some patterns are @vocab{linear}, and cluster around a straight line sloping up or down.

@clear

@right{@image{images/2NL.gif, 250}} Some patterns are **non-linear**, and may look like a curve or an arc.

@clear

@right{@image{images/B.gif, 250}} And sometimes there is **no relationship** or pattern at all!

@clear
[.lesson-point]
Linear relationships have direction

For straight-line relationships, we can talk about _direction:_

@right{@image{images/C.gif, 200 }}**Positive**: the line slopes up as we look from left-to-right. Positive relationships are by far most common because of natural tendencies for variables to increase in tandem. For example, “the older the animal, the more it tends to weigh”. This is usually true for human animals, too!

@clear

@right{@image{images/A.gif, 200}}**Negative**: the line slopes _down_ as we look from left-to-right. Negative relationships can also occur. For example, “the older a child gets, the fewer new words he or she learns each day.”

@clear

NOTE: Not every shape has a direction! For example, a curve can start out sloping upwards, but then peak and slope downwards.

[.lesson-point]
Strength indicates how closely the two variables are correlated.

How well does knowing the x-value allow us to predict what the y-value will be?

@right{@image{images/A.gif, 200}}**A relationship is strong if knowing the x-value of a data point gives us a very good idea of what its y-value will be** (knowing a student's age gives us a very good idea of what grade they're in). A strong linear relationship means that the points in the scatter plot are all clustered _tightly_ around an invisible line.

@clear

@right{@image{images/1a.gif, 200}}**A relationship is weak if x tells us little about y** (a student's age doesn't tell us much about their number of siblings). A weak linear relationship means that the cloud of points is scattered very _loosely_ around the line.

@clear
=== Investigate

[.lesson-instruction]
In pairs or small groups, complete @printable-exercise{pages/identifying-form.adoc}

Review student answers. Some of the answers are not so clear-cut!

[.lesson-instruction]
@printable-exercise{pages/identifying-form-matching.adoc}.

=== Common Misconceptions
- Students often conflate strength and direction, thinking that a strong correlation _must_ be positive and a weak one _must_ be negative.
- Students may also falsely believe that there is ALWAYS a correlation between any two variables in their dataset.
- Students often believe that strength and sample size are interchangeable, leading to mistaken assumptions like "any correlation found in a million data points _must_ be strong!"


=== Synthesize

Have students discuss their answers to the @printable-exercise{pages/identifying-form-matching.adoc}, then turn to their Notice and Wonder.

- Did anyone find any linear relationships in the States dataset? Non-linear? Were there any columns that had no relationship whatsoever?
- Did anyone find any positive linear relationships in the States dataset? Negative?
- What was the strongest-looking relationship you found? The weakest?

== Making Predictions with Linear Models @duration{25 minutes}

=== Overview

The line of best fit is framed as a _predictor function_, which attempts to predict where a new point would fall on the plane based on the relationship in the data. Students define their predictors (linear functions) to find the line of best fit, using @vocab{R-squared} to determine fitness and making predictions with the result. They explore the impact that slope and and y-intercept have on fitness.

=== Launch

[.lesson-instruction]
In Pyret, make a scatter plot showing the the relationship between `college-or-higher` and `median-household-income`.

@center{@image{images/college-v-income.png}}

This scatter plot appears to show a positive, linear relationship: states with higher percentages of college graduates tend to have higher median household incomes.

[.lesson-instruction]
**Suppose the United States were to add a new state**. What median household income would predict for that state, if exactly 50% of its citizens had attended college? What about 90%? 10%

Let students discuss, and explain their thinking. If possible, mark off a single point for each of the hypothetical percentages, then connect those points to show a straight line.

When we see patterns in data, we can use those patterns to __make predictions__ based on that data. We can even draw a line to show all the possible predictions at once! These predictions represent our "best guess" at the underlying relationship in the data, as we try to model that relationship using math.

These models are just functions being graphed on top of the scatter plot, with the goal of minimizing the distance between the line and all the points on the plot. For straight-line relationships, these are _linear functions_ or "linear models". You may also have heard of linear models referred to as the @vocab{line of best fit}.

When we make a model, we want it to be the closest possible approximation of all the points. A "good fit" has most of the points very close to the line, and a "bad fit" has the points very far away.


=== Investigate

If you could draw linear model through the cloud of points in your scatter plot, where would you draw it? What would the slope and y-intercept of that model be?

[.lesson-instruction]
Complete @printable-exercise{model-college-v-income.adoc}

The `fit model` function consumes columns for our xs and yes, __as well as a function__. It draws a scatter plot and then displays the function on top of it. The `fit-model` also calculates __how well the function models the data__.

Have students discuss their answers:

* What did you Notice and Wonder, the first time you ran `fit-model`?
** (Answers will vary)
* Did you notice something called @math{R^2} on the display? What number did it show?
** -15.63
* What linear model gave you the best fit? What was the @math{R^2}, slope and y-intercept?
** (Answers will vary)
* What do you think @math{R^2} tells us about a model?
** It tells you how well the model fits the data. When @math{R^2} is higher, the model fits better.
* How did you fill in the blanks for the last question on the page?
** (Answers will vary)

@math{R^2} describes the _percentage of the variation in the y-variable that is explained by the x variable_ in our model. In other words, an @math{R^2} value of 0.20 could mean that “20% of the variation in median household income is explained by the percentage of college degrees in a state, according to our linear model”. Better models will explain a higher percentage of that variation!

If the model is a perfect, the math{R^2} value will be 1.00, meaning 100% of the @math{y}-values can be explained by the @math{x}-values. Of course in the real world, no model is perfect! The @math{R^2} value for no correlation at all is *zero*. If we just drew a horizontal predictor line in the middle of the points on the scatter plot, it would mean that we expect a median income somewhere in that range but with no connection whatsoever to the percentage of people who finish college.

[.lesson-instruction]
But what if we drew a line that wasn't even in the cloud at all? Try changing your predictor to do just that.

Modeling a correlation that's __just wrong__ is worse than modeling no correlation at all! For particularly wrong models, @math{R^2} can actually be *negative*. In other words, the model's explanation for variation is _wrong_.

[.lesson-instruction]
Pyret also has a function that will calculate the optimal linear model, called `lr-plot`. Try using this in place of `scatter-plot`, and see how close your model came to the optimal one!

When we interpret a model, we try to make sense of the slope, the axes, the @math{R^2} value, and the real data behind them. In this example, __a model built from Alaska and Alabama predicts that a 1 percent increase in college degrees is associated with a $5613 increase in median household income. Based on the @math{R^2} value of -15.63, this model isn't very good.__

Have students fix or fill in their answers to the last question, so they can use this as a reference later!

[.lesson-instruction]
- For more practice, try building linear models for other relationships you found in the data! You can use @opt-printable-exercise{model-your-own.adoc}.
- Share their findings with the class.

[.strategy-box, cols="1a", grid="none", stripes="none"]
|===

|
@span{.title}{More `lr-plot` material}

If you'd like to have students dig deeper into linear regression, there's an @lesson-link{linear-regression, entire lesson} you can use that spends more time interpreting results and writing about findings. Deeper discussion of @math{R^2} and least-squares regression may be appropriate for older students, or in a dedicated statistics class.
|===

=== Synthesize

- How could we use scatter plots and linear models to find out if taller NBA players tend to make more three-pointers?
- How could we use them to find out if wealthier people live longer?
- How could we use them to find answers to _other_ questions?
