= Fitting Quadratic Models
++++
<style>
.lesson-instruction table .autonum { font-weight: bold; }
</style>
++++
@description{}

@lesson-prereqs{quadratic2-fitting-models}

@keywords{quadratic, square, coefficient}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

-

| Student-facing Lesson Goals
|

- Let's use Pyret to model quadratic relationships in data.


| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
|
@preparation{
- Much of the exploration in this lesson hinges on a custom-built interactive Desmos activity. +
You will want to:
 * Open @starter-file{alg2-exploring-quadratics-desmos}.
 * Make a link or code to share with your students.
 * Decide how you will share the link or code with students and, if you are using our Google Slides, add the appropriate link to the slide deck.
- _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}
}

| Key Points For The Facilitator
|
-
|===

== Fitting Quadratic Models @duration{45 minutes}

=== Overview
Students work with the vertex form to fit a quadratic model for the Fuel Efficiency dataset. They extend the model-fitting techniques from the @lesson-link{linear3-fitting-models} lesson into quadratic relationships and explore the @math{f(x) = a(x − h)^2 + k} form of quadratic models using a custom Desmos slider activity.

=== Launch

We just examined a series of quadratic and linear functions that looked a lot like the ones you might find in an Algebra 2 textbook: clean and predictable. Real-world data, however, is messy! Let's return to our @starter-file{alg2-fuel-efficiency} to dig into that messiness.

@slidebreak

@lesson-instruction{
- A scatter plot of the fuel efficiency data has the familiar "rise and fall" pattern of a parabola... but there appears to be a "dip" around 40mph.
- Does that mean we shouldn't use a quadratic model for the relationship between speed and fuel efficiency? Why or why not?
  * _Have students discuss and share back with the class._
  * _If necessary, remind students that *models are - by definition - approximations of the real world*._
}

The existence of a "dip" like this is normal in real data, but it doesn't mean that the overall shape of this relationship isn't quadratic. _There's no such thing as a perfect model!_

=== Investigate
Let's *try to build the best possible quadratic model we can for our Fuel Efficiency dataset.*

One form of a quadratic model looks like this: @math{f(x) = a(x − h)^2 + k}

Let's find out what each of these coefficients mean for our model.

@teacher{Make sure you have created a link or code for your class to @starter-file{alg2-exploring-quadratics-desmos}.}

@lesson-instruction{
- Open *Exploring Quadratic Functions (Desmos)*.
- Use *Slide 1: Transforming Parabolas* to complete @printable-exercise{graphing-models.adoc}
- @opt{When you're done, continue your exploration with *Slide 2: Do horizontal shifts correspond to vertical shifts for quadratic functions?*}}

@slidebreak

==== Quadratic Coefficient (@math{a})

@QandA{
@Q{How do you make a parabola "narrower"?}
@A{Increase the value of @math{a}}
@Q{How do you make a parabola "wider"?}
@A{Decrease the value of @math{a}}
@Q{How do you know whether to parabola opens up or down?}
@A{If @math{a} is negative, it will open down. If @math{a} is positive, it will open up.}
@Q{What value of @math{a} will result in a _linear_ model?}
@A{Zero}
}

@slidebreak

The quadratic coefficient @math{a} tells us whether the parabola opens up or down, and how tightly it hugs the axis of symmetry.

@slidebreak

==== Horizontal Shift (@math{h})

@QandA{
@Q{How do you translate a parabola to the left?}
@A{Increase the value of @math{h}.}
@Q{How do you translate a parabola to the right?}
@A{Decrease the value of @math{h}.}
@Q{What does an @math{h} of zero tell us about the axis of symmetry?}
@A{It's the y-axis.}
}

@slidebreak

The horizontal shift @math{h} tells us where the axis of symmetry hits the x-axis, which means it also tells us the x-coordinate of the vertex.

==== Vertical Shift (@math{k})

@QandA{
@Q{How do you translate a parabola up and down?}
@A{Change the value of @math{k}}
@Q{How can you find the coordinates of the parabola's vertex, just by looking at the equation?}
@A{@math{h} tells us the x-coordinate, and @math{k} tells us the y-coordinate.}
@Q{We know that for linear functions it's possible to achieve any transformation that we can do with a horizontal shift with a vertical shift. Is this also true for quadratic functions? Why or Why not?}
@A{No. That phenomenon worked for linear functions because they extend indefinitely without changing direction. Because quadratic functions curve, horizontal shifts and vertical shifts don't translate to each other.}
}

@slidebreak

Like the y-intercept of a linear model, the @vocab{vertical shift} translates the parabola up and down.

@slidebreak
Now that we know how @math{a}, @math{h}, and @math{k} shape a parabola, let's work on modelling our data!

@lesson-instruction{
Return to the @starter-file{alg2-fuel-efficiency} and work through @printable-exercise{model-speed-v-mpg.adoc}.
}

@teacher{
Students may wonder why fuel efficiency is a function of the _square_ of the speed, rather than the speed itself!

Physicists have determined that the biggest factor affecting fuel efficiency is _drag:_ the effect of air slowing it down. Physicists have calculated that drag increases based on squared velocity. Additionally, a car's transmission uses more efficient gears for higher speeds (the engine can turn more slowly at higher gears), but rarely does a car have a gear optimized for speeds above 65mph. As a result efficiency falls sharply once the "highest" gear is reached, as higher speeds require the engine to run faster.
}

@strategy{Optional Activity: Guess the Model!}{

1. Divide students into teams of 2-4, and have each team come up with a *secret*, quadratic, real-world scenario, then have them write down a quadratic function that fits this scenario on a sticky note. Make sure these functions are key private within each team! (Note: students may be tempted to just make up a scenario where something rises and falls, or vice versa. Challenge them to think through why the change in the output is quadratic with respect to the change of the change in the input!)
2. On the board or some flip-chart paper, have each team draw a _scatter plot_ for which their quadratic function is best fit. They should only draw the point cloud - _not the function itself!_ Finally, have students title display to describe their real-world scenario (e.g., "percentage of people wearing diapers vs. age").
3. Have teams switch places or rotate, so that each team is in front of another team's scatter plot. Have them figure out the original function, write their best guess on a sticky note, and stick it next to the plot.
4. Have teams return to their original scatter plot, and look at the model their colleagues guessed. How close were they? What strategies did the class use to figure out the model?

- The coefficients can be constrained to make the activity easier or harder. For example, limiting these coefficients to whole numbers, positive numbers, etc.
- To extend the activity, have the teams continue rotating so that each group adds their sticky note for the best-guess model. Then do a gallery walk so that students can reflect: were the models all pretty close? All over the place? Were the guesses for one coefficient grouped more tightly than the guesses for another?
}

=== Synthesize

@QandA{
@Q{What did you figure out about how adjusting @math{a} changed the shape of the parabola?}
@A{The _sign_ of @math{a} determines whether the parabola: 
- opens up (@math{a > 0})
- opens down (@math{a < 0})
- or exists as a straight line (@math{a = 0})
}
@A{The _magnitude_ of @math{a} determines how "tight" or "steep" the parabola is, with larger magnitudes creating tighter parabolas and values closer to zero creating wider ones.}
}

@slidebreak

Our model is built from data about these 6 vehicles, evaluated at 15-75mph. What does your best model predict for the fuel efficiency of a vehicle that is _turned off_, moving at 0mph? What about a racecar moving at 200mph?

It's impossible for a car that's _turned off_ to burn gas. A racecar with a negative mpg rating would _generate_ fuel as it drives, which is also nonsense! If our model's prediction for these two extreme values is so bad, does that mean we shouldn't use the model at all?

@teacher{No - a model is only as good as the data it was based on. With lots of data between 15-75mph, the model could be very reliable between these speeds and totally _unreliable_ for speeds outside that range!}
