= Are They Commutative?

++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

In this lesson, we've explored addition, subtraction, multiplication, and division to determine whether they are commutative or not. On this page, you will explore three _Pyret_ functions to determine if they are commutative. In other words, we will investigate whether changing the order of the arguments changes the result.

@n Here is the contract for `string-contains`:

@n Write down the code for each Circle of Evaluation below.

[.FillVerticalSpace, cols="^.^1,^.^5,^.^5"]
|===
| Circle of Evaluation |@show{(coe '(* 36 10))}	| @show{(coe  '(* 10 36))}
| Code | @ifnotsoln{@math{36 \times 10 = ?}} @ifsoln{@math{36 \times 10 = 360}} | @ifnotsoln{@math{10 \times 36 = ?}} @ifsoln{@math{10 \times 36 = 360}}

|===

@n What do you notice about the Circles of Evaluation above? @fitb{}{@ifsoln{Both Circles evaluate to 360. The order of the numbers changes}}

@fitb{@ifsoln{from one Circle to the next.}}

@vspace{1ex}

These Circles of Evaluation demonstrate the Commutative Property of Multiplication! *The Commutative Property is true for any expression where all _orders_ of the numbers produce the same result.* Draw another example of the Commutative Property of Multiplication with any two numbers, below. Evaluate each Circle to confirm that they are equivalent.

@vspace{1ex}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@showsoln{(coe '(* 4 3))}	| @showsoln{(coe  '(* 3 4))}
| @ifsoln{@math{4 \times 3 = ?}} | @ifsoln{@math{3 \times 4 = ?}}
|===

@n Examine and evaluate the Circles of Evaluation below to decide if the Commutative Property holds for problems involving *division*.


[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@show{(coe '(/ 200 10))}	| @show{(coe  '(/ 10 200))}
| @ifsoln{@math{200 \div 10 = 20}} @ifnotsoln{@math{200 \div 10 = ?}}  | @ifnotsoln{@math{10 \div 200 = ?}} @ifsoln{@math{10 \div 200 = \frac{1}{20}}}
|===


Explain your response. @fitb{}{@ifsoln{No, the Commutative Property does not hold for division. I know because the first Circle evaluates to 20, }}

@fitb{}{@ifsoln{while the second Circles evaluates to @math{\frac{1}{20}}. These Circles are not equivalent after I change the groupings.}}

@vspace{1ex}

Draw another example like the one above to confirm what you observed about the Commutative Property and division.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@showsoln{(coe '(/ 30 5))}	| @showsoln{(coe  '(/ 5 30))}
| @ifsoln{@math{30 \div 5 = 6}}| @ifsoln{@math{5 \div 30 = \frac{1}{6}}}
|===


