= Commutativity and Code (Images)

++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

Open the @starter-file{comm-and-assoc}. Complete the exploration to determine if @show{(code 'beside)}, @show{(code 'above)}, and @show{(code 'overlay)} are commutative.

@n *Is @show{(code 'beside)} commutative?* Make a prediction, then translate the two Circles of Evaluation into code. Test your code in @proglang.

[.FillVerticalSpace, cols="^.^1,^.^4,^.^4"]
|===
| Circle of Evaluation |@show{(coe '(beside aqua-star orange-dot))} | @show{(coe  '(beside orange-dot aqua-star))}
| Code | @ifsoln{@show{(code '(beside aqua-star orange-dot))}} | @ifsoln{@show{(code  '(beside orange-dot aqua-star))}}

|===

@n Did the two Circles of Evaluation produce _identical_ images? Explain. @fitb{}{@ifsoln{No. For the first Circle of Evaluation,}}

@fitb{}{@ifsoln{the aqua star was on the left, but for the second Circle, it was on the right.}}

@n *Is @show{(code 'above)} commutative?* Make a prediction, then draw a second Circle of Evaluation that changes the order of the arguments. Translate both Circles into code and test it out in @proglang.

[.FillVerticalSpace, cols="^.^1,^.^4,^.^4"]
|===
| Circle of Evaluation |@show{(coe '(above  purple-square orange-dot))} | @ifsoln{@show{(coe  '(above orange-dot purple-square))}}
| Code | @ifsoln{@show{(code '(above purple-square orange-dot))}} | @ifsoln{@show{(code '(above orange-dot purple-sqare))}}

|===

@n Did the two Circles of Evaluation produce _identical_ images? Explain. @fitb{}{@ifsoln{No. For the first Circle of Evaluation,}}

@fitb{}{@ifsoln{the purple square was on the top, but for the second Circle, it was on the bottom.}}

@n *Is @show{(code 'overlay)} commutative?* @show{(code 'overlay)} takes in two images and produces an image. Draw two Circles of Evaluation that will help you decide if @show{(code 'overlay)} is commutative. Translate your Circles into code and test the code.

[.FillVerticalSpace, cols="^.^1,^.^4,^.^4"]
|===
| Circle of Evaluation ||
| Code | |

|===

@n Did the two Circles of Evaluation produce _identical_ images? Explain. @fitb{}{@ifsoln{No. For the first Circle of Evaluation...}}

@fitb{}{@ifsoln{Responses will vary.}}



@n Were any of the above functions commutative? Explain. @fitb{}{@ifsoln{No. They all produced a different result}}

@fitb{}{@ifsoln{when we changed the order of the arguments.}}

@fitb{}{}

