= Discover the Commutative Property

++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

@n Analyze and evaluate the two Circles below:

@vspace{1ex}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@show{(coe '(* 36 10))}	| @show{(coe  '(* 10 36))}
| @math{36 \times 10 = ?} | @math{10 \times 36 = ?}
|===

What do you notice? @fitb{}{@ifsoln{Both Circles evaluate to 360. The order of the numbers changes from one Circle to the next.}}

@fitb{}

@fitb{}

@vspace{1ex}

These Circles represent the Commutative Property of Multiplication! *The Commutative Property is true for any expression where all _orders_ of the numbers produce the same result.* Draw another example of the Commutative Property of Multiplication with any two numbers, below. Evaluate each Circle to confirm that they are equivalent.

@vspace{1ex}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@showsoln{(coe '(* 4 3))}	| @showsoln{(coe  '(* 3 4))}
| @ifsoln{@math{4 \times 3 = ?}} | @ifsoln{@math{3 \times 4 = ?}}
|===



@n Analyze and evaluate the Circles below to decide if the Commutative Property holds for problems involving *division*.

@vspace{1ex}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@show{(coe '(/ 200 10))}	| @show{(coe  '(/ 10 200))}
| @math{200 \div 10 = ?}  | @math{10 \div 200 = ?}
|===


Explain your response. @fitb{}{@ifsoln{No, the Commutative Property does not hold for division. I know because the first Circle evaluates to 20, }}

@fitb{}{@ifsoln{while the second Circles evaluates to @math{\frac{1}{20}}. These Circles are not equivalent after I change the groupings.}}

@fitb{}

@vspace{1ex}

Draw another example like the one above to confirm what you observed about the Commutative Property and division.

@vspace{1ex}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@showsoln{(coe '(/ 30 5))}	| @showsoln{(coe  '(/ 5 30))}
| @ifsoln{@math{30 \div 5 = 6}}| @ifsoln{@math{5 \div 30 = /fract{1}{6}}}
|===


