= Discover the Commutative Property - Part 2

++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

@n Analyze and evaluate the Circles below to decide if the Commutative Property holds for problems involving *addition*.

@vspace{1ex}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@show{(coe '(+ (+ 9 2) 8))}	| @show{(coe  '(+ (+ 8 2) 9))}
| @math{9 + 2 + 8 = ?} | @math{8 + 2 + 9 = ?}
|===

What do you notice? @fitb{}{@ifsoln{Both Circles evaluate to 19. In the first Circle, we add 9 and 2 first, while in the second Circle,}}

@fitb{}{@ifsoln{we add 8 and 2 first.}}

@fitb{}

@vspace{1ex}

These Circles represent the Commutative Property of Addition! Draw another example of the Commutative Property of Addition with any three numbers, below. Evaluate each Circle to confirm that they are equivalent.

@vspace{1ex}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@showsoln{(coe '(+ (+ 14 9) 2))}	| @showsoln{(coe  '(+ 2 (+ 9 14)))}
| @ifsoln{@math{14 + 9 + 2 = 25}} | @ifsoln{@math{14 + 9 + 2 = 25}}
|===



@n Analyze and evaluate the Circles below to decide if the Commutative Property holds for problems involving *subtraction*.

@vspace{1ex}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@show{(coe '(- 50 4))}	| @show{(coe  '(- 4 50))}
| @math{50 - 4 = ?}  | @math{4 - 50 = ?}
|===


Explain your response. @fitb{}{@ifsoln{No, the Commutative Property does not hold for subtraction. I know because the first Circle evaluates to 46, }}

@fitb{}{@ifsoln{while the second Circles evaluates to a negative value (-46). These Circles are not equivalent after I change the order.}}

@fitb{}

@vspace{1ex}

Draw another example like the one above to confirm what you observed about the Commutative Property and subtraction. Evaluate each Circle to confirm your response.

@vspace{1ex}

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
|@showsoln{(coe '(- 40 2))}	| @showsoln{(coe  '(- 2 40))}
| @ifsoln{@math{40 - 2 = 38}}| @ifsoln{@math{40 - 2 = -38}}
|===
