= Computing Needs All Voices

@description{Students learn about a diverse group of programmers through a short film and a gallery walk of our Pioneers in Computing and Mathematics poster series, then consider the problem solving advantages that diverse teams foster.}

[@lesson-intro-table]
|===
@lesson-prereqs{}

| Lesson Goals
| Students will understand that:

* There are programmers of wide-ranging racial, ethnic, gender and sexual identities.
* Programming is creative and collaborative.
* Programming is useful in a wide range of fields.
* People who wrote the sophisticated programs we use every day started out writing simple programs.
* There are lots of programming jobs, but not enough programmers to fill them.
* Teams benefit from diversity.

| Student-Facing Lesson Goals
|
* Let's learn about some Pioneers in Computing and Mathematics and what they contributed.
* Let's explore some concrete ways in which teams benefit from diversity.
* Let's learn about how programming impacts our lives and things that we care about.

| Materials
|[.materials-links]

* @link{pages/computing-pioneers.html, Pioneers in Computing and Mathematics}

@material-links

| Preparation
|
* If a gallery walk works for your students, print a set of Pioneers in Computing and Mathematics Posters. If this isn't feasible for your class, figure out what structure you will use to engage students with  @printable-exercise{pages/computing-pioneers.adoc, these pioneers}.
* Choose a gentle timer sound on your phone, to facilitate transitions while students are sharing personal experiences.
* Make a copy of the google form so that you can examine your class's data. _If you are using the slide deck, be sure to add the link to your copy of the form to the appropriate slide._

|===

== Who writes the Code? @duration{35 minutes}

=== Overview
Students watch a 5-minute video, hearing from programmers about how they got their start and seeing some of their projects and work environments. Then, students engage in a gallery walk of computing pioneers. Finally, students reflect on how what they've seen connects to their own identify and also helps them to understand the broader world.

@centered-image{images/pioneers-header3.png}

=== Launch
Explain to students that they are going to watch a short clip and then share what they noticed and wondered. They may either record their thougths as they watch, or do so for a few minutes after the film is over.

[.lesson-instruction]
- Let's view @online-exercise{https://www.youtube.com/watch?v=nKIu9yen5nc, What Most Schools Don't Teach}.
- Take a few minutes to write down what you @printable-exercise{NoticeAndWonder.adoc}. "Notice"s should be statements about what stood out to you, or what you remembered - not questions!
- If the video sparked a question for you, write it under the "Wonder" section.

Have students share their Notices and Wonders.

@strategy{
@span{.title}{Pedagogy Note: Notice and Wonder!}

This pedagogy is a @link{https://www.nctm.org/noticeandwonder/, widely-used best practice in Math-Ed}, and is used throughout this course. In the "Notice" phase, students are asked to crowd-source their observations. No observation is too small or too silly! By listening to other students' observations, students may find themselves taking a closer look. The "Wonder" phase involves students raising questions, but they must also explain the context for those questions. Sharon Hessney (moderator for the NYTimes excellent @link{https://www.nytimes.com/column/whats-going-on-in-this-graph, What's Going On in This Graph?} activity) sometimes calls this "what do you wonder...and *why*?". Both of these phases should be done in groups or as a whole class, with adequate time given to each.
}

=== Investigate
Assuming that you have printed and hung posters of @link{pages/computing-pioneers.html, Pioneers in Computing and Mathematics} for a gallery walk:

[.lesson-instruction]
* There are posters of Mathematicians and Programmers hanging around the room.
* When I ask you to get up, you will head to the walls and have some time to move clockwise around the room to read them.
* Please spread out so that you can read the posters you are looking at.

Depending on your class and your timing, you may want to consider ending the gallery walk by having each student find a pioneer to present to the class.

If you aren't doing a gallery walk, decide on another format for engaging students with these pioneers.

=== Synthesize

[.lesson-instruction]
Return to your seats and spend 5 minutes reflecting on the posters and the video by completing @printable-exercise{windows-mirrors.adoc}.

The next section of this lesson is an opportunity for students to learn and grow from sharing with each other. If you haven't yet established a classroom culture in which students will feel safe sharing their lived experiences with a partner, you may want to facilitate a whole group discussion instead in which students can opt in or out of sharing their reflections.

[.lesson-instruction]
--
Now that you've had a chance to write, we are going to take turns sharing your mirrors and windows with your partners. __This activity is all about holding space for someone else to share!__ Each of you will get a minute to share your mirrors, then a minute to share your windows. When it's your turn to speak, share what feels comfortable. You do not have to read what you wrote. If it's your partner's turn and they finish before it's time to switch, leave space for them to think, and decide if they have anything else to add. I will let you know when it's time to switch. You will have time to discuss after you've both had two turns to speak. Decide which of you will go first and raise your hand when you're ready.

* The first speaker now has one minute to share their mirrors.
* It's time to switch. The second speaker now has one minute to share their mirrors.
* It's time to switch. The first speaker now has one minute to share their windows.
* It's time to switch. The second partner now has one minute to share their windows.
* Thank you for taking turns listening, and holding space for one another. You now have 3 minutes to discuss and ask each other followup questions.
--

@strategy{
@span{.title}{Pedagogy Note: Windows and Mirrors!}

@link{https://nationalseedproject.org/itemid-fix/entry/curriculum-as-window-and-mirror?highlight=WyJ3aW5kb3dzIiwibWlycm9ycyJd, Curriculum as Window and Mirror} was first published by Emily Style, founding co-director of @link{https://nationalseedproject.org/, the National SEED Project (Seeking Educational Equity and Diversity)} in 1988 and remains a key piece that informs the work of SEED leaders to create reflective and inclusive classrooms and communities. This lesson only begins to tap into the power of the practice.
}

== Advantages of Diverse Teams in Tech @duration{20minutes}

=== Overview

Students will complete a 30-second survey about how ketchup is used in their home, read a short article about diversity in tech, that uses ketchup placement in the kitchen as a metaphor for describing the advantages of diversity on a team when it comes to problem solving, reflect on the article, and then Notice and Wonder about the results of the class' ketchup survey.

=== Launch
*Be sure to copy the google form below before sharing it, so that you can look at your data as a class!*

[.lesson-instruction]
Complete this two-minute @online-exercise{https://docs.google.com/forms/d/16tCvWZmTvHrztrVvQeInusQovwoK61WLsg3OTV0VIwg/copy, Ketchup Use Survey}.

=== Investigate

[.lesson-instruction]
- Read @online-exercise{https://www.latimes.com/business/technology/la-diversity-right-thing-snap-story.html, LA Times Perspective: A solution to tech’s lingering diversity problem? Try thinking about ketchup}.
- After you've read the brief article, complete @printable-exercise{advantages-of-diverse-teams.adoc}.

=== Synthesize

Facilitate a conversation with your students about the article. _You may or may not choose to use the questions they just answered as your framing._

* The author argues that tech companies with diverse teams have an advantage. Why?
* What suggestions did the article offer for tech companies looking to diversify their teams?
* What is one thing of interest to you in the author’s bio?
* Think of a time when you had an idea that felt out of the box. Did you share your idea? Why or why not?
* Can you think of a time when someone else had a strategy or idea that you would never have thought of, but was interesting to you and/or pushed your thinking to a new level?
* Based on your experience of exceptions to main stream assumptions, propose another pair of questions that could be used in place of "Where do you keep your ketchup?" and "What would you reach for instead?".

Then, display the results of the google form (as pie charts) and facilitate a discussion. What do students Notice? What do they Wonder?
