[.beta]
= Regression Models

@description{Students return to the dataset, this time thinking about the factors that predict how long it will take for an animal to be adopted. This leads to an exploration of Linear Regression, then Multiple Regression. Finally, they learn about the world’s first self-driving car, and use multiple regression to control the steering wheel of a virtual car using AI.}

@lesson-prereqs{data-driven-algorithms, fitting-models}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives

| Student-facing Lesson Goals
|

- Let's use line-of-best-fit to predict how long it will take for an animal to be adopted!
- Let's learn about the functioning of the very first self-driving car!
- Let's use line-of-best-fit to predict how a self-driving car should steer!

| Materials
|[.materials-links]
@material-links

| Preparation
| - @opt{If you think your students will want the chance to actually see the first self-driving car in action, you can share @link{https://www.youtube.com/watch?v=ntIczNQKfjQ, "this two-minute video"} from the Carnegie Mellon University Robotics Institute.}

|===

== Linear Regression

=== Overview
What factors determine how many `weeks` an animal takes to be adopted? Students are introduced to the _concept_ of @vocab{linear regression}, and learn how to interpret the @vocab{slope} and @vocab{y-intercept} of @vocab{predictor functions}.

=== Launch
@slidebreak{Launch}
In @lesson-link{fitting-models}, we you learned that a relationship between two variables will show up as a point cloud in a 2d scatter plot, and that this relationship can be described by a @vocab{model}.

@lesson-point{Most models are wrong. Some are _useful_.}

- A model for a 2d relationship is a @vocab{line of best fit}
- When it comes data from the real world, most models are @vocab{lossy}, meaning the line won't _perfectly_ fit the points. It will usually be at least a little "wrong".
- If the model is a good fit, however, the information lost is minimal and the predictions we make from the model can be useful.

Can we use `pounds` and `age` in our animals dataset to _predict_ how long it takes for an animal to be adopted?

@slidebreak{Launch}
@lesson-instruction{
- Open the @starter-file{animals} in Pyret, and click "Run".
- Evaluate `animals-table` to see the data. Which animal is the oldest? Which is the heaviest? Which took the most weeks to be adopted?
- Make a scatter plot, using `name` as the label, `age` as the explanatory variable and `weeks` as the response. _Can you find Kujo on this plot?_
- Make another scatter plot, this time using `pounds` as the explanatory variable. _Find Kujo on this plot._
}


@slidebreak{LaunchC}
[cols="1a,1a", grid="none", frame="none"]
|===
| @image{images/pounds-v-weeks.png, 400}
| @image{images/age-v-weeks.png, 400}
|===

@QandA{
@Q{Based on these scatter plots, how does the *size* of an animal impact how long it takes to find a home?}
@A{Heavier animals *tend to* take longer to be adopted.}

@Q{How does the *age* of an animal impact how long it takes to find a home?}
@A{Older animals *tend to* take longer to be adopted.}

@Q{Do older and larger animals _always_ take more time to get adopted? Less time?}
@A{Neither - it's a general trend for them to take longer, but that doesn't mean every old/large animal takes longer than every small/young one!}
}

Can we be more precise actually _predict_ how long it will take an animal to be adopted, based on these factors? And which one would give us a better prediction?

=== Investigate
@slidebreak{Investigate-DN}

As you already learned about @lesson-link{fitting-models}, our goal is to fit a line to each of these scatter plots, minimizing the error as much as possible.

@center{@big{@math{weeks(age)=(m_{age} \times age) + b}}}

- The function @math{weeks} has one variable named @math{age}, which explains a _portion_ of the adoption time (there might other factors besides age!)
- The portion explained by @math{age} is the slope @math{m_{age}} in our equation, with our y-intercept @math{b} representing the predicted value if @math{age = 0}

@lesson-instruction{
- Make sure you have made your two scatter plots in @starter-file{animals}
- Open Desmos graphs for *both* @online-exercise{https://www.desmos.com/3d/glgrgcs4bp, Age v. Weeks}, and @online-exercise{https://www.desmos.com/3d/ip4ucm56mx, Age v. Pounds}
- Use Pyret and these Desmos graphs to complete @printable-exercise{predicting-weeks-from-1.adoc}.
}

@teacher{
- Note: reloading the page will reset the graph to its original configuration!
- Have students share their observations about the 3d plot! Did they notice that all the _non-purple_ dots were squished into one "face of the cube"?
- Did they notice that when viewing the `pounds` or `age` of the axis "head on", the 3d points perfectly overlapped the other set of 2d points?
}

@slidebreak{InvestigateR}
--
@right{@image{images/desmos3d.png, 300}}

- Desmos uses a cube outline, to help us orient in space
- Each of our graphs started with one axis being viewed "head on", so that all we could see was the flat, "far side" of the cube
- Each face of a cube is 2-dimensional, and in both cases we found ourselves looking at the original, 2d scatter plots of `age` v. `weeks` and `pounds` v. `weeks`
- When we work with our normal (2d) scatter plots, it's easy to forget that there's other data that we are choosing to ignore!
- But when we turn on the orange dots, we can rotate the cube to see that our 2d scatter plots are each "shadows" of the 3d data.
	- One shadow is projected onto the "weeks-pounds" plane
	- The other is projected onto the "age-pounds" plane
--


@slidebreak{InvestigateR}
@ifslide{@right{@image{images/desmos3d-pounds-fit.png, 300}}}

- What did you get for the slope of our __age__-based predictor, @math{m_{age}}? The y-intercept?
- What did you get for the slope of our __pounds__-based predictor, @math{m_{age}}?
- How well did these models fit in Pyret? What was your @math{S} value?



@slidebreak{InvestigateR}
@right{@image{images/lr-pounds-v-weeks.png, 300}}
Data scientists, statisticians, and machine learning engineers use a statistical method called @vocab{linear regression} to pinpoint linear relationships in a dataset. Linear regression is the math behind the @vocab{line of best fit}, which allows us to make predictions based on our data.

- In Machine Learning, the act of shrinking this data into a function is called @vocab{training}
- Regression finds patterns between a set of inputs and an _already-known_, target output

Think of each row in the animals dataset as a flash card, with `pounds` or `age` written on the front and `weeks` on the back. The computer is learning to predict the answer by identifying the patterns in our data. This form of learning -- where we already know the target values on -- is called @vocab{supervised learning}.

@slidebreak{Investigate-DN}

@lesson-point{
In supervised learning, computers train on sample input-output pairs tagged by a human, and learns a function that maps from input to output.
}

Pyret has a function that does this learning for us, and its contract is the *same* as the contract for `scatter-plot`:

@show{(contract "lr-plot" '((table-name Table)  (label-col String) (x-col String) (y-col String)) "Image")}

Now we want Pyret to "learn" a function with the *best possible* values for @math{m} and @math{b}:

@center{@big{@math{weeks(age)=(m_{age} \times age) + b}}}

@lesson-instruction{
- Make sure you have @starter-file{animals} open.
- Use Pyret to complete the *first two sections* @printable-exercise{supervised-learning-regression.adoc}.
- Be ready to share your thinking!
}

@teacher{Debrief student answers, especially the sense-making involved in interpreting regression results!}

@slidebreak{Investigate-DN}

Pyret has a several tools for doing linear regression, all with the same Domain:

@show{(contract "lr-coeffs" '((table-name Table)  (label-col String) (x-col String) (y-col String)) "Table"
"produces a table showing all coefficients (including the intercept!) of our model"
)}
@show{(contract "lr-code" '((table-name Table)  (label-col String) (x-col String) (y-col String)) "Code"
"produces code that you can copy and paste into the Definitions Area, to define the \"trained\" model")}

@lesson-instruction{
- Try these three functions out, by completing @printable-exercise{supervised-learning-regression.adoc}.
}

@slidebreak{InvestigateR}
@ifslide{@right{@image{images/lr-pounds-v-weeks.png, 300}}}
@QandA{
@Q{What is the code for a row-consuming version of our `age` predictor?}
@A{`weeks(r) = (0.79 * r["age"]) + 2.3`}

@Q{What does the slope (the coefficient for `age`) tell us about what our predictor has _learned_?}
@A{An extra year of age predicts roughly 0.79 extra weeks at the shelter (about 5.5 days longer)}

@Q{What is the code for a row-consuming version of our `pounds` predictor?}
@A{`weeks(r) = (0.08 * r["pounds"]) + 2.5`}

@Q{What does the slope (the coefficient for `pounds`) tell us about what our predictor has _learned_?}
@A{An extra pound predicts roughly 0.08 extra weeks at the shelter (about half a day longer)}

@Q{Based on these slopes, which has the bigger _impact_ on adoption time: `pounds` or `age?`}
@A{`age`}

@Q{Which predictor _fits better_ (has a lower @math{S})?}
@A{`pounds`}

@Q{How could we possibly build a better predictor?}
@A{Split the dataset by species, and fit each one separately!}
@A{Somehow use `pounds` _and_ `age` together!}
}

@teacher{Make sure your students have changed their `age-predictor` and `pounds-predictor` functions in Pyret, to consume Rows instead of Numbers!}

=== Common Misconceptions
- *Don't forget to look at sample size!* A linear regression plot with an @math{r}-value of 0.999 is strong...but that's useless if it's a sample of just three data points!


=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{Should we assume that either of our predictors will be generally accurate for another animal shelter?}
@A{No - this is only a handful of animals! Just not enough data to make a general claim. }
@A{No - there's no guarantee that another shelter even has the same species!}
@A{No - even with the same species, another shelter might be visited by humans with very different needs/interests, which could change the role that `age` and `weight` play in adoption time}

@Q{Suppose we did this same supervised learning on a dataset of millions of animals, from shelters all over the world. Could we assume those predictors}

@Q{Why does it only make sense to use predictor functions for values that fall _within the range of the dataset_?}
@A{Because our function describes a pattern observed within that particular range. Lots of observable patterns do not continue outside of a certain range... for example, babies are supposed to triple in weight in their first year... but grownups definitely shouldn't!
}
@A{If students have completed @lesson-link{decision-trees-evaluating}, you can connect this back to trusting a classifier only on inputs that are similar to what it was trained on.}
}

== Multiple Regression

=== Overview
Students extend their understanding of linear regression in 2 dimensions, moving into multiple regression in 3 dimensions. They see the improvement to the model fit, and interpret the coefficients of a multiple-regression result.

=== Launch
@slidebreak{LaunchR}
@right{@image{images/lr-pounds-v-weeks.png, 300}}

@math{weeks(age)=(0.79 \times age) + 2.3} +
`fun weeks(r): (0.79 * r["age"]) + 2.3 end`

This function (written in both math and Pyret notation) is our regression line, which we can draw on a 2 dimensional (x,y) scatter plot.

@slidebreak{Launch}

But what if we wanted to use `pounds` _and_ `age` on our flashcards, and train the computer to predict `weeks` based on the value of *both* variables?

=== Investigate
@slidebreak{InvestigateR}
@right{@image{images/plane-of-best-fit.png, 300}}
Nothing says we can't use multiple variables to make our predictions, or that we have to live in only 2 dimensions! Now we want Pyret to "learn" a function like this, with the best possible values for @math{A}, @math{B}, and @math{C}:

@center{@math{weeks(age, pounds)=(m_{age} \times age) + (m{pounds} \times pounds) + b}}

- `age` and `weeks` are _both inputs_ to the function, and each contributes to a _portion_ of the adoption time
- These portions are @math{m_{age}} and @math{m_{pounds}}, with our xy-intercept @math{b} representing the predicted value if `age` and `pounds` are _both_ zero

- TODO: make this page, with using (1) `mr-code`, interpreting output, (2) using `predict-col`, (3) adding "legs" as a column

@lesson-instruction{
- Open @online-exercise{https://www.desmos.com/3d/omnchml87a, this Desmos graph} and explore!
- Use this graph to complete the first section on @printable-exercise{mr-age-pounds.adoc}.
- Use Pyret to complete @printable-exercise{mr-age-pounds.adoc}.
- Be ready to share your thinking!
}


@slidebreak{InvestigateR}
@ifslide{@right{@image{images/plane-of-best-fit.png, 300}}}
What would this function look like?

In *Function Notation*: +
@math{weeks(age, pounds)=(0.79 \times age) + (0.08 \times pounds) + 2.3}

In *Pyret Notation*: +
`fun weeks(r): (0.79 * r["age"]) + (0.08 * r["pounds"]) + 2.3 end`

We're already consuming the entire row `r`, so we already have access to `age` and `pounds`.

=== Synthesize
@slidebreak{Synthesize}

TODO - put stuff here!

== Self-Driving Cars @duration{15 minutes}

@objective{ai-supervision}
@objective{car-function}


=== Overview
Students learn about ALVINN (Autonomous Land Vehicle in a Neural Network) as an example of supervised machine learning, then explore a driving simulator and use multiple regression to train a model to drive for them.

=== Launch
@slidebreak{LaunchR}
--
@right{@image{images/self-driving-car.jpg}}

Self-driving cars feel like the future has really arrived! Many people think they are one of the strongest examples of "AI" really thinking, instead of just "following an algorithm". What do _you_ think?

@teacher{Give students time to discuss. Remind them about the AI Effect, and how people also felt when the first spell-checkers were developed!}
--

@slidebreak{Launch}
Self-driving cards work via a lot of inputs (sensors, cameras, etc) and a lot of outputs (how much to accelerate, brake, and steer). Steering, for example, is incredibly difficult! A car needs to think about:

- Whether the road ahead bends to the left or right, and how sharply
- How far the car is from the center of the lane
- Whether the car is in-line with the lane, or heading towards one side
- Obstacles and traffoc lights that could be in the way
- And lots more!

We're going to explore how @vocab{supervised learning} -- regression, specifically -- allows cars to "know where they're going".

@slidebreak{LaunchR}

Meet ALVINN!

@center{@image{images/navlab.png, 400}} 

ALVINN (short for Autonomous Land Vehicle in a Neural Network) was developed in 1989 by a team of computer scientists at Carnegie Mellon University. ALVINN is the forebear of today's self-driving cars: a retrofitted Army ambulance equipped with sensors, computers, and actuators (the part of a machine that allows movement). ALVINN had about one-tenth of the processing power of an Apple Watch -- but was able to safely drive on a very limited course at 70 miles per hour by the early 1990s! How did it happen?  

@slidebreak{Launch}

As with all machine learning, ALVINN required @vocab{training}.

The goal of that training? Learning how to steer.

Here's what ALVINN's training entailed:

(1) A person drove the vehicle while a front-facing video camera recorded the road.

- In the context of @vocab{supervised learning}, the human driver is often referred to as the supervisor. 
- The supervisor demonstrates the learning process.
- The input-output pairs form the @vocab{training corpus}.

(2) Every two seconds, ALVINN...

- digitized an image of the road ahead
- recorded the steering direction chosen by the driver

@slidebreak{Launch}

(3) ALVINN's training data can be represented as an input-output table, with training images (reduced in resolution to 30x32 pixels) and obstacle distances as inputs, and the associated corresponding "correct" steering angles as outputs.

@indented{
[cols="^.^1,^.^1", stripes="none", options="header"]
|===
| road image                      	| obstacle distance (ft)| output data
| @image{images/road1.png, 100} 	|		21				|   0.02º
| @image{images/road2.png, 100} 	|		49				| -95.20º
| @image{images/road3.png, 100} 	|		37				| 135.43º
|===

@teacher{
Note: These images were selected for illustrative purposes. The 30x32 pixel images produced by ALVINN were of much lower quality!
}
}

@slidebreak{Launch}

(4) Using the set of inputs and outputs, ALVINN generates a @vocab{function} for predicting steering angles from the images and obstacle distances, which we can summarize using contract notation.

@indented{
@show{(contract 'steer '((road-image Image)) "Number")}
}

@lesson-point{
In the `steer` function, the Image and Distance are the @vocab{explanatory variables} and the steering angle is the @vocab{response variable}.
}

@slidebreak{Launch}

(5) After training is complete, a human can push ALVINN's "run" switch and the vehicle will begin driving!  As ALVINN drives, it produces steering angles it learned from the human driver (who demonstrated the steering angle at each segment of the road), along with a numeric of "confidence score" in the angle provided.

@teacher{
If you want your students to see ALVINN in action, now is a good time to view @link{https://www.youtube.com/watch?v=ntIczNQKfjQ, "this brief two-minute video"}.
}

@slidebreak{Launch}

@QandA{
@Q{What information does ALVINN process before producing a steering angle?}
@A{ALVINN instantaneously processes the image of the road in front of it in order to produce a steering angle.}

@Q{When humans make decisions about which way to steer, we are working with a lot of other information besides the image of the road in the moment. What examples can you come up with?}

@A{We can use maps to give us a sense of what the road might do before we can see it.}
@A{If a road is curving, we can predict that it will continue to curve.}
@A{We know that roads don't curve beyond a certain degree--and if they do, we can expect to see a warning sign ahead of time.}
@A{We can look at the cars in front of us to better understand how we should steer.}
@A{If we know that we're going to be taking a left turn, we might switch lanes and slow down ahead of time.}
}

@strategy{Computers aren't people!}{

In conversations about AI, computers often get anthropomorphized (given human-like traits) when they are not in fact human. This anthropomorphization of AI is a slippery slope that can block students from understanding the mechanics of machine learning.

We urge you to avoid referring to ALVINN as "him" or "he".

Many students will suspect that ALVINN has thoughts and feelings of its own, a misconception that is important to correct.

A machine's "confidence" is very different from a human's confidence. When you discuss ALVINN's "confidence", highlight that this score is a numeric value, which is the result of *mathematical computation*. All machine learning relies on data, functions, and computation.
}

@slidebreak{Launch}

In discovering the details of ALVINN's @vocab{supervised learning}, you may have noticed three big events:

- Demonstration of the learning process
- Function abstraction -- the machine learning algorithm finds a function that generalizes (hopefully well!) to new, unseen data
- Use the function! Apply it on new data.

As you explore other examples of @vocab{supervised learning} in this curriculum, you will notice that -- regardless of the context -- all three phases occur. 

=== Investigate
@slidebreak{Investigate}

Let's use the same kind of @vocab{supervised learning} algorithm we used to predict animals' adoption time -- and which ALVINN used to steer! -- to build a model that knows how to complete a driving simulator.

@lesson-instruction{
- Open @starter-file{self-driving}, and click "Run".
- Use this file to complete @printable-exercise{self-driving-car.adoc}
}

@slidebreak{Investigate}

Let's reflect on what we know about @vocab{supervised learning}, ALVINN, and its training.

@lesson-instruction{
With a partner, complete @printable-exercise{self-driving-car-reflection.adoc}.
}

@teacher{Review students' responses, allowing time for discussion, questions, and disagreement.}

@slidebreak{Investigate}

While responding to the questions on the worksheet, you hopefully arrived at a few conclusions about ALVINN:

- At the beginning of training, ALVINN's guesses about the best steering direction are not good.
- As ALVINN receives more examples, it becomes better at predicting and can imitate the steering reactions of a human driver.
- Training on one surface does not help ALVINN on any other surface! Failure to repeat the same training for a variety of road types (two-lane, four-lane, intersections, covered with leaves, covered with snow, etc.) would lead to bad outcomes.

=== Synthesize
@slidebreak{Synthesize}
Regression is a form of @vocab{supervised learning} that trains models to predict _quantitative_ outcomes:

- Number of weeks to adopt a pet, given the age and weight
- Number of degrees to turn the wheel, given the speed, road curvature, etc.

Each of these relies on a training dataset with a number of input columns and a target column. For each of the following examples, what do you think the input columns are?

- The rate you pay for car insurance
- The price of gas at the pump
- The predicted temperature in tomorrow's weather report

@teacher{Give students a chance to discuss as a class.}

@slidebreak{Synthesize}

@QandA{

@Q{What is supervised machine learning, and how is ALVINN an example it?}
@A{In supervised machine learning, the computer trains on example input-output pairs tagged by a human, and learns a function that maps from input to output. ALVINN is an example of supervised machine learning because a human provided the correct steering angles (_demonstration_), allowing ALVINN to produce a predictor function (_function abstraction_).}
}