= Linear Relationships

A relationship between two variables is *linear* if one changes at a _constant rate_ relative to the other. Here are a few examples of linear relationships:

- A car driving at 40mph will travel exactly 40 miles for each additional hour
- A lemonade stand that sells cups of lemonade for $0.75/ea will charge exactly $0.75 for each additional glass

Linear relationships can also start with an _initial value_:

- A gym membership costs $75/mo, but has an initial $100 signing fee
- A car could start out 20 miles from home, and then move at 40mph

We can see linear relationships show up in *Tables*, *Graphs*, and *Function Notation*:

[.sideways-pyret-table]
|===
| x | -1 | -2 | -3 | -4 | -5
| y |  1 |  2 |  3 |  4 |  5
|===

@image{images/10x+7.png}

@math{f(x) = 10x + 7}

`fun f(x): (10 * x) + 7 end`

In *Graphs*, linear relationships appear a _straight lines_. These lines have a _slope_ ("rise over run") and a y-intercept (where the line crosses the y-axis, at x=0).

In *Tables* where the rows are sorted by the x-value, linear relationships show up as y-values that change by a _constant rate_, with some _starting value_ (where the x-value is zero).

In *Function Notation* where like terms are combined, linear relationships will appear as two separate terms. One term includes an @math{x}, and the coefficient there shows us the slope. The other term is just the @vocab{y-intercept} (if that term is missing, the intercept is zero).

If you know how to read the slope and y-intercept for Tables, Graphs and Function Notation, you can switch back and forth between each representation. This flexibility is good: sometimes it's just easier to look at a table or a graph, or see the symbolic notation.