= Supervised Learning

@lesson-instruction{For this page, you'll need @starter-file{ai-image} open on your computer}

@vspace{1ex}

*How good is our `angle-similarity` measure at finding similar images for snow, grass, and sun?*

@n Evaluate each of the expressions below, paying attention to the closest matches at the top of the result table

(a) *Snow*: `angle-similarity(model, "4", [list: "LUMINANCE", "ENTROPY", "red", "green", "blue"])` +
(b) *Grass*: `angle-similarity(model, "6", [list: "LUMINANCE", "ENTROPY", "red", "green", "blue"])` +
(c) *Sun*: `angle-similarity(model, "7", [list: "LUMINANCE", "ENTROPY", "red", "green", "blue"])`

@indented{
Were the top results right for images with snow? @fitb{6em}{@ifsoln{Yes}} Grass? @fitb{6em}{@ifsoln{Yes}} Sun? @fitb{6em}{@ifsoln{No}}
}

Why is our similarity method worse at recommending sun images than it is with snow or grass? @fitb{}{} +
@fitb{}{@ifsoln{The sunset image is _really_ different from the others. Any time we search by the `ID` of the other images (0, 6, or 7), we get other recommendations before image 8.}}


== Calculating Centroids

@n Table below includes two rows with images of the sun (`"grass2"` and `"sun1"`). Complete the table by filling the Centroid. (NOTE: we're just showing _some_ of the columns on this page)

[%AUTOWIDTH, .FillVerticalSpace, cols="^.^, ^, ^a, ^a, ^a, ^a", options="header", stripes="none"]
|===
| ID
| WIDTH
| HEIGHT
| red
| green
| blue


| `"grass2"`
| 160
| 107
| 8932
| 5245
| 2921

| `"sun1"`
| 160
| 107
| 10971
| 175
| 5908

| `"SUN CENTROID"`
|@ifsoln{160}
|@ifsoln{107}
|@ifsoln{9,951.5}
|@ifsoln{2,710}
|@ifsoln{4,414.5}
|===

@n *Evaluate `m-sun = add-centroid(model, "SUN", [list: "grass2", "sun1"])`* to define a new model with the centroid, then `m-sun` to see it. What do you get back? (HINT: Be sure to view all the rows `m-sun`!) @fitb{}{} +
@fitb{}{@ifsoln{It added a centroid to our table, matching what I did by hand}}

@n Complete the code below, to find similar images using the `"SUN CENTROID"` in our new model, then try it out in Pyret:

`angle-similarity(` @fitbruby{5em}{@ifsoln{`m-sun`}}{Table}, @fitbruby{10em}{@ifsoln{"SUN CENTROID"}}{ID to compare}, `[list: "LUMINANCE", "ENTROPY", "red", "green", "blue"])`.

== Searching and Recommending

The questions below rely on the following contracts:

- @show{(contract "search-by-tag" '(Table String) "Table")}
- @show{(contract "recommend" '(Table) "Table")}

@n Make sure that only `"grass2"` and `"sun1"` are tagged with "sun", click "Run", and evaluate `search-by-tag(model, "sun")`. What does `search-by-tag` do? @fitb{}{} +
@fitb{}{@ifsoln{It find the images that have a matching tag, builds a centroid, then returns images similar to the centroid}}

@n Try tagging *one* of the grass images. Does `search-by-tag(model, "grass")` recommend the other? @fitb{3em}{@ifsoln{yes}} What about for snowy images? @fitb{}{@ifsoln{yes}}

@n Try adding a small number of likes and dislikes to the table, then evaluate `recommend(model)`.  The `recommend function` builds _two_ centroids. Can you figure out why? @fitb{}{} +
@fitb{}{@ifsoln{It builds one for likes and another for dislikes, then find images that are close to the first and far from the second}}