= Unsupervised Learning

@lesson-instruction{For this page, you'll need @starter-file{ai-image} open on your computer}

== Searching in Luminance-Entropy Space

@n Images 4 and 5 are both "snowy". Which images are "grassy"? @fitb{}{@ifsoln{Images 3 and 6}}

@n Evaluate `simple-similarity(decorated, "4", [list: "LUMINANCE", "ENTROPY"])`. Which image ID was the closest match to `"4"`? @fitb{}{@ifsoln{`"0"`}}

@n Try again, this time using `distance-similarity`. Which image ID was the closest match to `"4"`? @fitb{}{@ifsoln{`"3"`}}

@n Try again, this time using `angle-similarity`. Which image ID was the closest match to `"4"`? @fitb{}{@ifsoln{`"5"`}}

@n How well  `angle-similarity` work for image 3, using the same dimensions? @fitb{}{@ifsoln{not well!}}

@n Evaluate `image-scatter-plot(decorated2, "LUMINANCE", "ENTROPY", doc-thumbnail)`. Can you explain why searching in Luminance-Entropy Space worked well for our snowy images, but not the grassy ones?

@blanklines{3}{
@ifsoln{In Luminance-Entropy Space, there's a clear cluster for the snowy images. The grassy ones, however, are all spread out.}
}

== Bag-of-Words: Adding Color Axes

*Define a new image model, with attributes for each color:* +
@show{(code '(define decorated-bag (add-bag-cols decorated "color-names")))}

@n Evaluate `image-scatter-plot(decorated-bag, "LUMINANCE", "green", doc-thumbnail)`.

@n Are the grassy images clustered in Luminance-Green Space? @fitb{}{@ifsoln{yes!}} The snowy images? @fitb{}{@ifsoln{No}}

@n Use `angle-similarity` to search for Image 3. Is Image 6 a good match? @fitb{}{@ifsoln{yes}}

@n Will this work for snowy images, in Luminance-Green Space? @fitb{}{@ifsoln{no}}

@n Can you find two axes that define a space that will work for snowy _and_ grassy images?


== The "Best" Axes

We want an Image Search that does well with three kinds of images: snowy (4 and 5), grassy (3 and 6), and sunny (0, 6, 7 and 8). Some of our attributes will be helpful, some will not, and some might even result in _worse_ performance!

@n *Starting with the sun:* identify which attributes are most helpful when searching for images similar to Image 7, and write them below:

@fitb{}{}

@n *Scaling up:* identify which attributes are most helpful when searching for images in all three of our categories, and write them below:

@fitb{}{}