= Laws of Arithmetic

Laws of arithmetic can be applied to expressions with numbers and/or variables. By applying laws of arithmetic, we can determine if algebraic expressions are equivalent without assigning values to the variables.

== The Commutative Property

For expressions involving only addition or only multiplication, changing the order of the numbers will not change the result. The expressions below are equivalent (both equal @math{12}) on account of the Commutative Property of Multiplication.


[.embedded, cols="^.^3,^.^1,^.^3",grid="none", stripes="none" frame="none"]
|===
| @math{4 \times 3} || @math{3 \times 4}
|@show{(coe '(* 4 3))}	| @math{=} | @show{(coe  '(* 3 4))}
|===

The Commutative Property does not hold for subtraction or division.

@vspace{1ex}


== The Associative Property

For expressions involving only multiplication or only addition, changing the groupings will not change the result. The expressions below both equal @math{29}, even though their groupings have changed.

[.embedded, cols="^.^3,^.^1,^.^3",grid="none", stripes="none" frame="none"]
|===
| @math{(14 + 6) + (2 + 7)} |  | @math{(14 + 7) + 6 + 2}
|@show{(coe '(+ (+ 14 6) (+ 2 7)))} | @math{=} | @show{(coe  '(+ (+ (+ 14 7 ) 6) 2))}
|===

The Associative Property often results in simpler mental computations. The expression on the left is easier to compute because of the way in which the numbers are grouped.


@vspace{1ex}

== The Identity Property

Multiplying or dividing an expression by 1 does not change its value; similarly, adding or subtracting 0 results in the original value. Each of the expressions below results in the @math{14} due to the Identity Property.


[.embedded, cols="^.^6a,^.^1,^.^6a,^.^1,^.^6a",grid="none", stripes="none" frame="none"]
|===

| @math{5 + 9} || @math{(5 + 9) \times 1}|| @math{(5 + 9) + 0}

| @show{(coe '(+ 5 9))} | @math{=}
| @show{(coe '(* (+ 5 9) 1))} | @math{=}
| @show{(coe '(+ (+ 5 9) 0))}

|===

@vspace{1ex}

== The Distributive Property

Multiplying the sum of two addends by a number produces the same result as multiplying _each_ addend by that number before finding the sum. In other words: @math{a \times (b + c) = ab + ac}.

@vspace{1ex}


[.embedded, cols="^.^3,^.^1,^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
| @math{9 \times (40 + 6)}   |
| @math{(9 \times 40) + (9 \times 6)} |
| @math{360 + 54}
| @show{(coe '(* 9 (+ 40 6)))} | @math{=}
| @show{(coe '(+ (* 9 40) (* 9 6)))} | @math{=}
| @show{(coe '(+ 360 54))}
|===

Applying the Distributive Property often results in simpler computations that can be completed using mental math.


