= Frequency Tables, Bar Charts and Pie Charts
++++
<style>
body:not(.LessonPlan, .narrativepage) p { line-height: 1.1; }
</style>
++++
Open the @starter-file{expanded-animals} and click "Run".

== Part 1 - Visualizations for Categorical Data

Test the following expressions in the Interactions Area:

- @show{(code '(count more-animals "species"))}
- @show{(code '(bar-chart more-animals "species"))}

@n How are they similar? @fitb{}{@ifsoln{The height of each bar matches the count of each species.}}

@n Which do you like better: the bar chart or the frequency table? Why? @fitb{}{@ifsoln{Answers will vary.}} +
@fitb{}{}

@vspace{1ex}

Now test out the expression @show{(code '(pie-chart more-animals "species"))}

@n How does the pie chart connect to the bar chart you just made?

@fitb{}{@ifsoln{Pie charts show the frequency as a _percentage_. Bar charts show the frequency as a _count_.}}

@fitb{}{@ifsoln{With the pie chart we see how the categories compare to each other, but we have no way of knowing how many animals each wedge represents.}}

@vspace{1ex}

Note: When you first build a bar chart or pie chart in Pyret, they are interactive visualizations. That means that you can mouse over them for more information.  Hit the up arrow in the interactions area to reload your last expression and test it out!

== Part 2 - Comparing Bar and Pie Charts
_Best completed after @printable-exercise{bar-and-pie-notice.adoc} and @printable-exercise{matching-bar-to-pie.adoc}_

@n How are pie charts similar to bar charts? 

@fitb{}{@ifsoln{They both groups data by value to show frequency.}}

@n How are pie charts and bar charts different?

@fitb{}{@ifsoln{Bar charts show frequency as a count. Pie charts show frequency as a percentage.}}

@n What information is provided in bar charts that is hidden in pie charts?

@fitb{}{@ifsoln{In a bar chart, categories with no values are shown as empty categories, but there are no wedges for categories with 0% on a pie chart.}}

@n Why might this sometimes be problematic?

@fitb{}{@ifsoln{Answers will vary.  If a service isn't reaching a sector of the population, it's easier to ignore the issue if that population isn't represented in the display.}}

@n When would you want to use one chart instead of another?

@fitb{}{@ifsoln{Pie charts only make sense when our data reflects the whole.  For example, if a shelter has horses, sheep, goats, and donkeys...}}

@fitb{}{@ifsoln{ but we only had data for the horses and the sheep, we shouldn't make a pie chart of the species}}

== C - Bar and Pie Charts for Quantitative Data?

@n Make a `pie-chart` and `bar-chart` for the `pounds` column. Why isn't grouping the `pounds` column very useful?

@fitb{}{@ifsoln{Grouping by value works well for categorical data, when lots of different data points can be sorted into a smaller number of buckets.}}

@fitb{}{@ifsoln{But for quantitative data - which can have lots of different values - the number of buckets is too large to be useful.}}

@n Look at the list of columns in the Definitions Area. For which columns do you expect pie charts to be most useful?

@fitb{}{@ifsoln{Species, Sex, Fixed, and Legs}}

@vspace{1ex}

@star What questions about the dataset are you curious to investigate using these visualizations?

