= Introducing Displays for Subgroups

++++
<style>
#content { display: block !important; }
</style>
++++

_This page is designed to be used with the @starter-file{expanded-animals}._

== Part A

@n How many tarantulas are male? @fitb{10em}{@ifsoln{9}} 

@indented{_Hint: Sort the table by `species`!_}

@n How many tarantulas are female? @fitb{10em}{@ifsoln{11}}

@n Would you imagine that the distribution of male and female animals will be similar for every species at the shelter? Why or why not? @fitb{}{@ifsoln{no idea!}}

@fitb{}{}
@vspace{1ex}

== Part B

Sometimes we want to compare __sub-groups across groups__. In this example, we want to compare the distribution of sexes across each species.

@vspace{1ex}

Fortunately, Pyret has two functions that let us specify both a group and a subgroup:

@vspace{1ex}

[.indentedpara]
--
@show{(contract 'stacked-bar-chart '((table-name Table) (group String) (subgroup String)) "Image")}

@show{(contract 'multi-bar-chart '((table-name Table) (group String) (subgroup String)) "Image")}
--

@n Make a `stacked-bar-chart` showing the distribution of sexes across species in our shelter.

@n Make a `mutli-bar-chart` showing the distribution of sexes across species in our shelter.

@n What do you notice? @fitb{}{@ifsoln{Students may notice: The snails and clownfish are all hermaphrodites.}}

@fitb{}{@ifsoln{For the other species there are about as many males as females.}}

@fitb{}{@ifsoln{From the `stacked-bar-chart` we have no idea that there are way more dogs than snails.}}

@n What do you wonder? @fitb{}{}

@fitb{}{@ifsoln{Students may wonder: Is there a reason there are more male dogs? And more female cats? }}

@n Which display would be most efficient for answering the question: "What percentage of cats are female?"

@fitb{}{@ifsoln{stacked bar chart}}

@n Which display would be most efficient for answering the question: "Are there more cats or dogs?"

@fitb{}{@ifsoln{multi bar chart}}

@n Write a question of your own and decide which display would be most efficient for answering it. 

@fitb{}{}

