= Stacked & Multi Bar Charts - Notice and Wonder

++++
<style>
.tooltip, td, th { padding: 0 !important; }
img { max-height: 225px; }
table.stripes-odd tr:nth-of-type(odd) td { background: lightgray; }
</style>
++++

The displays on the left are called *multi bar charts*. The displays on the right are called *stacked barcharts*.


[cols="^.^1a,^.^1a", stripes=odd]
|===
2+| *Refugees in the Americas*
|@image{../images/refugees-multi.png, 300}
|@image{../images/refugees-stacked.png, 300}

2+| *Distribution of sexes across Cats, Dogs and Rabbits*
|@image{../images/multi-species-sex2.png, width}
|@image{../images/stacked-species-sex2.png, width}
|===

@vspace{1ex}
[.FillVerticalSpace, cols="^1a,^1a",options="header"]
|===
| What do you Notice? 	| What do you Wonder?
|						|
|===


@n Is it possible that the same data was used for the multi bar charts as for the stacked bar charts? How do you know?

@fitb{}{}

@n Write a question that it would be easiest to answer by looking at one of the multi bar charts.

@fitb{}{}

@n Write a question that it would be easiest to answer by looking at one of the stacked bar charts.

@fitb{}{}
