= Skull Exploring and Data Collection

Your evidence envelope contains pictures of 20 skulls you and your partner found scattered through the cave. In order to learn something about the skulls, you look through a book that provides the following information about typical skull sizes. You and your partner learn that skull circumferences (in inches) of various groups typically fall in these ranges:

[cols="1,1,1,1", options="header""]
|===

|
|Child:  14-21
|Adult Female: 21-23
|Adult Male: 22-24

|Skull circumference range
| 14 - 21 inches
| 21 - 23 inches
| 22 - 24 inches

|===

Collecting and Sorting Data into Google Sheets

. Make a copy of the @online-exercise{https://docs.google.com/spreadsheets/d/1Kw0m4K2jMQAvAE0gb2f93_7HB52KgnxjluuCmVpamOE/edit?usp=sharing, Skull Data table}.  
. Input the title of each column of your data in Row 1 of your Google Sheet. See below for column titles to include in your data table.
. Work with your partner to input the # of the skull and the skull circumference. You are just filling out Column A and Column B.
. “Sort” your data from smallest by clicking Row 1 so that the entire row is highlighted. Then go to “Data” → “Create a filter”. You should see a downward arrow in the first row of your data table.
. “Sort” your Skull Circumference from smallest to largest by clicking on the down arrow of Column B and selecting “Sort A → Z”. This will organize numbers from smallest to largest.


SAMPLE TABLE:
@centered-image{../images/skull-table.png, "screenshot of google sheet with 4 columns: skull number, circumference, age group, sex"}

DETERMINING AGE GROUP AND GENDER:
Now that you have sorted your skull circumference data, you will use the Skull Circumference Range information given at the top of this page to enter data for “Age Group” and “Gender”.

What will you do if you're unsure about whether a skull is from a child or an adult, because it's right on the border between them?

[.indented-para]
--
Option 1: 	Delete any data values for which you’re unsure about gender or age.
Option 2: 	Flip a coin if you’re unsure about gender; call it male if it comes up heads and female if it comes up tails. Likewise, call it a child for heads and an adult for tails.
Option 3: 	Classify gender or age as “Unsure” if you’re unsure about it.
--

Explain why the third of the following options would be the best way to handle this problem:

@fitb{}{}

@fitb{}{}
