= Starting to Program

@lesson-description{Students begin to program in Pyret, learning about Numbers,
Strings, Types, Operations, Contracts, and applying Functions.}

[@lesson-intro-table]
|===
@prereqs-stds{}
| Lesson Goals
| Students will be able to...

* Explain the difference between several data types: Numbers, Strings, Images and Booleans
* Identify a data type for a given value
* Write Numbers, String, and Booleans in the Interactions Area
* Apply functions to create Images
* Identify the parts of a Contract, and use it to apply a function

| Student-Facing Lesson Goals
| I can...

* Explain how Numbers, Strings, Images and Booleans are different
* Say what datatype a value is in Pyret
* Make Numbers, String, and Booleans in Pyret
* Make Images in Pyret
* Figure out how to use a function, based on the Contract

| Materials
|
* Computer for each student (or pair), with access to the
internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Preparation
|
* Make sure student computers can access @link{https://code.pyret.org, the Pyret IDE (CPO)}
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs
* All students should log into @link{https://code.pyret.org, CPO} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can @link{https://code.pyret.org/editor#share=1uK9VO5WO1RAH7g65DU_pkXZTyOnlno_-, open a new one}

| Supplemental Resources
|

| Relevant Standards
|
@worksheet-include{xtra/lang-prereq.adoc}
|===

== Numbers, Strings and Booleans @duration{20 minutes}

=== Overview
This lesson starts them programming, showing students how to make Pyret do simple math, work with text, and create simple computer graphics. It also draws attention to error messages, which are helpful when diagnosing mistakes.

=== Launch
Pyret lets us use many different kinds of data. In the animals table, for example, there are Numbers (the number of legs each animal has), Strings (the species of the animal), and Booleans (whether it is true or false than animal is fixed). Pyret has the usual arithmetic operators: addition (`+`), subtraction (`-`), multiplication (`*`), and division (`/`).

To identify if an animal is male, we need to know if the value in the `gender` column is _equal_ to the string `"male"`. To sort the table by age, we need to know if one animal’s age is _less than_ another’s and should come before it. To filter the table to show only young animals, we might want to know if an animal’s age is _less than_ 2. Pyret has Boolean operators, too: equals (`==`), less-than (`<`), greater-than (`>`), as well as greater-than-or-equal (`>=`) and less-than-or-equal (`<=`).


=== Investigate
[.lesson-instruction]
In pairs, students complete @worksheet-link{workbook-pages/numbers-n-strings.adoc}.

Discuss what students have learned about Pyret:

- Numbers and Strings evaluate to themselves.
- Anything in quotes is a String, even something like `"42"`.
- Strings _must_ have quotation marks on both sides.
- Operators like `+`, `-`, `*`, and `/` need spaces around them.
- Any time there is more than one operator being used, Pyret requires that you use parentheses.
- Types matter! We can add two Numbers or two Strings to one another, but we can’t add the Number `4` to the String `"hello"`.

Error messages are a way for Pyret to explain went wrong, and are a really helpful way of finding mistakes. Emphasize how useful they can be, and why students should read those messages out loud before asking for help. Have students see the following errors:

- `6 / 0`. In this case, Pyret obeys the same rules as humans, and gives an error.
- A`(2 + 2`. An unclosed quotation mark is a problem, but so is an unmatched parentheses.

[.lesson-instruction]
In pairs, students complete @worksheet-link{workbook-pages/booleans.adoc}.

=== Connect
Debrief student answers as a class.

By using `and` and `or`, we can _combine_ tests. For example, we might want to ask if a character in a videogame has run out of health points _and_ if they have any more lives. We might want to know if someone’s ZIP Code puts them in Texas or New Mexico. When you go out to eat at a restaurant, you might ask what items on the menu have meat and cheese. We’ll use these Boolean operators in a lot of our Data Science work later on.

[.lesson-instruction]
Have students play “true or false”, in which they stand if you say something true, and sit if you say something false. Start simple (“I am wearing a hat”), and gradually get complex (“I am wearing a hat, and I am standing on one leg”).

== Applying Functions @duration{35 minutes}

=== Overview
Students learn how to apply functions in Pyret, reinforcing concepts from standard Algebra. They also learn about @vocab{Contracts}, which can be used to figure out how to use functions they haven't seen before.

=== Launch
Students know about Numbers, Strings, Booleans and Operators -- all of which behave just like they do in math. But what about
@vocab{functions}? They may remember functions from algebra: @math{f(x) = x²}.

[.lesson-instruction]
- What is the name of this function?
- What will the expression _f(2)_ evaluate to? _f(3)_?
- The values that we give to a function are called its @vocab{arguments}. How many arguments does _f_ expect?

@vocab{Arguments} (or "inputs") are the values passed into a function. This is different from _variables_, which are the placeholders that get _replaced_ with input values! Pyret has lots of built-in functions, which we can use to write more interesting programs. 

[.lesson-instruction]
--
Have students type this line of code into the interactions area and hit Enter: `num-sqrt(16)`.

* What is the name of this function?
* What did the expression `num-sqrt(16)` evaluate to?
* Does the `num-sqrt` function produce Numbers? Strings? Booleans?
* How many @vocab{arguments} does `num-sqrt` expect?

Type this line of code into the interactions area and hit Enter: `triangle(50, "solid", "red")`

- What is the name of this function?
- What did the expression evaluate to?
- How many arguments does `triangle` expect?
- Does the `triangle` function produce Numbers? Strings? Booleans?

You’ve just created an example of a new Datatype, called an _Image_.

- What are the types of the arguments `triangle` was expecting?
- How does this output relate to the inputs?
- Try making different triangles. Change the size and color! Try
  using `"outline"` for the second argument.

The `triangle` function consumes a Number and two Strings as input, and produces an Image. As you can imagine, there are many
other functions for making images, each with a different set of arguments. For each of these functions, we need to keep track of
three things:

- *Name* -- the name of the function, which we type in whenever we want to use it
- *Domain* -- the data we give to the function (names and
  Types!), written between parentheses and separated by commas
- *Range* -- the type of data the function produces

Domain and Range are _Types_, not specific values. As a convention, we *capitalize Types and keep names in lowercase*. `triangle` works on many different Numbers, not just the `20` we used in the example above!

These three parts make up a @vocab{contract} for each function. Let’s take a look at the Name, Domain, and Range of `num-sqrt` and
`triangle`:

----
# num-sqrt :: (n :: Number) -> Number
# triangle :: (side :: Number, mode :: String, color :: String) -> Image
----

The first part of a contract is the function’s name. In this example, our functions are named `num-sqrt` and `triangle`.

The second part is the @vocab{Domain}, or the names and types of arguments the function expects. `triangle` has a Number and two
Strings as variables, representing the length of each side, the mode, and the color. We write name-type pairs with double-colons,
with commas between each one. Finally, after the arrow goes the type of the @vocab{Range}, or the function’s output, which in this case is Image.
--

=== Investigate
Most of the time, error messages occur when we've accidentally broken a contract. 
[.lesson-instruction]
--
Can you see what is wrong with each of these expressions? Try copying them into Pyret, one at a time, and reading the error messages aloud.

- `triangle(20 "solid" "red")`
- `triangle("20", "solid", "red")`
- `triangle(20, "solid", "red", "striped")`

Contracts tell us a lot about how to use a function. In fact, we can figure out how to use functions we've never seen before, just by looking at the contract!

Turn to the back of your workbook, and get some practice reading and using contracts! Make sure you try out the following functions:

- `text`
- `circle`
- `ellipse`
- `star`
- `string-repeat`

Here’s an _example_ of another function. Type it into the Interactions Area to see what it does. Can you figure out the contract, based on the example? 
`string-contains("apples, pears, milk", "pears")`
--

=== Possible Misconceptions
Students are _very_ likely to randomly experiment, rather than actually using the Contracts page. You should plan to ask lots of direct questions to make sure students are making this connection, such as:

- How many items are in this function's Domain?
- What is the _name_ of the 1st item in this function's Domain?
- What is the _type_ of the 1st item in this function's Domain?
- What is the _type_ of the Range?

=== Connect
You’ve learned about Numbers, Strings, Booleans, and Images. You’ve learned about operators and functions, and how they can be used to make shapes, strings, and more!

One of the other skills you’ll learn in this class is how to diagnose and fix errors. Some of these errors will be _syntax errors_: a missing comma, an unclosed string, etc. All the other errors are _contract errors_. If you see an error and you know the syntax is right, ask yourself these two questions:

- What is the function that is generating that error?
- What is the contract for that function?
- Is the function getting what it needs, according to its Domain?

By learning to use values, operations and functions, you are now familiar with the fundamental concepts needed to write simple programs. You will have many opportunities to use these concepts in this course, by writing programs to answer data science questions.

Make sure to save your work, so you can go back to it later!

== Additional Exercises:

- @worksheet-link{workbook-pages/practicing-contracts.adoc, Practicing Contracts}
- @worksheet-link{workbook-pages/practicing-contracts-2.adoc, Practicing Contracts}
- @worksheet-link{workbook-pages/matching-expressions.adoc, Matching Expressions}
- @worksheet-link{workbook-pages/matching-expressions-2.adoc, Matching Expressions}