= Compound Inequalities: Solutions & Non-Solutions

++++
<style>
#content .fitb { min-width: 3.5em; }
</style>
++++

For each Compound Inequality listed below, identify 4 _solutions_ and 4 _non-solutions_, unless the solution set includes *all real numbers* or there are *no solutions*.

@indented{
* Solutions for @vocab{intersections} (which use *and*) will make both of the expressions `true`.

* Solutions for @vocab{unions} (which use *or*) will make at least one of the expressions `true`.
}

@vspace{1ex}

Pay special attention to the numbers in the sample expression! Challenge yourself to use negatives, positives, fractions, decimals, etc. 

@vspace{1ex}

[.center]
_The first two have been done for you -- Answers will vary!_

[.FillVerticalSpace, cols="^.^1, ^.^5a, ^.^8, ^.^8", options="header", frame="none"]
|===
|
| Expression
| 4 solutions that evaluate to `true`
| 4 non-solutions that evaluate to `false`

| a
| `x > 5` and `x < 15`
| *6, 9.5, 12, 14.9*
| *-2, 5, 15, 16.1*

| b
| `x > 5` or `x < 15`
| *All real numbers*
| *No non-solutions*

| c
| `x <= -2` and `x > 7`
| @ifsoln{ _No solution_ 		}
| @ifsoln{ _All real numbers_ 	}

| d
| `x <= -2` or `x > 7`
| @ifsoln{ -2, -3.6, 8, 1000 	}
| @ifsoln{ 7, -1, 0, 5 			}

| e
| `x < 3.5` and `x > -4`
| @ifsoln{ -3.5, 0, 1, 3 		}
| @ifsoln{ 3.5, -4, -8, 400 	}

| f
| `x < 3.5` or `x > -4`
| @ifsoln{ _All real numbers_ 	}
| @ifsoln{ _No non-solutions_ 	}

| g
| `x >= -1` and `x > -5`
| @ifsoln{ -1, 0, 23, 400 		}
| @ifsoln{ -3, -5, -10, -542 	}

| h
| `x >= -1` or `x > -5`
| @ifsoln{ -4.5, -3, -1, 100 	}
| @ifsoln{ -5, -6, -28, -1000 	}

| i
| `x < -4` and `x > 2`
| @ifsoln{ _No solution_ 		}
| @ifsoln{ _All real numbers_ 	}

|===

@n Could there ever be a union with _no solutions_? Explain your thinking.
@blanklines{3}{
@ifsoln{_No. The solution set for each inequality includes a subset of the real numbers and the union of two inequalities will include more than the numbers in either of those subsets._
}
}

@vspace{4ex}

@n Could there ever be an intersection whose solution is _all real numbers_? Explain your thinking.

@blanklines{3}{
@ifsoln{_No. The solution set for each inequality includes a subset of the real numbers, so the list of numbers where the subsets overlap couldn't possibly include all of the real numbers._
}
}
