= Linear Relationships

++++
<style>
.graph-table img {width: 33%;}
.tableFlip { position: relative; }
.tableFlip table {
	top: 0px;
	left: 0px;
    transition: opacity 1s;
}
.tableFlip table:first-child {
	position: relative;
	background: lightpink;
}
.tableFlip table:last-child {
	position: absolute;
	background: lightgreen;
	opacity: 0;
}
.tableFlip:hover table:first-child { opacity: 0;}
.tableFlip:hover table:last-child  { opacity: 1;}
</style>
++++

@lesson-description{Students explore the concept of linear relationships, as described by tables with graphs.}

[@lesson-intro-table]
|===
@prereqs-stds{}
| Lesson Goals
| Students will be able to...

* match graphs to tables that represent the same relationship
* identify linear and non-linear graphs and tables

| Student-facing Lesson Goals
|

* I can match graphs to tables, if they both describe the same linear relationship
* I can tell the difference between linear and non-linear relationships in tables and graphs

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/1ihegdgsstshwg2wcZZO-BFr5hQHsqhR_JFlpThVP8WI/view, Lesson Slides}

@material-links

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with
* All students should log into @link{https://code.pyret.org, CPO} and open the @online-exercise{https://code.pyret.org/editor#share=XYZ, Graphing Starter File} they saved from the prior lesson. If they don't have the file, they can open a new one.

| Key Points for the Facilitator
| This lesson is about two big ideas:

* Linear relationships, defined as straight lines on a graph and sequences that change at a constant rate
* Connecting representations of Tables and Graphs

@include{xtra/lang-prereq.adoc}
|===

== Simple Sequences and Straight Lines @duration{35 minutes}

=== Overview
Students explore the concept of _linearity_, as represented in tables and graphs.

=== Launch
Take a look at the following Table and Graph:

[cols="^.^1a,^.^1a", grid="none", frame="none"]
|===
|

[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! 0
! 1 ! 2
! 2 ! 4
! 3 ! 6
! 4 ! 8
!===
| @image{images/2x.png}
|===

[.lesson-instruction]
- What do you *Notice*?
- What do you *Wonder*?

Each row in the Table represents an (x, y) point on the graph. We can think of the "x" column as counting the __order in which the y-values appear__ (1st value, 2nd value, etc). The "y" column, on the other hand, shows the values in the sequence.

[.lesson-instruction]
Can you predict the next two rows in the table? Could you extend the line on the graph? __How did you arrive at your prediction?__

Both the table and graph follow a _pattern_. We expect the line to continue straight in both directions, and for the sequence of values in the table to increase at the same rate for every additional row.

[.lesson-point]
*Linear Relationships*: Sequences that increase at a constant rate, or straight lines on a graph.

Simple sequences and straight-line relationships belong to a special category called @vocab{linear} relationships. If a sequence of numbers always increases (or decreases!) by the same amount, it's linear. If the graph of a function shows up as a straight line, it's linear.

Linear relationships are _everywhere_:

* A car is traveling at 50 miles per hour. How far does it travel in 4 hours? How long does it take to travel 350 miles?
* A gallon of milk costs $2.50. How much will it cost to buy 3 gallons? How much milk can you buy with $10?
* A tractor-trailer has 18 wheels. If a parking lot has 16 tractor-trailers, how many wheels is that in total?

If you know how to think about linear relationships, these questions become easy to answer!

=== Investigate

Look at the two "sideways" data tables below. You can think of the "x" column as counting the __order in which the y-values appear__ (1st value, 2nd value, etc). The "y" column, on the other hand, shows the values in the sequence:

[cols="^.^1a,^.^1a", frame="none"]
|===
|

[.sideways-pyret-table]
!===
! x ! 1 ! 2 ! 3 ! 4 ! 5
! y ! 2 ! 3 ! 4 ! 5 ! 6
!===

|

[.sideways-pyret-table]
!===
! x !   1 !   2 !   3 !   4 !   5
! y ! -12 ! -14 ! -16 ! -18 ! -20
!===

|===

- What do you *Notice?*
- What do you *Wonder?*
- Can you figure out what the next (x,y) pair should be for each of them?  
- Can you guess what the y-value for each table would be when x is 0?

When there is a @vocab{linear} relationship, the values in a table increase at a _constant rate_. If we were to graph those values, all of the points would fall on a straight line.

[.lesson-instruction]
- Complete @online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fc25d458dcfcf0b92021b13, "Matching Tables to Graphs"}.
- Optional: Complete @opt-printable-exercise{pages/match-tables-graphs.adoc}.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Pedagogy Note}

To encourage students to look at the _points_ in the table and graph, it is useful to change the scale of the graphs so that all lines look the same. This prevents students from leaning on visual cues like "steepness" to bypass the learning objective.

It can also be useful to list the points in the table __out of order__, both to focus students' attention on the points and to drive home that rows do not have to be ordered!
|===

[.lesson-point]
Axes on a graph need an order. Rows in a table don't!

The rows in a table are _discrete_. They preserve their meaning if the rows are shuffled into a different order. Ordering the rows in a table can make it easier for us to recognize patterns.

In the graph of a line, the points are _not_ discrete, and cannot be shuffled. Lines have properties that depend on order, like whether the line slopes up or down as it goes from left to right. Graphs can be stretched or squished by changing the scale of the axis. This can make the lines _look_ different, but the points will always be in the same order.

[.lesson-instruction]
Can you match tables and graphs, even if the rows are shuffled and the axes are changed? Complete @opt-printable-exercise{pages/match-tables-graphs2.adoc}.

=== Synthesize
@vocab{Linear} relationships show up all the time in real life, so it's helpful to know how to think about them. We've seen that linear relationships can be represented as tables and graphs. Tables only show us _some points_ on a line, whereas a line itself is made up of an _infinite_ number of points. When a table represents a _sample_ of some larger trend, the graph is a way of seeing the trend itself.

== Linear, Non-Linear, or Bust!  @duration{20 minutes}

=== Overview
Students deepen their understanding of linearity, by seeing counterexamples (non-linear relationships), as well as tables and graphs for which there is _no_ relationship.

=== Launch

If all linear relationships can be shown as a table or a graph, does that mean all tables and graphs are linear? Look at the six graphs shown below:

[.graph-table, stripes="none", frame="none"]
|===
| @image{images/constant-linear.png} 
  @image{images/num-abs.png}
  @image{images/num-sqrt.png}

| @image{images/negative-linear.png}
  @image{images/positive-linear.png}
  @image{images/num-sqr.png}
|===

[.lesson-instruction]
- What do you *Notice?*
- What do you *Wonder?*

Three of the graphs above are *straight lines* (called "linear") and three are not ("nonlinear"). As we can see, the linear graphs can be perfectly horizontal, slope upwards and to the right, or slope downwards to the right. 

[.lesson-point]
Linear relationships in a graph always appear as straight lines

Look at the six "sideways" data tables below. The bottom list of numbers (ys) is a sequence, and the top list (xs) tells us which order those numbers appear in that sequence.

[cols="^.^1a,^.^1a", frame="none"]
|===
|

[.sideways-pyret-table]
!===
! x ! 1 ! 2 ! 3 ! 4 ! 5
! y ! 2 ! 3 ! 4 ! 5 ! 6
!===
|

[.sideways-pyret-table]
!===
! x ! 1 ! 2 ! 3 !  4 !  5
! y ! 1 ! 4 ! 9 ! 16 ! 25
!===

|

[.sideways-pyret-table]
!===
! x !  1 !  2 !  3 !  4 !  5
! y ! 12 ! 14 ! 16 ! 18 ! 20
!===

|

[.sideways-pyret-table]
!===
! x ! 1 ! 2 ! 3 ! 4 ! 5
! y ! 3 ! 3 ! 3 ! 3 ! 3
!===

|

[.sideways-pyret-table]
!===
! x !  1 !  2 !   3 !   4 !  5
! y ! 84 ! 94 ! 104 ! 114 ! 124
!===

|

[.sideways-pyret-table]
!===
! x !  1 !  2 !   3 !   4 !  5
! y ! 84 ! 94 ! 104 ! 114 ! 124
!===

|===

- What do you *Notice?*
- What do you *Wonder?*
- Can you figure out what the next x,y pair should be for each of them?  
- Can you guess what the y-value for each table would be when x is 0?

[.lesson-point]
Linear relationships in a table show up as sequences that change at a constant rate. The y-value when x is zero is also the value where the line will cross the y-axis.

Sometimes there is __no pattern at all__! Take a look at the table and graph below. Can you predict the next two rows? Could you extend the line?

[cols="^.^1a,^.^1a", grid="none", frame="none"]
|===
|

[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! 13
! 1 ! -2
! 1 ! 16
! 3 ! 0
! 4 ! 54
!===
| @image{images/scatterplot.png}
|===

*PRO TIP:* One surefire way to tell that there is no relationship between @math{x} and @math{y} is when there are two different @math{y} values for the same @math{x}.

== Investigate
[.lesson-instruction]
Can you tell when a relationship has a linear pattern? A non-linear one? No pattern at all? Complete @opt-printable-exercise{linear-nonlinear-bust.adoc, "Linear, Non-Linear or Bust?"}

=== Synthesize
Data has a "shape", and this shape can emerge when we look for patterns in that data. A @vocab{linear} relationship is one kind of shape, and it shows up when we view that data as a table or a graph.

== Additional Exercises: