= Visualizing the “Shape” of Data

@lesson-description{Students explore the concept of "shape", using histograms to infer whether a dataset has skew, and what the direction of the skew means. They apply this knowledge to the Animals Dataset, and then to their own.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-exploring-your-dataset}
| Lesson Goals
| Students will be able to...

* histograms using the animals dataset
* visualizations of frequency using their chosen dataset, and write up their findings

| Student-Facing Lesson Goals
| I can...

| Materials
|
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|

| Relevant Standards
|
@worksheet-include{xtra/lang-prereq.adoc}
|===

== Review (15 minutes)
[.lesson-instruction]
Have students turn to @worksheet-link{workbook-pages/reading-histograms.adoc}, and complete the matching activity there.

== Describing Shape @duration{20 minutes}

=== Overview
This activity focuses on _describing shape_ based on a histogram. Students learn about "skew left", "skew right", and "symmetric" data, what those terms mean, and what that tells us about a dataset.

=== Launch
@span{.right}{@image{images/skew-right.png, "", 300, ""}}

Shape is one way to _summarize_ information in a dataset, to quickly describe what values are more or less common.

Consider the image on the right: most of the datapoints are clustered on the left side, and it contains a few unusually high values way off to the right. We might describe this histogram by saying that it is _“skewed right, or has high outliers.”_

@span{.clear}
Here are the most common shapes that we see for real-world data sets:

[.lesson-point]
Symmetric: values are balanced on either side of the middle.

In a @vocab{symmetric} distribution, it’s just as likely for the variable to take a value a certain distance below the middle as it is to take a value that same distance above the middle. Examples:

- Heights of 12-year-olds would have a symmetric shape. It’s just as likely for a 12-year-old to be a certain number of inches below average height as it is to be that number of inches above average height.
- In a standardized test, most students score fairly close to what’s average. Also, we see just as many students scoring a certain number of points above average as we see scoring that same number of points below average. The shape is symmetric (and bulges in the middle because most students score fairly close to what’s average).

[.lesson-point]
Skewed left, or low outliers.

In a distribution that is @vocab{skew left}, values are clumped around what’s typical, but they trail off to the left with a few unusually low values. Examples:

- Number of teeth that adults have in their mouths would be skewed left or have low outliers. Most adults will have close to a full set of 32 teeth, but a few of them with serious dental problems would have a very small number of teeth. We won’t get anyone in our data set who has 10 or 20 _extra_ teeth in their mouths!
- If most students did pretty well on an exam, but a few students performed very badly, then we’d see a shape that has left skewness and/or low outliers.

[.lesson-point]
Skewed right, or high outliers.

In a distribution that is @vocab{skew right}, values are clumped around what’s typical, but they trail off to the right with a few unusually high values. We see this shape often in the real world, because there are many variables -- like “income” or “time spent on the phone” -- for which a few individuals have unusually high values, which aren’t balanced out by unusually low values (things like “income” and “phone time” can’t be less than zero). Examples:

- Age when a woman in the U.S. gives birth would be skewed right or have high outliers. A few women would be unusually old, 40 years or even more above the average age of 26 (check the tabloids!), but none of them could be even close to 40 years below average to balance things out!
- A data set of earnings almost always shows right skewness or high outliers, because there are usually a few values that are so far above average, they can’t be balanced out by any values that are so far below average. (Earnings can’t be negative.)

=== Investigate
[.lesson-instruction]
* Make a histogram for the pounds column in the animals table, sorting the animals into 20-pound bins:
* Would you describe the shape of your histogram as being skewed left, skew right, or symmetric?
* Which one of these statements is justified by the histogram’s shape?

. A few of the animals were unusually light.
. A few of the animals were unusually heavy.
. It was just as likely for an animal to be a certain amount below average weight as it was for an animal to be that amount above average weight.

* Try bins of 1-pound intervals, then 100-pound intervals. Which of these three histograms best satisfies our rule of thumb?
* *Challenge*: Compare histograms for pounds of cats vs. dogs in the dataset. Are their shapes different? If so, how?
* On @worksheet-link{workbook-pages/shape-of-animals-dataset.adoc}, describe the pounds histogram and another one you make yourself. When writing down what you notice, try to use the language Data Scientists use, discussing both skew and outliers.

=== Collect
Discuss as a class, making sure students agree on the description of the shape.

== Your Dataset @duration{flexible}

=== Overview 
Students repeat the previous activity, this time applying it to their own dataset and interpreting their own results.

=== Launch
Now it's time to try looking at the shape of your own dataset! Pick one quantitative column in your dataset, and hypothesize whether you think it will be skew right, skew left, or symmetric. What do you think?

=== Investigate
[.lesson-instruction]
How is your dataset distributed? Choose two quantitative variables and display them with histograms. Explain what you learn by looking at these displays. If you’re looking at a particular subset of the data, make sure you write that up in your findings on @worksheet-link{workbook-pages/shape-of-my-dataset.adoc}.

=== Collect
Have students share their findings.

Histograms are a powerful way to display a data set and see its @vocab{shape}. But shape is just one of three key aspects that tell us what’s going on with a quantitative data set. In the next unit, we’ll explore the other two: center and spread.