[.landscape]
= Contracts

Contracts tell us how to use a function. e.g. `ellipse : Number, Number, String, String -> Image` tells us that the name of the function is  `ellipse`, and that it takes four inputs (two  Numbers and two Strings). From the contract, we know  `(ellipse 100 50 "outline" "fuchsia")` will evaluate to an Image.

++++
<style>
td {padding: .4em .625em !important; height: 15pt;}
</style>
++++

[.contract-table,cols="4,1,10,1,2", options="header",grid="rows",stripes="none"]

|===

| Name    
|       
| Domain      
|     
| Range

| `;` `sqr`
| `:`
| `Number`
| `->`
| `Number`
5+|`;` `_(sqr 5)_`

| `;` `sqrt`
| `:`
| `Number`
| `->`
| `Number`
5+|`;` `_(sqrt 25)_`

| `;` `string-length`
| `:`
|	`String`
| `->`
| `Number`
5+| `_(string-length "Awesome!")_`

| `;` `star`
| `:`
| `Number String String`
| `->`
| `Image`
5+| `_(star 50 "solid" "teal")_`

| `;` `circle`
| `:`
| `Number String String`
| `->`
| `Image`
5+| `_(circle 45 "outline" "darkgreen")_`

| `;` `triangle`
| `:`
| `Number String Sting`
| `->`
| `Image`
5+| `_(triangle 80 "solid" "fuchsia")_`

| `;` `square`
| `:`
| `Number String String`
| `->`
| `Image`
5+| `_(square 70 "outline" "lightblue")_`

| `;` `rectangle`
| `:`
| `Number Number String String`
| `->`
| `Image`
5+| `_(rectangle 20 80 "solid" "gold")_`

| `;` `rhombus`
| `:`
| `Number Number String String`
| `->`
| `Image`
5+| `_(rhombus 20 50 "solid" "turquoise")_`

| `;` `ellipse`
| `:`
| `Number Number String String`
| `->`
| `Image`
5+| `_(ellipse 70 30 "outline" "red")_`

|===
