[.landscape]
= Contracts

Contracts tell us how to use a function. e.g.  `ellipse : Number, Number, String, String -> Image` tells us that the name of the function is  `ellipse`, and that it takes four inputs (two  Numbers and two Strings). From the contract, we know  `(ellipse 100 50 "outline" "teal")` will evaluate to an Image.

++++
<style>
td {padding: .4em .625em !important; height: 15pt;}
</style>
++++

[.contract-table,cols="4,1,10,1,2", options="header",grid="rows",stripes="none"]
|===

| Name
|
| Domain
|
| Range

| `;` `flip-horizontal`
| `:`
| `Image`
| `->`
| `Image`
5+| `_(flip-horizontal(text "Bootstrap is fun!" 60 "darkblue"))_`

| `;` `flip-vertical`
| `:`
| `Image`
| `->`
| `Image`
5+| `(flip-vertical(triangle 80 "solid" "lightgreen"))`

| `;` `above`
| `:`
| `Image Image`
| `->`
| `Image`
5+| `_(above (triangle 30 "solid" "red")(square 30 "solid" "blue"))_`

| `;` `beside`
| `:`
| `Image Image`
| `->`
| `Image`
5+| `_(beside (star 50 "solid" "orange")(circle 50 "solid" "green"))_`

| `;` `<`
| `:`
| `Number Number`
| `->`
| `Boolean`
5+| `_(< 3 2)_`

| `;` `>`
| `:`
| `Number Number`
| `->`
| `Boolean`
5+| `_(> 3 2)_`

| `;` `=`
| `:`
| `Number Number`
| `->`
| `Boolean`
5+| `_(= 3 2)_`

| `;` `<=`
| `:`
| `Number Number`
| `->`
| `Boolean`
5+| `_(<= 3 2)_`

| `;` >=
| `:`
| `Number Number`
| `->`
| `Boolean`
5+| `_(>= 3 2)_`

| `;` `or`
| `:`
| `Boolean Boolean`
| `->`
| `Boolean`
5+| `(or (<= 3 2) (>= 3 2))`

|===
