= Evaluating Exponent Expressions with Negative Values

@description{Students use Circles of Evaluation to analyze the structure of expressions with exponents and negative values.}

@lesson-prereqs{evaluating-exponents}

@keywords{Circle of Evaluation}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Determine the order in which we negate and apply exponents in expressions both with and without grouping symbols.
* Evaluate expressions involving exponents and negative values.
* Evaluate exponent expressions with negatives and variables.


| Student-facing Lesson Goals
|

* Let's use Circles of Evaluation to analyse the structure of expressions with exponents and negative values.


| Materials
|[.materials-links]
@material-links

|===


== Exponent Expressions with Negatives @duration{30 minutes}

=== Overview

Students apply Circles of Evaluation to analyze expressions with @vocab{exponents} and negatives.

=== Launch

[.lesson-instruction]
--
- Look closely at each of these @vocab{arithmetic expressions}, considering the effect of the negation and the exponent on the outcome: @math{-3^2}, @math{(-3)^2}, and @math{-(3^2)}
- Are any of these three expressions equivalent? How do you know? Draw Circles of Evaluation to help you.
** _We know that in an expression with no grouping symbols, we evaluate the exponent first - before the negation. Therefore, the first and third expression are equivalent; they both evaluate to @math{-9}. The second expression evaluates to @math{9}. See Circles of Evaluation below._
[.embedded, cols="^.^1,^.^1", grid="none", stripes="none", frame="none"]
|===
|@math{-3^2} or @math{-(3^2)}				| @math{(-3)^2}
|@show{(coe  '(negate (num-expt 3 2)))}		| @show{(coe  '(num-expt (negate 3) 2) )}
|===
--

=== Investigate

In the following activity, students will apply exponents in two different types of contexts: (1) instances where they apply the exponent to a _negative value_, and (2) instances where they negate _after_ applying the exponent. Circles of Evaluation will help students to visualize the difference between these two scenarios.

[.lesson-instruction]
- On @printable-exercise{true-or-false.adoc}, draw two Circles of Evaluation two represent each equation. Then, use your Circles of Evaluation to determine if the equation is true or false. The first one is done for you.
- When you're finished, look over your work to see what patterns you notice and then respond to the questions at the bottom of the page.

=== Synthesize

- If an expression has no grouping symbols, which do we apply first: `num-expt` or
`negate`?
** _First, we apply `num-expt`, then `negate`._
- If an exponent expression has a negative value inside parentheses, which do we apply first: `num-expt` or `negate`?
** _First, we apply `negate`, then `num-expt`._
- Why were _some_ of the equations on the worksheet true, but not all of them?
** _Possible response: Exponent expressions with negatives but no grouping symbols were always negative, because the negation came last. Exponent expressions with grouping symbols were sometimes negative and sometimes positive, depending on how many times we multiplied the base by itself._

== Variable Exponent Expressions with Negatives @duration{25 minutes}

=== Overview

Students extend their knowledge of Circles of Evalution to evaluate expressions with @vocab{variables}, exponents, and negatives.

=== Launch

Invite students to consider the role of variables in expressions with negatives and exponents by facilitating a discussion using the prompts below.

[.lesson-instruction]
- Is @math{-m} sometimes, never, or always negative? Explain your response.
** _If the value of @math{m} is negative, then @math{-m} is positive. If the value of @math{m} is positive, then @math{-m} is negative. So, @math{-m} can be positive, negative, or zero._
- Is @math{-m^2} sometimes, never, or always negative? Explain your response.
** _First we apply the exponent, then we negate. The outcome is always negative (unless @math{m} is zero)._

=== Investigate

[.lesson-instruction]
- On @printable-exercise{evaluate-twice.adoc}, create a Circle of Evaluation for each expression provided. Once you have drawn a Circle of Evaluation, use it to help you evaluate the expression __twice__ - once for @math{x=5} and once for @math{x=−5}.
- When did the expressions produce the same outcome for both @math{x=5} and @math{x=-5}?
** _The expressions produced the same outcome for 1 and 2, the expressions that involved squaring rather than cubing._
- When you're done, turn to @printable-exercise{exponents-variables-table.adoc}. Draw a Circle of Evaluation to represent the expression, then evaluate using the assigned value.


=== Synthesize

Was it more challenging to work with _algebraic_ exponent expressions (with variables) than it was to work with numeric exponent expressions? Why or why not?


