= Building a Hybrid Model
++++
<style>
/* We don't need the margin on this page, and we want to save vertical space */
.listingblock { margin-bottom: 0; }
</style>
++++
@link-instructions{Open your copy of @starter-file{alg2-hybrid} and click "Run".}

== Composing a `hybrid` model for the `modern-table`

Both `periodic-sin` and `periodic-cos` are built to follow a midline with the equation @math{f(x) = 419.87}. +
*But who says the midline has to be __horizontal?__*

@n Which midline do we wish a model for the `modern-table` would follow instead?  @fitb{}{@ifsoln{The line of best fit, which we could find using `lr-plot`.}} 

@teacher{The line of best fit will be @math{y = 2.141263x - 4461}}

@n Find `linear-modern` in the starter file and define it to be the line you described above.

@n Find the definition for `hybrid-modern`. How is this function using `linear-modern`? @fitb{}{}

@fitb{}{@ifsoln{`linear-modern` is being used as the midline!}}

@n Fit `hybrid-modern` to the `modern-table`, and describe what you see: @fitb{}{}

@fitb{}{@ifsoln{Now the periodic wave is on a diagonal!}}


== Comparing Models

@n What @vocab{S-value} describes the expected error in our `hybrid-modern` model for this data? @fitb{}{@ifsoln{~1.4}}@fitbruby{8em}{@ifsoln{ppm}}{y-units}

@n What @vocab{S-value} describes the expected error in our `linear-modern` model for this data? @fitb{}{@ifsoln{~2.27}}@fitbruby{8em}{@ifsoln{ppm}}{y-units}

@n How much
@fitbruby{5em}{@ifsoln{less}}{more / less }
error do we expect in predictions made using `hybrid-modern` than with the `linear-modern` model?

@vspace{1ex}

@scrub{
A note for future authors:
- {&#8192;} is used below to add horizontal space.
- \mbox{} is used to make the words in the fraction use normal font.
}

@indented{
_Percent Change_ &#8192; = &#8192;
@math{
\frac{&#8192; \mbox{Difference} &#8192; \mbox{between} &#8192; \mbox{the} &#8192; \mbox{S-values}&#8192;}
{\mbox{S-value} &#8192; \mbox{for} &#8192; \mbox{linear} &#8192; \mbox{model}}
\times 100 &#8192; = &#8192; }
@ifnotsoln{@math{\frac{\qquad}{\qquad}}}
@ifsoln{@math{\frac{0.87}{2.27} = 0.38  &#8192; &rarr; &#8192;  ~38 \%}}

We expect 
@fitb{4em}{@ifsoln{~38}} percent
@fitbruby{5em}{@ifsoln{less}}{ more / less }
error from predictions made with `hybrid-modern` than with `linear-modern` model!
}


== Interpreting the Hybrid Model

__This model predicts that the overarching trend will be a(n)__
@fitbruby{7em}{@ifsoln{increase}}{increase/decrease} _of_
@fitbruby{5em}{@ifsoln{2.41263}}{rate of change}
@fitbruby{20em}{@ifsoln{parts per million of @math{/text{CO}_2} in the atmosphere}}{x-variable} _every_
@fitbruby{4em}{@ifsoln{year}}{x-units}. __The data will fluctuate following a periodic pattern that rises and falls around this @vocab{midline}, with an amplitude of__ 
@fitbruby{6em}{@ifsoln{4.13}}{amplitude}, __repeating every__
@fitbruby{4em}{@ifsoln{1}}{period} @fitbruby{5em}{@ifsoln{year}}{x-units}.

__The error in the model is described by an @vocab{S-value} of about__ 
@fitbruby{1em}{@ifsoln{1.4}}{S}@fitbruby{8em}{@ifsoln{ppm}}{y-units}. @hspace{1em} _I_
@fitbruby{18em}{@ifsoln{strongly agree}}{strongly agree, agree, disagree, strongly disagree}
that this model is a good fit considering that 
@fitbruby{8em}{@ifsoln{@math{/text{CO}_2}}}{y-variable} in this dataset ranges from about
@fitbruby{8em}{@ifsoln{387.03 ppm}}{lowest y-value} to @fitbruby{8em}{@ifsoln{424 ppm}}{highest y-value}.__
