= Modeling Modern Carbon Dioxide Levels
++++ 
<style>

/* Make code more visible */
td .codetwo { color: black; background: none; }

/* Allow fill in the blanks to be even shorter */
.fitb { min-width: 2em; padding-top: 1rem; }

/* Adjust padding and font-style for our tables */
table tr td { padding: 0; }
td:first-child { padding-right: 1em; }
td:first-child p { font-style:  italic; }
</style>
++++

@define{COtwo}{@math{\text{CO}_2}}
@do{
(define-values (hi lo lo-dateA lo-dateB) (values 424 415.74 2022.708 2023.708))
(define p (abs (- lo-dateA lo-dateB)))
(define a 4.13)
(define b 6.28)
(define c 419.87)
(define d 2023.1)
}

@link-instructions{
This page focuses on the `modern-table` of the @starter-file{alg2-hybrid}, which tracks atmospheric @COtwo (parts per million) from 2010-2023.
}

[.no-flex-section]
== Decomposing Your Periodic Model

Find the section of the starter file where you're asked to "Define your periodic sin functions..."

- Define `periodic-sin` to be the periodic model you found  @printable-exercise{periodic3-fitting-models/pages/modeling-recent-co2.adoc}. (You could also copy it from @starter-file{alg2-co2}.)  
- Using the deconstruction of `periodic-cos` as your model, change the four functions to show how to separate the wave and midline of your periodic model.

== Fitting the Optimal Linear Model

@n Use `lr-plot` to find the best linear model for the `modern-table` and record the function below:

@indented{@show{(code '(define (linear-modern x) (+ (* (?ANS 2.41263) x)(?ANS -4461))))}}

@n Change the `linear-modern` function in the starter file to match the function above. Then complete the interpretation stem below.

@indented{
__The @vocab{S-value} predicts an error of about__
@fitbruby{3em}{@ifsoln{2.27}}{S}
@fitbruby{3em}{@ifsoln{ppm}}{y-units}, _which range from_
@fitbruby{7em}{@ifsoln{387.03}}{lowest y-value} _to_
@fitbruby{7em}{@ifsoln{424}}{highest y-value} _in this dataset_.
}

== Fitting your Periodic Model
@n Use `fit-model` to fit `periodic-sin` to the data in the `modern-table`, and complete the interpretation stem below.

@indented{
__The @vocab{S-value} predicts an error of about__
@fitbruby{2em}{@ifsoln{17.76}}{S}
@fitbruby{3em}{@ifsoln{ppm}}{y-units}, _which range from_
@fitbruby{6em}{@ifsoln{387.03 ppm}}{lowest y-value} _to_ 
@fitbruby{6em}{@ifsoln{424 ppm}}{highest y-value} _in this dataset_.

@show{(code '(define (linear-modern x) (+ (* (?ANS 2.41263) x)(?ANS -4461))))}
}

@n Change the `linear-modern` function in the starter file to match the function above. Then complete the interpretation stem below.

[cols="3a, .^1a", frame="none"]
|===
|
*This model predicts* a(n)
@fitbruby{7em}{@ifsoln{decrease}}{increase/decrease} of
@fitbruby{5em}{@ifsoln{2.41263}}{rate of change}
@fitbruby{10em}{@ifsoln{@math{CO_2} (ppm)}}{y-units} every
@fitbruby{5em}{@ifsoln{year}}{x-units}.

*When fit to this data, the model's error* is described by an @vocab{S-value} of about
@fitbruby{3em}{@ifsoln{2.27}}{S-value}
@fitbruby{10em}{@ifsoln{@math{CO_2} (ppm)}}{y-units}. I
@fitbruby{18em}{@ifsoln{agree}}{strongly agree, agree, disagree, strongly disagree} that this model is a good fit, since
@fitbruby{10em}{@ifsoln{@math{CO_2} (ppm)}}{y-units} in this dataset ranges from about
@fitbruby{7em}{@ifsoln{387.03}}{lowest y-value} to
@fitbruby{7em}{@ifsoln{424}}{highest y-value}.

|
@ifnotsoln{@center{@image{../images/modern-co2-scatter.png}}}
@ifsoln{@center{@image{../images/modern-lr.png}}}
|===

== Fitting your Periodic Model
@n Change the `periodic-sin` function in the starter file to match what you found on @printable-exercise{periodic3-fitting-models/pages/modeling-recent-co2.adoc}.

@n Use `fit-model` to fit `periodic` to the data in the `modern-table`, and complete the interpretation stem below.

[cols="3a, .^1a", frame="none"]
|===
|
*When fit to this data, the model's error* is described by an @vocab{S-value} of about
@fitbruby{3em}{@ifsoln{17.76}}{S-value}
@fitbruby{10em}{@ifsoln{@math{CO_2} (ppm)}}{y-units}. I
@fitbruby{18em}{@ifsoln{disagree}}{strongly agree, agree, disagree, strongly disagree}
that this model is a good fit, since
@fitbruby{10em}{@ifsoln{@math{CO_2} (ppm)}}{y-units} in this dataset range from
@fitbruby{7em}{@ifsoln{387.03 ppm}}{lowest y-value} to
@fitbruby{7em}{@ifsoln{424 ppm}}{highest y-value}.

|
@ifnotsoln{@center{@image{../images/modern-co2-scatter.png}}}
@ifsoln{@center{@image{../images/modern-co2-model-soln.png}}}
|===

== Comparing Models

@n How much
@fitbruby{5em}{@ifsoln{less}}{more / less }
error do we expect in predictions made with the `linear` model than with the `periodic` model?

@vspace{1ex}

@scrub{
A note for future authors:
- {&#8192;} is used below to add horizontal space.
- \mbox{} is used to make the words in the fraction use normal font.
}

@indented{
_Percent Change_ &#8192; = &#8192;
@math{
\frac{&#8192; \mbox{Difference} &#8192; \mbox{between} &#8192; \mbox{the} &#8192; \mbox{S-values}&#8192;}
{\mbox{S-value} &#8192; \mbox{for} &#8192; \mbox{linear} &#8192; \mbox{model}}
\times 100 &#8192; = &#8192; }
@ifnotsoln{@math{\frac{\qquad}{\qquad}}}
@ifsoln{@math{\frac{15.49}{17.76} = 0.87  &#8192; &rarr; &#8192;  ~87 \%}}

We expect 
@fitb{4em}{@ifsoln{~87}} percent
@fitbruby{5em}{@ifsoln{less}}{ more / less }
error from predictions made with the `linear` model than with the `periodic` model!
}

== Imagining the _Best Possible_ Model

@n Sketch the _best possible model_ you can imagine for this data on the right, and describe it on the left. Do parts of it look linear? Quadratic? Exponenital? Logarithmic? Periodic?

[cols="3a, .^1a", frame="none"]
|===
| @fitb{}{} +
  @fitb{}{} +
  @fitb{}{} +
  @fitb{}{} +

|
@ifnotsoln{@center{@image{../images/modern-co2-scatter.png}}}
@ifsoln{@center{@image{../images/modern-hybrid.png}}}
|===
