= Modeling Modern Carbon Dioxide Levels
++++ 
<style>

/* Format autonumbering inside the table correctly */
table .autonum::after { content: ')' !important; }

/* Tweak padding to save vertical height */
td, .center { padding: 0 !important; }

/* Make code more visible */
td .codetwo { color: black; background: none; }

/* Shorten fill in the blanks */
.fitb { min-width: 2em; padding-top: 1rem; }
.studentAnswerMedium { min-width: 70pt !important; }
</style>
++++

@define{COtwo}{@math{\text{CO}_2}}
@do{
(define-values (hi lo lo-dateA lo-dateB) (values 424 415.74 2022.708 2023.708))
(define p (abs (- lo-dateA lo-dateB)))
(define a 4.13)
(define b 6.28)
(define c 419.87)
(define d 2023.1)
}

@link-instructions{
This page focuses on the `modern-table` of the @starter-file{alg2-hybrid}, which tracks atmospheric @COtwo (parts per million) from 2010-2023.
}

[.no-flex-section]
== Decomposing Your Periodic Model

Find the section of the starter file where you're asked to "Define your periodic sin functions..."

- Define `periodic-sin` to be the periodic model you found  @printable-exercise{periodic3-fitting-models/pages/modeling-recent-co2.adoc}. (You could also copy it from @starter-file{alg2-co2}.)  
- Using the deconstruction of `periodic-cos` as your model, change the four functions to show how to separate the wave and midline of your periodic model.

== Fitting the Optimal Linear Model

@n Use `lr-plot` to find the best linear model for the `modern-table` and record the function below:

@indented{@show{(code '(define (linear-modern x) (+ (* (?ANS 2.41263) x)(?ANS -4461))))}}

@n Change the `linear-modern` function in the starter file to match the function above. Then complete the interpretation stem below.

@indented{
__The @vocab{S-value} predicts an error of about__
@fitbruby{3em}{@ifsoln{2.27}}{S}
@fitbruby{3em}{@ifsoln{ppm}}{y-units}, _which range from_
@fitbruby{7em}{@ifsoln{387.03}}{lowest y-value} _to_
@fitbruby{7em}{@ifsoln{424}}{highest y-value} _in this dataset_.
}

== Fitting your Periodic Model
@n Use `fit-model` to fit `periodic-sin` to the data in the `modern-table`, and complete the interpretation stem below.

@indented{
__The @vocab{S-value} predicts an error of about__
@fitbruby{2em}{@ifsoln{17.76}}{S}
@fitbruby{3em}{@ifsoln{ppm}}{y-units}, _which range from_
@fitbruby{6em}{@ifsoln{387.03 ppm}}{lowest y-value} _to_ 
@fitbruby{6em}{@ifsoln{424 ppm}}{highest y-value} _in this dataset_.
}

== Imagining the Best Possible Model

@n Sketch the linear and periodic models you built above on the corresponding scatter plots below. Then consider: What if we weren't limited to choosing between linear, quadratic, exponential, logarithmic and periodic models...sketch the model you think would best fit the data!

@vspace{1ex}

[cols="^1a,^1a,^1a", options="header"]
|===
| Optimal Linear Model
| My Periodic Model
| Best Possible Model I can Imagine
|@ifnotsoln{@center{@image{../images/modern-co2-scatter.png}}}
@ifsoln{@center{@image{../images/modern-lr.png}}}
|@ifnotsoln{@center{@image{../images/modern-co2-scatter.png}}}
@ifsoln{@center{@image{../images/modern-co2-model-soln.png}}}
|@ifnotsoln{@center{@image{../images/modern-co2-scatter.png}}}
@ifsoln{@center{@image{../images/modern-hybrid.png}}}
|===
