= Modeling Modern Carbon Dioxide Levels
++++ 
<style>

/* Format autonumbering inside the table correctly */
table .autonum::after { content: ')' !important; }

/* Tweak padding to save vertical height */
td, .center { padding: 0 5px !important; }

/* Make code more visible */
td .codetwo { color: black; background: none; }

/* Shorten fill in the blanks */
.fitb { min-width: 2em; padding-top: 1rem; }
.studentAnswerMedium { min-width: 70pt !important; }
</style>
++++

@define{COtwo}{@math{\text{CO}_2}}
@do{
(define-values (hi lo lo-dateA lo-dateB) (values 424 415.74 2022.708 2023.708))
(define p (abs (- lo-dateA lo-dateB)))
(define a 4.13)
(define b 6.28)
(define c 419.87)
(define d 2023.1)
}

@link-instructions{
For this page, we are going to work with the data in the `modern-table` of the @starter-file{alg2-hybrid}, which tracks the amount of @COtwo in the atmosphere (parts per million) from 2010 to 2023.
}

== Fitting a Linear Model

@n Use `lr-plot` to find the best linear model for the `modern-table` and record the function below (in Pyret and Function Notation):

@vspace{1ex}

@indented{
[cols="1a, 5a", frame="none", stripes="none", grid="none"]
|===
.^| *Function Notation*
|
@math{\text{linear}(x) =} @fitbruby{70pt}{@ifsoln{2.41263}}{slope}x {nbsp} + {nbsp} @fitbruby{10em}{@ifsoln{-4461}}{y-intercept / vertical shift}

.>| *Pyret Notation*
| @show{(code '(define (linear x) (+ (* (?ANS 2.41263) x)(?ANS -4461))))}
|===
}

@n Update the definition for `linear-modern` in the starter file. Then complete the interpretation stem below.

@indented{
__**This model predicts** that we'll see a(n) __
@fitbruby{7em}{@ifsoln{decrease}}{increase/decrease} _of_
@fitbruby{5em}{@ifsoln{2.41263}}{rate of change}
@fitbruby{20em}{@ifsoln{parts per million of @math{CO_2} in the atmosphere}}{x-variable} _every_
@fitbruby{4em}{@ifsoln{year}}{x-units}.

__**The error in the model** is described by an @vocab{S-value} of about__
@fitbruby{3em}{@ifsoln{2.27}}{S}
@fitbruby{3em}{@ifsoln{ppm}}{y-units}. @hspace{1em} _I_
@fitbruby{18em}{@ifsoln{agree}}{strongly agree, agree, disagree, strongly disagree} _that this model is a good fit considering that_
@fitbruby{7em}{@ifsoln{@math{CO_2} levels}}{y-variable} _in this dataset range from_
@fitbruby{7em}{@ifsoln{387.03}}{lowest y-value} _to_
@fitbruby{7em}{@ifsoln{424}}{highest y-value}.__
}

== Fitting your Periodic Model
@link-instructions{Make sure you've updated the @starter-file{alg2-hybrid} so that `periodic` matches what you found on @printable-exercise{periodic3-fitting-models/pages/modeling-recent-co2.adoc}}.

[cols="5a, 4a", grid="none", frame="none"]
|===
|@n Use `fit-model` to fit your `periodic` model to the data in the `modern-table` and _sketch it_ on the scatter plot to the right.

@vspace{1ex}

@n Complete the interpretation stem below.

@vspace{1ex}

@indented{
__**The error in the model** is described by an @vocab{S-value} of about__ +
@fitbruby{2em}{@ifsoln{17.76}}{S}
@fitbruby{3em}{@ifsoln{ppm}}{y-units}. @hspace{1em} _I_
@fitbruby{17em}{@ifsoln{disagree}}{strongly agree, agree, disagree, strongly disagree}
_that this model is a good fit considering that_
@fitbruby{5em}{@ifsoln{@math{CO_2}}}{y-variable} _in this dataset ranges from about_
@fitbruby{6em}{@ifsoln{387.03 ppm}}{lowest y-value} _to_ 
@fitbruby{6em}{@ifsoln{424 ppm}}{highest y-value}.
}

| @ifnotsoln{@center{@image{../images/modern-co2-scatter.png, 300}}}
@ifsoln{@center{@image{../images/modern-co2-model-soln.png, 300}}}
|===

== Comparing Models

@n Which model is better, the `linear` model or the `periodic` model? @fitb{}{@ifsoln{linear}}

@n How much
@fitbruby{5em}{@ifsoln{less}}{more / less }
error do we expect in predictions made with the `linear` model than with the `periodic` model?

@vspace{1ex}

@scrub{
A note for future authors:
- {&#8192;} is used below to add horizontal space.
- \mbox{} is used to make the words in the fraction use normal font.
}

@indented{
_Percent Change_ &#8192; = &#8192;
@math{
\frac{&#8192; \mbox{Difference} &#8192; \mbox{between} &#8192; \mbox{the} &#8192; \mbox{S-values}&#8192;}
{\mbox{S-value} &#8192; \mbox{for} &#8192; \mbox{linear} &#8192; \mbox{model}}
\times 100 &#8192; = &#8192; }
@ifnotsoln{@math{\frac{\qquad}{\qquad}}}
@ifsoln{@math{\frac{15.49}{17.76} = 0.87  &#8192; &rarr; &#8192;  ~87 \%}}

We expect 
@fitb{4em}{@ifsoln{~87}} percent
@fitbruby{5em}{@ifsoln{less}}{ more / less }
error from predictions made with the `linear` model than with the `periodic` model!
}

== Imagining the Best Possible Model

What if we weren't limited to choosing between linear, quadratic, exponential, logarithimic and periodic models...

@n Describe what the best possible for this data would look like: @fitb{}{}

@fitb{}{@ifsoln{Hopefully students will describe a wave that follows the line of best fit.}}

@fitb{}{}
