= Identifying Threats to Validity

The animal shelter wanted to find out what kind of food to buy for their animals. They took a random sample of two animals and the food they eat, and they found that spider and rabbit food was by far the most popular cuisine!

@vspace{5ex}

What are some possible threats to the validity of this conclusion?

@span{.blankline}{_Two animals is _not_ large enough to be a representative sample!_}

@span{.blankline}{_It's too easy to randomly choose animals that give us unreliable conclusions._}

@span{.blankline}{_The sample size is too small to be representative._}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@vspace{10ex}
A volunteer opens the shelter in the morning and walks all the dogs. At mid-day, another volunteer feeds all the dogs and walks them again. In the evening, a third volunteer walks the dogs a final time and closes the shelter. The volunteers report that the dogs are much friendlier and more active at mid-day, so the shelter staff assume the second volunteer must be better with animals then the others.

@vspace{5ex}

What are some possible threats to the validity of this conclusion?

@span{.blankline}{_There may be several confounding variables here. Perhaps the volunteer is carrying bacon in their pocket!_}

@span{.blankline}{_Or perhaps dogs are in better moods in the middle of the day, when the sun is out..._}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}
