= Compound Inequalities: Solutions & Non-Solutions

For each Compound Inequality listed below, identify 4 _solutions_ and 4 _non-solutions_.  _If there are *no solutions* or the solution set includes *all real numbers* you can write that instead of making a list._

* Solutions for @vocab{intersections}, which use *and* will make both of the expressions `true`.

* Solutions for @vocab{unions}, which use *or* will make at least one of the expressions `true`.

The most critical numbers to understand are the ones used to define the expressions. Make sure to decide whether each of these is a solution or non-solution.

@vspace{1ex}

[.center]
_The first two have been done for you - Answers will vary!_

[cols="2, 4, 4", options="header", frame="none"]
|===
| Expression				|4 solutions: return `true`				| 4 non-solutions: return `false`

|`x > 5` and `x < 15`		| 6, 9.5, 12, 14.9						| -2, 5, 15, 16.1 

|`x > 5` or `x < 15`		| *All real numbers* 					|	*No non-solutions*

|`x <= -2` and `x > 7` 		| _No solution_							| _All real numbers_

|`x <= -2` or `x > 7` 		| -2, -3.6, 8, 1000						|7, -1, 0, 5

|`x < 3.5` 	and `x > -4`	| -3.5, 0, 1, 3							| 3.5, -4, -8, 400

|`x < 3.5` 	or `x > -4`		| _All real numbers_					| _No non-solutions_

|`x >= -1` and `x > -5` 	| -1, 0, 23, 400						| -3, -5, -10, -542

|`x >= -1` or `x > -5` 		| -4.5, -3, -1, 100						| -5, -6, -28, -1000

|`x < -4` and `x > 2`		| _No solution_							| _All real numbers_

|===
