= Creating Functions 3

@lesson-description{Students apply their skills in using the Design Recipe and writing purpose statements to a variety of word problems.}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Understand how to use the @vocab{Design Recipe} to break down simple word problems.
* Create a strong @vocab{purpose statement} that details in their own words what the @vocab{function} is doing.

|Student-Facing Lesson Goals
|
* I can use the Design Recipe to break down word problem when writing a function.
* I can identify @vocab{domain} and @vocab{range} and other quantities in a word problem when writing a function.
* I can create and revise a strong purpose statement that explains what the function is doing.

|Key Points for the Facilitator
|

* The purpose statement, like the contract, is a comment - something that the computer doesn't read.  It's important for readability of their code - there may be other people looking at their code and using their functions!
* Remind students that the domain and range are @vocab{data types}(Number, String, Image).
* If students struggle with creating the examples, go back to the Circle of Evaluation mapping activity in Creating Functions 2

|Prerequisites
|

* Students should be familiar with Circles of Evaluation.
* Students should be familiar with defining values.
* Students should be familiar wih the Design Recipe.

|Materials
|

* @link{https://docs.google.com/presentation/d/1jZ42nPILZIrv0FWiAh7h7tWVQcJ1r6_DxzlDOXXDo_s/view, Google Slides} for this lesson.
* Design Recipe worksheet (@worksheet-link{workbook-pages/DesignRecipe1.pdf, PDF}, @link{https://docs.google.com/document/d/1GQw-EJAw54BK04SMp_4jPtGGt4IojsUA7oXfz9TRm8Y/view, Google Doc})

* Purpose Statement - 3 Reads/Stronger & Clearer(@worksheet-link{workbook-pages/PurposeStatement3ReadsStrongerClearer.pdf, PDF}, @link{https://docs.google.com/document/d/16xiKkaB6GYUv95ug7-o3QubnmX7oZnm03J1AJTtH_2k/view, Google Doc})

* Word Problems - (@worksheet-link{workbook-pages/WordProblems.pdf, PDF}, @link{https://docs.google.com/document/d/1KpmYVJ9LdPyYeg839jEYotvMIbXx3urgIr8ZvRR3flw/view, Google Doc}) 

Bootstrap Formative Assessments


* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcaf7db4b8576069fdccd5, Bootstrap Algebra: Design Recipe} (Desmos Activity)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcaf49b4b8576069fdcc38, Bootstrap Algebra: Design Recipe Practice(Blank Template)} (Desmos Activity)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb07bb4b8576069fdcef1, Bootstrap: Algebra - More Design Recipe Practice} (Desmos Activity)

Connecting Activities

* @link{https://teacher.desmos.com/expressions, Expression Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/modeling, Mathematical Modeling Bundle} (Desmos Activities)
* @link{https://quizizz.com/admin/quiz/576d1e5f91cb32ef5fc67529/variables-and-expressions, Variables and Expressions} (Quizizz)
* @link{https://teacher.desmos.com/functions, Functions Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/polygraph/custom/560ad28e9e65da5615091edb, Functions & Relations} (Desmos Polygraph Activity)
* @link{https://quizizz.com/admin/quiz/582b7390e8e0c0c201647d9d/functions, Functions} (Quizizz)
* @link{https://quizizz.com/admin/quiz/582f0e34b805cc5c6608d326/function-notation, Function Notation} (Quizizz)
* @link{https://teacher.desmos.com/linear, Linear Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/quadratic, Quadratics Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/quadratic, Exponential Bundle} (Desmos Activities)
* @link{https://quizizz.com/admin/quiz/5a0f3d001699791000871e2a/linear-equations, Linear Equations} (Quizizz)
* @link{https://quizizz.com/admin/quiz/5ad0d3f700e91d0019307fc3/quadratic-equations, Quadratic Equations} (Quizizz)
* @link{https://quizizz.com/admin/quiz/59024aa95af2ad1000a10719/linear-exponential-and-quadratic-functions, Linear, Quadratic, and Exponential Equations]} (Quizizz)

|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Addressing
|
* @std{8.F.B}

|Approaching
|
* @std{HSF.BF.A.1}

|Standards for Mathematical Practice
|
* @std{MP.1}
* @std{MP.7}

|Bootstrap Benchmarks
|
* @std{BS-DR.1}
* @std{BS-DR.2}
* @std{BS-DR.3}

|===


== Get Ready:

Students should have their workbook and contracts page, a pencil, and their computers with a @link{https://www.wescheme.org, WeScheme} tab that they're logged into.

== Practice: (45 min)
This lesson is all about getting more reps and more practice with the Design Recipe and writing Purpose Statements.

Use the @worksheet-link{workbook-pages/PurposeStatement3ReadsStrongerClearer.pdf, Purpose Statement(3 Reads/Stronger And Clearer)} and the @worksheet-link{workbook-pages/DesignRecipe1.pdf, Design Recipe} workseets to work through several of the Word Problems from this @worksheet-link{workbook-pages/WordProblems.pdf, worksheet}.

[.strategy-box]
.Strategies for English Language Learners
****
MLR 6: 3 Reads 
In pairs, the word problem is read 3 times. Students will document their work in the "3 Reads/Stronger & Clearer" handout.

* 1st Read: Teacher reads the word problem. Without any pencil or pen, students discuss: What is the problem about? 
* 2nd Read: Partner A reads. Students discuss: What are the quantities?
* 3rd Read: Partner B reads. What is a good purpose statement?
****

[.strategy-box]
.Strategies for English Language Learners
****
MLR 1: Stronger and Clearer Each Time 
Using the "3 Reads/Stronger & Clearer" handout, students will switch partners 3 times.

* 1st new partner: Read their purpose statements to each other & revise the purpose statement to be stronger and clearer.
* 2nd new partner: Repeat.
* 3rd new partner: Repeat.
****

Write 2 EXAMPLES & The Definition

* Given the contract and purpose statement, write 2 examples of `rocket-height`.
* Circle and label what's changing in the 2 examples. What is a good variable name for what's changing?
* Write the `define` line of code that uses the decided upon variable name.
* Once the enter Design Recipe has been completed in the workbook, and the teacher has checked it for accuracy, students should type the code into the program to test and fix the `rocket-height` function.
