= Creating Functions 3

@lesson-description{Students will get more practice using The Design Recipe and writing Purpose Statements}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Understand how to use the Design Recipe to breakdown simple word problems.
* Create a strong purpose statement that details in their own words what the function is doing.

|Student-Facing Lesson Goals
|
* I can use The Design Recipe to breakdown word problem when writing a function.
* I can identify the Domain and Range and other quantities in a word problem when writing a function.
* I can create and revise a strong purpose statement that explains what the function is doing.

|Key Points for the Facilitator
|

* Remind students that The Purpose Statement, like the Contract is a comment and that it's really important for readability of their code because there may be other people looking at their code and using their functions.
* Remind students that the Domain and Range are data types(Number, String, Image)
* If students struggle with creating the examples, go back to the Circle of Evaluation mapping activity in Creating Functions 2

|Prerequisites
|

* Students should be familiar with Circles of Evaluation.

|Materials
|

* https://docs.google.com/presentation/d/1jZ42nPILZIrv0FWiAh7h7tWVQcJ1r6_DxzlDOXXDo_s/edit?usp=sharing[Google Slides]
* https://docs.google.com/document/d/1GQw-EJAw54BK04SMp_4jPtGGt4IojsUA7oXfz9TRm8Y/edit[Design Recipe] handout
* https://docs.google.com/document/d/16xiKkaB6GYUv95ug7-o3QubnmX7oZnm03J1AJTtH_2k/copy[Purpose Statement - 3 Reads/Stronger & Clearer]
* https://docs.google.com/document/d/1KpmYVJ9LdPyYeg839jEYotvMIbXx3urgIr8ZvRR3flw/edit[Word Problem] handout

Bootstrap Formative Assessments

* https://teacher.desmos.com/activitybuilder/custom/5a15e2907915bd2fd51a65bc[Unit 4 Bootstrap Algebra Review] (Desmos Activity)
* https://teacher.desmos.com/activitybuilder/custom/5a2f2c2e532d241d732593db[Unit 4: Design Recipe Practice - Blank Template] (Desmos Activity)

Connecting Activities

* https://teacher.desmos.com/functions[Functions Bundle] (Desmos Activities)
* https://teacher.desmos.com/polygraph/custom/560ad28e9e65da5615091edb[Functions & Relations] (Desmos Polygraph Activity)
* https://quizizz.com/admin/quiz/582b7390e8e0c0c201647d9d/functions[Functions] (Quizizz)
* https://quizizz.com/admin/quiz/582f0e34b805cc5c6608d326/function-notation[Function Notation] (Quizizz)
|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Math Standards (CCSS)
|
* http://www.corestandards.org/Math/Practice/MP2[CCSS.MATH.PRACTICE.MP2],
Reason abstractly and quantitatively.
* 7.EE.B @{7.EE.B}
* 7.EE.B.3 @{7.EE.B.3}
* 7.EE.B.4 @{7.EE.B.4}
* HSA.SSE.A.1 @{HSA.SSE.A.1}
* HSA.SSE.A.2 @{HSA.SSE.A.2}
* HSF.BF.A @{HSF.BF.A}
* HSF.IF.A.1 @{HSF.IF.A.1}



|CS Standards (CSTA)
|
* CS Standards here.
|===




== Get Ready:

Students should have their workbook and contracts page, a pencil, and their computers with a https://www.weschem.org[WeScheme] tab that they're logged into.

== Practice: (45 min)
This lesson is all about getting more reps and more practice with the Design Recipe and writing Purpose Statements.

Use this https://docs.google.com/document/d/16xiKkaB6GYUv95ug7-o3QubnmX7oZnm03J1AJTtH_2k/copy[Purpose Statement - 3 Reads/Stronger] handout to work through several of the Word Problems from this https://docs.google.com/document/d/1KpmYVJ9LdPyYeg839jEYotvMIbXx3urgIr8ZvRR3flw/edit[handout].

[.strategy-box]
.Strategies for English Language Learners
****
MLR 6: 3 Reads 
In pairs, the word problem is read 3 times. Students will document their work in the "3 Reads/Stronger & Clearer" handout.

* 1st Read: Teacher reads the word problem. Without any pencil or pen, students discuss: What is the problem about? 
* 2nd Read: Partner A reads. Students discuss: What are the quantities?
* 3rd Read: Partner B reads. What is a good purpose statement?
****

[.strategy-box]
.Strategies for English Language Learners
****
MLR 1: Stronger and Clearer Each Time 
Using the "3 Reads/Stronger & Clearer" handout, students will switch partners 3 times.

* 1st new partner: Read their purpose statements to each other & revise the purpose statement to be stronger and clearer.
* 2nd new partner: Repeat.
* 3rd new partner: Repeat.
****

Write 2 EXAMPLES & The Definition

* Given The Contract and Purpose statement, write 2 examples of `rocket-height`
* Circle and Label what's changing in the 2 examples. What's a good variable name for what's changing?
* Write the `define` line of code that uses the decided upon variable name.
* Once the enter Design Recipe has been completed in the workbook, and the teacher has checked it for accuracy, then allow the students to type the code into the program to fix the `rocket-height` function.
