= Measures of Center

// use double-space before the *bold* text to address a text-kerning bug in wkhtmltopdf 0.12.5 (with patched qt)
There are three ways to measure the “center” of a dataset, to summarize a whole column of data using just one number:

* The *mean* of a dataset is the average of all the numbers.

* The *median* of a dataset is a value that is smaller than half the dataset, and larger than the other half.

* The *mode(s)* of a dataset is the value (or values) that occurs most often.

	- In a  *symmetric* data set, values are just as likely to occur a certain distance above or below the mean, and the median and mean are usually close together. 

	- A data set with *left skew*, and/or low outliers, has a few values that are unusually low, pulling the mean _below_ the median.

	- A data set with *right skew*, and/or high outliers, means there are a few values that are unusually high, pulling the mean _above_ the median.

Data Scientists can also measure the  *spread* of a dataset using a  *five-number summary*:

	- The *minimum* – the smallest value in the dataset

	- The *first, or “lower” quartile (Q1)* – the middle of the smaller half of values which separates the smallest quarter from the next smallest quarter.

	- The *second quartile (Q2)* – the median value which separates the entire dataset into “top” and “bottom” halves.

	- The *third, or “upper” quartile (Q3)* – the middle of the larger half of values which separates the second largest quarter from the largest quarter.

** The *maximum* – the largest value in the dataset.

- The *five-number summary* can be used to draw a *box-and-whisker plot*.

@centered-image{box-n-whisker-plot.png, "", 400, align="center"}
