= Teacher Resources for Algebra

== Let's Get Started
- *Online Community* [@link{https://discourse.bootstrapworld.org, Discourse}] -- Talk with other Bootstrap teachers, ask questions, and share ideas!
- *Remote Instruction* [@dist-link{ImplementationNotes.shtml, link}] -- specific recommendations for in-person v. remote instruction.
- *Poster Set for Classroom Walls* [@lesson-link{computing-needs-all-voices/pages/computing-pioneers.adoc, link}] -- This poster set features Pioneers in Computing and Mathematics. For greater impact, engage your students with these materials using our @lesson-link{computing-needs-all-voices} lesson. (You can also @link{https://www.printme1.com/1100aa4996, purchase a printed set yourself!})
- *Information for Families about Bootstrap:Algebra* [@link{pages/info-for-families-alg.adoc, link}]

=== Standalone Hour of Code Activities from Bootstrap

- *Hour of Data* [@lesson-link{hoc-data/, link}] -- A self-guided Desmos activity for exploring a real dataset to make sense of a real-world problem.
- *Snowman Puzzle* [@link{https://www.wescheme.org/openEditor?publicId=tt8HB7mig9, link}] -- This WeScheme Starterfile has all the pieces your students will need to make a snowman by changing the coordinates in the code.

== Exercises and Solutions
@all-exercises

== Notes, Slides, and Starter Files
@lesson-info

== Projects in Bootstrap:Algebra

The Bootstrap:Algebra curriculum includes three mini projects, each designed to span 2-5 class periods. Projects allow students to express their creativity while showcasing their math and programming skills.

- @lesson-link{project-logo, "Create Your Own Logo"}
- @lesson-link{project-flags, "Make a Flag"}
- @lesson-link{project-function, "Create Your Own Function"}

@lesson-link{project-video-game, "Building an original video game"} is the (optional) capstone project for Bootstrap Algebra. This project involves all of the various algebra and programming concepts covered in the lessons, providing students with a creative way to demonstrate their mastery of the material.

== Other Curricular Materials

- *Contracts* [@link{solution-pages/Contracts.pdf, PDF}] -- for teachers who want only the contracts reference from the back of the student workbook, without using the entire book.
- *Glossary* [@dist-link{Glossary.shtml?pathway=algebra-wescheme, link}] -- All of the vocabulary words (and their definitions) used in this pathway.
- *Bilingual Glossary of Bootstrap Terms (English-Spanish)* [@dist-link{lib/bilingual-glossary.html, PDF}] -- For teachers with ELL/ESL students, we provide a bilingual glossary for all of the terms used across our curriculum library.
- *Blank Design Recipe Worksheet* -- [@dist-link{pages/2-blank-wescheme-recipes.adoc, html}] -- Use alongside story problems for a function development template.
- *Design Recipe Rubric* [@dist-link{lessons/functions-dr/pages/rubric-dr.adoc, html}]
- *Collection of Bootstrap:Algebra Desmos Activities* [@link{https://teacher.desmos.com/collection/5fbecc2b40d7aa0d844956f0, link}]
- *About Notice and Wonder pedagogy* [@dist-link{pages/notice-wonder.pdf, PDF}]
- *Game Templates*
 * @starter-file{game}
 * @starter-file{sample-game}
 * @starter-file{sample-game-w-distance}
 * @starter-file{sample-game-2d}

== Textbook Alignment
We offer alignment guides for several popular math textbooks, which make it easy to adopt Bootstrap as part of your normal scope and sequence. These guides are available for:

- Illustrative Math (Grade 6) -- [@link{../../../textbooks/IM-grade-6.html, HTML}, @link{../../../textbooks/IM-grade-6.pdf, PDF}]
- Illustrative Math (Grade 7) -- [@link{../../../textbooks/IM-grade-7.html, HTML}, @link{../../../textbooks/IM-grade-7.pdf, PDF}]
- Illustrative Math (Grade 8) -- [@link{../../../textbooks/IM-grade-8.html, HTML}, @link{../../../textbooks/IM-grade-8.pdf, PDF}]
- Illustrative Math (HS) -- [@link{../../../textbooks/IM-HS.html, HTML}, @link{../../../textbooks/IM-HS.pdf, PDF}]
- Connected Mathematics -- CMP3 (Grade 6) -- [@link{../../../textbooks/cmp-grade-6.html, HTML}, @link{../../../textbooks/cmp-grade-6.pdf, PDF}]
- Connected Mathematics -- CMP3 (Grade 7) -- [@link{../../../textbooks/cmp-grade-7.html, HTML}, @link{../../../textbooks/cmp-grade-7.pdf, PDF}]
- Connected Mathematics -- CMP3 (Grade 8) -- [@link{../../../textbooks/cmp-grade-8.html, HTML}, @link{../../../textbooks/cmp-grade-8.pdf, PDF}]

== Videos for Teachers
Developed in partnership with @link{https://www.code.org, Code.org}. *NOTE:* these were developed using our earlier, 9-unit format. The content is still applicable, so we continue to provide these resources.

//Embed 10 videos here
[cols="30a,30a,30a", stripes=none]
|===
| *Modeling and Coordinates*

video::hy3SKXANmSQ[youtube]

| *Order of Operations*

video::ObJ0Aawc9s4[youtube]

| *Domain and Range*

video::yW9XLaY5i8A[youtube]

| *Defining Values*

video::bOIs2DyMUv8[youtube]

| *Introducing The Design Recipe*

video::Yf5w56PpaTw[youtube]

| *Using The Design Recipe*

video::e5ORR9LpgkU[youtube]

| *Boolean Logic & Inequalities*

video::XjT-PdWmvtE[youtube]

| *Piecewise Functions*

video::DYrd_xaTKYU[youtube]

| *The Pythagorean Theorem*

video::35UgYAPkNcc[youtube]

| *Why Is Algebra So Hard?*

video::0t3Q_syA0Mk[youtube]

|

|

|===

