= Keeping NinjaCat in the Game

@vspace{2ex}

@span{.center}{@image{../images/NinjaCat.png, "A screenshot of the NinjaCat videogame. The bottom left corner is labeled (0,0). The bottom right corner is labeled (640,0). The top left corner is labeled (0, 480). Visible on the screen are ninja cat in the lower left, clouds in the upper left, a dog on the lower right, and a ruby in the upper right.", 600}}

After each jump, Ninjacat lands at the bottom of the screen. It wouldn't be much fun if Ninjacat kept falling past the bottom of the screen and couldn't be seen anymore!

@vspace{2ex}

@n What changes as Ninjacat moves up and down? @fitb{}{@ifsoln{_the y-coordinate_}}
@vspace{2ex}

*Use the new inequality functions to answer the following questions _with code_:*

@vspace{2ex}

@n Ninjacat is still visible on the bottom of the screen as long as…
@fitb{}{@showsoln{(code '(< y 490)) }}

@vspace{2ex}

@n Ninjacat hasn't gone off the top edge of the screen as long as…
@fitb{}{@showsoln{(code '(< y 490)) }}

@vspace{2ex}

@n Use the space below to draw Circles of Evaluation for these two expressions:

@span{.left }{@showsoln{(coe '(> y 0)) } }

@right{@showsoln{(coe '(< y 490)) } }
