= Sam the Butterfly

++++
<style>
.right{margin-right: 20ex; }
</style>
++++

Open the “Sam the Butterfly” starter file and press “Run”. 

_Hi, Sam!_ 

Move Sam around the screen using the arrow keys.

@vspace{2ex}

1) What do you notice about the program?

@vspace{6ex}

2) What do you wonder?

@vspace{6ex}

3) What do you see when Sam is at (0,0)?  Why is that?

@vspace{6ex}

4) What changes as the butterfly moves left and right? 


@vspace{4ex}

Sam is in a 640 × 480 yard. Sam’s mom wants Sam to stay in sight.

@vspace{2ex}

*How far to the left and right can Sam go and still remain visible?*

@vspace{2ex}

Use the new inequality functions to answer the following questions  _with code_:

@vspace{2ex}

5) Sam hasn't gone off the left edge of the screen as long as…
@span{.right}{@fitb{30ex}{}}

@vspace{2ex}

6) Sam hasn't gone off the right edge of the screen as long as…
@span{.right}{@fitb{30ex}{}}

@vspace{2ex}

7) Use the space below to draw Circles of Evaluation for these two expressions:

@vspace{20ex}