= Defining Rows
++++
<style>
table .autonum::after{ content: ')'; }
table { font-size: 1rem !important; }
table td { padding: 0 !important; }
table td .fitb { padding-top: 0 !important; }
</style>
++++
We've already given you two row definitions: `cat-dog` and `dog-row`:

```
cat-row = row-n(animals-table,  0)  # Sasha is a cat
dog-row = row-n(animals-table, 10) # Toggle is a dog
```

**Remember: rows start at index zero!** Use this to answer the questions below.

@n The index of a row containing a lizard is @fitb{}{}

@n The index of a row containing a rabbit is @fitb{}{}

@n The index of a row containing a fixed animal is @fitb{}{}

@n The index of a row containing a male animal @fitb{}{}

@n The index of a row containing a female animal is @fitb{}{}

@n The index of a row containing a hermaphroditic animal is @fitb{}{}

@n The index of a row containing an unfixed animal is @fitb{}{}

@n The index of a row containing a young animal (<2 years) is @fitb{}{}

@n The index of a row containing an old animal (>10 years) is @fitb{}{}

@n What code would you write to define `lizard-row`?

@fitb{}{}

@n What code would you write to define `rabbit-row`?

@fitb{}{}

@n What code would you write to define `fixed-row`?

@fitb{}{}

@n What code would you write to define `male-row`?

@fitb{}{}

@n What code would you write to define `female-row`?

@fitb{}{}

@n What code would you write to define `hermaphrodite-row`?

@fitb{}{}

@n What code would you write to define `young-row`?

@fitb{}{}

@n What code would you write to define `old-row`?

@fitb{}{}

@center{**Add this code to your Animals Starter File!** You'll want these rows for later!}
