== Numbers and Strings


Make sure you’ve loaded the Animals Starter File, and clicked “Run”.

1. Try typing `42` into the Interactions Area and hitting “Enter”. What happens?
2. Try typing in other Numbers. What happens if you try a decimal
   like `0.5`? A fraction like
`1/3`? Try really big Numbers, and really small ones.
3. String values are always in quotes. Try typing your name (in quotes!). What happens when
you hit Enter?
4. Try typing your name with the opening quote, but _without_ the closing quote. What
happens? Now try typing it without any quotes.
5. Is _42_ the same as `"42"`? Why or why not? Write your answer below:


== Operators

6. Just like in math, Pyret has operators like `+`, `-`, `*` and
   `/`. Try typing in `4 + 2`, and then `4+2`
(without the spaces). What can you conclude from this? Write your answer below:


7. Type in the following expressions, one at a time: `4 + 2 + 6`,
   `4 + 2 * 6`,
`4 + (2 * 6)`. What do you notice? Write your answer below:


8. Try typing in `4 + "cat"`, and then `"dog" + "cat"`. What can you conclude from this?
Write your answer below:

