= Ordre des opérations

++++
<style>
#content .embedded {min-width: 550px; width: 80%; margin: 0px auto;}
</style>
++++

@description{Les élèves apprendront à modéliser des expressions arithmétiques à l'aide d'un outil visuel pour l'ordre des opérations connu sous le nom de « cercle d'évaluation ».}

@lesson-prereqs{}

@keywords{Cercles d'évaluation, PEMDAS, GEMDAS} 

[@lesson-intro-table]
|===

| Objectifs de la leçon
| Les élèves pourront :

*	Modéliser une expression arithmétique en utilisant les @vocab{cercles d'évaluation}.
*	Traduire des cercles d'évaluation en code.

| Objectifs pour les élèves
|
*	Je peux écrire des cercles d'évaluation pour une @vocab{expression} arithmétique donnée.
*	Je peux traduire un cercle d'évaluation en code.
*	Je peux utiliser les nombres et les opérations dans un environnement de programmation.

| Matériel

|[.materials-links]

@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/103WRI5Ynv-sArPXgQQTtbnyyAH1HWRniPyNTn91Wyuo/, Diapositives de la leçon}
}
@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1-Xjz-7HBIx5DP4nc06e6EL6cTX3Fc4bPnYs_ZwdNjP4/, Diapositives de la leçon}
}

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Préparation
| @preparation

| Points clés pour la personne formatrice
 
|
*	Les messages d'erreur sont des indices de l'ordinateur, qui essaie de nous dire que quelque chose ne va pas.	Modélisez la réaction aux @vocab{messages d'erreur} et montrez aux élèves que ces messages sont un outil pratique.
*	Après les premiers exercices de création de cercles d'évaluation, demandez aux élèves s'ils les créent de l'intérieur vers l'extérieur (en dessinant d'abord les cercles intérieurs) ou de l'extérieur vers l'intérieur. Après avoir écouté leurs réponses, demandez-leur d'essayer l'AUTRE façon!
*	Jusqu'à présent, nous ne disposions pas d'un modèle spatial visuel pour _lire_ les expressions arithmétiques. Demandez aux élèves de comparer les cercles d'évaluation aux méthodes précédentes qu'ils ont apprises pour _calculer_ ces expressions (PEMDAS, GEMDAS, etc.)
*	Pour leur donner un aide-mémoire, modélisez l'explication de « l'insecte qui rampe dans le cercle ».
*	Les élèves peuvent bénéficier de l'utilisation de plusieurs couleurs pour distinguer les différentes petites expressions et parenthèses.



|===

[.old-materials]
Cliquez ici pour voir la @link{https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/units/unit1/index.html, version antérieure basée sur le module}.

== Ordre des opérations

=== Aperçu
Les élèves sont confrontés à une expression difficile qui met en évidence des idées fausses courantes sur l'ordre des opérations. L'objectif est de démontrer qu'une compréhension fragile et fixe de l'ordre des opérations est insuffisante. Il faut amener les élèves à une compréhension plus profonde de l'ordre des opérations en tant qu’une sorte d’appareil grammatical. Les cercles d'évaluation sont présentés comme des « schémas de phrases pour l'arithmétique ».

=== Lancement

Les humains utilisent des verbes comme « lancer », « courir », « construire » et « sauter » pour décrire des opérations sur des noms comme « balle », « chiot » et « blocs ». Les mathématiques ont des « opérations » @ifproglang{wescheme}{et des @vocab{fonctions}}, comme l'addition et la soustraction. Tout comme on peut « *lancer* une _balle_ », on peut aussi « *additionner* _quatre_ et _cinq_ ».

Une expression mathématique est une instruction pour faire quelque chose et elle précise les verbes et les noms impliqués. L'expression @smath{(+ 4 5)} nous dit d'additionner 4 et 5. Pour évaluer une expression, il faut suivre les instructions. L'expression @smath{(+ 4 5)} est évaluée à 9.

Si nous devions écrire des instructions pour nous préparer à aller à l'école, il serait très important de savoir quelle instruction vient en premier : mettre ses chaussettes, mettre ses chaussures, etc. Parfois, nous avons besoin d'expressions multiples en mathématiques et l'ordre importe ici aussi!

@right{@image{images/pemdas.png, "Le modèle pyramidal de l'ordre des opérations", 300, ""}}
Les mathématiciens n'ont pas toujours été d'accord sur l'ordre des opérations, mais à un certain moment, il était important d’établir des règles pour qu’ils puissent travailler ensemble.

La pyramide de droite est un modèle pour résumer l'ordre des opérations. Lorsque l'on évalue une expression, on commence par appliquer les opérations écrites au sommet de la pyramide (opérations entre parenthèses et autres symboles de regroupement). Ce n'est qu'après avoir effectué toutes ces opérations que nous pouvons descendre au niveau inférieur. Si les deux opérations du même niveau sont présentes (comme dans @math{4 + 2 - 1}), nous lisons l'expression de gauche à droite, en appliquant les opérations dans l'ordre dans lequel elles s’affichent. Cet ensemble de règles est fragile et ne permet pas toujours de savoir clairement ce que l'on doit faire. Les moyens mnémotechniques pour l'ordre des opérations (comme PEMDAS, GEMDAS, etc.) se concentrent sur la façon d'obtenir la réponse. Ce dont nous avons besoin, c'est d'une meilleure façon de lire les mathématiques.

@lesson-instruction{
Regardez l'expression ci-dessous. Selon vous, quelle est la réponse? Ce problème de maths est devenu viral sur les médias sociaux récemment. Les profs de maths ont fait bien des débats pour trouver la réponse! Pourquoi sont-ils en désaccord sur la solution?
}

++++
<style>
.big, .big p {margin-top: 0px; padding-top: 0px;}
.big .MathJax {font-size: 4em; color: black;}
</style>
++++
@center{@big{@math{6 \div 2(1 + 2)}}}

Au lieu d'utiliser une règle pour calculer les réponses, commençons par schématiser les maths elles-mêmes!

@strategy{Cercles d'évaluation}{


Les cercles d'évaluation sont un outil pédagogique essentiel dans ce cours. Ils mettent l'accent sur la _structure_ des expressions mathématiques afin de combattre la fausse idée des élèves selon laquelle la seule chose qui compte est la _réponse_. Ils peuvent être utilisés pour schématiser des phrases arithmétiques afin d'exposer les fausses idées les plus courantes sur l'ordre des opérations et constituent un excellent moyen d’accompagner les élèves quand ils appliquent l'ordre des opérations incorrectement. Ils sont également une sorte de représentation « pont », c’est-à-dire qui se connecte naturellement à la composition de fonctions et à la conversion d’expressions arithmétiques en code.
}

@lesson-instruction{
Nous pouvons _dessiner la structure_ de cette syntaxe en mathématiques en utilisant ce que l'on appelle les *cercles d'évaluation*. Les règles sont simples :
}

*1) Chaque cercle doit comprendre une SEULE (seulement une!) fonction, écrite en haut.*

Alors, les nombres (par exemple, @math{3}, @math{-29}, @math{77.01}...) sont toujours écrits par eux-mêmes. Ce n'est que lorsque nous voulons _faire une opération_ comme ajouter, soustraire, etc. que nous devons dessiner un cercle.

*2) Les entrées de la fonction sont écrites de gauche à droite, au milieu du cercle.*

Si nous voulons dessiner le cercle d'évaluation de @smath{(/ 6 3)}, la fonction de division (`/`) est écrite en haut, avec le `6` à gauche et le `3` à droite.


@center{@show{(coe '(/ 6 3))}}

Que faire si l'on veut utiliser plusieurs fonctions? Comment dessiner le cercle d'évaluation de @smath{(/ 6 (+ 1 2))}? Le cercle d'évaluation de l’expression @smath{(+ 1 2)} est facile à dessiner. Comment prendre le résultat de ce cercle et diviser 6 par ce résultat?

*3. Les cercles peuvent contenir d'autres cercles.*

En fait, nous remplaçons le 3 de notre premier cercle d'évaluation par un autre cercle, qui ajoute 1 et 2!

@center{@show{(coe '(/ 6 (+ 1 2)))}}

@lesson-instruction{
À quoi ressemblerait le cercle d'évaluation de @math{5 \times 6}?
}

@center{@show{(coe '(* 5 6))}}

@lesson-instruction{
À quoi ressemblerait le cercle d'évaluation de @math{(10 - 5) \times 6}?
}

@center{@show{(coe '(* (- 10 5) 6))}}

En plus de nous aider à détecter les erreurs avant qu'elles ne se produisent, les cercles d'évaluation sont également un moyen utile de réfléchir à la _transformation_ en mathématiques. Par exemple, vous avez peut-être entendu que « l'addition est commutative, donc @smath{(+ a b)} peut toujours s'écrire @smath{(+ b a)}. » Par exemple, @smath{(+ 1 2)} peut être transformé en @smath{(+ 2 1)}.

Supposons qu'un autre élève vous dise que @smath{(+ 1 (* 2 3))} peut être réécrit @smath{(+ 2 (* 1 3))}. C'est évidemment faux, mais
  pourquoi ?

*Prenez un moment pour réfléchir : quel est le problème?* Nous pouvons utiliser les cercles d'évaluation pour le découvrir!

Le premier cercle représente seulement l'expression originale. La deuxième expression représente ce que la transformation de commutativité (incorrecte) nous donne :
[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===

| @show{(coe '(+ 1 (* 2 3)))}
| __ ? __ &rarr;
| @show{(coe '(+ 2 (* 1 3)))}
|===

Dans ce cas-ci, l'élève n'a pas vu la structure  : il a vu le terme à droite du symbole @smath{+} comme @smath{2} au lieu de @smath{(* 2 3)}. Les cercles d'évaluation nous aident à voir la structure de l'expression plutôt que de nous forcer à la construire et à la garder en tête.

=== Mise en application

@lesson-instruction{
Demandez aux élèves d’aller à  @printable-exercise{translate-arithmetic-to-coe-and-code-1-intro-w-parenth.adoc} dans le guide
et de dessiner des cercles d'évaluation pour chacune des expressions. (Ignorez la colonne de code pour l'instant! Nous y reviendrons plus tard.)

Vous pouvez également demander aux élèves de réaliser les exercices  @printable-exercise{complete-coe-from-arith.adoc}, @printable-exercise{match-arith-coe.adoc} et @opt-starter-file{coe-matching, Associer des cercles d'évaluation à des expressions}.
}

@strategy{Remarque pédagogique}{


Les cercles d'évaluation sont un excellent moyen d’amener les élèves plus âgés à réviser (et à enfin comprendre) l'ordre des opérations tout en étant motivés et en se concentrant sur l'apprentissage de la programmation.	Nous reconnaissons l'importance de ce travail et savons que certains enseignants choisissent d'y consacrer une semaine entière. C’est pourquoi nous avons développé de nombreuses ressources supplémentaires pour favoriser l’accompagnement et l'approfondissement. Vous trouverez quelques pages supplémentaires dans le guide et plus de 20 autres liées dans @link{#_additional_exercices, la section Exercices supplémentaires} à la fin de cette leçon.

}

=== Synthèse

- Certains élèves ont-ils préféré travailler de l'extérieur vers l'intérieur plutôt que de l'intérieur vers l'extérieur? Pourquoi?
- Certains élèves ont-ils trouvé que différentes stratégies fonctionnaient mieux pour différents types de problèmes? Si oui, pourquoi? Si non, pourquoi pas?
- Y a-t-il plus d'une façon de dessiner le cercle de @smath{(+ 1 2)}? Si c'est le cas, quelle est la façon la plus « correcte »?

== Traduire des cercles d'évaluation en code

=== Aperçu

Les élèves apprennent à utiliser les cercles d'évaluation pour traduire des expressions arithmétiques en code.

=== Lancement

Lorsque vous convertissez un cercle d'évaluation en code, il est pratique d'imaginer une araignée qui rampe dans le cercle de gauche et ressort du cercle de droite. La première chose que fait l'araignée est de franchir une ligne courbe (une parenthèse ouvrante!). Ensuite, elle se dirige vers l'opération @ifproglang{wescheme}{- aussi appelée la _fonction_ -} en haut. Après cela, elle rampe de gauche à droite et va vers chacune des enrées @ifproglang{wescheme}{de la fonction}. Finalement, elle quitte le cercle en traversant une autre ligne courbe (une parenthèse de fermeture).

@ifproglang{pyret}{
Remarque : Comme en maths, il y des cas où les parenthèses les plus à l’extérieur peuvent être enlevées :

- @math{(1+ 2)} peut être écrit @math{1 + 2} sans problème et il en va de même pour le code Pyret.
- @math{(1 * 2) * 3)} peut être écrit @math{1 * 2 * 3} sans problème et il en va de même pour le code Pyret.

Vous verrez probablement du code écrit en utilisant ce « raccourci », mais il est toujours préférable de commencer par les parenthèses pour s'assurer que votre calcul ou code est correct avant de les retirer. *Il n'est jamais mauvais de les inclure!*
}


[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===

|*Expression*			| &rarr; | @show{(math '(+ 3 8)) }
|*Cercle d'évaluation*	| &rarr; | @show{(coe  '(+ 3 8)) }
|*Code*					| &rarr; | @show{(code '(+ 3 8)) }
|===

@ifproglang{wescheme}{
Toutes les expressions qui suivent le nom de la fonction sont appelées des « arguments » de la fonction. Le schéma suivant résume la forme d'une expression qui utilise une fonction. @center{@image{images/wescheme-code-diagram.fr, "Schéma d’une expression WeScheme", 400}}
}

Les expressions arithmétiques comprenant plus d'une opération se retrouveront avec plus d'un cercle
@ifproglang{wescheme}{et plus d'une paire de parenthèses.} @ifproglang{pyret}{De plus, qu'il y ait ou non des parenthèses dans l'expression originale, le code nécessite des parenthèses pour clarifier l'ordre dans lequel les opérations doivent être effectuées.}

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===

|*Expression*			| &rarr; | @show{(math '(* 2 (+ 3 8))) }
|*Cercle d'évaluation*	| &rarr; | @show{(coe  '(* 2 (+ 3 8))) }
|*Code*					| &rarr; | @show{(code '(* 2 (+ 3 8))) }
|===

@ifproglang{wescheme}{
-	Pourquoi y a-t-il deux parenthèses fermantes une à la suite de l’autre à la fin du code?
-	Si une expression comporte trois séries de parenthèses, combien de cercles d'évaluation pensez-vous avoir besoin?
}

@lesson-instruction{
À quoi ressemblerait le code de ces cercles?
}

[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===

|@show{(coe '(/ 6 (+ 1 2)))}		| @show{(coe '(* (- 10 5) 6))}
|@show{(code '(/ 6 (+ 1 2)))}		| @show{(code '(* (- 10 5) 6))}
|===

=== Mise en application

S’il vous reste du temps, commencez par les deux pages du guide de l'élève qui présentent comment traduire les cercles en code : @printable-exercise{complete-code-from-coe.adoc} et @printable-exercise{match-coe-to-code.adoc}.

@lesson-instruction{
Maintenant que nous savons comment traduire les cercles d'évaluation en code, revenez à @printable-exercise{translate-arithmetic-to-coe-and-code-1-intro-w-parenth.adoc}.
}

@indented{
*Avant de demander aux élèves de compléter le code de cette page, assurez-vous qu'ils ont dessiné leurs cercles correctement!* Vous pouvez leur demander de comparer leurs cercles avec un partenaire et une autre paire de partenaires ou vous pouvez mettre un corrigé à leur disposition.
}

@lesson-instruction{
Quand vous avez confirmé que votre code est bon, continuez avec @printable-exercise{translate-arithmetic-to-coe-and-code-2-outro.adoc}
}

@indented{
(La page précédente du guide offrait aux élèves du soutien pour traduire une expression en code avec des parenthèses supplémentaires. Ce soutien s’arrête sur cette page.)
}

@lesson-instruction{
Si vous en avez le temps, demandez aux élèves d’écrire le code dans l'éditeur avec leur partenaire, chacun leur tour.
}

Dans le guide, nous avons inclus une page de problèmes plus difficiles afin que vous soyez prêt à lancer des défis aux élèves avancés : @printable-exercise{translate-arithmetic-to-circles-and-code-challenge.adoc}.


*Remarque :* Si vous voulez vous exercer à faire des cercles d'évaluation avec des exposants et des racines carrées, nous utilisons @show{(code 'sqrt)} comme nom de la fonction racine carrée, et @show{(code 'sqr)} comme fonction qui élève au carré son entrée.

@ifproglang{pyret}{
Dans Pyret, les _opérateurs_ comme `+`, `-`, `*`, et `/` sont écrits entre les entrées, tout comme en mathématiques. Des noms de fonctions comme `f`, `g`, `sqrt` et `sqr` sont écrits au début d'une expression, par exemple @show{(code '(f x))} ou @show{(code '(sqrt 9))}.
}



@strategy{Stratégies pour les élèves qui apprennent l’anglais}{


MLR 7 -- Comparer et associer : Rassemblez les organisateurs graphiques des élèves pour en souligner et analyser quelques-uns en grand groupe. Demandez aux élèves de comparer et d’associer les différentes représentations.
}

=== Synthèse
Demandez aux élèves de dire ce qu'ils ont appris des cercles d'évaluation.

== Essai du code

=== Aperçu

Les cercles d'évaluation sont un outil efficace qui peut être utilisé sans même envoyer les élèves devant un ordinateur. Si vous avez du temps, présentez l’éditeur @ifproglang{wescheme}{@link{https://www.wescheme.org, wescheme}} @ifproglang{pyret}{@link{https://code.pyret.org, pyret}} aux élèves. En tapant leur code dans la zone d'interactions, les élèves obtiendront un retour sur leur utilisation des parenthèses. De plus, ils auront un sentiment de satisfaction en voyant leur code évaluer les expressions qu'ils ont générées.


=== Lancement

@lesson-instruction{
- Ouvrez @ifproglang{wescheme}{@link{https://www.wescheme.org, WeScheme}} @ifproglang{pyret}{@link{https://code.pyret.org, code.pyret.org (CPO)} } et cliquez sur Exécuter (Run).
-	Pour l'instant, nous allons uniquement travailler dans la zone d'interactions à droite de l'écran.
- Tapez @show{(code '(+ (* 8 2) (/ 6 3)))} dans la zone d'interactions.
- Remarquez comment l'éditeur met en évidence les paires de parenthèses pour vous aider à vérifier que vous avez fermé chaque paire.
- Appuyez sur Entrée (ou Retour) pour évaluer l’expression. Que se passe-t-il? _Si vous avez tapé le code correctement, vous obtiendrez 18. Si vous faites une erreur de frappe, l'ordinateur devrait vous aider à la repérer afin que vous puissiez la corriger et réessayer!_
- Prenez quelques minutes pour revenir en arrière et essayer toutes les lignes de code que vous avez écrites sur les pages en les saisissant dans la zone d'interactions. Utilisez les messages d'erreur pour vous aider à repérer les caractères manquants et à modifier votre code pour qu'il fonctionne.
}


=== Mise en application

@lesson-instruction{
Voici deux cercles d'évaluation.

[cols="1,1", grid="none", frame="none"]
|===

| @right{@show{(coe `(* 10 -4))}}
| @show{(coe `(text "Bon travail!" 50 "red"))}
|===

Vous reconnaissez un des cercles, mais l’autre est très différent de ceux que vous avez connus jusqu’à présent. Qu'est-ce qui est différent dans le cercle de droite?
}

@indented{
_Réponses possibles :_

- _Nous n'avons jamais vu la fonction `text` auparavant_
- _Nous n'avons jamais vu de mots dans un cercle d'évaluation auparavant_
- _Nous n’avons jamais vu une fonction prendre trois entrées auparavant_
- _Nous n'avons jamais vu une fonction prendre un mélange de nombre et de mots auparavant_
}

@lesson-instruction{
- Pouvez-vous trouver le nom de la fonction dans le deuxième cercle? C'est l'occasion de chercher et d'utiliser la structure pour déchiffrer une nouvelle expression!
_Nous savons que le nom de la fonction est `text`, car c'est ce qui se trouve en haut du cercle._
- Quelle sera l’évaluation de cette expression, selon vous?
- Convertissez ce cercle en code et essayez-le!
- Que veut dire le `50` pour l'ordinateur? Essayez de le remplacer par des valeurs différentes et voyez ce que vous obtenez.
- Que veut dire « blue » pour l'ordinateur? Essayez de le remplacer par des valeurs différentes et voyez ce que vous obtenez.


Voici un autre cercle à découvrir.
@show{(coe `(string-length "wow!"))}

- Quelle sera l’évaluation de cette expression, selon vous?
- Convertissez ce cercle en code et essayez-le!
}

=== Synthèse

Maintenant que nous comprenons la structure des cercles d'évaluation, nous pouvons les utiliser pour écrire le code de n'importe quelle fonction!


== Exercices supplémentaires

Si vous êtes en train de découvrir l'ordre des opérations et que vous souhaitez faire des exercices avec les cercles d'évaluation avant de présenter la programmation, nous avons de nombreuses options pour vous!

- @opt-starter-file{coe-desmos}.
* @opt-printable-exercise{matching-coe-exp.adoc, Un jeu de cartes imprimable pour faire associer physiquement des expressions à des cercles d'évaluation}
* @opt-printable-exercise{arith-to-coe.adoc}
* @opt-printable-exercise{arith-to-coe2.adoc}
* @opt-printable-exercise{arith-to-coe3.adoc}
* @opt-printable-exercise{coe-to-arith.adoc}
* @opt-printable-exercise{coe-to-arith2.adoc}
* @opt-printable-exercise{evaluate-coe.adoc}
* @opt-printable-exercise{evaluate-coe2.adoc}

Plus d’exercices pour associer des cercles d'évaluation au code

* @opt-printable-exercise{coe-to-code.adoc}
* @opt-printable-exercise{coe-to-code2.adoc}

Plus d’exercices à 3 colonnes pour associer les expressions arithmétiques aux cercles d'évaluation et au code :

* @opt-printable-exercise{translate-arithmetic-to-coe-and-code-3.adoc}
* @opt-printable-exercise{translate-arithmetic-to-coe-and-code-4.adoc}

Plus d’exercices à 3 colonnes avec des nombres négatifs :

* @opt-printable-exercise{translate-arithmetic-to-coe-and-code-w-neg-5.adoc}
* @opt-printable-exercise{translate-arithmetic-to-coe-and-code-w-neg-6.adoc}

Plus d’exercices à 3 colonnes avec des racines carrées :

* @opt-printable-exercise{translate-coe-to-code-w-sqrts.adoc}

Exercices à 3 colonnes avec des parenthèses et des exposants :

* @opt-printable-exercise{translate-arithmetic-to-circles-and-code-challenge-2.adoc}
* @opt-printable-exercise{translate-arithmetic-to-circles-and-code-challenge-3.adoc}
* @opt-printable-exercise{translate-arithmetic-to-circles-and-code-challenge-4.adoc}




