= Function Composition

@lesson-description{Students encounter new image transformation functions and strengthen their understanding of Circles of Evaluation by using functions within other functions.}

[.left-header, cols="20a, 80a", stripes=none]
|===
| Lesson Goals 
| Students will be able to:

* Demonstrate understanding of the Order of Operations
* Use Circles of Evaluation to combine multiple functions, including non-Number producing functions

|Student-facing Goals
|
* I can use Circles of Evaluation to combine many kinds of functions.

|Key Points For The Facilitator
|
* Check frequently for understanding of @vocab{datatype}s and @vocab{contract}s during this lesson and throughout subsequent lessons.
* When students encounter errors, encourage them to check their Contracts page and show their work using Circles of Evaluation.
* Students will use their Contracts page frequently, so it should be kept in an accessible, convenient location.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.


|Materials
|
* https://docs.google.com/presentation/d/1BvOHRghJtY7vKSc_Icirlt7bVolrMjxGf0r4NfRsR48/view[Google Slides]
* Workbook, writing utensil, computer

Bootstrap Formative Assessments

* @link{https://quizizz.com/admin/quiz/5a146afd3b4ad115000fcb57?from=quizEditor, Unit 1 Quiz Bootstrap Algebra} (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/5a15e2388c08800a6024c091, Unit 1 Circles of Evaluation And Code Practice} (Desmos Activity)
* @link{https://teacher.desmos.com/activitybuilder/custom/5a1c805bbfc8c40614d3904a, Unit 1 Circles of Evaluation And Code Practice - Blank Template} (Desmos Activity)
* @link{https://quizizz.com/admin/quiz/5a15d1a82b65d91100dc2055?from=quizEditor, Unit 2 Quiz Bootstrap: Algebra} (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/5a15e268dcb86b2b9fda3ce0, Unit 2 Bootstrap Algebra Review} (Desmos Activity)

Connection Activities

* @link{https://www.geogebra.org/m/nqymeFc4, Function Composition Dynamic Illustrator I} (Geogebra)
* @link{https://www.geogebra.org/m/h3qdzW3W, Composition of Function} (Geogebra Quiz)
* @link{https://quizizz.com/admin/quiz/58a61a2cf0b089151011ef50/composition-of-functions, Composite Functions} (Quizizz)

|===

[.left-header, cols="20a, 80a", stripes=none]
|===
|Math Standards(CCSS)
|
* _Math standards_

|CS Standards(CSTA)
|
* _CS Standards_
|===


== Get Ready: 

Students should be logged into WeScheme.

== Launch: (5 mins)

Which One Doesn't Belong?

@image{images/shape6.jpg, Which One Doesn't Belong?, 400, align="center"}

[.text-center]
*Source: Matt Owen, curated by https://wodb.ca/shapes.html*

Have students choose which image they feel doesn't belong and move together with other students who share their view. Take turns letting groups justify their reasons and discuss with other groups.  

*Ask students: What theme do you see here?*  _(All of the shapes are cubes with some aspect of their appearance changed - angle, color, size, etc)_

== Explore: (10 mins)

Have students open to @worksheet-link{workbook-pages/FunctionComposition1-WB1.pdf}.  Students create a text image of their name and experiment with their choice of these new functions.  

While students are exploring, be available for support but encourage student discussion to solve problems.  Make sure students are using the Definitions window (left side) for code they want to keep and are using the Interactions window (right side) to test code or try out new ideas.

Many questions can be addressed with these responses: 

* *Did you try drawing the Circle of Evaluation first?*
* *Did you check the contract?*
* *Have you pressed the Run button to save your Definitions changes?*


== Discuss: (10 mins)
* *What do all of these functions have in common?*
+
_They all produce images, they all change some element of the original image_
* *Does using one of these functions change the original image?*
+
_No, it creates a whole new image_
* *What does the number in ‘scale’ represent?*
+
_The scale factor, the percent by which the image should grow or shrink_
* *What does the number in ‘rotate’ represent?*
+
_The rotation angle, measured counterclockwise_
* *Suppose I wrote the code `(scale 3 (star 50 “solid” “red”))`.  What’s another line of code I could write that would produce the exact same image?*
+
_``(star 150 "solid" "red")``_
* *The domain and range for `flip-horizontal` is Image -> Image.  Why can I use the text function as an input for `flip-horizontal`?*
+
_Because the `text` function produces an Image, which is then used as the input for `flip-horizontal`._

[.strategy-box]
.Strategies for English Language Learners
****
MLR 1 - Stronger and Clearer Each Time: As an alternative, display the discussion questions during the last 5 minutes of the Explore and ask students to discuss the questions with their partner, asking each other for explanation and details and coming up with the clearest, most precise answer they can.
Student pairs can then share with another pair and compare their responses before moving into a full class discussion.
****

== Practice: (10 mins)
Students complete @worksheet-link{workbook-pagesFunctionComposition1-WB2.pdf}, practicing drawing Circles of Evaluation and writing code with their partner using different functions.  

Student-facing Task:
Create the circles of evaluation and write the code for the following images.  Write a new line of code for each exercise.

* a solid, green `star` of size 50
* a solid, green `star` that’s 3 x’s as large as the original (using the `scale` function)
* a solid, green `star` that’s ½ the size of the original (using the `scale` function)
* a solid, green `star` of size 50 that’s rotated 45 degrees (using the `rotate` function)
* a solid, green `star` that’s 3x as large as the original and rotated 45 degrees.

When students are finished, check their work, and ask them to change the color of all of the stars to “gold” or another color of your choosing.


== Create/Apply: (15 mins) 

Create an Image that uses the text function and at least 3 of following functions:

* `rotate`
* `scale`
* `overlay`
* `flip-horizontal`
* `flip-vertical`
* any other image producing function(`triangle`, `star`, `circle`, `rectangle`, etc..)

Write comments to describe what is being produced.
