= Solving Word Problems with the Design Recipe

@vspace{2ex}
Use The Design Recipe to create models for the word problems and write the appropriate functions.

@vspace{2ex}

[cols="1a,1a,1a"]
|===
|1.

Write a function `globo-gym` that
takes in a number of months and
produces the cost for attending the
gym that many months when there
is a $150 initiation fee and a monthly
fee of $45/month.

----
fun globo-gym(months):
  (45 * months) + 150
end
----

|2.

Write a function `rect-perimeter`
that takes in the length and width of a
rectangle and returns the perimeter of
that rectangle.

----
fun rect-perimeter(L, W);
  2 * (L + W)
end
----

|3.

Write a function `lawn-area` that
takes in a length and width of a
lawn and returns the area of that
rectangular lawn.

----
fun lawn-area(length, width):
  length * width
end
----

|4.

Write a function
`rectprism-volume` that takes in
the length, width, and height of a
rectangular prism and returns the
Volume of a rectangular prism.

----
fun rectprism-vol(L, W, H):
  (L * W) * H
end
----

|5.

Write a function `rideshare`,
that takes in a number of miles and
produces the cost of a ride for that
many miles at $2.50 plus $1.50/mile.

----
fun ridewhare(miles):
  (1.50 * miles) + 2.50
end
----

|6.

Write a function `marquee` that
takes in a message and returns that
message in large gold letters.

----
fun marquee(my-message):
  text(my-message, 100, "gold")
end
----

|7.

Write a function `split-tab` that
takes in a cost and the number of
people sharing the bill and splits the
cost equally.

----
fun split-tab(cost, people):
  cost / people
end
----

|8.

Write a function `num-cube` that takes
in a number and returns the cube of
that number.

----
fun num-cube(number):
  (number * number) * number
end
----

|9.

Write a function `circle-area` that
takes in a radius and returns the
area of the circle.

----
fun circle-area(radius):
  pi * num-sqr(radius)
end
----

|10.

Write a function `tip-calculator`
that takes in the cost of a meal and
returns the 15% tip of that meal.

----
fun tip-calculator(cost):
  0.15 * cost
end
----

|11.

Write a function `minimum-wage`, that
takes in a number of hours worked
and returns the amount a worker will
get paid at $10.25/hr.

----
fun minimum-wage(hours):
  10.25 * hours
end
----

|12.

Write a function `moving-truck`
that takes in the days and number
of miles driven and returns the cost
of renting a truck. The truck is $55
per day and each driven mile is 15¢.

----
fun moving-truck(days, miles):
  (55 * days) + (0.15 * miles)
end
----

|===

