= Surface Area of a Rectangular Prism - Explore

@n What do you picture in your mind when you hear _rectangular prism_?

@fitb{}{@ifsoln{_a box_}}

@fitb{}{}

@n What do you picture in your mind when you hear _surface area_?

@fitb{}{@ifsoln{_a box_}}

@fitb{}{}

@n Open the @starter-file{prism} and click "Run".

@n Type `prism` into the Interactions Area and hit "enter" to see an image of a rectangular prism.  What do you notice about the image?

@fitb{}{}

@fitb{}{}

@n The surface area of a prism is calculated by adding the areas of its faces. How many faces does this prism have? @fitb{}{}

*Find PART 2 in the starter file. (We'll skip PART 1 for now, and return to it in a moment.) You'll see a list, that only includes `front`.*

@n Complete the faces list, then type @ifproglang{pyret}{`print-imgs(faces)`}@ifproglang{wescheme}{`(print-imgs faces)`} into the interactions area. Why do we still not see all of the prism's faces?

@fitb{}{}

@fitb{}{}

@vspace{1ex}


*Find PART 1 in the starter file. You will see a definition for ``front``.*

@n How did the author know to use width and height as the dimensions for `front`?

@fitb{}{}

@fitb{}{}

@n Add definitions for the other faces of the prism, using the definition of `front` as a model, and the image of the prism as a support.

*We're going to print the faces following directions in PART 3 and build a paper model of a rectangular prism.*

_Before you print and build your prism, you can change the length, weidth, and height of your prism at the top of the starter file. Be sure that all 3 dimensions are different, and that they are all small enough to fit on a sheet of paper. If you change them, record your new dimensions here._

@vspace{1ex}

LENGTH: @fitb{10em}{} WIDTH: @fitb{10em}{} HEIGHT: @fitb{10em}{}

//@n What units are the dimensions of the prism given in? @fitb{}{}

//@n What units should the surface area be given in? @fitb{}{}

@n Calculate the surface area of your prism. @fitb{25ex}{} Show your work below.

@vspace{10ex}

@n In PART 4 of the starter file, you wrote code to calculate the surface area. How many definitions did you use? @fitb{}{@ifsoln{_4 or 7_}}

@n How does the surface area that the computer returns compare to the surface area you calculated by hand?

@fitb{}{}
