= True or False? Distributive Property

++++
<style>
td > .content > .paragraph > * { vertical-align: middle; }
</style>
++++

Decide whether or not the two expressions are equivalent. Explain your reasoning.

[.FillVerticalSpace, cols="^.^1a, ^.^5a, ^.^1a, ^.^5a, ^.^5a", grid="none", options="header", ]
|===
|	 | Circle 1 						| 	| Circle 2								| True or False? Justify.

| @n
| @show{(coe '(* 8 (+ 20 3)))}
| @math{=}
| @show{(coe '(+ (* 8 20) (* 8 3)))}
| @ifsoln{True. +
The Distributive Property has been applied correctly. +
Each side evaluates to @math{184}.}

| @n
| @show{(coe '(* (+ 4 3) 11))}
| @math{=}
| @show{(coe '(* 7 11))}
| @ifsoln{True. +
The nested Circle on the left evaluates to @math{7}. Each side evaluates to @math{77}.}

| @n
| @show{(coe '(* 9 12))}
| @math{=}
| @show{(coe '(* (+ 9 10) (+ 9 2)))}
| @ifsoln{False. +
To apply the Distributive Property correctly, we would find the sum of @math{9 \times 10} and @math{9 \times 2}.}

| @n
| @show{(coe '(* 4 36))}
| @math{=}
| @show{(coe '(* (* 4 30) (* 4 6)))}
| @ifsoln{False. +
The operator on the outer Circle on the right should be addition, not multiplication, because we are looking for the product of 4 and @math{30 + 6}. 
}

| @n
| @show{(coe '(+ (* 9 3) (* 9 20)))}
| @math{=}
| @show{(coe '(* 9 23))}
| @ifsoln{True. +
The Distributive Property has been correctly applied. +
Both are multiplying @math{20 + 3} by 4.}

| @n
| @show{(coe '(+ (* 4 6) (* 30 6)))}
| @math{=}
| @show{(coe '(* 34 6))}
| @ifsoln{True. +
The Distributive Property has been correctly applied. +
Both are multiplying @math{30 + 4} by 6.}
|===
