= Teacher Resources for Data Science

== Let's Get Started
- *Implementation Options* [@link{pages/implementation-options.html, link}] Bootstrap:Data Science was designed to be flexible, allowing for implementations in Middle and High School ranging from 1-week exposures to full-year courses! Find recommendations for the course structure that's right for you.
- *Online Community* [@link{https://discourse.bootstrapworld.org, Discourse}] -- Talk with other Bootstrap teachers, ask questions, and share ideas!
- *Remote Instruction* [@dist-link{ImplementationNotes.shtml, link}] -- specific recommendations for in-person v. remote instruction.
- *Poster Set for Classroom Walls* [@lesson-link{computing-needs-all-voices/pages/computing-pioneers.adoc, link}] -- This poster set features Pioneers in Computing and Mathematics. For greater impact, engage your students with these materials using our @lesson-link{computing-needs-all-voices} lesson. (You can also @link{https://www.printme1.com/1100aa4996, purchase a printed set yourself!})

=== Printables for Classroom Walls

- *Computing Pioneers Posters* [@lesson-link{computing-needs-all-voices/pages/computing-pioneers.adoc, link}] -- For greater impact, use our @lesson-link{computing-needs-all-voices} lesson to engage your students with these posters!

- *Data Fallacies to Avoid* [@lesson-link{threats-to-validity/pages/Geckoboard-Data-Fallacies-Poster.pdf, link}] from @link{https://geckoboard.com/best-practice/statistical-fallacies/, geckoboard.com}

=== Standalone Hour of Code Activities from Bootstrap

- *Hour of Data* [@lesson-link{hoc-data/, link}] -- A self-guided Desmos activity for exploring a real dataset, and using it to make sense of a real-world problem.
- *Snowman Puzzle* [@lesson-link{hoc-winter-parley, link}] -- This Pyret Starterfile has all the pieces your students will need to make a snowman by changing the coordinates in the code.

== Exercises and Solutions
@all-exercises

== Notes, Slides, and Starter Files
@lesson-info

== Projects

@project-list

== Dataset Library 

Students can import their own data into a @starter-file{blank-ds, Blank Starter File} following instruction in @starter-file{blank-ds-tutorial, this tutorial video} or choose from one of the many provided datasets below:

@vspace{1ex}

@include{../../../lessons/choosing-your-dataset/fragments/dataset-table.adoc}

_We have compiled some @lesson-link{choosing-your-dataset/about-datasets/for-teachers-about-datasets.adoc, Notes on our provided datasets}, to help you decide which might be most useful in your classroom._

== Other Curricular Materials

- *Contracts* [@link{solution-pages/Contracts.pdf, link}] -- A PDF of the contracts pages from the back of the student workbook.
- *Glossary* [@dist-link{Glossary.shtml?pathway=data-literacy, link}] -- All of the vocabulary words (and their definitions) used in this pathway.
- *Bilingual Glossary of Bootstrap Terms (English-Spanish)* [@dist-link{lib/bilingual-glossary.html, PDF}] -- For teachers with ELL/ESL students, we provide a bilingual glossary for all of the terms used across our curriculum library.
- *Blank Data Cycle Worksheet* -- [@dist-link{pages/2-blank-data-cycles.adoc, html}] -- When students need scaffolding for answering a question with data.
- *Collection of Bootstrap:Data Science Desmos Activities* [@link{https://teacher.desmos.com/collection/5fc9250afcaa3f30f4946746, link}] -- All of our Desmos Data Science lessons, in one place.
- *Sentence Starters* [@dist-link{pages/sentence-starters.adoc, html}] -- Use these sentence starters to help students describe patterns, make predictions, find comparisons, share discoveries, formulate hypotheses, and ask questions.

=== Resources that Pair Well with Bootstrap:Data Science

- *What's Going on in this Graph?* [@link{https://www.nytimes.com/column/whats-going-on-in-this-graph, link}] -- weekly intriguing data visualizations by the New York Times

- *The Pudding* [@link{https://pudding.cool/, link}] -- fascinating, data-rich visual essays explaining ideas debated in culture

- *How Not To* [@link{https://discourse.bootstrapworld.org/t/something-fun-for-the-classroom-hownotto/1459/9, link}] -- friendly potshots at terrible Data Science, regularly posted to social media under the hashtag "HowNotTo"

- *Same Stats, Different Graph* [@link{https://www.research.autodesk.com/publications/same-stats-different-graphs-generating-datasets-with-varied-appearance-and-identical-statistics-through-simulated-annealing, Autodesk}] -- an illustration from Autodesk of why we must see the shape of data and not just focus on the descriptive statistics

- *Guess the Correlation* [@link{http://guessthecorrelation.com/, link}] -- a game-ified resource (built by Omar Wagih) for building intuition for correlation, based on randomly-generated scatterplots

- *Sensitive r* [@link{https://www.geogebra.org/m/ZcVIxKtF, link}] -- an applet from Geogebra that shows how changing a single point can change the correlation coefficient `r`


