= Maya Gods

What does the writing on the stone carvings mean? Archaeologists have determined that the Maya worshipped many gods, and that the five most important gods were associated with these symbols: corn, a pig being carried by someone, a skeleton, someone holding a snake, and a turtle carrying someone. But which is which? Study the images of each god and draw a line to match it to the symbol it represents.

[cols="10a, >10a", options="header"]
|===

| God letter and Name
| God Image

| God A: Ah Puch – The God of Death (skeleton)
| @image{../images/snake.png, God B, 100}
@ifsoln{B}

| God B: Kukulcán – The Feathered Serpent God
| @image{../images/corn.png, God E, 150}
@ifsoln{E}

| God C: K'uhul - Sometimes bearded. Sometimes shown as a turtle carrying someone.
| @image{../images/pig.png, God D, 125}
@ifsoln{D}

| God D: Itzamna - Sometimes shown carrying a pig
| @image{../images/turtle.png, God C, 175}
@ifsoln{C}

| God E: Hun Hunahpu - The Maize God (corn)
| @image{../images/skeleton.png, God A, 100}
@ifsoln{A}

|===

_Note: In 1904 an archaeologist named Paul Schellhas began deciphering the Maya codices, assigning a new letter each time he found a god with new characteristics. Many of the gods' names are now known, but archaeologists still sometimes use the Schellhas letter system._
