= Setting the Stage: The Rise & Fall of the Maya

@centered-image{../images/maya-timeline.png, "graph of Maya population over time", 600}

[.center]
__(Images from L -> R: corn, Maya calendar, forests being cut down for farming, Spanish ship, modern archaeologist)__

@n About how big was the Maya population at its peak? @fitb{}{@ifsoln{over 20 million people}}

@n For about how many years did the Maya civilization thrive? @fitb{}{@ifsoln{about 1900 years (from 1000 BCE to 900 AD)}}

@vspace{1ex}

[cols="1a,3a, 3a, options="header""]
|===
| Year
| Event
| Possible Significance for the Maya

| 1000 BCE
| Maya myth tells that man was created from an ear of corn.
|

| Centuries after Maya origins
| Maya civilization thrives, with impressive advances like a very scientific calendar.
|

| Century before 1000 AD
| Maya population begins to decline! Why?!
|

| Shortly after 1500 AD
| Spanish arrive to conquer the remaining Maya people, who now live in rural, country areas because cities are gone. They write first accounts about the Maya.
|

| Around 2000 AD
|Archaeologists study Mayan bones to try to learn more about their ancient civilization.
|

|===

@vspace{1ex}

@n Knowing what you know about the Maya based on some significant events in their history, what do you think are some possible reasons as to why the Maya civilization declined so suddenly?

@fitb{}{}

@fitb{}{}
