= What Kind of Model? (Definitions)

++++
<style>
/* Position autonums in the top-left of every table cell
 */
td .autonum {
	padding-top: 0;
    position: 	absolute;
    top: 		10px;
    left: 		5px;
}

/* Any math- or code-containing element should take up the whole line,
 * with text centered on that line
 */
.obeyspaces, mjx-container, .mathunicode {
	display: 	inline-block;
	width: 		100%;
	text-align: center;
}

td .paragraph:nth-child(3) { text-align: left; margin-top: 2ex; }
.fitbruby { padding-top: 0rem !important; }
</style>
++++

Circle whether each representation below describes a *linear* or *quadratic* function, or *neither*, and fill in any x-intercepts. +
*If the function is quadratic*, fill in all the information that you can _easily read from the form_, without any calculation!

[.FillVerticalSpace, cols="^.^15a,^.^15a", frame="none", stripes="none"]
|===

| *@n*
*@big{@math{f(x) = 3x^2 + 22}}*

Linear @hspace{4em}
@ifsoln-choice{Quadratic} @hspace{4em}
Neither

@fitbruby{90%}{}{Root(s)/x-Intercept(s) - _write "none", one, or both x-coords_}

_If it's Quadratic_...

@fitbruby{40%}{@ifsoln{Standard}}{Form: Factored, Vertex, Standard}
@hspace{10%} @fitbruby{40%}{@ifsoln{up}}{Parabola opens: up/down}

@fitbruby{40%}{@ifsoln{not easy to tell}}{axis of symmetry (x=...)}
@hspace{10%} @fitbruby{40%}{@ifsoln{not easy to tell}}{Vertex (x, y)]}

| *@n*
*@big{@math{g(x) = 2(x − 11)(x − 243)}}*

Linear
@hspace{4em} @ifsoln-choice{Quadratic}
@hspace{4em} Neither

@fitbruby{90%}{@ifsoln{(11, 0) and (243, 0)}}{Root(s)/x-Intercept(s) - _write "none", one, or both x-coords_}

_If it's Quadratic_...

@fitbruby{40%}{@ifsoln{Factored}}{Form: Factored, Vertex, Standard}
@hspace{10%} @fitbruby{40%}{@ifsoln{up}}{Parabola opens: up/down}

@fitbruby{40%}{@ifsoln{not easy to tell}}{axis of symmetry (x=...)}
@hspace{10%} @fitbruby{40%}{@ifsoln{not easy to tell}}{Vertex (x, y)]}


| *@n*
*@big{@math{h(y) = 100 - 4y}}*

@ifsoln-choice{Linear}
@hspace{4em} Quadratic
@hspace{4em} Neither

@fitbruby{90%}{@ifsoln{n/a}}{Root(s)/x-Intercept(s) - _write "none", one, or both x-coords_}

_If it's Quadratic_...

@fitbruby{40%}{@ifsoln{n/a}}{Form: Factored, Vertex, Standard}
@hspace{10%} @fitbruby{40%}{@ifsoln{n/a}}{Parabola opens: up/down}

@fitbruby{40%}{@ifsoln{n/a}}{axis of symmetry (x=...)}
@hspace{10%} @fitbruby{40%}{@ifsoln{n/a}}{Vertex (x, y)]}

| *@n*
*@big{@math{z(x) = \frac{3}{5}x + 7}}*

@ifsoln-choice{Linear}
@hspace{4em} Quadratic
@hspace{4em} Neither

@fitbruby{90%}{@ifsoln{n/a}}{Root(s)/x-Intercept(s) - _write "none", one, or both x-coords_}

_If it's Quadratic_...

@fitbruby{40%}{@ifsoln{n/a}}{Form: Factored, Vertex, Standard}
@hspace{10%} @fitbruby{40%}{@ifsoln{n/a}}{Parabola opens: up/down}

@fitbruby{40%}{@ifsoln{n/a}}{axis of symmetry (x=...)}
@hspace{10%} @fitbruby{40%}{@ifsoln{n/a}}{Vertex (x, y)]}


| *@n*
@show{(code `(define (graph x) (* 12 x)))}

@ifsoln-choice{Linear}
@hspace{4em} Quadratic
@hspace{4em} Neither

@fitbruby{90%}{@ifsoln{n/a}}{Root(s)/x-Intercept(s) - _write "none", one, or both x-coords_}

_If it's Quadratic_...

@fitbruby{40%}{@ifsoln{n/a}}{Form: Factored, Vertex, Standard}
@hspace{10%} @fitbruby{40%}{@ifsoln{n/a}}{Parabola opens: up/down}

@fitbruby{40%}{@ifsoln{n/a}}{axis of symmetry (x=...)}
@hspace{10%} @fitbruby{40%}{@ifsoln{n/a}}{Vertex (x, y)]}


| *@n*
@show{(code `(define (m p) (* 2 (* (- p 5) (- p 16)))))}

Linear
@hspace{4em} @ifsoln-choice{Quadratic}
@hspace{4em} Neither

@fitbruby{90%}{@ifsoln{x=5, x=16}}{Root(s)/x-Intercept(s) - _write "none", one, or both x-coords_}

_If it's Quadratic_...

@fitbruby{40%}{@ifsoln{Factored}}{Form: Factored, Vertex, Standard}
@hspace{10%} @fitbruby{40%}{@ifsoln{up}}{Parabola opens: up/down}

@fitbruby{40%}{@ifsoln{not easy to tell}}{axis of symmetry (x=...)}
@hspace{10%} @fitbruby{40%}{@ifsoln{not easy to tell}}{Vertex (x, y)]}


| *@n*
@math{r(s) = 42(s - 10)^2 - 3}

Linear
@hspace{4em} @ifsoln-choice{Quadratic}
@hspace{4em} Neither

@fitbruby{90%}{@ifsoln{not easy to tell}}{Root(s)/x-Intercept(s) - _write "none", one, or both x-coords_}

_If it's Quadratic_...

@fitbruby{40%}{@ifsoln{Vertex}}{Form: Factored, Vertex, Standard}
@hspace{10%} @fitbruby{40%}{@ifsoln{up}}{Parabola opens: up/down}

@fitbruby{40%}{@ifsoln{10}}{axis of symmetry (x=...)}
@hspace{10%} @fitbruby{40%}{@ifsoln{(10, -3)}}{Vertex (x, y)]}


| *@n*
@show{(code `(define (f x) (+ (* 2 (sqr (- x 1))) 15)))}

Linear
@hspace{4em} @ifsoln-choice{Quadratic}
@hspace{4em} Neither

@fitbruby{90%}{@ifsoln{"none"}}{Root(s)/x-Intercept(s) - _write "none", one, or both x-coords_}

_If it's Quadratic_...

@fitbruby{40%}{@ifsoln{Vertex}}{Form: Factored, Vertex, Standard}
@hspace{10%} @fitbruby{40%}{@ifsoln{up}}{Parabola opens: up/down}

@fitbruby{40%}{@ifsoln{1}}{axis of symmetry (x=...)}
@hspace{10%} @fitbruby{40%}{@ifsoln{(1, 15)}}{Vertex (x, y)]}

|===
