= What can we learn from each form of a Quadratic Function?

Draw arrows from each form to the information which you can easily learn from it.

[.FillVerticalSpace, cols=".^5a, >.^1a, <.^3a", grid="none", frame= "none", stripes="none"]
|===

||*A*| roots (x-intercepts)

|*Factored Form:* @ifnotsoln{@hspace{10em}*@n* +
@vspace{1em} +
} @ifsoln{@hspace{1em}}
@big{@math{y= -2(x − 5)(x + 6)}}  @ifsoln{@hspace{5em} *@n*} @ifsoln-match{A, C, E}

@indented{
@teacher{
@math{y=a(x − r_1)(x − r_2)} +
roots: @math{r_1 and r_2} @hspace{1em}&rarr;@hspace{1em} @math{5 and -6} +
axis of symmetry: @math{x = (r_1 + r_2) / 2} @hspace{1em}&rarr; @hspace{1em}@math{-0.5} +
opens up/down: {nbsp} sign of @math{a} @hspace{1em}&rarr;@hspace{1em} @math{-2} is negative... so it opens down
}
}

|*B*| coordinates of vertex

|*Standard Form:* @ifnotsoln{@hspace{10em}*@n* +
@vspace{1em} +
} @ifsoln{@hspace{1em}}
@big{@math{y=3x^2+5x+6}} @ifsoln{@hspace{6em} *@n*} @ifsoln-match{C, D, (A)}

@indented{
@teacher{
@math{y=ax^2+bx+c} +
y-intercept: @math{c} @hspace{1em} &rarr; @hspace{1em}@math{6} +
opens up/down: {nbsp}sign of @math{a} @hspace{1em} &rarr;@hspace{1em} @math{3} is positive... so it opens up +
@vspace{1em} +
(could also calculate roots using the quadratic equation)
}
}

|*C*| the parabola opens up / down

|*Vertex Form:* @ifnotsoln{@hspace{11em}*@n* +
@vspace{1em} +
} @ifsoln{@hspace{1em}}
@big{@math{y=2(x − 5)^2 + 17}} @ifsoln{@hspace{6em} *@n*} @ifsoln-match{B, C, E}

@indented{
@teacher{
@math{y=a(x − h)^2 + k} +
coordinates of the vertex: @math{(h, k)}@hspace{1em} &rarr;@hspace{1em} @math{(5, 17)} +
axis of symmetry: @math{x = h} @hspace{1em}&rarr;@hspace{1em} @math{x = 5} +
opens up/down: {nbsp} sign of @math{a} @hspace{1em}&rarr; @hspace{1em} @math{2} is positive... so it opens up
}
}

|*D*| y-intercept

||*E*| axis of symmetry
|===

@star Record any specific values you can learn from the provided equations.