= Creating Functions 2

@lesson-description{Students will apply The Design Recipe to simple word problems.}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Understand how to use the Design Recipe to break down simple word problems.
* Create a strong purpose statement that details in their own words what the function should do.

|Student-Facing Lesson Goals
|
* I can use the @vocab{Design Recipe} to break down word problem when writing a @vocab{function}.
* I can identify the @vocab{domain} and @vocab{range} and other quantities in a word problem when writing a function.
* I can create and revise a strong @vocab{purpose statement} that explains what the function is doing.

|Key Points for the Facilitator
|

* The purpose statement, like the contract, is a comment - something the computer doesn't read.  It is important for readability of their code - there may be other people looking at their code and using their functions!
* Remind students that the domain and range are @vocab{data types} (Number, String, Image).
* If students struggle with creating the examples, go back to the Circle of Evaluation mapping activity in Creating Functions 2.  

|Prerequisites
|

* Students should be familiar with Circles of Evaluation.
* Students should be familiar with defining values.
* Students should be familiar with the Design Recipe.

|Materials
|

* @link{https://docs.google.com/presentation/d/1jZ42nPILZIrv0FWiAh7h7tWVQcJ1r6_DxzlDOXXDo_s/view, Google Slides} for this lesson.
* @link{https://www.wescheme.org/openEditor?publicId=LGTVNvzrax, rocket-height} starter file
* Notice & Wonder (@worksheet-link{workbook-pages/NoticeAndWonder.pdf, PDF}, @link{https://docs.google.com/document/d/1hNMUXcMRWgKllc7SOzzqaTR48RiWbXg8RvG9rtl3SuU/edit?usp=sharing, Google Doc}
* Design Recipe (@worksheet-link{workbook-pages/DesignRecipe1.pdf, PDF}, @link{https://docs.google.com/document/d/1GQw-EJAw54BK04SMp_4jPtGGt4IojsUA7oXfz9TRm8Y/view, Google Doc}
* Purpose Statement(3 Reads/Stronger & Clearer) (@worksheet-link{workbook-pages/PurposeStatement3ReadsStrongerClearer.pdf, PDF}, @link{https://docs.google.com/document/d/16xiKkaB6GYUv95ug7-o3QubnmX7oZnm03J1AJTtH_2k/view, Google Doc})

Bootstrap Formative Assessments

* @link{https://teacher.desmos.com/activitybuilder/custom/5a15e2907915bd2fd51a65bc, Unit 4 Bootstrap Algebra Review} (Desmos Activity)
* @link{https://teacher.desmos.com/activitybuilder/custom/5a2f2c2e532d241d732593db, Unit 4: Design Recipe Practice - Blank Template} (Desmos Activity)

Connecting Activities

* @link{https://teacher.desmos.com/expressions, Expression Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/modeling, Mathematical Modeling Bundle} (Desmos Activities)
* @link{https://quizizz.com/admin/quiz/576d1e5f91cb32ef5fc67529/variables-and-expressions, Variables and Expressions} (Quizizz)
* @link{https://teacher.desmos.com/functions, Functions Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/polygraph/custom/560ad28e9e65da5615091edb,
Functions & Relations} (Desmos Polygraph Activity)
* @link{https://quizizz.com/admin/quiz/582b7390e8e0c0c201647d9d/functions, Functions} (Quizizz)
* @link{https://quizizz.com/admin/quiz/582f0e34b805cc5c6608d326/function-notation, Function Notation} (Quizizz)

|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Math Standards (CCSS)
|
|Reinforcing
|
* @std{7.EE.B.4}

|Addressing
|
* @std{8.F.B}

|Approaching
|
* @std{HSF.IF.A.2}

|Bootstrap Benchmarks
|
* @std{BS-DR.2}
|===


== Get Ready:

Students should have their contracts page, a pencil, and a computer, with a https://www.wescheme.org[WeScheme] tab opened and logged into.

== Launch: (5 min)

Ask students to open the @link{https://www.wescheme.org/openEditor?publicId=LGTVNvzrax, `rocket-height`} program in WeScheme and play with this program for a few minutes while noticing and wondering.

[.notice-box]
.Notice and Wonder
****
What do you Notice?  What do you Wonder? 
****

Survey the class about their noticings and wonderings and jot a few down on the board before moving onto the discussion.

== Discuss: (5 min)

* Is `rocket-height` working?
* Why do you think it's not working?
* What do you think it is 'intended to do'? How do you know?
* What is the domain of `rocket-height`?
* What is the range of `rocket-height`? How do you know?
* As the program is currently written, how does it work?
* How can we fix this program?


== Discuss: Use The Design Recipe to fix `rocket-height` (15 min)
Use The Design Recipe to fix `rocket-height` and to introduce 'The Purpose Statement' to the DR.

Inquiry Based Instruction
* What's the contract for `rocket-height`?
* How does the Word Problem help us find out what the contract is?
* The Purpose Statement is a comment that explains what the function does in your own words. Re-read the Word Problem and then write down what you think a good purpose statement is.

[.strategy-box]
.Strategies for English Language Learners
****
MLR 6: 3 Reads 
In pairs, the word problem is read 3 times. Students will document their work in the @worksheet-link{workbook-pages/PurposeStatement3ReadsStrongerClearer.pdf, 3 Reads/Stronger & Clearer} worksheet.

* 1st Read: Teacher reads the word problem. Without any pencil or pen, students discuss: What is the problem about? 
* 2nd Read: Partner A reads. Students discuss: What are the quantities?
* 3rd Read: Partner B reads. What is a good purpose statement?
****

[.strategy-box]
.Strategies for English Language Learners
****
MLR 1: Stronger and Clearer Each Time 
Using the @worksheet-link{workbook-pages/PurposeStatement3ReadsStrongerClearer.pdf, 3 Reads/Stronger & Clearer} worksheet, students will switch partners 3 times.

* 1st new partner: Read their purpose statements to each other & revise the purpose statement to be stronger and clearer.
* 2nd new partner: Repeat.
* 3rd new partner: Repeat.
****

Now that the students have revised and refined their Purpose Statement, have them write The Contract and Purpose statement in the @worksheet-link{workbook-pages/DesignRecipe1.pdf, Design Recipe} worksheet.

Write 2 EXAMPLES & The Definition

* Given The Contract and Purpose statement, write 2 examples of `rocket-height`
* Circle and Label what's changing in the 2 examples. What's a good variable name for what's changing?
* Write the `define` line of code that uses the decided upon variable name.
* Once the enter Design Recipe has been completed in the workbook, and the teacher has checked it for accuracy, then allow the students to type the code into the program to fix the `rocket-height` function.

== Explore: (10 min)

Now that `rocket-height` is working correctly, explore the rest of the file and try the following:

* remove the comment from before the `(start rocket-height)` and test the program.
* put the comment back in front of `(start rocket-height)`, remove the comment from `(graph rocket-height)`, and test the program.
* put the comment back in front of `(graph rocket-height)`, remove the comment from `(space rocket-height)`, and test the program.
* put the comment back in front of `(space rocket-height)`, remove the comment from `(everything rocket-height)`, and test the program.
* Challenge: Explore the 3 variations of the program and try and get the rocket to blast off faster and reach the edge of the observable universe.


== Practice: (15 min)
Use @worksheet-link{workbook-pages/DesignRecipe1.pdf, Design Recipe} worksheet to write each of the following functions. Make sure to include:

* The Contract & Purpose Statement
* 2 EXAMPLES
* The Definition

Practice:

* Define a function ’purple-star’, that takes in the size of the star and produces an outlined, purple star of the given size.
* Define a function ’spot’, that takes in a color and produces a solid circle of radius 50, filled in with that color
To find the average of two numbers, they should be added together and divided by two. Define a function ’average’, which takes in two numbers and produces their average
* A company logo is a word drawn in big, red letters, rotated some number of degrees. Define a function ’logo’, that takes in a company name and a rotation, and produces a logo for that company
