= “Trust, but verify ...”

[.lessonInstructions]
This page requires that you also open the @starter-file{trust-but-verify}.

A "helpful" Data Scientist gives you access to the following function:

@show{(contract
  "fixed-cats" '("Table") "Table"
  "consumes a table of animals, and produces a table containing only cats that have been fixed, sorted from youngest-to-oldest"
)}

You can use the function, __but you can’t see the code for it!__ *How do you know if you
can trust their code?*

- You could make a _verification subset_ that contains one of every species, and make sure that the function filters out everything but cats.

- You could make sure this subset has multiple cats not already ordered youngest-to-oldest, and make sure the function puts them in the right order.

@n What other qualities would this subset need to have?

@fitb{}{
  @ifsoln{It should contain animals - especially cats - that are fixed and unfixed}
}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

@n Create your verification subset! In the space below, list the name of each animal in your subset.

[.FillVerticalSpace, cols='1',options='header']
|===
| Name
|
|
|
|
|
|
|
|
|===
