= Traduire des expressions arithmétiques en cercles d'évaluation et en code (4)

Traduisez chacune des expressions arithmétiques ci-dessous en cercles d'évaluation, puis traduisez-les en code.
@ifsoln{*Enseignants :* le corrigé de code ci-dessous est montré avec seulement les parenthèses _nécessaires_. Si un élève ajoute des parenthèses supplémentaires (correctes), il aura quand même la bonne réponse.}


@do{
  (define expr1 '(- 15 (/ 9 (+ 2 1))))
  (define expr2 '(+ (* (+ 9 6) 7) (/ 8 2)))
  (define expr3 '(- 7 (+ (* 8 3) 2)))
  (define expr4 '(+ 5 (* (/ 8 2) 4 )))

  (define mat1 (math expr1))
  (define mat2 (math expr2))
  (define mat3 (math expr3))
  (define mat4 (math expr4))
}

[.FillVerticalSpace, cols="^.^1a,^.^10a,^.^20a,^.^15a",options="header",stripes="none"]
|===
|
| Expression arithmétique
| Cercle d’évaluation
| Code


|*@n*
| @show{    (math expr1)}
| @showsoln{(coe  expr1)}
| @showsoln{(code expr1)}

|*@n*
| @show{    (math expr2)}
| @showsoln{(coe  expr2)}
| @showsoln{(code expr2)}

|*@n*
| @show{    (math expr3)}
| @showsoln{(coe  expr3)}
| @showsoln{(code expr3)}

|*@n*
| @show{    (math expr4)}
| @showsoln{(coe  expr4)}
| @showsoln{(code expr4)}

|===
