= Defining Functions

@lesson-description{Students learn a structured approach to problem 
solving called the “Design Recipe”. They then use these functions 
to filter the animals dataset, using methods.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-intro}
|Product Outcomes
|Students will be able to:

* define several row values from the animals table
* define several functions over rows from the animals table

@worksheet-include{ds-question-types/xtra/lang-prereq.adoc}
|===

== Defining Functions (Time 30 minutes)

Suppose you work at the animal shelter, taking care of all the
animals who live there. You want to make sure they’re healthy,
happy, and find good homes. For each animal, you might want to
ask certain questions:

- What kind of animal is it?
- Has it been fixed?
- When was it born?
- Is it a kitten?

////
Have students brainstorm additional questions!
////

Let’s try finding all the fixed animals by hand. Turn to
@worksheet-link{ds-intro/workbook-pages/animal-dataset-2.adoc},
and walk down the table one row at a time, putting a check next
to each animal that is fixed.

////
Give students 2min to find all the fixed animals they can.
////

What did you do to complete this activity? You went through the
table one row at a time, and for *each row* you did a lookup on the
`fixed` column. Lookups are easy, but they can get really
repetitive!

[.lesson-instruction]
In the Interactions Area, type the code that will look up if
`animalA` is fixed or not. Then type the code to look up if `animalB`
is fixed or not. Repeat for `animalC` and `animalD`. Suppose I wanted
to do this for every animal in the table, just as you did by
hand?

This seems really repetitive, doesn’t it? We keep typing the same
thing over and over, but all that’s really changing is the
animal. Wouldn’t it be great if Pyret had a function called
`is-fixed`, that would do this for us? 

\\\\
Have a student act out the
is-fixed function. You give them an animal, and they tell you
what they would type to find out if it is fixed.
\\\\

Look back to the Definitions Area, and find the line that starts
with `fun is-fixed`. This function isn’t built into Pyret, but it’s
_defined_ here in the program, so we can use it just as if it were
built into the language!

[.lesson-instruction]
Type `is-fixed(animalA)` into the Interactions Area. What did the function do?

You already know about the `.row-n` and `.order-by` methods. But
suppose you want to get a table of only animals that have been
fixed? Try typing this expression into the Interactions Area.
What do you get?

  animals-table.filter(is-fixed)

////
If time allows, ask students to explain what they think is going on.
////

The filter method walks through the table, applying whatever function it was given to each row, and producing a new table containing all the rows for which the function returned true. In this case, we gave it the is-fixed function, so the new table had only rows for fixed animals.

But how do we define functions like this?

To build our own functions, we’ll use a series of steps called the Design Recipe. The Design Recipe is a way to think through the behavior of a function, to make sure we don’t make any mistakes with the animals that depend on us! The Design Recipe has three steps, and we’ll go through them together for our first function.

[.lesson-instruction]
Turn to @worksheet-link{workbook-pages/design-recipe.adoc} in your Student Workbook.

[.lesson-point]
Step 1: Contract and Purpose

The first thing we do is write a Contract for this function. You
already know a lot about contracts: they tell us the Name, Domain
and Range of the function. Our function is named is-fixed, and it
consumes a row from the animals table. It looks up the value in
the fixed column, which will always be a Boolean. A Purpose
Statement is just a description of what the function does:

----
# is-fixed :: (animal :: Row) -> Boolean
# Consumes an animal, and looks up the value in the fixed column
----

Since the contract and purpose statement are notes for humans, we
add the # symbol at the front of the line to turn it into a
comment.

Be sure to check students’ contracts and purpose
statements before having them move on!

[.lesson-point]
Step 2: Write Examples

Examples are a way for us to tell the computer how our function
should behave for a specific input. We can write as many examples
as we want, but they must all be wrapped in an examples: block
and an end statement. Examples start with the name of the
function we’re writing, followed by an example input. Suppose we
have two animals defined, where animalA is fixed and animalB
isn’t. What work do we have to do on each row to look up whether
they are fixed? What is will the result be for each animal?

----
# is-fixed :: (r :: Row) -> Boolean
# Consumes an animal, and looks up the value in the fixed column
examples:
  is-fixed(animalA) is true
  is-fixed(animalB) is false
end
----

////
Make sure students understand (1) that is-fixed came from the
Name in our contract, (2) that animalA and animalB came from the
Domain in our contract, and (3) that the Booleans are determined
by whether those animals are fixed or not.
////

*When writing examples, we replace the look-up operation with the
actual value in the table.*

////
This is a MAJOR point. Make sure students see it (and maybe even repeat it!).
////

[.lesson-point]
Step 3: Define the Function

We start with the fun keyword (short for “function”), followed by
the name of our function and a set of parentheses. This is
exactly how all of our examples started, too. But instead of
writing animalA or animalB, we’ll use the label from our Domain.
Then we add a colon (:) in place of is, and write out the work we
did to get the answers for our examples. Finally, we finish with
the end keyword.

----
# is-fixed :: (animal :: Row) -> Boolean
# Consumes an animal, and looks up the value in the fixed column
examples:
  is-fixed(animalA) is true
  is-fixed(animalB) is false
end
fun is-fixed(animal): animal["fixed"]
end
----

This program is missing examples! Add an examples block in the
Definitions Area, using your animalA and animalB. Check the
Animals Dataset to make sure that your Booleans are correct for
your animals. If you click “Run”, you’ll see a report on whether
the examples are correct. Make sure both of them pass!

////
Walk around to make sure everyone’s examples pass.
////

[.lesson-instruction]
Now let’s try coming up with a totally new function, and use the Design Recipe to help us write it.
- Solve the word problem at the bottom of Page 10.
- Type in the Contract, Purpose Statement, Examples and Definition into the Definitions Area.
- Click “Run”, and make sure all your examples pass!
- Type gender(animalA) into the Interactions Area.

So far, our functions have all been Lookup Functions: they
consume a row, and they look up one column from that row as-is.
And as long as that row contains Boolean values, we can use that
function with the .filter method. But what if we want to filter
by a Boolean expression? For example, what if we want to find out
specifically whether or not an animal is a cat, or whether it’s
young? Let’s walk through an example of a Compute Function using
the Design Recipe, by turning to
@worksheet-link{workbook-pages/design-recipe-2.adoc}.

[.lesson-instruction]
Define a function called `is-cat`, which consumes a row from the
`animals-table` and returns true if the animal is a cat.
- Is this a Lookup, Compute or Relate question?
- What is the name of this function? What are its Domain and Range?
- Is Sasha a cat? _What did you do to get that answer?_

////
Have students explain their thinking carefully, step-by-step. Repeat this with other animals.
////

To find out if an animal is a cat, we look-up the species column
and check to see if that value is _equal_ to `"cat"`. Suppose `animalA`
is a cat and `animalB` is a lizard. What should our examples look
like? *Remember: we replace any lookup with the actual value, and
check to see if it is equal to `"cat"`.*

----
# is-cat :: (r :: Row) -> Boolean
# Consumes an animal, and compute whether the species is "cat"
examples:
  is-cat(animalA) is "cat" == "cat"
  is-cat(animalB) is "dog" == "cat"
end
----

[.lesson-instruction]
Write two examples for your defined animals. Make sure one is a cat and one isn’t!

////
Note that the string on the left is the lookup value: the actual species for that specific animal.
////

As before, we’ll use the pattern from our examples to come up with our definition.

- What is the function name?
- What is the name of the variable(s)?
- What do we do in the body in the function?

----
# is-cat :: (r :: Row) -> Boolean
# Consumes an animal, and compute whether the species is "cat"
examples:
  is-cat(animalA) is "cat" == "cat"
  is-cat(animalB) is "dog" == "cat"
end
fun is-cat(animal): animal["species"] == "cat"
end
----

[.lesson-instruction]
Type this definition -- and its examples! -- into the Definitions
Area, then click “Run” and try using it to filter the
`animals-table`.

[.lesson-instruction]
For practice, try solving the word problem for is-young at the
bottom of @worksheet-link{workbook-pages/design-recipe-2.adoc}.

== More About Table Methods (Time 15 minutes)

Find the contract for `.filter` in your contracts page. The `.filter`
method is taking in a _function_, calling it on every row in the
table, and producing a new table with only the rows for which it
returns `true`.

[.lesson-instruction]
Try using the `gender` function to filter. What happens?

Notice that the Domain for `.filter` says that test must be a
function (that’s the arrow), which consumes a Row and produces a
`Boolean`. If the function we pass in produces anything else, we’ll
get an error.

////
If time allows: have them make a pie chart using a table of only
cats, or a bar chart of only the animals that have been fixed.
////

Sometimes we want to _add a column_ to a table. For example, we
could add a boolean column called `"young"` to the table, which is
`true` if the animal is less than four years old and `false` if it’s
not. Pyret has another method for this.

  animals-table.build-column("young", is-young)

[.lesson-instruction]
Type this into the Interactions Area and hit Enter. What did you get back?

== Closing (Time 5 minutes)

Congratulations! You’ve explored the Animals dataset, formulated
your own questions and begun to think critically about the
connections between data and the questions we ask about it. For
the rest of this course, you’ll be learning new programming and
Data Science skills, practicing them with the Animals dataset and
then applying them to your own data.

////
Have students share which dataset they chose, and pick one question they’re looking at.
////

== Additional Exercises:

- @worksheet-link{workbook-pages/what-can-you-answer.adoc, What
  can you answer?}
