= Fitting Hybrid Models

++++
<style>
/* Add custom CSS to make the math bold, and add coloring to nested circles */
.hybridmath .mathunicode { font-weight: bold !important; }
.hybridCOE { display: inline-block !important; }
.hybridCOE .circleevalsexp { width: unset; vertical-align: middle; }

.hybridCOE .expression { background: rgb(231 231 231) !important; }
.hybridCOE .expression .expression { background: white !important; }

/* Further customized CSS to make any nesting after level 2 50% opaque */
.first .expression > .value { background: white !important; }
.first .circleevalsexp > .expression > .expression > .expression { opacity: 0.5; }
</style>
++++

@description{Students investigate how to combine the types of models they have already learned about. }

@lesson-prereqs{periodic3-fitting-models}

@keywords{periodic, period, amplitude, frequency}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|

- Let's use Pyret to model periodic relationships in data.

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

|===

== Deconstructing Models
@objective{function-composition-programming}

=== Overview

Students explore the historical data, discovering that there's a stronger pattern at work than seasonal periodicity: a seemingly-linear pattern of rising @math{\text{CO}_2} over time. After considering why we ended up with a periodic model initially and how it connects to the larger trend in the data, they practice comparing @vocab{S-values} for the different models they've fit.

=== Launch
@slidestyle{Launch-DN}

@lesson-instruction{
- Let's consider two periodic models built from the `recent-table` using cosine.
- Complete the first section of @printable-exercise{choosing-the-best-model.adoc}, looking at functions defined in the @starter-file{alg2-hybrid}.
}

@slidebreak{Launch}

@indented{
```
fun periodic-cos(x): (4.13 * cos(6.28 * (x - 2023.35))) + 419.87 end 
fun wave-cos(x):     (4.13 * cos(6.28 * (x - 2023.35)))          end 
fun midline-cos(x):                                       419.87 end 
fun periodic-cos2(x):     wave-cos(x)      +      midline-cos(x) end
```
}

@QandA{
@Q{What is going on in `periodic-cos2` and why does it produce the same graph as `periodic-cos`?}
@A{`periodic-cos2` is composed of two functions called `midline-cos` and `wave-cos`:
  * `midline-cos` is just the vertical shift of the `periodic-cos` function.
  * `wave-cos` is all of the parts of the `periodic-cos` function except for that vertical shift.
}
}
@slidebreak{Launch}


@QandA{
@Q{What kind of line passed between the peaks and waves of our `periodic-cos` model?}
@A{horizontal}

@Q{How did that line get defined in our function definition?}
@A{Horizontal lines are defined by a single number - the vertical shift.}
@A{The final term of our `periodic-cos` function definition is the number that defines the position of the horizontal line.}
}

@slidebreak{Launch}

Our `periodic-cos` model has two terms:

- The *periodic term* (@math{4.13 \times cos(2\pi(x - 2023.35))}), which described the wave that wrapped around the horizontal midline
- The *vertical shift* (@math{419.87}), which described the (fixed) y-coordinate of the midline

`periodic-cos2` splits these terms into _separate functions_, and then composes them:

[cols="^.^15a,^.^1a,^.^10a", frame="none", grid="none"]
|===
| [.hybridCOE.first]
@show{(coe '(+ (* 4.13 (cos (* (* 2 PI) (- x 2023.1)))) 419.87))}

| &rarr;

| [.hybridCOE.second]
@show{(coe '(+ (wave-cos x) (midline-cos x)))}
|===
@slidebreak{Launch}

@lesson-instruction{
- Let's take a moment to refresh ourselves on the models we've seen so far and what their key characteristics are.
- Complete the rest of @printable-exercise{choosing-the-best-model.adoc} with your partner.}

@QandA{
@Q{Of the models you sketched and described, which makes the most sense to try fitting to this scatter plot? Why?}
@A{Linear, because the point cloud is rising steadily.}
@Q{Any other Notices or Wonders you would like to share?}
}

=== Investigate
@slidestyle{Investigate}

We built our `periodic-sin` model using data from a small window: _just one year_. The scatter plot we just looked at on @printable-exercise{choosing-the-best-model.adoc} was also generated from @math{\text{CO}_2} data and had a very different shape!

@slidebreak{Investigate-DN}

@lesson-instruction{
- Open the @starter-file{alg2-hybrid} and click "Run".
- Make a scatter plot of @math{\text{CO}_2} over time for the `modern-table`, which includes historical @math{\text{CO}_2} levels from 2010 to 2023.
- What do you Notice? What do you Wonder?
}

@ifslide{@teacher{Proceed to the next slide, which includes the scatter plot, before discussing Notices and Wonders.}}

@slidebreak{InvestigateC}

@center{@image{images/modern-co2-scatter.png, 500}}

@QandA{
@Q{Why might somebody describe the shape of this data as @vocab{linear}?}
@A{Because we could draw a diagonal line with a positive slope through the middle of the wave and it would do a pretty good job of summarizing the trend.}
@Q{Why might somebody describe the shape of this data as @vocab{periodic}?}
@A{Because there is a consistent wave that goes up and down in regular intervals.}
}

@slidebreak{Investigate-DN}

@lesson-instruction{
- Turn to @printable-exercise{modeling-modern-co2.adoc}.
- Start by finding the section of the @starter-file{alg2-hybrid} where you're asked to "Define your periodic-sin functions..."
  * Define `periodic-sin` to be the periodic model you found using Desmos.
  *** You should already have defined it in @opt-starter-file{alg2-co2} and on @lesson-link{periodic3-fitting-models/pages/modeling-recent-co2-2.adoc}.
  * Using the deconstruction of `periodic-cos` as your model, change the other three functions in this section to show how to separate the wave and midline of your `periodic-sin` model and define `periodic-sin2` using function composition.
- Work with your partner to fit linear and periodic models to the `modern-table`. This @math{\text{CO}_2} data is from 2010 to 2023.
}


@slidebreak{Investigate}

[cols="^1a,^1a", options="header"]
|===
| Optimal Linear Model			| Our Periodic Model
|@image{images/modern-lr.png}	|@image{images/modern-co2-model-soln.png}
|===

@QandA{
@Q{How would you describe how the `linear-modern` model fit our `modern-table` data?}
@A{The @vocab{linear regression} plot shows the @vocab{line of best fit} passing through the middle of the diagonal wave of points.}

@Q{How would you describe how our `periodic-sin` model fits the shape of the data from the `modern-table`?}
@A{Answers will vary. Make sure discussion addresses residuals. Sample responses may include:
 * While they both have a wave, they look pretty different!
 * The model undulates around a horizontal line and the data undulates around a diagonal line.
 * The y-intercepts are in completely different places.
 * When we fit the `periodic-sin` model to the data we see the model as a horizontal wave at the top, eventually lining up with the points on the right hand side of the graph.
 * We also see vertical residuals showing the distance between each data point and the model.
}
}

@slidebreak{InvestigateR}

@ifslide{@image{images/modern-co2-model-soln.png,350}}

@QandA{
@Q{Where does the `periodic-sin` model fit the `modern-table` data best?}
@A{Within the range of the dataset that it was built on.}
@Q{Where does the `periodic-sin` model fit the `modern-table` data worst?}
@A{The farther we get from the date range it was built on.}
}

@slidebreak{Investigate}

@QandA{
@Q{How would you describe the shape of the model you drew that would be optimal?}
@A{Hopefully students will describe a wave whose midline is diagonal.}
}

=== Synthesize
@slidestyle{Synthesize}

@QandA{
@Q{We built the `periodic-sin` model to fit the data in the `recent-table`. Why doesn't it do a good job of predicting @math{CO_2} levels for a larger time frame?}
@A{Models are only reliable within the span of the data from which they were created. The fact that the model fit `recent-table` well means it's a good model for the data in _that year_, but we can't make any assumptions about dates outside of the range of the training data.}
}

== Hybrid Models

=== Overview

Students explore the possibility that a model could combine various kinds of models and use function composition to define functions from other functions.

@teacher{
We've chosen to describe these models as hybrid in order to make it accessible to students, but this is not a mathematical term. If you're looking to connect this lesson to related materials, polynomial functions and/or function addition are terms that might turn up relevant reading. 
}

=== Launch
@slidestyle{LaunchR}

@ifslide{@right{@image{images/historical-scatter-plot.png}}} 
When we zoom out to see the historical @math{\text{CO}_2} data, we see that there are two different things going on:

1. The amount of @math{\text{CO}_2} in the air _generally_ rises over time, for a positive, linear relationship with the year.
2. There are seasonal, periodic variations that cause @math{\text{CO}_2} to fluctuate up and down across that line.

The wave is following a diagonal line... {nbsp}so the midline for our model shouldn't be horizontal at all!  

@slidebreak{Launch}

@lesson-instruction{
- *Is it possible for a model to be both linear _and_ periodic?*
- With your partner, complete @printable-exercise{hybrid.adoc}.
}

@slidebreak{Launch}

@QandA{
@Q{What line should our model wrap around?}
@A{Our line of best fit!}

@Q{What happens when you fit your `hybrid-modern` model to the `modern-table` data?}
@A{The model should now look like waves along a diagonal.}

@Q{How much less error do we expect from predictions made with `hybrid-modern` than with `linear-modern`?}
@A{38%}
}

@slidebreak{Launch}

By replacing the vertical shift term in our periodic model with the linear model from `lr-plot`, we get the best of both worlds:

- Linear behavior for the midline representing the long-term trend...
- Periodic behavior for the seasonal variation in @math{\text{CO}_2}

[cols="^1a" grid="none", frame="none", stripes="none"]
|===
| [.hybridmath]
@big{*@math{f(x) = 4.13 \times sin(2\pi(x - 2023.1)) + (1.8345x + -3296)}*}

|
[.hybridCOE]
@show{(coe '(+ (wave-sin x) (linear-modern x)))}
|===

@slidebreak{Launch}

We can visualize the body of the function using the Circles of Evaluation.

@lesson-instruction{
- Now that you know how to build a hybrid model, let's have you try building one on your own! 
- Turn to @printable-exercise{more-hybrid.adoc} and build a hybrid model for the full @math{\text{CO}_2} data.
}

=== Synthesize
@slidestyle{Synthesize}

@QandA{
@Q{Why did our hybrid model fit better than the periodic or linear models alone?}
@A{Because it captures both the overarching trend and the seasonal trend.}

@Q{Why doesn't it make sense to compare the following @vocab{S-values}?
 
* the error we expect for predictions made from our `periodic-sin` model with the data in the `modern-table`
* the error we expect for predictions made from our `periodic-sin` model with the data in the `recent-table`
}
@A{The datasets have completely different ranges!}

@Q{Internet memes start out being shared from friend to friend, growing slowly until they "go viral". What would a hybrid model for meme growth look like, and what kinds of models would need to be combined?}
@A{Before it goes viral, the growth of a meme probably looks linear (growing faster in the beginning than an exponential model), but eventually the steep part of the curve takes over, and the model looks exponential.}
}

@ifnotslide{
@strategy{Going Deeper}{
- If students look carefully at the fit of their hybrid periodic model to the `co2-table`, they'll see that the model _under-predicts_ at the beginning of the graph, then _over-predicts_ in the middle, the _under-predicts_ again at the end. Is it possible that there's an _even-better_ hybrid model, which mixes periodic growth with something other than linear?
- Have your students refer back to @lesson-link{exponential1-exploring-covid}. As with the `recent-table` table in @starter-file{alg2-hybrid}, the starter file there constrains the dataset to show only recent data. This is done for the same reason: to introduce students to a more perfectly-exponential model. Now that students know how to combine terms from different models, they can go back and build a model that fits the entire Covid dataset!
}
}

