= Character Movement in Two Dimensions

[.center]
@ifproglang{wescheme}{
@show{
  (contract "update-danger" '("Number") "Number"
	"takes in danger's x-coordinate and produces the next one")
}
}
@ifproglang{pyret}{
@show{
  (contract "update-danger" '("Number" "Number") "Number"
	"takes in danger's x and y-coordinates and produces the next x-coordinate")
}
}

The `update-danger` function only moves our `DANGER` left or right... because it doesn't do anything with the y-coordinate!

Suppose we wanted to write a new function, `update-danger-2` that moves the `DANGER` _diagonally_...

@vspace{1ex}

@n What, if anything, will have to change about the Domain? @fitb{}{@ifproglang{wescheme}{@ifsoln{It will need two Numbers!}}@ifproglang{pyret}{@ifsoln{Nothing! It's already taking in 2 Numbers, it just isn't using both of them.}}

@n What, if anything, will have to change about the Range? @fitb{}{@ifsoln{It will need a second Number.}}

@vspace{1ex}
Since an (x, y) coordinate has two Numbers, one idea might be to write the contract this way:

[.center]
@show{
  (contract "update-danger-2" '("Number Number") "Number Number"
	"take in danger's x- and y-coordinate, and produces the next x- and next y-coordinate")
}

...But that contract breaks an important rule about functions: **Given an input, _all functions must produce one output!_**

@vspace{1ex}

Fortunately, our programming language has another data type, called a Posn, which utilizes two Numbers to describe a single "position"! We can make a Posn to represent the position (100, 200) with the following code: @show{ (code '(make-posn 100 200)) }

@n What expression will make a Posn representing the origin? @fitb{}{@showsoln{(code '(make-posn 0 0))}}

@n Write the contract for the @show{(code 'make-posn)} function on the line below.

@fitb{}{@showsoln{(contract "make-posn" '("Number Number") "Posn")}}

@vspace{1ex}

@include{fragments/danger2.adoc}

@vspace{1ex}

*Add your new function (including contract, purpose, examples, and definition) to your game file and change `update-danger` to `update-danger-2` in the list at the very end of the file to make your `DANGER` and `TARGET` move in two dimensions!*
