= Exercise: Matching Contracts and Examples (2)

++++
<style>
tt.pyret, tt.racket { font-size: .8rem; }
td {padding: 20px 0px !important; }
</style>
++++

@do{

(define e5a
   (code #:multi-line #t
"examples:
  match(30) is star(30 * 2, \"outline\", \"purple\")
end"))

(define e5b
   (code #:multi-line #t
"examples:
  match(24) is star(24 * 2, \"outline\", \"purple\")
end"))

(define e6a
   (code #:multi-line #t
"examples:
  match(star(20, \"outline\", \"red\"), 3) is
    3 * image-height(star(20, \"outline\", \"red\"))
end"))

(define e6b
   (code #:multi-line #t
"examples:
  match(circle(10, \"solid\", \"red\"), 6) is
    6 * image-height(circle(10, \"solid\", \"red\"))
end"))

(define e7a
   (code #:multi-line #t
"examples:
  match(\"triangle\", \"blue\") is
    triangle(40, \"outline\", \"blue\")
end"))

(define e8a
   (code #:multi-line #t
"examples:
  match(string-length(\"B\"), string-length(\"AT\")) is
    1 + 2
end"))

(define e9a
   (code #:multi-line #t
"examples:
  match(string-length(\"tabletop\")) is \"8\"
end"))

(define e9b
   (code #:multi-line #t
"examples:
  match(1.5) is \"greather than 1\"
end"))

(define c5 (code "# match :: Number -> Image"))
(define c6 (code "# match :: Image, Number -> Number"))
(define c7 (code "# match :: String, String -> Image"))
(define c8 (code "# match :: Number, Number -> Number"))
(define c9 (code "# match :: Number -> String"))

#|
(define answer-key
   (list  (list e5a c5)
          (list e5b c5)
          (list e6a c6)
          (list e6b c6)
          (list e7a c7)
          (list e8a c8)
          (list e9a c9)
          (list e9b c9)
          ))

|#
}


Match each Example on the left with the Contract on the right. NOTE: Multiple examples may match to the same contract!

[cols=".^12a,^.^2a,2a,^.^1a,.^8a",options="header",stripes="none",grid="none",frame="none"]
|===
| Contract                   |                      ||       | Examples
| @show{e9b}   |*1*@showsoln{"-A" }||       |
| @show{e5b}   |*2*@showsoln{"-B" }||       |
| @show{e9a}   |*3*@showsoln{"-A" }||*A*    | @show{c9}
| @show{e6a}   |*4*@showsoln{"-E" }||*B*    | @show{c5}
| @show{e6b}   |*5*@showsoln{"-E" }||*C*    | @show{c8}
| @show{e7a}   |*6*@showsoln{"-D" }||*D*    | @show{c7}
| @show{e5a}   |*7*@showsoln{"-B" }||*E*    | @show{c6}
| @show{e8a}   |*8*@showsoln{"-C" }||       |
|===
