= Top Down or Bottom Up

++++
<style>
.MathJax{ margin-bottom: 5ex; display: inline-block; }
</style>
++++

Jamal’s trip requires him to drive 20mi to the airport, fly 2,300mi, and then take a bus 6mi to his hotel. His average speed driving to the airport is 40mph, the average speed of an airplane is 575mph, and the average speed of his bus is 15mph.

Aside from time waiting for the plane or bus, how long is Jamal in transit?

@vspace{1ex}

[cols="2a, 2a" options="header", stripes="none"]
|===
| *Bear's Strategy:*	| *Lion's Strategy:*
|
@math{Drive Time = 20 miles \times \frac{1hour}{40 miles} = 0.5 hours}

@math{Fly Time = 2300 miles \times \frac{1hour}{575 miles} = 4 hours}

@math{Bus Time = 6 miles \times \frac{1hour}{15 miles} = 0.4 hours}

@math{In Transit Time = Drive Time + Fly Time + Bus Time}

@math{0.5 + 4 + 0.4 = 4.9 hours}

|
@math{In Transit Time = Drive Time + Fly Time + Bus Time}

@math{Drive Time = 20 miles \times \frac{1hour}{40 miles} = 0.5 hours}

@math{Fly Time = 2300 miles \times \frac{1hour}{575 miles} = 4 hours}

@math{Bus Time = 6 miles \times \frac{1hour}{15 miles} = 0.4 hours}

@math{0.5 + 4 + 0.4 = 4.9 hours}

|===

@vspace{1ex}
   
@n Whose Strategy was Top Down? How do you know?

@vspace{7ex}

@n Whose Strategy was Bottom Up? How do you know?

@vspace{7ex}

@n Which way of thinking about the problem makes more sense to you?

@vspace{7ex}


[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{What's happening with that Math?!}

Setting up the problem so that the units will cancel out helps us to know whether to divide or multiply! In this case, in order to cancel out the miles, 40 miles has to go on the bottom, so we end up dividing by 40.

@vspace{1ex}

@math{20 mi \times \frac{1 hr}{40 mi} = \frac{20 \require{enclose} \enclose{horizontalstrike}{mi} \times 1hr}{40 \require{enclose} \enclose{horizontalstrike}{mi}} = \frac{20 hr}{40} =20 \div 40 = 0.5 hrs}
|===
