= Top Down or Bottom Up

Jamal’s trip requires him to drive 20mi to the airport, fly 9,000mi, and then take a bus 6mi to his hotel. His average speed driving to the airport is 40mph, the average speed of an airplane is 575mph, and the average speed of his bus is 15mph.

Aside from time waiting for the plane or bus, how long is Jamal in transit?

Bear's Strategy:

Drive Time = @math{20 miles \times \frac{1hour}{40 miles} = 0.5 hours}
Fly Time = @math{9000 miles \times \frac{1hour}{575 miles} = 15.652173913 hours}
Bus Time = @math{6 miles \times \frac{1hour}{15 miles} = 0.4 hours}
In Transit Time = Drive Time + Fly Time + Bus Time = 0.5 + 15.652173913 + 0.4

Lion's Strategy: 

In Transit Time = Drive Time + Fly Time + Bus Time
Drive Time = @math{20 miles \times \frac{1hour}{40 miles} = 0.5 hours}
Fly Time = @math{9000 miles \times \frac{1hour}{575 miles} = 15.652173913 hours}
Bus Time = @math{6 miles \times \frac{1hour}{15 miles} = 0.4 hours}
In Transit Time = 0.5 + 15.652173913 + 0.4 = 16.552173913
   
@n Whose Strategy was Top Down? How do you know?

@vspace{5ex}

@n Whose Strategy was Bottom Up? How do you know?

@vspace{5ex}

@ Which way of thinking about the problem makes more sense to you?

@vspace{5ex}?
