= Exploring Table Functions

Make sure you've opened the @starter-file{table-functions} on your computer, and clicked "Run".

== Filtering Rows
@n What does @show{(code '(filter animals-table lookup-fixed))} evaluate to? Describe the value you get back below.

@fitb{}{@ifsoln{A table with only the fixed animals}}

@n What does @show{(code '(filter animals-table is-dog))} evaluate to? Describe the value you get back below.

@fitb{}{@ifsoln{A table with only the dogs}}

@n Write the code to generate a table of only old animals. @fitb{}{@showsoln{(code '(filter animals-table is-old))}}

@n In the Definitions Area, define `dogs` by writing @show{(code '(define dogs (filter animals-table is-dog)))}. Click "Run" and evaluate `dogs` in the Interactions Area.

@n In the Definitions Area, define `old` to be a table of only old animals. @fitb{}{@showsoln{(code '(define old (filter animals-table is-old)))}}

@n What do the contracts for `lookup-fixed`, `is-dog`, and `is-old` have in common?

@fitb{}{@ifsoln{They all produce Booleans}}

@n Find the contract for `filter` in your Contracts page. Explain how `filter` uses the two inputs specified in the Domain.

@fitb{}{@ifsoln{`filter` needs a Table, and the name of a function. It makes a new}}

@fitb{}{@ifsoln{copy of the table, leaving out rows for which the function produces false}}

@fitb{}{}

@n What happens if you evaluate `filter(animals-table, lookup-name)`? Why?

@fitb{}{@ifsoln{Error, because the function must produce a Boolean}}


== Building Columns
@n What does @show{(code '(build-column animals-table "old" is-old))} evaluate to?

@fitb{}{@ifsoln{A table with a new column called "old", filled with values from `is-old`}}

@n What does @show{(code '(build-column animals-table "sticker" label))} evaluate to?

@fitb{}{@ifsoln{A table with a new column called "sticker", filled with values from `label`}}

@n Find the contract for `build-column` in your Contracts page. Explain how `build-column` uses the three inputs specified in the Domain.

@fitb{}{@ifsoln{`build-column` needs a Table, the name of a column to add, and the name of a function.}}

@fitb{}{@ifsoln{It makes a new copy of the table, adding the column, and filling it by}}

@fitb{}{@ifsoln{applying the function to each row}}

@fitb{}{}

== Challenge!

★ In the Definitions Area, define a table of your own using `filter`, `build-column`, or `sort`. Add a comment to describe what's in it!
