= Bootstrap:Algebra Pathway

++++
<style>
.announcement {
	font-style: italic;
    background: #B6D990aa;
    border: #75328A 1px dashed;
    padding: 10px;
}
.announcement a {
	color: black;
	text-decoration: underline;
}
</style>
++++

[.logo]
@image{images/Logo.png, Bootstrap:Algebra}

== Teaching Remotely?
If you're teaching remotely, we've assembled an @link{../../ImplementationNotes.shtml, Implementation Notes} page that makes specific recommendations for in-person v. remote instruction.


[.announcement]
**The earlier version of our materials is also available @link{https://bootstrapworld.org/materials/spring2020/courses/algebra/es-mx/index.shtml, en Español}.** Let us know if you can @link{mailto:contact@BootstrapWorld.org, lend a hand} translating the new version!

== Ordering Student Workbooks?
While we give our workbooks away as a PDF (see below), we understand that printing them yourself can be expensive! You can purchase beautifully-bound copies of the student workbook from Lulu.com. 
@ifproglang{wescheme}{@link{https://www.lulu.com/en/us/shop/dorai-sitaram-and-ed-campos-and-jennifer-poole-and-flannery-denny/bootstrapalgebra-student-workbook-wescheme/paperback/product-4j9rmj.html, Click here to order}.}
@ifproglang{pyret}{@link{https://www.lulu.com/en/us/shop/dorai-sitaram-and-ed-campos-and-jennifer-poole-and-flannery-denny/bootstrapalgebra-student-workbook-pyret/paperback/product-6j9zek.html, Click here to order}.}

