= mdquiz

== Authoring Quizzes

Edits get made in .toml files saved in the `sample-quiz/src` folder
	
	`__Authoring/sample-lesson/langs/en-us/sample-quiz/src/file-name.toml`

We currently can only write:
- short answer questions 
- multiple choice question (but these can have just two option or many options)

== Building Quizzes

After we save, go to the terminal

- cd into the folder that contains the quiz using the following command:

	`cd lessons/__Authoring/__sample-lesson/langs/en-us/sample-quiz`


- build the distribution folder using the following command line in the terminal

	`npm exec vite build` 


- cd into the newly created dist folder using 

	`cd dist`


- launch a web server by running

	`python3 -m http.server` 


- open a new browser window in Chrome / Brave etc.

- Type `localhost:8000 into the navbar


== After making edits and saving a file go back to the terminal

=== Option 1:

- kill the web server from the terminal with the command control c

- cd back to the sample-quiz folder using `cd ../`

- run `npm exec vite build` in the terminal

- cd into the newly created dist folder using `cd dist`

- run `python3 -m http.server` to launch a new tiny web server

- launch a browser and to go localhost:8000

=== Option 2: 

- leave the web server running and tell unix to run the server in the background

	* control Z to suspend the server
 	* then bg to run it in the background
 	* then enter to get back to a new command line
  	* after that just need to run `npm exec vite build` in the terminal after edits are saved in the .toml file

- when done working with the .toml file and ready to move on

	* fg in terminal to bring it back to the foreground and it will look like the terminal is stalled
	* control c to kill it

=== Option 3:

- use `python3 -m http.server &` from the getgo and it will run in the background to begin with
- fg when ready stop running it and it will look like the terminal is stalled
- control c
(if control c doesn't work for some reason control shift backslash otherwise known as control | )
