= Asciidoc Command Notes for New Authors - read (at least in part) as an asciidoc.

== Don't be afraid to ask!

	* Sometimes it's way more efficient to post a question to the curriculum remix team
	* It might also be true that your work will surface a bug in something somebody else did and you won't be able to solve the problem alone!

=== Some files have commented notes to authors at the top because our system has layers and is dependent on other systems, which sometimes require work arounds.

The one that seems to work the best is:

@comment{}

But you will also see:

// comments out a section

////
comments out lines of code in between
////

If you're commenting out something in a table use @scrub{}


=== Heads up!

Some asciidoc files use multiple languages! asciidoc, css, racket, mathjax...

== Text formatting

=== Style

- *bold*
- _italics_
- __ `italics` if the formatting of the phrase is more complicated __
- [.underline]#underline#

@show{(code 'code)}
@show{(code '(coded sentences with "punctuation"))}
We are trying to write all functions using `code` ...
It's special Dorai wizardry that will
- take whatever we write in racket and automatically translate it into pyret if the document is opened in a pyret version
- autogenerate a list of functions used in the lesson plan and accompanying pages for a language prerequisites table
- who knows what other fabulous things it will do by the time you're reading this ;)

Widespread use of `sexp` in lesson plans is relatively recent, so you will also see code written like this.
- `code`
_``code`` at the beginning of an italicized sentence_

Feel free to update expressions you encounter to use `code`!
(And to use the alternate version of formatting code in text when wanting to format code that is outside the bounds of what `sexp` is used for.)


Vocab words like @vocab{variable} get flagged using the ``@````vocab`` directive when they are:

@n focal to the lesson and

@n focal to the sentence you're using it in.

_If you flag a word as a vocabulary word, be sure to add it to the glossary in both plural and singular form. The glossary is found in the curriculum directory (shared is at the same level as lessons and within that you will find glossary-terms.rkt)_

=== Size

- all sizes in bootstrap are written in `rem` not `pt` (10 pt = 1.1em) so that changes to the system as a whole can happen without having to rework font sizes on each section of each page individually.
- rem stands for relative em (em is a unit equivalent to the width of the letter "m")

== Formatting parts of the page

=== To center text horizontally on the line

@center{this text will be centered}

=== Vertical spaces between lines of text

Vertical space is measured in "ex" (a unit equivalent to the height of the letter x.)
@vspace{1ex}

=== Fill in the Blank lines for students to write on

Width is measured in "em" (a unit equivalent to the width of the letter "m")
@fitb{30em}{if you want text to appear on the line, type it here}
@fitb{30em}{} whether or not you want something on the line you have to include the second set of brackets or it will break the build

@right{@fitb{60ex}{}}

This makes a line that fills the whole width of the page:
// This blank line is necessary, if you want the fill-in-the-blank to be in on its own line!
@fitb{}{}

NOTE: to fill the whole page, the directive must have a blank line between it and the text above.

=== Horizontal space between words on the same line

If you need significant space between words @hspace{15em} will create that gap.

=== Links

These 7 directives are for links that appear in the lesson plan and should be auto-included in the list of materials at the start of the lesson plan including starter files, projects, workbook pages, desmos activities, etc.  (See comments in asciidoc)

_Note: What is included in the workbook is determined by what is listed in the workbook-pages.txt file in the lesson's "pages" folder._

@comment{
- @printable-exercise{whateverthepagetitleis.adoc} This is for workbook pages only and will automatically be shown with the title and the page number in the lesson plan.
- @opt-printable-exercise{whateverthepagetitleis.adoc} This is for pages that can be printed but are not going to be included in the workbook. W
- @online-exercise{whateverthelink is} or  @online-exercise{whateverthelink is, however you want the link to be named in the lesson plan}. This link is designed for things that we expect all teachers to use while teaching the lesson
- @starter-file{} and @opt-starter-file{whatever it's called in shared/starter-files.rkt} This link will automatically include the correct link for the language, will list starter files in the materials section, and will also list starter files in teacher resources.

Lesson slides and other external links can also be linked using @link{}
If you're using @link{} you need to use the file ending .html instead of .adoc
}

=== Bullet points

- First level bullets can be written using hyphens.
- It's important to leave a space after the dash and a blank line before the first line of the list
  * Second level bullets can be written using an asterisk with 2 spaces before it
  	 *** third level bullets
     *** more third level bullets
  * the list continues
- however we need it to.

For Questions and Answer sections (where A are hidden on slides)

@QandA{
@Q{What strategies did you use to match the dot plots to the box plots}
@A{Answers will vary. Sample responses may include:
 - I looked for the maximum and minimum values.
 - I looked at the shape of the data, starting with whether or not it was symmetrical.
 - I looked for tall clusters of points on the dot plot and matching narrow quarters on the box plot.
}
}


@n we have a special autonumbering command that will

@n keep numbering top to bottom

@n even if you go in and out of a table or other formatting

@n but it's new

1. so you will see
2. some pages that are
3. numbered like this instead
4. if you have energy, switch them to our new numbering command

@star is used for challenge problems

Checkboxes can be written as follows:
@ifnotsoln{
- [ ] There are potential outliers at @fitb{}{}
}
@ifsoln{
- [x] There are potential outliers at @fitb{}{45 and 500} 	
}
- [ ] There do not appear to be any potential outliers.

Code for including an arrow
[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(+ 1 (* 2 3)))}
| __?__ &rarr;
| @show{(coe '(+ 2 (* 1 3)))}
|===

=== Tables


In the code below, cols= could also be defined more simply as 4,2,3,1.

You can change the numbers to shift the ratio of the width of the columns and add or subtract numbers to increase or decrease the number of colummsn.

The other formatting defines where in the cell the words end up being placed (see alignment notes below)

[cols="^.^4,<.^2,>.>3, 1" options="header", stripes="none", grid="none", frame="none"]
|===
| each vertical 	| bar 		| is 		| a
| break 			| between 	| columns	| .
|===

==== Aligning text within the table

- without a dot, we mean horizontal alignment.
- With a dot before it, we mean vertical alignment.
- < means to the left (horizontally) or top (vertically).
- ^ is center (horizontally or vertically)
- > pushes to the right (horizontally) or bottom (vertically).
- ^.^ centers both horizontally & vertically

==== Inserting a table within a table
[cols="1a,1a,1a"]
|===
| add a to the column width to let asciidoc know to look out for something complicated
| and
!===
! this 	! part
! is 	! nested
!===

|  [cols="1a,1a"]
!===
! this 	! part
! is 	! nested
!===

|===

=== Programming Language specific content

When possible, use Dorai the Wizard's Special Code that automatically converts code you write into the correct programming language for the pathway.

@show{(code '(text "Math is fun!" 30 "red"))}

There are language specific commands (see asciidoc file):

- @ifproglang{wescheme}{}
- @ifproglang{pyret}{}

There are also pathyway specific commands, which we only use sparingly to include optional pages in core materials (see asciidoc file):

- @ifpathway{data-science}{}

=== Indentation
You can use

@indented{and whatever you write in here will be indented}


=== Landscape pages

_see comment_

@comment{
[.landscape] in the first line of the file makes it landscape
}

=== Special symbols can be included using unicode

@link{https://unicode-table.com/en/search/?q=triangle}

== Solutions!

The easy way is to make a copy of the page, add the solutions as you want them to appear, and put in the solution-pages folder for the same lesson.

The elegant way (which occasionally is impossible and you have to accept the easy way) is to use the command `@showsoln{}` in the original document for whatever you only want to only appear in the solutions mode version of the document. Whatever goes inside the brackets has to read as racket, so strings go in quotes.


== Images

The ``@````image`` and ``@````centered-image`` directives take in the name/location of the file and an optional width specification.

Copies of images should be saved in the images folder inside the lesson plan, preferably as png files.

All images used in materials (unless only used in slides.md files) must also be listed in the lesson-images.json files found inside the images file for the lesson.

There are three required fields that will throw warnings if you don't provide info.
"description" : "This is a detailed description of the information provided in the image that will be read aloud by screen readers so that visually impaired students have the info they need to engage with our materials"
"source" : "Be specific about whether we made the image (based on other work, based on data from a source, based on contrived data) or someone else made it"
"license" : ""

If you want a caption to appear beneath the image on the webpage and printed page for sighted users you can use the optional "caption" : "" argument. 

