= Visualizing the “Shape” of Data

@lesson-description{Students explore the concept of "shape", using
histograms to infer whether a dataset has skew, and what the direction
of the skew means. They apply this knowledge to the Animals Dataset,
and then to their own.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-exploring-your-dataset}
|Product Outcomes
|Students create

* histograms using the animals dataset
* visualizations of frequency using their chosen dataset, and write up their findings

@worksheet-include{xtra/lang-prereq.adoc}
|===


== Describing Shape  (Time 30 minutes)

Let’s get some practice reading histograms, and figuring out what they mean.
[.lesson-instruction]
Turn to @worksheet-link{workbook-pages/making-histograms.adoc}, and complete the matching activity there.

Shape is one way to _summarize_ information in a dataset, to
quickly describe what values are more or less common. imageA more
general way to summarize the shape of a data set like this, which
contains a few unusually high values, is to say that it is
“*skewed right, or has high outliers*.”

Here are the most common shapes that we see for real-world data sets:

[.lesson-point]
Symmetric: values are balanced on either side of the middle.

It’s just as likely for the variable to take a value a certain
distance below the middle as it is to take a value that same
distance above the middle. Examples:
- Heights of 12-year-olds would have a symmetric shape. It’s just
  as likely for a 12-year-old to be a certain number of inches
  below average height as it is to be that number of inches above
  average height.
- In a standardized test, most students score fairly close to
  what’s average. Also, we see just as many students scoring a
  certain number of points above average as we see scoring that
  same number of points below average. The shape is symmetric
  (and bulges in the middle because most students score fairly
  close to what’s average).

[.lesson-point]
Skewed left, or low outliers.

Values are clumped around what’s typical, but they trail off with
a few unusually low values. Examples:

- Number of teeth that adults have in their mouths would be
  skewed left or have low outliers. Most adults will have close
  to a full set of 32 teeth, but a few of them with serious
  dental problems would have a very small number of teeth. We
  won’t get anyone in our data set who has 10 or 20 _extra_ teeth
  in their mouths!
- If most students did pretty well on an exam, but a few students
  performed very badly, then we’d see a shape that has left
  skewness and/or low outliers.

[.lesson-point]
Skewed right, or high outliers.

Values are clumped around what’s typical, but they trail off with
a few unusually high values. We see this shape often in the real
world, because there are many variables -- like “income” or “time
spent on the phone” -- for which a few individuals have unusually
high values, which aren’t balanced out by unusually low values
(things like “income” and “phone time” can’t be less than zero).
Examples:

- Age when a woman in the U.S. gives birth would be skewed right
  or have high outliers. A few women would be unusually old, 40
  years or even more above the average age of 26 (check the
  tabloids!), but none of them could be even close to 40 years
  below average to balance things out!
- A data set of earnings almost always shows right skewness or
  high outliers, because there are usually a few values that are
  so far above average, they can’t be balanced out by any values
  that are so far below average. (Earnings can’t be negative.)

To build a histogram, we start by sorting all of the numbers in
our column from smallest to largest, marking our x-axis from the
smallest value to the largest value and dividing into
equally-sized intervals, or “bins”. Once we have our bins, we put
each value in our dataset into the bin it belongs, and then count
how many values are in each bin. This count determines the height
of the bars on our y-axis.

[.lesson-instruction]
Turn to @worksheet-link{workbook-pages/making-histograms.adoc}, and try drawing a histogram from a dataset.

////
Note that interals on this display include the left endpoint but
not the right. If we included the right endpoint and someone had
0 teeth, we’d have to add on a bar from -5 to 0, which would be
awfully strange!
////

*The size of the bins matters a lot!* Bins that are too small will
hide the shape of the data by breaking it into too many short
columns. Bins that are too large will hide the shape by squeezing
the data into just a few tall columns. In this workbook exercise,
the bins were provided for you. But how do you choose a good
bin-size?

[.lesson-point]
Rule of thumb: a histogram should have between 5–10 bins.

Let’s make a histogram for the pounds column in the animals table, sorting the animals into 20-pound bins:
----
histogram(animals-table, "pounds", 20)
----

[.lesson-instruction]
--
Would you describe the shape of your histogram as being skewed
left/low outliers or symmetric or skewed right/high outliers?
Which one of these statements is justified by the histogram’s
shape?

- A few of the animals were unusually light.
- A few of the animals were unusually heavy.
- It was just as likely for an animal to be a certain amount
  below average weight as it was for an animal to be that amount
  above average weight.

Try bins of 1-pound intervals, then 100-pound intervals. Which of
these three histograms best satisfies our rule of thumb?
--

[.lesson-instruction]
*Challenge*: Compare histograms for pounds of cats vs. dogs in
the dataset. Are their shapes different? If so, how?

[.lesson-instruction]
On @worksheet-link{workbook-pages/shape-of-animals-dataset.adoc},
describe the pounds histogram and another one you make yourself.
When writing down what you notice, try to use the language Data
Scientists use, and discuss skew and outliers.

== Your Dataset (Time 20 minutes)

[.lesson-instruction]
How is your dataset distributed? Choose two quantitative
variables and display them with histograms. Explain what you
learn by looking at these displays. If you’re looking at a
particular subset of the data, make sure you write that up in
your findings on
@worksheet-link{workbook-pages/shape-of-my-dataset.adoc}.

Give students 10–15 min to make their next set, and have them
share back. Encourage students to read their observations aloud,
to make sure they get practice saying and hearing these
observations.

== Closing (Time 5 minutes)

[.lesson-instruction]
Histograms are a powerful way to display a data set and assess
its @vocab{shape}. But shape is just one of three key aspects that tell
us what’s going on with a quantitative data set. In the next
unit, we’ll explore the other two: center and spread.
