[.beta]
= Evaluating Decision Trees
++++
<style>
/* allow lesson-points to co-exist with images */
.lesson-point{ clear: unset !important; }

/* force some images to have a white background */
.white-bg { background-color: white; display: block; }

.highlight-diagonal tr:nth-child(1) td:nth-child(2),
.highlight-diagonal tr:nth-child(2) td:nth-child(3),
.highlight-diagonal tr:nth-child(3) td:nth-child(4),
.highlight-diagonal tr:nth-child(4) td:nth-child(5),
.highlight-diagonal tr:nth-child(5) td:nth-child(6) {
  background: var(--bs-secondary-lighter-supernova) !important;
  color: white !important;
  font-weight: bold;
}
</style>
++++

@description{Students explore an approach to recommending videos and predicting election outcomes. They develop and analyze decision trees to predict individuals’ purchasing decisions.}

@lesson-prereqs{decision-trees-building}


@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|

- Let's learn about how to evaluate the _accuracy_ of a classifier
- Let's learn how the distribution in the training dataset influences the trees we build

| Materials
|[.materials-links]
@material-links


|===

== Report Cards for Classifiers

@objective{}

=== Overview
Students learn how to generate decision trees in Pyret, and turn them into functions.

=== Launch

@slidebreak{LaunchR}
--
@lesson-point{A @vocab{decision tree} is one way to model the structure hidden in the data.}

@QandA{
@right{@image{images/tree-3.png}}
@Q{What do we call the nodes in a decision tree?}
@A{Decision Nodes}

@Q{What do we call the _top_ node (the "first decision")?}
@A{Root Node}

@Q{What do we call the different targets (or "endpoints") of a decision tree?}
@A{Leaf Nodes}

@Q{How do decision trees help us _classify_ things?}
@A{When given a row from a table, narrow down the possible targets it could belong to}

@Q{When building a decision tree, how do we select a good decision node?}
@A{We want to pick a node that sorts the data into the neatest, most organized piles possible.}
}
--
@slidebreak{Launch}

@slidebreak{Launch-DN}
[cols="^.^1a,^3a", frame="none", grid="none"]
|===
| @image{images/tail-classifier-tree.png}
|
```
# tail-classifier :: Row -> String
# consumes an animal, and predicts the species
fun tail-classifier(r):
  if r["tail"] == true:
    "cat"
  else:
    "snail"
  end
end
```
|===

We also know that classifiers are just functions, and we can convert any decision tree into a Pyret function.

@slidebreak{Launch-DN}
@indented{@show{(contract "classify" '("Table" "String" "(Row -> String)") "Table")}}

And of course, there's the `classify` function, which consumes a Table of rows to be classified, the name of the column being predicted, and a *classifier function* that maps Rows to Strings.

@indented{`classify(simple-animals, "species", tail-classifier)`}

@lesson-instruction{
- Try this out using your 1-level classifier
- Then try it using your 2-level classifier
}


@slidebreak{Investigate}
How do we know if a @vocab{decision tree} makes a good @vocab{classifier} or not? Using the `classify` function only tells us how many we got right, and how many we got wrong.

It's not enough to know that a classifier messed up 6 times! Data Scientists and Machine Language Engineers want a full, detailed "classifier report card" showing _which mistake_ it made! This report card a @vocab{Confusion Matrix}.

@QandA{
@Q{Out of the 5 cats in this dataset, how many did your best classifier classify _correctly_?}
@Q{Roughly what *percentage* of the cats is that?}
@Q{Out of the 2 snails in this dataset, how many did your best classifier classify _correctly_?}
@Q{Roughly what *percentage* of the snails is that?}
}

@slidebreak{Investigate}
A @vocab{confusion matrix} typically shows _percentages:_ 4-out-of-5 cats becomes 80%, 2-out-of-2 lizards becomes 100%, and so on.

We've created a function that does just that! Here's the contract:

@show{(contract "confusion-matrix" '("Table" "String" "(Row -> String)") "Table")}

Try it out with the original `tail-classifier`:

@indented{`confusion-matrix(simple-animals, "species", tail-classifier)`}

@slidebreak{Investigate}

[.data-table.highlight-diagonal, cols="6a,^7a,^7a,^7a,^7a,^7a", options="header"]
|===
|actual-species|predicted-cat|predicted-dog|predicted-lizard|predicted-snail|predicted-tarantula
|"cat"         |      1      |      0      |       0        |       0       |       0
|"dog"         |      1      |      0      |       0        |       0       |       0
|"lizard"      |      1      |      0      |       0        |       0       |       0
|"snail"       |      0      |      0      |       0        |       1       |       0
|"tarantula"   |      0      |      0      |       0        |       1       |       0
|===

The "correct scores" are shown in the diagonal, running from top-left to bottom-right.

@QandA{
@Q{What are some things we can infer from this confusion matrix?}
@A{Our classifier got 100% of the cats and snails right}
@A{It mis-classified all of our dogs as cats}
@A{It mis-classified all of our lizards as cats}
@A{It mis-classified all of our tarantulas as snails}
@Q{What would the matrix for the *best possible classifier* look like?}
@A{1s along the diagonal, showing 100% of each category was classified correctly. 0s everywhere else, showing no mis-classifications.}
}

@lesson-instruction{
- Compare your confusion matrices with the people around you.
- How did your 2-level classifier do?
}

=== Synthesize
@slidebreak{Synthesize}
@QandA{
@Q{Will a decision tree always have the same number of leaf nodes as there were rows in the training dataset? Why or why not?}
@A{No. Generally multiple rows of a training dataset will have the same prediction. The training dataset we saw in this lesson section contained multiple knives, for example.}

@Q{Can a decision tree have the _fewer_ leaf nodes than there are unique categories in the training dataset? Why or why not?}
@A{Yes. A decision tree may not be deep enough to correctly classify every category - and in some cases, there may not *be* a way to correctly classify every category!}

@Q{Explain what the decision tree and table for the training dataset have to do with one another.}
@A{The column headers from the table are the questions that will get asked in the decision nodes of the decision tree.}
@A{The data in each column are the answers to those questions which become the arrow labels of the decision tree ("yes" and "no", for this dataset).}
@A{The output categories from the table are the leaf nodes in the decision tree.}
}

== Building Decision Trees in Pyret

=== Overview
Now that they know the algorithm, students explore Pyret's ability to build decision trees automatically! They explore the impact that different depths or columns have on the quality of a classifier.

=== Launch
@slidebreak{Launch}
By now, you know that not all @vocab{decision trees} are created equal! You also know the algorithm to compute an _optimal tree_, so you could generate a @vocab{decision tree} for any dataset.

[.data-table, cols="^2,^2,^3,^2,^2", stripes="none", options="header"]
|===
| name    | age        | shopping history     | interest in game  | buys game
| Jan     | "teens"    | "previous customer"  | false             | false
| Noah    | "thirties" | "previous customer"  | false             | true
| Sydney  | "thirties" | "previous customer"  | true              | true
| Mariana | "thirties" | "new customer"       | true              | false
| Rasula  | "twenties" | "new customer"       | true              | true
| Jillian | "teens"    | "previous customer"  | false             | false
| Ariella | "teens"    | "new customer"       | true              | true
| Isabela | "thirties" | "previous customer"  | true              | true
|===

Based on a dataset like this, could you write a classifier that predicts which customers are most likely to buy a game, and mail them a targeted advertisement?

@slidebreak{Launch}

You could write a simple spam filter, to get rid of unwanted email:

[.data-table, cols="^1,^1,^1", stripes="none", options="header"]
|===
| sender in address book  | seen sender before      | mass email
| true                    | true                    | true
| true                    | false                   | false
| false                   | true                    | true
| false                   | false                   | false
| true                    | true                    | true
| true                    | false                   | false
| false                   | false                   | true
|===

Based on a dataset like this, could you write a simple classifier that predicts whether an email is spam or not?

@slidebreak{Investigate}
Of course, computing a decision tree by hand takes a long time, especially if you're dealing with tens of thousands of rows and hundreds of columns! Fortunately, computers are really, _really_ good at following algorithms.

We've provided a function that will use a splitting algorithm similar to the one you know, to build the _optimal_ decision tree based on a set of training data! Here's the contract:

@show{(contract "build-tree" '("Table" "List" "String" "Number") "DecisionTree")}

The `build-tree` function takes *four arguments* in its Domain:

- The _training dataset_ on which to fit the tree
- A list of all the column names for the nodes to split on
- The name of the _target_ column containing all the "answers" for the various categories
- The _maximum depth_ the tree is allowed to be

@lesson-instruction{
- Complete @printable-exercise{computing-decision-trees.adoc}
- When you're finished, share your answer to the last question ("how deep will it go?") with your neighbors. Why do you think you got the answer your did?
}

@slidebreak{Investigate}

@QandA{
@Q{Was anyone surprised by Pyret's choice for the root?}
@Q{How did Pyret's choices for the rest of the tree compare to yours?}
@Q{Why do you think the optimal tree using all columns only needed 3 levels of depth?}
@A{Most of the variation in the dataset can be explained with splits on our Boolean columns. For a few animals (like `Shadestar`), we need to look at the `pounds` column. }
}

@slidebreak{Investigate}

@lesson-instruction{
- Complete @printable-exercise{testing-decision-trees.adoc}
}

=== Synthesize
@slidebreak{Synthesize}

TODO: harvest from the excellent (legacy) questions at the bottom


== Using our Trained Classifiers

=== Overview
Students are given a training dataset and a testing dataset, both drawn from the Spotify database. After train classifiers on the first data, they'll see how well they work on the second. Students will explore the problem of _over-fitting_, and return to dot-plots to explore natural variation between distributions in the training dataset v. the testing one.

=== Launch
@slidebreak{Launch}

How can you tell the difference between an R-and-B, Rock-and-Roll, or Country song?

@teacher{Let kids offer up a lot of suggestions!}

Can we teach a _computer_ how to tell the difference?


=== Launch
@slidebreak{Launch}

Let's build a classifier that can tell the difference between these three genres.

@lesson-instruction{
- Open @starter-file{decision-tree-music}, and click "Run".
- Complete @printable-exercise{music-classifier.adoc}.
}

=== Investigate
@slidebreak{Investigate}


=== Synthesize
@slidebreak{Synthesize}



@scrub{

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{What are some reasons that a decision tree might produce an inaccurate prediction or recommendation?}
@A{The prediction might represent closer to 50% of the training population rather than 100% of the population.}
@A{The training dataset might not completely represent the broader population, either in not having enough variables (columns) or enough samples (rows).}
@A{The training dataset could be inconsistent, in that the labeled outcomes for two rows are different while the rest of the columns have the same values.}

@Q{After testing our tree, we discovered that it was not as accurate as we had expected or hoped. Can you think of concrete, real-world examples of how a training dataset might under represent a population?}
@A{Responses will vary.}
@A{Medical systems being trained on only adults, but not children.}
@A{Tutoring systems trained on only native speakers of a language.}
@A{Music recommendation systems being trained on a narrow set of genres.}

@Q{We collapsed specific ages into categories (teenager, etc) to align the specificity of our data with the specificity of recommendations that we wanted from the decision tree. What if we had not done that, and instead created a branch for each individual age? How would individual branches have affected the decision tree and its recommendations?}
@A{The tree would have had many more branches and decision nodes.}
@A{We would likely have needed more training data with more samples at each age to get to acceptable accuracy.}

@Q{You have learned that @vocab{supervised learning} includes three steps: (1) demonstration of the learning process, (2) function abstraction, and (3) using the function. Describe what each step includes for the @vocab{supervised learning} of a @vocab{decision tree}.}
@A{Demonstration: For decision trees, the demonstration is the labeling of the data so that the computer learns the desired outcome (or "correct answer") for each data point. During the lesson, we knew whether the individuals in our training set would buy the video game.}
@A{Function abstraction: Creating the decision tree yields a model of how variables affect outcomes.}
@A{Use: Follow the decision tree to find the predicted outcome for a new input (set of values for the question variables).}

}



Creating a decision tree is a form of @vocab{supervised learning}, because the training data already contains the desired outcomes (as one column), and the algorithm just learns a function that maps from input to outcomes.
}