[.beta]
= Evaluating Decision Trees
++++
<style>
/* allow lesson-points to co-exist with images */
.lesson-point{ clear: unset !important; }

/* force some images to have a white background */
.white-bg { background-color: white; display: block; }

.highlight-diagonal tr:nth-child(1) td:nth-child(2),
.highlight-diagonal tr:nth-child(2) td:nth-child(3),
.highlight-diagonal tr:nth-child(3) td:nth-child(4),
.highlight-diagonal tr:nth-child(4) td:nth-child(5),
.highlight-diagonal tr:nth-child(5) td:nth-child(6) {
  background: var(--bs-secondary-lighter-supernova) !important;
  color: white !important;
  font-weight: bold;
}
</style>
++++

@description{Students learn how computers can automatically generate decision trees and how computer scientists evaluate them.}

@lesson-prereqs{decision-trees-building}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|
- Let's learn about how to evaluate the _accuracy_ of a classifier
- Let's learn how the distribution in the training dataset influences the trees we build

| Materials
|[.materials-links]
@material-links
|===

== Building Decision Trees in Pyret

=== Overview
Now that they know the algorithm, students explore Pyret's ability to build decision trees automatically! They explore the impact that different depths or columns have on the quality of a classifier.

=== Launch
@slidebreak{Launch}
Let's review what we know about classifiers:

- There is a simple algorithm we can use to compute an _optimal tree_ for any dataset .
- @vocab{Decision trees} are really just functions called @vocab{classifiers}: they take an input and produce a prediction as their output.
- Not all @vocab{decision trees} are created equal! 

Of course, computing a decision tree by hand takes a long time, especially if you're dealing with tens of thousands of rows and hundreds of columns! 
Fortunately, computers are really, _really_ good at following algorithms.

@slidebreak{Launch}
One example of an early application for this kind of automation is used by the United States Postal Service to read handwritten addresses on envelopes.  Their address interpretation system was trained on the MNIST database (Modified National Institute of Standards and Technology database), which includes thousands of labelled images of handwritten digits.

=== Investigate
@slidebreak{Investigate}

Given a dataset to train on, Pyret can build _optimal_ decision trees for us, and even give us the classifier code for those trees, using the algorithm you already know!

@show{(contract "build-tree" '("Table" "List" "String" "Number") "DecisionTree")}

The `build-tree` function takes *four arguments* in its Domain:

- The _training dataset_ on which to fit the tree
- A list of all the column names for the nodes to split on
- The name of the _target_ column containing all the "answers" for the various categories
- The _maximum depth_ the tree is allowed to be

@slidebreak{Investigate}

@lesson-instruction{
- Complete the first section of @printable-exercise{computing-decision-trees.adoc} using the @starter-file{decision-tree}.
}

@slidebreak{Investigate}

@QandA{
@Q{When you evaluated `dt-code(tree-cat1)`, did you recognize the code that came back?}
@A{It's the same function as `tail-classifier`, which was already in our Definitions Area}

@Q{What did Pyret do with the quantitative column (`"pounds"`)?}
@A{It figured out that it made most sense to split at 9.55 pounds!}

@Q{What column did Pyret decide to use when it got to choose between all of the columns?}
@A{`"swims"`}
}

@slidebreak{Investigate}

@lesson-instruction{
Complete the second section of @printable-exercise{computing-decision-trees.adoc}
}

@slidebreak{Investigate}

@QandA{
@Q{How are the definitions for `tree-cat1` and `tree-cat2` different?}
@A{`tree-cat1` allows for a maximum of 1 level.}
@A{`tree-cat2` allows for a maximum of 2 levels.}

@Q{How are the trees for `tree-cat1` and `tree-cat2` different?}
@A{They are the same! Once we split on whether or not animals have tails, there's no further sorting we can do with just the `"tail"` column.}

@Q{How did `tree-quant1`, `tree-quant2` and `tree-quant3` compare?}
@A{They all started with the same splits.}
}

@lesson-instruction{
- Make sure you've saved all of the new definitions to your copy of the @starter-file{decision-tree}
- Turn to @printable-exercise{comparing-decision-trees.adoc} and complete the first section.
}

@slidebreak{Investigate}

Notice that `tree-quant6` works just as well as `tree-any4`, even though it only has one column to train on!

As is common for quantitative columns, there's more variability in `pounds` than there is for any of our categorical columns. In fact, the only way to _not_ have a perfect classifier based on `pounds` would be for animals from two different species to weigh the exact same amount!

@lesson-instruction{
- Complete @printable-exercise{computing-decision-trees.adoc}
}

@slidebreak{Investigate}

When given another dataset to classify, `tree-any4` is out-scoring `tree-quant6`!

@QandA{
@Q{Why did `tree-quant6` do so poorly?}
@A{Let students share their theories}
}

@slidebreak{Investigate}
[cols="^1a, ^1a", frame="none", options="header"]
|===
| Training Dataset
| Testing Dataset

| @image{images/dot-plot-pounds-training.png}
| @image{images/dot-plot-pounds-testing.png}
|===

This is a classic example of what ML engineers call @vocab{over-fitting}. The more a classifier depends on an attribute, the more sensitive it is to variations in that attribute between populations. In this case, `tree-quant6` was _totally dependent_ on `pounds`, whose distribution is very different in the `testing` dataset.

@slidebreak{Investigate}
@ifslide{
[cols="^1a, ^1a", frame="none", options="header"]
|===
| Training Dataset
| Testing Dataset

| @image{images/dot-plot-pounds-training.png}
| @image{images/dot-plot-pounds-testing.png}
|===
}
This would be like studying for a test by memorizing the answers to a previous test. You've learned how to ace _that specific test_, but not enough to actually do well on a different one.

@slidebreak{Investigate}
In Machine Learning, over-fitting happens when our decision tree tries so hard to find a pattern in a specific set of data that it begins to "memorize" the details and random noise instead of learning the actual rule. That's exactly what happened with the `pounds` column here.

The other columns didn't vary as much at all! Dogs and cats are all `mammals` no matter what. Most dogs like to `swim`. And most dogs, cats, and lizards all have a `tail`. These attributes are more stable across samples, whereas `pounds` can vary widely.

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{Explain how the table for the training dataset is related to the decision tree.}
@A{The column headers from the table are the questions that will get asked in the decision nodes of the decision tree.}
@A{The data in each column are the answers to those questions which become the arrow labels of the decision tree ("yes" and "no", for this dataset).}
@A{The output categories from the table are the leaf nodes in the decision tree.}

@Q{Will a decision tree typically have the same number of leaf nodes as there were rows in the training dataset? Why or why not?}
@A{No. The splitting algorithm works _by attribute_, and, generally multiple rows of a training dataset will share attributes: multiple dogs will swim, multiple animals are mammals, etc. So, unless each row has a unique combination of attributes _and_ the tree can go infinitely deeply the decision tree will have fewer leaves than there are rows in the training dataset.}

@Q{Can a decision tree have _fewer_ leaf nodes than there are unique categories in the training dataset? Why or why not?}
@A{Yes. A decision tree may not be deep enough to correctly classify every category - and in some cases, there may not *be* a way to correctly classify every category!}
}

== Evaluating a Classifier
@objective{}

=== Overview
Students learn about confusion matrices, and use Pyret to generate them from classifier functions derived from decision trees.

=== Launch
@slidebreak{Launch}
How do we know if a @vocab{decision tree} makes a good @vocab{classifier} or not? Using the `classify` function only tells us how many we got right, and how many we got wrong.

It's not enough to know that a classifier messed up 6 times! Data Scientists and Machine Language Engineers want to know what percentage of the time the classifier did what it was supposed to and _which mistakes_ it made!

@QandA{
@Q{Out of the 5 cats in this dataset, how many did our `tail-classifier` classify _correctly_?}
@A{5}

@Q{Roughly what *percentage* of the cats is that?}
@A{100%}

@Q{Out of the 2 tarantulas in this dataset, how many did our `tail-classifier` classify _correctly_?}
@A{0}

@Q{Roughly what *percentage* of the snails is that?}
@A{0%}
}

@slidebreak{Launch}

The reports Data Scientists use to understand how "good" a classifier is are called @vocab{confusion matrices}. A @vocab{confusion matrix} typically shows _ratios:_ 

- 0-out-of-4 dogs becomes 0% (0 in decimal form)
- 2-out-of-2 lizards becomes 100% or (1)
- 4-out-of-5 cats becomes 80% (0.8)

...and so on.

@lesson-instruction{
- Turn to the first section of @printable-exercise{confusion-matrix.adoc}.
- With your partner, follow the directions to create a confusion matrix for the `swims-classifier`.
}

@slidebreak{Launch}

@center{@image{images/swims-confusion.png,600}}

@QandA{
@Q{Which species did `swims-classifier` predict _most_ accurately?}
@A{dogs}

@Q{Which species did `swims-classifier` predict _least_ accurately?}
@A{snails, lizards and tarantulas}

@Q{What else can we learn from the confusion matrix?}
@A{All of the snails and tarantulas are getting misclassified as cats.}
@A{Half of the lizards are getting misclassified as cats and the other half are getting misclassified as dogs.}
@A{20% of the cats are getting misclassified as dogs.}
}

=== Investigate
@slidebreak{Investigate}

Pyret has a function that will make a @vocab{confusion matrix} for you! Here's the contract:

@show{(contract "confusion-matrix" '("Table" "String" "(Row -> String)") "Table")}

@slidebreak{Investigate}

@lesson-instruction{
- Make sure you added the `swims-classifier` to your Definitions Area and clicked "Run".

```
fun swims-classifier(r):
  if r["swims"] == true:
    "dog"
  else: 
    "cat"
  end
end
```
}

@slidebreak{Investigate}

@lesson-instruction{
- Test out the confusion matrix for our `swims-classifier` using the following code:

@indented{`confusion-matrix(training, "species", swims-classifier)`}
- Compare the confusion matrix you made to the one that Pyret made. If they don't match, work with your partner to figure out why.
- Complete @printable-exercise{confusion-matrix.adoc}.
}

@slidebreak{Investigate}

@QandA{
@Q{How did the `swims-classifier` performance with the `testing` table compare to its performance with the `training` table?}
@A{It did impressively well, but misclassified all of the rabbits as dogs.}
@A{We wouldn't expect it to correctly classify the species of an animal that it wasn't trained on.}
}

@lesson-instruction{
- Make a confusion matrix for our original `tail-classifier` and be prepared to share what you learn from it.
}

@slidebreak{Investigate}

@indented{
[.data-table.highlight-diagonal, cols="6a,^7a,^7a,^7a,^7a,^7a", options="header", ]
|===
|actual-species|predicted-cat|predicted-dog|predicted-lizard|predicted-snail|predicted-tarantula
|"cat"         |      1      |      0      |       0        |       0       |       0
|"dog"         |      1      |      0      |       0        |       0       |       0
|"lizard"      |      1      |      0      |       0        |       0       |       0
|"snail"       |      0      |      0      |       0        |       1       |       0
|"tarantula"   |      0      |      0      |       0        |       1       |       0
|===
}

The "correct scores" are shown in the diagonal, running from top-left to bottom-right. *Note that we use 0-1, instead of 0%-100%!* "80%" would show up as `0.8`.

@QandA{
@Q{What are some things we can infer from this confusion matrix?}
@A{Our classifier got 100% of the cats and snails right}
@A{It mis-classified all of our dogs as cats}
@A{It mis-classified all of our lizards as cats}
@A{It mis-classified all of our tarantulas as snails}

@Q{What would the matrix for the *best possible classifier* look like?}
@A{1s along the diagonal, showing: 
  * 100% of the cats were predicted to be cats
  * 100% of the dogs were predicted to be dogs
  * 100% of the lizards were predicted to be lizards
  * and so on, showing 100% of each category was classified correctly.} 
@A{0s everywhere else, showing no mis-classifications.}
}

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{Why doesn't a decision tree that is 100% accurate for the training data always make good predictions for testing data?}
@A{If a classifier is overfitted to the training data, it might not make good predictions about related but different data.}
@A{Models based on quantitative columns are particularly susceptible to overfitting.}

@Q{In your own words, describe what a confusion matrix is.}  
}

@scrub{
== Optional: Classifying Songs

=== Overview
Students are given a training dataset and a testing dataset, both drawn from the Spotify database. After training classifiers on the training data, they'll see how well they work on the testing data. Students will explore the problem of _over-fitting_, and return to dot-plots to explore natural variation between distributions in the two datasets.

=== Launch
@slidebreak{Launch}

@QandA{
@Q{How can you tell the difference between R&B songs, Rock'n'Roll songs and Country songs?}
}

@teacher{Let kids offer up a lot of suggestions!}

@slidebreak{Launch}

Can we teach a _computer_ how to tell the difference?

@teacher{Maybe. If the differences are quantifiable or describable by . Let kids offer up a lot of suggestions!}

=== Investigate
@slidebreak{Launch}

Let's build a classifier that can tell the difference between these three genres.

@lesson-instruction{
- Open @starter-file{ai-music}, and click "Run".
- Complete the first section of @printable-exercise{music-classifier.adoc}.
- Be ready to share back and discuss your answers!
}

=== Investigate
@slidebreak{Investigate}

@QandA{
@Q{Share your observations about the `training` dataset}

@Q{Did anything in this dataset surprise you?}

@Q{Did you notice any groupings in the dot plots you made? What were they?}
@A{Responses will vary, but `popularity` should definitely stand out!}
}

@lesson-instruction{
- The `liveness` column is measuring how much a song sounds like a live recording v. a studio recording.
- Do you think this would be a good column to use for classification? Why or why not?
- Let's try writing a classifier using the `liveness` column...

- Complete the rest of @printable-exercise{music-classifier.adoc}.
}

@slidebreak{Investigate}

@QandA{
@Q{How well did your classifier do on the `training` dataset?}
@A{Fairly well!}

@Q{How well did your classifier do on the `testing` dataset?}
@A{Pretty poorly}

@Q{Why?}
@A{The distribution of `liveness` in Rock songs is very different between the training and testing dataset!}
@A{As with the `pounds` classifier in the animals dataset, we over-fit our music classifier to the `liveness` column.}

@Q{Will our classifier correctly identify k-pop and reggae songs? Why or why not?}
@A{Not at all - since none of those songs were in the original dataset, our decision tree doesn't even _have_ leaf nodes for those genres.}
}

@lesson-instruction{
TODO: another wbpage, this one challenging students to make the best classifier possible using whatever columns and depth they want. They should fill in the confusion matrix for the `testing` table in order to grade their results.

As a second challenge, they should try to make the best classifier possible using _as few columns as possible_. What does it mean, if it turns out that one column can be discarded with minimal loss of classification power?
}


=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{Why was `liveness` a bad column to use in our classifier?}
@A{Liveness has nothing to do with the music itself! Only how it was recorded.}

@Q{Suppose Spotify wanted to hire Data Scientists and Machine Learning Engineers to write a classifier like this. Does it matter whether they know anything about music?}
@A{Yes! Someone who understands music would have known right away that `liveness` is a bad column to use. They might also have understood *why* the data is shaped in certain ways, as in the case of the `popularity` column.}

@Q{What if a Machine Learning Engineer didn't know _anything_ about the domain they are trying to classify? Why might that be a problem?}
@A{If they're writing a facial recognition classifier without knowing anything about human facial structure, they might write a classifier that performs well on one group of people, but has a lot of false classifications for another.}
@A{This is where ethics and AI meet!}
}

@slidebreak{Synthesize}
@QandA{
@Q{What are some reasons that a decision tree might produce an inaccurate prediction or recommendation?}
@A{The prediction might be over-fit to the training population rather than the actual population.}
@A{The training dataset might not completely represent the broader population, either in not having enough variables (columns) or enough samples (rows), as with k-pop and reggae in the music dataset.}
@A{The training dataset could be inconsistent, in that the labeled outcomes for two rows are different while the rest of the columns have the same values, as with snails and tarantulas in the animals dataset.}

@Q{After testing our tree, we discovered that it was not as accurate as we had expected or hoped. Can you think of concrete, real-world examples of how a training dataset might _under_ represent a population?}
@A{Responses will vary, but here are a few examples:}
@A{Medical systems being trained on only adults, but not children.}
@A{Tutoring systems trained on only native speakers of a language.}
@A{Music recommendation systems being trained on a narrow set of genres.}
}

Creating a decision tree is a form of @vocab{supervised learning}, because the training data already contains the desired outcomes (as one column), and the algorithm just learns a function that maps from input to outcomes.
}