[.landscape]
= Contracts

Contracts tell us how to use a function. For example: `num-min {two-colons} (a {two-colons} Number, b {two-colons} Number) -> Number` tells us that the name of the function is  `num-min`, it takes two inputs (both Numbers), and it evaluates to a  `Number`. From the contract, we know  `num-min(4, 6)` will evaluate to a  `Number`. *Use the blank line under each contract for notes or sample code for that function!*

[.contracts-table, cols="4,1,10,1,2", options="header", grid="rows"]
|===

|Name||Domain||Range

| `num-sqr`
| `{two-colons}`
| `Number`
| `->`
| `Number`
5+|`_num-sqr(9)_`

| `num-sqrt`
| `{two-colons}`
| `Number`
| `->`
| `Number`
5+|`_num-sqrt(25)_`

| `triangle`
| `{two-colons}`
| `Number, String, String`
| `->`
| `Image`
5+|`_triangle(80, "solid", "darkgreen")_`

| `circle`
| `{two-colons}`
| @ifsoln{`Number, String, String`}
| `->`
| `Image`
5+| @ifsoln{`_circle(30, "outline", "fuchsia")_`}

| `star`
| `{two-colons}`
| @ifsoln{`Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_star(50, "solid", "teal")_`}

| `square`
| `{two-colons}`
| @ifsoln{`Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_square(10, "outline", "red")_`}

| `rectangle`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_rectangle(20, 80, "solid", "gold")_`}

| `text`
| `{two-colons}`
| @ifsoln{`String, Number, String`}
| `->`
| @ifsoln{ `Image`}
5+| @ifsoln{`_text("I'm thankful for...", 50, "green")_`}

| `ellipse`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_ellipse(30, 70, "outline", "lightblue")_`}

|===
