= Rocket Height Challenges

@n Can you make the rocket fly faster?

@fitb{}{@ifsoln{multiply `seconds` by a number larger than 7: @math{height(s) = 20 \times s}}}

@n Can you make the rocket fly slower?

@fitb{}{@ifsoln{multiply `seconds` by a number smaller than 7: @math{height(s) = 2 \times s}}}

@n Can you make the rocket sink down instead of fly up?

@fitb{}{@ifsoln{multiply `seconds` by a negative number: @math{height(s) = -7 \times s}}}

@n Can you make the rocket accelerate over time, so that it moves faster the longer it flies?

@fitb{}{@ifsoln{The formula for acceleration is _quadratic_: @math{height(s) = v \times 7s^2}. Use `seconds` as the exponenent with a number as the base.}}

@n Can you make the rocket blast off and then land again?

@fitb{}{@ifsoln{This is a parabola with a negative coefficient: @math{height(s) = -7s^2}. Adding a constant pushes the parabola up above @math{y = 0}}}

@n Can you make the rocket blast off, reach a maximum height of exactly 1000 meters, and then land?

@fitb{}{@ifsoln{See previous solution, with a constant of 1000: @math{height(s) = 1000 + -7s^2}}}

@n Can you make the rocket blast off, reach a maximum height of exactly 1000 meters, and then land after exactly 100 seconds?

@fitb{}{@ifsoln{multiply half the seconds by (50 minus half the seconds)}}

@n Can you make the rocket fly to the edge of the the universe?

@fitb{}{@ifsoln{Only an exponential function will counteract the effects of the background's log scale: @math{height(s) = 7^s}}}
