= Exploring the Countries Dataset
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
.columnInfo tr td { padding: 0 !important; }
table .paragraph:first-child .fitb:nth-child(3) {
	padding-top: 0px !important;
}
</style>
++++

[.linkInstructions]
For this section, you'll need the  @starter-file{alg2-countries} open on your computer. If you haven't already, select *Save a Copy* from the "File" menu to make a copy of the file that's just for you. The columns in this dataset are described below:

[.columnInfo, cols="5a,6a", grid=none, frame=none, stripes=none]
|===
|
- *country* - name of the country
- *gdp* - total gross domestic product of the country
- *population* - number of people in the country
|
- *pc-gdp* - "per-capita gdp": the average GDP _per-person_
- *has-univ-healthcare* - indicates if the country has universal healthcare
- *median-lifespan* - the median life expectancy of people in the country
|===

@vspace{1ex}

[.FillVerticalSpace, cols="45a,55a", frame=none, stripes=none]
!===
| @n Make a scatter plot showing the relationship between `pc-gdp` and `median-lifespan`, and sketch it plot below.
@center{@image{../images/scatter-grid.png, 225}}
|
--
@n What do you *Notice?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n What do you *Wonder?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@vspace{1ex}

@n Are there any countries that stand out? Why or why not? @fitb{}{} +
@fitb{}{}

@vspace{1ex}

@n Suppose a wealthy country is suffering heavy casualties in a war. Draw a star on the plot, showing where you might expect it to be.
--
!===

@n Do you think you see a relationship? If so, describe it. Is it linear or nonlinear? Strong or weak?

@fitb{}{@ifsoln{There seems to be a somewhat strong, nonlinear relationship}}

@fitb{}{} 

@center{*Stop here! We'll continue after some discussion.*}

== Fitting Models
_After you find each model below, update the corresponding definition in the @starter-file{alg2-countries} and click "Run" to load it. +
Hint: If you forgot the contract for `fit-model` (to calculate @math{S}), look it up in the @dist-link{Contracts.shtml, contracts pages}!_

@n Find the optimized *linear model* using `lr-plot`.

[cols="5a,1a", grid="none", frame="none", stripes="none"]
|===
|
@hspace{3em}@math{linear(x) =} @fitbruby{10em}{@ifsoln{@math{0.00021}}}{slope (m)}x + @fitbruby{10em}{@ifsoln{68.0125}}{y-intercept (b)}
|
@fitbruby{10em}{@ifsoln{5.93}}{S-value}
|===

@ifsoln{Answers below will vary - Solutions below are provided as a reference.}

@n Find the best *quadratic model* you can, using the second slide _(Wealth-v-Health Quadratic)_ in the Desmos activity.

[cols="5a,1a", grid="none", frame="none", stripes="none"]
|===
|
@hspace{3em}@math{quadratic(x) = }@fitbruby{10em}{}{quadratic coefficient (a)}@math{(x −}@fitbruby{10em}{}{vertex (h)}@math{)^2 +}@fitbruby{10em}{}{vertical shift (k)}
|
@fitbruby{10em}{}{S-value}
|===

@n Find the best *exponential model* you can, using the third slide _(Wealth-v-Health Exponential)_ in the Desmos activity.

[cols="5a,1a", grid="none", frame="none", stripes="none"]
|===
|
@hspace{3em}@math{exponential(x) = }@fitbruby{10em}{}{initial value (a)}@math{(}@fitbruby{10em}{}{growth factor (b)}@math{^x) + } @fitbruby{10em}{}{vertical shift (k)}
|
@fitbruby{10em}{}{S-value}
|===

@n Are any of these models a good fit for this data? Why or why not?

@fitb{}{}
