= Exploring the Countries Dataset
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
</style>
++++
For this page, you'll need the  @online-exercise{https://code.pyret.org/editor#share=1SGzPWywGy63-DaqOVTy39-497lcWaF4B, Countries of the World Starter File} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you.

@n Click "Run", and evaluate `countries-table` in the Interactions Area. Do you know what each column means?

[cols="1a,1a", grid="none", frame="none", stripes="none"]
|===
|
- *country* - name of the country
- *gdp* - total gross domestic product of the country
- *population* - number of people in the country
- *pc-gdp* - "per-capita gdp": the average GDP _per-person_
|
- *has-univ-healthcare* - indicates if the country has universal healthcare
- *median-lifespan* - the median life expectancy of people in the country
|===

@n Type `afghanistan` and `albania` into the Interactions Area. What do they evaluate to? @fitb{}{@ifsoln{Rows for those countries}}

[.FillVerticalSpace, cols="1a,1a" options="frame",stripes="none"]
!===
| @n Make a scatter plot showing the relationship between `pc-gdp` and `median-lifespan`. Sketch the shape of the plot below.
|
--
@n What do you *Notice?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n What do you *Wonder?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n Are there any countries that stand out? Why or why not? @fitb{}{} +
@fitb{}{}

@vspace{1ex}

@n Suppose a wealthy country is at war. Draw a star on the plot, showing where you might expect it to be.
--
!===

@n Do you see a correlation? Describe it, in terms of linear/nonlinear and strong/weak.

@fitb{}{@ifsoln{There seems to be a somewhat strong, nonlinear correlation}}

@fitb{}{}

@center{**Stop here! We'll continue after some discussion.**}

@n The contract for a function representing a linear model is on line 18. What is its name? @fitb{2em}{@ifsoln{f}} Domain? @fitb{5em}{@ifsoln{Number}} Range? @fitb{}{@ifsoln{Number}}

@n Fit the linear model `f` using the `fit-model` function. What is the @math{R^2} value? @fitb{}{@ifsoln{-11.7940}}.


@n Use `lr-plot` to find the _best-possible_ linear model, and write the model below. What is the @math{R^2}? @fitb{}{@ifsoln{0.413}}

@center{
 @math{f(x) =} @fitbruby{8em}{@ifsoln{@math{0.00021}}}{slope}x + @fitbruby{8em}{@ifsoln{68.0125}}{y-intercept} @hspace{5em} @show{(code '(define (f x) (+ (* (?ANS 0.00021) x) (?ANS 68.0125))))}
}

@n Change `f` to be the best _non-linear_ model you can build. What is the @math{R^2}? @fitb{5em}{} Write the model below.

@center{
 @math{f(x) =} @fitbruby{8em}{}{slope}x + @fitbruby{8em}{}{y-intercept} @hspace{5em} @show{(code '(define (f x) (+ (* (?ANS varies) x) (?ANS varies))))}
}

@n How close did you get? What kind of model do you think will best fit this data, and why?

@fitb{}{}

@fitb{}{}

