= Exploring the Countries Dataset
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
.columnInfo tr td { padding: 0 !important; }
table .paragraph:first-child .fitb:nth-child(3) {
	padding-top: 0px !important;
}
</style>
++++

[.linkInstructions]
For this section, you'll need the  @starter-file{alg2-countries} open on your computer. If you haven't already, select *Save a Copy* from the "File" menu to make a copy of the file that's just for you. The columns in this dataset are described below:

[.columnInfo, cols="5a,6a", grid=none, frame=none, stripes=none]
|===
|
- *country* - name of the country
- *gdp* - total gross domestic product of the country
- *population* - number of people in the country
|
- *pc-gdp* - "per-capita gdp": the average GDP _per-person_
- *has-univ-healthcare* - indicates if the country has universal healthcare
- *median-lifespan* - the median life expectancy of people in the country
|===

@vspace{1ex}

[.FillVerticalSpace, cols="45a,55a", frame=none, stripes=none]
!===
| @n Make a scatter plot showing the relationship between `pc-gdp` and `median-lifespan`, and sketch it plot below.
@center{@image{../images/scatter-grid.png, 225}}
|
--
@n What do you *Notice?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n What do you *Wonder?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@vspace{1ex}

@n Are there any countries that stand out? Why or why not? @fitb{}{} +
@fitb{}{}

@vspace{1ex}

@n Suppose a wealthy country is suffering heavy casualties in a war. Draw a star on the plot, showing where you might expect it to be.
--
!===

@n Do you think you see a relationship? If so, describe it. Is it linear or nonlinear? Strong or weak?

@fitb{}{@ifsoln{There seems to be a somewhat strong, nonlinear relationship}}

@fitb{}{} 