= Graphing Logarithmic Models:  __f(x) = a log~b~ x + c__
////
* Import Desmos Styles
*
* This includes some inline CSS which loads the Desmos font,
* which includes special glyphs used for icons on Desmos.com
*
* It also defines the classname '.desmosbutton', which is used
* to style all demos glphys
*
* Finally, it defines AsciiDoc variables for glyphs we use:
* {points}
* {caret}
* {magnifying}
* {wrench}
*
* Here's an example of using these:
* This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}
++++
<style>
.autonum { font-weight: bold; padding-top: 0.3rem !important; }
.autonum:after { content: ')' !important; }
.fitb { padding-top: 1rem; }
.FillVerticalSpace { grid-gap: 20px; margin-top: 5px; }

/* Use table cells as graph paper */
td {
  background-color: rgba(#fff, .5);
  background-image:
    linear-gradient(lightblue 2px, transparent 2px),
    linear-gradient(270deg, lightblue 2px, transparent 2px),
    linear-gradient(rgba(150, 150, 150, .3) 1px, transparent 1px),
    linear-gradient(270deg, rgba(150, 150, 150, .3) 1px, transparent 1px);
  background-size: 100px 200px, 200px 100px, 20px 20px, 20px 20px;
  background-position: 25px -75px;
  min-height: 1.5in;
  max-height: 1.5in;
  max-width: 2in;
}

td p.tableblock { position: absolute; }

/* Add labels for axes */
td::before, td::after { display: flex; font-style: italic; }
td::before {
  content: 'y';
  justify-content: center;
  align-items: center;
  margin-right: 10.5em;
  margin-top: 0;
    -webkit-transform:rotate(270deg);
    -moz-transform:rotate(270deg);
    -o-transform: rotate(270deg);
    -ms-transform:rotate(270deg);
    transform: rotate(270deg);
}
td::after {
  content: 'x';
  align-items: start;
  justify-content: right;
  margin-top: 4em;
  margin-right: -0.5em;
}
</style>
++++

@link-instructions{
Use this page with *Slide 4: Exploring Logarithmic Functions* of *Fitting Wealth-v-Health and Exploring Logarithmic Models (Desmos)*.

- The *blue curve* is the graph of @math{h(x) = 1 \log_{2} x + 0}. Its constants will remain set at @math{a=1}, @math{b=2}, and @math{c=0}.
- You can modify the *red curve* @math{g(x)} (which is hiding behind _h_!) by changing its coefficients: @math{a}, @math{b}, and @math{c}.
}

== Base @math{b}
@link-instructions{Keep *c* at @math{0} and *a* at @math{1}. Change the value of *b* as indicated on each grid below.}

@n Sketch each graph and *label the coordinates where @math{x = 1}, @math{y = 1}, @math{y = 2} and @math{y = 3}*.


[.FillVerticalSpace, cols="1,1,1", frame="none"]
|===
| @math{b = 3} | @math{b = 5}  | @math{b = 10}
|===

@n How does the value of @math{b} impact the shape of a logarithmic function? @fitb{}{@ifsoln{@math{b} determines how sharply the curve grows}}

@n What connections can you draw between the value of @math{b} and exponents? @fitb{}{@ifsoln{The output y is whatever}} +
@fitb{}{@ifsoln{exponent the base must be raised to in order to equal x}}

== Vertical Shift @math{c}
@link-instructions{Set *a* to @math{1} and *b* to @math{2}. Change the value of *c* as indicated on each grid below.}

@n Sketch each graph and *label the coordinate where @math{x = 1}*.

[.FillVerticalSpace, cols="1,1,1", frame="none"]
|===
| @math{c = -10} | @math{c = 0}  | @math{c = 10}
|===

@n How does the value of @math{c} impact the shape of a logarithmic function? @fitb{}{@ifsoln{@math{c} shifts the curve up (positive c) or down (negative c),}} +

@n Why does @math{y = c} when @math{x = 0}? @fitb{}{@ifsoln{Anything to the power of 0 is 1, so whatever the base is it must be raised to zero, and zero + c = c}}

== Logarithmic Coefficient @math{a}
@link-instructions{Set *c* to @math{0} and *b* to @math{10}, then zoom out out so you can see as far as @math{x = 1,000}. +

- Change @math{h(x)} to @math{h(x) = 1 \log_{10} (x) + 0} so that the blue curve lands on top of the red curve. +
- Now you're ready to change the value of *a* as indicated on each grid below.}

@n In each graph, *label the coordinates where @math{x = 10} and @math{x = 100} and @math{x = 1000}.*

[.FillVerticalSpace, cols="1,1,1", frame="none"]
|===
| @math{a = -2} | @math{a = 0}  | @math{a = 2}
|===

@n What is the value of @math{x} when @math{\log_{10}(x) = 6}? @fitb{6em}{@ifsoln{1,000,000}} @hspace{1em} What about when @math{2 \log_{10}(x) = 6}? @fitb{5em}{@ifsoln{1,000}} @hspace{1em} When @math{3 \log_{10}(x) = 6}? @fitb{5em}{@ifsoln{100}}

@star How are @math{a} and @math{b} related? @fitb{}{@ifsoln{@math{a \log_b(n) = log_b(n^a)}}
