= Graphing Logarithmic Models
////
* Import Desmos Styles
*
* This includes some inline CSS which loads the Desmos font,
* which includes special glyphs used for icons on Desmos.com
*
* It also defines the classname '.desmosbutton', which is used
* to style all demos glphys
*
* Finally, it defines AsciiDoc variables for glyphs we use:
* {points}
* {caret}
* {magnifying}
* {wrench}
*
* Here's an example of using these:
* This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}
++++
<style>
.autonum { font-weight: bold; padding-top: 0.3rem !important; }
.autonum:after { content: ')' !important; }

.FillVerticalSpace { grid-gap: 20px; margin-top: 5px; }

td {
  background-color: rgba(#fff, .5);
  background-image:
    linear-gradient(lightblue 2px, transparent 2px),
    linear-gradient(270deg, lightblue 2px, transparent 2px),
    linear-gradient(rgba(150, 150, 150, .3) 1px, transparent 1px),
    linear-gradient(270deg, rgba(150, 150, 150, .3) 1px, transparent 1px);
  background-size: 100px 100px, 100px 100px, 20px 20px, 20px 20px;
  background-position: -3px 74px;
  min-height: 1.6in;
  max-height: 1.6in;
  max-width: 2in;
}

td p.tableblock { position: absolute; }

/* Add labels for axes */
td::before, td::after { display: flex; font-style: italic; }
td::before {
  content: 'y';
  justify-content: center;
  align-items: center;
  margin-right: 1.5em;
  margin-top: -2em;
    -webkit-transform:rotate(270deg);
    -moz-transform:rotate(270deg);
    -o-transform: rotate(270deg);
    -ms-transform:rotate(270deg);
    transform: rotate(270deg);
}
td::after {
  content: 'x';
  align-items: start;
  justify-content: right;
  margin-top: 2em;
  margin-right: -0.5em;
}
</style>
++++

For this page, you'll need to have @starter-file{alg2-exploring-logarithms} open in Desmos. The curve you see is the graph of @math{h(x)=5 log_{10} x + 1}. Another, *identical* curve @math{g(x)} is hiding behind it. Each coefficient starts at values to make @math{g(x)} equivalent to @math{h(x)}.

== Vertical Shift @math{c}
@n Try changing the value of @math{c} to -10, 0, and 10, graphing each curve in the squares below. Be sure to identify the y-value where the curve "levels out".


[.FillVerticalSpace, cols="1,1,1", frame="none"]
|===
| @math{c=-10} | @math{c=0}  | @math{c=10}
|===

@n What does @math{c} tell us about a logarithmic function? @fitb{}{@ifsoln{How far the curve is shifted up (positive k) or down (negative k),}} +

== Base @math{b}
@n **Set @math{c} to zero and @math{a} to one.** Change the value of @math{b} to 2, 3, and 10, graphing each curve in the squares below. For each curve, label the points at y=1, 2, and 3.


[.FillVerticalSpace, cols="1,1,1", frame="none"]
|===
| @math{b=2} | @math{b=3}  | @math{b=10}
|===

@n What does @math{b} tell us about a logarithmic function? @fitb{}{@ifsoln{@math{a} determines how sharply the curve grows}} +
@fitb{}{}

@n What connections can you draw between the value of @math{b} and exponents? @fitb{}{@ifsoln{In order for y to reach}} +
@fitb{}{@ifsoln{some value c, b must be raised to the power of c}}


== Scaling Factor @math{a}
@n **Set @math{c} to zero and @math{b} to ten.** Change the value of @math{a} to -2, 0, and 2, graphing each curve in the squares below. For each curve, label the points at x=1, 2, and 3.


[.FillVerticalSpace, cols="1,1,1", frame="none"]
|===
| @math{a=-2} | @math{a=0}  | @math{a=2}
|===

@n What does @math{a} tell us about a logarithmic function? @fitb{}{@ifsoln{@math{a} determines how sharply the curve grows}} +
@fitb{}{}
