= Does Wealth impact lifespan equally if there's Universal Healthcare?
++++
<style>
table td:first-of-type p { font-weight: bold; }
</style>
++++

[.linkInstructions]
For this page, you'll need the @starter-file{alg2-countries} open on your computer. __If you haven't already__, select *Save a Copy* from the "File" menu to make a copy of the file that's just for you.

@n Read the function definition carefully: `fun no-universal(r): not(r["has-univ-healthcare"]) end`

@hspace{3em} What do you think this function does? @fitb{}{@ifsoln{it looks up the value of the `has-univ-healthcare`}}

@hspace{3em}@fitb{}{@ifsoln{column in whatever row it was passed and produces the opposite.}}


@n Add `fun no-universal(r): not(r["has-univ-healthcare"]) end` at the bottom of the Definitions Area. 

@hspace{2em} Click "Run" and evaluate @show{(code '(no-universal albania))} in the Interactions Area. What does Pyret return? @fitb{}{@ifsoln{`true`}}


@n Add `countries-wo-univ = filter(countries-transformed, no-universal)` to the bottom of the Definitions Area, then click "Run".


@hspace{3em}What does evaluating `countries-wo-univ` in the Interactions Area produce? @fitb{}{}

@hspace{3em} @fitb{}{@ifsoln{A table of all the countries without universal healthcare}}

@n Using the two definitions you just added as models:

[.indentedpara]
- *Define a new function* called `yes-universal`, which returns the value in the `has-univ-healthcare` column.
- *Define a new table* called `countries-w-univ`, which shows all the countries with universal healthcare.
- Click "Run" to load these new definitions once you have them both typed into the Definitions Area.

@n Fill in the table below by:

[.indentedpara]
- Building an `lr-plot` for each of these tables with the transformed-column `log(pc-gdp)`.
- Using what you learn from `lr-plot` to write logarithmic models for each table.
- Using `fit-model` to find @math{S} for each of your logarithmic models and their corresponding un-transformed `countries-w-univ` and `countries-wo-univ` tables.

@vspace{1ex}

[cols="^.^1a,^10a,^10a", options="header"]
|===
|
| With Universal Healthcare
| Without Universal Healthcare

| Linear Model
| @math{f(x) =} @fitbruby{8em}{@ifsoln{11.8617}}{slope}x + @fitbruby{8em}{@ifsoln{25.2718}}{y-intercept}
| @math{f(x) =} @fitbruby{8em}{@ifsoln{11.2079}}{slope}x + @fitbruby{8em}{@ifsoln{26.5875}}{y-intercept}

| Logarithmic Model
| @math{f(x) =} @fitbruby{8em}{@ifsoln{@math{11.8617}}}{log coefficient} @math{\log_{10}(x) +} @fitbruby{8em}{@ifsoln{25.2718}}{y-intercept}
| @math{f(x) =} @fitbruby{8em}{@ifsoln{@math{11.2079}}}{log coefficient} @math{\log_{10}(x) +} @fitbruby{8em}{@ifsoln{26.5875}}{y-intercept}

| @math{S}
| @fitb{10em}{@ifsoln{3.151}}
| @fitb{10em}{@ifsoln{4.943}}
|===

@n Was the relationship stronger for `countries-w-univ` or `countries-wo-univ`? @fitb{}{@ifsoln{Countries without universal healthcare}}

@n In `countries-w-univ`, what increase in `median-lifespan` did the model predict for each 10x increase in `pc-gdp`? @fitb{}{@ifsoln{11.8617}}

@n In `countries-wo-univ`, what increase in `median-lifespan` did the model predict for each 10x increase in `pc-gdp`? @fitb{}{@ifsoln{11.2079}}

@n For which table does an increase in `pc-gdp` have a bigger expected impact on `median-lifespan`? @fitb{}{@ifsoln{Countries with universal healthcare}}

@n Does the strength of the relationship determine how large of an impact `pc-gdp` has on `median-lifespan`? @fitb{}{@ifsoln{No! It determines how well the model predicts the data, not the increase in the variables in relationship to each other}}
