= Transforming the x-Axis
////
* Import Desmos Styles
*
* This includes some inline CSS which loads the Desmos font,
* which includes special glyphs used for icons on Desmos.com
*
* It also defines the classname '.desmosbutton', which is used
* to style all demos glphys
*
* Finally, it defines AsciiDoc variables for glyphs we use:
* {points}
* {caret}
* {magnifying}
* {wrench}
*
* Here's an example of using these:
* This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}

For this page, you'll need to load  @online-exercise{https://www.desmos.com/calculator/xectdnnqdy, Wealth-v-Health - Logarithmic} open on your computer.

== Fitting a Logarithmic Model

**Open the `Data Table` folder by clicking on the triangle ([.desmosbutton]#{caret}#)**

@vspace{1ex}

- @math{x_1} is the per-capita income for each country, and @math{y_1} is the median lifespan.
- Next to @math{y_1} you'll see a dark circle with spots ([.desmosbutton]#{points}#) inside. If the circle is dark, that means that those points are visible on our graph. Click the circle to "turn off" those dots, then click it again to turn them back on.
- Move the graph by clicking and dragging the background.
- Notice that a magnifying glass ([.desmosbutton]#{magnifying}#) appears to the bottom left of the table. Clicking on the magnifying glass resizes/rescales the graph to fit all the points in the table.

__Look at the numbers along the x-axis, which increase as they go from left to right.__

@n What would the next number be, if you were to add one at the far right: @fitb{5em}{} _Describe_ the pattern you used to find it: @fitb{}{@ifsoln{the numbers increase, *adding* a constant factor}}

@n What is the shape of the point cloud? @fitbruby{}{@ifsoln{It's a curve, but neither quadratic nor exponential!}}{Is it linear? Quadratic? Exponential? Something else?}

@n Move the sliders for @math{a} and @math{c} to create the best-fitting logarithmic model you can find, and write it below.

[cols="^1a", grid="none", frame="none", stripes="none"]
|===
|
@math{f(x) = }@fitbruby{10em}{}{scaling factor (a)}@math{\times log_10(x) + }@fitbruby{10em}{}{vertical shift (c)}
|===

@n In Pyret, modify `f(x)` to define this model, and fit it using the `fit-model` function. What is your @math{R^2}? @fitb{}{}

== Scaling the x-Axis

**Open the "Graph Settings" window in Desmos** by clicking on the wrench button ([.desmosbutton]#{wrench}#) in the top-right corner of the graph.

- **Expand the "More Options" section** by clicking the triangle ([.desmosbutton]#{caret}#).
- **Change the x-axis scale** from `Linear` to `Logarithmic`.
- **Zoom out** or **Zoom fit by click the magnifying glass beneath the table** [.desmosbutton]#{magnifying}# to put all of the points back into view.

__Look at the numbers along the x-axis, which increase as they go from left to right.__

@n What would the next number be, if you were to add one at the far right: @fitb{5em}{} _Describe_ the pattern you used to find it: @fitb{}{@ifsoln{the numbers increase, *multiplying* by a constant factor}}

@n What is the shape of the point cloud _now?_  @fitbruby{}{@ifsoln{It's linear!}}{Is it linear? Quadratic? Exponential? Something else?}

@n What has changed about the shape of the predictor function for the logarithmic model you graphed? @fitb{}{@ifsoln{It looks like a straight line!}}

@n Adjust the sliders for @math{a} and @math{c} to create the best-fitting model you can find, and write it below.

[cols="^1a", grid="none", frame="none", stripes="none"]
|===
|
@math{f(x) = }@fitbruby{10em}{@ifsoln{~12 to ~16}}{growth factor (b)}@math{\times log_10(x) + }@fitbruby{10em}{@ifsoln{~8 to ~25}}{vertical shift (c)}
|===

@n In Pyret, modify `f(x)` to define this model, and fit it using the `fit-model` function. What is your @math{R^2}? @fitb{}{}

@n Why did transforming the *x-axis* make our data look linear? @fitb{}{} +
@fitb{}{} +
@fitb{}{}
