= Transforming the Data
////
* Import Desmos Styles
*
* This includes some inline CSS which loads the Desmos font,
* which includes special glyphs used for icons on Desmos.com
*
* It also defines the classname '.desmosbutton', which is used
* to style all demos glphys
*
* Finally, it defines AsciiDoc variables for glyphs we use:
* {points}
* {caret}
* {magnifying}
* {wrench}
*
* Here's an example of using these:
* This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}

[.linkInstructions]
For this page, you'll need to have *Slide 6: Wealth-v-Health (Transformed)* of *Fitting Wealth-v-Health and Exploring Logarithmic Models (Desmos)* open on your computer.

== Transforming the Data

- *Find the `Wealth vs. Health` folder, which is open at the top of the expression list*
- This is the same table we've seen before, and the "points" circle ([.desmosbutton]#{points}#) shows us that these dots are "on" and visible.
- Underneath the `Wealth vs. Health` folder, you'll see a *function* @math{g(x)} and a *list* @math{y_2} defined to be the same as @math{y_1}.
- *Open the `Log(Wealth) vs. Health` folder by clicking on the triangle ([.desmosbutton]#{caret}#)*

@n Compare the two tables. What do you *Notice*? @fitb{}{@ifsoln{the 2nd columns are the same, but the 1st columns are really different}} +
@fitb{}{}

@n What do you *Wonder*? @fitb{}{} +
@fitb{}{}

@n Why is the second column of both tables the same? @fitb{}{@ifsoln{we defined @math{y_2} to be the same as @math{y_1}}}

@n How is the first column of this new table different from the original? @fitb{}{} +
@fitb{}{@ifsoln{We are using the function @math{g(x)} to take the log of `pc-gdp`}}

@vspace{1ex}

*Turn the points for the first table OFF, then turn the points for our new table ON.* Our log transformation is so drastic that it looks like all the black datapoints are smashed against the y-axis!

@n *Rescale* the graph ([.desmosbutton]#{magnifying}#) to see the cloud. What is the shape of this point cloud? Is it linear? Quadratic? Exponential? @fitb{}{@ifsoln{It's linear!}}

@n Move the sliders for @math{m} and @math{b} to create the best-fitting linear model you can find, and write it below.

[cols="^1a", grid="none", frame="none", stripes="none"]
|===
|
@math{f(x) = }@fitbruby{10em}{}{slope (m)}@math{x + }@fitbruby{10em}{}{y-intercept / vertical shift (b)}
|===

@n Why do you think transforming the *x-values* make our data look linear? @fitb{}{@ifsoln{The amount of extra income needed}} +
@fitb{}{@ifsoln{to create an extra year of predicted lifespan increased exponentially. By taking the log of that income,}} +
@fitb{}{@ifsoln{we are "cancelling out" that exponential growth and making it linear.}}

== Transforming Axes vs. Transforming Data

@n From your linear model above, copy your values for slope (@math{m}) and vertical shift (@math{c}):

[cols="^1a,^1a", grid="none", frame="none", stripes="none"]
|===
| @fitbruby{15em}{@ifsoln{~12 to ~16}}{slope (m)}
| @fitbruby{15em}{@ifsoln{~8 to ~25}}{vertical shift (c)}
|===

@n Look back at the values you wrote for log coefficient (@math{a}) and vertical shift (@math{c}) on question 8 of @printable-exercise{exploring-logarithmic-models/pages/changing-scale.adoc} and copy them here:

[cols="^1a,^1a", grid="none", frame="none", stripes="none"]
|===
| @fitbruby{15em}{@ifsoln{~12 to ~16}}{log coefficient (a)}
| @fitbruby{15em}{@ifsoln{~8 to ~25}}{vertical shift (c)}
|===

@n Are they similar? @fitb{5em}{} Why or why not? @fitb{}{@ifsoln{They are similar because we changed the _kind_ of growth from logarithmic to linear, but not the _amount_. }} +
@fitb{}{@ifsoln{Instead increasing logarithmically by @math{B}, our new function increases _linearly_ by @math{B}}} +
@fitb{}{}
