= Decomposing Flags

++++
<style>
#content img { border: solid 1px black; }
#content .centered-image { margin-bottom: 10px; }
#content td * { padding: 0; margin: 0; text-align: center; vertical-align: middle; }
#content tr { height: 2.3rem; font-size: 0.9rem; }
</style>
++++

Each of the flags below is shown with their width and height. Identify the shapes that make up each flag. Use the flag’s dimensions to estimate the dimensions of the different shapes. Then estimate the x and y coordinates for the point at which the center of each shape should be located on the flag. _Hint: The bottom left corner of each flag is at (0,0) and the top right corner is given by the flags dimensions._



[.flags, cols="^1a,^1a", stripes="none", frame="none"]
|===

| *Cameroon* (450 x 300)
@centered-image{../images/Cameroon.png, "Cameroon flag: 3 vertical stripes, green on L, red in center, yellow on right. solid 5-pointed yellow star in the center of the flag."}
[cols="2a,2a,1a,1a,1a,1a",options="header"]
!===
! shape:			! color: 	! width: 	! height: 	! x		! y
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!

!===

| *Chile* (420 x 280)
@centered-image{../images/Chile.png, "Chile flag: Bottom half is red. Top half has a blue square on the left with a solid 5-pointed white star. The rest of the top half is white."}
[cols="2a,2a,1a,1a,1a,1a",options="header"]
!===
! shape:			! color: 	! width: 	! height: 	! x		! y
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!

!===

| *Panama* (300 x 200)
@centered-image{../images/Panama.png, "Panama flag: Split into 4 quadrants. Top left is white with a solid 5-pointed blue star. Top right is red. Bottom left is blue. Bottom right is white with a solid 5-pointed red star."}
[cols="2a,2a,1a,1a,1a,1a",options="header"]
!===
! shape:			! color: 	! width: 	! height: 	! x		! y
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!===

| *Norway* (330 x 240)
@centered-image{../images/Norway.png, "Norway flag: Red with a blue cross splitting it into 4 unequal parts, the short end being on the left. The blue cross has a white border nearly equal in width to the cross itself on all sides that do not touch the edge of the flag."}
[cols="2a,2a,1a,1a,1a,1a",options="header"]
!===
! shape:			! color: 	! width: 	! height: 	! x		! y
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!  					!  			!  			! 			!  		!
!===

|===
