= Threats to Validity in a Nutshell

@vspace{1ex}

*Threats to Validity* can undermine a conclusion, even if the analysis was done correctly. 

@vspace{1ex}

== People Make Mistakes

Sometimes even well-meaning Data Scientists can make mistakes if they're not careful. Data Scientists need to be careful to avoid the four threats below.

@vspace{1ex}

- *Selection bias* - identifying the favorite food of the rabbits won’t tell us anything reliable about what all the animals eat.

- *Study bias* - If someone is supposed to assess how much cat food is eaten each day on average, but they only measure how much cat food is put in the bowls (instead of how much is actually consumed), they’ll end up with an over-estimate.

- *Poor choice of summary* - Suppose a different shelter that had 10 animals recorded adoption times (in weeks) as 1, 1, 1, 7, 7, 8, 8, 9, 9, 10. Using the mode (1) to report what’s typical would make it seem like the animals were adopted more quickly than they really were, since 7 out of 10 animals took at least 7 weeks to be adopted.

- *Confounding variables* - Some shelter workers might prefer cats, and steer people towards cats as a result. This would make it appear that “cats are more popular with people”, when the real variable  dominating the sample is what _workers at the shelter_ prefer.


== Fake News

But sometimes, it's not an accident: *some people deliberately misuse statistics to create "Fake News" and manipulate others!* An evil Data Scientist might make the four mistakes above _on purpose!_ Here are some other slimy ways to make an analysis invalid:

- *Using the Wrong Measure of Center* - With heavily-skewed data (like income in America), using the mean is deeply misleading.

- *Using a Correlation to Imply Causation* - Just because two variables are correlated doesn't mean one is _causing_ the other!

- *Incorrect Interpretation of a Visualization* - Someone might point to the tallest bar in a bar chart or histogram and say "See? Most of the people surveyed said...", even if the tallest bar represents only a small percentage of the people surveyed!

- *Intentionally Using the Wrong Chart* - Surveying pet-owners at a dog park to ask about their favorite animal is obviously misleading. A Bar Chart will show empty space for the "Cat" category, which would be a huge red-flag that the survey used a biased sample. But using a Pie Chart will hide the problem, because there's no such thing as an "empty pie slice"!

- *Changing the Scale of a Chart* - A change in poverty from 10.1% to 10.3% is really small, but if the y-axis of the graph goes from 10 to 10.5 it will look like a HUGE climb! The same trick can be played with bar charts, histograms, or box-plots, to exaggerate small differences or hide large ones.

== Outliers: Do they stay or do they go?

In any population, there are often one or two samples that are way outside the range of the group. These outliers can really change the results of your analysis, by altering up the average or skewing the shape of the data.

- It can be tempting to remove outliers, and _sometimes_ there's a good reason to do it! You might spot an obvious typo, or an answer that you can tell was written by accident.

- But _some_ outliers are completely valid, and very important! A small town that has a 30x higher rate of cancer than everywhere else might point to something really important!


As Data Scientists, outliers require us to investigate more closely. And whether we decide to keep or remove them, we should _always_ explain our reasoning.
