= Identifying Threats to Validity (2)
++++
<style>
div#body:not(.LessonPlan) p { min-height: 2rem; }
</style>
++++

@vspace{1ex}

_The animal shelter wanted to find out what kind of food to buy for their animals. They took a random sample of two animals and the food they eat, and they found that 100% of animals surveyed ate spider food!_

@vspace{1ex}

@n Explain why sampling just two animals can result in unreliable conclusions about what kind of food is needed.

@fitb{}{@ifsoln{Two animals is *not* large enough to be a representative sample!}}

@fitb{}{@ifsoln{It's too easy to randomly choose animals that give us unreliable conclusions.}}

@fitb{}{@ifsoln{The sample size is too small to be representative.}}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{9ex}

_A volunteer opens the shelter in the morning and walks all the dogs. At mid-day, another volunteer feeds all the dogs and walks them again. In the evening, a third volunteer walks the dogs a final time and closes the shelter. The volunteers report that the dogs are much friendlier and more active at mid-day, so the shelter staff assume the second volunteer must be better with animals than the others._

@vspace{1ex}

@n What are some possible threats to the validity of this conclusion?

@fitb{}{@ifsoln{There may be several confounding variables here. Perhaps the midday volunteer is the one who feeds the dogs at lunchtime!}}

@fitb{}{@ifsoln{Or perhaps dogs are in better moods in the middle of the day, when the sun is out...}}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}
