= Identifying Threats to Validity

@vspace{1em}

*Some volunteers from the animal shelter surveyed a group of pet owners at a local dog park. They found that almost all of the owners were there with their dogs. From this survey, they concluded that dogs are the most popular pet in the state.*

@vspace{1em}

@n What are some possible threats to the validity of this conclusion?

@blanklines{12}{
@ifsoln{Sample bias: most people at a dog park are going to be dog owners! And a single park may also be biased towards people who live near that park -- we can't make generalizations about a whole state!}
}

[.FillVerticalSpace, cols="1", frame="none"]
|===
|
|===

*The animal shelter noticed a large increase in pet adoptions between Christmas and Valentine’s Day. They conclude that at the current rate, there will be a huge demand for pets this spring.*

@vspace{1em}

@n What are some possible threats to the validity of this conclusion?

@blanklines{12}{
@ifsoln{Confounding variable: lots of people give puppies and kittens as gifts for the these holidays.}
}
