= Building More Linear Models
++++
<style>
/* shorten fill in the blanks */
.studentAnswerMedium { min-width: 10em !important; }
.studentAnswerLong { min-width: 22em !important; }

td { padding: 0 !important; }
</style>
++++

[.linkInstructions]
Open your copy of @starter-file{alg2-states-fit-model}. If you haven't already, *Save a Copy* now.

@n Which two columns will you explore? @fitbruby{20em}{}{x-axis} and @fitbruby{20em}{}{y-axis}.

@n Fill in the code to make a scatter plot exploring the relationship between those columns:

@show{(code '(scatter-plot states-table "state" (?ANS ______________________) (?ANS ______________________)))}

@n Pick two states to use for your first model: @fitb{10em}{} and @fitb{10em}{}.

@n Based on these two points, define your model in Function and Pyret Notation:

[cols="^1a, ^1a", options="header"]
|===
| Function Notation
| Pyret Notation
| @math{f(x) =} @fitb{12em}{}x + @fitb{12em}{}
| @show{(code '(define (f x) (+ (* (?ANS ______) x) (?ANS ______))))}
|===

@n Type this model into Pyret, and fit it to your data use `fit-model`. What @math{S} value did you get? @fitb{}{}

@n What's the best model you can build? In the table below, record your models and the @math{S} values you got for them, then draw a star next to the one with the best @math{S}-value.

[.FillVerticalSpace, cols="^1a, ^1a", options="header"]
|===
| Model (Function or Pyret Notation - whatever you prefer!)   | @math{S}
|                                                             |
|===


@star *What does this model actually mean? Try completing the sentences below:*

_This model predicts that a 1 @fitbruby{10em}{percent}{x-axis units} increase in @fitbruby{20em}{}{x-axis} is associated with a @fitbruby{20em}{@ifsoln{}}{slope, y-units} @fitbruby{10em}{increase}{increase / decrease} in @fitbruby{20em}{@ifsoln{}}{y-axis}. Based on the @math{S} of @fitbruby{10em}{}{S} and @fitbruby{15em}{}{y-axis} ranging from @fitbruby{6em}{}{lowest y-value} to @fitbruby{6em}{}{highest y-value}, I would say this model fits @fitbruby{30em}{}{real well / not great / poorly / terribly}._

 
