= Optimizing and Interpreting Linear Models
++++
<style>
/* shorten fill in the blanks */
.studentAnswerMedium { min-width: 8em !important; }
td { padding: 1 !important; }
.example { font-style: italic; }
.example .fitbruby {
	padding-top: 0.75rem !important;
	border-color: lightgray !important;
fitbruby {
  padding-top: 9rem !important;
}
/* Push content to the top (instead of the default vertical distribution), which was leaving empty space at the top. */
#content { display: block !important; }
</style>
++++

@link-instructions{
Open your copy of the @starter-file{alg2-states}.
}

== Build a Model Computationally

@n Evaluate @show{(code '(lr-plot states-table "state" "pct-college-or-higher" "median-income"))}. What is @math{S}? @fitb{}{@ifsoln{}}

@n On the line below, write the optimal linear model that was computed through linear regression:

@center{
 @math{optimal(x) =} @fitbruby{8em}{@ifsoln{@math{1142}}}{slope (m)}x + @fitbruby{11em}{@ifsoln{20868.14}}{y-intercept / vertical shift} @hspace{5em} @show{(code '(define (optimal x) (+ (* (?ANS 1142) x) (?ANS 20868.14))))}
}

== Interpret the `al-ak` Model

We started with a model based on Alabama and Alaska @show{(code '(define (al-ak x) (+ (* 5613.67 x) -83616.02)))} @hspace{1em} `S: ~36164.68` +
which we can interpret as follows:

@ifnotsoln{@vspace{1ex}}

[.example]
--
The @fitbruby{15em}{Alabama-Alaska}{sensible name} model predicts that a 1
@fitbruby{10em}{percent}{x-axis units} increase in
@fitbruby{15em}{percent college degrees}{explanatory variable (x)} is associated with a
@fitbruby{15em}{~5614 dollar}{rate of change in y-units}
@fitbruby{12em}{increase}{increase / decrease} in
@fitbruby{22em}{median household income}{response variable (y)}. +
With @fitbruby{20em}{median household income}{response variable (y)} ranging from
@fitbruby{12em}{$39,031}{lowest y-value} to
@fitbruby{12em}{$73,538}{highest y-value} and an @math{S}-value of +
@fitbruby{12em}{~36,164.68}{@math{S}-value}
@fitbruby{12em}{dollars}{y-axis units}, I
@fitbruby{18em}{strongly disagree}{strongly agree, agree, disagree, strongly disagree} that this model is a good fit.
--

@n What does the *slope (m)* of this linear model tell us? @fitb{}{}

@fitb{}{@ifsoln{The amount by which median income increases for each percentage of citizens who finished college}}

@n How would we use this model predict to predict the median income for a state where 30% of the population has attended college? @fitb{}{@ifsoln{@math{5614 \times 30 + 83616 = ~252306}}}

== Interpreting the Optimal Model

The @fitbruby{15em}{linear-regression}{sensible name} model predicts that a 1
@fitbruby{10em}{@ifsoln{percent}}{x-axis units} increase in
@fitbruby{15em}{@ifsoln{percent college degrees}}{explanatory variable (x)} is associated with a
@fitbruby{15em}{@ifsoln{1142 dollar}}{rate of change in y-units}
@fitbruby{12em}{@ifsoln{increase}}{increase / decrease} in
@fitbruby{22em}{@ifsoln{median household income}}{response variable (y)}. +
With @fitbruby{15em}{@ifsoln{median household income}}{response variable (y)} ranging from
@fitbruby{12em}{@ifsoln{$39,031}}{lowest y-value} to
@fitbruby{12em}{@ifsoln{$73,538}}{highest y-value} and an @math{S}-value of +
@fitbruby{12em}{@ifsoln{~5717}}{@math{S}-value}
@fitbruby{12em}{@ifsoln{dollars}}{y-axis units}, I
@fitbruby{18em}{@ifsoln{}}{strongly agree, agree, disagree, strongly disagree} that this model is a good fit.

@n What median income does this model predict when 30% of a state's population has attended college? @fitb{}{@ifsoln{@math{1142 \times 30 + 20868 = ~55128}}}

@n Why doesn't it make sense to use this model to predict median income for a state with no college attendees (0%)? @fitb{}{}

@fitb{}{@ifsoln{The model is only designed to make predictions that fall within the domain of the dataset (between 18 and 52 percent). This model predicts a median income of -83616 dollars for zero pct-college-or-higher!}}

@n If a state's college graduation increases from 10% to 11%, what change in median income does this model predict? @fitb{}{@ifsoln{$1142}}

- What if it goes from 50% to 51%? @fitb{20em}{@ifsoln{$1142}}
- What if it goes from 90% to 91%? @fitb{20em}{@ifsoln{$1142}}
- Does this model predict the same increase in income for _every_ additional 1% `college-or-higher`? Why or why not? @fitb{}{}

@fitb{}{@ifsoln{Yes. Linear models increase by equal amounts over all equal intervals}}

