= Better Modeling: College Degrees v. Income

++++
<style>
/* Shrink fill in the blanks */
.studentAnswerMedium { min-width: 7em !important; }
body.workbookpage .fitbruby { padding-top: 1.1rem; }

td { padding: 0 !important; }
.center { padding: 0; }

/* Push content to the top (instead of the default vertical distribution), which was leaving empty space at the top. */
#content { display: block !important; }
</style>
++++

[.linkInstructions]
Open your copy of the @starter-file{alg2-states-fit-model}.

@vspace{1ex}

== The `ma-nv` Model

Find `# Define some rows` in the Definitions Area. +
Add two new definitions for `MA` (row 21) and `NV` (row 28), using the definitions for `alaska` and `alabama` as a model.

@n Record the `college-or-higher` and `median-income` values for `MA` and `NV`, as @math{(x,y)} pairs below:

@center{
 (@fitbruby{10em}{@ifsoln{39.4}}{MA college-or-higher}, @fitbruby{10em}{@ifsoln{66866}}{MA median-income}) @hspace{10em} (@fitbruby{10em}{@ifsoln{22.4}}{NV college-or-higher}, @fitbruby{12em}{@ifsoln{52800}}{NV median-income})
}

@n Derive the `MA-NV model` (using the same steps you followed to derive the `AL-AK model` on @printable-exercise{model-college-v-income-2.adoc}) and write it below (in both Function and Pyret notation), then fit the model and record the @math{S}-value:

@vspace{13ex}


@math{ma-nv(x) =} @fitbruby{7em}{@ifsoln{827.41}}{slope (m)}x + @fitbruby{10em}{@ifsoln{34266.05}}{y-intercept / vertical shift} @hspace{1em} @show{(code '(define (ma-nv x) (+ (* (?ANS 827.41) x) (?ANS 34266.05))))} @hspace{1em} @math{S}: @fitb{5em}{@ifsoln{~7,504.54}}

@vspace{1ex}

== A Model of Your Own

@n Identify two other states that you think would make a better model: @fitb{13em}{} and @fitb{13em}{}.

@vspace{1ex}

- Add two new definitions for these states to your @starter-file{alg2-states-fit-model}.

@n Record the `college-or-higher` and `median-income` values for these states, as (x,y) pairs below:

@center{
 (@fitbruby{10em}{}{college-or-higher}, @fitbruby{10em}{}{median-income}) @hspace{10em} (@fitbruby{10em}{}{college-or-higher}, @fitbruby{12em}{}{median-income})
}

@n Derive your model and write it below (in both Function and Pyret notation), then fit the model and record the @math{S}-value:

@vspace{13ex}

@center{
 @math{other(x) =} @fitbruby{8em}{}{slope (m)}x + @fitbruby{10em}{}{y-intercept / vertical shift} @hspace{2em} @show{(code '(define (other x) (+ (* (?ANS "varies") x) (?ANS "varies"))))} @hspace{2em} @math{S}:@fitb{5em}{}
}

@n Adjust the slope and y-intercept of your model to get the *smallest @math{S} possible.* Write the best model you find (and corresponding @math{S}) below:

@center{
 @math{best(x) =} @fitbruby{7em}{}{slope (m)}x + @fitbruby{11em}{}{y-intercept / vertical shift} @hspace{2em} @show{(code '(define (best x) (+ (* (?ANS "will vary") x) (?ANS "will vary"))))} @hspace{2em} @math{S}: @fitb{5em}{}
}


