= Fitting Models: College Degrees v. Income

[.linkInstructions]
Open the @starter-file{alg2-states-fit-model} and *Save a Copy* of the file that's just for you.

== The `al-ak` Model

Type @show{(code '(fit-model states-table "state" "pct-college-or-higher" "median-income" al-ak))} in the Interactions Area, then find the points for AL and AK along the predictor line. _Hint: You know their coordinates and they will help you know where to look!_

@n What do you Notice? @fitb{}{@ifsoln{Answers will vary. AL and AK are both on the line, but they don't seem to be very representative of the group.}}

@fitb{}{@ifsoln{The line goes all the way up to $200,000 but median income doesn't seem to exceed $80000.}}

@n What do you Wonder? @fitb{}{@ifsoln{Answers will vary. What states might have been more representative of the trend?}}

@fitb{}{}

@n Find @math{S} in the upper left corner. What is the @math{S} value (the number after @math{S})? @fitb{}{@ifsoln{~36164.683}}

@vspace{1ex}

@n Given that the range of this dataset goes from @fitbruby{10em}{@ifsoln{$39,031}}{lowest median income} to @fitbruby{10em}{@ifsoln{$73538}}{highest median income}, what does it mean that the @math{S-value} of the `al-ak` model is @fitb{10em}{@ifsoln{~36164.683}} ?

@fitb{}{@ifsoln{We know that there’s enough error in the model to predict median incomes that are off by $36,165!}

@fitb{}{@ifsoln{Considering the range of the data, the error in the model is enough to double the median income of a state or cut it in half!}}

== A Model of Your Own

@n Identify two other states that you think would make a better model: @fitb{13em}{} and @fitb{13em}{}.

@vspace{1ex}

- Add two new definitions for these states to your @starter-file{alg2-states-fit-model}.

@n Record the `college-or-higher` and `median-income` values for these states, as (x,y) pairs below:

@center{
 (@fitbruby{10em}{}{college-or-higher}, @fitbruby{10em}{}{median-income}) @hspace{10em} (@fitbruby{10em}{}{college-or-higher}, @fitbruby{12em}{}{median-income})
}

@n Derive your model and write it below (in both Function and Pyret notation), then fit the model and record the @math{S}-value:

[.FillVerticalSpace, cols="1a", frame="none"]
|===
|
|===

@math{other(x) =} @fitbruby{8em}{}{slope (m)}x + @fitbruby{10em}{}{y-intercept / vertical shift} @hspace{2em} @show{(code '(define (other x) (+ (* (?ANS "varies") x) (?ANS "varies"))))} @hspace{2em} @math{S}:@fitb{5em}{}


@n Adjust the slope and y-intercept of your model to get the *smallest @math{S} possible.* Write the best model you find (and corresponding @math{S}) below:

@center{
 @math{best(x) =} @fitbruby{7em}{}{slope (m)}x + @fitbruby{11em}{}{y-intercept / vertical shift} @hspace{2em} @show{(code '(define (best x) (+ (* (?ANS "will vary") x) (?ANS "will vary"))))} @hspace{2em} @math{S}: @fitb{5em}{}
}

== Comparing Models


