= Describe and Define Your Own Functions!

*Let's define a function* @fitb{10em}{} *to generate...*

@span{.blankline}{}

If I say @fitb{10em}{}, what would our actor need to say?

@span{.blankline}{}

Let's write a few more examples:

@fitb{8em}{}(@fitb{5em}{} *)* --> @fitb{8em}{} *(* @fitb{23em}{} *)*

@fitb{8em}{}(@fitb{5em}{} *)* --> @fitb{8em}{} *(* @fitb{23em}{} *)*

@fitb{8em}{}(@fitb{5em}{} *)* --> @fitb{8em}{} *(* @fitb{23em}{} *)*

What variable changes? @fitb{10em}{}

Let's define our function using the variable.

*fun* @fitb{8em}{} (@fitb{5em}{}) *:* @fitb{8em}{}(@fitb{22em}{}) *end*


*Let's define a function* @fitb{10em}{} *to generate...*

@span{.blankline}{}

If I say @fitb{10em}{}, what would our actor need to say?

@span{.blankline}{}

Let's write a few more examples:

@fitb{8em}{}(@fitb{5em}{} *)* --> @fitb{8em}{} *(* @fitb{23em}{} *)*

@fitb{8em}{}(@fitb{5em}{} *)* --> @fitb{8em}{} *(* @fitb{23em}{} *)*

@fitb{8em}{}(@fitb{5em}{} *)* --> @fitb{8em}{} *(* @fitb{23em}{} *)*

What variable changes? @fitb{10em}{}

Let's define our function using the variable.

*fun* @fitb{8em}{} (@fitb{5em}{}) *:* @fitb{8em}{}(@fitb{22em}{}) *end*


*Let's define a function* @fitb{10em}{} *to generate...*

@span{.blankline}{}

If I say @fitb{10em}{}, what would our actor need to say?

@span{.blankline}{}

Let's write a few more examples:

@fitb{8em}{}(@fitb{5em}{} *)* --> @fitb{8em}{} *(* @fitb{23em}{} *)*

@fitb{8em}{}(@fitb{5em}{} *)* --> @fitb{8em}{} *(* @fitb{23em}{} *)*

@fitb{8em}{}(@fitb{5em}{} *)* --> @fitb{8em}{} *(* @fitb{23em}{} *)*

What variable changes? @fitb{10em}{}

Let's define our function using the variable.

*fun* @fitb{8em}{} (@fitb{5em}{}) *:* @fitb{8em}{}(@fitb{22em}{}) *end*
