[.canBeLongerThanaPage]
= Stress or Chill?

== The Issue

People report being more and more stressed every day - and that the amount of work they are expected to complete in a day is increasing. This trend extends beyond adults, with children and teenagers also reporting increased stress levels.

== Phases of the Project

=== 1. Ask questions

We will investigate questions about ourselves:

- What factors affect my stress level?
- What is my typical stress level?

@vspace{1ex}

We will investigate questions about our class:

- What factors affect our class stress level?
- What is the typical stress level of our class?

@vspace{1ex}

We will do some comparing:

- How does my stress level compare to that of my class?

@vspace{1ex}

And finally, we will examine the relationship between stress level and personality type:

- Do people with different personality types have different stress levels?
- Can personalilty assessments really predict a person's personality?

=== 2. Consider Data

Given that we are analyzing two different types of data - stress data and personality data - there are *two* phases of data collection.

@vspace{1ex}

First, you will complete the @link{https://my-personality-test.com/true-colours, Personality Colors Assessment}. This should take 5-10 minutes. After answering a series of multiple choice questions, your "true color" will be revealed to you - blue, green, orange, or gold. Make a note of your result.

@vspace{1ex}

Next, we will develop a plan to collect data on stress in our lives:

- First, preview the "Stress or Chill? Daily Survey" @link{https://docs.google.com/forms/u/2/d/1OrUCCL8kdhpTf78vzDUO6iBhw0jDLRK9kpqHRTvj6YE/copy, "here"} - but please note: *you MUST use the designated class survey link that your teacher provides.* In this project, we want examine _classwide_ data; if you use the wrong survey link, your data will not be included in our class dataset.

- Each student will use a @link{https://g.co/kgs/zybdHm, "random number generator"} to generate 2 numbers between 7 (for 7:00 am) and 20 (for 8:00 pm). For the next 5 days, including a weekend, each student will record an entry on our class stress survey at those designated times.

- If you are unable to access the stress survey during a designated time, jot down any observations on paper or make a mental note. (See the survey, above, to understand what you'll be looking for.) As soon as you are able, submit the survey.

- When possible, take a photo of what you are doing at each time slot. Save any photographic evidence for possible inclusion in your final report.

=== 3. Analyze the Data

- After five days of data collection, your teacher will share with you a file of class data. (Some teachers may share Pyret files, while other teachers may share spreadsheets for students to upload to Pyret.)
- Explore the data! What displays can help us to answer our questions?
- Save interesting displays for inclusion in your final report.
- Don't forget to consider numerical methods of analysis (mean, median, etc).

=== 4. Interpret the Data

Write a two-page report to address these research questions listed above. In your report, be sure to:

- Provide the plot(s) and numerical summary (or summaries).
- Describe what the plot shows.
- Explain why you chose to make that particular plot.
- Explain how the plot and numerical summary answer your questions.
- Explain conclusions you made from your analysis.

@vspace{1ex}

(Based on the What Stresses Us? project from @link{https://www.introdatascience.org/, IDS at UCLA})
