= Project: Make an Infographic

@description{Infographics are a powerful tool for communicating information, especially when made by people who understand how to connect visuals to data in meaningful ways. This project is an opportunity for students to become more flexible math thinkers while tapping into their creativity. _This project supports the learning goals of @ifproglang{pyret}{@lesson-link{bar-and-pie-charts}}@ifproglang{codap}{@lesson-link{codap-dot-plots-bar-charts}}._}

@ifproglang{pyret}{
@lesson-prereqs{bar-and-pie-charts}}

@ifproglang{codap}{
@lesson-prereqs{codap-dot-plots-bar-charts}}


[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

- think critically and creatively about ratio relationships
- represent ratio relationships using either repeated images, scaled images, or area models

| Student-facing Lesson Goals
|

- Let's make an infographic on a topic of interest!

| Materials
|[.materials-links]
@material-links

| Preparation
|
@preparation{
- Think about what data will be the basis of your students' infographics. We offer four different options in the Launch of the Making Inforgraphics section of this lesson. Some require teacher preparation.
- Students may create their final product with construction paper, markers and art supplies - or using a slide deck / word processor. It's up to you.
- This project is designed to span multiple days. Consider what work you want students to complete at home and at school.
}

|===

== Intro to Infographics @duration{flexible}

=== Overview

Students get curious about a variety of provided infographics, then complete research and plan to create their own - either electronically, or with paper and art supplies.

=== Launch

Infographics are graphic visual representations of data, information, or knowledge that present information quickly and clearly. You probably see infographics all around you - in advertisements, political campaigns, your textbooks, on the news... they're everywhere, because they are so impactful.

@slidebreak

A day before the 1986 launch of the Challenger, a team of engineers urged NASA to postpone, arguing that launching in cold weather would be extremely dangerous. Parts called "O-rings", they said, were likely to crack in cold weather. A cracked O-ring could lead to a catastrophic explosion – and the death of every astronaut onboard.

Mission control asked the engineers to explain this risk with _data_. 

@slidebreak

@right{@image{images/challenger-infographic.png, 350}}To make their case, the engineers created an infographic that displayed outlines of 48 rockets, each representing a previous launch. Each rocket was labeled with the temperature at launch, with marks showing O-ring damage. These marks were explained in a legend, to help mission control understand what the damage was.

@slidebreak@right{@image{images/challenger-infographic.png, 350}}

Unfortunately, their infographic was very hard to read:

- Instead of sorting the rockets by _temperature_ or _amount-of-damage_ (the two variables the engineers claimed were related!), they were sorted by...the date they launched.
- The temperature at launch, which was the most important thing the engineers wanted mission control to see, was written _sideways_, in a tiny font that was  difficult to read.
- The marks showing O-ring damage were hard to understand, and the legend that explained them __was on a separate page!__

@slidebreak

The engineers created an infographic that failed to clearly explain the risk, and mission control made the decision to go ahead with the launch. 73 seconds into the flight, the rocket exploded over the coast of Florida, killing everyone onboard. The tragedy crippled NASA, which did not launch another rocket for nearly three years. *The Challenger's explosion was, in the end, attributed to O-ring failure.*

A good infographic is worth a thousand words. And sometimes it even saves lives.

=== Investigate

For this project, you are going to create your own infographic! We'll start by studying a variety of infographics. What message does each convey? Is each infographic communicating its message in the most effective way? As a class, we'll view several infographics in the @online-exercise{https://docs.google.com/presentation/d/14D98yI7XPzZ-e8PDJrP0iXrvVNxhsFjm_m-1goKSRuw/edit?usp=sharing, "Sample Infographics"} slide deck and consider the answers to these questions.

@teacher{Teacher Note: Distributing the student-facing @handout{rubric-infographic.adoc} will help students understand the work that a good infographic does. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context.}

While viewing the @online-exercise{https://docs.google.com/presentation/d/14D98yI7XPzZ-e8PDJrP0iXrvVNxhsFjm_m-1goKSRuw/edit?usp=sharing, "Sample Infographics"}, we'll pause on each image to discuss.

@lesson-instruction{
- Look at the first slide of the @online-exercise{https://docs.google.com/presentation/d/14D98yI7XPzZ-e8PDJrP0iXrvVNxhsFjm_m-1goKSRuw/edit?usp=sharing, "Sample Infographics"} slide deck. What do you Notice? What do you Wonder?
- Are the words on the infographic clear and impactful - or does the meaning get lost? Why or why not?
- Are the images in the infographic impactful - or does the meaning get lost? Why or why not?
- Is the infographic accurate (e.g., every element is in the same proportion)?
- Why do you think each author chose to use a certain strategy to represent their ratio statement (e.g., illustrate ratios using repeated images)?}

@teacher{Use the questions above to facilitate a discussion of _each_ infographic in the slide deck.}

=== Synthesize

== Making an Infographic @duration{flexible}

=== Overview
In this project, students will (1) do some brainstorming and research, (2) write a ratio statement or create a display, and (3) make their infographic in a medium of their choice (or one that you have selected).

=== Launch

The first step of making an infographic is finding the data that you want to communicate!

@teacher{
There are a number of options for the data that might be the basis of your students' infographics.

- *Option 1:* Students can build bar charts or @ifproglang{pyret}{pie charts}@ifproglang{codap}{dot plots} in @ifproglang{pyret}{Pyret from the @starter-file{food}}@ifproglang{codap}{in CODAP from the @ifproglang{codap}{@link{https://docs.google.com/spreadsheets/d/1DYVHT7SSjnoDp4MQ80Z1qZSqFdEIlR8Gd20eMx9f1JA/edit#gid=161884673, "the Global Food Supply and Production dataset"}}} or any of the @link{https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/choosing-your-dataset/pages/datasets-and-starter-files.html, data sets in our library}.  __This option is appropriate for students who are comfortable independently building and interpreting displays.__

- *Option 2:* Students may find a @ifproglang{pyret}{pie or bar chart}@ifproglang{codap}{dot plot or bar chart} on the internet about a topic of interest to use as a starting point. _This option works best for students who can confidently conduct an internet search and discern which internet sources are reliable, but may struggle with independently building displays._

- *Option 3:* Students build a pie or bar chart in google sheets based on a summary statistic that they find about an issue that is of interest. _For this option, students need to be able to recognize reliable internet sources. Option 3 is valuable if there is a school-wide (or interdiscplinary) interest in students developing comfort with google sheets._

- *Option 4:* _This option is the most appropriate for younger students, who need more teacher support._ As a class, agree on a topic of interest, and then generate as many quantitative questions as possible about that topic. (E.g., if the topic is veterans, students might ask: What's the gender breakdown? Do veterans have higher suicide rates? What percentage of veterans struggle with mental health?) Then, spend some time locating data that answers each question to develop a list of ratio statements for students to choose from. Students will use their chosen statement to make a @ifproglang{pyret}{pie or bar chart}@ifproglang{codap}{dot plot or bar chart} and a corresponding infographic.

Some teachers prefer that all students work from the same dataset while others encourage students to pursue their own unique interests. It is up to you how much freedom or structure you offer your students during this phase.

Once students have conducted their research, it is time to write a ratio statement (for options 1-3) or create a bar/pie chart @ifproglang{codap}{or dot plot} (for option 4). Urge students to refer to their rubrics for guidance on doing this well!

Some teachers have students submit their work up to this point to monitor progress and ensure that all students have a solid foundation for the remainder of the project. Others opt to conduct a peer review using the @handout{rubric-infographic.adoc}.
}

=== Investigate

Once you have identified a ratio statement and a bar or pie chart to use as your starting point, you're ready to turn your creative energy toward making your infographic.

@lesson-instruction{

}

As students write their ratio statements and work on their infographics, one important point to emphasize is that all percentages are ratios! 40% is equivalent to 40 out of 100. If 40% of students wear baseball hats we can show 100 people, of which 40 are wearing hats. Or we could scale 40/100 down to 2/5 and show 5 people of which 2 are wearing hats.

Students should be now ready to independently complete their infographics.

A tricky thing about making infographics with images of people is that not all images accurately represent the diversity of the communities described by the statistics. We encourage the use of silhouetted images in infographics.

You may choose to allot class time (when students could use computers or art supplies), or you can direct students to complete the remainder of their infographics at home.}


=== Synthesize

- Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.

- If all students' infographics are on the same topic (e.g., if you used Option 4), a display featuring each student's project will provide a fascinating and comprehensive view of that topic!

