= Project: Make an Infographic

@description{Infographics are a powerful tool for communicating information, especially when made by people who understand how to connect visuals to data in meaningful ways. This project is an opportunity for students to become more flexible math thinkers while tapping into their creativity.}

@lesson-prereqs{bar-and-pie-charts}


[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* think critically and creatively about ratio relationships
* represent ratio relationships using either repeated images, scaled images, or area models

| Student-facing Lesson Goals
|

* Let's make an infographic on a topic of interest!

| Materials
|[.materials-links]

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
|
* Think about what data will be the basis of your students' infographics. We offer four different options in the "Investigate" section of this lesson. Some require teacher preparation.
* Students may create their final product with construction paper, markers and art supplies - or via a slide deck / word processor. It's up to you. You may opt to provide some supplies.
* This project is designed to span multiple days. Consider what work you want students to complete at home and at school.

|===

== Make an Infographic @duration{flexible}

=== Overview

Students get curious about a variety of provided infographics, then complete research and plan to create their own - either electronically, or with paper and art supplies.

=== Launch

A good *infographic* is worth a thousand words!

Infographics are graphic visual representations of data, information, or knowledge that present information quickly and clearly. You probably see infographics all around you - in advertisements, political campaigns, your textbooks... they're everywhere, because they are so impactful.

@teacher{Explain to students that they are going to create their own infographics. To launch the project, they will look and consider a variety of infographics. As you peruse the infographics in the @online-exercise{https://docs.google.com/presentation/d/14D98yI7XPzZ-e8PDJrP0iXrvVNxhsFjm_m-1goKSRuw/edit?usp=sharing, "Sample Infographics"} slide deck together, discuss as a class what students observe.

Before you dive in, we recommend printing and distributing the student-facing @handout{rubric-infographic.adoc} to help students understand the scope of the project and your expectations at the outset. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context.

As you move through the slide deck, discuss the questions below.}

[.lesson-instruction]
- What do you Notice? What do you Wonder?
- Are the words on the infographic clear and impactful? Why or why not?
- Are the images in the infographic impactful? Why or why not?
- Is the infographic accurate (e.g., every element is in the same proportion)?
- Why do you think each author chose to use a certain strategy to represent their ratio statement (e.g., illustrate ratios using repeated images)?

Emphasize to students that a tricky thing about making infographics with images of people is that not all images accurately represent the diversity of the communities described by the statistics. We encourage the use of silhouetted images in infographics.

=== Investigate

The remainder of the project involves: (1) research, (2) writing a ratio statement or creating a display, and (3) making the actual infographic.

First, students must consider the information that will form the basis of their infographics. Below, we offer a number of options for what data will be the basis of your students' infographics.

- *Option 1:* Students can build bar or pie charts in Pyret from the @starter-file{food} or any of the @link{https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/choosing-your-dataset/pages/datasets-and-starter-files.html, data sets in our library}.

- *Option 2:* Students may find a pie or bar chart on the internet about a topic of interest to use as a starting point.

- *Option 3:* Students build a pie or bar chart in google sheets based on a summary statistic that they find about an issue that is of interest.

- *Option 4:* Students choose from a list of provided ratio statements about topics of interest. Students will use that statement in making a bar or pie chart and a corresponding infographic.

Some teachers prefer that all students work from the same dataset while others encourage students to pursue their own unique interests. It is up to you how much freedom or structure you offer your students during this phase.

Once students have conducted their research, it is time to write a ratio statement (for options 1-3) or create a bar/pie chart (for option 4). Urge students to refer to their rubrics for guidance on doing this well!

Some teachers have students submit their work up to this point to monitor progress and ensure that all students have a solid foundation for the remainder of the project. Others opt to conduct a peer review using the @handout{rubric-infographic.adoc}.

As students write their ratio statements and work on their infographics, one important point to emphasize is that all percentages are ratios! 40% is equivalent to 40 out of 100. If 40% of students wear baseball hats we can show 100 people, of which 40 are wearing hats. Or we could scale 40/100 down to 2/5 and show 5 people of which 2 are wearing hats.

At this point, students should be ready to independently complete their projects. You may choose to allot class time (when students could use computers or art supplies), or you can direct students to complete the remainder of their infographics at home.


=== Synthesize

* Once finished, encourage students to self-assess and revise their work. Peer review is built into the lesson, but you might also have students use the @handout{rubric-infographic.adoc} to facilitate further self and peer review.

* Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.

