= Angle Similarity

Here's the data table from a different source. It has different restaurants, and only includes data for Fries and Burgers.

[.data-table, cols="^.^1a, 4a, ^4a, ^4a", options="header"]]
|===
| ID| Restaurant  		| Fries (5=best) | Burgers (5=best)
| 1 | Burger Sting 		| 0    		     | 4
| 2 | Dead Robin		| 4    	         | 0
| 3 | Five Lies     	| 2   	         | 2
| 4 | Snake Shack  		| 2            	 | 3
| 5 | In-N-Doubt 		| 1  	         | 1
| 6 | Dairy Spleen 		| 2 			 | 3
|===

[.FillVerticalSpace, cols="^1a,^1a",  stripes="none", frame="none"]
|===
|
@n *Burger Sting v. Dead Robin*

Coordinate A: @fitb{6em}{(0,4)}
Coordinate B: @fitb{6em}{(4,0)} +
@image{../images/soln1.png, 250} +
The angle formed is @fitb{2em}{@ifsoln{90°}}.


| @n *In-N-Doubt v. Burger Sting*

Coordinate A: @fitb{6em}{@ifsoln{(1,1)}}
Coordinate B: @fitb{6em}{@ifsoln{(0,4)}} +
@ifnotsoln{@image{../images/burger-fry-blank.png, 250}}
@ifsoln{@image{../images/soln2.png, 250}} +
The angle formed is @fitb{2em}{@ifsoln{45°}}.


| @n *Five Lies v. Dead Robin*

Coordinate A: @fitb{6em}{@ifsoln{(2,2)}}
Coordinate B: @fitb{6em}{@ifsoln{(4,0)}} +
@ifnotsoln{@image{../images/burger-fry-blank.png, 250}}
@ifsoln{@image{../images/soln-alt.png, 250}} +
The angle formed is @fitb{2em}{@ifsoln{45°}}.


| @n *Snake Shack v. Dairy Spleen*

Coordinate A: @fitb{6em}{@ifsoln{(2,2)}}
Coordinate B: @fitb{6em}{@ifsoln{(2,3)}} +

@ifnotsoln{@image{../images/burger-fry-blank.png, 250}}
@ifsoln{@image{../images/soln4.png, 250}} +
The angle formed is @fitb{2em}{@ifsoln{0°}}.

|===

