= Distance Similarity
++++
<style>
.one-dimension td, .two-dimensions td { padding: 0 0.6em !important; }
#preamble_disabled { flex-grow: 0 !important; }
table:not(.data-table) { margin: 0 !important; }
</style>
++++

[.data-table, cols="^.^1a, 4a, ^4a, ^4a, ^4a", options="header"]]
|===
| ID  |  Restaurant  | Price (1 = cheap)| Fries (5=best) | Burgers (10=best)
| "M" | McDonalds   | 1.45             | 4.6            | 5
| "B" | Burger King | 1.51             | 4.1            | 6
| "W" | Wendy's     | 1.47             | 4.5            | 7
| "F" | Five Guys   | 2.20             | 3.9            | 8
| "D" | Dairy Queen | 2.11             | 3.7            | 4
| "I" | @star *In-N-Out* | *1.45*      | *4.4*          | *8*
|===


[.no-flex-section]
== Distance in 1 Dimension
@n For each of the attributes plotted below, *find In-N-Out* and mark it with a @star. Then use the number lines and the corresponding columns of data above to complete each row of the table below by *finding the closest restaurant* in that dimension and *calculating the `distance-similarity`* to In-N-Out.

@vspace{1ex}

[.one-dimension,cols="^5a, ^.^4a, ^.^1a", stripes="none", frame="none", options="header"]
|===
| Number Line
| Closest Restaurant
| Distance

| @image{../images/number-line-price.png, 250}
| @ifsoln{McDonalds}
| @ifsoln{0}

| @image{../images/number-line-fries.png, 250}
| @ifsoln{Wendy's}
| @ifsoln{0.1}

| @image{../images/number-line-burger.png, 250}
| @ifsoln{Five Guys}
| @ifsoln{0}
|===

@n Did your calculations give you a clear answer about which restaurant is most similar to In-N-Out? @fitb{}{} +
@fitb{}{@ifsoln{No. It's different for each attribute!}}


== Distance in 2 Dimensions

@n Use the data table at the top of the page to help you find *In-N-Out* on each of the graphs below and mark it with a star (@star). Then find *Five Guys* on each of the graphs below and mark it with a triangle (&#9651;). Draw a line connecting them on each of the graphs below.

@vspace{1ex}

[.two-dimensions,cols="^5a,^5a", frame="none", grid="none", stripes="none"]
|===
| @image{../images/fries-v-price-scatter.png, 250}
| @image{../images/burgers-v-price-scatter.png, 250}

| *Price-Fries* Distance - *In-N-Out* to *Five Guys*: @fitb{}{@ifsoln{0.90}}
| *Price-Burgers* Distance - *In-N-Out* to *Five Guys*: @fitb{}{@ifsoln{0.75}}
|===

@n Use the @starter-file{ai-fast-food} to generate a table with a column for `distance-similarity` to In-N-Out for the Price-Fries Space and another table for the Price-Burgers space. Record the distances from In-N-Out to Five Guys above.

@n Why are the restaurants listed in different orders in these tables? @fitb{}{} +
@fitb{}{@ifsoln{because they are ordered from most similar to least similar and the most similar restaurants change depending on the space}}

@n Why might the values in the `distance-similarity` column be bigger for the Price-Burgers Space? @fitb{}{} +
@fitb{}{@ifsoln{The burger ratings are on a 1-10 scale, not a 1-5 scale. The burgers might be more different than the fries.}}