= From Two Dimensions to Three
++++
<style>

</style>
++++

== Projection
[%autowidth, cols="<,<", frame="none"]
|===
| @image{../images/projection-bw.png, 175}
|
@n In your own words, explain what is happening in this picture. @fitb{}{} +
@blanklines{5}{}
|===

== Plotting Images in 2 Dimensions ("Blue-Green-Red Space")
@link-instructions{You'll need the @online-exercise{https://www.desmos.com/3d/qmu6fmrs6h, RGB Image Plot} Desmos file open on your computer. At any time, you can click  &#8635;   to reset the file to the beginning.}

- Image 4 is represented as a purple dot, while the points for our other images are shown in green.
- *Remember the mission!* We want to find the green point that's "most similar" to the purple one.

@n This is the same as the Pyret scatter plot on the bottom of @printable-exercise{plotting-images.adoc} for (circle one): @hspace{1em} @ifsoln-choice{Blue-Green Space} @hspace{1em} Blue-Red Space

@n *Turn on* the "Blue-Red" folder, and explain what you see. @fitb{}{} +
@blanklines{1}{@ifsoln{A bunch of red points appear, all along the blue (Z) axis}}

@n Click on any dot, drag it around to explore, and explain what you see. @fitb{}{} +
@blanklines{1}{@ifsoln{The whole cube rotates! I can see the Blue-Green scatter plot against one wall of the cube, and the Blue-Red scatter plot against the other}}

@n Rotate the cube so that the Blue-Red scatter plot is at the "front" of the cube. Compare it to the Pyret scatter plot on the bottom of @printable-exercise{plotting-images.adoc}.

@n *Turn on* the "Blue-Green-Red" folder, and rotate the cube as needed. Explain what you see. @fitb{}{}
@blanklines{1}{@ifsoln{A bunch of blue points appear, one for each image. This time they are being plotted inside the cube, instead of on a face.}}

@n Can you rotate the space so that the blue (3D) points _completely cover_ the green (2D) ones? The red (2D) ones?

@n How is the 3D model in this desmos file like the image at the top of the page? @fitb{}{} +
@blanklines{2}{@ifsoln{Like the image at the top of the page, it means each of our 2D scatter plots is a projection of the data}}.

== Lines and Angles
@n *Turn on* the "Lines" folder, then adjust the @math{I_n} slider draw lines to different Images. Explain what is happening. @fitb{}{} +
@blanklines{2}{@ifsoln{There's always a line from the origin to the purple dot. The slider adds another line from the origin to the dot of my choosing.}}

@n Could you imagine two lines in this 3D space that start at the origin and *wouldn't* form an angle we can measure? If so, what are they? If not, why not? @fitb{}{} +
@blanklines{1}{
@ifsoln{No - as long as both lines need to start at the origin, they will always form a "V" - or "slingshot" - shape. And no matter how that "V" is rotated or tilted, the angle between the lines can always be measured.}
}