= Categories and Attributes

++++
<style>
 div#body .graph td {
  --width:    3.25in;
  --height:   2.5in;
  --top_pct:  0.9;
  --left_pct: 0.1;
  --x_label: '';
  --y_label: '';
  position: relative;
}

/* Make the middle cell white, overriding all the graph stuff */
 div#body .graph td:nth-child(2),
 div#body .graph th:nth-child(2) { background: white !important; }

</style>
++++
== Choose Your Category

@n Choose a category, along with *three* attributes. Fill in the header for the table below.

@n Add _at least three examples_ of your category to the table, filling in values for each attribute

[.FillVerticalSpace, cols="^.^1a,8a,4a,4a,4a", options="header"]
|===
| ID
| @fitbruby{100%}{}{category}
| @fitbruby{100%}{}{attribute1}
| @fitbruby{100%}{}{attribute2}
| @fitbruby{100%}{}{attribute3}

|1||||
|2||||
|3||||
|4||||
|5||||
|===

@n How could you *measure* the similarity between any two examples in this category? @fitb{}{} +
@blanklines{2}{}

@n Put a star (@star) next to the row that's your favorite example of this category.

@n Which of your other examples is the _most similar_ to your favorite? Put a check (✔) next to it.

== Graph Your Space

@n *Label* and *number* your axes on the two graphs below, paying attention to the scale of each attribute. Use attributes 1 & 2 for the first graph, and attributes 2 & 3 for the second.

[.graph, cols="^5a,1a,^5a", frame="none", grid="none",options="header"]
|===
| Attribute 1 v. Attribute 2   	| | Attribute 1 v. Attribute 3
|								| |
|===

@n Plot your examples as points in both graphs, using a star (@star) to plot your favorite example. Put a check (✔) next to the example that is most similar.


@n Do you have any new ideas for how to *measure* the similarity between any two examples in this category? @fitb{}{} +
@blanklines{2}{}
