= Plotting Images

@lesson-instruction{For this page, you'll need @starter-file{ai-image} open on your computer}


== Plotting Images in 1 Dimension ("Green Space")
@n In the *Interactions Area*, evaluate `image-dot-plot(model, "green", thumbnail)`, and hover your mouse over the images.

@indented{
- What are the `green` values for our grassy images? @fitb{6em}{@ifsoln{5,245}} and @fitb{6em}{@ifsoln{4784}} How far apart are they? @fitb{}{@ifsoln{461}}
- How does this help us look for similarity? @fitb{}{@ifsoln{The smaller the distance, the more similar the image!}}
}

@n Evaluate `distance-similarity(model, "3", [list: "green"])`. Was image 6 the most similar? @fitb{}{@ifsoln{yes!}}


== Plotting Images in 2 Dimensions ("Blue-Green Space")
@n In the *Interactions Area*, evaluate `image-scatter-plot(model, "green", "blue", thumbnail)`. Can we still calculate the distance? @fitb{}{@ifsoln{yes! The distance formula!}}

@n Are the grassy images still clustered together? @fitb{4em}{@ifsoln{yes}} Do you see any _other_ clusters? @fitb{}{} +
@fitb{}{@ifsoln{The images with trees and water are clustered, and the squares are clustered with the sunset.}}

@n Let's see how well `distance-similarity` works for our 2-dimensional space:

[%autowidth, cols="<,^,^", options="header"]
|===
| Check 	| Code 																| Success?
| *Grass*  	| `distance-similarity(model, "3", [list: "green", "blue"])` | @ifsoln{Yes}
| *Snow*  	| `distance-similarity(model, "5", [list: "green", "blue"])` | @ifsoln{Yes}
| *Sun* 	| `distance-similarity(model, "0", [list: "green", "blue"])` | @ifsoln{No}
|===

@n Looking at the `model` table (not a chart!), do you think using `"red"` would show us that our two squares are similar? Why or why not? @fitb{}{} +
@fitb{}{@ifsoln{No - the numbers are so far apart!}}


== Connecting Blue-Green and Blue-Red Space

@n The following Pyret scatter plots show the relationship between both Blue-v-Green and Blue-v-Red, for the images in our model:

[cols="<3a, 1a, >3a", frame="none", "grid="none"]
|===
| @image{../images/blue-v-green.png} | | @image{../images/blue-v-red.png}
|===

@n Are the points in similar places? @fitb{3em}{@ifsoln{No}} How can the plots be so different, if they represent the same images? @fitb{}{} +
@fitb{}{@ifsoln{we're using different axes}}

