[.beta]
= Generative Models

@description{Students consider how statistics and probability drive AI text generation, learning that language models can produce text that sounds credible but may not actually be credible.}

@lesson-prereqs{data-driven-algorithms}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives

| Student-facing Lesson Goals
|
- Let's explore how probability influences the output of generative AI models.

| Materials
|[.materials-links]
@material-links

| Preparation
| @preparation{
- Make a copy of the @online-exercise{https://docs.google.com/forms/u/1/d/1C1WSad_IrVT0pd_IXG7yCCM30CVoIibv9kBDKnEJ5RI/copy, What comes next? Survey Google Form} so that you can examine your class's data. _If you are using our Google Slides, be sure to add the link to your copy of the form to the appropriate slide._}
|===

== Introduction to Statistical Language Modeling
@objective{ai-slm}

=== Overview
Students explore how text prediction relies on statistical language modeling.

=== Launch
@slidebreak{Launch}

While texting, emailing, or even conducting a web search, you've probably noticed that your thoughts and sentences are sometimes finished for you! Predictive text is now a common feature of many apps, and it is made possible by a certain form of AI: the @vocab{language model}.

@teacher{
Make sure you've made a copy of the @online-exercise{https://docs.google.com/forms/u/1/d/1C1WSad_IrVT0pd_IXG7yCCM30CVoIibv9kBDKnEJ5RI/copy, survey} and have created a link to share with students, so that you can look at your data as a class!
}

@slidebreak{Launch}

@lesson-instruction{
Consider this start of a phrase: "Close the..."

- What word might come next?
- As a class, are there more than one “next word”?
- Which one is the most likely?
}

@teacher{
Display the survey results for the class to see. If a word is repeated, summarize the results by keeping a tally of how many students suggest each particular word.

Students will think of words like "door", "box", "microwave", "laptop"...
}

=== Investigate
@slidebreak{Investigate}

Let's look a little more closely at the words we generated.

@QandA{
@Q{Which words were suggested most often?}
@Q{Which words were suggested least often?}
@Q{Are you surprised by the most and least common words? Why or why not?}
@Q{What fraction of our class proposed each of our top three words?}
@A{For example: If there are 25 students in your class, and 8 students chose “door”, it was chosen 8/25ths of the time.}
}

@slidebreak{Investigate}

Statistical language models are built on the assumption that the fraction of the time that a word follows a series of words in a training corpus can help predict the likelihood of it being the right word to follow that same series of words in a future scenario. In this lesson, we will refer to that fraction as its @vocab{probability}.

@QandA{
@Q{Do you think a text messaging app with a predictive text feature would produce the same results as our class? Why or why not?}
@A{Answers will vary. Invite conversation.}
@A{An app will probably not suggest all the same words.}
@A{Our class is a pretty small sample, all from the same generation and geography and we are all currently at school so our minds are primed to respond differently than if we were somewhere else.}
}

@slidebreak{Investigate}

Similar to other AI systems we've discussed, predictive text features are trained on a large amount of data, in this case, text.

During training:

1. The computer extracts each use of the phrase "Close the" from the corpus, along with the subsequent word.
2. It then determines the probability of each possible next word.

@ifnotslide{@right{@image{images/texting-app.png, 200}} When making a suggestion: 

@hspace{1em}It offers the words that had the highest probability of following "Close the" in the corpus.

Consider this screenshot from a text messaging app. +
In the @vocab{training corpus} it was built on, "door", "doors", and "house"  most commonly appeared after "Close the". +
As a result, those words are suggested. +
But are all users recommended the _same_ completions?
}

@ifslide{When making a suggestion: 

@hspace{1em}It offers the words that had the highest probability of following "Close the" in the corpus.

@slidebreak{InvestigateR}

@image{images/texting-app.png, 200}
Consider this screenshot from a text messaging app. +
In the @vocab{training corpus} it was built on, "door", "doors", and "house"  most commonly appeared after "Close the". +
As a result, those words are suggested. +
But are all users recommended the _same_ completions?
}

@slidebreak{Investigate}

@QandA{
@Q{What do you think? Will your phone suggest the same words as your classmates' phones would? Why or why not?}
@A{Before we get into the in-depth student-facing explanation, below, invite discussion!}
@A{This question is a great opportunity to revisit previous concepts, in particular the process of training and sampling that students discussed when thinking about @lesson-link{decision-trees-evaluating} and @lesson-link{regression-models-simple}.}
}

@slidebreak{Investigate}

For a variety of reasons, not all phones will propose the same completions:

- If there are multiple words with equal probability, the system will select the word at random. As a result, even the same phone won't necessarily propose the same word every time.
- Not all phones use the same corpus, the same prediction rules, or the same amount of randomness.
- A messaging app also includes a @vocab{model} of _the words that the owner uses_, to personalize suggestions to the way the user writes.
- Some predictive text features even account for the specific message being written! Typing first letter of an unusual word that you used in the same message triggers the app to propose that unusual word.

@scrub{
@slidebreak{Investigate}

@QandA{
@Q{We just considered four reasons why different phones sometimes propose different completions. Do each of these four reasons represent _statistical_ phenomena? Why or why not?}
@A{Phenomena 1 and 2 are statistical, given that statistical language modeling always includes some element of randomness.}
@A{Phenomena 3 demonstrates the use of a _personalized_ language model, a more refined version of a statistical language model.}
@A{Phenomena 4 is almost anti-statistical! The AI consumes and uses data outside of the model for the corpus.}
}

Phenomena 3 and 4 above suggest that sometimes making a usable tool requires that we step out of bounds! Although pure statistical language models are powerful, the upgrades that programmers develop can make the AI _better_ at completing the task that it was designed to complete.
}

@slidebreak{Investigate}

You have just considered the workings and in-context use of a @vocab{language model}. Hopefully you have discovered that, although it sometimes may _seem_ like your texting app can read your mind... it can't. It doesn't know the rules of grammar, the meanings of words, or your intentions when you are composing a text. It just knows @vocab{probability}, which it uses in ways that are often very impressive (but sometimes not!).

@teacher{
Throughout the lesson, we'll explore the very important "sometimes not" parenthetical, above.}

Using computers to process languages, often by consuming a corpus and constructing a model, is referred to as @vocab{Natural Language Processing}. In this lesson, we will explore in greater detail what exactly @vocab{Natural Language Processing} entails.

=== Synthesize
@slidebreak{Synthesize}

@QandA{

@Q{Might statistical language modeling be possible for other spoken human languages? Which languages?}
@A{Statistical language modeling will work for any language! The AI does not need to "know" anything about the rules of grammar; it just follows rules that enable it to identify patterns.}

@Q{Can you think of other things besides human spoken languages that a similar approach might work for?}
@A{With statistical language modeling, AI can compose music, play chess games, and more. The "text" does not need to be made up of words: any symbolic notation at all will do as long as it uses spaces to separate the symbolic "words".}
}

== Constructing a Statistical Language Model
@objective{ai-slm}
@objective{ai-slm-create}

=== Overview
Students construct a statistical language model by decomposing the text and computing the probabilities of different words following each other.

=== Launch
@slidebreak{Launch}

The best way to make sense of statistical language modeling is to try it yourself! We'll start by constructing a model.

For our @vocab{corpus}, we will start with an excerpt from the folk song _There was an Old Lady Who Swallowed a Fly_, which tells the nonsensical story of an old lady who swallows a fly, and the unfortunate series of events that follow.

@indented{_she swallowed the cat to catch the bird +
she swallowed the bird to catch the spider_	
}

@lesson-instruction{
- You'll find this `short-corpus` at the top of @printable-exercise{build-lang-model-short.adoc}.
- You'll also see a table of strings of different lengths that we can chop our corpus into.
}

@slidebreak{Launch}

The formal word computer scientists use to describe the strings that can be generated from a corpus (one word at a time, two words at a time, etc.) is @vocab{n-gram}. In an @math{n}-gram, @math{n} represents the number of words in the chunk. For special cases where @math{n} is 1, 2, or 3, the @math{n}-grams are called @vocab{unigrams}, @vocab{bigrams}, and @vocab{trigrams}.

@QandA{
@Q{What other collections of words (besides @vocab{unigrams}, @vocab{bigrams}, and @vocab{trigrams}) have you encountered that begin with "uni", "bi", and "tri"?}
@A{Answers will vary!}
@A{unicycle, bicycle, tricycle}
@A{(monomial), binomial, trinomial...}
@A{triangle, n-gon}
@A{biceps, triceps, (quadriceps)}
@A{unicorn}
}

@slidebreak{Launch}

@lesson-instruction{
- Complete the table on @printable-exercise{build-lang-model-short.adoc} by determining how often each of the n-grams occurs in the text.
}

@slidebreak{Launch}

Computers are really fast at generating word counts. 
Pyret has a function that will make more or less the same table you just completed in the blink of an eye.

@hspace{2em} @show{(contract 'build-lang-model '((corpus String) (max-ngram-size Number)) "Table")}

@lesson-instruction{
- Open the @starter-file{ai-old-lady} and click "Run".
- In the Definitions Area (on the left) you will see `m-short` defined to produce a table using the `short-corpus` with a maximum @vocab{n-gram} length of 3.
- Evaluate `m-short` in the Interactions Area.
}

@QandA{
@Q{How is the table similar to the one you made?}
@A{It has the same 3 columns and the same number of rows}

@Q{How is the table different from the one you made?}
@A{n-grams that are the same size are listed in alphabetical order.
	* While it's easier for humans to read ordered tables like this, it's extra error-prone work for humans to attempt to make an alphabetized count table from a text.}
}

@slidebreak{Launch}

@lesson-instruction{
- Confirm that your counts match the counts in the pyret table.
- Then complete the questions at the bottom of @printable-exercise{build-lang-model-short.adoc}.
}

@slidebreak{Launch}

@QandA{
@Q{How was knowing the count of a particular @vocab{n-gram} in the @vocab{corpus} useful in determining the probability of the next word?}
@A{The count of any bigram, divided by the count of its first word gives us the probability of the first word being followed by the second word.}
}

=== Investigate
@slidebreak{Investigate}

In math we can describe the @vocab{conditional probability} that `"bird"` will follow `"the"` in our `short-corpus` using the following notation:

@indented{
@math{p(bird | the) =}
@math{\frac
	{\textit{count(the bird)}}
	{\textit{count(the...)}} = \frac{2}{4} = 0.5 = 50}%
}

@teacher{
If you'd like to explore @lesson-link{probability-inference, probability and sampling} in greater depth, check out our lesson on the subject
}

@slidebreak{Investigate}

Let's take a look at the full lyrics of _There was an Old Lady who Swallowed a Fly_ and explore how we could use probability to make predictions about lines in the song.


@scrub{I WOULD LOVE TO GIVE THEM THE OPTION OF MAKING A COUNT TABLE IN PYRET, BUT NEED TO SEE IT ALPHABETIZED FIRST - it's unwieldy in its current state.}

@lesson-instruction{
- Turn to @printable-exercise{old-lady-comparing-probability.adoc}.
- Complete the questions at the bottom using both the title and the lyrics as your @vocab{corpus}.
- If you find it helpful, you can use Pyret's `build-lang-model` function to find the counts.
}

@slidebreak{Investigate}

@QandA{
@Q{Which word would you suggest to follow "swallowed a" for a random line in the song? Why?}
@A{Fly. Because it has the highest probability of being the word that finishes the line in the song. }

@Q{How would you know that the word you suggested was the right word for finishing the line of the song?}
@A{We wouldn't! It would be the right word 60% of the time and the wrong word 40% of the time.}
@A{When our computers offer us suggested words, they don't always come up with the right one, either!}
}

@slidebreak{Investigate}

In order for Generative Text models to suggest next words, they need to build models with computed probabilities for all of the possible n-grams! Pyret has a function that will do just that.

@hspace{2em} @show{(contract 'build-stat-lang-model '((corpus String)) "Model")}

@lesson-instruction{
- Return to the @starter-file{ai-old-lady}.
- In the Definitions Area define `model = build-stat-lang-model(corpus)` and click "Run" to load it.
- Then evaluate `model` in the Interactions Area.
}

@QandA{
@Q{What do you Notice? What do you Wonder?}
@A{Answers will vary. Possible noticings might include: 
  * some of the strings are empty. These probabilities should the probability of those words occurring without taking the preceding word into consideration. Generative text functions use those probabilities to select starting words.
  * the table uses the same notation for describing conditional probability that they are used to
  }
}

=== Synthesize
@slidebreak{Synthesize}

@QandA{
In our song corpus, 

- there were _four_ possible completions for the unigram "the"
- there were only _three_ possible completions for the 3-gram "to catch the"

We can say that, _in this corpus_, as the n-gram gets longer, the number of completion options decreases.

@Q{Do you think it will generally be true of other corpuses that as the n-gram gets longer, the number of completion options decreases?}
@A{Yes, in general, this is a true statement: longer phrases have fewer possible completions than single words.}
}


== Sampling from the Model
@objective{ai-slm-hallucination}

=== Overview
Students use their statistical language model in a generative way, to produce output.

=== Launch
@slidebreak{Launch}

Having built a language model, what can we do with it? We can use it in a generative way: we can produce output!

How might we go about doing that?

- We can start by choosing our first word. A common approach is to ask, "What's the most common @math{n}-gram in the corpus?" but we can also choose the starting word on our own, if we want.
- Next, we ask: "Given the first @math{n}-gram, what is the most common successor?"
- We repeat this second step forever! ...or, more realistically, until we decide to stop the program. A simple statistical language model, however, will generate text ad infinitum.

=== Investigate
@slidebreak{Investigate}

We've created helper functions for this, too:

@show{(contract "completions" '((model Table) (start String)) "Table")}

@show{(contract "choose-completion" '((model Table) (start String) (n Number)) "String")}

- We can use these contract to find all the possible completions for a starting string: `completions(m, "swallowed the")`

- Or to choose the next `n` words at random:
@indented{
`choose-completion(m, "swallowed the", 1)`
`choose-completion(m, "swallowed the", 2)`
}

@slidebreak{Investigate-DN}

@teacher{Note that on @printable-exercise{sampling.adoc}, questions build on one another. In other words, a student who misses Question 2 will also get Question 3 incorrect. To ensure that class runs smoothly, we encourage you to require that students check their work with a partner before moving from one question to the next. Encouraging students to annotate @printable-exercise{old-lady-lyrics.adoc} will also result in more accurate counting and therefore more correct responses!}

@lesson-instruction{
- Complete the first section of @printable-exercise{sampling.adoc}.
}

@slidebreak{Investigate}
@QandA{
@Q{What four-word phrase did you generate?}
@A{"She swallowed a fly"}

@Q{Did everyone in your class end up with same phrase? How and why did that happen?}
@A{Yes. When considering which word to generate next, there was always one word that was clearly the most probable, and there were no ties.}

@Q{What do you think would happen if you start with a word like "llama", which doesn't appear _at all_ in the original corpus?}
@A{The probability of following "llama" is the same for every word: zero. Maybe `choose-completion` would choose at random?}
}

@slidebreak{Investigate}

@lesson-instruction{
- Complete the second section of @printable-exercise{sampling.adoc}.
- When you're finished, discuss: what would happen if we just kept evaluating `choose-completion`, over and over?
}

@QandA{
@Q{What four-word phrase did you generate for *Text Generation 2a*?}
@A{The class should be split between "the spider to catch" and "the spider that wriggled".}

@Q{Why didn't everyone end up with the same phrase?}
@A{We were forced to incorporate randomness when there was a tie for the most probable word to follow "spider".}

@Q{What would happen if we just kept evaluating `choose-completion`, over and over?}
@A{It would keep choosing words!}
}

@slidebreak{Investigate}
If you're curious to see what would happen if we just kept going, evaluate `generate-from(m, "there")`, or `generate-from(m, "cat")`!

@QandA{
@Q{Will we always get the same output if we always use the same input?}
@A{No - in the event of a tie, it will choose randomly!}
}

=== Synthesize
@slidebreak{Synthesize}
@lesson-point{A model is a mathematical summary of a dataset}

@QandA{
@Q{What does our n-grams table summarize about this dataset?}
@Q{What does it leave out?}
}

@slidebreak{Synthesize}
@lesson-point{All models are wrong. Some are useful.}

@QandA{
@Q{Will _any_ language model be *perfect*? Why or why not?}
@Q{When is a language model *useful*?}
}

@slidebreak{Synthesize}

@QandA{
Critics of ChatGPT and other language models raise a variety of concerns. Consider each of them, below.

@Q{ChatGPT sometimes "makes stuff up." Why does this happen? What is actually going on?}
@A{When ChatGPT produces false or misleading information, it is not glitching nor is there a bug. ChatGPT is just doing what it does, following the model as it ought to.}

@Q{ChatGPT has biases that can be seen in its text output. Where do these biases come from?}
@A{If there are biases in the corpus, there will likely be biases in the output!}
}
