= Defining Values -- Practice


1) On the line below, *write the Code* to define `PRIZE-STAR` as the pink outline of a star of size 65.

@vspace{3ex}

@show{(sexp->code `(define PRIZE-STAR (star 65 "outline" "pink")))}

@vspace{3ex}

Using the `PRIZE-STAR` definition from above, draw the Circle of Evaluation and write the code for each of the exercises. One Circle of Evaluation has been done for you.

@vspace{3ex}

[cols="^1a,^1a", stripes="none"]
|===
|2) The outline of a pink star that is 3 times 
@span{.clear}{}the size of the original (using `scale`)
--
@vspace{10ex}
@show{(sexp->coe  '(scale 3 PRIZE-STAR))}
@show{(sexp->code '(scale 3 PRIZE-STAR))}
--
|3) The outline of a pink star that is half the size of the
original (using scale)
--
@vspace{10ex}
@show{(sexp->coe  '(scale 0.5 PRIZE-STAR))}
@show{(sexp->code '(scale 0.5 PRIZE-STAR))}
--
|4) The outline of a pink star that is size 65 and has
been rotated 45 degrees
--
@vspace{10ex}
@show{(sexp->coe  '(rotate 45 PRIZE-STAR))}
@show{(sexp->code '(rotate 45 PRIZE-STAR))}
--
|5) The outline of a pink star that is 3 times the size of the original *and* has been rotated 45 degrees
--
@vspace{10ex}
@show{(sexp->coe  '(rotate 45 (scale 3 PRIZE-STAR)))}
@show{(sexp->code '(rotate 45 (scale 3 PRIZE-STAR)))}
--
|===

6) How does defining values help you as a programmer?

@vspace{20ex}

