[[questions]]
type = "MultipleChoice"
# The prompt we want to use (can be a multi-line string!)
prompt.prompt = """
Choose the statement you most agree with about the scatterplot on the left.
"""
prompt.image = "scatter-positive.png"

# We're OK with the answers being randomized, so leave this commented
# prompt.answerIndex = 1
answer.answer = "There appears to be a positive correlation."

prompt.distractors = [
"There appears to be a strong negative correlation.",
"There appears to be a perfect correlation.",
"There appears to be a weak negative correlation."
]

# This will add an extra string of text at the bottom of the question.
# Some questions might need some extra explanation
context = """
"""

#################################################################################
#################################################################################
#################################################################################
[[questions]]
type = "MultipleChoice"
prompt.prompt = """
A strong negative correlation would have an r-value that is closest to:
"""
answer.answer = "-1"
prompt.distractors = [
"-0.5",
"0",
"0.5",
"1",
]

prompt.answerIndex = 0
context = """
"""
