= Linear Functions: Definitions and Tables

++++
<style>
.small-table {max-width: 75%}
.first-table td, .first-table th {text-align: center;}
</style>
++++

@lesson-description{Students describe linear relationships as function definitions and tables of ordered pairs, identifying slope and y-intercept in both representations}

[@lesson-intro-table]
|===
@prereqs-stds{ds-linear-tables-graphs}
| Lesson Goals
| Students will be able to...

* define linear functions to match a given table
* identify whether or not a function definition is linear

| Student-facing Lesson Goals
|

* Given a table showing a linear relationship, I can define a function to match
* Given a function definition, I can tell whether or not it is linear

| Materials
|[.materials-links]
* Lesson Slides

@material-links

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with
* All students should log into @online-exercise{https://code.pyret.org, CPO} and open the "Graphing Starter File" they saved from the prior lesson. If they don't have the file, they can @link{https://code.pyret.org/editor#share=XYZ, open a new one}

@include{xtra/lang-prereq.adoc}
|===

== From Tables to Function Definitions @duration{20 minutes}

=== Overview
Students explore function definitions as a way of _summarizing_ linear relationships expressed through Tables.

=== Launch
Take a look at the following Table:

[.sideways-pyret-table]
|===
| x | 0 | 1 | 2 | 3 
| y | 1 | 3 | 5 | 7
|===

* What do you *Notice* about this table?
* What do you *Wonder*?

(After Notice and Wonder, ask specific questions...)

* What are the values in the @vocab{header row}?
* What do you think the values in the _next_ row will be?
* Is the relationship between x and y @vocab{linear}? Why or why not?
* If it's linear, what is the @vocab{slope}? What is the @vocab{y-intercept}?

Let's review know how to find the @vocab{slope} and @vocab{y-intercept} for a table.

We start by finding two rows in the table, dividing the difference in y's by the difference in x's. Taking the first two rows in the table, this gives us @math{\frac{3 - 1}{1 - 0}}, which simplifies to @math{\frac{2}{1}}, for a slope of @math{2}.

Once we have the slope, we can find the y-intercept from any row. Let's take the last row in the table, multiplying the x-value @math{3} by the slope @math{2} to get @math{6}. The y-value is 7, so the y-intercept is @math{7 - 6 = 1}.

For tables like this - where the rows follow a predictable pattern - a *function definition* can be used to summarize the entire Table using just a few symbols! Let's see the function definition, written both as regular function notation and as Pyret code.

[.first-table,cols="1,1",options="header"]
|===
| Function Notation 		| Pyret Code
|@math{f(x) = 2x + 1} 		| `fun f(x): (2 * x) + 1`
|===

As with tables and graphs, a function definition can reveal whether or not it is linear.

@image{images/slope-and-y.png}

[.lesson-point]
SLOPE: simplify, and find the number multiplied by @math{x}.

When we combine like terms, the definition of a linear function will have one term where a number is multiplied by @math{x}. This is the @vocab{slope} of the function - __no computation required!__ NOTE: if the line is perfectly flat the slope will be zero, making the term "invisible". In the example below, a linear function with a slope of zero is shown with and without this term:

[.first-table,cols="1,1",options="header"]
|===
| "Visible" Slope	 		| "Invisible" Slope
|@math{f(x) = 0x + 22}		| @math{f(x) = 22}
|===

[.lesson-point]
Y-INTERCEPT: simplify, and find the number that is standing alone.

A function definition will also have a term consisting of a number by itself. This is the @vocab{y-intercept} - __no computation required!__ Note: if the line crosses the y-axis at zero the y-intercept will be @math{0}, making this term "invisible". In the example below, a linear function with a y-intercept of zero is shown with and without this term:

[first-table,cols="1,1",options="header"]
|===
| "Visible"	y-intercept 	| "Invisible" y-intercept
|@math{f(x) = 3.2x + 0}		| @math{f(x) = 3.2x}
|===

To check our work, we can apply the function to the x-value in each Row in the table, it produces the y-value! Instead of writing endless rows repeating the pattern or drawing an entire graph, we can just declare the pattern itself using the function.

=== Investigate

[.lesson-instruction]
- Complete @online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fc24d7d7768970b95efa813, "Matching Tables and Definitions of Linear Functions (Desmos)"}.
- Complete @opt-printable-exercise{match-symbols-tables.adoc}.
- Complete @opt-printable-exercise{define-functions-tables.adoc}.

[.lesson-instruction]
- Can you tell whether or not a function is linear? Complete @opt-printable-exercise{linear-nonlinear-bust.adoc}.
- Can you find the slope and y-intercept of a functon? Complete @opt-printable-exercise{slope-and-yintercept.adoc}.

=== Synthesize
For Tables that fit a linear pattern like this, a function can be a much shorter way of describing all the Rows! In fact, a one-line function can summarize an _infinite_ number of Rows.

== Not Every Relationship is Linear! @duration{25 minutes}

=== Overview
Students learn how to _build_ Tables with linear functions, and that not all Tables can be generated from a function.

=== Launch
We've provided a special function `make-table` that takes in four arguments:

1) a starting point
2) an ending point
3) the size of the steps between the start and end point
4) a function

It produces a __new table__ with those steps as x-coordinates and the output of the function as the y-coordinates. For example:

```
fun f(x): 2 * x end
# make a table with xs going from 0-10 in steps of 2
make-table(0, 10, 2, f)
```

will produce:
[.pyret-table,cols="^.^1,^.^1",options="header"]
|===
|  x |  y
|  0 |  0
|  2 |  4
|  4 |  8
|  6 | 12
|  8 | 16
| 10 | 20
|===

[.lesson-instruction]
* What is the @vocab{slope} of this function? The @vocab{y-intercept}?
* How could we change this code to make steps of 1, instead of 2?
* How could we change this code to make a table for the integer values between 20 and 200, skipping by 10? 
* How could we change this code to make a table for a different function altogether? 
* Open the Table and Graphs Starter File, and try defining different functions and using them to build Tables.

=== Investigate
[.lesson-instruction]
* @opt-printable-exercise{building-tables-from-symbols.adoc, Match the code to the Table} it will generate.
* Can every Table be built from a function?

Any Table __constructed from a function__ will have points that precisely follow the pattern. But the opposite is not true: plenty of Tables don't follow the pattern of any function! In fact, most Tables in Data Science __don't__ follow an exact pattern! Can you tell which is which?

[.lesson-instruction]
Open @opt-printable-exercise{not-all-tables.adoc}. Which of these tables shows a linear relationship? Which ones don't?

=== Synthesize
Some things in life run like clockwork: 

* A car traveling at 50mph will take two hours to travel 50 miles
* If someone can make a bouquet of flowers every 15 minutes, you know it will take them 45 minutes to make three of them.

For these things, functions perfectly model what happens in reality. But...reality usually isn't quite so neat and tidy!

[.lesson-point]
Real life is messy. That's where Data Science comes in.

Outside of a math book, cars don't _actually_ move at exactly 50mph. Maybe the driver hits the gas at one point, or slows down to avoid a pothole. A worker at a flower shop may take a minute to use the bathroom! Algebraic functions can give us a good _approximation_ for how the world works, but they aren't an exact fit.

We don't use Data Science to find a perfect model for real life. We use it to find the __closest model__ we can to fit the messy data.


== Additional Exercises:

