= Matching Examples and Contracts

++++
<style>
td { height: 20pt; }
p { font-size: 0.9rem;}
div.circleevalsexp, .editbox, .cm-s-scheme {font-size: .75rem;}

td:first-child {border-bottom: 1pt solid gray !important;}

</style>
++++

@do{(define e1
   (code #:multi-line #t
"examples:
  f(100, \"red\") is star(100, \"solid\", \"red\")
  f(200, \"blue\") is star(200, \"solid\", \"blue\")
end"))

(define c1 (code "f :: Number, String -> Image"))

(define e2
   (code #:multi-line #t
"examples:
  f(15) is
    rectangle(15, 15, \"outline\", \"purple\")
  f(6) is
    rectangle(6, 6, \"outline\", \"purple\")
end"))

(define c2 (code "f :: Number -> Image"))

(define e3
   (code #:multi-line #t
"examples:
  f(\"Game Today!\") is
    text(\"Game Today!\", 50, \"red\")
  f(\"Go Team!\") is
    text(\"Go Team!\", 50, \"red\")
  f(\"Exit\") is
    text(\"Exit\", 50, \"red\")
end"))

(define c3 (code "f :: String -> Image"))

(define e4
   (code #:multi-line #t
"examples:
  f(5, \"outline\") is
    star(5, \"outline\", \"yellow\")
  f(15, \"solid\") is
    star(15, \"solid\", \"yellow\")
  f(36, \"outline\") is
    star(36, \"outline\", \"yellow\")
end"))

(define c4 (code "f :: Number, String -> Image"))

(define e5
   (code #:multi-line #t
"examples:
  f(5) is 5 / 2
  f(8) is 8 / 2
  f(900) is 900 / 2
end"))


(define c5 (code "f :: Number -> Number"))
}

_Match_ each set of examples (left) with the contract that best fits it(right).

@vspace{1ex}
[cols="<12a,^2a,1,^1a,.<6a",stripes="none",grid="none",frame="none", options="header"]
|===
|  Examples|  || |Contract
| @show{e5}
| *1* @show{(if *solutions-mode?* "*A*" "")}|| *A* | @show{c5}
@vspace{1ex}
| @show{e2}
| *2* @show{(if *solutions-mode?* "*C*" "")}|| *B* | @show{c3}
@vspace{1ex}
| @show{e1}
| *3* @show{(if *solutions-mode?* "*D*" "")}|| *C* | @show{c2}
@vspace{1ex}
| @show{e3}
| *4* @show{(if *solutions-mode?* "*B*" "")}|| *D* | @show{c4}
@vspace{1ex}
| @show{e4}
| *5* @show{(if *solutions-mode?* "*D*" "")}||	   |
|===
