= Diagramming Function Composition

++++
<style>
#content .listingblock pre {padding: 0;}
#content .autonum::after { content: ')'; }
#content .topTable tr:first-child td * { background-color: #f7f7f8; }
table table { border: none !important; }
table table td { height: 4rem; }
</style>
++++

[.topTable, cols="1,1,1", stripes="none"]
|===
a|
----
f :: Number -> Number
Consumes a number, multiplies by 3 to produce the result
----
a|
----
g :: Number -> Number
Consumes a number, adds six to produce the result
----
a|
----
h :: Number -> Number
Consumes a number, subtracts one to produce the result
----
|
@math{ f(x) = 3x }
|
@math{ g(x) = x + 6 }
|
@math{ h(x) = x - 1 }
|===

For each function composition diagrammed below, translate it into the equivalent Circle of Evaluation for Order of Operations. Then write expressions for _both_ versions of the Circles of Evaluation, and evaluate them for @math{x = 4}. The first one has been completed for you.

@do{
  (define comp1 '(h (g (f x))))
  (define expr1 '(-  (+ (* 3 x) 6) 1))

  (define comp2 '(g (f (h x))))
  (define expr2 '(+ (* 3 (- x 1)) 6))

  (define comp3 '(h (f (g x))))
  (define expr3 '(- (* 3 (+ x 6)) 1))

  (define comp4 '(f (h (g x))))
  (define expr4 '(* 3 (- (+ x 6) 1)))
}

[cols="^1,^2,^3a", options="header", stripes="none"]
|===

| Function Composition
| Order of Operations
| Translate & Evaluate

| @n  @show{(coe comp1)}
|     @show{(coe expr1)}
|
[cols=".^4,.^5"]
!===
! Composition: 			    ! @show{(code comp1)}
! Operations: 			    ! @show{(code expr1)}
! Evaluate for x = 4 	  ! @math{h(g(f(4))) = 17}
!===

| @n  @show{(coe comp2)}
|     @showsoln{(coe expr2) }
|
[cols=".^4,.^5"]
!===
! Composition: 			    ! @showsoln{(code comp2) }
! Operations: 			    ! @showsoln{(code expr2) }
! Evaluate for x = 4 	  ! @ifsoln{@math{g(f(h(4))) = 15}}
!===

| @n  @show{(coe comp3)}
|     @showsoln{(coe expr3) }
|
[cols=".^4,.^5"]
!===
! Composition: 			    ! @showsoln{(code comp3) }
! Operations: 			    ! @showsoln{(code expr3) }
! Evaluate for x = 4 	  ! @ifsoln{@math{h(f(g(4))) = 29}}
!===

| @n  @show{(coe comp4)}
|     @showsoln{(coe expr4) }
|
[cols=".^4,.^5"]
!===
! Composition: 			    ! @showsoln{(code comp4) }
! Operations: 			    ! @showsoln{(code expr4) }
! Evaluate for x = 4 	  ! @ifsoln{@math{f(h(g(4))) = 27}}
!===
|===

