= Function Cards

Print and cut these out, for use with the unplugged "function composition" activity.

[cols="1a,1a", stripes="none"]
|===
|
@show{(contract
  "double" '("Number") "Number"
  "consumes a number, and produces a number that is twice as big"
)}

|
@show{(contract
  "half" '("Number") "Number"
  "consumes a number, and produces a number that is half the input"
)}

|
@show{(contract
  "add5" '("Number") "Number"
  "consumes a number, adds five, and produces the result"
)}

|
@show{(contract
  "sub10" '("Number") "Number"
  "consumes a number, subtracts ten, and produces the result"
)}

|
@show{(contract
  "sqr" '("Number") "Number"
  "consumes a number, squares it, and produces the result"
)}

|
@show{(contract
  "neg" '("Number") "Number"
  "consumes a number, multiplies it by -1, and produces the result"
)}

|
@show{(contract
  "add1" '("Number") "Number"
  "consumes a number, adds one, and produces the result"
)}

|
@show{(contract
  "f" '("Number") "Number"
  "consumes a number, subtracts seven, and produces the result"
)}

|
@show{(contract
  "g" '("Number") "Number"
  "consumes a number, adds six, and produces the result"
)}

|
@show{(contract
  "h" '("Number") "Number"
  "consumes a number, subtracts one, and produces the result"
)}

|===
