= Function Composition -- Your Name

++++
<style>
p .editbox { font-size: 9pt; }
.center {padding: 0;}

.demo td, .demo td>p { padding: 0 !important; margin: 0 !important; }

.contracts td { padding: 0 !important; }
.contracts .editbox { background: none; }
.contracts { background-color: #f7f7f8 !important; }

.grid tr td {padding: 0; }
.grid tr td .paragraph:first-child { padding: 0.5em; }
.grid tr:nth-child(1){ height: calc(6.25in * 0.33); }
.grid tr:nth-child(2){ height: calc(6.25in * 0.66); }

/* Necessary rules to force the code solution to the bottom of the row */
.grid td { position: relative; }
.grid .content .paragraph:nth-child(3) p { position: absolute; bottom: 0; }

div.circleevalsexp .value {
  display:            inline-block;
  margin:             2px 5px;
  vertical-align:     top;
}
table .autonum:after { content: ") "; }

br:first-child { display: none; }
</style>
++++
@do{
	(define name-sexp '(text "X" 30 "red"))
}

You’ll be investigating these functions with your partner:

[.contracts, cols="5a, 4a", frame="none", grid="none"]
|===
| @show{ (contracts
'("text" ("String" "Number" "String") "Image")
'("flip-horizontal" ("Image") "Image")
'("flip-vertical" ("Image") "Image")
)}

| @show{ (contracts
'("frame" ("Image") "Image")
'("above" ("Image" "Image") "Image")
'("beside" ("Image" "Image") "Image")
)}
|===

@n In the editor, write the code to make an image of your name in big letters in a color of your choosing using `text`.  Then draw the Circle of Evaluation and write the Code that will create the image.

*Circle of Evaluation:*

@showsoln{(coe name-sexp) }
@vspace{7ex}

*Code:* @fitb{}{@showsoln{(code name-sexp)}}

Using the "image of your name" described above as the *original*, draw the Circles of Evaluation and write the Code for each exercise below. Test your ideas in the editor to make sure they work.

[.grid, cols="1a,1a",stripes="none"]
|===

| @n The framed "image of your name".

@showsoln{(coe `(frame ,name-sexp)) }

@showsoln{(code `(frame ,name-sexp)) }


| @n The "image of your name" flipped vertically.

@showsoln{(coe `(flip-vertical ,name-sexp)) }

@showsoln{(code `(flip-vertical ,name-sexp)) }




| @n  The "image of your name" above "the image of your name" flipped vertically.

@showsoln{(coe `(above ,name-sexp (flip-vertical ,name-sexp))) }

@showsoln{(code `(above  ,name-sexp (flip-vertical   ,name-sexp))) }


| @n The "image of your name" flipped horizontally beside "the image of your name".

@showsoln{(coe `(beside ,name-sexp (flip-horizontal ,name-sexp)))}

@showsoln{(code `(beside ,name-sexp (flip-horizontal ,name-sexp))) }

|===
