[.landscape]
= More than one way to Compose an Image!

++++
<style>
#content .blankline { margin-bottom: 8px !important; text-align: left; }
</style>
++++

Read through these 4 expressions and try to picture the images they are composing. If you're not sure what they'll look like, type them into the interactions area of your editor and see if you can figure out how the code connects to the image.

@do{
  (define wide-rect '(beside (rectangle 200 100 "solid" "black")(square 100 "solid" "black")))
  (define tall-rect '(scale/xy 1 2 (square 100 "solid" "black")))
  (define big-sq    '(scale 2 (rectangle 100 100 "solid" "black")))
  (define plus      '(above (rectangle 100 50 "solid" "black")
							(above
								(rectangle 200 100 "solid" "black")
								(rectangle 100 50 "solid" "black"))))
}

@ifproglang{pyret}{
```
beside(rectangle(200, 100, "solid", "black"), square(100, "solid", "black"))
scale-xy(1, 2, square(100, "solid", "black"))
scale(2, rectangle(100, 100, "solid", "black"))
above(
	rectangle(100, 50, "solid", "black"),
	above(
		rectangle(200, 100,  "solid", "black"),
		rectangle(100, 50, "solid", "black")))
```
}
@ifproglang{wescheme}{
```
(beside (rectangle 200 100 "solid" "black")(square 100 "solid" "black"))
(scale/xy 1 2(square 100 "solid" "black"))
(scale 2 (rectangle 100 100 "solid" "black"))
(above
	(rectangle 100 50 "solid" "black")
	(above
		(rectangle 200 100 "solid" "black")
		(rectangle 100 50 "solid" "black")))
```
}
For each image below, identify 2 expressions that could be used to compose it. _The bank of expressions at the top of the page includes one possible option for each image._

[cols="^.^1,^.^6,24", stripes="none"]
|===
a| @n
a| @image{../images/vert-rect.png}
a|
* @span{.blankline}{@showsoln{(sexp->code tall-rect)}}
* @span{.blankline}{@showsoln{(sexp->code '(rotate 90 (rectangle 200 100 "solid" "black")))}}

a| @n
a| @image{../images/square.png}
a|
* @span{.blankline}{@showsoln{(sexp->code big-sq)}}
* @span{.blankline}{@showsoln{(sexp->code '(above (rectangle 200 100 "solid" "black")(rectangle 200 100 "solid" "black")))}}

a| @n
a| @image{../images/hor-rect.png}
a|
* @span{.blankline}{@showsoln{(sexp->code wide-rect)}}
* @span{.blankline}{@showsoln{(sexp->code '(scale 0.5 (rectangle 600 200 "solid" "black")))}}

a| ★
a|  @image{../images/black-cross.png}
a|
* @span{.blankline}{@showsoln{(sexp->code plus)}}
* @span{.blankline}{@showsoln{(sexp->code '(overlay (rectangle 100 200 "solid" "black")(rectangle 200 100 "solid" "black")))}}

|===

