= Distribution of a Dataset

== The Ages at the Smith Family Reunion

1, 44, 3, 42, 46, 74, 75, 21, 74, 70, 40, 41, 45

@n Order the Numbers from Least to Greatest: @fitb{}{@ifsoln{1, 3, 21, 40, 41, 42, 44, 45, 46, 70, 74, 74, 75}}

@n 
@fitbruby{5em}{@ifsoln{1}}{Minimum} 	@hspace{1em}
@fitbruby{5em}{@ifsoln{30.5}}{Q1}       @hspace{1em}
@fitbruby{5em}{@ifsoln{44}}{Median} 	@hspace{1em}
@fitbruby{5em}{@ifsoln{72}}{Q3}      	@hspace{1em}
@fitbruby{5em}{@ifsoln{75}}{Maximum}	@hspace{5em}
@fitbruby{10em}{@ifsoln{74}}{Range} @hspace{1em} @fitbruby{10em}{@ifsoln{41.5}}{Interquartile Range (IQR)} 

== The Ages at the Young Family's First-Cousin Gathering

70, 68, 69, 72, 65, 75, 65, 78, 70, 72, 71, 70

@n Order the Numbers from Least to Greatest: @fitb{}{@ifsoln{65, 65, 68, 69, 70, 70, 70, 71, 72, 72, 75, 78}}

@n 
@fitbruby{5em}{@ifsoln{65}}{Minimum} 	@hspace{1em}
@fitbruby{5em}{@ifsoln{68.5}}{Q1}       @hspace{1em}
@fitbruby{5em}{@ifsoln{70}}{Median} 	@hspace{1em}
@fitbruby{5em}{@ifsoln{72}}{Q3}      	@hspace{1em}
@fitbruby{5em}{@ifsoln{78}}{Maximum}	@hspace{5em}
@fitbruby{10em}{@ifsoln{10}}{Range} @hspace{1em} @fitbruby{10em}{@ifsoln{3.5}}{*Interquartile Range (IQR)} 

== Box Plots - Visualizing Shape 

Plot the 5-Number Summaries for each family on the number lines below. Then draw a box around the IQR (connecting Q1 and Q3 with a line for the median dividing it into 2 sections) and draw whiskers to the minimum and maximum values to reveal the box plot.

@n Smith: @ifnotsoln{@image{../images/blank-0to80-num-line-numbered.png}} @ifsoln{@image{../images/smith.png}}

@n Young: @ifnotsoln{@image{../images/blank-0to80-num-line-numbered.png}} @ifsoln{@image{../images/young.png}}

== Compare and Contrast

@n For which family gathering was the median age more typical? How do you know? @fitb{}{}

@fitb{}{@ifsoln{Young. Because the data is more closely clustered around the median.}}

@n What else do you Notice and Wonder about the data from these two family gatherings?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n What advantages were there to making these two box plots on number lines with the same scale? @fitb{}{}

@fitb{}{@ifsoln{Seeing both box plots on the same scale makes them easy to compare.}}

@n What might have been a benefit of making the box plots on number lines with different scales? @fitb{}{}

@fitb{}{@ifsoln{It might be easier to read the precise values for the Young family data if we zoomed in on the range the data actually falls within.}}

