= Matching Dot Plots and Five-Number Summaries

++++
<style>
/* Format matching answers to render with an arrow */
strong+.solution::before{ content: ' → '; }
</style>
++++
Match each dot plot on the left to the corresponding five-number summary on the right. You might find it useful to label the five-number summaries before you begin matching (see question 1 for an example).

[.FillVerticalSpace, cols="^.^15a,^.^3a,5a,^.^1a,<.^5a", options="header", stripes="none", grid="none", frame="none"]
|===
| Dot Plot
|||
| 5-Number Summary

| @image{../images/dp1-soln.png}
|*@n* @ifsoln-match{C}  ||*A*
| Min: 2 +
Q1: 4 +
Median: 7 +
Q3: 9 +
Max: 10

| 
@ifnotsoln{@image{../images/dp2.png }}
@ifsoln{@image{../images/dp2-soln.png}}
|*@n* @ifsoln-match{A}  ||*B*
| Min: 2 +
Q1: 4 +
Median: 6 +
Q3: 8 +
Max: 10

| 
@ifnotsoln{@image{../images/dp3.png }}
@ifsoln{@image{../images/dp3-soln.png }}
|*@n* @ifsoln-match{F}  ||*C*
| Min: 2 +
Q1: 3 +
Median: 7 +
Q3: 9 +
Max: 10

| 
@ifnotsoln{@image{../images/dp4.png }}
@ifsoln{@image{../images/dp4-soln.png }}
|*@n* @ifsoln-match{B} ||*D*
| Min: 2 +
Q1: 4 +
Median: 6 +
Q3: 9 +
Max: 10

| 
@ifnotsoln{@image{../images/dp5.png }}
@ifsoln{@image{../images/dp5-soln.png }}
|*@n* @ifsoln-match{D}  ||*E*
| Min: 2 +
Q1: 5 +
Median: 6 +
Q3: 7 +
Max: 10

| 
@ifnotsoln{@image{../images/dp6.png }}
@ifsoln{@image{../images/dp6-soln.png }}
|*@n* @ifsoln-match{E}  ||*F*
| Min: 2 +
Q1: 4 +
Median: 7 +
Q3: 8 +
Max: 10

| 
@ifnotsoln{@image{../images/dp7.png }}
@ifsoln{@image{../images/dp7-soln.png }}
|*@n* @ifsoln-match{G}  ||*G*
| Min: 2 +
Q1: 3 +
Median: 5 +
Q3: 8.5 +
Max: 10

| 
@ifnotsoln{@image{../images/dp8.png }}
@ifsoln{@image{../images/dp8-soln.png }}
|*@n* @ifsoln-match{H}  ||*H*
| Min: 2 +
Q1: 3 +
Median: 5 +
Q3: 8 +
Max: 10
|===