= Age vs. Height Explore

++++
<style>
.lr-table td { padding: 0 2ex; }
.lr-table td p { margin: 0; }
</style>
++++

Open the @starter-file{height} and click Run.

@n Take a look at the code in the Definitions Area. What do you notice? What do you wonder?

@span{.blankline}{@ifsoln{_Answers will vary_}}
@span{.blankline}{}
@span{.blankline}{}

@n Build `image-scatter-plot(h-table, "age", "height", dot)`.  Try to visualize the line of best fit for just the blue dots. Then try to visualize the line of best fit for just the red stars. How do you think they would compare? Which line do you think would be steeper?

@span{.blankline}{@ifsoln{_Answers will vary_}}
@span{.blankline}{}
@span{.blankline}{}


@n Make three linear regression plots comparing `age` and `height`, and record the results for each in the table below:

- The whole population: `lr-plot(h-table, "gender-id", "age", "height")`
- Females only: `lr-plot(h-table.filter(is-f), "gender-id", "age", "height")`
- Males only: `lr-plot(h-table.filter(is-m), "gender-id", "age", "height")`


[.lr-table]
[cols="^.^1,^.^1,^.^1,^.^1", options="header"]
|===
| Sample 	| rate of change 		| y-intercept			| R value
| All		| @ifsoln{_48 in_}		| @ifsoln{_65 in_} 		| @ifsoln{_48 in_}
| Females	| @ifsoln{_48 in_}		| @ifsoln{_65 in_} 		| @ifsoln{_48 in_}
| Males		| @ifsoln{_48 in_}		| @ifsoln{_65 in_} 		| @ifsoln{_48 in_}
|=== 


@n Now build `lr-plot(h-table.filter(is-m), "gender-id", "age", "height")`.

[cols="^1,^1,^1", options="header"]
|===
| rate of change 		| y-intercept			| R value
| @ifsoln{_48 in_}		| @ifsoln{_65 in_} 		| @ifsoln{_48 in_}
@vspace{2ex}
|=== 

@n What makes it difficult to compare these two plots visually?

@span{.blankline}{ @ifsoln{_The axes are labelled differently_} }
@span{.blankline}{}

Rebuild `lr-plot(h-table.filter(is-f), "gender-id", "age", "height")`, adjust the window of the interactive plot so that:

[cols="^1,^1,^1,^1" options="header"]
|===
| x-min: 	| x-max:	| y-min:	| y-max:
| 6.5		| 12.5 		| 	40		| 70
|===
and click `Redraw`.

Do the same for `lr-plot(h-table.filter(is-m), "gender-id", "age", "height")`.

@vspace{1ex}

@n How do the two plots compare now that their windows match?

@span{.blankline}{ @ifsoln{_Answers will vary_} }
@span{.blankline}{}
@span{.blankline}{}
