= Drawing Predictors

++++
<style>
img { width: 230px; }
td { margin: 0; padding: 0; }
.fitb { padding-top: 0 !important; }
</style>
++++

For each of the scatter plots below, draw a *predictor line* that seems like the best fit. Describe the correlation in terms of Direction and Strength, then estimate the @math{r}-value as being close to -1, -0.5, 0, +0.5, or +1.

[.FillVerticalSpace, cols="^.^1a,^.^10a,.^10a",stripes="none", frame="none"]
|===

| *A*
| @image{../images/drawing-predictors-A.png, drawing predictors A}
|
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Direction*: 	! Positive  ! Negative 	! None
! *Strength*:  	! Strong 	! Weak 		!
! *r*: 			! @fitb{}{}	!			!
!===

| *B*
| @image{../images/drawing-predictors-B.png, drawing predictors B}
|
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Direction*: 	! Positive  ! Negative 	! None
! *Strength*:  	! Strong 	! Weak 		!
! *r*: 			! @fitb{}{} !			!
!===

| *C*
| @image{../images/drawing-predictors-C.png, drawing predictors C}
|
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Direction*: 	! Positive  ! Negative 	! None
! *Strength*:  	! Strong 	! Weak 		!
! *r*: 			! @fitb{}{}	!			!
!===

| *D*
| @image{../images/drawing-predictors-D.png, drawing predictors D}
|
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Direction*: 	! Positive  ! Negative 	! None
! *Strength*:  	! Strong 	! Weak 		!
! *r*: 			! @fitb{}{}	!			!
!===

|===
