= Drawing Predictors

++++
<style>
img { width: 230px; }
td { margin: 0; padding: 0; }
.fitb { padding-top: 0 !important; }
</style>
++++

*Remember what we learned about r-values...*
[cols="1,1,1,1,1"]
|===
| r = -1 | r = -0.5 | r = 0 | r = 0.5 | r = 1
| perfect negative correlation | moderate negative association | no correlation | moderate positive association | perfect positive correlation
|===

@vspace{1ex}

For each of the scatter plots below, draw a *predictor line* that seems like the best fit. Describe the correlation in terms of Direction and Strength, then estimate the @math{r}-value as being close to -1, -0.5, 0, +0.5, or +1.

@vspace{1ex}

[.FillVerticalSpace, cols="^.^1a,^.^10a,.^10a",stripes="none", frame="none"]
|===

| *A*
|@ifnotsoln{@image{../images/drawing-predictors-A.png, drawing predictors A}}
@ifsoln{@image{../images/drawing-predictors-A-soln.png, drawing predictors A}}
|
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Direction*: 	! @ifnotsoln{Positive} @ifsoln{*POSITIVE*}  ! Negative 	! None
! *Strength*:  	! @ifnotsoln{Strong} @ifsoln{*STRONG*} 		! Weak 		!
! *r*: 			! @fitb{}{@ifsoln{almost 1}}				!			!
!===

| *B*
| @ifnotsoln{@image{../images/drawing-predictors-B.png, drawing predictors B}}
@ifsoln{@image{../images/drawing-predictors-B-soln.png, drawing predictors B}}
|
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Direction*: 	! @ifnotsoln{Positive} @ifsoln{*POSITIVE*}  ! Negative 	! None
! *Strength*:  	! @ifnotsoln{Strong} @ifsoln{*STRONG*} 	 	! Weak 		!
! *r*: 			! @fitb{}{@ifsoln{~0.6}} 					!			!
!===

| *C*
| @ifnotsoln{@image{../images/drawing-predictors-C.png, drawing predictors C}}
@ifsoln{@image{../images/drawing-predictors-C-soln.png, drawing predictors C}}
|
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Direction*: 	! @ifnotsoln{Positive} @ifsoln{*POSITIVE*}  ! Negative 	! None
! *Strength*:  	! @ifnotsoln{Strong} @ifsoln{*STRONG*} 		! Weak 		!
! *r*: 			! @fitb{}{@ifsoln{~0.6}}					!			!
!===

| *D*
| @ifnotsoln{@image{../images/drawing-predictors-D.png, drawing predictors D}}
@ifsoln{@image{../images/drawing-predictors-D-soln.png, drawing predictors D}}
|
[cols="1a,1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! *Direction*: 	! Positive  ! @ifnotsoln{Negative} @ifsoln{*NEGATIVE*} 	! None
! *Strength*:  	! @ifnotsoln{Strong} @ifsoln{*STRONG*} 	 	! Weak 		!
! *r*: 			! @fitb{}{@ifsoln{~-0.7}					!			!
!===

|===
