= Grading Predictors

Below are the scatter plots for datasets A-D, with two different predictor lines drawn
on top. For plots A-D:


1. Circle the plot with the line that fits better
2. Give the circled plot your best guess for what r is closest to: −1, −0.5, +0.5, or +1.


[cols=".^1a,8a,8a,.^8a", frame="none"]
|===
|*A*
| @ifnotsoln{@centered-image{../images/grading-predictors-a-1.png, 200}}
 @ifsoln{@centered-image{../images/grading-predictors-a-1-soln.png, 200}}
| @centered-image{../images/grading-predictors-a-2.png, 200}
| 
[.big]
----
r= −1   @ifnotsoln{−0.5} @ifsoln{*−0.5*}   +0.5   +1
----

|*B*
| @ifnotsoln{@centered-image{../images/grading-predictors-b-1.png, 200}}
@ifsoln{@centered-image{../images/grading-predictors-b-1-soln.png, 200}}
| @centered-image{../images/grading-predictors-b-2.png, 200}
| 
[.big]
----
r= −1   −0.5   +0.5   @ifnotsoln{+1} @ifsoln{*+1*}
----

|*C*
| @centered-image{../images/grading-predictors-c-1.png, 200}
| @ifnotsoln{@centered-image{../images/grading-predictors-c-2.png, 200}}
@ifsoln{@centered-image{../images/grading-predictors-c-2-soln.png, 200}}
| 
[.big]
----
r= −1   −0.5   @ifnotsoln{+0.5} @ifsoln{*+0.5*}   +1
----

|*D*
| @ifnotsoln{@centered-image{../images/grading-predictors-d-1.png, 200}}
@ifsoln{@centered-image{../images/grading-predictors-d-1-soln.png, 200}}
| @centered-image{../images/grading-predictors-d-2.png, 200}
| 
[.big]
----
r= −1   −0.5   @ifnotsoln{+0.5} @ifsoln{*+0.5*}   +1
----

|===
