= Data Cycle: Regression Analysis (Example)

[cols="^.^1, ^.^3, .^20", frame="none", grid="none", stripes="none"]
|===
| @n
| @image{../images/AskQuestions.png, "Ask Questions icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ What question do you have? @fitb{20em}{How much does Age determine Adoption time for cats?}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ What type of question is this? (circle one) @hspace{1.5em} _Lookup_ @hspace{1.5em} _Arithmetic_ @hspace{1.5em} @ifsoln{*Statistical*} @ifnotsoln{_Statistical_}

| @n
| @image{../images/ConsiderData.png, "Consider Data icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ Rows: @fitbruby{30em}{_cats at the shelter_}{Just the cats, fixed rabbits, etc.}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ Column(s): @fitbruby{28em}{name, age, and weeks}{age, weight-in-kilograms, weeks, etc.}

| @n
| @image{../images/AnalyzeData.png, "Analyze Data icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
+a.+ What table or display will you create? _(🌟Then go create it!🌟)_

@fitbruby{95%}{lr-plot of weeks v. age for cats}{box-plot of pounds, pie-chart of species, table of dogs sorted by age, etc.}

+b.+ @fitbruby{95%}{lr-plot(animals-table.filter(is-cat), "name", "age", "weeks")}{Write the Pyret code here. Use the line below if needed!}

@fitb{99%}{}

| @n
| @image{../images/InterpretData.png, "Interpret icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
+a.+ What did it tell you? What can you infer?

@fitb{95%}{The slope is positive (0.23) and R=0.566, so there is a moderate relationship }

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
+b.+ What new question(s) does this raise?

@fitb{95%}{Is the relationship different for other animals?}

@fitb{95%}{Is the relationship different for fixed v. unfixed cats?}
|===

_Write your Data Story below:_

@n I performed a linear regression on a sample of @fitbruby{60ex}{_cats from the shelter_}{dataset or subset} and found @fitbruby{80ex}{_a moderate (r=0.566), positive_}{a weak/strong/moderate (R=...), positive/negative} correlation between @fitbruby{60ex}{_age of the cats (in years)_}{[x-axis]} and @fitbruby{60ex}{_number of weeks to adoption_}{[y-axis]}. I would predict that a 1 @fitbruby{20ex}{_year_}{[x-axis units]} increase in @fitbruby{30ex}{_age_}{[x-axis]} is associated with a @fitbruby{30ex}{_0.23 week_}{[slope, y-units]} @fitbruby{30ex}{_increase_}{[increase/decrease]} in @fitbruby{30ex}{_adoption time_}{[y-axis]}.
