= Which Questions Make Sense to Ask?

@span{.center}{@image{../images/age-v-height.png, lr-plot-age-v-height, 500}}

@n About how many inches are kids in this dataset expected to grow per year? @fitb{5em}

@vspace{1ex}

@n At that rate, if a child were 45" tall at age eight, how tall would you expect them to be at age 12? @fitb{5em}

@vspace{1ex}

@n At that rate, if a ten-year-old were 55" tall at age 11, how tall would you expect them to have been at age 9? @fitb{5em}

@vspace{1ex}

@n Using the equation, how tall would you expect a seven-year-old child to be? @fitb{5em}

@vspace{5ex}

@n How many of the seven-year-olds are actually that height? @fitb{5em}

@vspace{1ex}

@n Use the equation, determine the expected height of someone who is...

|===
| 7.5 years old 	| 13 years old		| 6 years old		| newborn 		| 90 years old
| @vspace{10ex}		|  					| 					|  				|
|===

@n Which ages does it make the most sense to determine using the linear regression equation? Why?

@vspace{6ex}

@n Which ages does it make the least sense to determine using the linear regression equation? Why?

@vspace{6ex}
