= Which Questions Make Sense to Ask?

@span{.center}{@image{../images/age-v-height.png, "A linear regression plot, showing height as a function of age", 500}}

@n About how many inches are kids in this dataset expected to grow per year? @fitb{5em}{@ifsoln{_3 inches_}}

@vspace{1ex}

@n At that rate, if a child were 45" tall at age eight, how tall would you expect them to be at age twelve? @fitb{5em}{@ifsoln{_57 inches_}}

@vspace{1ex}

@n At that rate, if a ten-year-old were 55" tall at age 11, how tall would you expect them to have been at age 9? @fitb{5em}{@ifsoln{_49 inches_}}

@vspace{1ex}

@n Using the equation, how tall would you expect a seven-year-old child to be? @fitb{5em}{@ifsoln{_46.6 inches_}}

@vspace{5ex}

@n How many of the seven-year-olds in this sample are actually that height? @fitb{5em}{@ifsoln{_zero!_}}

@vspace{1ex}

@n Use the equation, determine the expected height of someone who is...

[cols="^1,^1,^1,^1,^1", options="header"]
|===
| 7.5 years old 		| 13 years old			| 6 years old				| newborn 					| 90 years old
| @ifsoln{_48 in_}
@vspace{3ex}			| @ifsoln{_65 in_} 	| 	@ifsoln{_48 in_}	| @ifsoln{_43.5 in_}	| @ifsoln{_301 in_}
|===

@n For which ages is this predictor function likely to be the *most* accurate? Why?

@ifsoln{_The ages that fall within the range of the dataset._ Note: this function might be incredibly accurate for _this population_, but that doesn't mean it's accurate for other populations! Suppose this sample was drawn from students at a basketball training camp. A highly accurate predictor for the heights of those students might be terrible when used with students at a gymnastics camp.}

@vspace{4ex}

@n For which ages is this predictor function likely to be the *least* accurate? Why?

@ifsoln{_The regression might still work for extrapolating the height of a 6-year-old or a 13-year-old, since they are just beyond the range of the dataset, but it makes no sense to use this equation to figure out the height of a 90-year-old or babies, because humans don't grow at a constant rate for their entire life!_}

@vspace{4ex}
