= Order of Operations

++++
<style>
.embedded {min-width: 550px; width: 80%; margin: 0px auto;}
</style>
++++

@lesson-description{Students learn to model arithmetic expressions with a visual tool for order of operations, known as "Circles of Evaluation".}

[@lesson-intro-table]
|===
@prereqs-stds{alg-coordinates}
| Lesson Goals
| Students will be able to:

* Model an arithmetic expression using @vocab{Circles of Evaluation}.
* Translate Circles of Evaluation into code.

| Student-facing Goals
|
* I can write Circles of Evaluation for a given arithmetic @vocab{expression}.
* I can translate a Circle of Evaluation model into code.
* I can use numbers and operations in a programming environment.

| Materials
|[.materials-links]

@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/1f2sE20VEHYZ4IYOF43DCqd5wpvoRV6uUUl2tGa4KO9I/edit?usp=sharing, Lesson Slides}
}
@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1RgWEdZAx9_FLmrIPAjStRAN5wdyImAJh929d8t2U6NU/edit?usp=sharing, Lesson Slides}
}


@material-links

| Preparation
|
* Make sure all materials have been gathered

| Supplemental Resources
|
@ifproglang{wescheme}{
*  @link{https://quizizz.com/admin/quiz/5d9919a36c6f17001a9dc796, "Coordinates, Circles of Evaluation, and Code - Quizizz"}
}
@ifproglang{pyret}{
*  @link{https://quizizz.com/admin/quiz/5d6973a4536e0b001a736010, Order of Operations Review #1 - Quizizz}
}
@ifproglang{pyret}{
* @link{https://quizizz.com/admin/quiz/5d69796bfe45c5001d3d48ed, Order of Operations Review #2 - Quizizz}
}

| Key Points For The Facilitator
|
* Error messages are the computer trying to give us a clue that something is wrong.  Model reacting to @vocab{error message}s with interest to demonstrate to students that the messages are a helpful tool.
* After the first few exercises in creating Circles of Evaluation, ask students whether they create them from the 'inside-out' (drawing the inner circles first) or from the 'outside-in.'  After they've given their responses, have them try using the OTHER way!
* Up until now, we didn't have a visual spatial model for explaining the order of operations. Ask students to compare Circles of Evaluation to previous methods they've learned (PEMDAS, GEMAS, etc)
* For a memory hook, model the "bug that crawls through the circle" explanation.
* Students may benefit from using multiple colors to distinguish between the different smaller expressions and parentheses.
|===

[.old-materials]
Click here to see the @link{https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/units/unit1/index.html, prior unit-based version}.

== Numbers @duration{10 minutes}

=== Overview
Students experiment with the Editor, exploring the different kinds of numbers and how they behave in this programming language.

=== Launch

@ifproglang{wescheme}{ 
Students should open @link{https://www.wescheme.org, WeScheme} in their browser, and click "Log In". This will ask them to log in with a valid Google account (Gmail, Google Classroom, YouTube, etc.), and then show them the "My Programs" page. This page is empty - they don't have any programs yet! Have them click "Start a New Program".
}

@ifproglang{pyret}{
Students should open @link{https://code.Pyret.org, code.pyret.org (CPO) } in their browser, and click "Sign In". This will ask them to log in with a valid Google account (Gmail, Google Classroom, YouTube, etc.), and then show them the "Programs" page. This page is empty - they don't have any programs yet! Have them click "Open Editor".
}

@span{.right}{@image{images/editor.png, "Our Editing Environment", 300, ""}}
This screen is called the @vocab{Editor}, and it looks something like the diagram you see here. There are a few buttons at the top, but most of the screen is taken up by two large boxes: the @vocab{Definitions Area} on the left and the @vocab{Interactions Area} on the right.

The @vocab{Definitions Area} is where programmers define values and functions that they want to keep, while the @vocab{Interactions Area} allows them to experiment with those values and functions. This is like writing function definitions on a blackboard, and having students use those functions to compute answers on scrap paper.

[.lesson-point]
For now, we will only be writing programs in the *Interactions Area* on the right.

@span{.clear}{}

=== Investigate

Math is a language, just like English, Spanish, or any other language. We use nouns, like "bread", "tomato", "mustard" and "cheese" to describe physical objects. Math has @vocab{values}, like the numbers 1, 2 or 3, to describe quantities.

[.lesson-instruction]
--
Try typing the number `42` on the right, and then hitting "Enter" or "Return". What did this number evaluate to? (Hint: Numbers should evaluate to themselves - if you didn't get back the same number you put in, something is very wrong!)

If working in pairs, make sure you each take a turn at the keyboard. Suggestions:

- How _large_ of a number can you enter?
- How _small_ of a number can you enter?
- What happens if you type two numbers on the same line?
- Do fractions work? Decimals?
- Do negative numbers work?

Remember, we're only trying _numbers_ for now, not operations like @math{3 - 6}, @math{\sqrt{16}} or @math{4^2}
--

[.notice-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Notice & Wonder}

In pairs, students will each try entering a variety of numbers in the Interactions Area, hitting "Enter" each time to see what the computer does. Then they will write down what they Notice and Wonder on @workbook-link{pages/NoticeAndWonder.adoc}.
|===

- What did you Notice? What do you Wonder?
- Did you get any error messages? If so, read it carefully - what do you think it means?

=== Student Misconceptions
@ifproglang{pyret}{
- Students who write decimals as `.5` (without the leading zero) may get an error message, causing them to think that Pyret doesn't have decimals! They just need to add the zero.
}
- Students who try division by writing `3/2` and get an answer may falsely assume that they've performed division. In fact, what they've done is entered a _rational number_. ("Two-thirds" is _equivalent_ to the expression  "two divided by three", but only insofar as they result in the same value. "2" is equivelent to expression "10 minus 8", for the same reason!)
- Rational numbers can be converted back and forth between fraction and decimal forms by clicking on them.

=== Synthesize
Our programming language knows about many types of numbers, and they behave pretty much the way they do in math. Our Editor is also pretty smart, and can automatically switch between showing a rational number as a fraction or a decimal, just by clicking on it!

== Order of Operations @duration{30 minutes}

=== Overview
Students are given a challenging expression that exposes common misconceptions about order of operations. The goal is to demonstrate that a brittle, fixed notion of order of operations is _not good enough_, and lead students to a deeper understanding of Order of Operations as a grammatical device. The Circles of Evaluation are introduced as "sentence diagramming for arithmetic".

=== Launch

Humans also use verbs like "throw", "run", "build" and "jump" to describe operations on these nouns. Mathematics has @vocab{functions} - or "operations" - like addition and subtraction, which are operations performed on values. Just as you can "*spread* _mustard_ on _bread_", a person can also "*add* _four_ and _five_".

A mathematical expression is like a sentence: it’s an instruction for doing something. The expression 4+5 tells us to add 4 and 5. To evaluate an expression, we follow the instructions in the expression. The expression @math{4 + 5} evaluates to 9.

@span{.right}{@image{images/pemdas.png, "", 300, ""}}
Sometimes, we need multiple expressions to accomplish a task, and it will matter in which order they come. For exmple, if you were to write instructions for making a sandwich, it would matter very much which instruction came first: melting the cheese, slicing the bread, spreading the mustard, etc. The order of functions matters in mathematics, too.

Mathematicians didn’t always agree on the order of operations, but now we have a common set of rules for how to evaluate expressions. The pyramid on the right summarizes the order. When evaluating an expression, we begin by applying the operations written at the top of the pyramid (multiplication and division). Only after we have completed all of those operations can we move down to the lower level. If both operations are present (as in @math{4 + 2 − 1}), we read the expression from left to right, applying the operations in the order in which they appear.

@span{.clear}{}

[.lesson-instruction]
But this set of rules is brittle, and doesn't always make it clear what we need to do. Check out the expression below. What do you think the answer is?  This math problem went viral on social media recently, with math teachers arguing about what the answer was! Why might they disagree on the solution?

++++
<style>
.centered-image.big, .centered-image.big p {margin-top: 0px; padding-top: 0px;}
.big .MathJax {font-size: 6em; color: black;}
</style>
++++
[.centered-image.big]
@math{6 \div 2(1 + 2)}

Order of Operations mneumonic devices like PEMDAS, GEMDAS, etc focus on how to get the answer. What we need is a __better way to read math__.

Instead of a rule for computing answers, let's start by diagramming the math itself! We can _draw the structure_ of this grammer in mathematics using something called the *Circles of Evaluation*. The rules are simple:

[.lesson-point]
1) Every Circle must have one - and only one! - function, written at the top

That means that Numbers (e.g. - `3`, `-29`, `77.01`...) are still written by themselves. It's only when we want to _do something_ like add, subtract, etc. that we need to draw a Circle.

[.lesson-point]
2) The inputs to the function are written left-to-right, in the middle of the Circle.

If we want to draw the Circle of Evaluation for @math{6 \div 3}, the division function (`/`) is written at the top, with the `6` on the left and the `3` on the right.

[.centered-image]
@show{(sexp->coe '(/ 6 3))}
@span{.clear}{}

What if we want to use multiple functions? How would we draw the Circle of Evaluation for @math{6 \div (1 + 2)}? Drawing the Circle of Evaluation for the @math{1 + 2} is easy. But how do divide 6 by that circle?

*Circles can contain other Circles*

We basically replace the `3` from our earlier Circle of Evaluation with _another_ Circle, which adds 1 and 2!

[.centered-image]
@show{(sexp->coe '(/ 6 (+ 1 2)))}
@span{.clear}{}

[.lesson-instruction]
If you'd like to have students practice connecting expressions with Circles of Evaluation before you move on to talking about code, turn to @workbook-link{pages/complete-coe-from-arith2.adoc}, @workbook-link{pages/arith-to-coe3.adoc}, and/or @workbook-link{pages/match-arith-coe1.adoc} in the workbook.

*Circles of Evaluation _help us write code_*

When converting a Circle of Evaluation to code, it's useful to imagine a spider crawling through the circle from the left and exiting on the right. The first thing the spider does is cross over a curved line (an open parenthesis!), then visit the operation - also called the _function_ - at the top. After that, she crawls from left to right, visiting each of the inputs to the function. Finally, she has to leave the circle by crossing another curved line (a close parenthesis).

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|*Expression*			| &rarr; | @show{(sexp->math `(+ 3 8)) }
|*Circle of Evaluation*	| &rarr; | @show{(sexp->coe  `(+ 3 8)) }
|*Code*					| &rarr; | @show{(sexp->code `(+ 3 8)) }
|===

@ifproglang{wescheme}{
All of the expressions that follow the function name are called arguments to the function. The following diagram summarizes the shape of an expression that uses a function.
@span{.center}{@image{images/wescheme-code-diagram.png, "Diagram of a WeScheme Expression", 400}} 
}

Practice creating Circles of Evaluation using the common operators (`+`, `-`, `*`, `/`).

- Do spaces matter when typing in functions?
- Does the order of the numbers matter in the functions? Which functions?
- What do the error messages tell us?
- What connections do you see between the expression, circle, and code?

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|*Expression*			| &rarr; | @show{(sexp->math `(* 2 (+ 3 8))) }
|*Circle of Evaluation*	| &rarr; | @show{(sexp->coe  `(* 2 (+ 3 8))) }
|*Code*					| &rarr; | @show{(sexp->code `(* 2 (+ 3 8))) }
|===

@ifproglang{wescheme}{
- Why are there two closing parentheses in a row, at the end of the code?
- If an expression has three sets of parentheses, how many Circles of Evaluation do you expect to need?
}

*Circles of Evaluation _help us get the correct answer_*

Aside from helping us catch mistakes before they happen, Circles of Evaluation are also a useful way to think about _transformation_ in mathematics. For example, you may have heard that "any subtraction can be transformed to a negative addition." For example, @math{1 - 2} can be transformed to @math{1 + (-2)}.

Suppose someone tells you that @math{1 - 2 * 3 + 4} can be rewritten as @math{1 + (-2) * 3 + 4}. These two expressions will definitely give us the same answer, but this transformation is actually _incorrect_! It doesn't use the negative addition rule at all! *Take a moment to think: what's the problem?*

We can use the Circles of Evaluation to figure it out!

The first Circle is just the original expression. The multiplication happens first, so let's see how multiplication changes this circle:
[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(sexp->coe '(+ (- 1 (* 2 3)) 4))}
| __multiplication__ &rarr;
| @show{(sexp->coe '(+ (- 1 6) 4))}
|===

As you can see, replacing the subtraction with a negative addition happens to the _result_ of the multiplication. We can't actually change the `2` into a `-2`, because it isn't actually being subtracted from `1`!

Sure, we got the same answer - but that doesn't mean the way we got it was correct. If all that mattered was getting the right answer, we could just as easily have replaced the whole expression with @math{5 - 6}. And that is _definitely_ not a correct transformation!

Any time you make a transformation in math (replacing @math{10 - 2} with @math{8} because of subtraction, or replacing @math{2 + 6} with @math{6 + 2} because of commutativity), you need to make sure the transformation is _correct_. The Circles of Evaluation help us see these transformation _visually_, rather than forcing us to keep them in our heads.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Circles of Evaluation}

The Circles of Evaluation are a critical pedagogical tool in this course. They place the focus on the _structure_ of mathematical expressions, as a means of combating the harmful student belief that the only thing that matters is the _answer_. They can be used to diagram arithmetic sentences to expose common misconceptions about Order of Operations, and make an excellent scaffold for tracing mistakes when a student applies the Order of Operations incorrectly. They are also a bridge representation, which naturally connects to function composition and converting arithmetic into code.
|===

=== Investigate

[.lesson-instruction]
- Students complete @workbook-link{pages/translate-arithmetic-to-circles-and-code.adoc} page in their workbook. They should __draw all of the Circles first__ and check their work, before converting to code.
- Students complete the @workbook-link{pages/translate-coe-to-code.adoc}.
- If time allows, partners should take turns entering the code into the editor.
- - Additional workook pages for translating Circles of Evaluation to code include @workbook-link{pages/complete-code-from-coe1.adoc}, @workbook-link{pages/match-coe-to-code.adoc}, and @workbook-link{translate-arithmetic-to-circles-and-code.adoc}

The Circles of Evaluation are a great way to visualize _other_ functions you already know, such as square and square root!

@ifproglang{pyret}{
*Note:* In Pyret, we treat _operators_ like `+`, `-`, `*`, and `/` differently - they are written in between their inputs, just like in math. We also use letters instead of symbols for function names, so taking the square root is written as `num-sqrt` and squaring is written as `num-sqr`.
}

@ifproglang{wescheme}{
*Note:* In WeScheme, we use `sqrt` as the name of the square root function, and `sqr` as the function that squares its input.
}

[.lesson-instruction]
- Students complete @workbook-link{pages/translate-coe-to-code-w-sqrts.adoc } with their partners and test their code in the editor.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Strategies For English Language Learners}

MLR 7 - Compare and Connect: Gather students' graphic organizers to highlight and analyze a few of them as a class, asking students to compare and connect different representations.
|===

=== Synthesis
Have students share back what they learned from the Circles of Evaluation. You may want to assign traditional Order of Operations problems from your math book, but instead of asking them simply to compute the answer - or even list the steps - have them _draw the circle_.

== Additional Exercises

* @exercise-link{pages/complete-coe-from-arith1.adoc} 

* @exercise-link{pages/arith-to-coe1.adoc} 

* @exercise-link{pages/arith-to-coe2.adoc} 

* @exercise-link{pages/coe-to-arith1.adoc} 

* @exercise-link{pages/coe-to-arith2.adoc} 

* @exercise-link{pages/coe-to-math-answer1.adoc}

* @exercise-link{pages/coe-to-math-answer2.adoc} 

* @exercise-link{pages/coe-to-code1.adoc} 

* @exercise-link{pages/coe-to-code2.adoc} 