[.beta]
= Exploring Periodic Models
++++
<style>
table.rideData tr * { padding: 0 !important; margin: 2px !important; }
table.rideData { width: 70%; margin: auto; }
</style>
++++
@description{Students investigate periodic relationships, first by deciphering the patterns in a dataset with perfect sinusoidal behavior and then by looking data about Carbon Dioxide, using an inquiry-based model involving hypothesizing, experimental and computational modeling, and sense-making. }

@lesson-prereqs{exploring-quadratic-models}

@keywords{periodic, period, amplitude, frequency}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Read and interpret real-world data, presented in a scatter plot
* Recognize periodic behavior in tables and graphs
* Model periodic relationships using functions


| Student-facing Lesson Goals
|

* Let's use Pyret to model periodic relationships in data

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

|===

== Looking for Patterns @duration{45 minutes}

=== Overview
Students are introduced to the notion of @vocab{periodic relationships}: related variables where the response variable repeats the same pattern over and over as the explanatory variable increases.

=== Launch

@right{@image{images/state-fair.png, 200}} Your physics teacher comes back from a trip to the state fair, and keeps raving about some amazing ride they took. The class keeps asking them for details: was it a Rollercoaster? Bumper cars? Merry-Go-Round? Being a teacher, of course they decide to turn your casual curiosity into a _learning experience_, and share some data they recorded from their smart watch:

[.rideData, cols="^1a,^1a", options="header"]
|===
| `time` (minutes)  | `altitude` (feet)
|  0				|   5.0
|  5				|  55.0
| 10				| 154.9
| 15				| 205.0
| 20				| 155.2
| 25				|  55.2
| 30				|   5.0
| 35				|  54.7
| 40				| 154.6
| 45				| 205.0
| 50				| 155.5
| 55				|  55.5
| 60				|   5.0
|===

=== Investigate

@lesson-instruction{
Working in pairs or groups, complete questions 1-4 on @printable-exercise{exploring-periodic.adoc}.
}

@QandA{
@Q{What are some of your Noticings, and what did they make you Wonder?}
@A{(Solicit a range of student responses)}
@Q{What kind of ride do you think they were on?}
@A{Answers will vary. Write them all down on the board!}
@Q{What about this data supports your theory?}
}

@lesson-instruction{
Complete the remaining questions on @printable-exercise{exploring-periodic.adoc}.
}

=== Synthesize

This worksheet had you create a *new type of data display*, called a @vocab{line graph}.

@lesson-point{Line graphs are often used instead of scatter plots when the explanatory variable is _time_.}

[cols="^1a, ^1a"]
|===
| @image{images/rides-scatter-plot.png} | @image{images/rides-combined-plot.png}
|===

@slidebreak

In this example, we know the ferris wheel keeps turning, generating data "in between" the times represented in our scatter plot. Connecting those dots with the line gives us an approximation of what data is missing between those times, and helps us see the shape of the relationship.

@ifslide{
[cols="^1a, ^1a"]
|===
| @image{images/rides-scatter-plot.png} | @image{images/rides-combined-plot.png}
|===
}

@QandA{
@Q{Was it helpful to switch from a scatter plot to a line graph? Why or why not?}
@A{Yes - it was difficult to see the pattern until we added the line!}
@Q{Is there a relationship between `time` and `altitude`? Why or why not?}
@A{(Solicit a range of student responses, guiding the class to there being a relationship)}
@Q{What kind of ride do you think this teacher was on, and why?}
@A{A ferris wheel, because the ride keeps going up and down over and over, and it takes the same amount of time to go up as it does to go down.}
@Q{But what kind of relationship is it? Is it Linear? Quadratic? Something else?}
@A{(Let students discuss)}
}

== Periodic Functions

=== Overview

Students are introduced to periodic functions, and they become familiar with the terminology to describe them.

=== Launch

@right{@image{images/ferris-wheel.png, 300}}The relationship we're looking at is an example of a @vocab{periodic relationship}.

- The y-value (`height`) goes from 5ft to 205ft then back down to 5, then up again, then down again...
- This pattern of y-values repeats at regular intervals (every 30m)

*None of the tools in our modeling toolkit work here!* We've studied relationships that keep increasing or decreasing. We've studied relationships that grow one way until they reach a maxima or minima _once_, before growing in the other direction.

But we don't have any functions that keep repeating, going up and down over time.

@slidebreak

That's a problem for us as data scientists, because so many things in nature comes in _cycles:_ for most of the world, the sun rises each morning and sets each night, the moon waxes and wanes, and the tides come in and out. You may even have noticed that certain plants always seem to bloom in the Spring, or that more people tend to get sick in the winter. Being able to model these phenomenon is incredibly important, for everyone from farmers to fishermen to healthcare providers!

In this lesson we'll explore these periodic relationships, and a new class of functions - _@vocab{periodic functions}_ - that we can use to model cyclical relationships like these.

@strategy{A note on Vocabulary}{

You've probably heard of related terms _sinusoidal functions_ or _trigonometric functions_. We've chosen @vocab{periodic functions} because the term shows up often in both K-12 math _and_ science and engineering classes, in an attempt to balance the two. Note that "periodic" is also a broader term, as there are periodic functions that are _not_ sinusoidal/trigonometric. Science teachers may be quick to point out that periodic functions can be used to model relationships that _cycle_ (smooth ups-and-downs) and those that oscillate (any kind of up-and-down!).

As always, we advise you to use the term that works best for your classroom context!
}

When graphed, periodic functions rise to a certain height above a @vocab{Midline}, then drop the same distance below it, then rise again to complete the cycle. This cycle then repeats over and over.

@center{@image{images/wave-labeled-terms.png, 75%}}

- @vocab{Peaks} - the highest points on the wave (also called @vocab{Crests})
- @vocab{Troughs} - the lowest points on the wave
- @vocab{Period} - the length of a complete cycle, from peak-to-peak or trough-to-trough
- @vocab{Midline} - a horizontal line that falls halfway between the peaks and the troughs
- @vocab{Amplitude} - the distance from a peak or trough to the midline

@slidebreak

@ifslide{
@center{@image{images/wave-labeled-terms.png, 650}}
}

Starting at @math{x=0} with some initial value, a periodic function will rise to a maximum value (@vocab{peak}) or fall to a minimum value (@vocab{trough}), before returning to its initial value. As @math{x} increases, it will repeat this pattern over and over, fluctuating between its @vocab{peaks} and @vocab{troughs} over regular intervals, called @vocab{periods}.

You may already be familiar with two of the best-known periodic functions, @math{sin} and @math{cos}. Here are their contracts:

@center{
@show{(contracts
'("sin" ("Number") "Number")
'("cos" ("Number") "Number")
)}
}

*Note*: There are other periodic functions that do _not_ look like waves! For this exploration, we're going to limit ourselves to @math{sin} and @math{cos}.

=== Investigate

Periodic models with @math{sin} have the form @math{f(x) = a \sin(b(x - d)) + c}

@QandA{
@Q{You've seen the coefficient @math{c} before. What affect do you think it has on the model?}
@A{It's the vertical shift - it moves the midline of the graph up and down the y-axis.}
@Q{What effect do you think each of the _other_ coefficients has on the model?}
@A{Some may recognize @math{d} as the horizontal shift, or @math{a} as some kind of multiplier that makes the peaks higher and the troughs lower}
}

Both @math{sin} and @math{cos} are closely related to one another, and each one can be expressed in terms of the other. We're going to investigate @math{sin} for now, but everything you learn will also apply to @math{cos}.

@lesson-instruction{
Let's explore the coefficients of periodic models!

- Open @starter-file{alg2-exploring-periodic-desmos}.
- With your partner, complete @printable-exercise{graphing-models.adoc} using the first slide of the Desmos activity.
}

@teacher{Review student answers to the worksheet, giving ample time for them to hear one another's answers. Concepts like amplitude and frequency can be difficult to describe, and having students reach a consensus on their definition in their own words will help deepen their understanding.}

@slidebreak

The period is the distance between one @vocab{trough} and the next in a cycle. The frequency is _how many cycles_ occur over an interval.

@lesson-point{@center{@math{\mbox{period} = {2\pi \over \mbox{frequency}}}}}

- If the @vocab{period} is @math{2pi}, then the frequency is @math{1}.
- If the @vocab{period} doubles to @math{4pi}, the @vocab{frequency} _halves_ to  @math{pi/2}
- If the @vocab{period} is cut in half, the @vocab{frequency} _doubles_ to @math{2}

@slidebreak

Let's review our coefficients:

- @vocab{Amplitude} (@math{a}): the distance from a peak/trough to the midline (can be used with the @vocab{vertical shift} to produce the @vocab{midline})
- @vocab{Frequency} (@math{b}): the number of cycles in a given interval (can be used to compute the @vocab{period})
- @vocab{Vertical Shift} (@math{c}): the amount the graph is shifted up (@math{c} > 0) or down (@math{c} < 0)
- @vocab{Horizontal Shift} (@math{d}): the amount the graph is shifted right (@math{c} > 0) or left (@math{c} < 0)

@slidebreak

@lesson-instruction{
- Now that you have a sense for what terms like @vocab{amplitude}, @vocab{frequency}, and @vocab{midline} mean, complete @printable-exercise{matching-periodic-descriptions.adoc} by matching the graphs of periodic functions to their written descriptions.
- What strategies did you use to match the graphs to the descriptions?
}

@lesson-instruction{
- Open @link{https://www.tidetime.org/, TideTime.org}, and find a coastal city for which tidal data is available. Can you find the @vocab{amplitude}, @vocab{midline}, and @vocab{vertical shift} of the data?
- With your partner, complete @printable-exercise{modeling-ferris-wheel.adoc} using the last two slides of the Desmos activity.
- @opt{Open the @starter-file{alg2-ferris-wheel}, and change the definition of `f` and `g` to match the models defined on @printable-exercise{modeling-ferris-wheel.adoc}. How do they fit?}
}

=== Synthesize

Periodic relationships involve repeating cycles. Like our Ferris wheel, they rise and fall along regular intervals. Can you come up with some examples of periodic relationships?

For each one:

- Can you estimate the _period_ of the relationship?
- Can you estimate the _amplitude?_
- Can you estimate the _midline_ and _vertical shift?_

@teacher{
You'll likely need to support students in thinking through what these terms mean in the context of their first example, to get the class started. Suppose a student volunteers "the temperature, because it gets cold in the winter and warm in the summer":

- The seasons change over the course of one year, so the period would be 365 days.
- The temperature in your area might fluctuate between 95° in the summer and 25° F in the winter. That's a range of 70° F, for an amplitude of 35° F.
- The midline and the vertical shift are at 60° F (25 + 35 = 60).
}

== Modeling Periodic Relationships	@duration{45 minutes}

=== Overview

Students explore the @math{\mbox{CO}_2} dataset, which tracks the recorded quantity of carbon dioxide in the atmosphere from an observatory in Hawaii.

=== Launch

@lesson-instruction{
- Open the @starter-file{alg2-co2}, and complete @printable-exercise{exploring-co2.adoc}.
- What kind of model do you think would fit this best?
}



=== Investigate

@lesson-instruction{
Complete .
}


