[.beta]
= Exploring Periodic Models

@description{Students investigate periodic relationships in data about Covid spread, using an inquiry-based model involving hypothesizing, experimental and computational modeling, and sense-making. }

@lesson-prereqs{exploring-quadratic-models}

@keywords{periodic, period, amplitude, frequency}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Read and interpret real-world data, presented in a scatter plot
* Recognize periodic behavior in tables and graphs
* Model periodic relationships using functions


| Student-facing Lesson Goals
|

* Let's use Pyret to model periodic relationships in data

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

|===

== Round and Round We Go @duration{45 minutes}

=== Overview
Students are introduced to the notion of @vocab{periodic relationships}: related variables where the response variable repeats the same pattern over and over as the explanatory variable increases.

=== Launch

@lesson-instruction{
Working in pairs or groups, complete @printable-exercise{exploring-periodic.adoc}
}

@QandA{
@Q{What are some of your Noticings, and what did they make you Wonder?}
@A{(Solicit a range of student responses)}
@Q{Was it helpful to switch from a scatter plot to a line graph? Why or why not?}
@A{Yes - it was difficult to see the pattern until we added the line!}
@Q{Is there a relationship between `time` and `height`? Why or why not?}
@A{(Solicit a range of student responses, guiding the class to there being a relationship)}
@Q{What kind of ride was this teacher on?}
@A{A ferris wheel}
}

This worksheet had you create a different type of data display, called a @vocab{line graph}.

@lesson-point{Line graphs are often used instead of scatterplots when the explanatory variable is _time_.}

In this example, we know the ferris wheel keeps turning, generating data "in between" the times represented in our scatter plot. Connecting those dots with the line gives us an approximation of what data is missing between those times, and helps us see the shape of the relationship.

@QandA{
@Q{But what kind of relationship is it? Is it Linear? Quadratic? Something else?}
@A{(Let students discuss)}
}

The relationship we're looking at is an example of a _periodic relationship_.

- The y-value (`height`) goes from 5ft to 205ft then back down to 5, then up again, then down again...
- This pattern of y-values repeats at regular intervals (every 30m)

We can visualize the same pattern in both scatter plots and line-graphs

*None of the tools in our modeling toolkit work here!* We've studied relationships that keep increasing or decreasing. We've studied relationships that grow one way until they a maxima or minima, before growing in the other direction. But we don't have any functions that keep repeating, going up and down over time.

That's a problem for us as data scientists, because so many things in nature are _cyclical:_ for most of the world, the sun rises each morning and sets each night, the moon waxes and wanes, and the tides come in and out. You may even have noticed that certain plants always seem to bloom in the Spring, or that more people tend to get sick in the winter. Being able to model these phenomenon is incredibly important, for everyone from farmers to fishermen to healthcare providers!

In this lesson we'll explore these periodic relationships, and a new class of functions - _periodic functions_ - that we can use to model them.

=== Investigate

When graphed, periodic functions look like waves:

TBD - image!

Starting at some initial value at x=0, a periodic function will rise or fall as x-increases until it reaches some maximum or minimum value, before returning to its initial value. As x continues to increase, it will repeat this pattern over and over, fluctuating between its maximum and minimum value over regular intervals.

@QandA{
You may already be familiar with two best-known periodic functions, @math{sin} and @math{cos}.
@Q{What are the contracts for these functions?}
@A{both take a number and produce a number}
}

@slidebreak

@show{(contracts
'("sin" ("Number") "Number")
'("cos" ("Number") "Number")
)}

*Note*: There are other periodic functions that do _not_ look like waves! But for our first exploration, we're going to limit ourselves to @math{sin} and @math{cos}, since those are by far the most common ones.

@slidebreak

Periodic models with @math{sin} have the form @math{f(x) = a \sin(b(x - d)) + c}

@QandA{
@Q{You've all seen the coefficient @math{c} before. What affect do you think it has on the model?}
@A{It's the vertical shift - it moves the graph up and down the y-axis.}
@Q{What affect do you think each of the _other_ coefficients has on the model?}
@A{Some may recognize @math{d} as the horizontal shift, or @math{a} as some kind of multiplier that makes the high values higher and the low values lower}
}

Both @math{sin} and @math{cos} are closely-related to one another, and each one can be expressed in terms of the other. We're going to investigate @math{sin} for now, but everything you learn will also apply to @math{cos}.

@lesson-instruction{
Let's explore the coefficients of periodic models!

- Open @starter-file{alg2-exploring-periodic-desmos}.
- With your partner, complete @printable-exercise{exploring-periodic-2.adoc} using the first slide of the Desmos activity.
}

@teacher{Review student answers to the worksheet, giving ample time for them to hear one another's answers. Concepts like amplitude and frequence can be difficult to describe, and having students reach a consensus on their definition in their own words will help deepen their understanding.}

TBD - tidal data https://www.tidetime.org/
TBD - fit tidal data in desmos?
TBD - explore and explain period, midline



=== Common Misconceptions

=== Synthesize
-

== Looking for Patterns	@duration{45 minutes}

=== Overview

Students explore the @math{CO_2} dataset, which tracks the recorded quantity of carbon dioxide in the atmosphere from an observatory in Hawaii.

=== Launch

@lesson-instruction{
- Open the @starter-file{alg2-co2}.
- Make a scatter-plot showing the Covid infection rate for Massachusetts.
- What kind of model do you think would fit this best?
}

@strategy{Why just New England, starting from June 9th?!?}{

We have _artificially constrained this dataset_, showing only the data from June 9th to December 26th, 2020. We've made this choice in order to showcase the most purely-exponential behavior of the infection curve, for the sake of this lessons' math learning goals.

For students who are farther along, we recommend showing them _all_ the data through 2020, starting in January rather than June. The first portion of the infection curve shows a gradual, linear growth pattern before exploding in the Fall of 2020. This is _polynomial_ behavior, where a linear term dominates when the exponential term is small.

Based on the strength of your students, we encourage you to choose the data that best fits your learning goals. You may also wish to return to full dataset later on, once students are comfortable with polynomial functions.

To use all available data, open the @starter-file{alg2-covid} and change the source sheet on line 7 from `"New England"` to `"All"`
}


=== Investigate

@lesson-instruction{
Complete @printable-exercise{linear-models.adoc}, using the first slide of @starter-file{alg2-covid-desmos}.
}


