= From Dot Plots to Histograms

@description{Students are introduced to Histograms by comparing them to bar charts, learning to construct them by hand and in the programming environment.}

@ifproglang{pyret}{
@lesson-prereqs{contracts-tables-visualizations, ds-intro}
}

@ifproglang{codap}{
@lesson-prereqs{codap-dot-plots-bar-charts}
}

@keywords{histogram, bin, interval}

@add-to-lang{histogram}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives
@objective{histograms-pyret}
@objective{Make charts displaying frequency in Pyret and interpret them.}

| Student-facing Lesson Goals
|

- Let's create histograms for datasets and learn how to interpret them.

| Materials
|[.materials-links]

@material-links

| Preparation
|
@preparation{
- There is an interactive Desmos activity in the lesson, as well as Desmos formative assessments.
  * Open the Desmos activity you plan to use (@starter-file{histograms}, @assessment{histograms-check1-desmos}, or @assessment{histograms-check2-desmos}) and make a code or link to share with students.
  * If you are using our Google Slides, add the appropriate link to the slide deck. 
  * _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}
- There is an optional kinesthetic activity in this lesson that requires a ball of play-dough for each group of 3.
}

| Assessments
| @assessments

|===


== Introduction to Dot Plots

=== Overview

=== Launch

=== Investigate

=== Synthesize


== From Dot Plots to Histograms

=== Overview

=== Launch

A histogram is another data visualization commonly used to display quantitative data. Let's explore the ways that histograms are similar to and different from dot plots.


@QandA{
@Q{What do you Notice about the dot plot and histogram, which both display the same quantitative dataset?}
@A{What do you Wonder about the dot plot and histogram?}

[cols="^.^1a,^.^1a", option="header"]
|===
| Dot Plot            | Histogram
| @image{images/pounds.png}  | @image{images/pounds.png}

|===

}


=== Investigate

Now, let's think more deeply about the sort of information that dot plots and histograms provide us.


@lesson-instruction{
- Turn to @printable-exercise{compare-dot-plots-histograms.adoc}. At the top of the page, there is a dot plot on the left and a histogram on the right.
- First: Use *only the dot plot* to answer the questions. Record your responses in the *middle* column of the table. If there is a question that you *cannot* answer, put an X.

@image{images/pounds.png}

}



@QandA{
@Q{Were there any questions that you could *not* answer using the dot plot? If so, which ones?}

@Q{Were there any questions that were *challenging* to answer using only the dot plot? If so, which ones?}
}


Next, we'll use a histogram to answer the same questions.

@QandA{
@Q{Given that this is your first time interpreting a histogram: What questions do you have about doing reading a histogram?}

@A{Possible questions include:
- How is this different from a bar chart? Histograms show the distribution of quantitative data, not categorical. Histograms' bars cannot be reordered, as they allow us to see the shape of a dataset. We can reorder bars in a bar chart.
- Are the values on the tick mark included in the bar? On a histogram, each bar _includes_ the left-end value but not the right-end value.}
}

@lesson-instruction{
- Now, you will use *only the histogram* to answer the same set of questions. Record your responses in the *right-hand* column of the table. If there is a question that you cannot answer, put an X.
- Respond to the remaining questions on the page; we will discuss your responses when you are finished.

@images{images/pounds.png}

}


@strategy{Histograms Don't Display Individual Data Points!}{

According to research conducted by Bakker, Biehler, and Konold (2014), students are inclined to view data as _individual cases_.

For this reason, you may notice that dot plots are accessible to students while histograms (which only offer aggregate information) are more challenging to interpret.

To combat this student inclination, we spend ample time in this lesson focusing on data visualizations where individual cases are visible, as recommended by the research. Additionally, when we introduce aggregate plots, they are accompanied by representations that allow students to see individual cases.

}


@QandA{
@Q{How are the two displays alike?}
@A{They both display the frequency and distribution of quantitative data. They both show the total number of values.}

@Q{How are the two displays different?}
@A{We can see individual points on the dot plot, but on the histogram, we just get a collective overview of the data. There is no way to single out one particular animal's weight on the histogram.}
}


=== Synthesize


