= Bootstrap:Algebra Pathway

[.logo]
@image{images/Logo.png, Bootstrap:Algebra}

The Bootstrap:Algebra Pathway applies mathematical concepts and rigorous programming principles to creating a simple video game, and is @link{pathway-standards.shtml, aligned to National and State Standards for Mathematics, as well as the CSTA standards and K12CS frameworks}. The module can be taught as a separate, standalone tech or CS class, or can be integrated into a mainstream math class, delivered by a math teacher with no prior CS experience. 

In this series of lessons, students create a simple, 3-character game involving a player, a target and a danger. They design what each character looks like, and use mathematical concepts such as coordinate planes, order of operations, ratio and proportion, domain and range, function composition, word problems and the distance formula to detect collisions, handle keystrokes, and determine how they move and interact. 

== Teaching Remotely?
If you're teaching remotely, we've assembled an @link{../../ImplementationNotes.shtml, Implementation Notes} page that makes specific recommendations for in-person v. remote instruction.

== Ordering Student Workbooks?
While we give our workbooks away as a PDF (see below), we understand that printing them yourself an be expensive! You can purchase beautifully-bound copies of the student workbook from Lulu.com. 
@ifproglang{wescheme}{@link{https://www.lulu.com/en/us/shop/dorai-sitaram-and-flannery-denny-and-ed-campos-and-jennifer-poole/bootstrapalgebra-student-workbook-wescheme/paperback/product-4j9rmj.html, Click here to order}.}

@ifproglang{wescheme}{@link{https://www.lulu.com/en/us/shop/dorai-sitaram-and-flannery-denny-and-ed-campos-and-jennifer-poole/bootstrapalgebra-student-workbook-pyret/paperback/product-6j9zek.html, Click here to order}.}