= Pathway P narrative

(English version in @proglang)

@ifproglang{wescheme}{
Pathway narrative for WeScheme
}
@ifproglang{pyret}{
Pathway narrative for Pyret
}

== Pathway pages are entirely optional!

By default, the build script will create this page using all of the lessons defined in lesson-order.txt. It will also add boilerplate text from shared/langs/XYZ/defines.rkt.

**99% of the time, you will not need a pathway page like this one**

As of fall2022, the only time it's used is for Physics, History and Hour of Code -- as none of those pathways have traditional lesssons.

@vocab{variable}


Filler prose:

Assumenda possimus totam impedit. Ad modi ut quibusdam natus iste
saepe eaque. Itaque sapiente voluptatem fuga nisi quia.

Quo fuga quia rem repellendus autem explicabo. Aut et non autem.
Sunt commodi aut voluptas non. Aut quia accusamus eaque molestiae
eveniet reiciendis facere.

Et aspernatur repellendus quae laboriosam voluptas veritatis
nihil. Reiciendis dignissimos quo sint est distinctio et illo.
Pariatur velit dicta non suscipit eos laboriosam. Quia voluptas
qui error ullam consequatur rerum debitis sit.

(Lessons in pathway automatically linked below.)
