= Fitting Exponential Models

@description{Students investigate exponential relationships in data about Covid spread, using an inquiry-based model involving hypothesizing, experimental and computational modeling, and sense-making. They are introduced to table transformations and inverse functions, which are used to fit exponential models onto nonlinear data.}

@lesson-prereqs{exponential2-building-models}

@keywords{exponential, quadratic, square, coefficient}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

-

| Student-facing Lesson Goals
|

-

| Materials
|[.materials-links]
@material-links

| Preparation
| 
@preparation{
- Much of the exploration in this lesson hinges on a custom-built interactive Desmos activity. + 
You will want to:
 * Open @starter-file{alg2-covid-desmos}.
 * Make a link or code to share with your students.
 * Decide how you will share the link or code with students and, if you are using our Google Slides, add the appropriate link to the slide deck.
 * Set the pacing so that students are synced to you and only able to interact with the slide for the lesson section you are working on.
- _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions-alg2.adoc, _Here's what you need to do._}
}
|===

== Modeling in Desmos
@objective{model-fit-function}

=== Overview

Students extend their sampling techniques to exponential relationships, experimenting in Desmos to come up with plausible models

=== Launch

Now that you're familiar with exponential functions, let's use them to model this Covid data!

@lesson-instruction{
- Make a scatter plot showing the change in positive Covid cases for `MA-table`.
- What can you tell about the @vocab{base} @math{b} from this plot?
- What about the initial value @math{a}?
- What about @math{k}?
}

@slidebreak

@teacher{Have students respond to the discussion questions below in pairs or small groups.}

@QandA{
@Q{Does your scatter plot show exponential growth or exponential decay?}
@A{The scatter plot shows growth. The "hockey stick" is pointing up, meaning that positive cases are increasing.}
@Q{Can we make any conclusions about the value of @math{b}? Explain.}
@A{Because we see exponential growth, we know that @math{b} must be greater than one.}
@Q{Can we make any conclusions about the value of @math{k}?}
@Q{Can we make any conclusions about the value of @math{a}? Explain.}
@A{@math{a} must be positive, because the curve is consistently above @math{k}.}
}

=== Investigate

@teacher{Make sure you've advanced your teacher dashboard of @starter-file{alg2-covid-desmos} to the fourth slide ("Exponential Model for MA") so that students are looking at the correct screen. In the next activity, students use Desmos to find promising exponential models, and then fit the model programmatically in Pyret!}

@lesson-instruction{
- Let's return to the *Modeling Covid Spread Desmos file*.
- You should now be on the fourth slide ("Exponential Model for MA").
- Use it to complete @printable-exercise{exponential-models-ma.adoc}.
}

@teacher{Crowdsource the various values for each coefficient.}

- Look at all the values we came up with for @math{a}, @math{b}, and @math{k}.
- What do you notice? Are they clustered around a particular value, or completely spread out?  Are there any values that are really far from the others?

Models are helpful because they give us an easy way to make predictions about complex data. Oftentimes, we can just using mental arithmetic to do a quick calculation! But what if the model itself is hard to use?

@lesson-instruction{
Use your model to make predictions on @printable-exercise{predicting-exponential-growth.adoc}.
}

=== Synthesize
- Is an exponential model a good fit for this data?

@teacher{Have students share their predictions for each of the time-spans in question 5.}

@QandA{
@Q{How accurate were your "guesstimates" for your models' predictions after 50 days? (Very accurate? Not accurate at all?)}
@Q{How accurate were your "guesstimates" after 250 days?}
@Q{How accurate were your "guesstimates" after 450 days?}
@Q{How accurate were your "guesstimates" after 550 days?}
}

Chances are, your guesses got less accurate as the number of days increased!

@slidebreak

*Why was it so much guesstimate the farther out we got, when the number of days was always increasing by a fixed amount?*

We are creatures of nature, so our brains are designed to be really good at working with things we see all the time. It's normal to see groups of 2, 5, or even 10 or 100, and we have a pretty good intuition for comparing group sizes as long as they're small.

But when numbers grow really, really, _really_ fast...we get lost! Our brains lose track of differences when two numbers get really enormous.

_Mathematically,_ the number line is composed of equal intervals forever. @link{https://www.scientificamerican.com/article/a-natural-log/, *But we don't actually process it that way at all.*}

@slidebreak

*Exponential growth poses a problem for those of us with human brains*, because the numbers get so big, so fast that it can be difficult to wrap our heads around it!

This may have played a role in the sluggish response of many countries, and the tragic loss of life and decrease in public health that followed.

Fortunately, there's another mathematical tool that can help us get control of these wildly gigantic numbers. It's called a _logarithm_, and we'll be exploring it soon!

== Modeling in Pyret
@objective{model-fit-function}

=== Overview
Students take their Desmos-derived coefficients back to Pyret, to formalize their understanding. They are also exposed to computational limitations, which arise when dealing with extremely small or extremely large numbers.

=== Launch

Pyret's function `num-expt` is the function that we use for exponents. It takes in 2 numbers: the base and the power. `num-expt(2, 3)`, for example will produce @math{2^3}.

@lesson-instruction{
- Use @starter-file{alg2-covid} to complete the first section of @printable-exercise{computational-limits.adoc}.
- Be prepared to discuss what you observed.
}

=== Investigate

Sometimes, data scientists perform calculations that result in very large or very small numbers. They send satellites to far-away planets, or reason about the mass of electrons and neutrinos.

In math, numbers can be infinitely large or small. They can have any number of digits or decimal places! But computers are *finite*, and some numbers get too big to fit in their memory. So what do we do?

@slidebreak

One option is to make the really big or small numbers _approximations_ of the real numbers, in the same way a model approximates real data. We can shrink a number with 100 digits down to just 3 digits, as long as we remember "there's 97 zeros after it!" This way, numbers like a "four trillion and one" get approximated as "four trillion".

In a math classroom, this is the difference between @math{\frac{2}{3}} rendering as @math{ 0.\overline{3}} or being rounded to 0.666666667.

@slidebreak

Virtually every programming language does this when numbers get large enough, chopping off those last digits in order to stay fast. This is especially important for time-sensitive computations like weather modeling, where knowing where a hurricane will make landfall before it hits is worth _much_ more than pinpointing where it hits down to the kilometer.

Are there times when we *don't* want to chop off digits like this?

@slidebreak

Pyret has a special kind of Number, called a _RoughNum_, which chops off digits for faster calculation. But unlike other languages, Pyret wants to put the programmer in control. It will never drop digits _unless you tell it to!_

To turn a number into a RoughNum, we use the approximation symbol `~`. `~3`, for example, is "roughly three." This tells Pyret to round off the calculation, prioritizing *speed* over *precision* to get a result that is "roughly accurate".

@QandA{
@Q{Why do you think Pyret won't let us compare two RoughNums?}
@A{Because it knows that two different Numbers can both round to the same RoughNum, which means comparisons are not reliable!}
}

@slidebreak

Exponential growth and decay can create enormously large and enormously small numbers, which can slow down computation.

@lesson-instruction{
- Complete @printable-exercise{computational-limits.adoc}.
}

=== Synthesize

- What makes exponential models different from the linear and quadratic models you've seen before?
- Is it always okay for Data Scientists to round off their numbers to speed up computation? Why or why not?

@slidebreak

Linear regression allows us to find the *computationally optimal model*, not just a model that "fit really well."

@QandA{
@Q{In this project, do we know whether or not our model is the _best?_}
@A{We don't know!}
@Q{How do you know?}
@A{This fitting process was purely about adjusting sliders and seeing if @math{S} goes down. It was all trial-and-error, with no guarantee that there's no better model out there.}
}
