= Predictive Models: Regression Models


== Do Bigger Animals take longer to find a Home?
The scatter plot below shows how long it takes each animal to be adopted, based on their weight.

@center{@image{../images/pounds-v-weeks.png, 500}}


@n What do you *Notice* about this chart? @fitb{}{}
@fitb{}{}

@n What do you *Wonder* about this chart? @fitb{}{}
@fitb{}{}

@n Do heavier animals tend to take more weeks to be adopted? @fitb{3em}{@ifsoln{yes}} _Does this make sense to you?_ @fitb{1em}{} @hspace{2em} Explain why or why not:
@blanklines{3}{@ifsoln{A lot of apartments won't allow pets over a certain size, and fewer people can take care of a 80+ pound animal. Those factors might make it harder for larger animals to find homes.}}

@n *Draw a line* through the dots on the chart, showing the pattern you can see.

== Making Predictions

@n Some new animals are coming to the shelter! Using the line you drew at the top of this page, *predict how many weeks* it will take for each animal to be adopted in the table below.

[.FillVerticalSpace, cols="<2,^2,^2,^2,^1,^1,^2,^4",options="header"]
|===
| name       | species   | sex       | age| fixed  | legs  | pounds| Predicted Weeks
| Daisy      | dog       | female    |  5 | true   | 4     | 68    |
| Ada        | dog       | female    |  2 | true   | 4     | 32    |
| Miaulis    | cat       | male      |  7 | false  | 4     | 8.8   |
| Maple      | dog       | female    |  3 | true   | 4     | 51.6  |
|===

@n You drew the line based on a scatter plot of _every_ kind of animal. Would you get a better fit by looking at each species separately?
@blanklines{2}{@ifsoln{Probably - different species grow to different weights, so the line we drew isn't a good fit for any one species.}}

@n What other column of numbers could be used to predict the number of `weeks` an animal spends in the shelter? @fitb{}{@ifsoln{age}}
