= Predictive Models: Regression
++++
<style>
div#body td { padding: 0px 10px !important;}
div#body .fitb { min-width: 3em; }
</style>
++++

== How long will you live?
You're going to invent the questions for a *silly* online quiz the predicts how long people live. 

@vspace{1ex}

We've completed the first row of the table below, suggesting that the number of cats someone lives with might have a positive relationship with their lifespan. We made up a slope of 1.2 - every additional cat contributes to an extra 1.2 years of life! Having 10 pets would add 12 years to someone's lifespan!

[.FillVerticalSpace, cols="<.^2a, ^.^1a, .^2a", options="header", stripes="none"]
|===
| Variable 		 | Slope	| Years gained for 10 of the variable
| Number of cats | 1.2 		| 12 
| 				 | 			|
| 				 | 			|
|===

@n It's time for you to be silly and creative. What other _numeric_ variables might increase how long a person will live? (e.g. "how many jumping jacks they do a day, etc"). Add two more variables to the table above, including a fictional slope and the 10-year predictions.

@n How long will someone live if the value of all those variables is *zero*? @fitb{3em}{} *Use this to fill in the `y-intercept` blank below.*

@n Fill in the blanks for the definition below with the variables you added to the table above:

@center{
*lifespan prediction:*
(@fitbruby{3em}{1.2}{slope 1} @math{\times} @fitbruby{6em}{@ifsoln{cats}}{variable 1}) @math{+}
(@fitbruby{3em}{}{slope 2} @math{\times} @fitbruby{6em}{}{variable 2}) @math{+}
(@fitbruby{3em}{}{slope 3} @math{\times} @fitbruby{6em}{}{variable 3}) @math{+}
@fitbruby{3em}{}{y-intercept}
}


[.no-flex-section]
== Do Bigger Animals take longer to find a Home?
The scatter plot below shows how long it takes each animal to be adopted, based on their weight.

[cols="1a, 1a", frame="none"]
|===
|
@n *Draw a line through the dots on the chart*, showing the pattern you see.

@n Do heavier animals seem to take longer to find a home? @fitb{2em}{@ifsoln{yes}}

@n _Does this make sense to you?_ @fitb{1em}{} @hspace{2em} Why or why not?
@blanklines{3}{@ifsoln{A lot of apartments won't allow pets over a certain size, and fewer people can take care of a 80+ pound animal. Those factors might make it harder for larger animals to find homes.}}

|
@center{@image{../images/pounds-v-weeks.png}}
|===


== Making Predictions

@n Some new animals are coming to the shelter! Using the line you drew on the plot above, *predict how many weeks* it will take for each animal to be adopted in the table below.

[.FillVerticalSpace, cols="<.^2,^.^2,^.^2,^.^2,^.^1,^.^1,^.^2,^.^4",options="header"]
|===
| name       | species   | sex       | age| fixed  | legs  | pounds| Predicted Weeks
| Daisy      | dog       | female    |  5 | true   | 4     | 68    |
| Ada        | dog       | female    |  2 | true   | 4     | 32    |
| Miaulis    | cat       | male      |  7 | false  | 4     | 8.8   |
|===

@n What other column of numbers could be used to predict the number of `weeks` an animal spends in the shelter? @fitb{}{@ifsoln{age}}
