= Animal Image - Explore

@link-instructions{
Open the @opt-starter-file{piecewise-animal-images} and look at the code.
}

[.FillVerticalSpace, cols="^1,^1", options="header"]
|===
| What do you Notice? | What do you Wonder?
|						|
|===

@n How is this program similar to the last one we looked at?

@fitb{}{@ifsoln{They both have helper functions defined and use the helper function in the image-scatter-plot function.}} +
@fitb{}{}

@n How is the code different from the other `image-scatter-plot` programs we've seen?

@fitb{}{@ifsoln{The helper function in this file is much more complicated! It uses conditionals.}} +
@fitb{}{}

@n Click "Run". How does using clip art help us to better understand the data?

@fitb{}{@ifsoln{The images are cool! And they make it so easy to understand whether the species are evenly distributed or clustered.}} +
@fitb{}{}

@n What risks might there be to using clip art for data that describes humans?

@fitb{}{@ifsoln{Clipart of humans runs a serious risk of stereotyping or excluding populations!}} +
@fitb{}{}

@n We have seen `image-scatter-plot` used to make a lot of different custom scatter plots. How could you use `image-scatter-plot` in your own analysis?

@fitb{}{} +
@fitb{}{} +
@fitb{}{} +
@fitb{}{}
