= Exploring Image Scatter Plots

@link-instructions{
Look at the code in the @starter-file{custom-scatter-plot}.
}

@n Compare the definitions of `age-dot` and `species-tag` to what you wrote. Are they the same? If not, what is different?

@fitb{}{} +
@fitb{}{}

@vspace{2ex}

_Answer the following questions about the last line of code in the file, which is commented out._

@n What is the *name* of the function being used here? @fitb{15em}{@ifsoln{image-scatter-plot}}
 How many things are in its *Domain*? @fitb{}{@ifsoln{4}}

@n What is the 1st argument? @fitb{20em}{@ifsoln{animals-table}} What is its *data type?* @fitb{}{@ifsoln{Table}}

@n What is the 2nd argument? @fitb{20em}{@ifsoln{"pounds"}} What is its *data type?* @fitb{}{@ifsoln{String}}

@n What is the 3rd argument? @fitb{20em}{@ifsoln{"weeks"}} What is its *data type?* @fitb{}{@ifsoln{String}}

@n What is the 4th argument? @fitb{}{@ifsoln{age-dot}}

@n What is the *data type* of the fourth argument in the Domain? If you're not sure, write down your thinking. What can you rule out? What do you think it _might_ be? @fitb{}{@ifsoln{a function - because `age-dot` is the name of a function. Typing it into Pyret produces `<function:age-dot>`}}

@fitb{}{}

@n *Uncomment the last line at the bottom of the file, and click "Run".* What does `image-scatter-plot` do with its 4th argument?

@fitb{}{@ifsoln{It draws a scatter plot, but in place of each dot is a new image.}}

@fitb{}{@ifsoln{The image is determined by whatever the function produces for each Row.}}

@n Try changing your `age-dot` function to use different colors, or even different shapes! Can you make the size of the shape be _one half_ the age of the animal?

@n *On a new line in the Definitions Area, try making an `image-scatter-plot` using the `species-tag` function.* + 
Click run, and describe what you see. @fitb{}{@ifsoln{It draws a scatter plot, but in place of each dot is the species of the animal.}}

@fitb{}{}

== Understanding Custom Visualizations

@n *Look at the image scatter plot that has dots of different sizes.* +
Can you draw any conclusions about animals that are both _young_ and _lightweight_? @fitb{}{@ifsoln{The animals that are both young and lightweight seem to be adopted relatively quickly. There do not appear to be outliers to}}

@fitb{}{@ifsoln{this trend; that is, there are no young and lightweight animals that take more than 10 weeks to adopt.}}

@n Looking at that same scatter plot, the director of the shelter says: "Animals that are older _and_ that weigh more than 50 pounds generally take at least 5 weeks to be adopted." Do you agree with this statement? Explain.
@fitb{}{@ifsoln{Yes. We can see that the larger dots located to the right}}

@fitb{}{@ifsoln{of @math{x=50} are also positioned above @math{y=5}.}}

@n *Look at your image scatter plot with species nametags in red.* +
What does this chart reveal that we couldn't see on the original (pounds v. weeks) scatter plot? @fitb{}{}

@fitb{}{@ifsoln{A lot of the animals that are getting adopted more quickly weigh less than 25 pounds and are also _not_ dogs.}}
