= Advanced Data Visualizations in a Nutshell
++++
<style>
body code { line-height: 16px !important; }
body.LessonNotes li {
    margin-bottom: 2px;
}
</style>
++++
== Functions as Data

@vspace{1ex}

*You've learned that functions are _machines that consume and produce values_.* +

@vspace{1ex}

In the real world, we see machines consume things to produce things all the time:

- Bulbs consume electricity and produce light.
- Toasters consume bread and produce toast. 

@vspace{1ex}

*Sometimes, machines consume other machines:*

- A school bus is a machine. It comes with a stereo, which could be swapped out for a new one with more features. A stereo is a machine. And the bus needs one of them in order to play music over the speakers.
- A blender might have different attachments. Each attachment is a machine of its own and the blender needs one of them to work!

@vspace{1ex}

This is true of function machines in math and programming, as well! By now you've learned plenty of data types (e.g. - Numbers, Strings, Images, Booleans, Rows and Tables). *... And Functions can be their own kind of data type!*

- Imagine a function `species-dot`, that consumes a Row from the Animals Dataset, and produces a different-colored square depending on the species.
- What if we used `species-dot` to customize the dots on our scatterplot, instead of using the same blue dot for each animal? +
@hspace{1em} _In this example, we'd be using the `species-dot` function as an input to our `scatter-plot` function!_

@vspace{1ex}

Here are the Contracts for some special display *functions that consume functions*, including the scatter plot we just described: +
_Look carefully at the last argument in each Domain. In each case, *the function consumes a Row and produces an Image*._

@vspace{1ex}

@indented{
@show{(contracts
  '("image-scatter-plot" ("Table" "String" "String" "(Row -> Image)") "Image")
  '("image-histogram" ("Table" "String" "Number" "(Row -> Image)") "Image")
  '("image-bar-chart" ("Table" "String" "(Row -> Image)") "Image")
  '("image-pie-chart" ("Table" "String" "(Row -> Image)") "Image")
)}
}

== Piecewise Functions

Functions always apply a particular rule to their input. +

- In an earlier lesson, you saw how `gt` always draws a solid, green triangle using the input as the size.
- In the `species-dot` example above, there's no single rule that will generate a different color for each species. 

@vspace{1ex}

*We need a way for functions to change rules, depending on their input.*

@vspace{1ex}

*Piecewise Functions* are functions that can behave one way for part of their Domain, and another way for a different part.

- Piecewise functions are divided into "pieces".
- Each piece has two parts: the "if" and the "then".
- This tells the computer _when_ to apply each rule, and _what_ the rule is.

In our `species-dot` example, our function might draw black squares when the input is a dog, but orange squares when the input is a cat.  +
The function definition would look like this:

[.indentedpara]
--
```
# species-dot :: (Row) -> Image
fun species-dot(r):
  if      (r["species"] == "dog"):       square(5, "solid", "black")
  else if (r["species"] == "cat"):       square(5, "solid", "orange")
  else if (r["species"] == "rabbit"):    square(5, "solid", "pink")
  else if (r["species"] == "tarantula"): square(5, "solid", "red")
  else if (r["species"] == "lizard"):    square(5, "solid", "green")
  end
end
```
--
