= Teacher Resources for Data Science

== Let's Get Started
- *Online Community* [@link{https://discourse.bootstrapworld.org, Discourse}] -- Talk with other Bootstrap teachers, ask questions, and share ideas!
- *Remote Instruction* [@dist-link{ImplementationNotes.shtml, link}] -- specific recommendations for in-person v. remote instruction.

=== Printables for Classroom Walls
- *Computing Pioneers Posters* [@lesson-link{computing-needs-all-voices/pages/computing-pioneers.adoc, link}] -- For greater impact, use our @lesson-link{computing-needs-all-voices} lesson to engage your students with these posters!

- *Data Fallacies to Avoid* [@lesson-link{threats-to-validity/pages/Geckoboard-Data-Fallacies-Poster.pdf, link}] from @link{https://geckoboard.com/best-practice/statistical-fallacies/, geckoboard.com}

=== Standalone Hour of Code Activities from Bootstrap
- *Hour of Data* [@lesson-link{hoc-data/, link}] -- A self-guided Desmos activity for exploring a real dataset, and using it to make sense of a real-world problem.
- *Snowman Puzzle* [@lesson-link{hoc-winter-parley, link}] -- This Pyret Starterfile has all the pieces your students will need to make a snowman by changing the coordinates in the code.

== Exercises and Solutions
@all-exercises

== Notes, Slides, and Starter Files
@lesson-info

== Other Curricular Materials
- *Contracts* [@link{solution-pages/Contracts.pdf, link}] -- A PDF of the contracts pages from the back of the student workbook.
- *Glossary* [@dist-link{Glossary.shtml?pathway=data-literacy, link}] -- All of the vocabulary words (and their definitions) used in this pathway.
- *Bilingual Glossary of Bootstrap Terms (English-Spanish)* [@dist-link{lib/bilingual-glossary.html, PDF}] -- For teachers with ELL/ESL students, we provide a bilingual glossary for all of the terms used across our curriculum library.
- *Blank Data Cycle Worksheet* -- [@dist-link{pages/2-blank-data-cycles.adoc, html}] -- When students need scaffolding for answering a question with data.
- *Collection of Bootstrap:Data Science Desmos Activities* [@link{https://teacher.desmos.com/collection/5fc9250afcaa3f30f4946746, link}] -- All of our Desmos Data Science lessons, in one place.
- *Sentence Starters* [@dist-link{pages/sentence-starters.adoc, html}] -- Use these sentence starters to help students describe patterns, make predictions, find comparisons, share discoveries, formulate hypotheses, and ask questions.
