= Logic Errors

++++
<style>
.recipe_word_problem, .recipe_instructions { display: none; }
.test { line-height: 1.6rem; text-decoration: underline; }
</style>
++++

*Zahara was given this Word Problem:* 

@vspace{1ex}

@indented{_It's normal to tip 20% on a bill at a restaurant. Write a function that takes in the total on the bill, and returns the new total that adds a 20% tip._}

@vspace{1ex}

*And defined the following function to solve it:* 

@vspace{1ex}

@indented{
@show{(code '(define (check-total bill) (* 0.2 bill)))}
}

@vspace{1ex}

*The function runs without any errors, but...*

@n Can you see what is wrong with this definition?

@fitb{}{
	@ifsoln{The function computes the tip, but does not add it to the price of the bill.}
}
@fitb{}{}

@vspace{4ex}

To explain their thinking, they filled out the following Design Recipe. Read each step carefully, looking for where their thinking went wrong.

@vspace{2ex}

[cols="1a"]
|===
| @include{fragments/check-total.adoc}
|===

@vspace{2ex}

@n In which step did their thinking first go wrong? (circle one)

[cols="^1,^1,^1", grid="none", frame="none", stripes="none"]
|===
| Contract {amp} Purpose
| @ifnotsoln{Examples {amp} Labels} @ifsoln{*_Examples {amp} Labels_*}
| Definition
|===

@vspace{1ex}

@n What could they have done to find or avoid the mistake in the first place?
@fitb{}{
	@ifsoln{They could have checked to see if their examples really matched the purpose statement,}
}
@fitb{}{@ifsoln{Or used a simpler example to check their calculations}}

@fitb{}{}

@fitb{}{}
