= Case Study: Michelle's Spotify Use

Michelle started using Spotify six months ago. The first time she checked out her AI-produced "Discover Weekly" playlist, she was underwhelmed. The songs did not seem to match her tastes, and she ended up skipping over many of them before even 30 seconds had passed. Michelle was so disappointed in that first experience that she gave up entirely on the "Discover Weekly" playlist, writing it off as a feature she did not care for.

@vspace{1ex}

After three months of using Spotify and listening to all of her favorite songs, artists, and playlists, Michelle happened to click on "Discover Weekly" again - but this time, she was delighted by what she heard. It felt as though her best friend had curated a playlist just for her. Michelle discovered new music that she had never heard before, that she absolutely loved.

@vspace{1ex}

As Michelle listened, she remarked, "Wow, Spotify has really improved their algorithms since I last checked out Discover Weekly."

@vspace{1ex}

*Michelle’s statement is incorrect. In fact, the algorithms have remained exactly the same!* Why is her playlist much better after three months of using Spotify? Provide as much detail as you can, using what you have discovered during this lesson.

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}




Has Spotify or YouTube ever recommended you a new song or video that you enjoyed? Has it ever recommended you something that you _didn't_ enjoy? Elaborate.

Answers will vary. Allow students to share their personal experiences.}

How and why do you think recommendation algorithms seem to "know" what content you will like?

Allow students to share their responses. Some possible responses include: it reviews my viewing / listening history; it has access to the content I have skipped; it sees which videos and songs I return to over and over.

Why do you think the songs and videos recommended are sometimes _not_ what you were hoping to discover?

Our tastes are not always entirely predictable. Just because a listener enjoys _some_ upbeat pop music with a female vocalist does not indicate that they will enjoy _all_ upbeat pop music with a female vocalist.



Hopefully, our conversation about automatic song and video recommendation got you thinking about how computers need to be _trained_ on data for machine learning to happen.

In the case of song and video recommendation, Spotify and YouTube's algorithms process all the available data about your listening/viewing preferences. Let's say, however, that you have a history of listening to folk music... but a desire to branch out and explore some hip hop. Spotify cannot read your mind, nor will it guess that maybe today is the day you try some new music that is out of your comfort zone; it can only process the data you've provided it, and build a predictive model based on that data. While there's a small chance that Spotify will recommended hip hop music that is _influenced_ by folk music (especially if it features a female vocalist!). If you *really* want to branch out, ask a friend for a recommendation... and listen to it. If you spend enough time listening to hip hop, Spotify will eventually start generating hip hop recommendations.

Machine learning is driven by data. More data results in more accurate task completion.


The type of data that we use to train artificial intelligence varies by situation.
