= The First Spell Checker

The very first spell checker would use misspelled words as inputs.

- *First*, it would develop alternative candidates for the misspelled word (input) by making one of the following adjustments: (1) replace a single letter with a different one, or (2) swap the positions of two adjacent letters.

- *Next*, it would search the provided dictionary to see which alternatives were valid options.

- *Finally*, it would produce a list of valid correctly spelled words for the user to choose from.

== Part 1: Follow the Algorithm ("wello")

@n Generate alternative candidates for the misspelled word by replacing *one* letter with a different one. We’ve provided a first option to get you started. (Hint: these candidates don’t need to be real words!)

@fitb{8em}{cello} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{}

@fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{}



@n Generate alternative candidates for the misspelled word by swapping the positions of two *adjacent* letters. Again, we’ve provided a first option to get you started.

@fitb{8em}{ewllo} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{}

@fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{} @hspace{3em} @fitb{8em}{}


@n Are any of the candidates you listed above _actual_ words? If so, circle them. How many _plausible_ candidates did you find? @fitb{8em}{}

@n In questions 1 and 2 above, you generated 10 alternatives to "wello". Is that amount comparable to the amount of alternatives a computer would generate? Explain. @fitb{}{}

@fitb{}{}

@fitb{}{}

== Part 2: Reflect

@n What do you think are some limitations of this algorithm? What are some of its advantages? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n How does the first spell checker's algorithm compare with your personal (human) algorithm? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n In the previous activity (@printable-exercise{human-v-computer.adoc}), you tried to predict the steps a spell checking algorithm might follow. How close was your prediction to the first spell checker's algorithm? Explain at least one similarity and one difference. @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}



