= Introduction to Box Plots

@description{Students compute five-number summaries from quantitative datasets, and then use those five-number summaries to create box plots.}

@lesson-prereqs{histograms-interpret}

@keywords{range, box plot, box and whisker plot, five number summary, first quartile, interquartile range}

@add-to-lang{box-plot, modified-box-plot, box-plot-scaled, modified-box-plot-scaled, vert-box-plot, modified-vert-box-plot, modified-vert-box-plot-scaled}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives

| Student-facing Lesson Goals
|

- Let's compute and plot five-number summaries.

| Materials
|[.materials-links]

@material-links

@ifproglang{pyret}{

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
|
@preparation{
- Decide whether or not you want to launch this lesson using the *Live Pyret Survey* and your class' own data. If so, follow the instructions on @dist-link{pages/live-pyret-survey-instructions.adoc} to:
  * _Make a copy_ of the @opt-starter-file{box-plot-survey-form} and share it with your class. 
    ** This makes a great "Do Now" as students enter the room, but could also be assigned for homework the night before.
  * _Link the Google Sheet of their responses_ to the @opt-starter-file{box-plot-survey-starter}.
  * _Click "Run"_ and then either:
    ** Project the new Data Visualization they'll be introduced to today. 
    ** Publish the starter file and share a link with your students.
- If you are using our Google Slides, you will see the word "Optional" in the title of any slide that corresponds to an optional section of the lesson plan. Adjust the slides based on which portions of the lesson you will be doing with your students.
}

}

|===

== The Five-Number Summary

@objective{five-num-summary-compute}
@objective{five-num-summary-interpret}


=== Overview

Students learn about how to use range, quartiles, and interquartile range to talk about variability.

=== Launch
@slidestyle{Launch}

@ifproglang{pyret}{
@opt-block{

@teacher{
If you decided to launch today's class using our *Live Pyret Survey*, you'll probably want your students to complete the google form as they enter class. We won't actually look at the results until the next section, though, so feel free to make another choice about how and when to have your students enter their data. 

@indented{
Make sure you've already...

1. Followed the @dist-link{pages/live-pyret-survey-instructions.adoc, Instructions to Set up and Link the Files} +
2. Shared the *link you made to your class' copy* of the @opt-starter-file{box-plot-survey-form}
}
}

@lesson-instruction{
- Open the *Google Form Survey* link I shared and submit your response.
}

}
@slidebreak{Launch}
}

Each of the three dot plots shown below has a median of 60.

[cols="^.>1a,^.>1a,^.>1a"]
|===

| @image{images/dot-plot-2e.png}
| @image{images/dot-plot-1e.png}
| @image{images/dot-plot-3e.png}

|===

@QandA{

@Q{We know that these dot plots represent datasets that have the same median, but the data definitely isn't the same! In what ways are they _different_?}
@A{Each dot plot has a different spread and a different shape. There are different peaks, gaps, and outliers.}
}

@slidebreak{Launch}

*How do statisticians talk about what makes each sample unique?*

One way to characterize the distribution of data is a *five-number summary*. To compute a five-number summary, we arrange the data values from least to greatest. Then, we decompose a dataset into four equal parts, separated by @vocab{quartiles}. This process can offer us a more nuanced idea of how the data is spread out.

Here are the specific ingredients for a *5-Number Summary*:

- @vocab{Minimum}: the smallest value in a dataset - it starts the first quarter
- Q1 (lower @vocab{quartile}): the number that separates the first quarter of the data from the second quarter of the data
- Q2 (@vocab{Median}): the middle value in a dataset
- Q3 (upper @vocab{quartile}): the value that separates the third quarter of the data from the last
- @vocab{Maximum}: the largest value in a dataset - it ends the fourth quarter of the data

@slidebreak{Launch}

*Let's try this out for a dataset with an _even_ number of values*

@QandA{
Consider the dataset: 1, 2, 3, 5, 6, 7, 8, 9 (4 is missing!)

@Q{What is the @vocab{Minimum} of this dataset?}
@A{1}

@Q{What is the @vocab{Maximum} of this dataset?}
@A{9}

@Q{How can we calculate the @vocab{Median} (Q2) of this dataset?}
@A{The median is always the "middle number". This dataset has 8 numbers, so there is no exact "middle". When this happens, we take the mean of the two middle numbers (5 and 6), which is 5.5}

@Q{Which numbers are in the "lower half" of this dataset, and what is the median of that half (Q1)?}
@A{All the numbers _less_ than 5.5: 1, 2, 3, 5}
@A{The median is the middle number, but once again we need to take the mean of two middles (2 and 3): 2.5}

@Q{Which numbers are in the "upper half" of this dataset, and what is the median of that half (Q3)?}
@A{All the numbers _more_ than 5.5: 6, 7, 8, 9}
@A{The median is the middle number, but once again we need to take the mean of two middles (7 and 8): 7.5}
}


@slidebreak{Launch}
*Let's try this out for a dataset with an _odd_ number of values*

@QandA{
Consider the dataset: 1, 2, 3, 4, 5, 6, 7, 8, 9 (We let 4 back in!)

@Q{Are the @vocab{Minimum} and @vocab{Maximum} any different than they were without 4?}
@A{No!}

@Q{How can we calculate the @vocab{Median} (Q2) of this dataset?}
@A{The median is always the "middle number". This dataset has _9_ numbers, so we can grab the one in the middle: 5}

@Q{Which numbers are in the "lower half" of this dataset, and what is the median of that half (Q1)?}
@A{All the numbers less than 5: 1, 2, 3, 4}

@Q{Which numbers are in the "upper half" of this dataset, and what is the median of that half (Q3)?}
@A{All the numbers more than 5: 6, 7, 8, 9}
}

@slidebreak{Launch}

Our quartiles allow us to calculate the @vocab{Interquartile Range}(@vocab{IQR}) - _the distance spanned by the middle half of the data_.  The @vocab{IQR} is a more robust measure of variation than the range because it is less susceptible to @vocab{outliers}.  Seeing the relative size of the middle quartiles can be more useful than looking at data "on the edge". Mathematically, @math{\text{IQR} = Q3 - Q1}.

=== Investigate 
@slidestyle{Investigate}

@lesson-instruction{
- We are going to be looking at the data from 2 family gatherings.
  * The average age at the *Watson Family* gathering was *70.4 year old*.
  * The average age at the *Ledet Family* gathering was *44.3 years old*.
}  
@QandA{
@Q{What images do these statistics conjure in your mind? What do you imagine to be true about the ages of the people in attendance at each of the gatherings?}
@A{Answers will vary.}
@A{Some students will likely imagine that all of the people at both of the gatherings are adults.}
@A{Some students will likely expect that all of the people at the Watson Family Gathering were much older.}
}

@slidebreak{Investigate2}

@teacher{
We are going to find the 5-number summary, range and IQR for 2 datasets. Future reflection will rely upon students having worked through both datasets. If your students tend to need more support, you may want to work with the first dataset as a class and then have students work with the second dataset independently.
}

@lesson-instruction{
- Let's see what we can learn about how typical those averages were by looking at the datasets in the first section of @printable-exercise{distribution-by-hand.adoc}.
- Order the ages and compute the five-number summaries for both the *Ledet Family Reunion* and the *Watson Family Gathering*.
}

@slidebreak{Investigate2}

@teacher{
The partitioning of the data into four parts can be a challenge! Research by @citation{bakker-et-al-2005, "Bakker, Biehler, and Konold (2005)"} suggests that students do *not* tend to conceive of distribution in four parts, but three. (Their brains naturally view: the majority in the middle; lower values on the left; and higher values on the right.)

Annotating the list of ordered values can help students visualize the four groups. Emphasize that the median does *not* get included in the bottom or upper half of the data.

Ledet:

@center{@image{images/ledet-five-num.png, 400}}

Watson:

@center{@image{images/watson-five-num.png, 400}}

}

@QandA{
@Q{What do you Notice and Wonder about these datasets and the summary values you've just computed?}
@A{Students may notice that the maximum values are pretty close to each other, but the minimum values are very different from each other!}
@A{Students may notice that Q3 for both datasets is 72.}
@A{Students may notice that the median value for the Watson family data is a number that isn't in the dataset, whereas the median value for the Ledet family data is a number that's in the dataset.}
@A{Students may have questions about how to calculate the median and/or quartiles.}
}

@slidebreak{Investigate}

Now that we know how to compute a five-number summary, let's practice!

@lesson-instruction{
- Practice computing five-number summaries from small datasets (either 7 or 8 values) visualized as dot plots on @printable-exercise{match-dot-plots-summaries.adoc}.
- Be prepared to describe your strategy for matching dot plots with five-number summaries.
}

@slidebreak{Synthesize}

@QandA{
@Q{What strategies did you use to match dot plots to five-number summaries?}
@A{Responses will vary. Students will likely identify the median first to narrow in on a smaller pool of possible five-number summaries, and then compute the quartiles.}

@Q{Dot plots 7 and 8 included 8 points, rather than 7. Did you need to change your strategy to complete these problems? If so, how?}
@A{The median was no longer the 4th datapoint in sequence. Instead, the median was the average of the 4th and 5th datapoints.}

@Q{Which five-number summary on @printable-exercise{match-dot-plots-summaries.adoc} has the greatest IQR?}
@A{Option C, which corresponds with dot plot 1.}

@Q{Which five-number summary on @printable-exercise{match-dot-plots-summaries.adoc} has the smallest IQR?}
@A{Option E, which corresponds with dot plot 6.}
}

=== Synthesize
@slidestyle{Synthesize}

@QandA{

@Q{What is a quartile?}
@A{One of the three boundary points that splits our dataset into four equal quarters.}

@Q{A quartile is _sometimes_ / _always_ / _never_ one of the values in the dataset.}
@A{Sometimes.}

@Q{Why is the IQR a more robust measure of variability than the range?}
@A{Because it focuses on the middle half of the data, so is less susceptible to outliers.}
}




== Plotting our Five-Number Summary

@objective{box-plot-create}

=== Overview

Students plot five-number summaries as box plots before learning to make box plots in pyret.

=== Launch
@slidestyle{Launch}

To visualize the 5-number summary, the Range, and the Interquartile Range we can plot the five numbers on a number line and connect them to make a @vocab{box plot}. 

@ifslide{@image{images/box-n-whisker-plot-labeled.png, 500}}

@ifproglang{pyret}{

@slidebreak{Launch}

@opt-block{
@teacher{
If you decided to launch today's class using our *Live Pyret Survey*, now is the time to display the results!

When you click "Run", the @opt-starter-file{box-plot-survey-starter} builds a box plot. 

@indented{
Assuming you've already...

1. Followed the @dist-link{pages/live-pyret-survey-instructions.adoc, Instructions to Set up and Link the Files} +
2. Shared the *link you made to your class' copy* of the @opt-starter-file{box-plot-survey-form}

The data visualizations will be generated using data from your students! +
And they will continue to update in real time as more of your students complete the Google Form.
}

Project your screen and/or publish the starter file and share a link with your students.

Facilitate a discussion about this new-to-them Pyret Data Visualization!
}

@lesson-instruction{
- Take a look at the results of our survey displayed in the new Data Visualization on the Board.
- What do you Notice?
- What do you Wonder?
}
}
}

@lesson-instruction{
- Turn to @printable-exercise{create-bp-from-dp.adoc}.
- Take a look at the example. What do you Notice? What do you Wonder?
}

@slidebreak{Launch}

*To draw a box plot from a 5-number summary:*

- First, make a vertical line on the number line for each of the 5 values of the five-number summary.
- Next, make a box connecting Q1 to Q3. This box contains the middle half of the data (IQR).
  * Make sure the line you drew for the median is tall enough to split the box into 2 parts (not necessarily equal!)
- Finally, make a horizontal line (called a "whisker") connecting each end of the box to the minimum / maximum value. This helps us to visualize the full range of the data.

@lesson-point{No matter what shape the box plot has, all four sections contain _exactly the same number of points_.}

@slidebreak{Launch}

@QandA{
@Q{How do we know that the first quarter is the densest?}
@A{It is the narrowest, spanning just 2 units. And since all of the quarters contain the same number of data points, that tells us that these points are the most tightly packed.}
@A{We can see that the points on the dot plot are clustered more closely together in this section than they are in the others.}

@Q{Which quarter of the data is the most dispersed? How do you know?}
@A{The last quarter; it spans 11 units, and includes the same number of data points as each of the other quarters.}
@A{We can see that there is lots of space between the points on the dot plot in this section.}
}

@slidebreak{Investigate2}

@lesson-instruction{
- Complete @printable-exercise{create-bp-from-dp.adoc}.
- Then complete @printable-exercise{match-dot-plots-box-plots.adoc}.
}

@slidebreak{Investigate}

@QandA{
@Q{What strategies did you use to match the dot plots to the box plots}
@A{Answers will vary. Sample responses may include:
 * I looked for the maximum and minimum values.
 * I looked at the shape of the data, starting with whether or not it was symmetrical.
 * I looked for tall clusters of points on the dot plot and matching narrow quarters on the box plot.
}
}

=== Investigate
@slidestyle{Investigate}

@lesson-instruction{
- Let's practice making box plots with the data from the family gatherings.
- Complete the second and third sections of @printable-exercise{distribution-by-hand.adoc}.
}

@teacher{
The box plots should look like this: +
@center{Ledet: @hspace{2em} @image{images/ledet-pyret.png, 300} +
Watson: @hspace{1em}@image{images/watson-pyret.png, 300}}
} 

@slidebreak{Launch}

@QandA{
@Q{The average age at the *Watson Family* gathering was *70.4 year old*.} 
@Q{The average age at the *Ledet Family* gathering was *44.3 years old*.}
@Q{For which family was the average age more typical?}
@A{For the Watson family gathering because the data is more closely clustered, the Range and IQR are significantly smaller, and the mean and median are much more similar.}

@Q{How did making the box plots help you to understand the data?}
@Q{What else do you Notice and Wonder?}
}

=== Synthesize
@slidestyle{Synthesize}

@QandA{
@Q{Box plots have four sections. What must be true about all of those sections?}
@A{They each contain exactly one quarter of the data, no matter how different the sections look on the number line.}

@Q{Why isn't the median always in the middle of the box?}
@A{Because the median has to split the data itself in half and the quarter of the data to the left of the median isn't necessarily clustered as tightly as the quarter of the data to the right of the median.}

@Q{What part of the box plot represents the Range?}
@A{The full width from the end of the left whisker to the end of the right whisker}
}


== Making Box Plots in @proglang

@objective{box-plot-proglang}
@objective{box-plot-interpret}

=== Overview

Students create box plots and five-number summaries from the animals dataset in @proglang.

=== Launch
@slidestyle{Launch}

Let's see what we can learn about the spread of the data in the `pounds` column by making a `box-plot`!

@ifproglang{pyret}{
Below is the Contract for `box-plot`. +
@show{(contract 'box-plot '((table-name Table) (column String)) "Image")}
}

@ifproglang{codap}{
To create a box plot in CODAP, create a graph of randomly distributed points, then drag a quantitative column to the x-axis. From the `Measure` menu, select Box Plot. *If this information is not on your Data Visualizations Organizer, add it now!*
}

@slidebreak{Investigate}

@lesson-instruction{
- Log into @starter-file{program-list}, open your saved "Animals Starter File" and click "Run". If you don't have the file, you can open a @starter-file{animals, "new one"}.
- Turn to @printable-exercise{summarizing-columns-mos.adoc} and follow the directions to complete the *Summarizing the Pounds Column* section.
}

@ifproglang{pyret}{
@teacher{
Students will type `box-plot(animals-table, "pounds")` into the Interactions Area. They will use the resulting box plot to fill in the five-number summary for the `pounds` column, and then sketch the box plot.
}
}

@ifproglang{codap}{
Create a box plot in CODAP that visualizes the spread of `Pounds`.
}

@slidebreak{InvestigateC}

@ifproglang{pyret}{
@ifnotslide{@centered-image{images/box-plot-pounds.png, 300}}
@ifslide{@image{images/box-plot-pounds.png, 800}}
}

@ifproglang{codap}{
ifnotslide{@centered-image{images/codap-box-plot.png, 300}}
@ifslide{@image{images/codap-box-plot.png, 300}}
}

=== Investigate
@slidestyle{InvestigateC}

@QandA{

@Q{What conclusions can you draw about the distribution of values in this column?}
@A{While the animals' weights range from 0.1 pounds to 172 pounds, 50% of the animals weigh 11.3 pounds or less. The animal that weighs 172 pounds may be an outlier.}
}

@slidebreak{InvestigateC}

@ifslide{
@ifproglang{pyret}{@image{images/box-plot-pounds.png, 800}}
@ifproglang{codap}{@image{images/codap-box-plot.png, 300}}
}

@QandA{
@Q{Now that we've explored the spread of the dataset, do you think the mean is the best measure of center for the animals' weights?}
@A{No. Most of the animals weigh far less than the average weight (of nearly 40 pounds)!}
}

@slidebreak{Investigate}

@QandA{
@Q{If Q1 is the value for which 25% of the animals weighed that amount or less, what does Q3 represent?}
@A{The third quartile is the value for which 75% of the animals weighed that amount or less. Another way of saying that would be that it is the value for which 25% of the animals weigh that amount or more.}
@Q{Why do you think this visualization is sometimes called a "box and whisker plot"?}
@A{The distance between Min/Q1 and Q3/Max is drawn like whiskers!}
@Q{Could we make a box plot for every column in the dataset?}
@A{No. We can only make box plots for @vocab{quantitative} columns.}
}

@teacher{If students are struggling to write conclusions, go over the following five number summary from the box plot they made.

- *Minimum* (the left “whisker”) - the smallest value in the dataset . In our dataset, that’s just 0.1 pounds.
- *Q1* (the left edge of the box) - computed by taking the _median of the lower half of the values_. In the pounds column, that’s 3.9 pounds.
- *Q2* / Median value (the line in the middle), which is the middle Quartile of the whole dataset. We already computed this to be 11.3 pounds.
- *Q3* (the right edge of the box), which is computed by taking the _median of the upper half of the values_. That’s 60.4 pounds in our dataset.
- *Maximum* (the right “whisker”) - the largest value in the dataset . In our dataset, that’s 172 pounds.
}

@slidebreak{Investigate}

@lesson-instruction{
Choose another quantitative column to summarize and complete the second half of @printable-exercise{summarizing-columns-mos.adoc}
}

@ifproglang{pyret}{
@strategy{Other Box Plots}{

If you're trying to compare two box plots, you might like them both to appear on number lines using the same scale.  Pyret has a function for the that:

@show{(contract 'box-plot-scaled '((table-name Table) (column String) (low-end Number) (high-end Number)) "Image")}

More Statistics-based or Math-oriented classes will also be familiar with _modified box plots_ (@link{https://www.YouTube.com/watch?v=Cm_852R8JPw, video explanation}), which remove outliers from the box-and-whisker and draw them as asterisks outside of the plot. In Pyret, we can make them using the following contracts:

@show{(contract 'modified-box-plot '((table-name Table) (column String)) "Image")}
@show{(contract 'modified-box-plot-scaled '((table-name Table) (column String) (low-end Number) (high-end Number)) "Image")}

Finally, if you'd prefer to use vertical box plots, Pyret as the following contracts:

@show{(contract 'vert-box-plot '((table-name Table) (column String)) "Image")}
@show{(contract 'modified-vert-box-plot '((table-name Table) (column String)) "Image")}
@show{(contract 'modified-vert-box-plot-scaled '((table-name Table) (column String) (low-end Number) (high-end Number)) "Image")}

}
}

@ifproglang{CODAP}{
@strategy{Modified Box Plots}{
More Statistics-based or Math-oriented classes will also be familiar with _modified box plots_ (@link{https://www.YouTube.com/watch?v=Cm_852R8JPw, video explanation}), which remove outliers from the box-and-whisker and draw them as asterisks outside of the plot.

In CODAP, you can create a modified Box Plot by selecting both Box Plot and Show Outliers from the `Measure` menu.
}
}

=== Common Misconceptions
It is extremely common for students to forget that the quartiles divide the data into quarters, each of which includes 25% of the dataset. This will need to be heavily reinforced.

=== Synthesize
@slidestyle{Synthesize}

@QandA{

@Q{Is it safe to assume that the average typical?}
@A{No. It is sometimes typical. But sometimes there's a lot of variation or skew in the data.}

@Q{What percentage of points fall in the first quarter?}
@A{25%}

@Q{What percentage of points fall in the second quarter?}
@A{25%}

@Q{What percentage of points fall in the third quarter?}
@A{25%}

@Q{What percentage of points fall in the fourth quarter?}
@A{25%}

@Q{What percentage of points fall in the *Interquartile Range* (IQR)?}
@A{50%}

@Q{What percentage of points fall within the *Range*?}
@A{100%}
}

=== Additional Resources

- @opt-printable-exercise{identifying-shape-box-plots.adoc}


