= Box Plots

@description{Students are introduced to box plots, learn to evaluate the spread of a quantitative column, and deepen their perspective on shape by matching box plots to histogram.}

@lesson-prereqs{measures-of-center}

@keywords{range, box plot, box and whisker plot, five number summary, first quartile, interquartile range}

@add-to-lang{box-plot, modified-box-plot}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

- apply one approach to measuring and displaying spread of a dataset
- compare and contrast information displayed in a box plot and a histogram

| Student-facing Lesson Goals
|

* Let's compare different uses for box plots and histograms when talking about data.

| Materials
|[.materials-links]

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
|
* There is an optional kinesthetic activity in this lesson that requires a ball of playdough for each group of 3.

|===


== Making Box Plots @duration{30 minutes}

=== Overview
Students are introduced to the notion of _spread_ in a dataset. They learn about quartiles, box plots, and how to use them to talk about spread.

=== Launch
When we explored measures of center, we tried to answer a question about "typical" values. We considered a fact - that _the Animal Shelter Bureau says the average pet weighs almost 40 pounds_.

How useful is this fact, really? Maybe all the pets weigh between 35 and 45 pounds, with every pet close to the mean. But maybe all the pets are super small or huge, and no one is even _near_ to the mean!

So once we have our summary for a "normal value", it's likely we'll ask another question: _If the average pet is 40 pounds, just **how typical** is that?_

There are differences in every class of students. Not everyone likes the same music, not everyone dresses the same, etc. So we'd expect some deviation - or @vocab{spread} - in any class of students! Some classes are more different than others. How do we measure the @vocab{spread} of a population?

@center{@image{images/box-n-whisker-plot.png, 500}}


=== Investigate

Suppose we lined up all the animals' weights from smallest to largest. We can learn something about the @vocab{spread} of the dataset by splitting the population into four equal-sized @vocab{quartiles}. First we'll split them in half by finding the @vocab{median} and then we'll find the _median of each half_!

Splitting a dataset into @vocab{quartiles} gives us five numbers that we can play with to measure spread. Taken together these are called the **5 Number Summary** of a dataset:

. @vocab{Minimum}: _the smallest value in a dataset_
. Q1: _the median that falls between the minimum and Q2 - and 25% of the data points will have that value or less_
. Q2: @vocab{Median}: _the middle value (median) in a dataset_
. Q3: _the median that falls between Q2 and the maximum_
. @vocab{Maximum}: _the largest value in a dataset_


We can use these numbers to calculate two new values:

- Maximum - Minimum = _@vocab{Range}_ :  _the distance spanned by the extreme values in the dataset_ 
** (*Note*: the term “Range” means something different in statistics than it does in algebra and programming!)
- Q3 - Q1 = @vocab{IQR}:  _the @vocab{Interquartile Range}, or the distance spanned by the middle half of the data_

We can use @vocab{box plots} to visualize the 5 number summary, the Range, and the Interquartile Range. 

Below is the Contract for `box-plot`.

```
box-plot :: (t::Table, col::String) -> Image
# Consumes a table and the name of the column
# to plot, and produces a box plot"
```

@lesson-instruction{
* Let's see what we can learn about the spread of the data in the `pounds` column by making a `box-plot`!
* Log into @starter-file{program-list}, open your saved "Animals Starter File" and click "Run".
** _If students don't have the file, they can open a new one from @starter-file{animals}._
* Then turn to @printable-exercise{summarizing-columns-mos.adoc} and follow the directions to complete the *Summarizing the Pounds Column* section.
** _Students will type `box-plot(animals-table, "pounds")` into the Interactions Area and use the resulting box plot to fill in the five-number summary for the `pounds` column, and sketch the box plot._
}

@center{@image{images/5-plot.png,  400}}

This plot shows us the center and spread in our dataset according to those five numbers.

- **Minimum** (the left “whisker”) - the smallest value in the dataset . In our dataset, that’s just 0.1 pounds.
- **Q1** (the left edge of the box) - computed by taking the _median of the lower half of the values_. In the pounds column, that’s 3.9 pounds.
- **Q2** / Median value (the line in the middle), which is the middle Quartile of the whole dataset. We already computed this to be 11.3 pounds.
- **Q3** (the right edge of the box), which is computed by taking the _median of the upper half of the values_. That’s 60.4 pounds in our dataset.
- **Maximum** (the right “whisker”) - the largest value in the dataset . In our dataset, that’s 172 pounds.

@lesson-point{
Box plots divide our sample into equally-sized groups, and show where those groups are spread thin or clumped together.
}

@QandA{

@Q{What conclusions can you draw about the distribution of values in this column?}
@A{While the animals' weights range from 0.1 pounds to 172 pounds, 50% of the animals weigh 11.3 pounds or less. The animal that weighs 172 pounds may be an outlier.}

@Q{If Q1 is the value for which 25% of the animals weighed that amount or less, what does Q3 represent?}
@A{The third quartile is the value for which 75% of the animals weighed that amount or less. Another way of saying that would be that it is the value for which 25% of the animals weigh that amount or more.}

@Q{Could we make a box plot for every column in the data set?}
@A{No. We can only make box plots for @vocab{quantitative} columns.}
}

@lesson-instruction{
Choose another quantitative column to summarize and complete the second half of @printable-exercise{summarizing-columns-mos.adoc}
}

=== Common Misconceptions
It is extremely common for students to forget that every quartile _always_ includes 25% of the dataset. This will need to be heavily reinforced.

=== Synthesize

@lesson-instruction{
- What percentage of points fall in the first quartile?
** 25%
- What percentage of points fall in the second quartile?
** 25%
- What percentage of points fall in the third quartile?
** 25%
- What percentage of points fall in the fourth quartile?
** 25%
- What percentage of points fall in the **Interquartile Range** (IQR)?
** 50%
- What percentage of points fall within the Range?
** 100%
}

== Interpreting Box Plots @duration{30 minutes}

=== Overview
Students learn how to read a box plot, and consider spread and variability. They connect this visualization of spread to what they learned about histograms.

=== Launch
Just as pie and bar charts are ways of visualizing categorical data, box plots and histograms are both ways of visualizing the shape of quantitative data.

Box plots make it easy to see the 5-number summary, and compare the Range and Interquartile Range. Histograms make it easier to see skewness and more details of the shape, offering more granularity when using smaller bins.

Left-skewness is seen as a long tail in a histogram. In a box plot, it's seen as a longer left "whisker" or more spread in the left part of the box. Likewise, right skewness is shown as a longer right "whisker" or more spread in the right part of the box.

@lesson-point{
Box plots and histograms give us two different views on the concept of shape.
}

[.cols="^1,^1", options="header"]
|===
|               | Intervals | Points-per-Interval
| **Box Plots** | Variable  | Fixed
| **Histograms**| Fixed     | Variable
|===

*Histograms:* fixed intervals (“bins”) with variable numbers of data points in each one. Points “pile up in bins”, so we can see how many are in each. __Larger bars show where the clusters are.__

*Box plots:* variable intervals (“quartiles”) with a fixed number of data points in each one. Treats data more like “pizza dough”, dividing it into four equal quarters showing where the data is tightly clumped or spread thin. __Smaller intervals show where the clusters are.__

@strategy{
@span{.title}{Kinesthetic Activity}

Divide the class into groups, and give each group a ruler and a ball of playdough. Have them draw a number line from 0-6 with the ruler, marking off the points at 0, 3, 4, 4.5 and 6 inches. Have the groups roll the dough into a thick cylinder, divide that cylinder in half, and then split each half to form four __equally-sized cylinders__. The playdough represents a @vocab{sample}, with values divided into four @vocab{quartiles}.

Box plots stretch and squeeze these equal quartiles across a number line, so that each quartile fills up an interval in that quartile. On their number line, students have intervals from 0-3, 3-4, 4-4.5, and 4.5-6. Have students roll their cylinders so that they fill each of these intervals, retaining a uniform thickness.

They should notice that shorter intervals have __thicker cylinders__, and longer ones have skinny ones. Even though a box plot doesn't show us the thickness of the data points, we can tell that a small intervals has the same amount of data "squeezed" into it as a large interval.

}

=== Investigate
@lesson-instruction{
- Complete @printable-exercise{pages/identifying-shape-boxplots.adoc} and see if you can describe box plots using what you know about skewness.
- To make connections between histograms and box plots, complete @printable-exercise{pages/matching-boxplots-to-histograms.adoc}
- @optional Complete @opt-printable-exercise{pages/matching-boxplots-to-histograms-2.adoc} and/or @opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/601974faad8cb40d1c603324, Matching Box Plots to Histograms}
}

@strategy{
@span{.title}{Modified Box Plots}
More Statistics- or Math-oriented classes will also be familiar with __modified box plots__ (@link{https://www.youtube.com/watch?v=Cm_852R8JPw, video explanation}), which remove outliers from the box-and-whisker and draw them as asterisks outside of the plot. Modified box plots are also available in Bootstrap:Data Science, using the following Contract:

@show{(contract 'modified-box-plot '((table-name Table) (column String)) "Image")}
}


@lesson-instruction{
You've learned about @vocab{quartiles}, max and min, @vocab{interquartile range}, and more. With a partner, complete the @printable-exercise{boxplot-vocab-map.pdf, Box Plot Vocab Concept Map} and see if you can draw connections between these concepts!
}

=== Synthesize
Histograms, box plots, and measures of center and spread are all different ways to get at the @vocab{shape} of our data. It's important to get comfortable using every tool in the toolbox when discussing shape!

We started talking about measures of center with a single question: __is "average" the right measure to use when talking about animals' weights?__ Now that we've explored the spread of the dataset, do you agree or disagree that average is the right summary?

@strategy{
@span{.title}{Project Option: Stress or Chill?}

Students can gather data about their own lives, and use what they've learned in the class so far to analyze it. @opt-project{stress-project.html, rubric-stress-or-chill.adoc} can be used as a mid-term or formative assessment, or as a capstone for a limited implementation of Bootstrap:Data Science. 
}

== Data Exploration Project (Box Plots) @duration{flexible}

=== Overview
Students apply what they have learned about box plots to their chosen dataset. They will add three items to their @starter-file{exploration-project}: (1) at least two box plots, (2) the corresponding five-number summaries, and (3) any interesting questions they develop. To learn more about the sequence and scope of the Exploration Project, visit @lesson-link{project-data-exploration}. For teachers with time and interest, @lesson-link{project-research-paper} is an extension of the Dataset Exploration, where students select a single question to investigate via data analysis.

=== Launch

Let’s review what we have learned about making and interpreting box plots.

@lesson-instruction{
- Does a box plot display categorical or quantitative data? How many columns of data does a box plot display?
** _Box plots display a single column of quantitative data._
- How are box plots similar to histograms? How are they different?
** _Box plots and histograms give us two different views on the concept of shape. Histograms have fixed intervals ("bins") with variables numbers of data points in each one. Boxplots have variable intervals ("quartiles") with a fixed number of data points in each one._
- When we build a box plot from a quantitative column in Pyret, there's a five-number summary at the top. What does it tell us about the column?
** _The five-number summary includes the minimum, medium, and maximum. It also includes the median of the lower half of the values, and the median of the upper half of the data points._
}

=== Investigate

Let’s connect what we know about box plots to your chosen dataset.

@lesson-instruction{
- Open your chosen dataset starter file in Pyret.
** _Teachers: Students have the opportunity to choose a dataset that interests them from our @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "List of Datasets"} in the @lesson-link{choosing-your-dataset} lesson._
- Remind yourself which two columns you investigated in the @lesson-link{measures-of-center} lesson and make a box plot for one of them.
- What question does your display answer?
** _Possible responses: How is the data for a certain column distributed? Are the values close together or really spread out? Are their any outliers?_
- Now, write down that question in the top section of @printable-exercise{data-cycle-quantitative.adoc}
- Then, complete the rest of the data cycle, recording how you considered, analyzed and interpreted the question.
- Repeat this process for the other column you explored before (and any others you are curious about).
** _Note: If students want to investigate new columns from their dataset, they will need to copy/paste additional Measures of Center and Spread slides into their Explorartion Project and calculate the mean, median and modes for the new columns._
}

@teacher{Confirm that all students have created and understand how to interpret their box plots. Once you are confident that all students have made adequate progress, invite them to access their @starter-file{exploration-project} from Google Drive.}

@lesson-instruction{
- *It’s time to add to your @starter-file{exploration-project}.*
- Find the box plot slide in the "Making Displays" section and copy/paste your first box plot here. Duplicate the slide to add your other box plots.
- Add the five-number summaries from these plots to the corresponding "Measures of Center and Spread" slides. 
- Be sure to also add any interesting questions that you developed while making and thinking about box plots to the "My Questions" slide at the end of the deck.
}

=== Synthesize
Share your findings!

What @vocab{shape} did you notice in your box plots?

Did you discover anything surprising or interesting about your dataset?

What, if any, outliers did you discover when making box plots?

When your compared your findings with others, did they make any interesting discoveries? (For instance: Did everyone find outliers? Was there more or less similarity than expected?)


== Additional Exercises
- @opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/601c35a8e9fd103e94acee2b, Card Sort: What Information does the Box & Whisker Plot tell us?}
- @opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fe89eeaaef67d0cea85ba5e, "Matching Vocabulary to Definitions"}
