= So Many Groupings!

++++
<style>
  body.workbookpage table.FillVerticalSpace {
    grid-template-rows: unset !important; grid-auto-rows: 2fr;
  }
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

How many different ways can you re-group and re-order the following expression?

@vspace{1ex}

@math{88 + 637 + 71 + 129 + 12}

@vspace{1ex}

Draw as many equivalent circles of evaluation as you can in the boxes below, then answer the questions at the bottom of the page. To get you going, we've completed one sample Circle of Evaluation and started a second one.

@vspace{1ex}

[.FillVerticalSpace,cols="^.^8a,^.^8a", stripes="none"]
|===
| @show{(coe '(+ (+ (+ (+ 88 637) 71) 129) 12))} |
@show{(coe '(+ (+ (?ANS 88) (?ANS 637)) (+ (+ (?ANS 71) (?ANS 129)) (?ANS 12))))}

| @showsoln{(coe '(+ (+ (+ (?ANS 71) (?ANS 129))(+ (?ANS 88)(?ANS 637))) (?ANS 12)))}	|
@showsoln{(coe '(+ (+ (+ (?ANS 12) (?ANS 129))(+ (?ANS 88)(?ANS 71))) (?ANS 637)))}

| @showsoln{(coe '(+ (+ (?ANS 88) (?ANS 71))(+ (+ (?ANS 637)(?ANS 12)) (?ANS 71))))}	|
@showsoln{(coe '(+ (+ (?ANS 129) (?ANS 88))(+ (+ (?ANS 637)(?ANS 12)) (?ANS 71))))}

|===

@n Which Circle (above) seems like it would be the _most difficult_ to solve in your head? *Put a star by that one.* (You may award more than one star if it feels right.) Then, in the space below, explain what makes that Circle challenging to evaluate. @fitb{}{@ifsoln{Answers will vary. Students should}}

@fitb{}{@ifsoln{discuss awkward pairings of numbers that result in awkward sums.}}

@fitb{}

@n Which Circle of Evaluation seems like it would be the _easiest_ to solve in your head? *Put a check mark by that one.* (You may award more than one star if it feels right.) Then, in the space below, explain what makes that one easier to evaluate. @fitb{}{@ifsoln{Answers will vary. Students should}}

@fitb{}{@ifsoln{discuss "friendly" pairings of numbers that result in easy-to-work-with sums. }}

@fitb{}

@n You may have found that some Circles of Evaluation were _equally_ difficult or easy to evaluate. Can you explain what was going on in those Circles of Evaluation? @fitb{}{@ifsoln{The Commutative Property may have created unique Circles with the same groupings of numbers - but ordered differently.}}

@fitb{}
