= Categorical or Quantitative?
++++
<style>
div#body.workbookpage td .autonum:after { content: ')'; }
</style>
++++

- *Quantitative data* measures an _amount_ and can be ordered from smallest to largest.
- *Categorical data* specifies _qualities_ and is not subject to the laws of arithmetic -- for example, we cannot take the “average” of a list of colors. _Note: Numbers can sometimes be categorical rather than quantitative!_

@vspace{1ex}

For each piece of data below, circle whether it is *Categorical* or *Quantitative*.

[.FillVerticalSpace, cols="2a,20a,>10a",grid="none", frame="none"]
|===
| @n | Hair color
| @ifsoln-choice{categorical} 	@hspace{8ex} quantitative

| @n | Age
| categorical 					@hspace{8ex} @ifsoln-choice{quantitative}

| @n | ZIP Code
| @ifsoln-choice{categorical} 	@hspace{8ex} quantitative

| @n | Date
| @ifsoln-choice{categorical}	@hspace{8ex} quantitative

| @n | Height
| categorical 					@hspace{8ex} @ifsoln-choice{quantitative}

| @n | Sex
| @ifsoln-choice{categorical}	@hspace{8ex} quantitative

| @n | Street Name
| @ifsoln-choice{categorical}	@hspace{8ex} quantitative
|===

@span{.sectionbreak}{}

@vspace{1ex}

For each question below, circle whether it will be answered by *Categorical* or *Quantitative* data.


[.FillVerticalSpace, cols="2a,20a,>10a",grid="none", frame="none"]
|===
| @n | We’d like to find out the average price of cars in a lot.
| categorical 					@hspace{8ex} @ifsoln-choice{quantitative}

| @n | We’d like to find out the most popular color for cars.
| @ifsoln-choice{categorical} 	@hspace{8ex} quantitative

| @n | We’d like to find out which puppy is the youngest.
| categorical 					@hspace{8ex} @ifsoln-choice{quantitative}

| @n | We’d like to find out which cats have been fixed.
| @ifsoln-choice{categorical} 	@hspace{8ex} quantitative

| @n | We want to know which people have a ZIP code of 02907.
| @ifsoln-choice{categorical} 	@hspace{8ex} quantitative
|===

@star We can sort the animals in _ascending order_ (smallest-to-largest) by `age` and then sort the table in _alphabetical order_ (A-to-Z) by `name`. +
Does that mean `name` is a quantitative column? Why or why not? @fitb{}{} +
@blanklines{4}{
@ifsoln{Just because a column _can_ be sorted doesn't mean that it's quantitative. It's whether sorting v. not sorting *changes the meaning* of the data. For example, reshuffling the bars in a bar chart doesn't change the meaning of the chart. But reshuffling the bars in a histogram no longer presents the data accurately!}
}