= Questions and Column Descriptions
++++
<style>
.FillVerticalSpace { grid-template-rows: 45px repeat(7, 70px) !important; }
</style>
++++

@n Take some time to look through the Animals Dataset. What stands out to you? Which animals are interesting? What patterns do you notice? Put your observations in the *Notice* column below.

@n Do any of these observations make you wonder? If so, write your question next to the observation in the *Wonder* column. If not, think of another question to write down.

[.FillVerticalSpace, cols="^3a,^3a,^.^1a",options="header",stripes="none"]
|===

| Notice
| Wonder
| Answered by this dataset?

| I notice that

@vspace{2ex}

_Kujo took a long time to be adopted_
|  @vspace{4ex}

_Is it because he was so big?_
| _Yes_ {nbsp} _No_

| I notice that
|
| _Yes_ {nbsp} _No_

| I notice that
|
| _Yes_ {nbsp} _No_

| I notice that
|
| _Yes_ {nbsp} _No_

| I notice that
|
| _Yes_ {nbsp} _No_

| I notice that
|
| _Yes_ {nbsp} _No_

| I notice that
|
| _Yes_ {nbsp} _No_

|===


Describe the table, and two of the columns, by filling in the blanks below.

1. This dataset is about @fitb{30em}{@ifsoln{Animals that came from an animal shelter}}; it contains @fitb{10ex}{@ifsoln{32}} data rows.

2. Some of the columns are:

  a. @fitbruby{15em}{@ifsoln{species}}{column name}, which contains @fitbruby{15em}{@ifsoln{categorical}}{_categorical or quantitative_} data. Some example values are: @fitb{27em}{@ifsoln{"cat", "dog", and "rabbit"}}.

  b. @fitbruby{15em}{@ifsoln{age}}{column name}, which contains @fitbruby{15em}{@ifsoln{quantitative}}{_categorical or quantitative_} data. Some example values are: @fitb{27em}{@ifsoln{`1`, `5`, and `10`}}.
