= Grouped Samples

@description{Students practice creating grouped samples (non-random subsets) and think about why it might sometimes be useful to answer questions about a dataset through the lens of one group or another.}

@ifproglang{pyret}{
@lesson-prereqs{table-functions-dr, choosing-your-dataset}
@add-to-lang{filter}
}

@ifproglang{codap}{
@lesson-prereqs{codap-building}
}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives
@objective{sensible-grouped-samples}

| Student-facing Lesson Goals
|

- Let's combine what we know about sampling and filtering with creating visualizations.

| Materials
|[.materials-links]

@material-links

|===


== Problems with a Single Population

=== Overview
This activity is all about @vocab{grouped samples}: Students make a bunch of non-random samples from the Animals Dataset, and see how each sample might answer the same question differently.

=== Launch
@slidebreak{LaunchC}

When looking at a scatter plot of animals, it looks like the amount an animal weighs may have something to do with how long it takes to be adopted.
@center{@image{images/scatter-plot.png,550}}

@slidebreak{LaunchC}

But if we label the dots by species, we notice _every data point_ after 25 pounds belongs to a dog from the shelter! The cats are all clumped together in the lower weight range, making it hard to see how weeks to adoption may relate to a cat's weight.

@center{@image{images/image-scatter-plot.png,550}}

=== Investigate
@slidebreak{Investigate}
@teacher{
Divide the class into groups of 3-4, with one student identified as the "reporter".
}

@QandA{
@Q{Looking at this scatter plot (above), does it make sense to analyze all the animals together? Why or why not?}
@A{No. Every data point after 25 pounds belongs to a dog from the shelter. The cats are clumped in the lower weight range.}
@Q{Are there some questions where it would be important to break up the population into species-specific populations? What are they?}
@A{Sample response: Yes. If we want to know whether dogs or cats are more likely to be fixed, we would need to look at each species separately.}
@Q{Are there some questions where it would be important to keep the whole population together? What are they?}
@A{Sample response: Yes. If we want to know if, in general, young animals are adopted more quickly, we would look at the entire population.}
}

@teacher{
Have the reporters share their findings with the class.
}

=== Synthesize
@slidebreak{Synthesize}

You've been handed a dataset from a country where half the people have access to amazing medical care, and the other half have no healthcare.

@QandA{
@Q{Why might it be important to look at a particular sample of a population?}
@A{Sample response: Maybe we want to determine if emissions from a nearby factory impact the health of residents of one particular neighborhood.}
@Q{Why is it sometimes bad to blindly take random samples?}
@A{If we took a random sample of the population as a whole, we might think that they are generally middle-income and have average health. But if we ask the same question about the two groups _separately_, we would discover inequality hiding in plain sight!}
}


== Grouped Samples

=== Launch
@slidebreak{Launch}
Depending on the question we're asking, sometimes it makes more sense to ask about "just the cats" or "just the dogs". Averaging every animal together will give us an answer, but it may not be a _useful_ answer.

@lesson-point{
Sometimes important facts about samples get _lost_ if we mix them with the rest of the population!
}

Data Scientists define @vocab{grouped samples} of datasets, breaking them up into sub-groups that may be helpful in their analysis.

@ifproglang{pyret}{
@slidebreak{Launch}

Earlier, you learned how to define values in Pyret. We can define Numbers, Strings, Images, and even rows:

```
name = "Flannery"
age  = 16
logo = star(50, "solid", "red")
sasha= row-n(animals-table, 0)
```

@slidebreak{Launch}

Let's use this skill to define _Tables..._

We already know how to define values, and how to filter a dataset. So let’s put those skills together to define a grouped sample of the dogs in the shelter:

@show{(code '(define dogs (filter animals-table is-dog)))}

The `filter` function walks across each row in the table, and passes it to the `is-dog` function. If `is-dog` produces `true`, `filter` adds it to a new table. Otherwise, it just silently moves on to the next row. Finally, we define the name `dogs` to be the table produced by `filter`.
}

=== Investigate
@ifproglang{pyret}{@slidebreak{Investigate-DN}}
@ifproglang{codap}{@slidebreak{Investigate}}

A “kitten” is an animal who _is a cat_ and who _is young_. How would you define a table of just kittens?

@lesson-instruction{
@ifproglang{codap}{
* Turn to @printable-exercise{samples-from-animals-dataset.adoc}, and see what sequence of Transformers will compute whether or not an animal is a kitten.
* Can you fill in the function notation for the other grouped samples?
}

@ifproglang{pyret}{
* Open the @starter-file{grouped-samples}, save a copy, and click "Run".
* What functions do you see defined here? What do they do?
* Turn to @printable-exercise{samples-from-animals-dataset.adoc}, and see what code define a table of only young cats.
* Can you fill in the code to define the other grouped samples?
* In the starter file, scroll to the bottom of the Definitions Area. Add your solutions from @printable-exercise{samples-from-animals-dataset.adoc}. Test them out!
}
}

=== Synthesize
@slidebreak{Synthesize}

- How could we make a bar chart showing the distribution of `sex` in the `kittens` sample?
- How could we filter _and_ sort a table?
- How can we combine functions?

== Displaying Samples

=== Overview
Students revisit the data visualization activity, now using the samples they created.

=== Launch
@slidebreak{Launch}
Making grouped and random samples is a powerful skill, which allows us to dig deeper than just making charts or asking questions about a whole dataset. Now that we know how to make grouped samples, we can make much more sophisticated visualizations!

@slidebreak{LaunchR}

Let's start with question: _what's the ratio of fixed to unfixed *cats* at the shelter?_ Let's use the Data Cycle to get an answer, using our knowledge of grouped samples.

@left{@image{images/AskQuestions.png, 100}}This is an Arithmetic Question. We know it's not a lookup question because there's no ratio written somewhere in the table for us to read. Instead, we'll have to count all the fixed cats and the unfixed cats, then compare the totals.

@slidebreak{LaunchR}

@vspace{1ex}

@left{@image{images/ConsiderData.png, 100}}We know that we'll need to count *only the cats!*, and can ignore everything else. And once we've picked the rows for cats, the only column we want is the `fixed` column. This is a huge hint that *we'll need to filter the dataset!*

@slidebreak{LaunchR}

@vspace{1ex}

@left{@image{images/AnalyzeData.png, 100}}@ifproglang{pyret}{We could use a bar-chart or a pie-chart to do this analysis, but since we care more about the @vocab{ratio} ("2x as many fixed as unfixed") than the count ("20 fixed vs. 10 fixed"), a pie chart is a better choice.}@ifproglang{codap}{Given our options, a bar chart seems most appropriate for this scenario.} We've decided what to make and we know which rows and columns we're plotting, so the next step is to @ifproglang{pyret}{_write the code!_}@ifproglang{codap}{determine the configuration!}


@vspace{1ex}

@slidebreak{LaunchR}

@left{@image{images/InterpretData.png, 100}}What did our visualizations tell us? In this case, we got a clear answer to our question. But perhaps that's not the end of the story! We might have _new_ questions about whether a higher percentage of dogs are spayed and neutered than cats, or whether it's even possible to "fix" a tarantula. _All of this belongs in our data story!_

=== Investigate
@slidebreak{Investigate-DN}
@lesson-instruction{
- Use the @starter-file{animals} to complete @printable-exercise{data-visualizations2.adoc}. Apply what you've learned about samples to make more sophisticated data visualizations.
- Complete @printable-exercise{data-cycle-categorical.adoc}.
}

@ifproglang{pyret}{
@opt{

For students who are working on their own dataset, use @printable-exercise{samples-from-my-dataset.adoc} to define grouped samples!

Blank Design Recipes are also available @printable-exercise{design-recipe-helper-funs.adoc, here}.
}
}

=== Synthesize
@slidebreak{Synthesize}

- What connections do you see between the "Consider Data" and "Analyze Data" steps?
- How do we know when we need to filter? How do we know when we _don't?_
