= The Distributive Property

@description{Students develop an understanding of the Distributive Property by studying equivalent Circles of Evaluation. They then apply their understanding of the Distributive Property to make efficient mental computations.}

@lesson-prereqs{variables}

@keywords{Distributive Property}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Recognize how distribution results in equivalent expressions.
* Apply the Distributive Property to expressions with numbers and variables.
* Use distribution to efficiently complete mental computations.


| Student-facing Lesson Goals
|

* Let's explore the Distributive Property and Circles of Evaluation.

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Key Points For The Facilitator
|
* We introduce the Distributive Property by inviting students to look at patterns in _structure_, and then later apply what they know (to make mental computations or think about area).

|===

== The Distributive Property @duration{30 minutes}

=== Overview

Students develop an understanding of the @vocab{Distributive Property} by examining equivalent Circles of Evaluation.

=== Launch

@lesson-instruction{

[.embedded, cols="^.^3,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(* 9 (+ 40 6)))} | @show{(coe '(+ (* 9 40) (* 9 6)))}
|===

- What do you Notice and what do you Wonder about the two Circles of Evaluation, above?
** _Possible Noticings: The Circles of Evaluation have different structures. One has a single nested Circle, while the other has two nested Circles. Both include the numberes 9, 40, and 6. Both include addition and multiplication._
** _Possible Wonderings: Are these equivalent? What do they evaluate to? Why is there one 9 in the first Circle of Evaluation, but two 9s in the second Circle?_
- Are these two Circles of Evaluation @vocab{equivalent}? Why or why not?
}

Share with students that the Circles of Evaluation are equivalent because of the @vocab{Distributive Property}, which tells us that @math{a \times (b + c) = ab + ac}:

[.embedded, cols="^.^3,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(* a (+ b c)))} | @show{(coe '(+ (* a b) (* a c)))}
|===

Facilitate a discussion where students think deeply about what is happening in the scenarios above, namely, that distribution allows us to rewrite a product as a sum or a sum as a product.

@lesson-point{
Multiplying the sum of two addends by a number produces the same result as multiplying _each_ addend by that number before finding the sum.
}


In the next activity, students will use Circles of Evaluation to explore how the mathematical structure of an expression shifts when we apply Distributive Property.

@lesson-instruction{
- On @printable-exercise{pages/sum-to-product.adoc}, fill in the blanks so that the Circle of Evaluation on the right is equivalent to the Circle of Evaluation on the left.
- Use computation to confirm that the Circles of Evaluation in each pair are equivalent.
- After you finish evaluating each Circle of Evaluation, place a checkmark next to the Circle of Evaluation that you think results in a simpler comuptation.
- When was it easier to compute the _sum_? When was it easier to compute the _product_?
** _There are no right or wrong answers, here. We want students to begin to consider how a nuanced understanding of the Distributive Property can result in more flexible and efficient mental math._
- On @printable-exercise{pages/product-to-sum.adoc}, the Circle of Evaluation representing a product is provided, and you will complete the Circle of Evaluation that represents a sum.
- Now try @printable-exercise{pages/distribution-challenge.adoc}, where you will practice applying the Distributive Property in both directions - and with expressions that include fractions and decimals!
}

=== Investigate

Elise and Dani are discussing a pair of Circles of Evaluation.

[.embedded, cols="^.^3,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(* 5 43))} | @show{(coe '(+ 200 8))}
|===

Dani thinks the Circles of Evaluation are equivalent. She says, "You can think of 43 as the sum of 40 and 3. Then, you multiply 5 by 40 to get 200, and you add 5 and 3 to get 8."

Elise says, "The second Circle should say 200 + 15, not 200 + 8."

@lesson-instruction{
- Who is correct - Elise or Dani?
** _Elise is correct. We need to multiply each value by 5._
** _Note - it may be helpful for some students to see the Circle for @math{(5 \times 40) + (5 \times 3)}._
}

The activities in the Launch focused on students' internalizing the structure of expressions both before and after applying the Distributive Property. During this segment of the lesson, students apply what they have learned.

@lesson-instruction{
- Turn to @printable-exercise{pages/true-or-false.adoc}, where you will determine if equations represented by the Circles of Evaluation are true or false. Explain your response.
- Next, try @printable-exercise{pages/wodb.adoc}. Cross out the Circle of Evaluation that doesn’t belong with the others, and then explain your choice.
}


=== Synthesize

- Summarize the Distributive Property in your own words.
- Elise and Dani are looking at this problem: @math{4 \times (100 - 1.25)}. Dani tells Elise that we must _always_ evaluate what's inside the parentheses first. Do you agree with this idea - or can Dani be more flexible? Explain.
** _Some students may suggest that distributing is a way of addressing the grouping symbol. Others may agree with Dani. We encourage you to discuss with your students the pros and cons of a flexible approach to solving. In this particular instance, applying the Distributive Property results in a much simpler computation._

== The Distributive Property and Mental Math @duration{20 minutes}

=== Overview

=== Launch

@lesson-instruction{
- Can you represent the expression @math{45 \times 81 - 45 \times 79} in a simpler way?
** _Yes. We can apply the Distributive Property, transforming the expression into @math{45 \times (81 - 79)}._
- Can you represent your solving process with a chain of Circles of Evaluation?
** _Invite a student to draw on the board. See below for one possible representation. You might need to draw a Circle or two to get students_
}

[.embedded, cols="^.^5,^.^1,^.^4,^.^1,^.^3,^.^1,^.^2", grid="none", frame="none"]
|===
| @show{(coe '(- (* 45 81) (* 45 79)))} | &rarr; | @show{(coe '(* 45 (- 81 79)))} | &rarr; | @show{(coe '(* 45 2))} | &rarr; | 90
|===

The goal of this exercise is to help students recognize an important feature of the Distributive Property, namely:

@lesson-point{
We can use distribution and mental math to make computation simpler.
}

Note: In expressions such as @math{45 \times (81 - 79)}, the multiplication sign is unnecessary and implied when not there. Encourage students to try out this notation, especially if it is one that they have not encountered before.

=== Investigate

If we were asked to compute @math{70 \times 39}, we could do so using a calculator or the standard algorithm. Now that we are familiar with the Distributive Property, we have a valuable tool for efficient mental computation.

@lesson-instruction{
- Turn to @printable-exercise{pages/mental-math.adoc} and look at the first problem.
- Our goal here is to make the math easier by creating an equivalent expression that we can solve in our heads! So, instead of finding the product of 70 and 39, we are going to multiply 70 by the difference of 40 and 1.
- Complete the next Circle of Evaluation, which shows that we are going to _distribute_ 70.
- We can now compute our solution by finding difference between two products.
- Do you find this process more efficient than the standard algorithm for multiplication? Explain.
** _Note: Without ample practice, there is a good chance that students will not find this process efficient. Like any solving strategy, it takes practice!_
- Complete the rest of the page by creating equivalent expressions that we can solve in our heads.
}

=== Synthesize

- How can you multiply two 2-digit numbers using mental math?
- Can you think of a multiplication problem that would be _easier_ to solve using the Distributive Property?
** _Note: We recommend inviting many students to share the problems they come up with. Make a list on the board for students to review together._
- What sorts of problems are simpler to compute using the Distributive Property?
