= The Distributive Property

@description{Students develop an understanding of the Distributive Property by studying equivalent Circles of Evaluation. They then apply their understanding of the Distributive Property to make efficient mental computations.}

@lesson-prereqs{variables}

@keywords{Distributive Property}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Recognize how distribution results in equivalent expressions.
* Apply the Distributive Property to expressions with numbers and variables.
* Use distribution to efficiently complete mental computations.


| Student-facing Lesson Goals
|

* Let's explore the Distributive Property and Circles of Evaluation.

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
* We introduce the Distributive Property by inviting students to look at patterns in _structure_, and then later apply what they know (to make mental computations or think about area).

|===

== The Distributive Property @duration{30 minutes}

=== Overview

Students develop an understanding of the @vocab{Distributive Property} by examining equivalent Circles of Evaluation.

=== Launch

@teacher{Display the two Circles of Evaluation, which offer an example of multiplication being distributed over addition.}

[.embedded, cols="^.^3,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(* 9 (+ 40 6)))} | @show{(coe '(+ (* 9 40) (* 9 6)))}
|===


@QandA{
@Q{What do you Notice and what do you Wonder about the two Circles of Evaluation, above?}
@A{Possible Noticings: The Circles of Evaluation have different structures. One has a single nested Circle, while the other has two nested Circles. Both include the numberes 9, 40, and 6. Both include addition and multiplication.}
@A{Possible Wonderings: Are these equivalent? What do they evaluate to? Why is there one 9 in the first Circle of Evaluation, but two 9s in the second Circle?}

@Q{Are these two Circles of Evaluation @vocab{equivalent}? Why or why not?}
}

The Circles of Evaluation are equivalent because of the @vocab{Distributive Property}! The Distributive Property tells us that @math{a \times (b + c) = ab + ac}:

[.embedded, cols="^.^3,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(* a (+ b c)))} | @show{(coe '(+ (* a b) (* a c)))}
|===

@teacher{Facilitate a discussion where students think deeply about what is happening in the scenarios above, namely, that distribution allows us to rewrite a product as a sum or a sum as a product.}

@lesson-point{
Multiplying the sum of two addends by a number produces the same result as multiplying _each_ addend by that number before finding the sum.
}

@teacher{
In the next activity, students will use Circles of Evaluation to explore how the mathematical structure of an expression shifts when we apply Distributive Property.
}

@lesson-instruction{
- On @printable-exercise{pages/sum-to-product.adoc}, fill in the blanks so that the Circle of Evaluation on the right is equivalent to the Circle of Evaluation on the left.
- Use computation to confirm that the Circles of Evaluation in each pair are equivalent.
- After you finish evaluating each Circle of Evaluation, place a checkmark next to the Circle of Evaluation that you think results in a simpler comuptation.
}

@QandA{
Q@{When was it easier to compute the _sum_? When was it easier to compute the _product_?}
@A{There are no right or wrong answers, here. We want students to begin to consider how a nuanced understanding of the Distributive Property can result in more flexible and efficient mental math.}
}


@lesson-instruction{
- On @printable-exercise{pages/product-to-sum.adoc}, the Circle of Evaluation representing a product is provided, and you will complete the Circle of Evaluation that represents a sum.
- Complete @printable-exercise{pages/distribution-challenge.adoc}, where you will practice applying the Distributive Property in both directions - and with expressions that include fractions and decimals!
}

=== Investigate

Elise and Dani are discussing a pair of Circles of Evaluation.

[.embedded, cols="^.^3,^.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(* 5 43))} | @show{(coe '(+ 200 8))}
|===

Dani thinks the Circles of Evaluation are equivalent. She says, "You can think of 43 as the sum of 40 and 3. Then, you multiply 5 by 40 to get 200, and you add 5 and 3 to get 8."

Elise says, "The second Circle should say 200 + 15, not 200 + 8."

@QandA{
@Q{Who is correct - Elise or Dani?}
@A{Elise is correct. We need to multiply each value by 5.
It may be helpful for some students to see the Circle for @math{(5 \times 40) + (5 \times 3)}.}
}

@teacher{
The activities in the Launch focused on students' internalizing the structure of expressions both before and after applying the Distributive Property. During this segment of the lesson, students apply what they have learned.
}

@lesson-instruction{
- Turn to @printable-exercise{pages/true-or-false.adoc}, where you will determine if equations represented by the Circles of Evaluation are true or false. Explain your response.
- Complete @printable-exercise{pages/wodb.adoc}. Cross out the Circle of Evaluation that doesn’t belong with the others, and then explain your choice.
}


=== Synthesize

- Summarize the Distributive Property in your own words.
- Elise and Dani are looking at this problem: @math{4 \times (100 - 1.25)}. Dani tells Elise that we must _always_ evaluate what's inside the parentheses first. Do you agree with this idea - or can Dani be more flexible? Explain.

@teacher{
Some students may suggest that distributing is a way of addressing the grouping symbol. Others may agree with Dani. We encourage you to discuss with your students the pros and cons of a flexible approach to solving. In this particular instance, applying the Distributive Property results in a much simpler computation.
}

== The Distributive Property and Mental Math @duration{20 minutes}

=== Overview

Students discover how some computations are simpler and more efficient when we apply the distributive property.

=== Launch

@QandA{
@Q{Can you represent the expression @math{45 \times 81 - 45 \times 79} in a simpler way?}
@Q{Yes. We can apply the Distributive Property, transforming the expression into @math{45 \times (81 - 79)}.}

@Q{Can you represent your solving process with a chain of Circles of Evaluation?}
@A{Invite a student to draw on the board. See below for one possible representation. You might need to draw a Circle or two to get students.}
}

[.embedded, cols="^.^5,^.^1,^.^4,^.^1,^.^3,^.^1,^.^2", grid="none", frame="none"]
|===
| @show{(coe '(- (* 45 81) (* 45 79)))} | &rarr; | @show{(coe '(* 45 (- 81 79)))} | &rarr; | @show{(coe '(* 45 2))} | &rarr; | 90
|===


@lesson-point{
We can use distribution and mental math to make computation simpler.
}

@teacher{
In expressions such as @math{45 \times (81 - 79)}, the multiplication sign is unnecessary and implied when not there. Encourage students to try out this notation, especially if it is one that they have not encountered before.
}

=== Investigate

If we were asked to compute @math{70 \times 39}, we could do so using a calculator or the standard algorithm. Now that we are familiar with the Distributive Property, we have a valuable tool for efficient mental computation.

@lesson-instruction{
- Turn to @printable-exercise{pages/mental-math.adoc} and look at the first problem.
}

Our goal here is to make the math easier by creating an equivalent expression that we can solve in our heads! So, instead of finding the product of 70 and 39, we are going to multiply 70 by the difference of 40 and 1.


@lesson-instruction{
- Complete the next Circle of Evaluation, which shows that we are going to _distribute_ 70.
- Observe how we can now compute our solution by finding difference between two products.
}

@QandA{
@Q{Do you find this process more efficient than the standard algorithm for multiplication? Explain.}
}

@lesson-instruction{
- Complete the rest of the page by creating equivalent expressions that we can solve in our heads.
}


@teacher{Without ample practice, there is a good chance that students will not find this process efficient. Like any solving strategy, it takes practice!}

=== Synthesize

- How can you multiply two 2-digit numbers using mental math?
- What sorts of problems are simpler to compute using the Distributive Property?
- Can you think of a multiplication problem that would be _easier_ to solve using the Distributive Property?


@teacher{We recommend inviting many students to share the problems they come up with. Make a list on the board for students to review together.}

== Programming Exploration: Distribution @duration{20 minutes}

=== Overview

Extending concepts explored earlier in the lesson, students consider whether various functions that we use when coding are distributive.

=== Launch

We've learned a lot about how the distributive property works. For instance, multiplication can distribute over addition or subtraction, allowing us to complete otherwise complex computatoins with efficiency and ease.

But what about our programming functions? For instance, does `scale` distribute over `beside`?!

[cols="^.^4,^.^4", stripes="none"]
|===

| @show{(coe '(scale 0.5 (beside aqua-star orange-dot)))} | @show{(coe  '(beside (scale 0.5 orange-dot) (scale 0.5 aqua-star)))}

| @image{aqua-orange.png, 50} |

|===

@slidebreak

@lesson-instruction{
- After studying the two Circles of Evaluation, make a prediction: What image will the second Circle of Evaluation produce? Draw your prediction on @printable-exercise{distribution-and-code.adoc}.
- Test your prediction. Type into @starter-file{editor} the code for the second Circle of Evaluation.
}

@slidebreak

@QandA{
@Q{Does `scale` distribute over `beside`? How do you know?}
@A{Yes, it does. We know because both Circles of Evaluation produced identical images.}
}

@lesson-instruction{
Complete @printable-exercise{distribution-and-code.adoc}.
}

@QandA{
@Q{Why do you think `scale` distributed over `beside`, but `rotate` did not?}
}


=== Investigate

Let's look at whether we can distribute two additional functions: `flip-vertical` and `flip-horizontal`.

An interesting feature of these functions is that they require just *one* input: an Image. In a mathematics context, we haven't applied the Distributive Property to any such function... so let's give it a try now!

The function `triple` takes a value and multiplies it by three. Let's test if we can distribute `triple` over addition.

[cols="^.^4,^.^4", stripes="none"]
|===

| @show{(coe '(triple (+ 12 5)))} | @show{(coe  '(+ (triple 12) (triple 5)))}

| 51 |  51

|===
