= Linear Regression

@description{Students compute the “line of best fit” using the function for linear regression, and summarize linear relationships in a dataset.}

@lesson-prereqs{correlations}

@keywords{line of best fit}

@add-to-lang{lr-plot}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* interpret linear regression in the context of the animals table
* use linear regression to quantify patterns in a dataset

| Student-facing Lesson Goals
|

* Let's learn how to determine the strength of relationships between variables.

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
|
* Make sure students can access the @online-exercise{https://www.geogebra.org/m/ZcVIxKtF, Interactive Regression Line}
|===

== Intro to Linear Regression @duration{10 minutes}

=== Overview
Students are introduced to the _concept_ of @vocab{linear regression}, and learn how to interpret the @vocab{slope} and @vocab{y-intercept} of @vocab{predictor functions}.

_For teachers who have the need and the bandwidth to go deeper, this is a good opportunity to teach the algorithm behind linear regression. This algorithm is not part of Bootstrap:Data Science._

=== Launch


@strategy{
@span{.title}{Vocabulary Note}

We prefer the words “explanatory” and “response” in our curriculum, because in other contexts the words “dependent” and “independent” refer to whether or not the variables are related at all, as opposed to what role each plays in the relationship.

The straight line that best fits the points on a scatter plot has several names, depending on the context, subject, or grade level. All of the following terms refer to the same concept:

- Regression Line
- Line of Best Fit
- Least Squares Line
- Predictor
- Trendline

The line itself is computed through a process called _linear regression_, which also goes by the name _least squares regression_.
}


Make two scatterplots from the `animals-table`, using `age` as the explanatory variable in one plot and `pounds` as the @vocab{explanatory variable} in the other.

In both plots, use `weeks` as your @vocab{response variable} and `name` for the `labels`. We will refer to the explanatory column as “xs” and the response column as “ys.”


[cols="1a,1a", grid="none", frame="none"]
|===
| @image{images/pounds-v-weeks.gif, 400}
| @image{images/age-v-weeks.gif, 400}
|===

@teacher{
Quickly survey the class about whether they think we can use an animal’s size or age to predict how long it will take to be adopted.

- _A scatter plot of adoption time versus size does suggest that smaller animals get adopted faster than larger animals._
- _Similarly, younger animals tend to be adopted faster than older ones._
}

Can we be more precise about this, and actually _predict_ how long it will take an animal to be adopted, based on these factors? And which one would give us a better prediction?

Just as the mean, median, and mode can summarize data from a _single quantitative variable_, the “center” of points in a _two-dimensional_ cloud can be described by a @vocab{line of best fit}. Given a value for the @vocab{explanatory variable}, this line allows us to predict what the corresponding value for the @vocab{response variable} might be.

@lesson-instruction{
Open the @online-exercise{https://www.geogebra.org/m/ZcVIxKtF, Interactive Regression Line}, and use it to complete @printable-exercise{lr-plot-intro.adoc}.
}

@teacher{
Have students talk about their answers to the first section.}

@QandA{
@Q{Why do x-values that are far to the left or right of the point cloud have a larger impact on R?}
@A{Think of their distance from the "anchor" of the data as the length of a wrench. The longer the handle, the more "force" P applies on the regression line.}

@Q{Why can't we have a regression line with all points above or below the line?}
@A{Because the points exert a _balanced_ force on the line. If all the points were on one side, there would be nothing to balance them out on the other side.}
}

Data scientists use a statistical method called @vocab{linear regression} to pinpoint linear relationships in a dataset. Linear regression is the math behind the @vocab{line of best fit}, which allows us to make predictions based on our data.

Each point in our scatter plot “pulls” on the line, with points above the line yanking it up and points below the line dragging it down. Points that are really far away -- especially influential observations that are far to the left or right of the point cloud -- pull on the line with more force.

This line can be graphed on top of the scatter plot as a function, called the @vocab{predictor function}.

=== Investigate

@lesson-instruction{
* Turn to @printable-exercise{pages/drawing-predictors.adoc}.
* Draw a @vocab{line of best fit} through each of the scatter plots.
* Decide whether the _direction_ of the correlation (which could also be referred to as the slope of the line) is positive or negative.
* Then assess the strength of the correlation.
}

=== Common Misconceptions
* *Don't forget to look at sample size!* A linear regression plot with an @math{r}-value of 0.999 is strong...but that's useless if it's a sample of just three data points!

=== Synthesize
Give students some time to experiment, then share back observations.

== Performing Linear Regression @duration{20 minutes}

=== Overview
Students are introduced to the @ifproglang{pyret}{`lr-plot` function in Pyret}@ifproglang{codap}{Least Squares Line in CODAP}, which performs a linear regression and plots the result.

=== Launch
@ifproglang{pyret}{Pyret} includes a powerful display called @ifproglang{pyret}{`lr-plot`}@ifproglang{codap}{Least Squares Line}, which (1) draws a scatter plot, (2) draws the line of best fit, and (3) even displays the equation for that line.

@ifproglang{pyret}{
Just like the `scatter-plot` function, `lr-plot` takes in a Table and the names of *3 Columns*, the first of which will be used to label the points.}

@ifproglang{codap}{
To perform linear regression in CODAP, simply create a scatter plot and select Least Squares Line from the `Measure` menu.}

@lesson-instruction{
- Open your saved Animals Starter File, or @starter-file{animals, make a new copy}.
- Create @ifproglang{pyret}{an `lr-plot`}@ifproglang{codap}{a Least Squares Line} for the Animals Table.
** Use `"name"` for the labels.
** Use `"age"` for the x-axis.
** Use `"weeks"` for the y-axis.
}

@ifproglang{pyret}{@right{@image{images/lr-explained.png, 400}}}
@ifproglang{codap}{@right{@image{images/codap-lr-explained.png, 400}}}

. The resulting scatter plot looks like those we’ve seen before!

. The @vocab{line of best fit} is now drawn onto the plot.

. @ifproglang{pyret}{Above the display,}@ifproglang{codap}{In the yellow box on the display,} we see the @vocab{predictor function} for that line.

**  The predictor function is written in slope-intercept form.
(@math{y = mx + b}, where @math{m} describes the @vocab{slope} or @vocab{rate of change} and @math{b} identifies the @vocab{y-intercept}.)

** In this plot, we can see that the slope of the line is `0.789`, which means that on average, each extra year of age results in an extra @math{0.789} weeks of waiting to be adopted (about 5 or 6 extra days).

** The y-intercept is @ifproglang{pyret}{`2.2309`}@ifproglang{codap}{`2.3`}. This is where the best-fitting line crosses the y-axis.  We want to be careful not to interpret this too literally, and say that a newborn animal would be adopted in @ifproglang{pyret}{2.309}@ifproglang{codap}{2.3} weeks, because none of the animals in our dataset was that young. Still, the @vocab{regression line} (or @vocab{line of best fit}) suggests that a baby animal, whose age is close to 0, would take only about 3 weeks to be adopted.

** By subsituting an animal's age for _x_ in the predictor function, we can make a _prediction_ about how many weeks it will take to be adopted.

** For example, we predict a 4-year-old animal to be adopted in @ifproglang{pyret}{@math{0.789(5) + 2.309 = 6.254}}@ifproglang{codap}{@math{0.789(5) + 2.3 = 6.245}} weeks. That’s the y-value when @math{ x = 5} for a point that falls exactly on the regression line.

. @ifproglang{pyret}{We also see the @math{r}-value is `+0.448`.}@ifproglang{codap}{We also see that the @math{R^2} value is `0.201`. When we know @math{R^2}, we can find @math{r} by taking the square root of @math{R^2}. The @math{r}-value is `+0.448`.}

** The sign @ifproglang{pyret}{is}@ifproglang{codap}{must be} positive, @ifproglang{pyret}{consistent with the fact that}@ifproglang{codap}{because} the scatter plot point cloud and line of best fit both slope upward.

** The fact that the @math{r}-value is close to @math{0.5} tells us that the strength is moderate.

** This makes sense: the scatter plot points are somewhere between being really tightly clustered and really loosely scattered.

@strategy{
@span{.title}{Going Deeper}

@ifproglang{pyret}{Students may notice another value in the lr-plot, called @math{R^2}.}@ifproglang{codap}{CODAP displays @math{R^2} rather than @math{r}.} @math{R^2} describes the _percentage of the variation in the y-variable that is explained by least-squares regression on the x variable_. In other words, an @math{R^2} value of 0.20 could mean that “20% of the variation in adoption time is explained by regressing adoption time on the age of the animal”. Discussion of @math{R^2} may be appropriate for older students, or in an AP Statistics class.
}

=== Investigate
@lesson-instruction{
- Complete @printable-exercise{lr-plot-explore.adoc}, and be ready to discuss your answers with the class!
}

@teacher{Have students share their answers and discuss}

@lesson-instruction{
- Complete @printable-exercise{which-questions-make-sense.adoc}.
@ifproglang{pyret}{
- @optional Open @opt-starter-file{height} to explore the same student dataset broken down by gender identity using @opt-printable-exercise{age-v-height-explore.adoc}.}
}

=== Synthesize

A predictor __only makes sense within the range of the data that was used to generate it__.

Toddlers grow a lot faster than adults. A regression line predicting the height of toddlers based on age would predict that a 60-year-old is 10 feet tall!

Statistical models are just proxies for the real world, drawn from a limited sample of data: they might make a useful prediction in the range of that data, but once we try to extrapolate beyond that data we may quickly get into trouble!

@ifproglang{pyret}{
@strategy{
@span{.title}{Simpson's Paradox}

A common misconception is that "more data is always better", and the age-v-height worksheet challenges that assumption. Two sub-groups (girls and boys) can each have a strong correlation between age and height, but when they are combined the correlation is weaker. This phenomenon is called @link{https://en.wikipedia.org/wiki/Simpson's_paradox, Simpson's Paradox}. Statistics (especially AP!) teachers will want to dive deeper on this topic.

}}


== Interpreting Linear Regression Lines @duration{20 minutes}

=== Overview
Students learn how to _write_ about the results of a linear regression, using proper statistical terminology and thinking through the many ways this language can be misused.

=== Launch
How well can you interpret the results of a linear regression analysis? How would you explain it to someone else?

@lesson-instruction{
- What does it mean when a data point is _above_ the line of best fit?
** _It means the y-value is higher than the sample would have predicted for that x-value._
- What does it mean when a data point is _below_ the line of best fit?
** _It means the y-value is lower than the sample would have predicted for that x-value._
- Turn to @printable-exercise{interpreting-regression-lines-n-rvalues.adoc}, and fill in the blanks for each scenario on the left using information from the @vocab{predictor function} and @vocab{r-value} on the right.
}

Let's take a look at how the Data Cycle can be used with Linear Regression, and how the result can be used to form our Data Story.

@lesson-instruction{
- Read @printable-exercise{pages/data-cycle-regression-analysis-example.adoc}.
- What do you Notice? What do you Wonder?
- Do the `Ask Questions` and `Consider Data` steps match each other? Why or why not?
** _Yes. We're thinking about how age of cats impact time to adoption by looking a the cat rows and comparing `age` and `weeks`._
- At the bottom of the page we have the _Data Story_ for this question, which includes the results of the analysis and a responsible way to write about them.
}

=== Investigate

@lesson-instruction{
- Turn to @printable-exercise{describing-relationships-1.adoc}.
- Using the language you saw on @printable-exercise{data-cycle-regression-analysis-example.adoc}, how would you write up the findings on this page?
- @optional For more practice, you can complete @opt-printable-exercise{describing-relationships-2.adoc}.
}

=== Common Misconceptions
* *Don't call it "accuracy"!* One of the most common misconceptions about Linear Regression is that the @math{r} or @math{R^2} value is a _measure of accuracy._ For example, a student who sees a very high @math{r}-value when plotting age vs. weeks might say "this prediction is 95% accurate." But these values only speak to _how much variation in the y-axis can be explained by variation in the x-axis_, so the statement should be "95% of the variation in weeks can be explained by variation in the age."
* *X and Y matter!* The correlation coefficient will be the same, even if you swap the x- and y-axes. However, the _interpretation_ of the display is different! The column used for the x-axis will always be interpreted as "the explanation" for the "result" seen in the y-axis. It's fine to say that being older tends to make an animal take longer to be adopted, but it is *not true* that taking longer to be adopted makes an animal older!

=== Synthesize
Have students read their data stories aloud, to get comfortable with the phrasing.

@right{@image{images/lin-reg-2.png,  400}}

The word “linear” in “linear regression” is important here. In the image on the right, there’s clearly a pattern, but it doesn’t look like a straight line!

There are many other kinds of statistical models out there, but all of them work the same way: use a particular kind of mathematical function (linear or otherwise), to figure out how to get the “best fit” for a cloud of data.

@ifproglang{pyret}{
@strategy{
@span{.title}{Project Option: Olympic Records}

In this project, students analyze Olympic data in running, swimming, or speed skating. They analyze change over time using scatter plots and linear regression. @opt-project{olympics-project.adoc, olympics-project-rubric.adoc} can be used as a mid-term or formative assessment, or as a capstone for a limited implementation of Bootstrap:Data Science.

@span{.center}{__(Project designed by Joy Straub)__}
}}

== Data Exploration Project (Linear Regression) @duration{flexible}

=== Overview
Students apply what they have learned about linear regression to their chosen dataset. They will add at least one linear regression display to their @starter-file{exploration-project}, along with their interpretation of what this display tells them. To learn more about the sequence and scope of the Exploration Project, visit @lesson-link{project-data-exploration}. For teachers with time and interest, @lesson-link{project-research-paper} is an extension of the Dataset Exploration, where students select a single question to investigate via data analysis.

=== Launch

Let’s review what we have learned about linear regression.

Linear Regression is a way to calculate the line-of-best-fit (or "predictor function") for the relationship between two quantitative columns.

@lesson-instruction{
- Will @ifproglang{pyret}{`lr-plot`}@ifproglang{codap}{Least Squares Line} still find a line of best fit, even if there's no correlation?
** _Yes! Linear regression will always find a line of best fit -- it just might not fit very well!_
- What does the slope of the line-of-best-fit tell us about a correlation?
** If the slope is positive, the correlation is positive. If it's negative, so is the correlation._
- If the @math{r}-value is close to 1, does this mean the predictor function will always give us a good prediction of the y-value, based on _any_ x-value? Why or why not?
** No! Even with an exremely high @math{r}-value, the predictor function should not be used to make predictions far outside the range of the dataset.
}

=== Investigate

Let’s connect what we know about linear regression to your chosen dataset.

@lesson-instruction{
- Open your chosen dataset starter file @ifproglang{pyret}{in Pyret}@ifproglang{codap}{in CODAP}.
** _Teachers: Students have the opportunity to choose a dataset that interests them in @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "List of Datasets"} in the @lesson-link{choosing-your-dataset} lesson._
- Choose one correlation you were investigating, and use the Data Cycle to ask the question about the relationship between those two columns. Tell the story on @printable-exercise{data-cycle-regression-analysis-1.adoc}.
- You can explore another question in the same way, using @opt-printable-exercise{data-cycle-regression-analysis-2.adoc}.
}

@teacher{Confirm that all students have created and understand how to interpret their LR plots. Once you are confident that all students have made adequate progress, invite them to access their @starter-file{exploration-project} from Google Drive.}

@lesson-instruction{
- *It’s time to add to your @starter-file{exploration-project}.*
- Find the "Correlations I want to look into" section of the slide deck.
- Choose one correlation you explored, and duplicate the slide.
- On the new slide, replace your scatter plot with the linear regression plot and add your interpretation of that plot.
}

=== Synthesize

@teacher{Have students share their findings.}

Did you discover anything surprising or interesting about their dataset?

Did the results from @ifproglang{pyret}{`lr-plot`}@ifproglang{codap}{your Least Squares Line} confirm your suspicions about the correlation? Were any of them surprising?

== Additional Exercises

- An extra, @opt-printable-exercise{data-cycle-regression-analysis-2.adoc, blank regression analysis pages} is available
