= Translating Between Words and Math

@description{Students learn to model verbal expressions with a visual tool known as "Circles of Evaluation".}

@lesson-prereqs{}

@keywords{Circle of Evaluation, mathematical expression, equation}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

@objectives
@objective{Diagram an arithmetic expression using Circles of Evaluation.}
@objective{Translate between verbal expressions, Circles of Evaluation, and mathematical expressions.}
@objective{Recognize when expressions in words are ambiguous.}


| Student-facing Lesson Goals
|

- Let's analyze the structure of verbal expressions using Circles of Evaluation.


| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
|
@preparation{
- This activity involves a card sort. The easiest way to prepare for the card sort is to give each pair of students an envelope containing the three sets of cards. Keep each set (Expressions, Circles of Evaluation, and Verbal Expressions) together with rubber bands or paperclips. We recommend printing each set on a different color of paper.
}

| Key Points For The Facilitator
|
* This lesson may challenge students' ideas of math as a subject that is entirely black and white. This theme - that there are oftentimes a variety of completely valid ways of seeing a seemingly simple problem - will emerge again.
|===

== Circles of Evaluation

=== Overview
Students match Circles of Evaluation to @vocab{arithmetic expressions}, and then they consider how those arithmetic expressions in words map onto Circles of Evaluation.

=== Launch
@slidestyle{Launch}

@teacher{
Give each pair of students an envelope and explain that it contains three sets of cards, which you will print from @handout{pages/translating-card-sort-1.adoc}, @handout{pages/translating-card-sort-2.adoc}, and @handout{pages/translating-card-sort-3.adoc}.
}

@QandA{
@Q{Look through the first set of cards. What do you notice?}
@A{Students should notice that the first set of cards includes @vocab{arithmetic expressions}. The expressions on these cards each include the number 15, the number 3, and an @vocab{operator}. Note that because these are expressions - not @vocab{equations} - they do not include an equal sign.}
@Q{Now look through the second set of cards. What do you notice?}
@A{Students should observe that each card includes an oval-shaped diagram. They may also notice the position of the numbers and operator within that diagram.}
}

@slidebreak{Launch}

@teacher{
This second set of cards includes Circles of Evaluation. A @vocab{Circle of Evaluation} helps students visualize the structure of the mathematical expressions they encounter.}

For the time being, here’s what we need to know about Circles of Evaluation:

- Every Circle must have one - and only one! - operator (or @vocab{function}!), written at the top.

- The inputs of the operator are written left to right, in the middle of the Circle.

@slidebreak{Launch}

@lesson-instruction{
- With your partner, match each Arithmetic Expression card with the corresponding Circle of Evaluation card. Do not sort the Verbal Expression cards yet.
- Create a separate pile for any cards that do not have a match.
- Lay the cards out on the table in front of you so you can clearly see both the Circle of Evaluation and the expression.
- Discuss any questions that arose.
}

@teacher{
Cards with no match include: @math{15 \times \frac{1}{3}}, the Circle of Evaluation with the function between the operators rather than at the top of the Circle, and the Circle of Evaluation for @math{3 + 15}.
}

@slidebreak{Launch}

As you matched arithmetic expressions with Circles of Evaluation, you may have wondered about a few things...

- *Symbols*. Circles of Evaluation utilize `*` to represent multiplication and `/` to represent division. (Why? Circles of Evaluation are a bridge representation - one which can eventually be used to help students learn to code! These are also the symbols used to type mathematical expressions into a search bar!)

- *Order of terms*. While @math{15 + 3} and @math{3 + 15} both evaluate to the same _answer_, they are not the same _expression_.

- *Position of the operator*. The operator always belongs at the top of the Circle, and not in between terms.

@teacher{
Although we use symbols like `*` and `/` on all of our materials, you and your students can use whichever operator symbols feel most right.
}

@slidebreak{Launch}

@lesson-instruction{
- Now, you’re going to receive a set of cards with verbal expressions - expressions written out in _words_.
- One at a time, take turns reading each card from the Verbal Expressions set out loud. After reading the card, place it with the corresponding Circle of Evaluation and Expression cards. Some sets will include just 3 cards, and others will have more.
- Explain to your partner how and why you placed each card.
- You and your partner must agree on each card’s placement before advancing to the next.
}

@slidebreak{Launch}

As you worked, did you encounter any of the challenges listed below?

- *Order matters.* When translating, we must translate _precisely_. Even though @math{15 + 3} and @math{3 + 15} evaluate to the same result, they are structurally different expressions!

- *One-third of 15*. Another way to represent this expression is @math{\frac{1}{3} \times 15}. Dividing by 3 produces the same outcome as multiplying by @math{\frac{1}{3}}. Multiplication and division are inverse operations.

- *Translating subtraction.* It is tempting to translate "3 less than 15" into @math{3 - 15}, rather than @math{15 - 3}. Why won't this work?

@teacher{
Discuss the meaning of the word "less" in this context. Sometimes, asking, “What value is 3 less than 15?” can help students to make the connection. (The word "than" tends to force the numbers to appear in the _opposite_ order in which the language arranges them.)
}

@slidebreak{Launch}

@lesson-instruction{
- Turn to @printable-exercise{translating.adoc}. Each row of the table represents a single arithmetic expression, written in three different ways. Fill in the empty spaces so that all three representations match.
- Complete @printable-exercise{matching-words-to-circles.adoc}.
}

Getting stuck? Reading expressions aloud often helps us to recognize the words' meanings. Give it a try next time you feel confused!


=== Investigate
@slidestyle{Investigate}

During the launch, we looked at the Circle of Evaluation for "15 increased by 3."

Let’s say we want to replace @math{15} with @math{3 \times 5}. Now, our expression looks like this: @math{3 \times 5 + 3}.

If we want to translate this expression into words, then we need to somehow _see the underlying structure_ of the expression: Do we multiply @math{3} by @math{5} first? Or add @math{5} and @math{3}?

Once we know the structure, we need to think of the right vocabulary to describe what we see.


@slidebreak{Investigate}


What a complicated process!

There MUST be another way!

@slidebreak{InvestigateR}

@lesson-point{
Circles of Evaluation can contain other Circles of Evaluation.
}

The Circle of Evaluation for @math{3 \times 5 + 3} looks like this:

@show{(coe '(+ (* 3 5) 3))}

Because Circles of Evaluation highlight the structure of any given expression, translating into words becomes much simpler: the inner Circle clearly shows a product, which is being increased by @math{3} (as the outer Circle indicates).

@slidebreak{Investigate}

@teacher{
Your students do not need to know that multiplication precedes addition in the subsequent activities.
}

@lesson-instruction{
- Practice @printable-exercise{translate-words-to-circles.adoc}.
- Translate in the _other_ direction on @printable-exercise{translate-circles-to-words.adoc}.}

@teacher{
Note: There are multiple correct translations! Invite students to share their responses and evaluate the clarity of each translation as a class.
}

@slidebreak{Investigate}

@lesson-instruction{
- Complete @printable-exercise{translation-table1.adoc} and @printable-exercise{translation-table2.adoc} to practice moving between all three representations (the mathematical expression, the Circle of Evaluation, the verbal expression).
- @opt{Try @opt-printable-exercise{matching-math-to-words.adoc}, where you will match mathematical expressions with their corresponding expressions in words. (If you get stuck, feel free to draw Circles to help you.)}
}

@teacher{
In Translation Table (1), the same nested Circle is used in multiple expressions - but not all expressions! In Translation Table (2), the structure of the Circles of Evaluation shift from expression to expression.

Be sure to spend a moment going over students' solutions. Some translations into words are clearer than others; the subsequent section of this lesson will explore that notion in greater depth.
}

=== Synthesize
@slidestyle{Synthesize}
We did lots of different translations between Circles of Evaluation, verbal expressions, and arithmetic expressions.

- Was there any type of translation that was more challenging for you?
- Is there more than one way to draw the Circle of Evaluation for @math{1 + 2} ? If so, is one way more "correct" than the other?



== The Ambiguity of Words

=== Overview
Students diagram arithmetic expressions using Circles of Evaluations to consider how different mathematical interpretations can lead to different outcomes.


=== Launch
@slidestyle{Launch}

Read this sentence: @ifnotslide{*Bruno told Gus that Mr. Schneider suspected that he had cheated on the science test.*}

@ifslide{
@big{*Bruno told Gus that Mr. Schneider suspected that he had cheated on the science test.*}
}

@QandA{
@Q{Who is the "he" in this sentence?}
@A{We don't know! It could be Bruno, or it could be Gus.}
@Q{Who do you think is in trouble: Bruno or Gus?}
@A{Answers will vary.}
@Q{How could you rewrite this sentence to make it clearer?}
@A{Bruno said to Gus, "Mr. Schneider thinks *you* cheated!"}
@A{Bruno said to Gus, "Mr. Schneider thinks *I* cheated!"}
}

@teacher{
Discuss the two different possible interpretations of the sentence, which illustrate how even grammatically correct sentences in English can create confusion!
}

@slidebreak{Launch}

Math is precise, but that precision is difficult to preserve when we switch to words. Often, sentences can be _ambiguous_, meaning that there is more than one way to interpret them!

@slidebreak{Launch}

One reason that Circles of Evaluation are so powerful is that they eliminate the ambiguity we encounter when representing expressions with words.

Circles of Evaluation also parse expressions more clearly than traditional mathematical notation.

=== Investigate
@slidestyle{Investigate}

@ifnotslide{
Let's tackle some verbal expressions that have _more than one_ possible mathematical translation.}

Consider the expression *the sum of three and two multiplied by eight*.

Are we multiplying first and then adding (the Circle on the left), or adding first and then multiplying (the Circle on the right)?

[.embedded, cols=">.^1,<.^1", grid="none", stripes="none" frame="none"]
|===

|@show{(coe  '(+ 3 (* 2 8)))}		| @show{(coe  '(* (+ 3 2) 8))}
|===

@slidebreak{Investigate}

There are multiple ways to translate *the sum of three and two multiplied by eight*, which the Circles of Evaluation help us see.

@QandA{
@Q{Would inserting a comma after the word “two” provide clarity?}
@A{Students' responses will vary.}
}

@slidebreak{Investigate}

@lesson-instruction{
- Complete @printable-exercise{ambiguity-of-words.adoc}, drawing two possible Circles for each verbal expression.
}

@slidebreak{Investigate}

@QandA{
@Q{What happens when you translate each Circle into a mathematical expression? Do the expressions produce the same result?}
@A{The expressions are structurally different, and generally produce different results (with two noteworthy exceptions!)}
@Q{Did you notice anything interesting about the last two expressions, compared to the others on the page?}
@A{These expressions use only multiplication or only addition. As a result, the two expressions you wrote evaluated to the same outcome.}
}

@slidebreak{Investigate}

@lesson-instruction{
- Complete @printable-exercise{rewriting-ambiguous-expressions.adoc}.
}

@QandA{
@Q{Did the two versions of the expressions produce the same results?}
@A{Different interpretations produce very different results!}
}

@slidebreak{Investigate}

Be careful! Just because *some* mathematical expressions are ambiguous doesn't mean that they *all* are. Only _certain_ verbal structures create confusion. Some phrases have just a single mathematical translation!

@lesson-instruction{
- On @printable-exercise{ambiguous-or-clear.adoc}, identify the expressions that have two different numeric translations.
- When you encounter an expression that is ambiguous, rewrite it two times - once for each possible interpretation.
- When you encounter an expression that is clear, draw its Circle of Evaluation.
}

=== Synthesize
@slidestyle{Synthesize}

- Why are some expressions in words ambiguous and others are not?
- Do you think that expressions written in the language of math have ambiguity?
- Are Circles of Evaluation ever ambiguous?

