= Sam the Butterfly - Applying Inequalities

@description{Students discover that inequalities have an important application in video games: keeping game characters on the screen! Students apply their understanding to edit code so that it will keep Sam the Butterfly safely in view.}

@lesson-prereqs{functions-dr}

@keywords{compound inequalities, real world application, video game, on screen, bounds, limits}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:
@objectives
@objective{ineq-apply}

| Student-Facing Lesson Goals
|
- Let's use what we know about inequalities to define the boundaries that will keep a game character on the screen.

| Materials
|[.materials-links]

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Key Points for the Facilitator
| 
- To connect students with prior knowledge of inequalities, Circles of Evaluation, and code, have them complete @opt-printable-exercise{warmup-coding-compound-ineq.adoc} in advance of the lesson or at the end of the first section.
- Unlike our lessons on @lesson-link{inequalities1-simple} and @lesson-link{inequalities2-compound}, this lesson does not explicitly discuss solution sets of inequalities or how to represent them on number-lines.
- The focus of this lesson is on applying inequalities and Booleans to solve a programming challenge. Using inequalities to set boundaries for a character will change some students' relationship with inequalities from abstract symbols to useful tools. 
|===

== Introducing Sam

=== Overview
Students are introduced to Sam the Butterfly, a simple activity in which they must write simple @vocab{inequalities} to detect when Sam has gone too far in one dimension.

=== Launch
@slidestyle{Launch-DN}

@lesson-instruction{
- Open the @starter-file{inequalities-sam} in a new tab and save a copy of your own.
- Complete @printable-exercise{sam-intro.adoc, Introducing Sam}, clicking "Run" and using the arrow keys to investigate the program with your partner.
}

As you explore the program, notice that Sam's coordinates are displayed at the top of the screen! When Sam is at (0,0), we only see a part of Sam's wing because their position is based on the _center_ of the butterfly image.

@teacher{
Students should observe that Sam can go up to, but not beyond, an x of -50. Students can represent this algebraically as @math{x \gt -50}, or (for students who notice that Sam only moves in increments of 10) @math{x \ge -40}.

Eagle-eyed students might also notice that the butterfly image is defined at the top of the file, as `IMG`! Changing this definition will allow them to customize the way Sam looks.
}

@lesson-point{
Every time Sam moves, we want to check and see if Sam is safe.
}

@ifproglang{wescheme}{
@lesson-point{In this programming language, question marks are pronounced "huh?" So `safe-left?` would be pronounced "safe-left-huh?"}
}

@slidebreak{Launch}

@QandA{
@Q{What three functions do you see defined in this file?}
@Q{What _should_ our left-checking function do?}
@A{Check to see if x is greater than -50.}
@Q{What _should_ our right-checking function do?}
@A{Check to see if x is less than 690.}
@Q{What should @show{(code '(onscreen?))} do?}
@A{Answers may vary. Let students drive the discussion, and don't give away the answer!}
}

=== Investigate
@slidestyle{Investigate}

@lesson-instruction{
- Complete @printable-exercise{left-and-right.adoc} with your partner.
- Once finished, fix the corresponding functions in your Sam the Butterfly file, and test them out.
}

@teacher{
Students will notice that fixing @show{(code 'safe-left?)} keeps Sam from disappearing off the left side, but fixing @show{(code 'safe-right?)} doesn't seem to keep Sam from disappearing off the right side!  When students encounter this, encourage them to look through the code to try and figure out why.
}

@strategy{"False" doesn't mean "Wrong"!}{

A lot of students - especially confident ones - may struggle to come up with an example where @show{(code 'safe-left?)} returns `false`:

@show{

(code '(BEGIN
  (COMMENT "Students hate writing the second one!")
  (EXAMPLE
    (safe-left? 189) (> 189 -50)
    (safe-left? -65) (> -65 -50))
  ))
}

This misconception comes from confusing a statement that is "false" with a program that is "wrong". In the second example, above, the result of @show{(code '(safe-left? -65))} _is_ `false`, because "65 is greater than -50" _is a false statement_. Remind your students that you want one example that's true, and a second that's false!

@ifproglang{pyret}{
Pyret includes some functionality that makes this more explicit, and can help resolve the misconception:
```
examples:
  is-safe-left( 89) is true  because  89 > -50
  is-safe-left(-65) is false because -65 > -50
end
```

By writing the answer first ( `is-safe-left(-65) is false` ), it reduces anxiety about code being "wrong". Students can think of the `because` as _an explanation of why the answer is false_.
}
}

@slidebreak{Investigate}

The only way to know if @show{(code 'safe-right?)} works is to test it by itself. Did you write examples for that function...?

If a car starts up when you turn the key, does that mean we know the sunroof works? Of course not! _You can't trust the behavior of a complex system, just because one part of it works!_ The only way to see if the sunroof works is to test it.

=== Synthesize
@slidestyle{Synthesize}

- Does @show{(code 'safe-left?)} work correctly? How do you know?
- Does @show{(code 'safe-right?)} work correctly? How do you know?

== Protecting Sam on Both Sides

=== Overview
Students solve a word problem involving compound inequalities, using `and` to compose the simpler Boundary-checking functions from the previous lesson.

=== Launch
@slidestyle{Launch}

@lesson-instruction{
- We need three volunteers to roleplay the functions @show{(code 'safe-left?)}, @show{(code 'safe-right?)}, and @show{(code 'onscreen?)}!
- Take 1 minute to read the Contract and code for your function, as written in the program.
}

@teacher{
Ask the volunteers what their name, Domain and Range are. Explain that you, the facilitator, will be providing a coordinate input. The functions @show{(code 'safe-left?)} and @show{(code 'safe-right?)} will respond with either "true" or "false".
}

@slidebreak{Launch-RP}

@lesson-roleplay{

The function @show{(code 'onscreen?)}, will call the @show{(code 'safe-left?)} function, giving them a number representing Sam's x-coordinate. The student roleplaying @show{(code 'onscreen?)} should turn to @show{(code 'safe-left?)} and give the input to them.

@ifproglang{wescheme}{
@define{onscreen}{onscreen-huh}
@define{safe-left}{safe-left-huh}
@define{safe-right}{safe-right-huh}
}

@ifproglang{pyret}{
@define{onscreen}{is-onscreen}
@define{safe-left}{is-safe-left}
@define{safe-right}{is-safe-right}
}

For example:

- Facilitator: "@onscreen 70"
- @show{(code 'onscreen?)} (turns to @show{(code 'safe-left?)}): "@safe-left 70"
- @show{(code 'safe-left?)}: "true"
- @show{(code 'onscreen?)} (turns back to facilitator): "true" +
{empty} +

@ifslide{@teacher{
- Facilitator: "@onscreen -100"
- @show{(code 'onscreen?)} (turns to @show{(code 'safe-left?)}): "@safe-left -100"
- @show{(code 'safe-left?)}: "false"
- @show{(code 'onscreen?)} (turns back to facilitator): "false" +
{empty} +

- Facilitator: "@onscreen 900"
- @show{(code 'onscreen?)} (turns to @show{(code 'safe-left?)}): "@safe-left 900"
- @show{(code 'safe-left?)}: "true"
- @show{(code 'onscreen?)} (turns back to facilitator): "true"
}}

}

@slidebreak{Launch}

@QandA{
@Q{What is the problem with @show{(code 'onscreen?)}?}
@A{It's only talking to @show{(code 'safe-left?)}, it's not checking with @show{(code 'safe-right?)}}
@Q{What should @show{(code 'onscreen?)} be doing?}
@A{It needs to talk to @show{(code 'safe-left?)} AND @show{(code 'safe-right?)}}
}


=== Investigate
@slidestyle{Investigate}

@lesson-instruction{
- Complete @printable-exercise{onscreen.adoc}.
- When this function is entered into the editor, students should now see that Sam is protected on _both_ sides of the screen.
}

@strategy{Extension Option}{

What if we wanted to keep Sam safe on the top and bottom edges of the screen as well?

- What additional functions would we need?  
- What functions would need to change? 

_Note: In the context of Sam the Butterfly, there's a clear reason why we want to stop Sam from going off the top and bottom of the screen! But when we add the @show{(code 'onscreen?)} function to our Game Starter File, we might *want* to let the player go above and below the screen. It will be important that the @show{(code 'onscreen?)} function we use in the game only checks the x-coordinate._

We recommend that students tackling this challenge define a new function @show{(code 'onscreen2?)} so that their initial @show{(code 'onscreen?)} code remains ready for them to use in the next section of this lesson.
}

@slidebreak{Investigate-RP}

@lesson-roleplay{
Let's have our three student volunteers roleplay those functions again, with the @show{(code 'onscreen?)} function working properly. Be sure to test out values where Sam is off one edge, off the other, and on the screen!
}

@teacher{Repeat the back-and-forth that happened earlier, making sure that the onscreen function calls both the left-checking and right-checking functions _and_ that those functions work correctly!}

=== Synthesize
@slidestyle{Synthesize}

@pd-slide{
Where have we seen this concept before? Sally's Lemonade!

In Sally's lemonade and Sam the butterfly, we asked you to solve the simple pieces first, and then we asked you to stitch them together.

But there's nothing that says we have to do the steps in this order. We could just have easily said, "I know Sam is onscreen as long as she's safe on the left and the right. What does it mean to be safe on the left? I'll deal with it later. What does it mean if Sam is safe on the right? I'll deal with it later."
}

@pd-slide{
I could also have said this: "Safe on the left and right... How do I check if Sam is safe on the left? I'll deal with it later. I don't want to think about how Sam is safe on right, either... I'll deal with it later.

These are two different strategies.

- One is top down: deal with the big picture and then solve the pieces.
- The other is bottom up: write the pieces and then figure out how to stitch them together.
}

- How did it feel when you clicked Run, and saw Sam hit both walls for the first time?
- Are there multiple solutions for @show{(code 'onscreen?)}?
- Is this _Top-Down_ or _Bottom-Up_ design?


== Boundary Detection in the Game

=== Overview
Students identify common patterns between two-dimensional Boundary detection and detecting whether a player is onscreen. They apply the same problem-solving and narrow mathematical concept from the previous lesson to a more general problem.

=== Launch
@slidestyle{Launch}

@QandA{
Open your in-progress game file and click "Run".

@Q{How are the `TARGET` and `DANGER` behaving right now?}
@A{They move across the screen.}
@Q{What happens when they go off the edge of the screen?}
@A{They just keep going!}
@Q{What do we want to change?}
@A{We want them to come back after they leave one side of the screen.}
@Q{Is this similar to a problem we've already solved somewhere else?}
@A{This is the same problem we solved with Sam!}
}
=== Investigate
@slidestyle{Investigate}

@lesson-instruction{
Apply what you learned from Sam the Butterfly to fix the @show{(code 'safe-left?)}, @show{(code 'safe-right?)}, and @show{(code 'onscreen?)} functions in your own code.
}

Since the screen dimensions for their game are 640x480 - just like Sam - we can use our code from Sam with virtually no changes!

@teacher{
Students who tackled the optional @show{(code 'safe-top?)} and @show{(code 'safe-bottom?)} challenges should be sure *NOT* to add this to their game code! There are some exciting challenges in later lessons that rely on characters being able to go off the top or bottom edge of the screen!
}

=== Common Misconceptions

- Students will need to test their code with their images to see if the boundaries are correct for them.  Students with large images may need to use slightly wider boundaries, or vice versa for small images.  In some cases, students may have to go back and rescale their images if they are too large or too small for the game.
- Students may be surprised that the same code that "traps Sam" also "resets the `DANGER` and `TARGET` ". It's critical to explain that these functions do _neither_ of those things! All they do is test if a coordinate is within a certain range on the x-axis. There is other code (hidden in the teachpack) that determines _what to do if the coordinate is offscreen_. The ability to re-use function is one of the most powerful features of mathematics - and programming!

=== Synthesize
@slidestyle{Synthesize}

The same code that "trapped" Sam also "resets" the `DANGER` and the `TARGET`. What is actually going on?

== Additional Exercises
@slidestyle{Supplemental}

- @opt-printable-exercise{onscreen-discussion.adoc}
