= Sam the Butterfly - Applying Inequalities

@description{Students discover that inequalities have an important application in video games: keeping game characters on the screen! Students apply their understanding to edit code so that it will keep Sam the Butterfly safely in view.}

@lesson-prereqs{inequalities2-compound}

@keywords{compound inequalities, real world application, video game, on screen, bounds, limits}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* apply their understanding of inequalities to keep a game character on the screen

| Student-Facing Lesson Goals
|
* Let's use what we know about inequalities to define the boundaries that will keep a game character on the screen.

| Materials
|[.materials-links]



@material-links
|===

== Introducing Sam @duration{15 minutes}

=== Overview
Students are introduced to Sam the Butterfly, a simple activity in which they must write simple @vocab{inequalities} to detect when Sam has gone too far in one dimension.

=== Launch

[.lesson-instruction]
- Open the @starter-file{inequalities-sam} in a new tab and save a copy of your own.
- Complete @printable-exercise{pages/sam-intro.adoc, Introducing Sam}, clicking "Run" and using the arrow keys to investigate the program with your partner.

As students explore the program, they should notice that Sam's coordinates are displayed at the top of the screen. When Sam is at (0,0), we only see a part of Sam's wing because Sam's position is based on the _center_ of the butterfly image. Students should observe that Sam can go up to, but not beyond, an x of -50. Students can represent this algebraically as @math{x \gt -50}, or (for students who notice that Sam only moves in increments of 10) @math{x \geq -40}.

[.lesson-point]
Every time Sam moves, we want to check and see if Sam is safe.

@ifproglang{wescheme}{
*Note:* In this programming language, question marks are prounced "huh?" So `safe-left?` would be prounounced "safe left huh?" This can be a source of some amusement for students!
}

To further support students, consider asking what three functions are defined in their starter files. Then, ask students what each function _should_ do, when working properly.

[.lesson-instruction]
- What _should_ our left-checking function do?
** _Check to see if x is greater than -50._
- What _should_ our right-checking function do?
** _Check to see if x is less than 690._
- What should `onscreen?` do?
** _Answers may vary. Let students drive the discussion, and don't give away the answer!_

=== Investigate

[.lesson-instruction]
- Complete @printable-exercise{pages/left-and-right.adoc} with your partner.
- Once finished, fix the corresponding functions in your Sam the Butterfly file, and test them out.

Students will notice that fixing @show{(code 'safe-left?)} keeps Sam from disappearing off the left side, but fixing @show{(code 'safe-right?)} doesn't seem to keep Sam from disappearing off the right side!  When students encounter this, encourage them to look through the code to try and figure out why.


[.strategy-box, cols="1a", grid="none", stripes="none"]
|===

|
@span{.title}{"False" doesn't mean "Wrong"!}

A lot of students - especially confident ones - may struggle to come up with an example where @show{(code 'safe-left?)} returns `false`:

@show{

(code `(BEGIN
  (COMMENT "Students hate writing the second one!")
  (EXAMPLE
    (safe-left? 189) (> 189 -50)
    (safe-left? -65) (> -65 -50))
  ))
}

This misconception comes from confusing a statement that is "false" with a program that is "wrong". In the second example, above, the result of @show{(code '(safe-left? -65))} _is_ `false`, because "65 is greater than -50" _is a false statement_. Remind your students that you want one example that's true, and a second that's false!

@ifproglang{pyret}{
Pyret includes some functionality that makes this more explicit, and can help resolve the misconception:
----
examples:
  is-safe-left( 89) is true  because  89 > -50
  is-safe-left(-65) is false because -65 > -50
end
----

By writing the answer first ( `is-safe-left(-65) is false` ), it reduces anxiety about code being "wrong". Students can think of the `because` as _an explanation of why the answer is false_.
}
|===

Emphasize to students that they cannot trust the behavior of a complex system! After looking closely at examples and observing that they all pass, students should suspect that the bug is elsewhere.

=== Synthesize

- Does @show{(code 'safe-left?)} work correctly? How do you know?
- Does @show{(code 'safe-right?)} work correctly? How do you know?

== Protecting Sam on Both Sides @duration{30 minutes}

=== Overview
Students solve a word problem involving compound inequalities, using `and` to compose the simpler Boundary-checking functions from the previous lesson.

=== Launch
@ifproglang{wescheme}{
*Note:* In this programming language, question marks are pronounced "huh?". So `safe-left?` would be pronounced "safe left huh?" This can be a source of some amusement for students!
}

[.lesson-roleplay]
--
Recruit three student volunteers to roleplay the functions @show{(code 'safe-left?)}, @show{(code 'safe-right?)}, and @show{(code 'onscreen?)}. Give them 1 minute to read the contract and code, as written in the program.

Ask the volunteers what their name, Domain and Range are. Explain that you, the facilitator, will be providing a coordinate input. The functions @show{(code 'safe-left?)} and @show{(code 'safe-right?)} will respond with either "true" or "false".

The function @show{(code 'onscreen?)}, however, will call the @show{(code 'safe-left?)} function! So the student roleplaying @show{(code 'onscreen?)} should turn to @show{(code 'safe-left?)} and give the input to them.


For example:
@ifproglang{wescheme}{

- Facilitator: "onscreen-huh 70"
- onscreen? (turns to safe-left?): "safe-left-huh 70"
- safe-left?: "true"
- onscreen? (turns back to facilitator): "true" +
{empty} +

- Facilitator: "onscreen-huh -100"
- onscreen? (turns to safe-left?): "safe-left-huh -100"
- safe-left?: "false"
- onscreen? (turns back to facilitator): "false" +
{empty} +

- Facilitator: "onscreen-huh 900"
- onscreen? (turns to safe-left?): "safe-left-huh 900"
- safe-left?: "true"
- onscreen? (turns back to facilitator): "true"

Hopefully your students will notice that `safe-right?` did not participate in this roleplay scenario at all!
--

[.lesson-instruction]
- What is the problem with `onscreen?`?
** _It's only talking to `safe-left?`, it's not checking with ``safe-right?``_
- How can `onscreen?` check with both?
** _It needs to talk to `safe-left?` AND ``safe-right?``_
}

@ifproglang{pyret}{
- Facilitator: "is-onscreen 70"
- is-onscreen (turns to is-safe-left): "is-safe-left 70"
- is-safe-left: "true"
- is-onscreen (turns back to facilitator): "true" +
{empty} +

- Facilitator: "is-onscreen -100"
- is-onscreen (turns to is-safe-left): "is-safe-left -100"
- is-safe-left: "false"
- is-onscreen (turns back to facilitator): "false" +
{empty} +

- Facilitator: "is-onscreen 900"
- is-onscreen (turns to is-safe-left): "is-safe-left 900"
- is-safe-left: "true"
- is-onscreen (turns back to facilitator): "true"

Hopefully your students will notice that `is-safe-right` did not participate in this roleplay scenario at all!
--


[.lesson-instruction]
- What is the problem with `is-onscreen`?
** _It's only talking to `is-safe-left`, it's not checking with ``is-safe-right``_
- How can `is-onscreen` check with both?
** _It needs to talk to `is-safe-left` AND ``is-safe-right``_.
}

=== Investigate

[.lesson-instruction]
- Complete @printable-exercise{pages/onscreen.adoc}.
- When this function is entered into the editor, students should now see that Sam is protected on __both__ sides of the screen.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{Extension Option}
What if we wanted to keep Sam safe on the top and bottom edges of the screen as well?  What additional functions would we need?  What functions would need to change? _We recommend that students tackling this challenge define a new function @ifproglang{pyret}{`is-onscreen-2`} @ifproglang{wescheme}{onscreen2?} because they will need their original @show{(code 'onscreen?)} code in the next section of this lesson._
|===

=== Synthesize

Bring back the three new student volunteers to roleplay those functions, with the onscreen function now working properly. Make sure students provide correct answers, testing both `true` and `false` conditions using coordinates where Sam is onscreen and offscreen.

- How did it feel when you saw Sam hit both walls?
- Are there multiple solutions for @show{(code 'onscreen?)}?
- Is this _Top-Down_ or _Bottom-Up_ design?


== Boundary Detection in the Game @duration{10 minutes}

=== Overview
Students identify common patterns between two-dimensional Boundary detection and detecting whether a player is onscreen. They apply the same problem-solving and narrow mathematical concept from the previous lesson to a more general problem.

=== Launch

Have students open their in-progress game file and click "Run". Invite them to analyze the movement of the danger and the target

[.lesson-instruction]
- How are the `TARGET` and `DANGER` behaving right now?
** _They move across the screen._
- What do we want to change?
** _We want them to come back after they leave one side of the screen._
- What happens to an image's x-coordinate when it moves off the screen?
** _An image is entirely off-screen if its x-coordinate is less than -50 and greater than 690._
- How can we make the computer understand when an image has moved off the screen?
** _We can teach the computer to compare the image's coordinates to a boundary on the number line, just like we did with Sam the Butterfly!_

=== Investigate

[.lesson-instruction]
Apply what you learned from Sam the Butterly to fix the @show{(code 'safe-left?)}, @show{(code 'safe-right?)}, and @show{(code 'onscreen?)} functions in your own code.

Since the screen dimensions for their game are 640x480, just like Sam, they can use their code from Sam as a starting point.

NOTE: Students should NOT add @show{(code 'safe-top?)} and @show{(code 'safe-bottom?)} to their game code!

=== Common Misconceptions

- Students will need to test their code with their images to see if the boundaries are correct for them.  Students with large images may need to use slightly wider boundaries, or vice versa for small images.  In some cases, students may have to go back and rescale their images if they are too large or too small for the game.
- Students may be surprised that the same code that "traps Sam" also "resets the `DANGER` and `TARGET` ". It's critical to explain that these functions do _neither_ of those things! All they do is test if a coordinate is within a certain range on the x-axis. There is other code (hidden in the teachpack) that determines _what to do if the coordinate is offscreen_. The ability to re-use function is one of the most powerful features of mathematics - and programming!

=== Synthesize

- The same code that "trapped" Sam also "resets" the `DANGER` and the `TARGET`. What is actually going on?

== Additional Exercises

- @opt-printable-exercise{pages/onscreen-discussion.adoc}
- @opt-printable-exercise{pages/keeping-ninjacat-in-the-game.adoc}
