= Regression Analysis in the `animals` Dataset

I performed a linear regression on @fitbruby{20ex}{cats at the
shelter}{dataset or subset} and found @fitbruby{40ex}{a moderate
(r=0.566), positive}{a weak/strong/moderate (R=...),
positive/negative}
correlation between @fitbruby{30ex}{age of the cats (in
years)}{[x-axis]} and
@fitbruby{30ex}{number of weeks to adoption}{[y-axis]}. I would predict that a
1 @fitbruby{15ex}{year}{[x-axis units]} increase in
@fitbruby{15ex}{age}{[x-axis]} is associated
with a @fitbruby{15ex}{0.23 week}{[slope, y-units]}
@fitbruby{15ex}{increase}{[increase/decrease]} in
@fitbruby{15ex}{adoption time}{[y-axis]}.

@span{.vskip}{}

I performed a linear regression on @fitbruby{20ex}{}{dataset or
subset} and found @fitbruby{40ex}{}{a weak/strong/moderate
(R=...), positive/negative} correlation between
@fitbruby{30ex}{}{[x-axis]} and @fitbruby{30ex}{}{[y-axis]}. I
would predict that a 1 @fitbruby{15ex}{}{[x-axis units]} increase
in @fitbruby{15ex}{}{[x-axis]} is associated with a
@fitbruby{15ex}{}{[slope, y-units]}
@fitbruby{15ex}{}{[increase/decrease]} in
@fitbruby{15ex}{}{[y-axis]}.

@span{.vskip}{}

I performed a linear regression on @fitbruby{20ex}{}{dataset or
subset} and found @fitbruby{40ex}{}{a weak/strong/moderate
(R=...), positive/negative} correlation between
@fitbruby{30ex}{}{[x-axis]} and @fitbruby{30ex}{}{[y-axis]}. I
would predict that a 1 @fitbruby{15ex}{}{[x-axis units]} increase
in @fitbruby{15ex}{}{[x-axis]} is associated with a
@fitbruby{15ex}{}{[slope, y-units]}
@fitbruby{15ex}{}{[increase/decrease]} in
@fitbruby{15ex}{}{[y-axis]}.

