= Build a Model from Samples: Adj. Minimum Wage v. Year (Scaffolded)

++++
<style>
.studentAnswerMedium { min-width: 8em !important; }
.fitbruby .ruby { bottom: -12px; }
</style>
++++

_Open your copy of the @starter-file{alg2-ca-rent}. If you haven't already, **Save a Copy** now._

@vspace{1ex}

@n Record the `adj-wage` and `year` values for the `data-1940` and `data-1950` rows, as @math{(x,y)} pairs below:

@center{
 (@fitbruby{10em}{@ifsoln{1940}}{`year` in `data-1940`}, @fitbruby{10em}{@ifsoln{9.41}}{`adj-wage` in `data-1940`}) @hspace{10em} (@fitbruby{10em}{@ifsoln{1950}}{`year` in `data-1950`}, @fitbruby{12em}{@ifsoln{7.89}}{`adj-wage` in `data-1950`})
}

@n We want to understand how change (@math{\Delta}) in the _year_ relates to change (@math{\Delta}) in the _adjusted minimum wage_.

[.indentedpara]
--
Compute @math{\Delta \mbox{adj-wage} =} @fitbruby{12em}{@ifsoln{7.89}}{data-1950 `adj-wage`} @math{-} @fitbruby{12em}{@ifsoln{9.41}}{data-1940 `adj-wage`} = @fitb{}{@ifsoln{-1.52}}

Compute @math{\Delta \mbox{year} =} @fitbruby{12em}{@ifsoln{1950}}{data-1950 `year`} @math{-} @fitbruby{12em}{@ifsoln{1940}}{data-1940 `year`} = @fitb{}{@ifsoln{10}}

@vspace{1ex}

Compute the slope/rate of change between `data-1940` and `data-1950`: @math{\frac{\Delta \mbox{adj-wage}}{\Delta \mbox{year}} =} @ifnotsoln{@math{\frac{\qquad\qquad\qquad}{\qquad \qquad \qquad \qquad } =} } @ifsoln{@math{\frac{-1.52}{10} = }} @fitb{}{@ifsoln{-0.152}}

_Based solely on data from the first two rows, we are seeing that for each additional `year`, results in a @fitbruby{10em}{@ifsoln{$-0.152}}{&#916; `adj-wage`} dollar decrease in adjusted minimum wage._

--

@n Now, let's use the slope intercept form of the line to calculate the y-intercept of the line passing through `data-1940` and `data-1950`.

@vspace{1ex}

[.indentedpara]
--

A) Replace @math{m} with the slope we just calculated.

B) Replace @math{x} and @math{y} with the relevant values from the `data-1950` row: (@fitbruby{12em}{@ifsoln{1950}}{ *x* {two-colons} data-1950 `year`}, @fitbruby{12em}{@ifsoln{7.89}}{ *y* {two-colons} data-1950 `adj-wage`})

C) Solve for @math{b}. @fitbruby{10em}{@ifsoln{7.89}}{y} @math{=} @fitbruby{10em}{@ifsoln{-0.152}}{m} @math{\times} @fitbruby{10em}{@ifsoln{1950}}{x} @math{+} @hspace{2em} @math{b}

@vspace{10ex}

@math{b =} @fitb{8em}{@ifsoln{304.29}}

--

@n Write the complete model below (in both Function and Pyret notation):

@center{
 @math{f(x) =} @fitbruby{8em}{@ifsoln{-0.152}}{slope}x + @fitbruby{8em}{@ifsoln{304.29}}{y-intercept} @hspace{5em} @show{(code '(define (f x) (+ (* (?ANS -0.152) x) (?ANS 304.29))))}
}

[.indentedpara]
--
- Type your function into the Definitions Area on the left, modifying the existing function `f`.

- Then click "Run", and make sure you fix any errors or warnings. 

- In the Interactions Area, try plugging in the `year` value for `data-1940` by typing `f(1940)`

--

@n How well does it predict the correct adjusted minimum wage for 1940? @fitb{10em}{@ifsoln{almost perfectly!}} What about for 1950? @fitb{}{@ifsoln{almost perfectly!}}

@vspace{1ex}

Try different `year` values from _other_ rows in the `ca-table`, to see how well our 1940-1950 model fits the rest of the data.

@n Identify a year for which this model works well: @fitb{}{@ifsoln{1990 and 2000}}

@n Identify a state for which this model works poorly: @fitb{}{@ifsoln{1970, 2020, 2021}}

@n What adjusted minimum wage does this model predict for 2040? @fitb{}{@ifsoln{~$9.26 (rounded)}}
