= Histograms and Measures of Center

@n The two histograms below represent the amount of money spent on a pair of jeans, one for a sample of sixth grade students and one for a sample of eighth grade students.

[cols="^1a,^1a"]
|===

| Distribution of Cost of Jeans (Sixth Grade)
@image{../images/jeans-cost-6th.png, 175}
| Distribution of Cost of Jeans (Eighth Grade)
@image{../images/jeans-cost-8th.png, 175}

|===

Which group has the larger mode? @hspace{1em} *Girls* @hspace{1em} // @hspace{1em} *Boys* @hspace{1em} // @hspace{1em} *The modes are roughly the same.*



@n The histogram below shows the Verbal SAT scores for 205 students entering a local college in the fall of 2002.

[cols="^1a,<1a"]
|===

| @image{../images/sat-verbal.png}
| The median score for these 205 students is:

- about 40 or 41

- between 19 and 26

- between 500 and 600

- between 400 and 500

@vspace{1ex}

Explain how you determined the median value:

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

|===



@n A study was conducted to examine the standard of living for typical families in Knoxville. The following graph displays the distribution of family income for those in the town of Knoxville.


[cols="^1a,<1a"]
|===

| @image{../images/income.png}
| Which of the following statements is likely a correct comparison of the mean and median family income in Knoxville?

- The mean income is less than the median income.

- The mean income is equal to the median income.

- The mean income is greater than the median income.

- It is impossible to determine which measure is larger from the given graph.

@vspace{1ex}

Explain how you arrived at your choice:

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

|===
