= Measures of Center in a Nutshell

@vspace{1ex}

*There are three values used to report the _center_ of a dataset*.

@vspace{1ex}

- Each of these measures of center summarizes a whole column of quantitative data using just one number:

@vspace{1ex}

  * *Mean* is the average of all the numbers in a dataset .
  * *Median*: Half of the dataset will always be greater than or equal to the median. Half of the dataset will always be less than or equal to the median. In an ordered list, the median will either be the middle number or the average of the two middle numbers.
  * *Mode(s)* of a dataset is the value (or values) occurring most often. When all of the values occur equally often, a dataset has no mode.

@vspace{1ex}

*Which Measure of Center is most typical, depends on the shape of the data and the number of values.*

@vspace{1ex}

- _When a dataset is symmetric_, values are just as likely to occur a certain distance above the mean as below the mean, and the median and mean are usually close together.

- _When a dataset is asymmetric_, the median is a more descriptive measure of center than the mean.

@vspace{1ex}

  * *Left skew* datasets have a few values that are unusually low, which pull the mean _below_ the median.
  * *Right skew* datasets have a few values that are unusually high, which pull the mean _above_ the median.

- When a dataset contains a small number of values, the mode(s) may be the most descriptive measure of center. (Note that a small number of _values_ is not the same as a small number of _data points_!)
