= Summarizing Columns with Measures of Center

++++
<style>
#content { display: block !important; }
tbody td { height: 6ex; }
h2, h2 .fitb { padding-top: 0.5rem; line-height: 1.5em; }

</style>
++++

== Summarizing the `Pounds` Column

Find the measures of center to summarize the @fitb{20ex}{pounds} column of the @starter-file{animals}.

@pathway-only{_If you're using a printed workbook, be sure to add examples to your Contracts pages in the back as you work._}

@vspace{1ex}

@n The three measures of center for this column are:

[cols="^1a,^1a,^1a",options="header"]
|===
| Mean (Average) 		| Median 		| Mode(s)

| `mean(animals-table, "pounds")`
| `median(animals-table, "pounds")`
| `modes(animals-table, "pounds")`

| @ifsoln{approx. 39.7} | @ifsoln{11.3} | @ifsoln{[list: 0.1, 6.5]}
|===

@n What is the domain of the `mean` function? @fitb{}{@ifsoln{Table, String}}

@n What is the range of the `mean` function? @fitb{}{@ifsoln{Number}}

@n Since the mean is @fitbruby{20ex}{@ifsoln{higher}}{higher/lower/about equal} compared to the median, this suggests the shape is @fitbruby{60ex}{@ifsoln{skewed right}}{skewed right (or high outliers) / skewed left (or low outliers) / symmetric}.

@n To take the average of a column, we add all the numbers in that column and divide by the number of rows. Will that work for every column?

@fitb{}{@ifsoln{No! We can only find the average of @vocab{quantitative} data.For example, the mean of a list of Presidents doesn’t make sense.}}

@fitb{}{@ifsoln{Same thing for a list of zip codes: even though we can divide a sum of zip codes, the output doesn’t correspond to some “center” zip code.}}

@star For which column(s) in the animals table do you think the modes might be a good measure of center? Why? 

@fitb{}{@ifsoln{Legs! Because there aren't very many values to choose from.}}

== Summarizing the @fitb{20ex}{} Column

The three measures of center for this column are:

[cols="^1a,^1a,^1a",options="header"]
|===
| Mean (Average) 		| Median 		 | Mode(s)
| 						| 				 | 
|===

Since the mean is @fitbruby{20ex}{}{higher/lower/about equal} compared to the median, this suggests the shape is @fitbruby{60ex}{}{skewed right (or high outliers) / skewed left (or low outliers) / symmetric}.

@star Three animals weighing 5, 5, 10, and 100 pounds will have an average mean of 30 pounds. +
@hspace{3em} (_because_ @math{5 + 5 + 10 + 100 = 120} _and_ @math{120 \div 4 = 30}) +
@hspace{1em} Can you think of another set of four animals that would have the same average? How many sets can you come up with?
