= Check-in: Stress Project

@n How well have you done collecting data for this project?  Circle one of the choices below and explain why you ranked it at that level.

(5) Excellent   (4) Very Well   (3) Average   (2) Below Average   (1) Not as well as I wanted   (0) Collected no data

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n	Do you think everyone in the class collected data on the randomly selected times? Could our data have some problems due to people forgetting to enter data at the set time?  Is there anything that could have happened to cause our class data to be biased?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n	Describe 3 interesting facts you uncovered in your internet research on teens and stress?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n	What 2 research questions (from the objectives section of the instructions) have you decided to pursue for your paper?  Why?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n	What is a way that filtering the dataset might help you? Order-by? Build-column? What functions do you plan to write to you with the filter or build column?.

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n	What data displays are you considering to use?  Name the types of displays and the variables you think you will use.

@fitb{}{}

@fitb{}{}

@fitb{}{}