g= Project: Stress or chill

@description{Students will collect and analyze a sample of data related to their class' stress levels, applying what they've learned about filtering and building to make advanced data visualizations. The final product will be a written report in which they compare their findings with research about teens and stress.
_This project supports the learning goals of our lesson on @lesson-link{filtering-and-building}._}

@lesson-prereqs{data-cycle}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

- Apply what they've learned about filtering data, building columns, asking statistical questions and making advanced data visualizations to answer their own questions about a collectively generated dataset.

| Student-facing Lesson Goals
|

- Let's use what we've learned so far in Bootstrap:Data Science to see what we can learn about our stress levels and how they compare to teen stress levels in general!

@scrub{
| Materials
|[.materials-links]
@material-links
}

| Preparation
|
@preparation{
- Make a copy of @link{https://docs.google.com/forms/d/1NEhoDnRi7ekoIl7YkqIjehq6P8woq9d2u8x-9pGp2sk/copy, this Google form} and share a link with your students so that all of their responses will end up in the class' collective spreadsheet.
- None of the handouts for this project are in the workbook, so be sure to print copies of whatever you'll be distributing.
- Teachers are welcome and encouraged to edit and adapt the @handout{rubric-stress-or-chill.adoc, student facing rubric} for their unique classroom context and distribute it to help students understand the scope of the project - and your expectations - at the outset.
}

| Facilitation Note
| 
- This project involves 5 days of data collection before students can do any analysis in Pyret. It is most efficient to introduce the project midweek so that two of the data collection days fall on the weekend! 
- This project scratches the surface of what it means to clean data. If you find yourself wanting to dig deeper into that now, we offer an entire Bootstrap lesson on @lesson-link{data-collection} that could be taught during this project.

| Project Origins
| 

- This project builds on some of the seeds planted by a project named *What Stresses Us?* from the @link{http://introdatascience.org/, Mobilizing IDS project}.

|===

== Building a Dataset: Our Stress Levels & Context

=== Overview

=== Launch

For the next 5 days (including a weekend) each student in our class will record two entries per day on our class stress survey. 

@lesson-instruction{
- Turn to @handout{stress-or-chill-data.adoc} and take a look at the kinds of questions you will be answering. 
- What do you Notice? What do you Wonder?
- With your partner complete the third column of the table by deciding what data type each variable will be.
}

@teacher{
Confirm that students have correctly identified the data types. +
Note: Each school has a different philosophy on whether phones can be used as a tool during the school day. Be prepared to modify the direction below about setting alarms based on how it would work best at your school. 
}

@lesson-instruction{
- To increase the quality of the data we collect, we will be using a @link{https://numbergenerator.org/randomnumbergenerator/1-24#!numbers=1&low=6&high=22&unique=true&csv=&oddeven=&oddqty=0&sorted=false&addfilters=, random number generator} to determine what time of day each of you should record data.
- This random number generator is currently set to give a number between 6 and 22. 
  * 6 would translate to 6am and 22 would translate to 10pm. 
  * If you get a time at which you know you will be asleep, please do not write it down. +
  Instead, let the random number generator assign you a different time.
- Complete the `time` column now.
- It might help you to set alarms for those 10 times on your watch or phone.
}

=== Investigate

- First, @link{https://docs.google.com/forms/u/0/d/1OrUCCL8kdhpTf78vzDUO6iBhw0jDLRK9kpqHRTvj6YE/copy, take a look at the "Stress or Chill? Daily Survey"}. 


- If you are unable to access the stress survey during a designated time, jot down any observations on paper or make a mental note. (See the survey, above, to understand what you'll be looking for.) As soon as you are able, submit the survey.

- When possible, take a photo of what you are doing at each time slot. Save any photographic evidence for possible inclusion in your final report.

@lesson-instruction{
- Make your own copy of @link{https://docs.google.com/presentation/d/1nnPpgCQDYknyxTzc_dvs34R2szxS3izz2Ya5gpAKDtE/copy, this slide template}.
- Edit each slide to share your thinking and findings. 
Add more slides if you need!  
}

=== Synthesize

- What were the pros and cons of working with data generated by you and your classmates?
- What other data do you wish had been part of our collective dataset? What other questions would you suggest adding to the form?

@teacher{
- Once finished, encourage students to self-assess and revise their work. 
- Decide what form of sharing their projects works best for you. 
  * Class presentations can instill a sense of pride. 
  * Presenting in small groups can take less time. 
  * You may also want to have them print some part of their presentation to display on a bulletin board.
- Did your students have brilliant suggestions for how we could improve the form for future classes? Please share your ideas with @link{mailto:contact@bootstrapworld.org}!
}



