= Exploring Image Functions

++++
<style>
.lesson-section-1 { border: 0px !important;	}
.big 			  { font-size: 60pt;		}
.blankline		  { text-align: left;		}
</style>
++++

With your partner, discover as many Image-producing functions as you can!

@vspace{2ex}

Use the space below to draw the Circles of Evaluation for the new functions.
You can also sketch a picture of what the function produces, as shown.

[cols=".^1,.^1,.^1", grid="none", frame="none"]
|===
|@show{(sexp->coe '(star 50 "solid" "black"))}
|produces &rarr;
|@span{.big}{&#9733;}
|===

@vspace{50ex}



== Mystery Functions!

6) There is a function called `text`. Try to figure out how to use it! What do the inputs mean?

@span{.blankline}{The first input (a String) is the string we want to display.}

@span{.blankline}{The second input (a Number) tells us how big to print that string.}

@span{.blankline}{The third input tells us what the color will be.}

7) There is a function called `radial-star` with 5 inputs. What do they mean?

@span{.blankline}{The first input is the number of points in the star. The second and third}

@span{.blankline}{inputs are the outer and inner radius of the star. The fourth input is whether}

@span{.blankline}{the star is solid or outline, and the fifth input is the color.}