[.landscape]
= Contracts

Contracts tell us how to use a function. For example:  `ellipse {two-colons} (Number, Number, String, String) -> Image` tells us that the name of the function is  `ellipse`, it takes four inputs (two Numbers and two Strings), and it evaluates to an `Image`. From the contract, we know  `ellipse(50, 100, "solid", "teal")` will evaluate to an `Image`.

++++
<style>
td {padding: .4em .625em !important; height: 15pt;}
</style>
++++

[.contract-table,cols="4,1,10,1,2", options="header", grid="rows", stripes="none"]
|===
| Name    			|	 | Domain      							|     	| Range

| `# rhombus`
| `{two-colons}`
| `(Number, Number, String, String)`
| `->`
| `Image`
5+|`_rhombus(20, 50, "solid", "turquoise")_`

| `# ellipse`
| `{two-colons}`
| `(Number, Number, String, String)`
| `->`
| `Image`
5+|`_ellipse(30, 70, "outline", "lightblue")_`

| `# text`
| `{two-colons}`
| `(String, Number, String)`
| `->`
| `Image`
5+|`_text("I'm thankful for...", 50, "green")_`

| `# regular-polygon`
| `{two-colons}`
| `(Number, Number, String, String)`
| `->`
| `Image`
5+|`_regular-polygon(8, 40, "solid", "red")_`

| `# radial-star`
| `{two-colons}`
| `(Number, Number, String, String)`
| `->`
| `Image`
5+|`_radial-star(17, 50, 10, "solid", "orange")_`

| `# image-url`
| `{two-colons}`
| `(String)`
| `->`
| `Image`
5+|`_image-url("https://www.bootstrapworld.org/images/icon.png")_`

| `# scale`
| `{two-colons}`
| `(Number, Image)`
| `->`
| `Image`
5+|`_scale( 0.8, triangle(30, "solid", "red"))_`

| `# rotate`
| `{two-colons}`
| `(Number, Image)`
| `->`
| `Image`
5+|`_rotate(35, rectangle(30, 80, "solid", "purple"))_`

| `# overlay`
| `{two-colons}`
| `(Image, Image)`
| `->`
| `Image`
5+|`_overlay(star(30, "solid", "gold"),circle(30, "solid", "blue"))_`

| `# put-image`
| `{two-colons}`
| `(Image, Number, Number, Image)`
| `->`
| `Image`
5+|`_put-image(star(30, "solid", "red"), 50, 150, rectangle(300, 200, "outline", "black"))_`

|===
