[.landscape]
= Contracts

Contracts tell us how to use a function. For example:  `ellipse {two-colons} (Number, Number, String, String) -> Image` tells us that the name of the function is  `ellipse`, it takes four inputs (two Numbers and two Strings), and it evaluates to an `Image`. From the contract, we know  `ellipse(100, 50, "solid", "fuchsia")` will evaluate to an `Image`.

++++
<style>
td {padding: .4em .625em !important; height: 15pt;}
</style>
++++

[.contract-table,cols="4,1,10,1,2", options="header", grid="rows", stripes="none"]
|===
| Name    			|	 | Domain      							|     	| Range


| `# flip-horizontal`
| `{two-colons}`
| `(Image)`
| `->`
| `Image`
5+|`_flip-horizontal(text("Bootstrap is fun!", 60, "darkblue"))_`

| `# flip-vertical`
| `{two-colons}`
| `(Image)`
| `->`
| `Image`
5+|`_flip-vertical(triangle(80, "solid", "lightgreen"))_`

| `# above`
| `{two-colons}`
| `(Image, Image)`
| `->`
| `Image`
5+|`_above(triangle(30, "solid", "red"),square(30, "solid", "blue"))_`

| `# beside`
| `{two-colons}`
| `(Image, Image)`
| `->`
| `Image`
5+|`_beside(star(50, "solid", "orange"),circle(50, "solid", "green"))_`

|`#`
| `{two-colons}` 
|
|`->`
|
5+|`#`

|`#`
| `{two-colons}` 
|
|`->`
|
5+|`#`

|`#`
| `{two-colons}` 
|
|`->`
|
5+|`#`

|`#`
| `{two-colons}` 
|
|`->`
|
5+|`#`

|`#`
| `{two-colons}` 
|
|`->`
|
5+|`#`

|`#`
| `{two-colons}` 
|
|`->`
|
5+|`#`

|===
