[.landscape]
= Contracts

Contracts tell us how to use a function. For example:  `ellipse {two-colons} (Number, Number, String, String) -> Image` tells us that the name of the function is  `ellipse`, it takes four inputs (two Numbers and two Strings), and it evaluates to an `Image`. From the contract, we know  `ellipse(100, 50, "outline", "red")` will evaluate to an `Image`.

++++
<style>
td {padding: .4em .625em !important; height: 15pt;}
</style>
++++

[.contract-table,cols="4,1,10,1,2", options="header", grid="rows", stripes="none"]
|===
| Name    			|	 | Domain      							|     	| Range

| `# num-sqr`			
| `{two-colons}` 
| `(Number)`
| `->`
| `Number`
5+|`_num-sqr(9)_`

| `# num-sqrt`		
| `{two-colons}` 
| `(Number)`
| `->`
| `Number`
5+|`_num-sqrt(25)_`

| `# star`
| `{two-colons}`
| `(Number, String, String)`
| `->`
| `Image`
5+|`_star(50, "solid", "teal")_`

| `# circle`
| `{two-colons}`
| `(Number, String, String)`
| `->`
| `Image`
5+|`_circle(30, "outline", "fuchsia")_`

| `# triangle`
| `{two-colons}`
| `(Number, String, String)`
| `->`
| `Image`
5+|`_triangle(80, "solid", "darkgreen")_`

| `# square`
| `{two-colons}`
| `(Number, String, String)`
| `->`
| `Image`
5+|`_square(10, "outline", "red")_`

| `# rectangle`
| `{two-colons}`
| `(Number, Number, String, String)`
| `->`
| `Image`
5+|`_rectangle(20, 80, "solid", "gold")_`

| `# ellipse`
| `{two-colons}`
| `(Number, Number, String, String)`
| `->`
| `Image`
5+|`_ellipse(30, 70, "outline", "lightblue")_`

| `# regular-polygon`
| `{two-colons}`
| `(Number, Number, String, String)`
| `->`
| `Image`
5+|`_regular-polygon(8, 40, "solid", "red")_`

| `# radial-star`
| `{two-colons}`
| `(Number, Number, String, String)`
| `->`
| `Image`
5+|`_radial-star(17, 50, 10, "solid", "orange")_`
|===
