= Intro to CODAP & Displaying Categorical Data

@description{Students learn to generate and compare bar graphs, explore other plotting & display functions in CODAP, and (optionally) design an infographic.}

@add-to-lang{bar-chart, pie-chart, pie-chart-summarized, bar-chart-summarized, histogram, box-plot, scatter-plot}

[@lesson-intro-table]
|===
@lesson-prereqs{}
| Lesson Goals
| Students will be able to:

* Read bar charts
* Generate bar charts (among other data displays) from the Animals Dataset


| Student-facing Lesson Goals
|

* Let's get to know CODAP by creating bar graphs and other data displays from tables.

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/1MaNFBTVZIBXsvfn8I4f_0IQhoXYQHgEWkqGtQda2DG8/edit?usp=sharing, Lesson slides}
* @link{https://codap.concord.org/app/static/dg/en/cert/index.html#shared=https%3A%2F%2Fcfm-shared.concord.org%2FeZEwgF1qSm396MC6CNM9%2Ffile.json, Animals Dataset in CODAP}

@material-links

| Preparation
|
@preparation


| Supplemental Resources
| @link{https://informationisbeautiful.net/, Information is Beautiful}

@lang-prereq
|===

== Welcome to CODAP! @duration{10 minutes}
=== Overview

Students use the options on CODAP's _Configuration_ menu to produce displays and plots of the Animals Dataset.

=== Launch
Where have you seen infographics and graphs used to display data in the real world?


Open the @link{https://codap.concord.org/app/static/dg/en/cert/index.html#shared=https%3A%2F%2Fcfm-shared.concord.org%2FeZEwgF1qSm396MC6CNM9%2Ffile.json, Animals Dataset} in CODAP.

[.lesson-instruction]
--
- Click the `graph` icon from the horizontal toolbar in the upper left. (See toolbar, below.) What appears?

@centered-image{images/codap-upper-left-toolbar.png, CODAP upper left toolbar, 300}

- Select a dot with your mouse. What happens?
- Try generating the graph again. Does it look the same or different? Why might this be relevant?
- What happens when you select a table row? How about multiple table rows?
- What happens when you click the "eye" icon (to the right of the graph or the table, depending on which is selected)?
--

@right{@image{images/codap-initial-display.png,"An image of the CODAP environment" ,300}}

**If students report that a blank graph appears (rather than a scatterplot), prompt them to whitelist CODAP on their ad-blocker. Ad-blockers do seem to inhibit some of the functionality of CODAP (which will fortunately never advertise to users!).**

Initially, the data points are randomly distributed on the graph. Selecting an orange dot reveals the `name` of that particular animal. Selecting a particular dot causes the table row for that animal to be highlighted in blue. Holding the shift button allows students to select multiple dots in the graphical display, or multiple rows in the table.

Students should observe that when they select a table row (or multiple table rows), the corresponding dots change from orange to turquoise. When they set aside selected and / or unselected cases (by using the "eye" icon), they can temporarily alter the amount of pets in the dataset (with the option to restore to the original dataset).

Students can also resize the window by dragging its borders.


=== Investigate

Once we have a graph of randomly distributed data points, we can organize the data by selecting attributes from our _table_ that we want to appear on the axes of our graph.

Experiment with creating some bar charts in CODAP by following the steps below.
[.lesson-instruction]
- Select the y-axis on your graph (where it says "Click here"). On the drop-down menu that appears, select `fixed`. What do you notice?
- Now select the x-axis on your graph and select `fixed`. How does the graph change?
- Select the `configuration` icon (which looks like a bar graph) to the right of the data display. Select `fuse dots into bars`.
- Click the `ruler` icon; test out each of the two options available (count and percentage). What happens?
- Now, make a bar chart showing how many animals there are of each species by changing the variable on the x-axis to `species`.
- Create a graph with `weight` on the x-axis. Now select `weight` so that a drop-down menu appears. Observe how the graph changes when you select `Treat as Categorical`?
- Can you `fuse dots into bars` when treating `weight` categorically? Numerically? Why does CODAP _sometimes_ invite you to `fuse dots into bars` - but other times the option does not appear?

To dig deeper into bar charts, have students turn to @opt-printable-exercise{bar-chart-notice.adoc}.


[.strategy-box, cols="1", grid="none", stripes="none"]
|===
a|
@span{.title}{People aren't Hermaphrodite?}
When students make a display of the `sex` of the animals, they will see that some animals are male, some are female and some are hermaphrodites. We use the descriptor _sex_ rather than _gender_ because sex refers to biology, whereas gender refers to identity. Hermaphrodite is the biological term for animals that carry eggs & produce sperm (nearly 1/3 of the non-insect animal species on the planet!). Plants that produce pollen & ovules are also hermaphrodites. While the term was previously used by the medical community to describe intersex people or people who identify as transgender or gender non-binary, it is not biologically accurate. Humans are not able to produce both viable eggs and sperm, so "hermaphrodite" is no longer considered an acceptable term to apply to people.
|===


=== Common Misconceptions

Bar charts look a lot like another kind of chart - called a "histogram" - which are actually quite different because they display _quantitative_ data, not categorical. Making a histogram in CODAP, however, begins quite similarly to making a bar chart in CODAP - by creating a dot plot that will be modified.

=== Synthesize
Bar charts display how much of the sample belongs to each category. If they are based on sample data from a larger population, we use them to _infer_ the proportion of a whole population that might belong to each category.

[.lesson-point]
Bar charts are mostly used to _display categorical columns_.

While bars in some bar charts should follow some logical order (alphabetical, small-medium-large, etc), they can technically be placed in _any_ order, without changing the meaning of the chart.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
a|
@span{.title}{Mini Project: Making Infographics}
Infographics are a powerful tool for communicating information, especially when made by people who actually understand how to connect visuals to data in meaningful ways. @opt-project{infographics.adoc, infographic-rubric.adoc} is an opportunity for students to become more flexible math thinkers while tapping into their creativity. This project can be made on the computer or with pencil and paper. There's also an @link{pages/infographic-rubric.html, Infographics Rubric} to highlight for you and your students what an excellent infographic includes.
|===

== Exploring other Displays @duration{30 minutes}

=== Overview
Students freely explore the CODAP data display options available to them when they select the bar graph icon (also known as the Configuration menu). In doing so, they experiment with new charts and get comfortable with CODAP as a platform for doing data science.


=== Launch
There are _lots_ of different kinds of charts and plots. Even if you don’t know what these plots are for yet, see if you can figure out how to use them.

[.lesson-instruction]
- Open a scatterplot of randomly positioned points derived from the @link{https://codap.concord.org/app/static/dg/en/cert/index.html#shared=https%3A%2F%2Fcfm-shared.concord.org%2FeZEwgF1qSm396MC6CNM9%2Ffile.json, Animals Dataset} by clicking on the `graph` icon again.
- Now, select the `Weight` attribute/column on the x-axis, or drag it there.
- Select the icon that looks like a ruler; it is the `Measure` icon. Try producing a box plot by selecting the appropriate option from this menu.
- With `Weight` still on the x-axis, select `Time to Adoption` on the y-axis.
- Take another look at the `Measure` menu, now that your data display is two-dimensional. Which options do you see that did not appear before?
- Try producing a least squares line (also known as a regression line) by using the `Measure` menu.

=== Investigate
[.lesson-instruction]
Complete @printable-exercise{pages/exploring-displays-1.adoc} and @printable-exercise{pages/exploring-displays-2.adoc}.

=== Common Misconceptions
There are _many_ possible misconceptions about displays that students may encounter here. *But that's ok!* Understanding all those other plots is _not_ a learning goal for this lesson. Rather, the goal is to have them develop some loose familiarity.

=== Synthesize
Today you’ve added more data displays to your toolbox. You can create bar charts to visually display data, and even transform entire tables!

You will have many opportunities to use these concepts in this course, by applying what you've learned to answer data science questions.

== Additional Exercises:
@opt-printable-exercise{pages/plot-practice.adoc}
