= Evaluating Exponents

@description{Students use Circles of Evaluation to visualize the structure of expressions that include exponents.}

@lesson-prereqs{variables}

@keywords{exponent, base}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Translate between words, mathematical expressions, and Circles of Evaluation.
* Evaluate expressions involving exponents and one other operation.
* Evaluate expressions involving exponents and negatives.


| Student-facing Lesson Goals
|

* Let's use Circles of Evaluation to visualize the structure of expressions with exponents.

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
* Ensure that students are comfortable evaluating exponents during the Launch. Circles of Evaluation will help students parse expressions that involve exponents.

|===

== Expressions with Exponents and One Operation @duration{30 minutes}

=== Overview

Sudents use Circles of Evaluation, words, and arithmetic to visualize the structure of expressions with exponents and one operation.

=== Launch

Show students the following expression: @math{2^3}

@lesson-instruction{
- One way of reading this expression is "two raised to the power of three." Do you know any other ways of translating this expression into words?

** _Two to the third power; two to the third; two cubed_

@right{@image{images/cube.png, 150}}

- What does it mean to _cube_ a number?

** _We multiply it by itself three times. (Literally, we compute the volume of a cube with a side length of that number; see image on right.)_

- What does this expression evaluate to?
** @math{2^3 = 2 \times 2 \times 2 = 8}
}

Clarify and reinforce some key concepts about exponents via class discussion:

- The number on the left is called the @vocab{base}. That number is multiplied by itself when we apply the exponent.

- The smaller, raised number after the base is called the @vocab{exponent}; it indicates how many times to multiply the base.

- "Cubing" is the same as "raising to the third power", and "squaring" is the same as raising to the second power.

- There is no special terminology for any other exponents.

Explain to students that we can represent expressions with exponents as Circles of Evaluation. The function we use to do so is called `expt`; when we use `expt`, the first value in the Circle of Evaluation is the _base_, and the second value is the _exponent_.

Take a look at the two @vocab{equivalent} Circles of Evaluation, below. One is written in exponent notation, and the other is written in expanded notation.

[.embedded, cols="^.^5,^.^1,^.^5", grid="none", stripes="none" frame="none"]

|===
| @math{2^5}
|
| @math{2 \times 2 \times 2 \times 2 \times 2}

| @show{(coe '(expt 2 5))}
| @math{=}
| @show{(coe '(* (* (* (* 2 2) 2) 2) 2))}
|===

@lesson-point{
Exponents are valuable because they act as a shorthand.
}

The Circle of Evaluation with `expt` is a lot shorter and easier to read!

@lesson-instruction{
- Turn to @printable-exercise{exponents-intro.adoc}, where you will practice translating verbal exponent expressions into exponent notation, expanded notation, and Circles of Evaluation.
- When you're done, consider the Circle of Evaluation (below) that Jayla drew to represent the expanded form of @math{2^4}.

@show{(coe  '(* (* 2 2) (* 2 2)))}

- Jayla's Circle is different from the solution provided for the first problem on the worksheet. Is her response correct? Why or why not?
** _Yes, students may group the bases in a variety of ways, as per the @vocab{Associative Property} of Multiplication!_
}

Ensure that students are comfortable shifting between representations before discussing some common difficulties with interpreting exponents.

@lesson-instruction{

- Angela says the Circles of Evaluation below are equivalent because of the @vocab{Commutative Property}. Do you agree with Angela?

** _Angela is incorrect. The first expression evaluates to 25, while the second expression evaluates to 32. We cannot switch the order of the exponent and the base, as we could when adding or multiplying values._

[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===
|@math{5^2}							| @math{2^5}
|@show{(coe  '(expt 5 2))}		| @show{(coe  '(expt 2 5))}
|===

- Are these two Circles of Evaluation (below) equivalent? Explain.
** _No; multiplying the base by the exponent is a common student error which produces a different result than multiplying the base by the base._


[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===
|@math{5^2}							| @math{5 \times 2}
|@show{(coe  '(expt 5 2))}		| @show{(coe  '(* 5 2))}
|===
}

With a basic understanding of how exponents work, students are ready to discover how Circles of Evaluation can help them in analyzing more complicated expressions with exponents.

=== Investigate

@lesson-instruction{
- Look at the two Circles of Evaluation below:

[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===

|@show{(coe  '(* 9 (expt 3 2)))}		| @show{(coe  '(expt (* 9 3) 2))}
|===

- How would you translate each of these Circles of Evaluation into verbal expressions? Why are their translations different?
** _The Circle of Evaluation on the left is "nine multiplied by three squared," while the Circle of Evaluation on the right is "find the product of nine and three, then square it." Their translations differ because the Circles of Evaluation are organized differently._
- How would you translate each of these Circles of Evaluation into mathematical expressions?
** The Circle of Evaluation on the left is @math{9 \times 3^2} while the Circle of Evaluation on the right is @math{(9 \times 3)^2}.
}

Students will likely suggest @math{9 \times (3^2)} as a translation for the Circle of Evaluation on the right. This response is correct - but it is valuable for students to recognize that expressions with exponents are often written _without_ the parentheses. That said, the base and the exponent should always be placed within a Circle.

@lesson-point{
In an expression with no grouping symbols, we evaluate the exponent before the other operations.
}

In the subsequent activities, students solidify their understanding of this key concept.

@lesson-instruction{
- Try the @printable-exercise{matching-expressions-to-circles.adoc} to practice matching Circles of Evaluation with their corresponding mathematical expressions.
- Translate between Circles of Evaluation, mathematical expressions, and words on @printable-exercise{translating-exponent-expressions.adoc}
- In @printable-exercise{wodb.adoc}, examine each Circle of Evaluation to determine which expressions in the set are equivalent.
}

The first two pages above do not involve _any_ computation; rather, students think about the structure of expressions with exponents and one operation. The third page in the set involves some computation; students who consider structure in addition to computation will complete the activity more efficiently.


=== Synthesize

- Is @math{2 + (6^2)} equivalent to @math{2 + 6^2}? Why or why not?
** _Yes, these expressions are equivalent. Applying an exponent is a function separate from addition, regardless of whether we put it in parentheses or not._
- Is @math{2 + 6^2} equivalent to @math{(2 + 6)^2}? Why or why not?
** _No, these expressions are not equivalent. For the first expression, we apply the exponent and then multiply. For the second expression, we multiply and then apply the exponent._



== Expressions with Exponents and Variables @duration{25 minutes}

=== Overview

Students use Circles of Evaluation to parse and evaluate exponential expressions with variables.

=== Launch

@lesson-instruction{
- Ms. Brenneman asked her class to draw Circles of Evaluation to represent @math{4m^2}. Four students produced four different Circles of Evaluation (below).
- Which Circle of Evaluation do you think matches the expression? If you're not sure, are there any that you can rule out right away?
** _Sample response: Jayla's Circle of Evaluation is correct. I know that Keke's response is incorrect because we cannot change the order of the base and the exponent. Joe's Circle of Evaluation doesn't work because he added rather than finding a product. Aaron squared @math{4m}, rather than just squaring @math{m}._


[.embedded, cols="^.^1,^.^1", grid="none", stripes="none", frame="none"]
|===
| Keke: @show{(coe  '(* 4 (expt 2 m)))} | Jayla: @show{(coe  '(* 4 (expt m 2)))}
| Joe: @show{(coe  '(+ 4 (expt m 2)))}  | Aaron: @show{(coe  '(expt (* 4 m) 2))}
|===

}

Lead a discussion where students explain which Circle of Evaluation they chose and why.

Explain to students that when we _evaluate_ an @vocab{algebraic expression}, we substitute in a given value for the variable and then simplify the expression to a single number. Circles of Evaluation can help us avoid common pitfalls when evaluating algebraic expressions by helping us to see the structure of each expression.

@lesson-instruction{
- Let's evaluate the Circles of Evaluation made by Keke, Jayla, Joe, and Aaron using @math{m = 5}.
** _Depending on your students' level of comfort evaluating algebraic expressions, you may want to complete one or more of the expressions as a class. Try simply replacing the @math{m} in each Circle of Evaluation with @math{5}._
- Do any of the expressions produce the same outcome? Why or why not?
** _Each Circle of Evaluation has a different result because they all have different structures; one Circle of Evaluation even uses addition rather than multiplication. Jayla's evaluates to 100; Keke's evaluates to 132; Joe's evaluates to 29; and Aaron's evaluates to 400._
}

Ensure that students understand that - even with the inclusion of variables - we apply the exponent _before_ applying other operations (unless the parentheses indicate otherwise!).

=== Investigate

@lesson-instruction{
- Turn to @printable-exercise{exponents-variables-table.adoc}. Draw a Circle of Evaluation to represent each expression that is provided in the left-hand column. The first one is done for you.
- Once you have completely filled in the Circle of Evaluation column, move to the Evaluate column, where you will evaluate each expression by substituting in the given value.
}

=== Common Misconceptions

Students who are new to expressions like @math{4m^2} may misinterpret them. Explain that this notation represents multiplication - not that the 4 and @math{m} are contiguous digits.

=== Synthesize

- Jayla says that she likes to imagine an "invisible parentheses" enclosing every base and exponent. What is she describing? Do you find this helpful?
- What was your strategy for evaluating expressions with variables and exponents?
