= Evaluating Exponents

@description{Students use Circles of Evaluation analyze the structure of expressions that include exponents.}

@lesson-prereqs{absolute-value-and-opposites-2}

@keywords{exponent, base}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Translate between words, mathematical expressions, and Circles of Evaluation.
* Evaluate expressions involving exponents and one other operation.
* Evaluate expressions involving exponents and negations.


| Student-facing Lesson Goals
|

* Let's use Circles of Evaluation to analyze the structure of expressions with exponents.

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
* Ensure that students are comfortable evaluating exponents during the Launch. Circles of Evaluation will help students parse expressions that involve exponents.

|===

== Expressions with Exponents and One Operation @duration{30 minutes}

=== Overview

Sudents use Circles, words, and mathematical notation to analyze the structure of expressions with exponents and one operation.

=== Launch

[.lesson-instruction]
- Show students the following expression: @math{2^3}
- One way of reading this expression is "two raised to the power of three." Do you know any other ways of translating this expression into words?
** _Two to the third power; two to the third; two cubed_
- What does it mean to _cube_ a number?
** We multiply it by itself three times (literally, compouting the volume of a cube with a side-length of that number)
- What does this expression evaluate to?
** @math{2^3 = 2 \times 2 \times 2 = 8}

Clarify and reinforce some key concepts about exponents via class discussion:

- The number on the left is called the @vocab{base}. That number is multiplied by itself when we apply the exponent.

- The smaller, raised number after the base is called the @vocab{exponent}; it indicates how many times to multiply the base.

- "Cubing" is the same as "raising to the third power", and "squaring" is the same as raising to the second power.

- There is no special terminology for any other exponents.

Explain to students that we can represent expressions with exponents as Circles of Evaluation. The function we use to do so is called `num-expt`; when we use `num-expt`, the first value is the _base_, and the second value is the exponent.

[.lesson-point]
Exponents are valuable because they act as a shorthand.

The Circle of Evaluation for @math{2 \times 2 \times 2 \times 2 \times 2} looks like this:

[.centered-image]
@show{(coe '(* (* (* (* 2 2) 2) 2) 2))}

Here is the Circle of Evaluation for @math{2^5}, an equivalent expression:

[.centered-image]
@show{(coe '(num-expt 2 5))}

The Circle of evaluation with `num-expt` is a lot shorter, and easier to read!

[.lesson-instruction]
--
- Take a look at the expressions and Circles below.

[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===
|@math{5^2}							| @math{2^5}
|@show{(coe  '(num-expt 5 2))}		| @show{(coe  '(num-expt 2 5))}
|===

- Angela says the Circles are equivalent because of the Commutative Property. Do you agree with Angela?
** _Angela is incorrect. The first Circle evaluates to 25, while the second Circle evaluates to 32. We cannot switch the order of the exponent and the base, as we could when adding or multiplying values._
- Look at the two expressions and Circles, below.

[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===
|@math{5^2}							| @math{5 \times 2}
|@show{(coe  '(num-expt 5 2))}		| @show{(coe  '(* 5 2))}
|===
- Are these two Circles equivalent?
** _No; multiplying the base by the exponent is a common student error which produces a different result than multiplying the base by the base._
--

With a basic understanding of how exponents work, students are ready to discover how Circles can help them in analyzing more complicated expressions with exponents.

=== Investigate

[.lesson-instruction]
--
- Look at the two Circles below:

[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===

|@show{(coe  '(* 9 (num-expt 3 2)))}		| @show{(coe  '(num-expt (* 9 3) 2))}
|===

- How would you translate each of these Circles into words? Why are their translations different?
** _The Circle on the left is "nine multiplied by three squared," while the Circle on the right is "find the product of nine and three, then square it." Their translations differ because the Circles are organized differently._
- How would you translate each of these Circles into mathematical expressions?
** The Circle on the left is @math{9 \times 3^2} while the Circle on the right is @math{(9 \times 3)^2}.
--

Students will likely suggest @math{9 \times (3^2)} as a translation for the Circle on the right. This response is correct - but it is valuable for students to recognize that expressions with exponents are often written _without_ the parentheses. That said, the base and the exponent should always be placed within a Circle.

[.lesson-point]
In an expression with no grouping symbols, we evaluate the exponent before the other operations.

In the subsequent activities, students solidify their understanding of this key concept.

[.lesson-instruction]
- Try the @printable-exercise{expression-to-circles-matching.adoc} to practice matching Circles with their corresponding mathematical expressions.
- Translate between Circles, mathematical expressions, and words on @printable-exercise{translating-exponent-expressions.adoc}
- In @printable-exercise{wodb.adoc}, analyze the Circles to determine which expressions in the set are equivalent.

The first two worksheets above do not involve _any_ computation; rather, students think about the structure of expressions with exponents and one operation. The third worksheet in the set involves some computation; students who consider structure in addition to computation will complete the activity more efficiently.


=== Synthesize

- Is @math{2 + (6^2)} equivalent to @math{2 + 6^2}? Why or why not?
** _Yes, these expressions are equivalent. Applying an exponent is a function separate from addition, regardless of whether we put it in parentheses or not._
- Is @math{2 + 6^2} equivalent to @math{(2 + 6)^2}? Why or why not?
** _No, these expressions are not equivalent. For the first expression, we apply the exponent and then multiply. For the second expression, we multiply and then apply the exponent._



== Expressions with Exponents and Variables @duration{25 minutes}

=== Overview

Students use Circles of Evaluation to parse and evaluate exponential expressions with variables.

=== Launch

[.lesson-instruction]
--
- Ms. Brenneman asked her class to evaluate @math{4m^2}, when @math{m = 5}. Four students produced four different Circles! Take a look at their work:
[.embedded, cols="^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===
| Keke: @show{(coe  '(* 4 (num-expt 2 m)))} | Jayla: @show{(coe  '(* 4 (num-expt m 2)))}
| Joe: @show{(coe  '(+ 4 (num-expt m 2)))}  | Aaron: @show{(coe  '(num-expt (* 4 m) 2))}
|===
- Which Circle do you think matches the expression? If you're not sure, are there any that you can rule out right away?
** _Sample response: Jayla's Circle is correct. I know that Keke's response is incorrect because we cannot change the order of the base and the exponent. Joe's Circle oesn't work because he added rather than finding a product. Aaron squared @math{4m}, rather than just squaring @math{m}._
- Evaluate each Circle. Do any of them produce the same outcome? Why or why not?
** _Each Circle has a different result because they all have different structures; one Circle even uses addition rather than multiplication. Jayla's Circle is 100; Keke's is 132; Joe's is 29; and Aaron's is 400._
--

Lead a discussion where students explain which Circle they chose and why. Ensure that students understand that - even with the inclusion of variables - we still apply the exponent _before_ applying other operations.

=== Investigate

[.lesson-instruction]
- Turn  to @printable-exercise{exponents-variables-table.adoc}. Draw a Circle to match each expression. The first one is done for you.
- Once you have completely filled in the second column, move to the third column, where you will evaluate each expressions by substituting in the given value.

=== Common Misconceptions

Students who are new to expressions like @math{4m^2} may misinterpret them. Explain that this notation represents multiplication - not that the two digits are simply next to one another.

=== Synthesize

What was your strategy for evaluating expressions with variables and exponents?
