(
"DefiningFunctions3CoverPage.pdf"
"WordProblems.pdf"
"DesignRecipe1.pdf"
"PurposeStatement3ReadsStrongerClearer.pdf"
"DesignRecipe1.pdf"
"PurposeStatement3ReadsStrongerClearer.pdf"
"DesignRecipe1.pdf"
"PurposeStatement3ReadsStrongerClearer.pdf"
"DesignRecipe1.pdf"
"PurposeStatement3ReadsStrongerClearer.pdf"
)
