= Simple Datatypes

@lesson-description{Students begin to program in Pyret, learning about basic datatypes, operations, and value definitions.}

[@lesson-intro-table]
|===
@prereqs-stds{}
| Lesson Goals
| Students will be able to...

* Identify the data types: Numbers, Strings, and Booleans
* Write Numbers, Strings, and Booleans in the Interactions Area

| Student-facing Lesson Goals
|

* Let's explore programming in Pyret and learn about data types.

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/1EEqfeSF4b5aft8O6Sv7eP6Yfm1LxYPeVv85d2FO8W_4/, Lesson Slides}

@material-links

| Preparation
|
* Make sure all materials have been gathered
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with
* Decide how students will be grouped in pairs
* Make sure student computers can access @ifproglang{pyret}{@link{https://code.pyret.org, the Pyret IDE (CPO)}} @ifproglang{wescheme}{@link{https://www.wescheme.org, WeScheme}}

| Supplemental Resources
|

@lang-prereq

| Key Points For The Facilitator
|
* Error messages are the computer trying to give us a clue that something is wrong.  Model reacting to @vocab{error messages} with interest to demonstrate to students that the messages are a helpful tool.

|===

[.old-materials]
Click here to see the @link{https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/units/unit1/index.html, prior unit-based version}.

== Numbers & Strings @duration{20 minutes}

=== Overview
Students experiment with the Editor, exploring the different kinds of numbers and strings and how they behave in this programming language.

=== Launch

@ifproglang{wescheme}{ 
Students should open @link{https://www.wescheme.org, WeScheme} in their browser, and click "Log In". This will ask them to log in with a valid Google account (Gmail, Google Classroom, YouTube, etc.), and then show them the "My Programs" page. This page is empty - they don't have any programs yet! Have them click "Start a New Program".
}

@ifproglang{pyret}{
Students should open @link{https://code.Pyret.org, code.pyret.org (CPO) } in their browser, and click "Sign In". This will ask them to log in with a valid Google account (Gmail, Google Classroom, YouTube, etc.), and then show them the "Programs" page. This page is empty - they don't have any programs yet! Have them click "Open Editor".
}

@span{.right}{@image{images/editor.png, "Our Editing Environment", 300, ""}}
This screen is called the @vocab{Editor}, and it looks something like the diagram you see here. There are a few buttons at the top, but most of the screen is taken up by two large boxes: the @vocab{Definitions Area} on the left and the @vocab{Interactions Area} on the right.

The @vocab{Definitions Area} is where programmers define values and functions that they want to keep, while the @vocab{Interactions Area} allows them to experiment with those values and functions. This is like writing function definitions on a blackboard, and having students use those functions to compute answers on scrap paper.

[.lesson-point]
For now, we will only be writing programs in the *Interactions Area* on the right.

@span{.clear}{}

=== Investigate

Math is a language, just like English, Spanish, or any other language. Languages have *nouns* (e.g. “ball”, “tomato”, etc.) and *verbs*, which are actions we can perform on these nouns (e.g. - I can “throw a ball”). Math and programming also have *values*, like the numbers 1, 2 and 3. And, instead of verbs, they have functions, which are actions we can perform on values (e.g. - “I can square a number”).

Languages also have rules for *syntax*. In English, for example, words don’t have `!` and `?` in the middle. In math and programming, for example, numbers don’t have `&` in them.
Languages also have rules for *grammar*. In English the order in which we arrange the words in a sentence is important! `The cat sat.` is a sentence, whereas `The sat cat` is nonsense, even though the syntax of all the words is valid! In math, it doesn’t make sense to write `4 +` , even though the syntax of all the pieces is valid!
Keeping the importance of *syntax* and *grammar* in mind is helpful when learning to program!.

[.lesson-instruction]
--
Have students complete @printable-exercise{numbers-n-strings.adoc}. Ask them to pay special attention to the error messages!

- What did you Notice? What do you Wonder?
- Did you get any error messages? What did you learn from them?


@ifproglang{pyret}{
*Student Misconceptions:* Writing decimals as `.5` (without the leading zero) results in an error message. Make sure students understand that Pyret has decimals and they just need to add the zero!
}

--

=== Synthesize
Our programming language knows about many types of numbers, and they behave pretty much the way they do in math. 
Discuss what students have learned:

- Numbers and Strings evaluate to themselves.
- Our Editor is pretty smart, and can automatically switch between showing a rational number as a fraction or a decimal, just by clicking on it!
- Anything in quotes is a String, even something like `"42"`.
- Strings _must_ have quotation marks on both sides.

@ifproglang{pyret}{
- @vocab{Operators} like `+`, `-`, `*`, and `/` need spaces around them.
- In pyret, the @vocab{operators} work just like they do in math.
- Any time there is more than one operator being used, Pyret requires that you use parentheses to define the order of operations.
- Types matter! We can add two Numbers or two Strings to one another, but we can’t add the Number `4` to the String `"hello"`.

Error messages are a way for Pyret to explain what went wrong, and are a really helpful way of finding mistakes. Emphasize how useful they can be, and why students should read those messages out loud before asking for help. Have students see the following errors:

- `6 / 0`. In this case, Pyret obeys the same rules as humans, and gives an error.
- `(2 + 2`. An unclosed quotation mark is a problem, and so is an unmatched parentheses.
}

== Booleans @duration{20 minutes}

=== Overview
This lesson introduces students to @vocab{Booleans}.  

=== Launch

Boolean-producing expressions are yes-or-no questions and will always evaluate to either `true` (“yes”) or `false` (“no”).  The ability to separate inputs into two categories is unique and quite useful.  For example, some rollercoasters with loops require passengers to be a minimum height to make sure that riders are safely held in place by the one-size-fits all harnesses. The gate keeper doesn't care exactly how tall you are, they just check whether you are as tall as the mark on the pole. If you are, you can ride, but they don't let people on the ride who are shorter than the mark because they can't keep them safe.  Similarly, when you log into your email, the computer asks for your password and checks whether it matches what's on file. If the match is `true` it takes you to your messages, but, if what you enter doesn't match, you get an error message instead. Brainstorm other scenarios where Booleans are useful in and out of the programming environment.

=== Investigate
[.lesson-instruction]
--
In pairs, students complete @printable-exercise{pages/booleans.adoc}, making predictions about what a variety of Boolean expressions will return and testing them in the editor.
--

=== Synthesize
Debrief student answers as a class.  
[.lesson-instruction]
- What sets Booleans apart from other datatypes?

