= Circle of Evaluation to Code (Scaffolded)
++++
<style>
.codetwo { background: none; }
</style>
++++
== Complete the Code by Filling in the Blanks!

Finish the Code by filling in the blanks. +
@teacher{The answers below are shown with _all_ parentheses included. There are also correct solutions in which the unnecessary parentheses are left out.}

@do{
  (define expra '(overlay (circle 5 "solid" "tan") (square 9 "solid" "red")))
  (define codea '(overlay (circle (?ANS 5) "solid" (?ANS "tan")) ((?ANS square) 9 (?ANS "solid") "red")))
}

@n @show{(coe expra)}  

@show{(code codea #:parens true)}



== Complete the Code by adding Parentheses

For each Circle of Evaluation, finish the Code by adding parentheses@ifproglang{pyret}{ and commas}. +
@teacher{The answers below are shown with _all_ parentheses included. There are also correct solutions in which the unnecessary parentheses are left out.}

@do{
  (define expr1 '(beside (triangle 5 "solid" "blue") (circle 8 "outline" "red")))
  (define expr2 '(rotate 8 (above (star 5 "solid" "gold") (triangle 3 "solid" "green") )))
  (define expr3 '(beside (rotate 9 (triangle 5 "solid" "blue") ) (circle 8 "outline" "red")))
}

@n @show{(coe expr1)}    

@vspace{1ex}

[.codetwo]
beside @hspace{1em} triangle @hspace{1em} 5 @hspace{1em} "solid" @hspace{1em} "blue" @hspace{1em} circle @hspace{1em} 8 @hspace{1em} "outline" "red"
  
@showsoln{(code expr1 #:parens true)}

@vspace{1ex}

@n @show{(coe expr2)}    

@vspace{1ex}

[.codetwo]
rotate @hspace{1em} 8 @hspace{1em} above @hspace{1em} star @hspace{1em} 5 @hspace{1em} "solid" @hspace{1em} "gold" @hspace{1em} triangle @hspace{1em} 3 @hspace{1em} "solid" @hspace{1em} "green" 

@showsoln{(code expr2 #:parens true)}

@vspace{1ex}

@n @show{(coe expr3)}    

@vspace{1ex}

[.codetwo]
beside @hspace{1em} rotate @hspace{1em} 9 @hspace{1em} triangle @hspace{1em} 5 @hspace{1em} "solid" @hspace{1em} "blue" @hspace{1em} circle @hspace{1em} 8 @hspace{1em} "outline" @hspace{1em} "red"

@showsoln{(code expr3 #:parens true)}


