= Frayer Model: Domain and Range

++++
<style>
  :root {
    --gap: 25px;
  }
  .solution * { font-weight: normal; font-size: 10pt; margin-top: 2ex; }
  #content td {
    border: solid 1px black;
    border-radius: 25px;
    padding: 10px;
  }
  .sectionbody { align-items: center; }
  table {
    width: 6.5in;
    grid-gap: var(--gap);
    color: #444;
    font-size: 14pt;
    font-weight: bold;
    border: none !important;
    grid-template-columns: 48% 48% !important;
    position: relative;
  }

  tr:first-child td:first-child:after {
    content: "Domain";
    display: grid;
    align-items: center;
    justify-items: center;
    border: 1px solid black;
    width: 50%;
    height: 50%;
    border-radius: 50%;
    position: absolute;
    /* offset position is calculated via
     * .5 * (100% + width% + gap)
     */
    left: calc(.5 * (100% + 50% + var(--gap)));
    top:  calc(.5 * (100% + 50% + var(--gap)));
    background: white;
    z-index: 2;
    font-style: italic;
  }

  table:first-child tr:first-child td:first-child:after { content: "Domain"; }
  table:last-child tr:first-child td:first-child:after { content: "Range"; }
</style>
++++

[.FillVerticalSpace, cols="1a,>1a", frame="none", stripes="none"]
|===
|
My Definition
@ifsoln{
Domain - the set of all possible values that a function consumes
}

|
Facts and Characteristics
@ifsoln{
Domains are always expressed as *sets*, not
specific *values*

A Range can only have one part.

Ranges are always expressed as *sets*, not specific *values*

Domains can have multiple parts: a function
}

|
Examples
@ifsoln{
Domains can use named sets....

- Numbers, Rational Numbers, etc.

- Strings, Strings that represent colors, etc.

Or use set notation... {...-2, -1, 0, 1, 2, …}, {true, false}, etc

Domains can have multiple parts... (Number, Number, String, String)
}

|
Non-Examples
@ifsoln{
Specific values cannot be Domains:
4 “hello” true
}
|===

@vspace{5ex}

[.FillVerticalSpace, cols="1a,>1a", stripes="none"]
|===
|
My Definition
@ifsoln{
Range - the set of all possible values a function can produce
}

|
Facts and Characteristics
@ifsoln{
A Range can only have one part.

Ranges are always expressed as *sets*, not specific *values*
}

|
Examples
@ifsoln{
Ranges can use named sets....

- Numbers, Rational Numbers, etc.
- Strings, Strings that represent colors, etc.

Or use set notation... {...-2, -1, 0, 1, 2, …}, {true, false}, etc
}

|
Non-Examples
@ifsoln{
Specific values cannot be Ranges:
4 “hello” true

Multiple sets cannot be ranges: Number, String
}
|===
