= Triangle Contracts (SAS & ASA)

++++
<style>
td, #content .forceShading { font-size: 1rem !important; }
#content p { font-size: 0.9rem; margin: 0;}
#content .listingblock .highlight { padding: 0; }
.forceShading { background: #f7f7f8; }
</style>
++++

Type each expression (left) below into the @starter-file{editor} and match it to the image it creates (right).

[.FillVerticalSpace, cols="^.^18a,^.^2,3,^.^2,^.^8a",stripes="none",grid="none",frame="none", options="header"]
|===
| Expression
|||
| Image

| @show{(code '(triangle-sas 120 45 70 "solid" "black"))}
| *@n* @ifsoln{-D} || *A*
| @centered-image{../images/sas-120-90-70.png, 55}

| @show{(code '(triangle-sas 120 90 70 "solid" "black"))}
| *@n* @ifsoln{-A} || *B*
| @centered-image{../images/sas-120-135-70.png}

| @show{(code '(triangle-sas 120 135 70 "solid" "black"))}
| *@n*@ifsoln{-B} || *C*
| @centered-image{../images/sas-70-135-120.png}

| @show{(code '(triangle-sas 70 135 120 "solid" "black"))}
| *@n*@ifsoln{-C} || *D*
| @centered-image{../images/sas-120-45-70.png}
|===

Think about how you would describe each of the arguments that @show{(code 'triangle-sas)} takes in to someone who'd never used the function before and annotate the Contract below using descriptive variable names.

@vspace{1ex}

[.forceShading]
--
@show{(code 'triangle-sas)} {two-colons} `(`
@fitbruby{9em}{Number}{@ifsoln{top-side}},  
@fitbruby{9em}{Number}{@ifsoln{top-right-angle}}, 
@fitbruby{9em}{Number}{@ifsoln{bottom-right-side}},
@fitbruby{9em}{String}{@ifsoln{fill-style}},
@fitbruby{9em}{String}{@ifsoln{color}}
`) -> Image`

@vspace{3ex}
--

@vspace{1ex}

_If you have a printed workbook, add examples of each of the triangle functions we've explored to your contracts pages._

@vspace{1ex}

If you have time, experiment with the @show{(code 'triangle-asa)} function.

[.forceShading]
--
@show{(code 'triangle-asa)} {two-colons} `(`
@fitbruby{9em}{Number}{top-left-angle},  
@fitbruby{9em}{Number}{left-side}, 
@fitbruby{9em}{Number}{bottom-angle},
@fitbruby{9em}{String}{fill-style},
@fitbruby{9em}{String}{color}
`) -> Image`
--

@star Why did these two functions need to take in one more Number than `right-triangle` did?

@fitb{}{@ifsoln{Because right triangles have one fixed angle and that means that the ratio of base to height can be used to determine the other two angles!}}