= Project: Dataset Exploration

@description{Students choose a real world dataset that is interesting to them and are supported in exploring it by creating and interpreting a range of displays. __This project spans up to eight of our Data Science lessons, each of which includes an optional section with project-specific directions. We have built a @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, Library of Datasets} to support this project.__ }

@lesson-prereqs{choosing-your-dataset}


[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

- create a variety of displays about a dataset of their choosing
- compute a the measures of center and spread about a dataset of their choosing

| Student-facing Lesson Goals
|

- Let's explore and interpret a dataset that we find intriguing.

| Materials
|[.materials-links]

@material-links

| Preparation
|
@preparation{
* This project spans multiple lessons in the data science curriculum. Decide whether you intend to have your students engage with all or some of those lessons and modify the @starter-file{exploration-project} accordingly.
}

|===

== Dataset Exploration Project  @duration{flexible}

=== Overview

In this multi-lesson project, students explore and interpret a dataset of their choosing from our @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "Library of Datasets"}, which is introduced in the @lesson-link{choosing-your-dataset} lesson. At the end of up to 8 of our Data Science lessons, students will be supported in applying what they learn to their dataset by creating and interpreting a range of categorical and quantitative displays, as well as computing and analyzing various measures of spread and center. This work culminates in students developing a research question for possible further study through our @lesson-link{project-research-paper}.

=== Launch

The official launch of this project occurs during @lesson-link{choosing-your-dataset}. There are four project-related items to accomplish during this lesson:

- Students select a dataset of interest from the Bootstrap @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "List of Datasets"}.

- Students copy, save, and explore the @starter-file{exploration-project}. __Invite them to peruse the slide deck and familiarize themselves it; they'll be revisiting and adding to it often.__

- Students complete the "About My Dataset" section of the slide deck, reflecting on the dataset's source, structure, and relevance.

- Students add a bar chart and @ifproglang{pyret}{a pie chart}@ifproglang{codap}{a dot plot} to the "Making Displays" section of the slide deck, and then interpret them.

__Note: Students add their bar and pie charts during @lesson-link{choosing-your-dataset} rather than during the @ifproglang{pyret}{@lesson-link{bar-and-pie-charts}}@ifproglang{codap}{@lesson-link{codap-dot-plots-bar-charts}}, which comes before they'll have chosen a dataset. For all other displays, students will add to their slide deck during the relevant lesson.__

We recommend printing and distributing both @handout{exploration-paper-rubric.adoc, "page 1"} and @handout{exploration-paper-rubric-2.adoc, "page 2"} of the student-facing rubric to help students understand the scope of the project and your expectations at the outset. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context. For instance, some teachers will assess the entire project at its close, while some will offer intermittent checkpoints.

=== Investigate

The remainder of the project is completed at the conclusion of each of **eight** different Bootstrap:Data Science lessons: 

- @lesson-link{histograms} 
- @lesson-link{visualizing-the-shape-of-data} 
- @lesson-link{measures-of-center} 
- @lesson-link{box-plots} 
- @lesson-link{standard-deviation}
- @lesson-link{scatter-plots} 
- @lesson-link{correlations} 
- @lesson-link{linear-regression}

For these __Data Exploration Project__ lesson sections, students will always need on hand: 

1. Their copy of the@ifproglang{pyret}{ starter file for the} dataset they chose from our @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "Library of Datasets"}

2. Their copy of the @starter-file{exploration-project}

__When working on their Data Exploration Project, encourage students to create *multiple* displays.__

This project - as its name suggests - is all about __exploration__. 

=== Synthesize

- Invite students to customize their slides, add graphics, and beautify their slide decks.

- Encourage students to self-assess and revise their work. Peer review is a powerful tool if time allows! The rubric (both @handout{exploration-paper-rubric.adoc, "page 1"} and @handout{exploration-paper-rubric-2.adoc, "page 2"}) is a useful resource for facilitating self and peer review.

- Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.

- @opt{For teachers who have additional time available or students who are interested, the @lesson-link{project-research-paper} is a challenging extension, where students investigate the questions they've developed through their Data Exploration Project and use their data to tell a story.}
