= Project: Dataset Exploration

@description{Students choose a real world dataset that is interesting to them and practice making and interpreting a range of visualizations using that dataset. _This project spans up to nine of our Data Science lessons, each of which includes an optional section with project-specific directions. We have built a @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, Library of Datasets} to support this project._ }

@lesson-prereqs{choosing-your-dataset}


[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives
@objective{measures-of-center-proglang}
@objective{measures-of-spread-proglang}
- create a variety of visualizations from a dataset of their choosing

| Student-facing Lesson Goals
|

- Let's use a real world dataset that we find intriguing to get more practice making visualizations, computing measures of center & spread, and interpreting data.
- Let's record the interesting questions we generate while exploring our dataset.

| Materials
|[.materials-links]

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links


| Preparation
|
@preparation{
- This project spans multiple lessons in the data science curriculum. Decide whether you intend to have your students engage with all or some of those lessons and modify the @starter-file{exploration-project} accordingly.
- Decide how much choice you're ready to offer your students about what dataset they focus on before you begin. Research shows that choice increases student engagement! But focusing the whole class on a single dataset is also an option.
  * Would focusing all of your students on a single dataset make this doable for you? Because you teach younger students who might need more scaffolding? Or because you are new to teaching data science and managing fewer moving parts would increase your confidence? We recommend the @opt-starter-file{food, Global Food Supply and Production} dataset.
  * Are you ready to jump straight into supporting your students in working on a wide range of topics of their choosing? We have a full @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "Library of Datasets"}!
  @ifproglang{pyret}{
  * Want students to find their own data, clean it and import it into Pyret? They can watch this @opt-starter-file{blank-ds-tutorial, Tutorial Video} on how to import a spreadsheet into a copy of this @opt-starter-file{blank-ds, Pyret Dataset Starter File template}.}
  * Want to give students choice from a shorter curated list...to shorten the decision-making process, focus on topics related to curricular goals, or just to have fewer options to manage during class?  We've assembled @lesson-link{choosing-your-dataset/about-datasets/for-teachers-about-datasets.html, descriptions of individual datasets here}. For those looking for a pre-curated shorter list, we've starred a few of the datasets in our @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, library} for you.
  * *If you have time*, you may want to complete all of the lessons with everyone getting extra practice analyzing the @opt-starter-file{food, Global Food Supply & Production} dataset and then have your students choose a dataset to analyze for their culminating research papers!
- Teachers are welcome and encouraged to edit and adapt @handout{exploration-rubric.adoc, "page 1"} and @handout{exploration-rubric-2.adoc, "page 2"} of the student-facing rubrics for their unique classroom context and distribute them to help students understand the scope of the project - and your expectations - at the outset.
}

|===

== Dataset Exploration Project

=== Overview

This is a multi-lesson project focused on exploring and interpreting a real world dataset. 

@teacher{
Depending on how much time you have and what your learning goals are, this project may be used in preparation for a more focused analysis of the dataset and a more curated telling of the data story through our @lesson-link{project-research-paper}. 
}

Eight of our Data Science lessons have a section at the end that support students in applying what they learn by creating and interpreting a range of categorical and quantitative data visualizations, as well as computing and analyzing various measures of spread and center. _(The scope of the project can be easily modified if you do not intend to teach all 8 of those lessons.)_

There are several options for which dataset students focus this project on:

- _Standard Option:_ Students choose from our @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "Library of Datasets"}, which is introduced in the @lesson-link{choosing-your-dataset} lesson.
- _Simpler Option:_ Focus your class on the @opt-starter-file{food, Global Food Supply & Production} dataset.
@ifproglang{pyret}{
- _Students can also find/collect, clean, and import their own data!_}

@teacher{See the preparation section for more guidance on identifying which option makes the most sense for your class!}

=== Launch

The official launch of this project occurs during the @lesson-link{choosing-your-dataset} lesson. 

- Students copy, save, and explore the @starter-file{exploration-project}. +
__Invite them to peruse the slide deck and familiarize themselves with it; they'll be revisiting and adding to it often.__
- Students complete the "About My Dataset" section of the slide deck, reflecting on the dataset's source, structure, and relevance.
- This is also a great time to distribute your adapted version of @handout{exploration-rubric.adoc, "page 1"} and @handout{exploration-rubric-2.adoc, "page 2"} of the student-facing rubrics so students understand the scope of the project - and your expectations - at the outset.

=== Investigate

Once students have a real world dataset to focus on, they will apply what they learn about each new type of display to that dataset. Visualizations will be added during the conclusion of the following Bootstrap:Data Science lessons:

- @lesson-link{choosing-your-dataset} (since bar @ifproglang{pyret}{and pie} charts @ifproglang{codap}{and dot plots} are introduced in @ifproglang{pyret}{@lesson-link{bar-and-pie-charts}}@ifproglang{codap}{@lesson-link{codap-dot-plots-bar-charts}}, which comes before they'll have a dataset to focus on)

- @lesson-link{dot-plots}
- @lesson-link{histograms-visualize}
- @lesson-link{histograms-interpret}
- @lesson-link{measures-of-center} 
- @lesson-link{box-plots} 
- @lesson-link{standard-deviation}
- @lesson-link{scatter-plots} 
- @lesson-link{correlations} 
- @lesson-link{linear-regression}

@teacher{If you do not plan to teach all of those lessons, be sure to modify the @starter-file{exploration-project} and rubrics accordingly, before distributing them to students!}

@lesson-instruction{
This project is designed as a way to record your exploration process, much like you might "show your work" when solving a word problem.
}

- Some visualizations will reveal interesting information and lead to new thoughtful questions.
- Some visualizations will be useless.

@lesson-instruction{
All visualizations you make should be added to the "Making Data Visualizations" section of your @starter-file{exploration-project, Data Exploration Project}, with discussion about how they informed your thinking or a note that they didn't reveal much new information.
} 

@lesson-point{
Recognizing whether or not a display is useful or interesting is an important step in becoming data literate!
}

@teacher{
Encourage students to create **multiple** visualizations of each kind and to write about why they can't make more of a display if their options are limited.

Real world datasets are not one size fits all! If your students aren't all working on the same dataset, there will be a different number of each display that students can make using the available data. (For example, some students might be able to make 10 scatter plots with their data while other students may not be able to make any!)

@star If your students are up to the challenge, you might ask them to make ALL possible visualizations of each kind from their dataset.
} 

=== Synthesize

- Invite students to customize their slides, add graphics, and beautify their slide decks.

- Encourage students to self-assess and revise their work. Peer review is a powerful tool if time allows! The rubric (both @handout{exploration-rubric.adoc, "page 1"} and @handout{exploration-rubric-2.adoc, "page 2"}) is a useful resource for facilitating self and peer review.

- Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.

@teacher{@opt{Once students have completed this preliminary exploration of their dataset, the @lesson-link{project-research-paper} is an opportunity to investigate the questions they've developed and use their data to tell a story.}}
