= A Primitive Plagiarism Detector

Open the @starter-file{plagiarism}, click "Run", and then respond to the questions below.

== Review the Documents

@n Type `wiki-article` in the interactions area. Click enter.

@n Type `student-essay` in the interactions area. Click enter.

@n Read through the two paragraphs that appear, which we've also included below:

@vspace{1ex}

[cols="1,1", options="header"]
|===

| Wikipedia article on "Elephants in Thailand"
| Student-submitted essay on "Elephants in Thailand"

| The elephant has been a contributor to Thai society and its icon for many centuries. The elephant has had a considerable impact on Thai culture. The Thai elephant is the official national animal of Thailand. The elephant found in Thailand is the Indian elephant, a subspecies of the Asian elephant.

| The elephant is a contributor to Thai society and has been its icon for many centuries. The elephant has had a considerable impact on Thai culture. The Thai elephant is the official national animal of Thailand. The elephant found in Thailand is the Indian elephant, a subspecies of the Asian elephant.

|===

== Detect Identicality

The function `simple-similarity` takes in two Strings and produces a Number: 1 indicates that there is a match, 0 indicates that there is not.

@n Use `simple-similarity` to compare the wikipedia article to itself. What does the program tell you about the comparison? @fitb{}{}

@fitb{}{}

@n Use `simple-similarity` to compare the student-submitted essay with the wikipedia article. Click "Run". What does the program tell you about the comparison? @fitb{}{}

@fitb{}{}

== Assess Program Effectiveness

@n Do you think the student who submitted this essay on Elephants in Thailand committed plagiarism? Explain. @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n What are some problems with this plagiarism detector? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}



@n Describe what a more effective plagiarism detector must do. (Think creatively! How could you catch even the sneakiest of plagiarizers?) @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


