= Practicing Contracts: Domain & Range

_Note: The contracts on this page are not defined in @proglang and cannot be tested in the editor._

== is-beach-weather

@vspace{1ex}

Consider the following Contract:

@show{(contract 'is-beach-weather '(Number String) "Boolean")}

@n What is the *Name* of this function? @fitb{}{@ifsoln{is-beach-weather}}

@n How many arguments are in this function's *Domain*? @fitb{}{@ifsoln{2}}

@n What is the *Type* of this function's *first argument*? @fitb{}{@ifsoln{Number}}

@n What is the *Type* of this function's *second argument*? @fitb{}{@ifsoln{String}}

@n What is the *Range* of this function? @fitb{}{@ifsoln{Boolean}}

@vspace{1ex}

@n Circle the expression below that shows the correct application of this function, based on its Contract.

@vspace{1ex}

A. @show{(code '(is-beach-weather 70 90))}

B. @show{(code '(is-beach-weather 80 100 "cloudy"))}

C. @show{(code '(is-beach-weather "sunny" 90))}

D. @ifsoln-choice{@show{(code '(is-beach-weather 90 "stormy weather"))}}

@vspace{1ex}

== cylinder

@vspace{1ex}

Consider the following Contract:

@show{(contract 'cylinder '(Number Number String) "Image")}

@n What is the *Name* of this function? @fitb{}{@ifsoln{cylinder}}

@n How many arguments are in this function's *Domain*? @fitb{}{@ifsoln{3}}

@n What is the *Type* of this function's *first argument*? @fitb{}{@ifsoln{Number}}

@n What is the *Type* of this function's *second argument*? @fitb{}{@ifsoln{Number}}

@n What is the *Type* of this function's *third argument*? @fitb{}{@ifsoln{String}}

@n What is the *Range* of this function? @fitb{}{@ifsoln{Image}}

@vspace{1ex}

@n Circle the expression below that shows the correct application of this function, based on its Contract.

@vspace{1ex}

A. @show{(code '(cylinder "red" 10 60))}

B. @show{(code '(cylinder 30 "green"))}

C. @ifsoln-choice{@show{(code '(cylinder 10 25 "blue"))}}

D. @show{(code '(cylinder 14 "orange" 25))}
