= Bootstrap:Data Science Pathway

[.logo]
@image{images/Logo.png, Bootstrap:Data Science}

What factors make some people live longer than others? Are more expensive restaurants really better? Is voter fraud a problem? What data would you need to gather to answer these questions, and how would you measure that data to get your answer? Answering real questions in the world involves analyzing datasets, from sports stats to food sales to census information.

@vspace{2ex}

In Bootstrap:Data Science, students form their own questions about the world around them, analyze data using multiple methods, and write a research paper about their findings. The module covers functions, looping and iteration, data visualization, linear regression, and more. Social studies, science, and business teachers can utilize this module to help students make inferences from data. Math teachers can use this module to introduce foundational concepts in statistics, and it is aligned to @link{pathway-standards.shtml, National and State Standards for Mathematics, the Next Generation Science Standards, and the Data standards in CS Principles}.

@vspace{2ex}

The final project in Bootstrap:Data Science can be used as the Create Task for AP CS Principles!
