= Bootstrap:Data Science
++++
<style>
.algebra-2 {
	border-radius: 20px;
	border: solid 1px black !important;
	padding: 10px;
	margin: 10px auto;
	margin-bottom: 30px;
	width: 80%;
}
</style>
++++
@pathway-logo

_**Algebra 2** teachers looking to integrate only the non-linear modeling content into their classes will want our @dist-link{courses/algebra-2/, Algebra 2} materials._ +
_**Teachers of earlier-grades or those looking to integrate Data Science** into their existing Math, Science, or History classes will want to work with our @dist-link{courses/data-literacy/, Data Literacy} materials._

@pathway-lessons

[.algebra-2]
== What about Non-linear Models and Algebra 2?

There's no reason the modeling work introduced in this pathway has to stop at line of best fit! Our @dist-link{courses/algebra-2/, Algebra 2} materials extend into quadratic, exponential, logarithmic, and periodic models - all using inquiries into real data as a foundation for the non-linear content! We especially recommend this extension for Data Science teachers looking to count their course as an alternative to Algebra 2.

@workbooks

@other-resources
