= Bootstrap:Data Science

@pathway-logo

_**Algebra 2** teachers looking to integrate only the non-linear modeling content into their classes will want our @dist-link{courses/algebra-2/, Algebra 2} materials._ +
_**Teachers of earlier-grades or those looking to integrate Data Science** into their existing Math, Science, or History classes will want to work with our @dist-link{courses/data-literacy/, Data Literacy} materials._

@pathway-lessons

@workbooks

@other-resources

== Going Further

This pathway focuses on foundational Data Science, Statistics, Social Science, and Programming concepts, with only a limited amount of *modeling with functions*. Algebra 2 teachers - or Data Science teachers looking to count their course as an alternative to Algebra 2 - can extend this modeling work with quadratic, exponential, logarithmic, and periodic models using our @dist-link{courses/algebra-2/, Algebra 2} materials.

You can also pick-and-choose the lessons you want, using our @dist-link{customPathway.shtml} tool!
