== Collective information

The build also creates four files in `distribution/en-us` that combine
glossary-type information from all the courses and lessons. They
are: the dependency graph, the images list, the pathway ToCs,
and the bilingual glossary.

=== The dependency graph

The lesson dependency graph `dependency-graph.js` is generated by the program
`make-dependency-graph.lua`. It shows, for each
lesson:

- its title
- its description
- its programming language (i.e., pyret/wecheme/codap)
- the section headers in its lesson plan
- the pages it contains
- its optional (i.e., exercise) pages
- its handouts
- its notes pages
- the primitives needed for it
- its key words
- its glossary
- its notes
- its prerequisite lessons
- its starter files
- its optional starter files
- its slides file

The primitives and starter files are generated for each lesson as
`.cached/.index-primitives.txt.kp` and
`.cached/.index.starterfiles` respectively by the program
`collect-specials.lua`.

Note that the JS file represents the collected information as a JSON
object set to a variable. The file itself isn't JSON. This also holds
for the next two JS files described below.

=== Images list

A glossary of image information, `images.js`, is compiled from the
`images/lesson-images.json` file in each lesson.

=== Pathway ToCs

A list of all the courses with their constituent lessons is
generated in `pathway-tocs.js`.

=== Bilingual glossary

In addition to these JS files, a bilingual glossary
`bilingual-glossary.html` is created in `distribution/en-us/lib`.
This is a browsable version of the file `glossary-terms.json` in the
repo.
