== For users of legacy script build-pathway

Before the Makefile-based system was implemented, builds were
done using a shell
script called `build-pathway`.  For those familiar with its usage and unable to
let go, a new script `build` is provided whose API is similar to
`build-pathway`, and which is actually a wrapper that calls the new `make`
under the hood.

NOTE: The new name `build` is used  because `build-pathway`
(singular) would now be a
bit of a misnomer: the underlying `make` always creates or updates _all_
pathways (i.e., courses). Nevertheless, for those who really can't help using
the old name, `build-pathway` is provided a trivial identity wrapper for
`build`. Just remember that you cannot supply names of specific
pathways to build:
Such
arguments are ignored with a helpful diagnostic.

`build` takes the following options:

- `--book` (aka `--pdf`, `-b`): generates PDFs, both for
  individuals and the workbooks
- `--deploy`: deploys to website. Uses existing `distribution/`,
  if not, makes it first. May be preceded with settings for
  `SKIPLIB`, `SEASON`, `YEAR`
- `--force` (aka `--superforce`, `--super-force`, `-f`, `-F`):
  builds from scratch, scrubbing any previous `distribution/`
- `--help` (aka `-h`): displays help and exists
- `--link` (aka `--verify-links`, `-l`): verify all the links in
  the documentation
- `--natlang L`: builds doc for the natural language `L`
  (default: `en-us`)

Options may be combined in any order.

NOTE: The `--help` and `--version`
options overwhelm all other options: they display info but
do not build.

TIP: Use `-fb` or `-bf` for the often useful combination of
`--force` and `--book`, used to make a final-cut distribution
including the workbook PDFs after the source has been debugged to
satisfaction.

TIP: An experimental option `--adocjs` is provided that tells the
build to use the Node
version of Asciidoctor rather than the Ruby one.

// last modified 2023-03-06
