= Introduction to Transformers: Sort
@description{Students learn two different ways to sort - by modifying the table, and by using a _Transformer_ to build and modify a copy of the table.}

@add-to-lang{.order-by, .filter, .build-column}

[@lesson-intro-table]
|===
@lesson-prereqs{functions-solving-word-problems}
| Lesson Goals
| Students will be able to...

* write a contract, purpose statement, and expression
* use the `Sort` Transformer order the Animals Dataset by a number of criteria

| Student-facing Lesson Goals
|

* Let’s learn how transform one table into another.

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/1fONyy_r4GHysWMf4n3eKcYxtO4GfBYTKznRQRFrYoG4/edit?usp=sharing, Lesson Slides}

@material-links

|===
== Sorting Tables, Part 1 @duration{15 minutes}

=== Overview
Students _change a table,_ sorting it by a particular column.

=== Launch

Open the @starter-file{animals} in CODAP. How many animals' names start with the letter M? What would make it easier to figure out how many animals' names start with the letter M?


=== Investigate

Student work in groups or pairs. They will sort various columns on the table by clicking the attribute name and then selecting from the drop-down menu either `Sort Ascending` or `Sort Descending`.

[.lesson-instruction]
- Let's sort the animals alphabetically by name and see if we get the same answer as we did before!
- Sort the animals by age, from youngest to oldest.
- Sort the animals from heaviest to lightest.
- Sort the animals table by how long it took for each animal to be adopted, in ascending order.

=== Synthesize

. Can you think of a situation when it would be useful to sort animals from heaviest to lightest?

. Does sorting `animals-table` produce a _new_ table, or change the existing one? How do you know?

. Can you think of a situation where CODAP's default behavior - to alter the table each time we sort it - might inhibit more sophisticated data analysis?

== Sorting Tables, Part 2 @duration{20 minutes}

=== Overview
Using the `Sort` Transformer, students sort rows of a table in ascending or descending order, according to one column.

=== Launch
The Transformers plugin allows students to build and modify a _copy_ of the original table - enabling easy low-stakes "what if?" exploration.
@center{@image{images/plugins-location.png,"A screenshot of CODAP, showing where the Transformers can be found", 350}


[.lesson-instruction]
--
- Login to the Animal Starters File in CODAP.
- Access the Transformers plugin (see image above).
- Explore the different Transformers available, especially those categorized under “Construction.”
- What do you notice? What do you wonder?
--

We are going to create a copy of the Animals dataset in which the animals are organized alphabetically by name. To do this, we will use the `Sort` Transformer. Once you've opened the `Sort` Transformer, play with it and see if you can figure out how it works. *NEED IMAGE OF FINALIZED TRANSFORMER UI HERE*

[.lesson-instruction]
--
- What do you notice? What do you wonder?
- Why might it be useful to name the Transformer?
- What do you think a _purpose statement_ is?
- What do you think a _contract_ is?
--

=== Investigate

In order to apply this Transformer, we’ll need to provide it with several important pieces of information:

@n *Transformer name*. Describe to students that we want to give each Transformer a useful name, one which clearly describes what that Transformer does. Generally, a brief hyphenated description works - for instance: `order-by-weight`.

[.lesson-instruction]
--
- What would be a good name for a Transformer that organizes the table alphabetically by animals’ names?
- Type that name in the box. (A good option is `order-by-name`.)
--

@n *Dataset*. CODAP needs to know _which_ dataset to apply the Transformer to. Note: Transformers create a copy of the original dataset. After applying this Transformer, students will see _two_ datasets in the drop-down menu.

[.lesson-instruction]
--
- Click “Select a Dataset.”
- How many datasets appear on the drop-down menu?
- How many datasets do you think will appear in this drop-down menu after we apply order-by-name?
--

@n *Contract*. Contracts help us keep track of the different Transformers we’ll be using, and how they operate on each Row of a table.

Every contract has a _domain_ and a _range_.  The Domain of the Transformer Expression is the type(s) of data we give it. For our purposes, this will always be a single Row of the table. The Range of the Transformer Expression is the type of data the Transformer produces from that Row.

[.lesson-instruction]
--
- Select the drop-down menu that appears at the end of the contract, representing the Range.
- What different data types are listed here?
- What data type do you think is the output for this Transformer?
--

For now, it is important to understand that contracts are a simple notation (domain → range) for keeping track of the set of all possible inputs and outputs for a Transformer's expression. Students will get lots of practice with contracts as they work with Transformers in this lesson and others.

@n  *Purpose Statement*. The Purpose Statement is  a concise, detailed description of what a Transformer does with its inputs. The Purpose Statement is a comment in the code - something the computer doesn’t actually read. It is a note that students write for their future selves.

[.lesson-instruction]
--
- What would be an appropriate Purpose Statement for `order-by-name`?
- Type in your Purpose Statement.
--

@n *The Expression.* For sort, the expression is simply the column that we want to sort.

[.lesson-instruction]
--
- Notice that as you begin to type, CODAP offers suggestions that you can select.
- It is absolutely essential that the capitalization and spelling match the capitalization and spelling on the data table.
- When entering a String, remember the quotation marks!
--

@n *The Direction*

[.lesson-instruction]
--
- Choose ascending to sort from A to Z.
- Choose descending to sort from Z to A.
--

=== Common Misconceptions
Students may be more familiar with a `Sort` functionality that actually changes the table. CODAP Transformers produce a _brand new table_. These new and modified tables are automatically saved. CODAP titles each new table with a number in curly braces at the end (for example, `Filter(Animals-Dataset) {1}` ) to indicate how many times a Transformer has been applied. Students may rename saved tables, if they’d like.

=== Synthesize
- Does the Transformer `Sort` produce a _new_ table, or change the existing one?
- You've now learned two different strategies for sorting a column of a table. What do the two strategies have in common? How are they different?
- When would it be advantageous to use the `Sort` Transformer? When might it be disadvantageous?
