== Histograms Card Sort

Cut out one set of cards for every pair of students. Instructions for this sorting activity can be found on @printable-exercise{sorting-histograms.adoc}.

@vspace{1ex}

++++
<style>
/* Add letters to the top left corner, relative to each table cell */
.lettering td { position: relative; }
.lettering .paragraph:first-child p { position: absolute; top: 0; font-weight: bold; }
</style>
++++

[.lettering, cols="^.^1a,^.^1a,^.^1a", header="none"]
|===
| A

@image{../images/histoA.png, 170}
| B

@image{../images/histoB.png, 170}
| C

@image{../images/histoC.png, 170}
| D

@image{../images/histoD.png, 170}

| E

@image{../images/histoE.png, 170}
| F

@image{../images/histoF.png, 170}
| G

@image{../images/histoG.png, 170}
| H

@image{../images/histoH.png, 170}

| I

@image{../images/histoI.png, 170}
| J

@image{../images/histoJ.png, 170}
| K

@image{../images/histoK.png, 170}
| L

@image{../images/histoL.png, 170}

| M

@image{../images/histoM.png, 170}
| N

@image{../images/histoN.png, 170}
| O

@image{../images/histoO.png, 170}
| P

@image{../images/histoP.png, 170}

| Q

@image{../images/histoQ.png, 170}
| R

@image{../images/histoR.png, 170}

|===


