= Making Histograms

== By Hand

[cols="<.^4a,3a", frame="none", grid="none"]

|===

| Suppose we have a dataset for a group of 50 adults, showing the number of teeth each person has...

@vspace{1ex}

@big{
0, 0, 0, 0, 0, 22, 26, 27, 28, 28, 28, 28, 29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32
}

@vspace{1ex}

@n) Fill in the frequency table to the right. One row has been completed for you.

@vspace{1ex}

@n) When you're finished, use the frequency table to draw a histogram by filling in each bar so that its height is equal to the frequency for that interval.

@vspace{1ex}

@n) After creating the histogram by hand, follow the directions to create a tooth data histogram in Pyret.


| *Frequency Table*

!===
! number of teeth ! frequency
! 0-4 	! @ifsoln{4}
! 5-9 	! @ifsoln{0}
! 10-14 	! @ifsoln{0}
! 15-19 	! @ifsoln{0}
! 20-24 	! @ifsoln{1}
! 25-29 	! @ifsoln{9}
! 30-34 	! 35
!===


|===


@ifnotsoln{ @center{@image{../images/teeth-histogram.png, 350}}}
@ifsoln{ @center{@image{../images/teeth-histogram-soln.png, 350}}}

== In @proglang

[.linkInstructions]
Open the @starter-file{tooth-data} copy@ifproglang{pyret}{, and click "Run".}

@n Type `tooth-table` in the Interactions window. Press enter. What do you see? @fitb{}{@ifsoln{The tooth data from above, with names!}}

@n Type `count(tooth-table, "num-teeth")` in the Interactions window and press enter. How is the frequency table created in Pyret different from the one that you created, above? @fitb{}{@ifsoln{Different intervals were used.}}

@fitb{}{}

@n What bin sized was used (above) for the Tooth Data frequency table and the histogram? @fitb{5em}{@ifsoln{5}}

@n @ifproglang{pyret}{Build `tooth-table`.}@ifproglang{codap}{Review the tooth table.} Does this data appear to be the same or different from the tooth data that appeared in the first section? @fitb{5em}{@ifsoln{Same.}}


@n @ifproglang{pyret}{Use the contract below to build a histogram in Pyret.

@show{(contract 'histogram '((table-name Table) (labels String) (column-name String) (bin-size Number)) "Image")}
}

@ifproglang{codap}{Drag `Num Teeth` to the x-axis and select Group into Bins from the Configuration menu. Fuse dots into bars, then enter the desired bin width.}

@n How does the histogram you created in @proglang look _similar_ to the one that you drew? Are there any ways in which the histogram you created in @proglang is _different_ than the one you created by hand? @fitb{}{@ifsoln{On the histogram I created, intervals are labeled with the minimum and maximum value.}}

@fitb{}{@ifsoln{In @proglang, there are tick marks on the x-axis every 5 units.}}

@fitb{}{}

