= Predictions from Samples
++++
<style>
.blankline {margin-top: 15px; margin-bottom: 10px; }
</style>
++++

@n Use the Sampler plugin to create the following tables and give them the specified names. (Re-open Sampler _before_ creating each table to avoid getting one massive hierarchical table!)

- 10 animals randomly selected without replacement ⇒ tiny-sample
- 20 animals randomly selected without replacement  ⇒ small-sample
- 40 animals randomly selected without replacement ⇒ medium-sample
- 80 animals randomly selected without replacement ⇒ large-sample

@n Make a bar chart of the species in the tiny sample.

- What animals are in the sample? @fitb{}{}
- Create a new random tiny-sample. Create another bar-chart of species in the tiny-sample. What animals are in the sample? @fitb{}{}
- Create another random sample and make another bar-chart of species in the tiny-sample. Based on these samples, how many species of animals do you think are at the shelter? @fitb{1em}
- Which species do you think there are the most of at the shelter? @fitb{}

@n What did you learn from taking multiple samples that you wouldn't have known if you'd only taken a single sample?

@span{.blankline}

@n Now use the small sample to make a bar chart of the species.

- What animals are in the sample? @fitb{}{}
- Create a new random sample and make another bar chart of species in the small sample. What animals are in the sample? @fitb{}{}

@vspace{1ex}

@n Now that you've seen the small sample, how has your sense of the distribution of the species changed?

@span{.blankline}

@n Now use the medium sample to make a bar chart of the species.  If there are about 400 animals at the shelter, how many of each species would you predict there to be?

@span{.blankline}

@n Now use the large to make a bar chart of the species. If there's anything you'd like to change about your prediction now that you've seen the large sample, record it here.

@span{.blankline}

@n Let's see how accurate your prediction is... _feel free to click run and build a few more pie charts from your samples if you want to collect more information first!_ When you're ready, make a bar chart of Animals Table 2.

- Which predictions were closest? @fitb{27em}{}
- Which predictions were off? @fitb{28em}{}
- Were there any surprises?@fitb{29em}{}

@vspace{1ex}

@n In the real world, we usually don't have access to a whole dataset to check predictions against! How could we test...

- _Every giraffe on the planet?_

- _Everyone who has ever come in contact with a covid-positive person?_

- _Every person who identifies as queer?_

*What strategies can we use to make sure that predictions from samples are as close to accurate as possible?*

@span{.blankline}

@span{.blankline}




