= Problem Decomposition


*Sometimes a problem is too complicated to solve all at once:*

@vspace{1ex}

- Maybe there are too many variables.
- Maybe there is so much information that we can't get a handle on it!
- Maybe we'll be less likely to make mistakes if we think about the parts one at a time.

@vspace{1ex}

*Problem Decomposition* allows us to break complicated problems down into simpler pieces... and then solve by working with the pieces. +
There are two strategies:

@vspace{1ex}

- *Top-Down*: 
  * Start with the "big picture", writing functions or equations that describe the connections between parts of the problem. 
  * Then, work on defining those parts.

- *Bottom-Up*:
  * Start with the smaller parts, writing functions or equations that describe the parts we understand. 
  * Then, connect those parts together to solve the whole problem.

@vspace{1ex}

You may find that one strategy works better for some types of problems than another, so make sure you're comfortable using both of them!
