= What else can we learn from bones?

++++
<style>
.data-table td { margin: 0; padding: 0; }
</style>
++++

Excited by the discovery of skulls in a cave, another group of scientists arrived to see what they could learn about the Maya. These scientists are chemists and they know how to test bones to figure out what people were eating! It turns out that when you eat, some of the chemicals from your food get trapped in your bones. 

- What can we learn about the Maya from the food chemicals left in their bones? 
- How can what we learn help us better understand what lead to the end of the Maya civilization?

Here is a table that the chemists compiled of their findings. They figured out which time period the bones were from, and ran tests to figure out what proportion of that person’s diet came from corn.

[.data-table, cols="^.^1, ^.^1", options="header"]
|===
| When Person Lived | Proportion of Corn In Diet
| Before 900 AD
| 0.50
| Before 900 AD
| 0.50
| Before 900 AD
| 0.62
| Before 900 AD
| 0.59
| Before 900 AD
| 0.48
| Before 900 AD
| 0.42
| Before 900 AD
| 0.48
| Before 900 AD
| 0.43
| 900-1000 AD
| 0.36
| 900-1000 AD
| 0.25
| 900-1000 AD
| 0.35
| 900-1000 AD
| 0.39
| 900-1000 AD
| 0.40
| 900-1000 AD
| 0.36
|===
 
 @vspace{1ex}

_Answer the following questions based on the data._

@n Is the “When Person Lived” column categorical or quantitative? @fitb{}{}

@n Is the “Proportion of Corn in Diet” column categorical or quantitative? @fitb{}{}

@n Make a copy of @starter-file{bones} and use it to find the average proportion of corn in the diet for the people represented in the table? @fitb{}{}
 
@n Do you notice anything in the data that could help us get closer to knowing what happened to the Maya?

@fitb{}{}

@fitb{}{}
