= Correlations in My Dataset


[.lh-style]
. There may be a correlation between @fitbruby{30ex}{}{column} and
@fitbruby{30ex}{}{column}.  I think it is a
@fitbruby{30ex}{}{strong/weak}, @fitbruby{30ex}{}{positive/negative}
correlation, because @fitb{45ex}{} @fitb{45ex}{}. It might be
stronger if I looked at @fitbruby{90ex}{}{a subset of extension of my
data}.
+
@span{.vskip}{}

. There may be a correlation between @fitbruby{30ex}{}{column} and
@fitbruby{30ex}{}{column}.  I think it is a
@fitbruby{30ex}{}{strong/weak}, @fitbruby{30ex}{}{positive/negative}
correlation, because @fitb{45ex}{} @fitb{45ex}{}. It might be
stronger if I looked at @fitbruby{90ex}{}{a subset of extension of my
data}.
+
@span{.vskip}{}

. There may be a correlation between @fitbruby{30ex}{}{column} and
@fitbruby{30ex}{}{column}.  I think it is a
@fitbruby{30ex}{}{strong/weak}, @fitbruby{30ex}{}{positive/negative}
correlation, because @fitb{45ex}{} @fitb{45ex}{}. It might be
stronger if I looked at @fitbruby{90ex}{}{a subset of extension of my
data}.
