= Expressions -> Circles of Evaluation
++++
<style>
/* anchor the cell for relative positioning of solution */
td { position: relative; }
/* put the solution at the bottom of the cell, and centered */
td .solution { position: absolute; bottom: 0; left: 50%; transform: translate(-50%, 0); }
</style>
++++
Translate each of the arithmetic expressions below into Circles of Evaluation. 

@do{
  (define expr1 '(- (/ 6 2) (- 5 3)))
  (define expr2 '(- 9 (* 2 4)))
  (define expr3 '(- 8 (+ 1 (* 2 3))))
  (define expr4 '(- (+ 1 (* 4 7)) 3))
}

[.FillVerticalSpace, cols="^.^2a,^.^10a,^.^15a",options="header",stripes="none"]
|===
|
| Arithmetic Expression
| Circle of Evaluation


|*@n*
| 
@show{    (math expr1 #:parens true)} +
@ifsoln{@showsoln{(math expr1)}}
| @showsoln{(coe  expr1)}


|*@n*
| @show{    (math expr2 #:parens true)} +
@ifsoln{@showsoln{(math expr2)}}
| @showsoln{(coe  expr2)}

|*@n*
| @show{    (math expr3 #:parens true)} +
@ifsoln{@showsoln{(math expr3)}}
| @showsoln{(coe  expr3)}

|*@n*
| @show{    (math expr4 #:parens true)} +
@ifsoln{@showsoln{(math expr4)}}
| @showsoln{(coe  expr4)}
|===

@star Rewrite each of these expressions with one less pair of parentheses without changing its Order of Operations.
