= Circles of Evaluation -> Mathematical Expressions 2

For each Circle of Evaluation on left, write the arithmetic expression on the right
@teacher{The answers below are shown in two forms: using only the _necessary_ parentheses (top), and all parentheses (bottom).}

@do{
  (define expr1 '(/ 10 (* 2 (+ 3 1))))
  (define expr2 '(/ 5 20))
  (define expr3 '(+ (* 5 6) (/ 7 3)))
  (define expr4 '(* 4 (+ -9 8)))
  (define expr5 '(- (* 7 12) 8))
}

[.FillVerticalSpace, cols="^.^1a,^.^10a,^.^10a",options="header",stripes="none", frame="none"]
|===
|
| Circle of Evaluation
| Arithmetic Expression

|*@n*
| @show{(coe expr1)}
| @showsoln{(math expr1 #:parens false)} {empty} +
  @showsoln{(math expr1 #:parens true)}

|*@n*
| @show{(coe expr2)}
| @showsoln{(math expr2 #:parens false)} {empty} +
  @showsoln{(math expr2 #:parens true)}

|*@n*
| @show{(coe expr3)}
| @showsoln{(math expr3 #:parens false)} {empty} +
  @showsoln{(math expr3 #:parens true)}

|*@n*
| @show{(coe expr4)}
| @showsoln{(math expr4 #:parens false)} {empty} +
  @showsoln{(math expr4 #:parens true)}

|*@n*
| @show{(coe expr5)}
| @showsoln{(math expr5 #:parens false)} {empty} +
  @showsoln{(math expr5 #:parens true)}

|===
