= Complete the Code by adding Parentheses!

++++
<style>
  .studentAnswerShort { min-width: 50pt; }
</style>
++++

For each Circle of Evaluation on the left, finish the Code on the right by adding parentheses.
@ifsoln{*Teachers:* the answers below are shown with _all_ parentheses included. There are also correct solutions in which the unecessary parentheses are left out.}

@do{
  (define expr1 '(- (+ 16 4) (* 2 7)))
  (define expr2 '(/ (+ 17 13) (- 9 3)))
  (define expr3 '(- 27 (* 10 2)))
  (define expr4 '(* 6 (+ 7 (- 9 4))))
  (define expr5 '(+ (/ (- 5 1) 3) (+ 5 3)))
  (define expr6 '(/ (+ 7 9) (* 2 4)))
}

[.FillVerticalSpace, cols="^.^1a,^.^4a,^.^10a",options="header",stripes="none"]
|===
|    | Circle of Evaluation        | Code
|*@n*| @show{(coe expr1)}    
| @ifproglang{pyret}{16 @hspace{1em} + @hspace{1em} 4 @hspace{1em} - @hspace{1em} 2  @hspace{1em} @math{\times}  @hspace{1em} 7}
  @ifproglang{wescheme}{- + 16 4 @math{\times} 2 7}
  @showsoln{(code expr1 #:parens true)}
|*@n*| @show{(coe expr2)}    | @show{(code expr2 #:parens true)}
|*@n*| @show{(coe expr3)}    | @show{(code expr3 #:parens true)}
|*@n*| @show{(coe expr4)}    | @show{(code expr4 #:parens true)}
|*@n*| @show{(coe expr5)}    | @show{(code expr5 #:parens true)}
|*@n*| @show{(coe expr6)}    | @show{(code expr6 #:parens true)}
|===
