= Translating Circles of Evaluation to Code - w/Square Roots

++++
<style>
  td {height: 175pt;}
</style>
++++

@vspace{2ex}

Translate each of the arithmetic expressions below into Circles of Evaluation, then translate them to Code. 

@ifproglang{wescheme}{*HINT:* The function name is `sqrt`.}
@ifproglang{pyret}{*HINT:* The function name is `num-sqrt`.}

@do{
  (define expr1 '(sqrt 9))
  (define expr2 '(sqrt (+ 5 1)))
  (define expr3 '(+ (sqrt 4) 1))
  (define expr4 '(+ (* 3 (sqrt 3)) (sqrt 7)))

  (define mat1 (sexp->math expr1))
  (define mat2 (sexp->math expr2))
  (define mat3 (sexp->math expr3))
  (define mat4 (sexp->math expr4))

  (define coe1 (if *solutions-mode?* (sexp->coe expr1) ""))
  (define coe2 (if *solutions-mode?* (sexp->coe expr2) ""))
  (define coe3 (if *solutions-mode?* (sexp->coe expr3) ""))
  (define coe4 (if *solutions-mode?* (sexp->coe expr4) ""))

  (define code1 (if *solutions-mode?* (sexp->code expr1) ""))
  (define code2 (if *solutions-mode?* (sexp->code expr2) ""))
  (define code3 (if *solutions-mode?* (sexp->code expr3) ""))
  (define code4 (if *solutions-mode?* (sexp->code expr4) ""))
}


[cols=".^1a,^8a,^15,^15a",options="header",stripes="none"]
|===
|   | Arithmetic		| Circle of Evaluation	 | Code
|*1*| @show{mat1}		| @show{coe1}		 | @show{code1}
|*2*| @show{mat2}		| @show{coe2}		 | @show{code2}
|*3*| @show{mat3}		| @show{coe3}		 | @show{code3}
|*4*| @show{mat4}		| @show{coe4}		 | @show{code4}
|===
