= Applying Functions

++++
<style>
.indentedpara { margin-left: 3em; }
</style>
++++

Type this line of code into the interactions area and hit "Enter":  @show{(sexp->code `(triangle 50 "solid" "red"))}


[cols="1,18,5", frame="none"]
|===
|@n
| What is the name of this function?
| @fitb{15em}{ @show{(if *solutions-mode?* "*triangle*" "")}}

|@n
| What did the expression evaluate to?
| @fitb{15em}{ @show{(if *solutions-mode?* "*an image of a red triangle*" "")}}

|@n
| How many arguments does `triangle` expect?
| @fitb{15em}{ @show{(if *solutions-mode?* "*3*" "")}}

|@n
| What datatype does the `triangle` function produce? (Numbers? Strings? Booleans?)
| @fitb{15em}{ @show{(if *solutions-mode?* "*image*" "")}}
|===

== Catching Bugs

// /////////////////////////////////////////////////////////////

@ifproglang{pyret}{

The following lines of code are all BUGGY! Read the code and the error messages to identify the mistake.

@n `triangle(20, "solid" "red")` 	

[.indentedpara]
--
Pyret didn't understand your program around

triangle(20, "solid" *"red"*)

--

@vspace{3ex}

Can you spot the mistake?				@span{.right}{@fitb{60ex}{ @show{(if *solutions-mode?* "There is a missing comma after solid" "" )}}}

@vspace{2ex}

@n `triangle(20, "solid")`				

[.indentedpara]
--
This [.underline]#application expression# errored:

*triangle*(_20_, _"solid"_)

[.underline]#_2 arguments_# were passed to the [.underline]#*operator*#.
The [.underline]#*operator*# evaluated to a function accepting 3 parameters.
An [.underline]#application expression# expects the number of parameters and [.underline]#_arguments_# to be the same.
--

@vspace{3ex}

Can you spot the mistake?				@span{.right}{@fitb{60ex}{ @show{(if *solutions-mode?* "*The color is undefined*" "")}}}

@vspace{2ex}

@n `triangle(20, 10, "solid", "red")`		

[.indentedpara]
--
This [.underline]#application expression# errored:

*triangle*(20, 10, "solid", _"red"_)`

[.underline]#_4 arguments_# were passed to the [.underline]#*operator*#.
The [.underline]#*operator*# evaluated to a function accepting 3 parameters.
An [.underline]#application expression# expects the number of parameters and [.underline]#_arguments_# to be the same.
--

@vspace{3ex}

Can you spot the mistake?				@span{.right}{@fitb{60ex}{ @show{(if *solutions-mode?* "*There are two many numbers*" "")}}}

@vspace{2ex}

@n `triangle (20, "solid", "red")` 		

[.indentedpara]
--
Pyret thinks this code is probably a function call:

*triangle* _(20, "solid", "red")_

Function calls must not have space between the [.underline]*function expression* and the [.underline]_arguments_.
--

@vspace{3ex}

Can you spot the mistake? 				@span{.right}{@fitb{60ex}{ @show{(if *solutions-mode?* "*There shouldn't be a space between triangle and the parentheses*" "")}}}
}

// /////////////////////////////////////////////////////////////////

@ifproglang{wescheme}{

@n `(*triangle* 20 "solid")`

[.indentedpara]
--
[.underline]*triangle*: expects 3 arguments, but given 2: [.underline]20 [.underline]solid
[.underline]"at: line 1, column 0, in <interactions3>"
--

@vspace{3ex}

Can you spot the mistake?				@span{.right}{@fitb{60ex}{ @show{(if *solutions-mode?* "*It's missing a color*" "")}}}

@vspace{2ex}

@n `(*triangle* "solid" "red" 20)`		

[.indentedpara]
--
[.underline]triangle: expects a non-negative number as 1st argument, but given: [.underline]"solid"; other arguments were: [.underline]"red" [.underline]20
[.underline]"at: line 1, column 0, in <interactions2>"
--
@vspace{3ex}

Can you spot the mistake?				@span{.right}{@fitb{60ex}{ @show{(if *solutions-mode?* "*The number should come first*" "")}}}

@vspace{2ex}

@n `(*triangle* 20 40 "solid" "red")` 		

[.indentedpara]
[.underline]*triangle*: expects 3 arguments, but given 4: [.underline]20 [.underline]40 [.underline]solid [.underline]red
[.underline]"at: line 1, column 0, in <interactions12>" 
--
@vspace{3ex}
Can you spot the mistake?				@span{.right}{@fitb{60ex}{ @show{(if *solutions-mode?* "*There are too many numbers*" "")}}}

@n `(triangle 20 *solid* "red")` 	

[.indentedpara]
--
[.underline]*solid*: this variable is not defined
[.underline]"at: line 1, column 0, in <interactions11>" 
--
@vspace{3ex}
Can you spot the mistake?				@span{.right}{@fitb{60ex}{ @show{(if *solutions-mode?* "*solid is  missing quotes*" "")}}}
@vspace{2ex}

@n `(triangle 20 *"striped"* "red")`

[.indentedpara]
--
[.underline]triangle: expects a style ("solid" / "outline") or an opacity value [0-255]) as 2nd argument, but given: "striped"; other arguments were: 20 "red"
at: line 1, column 0, in <interactions8>
--
@vspace{3ex}
Can you spot the mistake?				@span{.right}{@fitb{60ex}{ @show{(if *solutions-mode?* "*striped is not an available option*" "")}}}
@vspace{2ex}
}