= Triangle Contracts

++++
<style>
.indentedpara { margin-left: 3em; }
</style>
++++

@n Match each `triangle-sas` expression (left) with the image it creates (right). 

@vspace{1ex}
[cols="1,^.^14a,^.^8a,1",stripes="none",grid="none",frame="none", options="header"]
|===
|   | Expression													| Image                                         |
| @n| @show{(sexp->code `(triangle-sas 120 45 70 "solid" "black"))} | @centered-image{../images/sas-120-90-70.png}	|A
| @n| @show{(sexp->code `(triangle-sas 120 90 70 "solid" "black"))}	| @centered-image{../images/sas-120-135-70.png}	|B
| @n| @show{(sexp->code `(triangle-sas 120 135 70 "solid" "black"))}| @centered-image{../images/sas-70-135-120.png}	|C
| @n| @show{(sexp->code `(triangle-sas 70 135 120 "solid" "black"))}| @centered-image{../images/sas-120-45-70.png}	|D
|===

Be sure to add your favorite examples of each of the triangle functions to your contracts pages!

Think about wow would you describe each of the arguments that @show{(sexp->code `triangle-sas)} takes in to someone who'd never used the function before and annotate

@show{(sexp->code `triangle-sas)}`{two-colons}` 
[.indentedpara]
 
 @fitb{25em}{} `{two-colons} number,`
 @fitb{25em}{} `{two-colons} number,`
 @fitb{25em}{} `{two-colons} number,`
 @fitb{25em}{} `{two-colons} string,`
 @fitb{25em}{} `{two-colons} string` 
 __

`-> image`

If you have time, try building triangles using

@show{(sexp->code `triangle-asa)}`{two-colons} number, number, number, string, string -> image`
