= Practicing Contracts

@vspace{1ex}

Consider the following contract:

----
is-beach-weather :: (temperature :: Number, cloud cover :: String) -> Boolean
----

What is the *Name* of this function? @fitb{39em}{}

How many things are in this function's  *Domain*? @fitb{33em}{}

What is the *type* of this function's  *first argument*? @fitb{32em}{}

What is the *name* of this function's  *second argument*? @fitb{30em}{}

What is the *Range* of this function? @fitb{38em}{} 

@vspace{1ex}

Circle the expression below that shows the correct application of this function, based on its contract.

@vspace{1ex}

1. @show{(sexp->code `(is-beach-weather 70 90))}

2. @show{(sexp->code `(is-beach-weather 80 100 "cloudy"))}

3. @show{(sexp->code `(is-beach-weather "sunny" 90))}

4. @show{(sexp->code `(is-beach-weather 90 "stormy weather"))}

@vspace{1ex}

Consider the following contract:

----
cylinder :: (radius :: Number, height :: Number, color :: String) -> Image
----

What is the *Name* of this function? @fitb{39em}{}

How may things are in this function's *Domain*? @fitb{35em}{}

What is the *type* of this function's *first argument*? @fitb{30em}{}

What is the *name* of this function's *third argument*? @fitb{30em}{}

What is the *Range* of this function? @fitb{39em}{}.

@vspace{1ex}

Below, circle which expression is the correct application of this function, based on its contract.

@vspace{1ex}

1. @show{(sexp->code `(cylinder "red" 10 60))}

2. @show{(sexp->code `(cylinder 30 "green"))}

3. @show{(sexp->code `(cylinder 10 25 "blue"))}

4. @show{(sexp->code `(cylinder 14 "orange" 25))}
