= Choosing Your Dataset

@description{Students select a real world dataset to investigate for the remainder of the course. They begin their analysis by identifying categorical and quantitative columns, and defining a few random and logical subsets.}

@lesson-prereqs{scatter-plots}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* Explain why they chose their dataset
* Describe their dataset
* Make subsets from their dataset

| Student-facing Lesson Goals
|

* Let's all choose an interesting dataset to investigate.

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/1yqz9a9O_PsXpzRzHVN4tFRNZ3FIbdVxzzSBRcJg-4p0/, Lesson Slides}
* @link{https://code.pyret.org/editor#share=1lGjndLCWSEoIrV3ErZMXSn_-xakqGvrK&v=1904b2c, Animals Starter File}
* @starter-file{exploration-paper}
* @starter-file{research-paper}

@material-links


| Preparation
|
* Decide whether you'd like your students to have access to our full dataset library or you want to curate a shorter list for them to choose from. (Depending on your goals, some datasets may work better for your class than others.) We've assembled @link{about-datasets/for-teachers-about-datasets.html, descriptions of individual datasets here}. For those looking for a precurated shorter list, we've starred a few of them for you.
* All students (or pairs) should log into @link{https://code.pyret.org, CPO} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can open the @starter-file{animals}.


| Supplemental Resources
| <<Datasets, Jump to Datasets and Starter files>>

|===

== Choosing a Dataset

=== Overview
Students select a dataset that interests them, and do some thinking about _why_ it interests them, _what questions they'd like to answer_ and _what hypotheses they have_. They'll be analyzing this data for a long time, so *it's critical to ensure a high degree of buy-in before signing off on a student's choice!*

=== Launch

[.lesson-point]
Data Science: it's all about YOU!

What data matters to *_you?_* What questions do *_you_* care about? We live in a world filled with data, gathered about almost every subject you can imagine.

- Climate sensors are gathering data on temperature, humidity, oxygen and more...practically everywhere on the globe
- Census data tracks the number of different groups of people, as well as their education, income level, and more
- Companies like Facebook, Amazon, and Google gather massive amounts of data on the websites you visit, what you chat about online, what you purchase, etc.

[.lesson-instruction]
Where else do you see data being gathered?

And this data is used to set public policy, draw voting districts, approve drugs, calculate school funding, decide which advertisements you see, and more.

[.lesson-instruction]
What are some other ways data is used around you?

=== Here Come the Datasets!
[[Datasets]]

Below is a list of every dataset already provided to students, with a corresponding Starter File that instantly imports the (cleaned) data into Pyret.

_Students can also find their own dataset_, and use this @starter-file{blank-ds}. See this @link{https://youtu.be/uqm9F_tmIho, tutorial video} for help importing your own data into Pyret.

=== Investigate
Have students choose a dataset that is interesting to them!

@include{fragments/dataset-table.adoc}

[.lesson-instruction]
Look at the spreadsheet for your dataset. What do you *Notice*? What do you *Wonder*? Complete @printable-exercise{pages/my-dataset.adoc}, making sure to include at least two questions that _can_ be answered by their dataset and one that _cannot_.

=== Synthesize
Have students share their datasets and their questions.

For the rest of this course, students will be learning new programming and Data Science skills, practicing them with the Animals Dataset and then applying them to their own data.

== Exploring Your Dataset @duration{flexible}

=== Overview
Students apply what they've learned about describing and making subsets from the Animals Dataset to their own dataset. *Note: this section should be broken up across multiple days!* Students should complete each of the investigate sections, then leave ample classtime for discussion and peer-sharing.

=== Launch
By now you've already learned what to do when you approach a new dataset. With the Animals Dataset, you first read the data itself, and wrote down your Notice and Wonders. You described the columns in the Animals Dataset, identifying which were categorical and which were quantitative, and whether they were Numbers, Strings, Booleans, etc. Finally, you used the Design Recipe and table methods to make random and logical subsets.

Now, you're doing to do the same thing _with your own dataset._

=== Investigate

[.lesson-instruction]
- Make a copy of @starter-file{exploration-paper}, and open the starter file for your chosen dataset.
- Why does this dataset matter? Where did it come from? Complete the
- In the Definitions Area, use `random-rows` to define *at least three* tables of different sizes: `tiny-sample`, `small-sample`, and `medium-sample`.
- In the Definitions Area, use `.row-n` to define *at least three* values, representing different rows in your table.

Have students share which datasets they chose, and why they are interesting or important to them.

[.lesson-instruction]
- What is the distribution of data in your categorical columns? Turn to Complete @printable-exercise{data-cycle-categorical.adoc}, and use the Data Cycle to generate pie and bar charts.
- What do these charts tell you? Add the images of these charts - along with your interpretation! - to the "Making Displays" section of the exploration document.
- How are the quantitative columns in your dataset distributed? @printable-exercise{data-cycle-quantitative.adoc}, and use the Data Cycle to explore two quantitative columns with histograms and box plots.
- Then add these displays - and your interpretations! - to "Making Displays" section.
- Do these displays bring up any interesting questions? If so, add them to the end of the document.

Have students share their findings. Were any of them surprising? What, if any, outliers did they discover when making histograms and box-plots?

[.lesson-instruction]
- How is this distribution represented in terms of measures of center and spread? Complete @printable-exercise{shape-of-my-dataset.adoc}, and complete the "Measures of Center and Spread" section of the exploration document.
- What is the standard deviation for these columns? Complete @printable-exercise{analysis-stdev.adoc}, and add your findings to the "Measures of Center and Spread" section.
- Do these measures bring up any interesting questions? If so, add them to the end of the document.

Have students share their findings. Are some colums more spread out - with a larger standard deviation - than others? What measures of center makes the most sense for one column or another?

[.lesson-instruction]
- Do you suspect any relationships _between_ quantitative columns in your dataset? Use the Data Cycle to generate some scatter plots, and add them to the "Making Displays" section of the exploration document.
- Do these displays bring up any interesting questions? If so, add them to the end of the document.

Have students share their findings.

[.lesson-instruction]
- Open the @starter-file{research-paper}, and save a copy.
- Fill in your first and last name(s), and your teacher's name on the first page of the research paper.
- Copy the link to the dataset (spreadsheet), and paste it onto the first page of the research paper.
- Click "Publish" in their Pyret Starter File, then copy/paste the resulting link into the first page of the research paper.
- Using the last section of your Exploration document to identify a research question you would like to pursue.
- Find the displays, measures of center, and measures of spread that are relevant to this question, and add them to the research paper. Be sure to include your interpretations, so that all of your data stories combine into a coherent paper!

=== Synthesize

The Animals Dataset contains a number of sub-groups that we might want to compare to one another. For example: maybe we'd like to compare the average adoption time for dogs v. cats!

Does your dataset contain any sub-groups? If so, what are they?
