[.datasheet]


[.datasheet]
= World Cities: Proximity to Ocean

[.question]
--
//Write a brief description of where this data comes from.
//Examples:
//
//- This dataset includes data from 271 Rhode Island public &
//  charter schools.
//- This data set looks at traffic stops in Durham, NC
//  between 2002 and 2013, recording the number of them that resulted in searches of the person
//  stopped. Data is broken down by age, race and sex.
--


[.answer-roman]
--
This dataset looks at the 5000 most populous (as of 2020) cities in the world and their geographical information, such as elevation, country, continent, and distance from the nearest shoreline. The data comes from various sources, including the World Cities Database (for cities and population), the National Centers for Environmental Information (for worlds shoreline), JohnSnowLabs (for each country's continent), and the World bank (for country GDP per capita). 



--
[.question]
--
//Write one of the following descriptors in the space below:
//
//- This data set has a limited number of categories, making it
//  accessible to any student.
//- This data set has a huge number of columns that will excite
//  some students and may overwhelm others.
--


[.answer-roman]
--
- This data set has a limited number of categories, making it accessible to any student.



--
[.question]
--
//Write one of the following descriptors in the space below:
//
//- The columns of this data set are defined to allow students to
//  start analysis without much additional coding.
//- The columns of this data set require calculations to convert
//  data before students start making graphs.
--


[.answer-roman]
--
- The columns of this data set are defined to allow students to start analysis without much additional coding.
- *Column Titles:* Name, Country, Population (2020), Continent, Elevation (m), Distance to Shore (km), GDP per Capita ($) 2017. This refers to the country's GDP per capita. 



--
[.question]
*Have students...*
--
//Make a list of functions below that you would recommend defining
//to deepen the analysis. For example:
//
//- *define* a function pct-black, which computes the percent of
//  black students at a school.
//- *define* a function high-math, which returns true if a school
//  has more than 60% of students passing the state math test.
--


[.answer-roman]
--
- *define* a function is-poverty, which returns true if a city's GDP per capita is below $15,000.
- *define* a function is-climate-change-prone, which returns true if a city's distance from shore is less than 20km and elevation is less than 10m.
- *define* a function is-metropolis, which returns true if a city's population is above 1 million dollars and GDP per capita is above $10,000.  



--