[.datasheet]


[.datasheet]
= Marijuana Arrests and Laws by State

[.question]
--
//Write a brief description of where this data comes from.
//Examples:
//
//- This dataset includes data from 271 Rhode Island public &
//  charter schools.
//- This data set looks at traffic stops in Durham, NC
//  between 2002 and 2013, recording the number of them that resulted in searches of the person
//  stopped. Data is broken down by age, race and sex.
--


[.answer-roman]
--
This dataset looks at marijuana arrest records for the year 2018 in 49 US States (data was unavailable for Florida), and breaks 
these arrests down by race. Each state also includes data for the years marijuana was legalized and/or decriminalized, 
and/or when medical marijuana was legalized.

--
[.question]
--
//Write one of the following descriptors in the space below:
//
//- This data set has a limited number of categories, making it
//  accessible to any student.
//- This data set has a huge number of columns that will excite
//  some students and may overwhelm others.
--


[.answer-roman]
--
This data set has a limited number of categories, making it accessible to any student.


--
[.question]
--
//Write one of the following descriptors in the space below:
//
//- The columns of this data set are defined to allow students to
//  start analysis without much additional coding.
//- The columns of this data set require calculations to convert
//  data before students start making graphs.
--


[.answer-roman]
--

- The columns of this data set require calculations to convert data before students start making graphs.
- **Column Titles:**  State, All Drug Arrests, Total Marijuana Arrests, Total Marijuana Possession Arrests, Black Marijuana Possession Arrests, White Marijuana Possession Arrests, Black Population, White Population, Total Population, Marijuana Legalized (year), Marijuana Decriminalized (year), Medical Marijuana Legalized (year)

--
[.question]
*Have students...*
--
//Make a list of functions below that you would recommend defining
//to deepen the analysis. For example:
//
//- *define* a function pct-black, which computes the percent of
//  black students at a school.
//- *define* a function high-math, which returns true if a school
//  has more than 60% of students passing the state math test.
--


[.answer-roman]
--
- *define* a function black-population-proportion, which computes the proportion of black individuals in a state's 
  population.
- *define* a function black-arrest-proportion, which computes the ratio between marijuana possession arrests for black 
  people and marijuana possession arrests for all people.
- *define* function marijuana-arrest-proportion, which computes the percent of drug arrests that were marijuana arrests, 
or marijuana possession arrests.
- *define* a function is-legal-in-2018, which determines whether marijuana was legalized in 2018 
(the time that the data was calculated). The same can be done for decriminalization and medical marijuana legalization.



--
[.question]
*Heads Up*
--
//If there are outliers teachers should be aware of, please note them below. For example:
//
//- *Outliers to be aware of:* Only a few films are from before 2000.
//- *Outlier to be aware of:* Classical High School has test scores of zero.
--


[.answer-roman]
--

- A few states have multiple dates for medical marijuana legalization, denoted by listing the two dates
separated by a slash.

--
[.question]
--
//List any recommended calculations below. For example:
//
//- Other than ELA and Math Passing Percentages, columns list the
//  number of students.  In order to compare between schools,
//  percentages would need to be calculated.
//- Free and Reduced lunch students are listed as two separate
//  quantities. Usually we combine these numbers for analysis.
--


[.answer-roman]
--
- In order to compare between states, percentages will need to be calculated. These could include 
the percentage of a population that is black or white, the percentage of marijuana arrests that were
of a black or white person, or the percentage of total arrests that were for marijuana possession.
- It may also make sense to split data into groups depending on whether marijuana/medical marijuana was legalized, decriminalized, or illegal.


--
