= R.I. Schools

This is data from 271 Rhode Island public & charter schools.
- *Column Titles:* District Name, School Name, % passing ELA in 2018, % passing Math in 2018, Charter School (yes/no?), Number of students free lunch eligible, Number of students reduced lunch eligible, Number of students by racial/ethnic group (American Indian/Alaska Native, Asian/Pacific Islander, Hispanic, Black, White, 2 or more races), male, female, total population.

Have students:
- *Define a function* pct-black, which computes the percent of black students at a school.
- *Define a function* pct-hispanic, which computes the percent of black students at a school. 
- *Define a function* high-math, which returns true if a school has more than 60% of students passing the state math test.

Heads up! 
- Other than ELA and Math Passing Percentages, columns list the number of students.  _In order to compare between schools, percentages would need to be calculated._
- Free and Reduced lunch students are listed as two separate quantities. Usually we combine these numbers for analysis.
- Outlier to be aware of: Classical High School
