= U.S. Voter Turnout 1986-2018

This dataset looks at demographics of the electorate.  Information is provided on what percentage of the electorate each group represents and how turnout for elections varies across age, educational attainment and race.

- *Column Titles:*  year, Turnout Rate 18-29, Turnout Rate 30-44, Turnout Rate 45-59, Turnout Rate 60+, Share of Electorate 18-29, Share of Electorate 30-44, Share of Electorate 45-59, Share of Electorate 60+, Turnout Rate Less Than High School, Turnout Rate High School Grad, Turnout RateSome College to College Grad, Turnout Rate Post-Graduate, Share of Electorate Less Than High School, Share of Electorate High School Grad, Share of Electorate Some College to College Grad, Share of Electorate Post-Graduate, Turnout Rate Non-Hispanic White, Turnout Rate Non-Hispanic Black, Turnout Rate Hispanic, Turnout Rate Other, Share of Electorate Non-Hispanic White, Share of Electorate Non-Hispanic Black, Share of Electorate Hispanic, Share of Electorate Other


