= Working with the Pre-Built Datasets

++++
<style>
.sect2{ margin-top: 15pt; }
</style>
++++

== Overview
*Best data sets for wide-range of graphs without lots of effort:*

- States
- Movies
- Schools
- Countries

*Datasets requiring calculations to convert data before making graphs:*

- Schools
- Marijuana Laws & Arrests by State
- Countries

*Datasets with a limited number of categories:*

- Police Traffic Stops
- Presidents
- Countries
- Sodas
- Movies

*Datasets with a huge number of columns*

- MLB
- U.S. Voter Turnout

*Datasets with fairly little quantitative data (well-suited to simpler analysis, not recommended for scatter plots):*

- International Exhibition of Modern Art 1913

@include{about-worldcities.adoc, leveloffset=+1}

@include{about-nypd-stop-frisk.adoc, leveloffset=+1}

@include{about-marijuana.adoc, leveloffset=+1}

@include{about-police-traffic-stops.adoc, leveloffset=+1}

@include{about-college-majors.adoc, leveloffset=+1}

@include{about-us-jobs.adoc, leveloffset=+1}

@include{about-refugees.adoc, leveloffset=+1}

@include{about-ri-schools.adoc, leveloffset=+1}

@include{about-movies.adoc, leveloffset=+1}

@include{about-fastfood.adoc, leveloffset=+1}

@include{about-beverages.adoc, leveloffset=+1}

@include{about-pipeorgans.adoc, leveloffset=+1}

@include{about-art.adoc, leveloffset=+1}

@include{about-esports.adoc, leveloffset=+1}

@include{about-mlb-hitting.adoc, leveloffset=+1}

@include{about-nba-players.adoc, leveloffset=+1}

@include{about-nfl-passing.adoc, leveloffset=+1}

@include{about-nfl-rushing.adoc, leveloffset=+1}

@include{about-voter-turnout.adoc, leveloffset=+1}

@include{about-state-demographics.adoc, leveloffset=+1}

@include{about-countries.adoc, leveloffset=+1}

@include{about-us-income.adoc, leveloffset=+1}

@include{about-us-presidents.adoc, leveloffset=+1}

@include{about-music.adoc, leveloffset=+1}
