= Data Displays and Lookups

@add-to-lang{.row-n}

@description{Students use displays to answer questions, focusing on which displays make sense for the data they are working with. They also learn how to extract individual rows from a table, and columns from a row. }

@lesson-prereqs{contracts, data-cycle}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Given a human-language request for a data display involving the entire Animals Dataset, break it down into parts and generate the display.
* Given a Table, use the `row-n` method to extract any Row from that table
* Given a Row, use the column lookups to extract the value of any column in the Row

| Student-facing Lesson Goals
|

* Let's practice making data displays to answer our questions about the data and retrieving information from tables.

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/1CwvnamtZ5irPTuvbzgmv02HM7w5Aa54SmR3JOBpJ6Iw/, Lesson Slides}
@material-links

| Preparation
|
* All students should log into @link{https://code.pyret.org, code.pyret.org (CPO)} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can open a new @starter-file{animals}.

|===

== Analyzing Data @duration{20 minutes}

=== Overview
Students progress to the third step in the Data Cycle, by combining the "Consider Data" stepwith their knowledge of Contracts to help them _Analyze_ that data.

=== Launch

@right{@image{images/data-cycle.png, "A circular progression: (1) Ask Questions, (2) Consider Data, (3) Analyze Data, (4) Interpret Data, and starting over", 150}}
Let's return to the Data Cycle, which describes the process of asking a question, considering the data we need, analyzing that data, and interpreting it. Sometimes the answers we get from our analysis spark new questions, leading to another round of the cycle. Each turn of the Data Cycle adds a chapter to our data story.

[.lesson-instruction]
- What are the three types of questions we can ask of a dataset?
- Can you explain the differences between them?
- When we consider the data needed for a question, what two questions do we ask?

Let's return to the example we used earlier, when we wanted to find the ratio of fixed to un-fixed animals from the shelter.

@left{@image{images/AskQuestions.png, "Ask Questions icon", 100}} This is an Arithmetic Question. We know it's not a lookup question because there's no ratio written somewhere in the table for us to read. Instead, we'll have to count all the fixed animals and the unfixed animals, then compare the totals.

@vspace{1ex}

@left{@image{images/ConsiderData.png, "Consider Data icon", 100}} To consider the data, we ask *which rows* we're talking about. Is it just the dogs? Just animals more than 5 years old? We know that we'll need to count every single animal, so we want all the rows. We also need to know *which column(s)* we are displaying. In this case, it's the `fixed` column.

@vspace{1ex}

@left{@image{images/AnalyzeData.png, "Analyze Data icon", 100}} What kinds of displays can help us analyze a single, categorical column? We could use a bar-chart _or_ a pie-chart to do this analysis, but since we care more about the ratio ("2x as many fixed as unfixed") than the actual count ("20 fixed vs. 10 fixed") a pie chart is the better choice. Once we've decided what to make and we know which rows and columns we're plotting, the next step is to _write the code!_

Once we know that we want a pie-chart, and that we're using it to look at the `fixed` column, analyzing the data is as easy as reading the Contract!

=== Investigate
Let's get some practice going from questions to code, and making data displays in the process!

[.lesson-instruction]
Turn to @printable-exercise{pages/analyzing-with-displays.adoc}, and see if you can fill in the first 3 steps of the Data Cycle for a set of predefined questions. When you're finished, try to make the display in Pyret.

Have students share their results. What did their charts tell them?

@left{@image{images/InterpretData.png, "Interpret Data icon", 100}} In this case, we got a clear answer to our question. But perhaps that's not the end of the story! We might be curious about whether a higher percentage of dogs are spayed and neutered than cats, or whether it's even possible to "fix" a tarantula. _All of this belongs in our data story!_

=== Synthesize
How do Contracts and the Data Cycle work together, to help us figure out what program will answer our questions?

== Row and Column Lookups @duration{30 minutes}

=== Overview
Students learn how to define values in Pyret, and practice by defining Numbers, Strings, and Images. They also learn how to define an individual row from a table in Pyret, and how to access a particular column from that row.

=== Launch
Have students open their saved Animals Starter File (or make a new @starter-file{animals} copy), and click “Run”.

Sometimes we have a value that we want to use again and again, and it makes sense to define a name for it. Every definition includes a _name_ and a _value_. In the code below, we have definitions for a String, a Number and an Image.

  name = "Flannery"
  age = 16
  logo = star(50, "solid", "red")

- What are the names given in each of these? __name, age, and logo__
- What are the values? __the String "Flannery", the Number 16, and an Image of a solid red star__

=== Investigate
[.lesson-instruction]
How many rows do we need to answer a Lookup question?
(Make sure sure students understand we only need one!)

@right{@image{images/AskQuestions.png,Ask Questions icon, 100}}
Let's talk about the code we can write, to let us answer a Lookup question by defining a row.

Tables have special functions associated with them, called @vocab{Methods}, which allow us to do all sorts of things with those tables. For example, we can get the first data row in a table by using the `.row-n` method:

  animals-table.row-n(0)

[.lesson-point]
Don't forget: data rows start at index _zero_!

[.lesson-instruction]
In the Interactions Area, use the `row-n` method to get the second and third data rows.

What is the Domain of .row-n? What is the Range? Find the contract for this method in your contracts table. A table @vocab{method} is a special kind of function which always operates on a specific table. In our example, we always use .row-n with the animals table, so the number we pass in is always used to grab a particular row from animals-table.

The code below will define the first row from the animals table:

  sasha    = animals-table.row-n(0)

Pyret also has a way for us to get at individual columns of a Row, by using a Row Accessor. Row accessors start with a Row value, followed by square brackets and the name of the column where the value can be found. Here are three examples that use row accessors to get at different columns from the first row in the animals-table:

  animals-table.row-n(0)["name"]
  animals-table.row-n(0)["age"]
  animals-table.row-n(0)["fixed"]

And of course, we can use our defined name, substituting it in place of all the redundant code:

  sasha["name"]
  sasha["age"]
  sasha["fixed"]

[.lesson-instruction]
- How would you get the `weeks` column out of the _second_ row? The third?
- Complete the exercises on @printable-exercise{pages/lookup-questions.adoc}.

Flip back to page 2 of your workbook and look at The Animals Dataset. Which row is animalA? Label it in the margin next to the dataset. Which row is animalB?  Label it in the margin next to the dataset.

Now turn back to your screen.
What happens when you evaluate `animalA` in the Interactions Area?

[.lesson-instruction]
- Define _at least_ two additional values to be animals from the `animals-table`, called `animalC` and `animalD`.

=== Synthesize
Have students share their answers, and see if there are any common questions that arise.

== Additional Exercises:
- @opt-printable-exercise{pages/more-practice-w-lookups.adoc}
- @opt-printable-exercise{pages/plot-practice.adoc}
