= Data Displays and Lookups

@add-to-lang{.row-n}

@description{Students use displays to answer questions, focusing on which displays make sense for the data they are working with. They also learn how to extract individual rows from a table, and columns from a row. }

@lesson-prereqs{contracts, data-cycle}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Given a human-language request for a data display involving the entire Animals Dataset, break it down into parts and generate the display.
* Given a Table, use the `row-n` method to extract any Row from that table
* Given a Row, use the column lookups to extract the value of any column in the Row

| Student-facing Lesson Goals
|

* Let's practice making data displays to answer our questions about the data and retrieving information from tables.

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/1CwvnamtZ5irPTuvbzgmv02HM7w5Aa54SmR3JOBpJ6Iw/, Lesson Slides}
@material-links

| Preparation
|
* All students should log into @link{https://code.pyret.org, code.pyret.org (CPO)} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can open a new @starter-file{animals}.

|===

== Displaying Data @duration{20 minutes}

=== Overview
Students freely explore the Data Science display library. In doing so, they experiment with new charts, practice reading @vocab{Contracts} and error messages, and develop better intuition for the programming constructs they've seen before. This activity stresses a hard programming skill (reading Contracts) with formal reading comprehension (identifying key portions of a statistical instruction).

=== Launch

@right{@image{images/data-cycle.png, "A circular progression: (1) Ask Questions, (2) Consider Data, (3) Analyze Data, (4) Interpret Data, and starting over", 150}}
Let's return to the Data Cycle, which describes the process of asking a question, considering the data we need, analyzing that data, and interpreting it. Sometimes the answers we get from our analysis spark new questions, leading to another round of the cycle. Each turn of the Data Cycle adds a chapter to our data story.

[.lesson-instruction]
- What are the three types of questions we can ask of a dataset?
- Can you explain the differences between them?
- When we consider the data needed for a question, what two questions do we ask?

@right{@image{images/AnalyzeData.png, "Analyze Data icon", 200}} Once we've asked our question and considered the data, it's time to do some analysis! This might involve making a new table, or making a data display like a chart or a graph. _But how do we know what to make?_

Suppose we want to find the ratio of fixed to un-fixed animals from the shelter. As always, we start by asking *which rows* we're talking about. In this case, it's all the animals from the shelter. We also need to know *which column(s)* - or "which variable(s)" - we are displaying. In this case, it's the `fixed` column.

[.lesson-point]
After considering Rows and Columns, it's time to ask _"What are we Creating?"_

Is it a histogram? Bar chart? Scatter plots are essential for displaying relationships _between_ columns, but the other displays only deal with one column. Some displays work for @vocab{categorical data}, and others are for @vocab{quantitative data}.

In this lesson, our goal is to expore the different kinds of displays we can make in Pyret, and what kinds of data each display is good for. For now, *this is all about exploring!* For example, you may not know how to read a histogram yet, but our goal today is to just figure out how to _make one_ in Pyret.

The Contracts page in the back of the student workbooks contains @vocab{contracts} for many functions that make displays. Once we know what to create, we can find the Contract for that display and start writing code!

=== Investigate
Let's get some practice going from questions to code, and making data displays in the process!

[.lesson-instruction]
Turn to @printable-exercise{pages/data-displays.adoc}, and see if you can fill in these three parts for a number of data display instructions. When you're finished, try to make the display in Pyret using the appropriate function.

Do you know what kind of data is used for each display?

[.lesson-instruction]
Turn to @printable-exercise{pages/type-v-display.adoc}, and see if you can identify what kind of data each display needs!

=== Common Misconceptions
There are _many_ possible misconceptions about displays that students may encounter here. *But that's ok!* Understanding all those other plots is _not_ a learning goal for this lesson. Rather, the goal is to have them develop a little familiarity, and to get more practice reading Contracts.

=== Synthesize
Debrief the activity with students.

- What displays can be used with categorical data?
- What displays can be used with quantitative data?
- What displays work with only one column of data?
- What displays work with two or more columns of data?

== Row and Column Lookups @duration{30 minutes}

=== Overview
Students learn how to define values in Pyret, and practice by defining Numbers, Strings, and Images. They also learn how to define an individual row from a table in Pyret, and how to access a particular column from that row.

=== Launch
Have students open their saved Animals Starter File (or make a new @starter-file{animals} copy), and click “Run”.

Sometimes we have a value that we want to use again and again, and it makes sense to define a name for it. Every definition includes a _name_ and a _value_. In the code below, we have definitions for a String, a Number and an Image.

  name = "Flannery"
  age = 16
  logo = star(50, "solid", "red")

- What are the names given in each of these? __name, age, and logo__
- What are the values? __the String "Flannery", the Number 16, and an Image of a solid red star__

=== Investigate
[.lesson-instruction]
How many rows do we need to answer a Lookup question?
(Make sure sure students understand we only need one!)

@right{@image{images/AskQuestions.png,Ask Questions icon, 100}}
Let's talk about the code we can write, to let us answer a Lookup question by defining a row.

Tables have special functions associated with them, called @vocab{Methods}, which allow us to do all sorts of things with those tables. For example, we can get the first data row in a table by using the `.row-n` method:

  animals-table.row-n(0)

[.lesson-point]
Don't forget: data rows start at index _zero_!

[.lesson-instruction]
In the Interactions Area, use the `row-n` method to get the second and third data rows.

What is the Domain of .row-n? What is the Range? Find the contract for this method in your contracts table. A table @vocab{method} is a special kind of function which always operates on a specific table. In our example, we always use .row-n with the animals table, so the number we pass in is always used to grab a particular row from animals-table.

The code below will define the first row from the animals table:

  sasha    = animals-table.row-n(0)

Pyret also has a way for us to get at individual columns of a Row, by using a Row Accessor. Row accessors start with a Row value, followed by square brackets and the name of the column where the value can be found. Here are three examples that use row accessors to get at different columns from the first row in the animals-table:

  animals-table.row-n(0)["name"]
  animals-table.row-n(0)["age"]
  animals-table.row-n(0)["fixed"]

And of course, we can use our defined name, substituting it in place of all the redundant code:

  sasha["name"]
  sasha["age"]
  sasha["fixed"]

[.lesson-instruction]
- How would you get the `weeks` column out of the _second_ row? The third?
- Complete the exercises on @printable-exercise{pages/lookup-questions.adoc}.

Flip back to page 2 of your workbook and look at The Animals Dataset. Which row is animalA? Label it in the margin next to the dataset. Which row is animalB?  Label it in the margin next to the dataset.

Now turn back to your screen.
What happens when you evaluate `animalA` in the Interactions Area?

[.lesson-instruction]
- Define _at least_ two additional values to be animals from the `animals-table`, called `animalC` and `animalD`.

=== Synthesize
Have students share their answers, and see if there are any common questions that arise.

== Additional Exercises:
- @opt-printable-exercise{pages/more-practice-w-lookups.adoc}
- @opt-printable-exercise{pages/exploring-displays-1.adoc}
- @opt-printable-exercise{pages/exploring-displays-2.adoc}
- @opt-printable-exercise{pages/plot-practice.adoc}
