= Discover Inverse Operations: Multiplication & Division (2)
++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++

== From Dividing by Fractions to Multiplying by Whole Numbers

[cols="^.^5,^.^1,^.^5", stripes="none"]
|===
| @show{(coe '(/ 12 1/4))}  | @math{=} | @show{(coe  '(* 12 4))}
| @math{12 \div \frac{1}{4}}| @math{=} | @math{12 \times 4}
|===

@n What will the first Circle evaluate to? @fitb{5em}{80}  @hspace{5em} The second Circle? @fitb{5em}{80}

@n How is this equation similar to the equations on the page you just completed? How is it different? @fitb{}{@ifsoln{The same values are being used, but this time we are *dividing* by the fraction,}}

@fitb{}{@ifsoln{rather than dividing by the whole number. As a result, we get a larger outcome.}}

@vspace{1ex}

@center{*Did you know that dividing by @math{\frac{1}{4}} is the same as multiplying by @math{4}?*}


@n In the table below, fill in the blanks to demonstrate how _dividing by a fraction_ produces the same result as _multiplying by the fraction's reciprocal._ Then write the equivalent arithmetic expression for each of the Circles.

[cols="^.^5,^.^1,^.^5", stripes="none"]
|===
| @show{(coe  '(/ 10 1/5))}| @math{=} | @show{(coe '(* (?ANS 10) (?ANS 5)))}
| @math{\div} | @math{=} | @math{\times}
|===

@n This time, we've completed the multiplication Circle of Evaluation. You fill in the division Circle of Evaluation.

[cols="^.^5,^.^1,^.^5", stripes="none"]
|===
| @show{(coe  '(/ (?ANS 18) (?ANS 1/3)))} | @math{=}| @show{(coe '(* 18 3))}
| @math{\div} | @math{=} | @math{\times}
|===

@n Provide another example that demonstrates how _dividing by a fraction_ produces the same result as _multiplying by the fraction's reciprocal_.

[cols="^.^5,^.^1,^.^5", stripes="none"]
|===
| @show{(coe  '(/ (?ANS 45) (?ANS 1/9)))} | @math{=} | @show{(coe '(* (?ANS 45) (?ANS 9)))}
| @math{\times} | @math{=} | @math{\div}
|===

== Practice
Rewrite multiplication as division, and division as multiplication.

[cols="^.^3,^.^3,^.^3", stripes="none"]
|===

| @math{20 \times 4 =} @fitb{10em}{@ifsoln{@math{20 \div \frac{1}{4}}}}
| @math{21 \div \frac{1}{3} =} @fitb{10em}{@ifsoln{@math{21 \times 3}}}
| @math{12 \times 4 =} @fitb{10em}{@ifsoln{@math{12 \div \frac{1}{4}}}}

| @fitb{10em}{@ifsoln{@math{6 \div \frac{1}{3}}}} @math{= 6 \times 3}
| @fitb{10em}{@ifsoln{@math{14 \times 7}}} @math{= 14 \div \frac{1}{7}}
| @fitb{10em}{@ifsoln{@math{15 \div \frac{1}{2}}}} @math{= 15 \times 2}

|===
