= Divide First... or Solve Left-to-Right?

++++
<style>
div.circleevalsexp { width: auto; }

/* Make autonums inside tables look consistent with those outside */
table .autonum::after { content: ')' !important;}

</style>
++++


For each expression, draw _two_ unique Circles of Evaluation.

- In the column on the left, draw a Circle to illustrate evaluating from left to right.
- In the column on the right, draw a Circle to illustrate evaluating division first, followed by multiplication.
- Evaluate each Circle and make a note of whether or not they produce the same result.
We've done the first one for you.

[.FillVerticalSpace,cols="^.^1a,^.^3a,^.^6a,^.^6a", stripes="none", options="header"]
|===
|	 | Expression | Divide First | Solve Left-to-Right

| @n
| @math{3 \times 8 \div 2}
| @show{(coe '(* 3 (/ 8 2)))}
| @show{(coe '(/ (* 3 8) 2))}


| @n
| @math{4 \times 50 \div 2}
| @ifsoln{@show{(coe '(/ (* 4 50) 2))}}
| @ifsoln{@show{(coe '(* 4 (/ 50 2)))}}


| @n
| @math{5 \times 3 \div 3}
| @ifsoln{@show{(coe '(/ (* 5 3) 3))}}
| @ifsoln{@show{(coe '(* 5 (/ 3 3)))}}


| @n
| @math{5 \times 6 \div 3}
| @ifsoln{@show{(coe '(/ (* 5 6) 3))}}
| @ifsoln{@show{(coe '(* 5 (/ 6 3)))}}


| @n
| Come up with an example of your own! See if you can come up with an unusual expression.
|
|


|===

@n What did you Notice? What do you Wonder? @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Can you change the groupings or the order in which you evaluate an expression like this one: @math{100 \div 20 \div 5}? On the back of your paper, sketch out a few possible Circles. Which one is correct? Why do we need to use the left-to-right rule here? @fitb{}{}

@fitb{}{}

@fitb{}{}
