= Is there another way?

++++
<style>
.circleevalsexp { width: auto; }

/* Shrink vertical spacing on fitbruby */
.fitbruby{padding-top: 0.3rem;}
</style>
++++

For each expression, we've drawn two unique Circles of Evaluation.

- Adding and subtracting from left to right always works. Sometimes computing in other orders work, too! Can you find a pattern?
- Evaluate each pair of Circles of Evaluation below. Determine whether or not they are equivalent.

[cols="^.^1a,^.^3a,^.^6a,^.^5a, 2a", stripes="none", options="header"]
|===
|	 
| Expression 
| Multiplying and Dividing from Left-to-Right +
ALWAYS Gives us the Correct Answer 
| How about Right-to-Left?
| Equivalent?

| @n
| @math{3 \times 8 \div 2}
| @show{(coe '(/ (* 3 8) 2))} = @fitb{2em}{@ifsoln{@math{12}}}
| @show{(coe '(* 3 (/ 8 2)))} = @fitb{2em}{@ifsoln{@math{12}}}
| @ifsoln{Yes}

| @n
| @math{30 \div 5 \times 2}
| @show{(coe '(* (/ 30 5) 2))} = @fitb{2em}{@ifsoln{@math{12}}}
| @show{(coe '(/ 30 (* 5 2)))}  = @fitb{2em}{@ifsoln{@math{3}}}
| @ifsoln{No}

| @n
| @math{4 \times 50 \div 2}
| @show{(coe '(/ (* 4 50) 2))} = @fitb{2em}{@ifsoln{@math{100}}}
| @show{(coe '(* 4 (/ 50 2)))} = @fitb{2em}{@ifsoln{@math{100}}}
| @ifsoln{Yes}

| @n
| @math{15 \times 16 \div 8}
| @show{(coe '(/ (* 15 16) 8))} = @fitb{2em}{@ifsoln{@math{30}}}
| @show{(coe '(* 15 (/ 16 8)))} = @fitb{2em}{@ifsoln{@math{30}}}
| @ifsoln{Yes}

| @n
| @math{100 \div 20 \div 5}
| @show{(coe '(/ (/ 100 20) 5))} = @fitb{2em}{@ifsoln{@math{1}}}
| @show{(coe '(/ 100 (/ 20 5)))}  = @fitb{2em}{@ifsoln{@math{25}}}
| @ifsoln{No}
|===

@n Describe the pattern you discovered for when grouping could be flexible:

- We have to work left to right when @fitb{}{@ifsoln{the expression starts with division.}}
- We can compute in either order when @fitb{}{@ifsoln{the expression started with multiplication and then we divided.}}

@n _For each row that was equivalent, put a star next to the Circle of Evaluation that would be easier to compute in your head._ Why might teachers to decide to teach that we always have to compute addition and subtraction expressions from left to right? +
@fitb{}{@ifsoln{Students only have to learn one rule and will always compute the answer correctly!}}

@n What might be an advantage of learning more nuanced rules so that you can sometimes compute in another order? @fitb{}{} +
@fitb{}{@ifsoln{It allows us to work with smaller numbers, thereby simplifying computations we're doing in our head}}
