= Table Functions: Bringing it all Together

@description{Students use the Design Recipe to define @ifproglang{pyret}{functions that consume rows}@ifproglang{codap}{Transformers}, developing a structured approach to answering questions by transforming tables.}

@lesson-prereqs{lookups, functions-dr}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives
@objective{write functions that consume a Row and perform a _lookup_ to produce a column}
@objective{write functions that consume a Row and _compute_ to produce an Image}
@objective{write functions that consume a Row and _compute_ to produce a Boolean}

| Student-facing Lesson Goals
|

- Let's define functions that look up values from a Row.
- Let's define functions that produce Images from a Row.
- Let's define functions that compute a Boolean from a Row.

| Materials
|[.materials-links]

@material-links

| Preparation
| 
@preparation{
To do the Design Recipe Telephone activity, you will need to decide on groups of 3 and print copies of the word problems that you will be using. (A class of 30 will only need 10 copies of each Design Recipe problem.)
}

|===

== Reviewing Function Definition

=== Overview
Students use different representations of functions to define functions that consume _Rows_, discover _functions that consume other functions_, and compose a scatter plot function with a function they've defined.

=== Launch

By now you've had a chance to explore functions on your own, thinking of them in terms of several different representations:

- A mapping between _Domain_ and _Range_
- A list of discrete _input values_ and _output values_
- A symbolic _definition_

Now it's time to use those representations to help us work with Tables!

@slidebreak

@lesson-instruction{
- Open the @starter-file{row-functions}, save a copy, and click "Run".
- Scroll until you see the definition for `cat-row`. What will you get back if you evaluate `cat-row` in the Interactions Area?
- What species is the animal?
- What is its name?
- How old is it?
- Complete the first section of @printable-exercise{making-connections.adoc} (questions 1-5).
}

=== Investigate

You've already had a chance to work with the Design Recipe.

Each step in the Design Recipe helps us write the next one.

- If we can't write our Contract and Purpose, it means we haven't thought through the problem enough. Better to find this out _before_ we write the rest of our function!
- If we're having trouble writing our Examples, *we can check our Contract and Purpose for hints*.
- If we're having trouble writing the Definition, *we can check our Examples to see the pattern.*

These steps also help us _check our work_. If any two representations don't match, it means there's likely a bug somewhere.

Let's look at an example to see how this works with table-functions!

@lesson-instruction{
Complete the `age-gt` section of @printable-exercise{making-connections.adoc}.
}

@slidebreak

@teacher{Review student answers from the `age-gt` section of @printable-exercise{making-connections.adoc}, paying particular attention to the connections between "Contract and Purpose" and "Examples".
@ifslide{_Note: Discussion continues on the next slide._}}

```
# CONTRACT:
# age-gt :: Row -> Image
# consumes an animal, and draws a solid green triangle whose
# size is 5x the number age of the animal as the size

examples:
  age-gt(cat-row) is triangle(5 *          1,     "solid", "green")
  age-gt(dog-row) is triangle(5 *          3,     "solid", "green")

  age-gt(cat-row) is triangle(5 * cat-row["age"], "solid", "green")
  age-gt(dog-row) is triangle(5 * dog-row["age"], "solid", "green")
end

fun age-gt(r):       triangle(5 *       r["age"], "solid", "green") end
```

These examples show us exactly what should be produced for `cat-row` and `dog-row` - the two Rows representing "Sasha" and "Toggle", based on their `age`.

@lesson-instruction{
- Take a closer look at the examples.
- Think about how the first pair of examples relates to the second.
}

@slidebreak

Both pairs of examples are _correct_!

In the first pair, we see the values 1 and 3 , but no explanation of where they are coming from. The last pair shows how those values are _looked up_ from the example rows.

@ifslide{

```
# CONTRACT:
# age-gt :: Row -> Image
# consumes an animal, and draws a solid green triangle whose
# size is 5x the number age of the animal as the size

examples:
  age-gt(cat-row) is triangle(5 *          1,     "solid", "green")
  age-gt(dog-row) is triangle(5 *          3,     "solid", "green")

  age-gt(cat-row) is triangle(5 * cat-row["age"], "solid", "green")
  age-gt(dog-row) is triangle(5 * dog-row["age"], "solid", "green")
end

fun age-gt(r):       triangle(5 *       r["age"], "solid", "green") end
```

}

@slidebreak

@lesson-point{
If you're stuck on the examples step, here's a useful trick to get you started. Complete the following sentence: +
"_For this Row, I..._" +
Whatever you answer is the precise description of what to do for your example!
}

@slidebreak

*You can use both kinds of examples in your code!* 

- Sometimes we want to use real, concrete numbers to make sure our work is correct. 
- And sometimes we need to show all of our work, to make sure we are defining the function correctly! 

Programmers often use a mix of the two.

=== Synthesize

Why might it be beneficial to include both kinds of examples?

== Design Recipe Telephone

=== Overview
Students work in teams to collaboratively define multiple Table Functions. When these functions are composed in different ways, they can be used to do much more sophisticated analysis!

=== Launch

Why would it be challenging to make the following visualizations?

- a box plot showing the distribution of kilograms across old cats at the shelter
- a scatter plot showing the relationship between kilograms of young dogs at the shelter, and how many days it took to be adopted

There would be a lot of steps involved!

Most computer programs are written by huge teams! It is critical that each team member records their thinking with enough detail for other team members to be able to pick up where they left off.

We're going to practice collaborative programming and try writing some other Table Functions using the Design Recipe, through an activity called Design Recipe Telephone.

=== Investigate

@teacher{

1. Divide the class into groups of three.

2. Choose which set of word problems you are going to start with and give each student within each group a different word problem from the set.

[cols="1a,1a", options="header"]
|===
|Word Problem Set 1:
|Word Problem Set 2:

|
@handout{is-dog.adoc, is-dog}

@handout{days.adoc, days}

@handout{is-young.adoc, is-young}

|
@handout{is-old.adoc, is-old}

@handout{kilos.adoc, kilos}

@handout{is-cat.adoc, is-cat}
|===

Note that each of these word problems is the function-version of the code students have already written in @lesson-link{lookups/pages/lookup-expressions.adoc}!

}

@lesson-instruction{

- In this activity, each person in your group will start with a different word problem. You will each be doing _one step of each Design Recipe problem_. After you complete your step, you will fold your paper to hide the part that you were looking at so that only _your work and the rest of the recipe_ are visible. Then you will pass your work to the person to your right.

- The person who has received your paper will review your work and complete the next step based solely on what you wrote down for them. If they don't have the information they need, they will give the paper back to you for revision.

- Meanwhile, you will receive a different problem from the person to your left. If at any point your realize that the person before you didn't provide enough information, you may hand the paper back to them for revision.

- HINT: All of the word problems here will use code that looks a _lot_ like the code you wrote in @lesson-link{lookups/pages/lookup-expressions.adoc}! If you get stuck, refer back to your answers on that page!
}

@slidebreak

*Round 1:*
@lesson-instruction{
You should have a page with a Word Problem.

- Write the Contract and Purpose Statement.
- Fold your paper to hide the Word Problem.
- Pass your paper to the person to your right.

}

@ifslide{
@teacher{
Choose which set of word problems you are going to start with and give each student within each group a different word problem.

- Set 1: @handout{is-dog.adoc, is-dog}, @handout{days.adoc, days}, @handout{is-young.adoc, is-young}
- Set 2: @handout{is-old.adoc, is-old}, @handout{kilos.adoc, kilos}, @handout{is-cat.adoc, is-cat}

}
}

@slidebreak


@ifslide{_Make sure you’ve folded your paper over so that only the Contract and Purpose are visible._}

*Round 2:*

@lesson-instruction{
You should have just received a new page, that has been folded to hide the Word Problem.

- Write Examples from the Contract and Purpose Statement.
- Circle the Variables.
- Then fold your paper to hide the Contract and Purpose Statement.
- Pass your paper to the person to your right.
}

@slidebreak

@ifslide{_Make sure you’ve folded the top of your paper over so that only the Examples are visible._}

*Round 3:*

@lesson-instruction{
You should have just received a new page that has been folded so that the Examples are at the top.

- Write a Definition from the Examples you just received.
- When you're done, pass your paper to your right to return it to the person it started with.
}

@slidebreak

*Round 4:*

@lesson-instruction{
You should now be holding the page you started with.

- Unfold the page and type the full Design Recipe into the Definitions Area of the @starter-file{animals}.
- If your function is a Boolean-producing function, make sure that at least one of the examples should produce true and at least one should produce false. If not, add an additional example.
- Click "Run" and confirm that all tests pass.
- If not, collaborate with your team to identify which steps of the Design Recipe need to be reworked.
}

@teacher{
This activity can be repeated several times, or done as a timed competition between teams. The goal is to emphasize that each step - if done correctly - makes the following step incredibly simple.}

=== Synthesize
@QandA{
The Design Recipe is a way of slowing down and thinking through each step of a problem.

@Q{If we already know how to get the answer, why would it ever be important to know how to do each step the slow way?}
@A{Someday we won't be able to get the answer, and knowing the steps will help}
@A{So we can help someone else who is stuck}
@A{So we can work with someone else and share our thinking}
@A{So we can check our work}
@Q{Why is it helpful to use each of these steps in the Design Recipe?}
@Q{What step do you find the most challenging right now? The easiest?}
@Q{What are some functions you might want to define for your _own_ analysis?}
}
