# TO WRITE A QUESTION IN MD QUIZ

# HERE ARE THE PARTS OF A QUESTION

# 1) Currently there can only be one question per page.
[[questions]]

# 2) Available types for Bootstrap: 
# - Short Answer 
# - Multiple Choice (which can be restricted to True or False)
type = "MultipleChoice"

# 3) Write the question prompt. You can use markdown formatting!
# Images can be included as well, using markdown
prompt.prompt = """
![](woodchuck.jpg)How much wood would a woodchuck chuck, *if* a woodchuck could chuck wood?
"""

# 4) Write the answer.
# If `answerIndex` is set, the distractors will show in the order 
#   they are written, wit the answer inserted at the appropriate index
# If `answerIndex` is not set, the distractors and answer will 
#   appear in random order.
answer.answer = "not enough information is available to answer this question, because no data about wood chucks chucking wood exists."
prompt.answerIndex = 3

# 5) If it's multiple choice, also write the non answers, called "prompt.distractors".
# - The order of the multiple choice answers
# - The non answers can be listed before or after the answers.
# - There is not a prescribed number of non answers. 
#   (I've tested 1, 2, 3, and 4. If someone discovers limits, please define them here.)
prompt.distractors = [
"one chord",
"a whole tree",
"none",
"many"
]

# 6) context is optional.
# - It only appears when the answers are revealed at the end of the quiz. 
# - Feel free to leave it blank """ """
context = """
A wood chuck is an alternate name for a ground hog, a medium-sized rodent in the marmot family.
"""

# 7) Give each question a unique ID (eventually these will be generated automagically).
id = "abcdefghijklmonpqrstuvwxyz123"



# HERE IS A BASIC SHORT ANSWER QUESTION
[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the slope of the line defined by y = 3x + 7?"
answer.answer = "3"
context = """ """
id = "dbbaea6a-f469-464f-9d60-99ae98456b6a6"


# TRUE OR FALSE QUESTIONS
# Use MulipleChoice with a single distractor
[[questions]]
type = "MultipleChoice"
prompt.prompt = """
True or False: Squares are Rectangles.
"""
prompt.distractors = [
  "false"
]
answer.answer = "true"
context = """
Rectangles are 4-sided polygons with 4 right angles. Squares are the subset of rectangles that also have sides of equal length.
"""
id = "18ea4c61-c7c3-433f-add5-d3d3156e3e742"

# CURRENTLY THE TRACING QUESTION TYPE IS NOT USABLE FOR BOOTSTRAP 
# It comes with predefined text about compilers.
[[questions]]
type = "Tracing"
prompt.program = """
something sensible
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
This is a compiler error because line 4 tries to mutate `x` when `x` is not marked as `mut`.
"""
id = "bba6a299-b20f-4685-934a-792a591df3c05"