= Flags of the World

*Students demonstrate what they’ve learned about image composition to recreate a nation’s flag with code.*

[@lesson-intro-table]
|===
|Lesson Goals
|Students will be able to:

* Decompose a composite image into its component parts
* Create composite images using functions and spatial reasoning

|Student-Facing Lesson Goals
|
* I can figure out what shapes make up an image.
* I can create complex images using combinations of smaller images.

|Key Points for the Facilitator
|
* Samples of Flags - a visual guide to some flags appropriate for this project (require knowledge of overlay, overlay/align, beside, above)
* Contracts are especially important in this lesson - students should have their contracts page open and be able to figure out why they can’t combine three images at once.
* While learning, most students will define a new image with every step, which is completely fine and expected at this stage.  As students grow more comfortable, they may discover that they can nest functions together without these extra definitions.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.
* Students must be familiar with Image Manipulation functions for this activity.

|Materials
|
* https://docs.google.com/presentation/d/1pIlr43pyVVKwHTY1rm07vjWQ8RbmsqzVh2B6NmQotOA/edit?usp=sharing[Google Slides]
|===

[@lesson-intro-table]
|===
|Math Standards (CCSS)
|
* http://www.corestandards.org/Math/Practice/MP2[CCSS.MATH.PRACTICE.MP2],
Reason abstractly and quantitatively.

|CS Standards (CSTA)
|
* CS Standards here.
|===

== Get Ready:

Students should have their computer, contracts page, and pencil.

== Launch: (10 min)

On the board, give students a prompt to think on while they view the video.

*What role do flags play in events such as the Olympics?*

@link{https://www.youtube.com/watch?v=lnPqFq1lIGg&t=23m45s, [2012 Olympic Parade of Nations]}

The video has been cued up to midway through the 2012 Olympic Parade of Nations in London.  Watch 45-60 seconds before moving on.

== Explore: (10 min)

Have students use the web to investigate flags that are relevant to them or that they have an interest in.  Ask students to choose 2 or 3 interesting flags

== Discuss: (10 min)

* What are some recurring themes we see in the flags of different nations?
* Why do you think some of those themes exist?
* What do the different colors make you think of?
* How do you think the colors and shapes of the flag were chosen?
* Why isn’t there a standard size or shape for a flag?  Do you think there should be?

[.strategy-box]
.Strategies for English Language Learners
****
MLR 5 -- Co-Craft Questions and Problems: Give students time to think and discuss with a partner or a small group before large group discussion.  Encourage students to build off each other's responses and listen to different cultural perspectives.  Some students may be eager to discuss the flag of their family's home country or lineage, and others may not feel comfortable.
****

== Practice: (10 min)

As a class, practice by recreating the flag of Cameroon together.

== Create/Apply: (5 min)

Students create another flag or flags of their choosing.

=== Synthesizeion Activities:

* Collaborate with Social Studies or Language teachers to create deeper cross-curricular connections.

* Print off student-created flags and make a mural in the room or for display in the school.

== Some demo text only

Test of vocab items:

@vocab{accessor functions}

@vocab{axis}

Design recipe
@workbook-link{pages/fragments/late-to-class-design-recipe-assess.adoc}
