= Soekia: A Closer Look

Go to @link{http://Soekia.ch/GPT/?lang=en}. Click "Look Inside." Access the "Weather" collection from the green "Documents" panel, then respond to the prompts below.

== Look Inside: N-grams

@n In the yellow n-grams panel, click the red vertical "Create n-Grams" button. After you click, you will see a red circle appear on each document, one at a time and in sequence. What do you think this red circle represents? @fitb{}{}

@fitb{}{}

@n Set the N-grams to unigrams by clicking "1er". Click the "Create n-grams" button. You should see all of the N-grams populate.

@n Locate the n-gram with the longest green line. Click on it, then use the information that appears to complete the first column of the table below. (*Don't panic* if your answers are different from your peers'! That's exactly what _should_ happen.)

@vspace{1ex}

[cols="<.^2,^.^1,^.^1,^.^1", stripes="none", options="header"]
|===

|
| 1-Gram
| 3-gram
| 5-gram

| What is the N-gram? |||
| How many times was it found? |||
| In which documents did the N-gram appear? |||

|===

@n Change the N-grams to 3-grams, then 5-grams, to complete the remaining two columns of the table above.

@n What do you Notice about the information you recorded on the above table? What do you Wonder? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

== Look Inside: Suggested Words

@n With N-grams set to 5er, click on the right-facing text generation arrow to ask Soekia to "what's the weather like?" After a few sentences have been generated, click "Pause".

@n Look at the "Suggested words" list in the red panel. Click on one of the suggestions. What do you see? @fitb{}{}

@fitb{}{}

@fitb{}{}

@n You may notice that Soekia sometimes subtracts words from the beginning of a 5-gram to produce a 4-gram, then a 3-gram, etc. (For instance, it offers each of the following: "to values of 10 to", "values of 10 to", "of 10 to", "10 to", and "to".) What do you think is going on here? @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Return to the "Generate text" panel. Click on the "Choose yourself" icon beneath the generated text. (It is represented by an icon of a smiling face.) Some buttons are darker green than others. Make a guess about what a darker shade of green represents. @fitb{}{}

@fitb{}{@ifsoln{The darker the button, the higher the N of the N-gram.}}

@fitb{}{}



