= More Transformers: Transform Attribute and Build Attribute

@description{Students learn more about _Transformers_, including `Transform Attribute` and `Build Attribute`.}

@lesson-prereqs{codap-filtering}


[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives
@objective{table-filter}
@objective{table-build-column}

| Student-facing Lesson Goals
|

- Let’s learn how to transform one table into another.

| Materials
|[.materials-links]

@material-links

|===


== Transforming Columns

=== Overview
Students learn how to _transform columns_ using the `Transform Attribute` Transformer.

=== Launch
@slidebreak{Launch}

We've already explored the `Filter` Transformer, which walks through a dataset, applying the @vocab{Boolean} expression that we give it to each row -- and then creating a modified copy of our original dataset.

Suppose we want to _transform_ our table in a different way!

- Maybe we want to convert `Pounds` to `Kilograms` or `Weeks` to `Days`.
- Maybe we want to transform the `Pounds` column into a `Heavy` column, which produces `true` or `false` depending on if the animal is heavy.

The `Transform Attribute` Transformer makes that possible!

=== Investigate
@slidebreak{Investigate}

Like the `Filter` Transformer, the `Transform Attribute` Transformer walks through the table -- but what the expression produces for each row becomes the value in a new column. We name that column when we create our `Transform Attribute` Transformer.

@strategy{Naming Transformers and Attributes}{


You may have noticed that when we create and save Transformers, we give them sensible names such as `filter-is-cat` or `filter-is-fixed`. The first part of the name comes from the type of Transformer, and the second part describes what the Transformer does.

In this lesson, students transform and build columns to create _new attributes_. These new attributes need sensible names, too!  If we transform our `Weeks` attribute to days (multiplying by 7), the new attribute name should be `Days`.  If we build a new attribute showing the animals’ weight in kilos, the new attribute should be called `Kilos`.
}

@lesson-instruction{
Complete @printable-exercise{codap-transform.adoc} in the @starter-file{animals} to explore how to create and apply a `Transform Attribute` Transformer.
}


=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{What are some situations where you would want to the `Transform Attribute` Transformer?}
@A{A dataset from Europe might list everything in metric (centimeters, kilograms, etc), so we use `Transform Attribute` to convert to imperial units (inches, pounds, etc).}
@A{A dataset about schools might include columns for how many students are in the school and how many of those students identify as multi-racial. But when comparing schools of different sizes, what we really want is a column showing what _percentage_ of students identify as multi-racial. We could use `Transform Attribute` to compute that for every row in the table.}
}

== Building Columns

=== Overview
Students learn how to _build columns_, using the `Build Attribute` Transformer.

=== Launch
@slidebreak{Launch}
So far, we've used Transformers to _filter_ and to _transform an attribute_. The other Transformer we are exploring today is called `Build Attribute`.

=== Investigate
@slidebreak{Investigate-DN}

Now that you have some familiarity with creating and defining Transformers, let's explore the `Build Attribute` Transformer. Can you determine what it does?

@teacher{It creates an additional column in the dataset, rather than _transforming_ the existing column.}

@lesson-instruction{
Complete @printable-exercise{codap-build.adoc} in the @starter-file{animals}.
}


=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{Can you think of any other situations where you would want to the `Build Attribute` Transformer?}
@Q{How is `Build Attribute` similar to `Transform Attribute`? How are they different?}
@A{`Build Attribute` creates an additional column, using the expression that we provide. `Transform Attribute` converts an existing column, using the expression that we provide.}
@Q{When might it make more sense to _build_ an attribute, rather than to _transform_ it?}
@A{We would build rather than transform if we want to do comparisons across columns, or need to preserve the original column for any reason (e.g., we want measurements in metric and standard units.)}
}

@slidebreak{Synthesize}

Being able to create and define a Transformer is a _huge_ upgrade in our ability to analyze data! But as a wise person once said, "with great power comes great responsibility"! Dropping all the dogs from our dataset might be a cute exercise in this class, but suppose we want to drop certain populations from a national census? Even a small programming error could erase millions of people, impact funding for things like roads and schools, etc.

