= Threats to Validity

@lesson-description{Students consider possible threats to the validity of their analysis.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-linear-regression}

@worksheet-include{xtra/lang-prereq.adoc}
|===

== Review @duration{10 minutes}

You’ve learned a lot in this class about how to analyze data. What questions matter to you?

- Come up with a question that you want answered about the world around you.
- Using what you know now, what information would you need to collect in order to answer it?
- What subsets would you need to create? What analysis would you need to perform?

== Threats to Validity @duration{20 minutes}

[.lesson-point]
Survey says: “People prefer cats to dogs”

As good Data Scientists, the staff at the animal shelter is constantly gathering data about their animals, their volunteers, and the people who come to visit. But just because they have data doesn’t mean the conclusions they draw from it are correct! For example: suppose they surveyed 1,000 cat-owners and found that 95% of them thought cats were the best pet. Could they really claim that people generally prefer cats to dogs?

////
Have students share back what they think. The issue here is that cat-owners are not a representative sample of the population, so the claim is invalid.
////

There’s more to data analysis than simply collecting data and crunching numbers. In the example of the cat-owning survey, the claim that “people prefer cats to dogs” is *invalid* because the data itself wasn’t representative of the whole population (of course cat-owners are partial to cats!). This is just one example of what are called @vocab{Threats to Validity}.

On @worksheet-link{workbook-pages/threats-to-validity-2.adoc} and @worksheet-link{workbook-pages/threats-to-validity-3.adoc}, you’ll find four different claims backed by four different datasets. Each one of those claims suffers from a serious threat to validity. Can you figure out what those threats are?

////
Give students time to discuss and share back. Answers: The dog-park survey is not a random sample, the dogs are friendlier towards whomever is giving them food, etc.
////

Life is messy, and there are _always_ threats to validity. Data Science is about doing the best you can to minimize those threats, and to be up front about what they are whenever you publish a finding. When you do your own analysis, make sure you include a discussion of the threats to validity!

On @worksheet-link{workbook-pages/fake-news.adoc}, you’ll find some deliberately misleading claims made by slimy Data Scientists. Can you figure out _why these claims should not be trusted_? Once you’ve finished, consider your own dataset and analysis: what misleading claims could someone make about your work? Turn to @worksheet-link{workbook-pages/lies-darned-lies-n-statistics.adoc}, and come up with four misleading claims based on data or displays from your work. Then trade papers with another group, and see if you can figure out why each other’s claims are not to be trusted!

== Your research paper @duration{flexible}

Now that you’ve completed your analysis, it’s time to write up your findings!

[.lesson-instruction]
Open the @link{https://docs.google.com/document/d/1JoF83vm9xh9VvB9prmRsOsNgfSXjT0orHgfNGSymAnc/edit, Research Paper} template, and save a copy to your Google Drive.

Each section of the research paper refers back to the work you’ve done in the Student Workbook. Use these pages and your program to write your findings!

== Additional Exercises:

@worksheet-link{exercises/identifying-threats-1.pdf, Identifying Threats 1}

@worksheet-link{exercises/identifying-threats-2.pdf, Identifying Threats 2}

@worksheet-link{exercises/identifying-threats-3.pdf, Identifying Threats 3}