= Threats to Validity

@lesson-description{Students consider possible threats to the validity of their analysis.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-linear-regression}
| Lesson Goals
| Students will be able to...

* FILL
* FILL

| Student-Facing Lesson Goals
| I can...

| Materials
|
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
| 

| Relevant Standards
|
@include{xtra/lang-prereq.adoc}
|===

== Threats to Validity @duration{20 minutes}

=== Overview
Students are introduced to the concept of _validity_, and a number of possible threats that might make an analysis invalid.

=== Launch

[.lesson-point]
Survey says: “People prefer cats to dogs”

As good Data Scientists, the staff at the animal shelter is constantly gathering data about their animals, their volunteers, and the people who come to visit. But just because they have data doesn’t mean the conclusions they draw from it are correct! For example: suppose they surveyed 1,000 cat-owners and found that 95% of them thought cats were the best pet. Could they really claim that people generally prefer cats to dogs?

Have students share back what they think. The issue here is that cat-owners are not a representative sample of the population, so the claim is invalid.

There’s more to data analysis than simply collecting data and crunching numbers. In the example of the cat-owning survey, the claim that “people prefer cats to dogs” is *invalid* because the data itself wasn’t representative of the whole population (of course cat-owners are partial to cats!). This is just one example of what are called @vocab{Threats to Validity}.

There are four types of threats to validity you should know:

. *Selection bias* - Data was gathered from a biased, non-representative sample of the population. This is the problem with surveying cat owners to find out which animal is most loved!

. *Sample size* - Too little data was gathered in order to make a generalization or prediction. Asking ten people who they want for president will _not_ give us a good idea of how the country as a whole is voting!

. *Sample error* - Even if the selection is unbiased and has a large enough sample size, sometimes outliers are so extreme that they shift the results of our analysis in ways that don't represent the population as a whole. 

. *Confounding variables* - The gathered data does not take into account other factors that might influence the outcome. For example, wealthier countries often have higher life expectancies. The confounding variable here is _access to healthcare_, and wealthier countries often have better access to healthcare. It would be incorrect to assume that simply _having money_ makes us healthy! 

=== Investigate
On @workbook-link{pages/threats-to-validity-1.adoc} and @workbook-link{pages/threats-to-validity-2.adoc}, you’ll find four different claims backed by four different datasets. Each one of those claims suffers from a serious threat to validity. Can you figure out what those threats are?

=== Synthesize
Give students time to discuss and share back.

Life is messy, and there are _always_ threats to validity. Data Science is about doing the best you can to minimize those threats, and to be up front about what they are whenever you publish a finding. When you do your own analysis, make sure you include a discussion of the threats to validity!

== Fake News! @duration{20 minutes}

=== Overview
Students are asked to consider the ways in which statistics are misused in popular culture, and become critical consumers of some statistical claims. Finally, they are given the opportunity to misuse their _own_ statistics, to better understand how someone might distort data for their own ends.

=== Launch
You've already seen a number of ways that statistics can be misused:

. A chart, graph or display might be selected because it hides unfavorable data, or amplifies favorable data
. The boundaries of a chart or graph might be changed. For example, changing the scale on a bar chart will distort the difference between two bars, making them appear closer together or farther apart than they actually are.
. Someone might use the @vocab{mean} instead of the @vocab{median} as a summary statistic for heavily-skewed data, to hide the impact of an outlier.
. People might use the wrong language to describe a finding from Linear Regression, in order to make a claim seems stronger than it really is.
. Someone might use a correlation to imply causation!

With all the news being shared through newspapers, television, radio, and social media, it's imporant that all of us are critical consumers of information.

=== Investigate
[.lesson-instruction]
* On @workbook-link{pages/fake-news.adoc}, you’ll find some deliberately misleading claims made by slimy Data Scientists. Can you figure out _why these claims should not be trusted_? 
* Once you’ve finished, consider your own dataset and analysis: what misleading claims could someone make about your work? Turn to @workbook-link{pages/lies-darned-lies-n-statistics.adoc}, and come up with four misleading claims based on data or displays from your work. 
* Trade papers with another group, and see if you can figure out why each other’s claims are not to be trusted!

=== Synthesize
Have students share back their "lies". Was anyone able to stump the other group?

== Your research paper @duration{flexible}

Now that you’ve completed your analysis, it’s time to write up your findings!

[.lesson-instruction]
Open the @link{https://docs.google.com/document/d/1JoF83vm9xh9VvB9prmRsOsNgfSXjT0orHgfNGSymAnc/edit, Research Paper} template, and save a copy to your Google Drive.

Each section of the research paper refers back to the work you’ve done in the Student Workbook. Use these pages and your program to write your findings!

== Additional Exercises:

@link{pages/identifying-threats-1.pdf, Identifying Threats 1}

@link{pages/identifying-threats-2.pdf, Identifying Threats 2}

@link{pages/identifying-threats-3.pdf, Identifying Threats 3}