= Évaluer des cercles d'évaluation (2)

Écrivez chaque cercle d'évaluation sous forme d'expression mathématique et évaluez-la. @ifsoln{*Enseignants :* les réponses ci-dessous sont seulement indiquées avec les
parenthèses _nécessaires_. Si un élève ajoute des parenthèses supplémentaires (correctes), il aura quand même la bonne réponse.}


@do{
  (define expr1 '(- 12 (* 2 5)))
  (define expr2 '(+ (* 2 (+ 3 1)) 10))
  (define expr3 '(+ (/ 56 (* 2 4)) (- -7 3)))
  (define expr4 '(* -7 (+ 9 (/ 14 2))))
  (define expr5 '(+ (/ 15 -3) (- 30 (+ 2 (* 7 3)))))
  (define expr6 '(- (* -3 (/ 8 2)) (+ 7 (/ 22 (- 15 4)))))
}

[.FillVerticalSpace, cols=".^1a,^.^10a,^.^8a,^.^1a",options="header",stripes="none"]
|===
|	| Cercle d’évaluation
| Expression mathématique
| Réponse


|*@n*| @show{(coe  expr1)}
|  @showsoln{(math expr1)}
|  @showsoln{(eval expr1) }

|*@n*| @show{(coe  expr2)}
|  @showsoln{(math expr2)}
|  @showsoln{(eval expr2) }

|*@n*| @show{(coe  expr3)}
|  @showsoln{(math expr3)}
|  @showsoln{(eval expr3) }

|*@n*| @show{(coe  expr4)}
|  @showsoln{(math expr4)}
|  @showsoln{(eval expr4) }

|*@n*| @show{(coe  expr5)}
|  @showsoln{(math expr5)}
|  @showsoln{(eval expr5) }

|*@n*| @show{(coe  expr6)}
|  @showsoln{(math expr6)}
|  @showsoln{(eval expr6) }

|===

