= Numbers and Strings
++++
<style>
  #content { display: block !important; }
</style>
++++

- For each of three sections below, refer to the corresponding table in the starter file.
- Start with Table A. One by one, working from left to right, follow the instructions at the top of each column. *_To do so, you will need to enter the specified text into the "Edit Formula" box that appears after you click on the column name._* (See images below.)
- Move onto the next table after you have responded to all of the relevant prompts.

@vspace{1ex}

@left{@image{../images/drop-down.png, 450}} @right{@image{../images/type-your-name.png, 250}}

@vspace{2ex}


== Strings (Table A)

_String values are always in quotes._

@n Type your name in the `Formula` box. Select `Apply.` What error message appears? @fitb{}{}

@n Type your name in quotes. Why didn't you get an error this time? @fitb{}{@ifsoln{I typed my name in quotation marks,}}

@fitb{}{@ifsoln{so the computer recognized it as a string.}}

@n Try typing your name with the opening quote, but _without the closing quote._ What do you think a "syntax error" is? @fitb{}{}

@fitb{}{@ifsoln{A syntax error is an error where the computer cannot make sense of the code}}

@fitb{}{@ifsoln{e.g. missing commas, missing parentheses, unclosed strings.}}

@vspace{1ex}

== Numbers (Table B)

@n Type `42` (no quotes). Type a fraction. Type a decimal. Type an integer. Does anything surprise you about how numbers behave in CODAP?

@fitb{}{}

@fitb{}{}

@star Click on any of the attribute names, and from the drop-down menu that appears, select "Edit Attribute Properties." What happens when you change the _type_?

@fitb{}{}

@fitb{}{}

@star How about when you change the _precision_?

@fitb{}{}

@fitb{}{}

@vspace{1ex}

== Numbers and Operators (Table C)

@vspace{1ex}

@n Just like math, CODAP has @vocab{operators} like `+`, `-`, `*` and `/` and `^`. Type into the Fomula Box and then apply the expressions speecified on Table C. What do you notice? Does CODAP know the order of operations? @fitb{}{@ifsoln{Yes, CODAP automatically applies the order of operations.}}




