= Project: Design a Survey

@description{Students come up with a research question and design a survey to gather data to answer it. They exchange surveys to get some hands-on practice with clean and dirty data and incorporate what they learn to polish their surveys.}

@lesson-prereqs{data-collection}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* a
* b
* c

| Student-facing Lesson Goals
|

* Let's use data to answer a question.

| Materials
|[.materials-links]

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
|
* This project an extension of @lesson-link{project-data-exploration}. In @lesson-link{project-data-exploration}, students gain familiarity with a dataset. In this project, students respond to that question by analyzing statistics and displays. We encourage you to modify @starter-file{research-paper} to meet your students needs.
* This project can also address _domain-specific learning goals_ that are appropriate for your classroom. For example, students in a Physics class might write their paper about data they collected from an experiment.


|===

== Design a Survey @duration{flexible}

=== Overview

It is exciting to collect data to answer the questions we are most curious about! But collecting high quality data is a tricky endeavor; many potential problems lurk beneath the surface. Good Data Scientists know how to minimize those issues.

=== Launch

In this project, your team will design a survey that yields "cleaner" data by using advanced survey tools to avoid many of the challenges faced by Data Scientists.

@teacher{We recommend printing and distributing the student-facing @handout{rubric-survey-design.adoc} to help students understand the scope of the project and your expectations at the outset. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context.}

@lesson-instruction{
Complete @opt-printable-exercise{survey-brainstorm.adoc} by choosing a topic and brainstorming:

- a list of questions that would help you gather data about the project
- the data types you would expect as responses for each of your questions
- the displays you would be interested in seeing as part of your analysis
- grouped samples that you'd want to explore separately (e.g. just 8th graders just the males, etc).}

=== Investigate

Now that you know what questions your team wants to ask, it's time to actually create the survey!

@lesson-instruction{
With your team, create a _first draft_ of the survey by opening a new google form and entering:
* The title of the survey
* A description of what the survey is for and how responses will be used
* At least 8 good questions, copied from your @opt-printable-exercise{survey-brainstorm.adoc}.}

Once a rough draft has been completed, students are ready to make improvements to the survey so that it yeilds the cleanest results possible!

@lesson-instruction{
Read through the survey with your team, considering each of the questions one by one, and making improvements along the way.
- Have you indicated which questions are required?
- Does each question have a good description or instructions?
- Would any of your questions yield cleaner results if you specified the data type of the answer?
- Would any of your questions yield cleaner results if you used multiple choice options?
- If you’re using multiple choice, have you included all of the options that people would need to be able to reply to your question?
}

Now, let's hack each other's surveys!


@lesson-instruction{
- Exchange surveys with another group and test the limits of their survey by trying to enter as much "dirty" data as you can!
- Turn to @opt-printable-exercise{survey-hacking.adoc} and, for each dirty data example, write down what you submitted and what suggestion you would have to help the other group guard against it.
}

=== Synthesis

Using what they learned from reflecting on the other team's survey and the written feedback they received, students should revise their survey so that it's ready to collect "cleaner" data from the general public!






