= Exploring Health v. Wealth

@description{Students investigating a dataset comparing wealth and median-life expectancy for countries of the world, and find the best linear, quadratic and exponential models they can to fit the data.}

@lesson-prereqs{fitting-models}

@keywords{logarithm}

@add-to-lang{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

- Model logarithmic relationships using functions

| Student-facing Lesson Goals
|

- Let's use Pyret to model logarithmic relationships in data


| Materials
|[.materials-links]
@material-links

| Preparation
| 
@preparation{
- Much of the exploration in this lesson hinges on a custom-built interactive Desmos activity. + 
You will want to:
 * Open @starter-file{alg2-log-desmos}.
 * Make a link or code to share with your students.
 * Decide how you will share the link or code with students and, if you are using our Google Slides, add the appropriate link to the slide deck.
 * Set the pacing so that students are only able to interact with the first two slides. _(As the lesson progresses you will be directed to adjust the pacing or sync students to you so that they have access to relevant slides.)_
- _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions-alg2.adoc, _Here's what you need to do._}
}

| Key Points For The Facilitator
|
- This lesson assumes that students have been introduced to logarithms before, and are familiar with computation involving logarithmic functions.
- The focus of this lesson is about _applications_ of log functions, and building an intuition for logarithmic computation by motivating substantial trial and error.
|===

== Is Poverty Bad for Your Health?
@objective{model-explore}

=== Overview
Students explore the @starter-file{alg2-countries}, and find a relationship between wealth and median life expectancy.

=== Launch
--
@right{@image{images/questions.png, 250}}

- Countries measure their income in "Gross Domestic Product", which is often abbreviated "GDP". Many economists divide the total income for the country by the number of people living there, to estimate the average income of each person. This is called _Per-Capita GDP._
- Countries estimate how long-lived their citizens are by recording how long everyone lives, then taking the median of all those ages. This is called _Median Life Expectancy._

We want to know if there a positive relationship between Per-Capita GDP and Median Life Expectancy. In other words: *Do people in rich countries live longer?*
--

@lesson-instruction{
- In small groups, discuss and complete @printable-exercise{hypothesis-graph.adoc}.
- Be prepared to share your graphs, and why they look the way they do!
}

@slidebreak

What graphs did you draw? Why do you think your graph accurately reflects the relationship between income and life-expectancy?

@slidebreak

For many of your graphs, the first $20,000 or so of income shows a huge improvement in life expectancy: this might be enough to afford a place to live, see a doctor every once in a while, etc. But will that same $20,000 make a difference in the life-expectancy of a billionaire?

=== Investigate
Let's take a look at some real data on income and life expectancy across the world.

@lesson-instruction{
- Open the @starter-file{alg2-countries}
- From the File menu, select "Save a Copy", and click "Run".
- Make a scatter plot showing the relationship between `pc-gdp` and `median-lifespan`, using the name of the `country` as the label.
- Working in pairs or small groups, complete @printable-exercise{exploring-countries.adoc}.
}

@slidebreak

@center{@image{images/scatter-plot-pcgdp-lifespan.png, 450}}

@teacher{
Discuss students' findings. Pay special attention to the @vocab{form} that students use to describe the pattern in the scatter plot. Is it linear, or something else? Is it strong or weak? If there's some disagreement among the students, that's a good thing!
}


=== Synthesize
- If a wealthy country is suffering heavy casualties in a war, where would we expect to see that country's datapoint?
- What other conditions would cause a point to shift up, down, left or right?

== Linear? Quadratic? Exponential?
@objective{model-fit-function}

=== Overview
Students try to fit models they've seen before to the data.

=== Launch
How well do you think a linear model would fit this data? A quadratic one? Exponential?

=== Investigate

@teacher{Make sure you have created a link or code for your class to @starter-file{alg2-log-desmos} and paced the class so they have access to the first 2 slides.}

@lesson-instruction{
- Open the *Desmos* link I've shared with you. (The file should be called *Fitting Wealth-v-Health and Exploring Logarithmic Models*.)
- Working in pairs or small groups, complete @printable-exercise{fitting-models.adoc}.}

@teacher{
This activity involves lots of trial and error, as students try to come up with a good linear, quadratic, or exponential model. +
The goal is to discover that a new kind of model is necessary, not to find a perfect fit with linear, quadratic, or exponential models!
}

@slidebreak

@ifslide{@image{images/scatter-plot-pcgdp-lifespan.png, 450}}

@QandA{
@Q{What's the best model you came up with?}
@Q{What kinds of lines or curves did you draw?}
@Q{How would you describe the shape of the scatter plot for `median-lifespan` versus `pc-gdp`?}
@A{It starts out rising fast on the left, before tapering off as `pc-gdp` increases to the right.}
@Q{How well did our linear, quadratic, and exponential models fit this data?}
@A{None of the kinds of functions we've seen so far exhibit the behavior we see here! In some ways, this behavior is the exact opposite of exponentials: instead of starting slow and taking off like a rocket, this curve explodes up the y-axis right away, before leveling off.}
}

=== Synthesize



