= Project: Snack Habits

@description{Students analyze their class' snacking habits in comparison with data on childhood obesity in the U.S. _This project supports the learning goals of our lesson on @lesson-link{data-cycle}._}

@lesson-prereqs{data-cycle}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

- develop interesting statistical research questions that can be answered using a spreadsheet of data collectively generated by the class
- understand what it means to clean a spreadsheet
- analyze class data, using Pyret displays to support their analysis
- search for relevant graphs on the internet to use as points of comparison

| Student-facing Lesson Goals
|

- Let's collect data, create a collective spreadsheet, and understand what it means to “clean” a spreadsheet.  
- Let's develop personal statistical research questions to investigate using our data.
- Let's analyze our class data, using Pyret to create displays that will support our analysis.  
- Let's compare our snacking habits to the class and to the U.S. population to find out how they are similar and different.

| Materials
|[.materials-links]
@material-links

| Preparation
|
@preparation{
- Make a copy of @link{https://docs.google.com/forms/d/1PklP5FhpsWlUrQU6UaV0OKYxzq_Pz5YheLoiGs3yTeM/copy, this Google form} and share a link with your students so that all of their responses will end up in the class' collective spreadsheet.
- None of the handouts for this project are in the workbook, so be sure to print copies of whatever you'll be distributing.
- Teachers are welcome and encouraged to edit and adapt the student-facing @handout{rubric-snack-habits.adoc} for their unique classroom context and distribute it to help students understand the scope of the project - and your expectations - at the outset.
}

| Facilitation Note
| 
Before students will be able to get to the analysis phase of this project, they will need at least 5 days to collect the data to generate the collective data set. Including at least one weekend for tracking snack habits will likely lead to richer data.

Some teachers use this lesson to teach about data cleaning and opt to teach our lesson on @lesson-link{data-collection} during this project or as a precursor to it.

Students can also gather their research about the US during the time between the start of this project.
|===

== Building a Data Set: Our Snacking Habits @duration{flexible}

=== Overview

Students track their snacking habits over the course of 5 days to generate a collective data set. In preparation, they'll identify the data types of each variable. By revisiting the spreadsheet the class is generating throughout the data collection phase, you'll have an opportunity to discuss what it means to clean a data set.

@teacher{Note: This phase of the project can be completed at the same time as the Researching U.S. Snacking Habits phase of this project. It could also be completed before or after that phase.}

=== Launch

As a result of advocacy, food packaging is required to provide consumers with nutritional information so we can make informed choices.  

We're going to track our snacking habits for 5 days to generate a collective data set that we can analyze. For each snack you eat on those days (not your real meals) you will record a number of pieces of information in a google form.

@lesson-instruction{
- Let's turn to @handout{snack-habits-data-types.adoc} and take a look at the kinds of data we'll be collecting.
- What do you Notice? What do you Wonder?
- With your partner complete the third column of the table by deciding what data type each variable will be.
}

Confirm that students have correctly identified the data types.

@teacher{
Make sure you've made a copy of @link{https://docs.google.com/forms/d/1PklP5FhpsWlUrQU6UaV0OKYxzq_Pz5YheLoiGs3yTeM/copy, this Google form} and shared a link with your students.
}

@lesson-instruction{ 
- Your task is to complete the google form for every snack you eat over the next 5 days. 
- Please save the link I shared with you somewhere that will be easy for you to find. (In "Notes" on your phone? In a text message? In an email?)
- If you eat a snack when you don't have time to fill out the form, please take a picture of it and/or make a note to help you fill out the form later on.
- We will be looking at the spreadsheet together in our next class to see how our dataset is shaping up.
}

=== Investigate

@teacher{
Reviewing the spreadsheet with students over the course of the next several days is a great opportunity to teach about data cleaning. Some teachers take a deeper dive into the topic during this phase of the project with our lesson on @lesson-link{data-collection}.
}

Project the spreadsheet each day and discuss as a class.

@lesson-instruction{
- Are there any inconsistencies in our data that we need to clean up before we will be able to import this sheet into Pyret?
- What ideas do you have for how we might address them?
} 

=== Synthesize



== Research: U.S. Snacking Habits Data

=== Overview

Students will gather information from studies about US American snacking habits and compare them to the data we've just gathered as a class.

=== Launch

@lesson-instruction{
Do you think the sample we've made of our snack habits is representative of snacking in the United States?
}

We don't have to guess! There's plenty of research out there for us to look at. In fact, enough data has been collected about childhood obesity in the United States that soda machines and unhealthy snacks have been pulled from many schools.

=== Investigate

@lesson-instruction{
- Open your favorite search engine (Google, Brave, DuckDuckGo, etc.) and type +
"What do Americans eat for snack?”
- Look for graphs that share information related to the kinds of data we're collecting about our own snacking habits.
- Use this to compare with your data and the class data.  
- What question does this inspire?
}

=== Synthesize



== Analysis: A Statistical Question of Your Own

=== Overview

=== Launch


=== Investigate

@lesson-instruction{
- Make your own copy of @link{https://docs.google.com/presentation/d/1nnPpgCQDYknyxTzc_dvs34R2szxS3izz2Ya5gpAKDtE/copy, this slide template}.
- Edit each slide to share your thinking and findings. 
Add more slides if you need!  
}

=== Synthesize

- What were the pros and cons of working with data generated by you and your classmates?
- What other data do you wish had been part of our collective data set? What other questions would you suggest adding to the form?

@teacher{
- Once finished, encourage students to self-assess and revise their work. 
- Decide what form of sharing their projects works best for you. 
  * Class presentations can instill a sense of pride. 
  * Presenting in small groups can take less time. 
  * You may also want to have them print some part of their presentation to display on a bulletin board.
- Did your students have brilliant suggestions for how we could improve the form for future classes? Please share your ideas with @link{contact@bootstrapworld.org}!
}



