[[questions]]
type = "MultipleChoice"
# The prompt we want to use (can be a multi-line string!)
prompt.prompt = """
Camille is curious about the distribution in the “pounds” column of the animals dataset and experiments with various bin sizes.

Which of the following displays would be most useful?
"""
# The correct choice
answer.answer = "hist3.png"

# NOTE: By default, the answer and distractor list are shuffled
# randomly! 
prompt.distractors = [
"hist1.png",
"hist2.png",
"hist4.png"
]

# randomized is OK, so we don't set the answerIndex
#prompt.answerIndex = 0

# This will add an extra string of text at the bottom of the question.
# Some questions might need some extra explanation
context = """
"""

