= Order of Operations

++++
<style>
#content .embedded {min-width: 550px; width: 80%; margin: 0px auto;}
.big .mathunicode {font-size: 3em !important; color: black;}
.strategy-box span.circleevalsexp { width: unset; }
</style>
++++

@description{Students learn to model arithmetic expressions with a visual tool for Order of Operations, known as "Circles of Evaluation".}

@lesson-prereqs{}

@keywords{Circles of evaluation, PEMDAS, GEMDAS}
@add-to-lang{+, -, * , /}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* Model an @vocab{arithmetic expression} using @vocab{Circles of Evaluation}.
* Translate Circles of Evaluation into code.

| Student-facing Goals
|
* Let's model @vocab{arithmetic expressions} visually with @vocab{Circles of Evaluation}.
* Let's learn how Circles of Evaluation can be translated into code!

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

|Preparation
| * @optional If you want to engage your students with a hands-on activity as part of this lesson, be sure to print and cut out this @handout{pages/cards-for-matching-coe-exp.adoc, set of cards for physically matching arithmetic expressions with Circles of Evaluation}.

| Key Points For The Facilitator
|
* Error messages are the computer trying to give us a clue that something is wrong.  Model reacting to error messages with interest to demonstrate to students that the messages are a helpful tool.
* After the first few exercises in creating Circles of Evaluation, ask students whether they create them from the 'inside-out' (drawing the inner circles first) or from the 'outside-in.'  After they've given their responses, have them try using the OTHER way!
* For a memory hook, model the "bug that crawls through the circle" explanation.


|===

== Order of Operations @duration{30 minutes}

=== Overview
Students are given a challenging expression that exposes common misconceptions about order of operations. The goal is to demonstrate that a brittle, fixed notion of order of operations is insufficient, and lead students to a deeper understanding of order of operations as a _grammatical_ device, rather than a computational one. The Circles of Evaluation can be thought of as "sentence diagramming for arithmetic".

@strategy{
@span{.title}{Circles of Evaluation}

The Circles of Evaluation are a critical pedagogical tool in this course. They place the focus on the _structure_ of mathematical expressions, as a means of combating the harmful student belief that the only thing that matters is the _answer_.

@right{@image{images/pemdas.png, 200}}The order of operations are often summarized by models like this pyramid or mnemonics like PEMDAS, GEMDAS, etc. These rules are brittle, and don't always make it clear what we need to do. 

Imagine a student with only these tools confronting the expression, @math{\frac{7 + 8}{2}} or @math{\sqrt{11 + 5} - 2}

What we need is a __better way to read math__! 

Circles of Evaluation can be used to diagram arithmetic sentences to expose common misconceptions about Order of Operations, and make an excellent scaffold for tracing mistakes when a student applies the Order of Operations incorrectly. They are also a bridge representation, which naturally connects to function composition and converting arithmetic into code.
}

=== Launch

If you were to write instructions for getting ready for school, it would matter very much which instruction came first!

Imagine what might happen if someone tried to follow these steps: 

. Put on your sneakers.
. Tie your sneakers.
. Put on your socks.
 
Sometimes we need multiple expressions in mathematics, and the order matters there, too!

Mathematicians didn’t always agree on the Order of Operations, but at some point it became important to establish conventions that would allow them to work together.

@lesson-instruction{

This math problem went viral on social media recently, with math teachers arguing about what the answer was! 
[.big]
@center{@math{6 \div 2(1 + 2)}}

- Take a minute to think about the answer before we learn a new strategy for _drawing the structure_ of this expression so that we can settle the debate! 
- Then turn to @printable-exercise{coe-notice.adoc} and take a minute to record what you Notice and Wonder about the @vocab{Circles of Evaluation} you see.
- What did you Notice?
- What did you Wonder?
}

*The rules for drawing Circles of Evaluation are simple:*

1) Every Circle must have one - and only one! - @ifproglang{pyret}{operator or} function, written at the top.

2) The inputs @ifproglang{wescheme}{to the function} are written left-to-right, inside the Circle.

3) Circles can contain other Circles.

@lesson-instruction{
- Let's draw the Circle of Evaluation for the expression @math{10 - (5 + 3)}
}

@QandA{
@Q{What should we do first?}
@A{It depends! We can either work 
- outside in: @show{(coe '(- 10 ((?ANS +) (?ANS 5) (?ANS 3))))}
- or inside out: @show{(coe '((?ANS -) (?ANS 10) (+ 5 3)))}
- Either way, we'll end up with @show{(coe '(- 10 (+ 5 3)))}
}
}

@teacher{
@optional If it works for you, use @handout{pages/cards-for-matching-coe-exp.adoc, this set of cards} to have students physically match expressions and Circles of Evaluations.
}

@lesson-instruction{
- Turn to @printable-exercise{pages/match-arith-coe.adoc} and match each expression with its corresponding Circle of Evaluation.}

@teacher{Confirm that students have correctly identified which circle goes with each expression.}

@lesson-instruction{
- Turn to @printable-exercise{pages/complete-coe-from-arith.adoc} and complete each Circle of Evaluation based on its corresponding expression.
- Then turn back to @printable-exercise{coe-notice.adoc} and write an expression for each of the Circles of Evaluation.

[cols="1a,2a,2a,3a,3a", options="header"]
|===
|1|2|3|4|5

|@show{(coe '(* 5 6))} 
|@show{(coe '(* (/ 15 3) 6))}
|@show{(coe '(* 5 (- 28 22)))}
|@show{(coe '(* (/ 15 3) (- 28 22)))}
|@show{(coe '(* (/ 15 (- 4 1)) 2))}

|@math{5 \times 6}
|@math{15 \div 3 \times 6}
|@math{5 \times (28 - 22)}
|@math{15 \div 3 \times (28 - 22)}
|@math{15 \div (4 - 1) \times 2}
|===
}

=== Investigate



@lesson-instruction{
Turn to  @printable-exercise{pages/2-column-intro-w-parens.adoc} and draw Circles of Evaluation for each of the expressions.
}

Spend some time ensuring that students have drawn their circles correctly. You may want to have them compare their circles with their partner, others at their table, or against a provided answer key.

@lesson-instruction{
Let's see if we can settle the internet debate about what @math{6 \div 2(1 + 2)} evaluates to. Take a minute to draw the Circles of Evaluation. Then evaluate the expression and see what you get.
}

@teacher{

[.embedded, cols="^.^3,^.^1,^.^3, ^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|@show{(coe '(* (/ 6 2) (+ 1 2)))} | &rarr; | @show{(coe '(* 3 3))} | &rarr; | @math{ 3 \times 3 = 9}
|===
}

@strategy{
@span{.title}{Pedagogy Note}

Circles of Evaluation are a great way to get older students to re-engage with (and finally understand) the order of operations while their focus and motivation are on learning to code.  Because we recognize this work to be so foundational, and know that some teachers choose to spend a whole week on it, we have developed lots of additional materials to help scaffold and stretch. You will about 20 additional pages linked in @link{index.shtml#_additional_exercises, the Additional Exercises section} at the the end of this lesson.

}

=== Synthesize

- Did some students prefer working outside-in to inside-out? Why?
- Did some students find that different strategies worked better for different _kinds_ of problems? Why or why not?
- Is there more than one way to draw the Circle for @smath{(+ 1 2)}? If so, is one way more "correct" than the other?
- Up until now, we didn't have a visual spatial model for _reading_ arithmetic expressions. Ask students to compare Circles of Evaluation to previous methods they've learned for _computing_ these expressions (PEMDAS, GEMDAS, etc)

== From Circles of Evaluation to Code  @duration{25 minutes}

=== Overview

Students learn how to use the Circles of Evaluation to translate arithmetic expressions into code.

=== Launch

Besides helping us to see the structure of mathematical expressions in order to evaluate them correctly, Circles of Evaluation can also be used to help us write code!

@lesson-instruction{
When converting a Circle of Evaluation to code, it's useful to imagine a "spider" crawling through the circle from the left and exiting on the right.

@ifproglang{wescheme}{
The first thing the spider does is cross over a curved line (an open parenthesis!), then visit the operation - also called the _function_ - at the top. After that, she crawls from left to right, visiting each of the inputs to the function. Finally, she has to leave the circle by crossing another curved line (a close parenthesis).
}

@ifproglang{pyret}{
* The first thing the spider does is cross over a curved line (an open parenthesis!). 
* For Circles of Evaluation with _operators_ (addition, subtraction, etc.):
** the spider visits the first number on the left
** then she visits the top of the circle for the operation
** then she visit the number on the right 
* Finally, she has to leave the circle by crossing another curved line (a close parenthesis).
}
}

@ifproglang{pyret}{
In Pyret, @vocab{operators} like `+`, `-`, `*`, and `/` are written in between their inputs, just like in math. @vocab{Function} names like `f`, `g`, `num-sqrt` and `num-sqr` get written at the beginning of an expression, for example @show{(code '(f x))} or @show{(code '(sqrt 9))}

For now, we'll focus on Circles of Evalutation with @vocab{operators}.
}

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===

|*Expression*			      | &rarr; | @show{(math '(+ 3 8)) }
|*Circle of Evaluation*	| &rarr; | @show{(coe  '(+ 3 8)) }
|*Code*					        | &rarr; | @show{(code '(+ 3 8) #:parens true) }
|===

@ifproglang{wescheme}{
All of the expressions that follow the function name are called arguments to the function. The following diagram summarizes the shape of an expression that uses a function.
@span{.center}{@image{images/wescheme-code-diagram.png, 400}}
}

Arithmetic expressions involving more than one operation, will end up with more than one circle,
@ifproglang{wescheme}{and more than one pair of parentheses.}
@ifproglang{pyret}{and, whether or not there are parentheses in the original expression, the code requires parentheses to clarify the order in which the operations should be completed.}

@do{
  (define exprA '(+ 7 (* 3 2)))
}

[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|*Expression*			      | &rarr; | @show{(math exprA)}
|*Circle of Evaluation*	| &rarr; | @show{(coe exprA)}
|*Code*					        | &rarr; | @show{(code exprA #:parens true) }
|===

@QandA{
@Q{Why are there two closing parentheses in a row, at the end of the code?}
@A{Because there are two circles that need to be closed! }
}

@lesson-instruction{
Fill in the blanks to complete the code for each Circle of Evaluation on @printable-exercise{pages/complete-code-from-coe.adoc}. 
}

@QandA{
@Q{What would the code look like for these circles? 
+
@do{
  (define expr1 '(/ 6 (+ 1 2)))
  (define expr2 '(* (- 10 5) 6))
}
[.embedded, cols="^.^1a,^.^1a", grid="none", stripes="none" frame="none"]
|===
|@show{(coe expr1)}		| @show{(coe expr2)}
|===
}
@A{ {empty} 
@hspace{9em} @show{(code expr1 #:parens true)}	@hspace{12em} @show{(code expr2 #:parens true)}
}

}

=== Investigate

@lesson-instruction{
- Turn to @printable-exercise{pages/3-column-intro.adoc}. On this page, both the Arithmetic Expression and Circles of Evaluation are provided. All you have to do is translate them into code.
- Once you confirm that your code is correct, continue on to @printable-exercise{pages/3-column-outro.adoc}.
- If time allows, take turns entering the code into @starter-file{editor} with your partner.
}

@teacher{We have lots of challenge materials, including @printable-exercise{pages/3-column-challenge.adoc}, available in the @link{#_additional_exercises, the Additional Exercises section} at the the end of this lesson so that you're ready to challenge students who fly.}


@strategy{
@span{.title}{Strategies For English Language Learners}

MLR 7 - Compare and Connect: Gather students' graphic organizers to highlight and analyze a few of them as a class, asking students to compare and connect different representations.
}

=== Synthesize
- What is something that's working well for you about using the Circles of Evaluation?
- What is something that is challenging for you about using the Circles of Evaluation?
- What questions do you still have about the Circles of Evaluation?
- If an expression has three sets of parentheses, how many Circles of Evaluation do you expect to need?

@ifproglang{pyret}{
As in math, **there are some cases where the outermost parentheses can be removed in Pyret**:

- @math{(1 + 2)} can be safely written as @math{1 + 2}, and the same goes for the Pyret code
- @math{(1 * 2) * 3)} can be safely written as @math{1 * 2 * 3}, and the same goes for the Pyret code

You will likely see code written using this "shortcut", but it's always better to at least start with the parentheses to make sure your math/code is _correct_ before taking them out. **It is never wrong to include them!**
}

== Testing out your Code @duration{optional}

=== Overview

Circles of Evaluation are a powerful tool that can be used without ever getting students on computers. If you have time to introduce students to the @starter-file{editor}, typing their code into the Interactions Area gives students a chance to get feedback on their use of parentheses as well as the satisfaction of seeing their code successfully evaluate the expressions they've generated.

=== Launch

@lesson-instruction{
- Open @starter-file{editor} and click "Run".
- For now, we are only going to be working in the Interactions Area on the right hand side of your screen.
- Type @show{(code '(+ (* 8 2) (/ 6 3)))} into the Interactions Area.
- Notice how the editor highlights pairs of parentheses to help you confirm that you have closed each pair.
- Hit Enter (or Return) to evaluate this expression. What happens? _If you typed the code correctly you'll get 18. If you make a mistake with your typing, the computer should help you identify your mistake so that you can correct it and try it again!_
- Take a few minutes to go back and test each line of code you wrote on the pages you've completed by typing them into the Interactions Area. Use the error messages to help you identify any missing characters and edit your code to get it working.
}

=== Investigate

@lesson-instruction{
Turn to @opt-printable-exercise{beyond-operations-notice.adoc}. You will see two Circles of Evaluation at the top. One of them is familiar, but the other is very different from what you've been working with. Complete Part A.

@ifproglang{wescheme}{
[cols="^1,^2", grid="none", frame="none"]
|===
| @show{(coe `(* 10 -4))}	| @show{(coe `(text "Good work!" 50 "red"))}
|===
}

@ifproglang{pyret}{
[cols="^1,^2", grid="none", frame="none"]
|===
| @show{(coe `(* 10 -4))}			| @show{(coe `(text "Good work!" 50 "red"))}
| Code: @show{(code `(* 10 -4))}	| Code: @show{(code `(text "Good work!" 50 "red"))}
|===
}
}

@QandA{
@Q{What did you Notice and Wonder?}
@A{There are more than just operators like addition and subtraction! Math also has _functions_, and so does Pyret! In math, the name of the function comes first (e.g. @math{f(7)}). @ifproglang{pyret}{Pyret is no different!} +
When converting a Circle of Evaluation that has a function, the spider starts at the **top** and visits the function, then visits the inputs from left-to-right.
}
}

@lesson-instruction{
Complete Part B on @opt-printable-exercise{beyond-operations-notice.adoc}.
}

=== Synthesize

Now that we understand the structure of Circles of Evaluation, we can use them to write code for any function!
@ifproglang{pyret}{
- What's the difference between how Pyret handles Operators and Functions?	
}
- What are you curious about after what we've explored today?
- What other things could you imagine functions doing?


== Additional Exercises


If you are digging into Order or Operations and are looking for more practice with Circles of Evaluation before introducing code, we have lots of options!

* @opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fc980e05de8ae2e71174aeb?collections=5fbecc2b40d7aa0d844956f0, Matching Circles of Evaluation to Expressions}.
}
* @printable-exercise{pages/match-arith-coe.adoc} 
* @opt-printable-exercise{pages/arith-to-coe.adoc}
* @opt-printable-exercise{pages/arith-to-coe2.adoc}
* @opt-printable-exercise{pages/arith-to-coe3.adoc}
* @opt-printable-exercise{pages/coe-to-arith.adoc}
* @opt-printable-exercise{pages/coe-to-arith2.adoc}
* @opt-printable-exercise{pages/evaluate-coe.adoc}
* @opt-printable-exercise{pages/evaluate-coe2.adoc}
* @opt-printable-exercise{pages/why-not-commutative.adoc}

More practice connecting Circles of Evaluation to Code

* @opt-printable-exercise{pages/match-coe-to-code.adoc}
* @opt-printable-exercise{pages/coe-to-code.adoc}
* @opt-printable-exercise{pages/coe-to-code2.adoc}

3-column practice connecting Arithmetic Expressions with Circles of Evaluation and Code:

* @opt-printable-exercise{pages/3-column-3.adoc}
* @opt-printable-exercise{pages/3-column-4.adoc}

More 3-column practice with negatives:

* @opt-printable-exercise{pages/3-column-w-neg-5.adoc}
* @opt-printable-exercise{pages/3-column-w-neg-6.adoc}

More 3-column practice with square roots: +

* @printable-exercise{pages/3-column-challenge.adoc}
* @opt-printable-exercise{pages/3-column-w-sqrts.adoc}

3-column challenge problems with brackets and exponents:

* @opt-printable-exercise{pages/3-column-challenge-2.adoc}
* @opt-printable-exercise{pages/3-column-challenge-3.adoc}
* @opt-printable-exercise{pages/3-column-challenge-4.adoc}




