= Exploring Linearity w/Tables and Graphs

++++
<style>
.graph-table img {width: 33%;}
</style>
++++

@lesson-description{Students see tables with graphs as different representations of the same data, and explore the concept of linearity in both.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-defining-functions}
| Lesson Goals
| Students will be able to...

* match graphs to tables that represent the same data
* identify linear and non-linear graphs and tables

| Student-facing Lesson Goals
|

* I can match graphs to tables, if they display the same data
* I can tell the difference between linear and non-linear relationships in tables and graphs

| Materials
|[.materials-links]
* Lesson Slides
* @link{https://code.pyret.org/editor#share=XYZ, Graphing Starter File}
* @link{https://teacher.desmos.com/activitybuilder/custom/5fc25d458dcfcf0b92021b13, Matching Tables to Graphs (Desmos)}
@material-links

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with
* All students should log into @link{https://code.pyret.org, CPO} and open the "Graphing Starter File" they saved from the prior lesson. If they don't have the file, they can @link{https://code.pyret.org/editor#share=XYZ, open a new one}

| Key Points for the Facilitator
| This lesson is about two big ideas:

* Linear relationships, as defined by slope and y-intercept
* Matching representations of Tables and Graphs

@include{xtra/lang-prereq.adoc}
|===

== Connecting Tables with Graphs @duration{15 minutes}

=== Overview
Students consider graphs as an alternate representation of tables.

=== Launch
Take a look at the following Table and Graph:

[cols="^.^1a,^.^1a", grid="none", frame="none"]
|===
|

[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! 0
! 1 ! 2
! 2 ! 4
! 3 ! 6
! 4 ! 8
!===
| @image{images/2x.png}
|===

[.lesson-instruction]
* What do you *Notice*?
* What do you *Wonder*?

There's a definite connection between the graph and the table. Each row in the Table represents an x,y point on the graph.

[.lesson-instruction]
Can you predict the next two rows in the table? Could you extend the line on the graph? __How did you arrive at your prediction?__

[.lesson-point]
Not every table or graph has a patterm!

Take a look at the table and graph below. Can you predict the next two rows? Could you extend the line?

[cols="^.^1a,^.^1a", grid="none", frame="none"]
|===
|

[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! 13
! 1 ! -2
! 1 ! 16
! 3 ! 0
! 4 ! 54
!===
| @image{images/scatterplot.png}
|===

Sometimes there is no pattern at all! *PROTIP:* One surefire way to tell that there is no relationship between @math{x} and @math{y} is when there are two different @math{y} values for the same @math{x}.

=== Investigate
All graphs are made of points, each of which has an x- and a y-coordinate. For any graph, we can list any number of x's and their matching y's as rows in a table. 

[.lesson-instruction]
- Complete @exercise-link{pages/match-tables-graphs.adoc}.
- Complete @link{https://teacher.desmos.com/activitybuilder/custom/5fc25d458dcfcf0b92021b13, "Matching Tables to Graphs (Desmos)"}.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Pedagogy Note}

To encourage students to look at the _points_ in the table and graph, it is useful to change the scale of the graphs so that all lines look the same. This prevents students from leaning on visual cues like "steepness" to bypass the learning objective.

It can also be useful to list the points in the table __out of order__, both to focus students' attention on the points and to drive home that rows do not have to be ordered!
|===

[.lesson-point]
Axes on a graph need an order. Rows in a table don't!

The rows in a table are _discrete_, meaning they preserve their meaning if the rows are shuffled into a different order. *Some* tables represent a pattern. Ordering the rows in a table can make it easier for us to recognize patterns.

On a graph of a line, the points are _not_ discrete, and cannot be shuffled. Lines have properties that depend on order, like whether the line slopes up or down as it goes from left to right. Graphs can be stretched or squished by changing the scale of the axis. This can make the lines _look_ different, but the points will always be in the same order.

[.lesson-instruction]
- Can you match tables and graphs, even if the rows are shuffled and the axes are changed? Complete @exercise-link{pages/match-tables-graphs2.adoc}.

=== Synthesize
Tables only show us _some points_ on a line, whereas a line itself is made up of an _infinite_ number of points. When a table represents a _sample_ of some larger trend, the graph is a way of seeing the trend itself.

== Linear vs. Non-linear

=== Overview
Students explore the concept of linearity, identifying properties like @vocab{slope} (or @vocab{rate}) and @vocab{y-intercept} in both tables and graphs.

=== Launch

Look at the six graphs shown below.

[.graph-table, stripes="none", frame="none"]
|===
| @image{images/constant-linear.png} 
  @image{images/num-abs.png}
  @image{images/num-sqrt.png}

| @image{images/negative-linear.png}
  @image{images/positive-linear.png}
  @image{images/num-sqr.png}
|===

What do you *Notice?*

What do you *Wonder?*

Three of the graphs above are *straight lines* (called "linear") and three are not ("nonlinear"). As we can see, the linear graphs can be perfectly horizontal, tilt upwards and to the right, or tilt downwards to the right. 

[.lesson-point]
Linear relationships are always a straight line.

Each of these linear relationships has two properties. First, they all increase at a consistent @vocab{rate} - @vocab{slope} - increasing or decreasing by the same amount. Second, they also have a @vocab{y-intercept}: the y-value when x = 0 ("intercepts" the y-axis).

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Pedagogy Note}

There is nothing "magical" about the @vocab{y-intercept}! It's just a convention that mathematicians use, since graphs don't have a "starting value". They could have arbitrarily picked some other point, like "the point where the line crosses -2735.1", and the only change to the way we teach linear functions would be a vocabulary word!
|===

Look at the six "sideways" data tables below. Each of the "y" columns shows a pattern. You can think of the "x" column as counting the __order in which the y-values appear__ (1st value, 2nd value, etc).

[cols="^.^1a,^.^1a", frame="none"]
|===
|

[.sideways-pyret-table]
!===
! x ! 1 ! 2 ! 3 ! 4 ! 5
! y ! 2 ! 3 ! 4 ! 5 ! 6
!===
|

[.sideways-pyret-table]
!===
! x ! 1 ! 2 ! 3 !  4 !  5
! y ! 1 ! 4 ! 9 ! 16 ! 25
!===

|

[.sideways-pyret-table]
!===
! x !  1 !  2 !  3 !  4 !  5
! y ! 12 ! 14 ! 16 ! 18 ! 20
!===

|

[.sideways-pyret-table]
!===
! x ! 1 ! 2 ! 3 ! 4 !  5
! y ! 3 ! 3 ! 3 ! 3 ! 3
!===

|

[.sideways-pyret-table]
!===
! x !  1 !  2 !   3 !   4 !  5
! y ! 84 ! 94 ! 104 ! 114 ! 124
!===

|

[.sideways-pyret-table]
!===
! x !  1 !  2 !   3 !   4 !  5
! y ! 84 ! 94 ! 104 ! 114 ! 124
!===

|===

* What do you *Notice?*
* What do you *Wonder?*
* Can you figure out what the next x,y pair should be for each of them?  
* Can you guess what the y-value for each table would be when x is 0?

When there is a @vocab{linear} relationship, the values in a table increase at a _consistent rate_ and the graph of those values will all fall on a straight line.

*Note:* Rows in a table don't have to be ordered! You may have to _sort_ the rows first in order to see the pattern emerge. 

For example, the pattern in this table is unclear.

[.sideways-pyret-table]
|===
| x | 3 | 2 | 4 | 0 | 1
| y | 6 | 4 | 8 | 0 | 2
|===

{empty}

But when we reorder the x values from least to greatest, we can quickly identify that for every 1 that x increases, y increases by 2.

{empty}

[.sideways-pyret-table]
|===
| x | 0 | 1 | 2 | 3 | 4
| y | 0 | 2 | 4 | 6 | 8
|===

Sometimes it can also be difficult to see patterns in tables when they are missing rows.  For example, in the table below if we just looked at the y-values we might think there is not a pattern because the value goes down by 6, then 2, then 2 and then 4... 

[.sideways-pyret-table]
|===
| x | -4 |-1  | 0  | 1  | 3
| y | 20 | 14 | 12 | 10 | 6
|===

If we fill in the missing x-values... and find a pattern by which to fill in the y-values...

[.sideways-pyret-table]
|===
| x | -4 | -3 | -2 | -1 | 0  | 1  | 2 | 3
| y | 20 | 18 | 16 | 14 | 12 | 10 | 8 | 6
|===

...the table reveals that the y-values are decreasing by 2 for each x.

Another way of thinking about this would be to look at how the x and y change __in proportion__ to each other. When x increased by 3, y decreased by 6. When x increased by 1, y decreased by 2. When x increased by 2, y decreased by 4. The y value decreased by twice as much as the x value increased no matter how much x changed by, so the slope of the line that would connect these points on a graph would be -2.

== Investigate
Can you identify the slope and y-intercept of a linear relationship in a table? In a graph?

- Complete @exercise-link{slope-and-y-tables.adoc}
- Complete @exercise-link{slope-and-y-graphs.adoc}

[.lesson-point]
The graph of a linear relationship will always appear as a straight line.  An ordered table of values for any linear relationship will reveal a constant rate of change.

- Complete @exercise-link{linear-nonlinear-bust.adoc, "Linear, Non-Linear or Bust?"}

=== Synthesize

Data has a "shape", and this shape can emerge when we look for patterns in that data. A linear, straight-line relationship is one kind of shape, and it shows up when we view that data as a table or a graph. But tables and graphs take a long time to draw/describe! Fortunately, there's a way to encode this relationship using _mathematical symbols_, either as equations or functions...

== Additional Exercises:

