= Using Table Methods

@lesson-description{Students learn about _table methods_, which allow them to order, filter, and extend the animals table.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-questions-and-value-defs}
|Product Outcomes
|Students will be able to:

* order the animals dataset by a number of criteria
* filter the animals dataset by gender, fixed status, and age

@worksheet-include{xtra/lang-prereq.adoc}
|===

== Reviewing Function Definitions (15 minutes)

Students have already learned to use the `.row-n` method to extract an individual row of the animals table. This lesson introduces other methods, having students experiment with them before trying to explain what they do and how they work.

[.lesson-instruction]
* Load the *shared file*, and click "Run". 
* Look over at the Definitions Area. What functions do you see defined here?
* Type `is-fixed(animalA)` into the Interactions Area. What did you get?
* Type `is-fixed(animalB)` into the Interactions Area. What did you get?
* What does the `is-fixed` function do?
* Type `gender(animalA)` into the Interactions Area. What did you get?
* Type `gender(animalB)` into the Interactions Area. What did you get?
* What does the `gender` function do?
* Type `is-young(animalA)` into the Interactions Area. What did you get?
* Type `is-young(animalB)` into the Interactions Area. What did you get?
* What does the `is-young` function do?
* Type `is-cat(animalA)` into the Interactions Area. What did you get?
* Type `is-cat(animalB)` into the Interactions Area. What did you get?
* What does the `is-cat` function do?

== Ordering Tables (10 minutes)

Find the contract for `.order-by` in your contracts page. The `.order-by` method consumes a String (the name of the column you want to order) and a Boolean (true for ascending, false for descending). But what does it produce?

[.lesson-instruction]
* Type `animals-table.order-by("name", true)` into the Interactions Area. What do you get?
* Type `animals-table.order-by("age", false)` into the Interactions Area. What do you get?
* What is the Domain of `.order-by`? What is the Range? Find the contract for this method in your contracts table, and make sure it makes sense!

== Filtering and Building (25 minutes)

You've already seen expressions like `animals-table.row-n(..)` and `animals-table.order-by(...)`. But suppose you want to get a table of only animals that have been fixed? 

[.lesson-instruction]
* Find the contract for `.filter` in your contracts page. 
* The `.filter` method is taking in a _function_. What is the contract for that function? Where have you seen functions-taking-functions before?
* Try typing `animals-table.filter(is-fixed)` into the Interactions Area.
* Try typing `animals-table.filter(is-cat)` into the Interactions Area. 
* What do you get? What do you think is going on?
* Try typing `animals-table.filter(gender)`. What happens?

The `.filter` method walks through the table, applying whatever function it was given to each row, and producing a new table containing all the rows for which the function returned `true`. In this case, we gave it the is-fixed function, so the new table had only rows for fixed animals. Notice that the Domain for `.filter` says that test must be a function (that’s the arrow), which consumes a `Row` and produces a `Boolean`. If it consumes anything besides a single `Row`, or if it produces anything else besides a `Boolean`, we'll get an error.

[.lesson-instruction]
* Find the contract for `.build-column` in your contracts page. The `.build-column` method is taking in a _function_ and a _string_. What is the contract for that function? 
* Try typing `animals-table.build-column("young", is-young)` into the Interactions Area. 
* What do you get? What do you think is going on?

The `.build-column` method walks through the table, applying whatever function it was given to each row. Whatever the function produces for that row becomes the value of our new column, which is named based on the string it was given. In this case, we gave it the is-young function, so the new table had an extra Boolean column for every animal, indicating whether or not it was young. Notice that the Domain for `.build-column` says that the builder must be a function which consumes a `Row` and produces some other value. If it consumes anything besides a single `Row`, we'll get an error.

== Closing (Time 5 minutes)

Congratulations! 

== Additional Exercises:

- TODO