= Table Methods

@lesson-description{Students learn about _table methods_, which allow them to order, filter, and extend the animals table.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-questions-and-value-defs}
| Lesson Goals
| Students will be able to...

* order the animals dataset by a number of criteria
* filter the animals dataset by gender, fixed status, and age

| Student-Facing Lesson Goals
| I can...
* order the animals dataset by any column
* filter the animals dataset

| Materials
|
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|

| Relevant Standards
|
@worksheet-include{xtra/lang-prereq.adoc}
|===

== Review Function Definitions (15 minutes)

[.lesson-instruction]
* Load the *shared file*, and click "Run". 
* Look over at the Definitions Area. What functions do you see defined here?
* Type `is-fixed(animalA)` into the Interactions Area. What did you get?
* Type `is-fixed(animalB)` into the Interactions Area. What did you get?
* What does the `is-fixed` function do?
* Type `gender(animalA)` into the Interactions Area. What did you get?
* Type `gender(animalB)` into the Interactions Area. What did you get?
* What does the `gender` function do?
* Type `is-young(animalA)` into the Interactions Area. What did you get?
* Type `is-young(animalB)` into the Interactions Area. What did you get?
* What does the `is-young` function do?
* Type `is-cat(animalA)` into the Interactions Area. What did you get?
* Type `is-cat(animalB)` into the Interactions Area. What did you get?
* What does the `is-cat` function do?

== Ordering Tables (10 minutes)

=== Overview
Students learn a second table method, which allows them to order columns in ascending or descending order.

=== Launch
Have students find the contract for `.order-by` in their contracts pages. The `.order-by` method consumes a String (the name of the column by which we want to order) and a Boolean (true for ascending, false for descending). But what does it produce?

=== Student-Facing Task Assessment
[.lesson-instruction]
* Type `animals-table.order-by("name", true)` into the Interactions Area. What do you get?
* Type `animals-table.order-by("age", false)` into the Interactions Area. What do you get?
* Sort the animals table from heaviest-to-lightest.
* Sort the animals table alphabetically by species.
* Sort the animals table so that fixed and unfixed animals are grouped together.
* Sort the animals table by how long it took for each animal to be adopted, in ascending order.

== Collect
Answer any questions students may have. Class discussion: what do `.order-by` and `.row-n` have in common? How are they different?

== Filtering and Building (25 minutes)

=== Overview
Students learn how to _transform_ tables, by filtering out rows and adding new columns.

=== Launch
Suppose we want to get a table of only animals that have been fixed? Have students find the contract for `.filter` in their contracts pages. The `.filter` method is taking in a _function_. What is the contract for that function? Where have we seen functions-taking-functions before?

[.lesson-instruction]
* Try typing `animals-table.filter(is-fixed)` into the Interactions Area.
* Try typing `animals-table.filter(is-cat)` into the Interactions Area. 
* What do you get? What do you think is going on?
* Try typing `animals-table.filter(gender)`. What happens?

The `.filter` method walks through the table, applying whatever function it was given to each row, and producing a new table containing all the rows for which the function returned `true`. In this case, we gave it the is-fixed function, so the new table had only rows for fixed animals. Notice that the Domain for `.filter` says that test must be a function (that’s the arrow), which consumes a `Row` and produces a `Boolean`. If it consumes anything besides a single `Row`, or if it produces anything else besides a `Boolean`, we'll get an error.

Suppose we want to _transform_ our table, converting `pounds` to `kilograms` or `weeks` to `days`. Or perhaps we want to add a "cute" column that just identifies the puppies and kittens? Have students find the contract for `.build-column` in their contracts pages. The `.build-column` method is taking in a _function_ and a _string_. What is the contract for that function? 

[.lesson-instruction]
* Try typing `animals-table.build-column("young", is-young)` into the Interactions Area. 
* What do you get? What do you think is going on?

The `.build-column` method walks through the table, applying whatever function it was given to each row. Whatever the function produces for that row becomes the value of our new column, which is named based on the string it was given. In this case, we gave it the is-young function, so the new table had an extra Boolean column for every animal, indicating whether or not it was young. Notice that the Domain for `.build-column` says that the builder must be a function which consumes a `Row` and produces some other value. If it consumes anything besides a single `Row`, we'll get an error.

=== Collect
TODO

== Additional Exercises:

- TODO