= Reading Histograms

@vspace{1ex}

Students watched 5 videos, and rated them on a scale of 1 to 10. While the *average score* for every video is the same (5.5), the *shapes* of the ratings distributions were very different! _Match_ the summary description (left) with the _shape_ of the histogram of student ratings (right). For each histogram, *the x-axis is the score, and the y-axis is the number of students who gave it that score*. These axes are intentionally unlabeled - focusing on the _shape_ is what matters here!

[cols=">.^7a,^.^1a,5,^.^1a,.^7a",stripes="none",grid="none",frame="none"]
|===
| Most of the students were fine
with the video, but a couple of
them gave it an unusually low
rating.
| *1*||*A*
| @centered-image{histogram-a.png, "", 200}

| Most of the students were okay
with the video, but a couple
students gave it an unusually
high rating.
| *2*||*B*
| @centered-image{histogram-b.png, "", 200}

| Students tended to give the
video an average rating, and
they weren't likely to stray far
from the average.
|*3*||*C*
| @centered-image{histogram-c.png, "", 200}

| Students either really liked or
really disliked the video.
|*4*||*D*
| @centered-image{histogram-d.png, "", 200}

| Reactions to the video were all
over the place: high ratings
and low ratings and inbetween ratings were all
equally likely.
|*5*||*E*
| @centered-image{histogram-e.png, "", 200}

|===
