= Inequalities -- Launch

@vspace{3ex}

What would each of the following expressions evaluate to? Write your guesses in the space provided, and then take turns typing them into the computer.

[cols="1a,1a"]
|===
|1) `1 + 4` will be @fitb{4ex}{5}
|2) `0 > 5` will be @fitb{4ex}{true}
|3) `4 / 2` will be @fitb{4ex}{2}
|4) `1 = 9` will be @fitb{4ex}{false}
|5) `0 - 9` will be @fitb{4ex}{-9}
|6) `2 <= 2` will be @fitb{4ex}{true}
|7) `(string-length "bat")` will be @fitb{4ex}{3}
|8) `(string=?" dog" "cat")` will be @fitb{4ex}{false}
|===

@vspace{5ex}

9) What does the function `<` do?

@vspace{1ex}
__it takes in two inputs, and returns true if the first one is less than the second__

@vspace{5ex}

10) What does the function @show{(sexp->code `string=?)} do?

@vspace{1ex}
__it takes in two Strings, and returns true if they are exactly the same__

@vspace{5ex}

11) Write the contract for these Boolean functions in your Contracts page.

@vspace{5ex}

12) How many Numbers are there in the entire universe? @fitb{15ex}{infinite}

@vspace{5ex}

13) How many Strings are there in the entire universe? @fitb{15ex}{infinite}

@vspace{5ex}

14) How many Images are there in the entire universe? @fitb{15ex}{infinite}

@vspace{5ex}

15) How many Booleans are there in the Universe? @fitb{4ex}{false}

@vspace{3ex} 
What are they?

@vspace{1ex}
__true and false__
