= Inequalities -- Launch

How many Numbers are there in the entire universe? @fitb{15ex}{}

@vspace{5ex}

How many Strings are there in the entire universe? @fitb{15ex}{}

@vspace{5ex}

How many Images are there in the entire universe? @fitb{15ex}{}

@vspace{5ex}



What would each of the following expressions evaluate to?

[cols="1a,1a"]
|===
| `(+ 1 4)` will be @fitb{4ex}{5}
| `(> 0 5)` will be @fitb{4ex}{false}
| `(/ 4 2)` will be @fitb{4ex}{2}
| `(= 1 9)` will be @fitb{4ex}{false}
| `(- 0 9)` will be @fitb{4ex}{-9}
| `(<= 2 2)` will be @fitb{4ex}{true}
| `(string-length "bat")` will be @fitb{4ex}{3}
| `(string=? "dog" "cat")` will be @fitb{4ex}{false}
|===

@vspace{5ex}

{}1. What does the function `<` do?

@vspace{1ex}
Takes two Numbers and compares them, returns `true` if the first
Number is less than the second Number, otherwise returns `false`.
@vspace{5ex}

{}2. What does the function `string=?` do?

@vspace{1ex}
Takes in two Strings and compares them, returns `true` if the
Strings are exactly identical, otherwise returns `false`.
@vspace{5ex}

{}3. How many Booleans are there in the Universe? @fitb{4ex}{2}

@vspace{1ex}
What are they?

@vspace{1ex}
`true` and `false`


