= Regression Analysis in Your Dataset

@vspace{1ex}

*My Dataset is* @fitb{92ex}.

@vspace{1ex}

1) I performed a linear regression on @fitbruby{65ex}{}{dataset or subset} and found 

@vspace{1ex}

@fitbruby{83ex}{}{a weak/strong/moderate (R=...), positive/negative} correlation between 

@vspace{1ex}

@fitbruby{46ex}{}{[x-axis]} and @fitbruby{46ex}{}{[y-axis]}. 

@vspace{1ex}

I would predict that a 1 @fitbruby{25ex}{}{[x-axis units]} increase in @fitbruby{30ex}{}{[x-axis]} is associated with a 

@vspace{1ex}

@fitbruby{32ex}{}{[slope, y-units]} @fitbruby{32ex}{}{[increase/decrease]} in @fitbruby{31ex}{}{[y-axis]}.

@vspace{5ex}
@span{.sectionbreak}{}
@vspace{1ex}

2) I performed a linear regression on @fitbruby{65ex}{}{dataset or subset} and found 

@vspace{1ex}

@fitbruby{80ex}{}{a weak/strong/moderate (R=...), positive/negative} correlation between 

@vspace{1ex}

@fitbruby{47ex}{}{[x-axis]} and @fitbruby{47ex}{}{[y-axis]}. 

@vspace{1ex}

I would predict that a 1 @fitbruby{25ex}{}{[x-axis units]} increase in @fitbruby{30ex}{}{[x-axis]} is associated with a 

@fitbruby{32ex}{}{[slope, y-units]} @fitbruby{32ex}{}{[increase/decrease]} in @fitbruby{32ex}{}{[y-axis]}.

@vspace{5ex}
@span{.sectionbreak}{}
@vspace{1ex}

3) I performed a linear regression on @fitbruby{65ex}{}{dataset or subset} and found 

@vspace{1ex}

@fitbruby{80ex}{}{a weak/strong/moderate (R=...), positive/negative} correlation between 

@vspace{2ex}

@fitbruby{47ex}{}{[x-axis]} and @fitbruby{47ex}{}{[y-axis]}. 

@vspace{1ex}

I would predict that a 1 @fitbruby{25ex}{}{[x-axis units]} increase in @fitbruby{30ex}{}{[x-axis]} is associated with a 

@vspace{1ex}

@fitbruby{32ex}{}{[slope, y-units]} @fitbruby{32ex}{}{[increase/decrease]} in @fitbruby{30ex}{}{[y-axis]}.
