= Identifying Threats to Validity

_The animal shelter wanted to find out what kind of food to buy for their animals. They took a random sample of two animals and the food they eat, and they found that spider and rabbit food was by far the most popular cuisine!_

@vspace{5ex}

Explain why sampling just two animals can result in unreliable conclusions about what kind of food is needed.

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@vspace{10ex}
_A volunteer opens the shelter in the morning and walks all the dogs. At mid-day, another volunteer feeds all the dogs and walks them again. In the evening, a third volunteer walks the dogs a final time and closes the shelter. The volunteers report that the dogs are much friendlier and more active at mid-day, so the shelter staff assume the second volunteer must be better with animals than the others._

@vspace{5ex}

What are some possible threats to the validity of this conclusion?

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}
