= Slope & Y-Intercept from Tables (Intro)

[.center]
--
*slope (rate)*: _how much y changes as x-increases by 1_

*y-intercept*: _the y-value when @math{x = 0}_
--

[.sideways-pyret-table]
|===

| x | -1 | 0 | 1 | 2 | 3 | 4
| y | -1 | 1 | 3 | 5 | 7 | 9
|===

@n Compute the slope: . @fitb{}{}

@n Identify the @vocab{y-intercept}:  @fitb{}{}

@n What strategies did you use to compute the slope and y-intercept?

@fitb{}{}

@fitb{}{}

@vspace{1ex}

The slope and y-intercept in this table are harder to find, because the x-values don't go up by 1 and we can't see a value for @math{x = 0}. *Try filling in the points that have been skipped to identify the slope and y-intercept.*

[.sideways-pyret-table]
|===

| x |  2 | 5 | 8  | 11
| y |  3 | 9 | 15 | 21
|===

@n slope: @fitb{}{}

@n y-intercept: @fitb{}{}

@vspace{1ex}

The slope and y-intercept in this table are even harder to find, because the x-values are out of order!

*Let's learn how to calculate the slope and y-intercept from any two points!* Be sure to write down your calculations!

[.sideways-pyret-table]
|===

| x | 3 | 20 | 5  |  9 | 1
| y | 5 | 56 | 11 | 23 | -1
|===

@n Slope: @fitb{}{}

@n Y-intercept: @fitb{}{}

