= Computation (Whole Numbers)

++++
<style>
div.circleevalsexp { width: auto; }

/* Make autonums inside tables look consistent with those outside */
table .autonum::after { content: ')' !important;}

/* for table cells with immediate .content children, which have immediate
 * .paragraph children: use flex to space them evenly and center vertically
*/
td > .content > .paragraph {
  display: flex;
  align-items: center;
  justify-content: space-around;
}
</style>
++++


@do{
  (define coe1a '(- (* 16 2) (+ 2 9)))
  (define coe1b '(- (?ANS 32) (?ANS 11)))
  (define coe2a '(+ (?ANS 6) (/ 50 10)))
  (define coe2b '(+ 6 (?ANS 5)))
  (define coe3a '((?ANS /) (+ (?ANS 25) 23) ((?ANS +) 5 3)))
  (define coe3b '(/ 48 (?ANS 8)))
  (define coe4a '((?ANS *) ((?ANS +) 4 (- 9 (?ANS 8))) (?ANS 5)))
  (define coe4b '(* (+ (?ANS 4) 1) 5))
  (define coe4c '((?ANS *) (?ANS 5) (?ANS 5)))
  (define coe5a '((?ANS -) (* 6 4) (/ (+ (?ANS 9) 6) 5)))
  (define coe5b '((?ANS -) (?ANS 24) (/ 15 5)))
  (define coe5c '(- (?ANS 24) (?ANS 3)))
  (define coe6a '((?ANS *) ((?ANS +) (?ANS 6) ((?ANS -) (?ANS 20) 15)) (+ 5 (* (?ANS 2) 2))))
  (define coe6b '((?ANS *) (+ 6 5) ((?ANS +) 5 4)))
  (define coe6c '((?ANS *) 11 (?ANS 9)))
}


The Circles of Evaluation below represent a step-by-step computation, which results in an answer. Some of the steps are missing numbers and operators! Fill in those numbers and operators so that each sequence of circles will end with the answer shown on the right.

[.FillVerticalSpace, cols="^.^1a,.^14a,stripes="none", options="header"]
|===
|    | Circle Solving Diagram
| @n | @show{(coe coe1a)} &rarr; @show{(coe coe1b)} &rarr; @math{21}
| @n | @show{(coe coe2a)} &rarr; @show{(coe coe2b)} &rarr; @math{11}
| @n | @show{(coe coe3a)} &rarr; @show{(coe coe3b)} &rarr; @math{6}
| @n | @show{(coe coe4a)} &rarr; @show{(coe coe4b)} &rarr; @show{(coe coe4c)} &rarr; @math{25}
| @n | @show{(coe coe5a)} &rarr; @show{(coe coe5b)} &rarr; @show{(coe coe5c)} &rarr; @math{21}
| @n | @show{(coe coe6a)} &rarr; @show{(coe coe6b)} &rarr; @show{(coe coe6c)} &rarr; @math{99}
|===


