= Computation (Whole Numbers) (2)

++++
<style>
div.circleevalsexp { width: auto; }

/* Make autonums inside tables look consistent with those outside */
table .autonum::after { content: ')' !important;}

/* for table cells with immediate .content children, which have immediate
 * .paragraph children: use flex to space them evenly and center vertically
*/
td > .content > .paragraph {
  display: flex;
  align-items: center;
  justify-content: space-around;
}

tr span.arrow::before {
  content: 'Comp';
}

</style>
++++


@do{
  (define coe1a '(- (* 5 4) (+ 3 7)))
  (define coe1b '(- (?ANS 20) (?ANS 10)))

  (define coe2a '(- (* 7 2) (+ 5 6)))
  (define coe2b '(- (?ANS 14) (?ANS 11)))

  (define coe3a '(+ (?ANS 25) (/ 30 5)))
  (define coe3b '(+ 25 (?ANS 6)))

  (define coe4a '(+ (?ANS 1) (/ 12 4)))
  (define coe4b '(+ 1 (?ANS 3)))

  (define coe5a '((?ANS /) (+ (?ANS 10) 8) (+ 3 6)))
  (define coe5b '(/ 18 (?ANS 9)))

  (define coe6a '((?ANS -) (+ (?ANS 9) 12) (+ 5 6)))
  (define coe6b '(- 21 (?ANS 11)))
}


The Circles of Evaluation below represent a step-by-step computation ("Comp"), which results in an answer. Some of the steps are missing numbers and operators! Fill in those numbers and operators so that each sequence of circles will end with the answer shown on the right.

[.FillVerticalSpace, cols="^.^1a,.^14a,stripes="none", options="header"]
|===
|    | Circle Solving Diagram
| @n | @show{(coe coe1a)} @arrow @show{(coe coe1b)} @arrow @math{10}
| @n | @show{(coe coe2a)} @arrow @show{(coe coe2b)} @arrow @math{3}
| @n | @show{(coe coe3a)} @arrow @show{(coe coe3b)} @arrow @math{31}
| @n | @show{(coe coe4a)} @arrow @show{(coe coe4b)} @arrow @math{4}
| @n | @show{(coe coe5a)} @arrow @show{(coe coe5b)} @arrow @math{2}
| @n | @show{(coe coe6a)} @arrow @show{(coe coe6b)} @arrow @math{10}
|===


