#!/bin/bash

f="$1"

fd=$(dirname $f)

if test "$fd" = "."; then fd=""
else fd="$fd/"
fi

fb=$(basename $f)

fe=${fb##*.}

if test "$fe" = "$fb"; then fe=""
else fe=".$fe"
  fb=$(basename $fb $fe)
fi

fbb=$(echo $fb|git hash-object --stdin|sed -e 's/^\(.\{16\}\).*/\1/')

anonf="$fd$fbb$fe"

if test -f "$anonf"; then
  if test -f "$f"; then
    mv "$f" "$anonf"
  fi
  echo "$anonf"
elif test -f "$f"; then
  mv "$f" "$anonf"
  echo "$anonf"
fi
