#!/bin/bash

BROKEN_EXTERNAL_LINKS=

for f in "$@"; do
  # echo checking external link $f
  invalid=
  # possible alternative? wget -q --spider $f
  curl -Is $f > .temp.txt

  if test ! -s .temp.txt; then
    invalid=1
  elif ! cat .temp.txt|head -n 1|grep -q 302; then
    :
  elif cat .temp.txt|head -n 1|grep -q 200; then
    if cat .temp.txt|grep -q '^Connection: close'; then
      invalid=1
    fi
  fi

  rm .temp.txt

  if test $invalid; then
    BROKEN_EXTERNAL_LINKS=1
    echo
    echo WARNING: Invalid external link $f
  fi

done

if test $BROKEN_EXTERNAL_LINKS; then
  echo 👎 Broken external links found
else
  echo 👍 No broken external links found
fi
