#lang racket

#| REMEMBER TO ADD ALL ENTRIES AND BIG CHANGES TO SPANISH GLOSSARY |#

(provide *glossary-list*)

#|
Glossary for terminology used in the notes.  The first entry of each entry can be either
a single string or a list of keys that map to the same definition.

If a list of keys is provided, the generated glossary will use the first in the list
when it prints out the glossary for a particular unit
|#

(define *glossary-list*
  '(

    ((en-us "accessor functions" "functions to extract values from a data structure")
     (es-mx "funciones de acceso" "funciones para extraer valores de una estructura de datos"))

    ((en-us "apply" "use a given function on some inputs")
     (es-mx "aplicando" "use una función dada en algunas entradas"))

    ((en-us ("argument" "arguments") "the inputs to a function; expressions for arguments follow the name of a function")
     (es-mx ("argumento" "argumentos") "las entradas de una función, las expresiones de los argumentos siguen el nombre de una función"))

    ((en-us "ascending" "an order in which lower values appear first, and higher values appear after")
     (es-mx "ascendente" "un orden de valores en lo cual los más bajos aparecen primero y los más grandes aparecen después"))

    ((en-us ("bar chart" "bar charts") "a display of categorical data that uses bars positioned over category values; each bar’s height reflects the count or percentage of data values in that category"))
    ((en-us ("bin" "bins") "a range that values from a dataset can belong to; there is one bar in a histogram per bin"))
    ((en-us "Boolean" "a type of data with two values: true and false"))
    ((en-us ("box plot" "box plots") "the box plot (a.k.a. box-and whisker-plot) is a way of displaying a distribution of data based on the five-number summary: minimum, first quartile, median, third quartile, and maximum"))
    ((en-us ("calling" "calls") "using a function by giving it inputs"))
    ((en-us ("category" "categories") "the set of possible values that a value in a categorical dataset can have"))
    ((en-us "categorical data" "data whose values are qualities that are not subject to the laws of arithmetic."))
    ((en-us ("circle of evaluation" "circles of evaluation") "a 'sentence diagram' of the structure of a mathematical expression"))
    ((en-us "clause" "a question and its corresponding answer in a conditional expression"))
    ((en-us ("chart" "charts") "visual reprsentations of how values in a dataset are distributed"))
    ((en-us ("column" "columns") "set of values in a table of a particular type.  Every row has exactly 1 element in every column"))
    ((en-us ("combination" "combinations") "the number of possible arrangements in a collection of items where the order of the selection does NOT matter. (ABC and CBA would be considered the same combination)"))
    ((en-us "conditional" "a code expression made of questions and answers"))
    ((en-us "constructor" "a function that creates instances of a data structure"))
    ((en-us ("contract" "contracts") "a statement of the name, domain, and range of a function"))
    ((en-us ("contract error" "contract errors") "errors where the code makes sense, but uses a function with the wrong number or type of arguments"))
    ((en-us ("coordinate" "coordinates") "a number or set of numbers describing an object's location"))
    ((en-us "coordinate plane" "a grid formed by a pair of intersecting horizontal and vertical number lines"))
    ((en-us ("correlation" "correlations") "a single number somewhere between -1 and +1 that reports the direction and strength of the linear relationship between two quantitative variables (also known as the r-value)"))
    ((en-us "data block" "code that lists the name, constructor(s), and field(s) of a data structure"))
    ((en-us ("data row" "data rows") "a structured piece of data in a dataset that typically reports all the information gathered about a given individual"))
    ((en-us "data science" "the science of collecting, organizing, and drawing general conclusions from data, with the help of computers"))
    ((en-us ("dataset" "datasets") "a collection of related information that is composed of separate elements, but can be manipulated as a unit by a computer"))
    ((en-us "data structure" "a datatype which packages several datatypes as fields"))
    ((en-us ("data types" "data type") "a way of classifying values, such as: Number, String, Image, Boolean, or any user-defined data structure"))
    ((en-us "debug" "to find and fix errors in one's code"))
    ((en-us "define" "to associate a descriptive name with a value"))
    ((en-us "definitions area" "the left-most text box in the Editor where definitions for values and functions are written"))
    ((en-us "descending" "an order in which higher values appear first, and lower values appear after"))
    ((en-us "design recipe" "a sequence of steps that helps people document, test, and write functions"))
    ((en-us "direction" "of a relationship between two quantitative variables: whether they tend to increase together, or if as one goes up the other tends to go down"))
    ((en-us "domain" "the type or set of inputs that a function expects"))
    ((en-us "dot accessor" "a way to extract the values of fields an instance"))
    ((en-us "driver" "in pair programming, the person who is doing the typing"))
    ((en-us ("edge" "edges") "the line segments where the faces of solid figures meet in each of the three dimensions."))
    ((en-us "editor" "software in which you can write and evaluate code"))
    ((en-us ("entry" "entries") "a single value in a table, belonging to a particular row and column"))
    ((en-us ("error message" "error messages") "information from the computer about errors in code"))
    ((en-us "evaluate" "perform the computation in an expression, producing an answer"))
    ((en-us "evaluates to" "the result of computing an expression"))
    ((en-us "event" "something that happens outside of a running program, which the program can respond to"))
    ((en-us "event-based programming" "a style of programming in which every functions are written to respond to mouse-clicks, keypresses, etc."))
    ((en-us "example" "shows the use of a function on specific inputs and the computation the function should perform on those inputs"))
    ((en-us "examples block" "code that lists examples starting with 'examples:' and ends with 'end'"))
    ((en-us ("explanatory variable" "explanatory") "the variable in a relationship that is presumed to impact the other variable"))
    ((en-us "expression" "a computation written in the rules of some language (such as arithmetic, code, or a Circle of Evaluation)"))
    ((en-us ("extend" "extending" "extends") "a table query that creates a table with new column(s), whose entries are computed with an expression"))
    ((en-us "extract" "to construct a list using data from a particular column in a table"))
    ((en-us ("face" "faces") "the shapes on the outside of a figure"))
    ((en-us "field" "a part of a data structure that has a name and holds a single value of a specified datatype"))
    ((en-us "form" "of a relationship between two quantitative variables: whether the two variables together vary linearly or in some other way"))
    ((en-us ("frequency bar chart" "frequency bar charts") "a bar chart in which each the length of each bar corresponds to the frequency of a particular value"))
    ((en-us ("function" "functions") "a mathematical object that consumes inputs and produces an output"))
    ((en-us "function block" "code that names a function, lists its variables, and states the expression to compute when the function is used"))
    ((en-us "function definition" "code that names a function, lists its variables, and states the expression to compute when the function is used")(("frequency" "frequencies") "how often a particular value appears in a dataset"))
    ((en-us ("grouped sample" "grouped samples") "a non-random subset of individuals chosen from a larger set, where the individuals belong to a specific group"))
    ((en-us "handler" "Connects an event (like a tick or keypress) and a function within a reactor"))
    ((en-us ("header" "header row" "headers" "header rows") "the titles of each column of a table, usually shown at the top"))
    ((en-us "helper function" "a small function that handles a specific part of another computation, and gets called from other functions"))
    ((en-us ("histogram" "histograms") "a display of quantitative data that uses vertical bars positioned over bins (sub-intervals); each bar’s height reflects the count or percentage of data values in that bin."))
    ((en-us ("horizontal axis" "x-axis") "axis on a coordinate plane that runs from left to right"))
    ((en-us "hypotenuse" "the side opposite the 90-degree angle in a right triangle"))
    ((en-us "identifier column" "a column of unique values which identify all the individual rows (e.g. - student IDs, SSNs, etc)"))
    ((en-us "image" "a type of data for pictures"))
    ((en-us "instance" "a specific, packaged value of a data structure that contains other values in its fields"))
    ((en-us "interactions area" "the right-most text box in the Editor, where expressions are entered to be evaluated"))
    ((en-us ("interquartile range" "IQR") "(IQR) is one possible measure of spread, based on dividing a dataset into four parts. The values that divide each part are called the first quartile (Q1), the median, and third quartile (Q3). IQR is calculated as Q3 minus Q1."))
    ((en-us ("intersection" "intersections") "the set of values that makes both inequalities true"))
    ((en-us "legal expression" "code that follows the Code Rules for a language"))
    ((en-us ("library" "libraries") "a collection of functions that can be made available to our program by using include"))
    ((en-us ("linear" "linear relationship") "a rule that computes one quantity from another, which can be graphed as straight line or written as a sequence of numbers that change at a constant rate"))
    ((en-us "linear regression" "modeling the relationship between two quantitative variables using a straight line"))
    ((en-us ("line of best fit" "lines of best fit" "regression line" "regression lines") "summarizes the relationship (if linear) between two quantitative variables"))
    ((en-us ("list" "lists") "a data structure containing a sequence of values"))
    ((en-us "mathematical expression" "a computation using the rules of arithmetic"))
    ((en-us ("mean" "average") "a representation of the center, or 'typical' value in a set of numbers, calculated as the sum of those numbers divided by the number of values."))
    ((en-us "median" "the middle element of a quantitative dataset"))
    ((en-us "method" "a function that is only associated with an instance of a datatype, which consumes inputs and produces an output based on that instance"))
    ((en-us ("mode" "modes") "the most commonly appearing categorical or quantitative value or values in a dataset"))
    ((en-us "name" "how we refer to a function or value defined in a language (examples: +, *, star, circle)"))
    ((en-us "navigator" "in pair programming, the person who has their eyes on the screen helping the driver"))
    ((en-us "negative correlation" "relationship in which one variable increases as the other decreases, and vice versa"))
    ((en-us "nonlinear" "an pattern that is not a straight line when it is graphed"))
    ((en-us ("normal" "normal distribution") "A normal distribution has a particular symmetric shape that bulges in the middle and tapers at the ends."))
    ((en-us "number" "a data type representing a real number"))
    ((en-us ("operator" "operators") "a symbol that manipulates two Numbers and produces a result"))
    ((en-us ("order" "orders" "ordering") "an arrangement of data according to some pattern"))
    ((en-us ("outlier" "outliers") "a data point that is unusually far above or below most of the others"))
    ((en-us ("permutation" "permutations") "the number of possible arrangements in a collection of items where the order of the selection matters (ABC and CBA would be considered different permutations)"))
    ((en-us ("piecewise function" "piecewise functions") "a function that computes different expressions based on its input"))
    ((en-us ("pie chart" "pie charts") "a display that uses areas of a circular pie's slices to show percentages in each category"))
    ((en-us ("pixel" "pixels") "the smallest unit that makes up a digital image. The more pixels, the more detailed an image or video can appear."))
    ((en-us "positive correlation" "relationship in which one variable increases as the other increases, and vice versa"))
    ((en-us ("predictor function" "predictor") "a function which, given a value from one dataset, makes an educated guess at a related value in a different dataset"))
    ((en-us "produce" "to compute a value from an expression"))
    ((en-us "programming language" "a set of rules for writing code that a computer can evaluate"))
    ((en-us "purpose statement" "a concise, detailed description of what a function does with its inputs"))
    ((en-us "quantitative data" "number values for which arithmetic makes sense"))
    ((en-us ("quartiles" "quartile") "three values that divide a dataset into four equal-sized groups"))
    ((en-us ("r" "r-value") "a number between −1 and 1 that measures the direction and strength of a linear relationship between two quantitative variables (also known as correlation value)"))
    ((en-us ("r-squared") "a number between 0 and 1 that measures the strength of association between two variables"))
    ((en-us ("random sample" "random samples") "a subset of individuals chosen from a larger set, such that each individual has the same probability of being chosen"))
    ((en-us "range" "the type or set of outputs that a function produces"))
    ((en-us "range of a dataset" "the distance between minimum and maximum values"))
    ((en-us "rate" "A comparison of two related quantities"))
    ((en-us "reactor" "a value that contains a current state, and functions for updating, drawing, and interacting with that state"))
    ((en-us ("rectangular prism" "rectangular prisms") "a solid figure which has 6 faces, all of which are rectangular"))
    ((en-us ("refactor" "refactoring") "the process of changing the style or structure of a program's code, without changing the program's behavior"))
    ((en-us ("response variable" "response") "the variable in a relationship that is presumed to be affected by the other variable"))
    ((en-us ("row" "rows") "item(s) in a table, which consist of some group of values; each table is a collection of rows"))
    ((en-us ("sample" "samples") "a set of individuals or objects collected or selected from a statistical population by a defined procedure"))
    ((en-us "sample instances" "a collection of single instances, or also used to describe illustrative instances that we use to provide examples of a data structure"))
    ((en-us ("scatter plot" "scatter plots") "a display of the relationship between two quantitative variables, graphing each explanatory value on the x axis and the accompanying response on the y axis"))
    ((en-us ("select" "selects" "selecting") "a query that creates a table containing only a subset of a specified table's columns"))
    ((en-us "shape" "The aspect of a dataset that tells which values are more or less common"))
    ((en-us "sieve" "a table query that creates a table containing only rows that satisfy a boolean expression"))
    ((en-us ("skew" "skewness") "lack of balance in a dataset’s shape, arising from more values that are unusually low or high. Such values tend to trail off, rather than be separated by a gap (as with outliers)."))
    ((en-us ("skewed left" "skew left" "left skew") "A distribution is skewed left if there are a few values that are fairly low compared to the bulk of data values. A display of the data will show a longer tail to the left."))
    ((en-us ("skewed right" "skew right" "right skew") "A distribution is skewed right if there are a few values that are fairly high compared to the bulk of data values. A display of the data will show a longer tail to the right."))
    ((en-us "slope" "the steepness of a straight line on a graph"))
    ((en-us "spread" "the extent to which values in a dataset vary, either from one another or from the center"))
    ((en-us "state" "the value of a changing system at any point in time (i.e. a stoplight can be in the 'red', 'yellow' or 'green' state). In Pyret, the state of a Reactor is it's current value."))
    ((en-us "statistical inference" "using information from a sample to draw conclusions about the larger population from which the sample was taken"))
    ((en-us "strength" "of a relationship between two quantitative variables: the extent to which knowing the value of one variable tells us something about the value of the other"))
    ((en-us "string" "a data type for any sequence of characters between quotation marks (examples: \"hello\", \"42\", \"this is a string!\")"))
    ((en-us "surface area" "the sum of the areas of the faces of a polyhedron or the total area that the surface of a solid object occupies"))
    ((en-us ("symmetric" "symmetric distribution") "A symmetric distribution has a balanced shape, showing that it's just as likely for the variable to take lower values as higher values."))
    ((en-us "syntax" "the set of rules that defines a language, whether it be spoken, written, or programmed."))
    ((en-us ("syntax error" "syntax errors") "errors where the computer cannot make sense of the code (e.g. - missing commas, parentheses, unclosed strings)"))
    ((en-us ("table" "tables") "a data structure that stores data as rows, with entries in particular columns"))
    ((en-us "table plan" "a sequence of steps that helps people write code for several table queries, in order to solve a problem"))
    ((en-us ("table query" "table queries") "an expression that consumes tables and creates a new table object"))
    ((en-us "threats to validity" "factors that can undermine the conclusion of a study"))
    ((en-us "union" "the set of values that makes either or both of a set of inequalities true"))
    ((en-us "unit test" "an example showing the use of a function with a specific value or values, and the answer it should produce"))
    ((en-us "value" "a specific piece of data, like 5 or \"hello\""))
    ((en-us ("variable" "variables") "a letter or symbol that stands in for a value or expression"))
    ((en-us "variable name" "name of the information that can be different each time a function is used"))
    ((en-us ("vertical axis" "y-axis") "number line on a coordinate plane that runs from bottom to top, indicating values in that direction"))
    ((en-us "y-intercept" "The point where a line or curve crosses the y-axis of a graph"))

    ))
