var langTable = {
  "Number": {
    "primitives": [
      {name: "+", domain: "Number Number", range: "Number"},
      {name: "-", domain: "Number Number", range: "Number"},
      {name: "*", domain: "Number Number", range: "Number"},
      {name: "/", domain: "Number Number", range: "Number"},
      {name: "expt", domain: "Number Number", range: "Number"},
      {name: "mean", domain: "Number Number", range: "Number"},
      {name: "median", domain: "Table String", range: "Number"},
      {name: "modes", domain: "Table String", range: "List<Number>"},
      {name: "sqr", domain: "Number", range: "Number"},
      {name: "sqrt", domain: "Number", range: "Number"},
    ],
    "values": ["4", "-1.2", "2/3", "pi"]
  },
  "String": {
    "primitives": [
      {name: "string-length", domain: "String", range: "Number"},
      {name: "string-repeat", domain: "String Number", range: "String"},
      {name: "string-contains?", domain: "String String", range: "Boolean"},
      ],
    "values": ["\"hello\"", "\"91\""]
  },
  "Boolean": {
    "primitives": [
      {name: "==", domain: "Number Number", range: "Boolean"},
      {name: "<", domain: "Number Number", range: "Boolean"},
      {name: ">", domain: "Number Number", range: "Boolean"},
      {name: "<>", domain: "Number Number", range: "Boolean"},
      {name: "<=", domain: "Number Number", range: "Boolean"},
      {name: ">=", domain: "Number Number", range: "Boolean"},
      {name: "string-equal", domain: "String String", range: "Boolean"},
      {name: "string<?", domain: "String String", range: "Boolean"},
      {name: "string>?", domain: "String String", range: "Boolean"},
      {name: "string=?", domain: "String String", range: "Boolean"},
      {name: "string<>?", domain: "String String", range: "Boolean"},
      {name: "string<=?", domain: "String String", range: "Boolean"},
      {name: "string>=?", domain: "String String", range: "Boolean"},
      {name: "and", domain: "Boolean Boolean", range: "Boolean"},
      {name: "or", domain: "Boolean Boolean", range: "Boolean"},
    ],
    "values": ["true", "false"]
  },
  "Image": {
    "primitives": [
      {name: "star", domain: "Number String String", range: "Image"},
      {name: "triangle", domain: "Number String String", range: "Image"},
      {name: "circle", domain: "Number String String", range: "Image"},
      {name: "square", domain: "Number String String", range: "Image"},
      {name: "rectangle", domain: "Number Number String String", range: "Image"},
      {name: "rhombus", domain: "Number Number String String", range: "Image"},
      {name: "ellipse", domain: "Number Number String String", range: "Image"},
      {name: "regular-polygon", domain: "Number Number String String", range: "Image"},
      {name: "radial-star", domain: "Number Number Number String String", range: "Image"},
      {name: "polygon-star", domain: "Number Number Number String String", range: "Image"},
      {name: "text", domain: "String Number String", range: "Image"},
      {name: "image-url", domain: "String", range: "Image"},
      {name: "overlay", domain: "Image Image", range: "Image"},
      {name: "put-image", domain: "Image Number Number Image", range: "Image"},
      {name: "above", domain: "Image Image", range: "Image"},
      {name: "beside", domain: "Image Image", range: "Image"},
      {name: "below", domain: "Image Image", range: "Image"},
      {name: "rotate", domain: "Number Image", range: "Image"},
      {name: "scale", domain: "Number Image", range: "Image"},
      {name: "flip-horizontal", domain: "Image", range: "Image"},
      {name: "flip-vertical", domain: "Image", range: "Image"},
      {name: "bar-chart", domain: "Table String", range: "Image"},
      {name: "stacked-bar-chart", domain: "Table String String", range: "Image"},
      {name: "multi-bar-chart", domain: "Table String String", range: "Image"},
      {name: "pie-chart", domain: "Table String", range: "Image"},
      {name: "box-plot", domain: "Table String", range: "Image"},
      {name: "scatter-plot", domain: "Table String String String", range: "Image"},
      {name: "lr-plot,", domain: "Table String String String", range: "Image"},
      {name: "histogram,", domain: "Table String String Number", range: "Image"},
      {name: "image-scatter-plot", domain: "Table String String (Row->Image)", range: "Image"},
      {name: "bar-chart-summarized", domain: "Table String String", range: "Image"},
      {name: "pie-chart-summarized", domain: "Table String String", range: "Image"},
      {name: "modified-box-plot", domain: "Table String", range: "Image"},
    ],
    "values": ["🔵", "🔺", "🔶"]
  },
  "Table": {
    "primitives": [
      {name: "count", domain: "Table String", range: "Number"},
      {name: "row-n", domain: "Table Number", range: "Row"},
      {name: "sort", domain: "Table String Boolean", range: "Table"},
      {name: "filter", domain: "Table (Row->Boolean)", range: "Table"},
      {name: "build-column", domain: "Table String (Row->Value)", range: "Table"},
      {name: "random-rows", domain: "Table Number", range: "Table"},
      {name: "fit-model", domain: "Table (Number->Number)", range: "Image"},
    ],
    "values": ["This whole table is a table!"]
  }
}
