var langTable = {
  "Number": {
    "primitives": [
      {"name": "+",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example": "1 + 2"},
      {"name": "-",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example": "1 - 2"},
      {"name": "*",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example": "1 * 2"},
      {"name": "/",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example": "1 / 2"},
      {"name": "num-expt",
       "domain": [{"name": "base", "type":"Number"}, {"name": "power", "type": " Number"}],
       "range": "Number",
       "example": "expt(3,4)",
       "comment" :  "three to the fourth power"},
      {"name": "mean",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": " Number"}],
       "range": "Number",
       "example": "mean(animals-table, \"pounds\")"},
      {"name": "median",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": "String"}],
       "range": "Number",
       "example": "median(animals-table, \"pounds\")"},
      {"name": "modes",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": "String"}],
       "range": "List<Number>",
       "example": "modes(animals-table, \"species\")"},
      {"name": "num-sqr",
       "domain": [{"name": "n", "type":"Number"}],
       "range": "Number",
       "example": "sqr(4, 2)"},
      {"name": "num-sqrt",
       "domain": [{"name": "n", "type":"Number"}],
       "range": "Number",
       "example": "sqr(4, 2)"}
    ],
    "values": ["4", "-1.2", "2/3", "pi"]
  },
  "String": {
    "primitives": [
      {"name": "string-length",
       "domain": [{"name": "s", "type":"String"}],
       "range": "Number",
       "example": "string-length(\"rainbow\")"},
      {"name": "string-repeat",
       "domain": [{"name": "s", "type":"String"}, {"name": "n", "type": " Number"}],
       "range": "String",
       "example": "string-repeat(\"hi\", 2)"},
      {"name": "string-contains",
       "domain": [{"name": "haystack", "type":"String"}, {"name": "needle", "type": "String"}],
       "range": "Boolean",
       "example": "string-contains(\"hotdog\", \"dog\")"}
      ],
    "values": ["\"hello\"", "\"91\""]
  },
  "Boolean": {
    "primitives": [
      {"name": "==",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example": "3 == 4",
       "comment": "produces false"},
      {"name": "<",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example": "3 < 4",
       "comment": "produces true"},
      {"name": ">",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example": "\"a\" > \"b\"",
       "comment": "produces false"},
      {"name": "<>",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example": "3 <> 3",
       "comment": "produces false, because 3 is neither less-than nor greater-than 3"},
      {"name": "<=",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example": "3 <= 3",
       "comment": "produces true, because 3 is equal to 3"},
      {"name": ">=",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example": "3 >= 4",
       "comment": "produces false, because 3 is neither greater-than nor equal-to 4"},
      {"name": "and",
       "domain": [{"name": "condition1", "type":"Boolean"}, {"name": "condition2", "type": " Boolean"}],
       "range": "Boolean",
       "example": "(0 > 1) and (4 == 4)",
       "comment": "produces false because both conditions must be true"},
      {"name": "or",
       "domain": [{"name": "condition1", "type":"Boolean"}, {"name": "condition2", "type": " Boolean"}],
       "range": "Boolean",
       "example": "(1 > 0) or (4 == 4)",
       "comment": "produces true if one or more conditions are be true"}
    ],
    "values": ["true", "false"]
  },
  "Image": {
    "primitives": [
      {"name": "star",
       "domain": [{"name": "radius", "type":"Number"}, {"name": "style", "type": "String, String"}],
       "range": "Image",
       "example": "star(50, \"solid\", \"red\")"},
      {"name": "triangle",
       "domain": [{"name": "size", "type":"Number"}, {"name": "style", "type": "String, String"}],
       "range": "Image",
       "example": "triangle(50, \"outline\", \"blue\")"},
      {"name": "circle",
       "domain": [{"name": "radius", "type":"Number"}, {"name": "style", "type": "String, String"}],
       "range": "Image",
       "example": "circle(50, \"solid\", \"purple\")"},
      {"name": "square",
       "domain": [{"name": "size", "type":"Number"}, {"name": "style", "type": "String, String"}],
       "range": "Image",
       "example": "square(50, \"solid\", \"red\")"},
      {"name": "rectangle",
       "domain": [{"name": "width", "type":"Number"}, {"name": "height", "type": "Number"}, {"name": "style", "type": "String"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example": "rectangle(100, 50, \"outline\", \"green\")"},
      {"name": "rhombus",
       "domain": [{"name": "angle", "type":"Number"}, {"name": "", "type": " Number, String, String"}],
       "range": "Image",
       "example": "rhombus(60, 90, \"solid\", \"pink\")"},
      {"name": "ellipse",
       "domain": [{"name": "width", "type":"Number"}, {"name": "height", "type": "Number"}, {"name": "style", "type": "String"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example": "ellipse(100, 50, \"outline\", \"green\")"},
      {"name": "regular-polygon",
       "domain": [{"name": "vertices", "type":"Number"}, {"name": "size", "type": "Number"}, {"name": "style", "type": "String"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example": "regular-polygon(25,5, \"solid\", \"purple\")"},
      {"name": "radial-star",
       "domain": [{"name": "points", "type":"Num"}, {"name": "inner", "type":"Num"}, {"name": "outer", "type": "Num"}, {"name": "style", "type": "Str"}, {"name": "color", "type": "Str"}],
       "range": "Image",
       "example": "radial-star(6, 20, 50, \"solid\", \"red\")"},
      {"name": "text",
       "domain": [{"name": "str", "type":"String"}, {"name": "size", "type": "Number"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example": "text(\"Zari\", 50, \"red\")"},
      {"name": "image-url",
       "domain": [{"name": "url", "type":"String"}],
       "range": "Image",
       "example": "image-url(\"https://bootstrapworld.org/images/icon.png\")"},
      {"name": "overlay",
       "domain": [{"name": "top", "type":"Image"}, {"name": "bottom", "type": " Image"}],
       "range": "Image",
       "example": "overlay(circle(10, \"solid\", \"black\"), square(50, \"solid\", \"red\"))"},
      {"name": "put-image",
       "domain": [{"name": "top", "type":"Image"}, {"name": "x", "type":"Number"}, {"name": "y", "type":"Number"}, {"name": "bottom", "type": " Image"}],
       "range": "Image",
       "example": "put-image(circle(10, \"solid\", \"black\"), 10, 10, square(50, \"solid\", \"red\"))"},
      {"name": "above",
       "domain": [{"name": "high", "type":"Image"}, {"name": "low", "type": " Image"}],
       "range": "Image",
       "example": "above(circle(10, \"solid\", \"black\"), square(50, \"solid\", \"red\"))"},
      {"name": "beside",
       "domain": [{"name": "left", "type":"Image"}, {"name": "right", "type": " Image"}],
       "range": "Image",
       "example": "beside(circle(10, \"solid\", \"black\"), square(50, \"solid\", \"red\"))"},
      {"name": "below",
       "domain": [{"name": "low", "type":"Image"}, {"name": "high", "type": " Image"}],
       "range": "Image",
       "example": "below(circle(10, \"solid\", \"black\"), square(50, \"solid\", \"red\"))"},
      {"name": "rotate",
       "domain": [{"name": "degrees", "type":"Number"}, {"name": "img", "type": " Image"}],
       "range": "Image",
       "example": "rotate(45, star(50, \"solid\", \"blue\"))"},
      {"name": "scale",
       "domain": [{"name": "factor", "type":"Number"}, {"name": "img", "type": " Image"}],
       "range": "Image",
       "example": "scale(1/2, star(50, \"solid\", \"blue\"))"},
      {"name": "flip-horizontal",
       "domain": [{"name": "", "type":"Image"}],
       "range": "Image",
       "example": "flip-horizontal(text(\"Lion\", 50, \"red\"))"},
      {"name": "flip-vertical",
       "domain": [{"name": "img", "type":"Image"}],
       "range": "Image",
       "example": "flip-vertical(text(\"Dacks\", 50, \"red\"))"},
      {"name": "bar-chart",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": "String"}],
       "range": "Image",
       "example": "bar-chart(animals-table, \"species\")"},
      {"name": "stacked-bar-chart",
       "domain": [{"name": "t", "type":"Table"}, {"name": "group", "type": "String"}, {"name": "subgroup", "type": "String"}],
       "range": "Image",
       "example": "stacked-bar-chart(animals-table, \"species\", \"sex\")"},
      {"name": "multi-bar-chart",
       "domain": [{"name": "t", "type":"Table"}, {"name": "group", "type": "String"}, {"name": "subgroup", "type": "String"}],
       "range": "Image",
       "example": "multi-bar-chart(animals-table, \"species\", \"sex\")"},
      {"name": "pie-chart",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": "String"}],
       "range": "Image",
       "example": "pie-chart(animals-table, \"species\")"},
      {"name": "box-plot",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": "String"}],
       "range": "Image",
       "example": "box-plot(animals-table, \"weeks\")"},
      {"name": "scatter-plot",
       "domain": [{"name": "t", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}],
       "range": "Image",
       "example": "scatter-plot(animals-table, \"name\", \"pounds\",\"weeks\")"},
      {"name": "lr-plot",
       "domain": [{"name": "t", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}],
       "range": "Image",
       "example": "lr-plot(animals-table, \"name\", \"pounds\",\"weeks\")"},
      {"name": "histogram",
       "domain": [{"name": "t", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "values", "type": "String"}],
       "range": "Image",
       "example": "histogram(animals-table, \"weeks\", 2)"},
      {"name": "image-scatter-plot",
       "domain": [{"name": "t", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}, {"name": "f", "type": "(Row -> Image)"}],
       "range": "Image",
       "example": "image-scatter-plot(animals-table, \"name\", \"pounds\",\"weeks\", f)"},
      {"name": "bar-chart-summarized",
       "domain": [{"name": "t", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "values", "type": "String"}],
       "range": "Image",
       "example": "bar-chart-summarized(count(animals-table, \"species\"), \"value\",\"count\")"},
      {"name": "pie-chart-summarized",
       "domain": [{"name": "t", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "values", "type": "String"}],
       "range": "Image",
       "example": "pie-chart-summarized(count(animals-table, \"species\"), \"value\",\"count\")"},
      {"name": "modified-box-plot",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": "String"}],
       "range": "Image",
       "example": "modified-box-plot(animals-table, \"pounds\")"}
    ],
    "values": ["🔵", "🔺", "🔶"]
  },
  "Table": {
    "primitives": [
      {"name": "count",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": "String"}],
       "range": "Number",
       "example": "count(animals-table, \"species\")"},
      {"name": "row-n",
       "domain": [{"name": "t", "type":"Table"}, {"name": "index", "type": " Number"}],
       "range": "Row",
       "example": "row-n(animals-table, 2)"},
      {"name": "sort",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": "String"}, {"name": "ascending", "type": "Boolean"}],
       "range": "Table",
       "example": "sort(animals-table, \"species\", true)"},
      {"name": "filter",
       "domain": [{"name": "t", "type":"Table"}, {"name": "test", "type": " (Row -> Boolean)"}],
       "range": "Table",
       "example": "filter(animals-table, is-dog)"},
      {"name": "build-column",
       "domain": [{"name": "t", "type":"Table"}, {"name": "col", "type": "String"}, {"name": "builder", "type": "(Row -> Value)"}],
       "range": "Table",
       "example": "build-column(animals-table, kilograms)"},
      {"name": "random-rows",
       "domain": [{"name": "t", "type":"Table"}, {"name": "num-rows", "type": " Number"}],
       "range": "Table",
       "example": "random-rows(animals-table, 10)",
       "comment": "select 10 random rows from the table"},
      {"name": "fit-model",
       "domain": [{"name": "t", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}, {"name": "f", "type": "(Number -> Number)"}],
       "range": "Image",
       "example": "fit-model(animals-table, \"name\", \"pounds\",\"weeks\", f)"}
    ],
    "values": ["This whole table is a table!"]
  }
}
