var langTable = {
  "Number": {
    "primitives": [
      {"name": "+",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example-pyret": "1 + 2",
       "example-wescheme": "(+ 1 2)"},
      {"name": "-",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example-pyret": "1 - 2",
       "example-wescheme": "(- 1 2)"},
      {"name": "*",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example-pyret": "1 * 2",
       "example-wescheme": "(* 1 2)"},
      {"name": "/",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example-pyret": "1 / 2",
       "example-wescheme": "(/ 1 2)"},
      {"name": "expt",
       "domain": [{"name": "base", "type":"Number"}, {"name": "power", "type": " Number"}],
       "range": "Number",
       "example-pyret": "expt(3, 4)",
       "example-wescheme": "(expt 3 4)",
       "comment" :  "three to the fourth power"},
      {"name": "mean",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Number",
       "example-pyret": "mean(animals-table, \"pounds\")"},
      {"name": "median",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Number",
       "example-pyret": "median(animals-table, \"pounds\")"},
      {"name": "modes",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "List<Number>",
       "example-pyret": "modes(animals-table, \"pounds\")"},
      {"name": "max",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example-pyret": "max(3, 4)",
       "example-wescheme": "(max 3 4)"},      
      {"name": "min",
       "name-pyret": "min",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Number",
       "example-pyret": "min(3, 4)",
       "example-wescheme": "(min 3 4)"},
      {"name": "sqr",
       "domain": [{"name": "", "type":"Number"}],
       "range": "Number",
       "example-pyret": "sqr(4)",
       "example-wescheme": "(sqr 4)"},
      {"name": "sqrt",
       "domain": [{"name": "", "type":"Number"}],
       "range": "Number",
       "example-pyret": "sqrt(4)",
       "example-wescheme": "(sqrt 4)"},
      {"name": "log",
       "name-pyret": "log",
       "domain": [{"name": "n", "type":"Number"}],
       "range": "Number",
       "example-pyret": "log(4)"},
      {"name": "log-base",
       "name-pyret": "log-base",
       "domain": [{"name": "base", "type":"Number"}, {"name": "n", "type":"Number"}],
       "range": "Number",
       "example-pyret": "log-base(2, 4)"}
    ],
    "values": ["4", "-1.2", "2/3", "pi"]
  },
  "String": {
    "primitives": [
      {"name": "string-contains?",
       "name-pyret": "string-contains",
       "domain": [{"name": "haystack", "type":"String"}, {"name": "needle", "type": "String"}],
       "range": "Boolean",
       "example-pyret": "string-contains(\"hotdog\", \"dog\")",
       "example-wescheme": "(string-contains? \"hotdog\" \"dog\")"},
      {"name": "string-length",
       "domain": [{"name": "", "type":"String"}],
       "range": "Number",
       "example-pyret": "string-length(\"rainbow\")",
       "example-wescheme": "(string-length \"rainbow\")"},
      {"name": "string-repeat",
       "domain": [{"name": "", "type":"String"}, {"name": "", "type": " Number"}],
       "range": "String",
       "example-pyret": "string-repeat(\"hi\", 2)",
       "example-wescheme": "(string-repeat \"hi\" 2)"}
         ],
    "values": ["\"hello\"", "\"91\""]
  },
  "Boolean": {
    "primitives": [
      {"name": "=",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example-pyret": "3 == 4",
       "example-wescheme": "(= 3 4)",
       "comment": "produces false"},
      {"name": "<",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example-pyret": "3 < 4",
       "example-wescheme": "(< 3 4)",
       "comment": "produces true"},
      {"name": ">",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example-pyret": "\"a\" > \"b\"",
       "example-wescheme": "(> \"a\" \"b\")",
       "comment": "produces false"},
      {"name": "<>",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example-pyret": "3 <> 3",
       "example-wescheme": "(<> 3 3)",
       "comment": "produces false, because 3 is neither less-than nor greater-than 3"},
      {"name": "<=",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example-pyret": "3 <= 3",
       "example-wescheme": "(<= 3 3)",
       "comment": "produces true, because 3 is equal to 3"},
      {"name": ">=",
       "domain": [{"name": "a", "type":"Number"}, {"name": "b", "type": " Number"}],
       "range": "Boolean",
       "example-pyret": "3 >= 4",
       "example-wescheme": "(>= 3 4)",
       "comment": "produces false, because 3 is neither greater-than nor equal-to 4"},
      {"name": "and",
       "domain": [{"name": "condition1", "type":"Boolean"}, {"name": "condition2", "type": " Boolean"}],
       "range": "Boolean",
       "example-pyret": "(0 > 1) and (4 == 4)",
       "example-wescheme": "(and (> 0 1)  (= 4 4))",
       "comment": "produces false because both conditions must be true"},
      {"name": "or",
       "domain": [{"name": "condition1", "type":"Boolean"}, {"name": "condition2", "type": " Boolean"}],
       "range": "Boolean",
       "example-pyret": "(1 > 0) or (4 == 4)",
       "example-wescheme": "(or (> 1 0)  (= 4 4))",
       "comment": "produces true if one or more conditions are be true"}
    ],
    "values": ["true", "false"]
  },
  "Image": {
    "primitives": [
      {"name": "circle",
       "domain": [{"name": "radius", "type":"Number"}, {"name": "fill-style", "type": "String,"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "circle(50, \"solid\", \"purple\")",
       "example-wescheme": "(circle 50 \"solid\" \"purple\")"},
      {"name": "ellipse",
       "domain": [{"name": "width", "type":"Number"}, {"name": "height", "type": "Number"}, {"name": "fill-style", "type": "String"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "ellipse(100, 50, \"outline\", \"orange\")",
       "example-wescheme": "(ellipse 100 50 \"outline\" \"orange\")"},
      {"name": "radial-star",
       "domain": [{"name": "points", "type":"Num"}, {"name": "outer", "type":"Num"}, {"name": "inner", "type": "Num"}, {"name": "fill-style", "type": "Str"}, {"name": "color", "type": "Str"}],
       "range": "Image",
       "example-pyret": "radial-star(6, 20, 50, \"solid\", \"red\")",
       "example-wescheme": "(radial-star 6 20 50 \"solid\" \"red\")"},
      {"name": "rectangle",
       "domain": [{"name": "width", "type":"Number"}, {"name": "height", "type": "Number"}, {"name": "fill-style", "type": "String"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "rectangle(100, 50, \"outline\", \"green\")",
       "example-wescheme": "(rectangle 100 50 \"outline\" \"green\")"},
      {"name": "regular-polygon",
       "domain": [{"name": "size", "type":"Number"}, {"name": "vertices", "type": "Number"}, {"name": "fill-style", "type": "String"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "regular-polygon(25,5, \"solid\", \"purple\")",
       "example-wescheme": "(regular-polygon 25 5 \"solid\" \"purple\")"},
      {"name": "rhombus",
       "domain": [{"name": "size", "type":"Number"}, {"name": "top-angle", "type": "Number"}, {"name": "fill-style", "type":"String"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "rhombus(100, 45, \"outline\", \"pink\")",
       "example-wescheme": "(rhombus 100 45 \"outline\" \"pink\")"},
      {"name": "square",
       "domain": [{"name": "size", "type":"Number"}, {"name": "fill-style", "type": "String"},{"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "square(50, \"solid\", \"red\")",
       "example-wescheme": "(square 50 \"solid\" \"red\")"},
      {"name": "star",
       "domain": [{"name": "radius", "type":"Number"}, {"name": "fill-style", "type": "String"},{"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "star(50, \"solid\", \"red\")",
       "example-wescheme": "(star 50 \"solid\" \"red\")"},
      {"name": "star-polygon",
       "domain": [{"name": "size", "type":"Number"}, {"name": "point-count", "type":"Number"}, {"name": "step-count", "type":"Number"},{"name": "fill-style", "type": "String"},{"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "star-polygon(100, 10, 3 ,\"outline\", \"red\")",
       "example-wescheme": "(star-polygon 100 10 3 \"outline\" \"red\")"},
      {"name": "text",
       "domain": [{"name": "message", "type":"String"}, {"name": "size", "type": "Number"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "text(\"Zari\", 85, \"orange\")",
       "example-wescheme": "(text \"Zari\" 85 \"orange\")"},
      {"name": "triangle",
       "domain": [{"name": "size", "type":"Number"}, {"name": "fill-style", "type": "String"}, {"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "triangle(50, \"solid\", \"fuchsia\")",
       "example-wescheme": "(triangle 50 \"solid\" \"fuchsia\")"},
       {"name": "right-triangle",
       "domain": [{"name": "leg 1", "type":"Number"}, {"name": "leg 2", "type":"Number"}, {"name": "fill-style", "type": "String"},{"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "right-triangle(50, 60, \"outline\", \"blue\")",
       "example-wescheme": "(right-triangle 50  60 \"outline\" \"blue\")"},
       {"name": "isosceles-triangle",
       "domain": [{"name": "size", "type":"Number"}, {"name": "vertex-angle", "type":"Number"}, {"name": "fill-style", "type": "String"},{"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "isosceles-triangle(50, 20, \"solid\", \"grey\")",
       "example-wescheme": "(isosceles-triangle 50  20 \"solid\" \"grey\")"},
       {"name": "triangle/sas",
       "name-pyret": "triangle-sas",
       "domain": [{"name": "bottom-R-side", "type":"Number"}, {"name": "top-R-angle", "type":"Number"}, {"name": "top-side", "type":"Number"},{"name": "fill-style", "type": "String"},{"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "triangle-sas(50, 20, 70, \"outline\", \"dark-green\")",
       "example-wescheme": "(triangle/sas 50  20 70 \"outline\" \"darkgreen\")"},
       {"name": "triangle/asa",
       "name-pyret": "triangle-asa",
       "domain": [{"name": "top-left-angle", "type":"Number"}, {"name": "left-side", "type":"Number"}, {"name": "bottom-angle", "type":"Number"},{"name": "fill-style", "type": "String"},{"name": "color", "type": "String"}],
       "range": "Image",
       "example-pyret": "triangle-asa(90, 200, 10, \"solid\", \"purple\")",
       "example-wescheme": "(triangle/asa 90  200 10 \"solid\" \"purple\")"},
       {"name": "above",
       "domain": [{"name": "above", "type":"Image"}, {"name": "below", "type": " Image"}],
       "range": "Image",
       "example-pyret": "above(circle(10, \"solid\", \"black\"), square(50, \"solid\", \"red\"))",
       "example-wescheme": "(above (circle 10 \"solid\" \"black\") (square 50 \"solid\" \"red\"))"},
      {"name": "below",
       "domain": [{"name": "below", "type":"Image"}, {"name": "above", "type": " Image"}],
       "range": "Image",
       "example-pyret": "below(circle(10, \"solid\", \"black\"), square(50, \"solid\", \"red\"))",
       "example-wescheme": "(below (circle 10 \"solid\" \"black\") (square 50 \"solid\" \"red\"))"},
      {"name": "beside",
       "domain": [{"name": "left", "type":"Image"}, {"name": "right", "type": " Image"}],
       "range": "Image",
       "example-pyret": "beside(circle(10, \"solid\", \"black\"), square(50, \"solid\", \"red\"))",
       "example-wescheme": "(beside (circle 10 \"solid\" \"black\") (square 50 \"solid\" \"red\"))"},
      {"name": "flip-horizontal",
       "domain": [{"name": "", "type":"Image"}],
       "range": "Image",
       "example-pyret": "flip-horizontal(text(\"Lion\", 50, \"maroon\"))",
       "example-wescheme": "(flip-horizontal (text \"Lion\" 50 \"maroon\"))"},
      {"name": "flip-vertical",
       "domain": [{"name": "", "type":"Image"}],
       "range": "Image",
       "example-pyret": "flip-vertical(text(\"Orion\", 65, \"teal\"))",
       "example-wescheme": "(flip-vertical (text \"Orion\" 65 \"teal\"))"},
      {"name": "image-url",
       "domain": [{"name": "url", "type":"String"}],
       "range": "Image",
       "example-pyret": "image-url(\"https://bootstrapworld.org/images/icon.png\")",
       "example-wescheme": "(image-url \"https://bootstrapworld.org/images/icon.png\")"},
      {"name": "overlay",
       "domain": [{"name": "top", "type":"Image"}, {"name": "bottom", "type": " Image"}],
       "range": "Image",
       "example-pyret": "overlay(circle(10, \"solid\", \"black\"), square(50, \"solid\", \"red\"))",
       "example-wescheme": "(overlay (circle 10 \"solid\" \"black\") (square 50 \"solid\" \"red\"))"},
      {"name": "translate",
       "domain": [{"name": "front", "type":"Image"}, {"name": "x-coordinate", "type":"Number"}, {"name": "y-coordinate", "type":"Number"}, {"name": "behind", "type": " Image"}],
       "range": "Image",
       "example-pyret": "translate(circle(10, \"solid\", \"black\"), 10, 10, square(50, \"solid\", \"red\"))",
       "example-wescheme": "(translate (circle 10 \"solid\" \"black\") 10 10 (square 50 \"solid\" \"red\"))"},
      {"name": "put-image",
       "domain": [{"name": "front", "type":"Image"}, {"name": "x-coordinate", "type":"Number"}, {"name": "y-coordinate", "type":"Number"}, {"name": "behind", "type": " Image"}],
       "range": "Image",
       "example-pyret": "put-image(circle(10, \"solid\", \"black\"), 10, 10, square(50, \"solid\", \"red\"))",
       "example-wescheme": "(put-image (circle 10 \"solid\" \"black\") 10 10 (square 50 \"solid\" \"red\"))"},
      {"name": "rotate",
       "domain": [{"name": "degrees", "type":"Number"}, {"name": "img", "type": " Image"}],
       "range": "Image",
       "example-pyret": "rotate(45, star(50, \"solid\", \"dark-blue\"))",
       "example-wescheme": "(rotate 45 (star 50 \"solid\" \"darkblue\"))"},
      {"name": "scale",
       "domain": [{"name": "factor", "type":"Number"}, {"name": "img", "type": " Image"}],
       "range": "Image",
       "example-pyret": "scale(1/2, star(50, \"solid\", \"light-blue\"))",
       "example-wescheme": "(scale 1/2 (star 50 \"solid\" \"lightblue\"))"},
      {"name": "bar-chart",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Image",
       "example-pyret": "bar-chart(animals-table, \"species\")"},
      {"name": "bar-chart-summarized",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "values", "type": "String"}],
       "range": "Image",
       "example-pyret": "bar-chart-summarized(count(animals-table, \"species\"), \"value\",\"count\")"},
      {"name": "stacked-bar-chart",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "group", "type": "String"}, {"name": "subgroup", "type": "String"}],
       "range": "Image",
       "example-pyret": "stacked-bar-chart(animals-table, \"species\", \"sex\")"},
      {"name": "multi-bar-chart",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "group", "type": "String"}, {"name": "subgroup", "type": "String"}],
       "range": "Image",
       "example-pyret": "multi-bar-chart(animals-table, \"species\", \"sex\")"},
      {"name": "box-plot",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Image",
       "example-pyret": "box-plot(animals-table, \"weeks\")"},
      {"name": "modified-box-plot",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Image",
       "example-pyret": "modified-box-plot(animals-table, \"pounds\")"},
      {"name": "box-plot-scaled",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}, {"name": "low", "type": "Number"}, {"name": "high", "type": "Number"}],
       "range": "Image",
       "example-pyret": "box-plot-scaled(animals-table, \"weeks\", 1, 40)"},
      {"name": "vert-box-plot",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Image",
       "example-pyret": "vert-box-plot(animals-table, \"weeks\")"},
      {"name": "modified-vert-box-plot",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Image",
       "example-pyret": "modified-vert-box-plot(animals-table, \"pounds\")"},
      {"name": "modified-box-plot-scaled",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}, {"name": "low", "type": "Number"}, {"name": "high", "type": "Number"}],
       "range": "Image",
       "example-pyret": "modified-box-plot-scaled(animals-table, \"weeks\", 1, 40)"},
      {"name": "modified-vert-box-plot-scaled",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}, {"name": "low", "type": "Number"}, {"name": "high", "type": "Number"}],
       "range": "Image",
       "example-pyret": "modified-vert-box-plot-scaled(animals-table, \"weeks\", 1, 40)"},
      {"name": "dot-plot",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "values", "type": "String"}],
       "range": "Image",
       "example-pyret": "dot-plot(animals-table, \"name\", \"pounds\")"},
      {"name": "histogram",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "values", "type": "String"}, {"name": "bin-size", "type": " Number"}],
       "range": "Image",
       "example-pyret": "histogram(animals-table, \"species\", \"weeks\", 2)"},      
      {"name": "line-graph",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}],
       "range": "Image",
       "example-pyret": "line-graph(animals-table, \"name\", \"pounds\",\"weeks\")"},
      {"name": "pie-chart",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Image",
       "example-pyret": "pie-chart(animals-table, \"species\")"},
      {"name": "pie-chart-summarized",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "values", "type": "String"}],
       "range": "Image",
       "example-pyret": "pie-chart-summarized(count(animals-table, \"species\"), \"value\", \"count\")"},
      {"name": "scatter-plot",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}],
       "range": "Image",
       "example-pyret": "scatter-plot(animals-table, \"name\", \"pounds\",\"weeks\")"},
       {"name": "lr-plot",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}],
       "range": "Image",
       "example-pyret": "lr-plot(animals-table, \"name\", \"pounds\",\"weeks\")"},
       {"name": "image-histogram",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "values", "type": "String"}, {"name": "bin-size", "type": "Number"}, {"name": "draw-function", "type": "(Row -> Image)"}],
       "range": "Image",
       "example-pyret": "image-histogram(animals-table, \"pounds\", 2, f)"},
       {"name": "image-bar-chart",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "values", "type": "String"}, {"name": "draw-function", "type": "(Row -> Image)"}],
       "range": "Image",
       "example-pyret": "image-bar-chart(animals-table, \"species\", f)"},
       {"name": "image-scatter-plot",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}, {"name": "draw-function", "type": "(Row -> Image)"}],
       "range": "Image",
       "example-pyret": "image-scatter-plot(animals-table, \"pounds\",\"weeks\", f)"}
    ],
    "values": ["🔵", "🔺", "🔶"]
  },
  "Table": {
    "primitives": [
      {"name": "build-column",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}, {"name": "builder-function", "type": "(Row -> Value)"}],
       "range": "Table",
       "example-pyret": "build-column(animals-table, \"kilos\", kilograms)"},
      {"name": "count",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Table",
       "example-pyret": "count(animals-table, \"species\")"},
      {"name": "filter",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "tester-function", "type": "(Row -> Boolean)"}],
       "range": "Table",
       "example-pyret": "filter(animals-table, is-dog)"},
      {"name": "first-n-rows",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "num-rows", "type": "Number"}],
       "range": "Table",
       "example-pyret": "first-n-rows(animals-table, 15)"},
      {"name": "fit-model",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "labels", "type": "String"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}, {"name": "model-function", "type": "(Num -> Num)"}],
       "range": "Image",
       "example-pyret": "fit-model(animals-table, \"name\", \"pounds\",\"weeks\", f)"},
      {"name": "random-rows",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "num-rows", "type": " Number"}],
       "range": "Table",
       "example-pyret": "random-rows(animals-table, 10)",
       "comment": "select 10 random rows from the table"},
      {"name": "r-value",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}],
       "range": "Number",
       "example-pyret": "r-value(animals-table, \"pounds\",\"weeks\")"},
      {"name": "row-n",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "index", "type": " Number"}],
       "range": "Row",
       "example-pyret": "row-n(animals-table, 2)"},
      {"name": "sort",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}, {"name": "ascending", "type": "Boolean"}],
       "range": "Table",
       "example-pyret": "sort(animals-table, \"species\", true)"},
      {"name": "stdev",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Number",
       "example-pyret": "stdev(animals-table, \"pounds\")"},
      {"name": "S",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "xs", "type": "String"}, {"name": "ys", "type": "String"}, {"name": "model-function", "type": "(Num -> Num)"}],
       "range": "Number",
       "example-pyret": "S(animals-table, \"pounds\",\"weeks\", f)"},
      {"name": "sum",
       "domain": [{"name": "table-name", "type":"Table"}, {"name": "column", "type": "String"}],
       "range": "Number",
       "example-pyret": "sum(animals-table, \"pounds\")"}
    ],
    "values": ["This whole table is a table!"]
  }
}
