[.canBeLongerThanAPage]
= How to Use Our Built-In Assessments

++++
<style>
	#content { display: block !important; }
  .center img {
    border: solid 1px black;
    margin: 10px;
    box-shadow: 1px 1px 6px black;
    max-width: 90%;
  }
  h2 { margin-top: 15px !important; }
  li { margin-top: 10px !important; }

</style>
++++

Bootstrap is a research-based project, which means we're constantly evaluating our materials and impact on student learning. The benefit to teachers - besides piece of mind - is that we put a fair amount of effort into the assessments and tools we use.

@vspace{1ex}

*Starting in 2025, we began to develop assessments that teachers could use with their students.* This document outlines the design goals of those assessments, how your students' data is protected, and how to use the assessments.

== Design Goals for Assessments

- If a lesson claims to teach concept XYZ, it should include an assessment of XYZ
- Start with assessments for our most-used lessons, and add new assessments each year
- NEVER gather personally-identifiable information about students
- Give teachers an easy way to see results for their class as a whole, and for each individual student
- Improve quality of Bootstrap materials through continuous data-gathering

== Giving Students an Assessment

If a lesson includes one or more assessments they will be listed in the summary table at the top (see @lesson-link{box-plots-interpret}). Here's how to give an assessment to your class:

- Make sure you are logged into your teacher account at @link{https://www.BootstrapWorld.org}. _Assessments will not work unless they can be linked to your teacher account!_

- To generate a link for your students, click the quiz button (@image{../lib/images/quizLinkIcon.png, 16}) and type the name of your class or group (e.g. - "Period 2", "Algebra 1", "Students who failed the midterm"). When you press "Enter", a link will appear with the name you chose. *Remember the name you use*, as this link will disappear the next time you load the page. (You can always regenerate the same link by re-entering the same name)

@center{@image{images/MakeQuizLink.gif}}

- Share this link with that group of students (via email, Google Classroom, etc.) in the next 7 days. After that, the link will expire and you will have to create a new one. _Students must enter a short ID when taking the quiz, which only *YOU* can use to identify them!_ (The first two letters of their first and last name, their studentID number, a special code you create with them, etc). Make sure this ID does not include their full name, email address, or any other personally-identifiable information (PII)!

== Getting Assessment Results

- When a student completes the assessment, their data is stored on our server alongside their (non-PII) ID, the name of the group or class you created, and an anonymous identifier that connects them to you as their teacher.

- In 24 hours, *you will receive an automated email* summarizing every submitted assessment for each group, for each given quiz that day. For example: if you gave the same quiz to 3 classes, you'll receive 3 different emails; if you gave two assessments to one class, you'll receive 2 different emails. Each email will include a summary of the group as a whole, followed by data on individual question and student.

- Remember: these results will only be identified by the student ID you use! You'll have to connect the scores back to the individual students.

== Retrieving Old Assessments

Every lost an important email? We have too! So as a free service, we are also providing a simple interface for retrieving old assessment data. Go to *Link TBD*, and enter the start and end dates for window of data you want to retrieve. If you want to get access to just yesterday's quiz, for example, you'd use yesterday's date for both the start and end date.

@vspace{1ex}

Within 24 hours, you will receive an automated email for each assessment given to each group on each day within the window. If you gave an assessment to four sections of students every day between 2/4/26 and 2/6/26, you should expect to get (4 classes × 3 days) 12 of these emails.