= How to Use a Live Pyret Survey

++++
<style>
	#content { display: block !important; }
</style>
++++

Wouldn't it be fun to launch class by making a display from your students' data? Live Surveys in Pyret do just that!

@vspace{1ex}

We've created a starter file and corresponding google form to share with students for each new data visualization we introduce in Bootstrap:Data Science. Using your class's google form responses, the starter file will produce the data visualization being introduced in the lesson. The display will update in real time as students continue to enter their data!

@vspace{1ex}

All you need to do is:

- _Make a copy of the Google Form_ listed in the preparation section of the lesson.
  * _Create a new destination_ spreadsheet from the "Responses" tab to collect and save your students' data.
  * _Click "Share"_, and make sure the spreadsheet is viewable by "anyone with the link".
- _Open the starter file_ listed in the the preparation section of the lesson.
  * _Replace the spreadsheet_ link with a link to your new spreadsheet.
- _Important: Wait to click "Run"_ until after the first response is collected in the google form.
  * _Project the starter file_ so students can watch!
  * You can also publish and share the starter file with your students, once the first response has been collected.
- _Hint:_ If you want to be done with all of the setup and file sharing before class starts, you can:
  * Submit your own data via the google form as the first response.
  * Assign the google form for homework the night before.

@vspace{1ex}

Interested in asking your students other questions for use with live Pyret surveys?

- Just make your own google form and connect the link following the directions above. +
- We'd love it if you'd share a copy of the forms you make with us @link{mailto:contact@bootstrapworld.org, contact@bootstrapworld.org}!
