== Introducing Datasets in Pyret @duration{10 minutes}

=== Overview
Students open up the Pyret environment (code.pyret.org, or "CPO") and see how tables look in Pyret.

==== Launch
The first few lines in the Definitions Area tell Pyret to `import` files from elsewhere, which contain tools we’ll want to use for this course. We’re importing a file called Bootstrap:Data Science, as well as files for working with Google Sheets, tables, and images:

  include shared-gdrive("Bootstrap-DataScience-...")
  include gdrive-sheets
  include tables
  include image

After that, we see a line of code that _defines_ `shelter-sheet` to be a spreadsheet. This table is loaded from Google Drive, so now Pyret can see the same spreadsheet you do. (Notice the funny scramble of letters and numbers in that line of code? If you open up the Google Sheet, you'll find that same scramble in the address bar! That scramble is how the Pyret editor knows which spreadsheet to load.) After that, we see the following code:

  # load the 'pets' sheet as a table called animals-table
  animals-table = load-table: name, species, age, fixed, legs
    source: pets-sheet.sheet-by-name("pets", true)
  end

The first line (starting with `#`) is called a _Comment_. Comments are notes for humans, which the computer ignores. The next line defines a new table called `animals-table`, which is loaded from the `shelter-sheet` defined above. We also create names for the columns: `name`, `species`, `sex`, `age`, `fixed`, `legs`, `pounds` and `weeks`. We could use any names we want for these columns, but it’s always a good idea to pick names that make sense!

[.lesson-point]
Even if your spreadsheet already has column headers, Pyret requires that you name them in the program itself.

[.lesson-instruction]
Click “Run”, and type `animals-table` into the Interactions Area to see what the table looks like in Pyret. Is it the same table you saw in Google Sheets? What is the same? What is different?

In Data Science, every table is composed of cells, which are arranged in a grid of rows and columns. Most of the cells contain data, but _the first row and first column_ are special. The first row is called the @vocab{header row}, which gives a unique name to each variable (or “column”) in the table. The first column in the table is the @vocab{identifier column}, which contains a unique ID for each row. Often, this will be the name of each individual in the table, or sometimes just an ID number.

Below is an example of a table with one header row and two data rows:

[.pyret-table,cols="5a,5a,5a,5a,5a,5a,5a,5a",options="header"]
|===
| name | species | sex | age | fixed | legs | pounds | weeks
| "Sasha" | "cat" | "female" | 1 | false | 4 | 6.5 | 3
| "Mittens" | "cat" | "female" | 2 | true | 4 | 7.4 | 1
|===

=== Investigate
[.lesson-instruction]
- How many variables are listed in the header row for the Animals Dataset? What are they called? What is being used for the identifier column in this dataset?
- Try changing the name of one of the columns, and click "Run". What happens when you print out the table back in the Interactions Area?
- What happens if you remove a column from the list? Or add an extra one?


After the header, Pyret tables can have any number of @vocab{data rows}.
Each data row has values for every column variable (nothing can be left empty!). A table can have any number of data rows, including _zero_, as in the table below:

[.pyret-table,cols="5a,5a,5a,5a,5a,5a,5a,5a",options="header"]
|===
| name | species | sex | age | fixed | legs | pounds | weeks
|===

_This was a part of the intro to pyret lesson. I think it makes more sense in compound inequalities. Thoughts?_

Additional Exercises - 
- @opt-printable-exercise{pages/boolean-operators.html, Boolean Operators}

Pyret lets us use many different kinds of data. In the animals table, for example, there are Numbers (the number of legs each animal has), Strings (the species of the animal), and Booleans (whether it is true or false that an animal is fixed). Pyret has the usual arithmetic operators: addition (`+`), subtraction (`-`), multiplication (`*`), and division (`/`).

To identify if an animal is male, we need to know if the value in the `sex` column is _equal_ to the string `"male"`. To sort the table by age, we need to know if one animal’s age is _less than_ another’s and should come before it. To filter the table to show only young animals, we might want to know if an animal’s age is _less than_ 2. Pyret has Boolean operators, too: equals (`==`), less-than (`<`), greater-than (`>`), as well as greater-than-or-equal (`>=`) and less-than-or-equal (`<=`).
