= Function Composition

@lesson-description{Students encounter new image transformation functions and strengthen their understanding of Circles of Evaluation by using functions within other functions.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-domain-and-range}

| Lesson Goals
| Students will be able to:

* Demonstrate understanding of the Order of Operations
* Use @vocab{Circles of Evaluation} to combine multiple @vocab{function}s, including non-Number producing functions

| Student-facing Goals
|
* I can use Circles of Evaluation to combine many kinds of functions.

| Materials
|
ifeval::["{proglang}" == "wescheme"]
* Lesson slides template (@link{https://docs.google.com/presentation/d/1BvOHRghJtY7vKSc_Icirlt7bVolrMjxGf0r4NfRsR48/view, Google Slides})
endif::[]
ifeval::["{proglang}" == "pyret"]
* Lesson slides template (@link{https://drive.google.com/open?id=1IAViGbTynOiKoAu9RqOMqpIjRiFtfv6ac1GKcGlwaS8, Google Slides})
endif::[]

* Composing Image Functions (@workbook-link{pages/composing-image-functions.adoc, original}, @link{solution-pages/composing-image-functions.adoc, solutions})

* Making Stars (@workbook-link{pages/making-stars.adoc, original}, @link{solution-pages/composing-image-functions.adoc, solutions})

| Supplemental Resources
|
- Circles of Evaluation Review - Blank Template (@link{https://teacher.desmos.com/activitybuilder/custom/5d991a674febfc7e0ff8cb15, Desmos Activity})
- Function Composition Dynamic Illustrator I (@link{https://www.geogebra.org/m/nqymeFc4, Geogebra })
- Composite Functions (@link{https://quizizz.com/admin/quiz/58a61a2cf0b089151011ef50/composition-of-functions, Quizizz}
- Composition of Function (@link{https://www.geogebra.org/m/h3qdzW3W, Geogebra Quiz })

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Key Points For The Facilitator
|
* Check frequently for understanding of @vocab{data types} and @vocab{contract}s during this lesson and throughout subsequent lessons.
* When students encounter errors, encourage them to check their Contracts page and show their work using Circles of Evaluation.
* Students will use their Contracts page frequently, so it should be kept in an accessible, convenient location.
|===

== Warmup
ifeval::["{proglang}" == "wescheme"]
Students should be logged on to @link{https://www.wescheme.org, WeScheme}.
endif::[]
ifeval::["{proglang}" == "pyret"]
Students should be logged on to @link{https://code.pyret.org, code.pyret.org}.
endif::[]

== Composing Functions @duration{20 minutes}

=== Overview
Students are given a scaffolded activity that forces them to use the output of one function as the input to another - to _compose_ them. The Circles of Evaluation are extended to provide a visual-spatial metaphor for function composition, in addition to Order of Operations.

=== Launch

[.text-center]
Which One Doesn't Belong?

@centered-image{images/shape6.jpg, "Which One Doesn't Belong?, Matt Owen,
Curated by Mary Bourassa's https://wodb.ca", 400, align="center"}

Have students choose which image they feel doesn't belong and move together with other students who share their view. Take turns letting groups justify their reasons and discuss with other groups.

*Ask students: What theme do you see here?*  _(All of the shapes are cubes with some aspect of their appearance changed - angle, color, size, etc)_

=== Investigate

Have students open to @workbook-link{pages/composing-image-functions.adoc, Composing Image Functions}.  Students create a text @vocab{image} of their name and experiment with their choice of these new functions.

While students are exploring, be available for support but encourage student discussion to solve problems.  Make sure students are using the @vocab{Definitions area} (left side) for code they want to keep and are using the @vocab{Interactions area} (right side) to test code or try out new ideas.

Many questions can be addressed with these responses:

- *Did you try drawing the Circle of Evaluation first?*
- *Did you check the contract?*
- *Have you pressed the Run button to save your Definitions changes?*

=== Synthesize
- *What do all of these functions have in common?*+
_They all produce images, they all change some element of the original image_

- *Does using one of these functions change the original image?*
_No, it creates a whole new image_

- *What does the number in ‘scale’ represent?*
_The scale factor, the percent by which the image should grow or shrink_

- *What does the number in ‘rotate’ represent?*
_The rotation angle, measured counterclockwise_

- *Suppose I wrote the code
ifeval::["{proglang}" == "wescheme"]
`(scale 3 (star 50 “solid” “red”))`.
endif::[]
ifeval::["{proglang}" == "pyret"]
`scale(3, star(50, "solid", "red"))`.
endif::[]
  What’s another line of code I could write that would produce the exact same image?*

ifeval::["{proglang}" == "wescheme"]
_``(star 150 "solid" "red")``_
endif::[]
ifeval::["{proglang}" == "pyret"]
_``star(150, "solid", "red")``_
endif::[]

- *The domain and range for `flip-horizontal` is Image -> Image.  Why can I use the text function as an input for `flip-horizontal`?*
_Because the `text` function produces an Image, which is then used as the input for `flip-horizontal`._

[.strategy-box]
.Strategies for English Language Learners
****
MLR 1 - Stronger and Clearer Each Time: As an alternative, display the discussion questions during the last 5 minutes of the Explore and ask students to discuss the questions with their partner, asking each other for explanation and details and coming up with the clearest, most precise answer they can.
Student pairs can then share with another pair and compare their responses before moving into a full class discussion.
****

== Decomposing Image Problems @duration{25 minutes}

=== Overview
Students are given (simple, highly-structured) word problems involving creating images, and must map from the word problems to the names and order of functions needed to solve them. At this stage, the skill is quite brittle and hardly resembles the generalized problem-decomposition skill needed to solve complex word problems in algerba. This is merely the first introduction, and other lessons will deepen and broaden the idea.

=== Launch
Create the circles of evaluation and write the code for the following images.  Write a new line of code for each exercise.

* a solid, green `star` of size 50
* a solid, green `star` that’s 3 x’s as large as the original (using the `scale` function)
* a solid, green `star` that’s ½ the size of the original (using the `scale` function)
* a solid, green `star` of size 50 that’s rotated 45 degrees (using the `rotate` function)
* a solid, green `star` that’s 3x as large as the original and rotated 45 degrees.

=== Investigate
Students complete @workbook-link{pages/making-stars.adoc, Making Stars}, practicing drawing Circles of Evaluation and writing code with their partner using different functions.

When students are finished, check their work, and ask them to change the color of all of the stars to “gold” or another color of your choosing.

[.lesson-instruction]
Create an Image that uses the text function and at least 3 of following functions:

- `rotate`
- `scale`
- `overlay`
- `flip-horizontal`
- `flip-vertical`
- any other image producing function (`triangle`, `star`, `circle`, `rectangle`, etc..)

Students should practice writing *comments* in the code to describe what is being produced.
ifeval::["{proglang}" == "wescheme"]
Use `;` at the beginning of a line to write a comment.
endif::[]
ifeval::["{proglang}" == "pyret"]
Use `#` at the beginning of a line to write a comment.
endif::[]

== Additional Exercises:
* @link{https://www.geogebra.org/m/nqymeFc4, Function Composition Dynamic Illustrator I} (Geogebra)
* @link{https://www.geogebra.org/m/h3qdzW3W, Composition of Functions} (Geogebra Quiz)
* @link{https://quizizz.com/admin/quiz/58a61a2cf0b089151011ef50/composition-of-functions, Composite Functions} (Quizizz)
