= Teacher Resources for Algebra

== Essentials
- *Online Community (Discourse)* [@link{https://discourse.bootstrapworld.org, Discourse}] - Talk with other Bootstrap teachers, ask questions, and share out ideas!
- *Information for Families about Bootstrap:Algebra* [@link{pages/info-for-families-alg.adoc, link}]
- *Poster Set for Classroom Walls* [@link{../../../lessons/computing-needs-all-voices/pages/computing-pioneers.html, link}] - This poster set features Pioneers in Computing and Mathematics. For greater impact, engage your students with these materials using our @lesson-link{computing-needs-all-voices} lesson.
- *Contracts* [@link{solution-pages/Contracts.pdf, PDF}] - for teachers who want only the contracts reference from the back of the student workbook, without using the entire book.
- *Glossary* [@link{../../../Glossary.shtml?pathway=algebra-pyret, link}] - All of the vocabulary words (and their definitions) used in this pathway.
- *Bilingual Glossary of Bootstrap Terms (English-Spanish)* [@link{../../../lib/bilingual-glossary.html, PDF}] - For teachers with ELL/ESL students, we provide a bilingual glossary for all of the terms used across our curriculum library.
- *Blank Design Recipe Worksheet* [@dist-link{pages/2-blank-pyret-recipes.adoc, html}] - Use alongside story problems for a function development template.
- *Blank Image Contracts Page* [@lesson-link{contracts/pages/image-contracts.pdf, PDF}] - For use along with the @lesson-link{contracts} lesson, this printed page supports student discover when exploring image contracts.
- *Collection of Bootstrap:Algebra Desmos Activities* [@link{https://teacher.desmos.com/collection/5fbecc2b40d7aa0d844956f0, link}]

== Starter Files
Many of our lessons have their own starter files, linked from the materials section of each lesson plan. Below is a collated list of all the starter files from across the curriculum.

- *Game Templates*
 * @starter-file{ninja-cat}
 * @starter-file{game}
 * @starter-file{sample-game-no-distance-lines}
 * @starter-file{sample-game-w-distance}
 * @starter-file{sample-game-2d}
- *Ratio & Proportion, Geometric Transformations, Coordinate Plane Geometry - _Flags_*
 * @starter-file{flags}
 * @starter-file{flags-2}
 * @starter-file{flags-ak}
 * @starter-file{flags-lebanon}
 * @starter-file{flags-pr}
 * @starter-file{flags-trinidad}
 * @starter-file{flags-turkey}
- *Inequalities*
 * @starter-file{inequalities-simple}
 * @starter-file{inequalities-compound}
 * @starter-file{inequalities-sam}
- *Other*
 * @starter-file{defining-values}
 * @starter-file{flags-china}
 * @starter-file{rocket-height}
 * @starter-file{bug-hunting}
 * @starter-file{boolean}
 * @starter-file{sallys-lemonade}
 * @starter-file{alices-restaurant}
 * @starter-file{prism}

== Projects in Bootstrap:Algebra
Designing an original video game is the (optional) capstone project for Bootstrap Algebra. This project involves all of the various algebra and programming concepts covered in the lessons, providing students with a creative way to demonstrate their mastery of the material.

You can find the description of this project (and the grading rubric!) at @link{../../../lessons/project-video-game, the video game Project Page}.

== Exercises and Solutions
@all-exercises

== All Lesson Notes
The student workbook includes notes for various lessons. You can access all of these notes by clicking the links below:

@all-lesson-notes

== Textbook Alignment
We offer alignment guides for several popular math textbooks, which make it easy to adopt Bootstrap as part of your normal scope and sequence. These guides are available for:

- Illustrative Math (Grade 6) - [@link{../../../textbooks/IM-grade-6.html, HTML}, @link{../../../textbooks/IM-grade-6.pdf, PDF}]
- Illustrative Math (Grade 7) - [@link{../../../textbooks/IM-grade-7.html, HTML}, @link{../../../textbooks/IM-grade-7.pdf, PDF}]
- Illustrative Math (Grade 8) - [@link{../../../textbooks/IM-grade-8.html, HTML}, @link{../../../textbooks/IM-grade-8.pdf, PDF}]
- Illustrative Math (HS) - [@link{../../../textbooks/IM-HS.html, HTML}, @link{../../../textbooks/IM-HS.pdf, PDF}]
- Connected Mathematics - CMP3 (Grade 6) - [@link{../../../textbooks/cmp-grade-6.html, HTML}, @link{../../../textbooks/cmp-grade-6.pdf, PDF}]
- Connected Mathematics - CMP3 (Grade 7) - [@link{../../../textbooks/cmp-grade-7.html, HTML}, @link{../../../textbooks/cmp-grade-7.pdf, PDF}]
- Connected Mathematics - CMP3 (Grade 8) - [@link{../../../textbooks/cmp-grade-8.html, HTML}, @link{../../../textbooks/cmp-grade-8.pdf, PDF}]

== Videos for Teachers
Developed in partnership with @link{https://www.code.org, Code.org}. **NOTE:** these were developed using our earlier, 9-unit format. The content is still applicable, so we continue to provide these resources.

//Embed 10 videos here
[cols="30a,30a,30a", stripes=none]
|===
|
*Modeling and Coordinates*

video::hy3SKXANmSQ[youtube]

|
*Order of Operations*

video::ObJ0Aawc9s4[youtube]

|
*Domain and Range*

video::yW9XLaY5i8A[youtube]

|
*Defining Values*

video::bOIs2DyMUv8[youtube]

|
*Introducing The Design Recipe*

video::Yf5w56PpaTw[youtube]

|
*Using The Design Recipe*

video::e5ORR9LpgkU[youtube]

|
*Boolean Logic & Inequalities*

video::XjT-PdWmvtE[youtube]

|
*Piecewise Functions*

video::DYrd_xaTKYU[youtube]

|
*The Pythagorean Theorem*

video::35UgYAPkNcc[youtube]

|
*Why Is Algebra So Hard?*

video::0t3Q_syA0Mk[youtube]

|===

== Other Facilitation Resources
@ifproglang{wescheme}{
- *Assessment Guide* [@link{https://docs.google.com/document/d/1uJk66awwVCqJPSTiwMy1FKuYd1FipsShJwCUCq0P7Tw/edit?usp=sharing, Google Doc}] - Guidance for teachers on assessing student programs.
}

- *Design Recipe Rubric* [@link{../../../lessons/functions-dr/pages/rubric-dr, link}] - A simple grading rubric for Design Recipes, with instructions to students for completing a Design Recipe Peer Review.

- *Sample Homework Submission Form* [@link{https://docs.google.com/forms/d/1fyf1xHQElboxDoHy_Voq1YNRy3aRpxIS99ofek5ti8c/viewform, Google Doc}]

- *Broadening Participation* [@link{https://docs.google.com/presentation/d/17uEl-yS2smjSuOdDLJPzMWWffeXTqBsENjAaZe_qkso/view, Google Slides}] - Making computing relevant, accessible and welcoming to all students isn't a pipe-dream. Like anything else worth doing, it takes some good practice and a desire to do it right and keep improving. We've put together some pointers based on best-practices from the CS-Education literature, for Bootstrap teachers or anyone looking to broaden participation in Computer Science.

== Standalone Hour of Code Activities from Bootstrap

- *Hour of Data* [@lesson-link{hoc-data/, link}] - A self-guided Desmos activity for exploring a real dataset, and using it to make sense of a real-world problem.

- *Snowman Puzzle* [@link{https://code.pyret.org/editor#share=1Lgax_uAdFxUJzyGKPbx2BESj9BNkTK3i&v=1904b2c, link}] - This Pyret Starterfile has all the pieces your students will need to make a snowman by changing the coordinates in the code.
