= What Kind of Model? (Definitions)

++++
<style>
#content img {width: 75%; height: 75%;}
body.workbookpage td .autonum:after { content: ')'; }
</style>
++++

Decide whether each representation describes a linear, quadratic, or exponential function. +
*If the function is exponential:* Identify the growth factor and the initial value.

[.FillVerticalSpace, cols="<.^15a,<.^15a", frame="none", stripes="none"]
|===
| @center{@math{f(x) = 6x^2 - 5}}

@vspace{6ex}

[cols="1a,4a,4a,8a",stripes="none",frame="none",grid="none"]
!===
! *@n*
! Linear
! @ifsoln-choice{Quadratic}
! Exponential
!===

How did you know? @fitb{}{} +
@fitb{}{}

If it's exponential, what's the @fitbruby{5em}{}{growth factor} @hspace{1em} @fitbruby{2em}{}{initial value}?



| @center{@math{\mbox{miles}(\mbox{hours}) = \frac{22 \times \mbox{hours} + 14}{12 - 9}}}

@vspace{6ex}

[cols="1a,4a,4a,8a",stripes="none",frame="none",grid="none"]
!===
! *@n*
! @ifsoln-choice{Linear}
! Quadratic
! Exponential
!===

How did you know? @fitb{}{} +
@fitb{}{}

If it's exponential, what's the @fitbruby{5em}{}{growth factor} @hspace{1em} @fitbruby{2em}{}{initial value}?

| @center{@math{\mbox{cost}(w) = 5(1.2^w) + 16}}

@vspace{6ex}

[cols="1a,4a,4a,8a",stripes="none",frame="none",grid="none"]
!===
! *@n*
! Linear
! Quadratic
! @ifsoln-choice{Exponential}
!===

How did you know? @fitb{}{} +
@fitb{}{}

If it's exponential, what's the @fitbruby{5em}{@ifsoln{1.2}}{growth factor} @hspace{1em} @fitbruby{2em}{@ifsoln{5}}{initial value}?

| @center{@math{t(g) = 42 - 2g^2}}

@vspace{6ex}

[cols="1a,4a,4a,8a",stripes="none",frame="none",grid="none"]
!===
! *@n*
! Linear
! @ifsoln-choice{Quadratic}
! Exponential
!===

How did you know? @fitb{}{} +
@fitb{}{}

If it's exponential, what's the @fitbruby{5em}{}{growth factor} @hspace{1em} @fitbruby{2em}{}{initial value}?

| @center{@math{\mbox{price}(d) = d^2 + 6d}}

@vspace{6ex}

[cols="1a,4a,4a,8a",stripes="none",frame="none",grid="none"]
!===
! *@n*
! Linear
! @ifsoln-choice{Quadratic}
! Exponential
!===

How did you know? @fitb{}{} +
@fitb{}{}

If it's exponential, what's the @fitbruby{5em}{@ifsoln{}}{growth factor} @hspace{1em} @fitbruby{2em}{@ifsoln{}}{initial value}?

| @center{@math{j(x) = \frac{1}{2}^x + 22}}

@vspace{6ex}

[cols="1a,4a,4a,8a",stripes="none",frame="none",grid="none"]
!===
! *@n*
! Linear
! Quadratic
! @ifsoln-choice{Exponential}
!===

How did you know? @fitb{}{} +
@fitb{}{}

If it's exponential, what's the @fitbruby{5em}{@ifsoln{0.5}}{growth factor} @hspace{1em} @fitbruby{2em}{@ifsoln{1}}{initial value}?


| @center{@math{f(a) = 20000 - 4.1^a}}

@vspace{6ex}

[cols="1a,4a,4a,8a",stripes="none",frame="none",grid="none"]
!===
! *@n*
! Linear
! Quadratic
! @ifsoln-choice{Exponential}
!===

How did you know? @fitb{}{} +
@fitb{}{}

If it's exponential, what's the @fitbruby{5em}{@ifsoln{-4.1}}{growth factor} @hspace{1em} @fitbruby{2em}{@ifsoln{1}}{initial value}?


| @center{@math{g(x) = 8(3^{–4x})}}

@vspace{6ex}

[cols="1a,4a,4a,8a",stripes="none",frame="none",grid="none"]
!===
! *@n*
! Linear
! Quadratic
! @ifsoln-choice{Exponential}
!===

How did you know? @fitb{}{} +
@fitb{}{}

If it's exponential, what's the @fitbruby{5em}{@ifsoln{3}}{growth factor} @hspace{1em} @fitbruby{2em}{@ifsoln{8}}{initial value}?
|===
