= What Kind of Model? (Descriptions)

++++
<style>
/*
use tables for positioning, so don't let them add
any space or change autonum formatting
*/
body.workbookpage td { padding: 0; }
body.workbookpage td .autonum { font-weight: bold; }
body.workbookpage td .autonum:after { content: ')'; }

/* let the nested questions set the vertical space*/
.content .paragraph:nth-child(2) { margin-top: 1em;}
.quad { padding-bottom: 1.3em; }
.fitb { padding-top: 0; }
</style>
++++

Decide whether each situation is best described by a linear, quadratic, or exponential function. +
*If the function is exponential:* What is the growth factor. Is it doubling (factor of 2)? Tripling (factor of 3)? Factor of 5? 10?

@vspace{2ex}

[.FillVerticalSpace, cols="10a", frame="none", stripes="none", grid="none"]
|===
| *@n A particular kind of car sells for $32,000, and its resale value drops by 12.5% each year.*

@hspace{6em} +a.+ When the car is brand-new (x=0), how much is it worth? @fitb{8em}{@ifsoln{$32,000}}

@hspace{6em} +b.+ How much is it worth after... 

@indented{
[cols="^1a,^1a,^1a,^1a"]
!=== 
!1 year? +
x=1 	
! 2 years? +
x=2	
.>! 3 years? +
x=3		
.>! x =4

! @ifsoln{$28,000}	
! @ifsoln{$24,500} 	
! @ifsoln{$21,437.50} 	
! @ifsoln{$18,757.81} @ifnotsoln{@vspace{2ex}}
!===
}

@hspace{6em} +c.+ What is the *form* of this function?  @hspace{3em} 
linear &#9744; @hspace{3em} 
quadratic &#9744; @hspace{3em}  
@ifsoln-choice{exponential}@ifnotsoln{&#9744;} +

@hspace{7em} *If it's exponential*, +
@hspace{7em} Identify the 
_initial value_: @fitb{4em}{@ifsoln{$32,000}} @hspace{1em} 
_base_: @fitb{4em}{@ifsoln{1/8}} +

@hspace{7em} Is it 
_growth_? &#9744;  @hspace{1em} or @hspace{1em} 
@ifsoln-choice{_decay_?} @ifnotsoln{&#9744;} 

| *@n Sally is selling lemonade, for $1.25 a glass in hopes of finally be able to get the power drill she's been wanting. She starts with $20 cash.*

@hspace{6em} +a.+ When Sally starts the day (x=0), how many dollars does she have? @fitb{8em}{@ifsoln{$20}}

@hspace{6em} +b.+ How many dollars will she have after...
@indented{
[cols="^1a,^1a,^1a,^1a"]
!=== 
! the first sale? +
x=1 	
! second sale? +
x=2	
.>! x =3		
.>! x = 4

! @ifsoln{20 + 1.25 = $21.25}	
! @ifsoln{$22.50} 	
! @ifsoln{$23.75} 	
! @ifsoln{$25.00} 				@ifnotsoln{@vspace{2ex}}
!===
}

@hspace{6em} +c.+ What is the *form* of this function?  @hspace{3em} 
@ifnotsoln{&#9744;} @ifsoln-choice{linear} @hspace{3em} 
&#9744;quadratic  @hspace{3em} 
&#9744; exponential +

@hspace{7em} *If it's exponential*, +
@hspace{7em} Identify the 
_initial value_: @fitb{4em}{} @hspace{1em} 
_base_: @fitb{4em}{} +

@hspace{7em} Is it 
_growth_? &#9744;   @hspace{1em} or @hspace{1em} 
_decay_? &#9744; 

| *@n Two students started a club. At every meeting, students in attendance must high-five each of the other students. Club membership has been growing steadily by one student each meeting.*

@hspace{6em} +a.+ When the 2 students started the club (x=0), how many high-fives happened? @fitb{8em}{@ifsoln{1}} +
@hspace{6em} +b.+ How many high-fives happen at the subsequent meetings...

@indented{
[cols="^1a,^1a,^1a,^1a"]
!=== 
! with 3 students? +
x=1 	
! with 4 students? +
x=2	
! with 5 students? +
x=3		
.>! x=4

! @ifsoln{3}	
! @ifsoln{6} 	
! @ifsoln{10} 	
! @ifsoln{15} 				@ifnotsoln{@vspace{2ex}}
!===
}

@hspace{6em} +d.+ What is the *form* of this function?  @hspace{3em} 
linear &#9744; @hspace{3em} 
@ifsoln-choice{quadratic} @ifnotsoln{&#9744;} @hspace{3em}  
exponential &#9744; +

@hspace{7em} *If it's exponential*, +
@hspace{7em} Identify the 
_initial value_: @fitb{4em}{}  @hspace{1em} 
_base_: @fitb{4em}{} +

@hspace{7em} Is it 
_growth_? &#9744;   @hspace{1em} or @hspace{1em} 
_decay_? &#9744; 

| *@n A student posted their animation of a puppy doing a back flip into a pile of laundry and the meme went viral! Every person that sees the meme falls in love with it and shares it with 10 new friends.*

@hspace{6em} +a.+ When the student posts it (x=0), how many total times has it been shared? @fitb{8em}{@ifsoln{1}}

@hspace{6em} +b.+ How many times will it have been shared after...

@indented{
[cols="^1a,^1a,^1a,^1a"]
!=== 
! the next person shares it? +
x=1 	
! their friends share it? +
x=2	
.>! x=3				
.>! x =4

! @ifsoln{@math{10 + 1 =} + 
11}				
! @ifsoln{@math{11 \times 10 + 11 =} +
121}
.>! @ifsoln{1331} 	
.>! @ifsoln{14641} 			@ifnotsoln{@vspace{2ex}}
!===
}

@hspace{6em} +c.+ What is the *form* of this function?  @hspace{3em} 
linear &#9744; @hspace{3em} 
quadratic &#9744; @hspace{3em}  
@ifsoln-choice{exponential}@ifnotsoln{&#9744;} +

@hspace{7em}  *If it's exponential*, +
@hspace{7em} Identify the 
_initial value_: @fitb{4em}{@ifsoln{1}} @hspace{1em} 
_base_: @fitb{4em}{@ifsoln{11}} +

@hspace{7em} Is it 
@ifsoln-choice{_growth_?}@ifnotsoln{&#9744;}  @hspace{1em} or @hspace{1em}  
_decay_? &#9744; 
|===
