= Exploring the Covid Dataset
++++
<style>
/* Don't let tables add any space of change autonum formatting  */
body.workbookpage td .autonum::after { content: ')' !important; }
td:last-child { padding-top: 0; padding-bottom: 0; }
td { color: inherit !important; }
body .center { padding: 0; }
</style>
++++

[.linkInstructions]
For this page, you'll need to have the @starter-file{alg2-covid} open on your computer. If you haven't already, select *Save a Copy* from the "File" menu to make a copy of the file that's just for you.

@n Click "Run", and evaluate `covid-table` in the Interactions Area. 

@n Take a look at the Definitions Area and find the "notes on columns". What is the start date for the data in this table? @fitb{}{@ifsoln{June 20, 2020}}

@n In the Definitions Area we see rows defined for Connecticut (`CT1`), Massachusetts (`MA1`) and Maine (`ME1`). +
@hspace{3em}What happens when you evaluate `MA1` in the Interactions Area? @fitb{}{@ifsoln{A single row of the table}}

@n Evaluate `CT1`. What information do you learn? @fitb{}{@ifsoln{1 day after 6/20/20, the state of}}

@fitb{}{@ifsoln{Connecticut had 44347 total positive covid cases.}}

@n Define three new Rows called `VT1`, `NH1` and `RI1` for Vermont, New Hampshire and Rhode Island. Click "Run" and test them out.

@hspace{3em}+a.+ How many people in *Vermont* tested positive on June 21st, 2020? @fitb{}{@ifsoln{1092}} +
@hspace{3em}+b.+ How many people in *New Hampshire* tested positive on June 21st, 2020? @fitb{}{@ifsoln{5178}} +
@hspace{3em}+c.+ How many people in *Rhode Island* tested positive on June 21st, 2020? @fitb{}{@ifsoln{15855}}

@n In Pyret, make a scatter plot showing the relationship between `day` and `positive`, using `state` as your labels, then sketch the resulting scatter plot below.
[.FillVerticalSpace, cols="2a,.^1a", options="grid",stripes="none",frame="none"]
|===
|
@center{
    @ifnotsoln{@image{../images/covid-grid.png, 400}}
    @ifsoln{@image{../images/covid-scatterplot.png, 350}}
}

|
--
@n In which state did the number of cases grow _fastest_?

@fitb{}{@ifsoln{MA}}

@vspace{5ex}

@n In which state did the number of cases grow _slowest_?

@fitb{}{@ifsoln{VT}}

@vspace{5ex}

@n Are these strong or weak relationship(s)?

@fitb{}{@ifsoln{strong}}
--
|===

@n What do you *Notice?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n What do you *Wonder?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}
