= Exploring the Covid Dataset
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
</style>
++++
For this page, you'll need to have the @starter-file{alg2-covid} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you.

@n Click "Run", and evaluate `covid-table` in the Interactions Area. Do you know what each column means?

[cols="1a,1a,1a", frame="none", stripes="none"]
|===
| *state* - the state reporting the data
| *day* - the number of days after June 20th, 2020
| *positive* - the number of new, positive cases reported
|===

@n Evaluate `CT1`, `MA1` and `ME1` in the Interactions Area. Which state(s) and day(s) are represented by these rows? @fitb{}{@ifsoln{CT, MA, and ME - day 1}}

@n How many total positive cases were reported in Massachusetts, as of 1 day after June 20th? @fitb{}{@ifsoln{104156}}

@n In the Definitions Area on the left, define two new Rows for Vermont (VT) and Rhode Island (RI) on lines 17 and 18. Click "Run" and test these Rows out in the Interactions Area.

@vspace{1ex}

[.FillVerticalSpace, cols="1a,1a", options="frame",stripes="none"]
!===
| @n In Pyret, make a scatter plot showing the relationship between `day` and `positive`, using `state` as your labels, then sketch the resulting scatter plot below.
|
--
Based on the scatter plot...

@n What do you *Notice?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n What do you *Wonder?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n In which state did the number of cases grow _fastest_? @fitb{}{@ifsoln{MA}}

@n In which state did the number of cases grow _slowest_? @fitb{}{@ifsoln{VT}}

@n Are these strong or weak relationship(s)? @fitb{}{@ifsoln{strong}}
--
!===

@n On or after line 23 (if you added new lines above) you'll find a Contract and Purpose Statement for a function called `is-MA`. Read them both carefully! What is the *Name* of this function? @fitb{10em}{@ifsoln{is-MA}} Its *Domain*? @fitb{10em}{@ifsoln{Row}} Its *Range*? @fitb{}{@ifsoln{Boolean}}

@n What do you _think_ @show{(code '(is-MA MA1))} will evalute to? @fitb{7em}{@ifsoln{true}}. @show{(code '(is-MA CT1))}? @fitb{7em}{@ifsoln{false}}. @show{(code '(is-MA ME1))}? @fitb{7em}{@ifsoln{false}}

@center{**Try typing each of these into the Interactions Area on the right. Were you correct?**}

@n In the Interactions Area, type @show{(code '(filter covid-table is-MA))}. What did this evaluate to? @fitb{}{} +
@fitb{}{@ifsoln{A Table just for data from Massachusetts}}

@n Type `MA-table` in the Interactions Area, then read the code on or after line 30 carefully. What is that code doing? @fitb{}{} +
@fitb{}{@ifsoln{Defining a new table called `MA-table`, which is all the rows from our original table where state is "MA"}}

@fitb{}{}