= Graphing Exponential Models: __f(x) = ab^x^ + k__
++++
<style>
.autonum { font-weight: bold; padding-top: 2px !important; }
.autonum:after { content: ')' !important; }
.fitb, .fitb.stretch::after, .fitbruby.stretch::after { padding-top: 0.9rem; }

/* Cut the padding under each section */
.sect1 { padding: 0 !important; }

.graph td {
  background-size: 100px 100px, 100px 100px, 20px 20px, 20px 20px !important;
  background-position: -3px 74px !important;
  height: 1.5in !important;
  width: 2in !important;
}
</style>
++++

[.linkInstructions]
For this page, you'll need to have *Slide 3: Exploring Exponential Models* of *Modeling Covid Spread (Desmos)* open on your computer. +
The curve you'll see is the graph of @math{h(x) = 2^x}. Another curve @math{f(x)} is hiding behind it. +
For starters, the values of the coefficients of @math{f(x)} have been set to make it equivalent to @math{h(x)} so @math{k=0}, @math{b=2} and @math{a=1}

== Base @math{b}
@n Make sure @math{k = 0} and @math{a=1}. Experiment with @math{b}. *For what values of @math{b} is the function _undefined_*, with the line disappearing? @fitb{}{@ifsoln{negative}}

@n Keeping @math{a=1} and @math{k=0}, change @math{b} to 0.5, 1, and 2, graphing each curve below. For each curve, *label the coordinates at x=1, 2, and 3.*


[.FillVerticalSpace.graph, cols="1,1,1", frame="none"]
|===
| @math{b=0.5} | @math{b=1}  | @math{b=2}
|===

@n What does @math{b} tell us about an exponential function, when @math{b > 1}? @fitb{}{@ifsoln{How quickly the function grows - }} +

@fitb{}{@ifsoln{literally the multiplier that says how quickly the growth intervals change}}

@n What does @math{b} tell us about an exponential function, when @math{0 < b < 1}? @fitb{}{@ifsoln{How quickly the function decays - }} +

@fitb{}{@ifsoln{literally the multiplier that says how quickly the decay intervals change}}

== Vertical Shift...and Horizontal Asymptote @math{k}
@n Keeping @math{a=1} and @math{b=2}, try changing the value of @math{k} to -10, 0, and 10, graphing each curve in the squares below. For each curve, find and label the y-value where the curve is "most horizontal", then *draw a horizontal line at that y-value*.


[.FillVerticalSpace.graph, cols="1,1,1", frame="none"]
|===
| @math{k=-10} | @math{k=0}  | @math{k=10}
|===

@n What does @math{k} tell us about an exponential function? @fitb{}{@ifsoln{How far the parabola is shifted up (positive k) or down (negative k),}} +
@fitb{}{@ifsoln{and where the curve levels out}}

== Initial Value @math{a}
@n Set @math{k=0} and @math{b=2}. Change the value of @math{a} to 10, 2, and -5, graphing each curve in the squares below. +
*For each curve, label the y-intercept (x=0).*


[.FillVerticalSpace.graph, cols="1,1,1", frame="none"]
|===
| @math{a=10} | @math{a=2}  | @math{a=-5}
|===

@n What does @math{a} tell us about an exponential function? @fitb{}{@ifsoln{The initial value of the function, when x=0}}

