= Functions: Contracts, Examples & Definitions

@description{Students learn to connect function descriptions across three representations: Contracts (a mapping between Domain and Range), Examples (a list of discrete inputs and outputs), and Definitions (symbolic).}

@lesson-prereqs{contracts}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* identify patterns where a function would be useful
* define their own function
* match examples, contracts, and definitions for the same function

| Student-Facing Lesson Goals
|
* I can explain why a function is useful.
* I can write my own function.
* I can connect contracts, examples, and definitions for a function.

| Materials
|[.materials-links]

@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/1B9mESkR0VtlWSF712C0p35d0fNF1kiv_Ar33wIK297c/, Lesson Slides}
}
@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1f58vvHsNgb-YumWEBH_J6o0L3Pc7AacBw-UxvCbYYIs/, Lesson Slides}
}

@material-links

| Preparation
| @preparation
|===

[.old-materials]
Click here to see the @link{https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/units/unit4/index.html, prior unit-based version}

== Three Representations of a Function @duration{55 minutes}

=== Overview
Students will practice describing functions using all 3 representations in @ifproglang{pyret}{Pyret} @ifproglang{wescheme}{WeScheme} syntax and test their code against the examples in the editor.

=== Launch

Have students open the @starter-file{bc}. They'll see the Contract, some Examples and the Function Definition for `gt`.

[.lesson-instruction]
What do you notice? What do you wonder?

[.lesson-point]
--
We know that...

@n Every function has a contract.

[.indentedpara]
@show{(contract "gt" '("Number" ) "Number")}

@n We can write examples illustrating how a function should work to help us identify the pattern.

@ifproglang{Pyret}{

[.indentedpara]
@image{images/examples-pyret.png, "gt Examples", 400}}


@ifproglang{WeScheme}{

[.indentedpara]
@image{images/examples-wescheme.png, "gt Examples", 400}}

@n Function definitions replace whatever changes in the examples with a variable describing what changes.

[.indentedpara]
@ifproglang{pyret}{@image{images/gt-fun-pyret.png, "gt Function Definition", 400}}
@ifproglang{wescheme}{@image{images/gt-fun-wescheme.png, "gt Function Definition", 500}}
--

[.lesson-instruction]
--
If we use the correct syntax, we can include all three of these function representations in our @ifproglang{pyret}{Pyret} @ifproglang{wescheme}{WeScheme} files. Let's take a look!

* Click *Run*.
@ifproglang{pyret}{
* What message do you get back? _Looks shipshape, all 5 tests passed, mate!_
* What do you think that message means?
** _The editor has checked to see whether the 5 examples work with the function definition and they do!_
}
* Change
@ifproglang{pyret}{`gt(10) is triangle(10, "solid", "green")` to `gt(15) is triangle(15, "solid", "green")`}
@ifproglang{wescheme}{`(EXAMPLE (gt 10) (triangle 10 "solid" "green"))` to `(EXAMPLE (gt 10) (triangle 15 "solid" "green"))`}
* Click run. What happens?
** _The editor lets us know that the function doesn't match the examples so that we can fix our mistake!_
--

[.lesson-point]
Examples not only help us to identify the pattern to define a function, they also let us double check that the functions we define do what we intend for them to do!

OPTIONAL: If students feel confident with the Circles of Evaluation but less confident about typing examples, use @opt-printable-exercise{MappingExamplesWithCOE.adoc} to make the connection explicit.

=== Investigate

Have students think about these three representations of functions by completing:

- @printable-exercise{match-examples-contracts.adoc}
- @printable-exercise{match-examples-definitions.adoc}
- @printable-exercise{create-contracts-examples.adoc}

And/or by completing these desmos card sort activities:

- @ifproglang{wescheme}{@opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/60aa50b7012000080d4136a0, Matching Examples & Contracts}}
@ifproglang{pyret}{@opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fc9328d18307e2e492ca0d8, Matching Examples & Contracts}}
- @ifproglang{pyret}{@opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fc536c0e2f06d0cd3992c68, Matching Examples & Function Definitions}}
@ifproglang{wescheme}{@opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/607b618988b17d447fe159e8?collections=5fece3d3e755260caa22904c, Matching Examples & Function Definitions}}

_There are many more materials for students to work with in the Additional Practice section at the end of the lesson!_

=== Synthesize

- What strategies did you use to match the @vocab{examples} with the @vocab{contracts}?
- What strategies did you use to match the @vocab{examples} with the @vocab{function definitions}?

== Defining bc and Other Functions

=== Overview
Using `gt` as an example, students will write the `contract`, `examples`, and `definition` for several other functions.

=== Launch
Have students turn to @printable-exercise{pages/contracts-examples-definitions.adoc}

[.lesson-instruction]
--
On the top half of the page you will see the contract, examples, and function definition for `gt`. Circle what is changing and label it with the word `size`. Using `gt` as a model, complete the contract, examples and function definition for `bc`.  Then type the Contract, Examples and Definition into the Definitions Area, click “Run”, and make sure all of the examples pass!

Thumbs up? Thumbs to the side? or Thumbs down? How confident do you feel that you could write the contract, examples and function definition on your own if you were given a word problem about another shape function?
--

=== Investigate

Have students complete @printable-exercise{pages/contracts-examples-definitions-stars.adoc} and @printable-exercise{pages/contracts-examples-definitions-name.adoc}.

As students work, walk around the room and make sure that they are circling what changes in the examples and labeling it with a variable name that reflects what it represents.

=== Synthesize
[.lesson-instruction]
- How were each of the representations helpful?
- Why is it important to write examples in our code?

== Additional Exercises

- @opt-printable-exercise{pages/examples-same-contracts1.adoc}
- @opt-printable-exercise{pages/examples-same-contracts2.adoc}
- @opt-printable-exercise{pages/match-contracts-examples1.adoc}
- @opt-printable-exercise{pages/match-contracts-examples2.adoc}

