= Making Flags
++++
<style>
.whiteBG img {background: white;}
.strategy-box .editbox { width: auto; }
.lesson-instruction .editbox {width: auto;}
</style>
++++

@lesson-description{Students compose the image functions they've learned, applying their knowledge of coordinates to position differently-shaped and transformed images to create flags of varying complexity.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-function-composition, alg-defining-values}

| Lesson Goals
| Students will be able to:

* Put one image on top of another, using the `put-image` function.
* Decompose complex images into parts. 
* Combine and manipulate images to create more complex images.

| Student-facing Goals
|
* I can put one image on top of another.
* I can make complex images like flags.

| Materials
|[.materials-links]

@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/1I5ljcgyfhKXkHiUbIIX0rE9KwTFpQ3x265bIeSsrPHQ/edit?usp=sharing, Lesson Slides}
* @link{https://www.wescheme.org/openEditor?publicId=jH25JejavW, Flags Starter File} 
* @link{https://www.wescheme.org/openEditor?publicId=RZrcCDD89Q, "Flags of Netherlands, Ireland, Mauritius Starter File"}
}

@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1HYLkBQ6aTK-nxsbLsWVaiUqOD8RQqx8WhzoSdfZTriU/edit?usp=sharing, Lesson Slides}
* @link{https://code.pyret.org/editor#share=1z3fDFl23HAlW8HBONANVI9Z7cWSMAUFa&v=8c4da7d, Flags Starter File}
* @link{https://code.pyret.org/editor#share=1-fMBwqwUBIz2JYNFHmNa159uFTAClGrF&v=8c4da7d, "Flags of Netherlands, Ireland, Mauritius Starter File"}
}

@material-links

@ifproglang{pyret}{
* [.ExercisePage]#@link{https://code.pyret.org/editor#share=13gXxlRal1Bi43mjodFh79ARGog8JdU1D&v=8c4da7d, Flag of Alaska Starter File}#
* [.ExercisePage]#@link{https://code.pyret.org/editor#share=1Z1dPVZv2THmPBTqaKgtwLtVdBSTJ4B29&v=8c4da7d, Flag of Lebanon Starter File}#
* [.ExercisePage]#@link{https://code.pyret.org/editor#share=1WbqiwGj5mFYltiB2lB2OYwWQ-E0h9X4h&v=8c4da7d, Flag of Puerto Rico Starter File}#
* [.ExercisePage]#@link{https://code.pyret.org/editor#share=1HH39t2rTH2DIoClabJ17MSqkYS9uUChY&v=8c4da7d, Flag of Trinidad and Tobago Starter File}#
}

@ifproglang{wescheme}{
* [.ExercisePage]#@link{https://www.wescheme.org/view?publicId=ve2gTEY06p, Flag of Alaska Starter File}#
* [.ExercisePage]#@link{https://www.wescheme.org/view?publicId=8mMKtpZiZ5, Flag of Lebanon Starter File}#
* [.ExercisePage]#@link{https://www.wescheme.org/view?publicId=6TJ0N2CJqU, Flag of Puerto Rico Starter File}#
* [.ExercisePage]#@link{https://www.wescheme.org/view?publicId=SQRHKcqQvW, Flag of Trinidad and Tobago Starter File}#
}

| Supplemental Resources
|
* @link{http://www.flagwizard.net/, Flag Wizard} - Searchable index of the world's flags, based on geometric properties and complexity.

| Preparation
|
* Make sure all materials have been gathered.
* Decide how students will be grouped in pairs.
* For some students, the use of graph paper for this activity will make a big difference!

| Key Points For The Facilitator
|
* The `put-image` function treats the second image as the first quadrant of a cartesian plane. Having students sketch their flag on a sheet of graph paper drives this point home, and makes the programming easier.
* This is an excellent opportunity to introduce students to __indenting code__. The difference between poorly-indented flag code and well-indented flag code is extremely noticable.

@include{xtra/lang-prereq.adoc}

|===


== Putting Images Together @duration{25 minutes}

=== Overview
Students learn about the `put-image` function.

=== Launch
As you've already seen, `overlay` sticks two images together, so that the _center_ of the first image is placed exactly on top of the _center_ of the second image. But what if we want to put the dot somewhere besides the center?

The `put-image` function works like `overlay`, but instead of placing the centers of each image on top of one another, it _translates_ the center of the top image by some distance in the x- and y-direction.

[.lesson-point]
--
Think of the background image as a sheet of graph paper with the origin (0,0) in the bottom left corner.

The numbers in `put-image` specify a point on that graph paper, with the center of the top image being placed there.
--

[.lesson-instruction]

- Distribute @exercise-link{japan-estimating-coordinates.adoc} or project the flag images from the peardeck. 
- The code beneath each image is missing the x and y coordinates to place the dot.  
- Estimate the x- and y-coordinate of the dot's location for each image and complete the code!

=== Investigate

Have students open the
@ifproglang{wescheme}{@link{https://www.wescheme.org/view?publicId=jH25JejavW, Flags Starter File}}
@ifproglang{pyret}{@link{https://code.pyret.org/editor#share=1z3fDFl23HAlW8HBONANVI9Z7cWSMAUFa&v=8c4da7d, Flags Starter File}}
, and click Run. 

There are some special lines in this file called *comments*. The programmer who wrote this code included a series of messages - called comments - that will never be read by the computer.  

[.lesson-point]
Professional programmers use comments __all the time__.

Professional programmers work with teams who need to be able to follow each other's thinking in order to collaborate efficiently. Comments are a way for programmers to leave notes for one another, and even for a single programmer to keep track of their thinking when _they_ come back to their code another day.

[.lesson-instruction]
- @ifproglang{wescheme}{Each language has its own symbol for commenting. In WeScheme, we use the semi colon (`;`) to tell the computer to ignore what we're typing. What color does the code turn when it has a semicolon in front of it? _Purple!_}
@ifproglang{pyret}{In Pyret, we use the number sign (`#`) to tell the computer to ignore what we're typing. What color does the code turn when it has a number sign in front of it? _Red!_}
- Type `japan-flag` into the Interactions Area. What do you get back?
- Type `japan` into the Interactions Area and compare the image to `japan-flag`.
- `japan` is composed using `dot` and `background`. Type each of those variables into the Interactions Area. What do you get back?
- Take a look at the `japan` code and fix it so that it matches the `japan-flag` image.
- What is the @vocab{Contract} for `put-image`? (Write it in your Contracts page!)

Have students open the
@ifproglang{wescheme}{@link{https://www.wescheme.org/view?publicId=RZrcCDD89Q, "Flags of Netherlands, Ireland, Mauritius Starter File"}}
@ifproglang{pyret}{@link{https://code.pyret.org/editor#share=1-fMBwqwUBIz2JYNFHmNa159uFTAClGrF&v=8c4da7d, "Flags of Netherlands, Ireland, Mauritius Starter File"} }
, and click Run. 

[.lesson-instruction]
--
- Look at the code for the flag of the Netherlands.
- How big is the flag?
- What was the programmer thinking when she coded the height of the red stripe as @show{(sexp->code `(/ 200 3))}?
- The center of the blue stripe is placed at (`150`, @show{(sexp->code `(/ 200 6))}).
- How did the programmer know to use 150 as the x-coordinate?
- What was the programmer thinking when she coded the y-coordinate as @show{(sexp->code `(/ 200 6))}?
- Explain the thinking behind coding the redstripe's y-coordinate as @show{(sexp->code `(* 5 (/ 200 6)))}.
--

Once you've discussed the code for the flag of the Netherlands with your class, have them keep working with this starter file to write code for the flags of Ireland and Mauritius.  Some students will make it through the challenges. Some students may only complete one flag. All of them will be synthesizing how to apply put-image and locate images on the coordinate grid.

=== Synthesize

Could we completely replace `overlay` with `put-image`? Why or why not?

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Going Deeper}

If you have time, we have lots of additional starter files to push student thinking linked in the additional exercises at the end of this lesson and now would be the time to dive into them!
|===

== Making Flags @duration{25 minutes}

=== Overview
Students focus on decomposing complex images into simple ones, and using `put-image` to combine them.

=== Launch
Let's dig into the process for how the flags we’ve seen so far were made:

*1) Decompose the Image*

We observe that the Japanese flag is made up of two simpler images: a black, outline rectangle and a red dot.


*2) Define those parts*

We define `dot` and `background`. Once we’ve defined those images, we test them out in the Interactions Area to make sure they look right!


*3) Find the Coordinates*

For each image, calculate what the x- and y-coordinates of the center should be. __TIP: this is a lot easier if you have a sheet of graph paper handy!__


*4) Build the Image & Check that it Matches the Target Image*

We stack the parts on top of the bottom image using the coordinates we found.
 __TIP: don't cram all the code into one line! If you break it up into new lines (for example, hitting "Return" before the x-coordinate and after the y-coordinate), you'll notice that the code forms a "staircase" pattern.__ Be sure to compare the image you get with the target image!

 @ifproglang{pyret}{
 If you have time, these matching activities will support student thinking.
 - @activity-link{https://teacher.desmos.com/activitybuilder/custom/5fc53aeef328540d3ad2123c, Scaling Flag Ratios (Desmos Activity)}
 -@activity-link{https://teacher.desmos.com/activitybuilder/custom/5fc90f1289c78e0d2a5bccfc, Matching Code to Images using overlay and put-image (Desmos Activity)}
 }

=== Investigate

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Paper Flag Models to Code}
In this next exercise, students will be decomposing the image of a flag. For a more tactile experience, you could have students construct images of the flags they choose using construction paper. This should happen between the step where they describe the shapes needed to compose the flags image and write the code to build the image.  The act of physically building the flag from layers of paper makes the layering of the coded images visible and helps students to remember that white space is not just "blank".
|===

[.lesson-instruction]
--
- Turn to @workbook-link{decomposing-flags.adoc}, and choose ONE flag to focus on. On the blank lines below, describe the parts that make up that flag.

- Once you're done, return to the 
@ifproglang{wescheme}{@link{https://www.wescheme.org/view?publicId=PYN3JaBTzy, Flags Starter File}}
@ifproglang{pyret}{@link{https://code.pyret.org/editor#share=1QEz7p-AVDMd3xmuJCvh2YRHSt8uF82CW, Flags Starter File}}
and define those parts.

- Then, compose those parts using `put-image`, and make your flag!
--

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Around the World in your Classroom}
The opportunity to focus on a flag of their choosing is a big motivator for students. Coding flags also presents a rare opportunity for students to share a piece of their identity in math class. If you have more time to devote, we highly encourage you to give students the opportunity to create the image of a flag they connect with in some way.  Students might choose the flags of countries related to their heritage, a place they’ve visited, a country they’re interested in, or a group they identify with or support.  Encourage students to choose an appropriately challenging flag.  The teacher may introduce parameters if necessary, such as “Flags need at least 5 different shapes”.  This is intended to be a summative project, so encourage students to demonstrate what they’ve learned. Once students have coded their flags, host a tour of the flags of the world in your classroom!

Be mindful of the fact that not every student will know their family’s geographical history, and 
that immigration can be a sensitive topic for some students.  For this reason, it is important that students have the option to choose a flag based on interest instead of just family history.   

Be prepared that students might choose flags representing groups other than countries.  Indigenous students might choose a flag that represents their indigenous nation or the American Indian Movement. Students might also choose to focus on the pride flag (representing solidarity amongst members of the LGBTQ community) or an ethnic flag (representing solidarity amongst members of different ethnic groups, such as the Hispanic flag).  There are also some flags that represent political or activist groups.  It is important for the teacher to be open to different beliefs and ideologies, but it is also up to the teacher’s discretion as to whether or not a flag is appropriate for use in this project. Flags associated with hate groups, or any institution that denies the dignity of other students, are not appropriate.

@link{http://www.flagwizard.net/, Flag Wizard} offers a searchable index of the world's flags and may be useful to students looking for ideas. Flags are listed with their width:length ratios in the opposite order of how we define the sides of a flag in code. e.g. 2:3 could be scaled up to a 300 x 200 flag or 8:11 could be scaled up to 330 by 240.
|===

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Ratio and Proportion}

Have students define the `WIDTH` and `HEIGHT` of their flags as values, and then __replace the numbers in each flag__ with expressions relative to width and height. For example, if the `dot` in the Japanese flag is at (150, 100), those numbers would be replaced with @show{(sexp->code `(/ WIDTH 2))} and @show{(sexp->code `(/ HEIGHT 2))}.
|===

=== Synthesize

Which flags were the easiest to make? The hardest?

Why is it useful to define each part of the flag first, before stitching 

== Additional Exercises

- For students who could use more scaffolding between overlay and put-image, use @workbook-link{combining-images.adoc}.

- For a quick dive into why it’s more efficient to define shapes before building the image, open 
@ifproglang{pyret}{@link{https://code.pyret.org/editor#share=13gXxlRal1Bi43mjodFh79ARGog8JdU1D&v=8c4da7d, the Alaska Flag Starter Code.}} 
@ifproglang{wescheme}{@link{https://www.wescheme.org/view?publicId=ve2gTEY06p, the Alaska Flag Starter Code.}}

- For practice scaling imported graphics, open @ifproglang{pyret}{@link{https://code.pyret.org/editor#share=1Z1dPVZv2THmPBTqaKgtwLtVdBSTJ4B29&v=8c4da7d, the Flag of Lebanon Starter Code.}}
@ifproglang{wescheme}{@link{https://www.wescheme.org/view?publicId=8mMKtpZiZ5, the Flag of Lebanon Starter Code.}}

- For practice with composing more complex images, fix @ifproglang{pyret}{@link{https://code.pyret.org/editor#share=1WbqiwGj5mFYltiB2lB2OYwWQ-E0h9X4h&v=8c4da7d, this Code for the Puerto Rican flag.}}
@ifproglang{wescheme}{@link{https://www.wescheme.org/view?publicId=6TJ0N2CJqU, this Code for the Puerto Rican flag.}}

- If you’ve already studied Pythagorean Theorem and are ready to apply it, open @ifproglang{pyret}{@link{https://code.pyret.org/editor#share=1HH39t2rTH2DIoClabJ17MSqkYS9uUChY&v=8c4da7d, the Flag of Trinidad and Tobago Starter Code.}} 
@ifproglang{wescheme}{@link{https://www.wescheme.org/view?publicId=SQRHKcqQvW, the Flag of Trinidad and Tobago Starter Code.}}
