= Function Composition 3

@lesson-description{Students take a closer look at how functions can work together by investigating the relationship between revenue, cost, and profit}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Explain the pros and cons of functions that depend on each other
* Write a function that explicitly uses another function

|Student-Facing Lesson Goals
|
* I can explain the pros and cons of functions that use other functions.
* I can write a function that uses another function.

|Key Points for the Facilitator
|
* There are several ways to write the profit function - use this opportunity for discussion and to promote higher-order critical thinking.
* If students are struggling with understanding the basis of the problem, start by coming up with examples of cost and revenue.  If Sally sells one glass, what is her total revenue?  How much does it cost her to produce that one glass?
* Ensure students understand the difference between "revenue" and "profit", and that "cost" refers to the cost of making the lemonade, not the amount Sally is charging.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.
* Students should be familiar with the Design Recipe.

|Materials
|
* https://docs.google.com/presentation/d/1PRpzz2bIL-JH9B-5hZJarbO4COGtl0HhCiAWFiG8mjo/view[Google Slides]

Bootstrap Formative Assessments


* @link{https://quizizz.com/admin/quiz/5cdcb223862fd8001a135579, Bootstrap: Algebra - Coordinates, Circles of Evaluation, & Code} (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb288f41b366950eba1e1, Bootstrap:Algebra - Data Types & Circles of Evaluation} (Desmos Activity)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb336f41b366950eba420, Bootstrap:Algebra - Circles of Evaluation Review(Blank Template)} (Desmos Activity)
* @link{https://quizizz.com/admin/quiz/5cdcb3907f8c98001a203c1b, Bootstrap:Algebra - Contracts, Domain/Range, Data Types, & Functions } (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb3f555e3fb606a1f1ba2, Bootstrap:Algebra - Data Types, Circles of Evaluation, and Contracts} (Desmos Activity)

Connection Activities

* https://www.geogebra.org/m/nqymeFc4[Function Composition Dynamic Illustrator I ] (Geogebra)
* https://www.geogebra.org/m/h3qdzW3W[Composition of Function] (Geogebra Quiz)
* https://quizizz.com/admin/quiz/58a61a2cf0b089151011ef50/composition-of-functions[Composite Functions] (Quizizz)

|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Addressing Math Standards (CCSS)
|
* @std{HSF.BF.A.1.B}

|CS Standards
|
*
|===


== Get Ready:

Students should have their computer, contracts page, and pencil.

== Launch: (5 min)

"Lemonade" WODB - Have students select one that they want to discuss and group up.  Walk among the groups and encourage mathematical discussion of the image.

== Explore: (10 min)

Students complete "Sally's Lemonade" workbook page and brainstorm their ideas for functions.

[.strategy-box]
.Strategies for English Language Learners
****
MLR 7 - Compare and Connect
There are several correct ways to write the functions needed for Sally's Lemonade.  Have students compare methods and develop understanding and language related to mathematical representation and methods.  What are the advantages of the different solutions?  What are some drawbacks?
****

== Discuss: (10 min)

* *What functions could help Sally better manage her lemonade stand?*
+
_revenue, cost, profit_
* *What is the difference between _revenue_ and _profit_?*
+
_Revenue is the total amount of money that comes in, profit is the remaining money after cost has been subtracted._
* *How could Sally _increase_ her profits?*
+
_By decreasing her costs, raising her prices (which increases revenue), by selling more lemonade_
* *What is the _relationship_ between profit, cost, and revenue?*
+
_Profit = Revenue - Cost_

== Apply (15 min)

Students work with their partners to develop their
function models for
@worksheet-link{FunctionComposition3/workbook-pages/FunctionComposition3-WB1.adoc,
revenue},
@worksheet-link{FunctionComposition3/workbook-pages/FunctionComposition3-WB2.adoc,
cost}, and
@worksheet-link{FunctionComposition3/workbook-pages/FunctionComposition3-WB3.adoc,
profit}, using the Design Recipe.

While students are working, walk the room and gauge student understanding.  There is more than one correct way to write the profit function (see sample responses below).  Encourage discussion between students and push students to develop their thinking on the advantages and disadvantages of each correct solution.

