= Exploring the Countries Dataset

++++
<style>
/* Make autonums inside tables look consistent with those outside */
td .autonum::after { content: ')' !important; }
td li+li { margin-top: 15px !important; }
td { padding-top: 0 !important; padding-bottom: 0 !important; }
</style>
++++

@link-instructions{
For this section, you'll need the  @starter-file{alg2-countries} open on your computer. If you haven't already, select *Save a Copy* from the "File" menu to make a copy of the file that's just for you. The columns in this dataset are described in the left column below:
}

@vspace{1ex}

[cols=".^1a,2a", frame=none, stripes=none]
|===
|
- *country* -- name of the country
- *gdp* -- total Gross Domestic Product of the country. GDP is often used to measure the economic health of a country.
- *population* -- number of people in the country
- *pc-gdp* -- the average GDP _per-person_, in US Dollars
- *has-univ-healthcare* -- indicates if the country has universal healthcare
- *median-lifespan* -- the median life expectancy of people in the country

| *In Pyret, make a scatter plot showing the relationship between `pc-gdp` and `median-lifespan`, and sketch it below.*

@center{
@ifnotsoln{@image{../images/blank-graph.png, 400}}
@ifsoln{   @image{../images/soln-graph.png,  400}}
}
|===

@n What do you *Notice* about the point cloud? @fitb{}{} +
@fitb{}{} +

@n What do you *Wonder* about the point cloud? @fitb{}{} +
@fitb{}{} +

@n Do you see a relationship? If so, describe it (e.g. linear or nonlinear? Strong or weak?)

@blanklines{2}{
@ifsoln{There seems to be a somewhat strong, nonlinear relationship}
}

@n Find the point for Equatorial Guinea, an outlier with `pc-gdp` = $38,058 and `median-life-expectancy` = 65. Can you think of a reason why this point might be so far from the rest?

@blanklines{2}{
@ifsoln{Answers will vary -- perhaps a war or disease is causing people to die young?}
}

@n Find the point for Japan, another outlier with `pc-gdp` = $43,030 and `median-life-expectancy` = 85.5. Can you think of a reason why this point might be so far from the rest?

@blanklines{2}{
@ifsoln{Answers will vary -- maybe Japanese people have healthier diets?}
}

@n Are there any countries that stand out? Why or why not? @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n Suppose a wealthy country is suffering heavy casualties in a war. Draw a star on the scatter plot, showing where you might expect it to be.

