= Do People in Rich Countries Live Longer?
++++
<style>
table { width: 300px !important; margin-left: 0.5in; }
th { text-align: center !important; }
</style>
++++

@link-instructions{
- *Median life expectancy* is a measure of what a "typical lifespan" is for people in each country
- *Per-Capita GDP* is a measure of what a "typical income" is for people in each country (in thousands of US Dollars).

@vspace{1ex}

A point at (75, 62) would represent a country where the average GDP is $75,000/year and the median life expectancy is 62 years old.
}

@n In 2016, the United States had a median life expectancy of *80.1 years*, and a per-capita GDP of $58,890. Plot this point on the graph.

@n In the table below, fill in your best guess for the median life expectancy for people in a country with each per-capita GDP:

[cols=">1,1", options="header"]
|===
| Per-Capita GDP		| Median Life Expectancy
|   $5,000				|
|  $25,000				|
| $125,000				|
| $150,000				|
|===

@vspace{1ex}

@n Plot each row of the table as points on the graph, using _Per-Capita GDP_ as the x-coordinate and _Median Life Expectancy_ as the y-coordinate.

@n Using your points as a guide, sketch the line that _you_ think represents the relationship between median life expectancy and per-capita GDP.

@center{@image{../images/blank-graph.png, 650}}
