= Do People in Rich Countries Live Longer?
++++
<style>
table { width: 500px !important; margin: 1ex auto !important; }
th { text-align: center !important; }
th, td { padding: .25em .625em !important; }
</style>
++++

@link-instructions{

- *Per-capita GDP* is a measure of what a "typical income" is for people in each country (in thousands of US Dollars).
- *Median lifespan* is a measure of what a "typical lifespan" is for people in each country

@vspace{1ex}

A point at (75, 62) would represent a country where the average GDP is $75,000/year and the median lifespan is 62 years old.

The table below shows the per-capita GDP and median life expectancy for three different countries.
}

[cols="1,^1,^1", options="header"]
|===
| Country		| Per-Capita GDP ($)	| Median Lifespan (years)
| Mozambique	|   $1,843				| 54.1
| Pakistan		|   $5,085				| 68.4
| Poland		|  $29,176				| 77.9
| Luxembourg	| $103,511				| 82.4
|===

@n *Plot these four countries* as points on the graph below.

@n Use your _best guess_ to *draw a curve* that fits all four points.

@n *Plot the points on your curve* corresponding to the four per-capita GDPs below. What does your curve predict the median lifespan to be, at each of these points?

[cols="1,^1,^1", options="header"]
|===
| Country		| Per-Capita GDP ($)	| Median Lifespan (years)
| Country A 	|   $5,000				| @ifsoln{Answers will vary}
| Country B 	|  $25,000				| @ifsoln{Answers will vary}
| Country C 	| $125,000				| @ifsoln{Answers will vary}
| Country D 	| $150,000				| @ifsoln{Answers will vary}
|===

@center{@image{../images/blank-graph.png, 500}}

@n What do you *Notice* about the shape of the curve? Does it look like one of the functions we've seen before? @fitb{}{} +
@fitb{}{} +
@fitb{}{}
