= Discover Inverse Operations: Addition & Subtraction (2)
++++
<style>
table {grid-template-rows: 3fr 1fr !important;}
div.circleevalsexp .value,
div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }

td:nth-child(2) span.arrow::before { content: 'CP'; }
td:nth-child(4) span.arrow::before { content: 'AI'; }
</style>
++++

== What if the expression _starts_ with a negative value?

@n In the example below, we've applied the Commutative Property ("CP") and then the Additive Inverse Property ("AI") to rewrite an addition expression as subtraction.

[cols="^.^4,^.^1,^.^4,^.^1,^.^4", stripes="none"]
|===
| Start here:   | | Apply the Commutative Property: | | Apply the Additive Inverse Property:
|@show{(coe '(+ -4 7))}  | @arrow | @show{(coe  '(+ 7 -4))} | @arrow | @show{(coe  '(- 7 4))}
| @math{-4 + 7}|  | @math{7 + -4} | | @math{7 - 4}
|===

@n What will the first Circle evaluate to? @fitb{5em}{3}  @hspace{5em} The second Circle? @fitb{5em}{3}  @hspace{5em} The third Circle? @fitb{5em}{3}

@n What do you Notice about these three Circles? What do you Wonder? @fitb{}{}

@fitb{}{} +
@fitb{}{}

@vspace{1ex}

@n Look at the worksheet you just completed. Why is there an additional step in rewriting the addition expressions above? @fitb{}{}

@fitb{}{}

@vspace{1ex}

@n In the table below, draw another example like the one above to show how we can rewrite more complex addition expressions as subtraction.

[cols="^.^4,^.^1,^.^4,^.^1,^.^4", stripes="none"]
|===
| Start here:   | | Apply the Commutative Property: | | Apply the Additive Inverse Property:
|@show{(coe '(+ (?ANS -8) (?ANS 5)))}  | @arrow | @show{(coe  '((?ANS +) (?ANS 5) (?ANS -8)))} | @arrow | @show{(coe  '((?ANS -) (?ANS 5) (?ANS 8)))}
| @math{+}|  | @ifsoln{@math{5 + -8}} | | @ifsoln{@math{5 - 8}}
|===


== Try it out

@vspace{1ex}

Rewrite addition as subtraction, and subtraction as addition.

[cols="^.^3,^.^3,^.^3", stripes="none"]
|===
| @math{-50 + 5 =} @fitb{10em}{@ifsoln{@math{5 - 50}}}
| @math{-8 + 4 =} @fitb{10em}{@ifsoln{@math{4 - 8}}}
| @math{100 - 101 =} @fitb{10em}{@ifsoln{@math{100 + -101}}}

| @fitb{10em}{@ifsoln{@math{6 + -18}}} @math{= 6 - 18}
| @fitb{10em}{@ifsoln{@math{0 - 12}}} @math{= 0 + -12}
| @fitb{10em}{@ifsoln{@math{6 + -36}}} @math{= 6 - 36}
|===

