= Discover Inverse Operations: Addition & Subtraction
++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  .circleevalsexp .value,
  .circleevalsexp .studentBlockAnswerFilled { min-width:unset; }

  .autonum { padding-top: 1rem !important; }
  .center{ padding: 0; }
</style>
++++

== From Adding to Subtracting

@n Under each Circle of Evaluation, write the equivalent arithmetic expression.

[cols="^.^5,^.^1,^.^5", stripes="none"]
|===
|@show{(coe  '(+ 10 -3))}       | @math{=}  | @show{(coe '(- 10 3))}
|@math{+}                       |@math{=}   | @ifsoln{@math{-}}
|===

@n What will the first Circle evaluate to? @fitb{5em}{@ifsoln{@math{7}}} @hspace{12em} The second Circle? @fitb{5em}{@ifsoln{@math{7}}}

@n What do you Notice? What do you Wonder? @fitb{}{@ifsoln{Both expressions produce 7. One has addition and one has subtraction. One has @math{3} and one has @math{-3}}}

@fitb{}{}

@center{*Did you know that adding @math{-3} is the same as subtracting @math{3}?*}

@n In the table below, fill in the blanks to demonstrate how _adding a negative_ produces the same result as _subtracting a positive._ Then write the equivalent arithmetic expression for each of your Circles.

[cols="^.^5,^.^1,^.^5", stripes="none"]
|===
| @show{(coe  '(+ 30 -5))} 
| @math{=} 
| @show{(coe '(- (?ANS 30) (?ANS 5)))}

| @ifnotsoln{@math{+}}     @ifsoln{@math{30 + -5}}       
| @math{=}
| @ifnotsoln{@math{-}}     @ifsoln{@math{30 - 5}}  
|===

@n This time, we've completed the _subtraction_ Circle of Evaluation. You fill in the equivalent addition Circle of Evaluation.

[cols="^.^5,^.^1,^.^5", stripes="none"]
|===
| @show{(coe  '(+ (?ANS 2) (?ANS -10)))} 
| @math{=} 
| @show{(coe  '(- 2 10))}

| @ifnotsoln{@math{+}}     @ifsoln{@math{2 + -10}}       
| @math{=}
| @ifnotsoln{@math{-}}     @ifsoln{@math{2 - 10}}  
|===


== Try it out

Complete the table by rewriting each addition expression as subtraction, and each subtraction expression as addition.

[cols="^.^10,^1,^.^10", stripes="none"]
|===
| @math{30 - 12}              | = | @ifsoln{@math{30 + -12}}
| @math{24 + -4}              | = | @ifsoln{@math{24 - 4}}
| @math{100 - 101}            | = | @ifsoln{@math{100 + -101}}
| @ifsoln{@math{6 + -18}}     | = | @math{= 6 - 18}
| @ifsoln{@math{0 - 12}}      | = | @math{= 0 + -12}
| @ifsoln{@math{6 + -36}}     | = | @math{= 6 - 36}
|===