= Inverted Images (continued)

[.no-flex-section]
== Are they Inverses?

Decide whether or not each pair of images are inverses or not. If `blend-images` wouldn't produce a gray shape, explain why not.

[cols="^.^4a,^10,10", grid="none", frame="none"]
|===
| | | 
| @ifsoln-choice{inverses} +
{empty} +
not inverses
| @image{../images/butterflies.png} +
`butterfly` @hspace{6em} `butterfly2`
| @blanklines{4}{}

| inverses +
{empty} +
@ifsoln-choice{not inverses}
| @image{../images/tractors.png} +
`tractor` @hspace{6em} `tractor2`	 
| @blanklines{4}{@ifsoln{They would be inverses, except that they are facing the opposite direction.}}

| inverses +
{empty} +
@ifsoln-choice{not inverses}
| @image{../images/moon-people.png, 215} +
`moon` @hspace{6em} `moon2`
| @blanklines{4}{@ifsoln{They would be inverses, except one image has stars and the other doesn't}}

| inverses +
{empty} +
@ifsoln-choice{not inverses}
| @image{../images/image-C-D.png} +
`imageC` @hspace{6em} `imageD`	 
| @blanklines{4}{@ifsoln{They would be inverses, except that the gray colors aren't inverses of each other.}}
|===

@link-instructions{Test your thinking using the @starter-file{additive-inverse}.}


== What does it mean to `invert` a color image?

@n What would you expect to happen if we `invert` a blue square? Why? @fitb{}{}

@fitb{}{@ifsoln{Answers will vary. *An orange square?* would be the most obvious guess since orange is across the color wheel from blue.}}

@n Test it out. What happens? @fitb{}{@ifsoln{a yellow square}}

@n Make a prediction. What will    @show{(code '(blend-images blue-square(invert blue-square)))}   produce? @fitb{}{@ifsoln{A gray square.}}

Why? @fitb{}{@ifsoln{It doesn't matter what color an image and its inverse are, they are still inverses of each other and blend to gray!}}

@star Make and test predictions about what would happen if you `invert` each of the other shapes defined in the file. Record your notices and wonders.