= Exploring Displays

++++
<style>
#content .fitb{ margin-top: 0.5ex !important; min-width: 1.5em; }
#content img { max-height: 2in !important; display: block;}
.text { position: absolute; bottom: 0; text-align: left; width: 95%; }
td { padding: 0 !important; }
</style>
++++

Using the contracts provided and the @starter-file{animals}, make each type of display below in Pyret. +
Then sketch the displays and answer the questions.


[cols="^1a,^1a",stripes="none",options="header"]
|===
2+| Bar Charts @show{(contract "bar-chart" '("Table" "String") "Image")}
2+| @fitbruby{10em}{@ifsoln{bar-chart}}{function-name} (@fitbruby{20em}{@ifsoln{animals-table}}{table-name {two-colons} Table}, @fitbruby{15em}{@ifsoln{Answers will vary!}}{column-name {two-colons} String})
| Sketch a bar chart below.
@ifsoln{@image{../images/image/bar-chart.png}}
|
[.FillVerticalSpace, cols="1a", stripes="none", frame="none"]
!===
! Display summarizes 1 column of @fitbruby{10em}{@ifsoln{categorical}}{categorical/quantitative} data.
! What do you think this kind of display tells us?
!===
|===


[cols="^1a,^1a",stripes="none",options="header"]
|===
2+| Pie Charts @show{(contract "pie-chart" '("Table" "String") "Image")}
2+| @fitbruby{10em}{@ifsoln{pie-chart}}{function-name} (@fitbruby{20em}{@ifsoln{animals-table}}{table-name {two-colons} Table}, @fitbruby{15em}{@ifsoln{Answers will vary!}}{column-name {two-colons} String})
| Sketch a pie chart below.
@ifsoln{@image{../images/image/pie-chart.png}}
|
[.FillVerticalSpace, cols="1a", stripes="none", frame="none"]
!===
! Display summarizes 1 column of @fitbruby{10em}{@ifsoln{categorical}}{categorical/quantitative} data.
! What do you think this kind of display tells us?

@fitb{}{@ifsoln{The count of each value in a categorical column...}}

@fitb{}{@ifsoln{including bars for values that are NOT represented}}

@fitb{}{}
!===
|===


[cols="^1a,^1a",stripes="none",options="header"]
|===
2+| Box Plots @show{(contract "box-plot" '("Table" "String") "Image")}
2+| @fitbruby{10em}{@ifsoln{box-plot}}{function-name} (@fitbruby{20em}{@ifsoln{animals-table}}{table-name {two-colons} Table}, @fitbruby{15em}{@ifsoln{Answers will vary!}}{column-name {two-colons} String})
| Sketch a box plot below.
@ifsoln{@image{../images/image/box-plot.png}}
|
[.FillVerticalSpace, cols="1a", stripes="none", frame="none"]
!===
! Display summarizes 1 column of @fitbruby{10em}{@ifsoln{quantitative}}{categorical/quantitative} data.
! What do you think this kind of display tells us?

@fitb{}{@ifsoln{The range of quantitative values in the bottom quarter, top quarter, and the middle quarters.}}

@fitb{}{@ifsoln{This tells us something about the spread of the
data}}

@fitb{}{}
!===
|===


[cols="^1a,^1a",stripes="none",options="header"]
|===
2+| Histograms @show{(contract "histogram" '("Table" "String" "Number") "Image")}
2+| @fitbruby{10em}{@ifsoln{histogram}}{function-name} (@fitbruby{20em}{@ifsoln{animals-table}}{table-name {two-colons} Table}, @fitbruby{15em}{@ifsoln{Answers will vary!}}{column-name {two-colons} String} @fitbruby{9em}{@ifsoln{Answers will vary!}}{bin-width {two-colons} Number})
| Sketch a histogram below.
@ifsoln{@image{../images/image/histogram.png}}
|
[.FillVerticalSpace, cols="1a", stripes="none", frame="none"]
!===
! Display summarizes 1 column of @fitbruby{10em}{@ifsoln{quantitative}}{categorical/quantitative} data.
! What do you think this kind of display tells us?

@fitb{}{@ifsoln{How many values in a quantitative column fall into equally-sized bins.}}

@fitb{}{@ifsoln{This tells us something about the spread of the data.}}

@fitb{}{}
!===
|===
