= Matching Examples and Contracts

++++
<style>
td { height: 20pt; }
p { font-size: 0.9rem;}
div.circleevalsexp, .editbox, .cm-s-scheme {font-size: .75rem;}

td:first-child {border-bottom: 1pt solid gray !important;}

</style>
++++

@do{(define e1
   (code #:multi-line #t
"(EXAMPLE (f \"pink\" 5)
  (star 5 \"solid\" \"pink\"))
(EXAMPLE (f \"blue\" 8)
  (star 8 \"solid\" \"blue\")"))

(define c1 (code "f {two-colons} String, Number -> Image"))

(define e2
   (code #:multi-line #t
"(EXAMPLE (f 1)
  (rectangle  1 1 \"outline\" \"red\"))
(EXAMPLE (f 6)
  (rectangle 6 6 \"outline\" \"red\"))"))

(define c2 (code "f {two-colons} Number -> Image"))

(define e3
   (code #:multi-line #t
"(EXAMPLE (f \"Hi!\")
  (text(\"Hi!\", 50, \"red\"))
(EXAMPLE (f \"Hola!\")
  (text(\"Hola!\", 50, \"red\"))
(EXAMPLE (f \"Ciao!\")
  (text(\"Ciao!\", 50, \"red\")"))

(define c3 (code "f {two-colons} String -> Image"))

(define e4
   (code #:multi-line #t
"(EXAMPLE (f 5 \"outline\")
  (star 5 \"outline\" \"yellow\"))
(EXAMPLE (f 5 \"solid\")
  (star 5 \"solid\" \"yellow\"))"))

(define c4 (code "f {two-colons} Number, String -> Image"))

(define e5
   (code #:multi-line #t
"(EXAMPLE (f 5)(/ 5 2))
(EXAMPLE (f 9)(/ 9 2))
(EXAMPLE (f 24)(/ 24 2))"))


(define c5 (code "f {two-colons} Number -> Number"))
}

Match each set of examples (left) with the contract that best describes it(right).

@vspace{1ex}
[cols="<10a,^2a,1,^1a,>8a",stripes="none",grid="none",frame="none", options="header"]
|===
|  Examples|  || |Contract
| @show{e5}
| *1* @showsoln{"*A*" }|| *A* | @show{c5}
@vspace{1ex}
| @show{e2}
| *2* @showsoln{"*C*" }|| *B* | @show{c3}
@vspace{1ex}
| @show{e1}
| *3* @showsoln{"*E*" }|| *C* | @show{c2}
@vspace{1ex}
| @show{e3}
| *4* @showsoln{"*B*" }|| *D* | @show{c4}
@vspace{1ex}
| @show{e4}
| *5* @showsoln{"*D*" }|| *E* | @show{c1}
|===
