= Function Composition

@description{Students learn to combine image transformation functions using Circles of Evaluation.}

@lesson-prereqs{order-of-operations, contracts}

@keywords{}

@add-to-lang{flip-horizontal, flip-vertical, rotate, scale, above, beside, overlay}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* Use functions as building-blocks, composing them to achieve a desired affect
* Diagram function composition using the Circles of Evaluation
* Compose functions when programming

| Student-facing Goals
|
* Let's learn to use functions as building blocks that can be combined or composed to achieve desired outcomes.
* Let's use Circles of Evaluation to show how functions can be composed.

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links
* @link{https://www.google.com/search?q=random+number, Random Integer Generator}
* @lesson-link{project-logo}

|Preparation
| * There is an optional interactive Desmos activity in the lesson. If you would like to use it, decide how you will share it with students and, if you are using our Google Slides, add the appropriate link to the slide deck. _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}

| Key Points For The Facilitator
|
* Check frequently for understanding of @vocab{data types} and @vocab{contracts} during this lesson and throughout subsequent lessons.
* When students encounter errors, encourage them to check their @dist-link{Contracts.shtml, contracts} @pathway-only{(which, if you're using a printed workbook, are included in the back)} and show their work using Circles of Evaluation.
|===

== Composing Functions @duration{10 minutes}
Students are given a scaffolded activity that forces them to use the output of one function as the input to another - to _compose_ them.

=== Launch
@teacher{
- Divide students into groups of 3 and distribute a set of @handout{function-cards.adoc} to each group. __(If you're teaching remotely you can use the @opt-starter-file{functioncardsDesmos} instead.)__
- Write down pairs of integers on the board, representing the "starting numbers" and "ending numbers". These integers should range from -50 to +50, but you can change the difficulty of the activity by making that span wider (more difficult) or more narrow (less difficult). You can find a random integer generator @link{https://www.google.com/search?q=random+number, here}.
- Have students practice reading contracts by asking them questions about one or two of these cards.
}

@lesson-instruction{
* Pick a card at random.
* According to its Contract, what is the function's Name, Domain, and Range?
}

These cards represent a collection of functions, each of which takes an input and produces an output. For example, we can start with the number `4`, and give it to the function `add6`. The output will be `10`.

We can also _compose_ functions, meaning that the output of one is immediately passed into another. For example, we could compose `add6` `4` and `double`, so the `10` gets passed into the next function, and doubled to produce `20`.

And, if we composed `add6` `4` with `double` _and_ with `half`? _We'd get 10._

=== Investigate

@lesson-instruction{
- For each of the starting numbers on the board, your job is to figure out which functions to compose in order to get to the end.
- You will need to use some functions more than once, and that's okay!
}

Give students time to experiment with this!

@teacher{Make the activity more challenging:

* ask students to find the shortest path from start to end, using the smallest number of compositions.

Other ways to play: Show students a starting number and an ending number and...

* _ask them to give a card back._
* _ask them which cards are the most valuable._
* _give them a blank card and let them come up with a new function._
}

=== Synthesize
If two groups come up with different compositions that achieve the same end result, have them share their ideas!

== Composing Functions in Code @duration{20 minutes}

=== Overview

The Circles of Evaluation are extended to functions that do more than compute values.

=== Launch
Explain to students that the functions available to them in @proglang can be composed just like the Function Cards from the activity. Their job as programmers is to figure out how to compose functions to achieve their goals in the most clever or elegant way possible.

=== Investigate

@lesson-instruction{
- Have students open @starter-file{program-list} in their browser, and @ifproglang{wescheme}{"Log In"} @ifproglang{pyret}{"Sign In"} using a valid Google account (Gmail, Google Classroom, YouTube, etc.) and their password for that account.
- This will take them to the "Programs" page. This page is empty - they don’t have any programs yet!
- Have them open a new program by clicking @ifproglang{WeScheme}{"Start a new program"} @ifproglang{Pyret}{"File" -> "New"} and save it as "Function Composition"
- Complete @printable-exercise{pages/function-composition-green-star.adoc}, in which you will draw circles of evaluation to help you write expressions to compose a series of images.
- Be sure to use the *Definitions Area* (left side) for code you want to keep and the *Interactions Area* (right side) to test code or try out new ideas.
}

When students are finished, check their work, and ask them to change the color of all of the stars to “gold” or another color of their choosing.

@lesson-instruction{
Now, turn to @printable-exercise{pages/function-composition-your-name.adoc} in which you will create a text @vocab{image} of your name and experiment with other functions.
}

@strategy{Strategies for Facilitation}{

While students are exploring, be available for support but encourage student discussion to solve problems. Many student questions can be addressed with these responses: _Did you try drawing the Circle of Evaluation first? Did you check the @dist-link{Contracts.shtml, contract}? Have you pressed the "Run" button to save your Definitions changes?_

Encourage students to practice writing comments in the code to describe what is being produced, using @ifproglang{wescheme}{`;`} @ifproglang{pyret}{`#`} at the beginning of the line.
}

@opt{If you have time, you can have students work with @printable-exercise{pages/function-composition-scale-xy.adoc} and/or @opt-starter-file{functioncompDesmos} - or use either onefor assessment!}

@strategy{Optional Project: Create Your Own Logo}{


Extend and solidify student understanding of function composition by challenging your students to create their own logos! @lesson-link{project-logo} walks students through the process of designing and building a personal design or logo.
}

=== Synthesize

@QandA{
@Q{What do all of these functions have in common?}
@A{They all produce images, they all change some element of the original image_}

@Q{Does using one of these functions change the original image?}
@A{No, it creates a whole new image}

@Q{What does the number in @show{(code 'scale)} represent?}
@A{The scale factor by which the image should grow or shrink}

@Q{What does the number in @show{(code 'rotate)} represent?}
@A{The rotation angle, measured counterclockwise}

@Q{The Domain and Range for @show{(code 'flip-horizontal)} is `Image -> Image`.  Why can we use the output of the @show{(code 'text)} function as an _input_ for @show{(code 'flip-horizontal)}?}
@A{Because the @show{(code 'text)} function produces an Image, which is then used as the input for @show{(code 'flip-horizontal)}.}
}



@strategy{Strategies for English Language Learners}{


MLR 1 - Stronger and Clearer Each Time: As an alternative, display the discussion questions during the last 5 minutes of the Explore and ask students to discuss the questions with their partner, asking each other for explanation and details and coming up with the clearest, most precise answer they can.
Student pairs can then share with another pair and compare their responses before moving into a full class discussion.
}

@strategy{Fun with Images!}{

Now that students have learned how to use all of these image-composing functions, you may want to give them a chance to create a design of their own, tasking them with using at least 4 functions to create an image of their choosing.

Our @lesson-link{transform-compose-images/} and @lesson-link{project-flags/} also dive deeper into image composition.
}

== Composing Multiple Ways @duration{Optional}

=== Overview
Students identify multiple expressions that will create the same image, and think about the merits of one expression over another.

=== Launch

As is often true with solving math problems, there is more than one way to get the same composed image.

@QandA{
Suppose I wrote the code: @show{(code '(scale 3 (circle 50 "solid" "red")))}.
@Q{What’s another line of code I could write that would produce the exact same image?}
@A{@show{(code '(circle 150 "solid" "red"))}}
}

=== Investigate

@lesson-instruction{
Complete @printable-exercise{pages/more-than-one-way.adoc}
}

When students have completed the worksheet, explain that there is a special function that lets us test whether or not two images are equal:

@show{(code 'image=?)}`{two-colons} Image, Image -> Boolean`

Invite students to use the above function to test whether all of the expressions that they wrote successfully build the same images.

=== Synthesize

- Could we have written more expressions to create the same images?
- Are all of the ways to write the code equally efficient?
