= Case Study: Michelle's Spotify Use

@center{@image{../images/spotify-123.jpg, 325}}

@vspace{1ex}

Michelle started using Spotify six months ago. The first time she checked out her AI-produced "Discover Weekly" playlist, she was underwhelmed. The songs did not match her tastes, and she ended up skipping over many of them within a few seconds. Michelle was so disappointed in that first experience that she gave up entirely on the "Discover Weekly" playlist, writing it off as a feature she did not care for.

@vspace{1ex}

After three months of using Spotify and listening to all of her favorite songs, artists, and playlists, Michelle happened to click on "Discover Weekly" again -- but this time, she was delighted by what she heard. It felt as though her best friend had curated a playlist just for her. Michelle discovered new music that she had never heard before, that she absolutely loved.

@vspace{1ex}

She remarked, *"Wow, Spotify has really improved their algorithms since I last checked out Discover Weekly."*

@n Circle your assessment of Michelle’s statement: @hspace{1em} _definitely true_ @hspace{2em} _possibly true_ @hspace{2em} _definitely not true_

@n What do you think might explain why her playlist is much better after three months of using Spotify? Provide as much detail as you can. _Hint: There may be more than one possible explanation!_

@fitb{}{@ifsoln{There are several possible explanations for why the playlist suggestions are more to Michelle's liking!}}

@fitb{}{@ifsoln{It is possible that the algorithm has not changed at all. Spotify uses data on which songs Michelle returns to over and over, and which songs she skips.}}

@fitb{}{@ifsoln{When supplied with _more data_, AI can produce better predictions. Maybe the AI is making predictions exactly the same way that it did six months ago. }}

@fitb{}{@ifsoln{Alternatively, it is possible that Spotify tweaked its algorithm. Spotify makes _minor_ changes to its algorithm regularly! }}

@fitb{}{@ifsoln{Maybe, for example, the algorithm was altered to put more weight on _other_ listeners' behaviors, and less weight on the user's listening behaviors.}}

@fitb{}{@ifsoln{It is also possible that Spotify completely overhauled its algorithm! If this were the case, users would likely all be noticing the impact of the changes }}

@fitb{}{@ifsoln{and disagree about whether or not they're an improvement!}}

@fitb{}{@ifsoln{From an outside perspective, it is impossible to know why Michelle's experience has improved. But the most important variable was probably that }}

@fitb{}{@ifsoln{Michelle listened to more music.}}

@n Michelle loves folk music featuring female vocals, but she has decided that she wants to branch out and is starting to feel frustrated by how Spotify keeps recommending folk music to her over and over and over! Why isn't Spotify giving Michelle the music suggestions she's looking for?

@fitb{}{@ifsoln{Spotify cannot read Michelle's mind, nor will it guess that maybe today is the day that she wants try some new music that is out of her comfort zone. }} +
@fitb{}{@ifsoln{Spotify can only process the data Michelle has provided, and make predictions based on that data. There's only  a small chance that Spotify will }} +
@fitb{}{@ifsoln{recommend something different, like hip hop music that is _influenced_ by folk music, and most likely it will also be something that features a  }} +
@fitb{}{@ifsoln{female vocalist!}}

@n What do you think Michelle should do to start getting different recommendations?

@fitb{}{@ifsoln{The best way to branch out is to ask a friend for recommendations... and to listen to those recommendations, repeatedly. If Michelle spends enough  }} +
@fitb{}{@ifsoln{time listening to other music, Spotify will eventually start generating different music recommendations.}}
