= Exploring the States Dataset

For this page, you'll need to open the @starter-file{alg2-states} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you.

@n Click "Run" and type `states-table` into the Interactions Area on the right to see the dataset.

@vspace{2ex}

[.FillVerticalSpace, cols="^1a,^1a",options="header",stripes="none"]
|===
| What do you Notice about this dataset?
| What do you Wonder about this dataset?
|
|
|===

The two lines of code under `# Define some rows` *extract rows 0 and 1 from the table, and define them as `alabama` and `alaska`*.

@n Type `alabama` into the Interactions Area. What do you get back? @fitb{}{@ifsoln{Just the Row for Alabama}}


@n What columns do you think might be related to one another? (e.g. - is the number of veterans related the amount of land-area? Is the population in 2010 related to the population in 2020?) List three possible relationships below.

+a.+ I think that @fitb{25em}{} may be related to @fitb{}{}

+b.+ I think that @fitb{25em}{} may be related to @fitb{}{}

+c.+ I think that @fitb{25em}{} may be related to @fitb{}{}

@vspace{1ex}

@n Make a scatter plot for each of the three relationships you listed. What do you think each display tells you about the relationship between those two columns? (**Reminder:** @show{(contract 'scatter-plot (list "Table" "String" "String" "String") "Image")})

+a.+ @fitb{}{}

@fitb{}{}

+b.+ @fitb{}{}

@fitb{}{}

+c.+ @fitb{}{}

@fitb{}{}

@vspace{3ex}

@center{**STOP HERE! You will finish this page AFTER diving deeper into statistical relationships.**}

@n For the three relationships in Question 3....

- Place a star by any relationships that you think might be linear.
- Place a "P" by any relationships that were positive.
- Place an "N" by any relationships that were negative.
- Place an "S" by the strongest-looking relationship.
- Place a "W" by the weakest-looking relationship.
