= Looking for Patterns

[.linkInstructions]
Open your copy of the @starter-file{alg2-states}.

@vspace{1ex}

== Part 1

@n Our state: @fitb{10em}{} Neighboring states: @fitb{}{}

@n What columns do you think might be related to one another? (e.g. - is the number of veterans related to the amount of land-area? Is the population in 2010 related to the population in 2020?) List three possible relationships below.

@hspace{1em} +a.+ I think that @fitb{25em}{} may be related to @fitb{}{}

@hspace{1em} +b.+ I think that @fitb{25em}{} may be related to @fitb{}{}

@hspace{1em} +c.+ I think that @fitb{25em}{} may be related to @fitb{}{}

@vspace{1ex}

@center{@show{(contract 'scatter-plot '("Table" (labels String) (explanatory String) (response String)) "Image")}}

@n Use the Contract above to make a scatter-plot for the *first relationship* you wrote.

@hspace{1em} +a.+ Find your state and its neighbors by mousing over the display. How do they compare? @fitb{}{} +
@fitb{}{}

@hspace{1em} +b.+ If there's a pattern in this scatter-plot, what does that mean? If there isn't, what does _that_ mean? @fitb{}{} +
@fitb{}{}

@n Make a scatter-plot for the *second relationship* you wrote. Then find your home state, and its neighbors.

@hspace{1em} +a.+ How does your home state compare to the neighboring ones? @fitb{}{}

@fitb{}{}

@hspace{1em} +b.+ If there's a pattern in this scatter-plot, what does that mean? If there isn't, what does _that_ mean? @fitb{}{} +
@fitb{}{}

@n Make a scatter-plot for the *third relationship* you wrote. Then find your home state, and its neighbors.

@hspace{1em} +a.+ How do they compare? @fitb{}{}

@fitb{}{}

@hspace{1em} +b.+ If there's a pattern in this scatter-plot, what does that mean? If there isn't, what does _that_ mean? @fitb{}{} +
@fitb{}{}

@vspace{1ex}

== Part 2
*Wait to complete this until after diving deeper into statistical relationships!*

Revisit the three scatter plots you made and add the following labels to the descriptions you wrote in Question 1:

- Place an "L" by any relationships that you think might be linear.
- Place a "P" by any relationships that were positive.
- Place an "N" by any relationships that were negative.
- Place an "S" by the strongest-looking relationship.
- Place a "W" by the weakest-looking relationship.
