= Fit a Model: College Degrees v. Income

_This page will require you to work with your copy of the @starter-file{alg2-states} in which you should have already defined `f(x)` based on your work on @printable-exercise{model-college-v-income-1.adoc}._

@vspace{1ex}

_Type @show{(code '(fit-model states-table "state" "pct-college-or-higher" "median-income" f))} in the Interactions Area._

@n Find the points for AL and AK along the predictor line. 

@n What do you Notice?

@fitb{}{@ifsoln{Answers will vary. AL and AK are both on the line, but they don't seem to be very representative of the group.}} 

@fitb{}{@ifsoln{The line goes all the way up to $200,000 but median income doesn't seem to exceed $80000.}}

@fitb{}{}

@n What do you Wonder?

@fitb{}{@ifsoln{Answers will vary. What states might have been more representative of the trend?}} 

@fitb{}{}

@fitb{}{}

@n In the upper left corner, you'll see that it says "S", followed by a number. What is that number? @fitb{}{@ifsoln{~9930.59}}

@n Change the definition of `f` so that the slope is _less steep_ and click "Run". What is the @math{S} value now? @fitb{}{}

@n Change the definition of `f` so that the slope is _negative_ and click "Run". What is the @math{S} value now? @fitb{}{}

@n Change the definition of `f` so that it draws a horizontal line and click "Run". What is the @math{S} value? @fitb{}{}

@n Change the y-intercept so that the horizontal line passes through more of the points. What is the @math{S} value? @fitb{}{}

@n What do you think @math{S} tells us? @fitb{}{@ifsoln{It measures how well the model fits the data}}

@fitb{}{}

@fitb{}{}

@fitb{}{}
