= What does _S_ tell us about the fit of these models?

@n A data scientist is working with data from animals at a shelter.

  * The range of days to adoption in this dataset are from 0 to 400. 
  * An @math{S} value of 300 means predicted adoption times could be off by 300 days.  
  
This is @fitbruby{25em}{@ifsoln{a terrible}}{a terrible, bad, ok, good, terrific} model for the dataset.

@n A student is exploring a dataset on climate change.

  * The range of Arctic Sea Ice is from 3,920,000 to 7,670,000 square kilometers
  * An @math{S} value of 300 means predicted Arctic Sea Ice coverage could be off by 300 square kilometers.

This is @fitbruby{25em}{@ifsoln{a terrific}}{a terrible, bad, ok, good, terrific} model for the dataset.

@n A data scientist is working with data from US public schools.

  * The range of graduates per school per year is 2 to 2003. 
  * An @math{S} value of 300 means predicted graduate values could be off by 300 students.  
  
This is @fitbruby{25em}{@ifsoln{a bad}}{a terrible, bad, ok, good, terrific} model for the dataset.

@n A student is exploring a dataset on earthquakes.

  * The range of earthquake depths in this dataset are from 4200m to 664000m. 
  * An @math{S} value of 300 means predicted earthquake depths could be off by 300 meters.  
  
This is @fitbruby{25em}{@ifsoln{a good}}{a terrible, bad, ok, good, terrific} model for the dataset.

@n A student is exploring a dataset on arrests in Los Angeles.

  * The age range in this dataset is from 0 to 92. 
  * An @math{S} value of 1 means predicted ages could be off by 1 year.  
  
This is @fitbruby{25em}{@ifsoln{a good}}{a terrible, bad, ok, good, terrific} model for the dataset.

@n A data scientist is working with data about snowflakes.

  * The range of snowflake weights is from 0.001 grams to 0.02 grams. 
  * An @math{S} value of 1 means predicted values could be off by 1 gram.  
  
This is @fitbruby{25em}{@ifsoln{a terrible}}{a terrible, bad, ok, good, terrific} model for the dataset.

@n A data scientist is working with data from animals at a shelter.

  * The range of ages is from 0.5 years to 16 years. 
  * An @math{S} value of 1 means predicted ages could be off by 1 year.  
  
This is @fitbruby{25em}{@ifsoln{an ok}}{a terrible, bad, ok, good, terrific} model for the dataset.

@n A student is working with a dataset of adult blue whales.

  * The range of weights is 200,000 to 330,000 pounds. 
  * An @math{S} value of 1 means predicted weights could be off by 1 pound.  
  
This is @fitbruby{25em}{@ifsoln{a terrific}}{a terrible, bad, ok, good, terrific} model for the dataset.
