= Which Form is Best?
++++
<style>
td:last-child { position: relative; }
td:last-child .paragraph:last-child { position: absolute; bottom: 0; }
</style>
++++
For each set of data provided below, 

- Decide which form of the line would be the easiest to build from the available information.
- Write a definition of the linear model in that form.
- Translate the definition into Pyret notation.
- Add the Pyret definition to your copy of @starter-file{alg2-states}.

[.FillVerticalSpace, cols="^.^1a, 10a, 20a", frame="none"]
|===
| @n
| @image{../images/si.png,200}
|
Linear Model: @fitbruby{}{}{slope-intercept form? &#8193; point-slope form? &#8193; standard form?}

`fun f(x) :  @fitb{28em}{@ifsoln{(-0.5 * x) - 10}} end`

| @n
| @image{../images/ps1.png,200}
|
Linear Model: @fitbruby{}{}{&#8193; slope-intercept form? &#8193; point-slope form? &#8193; standard form?}

`fun f(x) :  @fitb{28em}{} end`

| @n
| @image{../images/s.png,200}
|
Linear Model: @fitbruby{}{}{&#8193; slope-intercept form? &#8193; point-slope form? &#8193; standard form?}

`fun f(x) :  @fitb{28em}{} end`
|===
