= Defining Values

@lesson-description{Students learn how to define lines of code as a set value that can be used repeatedly in different situations, similar to a variable in math.}

[.left-header, cols="20a, 80a", stripes=none]
|===
| Lesson Goals 
| Students will be able to:

* Demonstrate understanding of @vocab{variable}s and why they are useful in math and programming 

|Student-facing Goals
|
* I can define a line of code as a value, such as `myStar` or `eyeColor`.
* I can use my defined value in different situations.

|Key Points For The Facilitator
|
* Check frequently for understanding of @vocab{datatype}s and @vocab{contract}s during this lesson and throughout subsequent lessons.

* Students will use their Contracts page frequently, so it should be kept in an accessible, convenient location.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.


|Materials
|
* Workbook, writing utensil, computer
|===

[.left-header, cols="20a, 80a", stripes=none]
|===
|Math Standards(CCSS)
|
* http://www.corestandards.org/Math/Practice/MP1/[CCSS.MATH.PRACTICE.MP1],  Make sense of problems and persevere in solving them.
* http://www.corestandards.org/Math/Practice/MP2/[CCSS.MATH.PRACTICE.MP2], Reason abstractly and quantitatively.
* Other math standards

|CS Standards(CSTA)
|
* CS Standards here
|===


== Get Ready: 

Students should be logged into WeScheme.

== Launch: (5 mins)
Display the sample code from the "Prize Star" exercise.

`(star 50 "solid" "green")`

`(scale 3 (star 50 "solid" "green"))`

`(scale .5 (star 50 "solid" "green"))`

`(rotate 45 (star 50 "solid" "green"))`

`(rotate 45 (scale 3 (star 50 "solid" "green")))`

*What common element was repeated throughout all the lines of code?* `_(star 50 "solid" "green")_`

*What happened when you were asked to change the color of the star to gold?* _We had to change it everywhere it appeared._  

*Since we're using that star over and over again, wouldn't it be nice if we could give that piece of code a "nickname", something shorter we could type to represent that piece of code?*

== Explore: (10 mins)
On WeScheme, have students click "Start a new program" and open to @worksheet-link{DefiningValues-WB1.pdf} to explore the new ‘define’ keyword.

== Discuss: (10 mins)
* How is ‘define’ similar to a function?  How is it different? 
_It’s written inside parentheses like a function, ‘define’ must be given a value name and a function call (a circle of evaluation), but ‘define’ doesn’t have an output_
* What is the usefulness of defining values? 
_Lets the programmer reuse code, saves time, lets the programmer make changes easily, allows us to more easily use elements inside other functions_
* What datatypes can we define values for? 
_All of them - Number, String, Image_

[.strategy-box]
.Support for English Language Learners
****
MLR 8 - Discussion Supports: As students discuss, rephrase responses as questions and encourage precision in the words being used to reinforce the meanings behind some of the programming-specific language, such as "define" and "value".
****

== Practice: (10 mins)
Students complete @worksheet-link{DefiningValues-WB2.pdf} with their partner.

Student-facing task:

* Write the code for a solid, green `star` of size 50 and define it as `PRIZE_STAR`

Use PRIZE_STAR to complete the following exercises:

* a solid, green `star` that’s 3 times as large as the original (using the `scale` function)
* a solid, green `star` that’s ½ the size of the original( using the `scale` function)
* a solid, green `star` of size 50 that’s rotated 45 degrees (using the `rotate` function)
* a solid, green `star` that’s 3 times as large as the original and rotated 45 degrees

== Create/Apply: (15 mins) 

*Option 1*:
Define at least 3 images of your own and combine using `overlay`, `beside`, and/or `above`.  You can also use any other functions you've learned, such as:

* `rotate`
* `scale`
* `flip-horizontal`
* `flip-vertical`
* any other image producing function(`triangle`, `star`, `circle`, `rectangle`, etc..)

Write comments to describe what is being produced.

*Option 2*:
Have students choose a flag from this list: @worksheet-link{exercises/flags-of-the-world-resource.pdf, (Flags of the World Resource),} and recreate one (or more!) of the flags using `define` and any of the other functions they've learned so far.
