= Making Flags
++++
<style>
.whiteBG img {background: white;}
.strategy-box .editbox { width: auto; }
</style>
++++

@lesson-description{Students compose the image functions they've learned, applying their knowledge of coordinates to position differently-shaped and transformed images to create flags of varying complexity.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-function-composition, defining-values}

| Lesson Goals
| Students will be able to:

* Put one image on top of another, using the `put-image` function.
* Decompose complex images into parts. 
* Combine and manipulate images to create more complex images.

| Student-facing Goals
|
* I can put one image on top of another.
* I can make complex images like flags.

| Materials
|[.materials-links]

@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/12Pm4x4eN3Ldq9S4mnpU-GVlUT6qh-GTKDx3XiZTIZCI/edit?usp=sharing, Lesson Slides}
}
@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1X2l3Lyz3dxDNFwAFYuQgWUjbL8GcanaPOPRXK542WSY/edit?usp=sharing, Lesson Slides}
}

@material-links


| Preparation
|
* Make sure all materials have been gathered.
* Decide how students will be grouped in pairs.

| Key Points For The Facilitator
|
* The `put-image` function treats the second image as the first quadrant of a cartesian plane. Having students sketch their flag on a sheet of graph paper drives this point home, and makes the programming easier.
* This is an excellent opportunity to introduce students to __indenting code__. The difference between poorly-indented flag code and well-indented flag code is extremely noticable.
|===


== Putting Images Together @duration{15 minutes}

=== Overview
Students learn about the `put-image` function.

=== Launch
You already know how to place one image on top of another, using the `overlay` function. 

[.lesson instruction]
Open the
@ifproglang{wescheme}{ @link{https://www.wescheme.org/view?publicId=xTZUy7EmCR, Flags Starter File} }
@ifproglang{pyret}{ @link{https://code.pyret.org/editor#share=1QEz7p-AVDMd3xmuJCvh2YRHSt8uF82CW, Flags Starter File} }
, and click Run. 

There's some code in the Definitions Area you haven't seen before. For now, just focus on lines 4 and 5 in the code. __What do these lines of code do?__

[.lesson-instruction]
Evaluate `dot` and `blank` in the Interactions Area. What do you get?

How could we overlay the `dot` on top of the `blank` rectangle image? What image do we get back?

As you've seen, `overlay` sticks two images together, so that the _center_ of the first image is placed exactly on top of the _center_ of the second image. But what if we want to put the dot somewhere besides the center?

=== Investigate
[.lesson-instruction]
- Type `japan` into the Interactions Area. What do you get back?
- Take a look at the code on line 7. What function is being used here?
- Try changing the `150` to `50`, then click Run. How does this image change?
- Try changing the `50` to `0`, then click Run. How does this image change?
- What is the @vocab{Contract} for `put-image`? (Write it in your Contracts page!)
- What does the `put-image` function do?

The `put-image` function works like `overlay`, but instead of placing the centers of each image on top of one another, it _translates_ the center of the top image by some distance in the x- and y-direction.

[.lesson-point]
Think of the bottom image as a sheet of graph paper with the origin (0,0) in the bottom left corner.

The numbers in `put-image` specify a point on that graph paper, with the center of the top image being placed there.

[.lesson-instruction.whiteBG]
--
The width of the rectangle is 300 and height is 200. *Estimate:* What coordinates for the `dot` would create each of the following images?

. @image{images/flag1.png}
. @image{images/flag2.png}
. @image{images/flag3.png}
. @image{images/flag4.png}
--

Complete @workbook-link{combining-images.adoc}.

=== Synthesize
Could we completely replace `overlay` with `put-image`? Why or why not?

== Making Flags @duration{25 minutes}

=== Overview
Students focus on decomposing complex images into simple ones, and using `put-image` to combine them.

=== Launch
Let's dig into the process for how the `japan` was made:

*1) Decompose the Image*

We observe that the Japanese flag is made up of two simpler images: a blank rectangle and a red dot.

*2) Define those parts*

We define `dot` and `blank`. Once we’ve defined those images, we test them out in the Interactions Area to make sure they look right!


*3) Find the Coordinates*

For each image, calculate what the x- and y-coordinates of the center should be. __TIP: this is a lot easier if you have a sheet of graph paper handy!__


*4) Build the Image*

We stack the parts on top of the bottom image using the coordinates we found.
 __TIP: don't cram all the code into one line! If you break it up into new lines (for example, hitting "Return" before the x-coordinate and after the y-coordinate), you'll notice that the code forms a "staircase" pattern.__

=== Investigate
[.lesson-instruction]
--
. Turn to @workbook-link{decomposing-flags.adoc}, and choose ONE flag to focus on. On the blank lines below, describe the parts that make up that flag.

. Once you're done, return to the 
@ifproglang{wescheme}{ @link{https://www.wescheme.org/view?publicId=PYN3JaBTzy, Flags Starter File} }
@ifproglang{pyret}{ @link{https://code.pyret.org/editor#share=1QEz7p-AVDMd3xmuJCvh2YRHSt8uF82CW, Flags Starter File} }
and define those parts.

. Then, compose those parts using `put-image`, and make your flag!
--

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Ratio and Proportion}

Have students define the `WIDTH` and `HEIGHT` of their flags as values, and then __replace the numbers in each flag__ with expressions relative to width and height. For example, if the `dot` in the Japanese flag is at (150, 100), those numbers would be replaced with @show{(sexp->code `(/ WIDTH 2))} and @show{(sexp->code `(/ HEIGHT 2))}.
|===

=== Synthesize
Which flags were the easiest to make? The hardest?

Why is it useful to define each part of the flag first, before stitching them together?