= Other Forms of Linear Models
++++
<style>
/* Shrink vertical space*/
body.workbookpage .fitbruby { padding-top: 1.1rem; }
.studentAnswerMedium { min-width: 8em !important; }
body:not(.LessonPlan, .narrativepage) p { line-height: 1.2; }

.center { padding: 0; }
tbody td { padding: 0.5em 0!important !important; }
</style>
++++

Depending on what you want to _do_ with a model, it can be more convenient to use one form instead of another!

[cols="^1a,^1a, ^1a", stripes="none", options="header", frame="none"]
|===
| Slope-Intercept Form
| Standard Form
| Point-Slope Form

| @math{y = mx + b}
| @math{ Ax + By = C}
| @math{ y-y_1 = m(x-x_1)}
|===

@vspace{1ex}

== Optimal Linear Model
The *Slope-Intercept Form* of the optimal linear model for predicting median income from pct-college-or-higher is :

@center{
 @math{y =} @fitbruby{8em}{1142}{slope}x + @fitbruby{8em}{20868.14}{y-intercept}
}

@n Write the Standard Form and Point-Slope Form of the *optimal* linear model below.

[cols="^5a,^4a", stripes="none", options="header"]
|===
| Standard Form
| Point-Slope Form

| @fitbruby{9em}{@ifsoln{1142}}{A}@math{x + } @fitbruby{9em}{@ifsoln{1}}{B} @math{ = } @fitbruby{9em}{@ifsoln{-20864.14}}{C}
| @math{y - }@fitbruby{9em}{@ifsoln{20868.14}}{y1} @math{ = m(x - } @fitbruby{9em}{@ifsoln{0}}{x1})
|===

== The `al-ak` model

The *Slope-Intercept Form* of the `al-ak` model for predicting median income from pct-college-or-higher is :

@center{
 @math{y =} @fitbruby{8em}{5614}{slope}x + @fitbruby{8em}{83616}{y-intercept}
}

@n Write the Standard Form and Point-Slope Form of the `al-ak` linear model below.

[cols="^5a,^4a", stripes="none", options="header"]
|===
| Standard Form
| Point-Slope Form

| @fitbruby{9em}{}{A}@math{x + } @fitbruby{9em}{}{B} @math{ = } @fitbruby{9em}{}{C}
| @math{y - }@fitbruby{9em}{}{y1} @math{ = m(x - } @fitbruby{9em}{}{x1})
|===

== Your Choice
Choose *another* linear model you came up with.

@n The *Slope-Intercept Form* of my @fitb{15em}{} model is: @math{y =} @fitbruby{8em}{}{slope}x + @fitbruby{8em}{}{y-intercept}

@n Write the Standard Form and Point-Slope Form of that linear model below.

[cols="^5a,^4a", stripes="none", options="header"]
|===
| Standard Form
| Point-Slope Form

| @fitbruby{9em}{}{A}@math{x + } @fitbruby{9em}{}{B} @math{ = } @fitbruby{9em}{}{C}
| @math{y - }@fitbruby{9em}{}{y1} @math{ = m(x - } @fitbruby{9em}{}{x1})
|===

== Comparing Forms
@n Which form is most useful to YOU, and why? @fitb{}{} +
@fitb{}{} +
@fitb{}{} +
@fitb{}{} +
@fitb{}{}
