= Project: Create Your Own Function

@description{Students develop and define a function of their own. The function must take in an image and manipulate it using at least three transformations.}

@lesson-prereqs{functions-examples-definitions}


[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* represent function composition with Circles of Evaluation
* use image-producing functions and functions that transform to define a function

| Student-facing Lesson Goals
|

* Let's make our own functions in Pyret!

| Materials
|[.materials-links]

@material-links

| Preparation
|
* Before launching this project, ensure that students are comfortable using image-producing functions and function composition.
* Note that for this project, students must submit XXXXX

* This project is designed to span multiple days.

|===

== Create Your Own Function @duration{flexible}

=== Overview

Students decide what they want their function to do. Then, they represent their function with a Circle of Evaluation. After writing the function's name, contract, and examples, students define the function. Finally, they enter all of this information into Pyret in order publish and share their program.

=== Launch

@teacher{To launch this project, you'll facilitate a conversation to review with students some of the functions that they have already created.}

[.lesson-instruction]
Use the @starter-file{functions} to complete the first section of the @handout{sample-function-study.adoc}.

@teacher{After this brief refresher on how to use a defined function, invite students to find a partner. One student will pose questions the questions below and the other will answer them. If you prefer, you can pose these questions to the class and call on individual students.}

@QandA{
Turn and talk to a partner. One student will ask questions, and the other will answer. The student who is asking the questions should point to the line of code that the the question refers to.
@Q{In the first example, how did we decide what number to use as the input for `maroon-square`?}
@A{We randomly chose the number! You can use any number.}
@Q{How did we decide on the output for `maroon-square`?}
@A{We thought about "what our actor would need to say" or looked at the directions.}
@Q{How would we decide what to circle in the examples?}
@A{We would look to see what changes.}
@Q{How did we decide on our function definition?}
@A{We looked at the examples. We wrote down everything that remained the same, and we used what we circled as our variable.}
}

For this project, we're going to create a function that takes in an _image_, and transforms that image at least three times. Let's look at a function like that!

@teacher{Before you dive in, we recommend printing and distributing the student-facing @handout{function-rubric.adoc} to help students understand the scope of the project and your expectations at the outset. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context.}

[.lesson-instruction]
- Using the @starter-file{functions}, complete the second section of the @handout{sample-functions-study.adoc}.

@QandA{
@Q{What does the function `sample` do?}
@A{It consumes an image, which will be scaled, rotated, and overlayed on a purple rectangle that is overlayed on a green star.}
@Q{How are the two functions alike? How are they different?}
@A{Both functions produce images, but `maroon-square` consumes a number, while `sample` consumes an image. The function `sample` is more complex: it uses a variety of composed functions, while `maroon-square` uses only one function.}
}

@teacher{Now that students have revisited defining and using functions, they are ready to plan out their own functions. Before moving to this next phase of the project, you can have students submit their work so far and evaluate it using the first row of the @handout{function-rubric}.}

[.lesson-instruction]
- Once you've sketched out and annotated your personal logo, find a partner.
- Shaer your logos with one another. Then, take turns describing to one another the decisions you made in designing your logo.
- If you have any ideas about what functions you will need to use to create this logo, share that with your partner, too.
- Give feedback to your partner on their logo. Do you have any concerns about their logo to share? Does their design seem within reach?

=== Investigate

@teacher{In this phase of the project, students begin to think more deeply about how they will write the code needed to produce their logo. They then sketch the Circle of Evaluation to produce their logo, and then write the code!}


[.lesson-instruction]
- Complete 1-4 on @handout{create-your-own.adoc}.
- Discuss your work with your partner before finishing the worksheet.

@teacher{Number 7 on @handout{create-your-own.adoc}} walks students through __defining__ their logo as `my-logo`. We offer an entire lesson on @lesson-link{defining-values} that goes into more depth on this topic - but the notes in Number 7 should be adequate for the purposes of this project! You might want to highlight for students that this is a new skill, and their first time typing in the Definitions Area.}

@teacher{Also note that in Number 9, students are asked to publish the link to their program and share it with their teacher. You may use a variety of methods for link submission including (but not limited to!) email, google classroom, and google form.}

=== Synthesize

* Encourage students to self-assess and revise their work. Peer review is a powerful tool if time allows! The @handout{logo-rubric.adoc} is a useful resource for facilitating both self and peer review.

* Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.

