= Project: Create Your Own Logo

@description{Students use image-producing functions and functions that transform to create their own personal logo.}

@lesson-prereqs{choosing-your-dataset}


[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* represent function composition with Circles of Evaluation
* use image-producing functions and functions that transform to create a personal logo

| Student-facing Lesson Goals
|

* Let's make a logo in Pyret!

| Materials
|[.materials-links]

@material-links

| Preparation
|
* Before launching this project, ensure that students are comfortable using image-producing functions and function composition.
* Note that for this project, students must submit three different components: (1) Sample Logo Study, (2) Create Your Own Logo, and (3) the link to their published Pyret program.
* This project is designed to span multiple days.

|===

== Create Your Own Logo @duration{flexible}

=== Overview

Students design their logo and consider which functions they will need to include. Then, they represent their logo first with a Circle of Evaluation, next with code. Finally, they publish and share their logo.

=== Launch

@teacher{To launch this project, begin with a conversation about students' favorite logos. Then, invite students to study some sample logos (and the corresponding code that produced them!). Finally, students begin sketching their own logo design.

Before you dive in, we recommend printing and distributing the student-facing @opt-printable-exercise{logo-rubric.adoc} to help students understand the scope of the project and your expectations at the outset. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context.}

[.lesson-instruction]
- If I ask you to think of a logo (any logo!), what are some of the first that come to mind?
- What makes those particular logos memorable or unique?
** _Possible responses: They include bright colors. The font is interesting. The logo tells some sort of story._
- Now, open @starter-file{logos}. What do you Notice? What do you Wonder?
- Using the @starter-file{logos}, complete @printable-exercise{sample-logo-study.adoc}.

@teacher{Now that students have a rough draft sketch of their logo, they are ready to give and receive feedback on their design.}

[.lesson-instruction]
- Once you've sketched out and annotated your personal logo, find a partner.
- Shaer your logos with one another. Then, take turns describing to one another the decisions you made in designing your logo.
- If you have any ideas about what functions you will need to use to create this logo, share that with your partner, too.
- Now, give feedback to your partner on their logo. Do you have any concerns about their logo to share? Does their design seem within reach?

=== Investigate

@teacher{In this phase of the project, students begin to think more deeply about how they will write the code needed to produce their logo. They then sketch the Circle of Evaluation to produce their logo, and then write the code!}


[.lesson-instruction]
- Complete 1-4 on @printable-exercise{create-your-own.adoc}.
- Discuss your work with your partner before finishing the worksheet.

@teacher{Number 7 on @printable-exercise{create-your-own.adoc}} walks students through __defining__ their logo as `my-logo`. We offer an entire lesson on @lesson-link{defining-values} that goes into more depth on this topic - but the notes in Number 7 should be adequate for the purposes of this project! You might want to highlight for students that this is a new skill, and their first time typing in the Definitions Area.}

@teacher{Also note that in Number 9, students are asked to publish the link to their program and share it with their teacher. You may use a variety of methods for link submission including (but not limited to!) email, google classroom, and google form.}

=== Synthesize

* Encourage students to self-assess and revise their work. Peer review is a powerful tool if time allows! The @opt-printable-exercise{logo-rubric.adoc} is a useful resource for facilitating both self and peer review.

* Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.

