= Project: Create Your Own Function

@description{Students develop and define a function of their own. The function must take in an image and manipulate it using at least three transformations. _This project supports the learning goals of @lesson-link{functions-examples-definitions}._}

@lesson-prereqs{functions-examples-definitions}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

- represent function composition with Circles of Evaluation
- use image-producing functions and functions that transform to define a function

| Student-facing Lesson Goals
|

- Let's make our own functions in @proglang!

| Materials
|[.materials-links]
@material-links

| Preparation
|
@preparation{
- Before launching this project, ensure that students are comfortable using image-producing functions and function composition.
- Teachers are welcome and encouraged to edit and adapt the student-facing @handout{function-rubric.adoc} for their unique classroom context and distribute it to help students understand the scope of the project - and your expectations - at the outset.
}

| Key Points for the Facilitator
|
- This project is designed to span multiple days.
- Note that, in addition to a published @proglang program link, students should submit their Sample Function Study, Designing Your Function and both Coding Your Function pages.

|===

== Create Your Own Function @duration{flexible}

=== Overview

Students explore two sample functions, then design a function of their own and represent it with a Circle of Evaluation and code. Finally, they publish and share their program.

=== Launch

@QandA{
@Q{What functions have we defined so far and what did they do?}
@A{Answers will vary, but may include:}
@A{`gt` made green equilateral triangles of any size.}
@A{`bc` made blue circles of any size.}
@A{`sticker` made a solid 50px star of a given color}
@A{`gold-star` made a gold star of any size}
@A{`name-color` made an image of your name at size 50 in whatever color is given}
@A{`name-size` made an image of your name in your specified favorite color in the given size...}
}

@slidebreak

Let's take a look at the definition for a new function.

@lesson-instruction{
Complete the first section of the @handout{function-study.adoc} using the @starter-file{functions}.
}

@slidebreak

Your are going to be defining a function of your own design that takes in an _image_, and transforms that image at least three times. Let's look at a function like that!

@lesson-instruction{
Complete the second section of the @handout{function-study.adoc} using the @starter-file{functions}, 
}

@QandA{
@Q{What does the function `sample` do?}
@A{It consumes an image, which will be scaled, rotated, and overlayed on a purple rectangle that is overlayed on a green star.}

@Q{How are the `maroon-square` and `sample` alike? How are they different?}
@A{Both functions produce images, but `maroon-square` consumes a number, while `sample` consumes an image. The function `sample` is more complex: it uses a variety of composed functions, while `maroon-square` uses only one function.}

@q{When writing an example, how does a programmer decide what number to use as the input?}
@a{We can use any number, unless we're trying to test for a special use-case.}

@q{When writing an example, how does a programmer decide what the output should be?}
@A{We can think about "what our actor would need to say".}
@A{We can look at the directions.}

@q{When writing a function definition, how does a programmer decide what the variable(s) should be?}
@A{We would look to see what changes.}

@q{What is the process for writing our function definition?}
@A{We look at the examples, write down everything that remained the same, and we replace the part that changes from one example to the next with a descriptive variable.}
}

@teacher{
Before moving onto the next phase of the project, some teachers have students submit their work now, and evaluate it using the first row of the @handout{function-rubric.adoc, "rubric"}. Intermittently receiving feedback is useful for many students.}

@slidebreak

@lesson-instruction{
Turn to @handout{design-your-function.adoc}, and describe about what you'd like __your function__ to do.
}

@teacher{If students get stuck, you can refer them to the @handout{function-study.adoc}.

Note that if you are collecting student work intermittently, now is a good time to do so. This phase of the project can be evaluated according to the second row of the @handout{function-rubric.adoc, "rubric"}.
}

=== Investigate

@teacher{In this phase of the project, students begin to think more deeply about how they will write the code needed to produce their function. They also code and test their function in @proglang, before publishing and submitting.}

@lesson-instruction{
- Turn to @handout{function-coe.adoc} and draw a Circle of Evaluation to represent the function you planned on @handout{design-your-function.adoc}.
- For your variable, you can just write "img".
- When you are finished, swap papers with a partner and complete the Peer Review on the bottom half of the page.
}

@teacher{Students who are able to conceptualize their function by drawing an accurate Circle of Evaluation will be able to progress through the remainder of the project much more confidently. It is vital to ensure that students have done adequate planning before they begin coding in @proglang. If you'd like, this is another good opportunity to assess student work using the third row of the @handout{function-rubric.adoc, "rubric"}.}

@lesson-instruction{
Open @starter-file{my-function}, which you will use to complete @handout{code-your-function.adoc}.
}

@teacher{@handout{code-your-function.adoc} asks students to define a value, add examples, and define their functions. They also complete a second round of peer review. When students are struggling, encourage them to read error messages carefully and refer to any relevant contracts.

Finally, students publish and submit their program links. Specify how you would like students to do this. Email, a form, or any SMS (ie, Google Classroom or Schoolology) will work!}

=== Synthesize

- Think about the process of creating your own function. What was the most rewarding part? What was the most challenging part?
- What advice would you offer to someone who was trying to build a function, like you just did?

@teacher{
Encourage students to self-assess and revise their work. Peer review is a powerful tool if time allows! The @handout{function-rubric.adoc, "rubric"} is a useful resource for facilitating both self and peer review.

Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.
}
