= Fixing Purpose Statements

Beneath each of the word problems below is a purpose statement (generated by ChatGPT!) that is either missing information or includes unnecessary information. 

- Write an improved version of each purpose statement beneath the original.
- Then, explain what was wrong with the ChatGPT-generated Purpose Statement.

@vspace{1ex}

@n *Word Problem:* _The New York City ferry costs $2.75 per ride. The Earth School requires two chaperones for any field trip. Write a function `fare` that takes in the number of students in the class and returns the total fare for the students and chaperones._

@vspace{1ex}

*ChatGPT's Purpose Statement:* Take in the number of students and add @math{2}.

*Improved Purpose Statement:* @fitb{}{@ifsoln{Consume the number of students and increase it by 2, then multiply that sum by 2.75, }}

@fitb{}{@ifsoln{producing total fare for students and chaperones.}}

*Problem with ChatGPT's Purpose Statement:* @fitb{}{@ifsoln{Does not multiply by $2.75, cost per ride.}}

@fitb{}{}

@vspace{1ex}

@n *Word Problem:* _It is tradition for the Green Machines to go to Humpy Dumpty's for ice cream with their families after their soccer games. Write a function `cones` to take in the number of kids and calculate the total bill for the team, assuming that each kid brings two family members and cones cost $1.25._

@vspace{1ex}

*ChatGPT's Purpose Statement:* Take in the number of kids on the team and multiply it by @math{1.25}.

*Improved Purpose Statement:* @fitb{}{@ifsoln{Consume the number of kids and multiply it by 3, then multiply that product by 1.25,  }}

@fitb{}{@ifsoln{producing cost for ice cream cones.}}

*Problem with ChatGPT's Purpose Statement:* @fitb{}{@ifsoln{Does not take family members into account.}}

@fitb{}{}

@vspace{1ex}

@n *Word Problem:* _The cost of renting an ebike is $3 plus an additional $0.12 per minute. Write a function `ebike` that will calculate the cost of a ride, given the number of minutes ridden._

@vspace{1ex}

*ChatGPT's Purpose Statement:* Take in the number of minutes and multiply it by @math{3.12}.

*Improved Purpose Statement:* @fitb{}{@ifsoln{Consume the number of minutes and multiply it by 0.12, then add 3 to that product, }}

@fitb{}{@ifsoln{producing total ride cost.}}

*Problem with ChatGPT's Purpose Statement:* @fitb{}{@ifsoln{Does not add $3 rental cost.}}

@fitb{}{}

@vspace{1ex}

@n *Word Problem:* _Suleika is a skilled house painter at only age 21. She has painted hundreds of rooms and can paint about 175 square feet an hour. Write a function `paint` that takes in the number of square feet of the job and calculates how many hours it will take her._

@vspace{1ex}

*ChatGPT's Purpose Statement:* Take in the number of square feet of walls in a house and divide them by @math{175} then add 21 years.

*Improved Purpose Statement:* @fitb{}{@ifsoln{Consumes the number of square feet of walls and divides that amount by 175, }}

@fitb{}{@ifsoln{producing hours spent painting.}}

*Problem with ChatGPT's Purpose Statement:* @fitb{}{@ifsoln{Unnecessarily adds 21.}}

@fitb{}{}
