= Rocket Height Challenges

++++
<style>
.paragraph:nth-child(odd)+.paragraph { margin-top: 0.5in; }
.paragraph:last-child { margin-top: 0 !important; }
</style>
++++

@n Can you make the rocket fly faster?

@fitb{}{@ifsoln{multiply `seconds` by a number larger than 7: @math{\mbox{height}(\mbox{seconds}) = 20 \times \mbox{seconds}}}}

@n Can you make the rocket fly slower?

@fitb{}{@ifsoln{multiply `seconds` by a number smaller than 7: @math{\mbox{height}(\mbox{seconds}) = 2 \times \mbox{seconds}}}}

@n Can you make the rocket sink down instead of fly up?

@fitb{}{@ifsoln{multiply `seconds` by a negative number: @math{\mbox{height}(\mbox{seconds}) = -7 \times \mbox{seconds}}}}

@n Can you make the rocket accelerate over time, so that it moves faster the longer it flies?

@fitb{}{@ifsoln{The formula for acceleration is _quadratic_: @math{\mbox{height}(\mbox{seconds}) = 7 \times \mbox{seconds}^2}.}}

@n Can you make the rocket blast off and then land again?

@fitb{}{@ifsoln{A parabola with a negative coefficient, shifted right by subtracting from the squared term and up by adding a constant: @math{\mbox{height}(\mbox{seconds}) = -(\mbox{seconds} - 10)^2 + 100}}}

@n Can you make the rocket blast off, reach a maximum height of exactly 1000 meters, and then land?

@fitb{}{@ifsoln{In the previous solution, the constant we add is the square of the constant we subtract from @math{\mbox{seconds}}. To reach a height of 1000: @math{\mbox{height}(\mbox{seconds}) = -(\mbox{seconds} - \sqrt{1000})^2 + 1000}}}

@n Can you make the rocket blast off, reach a maximum height of exactly 1000 meters, and then land after exactly 100 seconds?

@fitb{}{@ifsoln{A good challenge for a unit on quadratics! @math{\mbox{height}(\mbox{seconds}) = 0.4 \times (\mbox{seconds})^2 + 40\mbox{seconds}}}}

@n Can you make the rocket fly to the edge of the the universe?

@fitb{}{@ifsoln{What's the inverse function of log? Exponential } }

@fitb{}{@ifsoln{Use any number for the base and seconds as the exponent: @math{\mbox{height}(\mbox{seconds}) = 7^{\mbox{seconds}}}}

