= Health Problems in America that May Be Related to Food

@description{This lesson explores modern data on Americans’ health, specifically rates of obesity, diabetes, and high blood pressure. These data illustrate some of the food-related health challenges facing Americans today. They set us up for the next lesson on changes and challenges in what Americans eat. Taken together, these help frame an argument that there are problems to address about modern American food consumption.}

@lesson-prereqs{}

@keywords{}

@add-to-lang{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* create charts and analyze trends in data to determine trends in Americans’ rates of obesity, diabetes, and blood pressure since the mid 1900s.
* review data types and the role they play in choosing appropriate displays.
* create line charts for tables with a time column and a quantitative column.
* interpret line charts to provide evidence to answer broader questions.

| Student-facing Lesson Goals
|

* Let's

| Materials
|[.materials-links]

@material-links

|===

== xyz

Complete the @printable-exercise{do-now.adoc}

=== Overview

=== Launch

=== Investigate

=== Synthesize

0-4 minutes—Do Now:
Students enter the classroom silently. **If time is an issue, the teacher may pre-assign each table/group a question to focus on. Students should then complete their Do Now in 5 teams, 1 question per team.

4-5 minutes—Share Out:
Call on select students to share out while revealing correct answers under the document camera.

5-6 minutes—Recap the Unit and Yesterday:
“Welcome Back, New York Times reporters! Today, we will be diving into the sixth day of our Data Science Unit and remember we are attempting to discover the answers to our big unit questions: How has the way Americans get food changed from the time of early Native Americans up until now? Does the way we eat now seem better or worse than before?”

“Yesterday, we saw how although the U.S. population is increasing, fewer people are farmers than ever before. We learned that the invention of the railroad and the refrigerator car allowed us to make bigger farms further away and ship food into cities. This has radically changed our society.
6-8 minutes—Homework Check:
“Before we move on, let’s see how you did on your homework!”

Reveal correct answers quickly under the document camera while calling on selected students.

“Awesome! We will continue to use your graphing skills today!
8-9 minutes—Frame the Day:
“This leads us to our big question of today: What are some possible food-related health problems that affect Americans today? ”

“Let’s think back to our Do Now. We saw that we’ve gone from almost all living on farms and in the country, to all living in cities. Is this good or bad? Can you brainstorm some possible good effects of this change? What about possible bad effects?

9-11 minutes—Turn and Talk: Turn and talk with your neighbor. Try to come up with at least one possible good effect and one possible bad effect.

11-13 minutes—Share out: Students share out. Teacher may choose to chart some of these ideas on the board.

“Alright, this is a great list of ideas. It’s now time to start researching to see if we were right. What are some possible side-effects of this change in how we get our food?”

The teacher chooses any of the following challenge setups below. It is up to the teacher entirely. Select the setup you prefer most and adjust your schedule to match it.

CHALLENGE OPTION 1: GROUP RESEARCH and PRESENTATIONS
CHALLENGE OPTION 2: FULL RESEARCH - Individual or Partners

13-15 minutes—Challenge Introduction and Directions:
The National Institutes of Health have prepared 3 data sets for us to investigate. We are going to break into groups today. Each group will be assigned one of the three datasets (A, B, and C) to analyze and read.
Two groups will analyze set A: Diabetes
Two groups will analyze set B: Obesity
Two groups will analyze set C: High Blood Pressure

You have 15 minutes to:
Read the Background Information
Complete your Worksheet.
Create your display.
Edit your display with titles and labels.
Plan your presentation

Then, at the end of class I will choose one group from each set to present to the class. I will flip a coin. The group that is not chosen to present will provide feedback after the first group presentation.

15-17 minutes—Set Up:
Teacher takes clarifying questions, splits teams into groups, and distributes materials (two groups should receive packet A, two receive packet B, and two receive packet C).
17-29 minutes—Group Work Time:
Students read their article, create their display, and prepare to present to the group. Teacher circulates and assists as needed.
29-31 minutes—Directions and Expectations:
“It’s now time to share what you learned and learn what your other teammates have researched. I am going to select one group from each research article to present for two minutes. If your group is chosen, get ready to present your findings for 2 minutes. If your group is NOT chosen, you will provide feedback after they are done according to the following questions:
Did they accurately present the research? Does your group agree or not?
Was there any part of their presentation that was confusing? If so, how would you re-explain it?
Anything else your group wants to share about what you learned?

If your research is not being presented, use the thought catcher below to take notes while other groups present their findings. Record what the trend is, is it good or bad, and one piece of evidence you found interesting. You will need this information to answer your exit ticket for the day.”

31-34: Group A presents and their partner group gives feedback.
34-37: Group B presents and their partner group gives feedback.
37-40 Group C presents and their partner group gives feedback.
40-45 minutes—Evidence Journal:
Fantastic work. Teacher may choose to reveal the exemplar graphs if needed.

It’s time to summarize our findings for today! You may work with your group to answer this evidence journal question.

Turn to your evidence journal and begin: What are some recent health problems that can result from a poor diet? Could this be a result of changes in how we get our food these days (shipped long distances instead of from local farms)? Name 2-3 bad effects we explored today and then explain which one you think is most dangerous for society and why.

No homework.

CHALLENGE OPTION 2: FULL RESEARCH - Individual or Partners
13-15: Challenge Introduction and Directions:
The National Institutes of Health have prepared 3 data sets for us to investigate. We are going to break into groups today to analyze these sets.
We will do the first one together as a class, and then your group will analyze the other two with a partner. You must have all three complete and ready to discuss by the end of our day (or two days) together.
15-22 minutes—Guided Analysis for Research Set A: Diabetes
Teacher guides students to analyze the first research set (A) together.
22-29 minutes—Partner work for Research Set B: Obesity.
Students work in partners to complete research Set B.

29-31 minutes—Share out:
Teacher uses computer/doc cam to check over final answers.
31-38 minutes—Partner work for Research Set C: High Blood Pressure
Students work in partners to complete research Set C.

38-40 minutes—Share out:
Teacher uses computer/doc cam to check over final answers.
40-45 minutes—Evidence Journal:
Fantastic work. Teacher may choose to reveal the exemplar charts if needed.

It’s time to summarize our findings for today! You may work with your group to answer this evidence journal question.

Turn to your evidence journal and begin: We studied several issues that impact people’s health. Name 2-3 bad effects we explored today. Tell how one of them relates to the food we eat. Then explain which one you think is most dangerous for society and why.

No homework.


