= Coding Your Function

== Translate Your Circle of Evaluation to Code

@n Code: @fitb{}{}

== Add Examples and Define Your Function

@link-instructions{Open @starter-file{my-function} on your computer. @ifproglang{pyret}{Select "File", then "Save a Copy."}@ifproglang{wescheme}{Click "Save".}}

@n At the top of the starter file we've defined two functions for you to write examples with.

  * What shape will `pt` make? @fitb{}{@ifsoln{pink triangles of size 30}} 
  * What shape will `yr` make? @fitb{}{@ifsoln{yellow rectangles of size 20}}

@n Define a third image value called `img` to make a shape of your choosing and then click "Run" to load the program with your new definition.

- What shape will `img` make? @fitb{}{}

@n Test out the code you wrote in question 1 in the Interactions Area and hit Enter/return.

- If you get an error or a different result than you expected, try again until it works and describe one adjustment that you made. @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Once the code is working how you want it to, it's time to add it to the EXAMPLES in the definitions area.

- Type `my-function(shape)` *is* and then paste in the code you just entered.
- Follow the pattern to add examples using `pt` and `yr`.
- Remember to use linebreaks and indentation to make your code easy to read. If you're not sure how to do that, look at the EXAMPLES in the @starter-file{functions-study}.

@n After entering your examples, click "Run" to confirm that your tests passed in @proglang, with no error messages. @ifproglang{pyret}{You should see the message, "Looks shipshape, all 3 tests passed, mate!"}

@n Define `my-function` in @proglang. (If you don't remember how to define a function, you can refer to the @starter-file{functions-study}.)


== Peer Review

Save your program. Then swap papers and computers with your partner so they can view your @proglang file.

@n  Write your name on the line so that your teacher knows who is reviewing this function. @fitb{}{}

@n Did your partner write 3 different and correctly formatted examples? If they do write "yes", or else describe what needs to be fixed.

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n When you click "Run", do you see @ifproglang{wescheme}{any error messages? If so,} @ifproglang{pyret}{the message, "Looks shipshape, all 3 tests passed, mate!"? If not,} work with your partner to find and fix the problem. Describe the issue below or write "No errors!".

@fitb{}{}

@fitb{}{}

== Publish and Submit Your Program

@n Save your program. Go to @ifproglang{wescheme}{"Share"}@ifproglang{pyret}{"Publish"}, and copy the link that appears. Follow your teacher’s instructions for submitting the link.



