= Designing Your Function

== Planning Your Function
In this project, you will develop and define a function of your own! This function must take in a shape and manipulate it using at least three transformations. This is the planning sheet. You will also create, save, and share a Pyret file with your teacher.

@n Put a checkmark by each of the shape functions that you plan to use in your personal function. You must choose at least one. If you plan to use one image multiple times, you can add additional checkmarks next to it.

@vspace{1ex}

[.FillVerticalSpace, cols="2a,2a,2a,2a"]
|===

|
* [ ] circle |
* [ ] ellipse |
* [ ] text	|
* [ ] rectangle |
* [ ] rhombus |
* [ ] triangle |
* [ ] radial-star | |

|===

@n Put a checkmark by each of the transformation functions you plan to use in your personal function. You must choose at least three functions. If you plan to use one function multiple times, you can add additional checkmarks next to it.

@vspace{1ex}


[.FillVerticalSpace, cols="2a,2a,2a,2a"]
|===

|
* [ ] above |
* [ ] beside |
* [ ] flip-horizontal	|
* [ ] flip-vertical |
* [ ] rotate |
* [ ] scale |
* [ ] overlay |
* [ ] put-image |

|===

@n What do you want your function to do?

- Example: @fitb{}{_I want my function to take in any shape, and then: double its size, turn it upside down, and place it in_}

@fitb{}{_the center of a solid blue square that is 100 pixels wide._}

- Your response: @fitb{}{I want my function to take in a shape, and then: }

@fitb{}{}

@fitb{}{}


@n Draw a sketch of what your function would produce for two different provided inputs.

@vspace{1ex}

[cols="2a,2a", rows="none", options="header"]
|===

| input: `triangle(30, "solid", "pink")`

| input: `rectangle(20, 50, "outline", "yellow")`

| @vspace{45ex}

| @vspace{45ex}

|===


