= Represent Your Function with a Circle of Evaluation

@n Draw a Circle of Evaluation to show how you will compose the functions you selected on @handout{design-your-function.adoc} in order to create your function. *Hint:* You can use `shape` as the variable name for the images that your function will take in.

@vspace{50ex}

== Peer Review

@n Swap papers with a partner. Write your name so your teacher knows who is reviewing this function. @fitb{}{}

@n Did your partner put a function at the top of each Circle? If not, explain what the problem is. @fitb{}{} +
@fitb{}{}

@n Are all of the inputs to each function in the correct order? If not, which contracts does your partner need to revisit to solve the problem? @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n Are all of the inputs to each function in the correct order? If not, which contracts does your partner need to revisit to solve the problem? @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n What do you think your partner's function is trying to do? @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n Ask your partner to give you their copy of @handout{design-your-function.adoc}. Look at their responses for numbers 3 and 4. Do you think the code represented by the Circle of Evaluation above will do what they want it to do? If not, tell them what you think needs to change. @fitb{}{} +
@fitb{}{} +
@fitb{}{}
