= Sample Function Study

Respond to the questions below using @starter-file{functions}.

@vspace{1ex}

== Maroon Square

@n We're going to test out the function `maroon-square`. Let's think about its domain and range.

- What does `maroon-square` consume? @fitb{15em}{}
- What does `maroon-square` produce? @fitb{15em}{}

@n What do you think the function `maroon-square` does? @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Let's test it out. Type `maroon-square(20)` in your Interactions Area, then hit enter. Repeat this for the other two examples that you see in the Definitions Area. What happens and why? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{1ex}


== Sample

@n On lines 23-27, some different values have been defined. What are their names? @fitb{}{}

@fitb{}{}

@n Let's examine what happens when we use each of those values as inputs for `sample`. Hit "Run". Type `small-yellow-tri` into the Interactions Area and hit enter. Then, test out `sample(small-yellow-tri)`. What do you Notice? What do you Wonder? @fitb{}{}

@fitb{}{}

@fitb{}{}

@n What do you expect to happen when you test `big-blue-tri` and `sample(big-blue-tri)`? @fitb{}{}

@fitb{}{}

@n If you'd like, test out `hello-text` and `sample(hello-text)`. You can run `sample` with __any__ image-producing functions.

@n In your own words, describe how the function `sample` transform its input. @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Did you notice how the code in the `EXAMPLES` section goes down and to the right, like a staircase? Why do you think the programmer wrote it that way? @fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

