= Defining Row Functions &amp; Using Table Methods

*Methods* are special functions that are attached to pieces of data. We use them to manipulate Tables. 

- In this course, the methods we’ll be using are  

** `row-n` - consumes an index (starting with zero!) and produces a row from a table
** `order-by` - consumes the name of a column and a Boolean value to determine if that table should be sorted by that column in ascending order
** `filter` - consumes a __Boolean-producing function__, and produces a table containing only rows for which the function returns `true`
** `build-column` - consumes the name of a new column, and a function that produces the values in that column for each Row

- Unlike functions, methods can’t be used alone. They have a “secret” argument, which is the data they are attached to. They are written as part of that data, separated by a dot. For example:
+
`shapes.row-n(2)`

- Contracts for methods are different from other functions. They include the type of the data as part of their names. For example:
+ 
`<table>.row-n {two-colons} (index {two-colons} Number) -> Row`