= Creating a Scatter Plot

++++
<style>
p, .paragraph { width: auto !important; }
#content .fitb{ line-height: 2; }
table:first-of-type td.tableblock { padding: 8px !important; text-align: center; }
</style>
++++

[cols="<.^1a, >.^1a", header="none", stripes="none", frame="none", grid="none"]
|===
|
[%autowidth,options="header"]
!===
! name 			! species 	! age 	! weeks
! `"Sasha"` 	! `"cat"` 	!  1	!  3
! `"Boo-boo"` 	! `"dog"` 	! 11	!  5
! `"Felix"` 	! `"cat"` 	! 16	!  4
! `"Buddy"` 	! `"lizard"`!  2	! 24
! `"Nori"` 		! `"dog"` 	!  6	!  9
! `"Wade"` 		! `"cat"` 	!  1	!  2
! `"Nibblet"` 	! `"rabbit"`!  6	! 12
! `"Maple"` 	! `"dog"` 	!  3	!  2
!===


| @image{scatterplot.png, scatter plot, 300, "An empty scatterplot, waiting for data from the table on the left to be filled in"}
|===

@n Choose *two animals* at random in the table on the left, and plot their age/weeks values by adding a point to the scatter plot on the right (be sure to check your axes!). Do you see a pattern? @fitb{}{}

@n Plot the rest of the animals - one at a time. After each one, ask yourself whether or not you see a pattern in the data. After how many animals did you begin to see a pattern? @fitb{}{}

*Draw a line that shows the pattern you see, then circle the cloud of points around that line*

@n Are the points tightly clustered around the line or loosely scattered?  @fitb{}{}

@ Does this display support the claim that younger animals get adopted faster? Why or why not? @fitb{}{}

@fitb{}{}

[cols="<.^1a, >.^1a", header="none", stripes="none", frame="none", grid="none"]
|===
| @n What would the scatter plot look like if there was NO relationship between the age and weeks? Draw a scatter plot with no relationship in the smaller graph on the right.
| @image{scatterplot.png, scatter plot, 250, "An empty scatterplot, waiting for random data to be filled in"}
|===
