// use double-space before the *bold* text to address a text-kerning bug in wkhtmltopdf 0.12.5 (with patched qt)
= Creating a Scatter Plot

++++
<style>
.fitb{ line-height: 2;}
</style>
++++


. *For each row in the Sample Table on the left, add a point to the scatter plot on the right*. Use the values from the age column for the x-axis, and values from the weeks column for the y-axis.

. Do you see a pattern? Do the points seem to go up or down as age increases to the right?  

** *Draw a cloud around all the points, and a line around which the cloud appears to be centered*

. Does the line slope upwards or downwards? @fitb{35em}{}

. Are the points tightly clustered around the line or loosely scattered?  @fitb{25em}{}

@vspace{10ex}

[.left]
[%autowidth,cols="5a,5a,2a,3a",options="header"]
|===
| name 			| species 	| age 	| weeks
| `"Sasha"` 	| `"cat"` 	|  1	|  3
| `"Boo-boo"` 	| `"dog"` 	| 11	|  5
| `"Felix"` 	| `"cat"` 	| 16	|  4
| `"Buddy"` 	| `"lizard"`|  2	| 24
| `"Nori"` 		| `"dog"` 	|  6	|  9
| `"Wade"` 		| `"cat"` 	|  1	|  2
| `"Nibblet"` 	| `"rabbit"`|  6	| 12
| `"Maple"` 	| `"dog"` 	|  3	|  2
|===

@span{.right}{@centered-image{scatterplot.png, "", 375, ""}}

@span{.clear}{}