= Creating a Scatter Plot

++++
<style>
#content .fitb{ line-height: 2; }
td.tableblock { padding: 0 !important; text-align: center; }
</style>
++++

[cols="<.^1a, >.^1a", header="none", stripes="none", frame="none", grid="none"]
|===
|
[%autowidth,options="header"]
!===
! name 			! species 	! age 	! weeks
! `"Sasha"` 	! `"cat"` 	!  1	!  3
! `"Boo-boo"` 	! `"dog"` 	! 11	!  5
! `"Felix"` 	! `"cat"` 	! 16	!  4
! `"Buddy"` 	! `"lizard"`!  2	! 24
! `"Nori"` 		! `"dog"` 	!  6	!  9
! `"Wade"` 		! `"cat"` 	!  1	!  2
! `"Nibblet"` 	! `"rabbit"`!  6	! 12
! `"Maple"` 	! `"dog"` 	!  3	!  2
!===


| @image{scatterplot.png, scatter plot, 300, "An empty scatterplot, waiting for data from the table on the left to be filled in"}
|===


. *For each row in the Sample Table on the left, add a point to the scatter plot on the right*. Use the values from the age column for the x-axis, and values from the weeks column for the y-axis.

. Do you see a pattern? Do the points seem to go up or down as age increases to the right?  

** *Draw a line that shows the pattern you see, then circle the cloud of points around that line*

. Does the line slope upwards or downwards? @fitb{}{}

. Are the points tightly clustered around the line or loosely scattered?  @fitb{}{}
