= Sort Transformer

Make sure you’re logged into CODAP with the Animals Dataset open. Open the Transformers plugin, and select `Sort`.

@vspace{2ex}

== Creating a Sort Transformer

@n Select `Sort` from the drop-down menu of Transformers.

@n Enter a Transformer Name. We want to give each Transformer a useful name, one which clearly describes what that Transformer does. Generally, a brief hyphenated description works - for instance: `order-by-weight`. What would be a good name for a Transformer that organizes the table alphabetically by animal' names?
 @span{.blankline}{@ifsoln{_order-by-name._}}

@n Select the appropriate dataset. Which dataset do you want CODAP to apply this Transformer to?
 @span{.blankline}{@ifsoln{_Animals Dataset_}}

@n Select _sort by attribute_ as the sort method.

@n Select `Name` as the attribute to sort.

@n Which direction will you select? Why?
 @span{.blankline}{@ifsoln{_"Ascending" sorts from A to Z, so I will select that._}}

== Applying and Saving the Sort Transformer

@n Apply the Transformer. What happens?
 @span{.blankline}{@ifsoln{_A copy of the original dataset is created._}}

@n What do you notice about the name of the new dataset?
 @span{.blankline}{@ifsoln{_It has `Sort`, the Transformer name, at the front, with the name of the original dataset in parentheses._}}

@n What happens when you save a Transformer? How is saving a Transformer different from saving a dataset?
 @span{.blankline}{@ifsoln{_When I save a Transformer, a small box appears that has my Transformer's name at the top. I will now be able to use the Transformer again, without inputting all of the different specifications._}}
