= Filter, Transform, Build

Make sure you’re logged into CODAP with the Animals Dataset open.

@vspace{2ex}

== Creating a Filter Transformer

@n Open the Transformers plugin, and select `Filter`.

@n Enter a `filter-is-fixed` as the Transformer name. What does this name tell you about the Transformer you are creating?
 @span{.blankline}{@ifsoln{_The Transformer will filter out only animals that are fixed._}}

@n Select the appropriate dataset. Which dataset do you want CODAP to apply this Transformer to?
 @span{.blankline}{@ifsoln{_Animals Dataset_}}

@n Examine the contract. Why does the provided contract make sense?
 @span{.blankline}{@ifsoln{_The expression will consume a Row and produce a Boolean._}}

@n Write a purpose statement.
@span{.blankline}{@ifsoln{_The expression will consume a Row and produce a Boolean._}}

@n Enter `Fixed = true` as the expression.

@n Select `Apply Transformer`. What happens?
 @span{.blankline}{@ifsoln{_A copy of the original dataset is created, with only animals that are fixed._}}

== Creating a Transform Transformer

@n Now select `Transform Attribute` in the Transformer plugin.

@n Enter `transform-is-young` as the name.

@n Select the Animals Dataset.

@n What would be an appropriate name for our altered attribute?
@span{.blankline}{@ifsoln{Students can select the attribute name `Age` and reame it `Young`.}}

@n Examine the contract. A domain is provided (row), but not a range. What is the desired output for `transform-is-young`?

@n Let's write a purpose statement. Whta do you think we want a Transformer called `transform-is-young` to do?

@n Enter `Age < 5` as the expression.

@n Apply the Transformer. To define the Transformer for future use, select `Save`.

@n Now, try creating a Transformer called `weight-in-kg`
