= Build Attribute

Make sure you’re logged into CODAP with the Animals Dataset open.

@vspace{2ex}

== Creating a Build Attribute Transformer

@n Now select `Build Attribute` in the Transformer plugin.

@n Enter `build-is-heavy` as the name. What does this name tell you about the Transformer we are creating?
@span{.blankline}{@ifsoln{We are going to build a column that states `true` for heavy animals and `false` for lightweight animals.}}

@n Select `animals-dataset`.

@n What would be an appropriate name for our _new_ attribute?
@span{.blankline}{@ifsoln{`Heavy`}}

@n Examine the contract. A domain is provided (row), but not a range. What is the desired output for `build-is-heavy`?
@span{.blankline}{@ifsoln{Boolean.}}

@n Let's write a purpose statement. What do you think we want a Transformer called `build-is-heavy` to do?
@span{.blankline}{@ifsoln{`build-is-heavy` consumes a weight and returns `true` if the weight is greater than a specified amount.}}

@n Enter `Weight > 40` as the expression.

@n Apply the Transformer. To define the Transformer for future use, select `Save`.

== More Building

@n Now, try creating a Transformer called `updated-age`. This Transformer will give the animals' ages one year from today. How many animals are 9 years-old one year from today?

@fitb{}{@ifsoln{In one year, there are three animals that are 9 years-old.}}
