= Transform

Make sure you’re logged into CODAP with the Animals Dataset open.

@vspace{1ex}

== Creating a "Transform" Transformer

- Select `Transform Attribute` in the Transformer plugin.
- Enter `transform-is-young` as the name. This Transformer will replace all ages less than 5 with the Boolean `true`. In other words, it will _transform_ our "age" column into a column that tells us if an animal is young or not.
- Select the Animals Dataset.

@n What would be an appropriate name for our transformed attribute? @fitb{}{@ifsoln{`Young`}

@n Examine the contract for the expresson. A Domain (row) is provided... but not a Range. What type of data do we expect for this expression? @fitb{}{@ifsoln{`Boolean`}

@vspace{1ex}

@n Let's write a purpose statement. What do you think we want a Transformer called `transform-is-young` to do?

@fitb{}{@ifsoln{Creates a new table where ages below 5 are replaced with an indication of whether the animal is young or not.}}

@vspace{1ex}

- Enter `Age (years) < 5` as the expression. (Include tick marks around `Age (years)`.)

- Apply the Transformer. To define the Transformer for future use, select `Save`.

== More Transforming

@n Now, try creating a Transformer called `weight-in-kg`. (Note: To convert pounds to kilograms, divide pounds by 2.205.) How many kilograms is the heaviest animal in the shelter?

@fitb{}{@ifsoln{Kujo, the heaviest animal, is 78 kilograms.}}
