= Filter

Make sure you’re logged into CODAP with the Animals Dataset open.

@vspace{1ex}

== Creating a "Filter" Transformer

Open the Transformers plugin, and select `Filter`.

@n Enter a `filter-is-fixed` as the name. What does this name tell you about the Transformer you are creating?

@fitb{}{@ifsoln{_The Transformer will filter out only animals that are fixed._}}

@n Which dataset should we select? @fitb{}{@ifsoln{_Animals Dataset_}}

@n Examine the contract. Why does the provided contract make sense?

@fitb{}{@ifsoln{_The expression will consume a Row and produce a Boolean._}}

@n Write a purpose statement.

@fitb{}{@ifsoln{_The expression will consume a Row and produce a Boolean._}}

- Enter `Fixed = true` as the expression.

@n Select `Apply Transformer`. What happens?

@fitb{}{@ifsoln{_A copy of the original dataset is created, with only animals that are fixed._}}

@n Try typing `fixed = true` as the expression (instead of `Fixed = true`). What happens?

@fitb{}{@ifsoln{_An error message appears that says, "Evaluating `fixed = true` failed: 'fixed' is unrecognized."_}}

@n What happens when you enter `FIXED = true`? How about `Fixed = TRUE`?

@fitb{}{@ifsoln{_Error messages appear stating that FIXED and TRUE are unrecognized._}}


== More Filtering

@n Create, save, and apply a Transformer called `filter-is-old` that creates a new dataset with animals older than 5 years. Note that `Age (years)` needs to be typed within backticks ` ` in order for CODAP to recognize it as an attribute. (The backtick key is in the upper left corner of the keyboard.) How many rows does the resulting table have?

@fitb{}{@ifsoln{_There are 9 rows._}}

@n Create, save, and apply a Transformer called `filter-is-dog` that creates a new dataset with only dogs. How many dogs are there at the shelter?

@fitb{}{@ifsoln{_There are 15 dogs._}}
