= Transform

Make sure you’re logged into CODAP with the Animals Dataset open.

@vspace{1ex}

== Creating a "Transform" Transformer

- Select `Transform Attribute` in the Transformer plugin.
- Enter `transform-is-young` as the name. This Transformer will replace all ages less than 5 with Boolean `true`.
- Select the Animals Dataset.

@n What would be an appropriate name for our transformed attribute? @fitb{}{@ifsoln{`Young`}

@ifsoln{Note: Students can select the attribute name `Age` on their table and rename it `Young`.}}

@n Examine the contract for the expresson. A Domain is provided (row), but not a Range. What type of data do you we expect for this expression? @fitb{}{@ifsoln{`Boolean`}


@n Let's write a purpose statement. What do you think we want a Transformer called `transform-is-young` to do?

@fitb{}{@ifsoln{Creates a new table where ages below 5 are replaced with an indication of whether the animal is young or not.}}

- Enter `Age < 5` as the expression.

- Apply the Transformer. To define the Transformer for future use, select `Save`.

== More Transforming

- Now, try creating a Transformer called `weight-in-kg`.
