= Filter

Make sure you’re logged into CODAP with the Animals Dataset open.

@vspace{2ex}

== Creating a Filter Transformer

@n Open the Transformers plugin, and select `Filter`.

@n Enter a `filter-is-fixed` as the Transformer name. What does this name tell you about the Transformer you are creating?
 @span{.blankline}{@ifsoln{_The Transformer will filter out only animals that are fixed._}}

@n Select the appropriate dataset. Which dataset do you want CODAP to apply this Transformer to?
 @span{.blankline}{@ifsoln{_Animals Dataset_}}

@n Examine the contract. Why does the provided contract make sense?
 @span{.blankline}{@ifsoln{_The expression will consume a Row and produce a Boolean._}}

@n Write a purpose statement.
@span{.blankline}{@ifsoln{_The expression will consume a Row and produce a Boolean._}}

@n Enter `Fixed = true` as the expression.

@n Select `Apply Transformer`. What happens?
 @span{.blankline}{@ifsoln{_A copy of the original dataset is created, with only animals that are fixed._}}

== More Filtering

@n Create, save, and apply a Transformer called `filter-is-old` that creates a new dataset with animals older than 5 years.

@n Create, save, and apply a Transformer called `filter-is-dog` that creates a new dataset with only dogs.
