= Data Cycle: Looking for Relationships (My Dataset)

++++
<style>
/* hide the Interpret rows, as well as the sub-questions for Analyze */
.data-cycle tr:nth-of-type(4),
.data-cycle tr:nth-of-type(3) td:nth-of-type(2) p:nth-of-type(1),
.data-cycle tr:nth-of-type(3) td:nth-of-type(2) p:nth-of-type(2) { display: none; }
table.template { border-top: 0; }
table.template td:first-of-type { background: #ccc; }
table { flex-grow: 1; }
</style>
++++

@link-instructions{Open @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, "your chosen dataset"}.} Use the Data Cycle to search for relationships between columns.

@data-cycle{ ""
  #:question ""
  #:show-question? #t
  #:question-type "statistical"
  #:show-question-type? #f
  #:rows ""
  #:show-rows? #f
  #:cols ""
  #:show-cols? #f
  #:filter-fn ""
  #:show-filter? #f
  #:build-fn ""
  #:show-build? #f
  #:expression ""
  #:show-expression? #f
  #:finding ""
  #:show-finding? #f
  #:new-question ""
  #:show-new-question? #f
}


[.template, cols="^.^2a,13a"]
|===
|@centered-image{../images/InterpretData.png}
|
- [ ] There appears to be no relationship between @fitbruby{13em}{}{x-variable} and @fitbruby{13em}{}{y-variable}.

- [ ] There appears to be a @fitbruby{10em}{}{strong / weak / moderate}, @fitbruby{10em}{}{positive / negative}, @fitbruby{10em}{}{linear / non-linear} relationship between @fitbruby{15em}{}{x-variable} and @fitbruby{15em}{}{y-variable}. +
Some possible outliers might be @fitb{}{}
|===
   
@vspace{2ex}   

@span{.sectionbreak}{}

@vspace{2ex}   

@data-cycle{ ""
  #:question ""
  #:show-question? #t
  #:question-type "statistical"
  #:show-question-type? #f
  #:rows ""
  #:show-rows? #f
  #:cols ""
  #:show-cols? #f
  #:filter-fn ""
  #:show-filter? #f
  #:build-fn ""
  #:show-build? #f
  #:expression ""
  #:show-expression? #f
  #:finding ""
  #:show-finding? #f
  #:new-question ""
  #:show-new-question? #f
}

[.template, cols="^.^2a,13a"]
|===
|@centered-image{../images/InterpretData.png}
|
- [ ] There appears to be no relationship between @fitbruby{13em}{}{x-variable} and @fitbruby{13em}{}{y-variable}.

- [ ] There appears to be a @fitbruby{10em}{}{strong / weak / moderate}, @fitbruby{10em}{}{positive / negative}, @fitbruby{10em}{}{linear / non-linear} relationship between @fitbruby{15em}{}{x-variable} and @fitbruby{15em}{}{y-variable}. +
Some possible outliers might be @fitb{}{}
|===

