= Exploring Relationships Between Columns

[.linkInstructions]
This page is designed to be used with the @starter-file{animals}. Log into @starter-file{program-list} to open your saved copy.

@vspace{1ex}

As you consider each of the following relationships, first think about what you _expect_, then make the scatter plot to see if it supports your hunch.

@n How are the @fitbruby{8em}{`pounds`}{explanatory variable} an animal weighs related to its @fitbruby{7em}{`age`}{response variable}?

- What would you expect? @fitb{}{}

@hspace{2em} @fitb{}{}

- What did you learn from your scatter plot? @fitb{}{@ifsoln{There seems to be some relationship between weight and age. }} 

@hspace{2em} @fitb{}{@ifsoln{The heaviest animals aren't necessarily the oldest, but none of the heaviest animals are the youngest.}}

@n How are the number of @fitbruby{8em}{`weeks`}{explanatory variable} it takes for an animal to be adopted related to its number of @fitbruby{7em}{`legs`}{response variable}?

- What would you expect? @fitb{}{}

@hspace{2em} @fitb{}{}

- What did you learn from your scatter plot? @fitb{}{@ifsoln{There doesn't seem to be much of a relationship between `weeks` and number of `legs`.}} 

@hspace{2em} @fitb{}{@ifsoln{ Almost all of the animals have 4 legs and they spend a varied number of weeks at the shelter before adoption.}}

@n How are the number of @fitbruby{8em}{`legs`}{explanatory variable} an animal has related to its @fitbruby{7em}{`age`}{response variable}?

- What would you expect? @fitb{}{}

@hspace{2em} @fitb{}{}

- What did you learn from your scatter plot? @fitb{}{@ifsoln{The number of legs does not seem to explain an animals age.}} 

@hspace{2em} @fitb{}{@ifsoln{ Most of the animals have four legs.}}

@n Do any of these relationships appear to be linear (straight-line)?

@fitb{}{}

@fitb{}{@ifsoln{Maybe the first relationship, but a line wouldn't be a very good fit.}}

@n Are there any unusual observations?

@fitb{}{@ifsoln{There is an animal named Felix who is 16 years old and only weighs 9.6 pounds.}}

@fitb{}{@ifsoln{There appear to be only 3 animals who don't have four legs: one with 0, one with 3, and one with 8.}}

@fitb{}{}

@fitb{}{}