# created 2023-01-14
# last modified 2023-01-17

# all: initialization copylessons buildlessons buildpathways doconversions

include utils.mk

all: copy-lessons build-pathway-independent

include copy-lessons.mk

include build-pathway-independent.mk
