# created 2023-01-14
# last modified 2023-01-15

# all: initialization copylessons buildlessons buildpathways doconversions

all: copylessons pathwayindep

include copylessons.mk

include pathwayindep.mk
