#!/bin/bash

# created 2023-01-14
# last modified 2023-01-19

CP=cp
SED=sed

function adjustproglangsubdirs() {
  local d=$1
  local pl=$2

  if test -d "$d"/"$pl"; then
    $CP -p "$d"/"$pl"/* "$d"
  fi

  local lang
  for lang in codap pyret wescheme spreadsheets none; do
    if test -d "$d"/$lang; then
      rm -fr "$d"/$lang
    fi
  done

  local subdir
  for subdir in "$d"/*; do
    if test -d "$subdir"; then
      adjustproglangsubdirs "$subdir" "$pl"
    fi
  done
}

function shadowcopydir() {
  local srcdir=$1
  local tgtdir=$2
  mkdir -p "$tgtdir"

  local f
  for f in "$srcdir"/*; do
    local g=$(basename "$f")
    if test -f "$f"; then
      $CP -p "$f" "$tgtdir"
    elif test -d "$f"; then
      shadowcopydir "$f" "$tgtdir"/"$g"
    fi
  done
}

# echo
# echo doing massage-distribution-lesson $1

d=$1

d=${d%/.}

lessonName=$(basename $d)

cd $d

proglangs=pyret
firstproglang=pyret

if test -f proglang.txt; then
  proglangs=$(cat proglang.txt)
  firstproglang=$(echo $proglangs|sed -e 's/^\([^ ]\+\).*/\1/')
fi

cd ..

lessonNamePl=
for pl in $proglangs; do
  lessonNamePl="$lessonName"
  if test "$pl" != pyret; then
    lessonNamePl="$lessonName"-$pl
    mkdir -p "$lessonNamePl"
    cp -upr "$lessonName"/* "$lessonNamePl"
  fi
  #
  cd "$lessonNamePl"
  mkdir -p .cached
  touch .cached/.proglang-$pl
  touch .cached/.redo
  if test "$firstproglang" = $pl; then
    touch .cached/.primarylesson
  fi
  if test ! -d pages; then
    mkdir pages
  fi
  if test ! -f pages/workbook-pages.txt; then
    touch pages/workbook-pages.txt
  fi
  test -d pages/.cached || mkdir -p pages/.cached

  #ensure workbook-pages.txt ends in newline, or while isn't happy
  $SED -i -e '$a\' pages/workbook-pages.txt

  rm -f pages/.cached/.workbook-{pages,pages-ls,notes-pages-ls}.txt.kp

  # it should exist, even if empty
  touch pages/.cached/.workbook-pages-ls.txt.kp

  while read -r f; do
    # echo finding aspect of "$f"
    aspect=portrait
    g=$f
    if echo "$f"|grep -q '^ *;'; then
      :
    elif echo "$f"|grep -q '^ *//'; then
      :
    elif echo "$f"|grep -q landscape; then
      echo $f >> pages/.cached/.workbook-pages.txt.kp
      g=$(echo $f|$SED -e 's/^ *\([^ ]\+\).*/\1/')
      echo $g >> pages/.cached/.workbook-pages-ls.txt.kp
      aspect=landscape
    elif echo "$f"|grep -q portrait; then
      echo $f >> pages/.cached/.workbook-pages.txt.kp
      g=$(echo $f|$SED -e 's/^ *\([^ ]\+\).*/\1/')
      echo $g >> pages/.cached/.workbook-pages-ls.txt.kp
    elif test "${f%.adoc}" = "$f"; then
      echo $f >> pages/.cached/.workbook-pages.txt.kp
      echo $f >> pages/.cached/.workbook-pages-ls.txt.kp
    else
      if test -f "$f" && head -n 5 "$f"|grep -q '^ *\[\.landscape\] *$'; then
        echo $f landscape >> pages/.cached/.workbook-pages.txt.kp
        echo $f >> pages/.cached/.workbook-pages-ls.txt.kp
        aspect=landscape
      elif test -f "$g" && head -n 60 "$g"|grep -q 'body.*landscape'; then
        echo $f landscape >> pages/.cached/.workbook-pages.txt.kp
        echo $f >> pages/.cached/.workbook-pages-ls.txt.kp
        aspect=landscape
      else
        echo $f >> pages/.cached/.workbook-pages.txt.kp
        echo $f >> pages/.cached/.workbook-pages-ls.txt.kp
      fi
    fi
  done < pages/workbook-pages.txt

  for subdir in *; do
    if test -d "$subdir"; then
      adjustproglangsubdirs "$subdir" "$pl"
    fi
  done
  #
  if test -d solution-pages-2; then
    # this shd be deadc0de
    rm -fr solution-pages-2
  fi
  cp -pr pages solution-pages-2
  cp -p $PROGDIR/.hta* solution-pages-2
  if test -d solution-pages; then
    shadowcopydir solution-pages solution-pages-2
    rm -fr solution-pages
  fi
  mv solution-pages-2 solution-pages
  test -d solution-pages/.cached || mkdir -p solution-pages/.cached
  #
  cd ..
  echo "$lessonNamePl" >> $RELEVANT_LESSONS_INPUT
done
