= Dot Plots

@description{First, students create and interpret dot plots, considering the distribution, typicality, and variability of the data. Then, they consider the relationship between dot plots and histograms, extending the understandings developed in the first half of the lesson. }

@ifproglang{pyret}{
@lesson-prereqs{contracts-tables-visualizations, ds-intro}
}

@ifproglang{codap}{
@lesson-prereqs{codap-dot-plots-bar-charts}
}

@keywords{histogram, bin, interval}

@add-to-lang{histogram}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives


| Student-facing Lesson Goals
|

- Let's create dot plots and learn how to interpret them.

| Materials
|[.materials-links]

@material-links

| Preparation
|


|===


== Dot Plots' Distribution and Typicality

@objective{make-dot-plots}
@objective{dot-plot-features}

=== Overview

Students create and interpret dot plots, formalizing their vocabulary to accurate describe a dataset's distribution and typicality.

=== Launch

@teacher{Before class, draw a number line on a piece of chart paper or on the board. Your number line should start at zero and go up to about 15 by ones. Your ending value should match the number of letters in the longest student name in your class.}

@lesson-instruction{
- Count how many letters are in your first name.
- Once you have counted, line up at the board to draw a dot above the number of letters in your first name. Keep dots evenly spaced.
- Once you return to your desk, copy the class dot plot onto the top section of @printable-exercise{create-interpret-dot-plots.adoc}
}

@QandA{
@Q{What do you Notice about this data? What do you Wonder about this data?}
@A{Students will likely use informal language to describe the distribution of data. During the lesson, students will learn and practice using formal vocabulary for describing distributions. }
}

@strategy{Dot Plots?!}{
If you teach students who are older than 10 or 11 years old, you may be asking yourself: Why dot plots? Aren't those a little elementary?

Students are generally successful interpreting dot plots (compared to, say, box plots and histograms) because on a dot plot, _individual cases are visible_. Educational research tells us that interpreting box plots and histograms is often difficult for students because they tend to view data as individual cases. Box plots and histograms only provide an _aggregate_ view.

To combat this challenge, Bakker, Biehler, and Konold (2005) recommend  building a strong foundation with data visualizations where individual cases are visible. In short: don't gloss over dot plots! When introducing dot plots and histograms, the authors urge teachers to support students by pairing the less-familiar aggregate data visualizations with their corresponding (familiar) dot plots.
}

=== Investigate

@lesson-instruction{
- On @printable-exercise{dot-plots.adoc}, we will think more about what's happening in this dot plot, and then explore some new ways of describing the data.
- Respond to the questions on the second section of the page, Reading a Dot Plot. Be prepared to discuss your answers.
}

@teacher{Review students' responses as a class.}

Now that we are comfortable creating dot plots, we need a common vocabulary to discuss the data that they display. To describe the distribution of data--the way that it is spread out on a number line--it is helpful to locate any outliers, clusters, peaks, and gaps.

- A *cluster* is a group of data points that are close together.
- A *gap* is an interval where there are no data points.
- An *outlier* occurs when one data point is much larger or smaller than the other data points.
- A *peak* is the value(s) with the most data.

@lesson-instruction{

@image{images/number-line.png}

- Let's label the clusters, gaps, outliers, and peaks in the dot plot in question 4 on @printable-exercise{create-interpret-dot-plots.adoc}
- With your partner, describe the distribution of our name length data in as much detail as possible, using the vocabulary you have just learned. Be prepared to share your response.
}

Another way of describing data on a dot plot is to think about its typicality.

@QandA{
@Q{Let's think about the word "typical". Describe a "typical" morning for you.}
@A{Invite students' to share. Emphasize that "typical" is "the usual", or "what's expected", but it is not always a perfect predictor. It may be "typical" to eat breakfast at 7am, but there are probably days where you eat a little bit earlier or a little bit later - or even much earlier or much later!}

@Q{What does the word "typical" mean to you?}
}

@lesson-instruction{

Complete the final section of @printable-exercise{create-interpret-dot-plots.adoc}.
}

@teacher{Review students' responses, emphasizing that there are multiple ways to decide what is typical in a dataset.}


=== Synthesize

@QandA{

@Q{What were some of the different strategies you used to choose a typical value in the dataset?}
@A{This question is designed to prime students to recognize that what's typical generally exists at the center of the data. Students will likely identify the values that (approximately) represent the mean, median, and mode. It is fine if students are not yet able to recognize these measures of center, which they will explore during @lesson-link{measures-of-center}.}

@Q{When determining what value is typical, was it helpful to consider peaks, clusters, gaps, and outliers in the dataset?}
}




== From Dot Plots to Histograms

@objective{dot-plot-v-histogram}

=== Overview

=== Launch

A histogram is another data visualization commonly used to display quantitative data. Let's explore the ways that histograms are similar to and different from dot plots.


@QandA{
@Q{What do you Notice about the dot plot (left) and the histogram (right), which both display the same quantitative dataset?}
@A{Possible responses: the histogram has bars that are touching; I can see that the gaps and peaks are in the same place; I can't see individual data points.}

@Q{What do you Wonder about the dot plot and histogram?}
@A{Possible responses: Why do we need two displays that are so similar? How do I read and interpret a histogram? What are histograms useful for?}

[cols="^.^8a,^.^1,^.^8a", frame="none", grid="none"]
|===

| @image{images/pounds.png, 350}  | | @image{images/pounds.png, 350}

|===

}


=== Investigate

Now, let's think more deeply about the sort of information that dot plots and histograms provide us.


@lesson-instruction{
- Turn to @printable-exercise{compare-dot-plots-histograms.adoc}. At the top of the page, there is a dot plot on the left and a histogram on the right.
- First: Use *only the dot plot* to answer the questions. Record your responses in the *middle* column of the table. If there is a question that you *cannot* answer, put an X.
}


Next, we'll use a histogram to answer the same questions.

@QandA{
@Q{Given that this is your first time interpreting a histogram: What questions do you have about doing reading a histogram?}

@A{Possible questions include:
- *How is this different from a bar chart?* Histograms show the distribution of quantitative data, not categorical. Histograms' bars cannot be reordered, as they allow us to see the shape of a dataset. We can reorder bars in a bar chart.
- *Are the values on the tick marks included in the bar?* On a histogram, each bar _includes_ the left-end value but not the right-end value.}
- *How was the size of the intervals (bins) determined?* We will explore this in a different lesson; bin size varies depending on the data being displayed.
}

@lesson-instruction{
- Return to @printable-exercise{compare-dot-plots-histograms.adoc}.
- Use *only the histogram* to answer the same set of questions. Record your responses in the *right-hand* column of the table. If there is a question that you cannot answer, put an X.
- Respond to the questions in the Reflection section.
}

@teacher{Invite students to share their responses, emphasizing the important idea that histograms display aggregate information rather than individual cases.}

@strategy{Histograms Don't Display Individual Data Points!}{

Dot plots and histograms have a lot in common... so why is interpreting histograms a challenge for many students?

According to research conducted by Bakker, Biehler, and Konold (2014), students are inclined to view data as _individual cases_. Histograms, however, display _aggregate information_.

How do we prevent this misconception? The authors have two recommendations:

- Spend ample time learning about data visualizations _where individual cases are visible_ to establish a solid foundation.
- When aggregate plots *are* introduced, pair them with representations that allow students to see individual cases.

}

Lets think more deeply about dot plots and histograms, two data visualizations of both the frequency and distribution of quantitative data.

@lesson-instruction{
- Complete @printable-exercise{match-dot-plots-histograms.adoc}.
- What was your strategy for matching dot plots and histograms?
}



=== Synthesize


@QandA{

@Q{How are the two displays alike?}
@A{They both display the frequency and distribution of quantitative data. They both show the total number of values.}

@Q{How are the two displays different?}
@A{We can see individual points on the dot plot, but on the histogram, we just get a collective overview of the data. There is no way to single out one particular animal's weight on the histogram.}

@Q{When might a histogram be more useful than a dot plot? WHen might a dot plot be more useful than a histogram?}
@A{If we have a large dataset and we want to get a collective overview of the data, a histogram would be more useful. If we need to look at individual data points in a smaller dataset, we should use a dot plot.}

}
