= Practice Plotting 2

++++
<style>
.blankline { margin-bottom: 0.5rem; }
td, th, .center { padding: 0 !important; vertical-align: middle; }
p { margin: 0 !important; }
.checklist li { margin: 0; padding: 0; }
</style>
++++

Fill in the tables, predict what the graph will look like (a rough sketch is fine!), and then use CODAP to make the following displays.

@vspace{1ex}

@n A histogram of the number of `pounds` that animals weigh.
[cols="1a,1a,1a", options="header"]
|===
|@span{.center}{*Column / Attribute*}
|@span{.center}{*Type of Data*}
|@span{.center}{*Configuration*}

|
@ifnotsoln{
@fitbruby{100%}{}{[column used as x-axis]}
@fitbruby{100%}{}{[column used as y-axis]}
}

@ifsoln{
@fitbruby{100%}{_pounds_}{[column used as x-axis]}
@fitbruby{100%}{_n/a_}{[column used as y-axis]}
}

|
@ifnotsoln{
* [ ] Quantitative
* [ ] Categorical
}

@ifsoln{
* [x] Quantitative
* [ ] Categorical
}

|
@ifnotsoln{
* [ ] Points
* [ ] Fuse dots into bars
* [ ] Bar for each point
* [ ] Group into bins
}

@ifsoln{
* [ ] Points
* [x] Fuse dots into bars
* [ ] Bar for each point
* [x] Group into bins
}

|===


[cols="1a,1a", options="header"]
|===
|@span{.center}{*Sketch the chart below:*}
|@span{.center}{*What do you think the data display tells us?*}

|
@ifsoln{
@centered-image{../images/weight-histo.png, histogram showing animals' weights, 150}
}

@ifnotsoln{
@vspace{20ex}
}

|
@ifnotsoln{
@vspace{10ex}
}

@ifsoln{

The display shows us the distribution of animals' weights into varying increments.

}

|

|===

@vspace{1ex}

@n A scatter-plot, using the animals `name` as the labels, `age` as the x-axis, and `pounds` as the y-axis, for all the animals from the shelter.
[cols="1a,1a,1a", options="header"]
|===
|@span{.center}{*Column / Attribute*}
|@span{.center}{*Type of Data*}
|@span{.center}{*Measure*}


|
@ifnotsoln{
@fitbruby{100%}{}{[column used as x-axis]}
@fitbruby{100%}{}{[column used as y-axis]}
@fitbruby{100%}{}{[(optional) column used for labels]}
}

@ifsoln{
@fitbruby{100%}{_age_}{[column used as x-axis]}
@fitbruby{100%}{_pounds_}{[column used as y-axis]}
@fitbruby{100%}{_name_}{[(optional) column used for labels]}
}

|
@ifnotsoln{
* [ ] Quantitative
* [ ] Categorical
}

@ifsoln{
* [x] Quantitative
* [ ] Categorical
}

|
@ifnotsoln{
* [ ] Box plot
* [ ] Least squares line
* [ ] No need to make a selection
}

@ifsoln{
* [ ] Box plot
* [ ] Least squares line
* [x] No need to make a selection
}

|===


[cols="1a,1a", options="header"]
|===
|@span{.center}{*Sketch the chart below:*}
|@span{.center}{*What do you think the data display tells us?*}

|
@ifsoln{
@centered-image{../images/age-pounds-scatter-plot.png, scatterplot showing animals' weights compared to their age, 150}
}

@ifnotsoln{
@vspace{20ex}
}

|
@ifnotsoln{
@vspace{10ex}
}

@ifsoln{

The display shows us the relationship between animals' age and weight.


}

|


|===
