= Histograms: Center, Spread, and Variability

@description{Students are introduced to Histograms by comparing them to bar charts, learning to construct them by hand and in the programming environment.}

@ifproglang{pyret}{
@lesson-prereqs{contracts-tables-visualizations, ds-intro}
}

@ifproglang{codap}{
@lesson-prereqs{codap-dot-plots-bar-charts}
}

@keywords{histogram, bin, interval}

@add-to-lang{histogram}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives
@objective{histograms-pyret}
@objective{Make charts displaying frequency in Pyret and interpret them.}

| Student-facing Lesson Goals
|

- Let's create histograms for datasets and learn how to interpret them.

| Materials
|[.materials-links]

@material-links

| Preparation
|
@preparation{
- There is an interactive Desmos activity in the lesson, as well as Desmos formative assessments.
  * Open the Desmos activity you plan to use (@starter-file{histograms}, @assessment{histograms-check1-desmos}, or @assessment{histograms-check2-desmos}) and make a code or link to share with students.
  * If you are using our Google Slides, add the appropriate link to the slide deck. 
  * _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}
- There is an optional kinesthetic activity in this lesson that requires a ball of play-dough for each group of 3.
}

| Assessments
| @assessments

|===


== Identifying Center and Spread on Histograms

=== Overview

=== Launch

=== Investigate

=== Synthesize


== Histograms and Variability

=== Overview

=== Launch


=== Investigate


=== Synthesize

