= Visualizing the "Shape" of the Data

@description{Students are introduced to Histograms by comparing them to bar charts, learning to construct them by hand and in the programming environment.}

@ifproglang{pyret}{
@lesson-prereqs{contracts-tables-visualizations, ds-intro}
}

@ifproglang{codap}{
@lesson-prereqs{codap-dot-plots-bar-charts}
}

@keywords{histogram, bin, interval}

@add-to-lang{histogram}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives

| Student-facing Lesson Goals
|

- Let's create histograms for datasets and learn how describe their shape.

| Materials
|[.materials-links]

@material-links

| Preparation
|
@preparation{
- There is an interactive Desmos activity in the lesson, as well as Desmos formative assessments.
  * Open the Desmos activity you plan to use (@starter-file{histograms}, @assessment{histograms-check1-desmos}, or @assessment{histograms-check2-desmos}) and make a code or link to share with students.
  * If you are using our Google Slides, add the appropriate link to the slide deck. 
  * _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}
- There is an optional kinesthetic activity in this lesson that requires a ball of play-dough for each group of 3.
}

| Assessments
| @assessments

|===


== Creating and Understanding Histograms

@objective{make-histograms}
@objective{histogram-center-spread}

=== Overview

=== Launch

Let's make histograms by hand and in @proglang.

@lesson-instruction{
- Use the data provided on @printable-exercise{making-histograms.adoc} to complete the frequency table and corresponding data visualization.
- Open the @starter-file{tooth-data} to build a histogram @ifproglang{pyret}{by using the provided contract.}@ifproglang{codap}{by following the given instructions.}
}


=== Investigate

Practice reading histograms.

@lesson-instruction{
- Complete @printable-exercise{reading-histograms.adoc}
}

@teacher{
Depending on your students' familiarity with histograms, you may want to emphasize some of the common misconceptions, below.
}

-


=== Synthesize



== Describing Shape @duration{30 minutes}

@objective{peaks-clusters-gaps}
@objective{skew-or-symmetric}
@objective{bar-chart-v-histogram}

=== Overview

This activity focuses on _describing shape_ from a @vocab{histogram}. Students explore shape by considering symmetry, peaks, clusters, and skew.

=== Launch

@QandA{
Your teacher will give you and your partner an envelope containing lettered histogram cards. Lay out the cards in front of you.

@Q{What do you Notice about the histograms? You can describe something you notice about the group, a sub-group, or even one histogram in particular.}

@Q{What do you Wonder about the histograms?}
}

Let's sort some histograms!

@lesson-instruction{
- With your partner, use the histogram cards to sort the cards into two piles: histograms that are roughly symmetrical, and histograms that are not roughly symmetrical.
- Be prepared to share your groupings with the class.
}

@teacher{
If students are not familiar with the concept of "symmetry", spend some time briefly explaining that it exists when the halves of the histogram are symmetrical. Ensure that students agree on which histograms are symmetrical and which ones are not.
}


=== Investigate

@lesson-instruction{
- With your partner, use the histogram cards to complete @printable-exercise{sorting-histograms.adoc}.
- We will pause for discussion after you complete the first section.
}

@teacher{
As you circulate: (1) make note of the different grouping strategies used by different students to foster group discussion, and (2) encourage students to use appropriate vocabulary (i.e., peak, cluster, gap).
}

Let's debrief.

@QandA{
@Q{How did you group your symmetrical histograms?}
@A{Responses will vary. Students may have grouped their histograms by the number of peaks, the number of gaps, or the location of the center. There are no wrong answers here.}

@Q{How can you determine what's typical of a symmetrical histogram?}
}

@lesson-instruction{
- With your partner, complete the second section of @printable-exercise{sorting-histograms.adoc}.
}

@QandA{
@Q{How did you group your symmetrical histograms?}
@A{Possible groupings: no peaks, 1 peak, 2 peaks; 1 gap, no gaps; and center at X, center at Y.}

@Q{How can you determine what's typical of a symmetrical histogram?}
@A{The center of a symmetrical histogram is the line of symmetry. A common misconception is arguing that the center of the axis is the center of the histogram; students must also consider the range of the histogram.}
}

You probably noticed that some histograms trail off to the left, and others trail off to the right. Statisticians refer to this trailing as "skew". Lets compare the skew-left, skew-right, and symmetric histograms.



[cols="^.^1a,^.^1a,^.^1a", options="header"]
|===

| Symmetric | Skew-left               | Skew-right

| @image{images/symmetric.png, 150 }| @image{images/left-w-foot.png, 150}  | @image{images/right-w-foot.png, 150}

| Values are balanced on either side of the center.

| Values are clumped around what's typical, but trail off to the right.

| Values are clumped around what's typical, but trail off to the left.

|===

Skew-left distributions look like the toes on your left foot, and skew-right distributions look like the toes on your right foot!

@vocab{Shape} is useful because it enables us to quickly identify and describe trends in data. *Shape is also one of a few key features that sets histograms apart from bar charts!* Let's explore this concept further.

@lesson-instruction{
Complete @printable-exercise{bar-chart-v-histogram.adoc}.
}

@teacher{
@printable-exercise{bar-chart-v-histogram.adoc} surfaces two common student misconceptions about bar graphs that @citation{whittaker-jacobbe-2017, "Whittaker and Jacobbe (2017)" } cite in their research. First, students commonly fail to understand that skew is associated with *distributions of quantitative variables*. This is why a bar graph with its bars arranged in increasing or decreasing order does not display a skewed distribution. Students also commonly believe that the category with the greatest value represents a majority of the responses. In this dataset, that is not the case: the bar representing the college of science does not represent more than half of the students.
}

Because a bar chart displays categorical data, we can order the bars anyway that we wish. That is not the case with histograms: since quantitative data must follow a natural order, a histogram's bars cannot be re-ordered.


=== Synthesize

@QandA{

@Q{Envision a skew-left histogram. Where do you think its outliers are? Explain how you know.}

@Q{Why do histograms have shape but bar graphs do not?}
}


== Choosing the Right Bin Size @duration{30 minutes}

@objective{choosing-bin-size}

=== Overview
Students learn to make histograms from the animals-dataset in @proglang and explore the importance of choosing the right bin size in order for a histogram to show us the shape of the data.

=== Launch
Bins that are too small will hide the shape of the data by breaking it into too many short bars. Bins that are too large will hide the shape by squeezing the data into just a few tall bars. So far, the bins were provided for you. But how do you choose a good bin-size?

@teacher{Make sure you have created a link or code for your class to @starter-file{histograms}.}

@lesson-instruction{
- Open the *Desmos* link I've shared with you. (The file should be called *Histogram Bin Size Exploration*.)
- Use the Bin Size slider to explore how changing the bin size impacts the shape of the histogram and what we can learn about the distribution of the data.
- Record your notices and wonders in the space provided on Slide 1.
- Before moving on to Slide 2, be sure to click the "New Dataset" button and see if you notice and wonder anything new.
- When you're done exploring Slide 1, move on to Slide 2 and answer the questions.
}

=== Investigate
Suppose we want to know how long it takes for animals from the shelter to be adopted.

@lesson-instruction{
- Log into @starter-file{program-list}, open your saved Animals Starter File, and click "Run".
- Complete @printable-exercise{choosing-bin-size.adoc}.
}

@teacher{Students who haven't saved this file yet can @starter-file{animals, make a new copy}.}

@slidebreak

@QandA{
@Q{What did you Notice?}
@A{We see most of the histogram's area under the two bars between 0 and 10 weeks, so we can say it was most common for an animal to be adopted in 10 weeks or less.}
@A{We see a small amount of the histogram's area trailing out to unusually high values, so we can say that a couple of animals took an unusually long time to be adopted: one took even more than 30 weeks.}
@A{More than half of the animals (17 out of 31) took just 5 weeks or less to be adopted. But the few unusually long adoption times pulled the average up to 5.8 weeks.}

@Q{What was a typical adoption time?}
@A{Almost all of the animals were adopted in 10 weeks or less, but a couple of animals took an unusually long time to be adopted -- even more than 20 or 30 weeks!}
@A{Be sure to draw attention to the fact that it would have been hard to give this summary by reading through the table, but the histogram makes it easy to see!}

@Q{What bin sizes worked best for analyzing `adoption`?}
@A{Have students talk about the bin sizes they tried. Encourage open discussion as much as possible here, so that students can make their own meaning about bin sizes before moving on to the next point.}
}

@slidebreak

@lesson-point{
Rule of thumb: a histogram should have between 5–10 bins.
}

Histograms are a powerful way to display a dataset and assess its @vocab{shape}. Choosing the right bin size for a column has a lot to do with how data is distributed between the smallest and largest values in that column! With the right bin size, we can see the _shape_ of a quantitative column.

@teacher{
But how do we talk about or describe that shape, and what does the shape actually tell us?

Our @lesson-link{visualizing-the-shape-of-data} lesson addresses these questions... and our @lesson-link{measures-of-center} lesson explores the effect of the shape of a histogram on the mean (average).
}

@slidebreak

@lesson-instruction{
Apply what you've learned by completing THE DATA CYCLE ???
}

=== Synthesize
- What would the histogram look like if most of the animals took more than 20 weeks to be adopted, but a couple of them were adopted in fewer than 5 weeks?
- What would the histogram look like if every animal was adopted in roughly the same length of time?


@teacher{

Want to check student mastery of the content you've just taught? Administer @assessment{histograms-check2-desmos} to get a snapshot of your students' current level of mastery. Make sure you have created a link or code for your class to the assessment.

Alternatively, we offer a compilation of both Checkpoints in @assessment{histograms-cumulative-desmos}.
}



@pd-slide{
Shape is Critical!

The axes are not labeled intentionally! We want you to get good  at identifying shape without leaning on numbers, because numbers can be very misleading in statistics.

K-12 mathematics doesn't talk about shape enough... and when we do talk about shape, we often give kids the misconception that all datasets should have a normal distribution - a hump in the middle of a bell curve. A robust focus on _shape_ helps address this misconception, while also helping to develop students' visual sense for statistics and distribution.
}
