= Project: Beautiful Data

@description{Students define row-consuming functions and combine them with advanced display contracts to create compelling data visualizations. _This project supports the learning goals of @lesson-link{advanced-visualizations}._}

@lesson-prereqs{advanced-visualizations}


[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...
@objectives
@objective{visual-cues}
@objective{advanced-display-pyret}

| Student-facing Lesson Goals
|

- Let's use creativity and code to meaningfully visualize data.

| Materials
|[.materials-links]

@material-links

| Key Points for the Facilitator
|
- This lesson uses visualizations that students created and discussed during @lesson-link{advanced-visualizations}.
- Visualizations created for this project can be added to @lesson-link{project-data-exploration} or @lesson-link{project-research-paper}!
|===

== Beautiful Data Project

Students advance their programming skills by using code to add their own flair and style to data that matters to them.

=== Launch

Data visualization is where data science and creativity mix. Data visualizations are meant to _tell a story_, and storytelling is an art form!

@lesson-instruction{
Take a moment to explore the resources below, and choose *one display* that really interests you:

- @link{https://pudding.cool/projects/vocabulary/index.html, The Largest Vocabulary in Hip Hop}
- @link{https://insightfulinteraction.com/immigration200years.html, 200 Years of Immigration}
- @link{https://informationisbeautiful.net/, Information is Beautiful}
}

@teacher{Allow students ample time to check out the provided resources. You might consider inviting a few students to share their reflections on the different visualizations.

We recommend printing and distributing the student-facing @handout{beautiful-data-rubric.adoc} to help students understand the scope of the project and your expectations at the outset. Teachers are welcome and encouraged to edit and adapt the rubric for their unique classroom context.}

@lesson-instruction{
Respond to the questions in the first section of @handout{beautiful-data-reflect.adoc}.
}

@slidebreak

Today, you're going to get a chance to create your own customized data visualization - one that connects artistic expression to data in ways that are relevant and meaningful.

The first step is to find your data!

@lesson-instruction{
- @lesson-link{choosing-your-dataset/pages/datasets-and-starter-files.adoc, Choose a dataset} that interests you - or use one that you're already working with - and create a `bar-chart`, `pie-chart`, `histogram`, or `scatter-plot` in @starter-file{program-list}.
- Complete the second section of @handout{beautiful-data-reflect.adoc}.
}

=== Investigate


@right{@image{images/age-v-weeks.gif, 250}}

Once we have created a basic display, things start to get interesting!

- The scatter plot on the right suggests a moderate correlation between age and weeks: older animals take longer to be adopted.
- But the connection is not as direct as we might think!
- It's time to get curious, and ask ourselves: *What data is missing?*

@slidebreak

@ifslide{@right{@image{images/age-v-weeks.gif, 300}}}

@teacher{
Solicit student responses. Students may wonder whether the species matters; how big each animal is; and whether or not each animal is fixed.
}

@slidebreak

@left{@image{images/age-v-weeks-species-dot.png, 350}}
Once we write code to add the species column to our data visualizations by customizing the dots, we see some interesting results!

Right away, we can see that cats and dogs take longer to be adopted based on their age, but the impact of each extra year is much smaller for cats than for dogs. It's almost like we have two stronger correlations in the same display: the line for dogs slopes up more steeply, and the line for cats is more gentle. When all the dots looked the same, these lines blurred each other out to create one weak-to-moderate correlation.

@slidebreak

@teacher{Specify how you would like students to submit Pyret files. Email, a form, or any platform that allows students to share links (i.e., Google Classroom or Schoology) will work.}

@lesson-instruction{
- Think about at least two columns that might give you more insight into your data, and why those other columns matter in the display(s) you’ve chosen.
- In your @starter-file{program-list}, define a row-consuming function that produces custom images for each Row in your dataset using your new column(s).
- Use that row-consuming function to create a data visualization that makes the data pop and really shows the deeper patterns at work.
}

=== Synthesize

@ifslide{
Use the @handout{beautiful-data-rubric.adoc, "rubric"} to assess and revise your work.
}

@teacher{
- Encourage students to self-assess and revise their work. Peer review is a powerful tool if time allows! The @handout{beautiful-data-rubric.adoc, "rubric"} is a useful resource for facilitating both self and peer review.

- Finally, celebrate students' work! In many instances, students will want to share their project, given how much time they have invested. Class or public presentations can instill a sense of pride.
}
