= Other Forms of Quadratic Models
++++
<style>
.lesson-instruction table .autonum { font-weight: bold; }
</style>
++++
@description{}

@lesson-prereqs{quadratic3-fitting-models}

@keywords{quadratic, square, coefficient}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

| Student-facing Lesson Goals
|

- Let's use Pyret to model quadratic relationships in data.


| Materials
|[.materials-links]
@material-links

|===


== Other Forms of Quadratic Models
@objective{quadratics-forms}

=== Overview
Students are introduce to Factored Form and Standard Form, and why they each have a role to play in modeling.

=== Launch
++++
<style>
.clippedImage img {clip-path: inset(50px 0px 0px 0px); margin-top: -50px; }
</style>
++++
[.clippedImage]
@right{@image{images/p3.png, 150}} Defining our model using the *Vertex Form* require us to know the vertex, but a scatter plot of quadratic data, doesn't always reveal the vertex!

As with Linear Models, mathematicians and data scientists use different forms of Quadratic Models to make model-fitting and calculations easier.

==== Factored Form: @hspace{1em} @math{f(x) = a(x - r_1)(x - r_2)}

Factored form makes it really easy to identify the _roots_ of the function, where the parabola crosses the x-axis.

If @math{x = r_1} or @math{x = r_2}, one of the parenthetical terms will be zero and make the whole equation zero.

Factored form is especially useful, where a scatter plot shows the roots but not the vertex!

@slidebreak

==== Standard Form: @hspace{1em} @math{f(x) = Ax^2 + Bx + C}

Standard form requires that any polynomial be written with their terms from highest to lowest degree. The standard form for quadratics puts the quadratic (squared) term first, followed by the linear term, followed by the constant term for vertical shift. Knowing that an equation is in standard form makes it easy for someone to know exactly what kind of equation it is just by looking at the first term.

@teacher{This is a great time to include your textbook's traditional content on standard form!}

The coefficients in standard form can also be computed by the @link{https://en.wikipedia.org/wiki/Quadratic_formula, quadratic formula}, which is useful when simple factoring isn't enough.

@lesson-instruction{
- Complete @printable-exercise{classifying-defs.adoc} to get comfortable identifying the different forms of quadratic functions.
}


=== Investigate

@lesson-instruction{
Let's try to use standard form to build a model from _samples_.

- Open your copy of the @starter-file{alg2-aaron-judge}.
- With your partner, complete @printable-exercise{build-from-samples-batting-data.adoc}.
}


=== Synthesize

- How close did your sampled model get to the one you created visually using Desmos sliders in @lesson-link{quadratic3-fitting-models}?
- Which method did you like better?

== Additional Exercises

- @opt-printable-exercise{build-from-samples-fuel-efficiency.adoc} engages students with the @opt-starter-file{alg2-fuel-efficiency}.

@indented{
@teacher{
*NOTE*: While the fuel efficiency dataset used in the optional materials we'll be offering throughout our quadratics lessons is based on real data obtained from the @link{https://tedb.ornl.gov/, Transportation Energy Book}, *it has been augmented with fictional data* in order to provide a sufficiently-rich dataset for student modeling. You can find out more about this augmentation in the README tab of @link{https://docs.google.com/spreadsheets/d/1SLm1hDkVgAYxgh12dTD2Z3GXCUO9PrbwIZdqu9FiCGI/edit?gid=0#gid=0, the dataset}.
}
}

- @opt-printable-exercise{match-graph-v.adoc}
- @opt-printable-exercise{match-graph-f.adoc}
- @opt-printable-exercise{match-graph-s.adoc}.

@vspace{1ex}

@strategy{Coming Soon!}{

We are working on collecting more datasets that can be modeled with quadratic functions so that we can offer students more practice with building quadratic models and engage them in thinking about which form is most efficient to start with depending on the available data.
}
