= Meet Soekia! (Continued)

@link-instructions{Respond to the prompts below by interacting with @starter-file{soekia}}

== N-Grams

The orange _N-grams_ panel is where Soekia lists out possible n-grams and their frequency of occurrence within the training corpus. The default setting ("3") displays a list of every trigram that appears in the training corpus. 

@n The most common trigram appears at the top of the list. Click on it. What do you learn? @fitb{}{@ifsoln{I can see how many times the trigram appears,}}

@fitb{}{@ifsoln{and in which documents.}}

@n At the top of the orange _N-grams_ panel, select "4" to indicate that you want Soekia to display 4-grams. What is the most common 4-gram in the corpus? @fitb{}{@ifsoln{Lord Marquis of Carabas}}

@vspace{1ex}

Take a minute to explore the N-Grams Panel, by scrolling through the list of N-Grams and clicking on some other examples. 

@n What do you Notice? What do you Wonder? 

@blanklines{4}{
@ifsoln{
*Possible Noticings:* Punctuation counts as a word! The green bar under each trigram indicates how often it appears in the corpus. The most common trigram appears almost as twice as frequently as the next most common trigram. *Possible Wonderings:* Why does Soekia interpret a period as a word? Why do individual 5-grams appear so much less frequently than individual unigrams?
}
}

== Suggested words

In the _Suggested words_ panel, Soekia offers possible completions for different inputs. Click on one of the suggestions. 

@n What information appears? @fitb{}{@ifsoln{We learn how many times the suggestion is used in the training corpus, }}

@fitb{}{@ifsoln{and in which document it appears.}}

@vspace{1ex}

- Click "Customize temperature/ number of suggestions" on the middle of the left-side of the _Suggested words_ panel. Set the temperature to *low*. 
- In the _Generate Text_ panel, click @image{../images/send-icon.png, 15} to tell a fairy tale. 

@n Once a few sentences have appeared, read and rate the story: @hspace{1em} _It makes no sense._ @hspace{1em} _It sort of makes sense?_ @hspace{1em} _Wow! It makes sense!_

@vspace{1ex}

- In the _Generate Text_ panel, click @image{../images/reset-icon.png, 15} to delete the story and start over. 
- In the _Suggested words_ panel, click "Customize temperature/ number of suggestions" and set the temperature to *high*.
- In the _Generate Text_ panel, click @image{../images/send-icon.png, 15} to tell another fairy tale. 

@n Once a few sentences have appeared, read and rate the story: @hspace{1em} _It makes no sense._ @hspace{1em} _It sort of makes sense?_ @hspace{1em} _Wow! It makes sense!_

@vspace{1ex}

Spend some time clicking and exploring the _Suggested words_ panel. 

@n What do you Notice about the _Suggested words_ panel? What do you Wonder about the _Suggested words_ panel? 

@blanklines{4}{
@ifsoln{Possible Noticings: The _Suggested words_ panel updates automatically as Soekia generates text. Soekia often suggests a 5-gram and the shorter n-grams that are contained within that 5-gram (e.g., "the wind in the trees", "wind in the trees", "in the trees" and "trees"). Possible Wonderings: What are the different ways that I can customize the selection? How does changing the temperature affect the output?
}
}