= (More) Exploring Displays

++++
<style>
.fitb{height: 2rem;}
tbody tr:first-child { height: 3.6in; }
</style>
++++

For each type of display, fill in the information below.

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Scatter Plot
| Linear Regression Plot

| @ifsoln{@image{scatter-plot.png}} Sketch a scatter plot here.
| @ifsoln{@image{lr-plot.png}} Sketch a linear regression plot here.

|
--
@span{.left}{
Scatter Plots are constructed from @fitb{3ex}{2} column(s), and show @fitb{28ex}{quantitative} data.
What do you think this display tells us?
@fitb{55ex}{@ifsoln{_something about the relationship between two quantitative_}}
@fitb{55ex}{@ifsoln{_columns, graphing all pairs of values as points on a plane._}}
@fitb{55ex}{@ifsoln{_This allows us to look for patterns, clusters, trends, etc._}}
}
--

|
--
@span{.left}{
LR Plots are constructed from @fitb{3ex}{2} column(s), and show @fitb{28ex}{quantitative} data.
What do you think this display tells us?
@fitb{55ex}{@ifsoln{_something about the relationship between two quantitative_}}
@fitb{55ex}{@ifsoln{_columns, graphing all pairs of values as points on a plane,_}}
@fitb{55ex}{@ifsoln{_drawing the line of best fit, and showing correlation stats_}}
}
--
|===
