= Histograms and Variability




@n Students watched 2 videos, and rated them on a scale of 1 to 10. The average score for every video is the same (5.5). The top histogram is for Movie A, the bottom histogram is for Movie B.


[cols="^1a,<1a"]
|===

| @image{../images/histogram-a.png, 200}
@image{../images/histogram-e.png, 200}

|

Comparing the two graphs, we know that:

@vspace{1ex}

- [ ] The scores for Movie A have greater variability.

@vspace{1ex}

- [ ] The scores for Movie B have greater variability.

@vspace{1ex}

- [ ] The scores for Movie A and Movie B have equal variability.

@vspace{1ex}

- [ ] It is impossible to tell from the given information.

@vspace{1ex}

Explain how you arrived at your answer:

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

|===




@n The following graphs show the distribution of quiz scores for two classes, Class 1 (top) and Class 2 (bottom).

[cols="^1a,<1a"]
|===

| @image{../images/class1quiz.png, 200}
@image{../images/class2quiz.png, 200}

|

Comparing the two graphs, we know that:

@vspace{1ex}

- [ ] The quiz scores of Class 1 have greater variability.

@vspace{1ex}

- [ ] The quiz scores of Class 2 have greater variability.

@vspace{1ex}

- [ ] The quiz scores of Class 1 and Class 2 have equal variability.

@vspace{1ex}

- [ ] It is impossible to tell from the given information.

@vspace{1ex}

Explain how you arrived at your answer:

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

|===



@n Caro says, "Flatter histograms always show less variability." Is she correct? Explain why you agree or disagree with Caro.

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}
