= Histograms and Measures of Center

@n The two histograms below show the number of minutes students spent traveling to school: one represents a sample of sixth grade students and the other represents a sample of eighth grade students. All travel times in the dataset are whole numbers.

[cols="^1a,^1a"]
|===
| *Distribution of Travel Times (Sixth Grade)*
  @image{../images/travel-time-a.png, 200}
| *Distribution of Travel Times (Eighth Grade)*
  @image{../images/travel-time-b.png, 200}
|===

@n Which group has the larger mode(s). @hspace{1em} sixth graders @hspace{2em} @ifsoln-choice{eighth graders} @hspace{2em} the modes are roughly the same

@teacher{Students might choose 6th graders because the tallest bin has 10, whereas the tallest 8th grade bin has 9... but we're looking for which value the tallest bin lands on, which is between 10 and 15 for 8th graders and between 5 and 10 for sixth graders.}

@n The histogram below shows the ages of the 19 children who signed up for rock climbing camp.

[cols="^3a,<4a"]
|===
| *Distribution of Rock Climbers' Ages*
@image{../images/rock-climbing-ages.png, 190}
| The median age for these 19 climbers is:

@vspace{1ex}

&#9744; about 6 or 7

@vspace{1ex}

@ifsoln-choice{&#9744; about 8 or 9}

@vspace{1ex}

&#9744; about 10 or 11

@vspace{1ex}

&#9744; about 12 or 13
|===

Explain how you determined the median value: @fitb{}{@ifsoln{Possible response: I knew that the 10th value is the median, because there }}

@fitb{}{@ifsoln{are 19 children represented. I located the 10th value on the histogram, and it was in the 8-9 interval.}}

@ifnotsoln{@fitb{}{}}


@n Eleven students were asked to solve a logic puzzle. The minimum time was 5 minutes, and the maximum time was 35 minutes. The distribution of their times is shown on the histogram below.


[cols="^3a,<4a"]
|===
| *Distribution of Time Spent Solving a Logic Puzzle*
@image{../images/logic-puzzle.png, 210}
| Which of the following statements is likely a correct comparison of the mean and median number of minutes spent working?

@vspace{1ex}

&#9744; The mean time is less than the median time.

@vspace{1ex}

&#9744; The mean time is equal to the median time.

@vspace{1ex}

@ifsoln-choice{&#9744; The mean time is greater than the median time.}

@vspace{1ex}

&#9744; There isn't enough information provided to determine which is greater.
|===

Explain how you arrived at your choice: @fitb{}{@ifsoln{The outliers on the right pull the mean to the right,}}

@fitb{}{@ifsoln{resulting in a greater mean than median.}}

@fitb{}{}


