= Variables

++++
<style>
.circleevalsexp { display: inline; }
</style>
++++
@description{Students are introduced to variables.}

@lesson-prereqs{equivalence}

@keywords{variables, values}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|
- Let's learn what a variable is.

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
- This lesson emphasizes that not all letters used in math are @vocab{variables}. In fact, many letters students encounter in math problems and programming have defined @vocab{values}. We encourage you to make sure that you are clear on the distinction.
|===

== Programming Exploration: What is a variable?
@scrub{
@objective{Students will understand what a variable is and why they are useful.}
@objective{Students will be able to explain the difference between a variable and a letter that is actually a value.}
}

=== Overview
Students consider what makes one line of code produce output that is equivalent to the output of another line of code.

=== Launch
@slidebreak{Launch}

What if a programmer wants to determine whether two lines of code will produce the same result? They have two options. They can test the code and see what happens. More experienced programmers, however, study the structure of the code. They think about the functions being used... and then come to a conclusion. These programmers are more strategic and efficient when they write their own code.

=== Investigate
@slidebreak{Investigate-DN}

Alex was born on his dad's 30th birthday. Whether Alex is a baby or an adult, how would we find his dad's age?

The tax on clothes in Saratoga Springs, NY is 7%. Regardless of whether we buy $5 or $5000 worth of clothes, how would we calculate the tax?

The area of a rectangle is determined by multiplying the base x the height. This works for rectangles of all shapes and sizes including rectangles that are squares and long skinny rectangles.

A website sells blue, green and red backpacks with 3 letters of your choice embroidered on it. What are the variables that customers need to select?

A garden center sells Amaryllis bulbs. They can be purchased bare or potted and will bloom white, pink, variegated or red.

A photograph that can be printed at 4x6 can also be printed smaller or larger. How could you describe the height of the print in terms of its width?

=== Synthesize

@QandA{
@Q{How would you describe what a variable is in your own words?}
@A{}

@Q{How can we tell whether a letter is a value or a variable?}
@A{One we declare that a letter equals a numerical value, it is value rather than a variable.}

@Q{Why are variables useful?}
@A{}
}