= Practice Plotting

++++
<style>
td, th, .center { padding: 0 !important; vertical-align: middle; }
p { margin: 0 !important; }
.checklist li { margin: 0; padding: 0; }
</style>
++++

Use the @starter-file{animals} to create the following displays in CODAP. First, fill in the blanks and check all boxes that apply. Next, create the display in CODAP. Finally, sketch the displays and answer the questions. We've started the first one for you.

@vspace{1ex}



@n A histogram of the number of `pounds` that animals weigh.
[cols="1a,1a,1a", options="header"]
|===
|@center{*Column / Attribute*}
|@center{*Type of Data*}
|@center{*Configuration*}

|
@fitbruby{100%}{pounds}{[column used as x-axis]}
@fitbruby{100%}{n/a}{[column used as y-axis]}

|

* [x] Numeric
* [ ] Categorical

|

* [ ] Points
* [x] Fuse dots into bars
* [ ] Bar for each point
* [x] Group into bins
* [ ] No need to make a selection


|===


[.FillVerticalSpace, cols="^1a,^1a", options="header"]
|===
|*Sketch the chart below:*
|*What do you think the data display tells us?*

|
@ifsoln{@image{../images/weight-histo.png, 150}}

@ifnotsoln{ @vspace{20ex} }

|
@ifnotsoln{ @vspace{10ex} }

@ifsoln{
The display shows us the distribution of animals' weights into varying increments.
@vspace{5ex}
}

|

|===

@vspace{1ex}

@n A dot plot showing the `sex` of animals from the shelter.
[cols="1a,1a,1a", options="header"]
|===
|@center{*Column / Attribute*}
|@center{*Type of Data*}
|@center{*Configuration*}

|
@fitbruby{100%}{@ifsoln{sex}}{[column used as x-axis]}
@fitbruby{100%}{@ifsoln{n/a}}{[column used as y-axis]}

|
@ifnotsoln{
* [ ] Numeric
* [ ] Categorical
}

@ifsoln{
* [ ] Numeric
* [x] Categorical
}

|
@ifnotsoln{
* [ ] Points
* [ ] Fuse dots into bars
* [ ] Bar for each point
* [ ] Group into bins
* [ ] No need to make a selection
}

@ifsoln{
* [ ] Points
* [ ] Fuse dots into bars
* [ ] Bar for each point
* [ ] Group into bins
* [x] No need to make a selection

}

|===


[.FillVerticalSpace, cols="^1a,^1a", options="header"]
|===
|*Sketch the chart below:*
|*What do you think the display tells us?*

|
@ifsoln{@image{../images/dot-plot.png, 200}}

@ifnotsoln{ @vspace{20ex} }

|
@ifnotsoln{ @vspace{10ex} }

@ifsoln{
The display tells us how many animals are male, hermaphrodite, and female.
@vspace{5ex}
}

|

|===


