= Building and Testing a Decision Tree

On @printable-exercise{which-question.adoc}, we decided that the decision mode at the end of the "teens" branch should be "interest in game". Let's create the rest of the tree and test it out. You can refer to the training dataset on @handout{decision-tree-data.adoc}.

== Build and Understand the Tree

Fill in the remainder of the tree using the algorithm you have learned (left) before filling in the blanks (right).

[cols="1,1", stripes="none"]
|===

|
@ifnotsoln{@center{@image{../images/incomplete-tree.png, 350}}}

@ifsoln{@center{@image{../images/final-tree, 350}}}

|

@n The root node of this tree is @fitb{10em}{@ifsoln{age}}.


@n The first set of branches includes @fitb{10em}{@ifsoln{teens}}, @fitb{10em}{@ifsoln{twenties}}, and @fitb{10em}{@ifsoln{thirties}}.

@vspace{1ex}

@n Write some rules: @ifsoln{Answers will vary.}


a) Predict that @fitb{10em}{@ifsoln{interested teens}} will buy the game.

b) Predict that all individuals in their twenties @fitb{10em}{@ifsoln{will buy the game}.

c) Predict that @fitb{10em}{@ifsoln{new customers in their thirties}} will not buy the game.

|===


== Test the Tree

Let's see how well our decision tree recommends apps for three additional individuals, who were _not_ a part of the training dataset.

[cols="2,2,3,2,2", stripes="none", options="header"]
|===

| name 		| age 		| shopping history 	| interest in game 	| buys game
| Kat 		| teen 		| new customer		| yes 				| yes
| Billy		| twenties	| new customer		| no 				| no
| Chen	    | twenties 	| previous customer | no  				| no

|===

@n What prediction will the decision tree make for Kat? @fitb{10em}{@ifsoln{will buy}} Billy? @fitb{10em}{@ifsoln{will buy}} Chen? @fitb{10em}{@ifsoln{will buy}}

@n Compare the test data with the decision tree recommendations. How often was the computer correct? @fitb{10em}{@ifsoln{1 out of 3 times}}


@n Based on this new test data, which rule (Q4, above) needs to change? Why? @fitb{}{@ifsoln{We need to change Rule b, that all individuals in their 20s will buy the game.}}

@fitb{}{@ifsoln{The new test data indicates that some individuals in their twenties will buy the game.}}

== Reflect

@n The decision tree we built was correct 100% of the time with our training dataset, but correct only 33% of with our test dataset. Why

