= Which Question Should We Ask First?


[cols="1,1,1", stripes="none", options="header"]
|===

| sex		| age	| app
| female 	| 16 	| tiktok
| female 	| 24	| youtube
| male		| 33	| facebook
| female 	| 35	| youtube
| male 		| 12 	| tiktok
| male	 	| 13 	| tiktok

|===

== Let's consider "sex" first.

@n Using information from the "sex" column and the "app" column, fill in the blanks below.

- The training data indicates that females are most likely to use @fitbruby{15em}{@ifsoln{youtube}}{tiktok / youtube / facebook}.

- The training data indicates that males are most likely to use @fitbruby{15em}{@ifsoln{tiktok}}{tiktok / youtube / facebook}.

Here’s our rule: “Recommend @fitbruby{15em}{@ifsoln{youtube}}{tiktok / youtube / facebook} to females and recommend @fitbruby{15em}{@ifsoln{tiktok}}{tiktok / youtube / facebook} to males.”

@n Will a computer following this rule provide the correct app for all six individuals in the training dataset? @fitb{5em}{@ifsoln{No.}}

@n According to our training data, this rule is correct in @fitb{5m}{@ifsoln{four}} instances out of six.

Here is one way to represent the decision tree for "sex". Place checkmarks below all correctly predicted values in the "male" leaf node.

@image{images/sex-stump.png, 200}

Are either of the leaf nodes for "sex" pure? (__Pure__ means that the leaf contains exclusively one single value.) @fitb{}{}
