= Decision Tree: Level 2

== Shopping History as the Decision Node

@n Using information from the "age" column and the "shopping history" column, fill in the blanks below.

@indented{a) The training data indicates that *frequent customers in their teens* @fitbruby{10em}{@ifsoln{will}}{will / will not} buy the game.

b) The training data indicates that *new customers in their teens* probably @fitbruby{10em}{@ifsoln{will}}{will / will not} buy the game.

@vspace{1ex}

c) The training data on *infrequent customers in their teens* does provide any information on the likelihood of game purchase. Explain.

@fitb{}{}

@fitb{}{}

}


@n Rule: *Predict that frequent teenager shoppers @fitbruby{5em}{@ifsoln{will}}{will / will not} buy the game and that new teenage customers @fitbruby{5em}{@ifsoln{will}}{will / will not} buy the game.*

@n Will a computer following this rule make the correct prediction every time? @fitb{5em}{@ifsoln{No.}}

@n According to our training data, this rule is correct in @fitb{5m}{@ifsoln{three}} instances out of five.

@n Create a decision stump for "shopping history" with a root node of "teens". Place checkmarks below all correctly predicted values in the leaf node.

@ifnotsoln{@vspace{15ex}}

@ifsoln{@center{@image{../images/age-stump.png, 150}}}


== Interest in Game as the Decision Node

@n Using information from the "age" column and the "interest in game" column, fill in the blanks below.

@indented{

a) The training data indicates that *interested teens*  @fitbruby{10em}{@ifsoln{will}}{will / will not} buy the game.

b) The training data indicates *uninterested teens* probably @fitbruby{10em}{@ifsoln{will}}{will / will not} buy the game.
}

@n Rule: *Predict that interested teenager shoppers @fitbruby{5em}{@ifsoln{will}}{will / will not} buy the game and uninterested teenagers shoppers @fitbruby{5em}{@ifsoln{will}}{will / will not}.*

@n Will a computer following this rule make the correct prediction every time? @fitb{5em}{@ifsoln{Yes!}}

@n Create a decision stump for teenagers' interest in the game.Place checkmarks below all correctly predicted values in the leaf node.

@ifnotsoln{@vspace{15ex}}

@ifsoln{@center{@image{../images/interest-stump.png, 150}}}

== What decision attribute should we use at the root node?

@n Shopping history or interest? Explain your response. @fitb{}{@ifsoln{interest in game}}

@fitb{}{}
