= Fei Fei Li

++++
<style>
@import url("../../../lib/pioneers.css");
</style>
++++

[.posterImage]
@image{../images/fei-fei-li.png}

[.credit]
Credit:  https://profiles.stanford.edu/fei-fei-li

[.name]
Fei Fei Li

[.title]
A "Godmother" of Artificial Intelligence

[.text]
Born in Sichuan, China, Li moved to the US with her family in high school. While learning English, she excelled in mathematics and, within three years of arriving in the US, she started her studies at Princeton. Around that same time her family started a laundromat, and she returned home from college every weekend to help run the family business. Li's curiosity for exploring the most challenging questions in nature led her to pursue research in how the brain works... and eventually to artificial intelligence. She earned her PhD from the California Institute of Technology and is now a leading expert in the branch of AI known as computer vision and continues her research as Co-Director of Stanford University’s Human-Centered AI Institute. One of her many contributions to the field includes leading the effort to create ImageNet, a database of hundreds of thousands of labeled images used to train computer vision algorithms to recognize objects and the contexts they appear in. One of her hopes is that as computers learn to “see”, they will help humans make medical diagnoses, drive more safely, etc. In 2023 Dr. Li published  "The Worlds I See", in which she tells her story of immigrating to the US and explains her work in computer vision. Li also heads AI4All, a program that encourages diverse groups of high school students to become involved in artificial intelligence. 

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. We offer FREE, research-driven, integrated Computer Science & Data Science modules for Math, Physics, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
