= Joy Buolamwini

++++
<style>
@import url("../../../lib/pioneers.css");
</style>
++++

[.posterImage]
@image{../images/joy-buolamwini.png}

[.credit]
Credit: Joy Buolamwini https://creativecommons.org/licenses/by-nc-nd/2.0/

[.name]
Joy Buolamwini

[.title]
Digital Activist, Poet of Code, AJL Founder

[.text]
Born in Edmonton, Alberta, Buolamwini grew up in Mississippi and was inspired to teach herself to code at age 9 by Kismet, the MIT robot. A competitive pole vaulter, Buolamwini graduated from Cordova High School in Tennessee and completed undergraduate studies at Georgia Tech before earning her PhD from the MIT Media Lab. She founded the Algorithmic Justice League (AJL) in 2016 to promote equitable and accountable artificial intelligence (AI). The AJL combines art and research to point out potential societal implications and harms of AI. In fact, Buolamwini's research, which revealed gender and race bias in AI system's by Google and Microsoft, has prompted these companies to examine and change their products and processes. The Netflix documentary Coded Bias features Buolamwini’s research about AI inaccuracies in facial recognition technology and automated assessment software.

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. We offer FREE, research-driven, integrated Computer Science & Data Science modules for Math, Physics, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
