= Katherine Johnson

++++
<style>
@import url("../../../lib/pioneers.css");
</style>
++++

[.posterImage]
@image{../images/katherine-johnson.png}

[.credit]
Image cartoonized using vanceai.com

[.name]
Katherine Johnson

[.title]
Mathematician -- NASA Flight Research Division

[.text]
Johnson, who was featured in the 2017 film "Hidden Figures," worked as a computer in NASA's Flight Research Division for 33 years. Her work made it possible for John Glenn to orbit the Earth, and she calculated the precise trajectories that would let Apollo 11 land on the moon. Despite these achievements, almost no one knew Johnson's name until decades later, when, in 2015, President Barack Obama awarded Johnson the Presidential Medal of Freedom, proclaiming, “Katherine G. Johnson refused to be limited by society’s expectations of her gender and race while expanding the boundaries of humanity’s reach.” Johnson grew up in West Virginia. She took every math course offered by West Virginia State College (some were added just for her!) and earned a double major in French. She taught public school for a year after graduation, before marrying and focusing on raising 3 children. She was the first African-American woman to attend graduate school at West Virginia University after the Supreme Court ruling in Missouri ex rel. Gaines v. Canada required States which provided public higher education to white students to provide it to black students as well. Johnson lived to be 101.

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. FREE, research-driven, integrated Computer Science & Data Science modules for Math, Science, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
