= Mark Dean

++++
<style>
@import url("../../../lib/pioneers.css");
</style>
++++

[.posterImage]
@image{../images/mark-dean.png}

[.credit]
Image cartoonized using vanceai.com

[.name]
Mark Dean

[.title]
Inventor, Computer Engineer

[.text]
In the 1980s, Dean was chief engineer of the 12-person team that designed the original IBM PC. Dean's work at IBM led to the development of the color PC monitor as well as the first gigahertz chip -- a revolutionary piece of technology that can do a billion calculations per second! Dean holds three of IBM's original nine patents, and in total has twenty to his name. From an early age, Dean loved building things -- and even has memories of constructing a tractor from scratch with his father when he was a young boy in Tennessee. Dean states, "a lot of kids growing up today aren't told that you can be whatever you want to be." He acknowledges, "There may be obstacles, but there are no limits." In 1996, Dean was the first African American ever to be named an IBM fellow, and in 1997, he was honored with the Black Engineer of the Year President's Award.

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. FREE, research-driven, integrated Computer Science & Data Science modules for Math, Science, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
