= Taher Elgamal

++++
<style>
@import url("../../../lib/pioneers.css");
</style>
++++

[.posterImage]
@image{../images/taher-elgamal.png}

[.credit]
Image cartoonized using vanceai.com

[.name]
Taher Elgamal

[.title]
Security Leader, Cryptographer, CISO, CTO

[.text]
Elgamal is a world-renowned Egyptian-American cryptographer -- someone who studies secure communication techniques. He is considered a pioneer of the Secure Sockets Layer (SSL), which allows sensitive information such as credit card numbers, social security numbers, and login credentials to be safely transmitted online. SSL secures millions of peoples’ data on the Internet each day! You can tell that a website is SSL-secured -- and you can simultaneously see the impact of Elgamal's work -- when a web address begins with "https" rather than "http."  After earning his B.S. from Cairo University Elgamal went on to earn his PhD in Electrical Engineering from Stanford University, graduating at the beginning of the dot com era. He has authored important papers since the 1980s, been an entrepreneur, and has held several executive roles at technology and security companies. Elgamal's first love was mathematics. He's said, "cryptography was the most beautiful use of math I'd ever seen."

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. FREE, research-driven, integrated Computer Science & Data Science modules for Math, Science, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
