= Ordre des opérations

++++
<style>
.codetwo { white-space: nowrap; }
</style>
++++

*L'ordre des opérations* est incroyablement important en programmation. Pour nous aider à bien organiser nos maths, nous pouvons faire un _schéma_ d’une expression mathématique avec des *cercles d’évaluation*. Par exemple, l'expression @smath{(/ (- 1 4) (* 10 7))} peut être schématisée comme indiqué ci-dessous.

[.centered-image]
@show{(coe `(/ (- 1 4) (* 10 7)))}

@vspace{2ex}

@ifproglang{wescheme}{
Pour convertir un *cercle d'évaluation* en code, nous passons dans le cercle de l'extérieur vers l'intérieur, de gauche à droite. Nous faisons une parenthèse ouverte quand nous _commençons_ un cercle, et une parenthèse fermée quand nous _finissons_ un cercle. Une fois que nous sommes dans un cercle, nous écrivons d'abord la *fonction* en haut, puis les entrées de gauche à droite. Le cercle ci-dessus, par exemple, serait programmé comme ceci : @show{(code '(/ (- 1 4) (* 10 7)))}.
}

@ifproglang{pyret}{
Pour convertir un *cercle d'évaluation* en code, nous passons dans le cercle de l'extérieur vers l'intérieur, en nous déplaçant de gauche à droite. Nous faisons une parenthèse ouverte quand nous _commençons_ un cercle, et une parenthèse fermée quand nous _finissons_ un cercle. Une fois que nous sommes dans un cercle, nous écrivons ce qui se trouve à gauche du cercle, puis l'*opération* en haut, et enfin, ce qui se trouve à droite. Le cercle ci-dessus, par exemple, serait programmé comme ceci : @show{(code '(/ (- 1 4) (* 10 7)) #:parens true)}.
}
