= Traduire les cercles d'évaluation en code, avec des racines carrées

Traduisez chacune des expressions arithmétiques ci-dessous en cercles d'évaluation, puis traduisez-les en code.
@ifsoln{*Enseignants :* le corrigé de code ci-dessous est montré avec seulement les parenthèses _nécessaires_. Si un élève ajoute des parenthèses supplémentaires (correctes), il aura quand même la bonne réponse.}

*INDICE :* Le nom de la fonction est @show{(code 'sqrt)}.


@do{
  (define expr1 '(sqrt 9))
  (define expr2 '(sqrt (+ 5 1)))
  (define expr3 '(+ (sqrt 4) 1))
  (define expr4 '(+ (* 3 (sqrt 3)) (sqrt 7)))
}

[.FillVerticalSpace, cols="^.^1a,^.^8a,^.^15,^.^15a",options="header",stripes="none"]
|===
|
| Expression arithmétique
| Cercle d’évaluation
| Code

|*@n*
| @show{    (math expr1)}
| @showsoln{(coe  expr1)}
| @showsoln{(code expr1)}

|*@n*
| @show{    (math expr2)}
| @showsoln{(coe  expr2)}
| @showsoln{(code expr2)}

|*@n*
| @show{    (math expr3)}
| @showsoln{(coe  expr3)}
| @showsoln{(code expr3)}

|*@n*
| @show{    (math expr4)}
| @showsoln{(coe  expr4)}
| @showsoln{(code expr4)}

|===
