= Piecewise Functions 

@lesson-description{Students will learn how one function can have different behaviors based on the input.}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Explain what a piecewise function is.
* Give examples of inputs and outputs of a given piecewise function.

|Student-Facing Lesson Goals
|
* I can describe how piecewise functions work.

|Key Points for the Facilitator
|
* The Design Recipe looks a bit different for piecewise, or conditional, functions.  Check that students are taking time to write examples and circle what is changing.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.
* Students should be familiar with the Design Recipe.

|Materials
|
* @link{https://docs.google.com/presentation/d/1Xz0VOY7Kg_lawcRPvZX5FvPnZ8pdRfiQ4JRjtl54mP4/edit?usp=sharing, Google Slides}
* @link{https://www.wescheme.org/openEditor?publicId=pLVBsxgC93, Piecewise Mystery Functions starter file}
* @link{https://drive.google.com/open?id=1D72mjH1GZiZYIHXFJ-KSHpTSckBy0VlTthjs9tnIJts, Alice's Restaurant Exploration}
* @link{https://www.wescheme.org/openEditor?publicId=SF5vyMJyw2, Alice's Restaurant starter file}

////
Connection Activities
* @link{https://teacher.desmos.com/activitybuilder/custom/57d6b323d5b6478408b8748b, Domain & Range of Piecewise Function} (Desmos Activity)
////

|===

[.left-header,cols="20a,80a", stripes=none]
|===

|Approaching (CCSSM)
|
* @std{HSA.SSE.A.1.A}
* @std{HSA.SSE.A.1.B}

|Standards for Mathematical Practice (CCSSM)
|
* @std{MP.8}

|===

== Get Ready:

Students should have their computer, workbook, contracts page, and pencil.

== Launch: (10 min)

What's My Rule?

Students open the @link{https://www.wescheme.org/openEditor?publicId=pLVBsxgC93, Piecewise Mystery Functions file} and try to determine the behaviors of the three built-in functions by trying different input values.  

== Explore: (10 min)

Students open the @link{https://www.wescheme.org/openEditor?publicId=JUXrqT0UT5, Alice's Restaurant file} and turn to @worksheet-link{workbook-pages/PiecewiseFunctions1-WB1.pdf, Alice's Restaurant - Explore} .  Students investigate the file using their workbook page as a guide.

[.notice-box]
.Notice and Wonder
****
Have students take time to think and discuss what they notice and wonder about this file, which contains some new elements they haven't seen before!
****

== Discuss: (10 min)

* *What are some familiar things you notice in this file?* 
+
_Answers vary: `define`, `string=?`, a contract and purpose statement, etc._
* *What new things did you notice in this file?*
+
_Answers vary: the `cond` keyword, the square brackets, `else`, the general look of the `cost` function, etc._
* *What function is being defined here? What is its contract?*
+
_`cost`, takes in a String and produces a Number._
* *How do you think this function works?*
+
_Answers vary - let students drive discussion!_

== Practice: (10 min)

Students turn to @worksheet-link{workbook-pages/PiecewiseFunctions1-WB2.pdf, Alice's Restaurant - Practice} and complete the exercises with their partner.  Students should have added as least one extra option to the menu before moving on.

== Discuss II: (5 min)

* *What happens with the interactive cash register when you enter an item not on the menu?*
+
_The program freezes, or crashes._
* *Why does the cash register stop working when you enter an item not on the menu?*
+
_Let students discuss - move towards the realization that the contract for `cost` is `cost: String -> Number`, and the `else` statement returns a String instead of a Number._
* *The programmer who wrote the code for the cash register had the following comment in his code: `; If the cost function returns a non-positive value, the cash register will display an ERROR message and ask for a different topping` How should we change our `cost` function so that it will fully integrate with the cash register function?*
+
_We should change `else` to return something non-positive, like 0 or -1._


== Apply: (10 min)

Option 1: Students create another function in the Alice's Restaurant code that displays an image of the food instead of the price. This integrates earlier-learned skills in creating images and defining values.

Option 2: Students create an engaging visual representation of how the computer moves through a conditional function.


