= Practice Plotting

++++
<style>
.blankline { margin-bottom: 2.5rem; }
</style>
++++

Fill in the tables, then use CODAP to make the following displays.

@vspace{2ex}

@n A bar chart showing the `species` of animals from the shelter.
[cols="^1,^1,^1",options="header"]
|===
| What Rows?			| Which Column(s)?			| What Display?
|	_animals_			| _species_					| _bar-chart_
|===

@vspace{1ex}

@n A bar chart showing how many animals are fixed or not.
[cols="^1,^1,^1",options="header"]
|===
| What Rows?			| Which Column(s)?			| What Display?
|						| @vspace{2ex}				|
|===

@vspace{1ex}

@n A histogram of the number of `pounds` that animals weigh.
[cols="^1,^1,^1",options="header"]
|===
| What Rows?			| Which Column(s)?			| What Display?
|						| @vspace{2ex}				|
|===

@vspace{1ex}

@n A box-plot of the number of `weeks` that it takes animals to be adopted.
[cols="^1,^1,^1",options="header"]
|===
| What Rows?			| Which Column(s)?			| What Display?
|						| @vspace{2ex}				|
|===

@vspace{1ex}

@n A scatter-plot, using the animals `name` as the labels, `age` as the x-axis, and `pounds` as the y-axis, for all the animals from the shelter.
[cols="^1,^1,^1",options="header"]
|===
| What Rows?			| Which Column(s)?			| What Display?
|						| @vspace{2ex}				|
|===

@vspace{1ex}

@n A scatter-plot, using the animals `species` as the labels, `age` as the x-axis, and `weeks` as the y-axis, for all the animals from the shelter.
[cols="^1,^1,^1",options="header"]
|===
| What Rows?			| Which Column(s)?			| What Display?
|						| @vspace{2ex}				|
|===

@vspace{1ex}

@n (Challenge) A least squares line, using the animals `species` as the labels, `pounds` as the x-axis, and `weeks` as the y-axis, for all the animals from the shelter.
[cols="^1,^1,^1",options="header"]
|===
| What Rows?			| Which Column(s)?			| What Display?
|						| @vspace{2ex}				|
|===
