= Defining Table Functions

@lesson-description{Students continue practicing the Design Recipe, writing helper functions to filter rows and build columns in the animals dataset, using methods.}

[@lesson-intro-table]
|===
@prereqs-stds{ds-methods}
| Lesson Goals
| Students will be able to...

* write custom helper functions to filter the animals table
* write custom helper functions to build on the animals table

| Student-Facing Lesson Goals
| I can...

* filter the animals table however I want
* build columns on the animals table however I want

| Materials
|
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|

| Relevant Standards
|
@worksheet-include{xtra/lang-prereq.adoc}
|===

== Defining Lookup Functions @duration{25 minutes}

=== Overview
Students continue practicing the Design Recipe, by writing functions to answer *Lookup Questions*.

=== Launch

[.lesson-instruction]
Take two minutes to find all the fixed animals by hand. Turn to @worksheet-link{ds-intro/workbook-pages/animal-dataset-2.adoc}, and walk down the table one row at a time, putting a check next to each animal that is fixed.

For each animal, what kind of question were you asking? Was it a *Lookup*, *Compute*, or *Relate* question?

What did you do to complete this activity? You went through the table one row at a time, and for *each row* you did a lookup on the `fixed` column.

[.lesson-instruction]
Have students type the code that will look up if `animalA` is fixed or not, then do the same with `animalB`. Suppose we wanted to do this for every animal in the table? This seems really repetitive, doesn’t it? We would keep typing the same thing over and over, but all that’s really changing is the animal. Wouldn’t it be great if Pyret had a function called `is-fixed`, that would do this for us?

Fortunately, we already know how to define functions using the Design Recipe!

[.lesson-instruction]
Turn to @worksheet-link{workbook-pages/design-recipe.adoc} in your Student Workbook.

[.lesson-point]
Step 1: Contract and Purpose

The first thing we do is write a Contract for this function. You already know a lot about contracts: they tell us the Name, Domain and Range of the function. Our function is named is-fixed, and it consumes a row from the animals table. It looks up the value in the fixed column, which will always be a Boolean. A Purpose Statement is a description of what the function does:

----
# is-fixed :: (animal :: Row) -> Boolean
# Consumes an animal, and lookup the value in the fixed column
----

Since the contract and purpose statement are notes for humans, we add the # symbol at the front of the line to turn it into a comment. Note that we used "lookup" in the purpose statement!

Be sure to check students’ contracts and purpose statements before having them move on.

[.lesson-point]
Step 2: Write Examples

Writing examples for Lookup questions is really simple: all we have to do is look up the correct value in the table, and then write the answer!

----
# is-fixed :: (r :: Row) -> Boolean
# Consumes an animal, and looks up the value in the fixed column
examples:
  is-fixed(animalA) is true
  is-fixed(animalB) is false
end
----

[.lesson-point]
Step 3: Define the Function

When defining the function, we replace the answer with the lookup code.

----
# is-fixed :: (animal :: Row) -> Boolean
# Consumes an animal, and looks up the value in the fixed column
examples:
  is-fixed(animalA) is true
  is-fixed(animalB) is false
end
fun is-fixed(animal): animal["fixed"]
end
----

=== Student-Facing Task Assessment
For practice, try using the Design Recipe to define another lookup function.

[.lesson-instruction]
* Use the Design Recipe to solve the word problem at the bottom of @worksheet-link{workbook-pages/design-recipe.adoc}.
* Type in the Contract, Purpose Statement, Examples and Definition into the Definitions Area.
* Click “Run”, and make sure all your examples pass!
* Type `gender(animalA)` into the Interactions Area.

== Defining Compute Functions @duration{25 minutes}

=== Overview
Students define functions that answer *Compute Questions*, again practicing the Design Recipe.

=== Launch
We've only been writing *Lookup Functions*: they consume a Row, look up one column from that row, and produce the result as-is. And as long as that row contains Boolean values, we can use that function with the `.filter` method.

But what if we want to filter by a Boolean expression? For example, what if we want to find out specifically whether or not an animal is a cat, or whether it’s young? Let’s walk through an example of a Compute Function using the Design Recipe, by turning to @worksheet-link{workbook-pages/design-recipe-2.adoc}.

Suppose we want to define a function called `is-cat`, which consumes a row from the `animals-table` and returns true if the animal is a cat.

* Is this a Lookup, Compute or Relate question?
* What is the name of this function? What are its Domain and Range?
* Is Sasha a cat? _What did you do to get that answer?_

To find out if an animal is a cat, we look-up the species column and check to see if that value is _equal_ to `"cat"`. Suppose `animalA` is a cat and `animalB` is a lizard. What should our examples look like? *Remember: we replace any lookup with the actual value, and check to see if it is equal to `"cat"`.*

----
# is-cat :: (r :: Row) -> Boolean
# Consumes an animal, and compute whether the species is "cat"
examples:
  is-cat(animalA) is "cat" == "cat"
  is-cat(animalB) is "dog" == "cat"
end
----

[.lesson-instruction]
Write two examples for your defined animals. Make sure one is a cat and one isn’t!

As before, we’ll use the pattern from our examples to come up with our definition.

----
# is-cat :: (r :: Row) -> Boolean
# Consumes an animal, and compute whether the species is "cat"
examples:
  is-cat(animalA) is "cat" == "cat"
  is-cat(animalB) is "dog" == "cat"
end
fun is-cat(animal): animal["species"] == "cat"
end
----

Don't forget to include the lookup code in the function definition! We only write the actual value for our examples!

=== Student-Facing Task Assessment
[.lesson-instruction]
* Type this definition -- and its examples! -- into the Definitions Area, then click “Run” and try using it to filter the `animals-table`.
* For practice, try solving the word problem for `is-young` at the bottom of @worksheet-link{workbook-pages/design-recipe-2.adoc}.

=== Collect
Debrief as a class. Ask students to brainstorm some other functions they could write?

== Additional Exercises:

- TODO