= My Dataset

++++
<style>
tbody td { padding: 0 !important; }
</style>
++++

The @fitb{30em}{} dataset contains @fitb{2em}{} data rows.

@n I'm interested in this data because @fitb{}{} +
@fitb{}{}

@n My friends, family or neighbors would be interested because @fitb{}{} +
@fitb{}{}

@n Someone else should care about this data because @fitb{}{} +
@fitb{}{}

@n In the table below, write down what you Notice and Wonder about this dataset.

[.FillVerticalSpace, cols="^4a,^4a,^1a",options="header",stripes="none"]
|===

| What do you Notice?	| What do you Wonder?	| Question
||| _Lookup Arithmetic Statistical +
Can't Answer_
||| _Lookup Arithmetic Statistical +
Can't Answer_
||| _Lookup Arithmetic Statistical +
Can't Answer_
||| _Lookup Arithmetic Statistical +
Can't Answer_
||| _Lookup Arithmetic Statistical +
Can't Answer_
||| _Lookup Arithmetic Statistical +
Can't Answer_
|===

@n Consider each Wonder you wrote above and Circle what type of question it is.

@vspace{1ex}

*Choose two columns to describe below.*

@n @fitbruby{13em}{}{column name}, which contains @fitbruby{10em}{}{categorical/quantitative} data. Example values from this column include:

@fitb{}{}

@n @fitbruby{13em}{}{column name}, which contains @fitbruby{10em}{}{categorical/quantitative} data. Example values from this column include:

@fitb{}{}

