= Functions Can Be Linear

++++
<style>
#content .small-table {max-width: 75%}
#content .graph-table img {width: 30%;}
</style>
++++

@description{Students explore the concept of slope and y-intercept in linear relationships, using function definitions as a third representation (alongside tables and graphs).}

@lesson-prereqs{}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...
@objectives
@objective{slope-from-table}
@objective{slope-from-graph}
@objective{linear-or-not-graph}
@objective{linear-or-not-table}
- match different representations of the same linear relationship

| Student-facing Lesson Goals
|

- Let's learn to tell the difference between linear and nonlinear relationships in tables and graphs.
- Let's connect @vocab{graphs} to @vocab{tables} that describe the same @vocab{linear relationships}.
- Let's compute the @vocab{slope} and @vocab{y-intercept} from a table or graph of a linear relationship.

| Materials
|[.materials-links]

@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links

| Preparation
| 
@preparation{
- There is an optional interactive Desmos activity in the lesson. If you would like to use it, decide how you will share it with students and, if you are using our Google Slides, add the appropriate link to the slide deck. _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions.adoc, _Here's what you need to do._}
}

| Key Points for the Facilitator
|

- Lines are made of points (try to avoid referring to "lines" as much as "collections of points")
- Linear functions can be represented as straight lines on a graph or as sequences that change at a constant rate in a table.
|===

== Linear, Nonlinear, or Bust!

=== Overview
Students explore the concept of _linearity_, as represented in tables and graphs, and then deepen their understanding of linearity, by seeing counterexamples (nonlinear relationships), as well as tables and graphs for which there is _no_ relationship.

=== Launch

@lesson-instruction{
Complete @printable-exercise{notice-wonder-linearity.adoc}
}

*Part 1:*
[cols="^.^1a,^.^1a", grid="none", frame="none"]
|===
|
[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! 0
! 1 ! 2
! 2 ! 4
! 3 ! 6
! 4 ! 8
!===
| @image{images/2x.png}
|===

@QandA{
@Q{In Part 1, what did you *Notice?*}
@A{Answers will vary.}
@A{Each (x, y) pair on the table corresponds to a point on the graph.}
@A{Both the x and y values in the table are increasing by consistent intervals.}
@A{The points on the graph are connected by a straight line.}
@Q{What did you *Wonder?*}
}

@slidebreak

*Part 2:*

[cols="^.^1a,^.^1a", frame="none"]
|===
|
[.pyret-table.first-table,cols="^1,^1",options="header"]
!===
! x ! y
! 1   ! 2
! 2   ! 3
! 3   ! 4
! 4   ! 5
! 5   ! 6
!===
|
[.pyret-table.first-table,cols="^1,^1",options="header"]
!===
! independent ! dependent
! 1 ! 20
! 2 ! 17
! 3 ! 14
! 4 ! 11
! 5 ! 8
!===
|===

@QandA{
@Q{What strategies did you to answer the questions in Part 2?}
@Q{What would the next pair of x-y values be for each of the tables?}
@Q{What would the y-values be when x is 0?}
}

@slidebreak

When we notice that x-values change at a _constant rate_ and the y-values also change at a _constant rate_, we know that there is a @vocab{linear relationship} - plotted on a graph, all of the points will fall on a straight line.

@slidebreak

- @vocab{Tables} only show us _some of the points_ on a line, representing a _sample_ of some larger trend.
- A @vocab{line} is made up of an _infinite_ number of points. _The graph is a way of seeing the trend itself._
- We can follow the pattern to identify additional points with the same relationship.

Even when we describe a linear relationship with a table that only includes integers, the line connecting those points would include points with fractional and decimal values! 

@slidebreak

@lesson-point{
@vocab{Linear Relationships} are sequences where the x and y-values change in proportion with one another, *forming a straight line* that rises or falls at a constant rate, and includes infinite other points satisfying the same rule.
}

@slidebreak

The points in a table are _discrete_.

- Ordering the rows in a table can make it easier for us to find the function.
- But the rows can be shuffled into a different order.

On a graph, the x-axis must always be _ordered_. 

- We can stretch the _scale_ of the axes to making the lines _look_ different.
- But the points will always be in the same order.

@lesson-point{
@vocab{Axes} on a graph need an order. @vocab{Rows} in a table don't!
}


=== Investigate

@lesson-instruction{
Complete the Notice and Wonder on @printable-exercise{graphs-all-linear.adoc}}

@ifnotslide{@teacher{On this page, students will refer to the six graphs below to consider the question: +
*If all linear relationships can be shown as points on a graph, does that mean all graphs are linear?*
}
}

@slidebreak

[cols="^1a,^8a,^1a,^8a,^1a,^8a", stripes="none", frame="none", grid="none"]
|===
| 1) |@image{images/constant-linear.png}
| 2) |@image{images/num-abs.png}
| 3) |@image{images/num-sqrt.png}
| 4) |@image{images/negative-linear.png}
| 5) |@image{images/positive-linear.png}
| 6) |@image{images/num-sqr.png}
|===

@QandA{
@Q{What do you *Notice?*}
@Q{What do you *Wonder?*}
@Q{If all linear relationships can be shown as points on a graph, does that mean all graphs are linear?}
@A{All of the graphs follow patterns, meaning we know where the next point should go. But, only three of the graphs above represent @vocab{linear relationships}.}
@A{As we can see, the linear graphs can go in lots of directions.}
}

@slidebreak

@lesson-point{
On a graph, linear relationships always appear as straight lines.
}

@slidebreak

@lesson-instruction{
Complete the Notice and Wonder on @printable-exercise{tables-all-linear.adoc}.
}

@teacher{@ifnotslide{On this page, students will refer to the six tables below to consider the question: +
*If all linear relationships can be shown as tables, does that mean all tables are linear?*

@vspace{1ex}}
Note: In preparation for future conversations, students are asked to identify the y-value when x=0. +
(This is not yet being described as the y-intercept!) 
}


@slidebreak

[cols="1a,14a,1a,14a", frame="none", grid="none", stripes="none"]
|===

| *A*
|
[.sideways-pyret-table]
!===
! x ! -2 ! -1 !  0 !  1 !  2 ! @ifsoln{*3*}{nbsp}
! y ! -2 ! -3 ! -4 ! -5 ! -6 ! @ifsoln{*-7*}{nbsp}
!===
| *B*
|
[.sideways-pyret-table]
!===
! x !  2  !  4  !  6  !  8  !  10 ! @ifsoln{*12*}{nbsp}
! y ! -12 ! -16 ! -20 ! -24 ! -28 ! @ifsoln{*-32*}{nbsp}
!===

| *C*
|
[.sideways-pyret-table]
!===
! x ! 1 ! 2 ! 3 !  4 !  5 ! @ifsoln{*6*}{nbsp}
! y ! 1 ! 4 ! 9 ! 16 ! 25 ! @ifsoln{*36*}{nbsp}
!===

| *D*
|
[.sideways-pyret-table]
!===
! x ! 5 ! 6 ! 7 ! 8 ! 9 ! @ifsoln{*10*}{nbsp}
! y ! 3 ! 3 ! 3 ! 3 ! 3 ! @ifsoln{*3*}{nbsp}
!===

| *E*
|
[.sideways-pyret-table]
!===
! x !  1 !  2 !   3 !   4 !  5  ! @ifsoln{*6*}{nbsp}
! y ! 84 ! 94 ! 104 ! 114 ! 124 ! @ifsoln{*134*}{nbsp}
!===

| *F*
|
[.sideways-pyret-table]
!===
! x ! -10 ! -9 ! -8 !  -7 ! -6 ! @ifsoln{*-5*}{nbsp}
! y ! @math{\frac{-1}{10}} ! @math{\frac{-1}{9}} ! @math{\frac{-1}{8}} ! @math{\frac{-1}{7}} ! @math{\frac{-1}{6}} ! @ifsoln{*@math{\frac{-1}{5}}*}{nbsp}
!===
|===


@QandA{
@Q{What do you *Notice?*}
@Q{What do you *Wonder?*}
@Q{If all linear relationships can be shown as tables, does that mean all tables are linear? Did you find any tables that could not represent linear relationships?}
@A{Tables C and F are not linear. The other four tables could be linear. +
}
@Q{How did you make your predictions about what the next pair of x-y values would be?}
@A{Answers will vary, but should involve looking for patterns.}
@Q{How did you identify the y-values when x=0 (for the tables that appeared to be linear)?}
@A{Answers will vary, but will most likely involve extending the tables.}

}

@slidebreak

As we saw in the tables, as the x-value increases in linear relationships, the y-values can change in many ways:

- by zero (no change)
- by a positive number (constant increase)
- by a negative number (constant decrease) 

@slidebreak

@lesson-point{
In a table representing a linear relationship, a change in the independent variable corresponds to a @vocab{proportional} change in the dependent variable.
}

@slidebreak

@lesson-instruction{
- Take a look at this table and graph. 
- Can you predict the next row of the table or the next point on the graph?
}

[cols="^.^1a,^.^1a", grid="none", frame="none"]
|===
|

[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! 13
! 1 ! -2
! 1 ! 16
! 3 ! 0
! 4 ! 54
!===

| @image{images/scatterplot.png}
|===

@lesson-point{
Sometimes there is _no function_ that will give us a particular table or graph!
}

@slidebreak

@QandA{
@Q{How do we know whether a graph represents a function?}
@A{It has to pass the vertical line test! There should be exactly one y-value for each x-value.}
@A{*Note*: We discuss this concept in depth in our lesson on @lesson-link{functions-vertical-line-test}.}

}

@lesson-instruction{
Complete @printable-exercise{linear-nonlinear-bust.adoc}.
} 

@slidebreak

Data has a "shape", and this shape can emerge when we look for patterns in that data. A @vocab{linear} function is one kind of pattern, and we can see it whether viewing data as a table or a graph.

=== Synthesize

- How can we recognize a linear relationship in a table?
- How can we recognize a linear relationship on a graph?


== Slope and y-Intercept from Tables

=== Overview
Students refine their understanding of linearity, identifying properties like @vocab{slope} and @vocab{y-intercept} in tables.

=== Launch

Every linear relationship has two properties:

1. The sequence of y-values always changes at a constant rate - called @vocab{slope} - increasing or decreasing by the same amount for each change in the x-value.
2. The y-value when @math{x = 0} is called the @vocab{y-intercept}.

@slidebreak

@lesson-instruction{
- Turn to @printable-exercise{slope-int-tables-intro.adoc}.
- Let's consider the first table on the page together:
[.sideways-pyret-table]
|===
| x | -1 | 0 | 1 | 2 | 3 | 4
| y | -1 | 1 | 3 | 5 | 7 | 9
|===
}

@QandA{
@Q{The @vocab{slope} is how much y increases as x increases by 1. What is the slope?}
@A{We can see that the y-values increase by 2 each time x increases by 1, giving us a @vocab{slope} of 2.}
@A{Some students may need an explicit demonstration of subtracting two adjacent y-values in order to recognize that they are changing by 2.}
@Q{Identify the @vocab{y-intercept} by finding the y-value when @math{x = 0}.}
@A{The @vocab{y-intercept} is 1.}
@Q{What strategies did you use to compute the slope and y-intercept?}
@A{Leave some time for group discussion of strategies!}
}

@slidebreak

@lesson-instruction{Before we move on to finding the slope from more complicated tables, let's get some more practice! + 
Complete @printable-exercise{slope-int-tables-basic.adoc}.}

=== Investigate

Life isn't always so simple!

- What if the table didn't include x = 0?
- What if the x-values didn't increase by 1?
- What if the x-values were _out of order_?
- What if we only had two random coordinate pairs?

@slidebreak

@lesson-instruction{
Consider the second table on @printable-exercise{slope-int-tables-intro.adoc, the page}:
[.sideways-pyret-table]
|===
| x |  3 | 6 | 9  | 12
| y |  4 | 9 | 14 | 19
|===

- Try extending the table and filling in the missing points to find the slope and y-intercept.
- What strategies did you use to extend the table?
}

@teacher{
To find the @vocab{slope} and @vocab{y-intercept} for functions like this one, _without_ having to extend the table we can exploit the fact that all linear functions form _straight lines_, and a straight line can be defined with only _two points!_
}

@lesson-point{
It is always possible to compute @vocab{slope} and @vocab{y-intercept}, as long as we have two coordinate pairs!
}

@slidebreak

@ifslide{
[.sideways-pyret-table]
|===
| x |  3 | 6 | 9  | 12
| y |  4 | 9 | 14 | 19
|===
}

@lesson-instruction{
Take a few minutes to brainstorm about how we might compute the slope using only two points from the table. Would your strategy work if the points weren't adjacent to (next to) each other in the table?
}

@teacher{Leave some time for group discussion... }

@slidebreak

*TO FIND THE SLOPE: Find any two pairs of values in the table, and divide the difference in y's by the difference in x's.*

This lets us see the change in y _as a proportion_ of the change in x, which gives you the @vocab{slope} of the function.

This strategy is often described by the algorithm @math{{{\text{ChangeInY}} \over {\text{ChangeInX}}} or {{\text{Rise}} \over {\text{Run}}}}.

@slidebreak

[.sideways-pyret-table]
|===

| x | *3* | *20* | 5  |  9 | 1
| y | *5* | *56* | 11 | 23 | -1
|===

Taking the first two pairs of (x,y) coordinates in the the last table on @printable-exercise{slope-int-tables-intro.adoc, the page}, gives us:

@indented{@math{ {{56 - 5} \over {20 - 3}} = {51 \over 17} = 3}}

We would get the same answer for this example if we subtracted the (x,y) coordinates in the opposite order...

@indented{@math{ {{5 - 56} \over {3 - 20}} = {-51 \over -17} = 3 }}

But if we mixed subtracted the x-values in a different order than we subtracted the y-values, we'd get the wrong answer!

@indented{@math{ {{56 - 5} \over {3 - 20}} = {51 \over -17} = -3 }}

@slidebreak

@lesson-point{
We can work with the two points in any order, but we need to use the same order for our x's as we use for our y's. 
}

@teacher{While we can find the slope from any two points in a table, there is often an easiest pair to work with. For example, points that are adjacent to each other, points that have whole number values, etc. +
*Encourage students to make conscious choices as they work so that they are working smarter not harder!*
}

@slidebreak

@lesson-instruction{
- Pick two other pairs of values from the third table and compute the @vocab{slope}. Did you get the same answer?
- Are there other strategies we could have used to find the slope?
}

@teacher{
The focus here is on finding the slope from two points. Finding the y-intercept from two points is significantly more involved - we discuss strategies for that in detail in our @lesson-link{function-definition-linear} lesson.
}

@slidebreak

@lesson-instruction{
Let's practice identifying the slope of a linear function when tables aren't organized to make the pattern jump out at us by completing @printable-exercise{slope-tables.adoc}.
}

@vocab{Slope} and @vocab{y-intercept} form the essence of linear functions. If we can find them in a sample of data, we can make predictions that go outside that sample. For example: If we know a car is moving at a consistent speed, all we need to know is _where it is located at two points in time_ in order to figure out the speed, and to predict where it will be at any other point during its trip!

=== Synthesize

@QandA{
@Q{How many points are needed to define a line?}
@A{2}
}

== Slope and y-Intercept from Graphs

=== Overview
Students refine their understanding of linearity, identifying properties like @vocab{slope} and @vocab{y-intercept} from graphs.

=== Launch
On a graph, the y-intercept is the value where the line "intercepts" the y-axis.

[cols="^1,^1"]
|===
|
@centered-image{images/y-intercept-diagonal.png}
|
@centered-image{images/y-intercept-horizontal.png}
|===

@slidebreak

On a graph, the slope refers to both the "steepness" and "direction" of the line.

[cols="^1,^1, ^1"]
|===
| If it goes up as we go from left to right, the slope is *positive*.
| If it goes down as we go from left to right, the slope is *negative*.
| If it stays perfectly horizontal, the slope is *zero*.
| @centered-image{images/positive.png}
| @centered-image{images/negative.png}
| @centered-image{images/horizontal.png}
|===

@slidebreak

We can compute the @vocab{slope} from a graph the same way we would with a table, by picking two points we know the exact coordinates of.

@centered-image{images/slope.png, 600}

=== Investigate
Let's get some practice identifying the slope and y-intercept of a linear function in a graph by completing @printable-exercise{slope-and-y-graphs.adoc}

@strategy{Pedagogy Note}{

Some texts refer to "four ways to draw straight lines on a graph": sloping up and to the right, down and to the left, horizontal, or _vertical_. When thinking only in terms of straight lines on a graph, this is technically correct! However, just because we can draw those lines doesn't make them _functions_, and it doesn't mean they all have a defined slope!

Once students are comfortable computing slope, try having them compute the slope of a vertical line. They will quickly realize that this results in a zero in the denominator, which makes the slope _undefined_! This can be a good review of divide-by-zero and another lens for thinking about the vertical line test.
}

=== Synthesize

We have learned how to find @vocab{slope} and @vocab{y-intercept} from tables and graphs of linear relationships. Looking ahead, we will be learning about yet another representation of Linear Functions that you might find to be even more flexible and powerful.

- Check in with yourself and what we've learned.
  * Which representation do you feel more confident finding the slope from? Why?
  * Which representation do you feel more confident finding the y-intercept from? Why?

@slidebreak

- Linear relationships are _everywhere_...
  * "On average, for each extra gallon I pump into my tank, I can drive an additional 31 miles."
  * "For each additional hour Carlo babysits, he earns 15 more dollars."
  * "Each cockroach the lizard eats decreases the number of cockroaches in the house by one."  
  * "Every 10 additional people in line for the ride at the amusement park increases the wait time by 3 minutes."
  * *What other linear relationships can you think of?*

== What Stories do they tell us?

=== Overview

In this section students will have a chance to describe the stories they see in tables and graphs.

=== Launch

When we are fluent at reading graphs and tables, they tell us a story.
@lesson-instruction{
Turn to @printable-exercise{story-graph.adoc} and consider the first example.
}
@QandA{
@Q{Based on the example, what are the key components we should include when telling the story of a linear relationship?}
@A{The starting point, the variables, and the rate of change.}
}

=== Investigate

@lesson-instruction{
- Write a story for each of the remaining graphs on @printable-exercise{story-graph.adoc}.
- Then apply the same thinking to the tables on @printable-exercise{story-table.adoc}.
}

@opt{Have students work through:

- @opt-printable-exercise{story-graph2.adoc}
- @opt-printable-exercise{story-graph3.adoc}
- @opt-printable-exercise{story-graph-challenge.adoc}
}

=== Synthesize

- Have you thought about graphs and tables as telling stories before?
- Is it easier for you to read the stories from tables or graphs?

== Additional Exercises

- @printable-exercise{pages/match-tables-graphs.adoc}
- @opt-starter-file{linear-functions2}
- @opt-printable-exercise{match-tables-graphs2.adoc} uses tables with shuffled rows
- @opt-printable-exercise{linear-nonlinear-bust-graphs.adoc} 
- @opt-printable-exercise{linear-nonlinear-bust-graphs-2.adoc}

@ifnotslide{
@strategy{Pedagogy Note}{
To encourage students to look at the _points_ in the table and on the graph, it can be useful to change the @vocab{scale} of the graphs to prevent students from leaning on visual cues like "steepness" to bypass the learning objective.

It can also be useful to list the points in the table _out of order_, both to focus students' attention on the points and to drive home that rows do not have to be ordered!
}
}
