= Coordinates & Estimation

@lesson-description{Students review the importance and need for coordinates in the context of a video game and brainstorm a game of their own.}

[@lesson-intro-table]
|===
|Lesson Goals
|Students will be able to:

* Explain the need for @vocab{coordinates} in a given situation.
* Estimate coordinates in a bounded area.

|Student-Facing Lesson Goals
|
* I can estimate the positions of objects using coordinates.
* I can collaborate with a partner to brainstorm a video game.
* I can create a sample mock-up (proof of concept) of my video game.

|Key Points for the Facilitator
|
* The launch activity should create and reinforce the need for coordinates and to attend to precision.
* Continue to use the same "Estimation" handout so students can track their pattern of estimation over time.

|Prerequisites
|
* Students should be familiar with the @vocab{coordinate plane}.

|Materials
|

ifeval::["{proglang}" == "wescheme"]
* Lesson slides template (@link{https://docs.google.com/presentation/d/197qEduqpIWLrJR38mgk5aga-8qcT9apEcIif9sr5RbM/edit#slide=id.g43c588b89e_1_5, Google Slides})
endif::[]
ifeval::["{proglang}" == "pyret"]
* Lesson slides template (@link{https://drive.google.com/open?id=1Z9Y1ZGUarBGk2zrnPBZdHT8BwLfZzv4ZTiw2Yh1ILH0, Google Slides})
endif::[]

* Estimation worksheet (@workbook-link{pages/Estimation.pdf, PDF}, @link{https://docs.google.com/document/d/1WObz4aczEfd7vqxAnfYwp1NT0OZ7cge8hWB2ESc_UUk/copy, Google Doc})
* Game Brainstorming organizer
(@workbook-link{pages/BrainstormGame1.pdf, PDF}, @link{https://docs.google.com/document/d/1gM5eqfI-VVzccr_3-UugZWOvYKYKYd_wrOrFyOKoQ0o/copy, Google Doc})

|===

== Warmup

Students should be logged into
ifeval::["{proglang}" == "wescheme"]
	@link{https://www.wescheme.org, WeScheme }
endif::[]
ifeval::["{proglang}" == "pyret"]
	@link{https://code.pyret.org, code.pyret.org }
endif::[]
and have their workbooks with a pen or pencil.

== Navigating a Grid @duration{20 minutes}

=== Overview
Students are asked to come up with a way of identifying location on a grid, which provides the justification for coordinates.

=== Launch
Let's look at a game of "Hit or Miss." Have students notice and wonder about the Grid image below.

[.notice-box]
.Notice and Wonder
****
What do you notice? What do you wonder?
****

=== Investigate
[.lesson-instruction]
- How would describe where the "hits" are?
- How would you describe where the "misses" are?
- Where would you guess next to get a "hit"?

[.text-center]
Hit or Miss

@centered-image{images/HitOrMiss.png, Hit or Miss, 400, align="center"}

_As students discuss, let them reach the consensus themselves about the need for coordinates!_

=== Synthesize

- What can help us be more precise in playing "Hit or Miss"? _A system for describing exactly where we want to go, like coordinates!_
- How do you think this concept relates to a videogame? _Answers vary: we need to know where characters are on the screen, we need a way for players to interact with certain parts of the screen, etc_

== Bridging to Videogames @duration{20 minutes}

=== Overview
Students explore a coordinate activity in which a cartesian point is used to compute the position of a character in a game. From there, they brainstorm a game of their own.

=== Launch
In pairs, have students explore the @link{https://www.desmos.com/calculator/pbm9nxr2rd, Ninja Cat Desmos graph}.

[.notice-box]
.Notice and Wonder
****
As one partner explores the graph, the other student will write down what they notice.

As one partner explores the graph, the other student will write down what they wonder.
****

=== Investigate

[.lesson-instruction]
 - Students complete the @workbook-link{pages/BrainstormGame1.pdf, "Brainstorm Your Own Game"} worksheet and decide on a Player, Target, Danger, and Background for their game.
 - Students will use a @link{https://docs.google.com/drawings/d/1ET8OazCiswbHrx8wyUAsSkcPRcsKC8xVoOJAc1YFKVE/copy, Google Draw template} (click "Make a copy" when prompted) to create a sample "screenshot" of their game by inserting images via Google Search.

Screenshot should include:

* Labeled estimates of coordinates for each character.
* 2 characters that have the same x-coordinate.
* 2 different characters that have the same y-coordinate.

[.lesson-instruction]
Have students practice their estimation skills with this @workbook-link{pages/Estimation.pdf, Estimation handout} and analyze their absolute error and percentage error along the way.

=== Synthesize

* Why do we estimate? _Practice number sense, get better at working with numbers_
* What constitutes a good estimate?
* How can we improve our estimation skills? _Practice, get more comfortable with numbers and more comfortable with making guesses_

== Additional Exercises:

* @link{https://quizizz.com/admin/quiz/5739e1b55752be78da03a648/coordinates, Coordinates} (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/563d705f36a7843710aba2ce, The Awesome Coordinate Plane Activity} (Desmos Activity)
* @link{https://www.geogebra.org/m/dyaxqKdP, Boat Coordinate Game} (Geogebra)
* @link{https://t.co/2lIf5Yofmj, Coordinate Grid Exploration} (Geogebra)