= Line Length Explore

*Find the `line-length` function in your game files and take a minute to look at the code.*

@n What do you Notice?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n What do you Wonder?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

*Click Run, and practice using `line-length` in the @vocab{Interactions Area} with different values for `a` and `b`.*

@n What does the `line-length` function _do?_

@fitb{}{@ifsoln{Subtracts the smaller input from the bigger one, which computes}}

@fitb{}{@ifsoln{the distance between those points on a number line}}

@fitb{}{}

@fitb{}{}

@n Why does it use conditionals?

@fitb{}{@ifsoln{Sometimes we want to subtract the first input from the second,}}

@fitb{}{@ifsoln{and sometimes we want to subtract the second from the first.}}

@fitb{}{}

@fitb{}{}

@n Why is the distance between two points always positive?

@fitb{}{@ifsoln{The distance between two points is the same, regardless of where one starts}}

@fitb{}{}

@fitb{}{}

@fitb{}{}
