= Choosing My Flag

Complete the prompts below to brainstorm flags you are interested in coding. Then, locate images of each flag to make a decision about which one you'd like to create.

== Brainstorming

@vspace{1ex}

What are some different flags you might want to code and why? Choose three.

@n Flag: @fitb{200px}{} Why? @fitb{}{} +
@fitb{}{}

@n Flag: @fitb{200px}{} Why? @fitb{}{} +
@fitb{}{}

@n Flag: @fitb{200px}{} Why? @fitb{}{} +
@fitb{}{}

== Previewing

@vspace{1ex}

Conduct an internet search to locate images of the flags you listed above, or refer to @opt-printable-exercise{flags-of-the-world-resource.pdf, Flags of the World} and @link{http://www.flagwizard.net/, Flag Wizard}. Respond to the prompts below, providing as much detail as you can. Here are some questions to consider:

- How many shapes would you need to define?
- How many colors does the flag include? What are they?
- What color do you think the background of the flag should be?
- What is the length:width ratio of the flag?

@n The first flag I'm considering is @fitb{200px}{}. Here is how I would describe the flag's appearance: @fitb{}{} +
@fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n The second flag I'm considering is @fitb{200px}{}. Here is how I would describe the flag's appearance: @fitb{}{} +
@fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n The third flag I'm considering is @fitb{200px}{}.Here is how I would describe the flag's appearance: @fitb{}{} +
@fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n After reflecting on the design and appearance of each flag, what flag are you going to create for this project? @fitb{}{}
