= Discover the Commutative Property (2)
++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
  .fitb, .fitbruby, .fitb.stretch::after, .fitbruby.stretch::after {
    padding-top: 0.6em !important;
</style>
++++

@n Evaluate these Circles of Evaluation and consider whether the Commutative Property holds true for problems involving *addition*.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @show{(coe '(+ 20 5))}
| @show{(coe  '(+ 5 20))}
| @math{20 + 5 = } @fitb{5em}{@ifsoln{@math{25}}} 
| @math{5 + 20 = } @fitb{5em}{@ifsoln{@math{25}}}
|===

@n What do you notice? @fitb{}{@ifsoln{Both Circles evaluate to 25. In the first Circle, we add 20 and 5 first, while in the second Circle, we add 5 and 20.}}

@fitb{}{@ifsoln{}}

@fitb{}{}

@n Now look at two more Circles of Evaluation to see how the Commutative Property holds for problems involving *addition of three values*. Can you fill in a third Circle so that the _order_ changes, but not the _groupings_?

[.FillVerticalSpace, cols="^.^3,^.^3,^.^3"]
|===
| @show{(coe '(+ (+ 9 2) 8))}
| @show{(coe  '(+ 8 (+ 9 2)))}
| @show{(coe  '(+ (+ (?ANS 2) (?ANS 9)) 8))}
| @math{(9 + 2) + 8 = } @fitb{5em}{@ifsoln{@math{ 19}}}
| @math{8 + (2 + 9) = } @fitb{5em}{@ifsoln{@math{ 19}}}
| @ifsoln{@math{(2 + 9) + 8 = 19}}
|===

What do you notice? @fitb{}{@ifsoln{Both Circles evaluate to 19. In the first Circle, we add 9 and 2 first, while in the second Circle,}}

@fitb{}{@ifsoln{we have moved the position of 9 + 2, so that 11 is added to 8.}}

@fitb{}{}

@vspace{1ex}

These Circles of Evaluation _all_ represent the Commutative Property of Addition! Notice how, when we used three values, there were multiple ways of reconfiguring the numbers. (_Do you think that is true, also, for the Commutative Property of Multiplication?_)

@n Evaluate the Circles below to decide if the Commutative Property holds for problems involving *subtraction*.

[.FillVerticalSpace, cols="^.^3,^.^3"]
|===
| @show{(coe '(- 50 4))}
| @show{(coe  '(- 4 50))}
| @math{50 - 4 = } @fitb{5em}{@ifsoln{@math{46}}}
| @math{4 - 50 = } @fitb{5em}{@ifsoln{@math{-46}}}
|===

Explain your response. @fitb{}{@ifsoln{No, the Commutative Property does not hold for subtraction. I know because the first Circle evaluates to 46, }}

@fitb{}{@ifsoln{while the second Circle evaluates to a negative value (-46). These Circles are not equivalent after I change the order.}}

@fitb{}{}

@n On a separate page, draw two additional examples -- one pair of Circles that confirms what you observed about the Commutative Property and _addition_, and another pair of Circles that confirms what you observed about the Commutative Property and _subtraction_. Evaluate each Circle to verify your response.
