= Discover the Commutative Property (3)
++++
<style>
  table {grid-template-rows: 3fr 1fr !important;}
</style>
++++

@do{
  (define expr1 '(+ (* 3 2) 5))
  (define expr2 '(+ (* 3 5) 2))
  (define expr3 '(+ 2 (* 5 3)))
  (define expr4 '(+ 5 (* 2 3)))
  (define expr5 '(+ 3 (* 2 5)))
  (define expr6 '(+ 3 (* 5 2)))
  (define expr7 '(+ (* 2 5) 3))
  (define expr8 '(+ (* 5 2) 3))
  (define expr9 '(+ (* 2 3 ) 5))
  (define expr10 '(+ (* 5 3) 2))
  (define expr11 '(+ 2 (* 3 5)))
  (define expr12 '(+ 5 (* 3 2)))
}
Can we change the order for problems involving *multiplication and addition*. 

@n Complete the table below by drawing the Circle of Evaluation for each expression. 

[.FillVerticalSpace, cols="^.^1,^.^1,^.^1,^.^"]
|===
| @show{    (math expr5)} @ifsoln{@math{= 30}}
| @show{    (math expr6)} @ifsoln{@math{= 30}}
| @show{    (math expr7)} @ifsoln{@math{= 30}}
| @show{    (math expr8)} @ifsoln{@math{= 30}}

| @showsoln{ (coe expr5)}
| @showsoln{ (coe expr6)}
| @showsoln{ (coe expr7)}
| @showsoln{ (coe expr8)}

| @show{    (math expr1)} @ifsoln{@math{= 11}}
| @show{    (math expr2)} @ifsoln{@math{= 17}}
| @show{    (math expr3)} @ifsoln{@math{= 17}}
| @show{    (math expr4)} @ifsoln{@math{= 11}}

| @showsoln{ (coe expr1)}
| @showsoln{ (coe expr2)}
| @showsoln{ (coe expr3)}
| @showsoln{ (coe expr4)}

| @show{    (math expr9)}  @ifsoln{@math{= 11}}
| @show{    (math expr12)} @ifsoln{@math{= 17}}
| @show{    (math expr10)} @ifsoln{@math{= 17}}
| @show{    (math expr11)} @ifsoln{@math{= 11}}

| @showsoln{ (coe expr9)}
| @showsoln{ (coe expr12)}
| @showsoln{ (coe expr10)}
| @showsoln{ (coe expr11)}
|===

@n Evaluate each expression. Do they all evaluate to the same thing? @fitb{}{@ifsoln{No. They evaluate to 3 different numbers!}}

@n Are expressions containing both multiplication and addition commutative? Explain your thinking. 

@blanklines{3}{@ifsoln{You have to use the Order of Operations to identify the groupings first! Then you can swap the order of the multiplicands and/or the addends without changing the groupings.}}

