= Discover the Commutative Property (1)
++++
<style>
  .fitb, .fitbruby, .fitb.stretch::after, .fitbruby.stretch::after {
    padding-top: 1em !important;
    }

/* allow more than one circle to exist on the same line */
  .circleevalsexp { width: unset; }

/* when a paragraph tag is followed by a circle, allow them both to exist on the same line */
  div.paragraph>p:has(+.circleevalsexp) { display: inline; }
</style>
++++

*The Commutative Property is true for any operation where _all orders_ of the numbers produce the same result.*

== Does Order matter for Addition? (or "Is Addition Commutative?")

@n Everett thinks that order doesn't matter for addition. They write the following equations as proof: @hspace{1em} @show{(coe '(+ 2 -3))} = -1 @hspace{1em} @show{(coe '(+ -3 2))} = -1

Can you think of any addition problems where order matters? Write at least three more examples in both orders and see if they evaluate to the same thing. _(We've provided the start of one example.)_

@center{@fitb{9em}{16 + 4 =} @fitb{9em}{} @hspace{1em}|@hspace{1em} @fitb{18em}{} @hspace{1em}|@hspace{1em} @fitb{18em}{}}

@n Do you think *addition* is commutative? Explain. @fitb{}{}

@blanklines{1}{}

== Is Multiplication Commutative?

@n Ani thinks that order doesn't matter for multiplication. They write the following equations as proof: @hspace{1em} @big{@math{2 \times -3 = -6} @hspace{1em} @math{-3 \times 2 = -6}}

@vspace{1ex}

Can you think of any multiplication problems where order matters? Write at least three more examples in both orders and see if they evaluate to the same thing. _(We've provided the start of one example.)_

@center{@fitb{9em}{@math{25 \times 4 =}} @fitb{9em}{} @hspace{1em}|@hspace{1em} @fitb{18em}{} @hspace{1em}|@hspace{1em} @fitb{18em}{}}

@n Do you think *multiplication* is commutative? Explain. @fitb{}{}

@blanklines{1}{}

== Is Subtraction Commutative?

@n Olive thinks that order doesn't matter for subtraction. They write the following equations as proof: @hspace{1em} @big{@math{12 - 12 = 0} @hspace{1em} @math{12 - 12 = 0}}

@vspace{1ex}

Can you think of any subtraction problems where order matters? Write at least three more examples in both orders and see if they evaluate to the same thing. _(We've provided the start of one example.)_

@center{@fitb{9em}{10 - 4 =} @fitb{9em}{} @hspace{1em}|@hspace{1em} @fitb{18em}{} @hspace{1em}|@hspace{1em} @fitb{18em}{}}

@n Do you think *subtraction* is commutative? Explain. @fitb{}{}

@blanklines{1}{}

== Is Division Commutative?

@n Jo thinks that order doesn't matter for division. They write the following equations as proof: @hspace{3em} @big{@math{-3 \div -3 = 1} @hspace{1em} @math{-3 \div -3 = 1}}

@vspace{1ex}

Can you think of any division problems where order matters? Write at least three more examples in both orders and see if they evaluate to the same thing. _(We've provided the start of one example.)_

@center{@fitb{9em}{@math{4 \div 1 =}} @fitb{9em}{} @hspace{1em}|@hspace{1em} @fitb{18em}{} @hspace{1em}|@hspace{1em} @fitb{18em}{}}

@n Do you think *division* is commutative? Explain. @fitb{}{}

@blanklines{1}{}

@star Can you identify a pattern for the operations that aren't commutative? What happens when the order of their arguments gets reversed. @fitb{}{}
