= Laws of Arithmetic

Laws of arithmetic can be applied to expressions with numbers and/or variables. By applying laws of arithmetic, we can determine if algebraic expressions are equivalent without assigning values to the variables.

@vspace{1ex}

*The Commutative Property: @hspace{2em} @math{a + b = b + a} @hspace{2em} @math{a \times b = b \times a}* 

For expressions involving only addition or only multiplication, changing the order of the numbers will not change the result. 

- @math{4 + 3} is equivalent to @math{3 + 4} on account of the Commutative Property of Addition. 
- @math{4 \times 3} is equivalent to @math{3 \times 4} on account of the Commutative Property of Multiplication. 
- The Commutative Property does not hold for subtraction or division. 

@vspace{1ex}

*The Associative Property: @hspace{2em}  @math{(a + b) + c = a + (b + c)}* 

For expressions involving only addition or only multiplication, we can regroup to compute in any order, no matter how many numbers are involved.  

- In other words, when adding three numbers we can start with either the first pair or the last pair. 
- For example: We have two options for adding @hspace{1em} @math{98 + 37 + 53} @hspace{1em} &rarr; @hspace{1em} @math{(98 + 37) + 53} @hspace{2em} @math{98 + (37 + 53)} +
@hspace{1em} The mental math ends up being friendler if we start with the last two numbers and then add @math{98 + 90}
- The Associative Property does not hold for subtraction or division.

@vspace{1ex}

*The Additive Inverse Property: @hspace{2em}  @math{a + -a = 0}* 

Adding a number and its opposite always produces zero. For instance, @math{8 + -8 = 0}.

@vspace{1ex}

*The Multiplicative Inverse Property: @hspace{2em}  @math{\frac{a}{b} \times \frac{b}{a} = 1}* 

Multiplying a number and its reciprocal always produces 1. For instance, @math{8 \times \frac{1}{8} = 1}.

@vspace{1ex}

*The Identity Property: @hspace{2em}  @math{a \times 1 = a} @hspace{2em} @math{a + 0 = a}* 

- Multiplying or dividing an expression by 1 does not change its value.
- Adding or subtracting 0 to an expression does not change its value.
- For example: @math{5 + 9 = (5 + 9) \times 1 = (5 + 9) + 0}

@vspace{1ex}

*The Distributive Property: @hspace{2em}  @math{a \times (b + c) = ab + ac}* 

Multiplying the sum of two addends by a number produces the same result as multiplying _each_ addend by that number before finding the sum. Applying the Distributive Property can simplify mental math. Sometimes factored form is simpler and sometimes expanded form is simpler.


[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
| Factored Form 
|
| Expanded Form
| @show{(coe '(* 9 (+ 40 6)))} 
| @math{=}
| @show{(coe '(+ (* 9 40) (* 9 6)))} 
|===


