= Which Circle of Evaluation is Correct? Challenge

++++
<style>
/* Make autonums inside tables look consistent with those outside */
table .autonum::after { content: ')' !important;}
</style>
++++

Claire and Walker each draw a Circle of Evaluation for the following expression: _Add 10 and 2. Multiply the sum by 3. Next, add 1 to the product, then double the result._ Examine their work and then write your analysis, below.

@vspace{1ex}

[cols="^.^4a,^.^4a",options="header",options=stripes="none"]
|===

| Claire: 		| Walker:

| @vspace{1ex}
 @show{(coe '(* (+ (* (+ 10 2) 3) 1) 2))}
@vspace{1ex}

| @vspace{1ex}
 @show{(coe '(* (+ 1 (* 3 (+ 10 2))) 2 ))}
@vspace{1ex}

| @math{(((10 + 2) \times 3) + 1) \times 2}
| @math{(1 + (3 \times (10 + 2))) \times 2}
|===

@vspace{1ex}

@n Is Claire correct? Is Walker correct? Explain. How are their Circles of Evaluation alike? Different? @fitb{}{@ifsoln{Both Circles are correct.}}

@fitb{}{@ifsoln{The innermost Circle for both Claire and Walker is @math{10 + 2}. Walker applies the Commutative property, adding and multiplying}}
@fitb{}{@ifsoln{in an order different than the order stated in the problem. His Circle of Evaluation evaluates to the same result, however.}}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

@n In the space below, draw a _different_ correct translation of the expression printed at the top of the page. (Try to draw a Circle of Evaluation that no one else in your class will draw!)

@vspace{1ex}

@ifsoln{Answers will vary.}





