= Exploring Table Functions
++++
<style>
/* manually tweak page height because for some reason
this page forces a second blank */
body { height: 9.7in !important;}
</style>
++++

@link-instructions{
Open your copy of the @starter-file{table-functions} and click "Run".
}

== Filtering Rows
@n Evaluate @show{(code '(filter shapes-table is-red))} in the Interactions Area. Describe the value you get back below.

@fitb{}{@ifsoln{A table with only the red shapes}}

@n Evaluate @show{(code '(filter shapes-table is-polygon))} in the Interactions Area. Describe the value you get back below.

@fitb{}{@ifsoln{A table without rows for circle or ellipse}}

@n Write the code to generate a table of only triangles. @fitb{}{@showsoln{(code '(filter shapes-table is-triangle))}}

@vspace{1ex}

@indented{
Add your code to the _bottom_ of the Definitions Area. +
Click "Run" and evaluate `triangles` in the Interactions Area to confirm that it does what it's supposed to do before you continue.
}

@n Record the code to define `reds` to be a table of only red shapes. @fitb{}{@showsoln{(code '(define reds (filter shapes-table is-red)))}}

@n What do the contracts for `is-red`, `is-polygon`, and `is-triangle` have in common? @fitb{}{}

@fitb{}{@ifsoln{They all produce Booleans}}

@n *Find the Contract for `filter` on the @dist-link{Contracts.shtml, Contracts Page}.* Explain how `filter` uses the two inputs specified in the Domain. +
@pathway-only{_If you're working with a printed workbook, the contracts pages are included in the back._}

@fitb{}{@ifsoln{`filter` needs a Table, and the name of a function. It makes a new copy of the table, leaving out rows for which the helper function produces false}}

@fitb{}{}

@n What happens if you evaluate @show{(code '(filter shapes-table lookup-name))}? Why? @fitb{}{}

@fitb{}{@ifsoln{Error, because filter needs a function that produces a Boolean.}}

== Building Columns
@n What does @show{(code '(build-column shapes-table "red" is-red))} evaluate to? @fitb{}{}

@fitb{}{@ifsoln{A table with a new column called "red", filled with values from `is-red`}}

@n What does @show{(code '(build-column shapes-table "img" draw-shape))} evaluate to? @fitb{}{}

@fitb{}{@ifsoln{A table with a new column called "img", filled with values from `draw-shape`}}

@n Find the Contract for `build-column` on the @dist-link{Contracts.shtml, Contracts Page}. Explain how `build-column` uses the three inputs in the Domain. +
@pathway-only{_If you're working with a printed workbook, the contracts pages are included in the back._}

@fitb{}{@ifsoln{`build-column` needs a Table, the name of a column to add, and the name of a helper function.}}

@fitb{}{@ifsoln{It makes a new copy of the table, adding the column, and filling it by applying the helper function to each row}}

@fitb{}{}

== Define your own table!
@star In the Definitions Area, define a table of your own using `filter` or `build-column`. Add a comment to describe what's in it!
