= Function Cards

Print and cut these out, for use with the `Filter` activity in this lesson. You can make up your own using the blanks provided at the bottom!

[.FillVerticalSpace, cols="1a,1a", stripes="none"]
|===
|
@show{(contract
"has-glasses" '("Student") "Boolean"
"consumes a student, produces true if they are wearing glasses"
)}

|
@show{(contract
"is-taller" '("Student") "Boolean"
"consumes a student, and produces true if they are taller than you"
)}

|
@show{(contract
"has-long-hair" '("Student") "Boolean"
"consumes a student, and produces true if they have long hair"
)}

|
@show{(contract
"has-red-hair" '("Student") "Boolean"
"consumes a student, and produces true if they have red hair"
)}

|
@show{(contract
"is-shorter" '("Student") "Boolean"
"consumes a student, and produces true if they are shorter than you"
)}

|
@show{(contract
"is-smiling" '("Student") "Boolean"
"consumes a student, and produces true if they are smiling"
)}

|
@show{(contract
"starts-with-vowel" '("Student") "Boolean"
"consumes a student, and produces true if the first letter of their name is a vowel"
)}

|
@show{(contract
"wears-jeans" '("Student") "Boolean"
"consumes a student, and produces true if they are wearing jeans"
)}

| @vspace{17ex}

| @vspace{17ex}

|===
