= Advanced Table Manipulation in a Nutshell

You've seen that Pyret has special functions that we can use to manipulate Tables:

  * `sort` - consumes the name of a column and a Boolean value to determine if that table should be sorted by that column in ascending order
  * `row-n` - consumes an index (starting with zero!) and produces a row from a table
  * `filter` - consumes a _Boolean-producing function_, and produces a table containing only rows for which the function returns `true`
  * `build-column` - consumes the name of a new column, and a function that produces the values in that column for each Row

You've also seen the "Order of Operations" for things like addition, subtraction, multiplication and division.

@vspace{1ex}

*Is there an Order of Operations for manipulating tables?*

@vspace{2ex}

Suppose you want to build a table from the `animals-table` using the `days-to-adopt` function defined below. Consider the two Circles of Evaluation that follow.

@vspace{1ex}

[cols="^1a", stripes="none", frame="none", grid="none"]
|===
|`fun days-to-adopt(r): r["weeks"] * 7 end`
|@show{(coe '(sort (build-column animals-table "days" days-to-adopt) "days" true))}
@vspace{1ex
}
|@show{(coe '(build-column (sort animals-table "days" true) days-to-adopt "days"))}
|===

- One of the Circles of Evaluation will sort the table by the number of days it took for each animal to be adopted.
- One of them will produce an error! Can you figure out which one?

@vspace{1ex}

**We can't `sort` by a column that doesn't exist yet! In fact, we can't `filter` by that column either.**


