= Regression Analysis in the Animals Dataset

@n I performed a linear regression on a sample of @fitbruby{60ex}{_cats from the shelter_}{dataset or subset} and found @fitbruby{80ex}{_a moderate (r=0.566), positive_}{a weak/strong/moderate (R=...), positive/negative} correlation between @fitbruby{60ex}{_age of the cats (in years)_}{[x-axis]} and @fitbruby{60ex}{_number of weeks to adoption_}{[y-axis]}. I would predict that a 1 @fitbruby{20ex}{_year_}{[x-axis units]} increase in @fitbruby{30ex}{_age_}{[x-axis]} is associated with a @fitbruby{30ex}{_0.23 week_}{[slope, y-units]} @fitbruby{30ex}{_increase_}{[increase/decrease]} in @fitbruby{30ex}{_adoption time_}{[y-axis]}.

@vspace{8ex}
@span{.sectionbreak}{}
@vspace{8ex}

@n I performed a linear regression on a sample of @fitbruby{60ex}{}{dataset or subset} and found @fitbruby{80ex}{}{a weak/strong/moderate (R=...), positive/negative} correlation between @fitbruby{60ex}{}{[x-axis]} and @fitbruby{60ex}{}{[y-axis]}. I would predict that a 1 @fitbruby{20ex}{}{[x-axis units]} increase in @fitbruby{20ex}{}{[x-axis]} is associated with a @fitbruby{30ex}{}{[slope, y-units]} @fitbruby{30ex}{}{[increase/decrease]} in @fitbruby{30ex}{}{[y-axis]}.

@vspace{8ex}
@span{.sectionbreak}{}
@vspace{8ex}

@n I performed a linear regression on a sample of @fitbruby{60ex}{}{dataset or subset} and found @fitbruby{80ex}{}{a weak/strong/moderate (R=...), positive/negative} correlation between @fitbruby{60ex}{}{[x-axis]} and @fitbruby{60ex}{}{[y-axis]}. I would predict that a 1 @fitbruby{20ex}{}{[x-axis units]} increase in @fitbruby{20ex}{}{[x-axis]} is associated with a @fitbruby{30ex}{}{[slope, y-units]} @fitbruby{30ex}{}{[increase/decrease]} in @fitbruby{30ex}{}{[y-axis]}.
