= Dirty Data!

A bunch of new animals are coming to shelter, and that means more data! Open the @link{https://docs.google.com/spreadsheets/d/1wLPE6i4P7TMWxpcOnOHGMWBNYopwHf7GpdZMnbgosqA/edit?usp=sharing, New Animals Dataset} and look at the data _carefully_.

[cols="1,1", options="header"]
|===
| What do you Notice? 	| What do you Wonder?
| @vspace{15ex}			|
|===

There are many different ways that data can be dirty!

. *Missing Data* - A column containing some cells with data, but some cells left blank.

. *Inconsistent Types* - A column with inconsistent data types. For example, a `years` column where almost every cell is a Number, but one cell contains the string `"5 years old"`.

. *Inconsistent Units* - A column with consistent data types, but inconsistent units. For example, a `weight` column where some entries are in pounds but others are in kilograms.

@n Which animals have rows with *missing data*, and which column(s) are missing?
@span{.blankline}{}

@n Which animals have rows with *inconsistent types*, and which column(s) are inconsistent?
@span{.blankline}{}

@n Which animals have rows with *inconsistent units*?, and which column(s) are inconsistent?
@span{.blankline}{}

@n If we want to analyze this data, what should we do with the row for Niko?
@span{.blankline}{}
@span{.blankline}{}

@n If we want to analyze this data, what should we do with rows for Mona, Rover, Susie Q, and Happy?
@span{.blankline}{}
@span{.blankline}{}

@n If we want to analyze this data, what should we do with rows for Tanner, Toni, and Lizzy?
@span{.blankline}{}
@span{.blankline}{}

@n If we want to analyze this data, what should we do with rows for Chanel and Hudson?
@span{.blankline}{}
@span{.blankline}{}

@n If we want to analyze this data, what should we do with rows for Porche and Boss?
@span{.blankline}{}
@span{.blankline}{}
