= Translation and Equivalence

== Translation

@vspace{1ex}

Circles of Evaluation help us visualize the structure of mathematical expressions.

- Every Circle of Evaluation must have one -- and only one! -- operator (or function!) written at the top.

- The inputs of the operator are written left to right, in the middle of the Circle.

- Circles of Evaluation can contain other Circles of Evaluation.

@vspace{1ex}

We can translate any arithmetic expression into a Circle of Evaluation or a verbal expression. For example:

@vspace{1ex}


[.embedded, cols="^.^3,^.^1,^.^3,^.^1,^.^3", grid="none", stripes="none", frame="none"]
|===
| @math{5+3} | &rarr; | @show{(coe '(+ 5 3))} | &rarr; | the sum of 5 and 3
|===

@vspace{1ex}

Almost any mathematical expression can be described by many different verbal expressions. It is important to choose our words carefully to make sure they can only be translated and interpreted as the expression we intend them to communicate.

== Equivalence and Computation

@vspace{1ex}

Arithmetic expressions are *equivalent* when they simplify to the same value.  Here is an illustration (with Circles of Evaluation) that can help us visualize simplifying a more complex expression into a single numeric value.

@vspace{1ex}


[.embedded, cols="^.^3,^.^1,^.^3,^.^1,^.^3", grid="none", stripes="none", frame="none"]
|===
| @show{(coe '(+ 3 (- 14 5)))} | &rarr; | @show{(coe '(+ 3 9))} | &rarr; | @math{12}
|===

Computation is one tool (of many!) that can allow us to determine if two expressions are equivalent.
