= Questions and Column Descriptions

What questions can you ask about the animals dataset? Come up with at least one *Lookup*, *Compute*, *Relate* or *Can't Answer* question, and write them as wonders below. (Note: These question types are defined on Page 1.)

[cols="3a,3a,^1a",options="header",stripes="none"]
|===

| What do you NOTICE about this dataset?
| What do you WONDER about this dataset?
| _Question Type_

|
|
|
_Lookup_ +
_Compute_ +
_Relate_ +
_Can't answer_
|
|
|
_Lookup_ +
_Compute_ +
_Relate_ +
_Can't answer_
|
|
|
_Lookup_ +
_Compute_ +
_Relate_ +
_Can't answer_
|
|
|
_Lookup_ +
_Compute_ +
_Relate_ +
_Can't answer_
|
|
|
_Lookup_ +
_Compute_ +
_Relate_ +
_Can't answer_
|
|
|
_Lookup_ +
_Compute_ +
_Relate_ +
_Can't answer_
|
|
|===


[.lh-style]
. This dataset is @fitb{60ex}{Animals that came from an animal shelter}, which contains @fitb{10ex}{31} data rows.

. Some of the columns are:

.. @fitb{30ex}{species}, which contains @fitb{25ex}{categorical} data. Some example values are: @fitb{100ex}{`"cat"`, `"dog"`, and `"rabbit"`}.

.. @fitb{30ex}{}, which contains @fitb{25ex}{} data. Some example values are: @fitb{100ex}{}.
