= Questions and Column Descriptions
++++
<style>
#content tbody tr {height: 5ex;}
</style>
++++

What questions can you ask about the animals dataset? For each question, *can it be answered by this dataset?* Make sure you have at least two questions that can be answered, and at least one that cannot.

[cols="3a,3a,^1a",options="header",stripes="none"]
|===

| What do you NOTICE about this dataset?
| What do you WONDER about this dataset?
| Answered by this dataset?

| @ifsoln{Not every animal has the same number of legs}
| @ifsoln{Why does Lucky only have 3 legs?}
| _Yes_ {nbsp} _No_

|
|
| _Yes_ {nbsp} _No_

|
|
| _Yes_ {nbsp} _No_

|
|
| _Yes_ {nbsp} _No_

|
|
| _Yes_ {nbsp} _No_

|
|
| _Yes_ {nbsp} _No_

|
|
| _Yes_ {nbsp} _No_

|===


[.lh-style]
. This dataset is @fitb{30em}{Animals that came from an animal shelter}, which contains @fitb{10ex}{32} data rows.

. Some of the columns are:

.. @fitb{15em}{species}, which contains @fitb{15em}{categorical} data. Some example values are: @fitb{27em}{"cat", "dog", and "rabbit"}.

.. @fitb{15em}{@ifsoln{age}}, which contains @fitb{15em}{@ifsoln{quantitative}} data. Some example values are: @fitb{27em}{@ifsoln{`1`, `5`, and `10`}}.
