= Making Connections

_Open the @starter-file{row-functions} on your computer, save a copy, and *Click "Run"*!_

@n Find the definition for `cat-row`. What do you get back when you evaluate `cat-row` in the Interactions Area? @fitb{}{@ifsoln{we see the row for Miaulis}}

@n How many weeks did it take for `cat-row` to be adopted? @fitb{6em}{@ifsoln{4}} How many for `young-row`? @fitb{}{@ifsoln{1}}

@n Scroll down in the starter file until you find the Contract, Purpose, Examples and Definition for `weeks-dot`. Discuss with your partner:

- What is the Domain of this function? @fitb{8em}{@ifsoln{Row}} The Range? @fitb{}{@ifsoln{Image}}
- The @vocab{Purpose Statement} is a way of describing the function in detail. Does the Purpose Statement make it clear what this function should do, when given a Row?
- How many examples do you see defined for this function? @fitb{}{@ifsoln{4}}

@vspace{1ex}

@n Look at the first two examples. How do they satisfy the Contract and Purpose Statement?

@fitb{}{@ifsoln{Both examples show the function consuming one argument, and the Domain has one thing in it}}

@fitb{}{@ifsoln{Both examples make a solid circle using the animal's `weeks` to adoption, and the purpose says to do that}}

@vspace{1ex}

These examples show us exactly what should be produced for `cat-row` and `young-row` - the two Rows representing "Sasha" and "Wade", based on their `weeks` to adoption. But these examples only tell us part of the story! Where does the computer get the number of `weeks` from?

@vspace{1ex}

@n Now look at the _last_ two examples. How do they satisfy (connect to) to the first two?

@fitb{}{@ifsoln{The numbers have been replaced by Row lookups}}

@vspace{1ex}

@n Now look at the definition. How is this connected to our examples?

@fitb{}{@ifsoln{The definition follows the pattern of the examples.}}

@vspace{1ex}

@n We've learned that representations of functions have to match.

@vspace{1ex}

Look at the Examples carefully - **there's a mistake**, where the Examples and Definition don't match the Contract and Purpose.

@vspace{1ex}

What's the mistake?

@fitb{}{@ifsoln{The purpose says purple, but all the examples and definition say green.}}

@center{**When you're done, fix the mistake in the code!**}
