= Introduction to Dilations

*Students explore dilations and learn a new function that enables them to create enlargements and reductions of images.*


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Explain 'center' and 'scale factor' as related to dilations
* Demonstrate understanding that dilations change measurements of a figure proportionally

|Student-Facing Lesson Goals
|
* I can describe what a dilation is using words or actions.
* I can determine, given the scale factor, if the dilation will be larger or smaller than the original image.
* I can figure out the dimensions of a shape after a dilation.

|Key Points for the Facilitator
|
* Students should discover independently that a scale factor of <1 creates a smaller image (reduction) and a scale factor of >1 creates a larger image (enlargement).
* Students should connect the scale factor to previous knowledge of percentages.
* The scale function in WeScheme will not allow for negative scale factors.  Negative scale factors are covered in Dilations on the Coordinate Plane.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.

|Materials
|
* https://docs.google.com/presentation/d/12sqh4CFRysry_jxgpVph4FoQzH8bUyZ_TOU9CDJzJpQ/edit?usp=sharing[Google Slides]
|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Math Standards (CCSS)
|
* http://www.corestandards.org/Math/Content/8/G/A/[CCSS.8.G.A], Understand congruence and similarity using physical models, transparencies, or geometry software.

* http://www.corestandards.org/Math/Practice/MP2[CCSS.MATH.PRACTICE.MP2],
Reason abstractly and quantitatively.


|CS Standards (CSTA)
|
* CS Standards here.
|===


== Get Ready:

Students should have their computer, contracts page, and pencil.

== Launch: (10 min)

Which One Doesn't Belong?

@image{images/WODB-cubes.jpg, Which One Doesn't Belong?,400,align="center"}

Give students 20-30 seconds to look at the image and decide which one they think does not belong, then move into groups according to the item they chose.

Give students 1-2 minutes to discuss their choice as a group before moving into group discussion and debate.    

All the figures are cubes that have had some element of their appearance altered, whether it's the position on the table, the angle it's sitting at, its color, or its size.  However, they're all still cubes.

[.strategy-box]
.Strategies for English Language Learners
****
MLR 5 -- Co-Craft Questions and Problems: Give students time to think and discuss with a partner or a small group before large group discussion.  Encourage students to build off each other's responses and move towards mathematical language.
**** 

== Explore: (10 min)

Have students open the Scaling Exploration teachpack and investigate with their partner, using the workbook as a guide. @worksheet-link{workbook-pages/intro-to-dilations-wb1.adoc, Link to Workbook Page}

== Discuss: (10 min)

* What new tools did you discover in this activity? _(bitmap/url, scale, image-width)_
* What do you think the @vocab{contract} for bitmap/url is? _(bitmap/url: String -> Image)_  
* What do the different parts represent? _(The String is a URL (an address on the Internet), and the Image is the picture found at that URL, or address)_
* What is the @vocab{domain} for scale? The @vocab{range}? _(Domain is Number Image, Range is Image)_
* What does the Number appear to mean? _(The scale factor, how much bigger or smaller the new image will be)_
* What do you notice about the scale factor when using the scale @vocab{function}?  _(We can use either decimals or fractions, a scale factor of less than one makes the image smaller and greater than one makes the image larger, negative numbers don't work, etc)_
* Why is being able to change the size of an object useful?  What are some situations where you've needed to use this skill?

== Practice: (10 min)

Students practice identifying scale factors and missing lengths.  The facilitator may choose to have students work together as a class, in partners, or individually.  Some sample problems are included on @worksheet-link{exercises/intro-to-dilations-ex1.adoc}.

== Create/Apply: (5 min)

Students open the "Define Values" teachpack and search for images on the Internet and bring them into WeScheme using bitmap/url, then scale them to create a scene of their choosing.  

_If students will be completing the Game Project, this is a good time for students to find player, target, danger, and background images for their game._

== Some demo text only

Test of vocab items:

@vocab{accessor functions}

@vocab{axis}


