= Graphing Periodic Models: Frequency (𝑏)

++++
<style>
/*
  "Graph" tables provide a pure-CSS solution for all coordinate planes.

  They rely on a set up CSS variables, with reasonable defaults:
    --width and --height determine the size of plane. Defaults to 3in x 3x.
    --min-gap determines the minimum space between graphs. Defaults to 20px.

    --top_pct and --left_pct determine the origin's position (btw 0 and 1). Defaults to (0.5, 0.5).
    --minors determines how many "minor axes" (incl the one behind major). Defaults to 7.

    --x_label defaults to 'x'
    --y_label defaults to 'y'
*/
.graph td {
  --width:    3.2in;
  --height:   3.0in;
  --left_pct: 0.08;
  --top_pct:  0.92;
  --x_label: 'time';
  --y_label: 'altitude';
}

/* "Altitude" is such a long label that we need to 
   override the normal top positioning rule */
table.graph td::before { top: 4% !important; }
</style>
++++

On this page, we'll explore the role of @vocab{frequency} @math{b} in periodic functions. @link-instructions{Open the Desmos File *Exploring Periodic Functions*. You should be on *Slide 1: Modeling the Ferris Wheel Dataset (sine)* and see four sliders for @math{a}, @math{P}, @math{h}, and @math{k}. Adjusting @math{P} also changes @math{b}, which is always @math{2\pi \div P}}

@n Adjust the sliders to fit the data as best you can, then record your model settings: @fitbruby{5em}{@ifsoln{100}}{@math{a}}, @fitbruby{5em}{@ifsoln{30}}{@math{P}}, @fitbruby{5em}{@ifsoln{-22.77}}{@math{h}} and @fitbruby{5em}{@ifsoln{105}}{@math{k}}.


@n Click on one of the @vocab{peaks} (highest-points) on the graph of your periodic function. Desmos will add a gray dot to _all_ of the peaks.

@n Leaving the other sliders where they best fit the data, change *ONLY* the slider for @math{P}. Changing @math{P} also changes @math{b} and this time we are going to focus on the values of @math{b} close to  @math{0.2},  @math{0.1},  @math{0.05},   and   @math{0.025}, graphing each curve below. +
*For each curve, label two adjacent peaks.*

[.FillVerticalSpace.graph, cols="1,1", frame="none"]
|===
| @math{b=0.2}   | @math{b=0.1}
|===
[.FillVerticalSpace.graph, cols="1,1", frame="none"]
|===
| @math{b=0.05}  | @math{b=0.25}
|===

*The distance between two adjacent @vocab{peaks} or @vocab{valleys} is called the @vocab{period}: the interval over which the pattern repeats itself.*

@n What is the @vocab{period}
             when *@math{b=0.2}*?       @fitb{5em}{@ifsoln{@math{10\pi}}}
@hspace{1em} when *@math{b=0.1}*?       @fitb{5em}{@ifsoln{@math{20\pi}}}
@hspace{1em} When *@math{b=0.5}*?       @fitb{5em}{@ifsoln{@math{40\pi}}}
@hspace{1em} @star When *@math{b=0.25}*?   @fitb{}{@ifsoln{@math{80\pi}!}}

@n As the @vocab{frequency} (@math{b}) doubles, the @vocab{period} @fitb{11em}{@ifsoln{gets cut in half}}. @hspace{1em} As the @vocab{frequency} (@math{b}) gets cut in half, the @vocab{period} @fitb{}{@ifsoln{doubles}}
