= Graphing Periodic Models: Frequency (𝑏)

++++
<style>
div#body table td { padding: 0.2em !important; }
</style>
++++


[cols="1a,1a", options = "header", stripes="none"]
|===
^|Period-based model (@math{P})
^|Frequency-based model (@math{b})

^|@math{f(x) = a \sin(\frac{2\pi}{P}(x - h)) + k}
^|@math{f(x) = a \sin(b(x - h)) + k}


|@vocab{Period}: _time to complete one cycle from one @vocab{peak} or @vocab{valley} to another_
|@vocab{Frequency}: _how many completed cycles happen in a length of time_

|
For example:

- It takes the moon about @fitbruby{5em}{_1 month_}{period} to orbit the earth. +
- Teenagers check their phones about every @fitbruby{8em}{_10-22 minutes_}{period}
|
For example:

- The moon orbits the earth about: @fitbruby{8em}{_12x per year_}{frequency}. +
- Teenagers check their phones about: @fitbruby{8em}{_50-100x per day_}{frequency}.
|===

== Period or Frequency?


@link-instructions{Circle whether each of the sentences below describes @vocab{Period} or @vocab{Frequency}}

[cols="4a,1a", frame="none", stripes="none"]
|===
| @n A student's waking and sleeping patterns tend to follow a daily cycle.
| @right{@ifsoln-choice{period} @hspace{2em} frequency}

| @n A microprocessor in a phone runs at 3.4Ghz, meaning it executes 3.4 billion instructions per second.
| @right{period @hspace{2em} @ifsoln-choice{frequency}}

| @n It's good to take your dog for a walk at least twice per day.
| @right{period @hspace{2em} @ifsoln-choice{frequency}}

| @n As they migrate north and south, the crane population in Alaska grows and shrinks on a yearly cycle.
| @right{@ifsoln-choice{period} @hspace{2em} frequency}
|===

== Switching between Period and Frequency

@n _"A Ferris Wheel completes a revolution every 30m."_ Rewrite this sentence in terms of @vocab{frequency}:

@fitb{}{@ifsoln{A Ferris Wheel completes two revolutions per hour}}

@n Do you prefer to think in terms of @vocab{period} of @vocab{frequency}? Why? @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@vspace{1ex}

@link-instructions{Open the Desmos File *Exploring Periodic Functions* to Slide 1: *Modeling the Ferris Wheel Dataset (sine)*. You should see four sliders: @math{k}, @math{h}, @math{P}, and @math{a}. +
Note: adjusting @math{P} also changes @math{b}, which is always @math{2\pi \div P}.}

@n Adjust the sliders to fit the data as best you can and record your model settings: @fitbruby{5em}{@ifsoln{~7.46 or ~-22.77}}{@math{h}} and @fitbruby{5em}{@ifsoln{105}}{@math{k}}, @fitbruby{5em}{@ifsoln{30}}{@math{P}},@fitbruby{5em}{@ifsoln{100}}{@math{a}}.

@n At the bottom of the list of definitions you'll find `g(x)`. Turn it on by clicking the circle in front. What happens? @fitb{}{}

@blanklines{1}{@ifsoln{An orange dotted curve lands directly on top of the red curve that went through the points.}}

@vspace{1ex}

@link-instructions{Click on one of the @vocab{peaks} (highest-points) on the graph of your periodic function. Desmos will add a gray dot to _all_ of the peaks.  Leaving the other sliders where they best fit the data, change *ONLY* the slider for @math{P} to fill in the blanks below.}  

@n What is the @vocab{frequency} (to the nearest thousandth) when the @vocab{period} is: +
@hspace{2em} *@math{P=60}*?   @hspace{1em}   ~ @fitb{10em}{ @ifsoln{0.104}}
@hspace{2em} *@math{P=30}*?   @hspace{1em}   ~ @fitb{10em}{ @ifsoln{0.209}}
@hspace{2em} *@math{P=15}*?   @hspace{1em}   ~ @fitb{}{ @ifsoln{0.418}}

@hspace{2em} As the @vocab{period} (@math{P}) doubles, the @vocab{frequency} @fitb{11em}{@ifsoln{gets cut in half}}. @hspace{1em} As the @vocab{period} (@math{P}) gets cut in half, the @vocab{frequency} @fitb{}{@ifsoln{doubles}}

@n What is the @vocab{period} when the @vocab{frequency} is: +
@hspace{2em} *@math{b &#8776; 6.28}*?   @hspace{1em}   @fitb{10em}{@ifsoln{1}}
@hspace{2em} *@math{b &#8776; 3.14}*?   @hspace{1em}   @fitb{10em}{@ifsoln{2}}
@hspace{2em} *@math{b &#8776; 1.57}*?   @hspace{1em}   @fitb{}{@ifsoln{4}}

@hspace{2em} As the @vocab{frequency} (@math{b}) doubles, the @vocab{period} @fitb{11em}{@ifsoln{gets cut in half}}. @hspace{1em} As the @vocab{frequency} (@math{b}) gets cut in half, the @vocab{period} @fitb{}{@ifsoln{doubles}}