= Graphing Periodic Models: Period (P) and other settings
++++
<style>
/* Maximize the image size, and position the overlays at the top left of the TD */
td { position: relative; }
td img { width: 80%; }
td .overlay { position: absolute; bottom: 90%; left: 75%; font-weight: bold; }
</style>
++++

@center{The standard form of periodic models is @big{@math{f(x) = a \sin(\frac{2\pi}{P}(x - h)) + k}}}

@n Based on what you know of other models, make some predictions...

[cols="2, ^3, ^3", frame="none", stripes="none" options="header"]
|===
|                                        | *Prediction*   | *Result*
| when the value of @math{k} changes:    |                | @ifsoln{where the function crosses the y-axis changes}
| when the value of @math{h} changes:    |                | @ifsoln{where the function crosses the x-axis changes}
|===

@link-instructions{Open the Desmos File *Exploring Periodic Functions* to Slide 1: *Modeling the Ferris Wheel Dataset (sine)*. You should see four sliders: @math{k}, @math{h}, @math{P}, and @math{a}. 

@n Test your predictions above using the @math{h} and @math{k} sliders and record the results. 

@n Then adjust the sliders to fit the data as best you can and record your model settings: @fitbruby{5em}{@ifsoln{~7.46 or ~-22.77}}{@math{h}} and @fitbruby{5em}{@ifsoln{105}}{@math{k}}, @fitbruby{5em}{@ifsoln{30}}{@math{P}},@fitbruby{5em}{@ifsoln{100}}{@math{a}}. +
@indented{_Note: adjusting @math{P} also changes @math{b}, which is always_ @math{2\pi \div P}.}}

@n Click on one of the @vocab{peaks} (highest-points) on the graph of your periodic function. Desmos will add a gray dot to _all_ of the peaks. Label two adjacent peaks on the first graph below and fill in the @math{P = } blank using the @vocab{Period} you just found.

@n Leaving the other sliders where they best fit the data, change *ONLY* the slider for @math{P}. Experimenting with values at  @math{60},  @math{15},  ,  @math{0}, and your own experiment on the scatter plots below. *For each curve, label two adjacent peaks.*

[.FillVerticalSpace, cols="^1,^1", frame="none", stripes="none"]
|===
| @image{../images/points-w-curve.png}  
@span{.overlay}{P = @fitb{3em}{@ifsoln{varies}}}

| @ifnotsoln{@image{../images/points.png}} @ifsoln{@image{../images/p60.png, 80%}}          
@span{.overlay}{P = @fitb{3em}{60}}

| @ifnotsoln{@image{../images/points.png}} @ifsoln{@image{../images/p15.png, 80%}} 
@span{.overlay}{P = @fitb{3em}{15}

| @image{../images/points.png}
@span{.overlay}{P = @fitb{3em}{0}}
|===

@n As @math{P} gets bigger, the height of the wave @fitb{15em}{@ifsoln{stays the same}} and the length of the wave @fitb{}{@ifsoln{increases}} +
@hspace{1em}When @math{P} equals zero, the wave @fitb{}{@ifsoln{disappears}}