= Graphing Periodic Models: Amplitude (𝑎)

@center{The standard form of periodic models is @big{@math{f(x) = a \sin(\frac{2\pi}{P}(x - h)) + k}}}

Let's explore the role of @vocab{amplitude} @math{a} in periodic functions! 

@link-instructions{Open the Desmos File *Exploring Periodic Functions* to Slide 1: *Modeling the Ferris Wheel Dataset (sine)*. You should see four sliders: @math{k}, @math{h}, @math{P}, and @math{a}.}

@n Adjust the sliders to fit the data as best you can and record your model settings: @fitbruby{5em}{@ifsoln{~7.46 or ~-22.77}}{@math{h}} and @fitbruby{5em}{@ifsoln{105}}{@math{k}}, @fitbruby{5em}{@ifsoln{30}}{@math{P}},@fitbruby{5em}{@ifsoln{100}}{@math{a}}.

@n Leaving the other sliders where they best fit the data, change *ONLY* the slider for @math{a}, experiment with values at -50, 0, and 50, graphing each curve below. *For each curve, label the coordinates at time=@math{15}, @math{30}, and @math{45}.*

[.FillVerticalSpace, cols="1,1", frame="none"]
|===
| @image{../images/points.png, 80%}
@hspace{2em}a = -50
| @image{../images/points.png, 80%}          
@hspace{2em}a = 0
| @image{../images/points.png, 80%}
@hspace{2em}a = 50
| @image{../images/points-w-curve.png, 80%}  
@hspace{2em}a = @fitb{3em}{@ifsoln{100}}
|===

@n What does @math{a} tell us about a periodic function? @fitb{}{@ifsoln{How high and low the function will go.}}

@n When @math{a} is zero, the function... @fitb{}{@ifsoln{is a horizontal line}} 

@vspace{1ex}

*The distance between two adjacent @vocab{peaks} or @vocab{valleys} is called the @vocab{period}: the interval over which the pattern repeats itself.*

@n What effect does changing @math{a} have on the @vocab{period} of a periodic function? @fitb{}{@ifsoln{None}}
