= Graphing Periodic Models: Frequency (𝑏)

== Period-based model: @hspace{2em} @math{f(x) = a \sin(\frac{2\pi}{P}(x - h)) + k}

So far we've looked at periodic models written in terms of the @vocab{Period} (@math{P}).

@n How would you describe what a period is? @fitb{}{}

@blanklines{1}{@ifsoln{The distance between two adjacent @vocab{peaks} or @vocab{valleys}. The interval over which the pattern repeats itself.}}

@n @vocab{Periods} are an intuitive way for our brains to think about natural cycles. Complete the sentence stems:

- The cycle of the earth's position repeats every: @fitb{5em}{@ifsoln{year}} as it orbits around the sun 
- The migratory crane population in Alaska grows and shrinks on a cycle that repeats every @fitb{5em}{@ifsoln{year}} as they travel north for summer and south for winter.
- A student's waking and sleeping patterns during the school year tend to follow a cycle that repeats every: @fitb{}{@ifsoln{day? week? (varies by student)}
- The visible portion of the moon changes on a cycle that repeats every @fitb{5em}{@ifsoln{month}}} +
_(from full &rarr; waning gibbous &rarr; quarter &rarr; crescent &rarr; new &rarr; crescent &rarr; quarter &rarr; waxing gibbous &rarr; full)_ 

== Frequency-based model: @hspace{2em} @math{f(x) = a \sin(b(x - h)) + k}

@vspace{1ex}

Periodic models can also be written in terms of their @vocab{frequency} (@math{b}). @hspace{20em} @math{b = \frac{2\pi}{P}} 

@vspace{1ex}

*The @vocab{frequency} is the number of complete cycles (from one @vocab{peak} or @vocab{valley} to another) over a fixed length of time.* +
_For example, 1 Hertz (Hz) equals one cycle per second - the frequency of a healthy human heartbeat._

@vspace{1ex}

@vocab{Frequency}-based models tend to be how engineers think about cyclical behavior. 

@n Where else have you heard the word frequency used before? @fitb{}{}

@blanklines{1}{@ifsoln{radio, wifi, blue tooth, processor speeds, etc. }}

@vspace{1ex}

@link-instructions{Open the Desmos File *Exploring Periodic Functions* to Slide 1: *Modeling the Ferris Wheel Dataset (sine)*. You should see four sliders: @math{k}, @math{h}, @math{P}, and @math{a}. +
Note: adjusting @math{P} also changes @math{b}, which is always @math{2\pi \div P}.}

@n Adjust the sliders to fit the data as best you can and record your model settings: @fitbruby{5em}{@ifsoln{~7.46 or ~-22.77}}{@math{h}} and @fitbruby{5em}{@ifsoln{105}}{@math{k}}, @fitbruby{5em}{@ifsoln{30}}{@math{P}},@fitbruby{5em}{@ifsoln{100}}{@math{a}}.

@n At the bottom of the list of definitions you'll find `g(x)`. Turn it on by clicking the circle in front. What happens? @fitb{}{}

@blanklines{1}{@ifsoln{An orange dotted curve lands directly on top of the red curve that went through the points.}}

@vspace{1ex}

@link-instructions{Click on one of the @vocab{peaks} (highest-points) on the graph of your periodic function. Desmos will add a gray dot to _all_ of the peaks.  Leaving the other sliders where they best fit the data, change *ONLY* the slider for @math{P} to fill in the blanks below.}  

@n What is the @vocab{frequency} (to the nearest thousandth) when the @vocab{period} is: +
@hspace{2em} *@math{P=60}*?   @hspace{1em}   ~ @fitb{10em}{ @ifsoln{0.104}}
@hspace{2em} *@math{P=30}*?   @hspace{1em}   ~ @fitb{10em}{ @ifsoln{0.209}}
@hspace{2em} *@math{P=15}*?   @hspace{1em}   ~ @fitb{}{ @ifsoln{0.418}}

@hspace{2em} As the @vocab{period} (@math{P}) doubles, the @vocab{frequency} @fitb{11em}{@ifsoln{gets cut in half}}. @hspace{1em} As the @vocab{period} (@math{P}) gets cut in half, the @vocab{frequency} @fitb{}{@ifsoln{doubles}}

@vspace{1ex}

@n What is the @vocab{period} when the @vocab{frequency} is: +
@hspace{2em} *@math{b &#8776; 6.28}*?   @hspace{1em}   @fitb{10em}{@ifsoln{1}}
@hspace{2em} *@math{b &#8776; 3.14}*?   @hspace{1em}   @fitb{10em}{@ifsoln{2}}
@hspace{2em} *@math{b &#8776; 1.57}*?   @hspace{1em}   @fitb{}{@ifsoln{4}}

@hspace{2em} As the @vocab{frequency} (@math{b}) doubles, the @vocab{period} @fitb{11em}{@ifsoln{gets cut in half}}. @hspace{1em} As the @vocab{frequency} (@math{b}) gets cut in half, the @vocab{period} @fitb{}{@ifsoln{doubles}}