#lang racket

(provide *textbooks-and-lessons*)

(define *textbooks-and-lessons*
  '(
    ("IM.6.6.16"
     "contracts"
     )
    ("IM.6.6.17"
     "contracts"
     )
    ("IM.6.6.18"
     "contracts"
     )
    ("IM.7.2.4"
     "contracts"
     )
    ("IM.7.2.5"
     "contracts"
     )
    ("IM.7.2.6"
     "contracts"
     )
    ("IM.8.5.1"
     "contracts"
     )
    ("IM.8.5.2"
     "contracts"
     )
    ("IM.Alg1.4.2"
     "making-game-images"
     "defining-values"
     "defining-functions"
     "contracts"
     )
    ("IM.Alg1.4.3"
     "method-chaining"
     "flags"
     "defining-functions"
     "contracts"
     )
    ("IM.8.5.3"
     "defining-table-functions"
     "solving-word-problems"
     "restating-the-problem"
     "defining-functions"
     )
    ("IM.Alg1.4.4"
     "restating-the-problem"
     "defining-functions"
     )
    ("IM.Alg1.4.5"
     "restating-the-problem"
     "defining-functions"
     )
    ("CMP.6.6"
     "defining-values"
     )
    ("IM.6.6.2"
     "defining-values"
     )
    ("IM.7.6.11"
     "defining-values"
     )
    ("IM.6.7.8"
     "inequalities1-simple"
     "simple-data-types"
     )
    ("IM.6.7.9"
     "inequalities1-simple"
     "simple-data-types"
     )
    ("IM.6.7.10"
     "inequalities3-sam"
     "inequalities1-simple"
     "simple-data-types"
     )
    ("IM.7.6.13"
     "simple-data-types"
     )
    ("HSS.CP.B.9"
     "combinatorics-combination"
     "combinatorics-permutation"
     )
    ("IA.5.G.A.1"
     "coordinates"
     )
    ("5.G.A.1"
     "coordinates"
     )
    ("IM.8.1.1"
     "numbers-inside-video games"
     "making-game-images"
     "flags"
     "coordinates"
     )
    ("IM.Alg1.4.1"
     "coordinates"
     )
    ("CMP.8.2"
     "distance-formula"
     )
    ("IM.8.8.6"
     "distance-formula"
     )
    ("IM.8.8.7"
     "distance-formula"
     )
    ("IM.8.8.8"
     "distance-formula"
     )
    ("IM.8.8.10"
     "distance-formula"
     )
    ("IM.Alg1.2.9"
     "distance-formula"
     )
    ("IM.6.1.3"
     "flags"
     )
    ("IM.6.2.5"
     "flags"
     )
    ("IM.6.2.14"
     "flags"
     )
    ("IM.6.7.14"
     "flags"
     )
    ("IM.6.7.15"
     "flags"
     )
    ("IM.7.1.1"
     "making-game-images"
     "flags"
     )
    ("IM.7.1.5"
     "making-game-images"
     "flags"
     )
    ("IM.7.4.1"
     "flags"
     )
    ("IM.8.1.2"
     "making-game-images"
     "flags"
     )
    ("IM.8.1.3"
     "making-game-images"
     "flags"
     )
    ("IM.8.2.1"
     "making-game-images"
     "flags"
     )
    ("IM.6.3.8"
     "functions-for-character-animation"
     )
    ("IM.6.6.6"
     "functions-for-character-animation"
     )
    ("IM.8.3.11"
     "functions-for-character-animation"
     )
    ("IM.Alg1.4.6"
     "functions-for-character-animation"
     )
    ("IM.Alg1.4.10"
     "if-expressions"
     "defining-table-functions"
     "functions-for-character-animation"
     )
    ("IM.8.8.11"
     "inequalities-collision"
     )
    ("IM.Alg1.2.20"
     "inequalities3-sam"
     "inequalities-collision"
     )
    ("IM.Alg1.2.18"
     "inequalities2-compound"
     "inequalities1-simple"
     )
    ("IM.7.6.17"
     "inequalities3-sam"
     )
    ("IM.6.5.5"
     "making-game-images"
     )
    ("IM.6.7.11"
     "numbers-inside-video games"
     )
    ("IM.6.7.12"
     "numbers-inside-video games"
     )
    ("IM.Alg1.1.1"
     "ds-intro"
     "numbers-inside-video games"
     )
    ("CMP.6.1"
     "order-of-operations"
     )
    ("CMP.7.2"
     "order-of-operations"
     )
    ("IM.6.6.13"
     "order-of-operations"
     )
    ("IM.6.6.14"
     "order-of-operations"
     )
    ("IM.6.6.15"
     "order-of-operations"
     )
    ("IM.7.5.13"
     "order-of-operations"
     )
    ("IM.7.5.14"
     "order-of-operations"
     )
    ("IM.8.7.7"
     "order-of-operations"
     )
    ("IM.Alg1.2.6"
     "problem-decomposition"
     "order-of-operations"
     )
    ("CMP.Alg-Ext.2"
     "piecewise-functions"
     )
    ("IM.8.5.10"
     "player-animation"
     "piecewise-functions"
     )
    ("IM.Alg1.4.12"
     "player-animation"
     "piecewise-functions"
     )
    ("IM.6.6.8"
     "problem-decomposition"
     )
    ("IM.Alg1.2.8"
     "problem-decomposition"
     )
    ("IM.7.2.3"
     "solving-word-problems"
     )
    ("IM.Alg1.2.5"
     "solving-word-problems"
     )
    ("CMP.6.4"
     "surface-area-rect-prism"
     )
    ("CMP.7.7"
     "surface-area-rect-prism"
     )
    ("IM.6.1.12"
     "surface-area-rect-prism"
     )
    ("IM.6.1.13"
     "surface-area-rect-prism"
     )
    ("IM.6.1.14"
     "surface-area-rect-prism"
     )
    ("IM.6.1.15"
     "surface-area-rect-prism"
     )
    ("IM.7.7.14"
     "surface-area-rect-prism"
     )
    ("IM.Alg1.2.2"
     "surface-area-rect-prism"
     )
    ("IM.Alg1.2.3"
     "surface-area-rect-prism"
     )
    ("IM.Alg1.1.15"
     "box-plots"
     "checking-your-work"
     )
    ("IM.8.6.9"
     "choosing-your-dataset"
     )
    ("IM.Alg1.1.9"
     "choosing-your-dataset"
     )
    ("IM.Alg1.3.10"
     "choosing-your-dataset"
     )
    ("CMP.8.1"
     "scatter-plots"
     "measures-of-center"
     "linear-regression"
     "linearity2"
     "linearity"
     "correlations"
     )
    ("IM.8.6.4"
     "correlations"
     )
    ("IM.8.6.5"
     "correlations"
     )
    ("IM.Alg1.3.5"
     "correlations"
     )
    ("IM.Alg1.3.7"
     "linear-regression"
     "correlations"
     )
    ("IM.Alg1.3.8"
     "linear-regression"
     "correlations"
     )
    ("IM.6.8.1"
     "ds-intro"
     )
    ("IM.6.8.2"
     "ds-intro"
     )
    ("IM.7.8.11"
     "measures-of-center"
     "grouped-samples"
     )
    ("IM.7.8.18"
     "grouped-samples"
     )
    ("IM.6.8.6"
     "histograms2"
     "histograms"
     )
    ("IM.6.8.7"
     "histograms2"
     "histograms"
     )
    ("IM.6.8.8"
     "histograms2"
     "histograms"
     )
    ("IM.8.6.2"
     "scatter-plots"
     "bar-and-pie-charts"
     "histograms"
     )
    ("IM.Alg1.1.2"
     "bar-and-pie-charts"
     "histograms"
     )
    ("IM.Alg1.1.3"
     "bar-and-pie-charts"
     "histograms"
     )
    ("IM.8.6.1"
     "bar-and-pie-charts"
     "histograms2"
     )
    ("CMP.7.5"
     "linearity2"
     "linearity"
     )
    ("IM.8.6.6"
     "linear-regression"
     )
    ("IM.8.6.7"
     "linear-regression"
     )
    ("IM.8.6.8"
     "linear-regression"
     )
    ("IM.Alg1.3.9"
     "threats-to-validity"
     "linear-regression"
     )
    ("CMP.6.7"
     "box-plots"
     "measures-of-center"
     )
    ("IM.6.8.9"
     "measures-of-center"
     )
    ("IM.6.8.10"
     "measures-of-center"
     )
    ("IM.6.8.13"
     "measures-of-center"
     )
    ("IM.6.8.14"
     "measures-of-center"
     )
    ("IM.7.8.13"
     "measures-of-center"
     )
    ("IM.Alg1.1.5"
     "measures-of-center"
     )
    ("IM.Alg1.1.11"
     "box-plots"
     "measures-of-center"
     )
    ("IM.6.8.15"
     "box-plots"
     )
    ("IM.6.8.16"
     "box-plots"
     )
    ("IM.6.8.17"
     "box-plots"
     )
    ("IM.7.8.15"
     "box-plots"
     )
    ("CMP.7.8"
     "random-samples"
     )
    ("IM.7.8.12"
     "random-samples"
     )
    ("IM.7.8.14"
     "threats-to-validity"
     "random-samples"
     )
    ("IM.7.8.17"
     "threats-to-validity"
     "random-samples"
     )
    ("IM.8.6.3"
     "scatter-plots"
     )
    ("IM.Alg1.3.4"
     "scatter-plots"
     )
    ("IM.Alg1.1.6"
     "simple-data-types"
     )
    ("IM.7.8.19"
     "threats-to-validity"
     )
    ("IM.Alg1.1.4"
     "visualizing-the-shape-of-data"
     )
    ))
