= Threats to Validity Formative Assessment

== Published Assessment

- Desmos File: @link{https://teacher.desmos.com/activitybuilder/custom/66c391955b3af1281567a903?collections=66d8678a5c04bcca1cb0544c, Formative Assessment: Threats to Validity}

== Objectives

- Recognize how selection bias and bias in study design threaten the validity of a study.
- Recognize how extreme outliers in a dataset create the need to thoughtfully select summary data, so as not to misrepresent the data.
- Recognize how extraneous confounding variables can influence the relationship observed between the explanatory and response variables.
- Recognize that valuable information can be hidden to mislead the viewer by intentionally using the wrong chart, changing the scale of the chart, etc.


== Questions and Solutions

@n A study seeks to determine whether kids prefer ice cream, cherry tomatoes, or potato chips in the summer. On the next two slides you will answer questions about this study.

... Which detail (below) suggests Selection Bias in the study? [The children were a variety of ages, from 5 years old to 15 years old; Before the children were surveyed, the researchers asked permission from their parents; Some of the children played soccer; The researchers went to an ice cream shop and interviewed children who were waiting in line.]

... Which detail (below) suggests *Bias in the Study Design*? [*The researchers asked children, "Which would you prefer: (1)  some creamy, delicious ice cream in whatever flavor you like the most; (2) cherry tomatoes or (3) potato chips?"*; The researchers asked children, "What is your age?"; After surveying the children, the researchers thanked them for their time; The researchers surveyed children during June, July, and August.]


@n Which option (below) represents Poor Choice of Summary Data? [A company has 20 employees. It pays $30,000 a year to 18 employees, and $32,000 per year to 2 employees. The company claims that the average salary per person is $30,200; *A company pays $30,000 a year to its 20 employees. The boss earns $500,000 a year. The company claims that average salary per person is $52,381*; A company pays $30,000 a year to its 20 employees. The boss earns $500,000 a year. The company claims that most employees earn a salary of $30,000; A company has 20 employees. They pay 10 employees $25,000 per year. They pay 10 employees $35,000 per year. The company claims that the average salary per person is $30,000 per year.]

@n A study concludes that there is an association between drinking coffee and heart disease. Which of the following is a possible Confounding Variable in the study? [Some people prefer hot coffee and some people prefer iced coffee. Some people's preferences change depending on the season; *Coffee drinkers are more likely to be smokers and cigarettes can lead to heart disease*; There are a variety of types of heart disease, including irregular heartbeat and heart valve disease; Chest pain, shortness of breath, and fainting are all symptoms of heart disease for which one should seek immediate medical attention.]

@n The community of xville is up in arms that the school doesn't represent the diversity of their city. The school board commissioned a survey of how the student body identifies, offering each of the major demographic groups in the community as choices.
The bar chart and pie chart shown below both display results of the same data. If someone were trying to mislead the community into believing that their concern the school does not represent the diversity of the city was unfounded they would use: [*The pie chart*; The bar chart; Neither could be misleading; Both could be misleading.]

== Links to Documents Used for Thinking and Generating Content

- Desmos file?
- Pyret file?
- Google Doc?
- Google Sheet: @link{https://docs.google.com/spreadsheets/d/17zzKtHpomQJ7CI4VcFEnZCersl-iqFRdiY1of-LJxN8/edit?gid=1206766104#gid=1206766104}
