= Histograms Formative Assessment

== Published Assessment

- Desmos File: @link{https://teacher.desmos.com/activitybuilder/custom/66be6b56035a26d01fc17889?collections=66d8678a5c04bcca1cb0544c, Formative Assessment: Histograms}


== Objectives

- Distinguish between bar charts and histograms by understanding the type of data they represent and how useful they are for answering different statistical questions. (Q1)

- Translate a small dataset into a histogram. (Q2)

- Interpret histograms to answer questions about a dataset. (Q3, Q4)

- Determine which histogram bin size will most effectively reveal the shape of the data. (Q5)



== Questions and Solutions

@n Sort the cards into two groups - one for bar charts and one for histograms. Be sure to sort all 9 cards. [Solution: Histogram - uses quantitative data; its bars cannot be reordered; requires us to determine bin width. Bar chart - uses categorical data; its bars can be reordered in any way that we wish.]


@n Clara's Classmates' commute lengths (in minutes) were: 1, 4, 6, 6, 8, 11, 12, 14, 18, 22, 24. Select the histogram below that best models the data. [A, B, *C*, D]


@n A teacher surveys her students on how many hours of TV they watch per week. (See display for results.)

... How many students did the teacher survey? [9, 12, 18, *26*]
... How many students watch 13 hours of TV per week? [*0*, 1, 2, 3, 4]
... How many students watch fewer than 4 hours of TV per week? [4, 9, *13*, 17]
... How many students watch 10 or more hours of TV per week? [1, 2, *3*, 8]

@n The display below represents the distribution of mile run times for a sample of adult women. The next five slides feature True/False questions about this display.

... The number of women in the sample who could run a mile in under 10 minutes is six. [False]
... A total of 13 women were in the sample. [False]
... A total of 40 women were in the sample. [True]
... The fastest time to run a mile was 9 minutes. [False]
... The majority of the women in the sample could run a mile in under 11.5 minutes. [True]


@n Which of the following displays would be most useful? Camille is curious about the distribution in the “pounds” column of the animals dataset and experiments with various bin sizes. [A, B, *C*, D]


== Links to Documents Used for Thinking and Generating Content

- Desmos file?
- Pyret file?
- Google Doc?
- Google Sheet?
