= Graphs 2: Linear, Non-linear, or Bust?

++++
<style>
table {background: transparent; margin: 0px; padding: 5px 20px;}
td, th {padding: 0px !important; text-align: center !important;}
table td p {white-space: pre-wrap; margin: 0px !important;}
table table {padding: 5px 0px;}
img {width: 75%; height: 75%;}
</style>
++++

Decide whether each representation is of a linear function, a non-linear function or is not a function at all!

[cols="^.^1a,^.^15a,^.^1a,^.^15a", frame="none", stripes="none"]
|===
| *@n*
| @image{images/nonlin1.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear
! @ifnotsoln{Non-Linear} @ifsoln{*NON-LINEAR*}
! Not a Function
!===

| *@n*
| @image{images/x.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! @ifnotsoln{Linear} @ifsoln{*LINEAR*}
! Non-Linear
! Not a Function
!===

| *@n*
| @image{images/rot-abs.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear
! Non-Linear
! @ifnotsoln{Not a Function} @ifsoln{*NOT A FUNCTION*}
!===

| *@n*
| @image{images/sqrtx.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear
! @ifnotsoln{Non-Linear} @ifsoln{*NON-LINEAR*}
! Not a Function
!===

| *@n*
| @image{images/horizontal.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! @ifnotsoln{Linear} @ifsoln{*LINEAR*}
! Non-Linear
! Not a Function
!===

| *@n*
| @image{images/sqr(x).png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear
! @ifnotsoln{Non-Linear} @ifsoln{*NON-LINEAR FUNCTION*}
! Not a Function
!===

|===
