= Graphs 2: Linear, Non-linear, or Bust?

++++
<style>
table {background: transparent; margin: 0px; padding: 5px 20px;}
td, th {padding: 0px !important; text-align: center !important;}
table td p {white-space: pre-wrap; margin: 0px !important;}
table table {padding: 5px 0px;}
img {width: 75%; height: 75%;}
</style>
++++

Decide whether each representation is of a linear function, a non-linear function or is not a function at all!

[cols="^.^1a,^.^15a,^.^1a,^.^15a", frame="none", stripes="none"]
|===
|*1*
| @image{images/nonlin1.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear Function	! Non-Linear Function	! Not a Function
!===

|*2*
| @image{images/x.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear Function	! Non-Linear Function 	! Not a Function
!===

|*3*
| @image{images/rot-abs.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear Function	! Non-Linear Function	! Not a Function
!===

|*4*
| @image{images/sqrtx.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear Function	! Non-Linear Function	! Not a Function
!===

|*5*
| @image{images/horizontal.png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear Function	! Non-Linear Function	! Not a Function
!===

|*6*
| @image{images/sqr(x).png}
[cols="1a,1a,1a",stripes="none",frame="none",grid="none"]
!===
! Linear Function	! Non-Linear Function	! Not a Function
!===

|===