= Probability, Inference, and Sample Size

@description{Students explore sampling and probability as a mechanism for detecting patterns. After exploring this in a binary system (flipping a coin), they consider the role of sampling as it applies to relationships in a dataset.}

@ifproglang{pyret}{
@lesson-prereqs{bar-and-pie-charts, ds-intro}
}

@ifproglang{codap}{
@lesson-prereqs{codap-bar-charts}
}

@keywords{probability, sampling, p-value, null hypothesis,}

@add-to-lang{random-rows}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Understand the connection between probability and inference
* Understand the need for random samples
* Understand the role of @vocab{sample size}
* Take random samples from a population

| Student-facing Lesson Goals
|

* Let's explore what random sampling has to do with seeing trends

| Materials
|[.materials-links]

@material-links
|===

== How to Spot a Scam @duration{10 minutes}

=== Overview
Students consider a classic randomness scenario: the probability that a coin will land on heads or tails. From a data science perspective, this can be flipped from a discussion of _probability_ to one of _inference_. Specifically, "how many samples do we need, to determine whether a coin is fair or not?"

=== Launch

@right{@image{images/heads.png, 110}} A stranger on the street invites you to a game of chance. They'll flip a coin, and you'll win money if you can predict whether it lands heads-or-tails. If you guess wrong, however, you pay THEM.

"It's a pure game of chance", they tell you, "we each have equal odds of winning".

[.lesson-instruction]
- What do you think? Can you trust them to play fair?
- For a fair coin, what are the chances of it landing heads? Tails?
** _A fair coin has a 50% chance of landing heads and a 50% chance of landing tails._
- How do you know if a coin is fair or not?
** _Flip it! The more flips you make, the more accurately you can assess if it is fair or not._

=== Investigate
[.lesson-point]
A fair coin should land on "heads" about as often as it lands on "tails".

A fair coin is just as likely to land on one side as it is on the other. A weighted coin, on the other hand, might be heavier on one side, creating a @vocab{bias} toward one side!

In statistics, the @vocab{null hypothesis} represents an assumption that there is no significant difference between two sampled populations. In other words, any difference is due to naturally-occuring variations. In the case of our coin, the null hypothesis would be that there is no significant difference between the likelyhood of coming up heads or tails.

_How do we test the @vocab{null hypothesis}?_

[.lesson-instruction]
Open @starter-file{fair-coins}, and complete @printable-exercise{fair-coins.adoc}

Have students share back their sample results, and their predictions after 5 samples and then 20 samples.

Do any samples seem to undermine the null hypothesis?

In Statistics and Data Science, samples like these don't *prove* anything about the coins! Instead, they either _succeed or fail to produce evidence that rejects the null hypothesis_. The larger the sample, the more evidence we have.

The chances of getting tails from a fair coin three times in a row are pretty good: one-in-8! Maybe it was just the luck of the draw, and the coin is still fair.

But what are the chances of flipping "head" 10 times in a row? 20 times? We might say "There's a one in a million chance of a fair coin coming up heads 20 times. No _way_ is this coin fair!"

But of course, there *is* a way. It's just..._incredibly unlikely_.

[.strategy-box, cols="1a", grid="none", stripes="none"]
|===
|
@span{.title}{Going Deeper: p-value}

Statisticians would use more formal language to describe this highly unlikely, "one in a million chance". They call it the *p-value*, and use a decimal to represent the chance that a pattern is found in a sample, when no such pattern exists in the population.

[options="header"]
!===
! Most people say...					! Statisticians say...
! "There's a 1-in-10 chance of this"	! "The p-value is 0.1"
! "There's a 1-in-100 chance of this"   ! "The p-value is 0.01"
! "There's a 2-in-100 chance of this"   ! "The p-value is 0.02"
! "There's a one-in-a million chance"	! "The p-value is 0.000001"
!===
|===

=== Common Misconceptions
Students may think that _any_ sample from a fair coin should have an equal number of heads and tails outcomes. That's not true at all! A fair coin _might_ land on "tails" three times in a row! The fact that this is possible doesn't mean it's _likely_. Landing on "tails" five times in a row? Still possible, but much less likely.

This is where arithmetic thinking and statistical thinking diverge: it's not a question of what is _possible_, but rather what is _probable_.

=== Synthesize

- Suppose we are rolling a 6-sided die. How could we tell if it's weighted or not?
** _We could record how many times the die landed on each number. If the die is fair, we should see that it lands on each number approximately equally._
- Could a coin come up "heads" twice in a row, and still be a fair coin? Why or why not? What about 10 times in a row? 20?
** _The coin could be fair in all of these intsances! Heads 20 times in a row, however, is extremely unlikely._
- What is the relationship between how weighted a coin is, and how many samples you need to figure it out?
** _A fair coin should land on heads about 50% of the time. If a coin landed on heads _100%_ of the time, it wouldn't take long to figure out that something was up! A trick coin designed to come up heads 60% of the time, however, would need a much larger sample to be detected. The smaller the bias, the larger the sample we need to see it. A small bias might be enough to guarantee that a casino turn a profit, and be virtually undetectable without a massive sample!_

== Probability v. Inference @duration{30 minutes}

=== Overview
Statistical inference involves looking at a sample and trying to _infer something you don’t know_ about a larger population. This requires a sort of backwards reasoning, kind of like making a guess about a _cause_, based on the _effect_ that we see.

=== Launch
In the coin-flip activity, we took samples of each coin and used our intuition about _chance_ and _probability_ to make @vocab{inferences} about whether the coins were fair or weighted.

In other words, we *knew how the coin should behave before we even started sampling* coin-flips, and then checked to see if the samples matched our expectation.

In statistics, we run the process in reverse: we take a sample and then *_infer_ something we didn't know to begin with*.

[.lesson-point]
Inference Reasons Backwards; Probability Reasons Forwards.


@vocab{Statistical inference} is used to gain information in practically every field of study you can imagine: medicine, business, politics, history; even art!

Suppose we want to estimate what percentage of all Americans plan to vote for a certain candidate.  We don't have time to ask every single person who they’re voting for, so pollsters instead take a _sample_ of Americans, and _infer_ how all Americans feel based on the sample.

Just like our coin-flip, we can start out with the null hypothesis: assuming that the vote is split equally. Flipping a coin 10 times isn't enough to infer whether it's weighted, and polling 10 people isn't enough to prove that one candidate is in the lead. _But if we survey enough people_ we can infer something about the whole population.

[.lesson-point]
Sample size matters!

[.lesson-instruction]
* We're taking a survey of religions in our neighborhood. There's a Baptist church right down the street, so we could get a nice big sample by asking everyone there...right?
** _Sampling this population would reveal to us that everyone in the neighborhood is Baptist, which might not be the case!_
* Taking a sample of whoever is nearby is called a _convenience sample_. Why is a convenience sample a problem in this example?
** _Everyone at the church is Baptist, but the entire neighborhood might not be._
* Would it be problematic to only call voters who are registered Democrats? To only call voters under 25? To only call regular churchgoers? Why or why not?
** _Calling only certain segments of the population will not reveal the way an entire population will vote._

[.lesson-point]
Bad samples can be an accident - or malice!

When designing a survey or collecting data, Data Scientists need to make sure they are working hard to get a good, random sample that reflects the population. Lazy surveys can result in some really bad data! _But poor sampling can also happen when someone is trying to hide something, or to oppress or erase a group of people._

* A teacher who wants the class to vote for a trip to the dinosaur museum might only call on the students who they know love dinosaurs, and then say "well, everyone I asked wanted that one!"
* A mayor who wants to claim that they ended homelessness could order census-takers to only talk to people in verified home addresses. Since homeless people don't typically have an address, the census would show no homeless people in the city!
* A city that is worried about childhood depression could survey children to ask about their mood...but only conduct the survey at an amusement park!

Can you think of other examples where biased sampling has been used - or could be used - to harm people?

=== Investigate
The main reason for doing inference is to guess about something that’s _unknown_ for the whole population.

A useful step along the way is to practice with situations where we happen to _know_ what’s true for the whole population. As an exercise, we can keep taking @vocab{random samples} from that population and see how close they tend to get us to the truth.

The Animals Dataset we've been using is just one _sample_ taken from a very large animal shelter.

@ifproglang{pyret}{
How much can we infer about the whole population of hundreds of animals, by looking at just this one sample?

Let’s see what happens if we switch from smaller to larger sample sizes.

Divide the class into groups of 3-5 students.

[.lesson-instruction]
- Open the @starter-file{expanded-animals}, save a copy and click "Run".
- Complete @printable-exercise{pages/sampling-and-inference.adoc}, sharing their results and discussing with the group.
- Optional: complete @opt-printable-exercise{pages/predictions-from-samples.adoc}
}

@ifproglang{codap}{
We're going to analyze which is better at guessing the truth about an entire population - a small sample of 10 randomly selected animals, or a large sample of 40 randomly selected animals.

[.lesson-instruction]
Select `Sampler` from the Plugins dropdown menu.

@center{@image{images/sampler-plugin-default.PNG,250}}

The `Sampler` plugin features a _Mixer_, _Spinner_, and _Collector_. Today, we’ll be using the _Collector_, which chooses a specified number of cases from a dataset.

[.lesson-instruction]
What do you _notice_ about the `Sampler`? What do you _wonder_?

(Possible wonderings include: __How many turquoise balls are there? Why is there that amount? How many brackets are alongside the collection of turquoise balls? Why are there that many?__)

[.lesson-point]
With or without "replacement"?

If we pick cards from a deck, each sample _changes the outcomes_ of the ones that follow. There's only one Ace of Hearts in the deck, and you can't draw it twice! When flipping a coin, each sample has the same number of possible outcomes as the one before: heads or tails. It's as if each one has been _replaced_ with a copy of the same outcome.

That's the difference between sampling with or without replacement. If it's like rolling dice or flipping a coin, it's sampling _with_ replacement. If it's like drawing cards from a deck, it's sampling _without_ replacement.

[.lesson-instruction]
- Can you think of other examples for each?
- Select the `Options` tab of the `Sampler`.
- Which makes the most sense for our dataset: collecting cases _with replacement_ or _without replacement_?

Discuss with the class, making sure everyone understands which one this is!

[.lesson-instruction]
- Designate the number of items to select and the number of samples to collect.
- What would it mean to select three samples of five items each? (These are CODAP's default settings.)
- Enter the correct specifications for 1 collection of 10 items.
-  Click `Start` to observe the sampling simulation.
- When it's complete, the sample will be shown as a new table called itled `experiment/samples/items`. Rename it (by clicking on its title) to `small-sample`.

Ensure that students understand all the components of the new table they’ve created!

Now that students are comfortable using the `Sampler`, it's time to dig into the data.

[.lesson-instruction]
- We want `large-sample` (on the worksheet) to be its own unique table! To produce a new table using `Sampler`, reopen the plugin rather than simply modifying the number of items.
- Complete @printable-exercise{pages/sampling-and-inference.adoc}, sharing their results and discussing with the group.
- Optional: Complete @opt-printable-exercise{pages/predictions-from-samples.adoc}.

}

[.lesson-point]
The most accute samples are random, and large!

=== Common Misconceptions
Many people mistakenly believe that larger populations need to be represented by larger samples. In fact, the formulas that Data Scientists use to assess how good a job the sample does is only based on the _sample size_, not the population size.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Extension}

In a statistics-focused class, or if appropriate for your learning goals, this is a great place to include more rigorous statistics content on @link{https://www.khanacademy.org/math/ap-statistics/estimating-confidence-ap/one-sample-z-interval-proportion/v/determining-sample-size-based-on-confidence-and-margin-of-error, sample size}, @link{https://www.youtube.com/watch?v=SRwMfEmKx3A, sampling bias}, etc.
|===

=== Synthesize

* Were larger samples always better for guessing the truth about the whole population? If so, how much better?
* Why is taking a @vocab{random sample} important for avoiding bias in our analyses?

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Project Options: Food Habits / Time Use}


@opt-project{food-habits-project.adoc, rubric-food-habits.adoc} and @opt-project{time-use-project.adoc, rubric-time-use.adoc} are both projects in which students gather data about their own lives and use what they've learned in the class so far to analyze it. These projects can be used as a mid-term or formative assessment, or as a capstone for a limited implementation of Bootstrap:Data Science. Both projects also require that students break down tasks and follow a timeline - either individually or in groups. Rubrics for assessing the projects are linked in the materials section at the top of the lesson.

@span{.center}{__(Based on the projects of the same name from @link{https://www.introdatascience.org/, IDS at UCLA})__}
|===
