= Identifying Functions from Graphs (2)
++++
<style>
img { max-height: 3in; }
tr:nth-child(3n + 1) td { background: lightgray !important; }
td { background: white !important; }
td .autonum:after { content: ") " !important; }
</style>
++++

Decide whether each graph below is a function. If it's not, prove it by drawing a vertical line that crosses the graph at more than one point.

[cols="^1,^1,^1"]
|===
| @n
*Function* or
@ifsoln-choice{*Not a Function*?}
| @n
*Function* or
@ifsoln-choice{*Not a Function*?}
| @n
@ifsoln-choice{*Function*}
or *Not a Function*?
|@ifnotsoln{@centered-image{../images/nf5.png}} @ifsoln{@centered-image{../images/nf5s.png}}
|@ifnotsoln{@centered-image{../images/nf9.png}} @ifsoln{@centered-image{../images/nf9s.png}}
|@centered-image{../images/f10.png}
3+|

| @n
@ifsoln-choice{*Function*}
or *Not a Function*?
| @n
@ifsoln-choice{*Function*}
or *Not a Function*?
| @n
*Function* or
@ifsoln-choice{*Not a Function*?}
|@centered-image{../images/f7.png}
|@centered-image{../images/f2.png}
|@ifnotsoln{@centered-image{../images/nf6.png}} @ifsoln{@centered-image{../images/nf6s.png}}
3+|

| @n
*Function* or
@ifsoln-choice{*Not a Function*?}
| @n
@ifsoln-choice{*Function*}
or *Not a Function*?
| @n
*Function* or
@ifsoln-choice{*Not a Function*?}
|@ifnotsoln{@centered-image{../images/nf1.png}} @ifsoln{@centered-image{../images/nf1s.png}}
|@centered-image{../images/f5.png}
|@ifnotsoln{@centered-image{../images/nf7.png}} @ifsoln{@centered-image{../images/nf7s.png}}
|===

