== Teacher Resources

- *Online Community (Discourse)* [@link{https://discourse.bootstrapworld.org/, link}] - Talk with other Bootstrap teachers, ask questions, and share out ideas!
- *Collection of Bootstrap:Data Science Desmos Activities* [@link{https://teacher.desmos.com/collection/5fc9250afcaa3f30f4946746, link}] - All of our Desmos Data Science lessons, in one place.
- *Contracts* [@link{solution-pages/contracts.pdf, link}] - A PDF of the contracts pages from the back of the student workbook.


== Other Facilitation Resources
- *Implementation Options* [@link{pages/implementation-options.adoc, link}] - These guide includes suggestions for teachers looking spend a week, a month, or a semester teaching Bootstrap:Data Science.

- *Homework Submission Template* [@link{https://docs.google.com/forms/d/e/1FAIpQLSfj24nCBA18zvjK19OwS_DZfwFZpHoPtPcd-2ADiUDfevkaSA/viewform, google form}] - Efficiently collect hyperlinks to student work.

- *Broadening Participation* [@link{https://docs.google.com/presentation/d/17uEl-yS2smjSuOdDLJPzMWWffeXTqBsENjAaZe_qkso/view, slides}] - This compilation of best-practices from the CS-Education literature offers guidance on broadening student participation.


== Starter Files

- @link{https://docs.google.com/spreadsheets/d/1VeR2_bhpLvnRUZslmCAcSRKfZWs_5RNVujtZgEl6umA/, Animals Dataset}

- @link{https://code.pyret.org/editor#share=1TaT71hwwL5WgR7F_2gHHeS7doyV_ncoZ&v=a3ffc15, Animals Starter File}

- @link{https://code.pyret.org/editor#share=1bGC-RCZhH4mFe-vzrrvQcCj6Y83swJYj&v=a3ffc15, Expanded Animals Starter File}

- @link{https://code.pyret.org/editor#share=1IWPbJK_hsxIGtbUJLz59tLeL_NE1p9FG&v=a3ffc15, Table Methods Starter File}

- @link{https://code.pyret.org/editor#share=1VVz4l0P6GLwbcpYyAGYJuRgBxj69R52Z, Trust-but-Verify Starter File}

- @link{https://code.pyret.org/editor#share=1q_yHgXVUHMeqVfdEuWotGXy4k149ecqZ&v=1904b2c, Box Plots and Histograms Starter File}

== Mini Projects

- @link{../lessons/displaying-categorical-data/pages/infographics.adoc, Making Infographics} & @link{../lessons/displaying-categorical-data/pages/infographic-rubric.adoc, Rubric} - Students develop a ratio statement from a dataset of their choice, and then illustrate it via a compelling infographic.

- @link{../lessons/random-samples/pages/food-habits-project.adoc, Food Habits Project} - Students analyze their snacking habits in comparison with data on childhood obesity in the U.S.

- @link{../lessons/random-samples/pages/time-use-project.adoc, Time Use Project} - Students investigate the amount of time they spend interacting with technology and doing homework as compared with other Americans.

- @link{../lessons/threats-to-validity/pages/threats-to-validity-project.adoc, Threats to Validity Project} - Students pretend to be terrible data scientists who develop and support a claim based on faulty sampling techniques (selection bias, sample size problems, sampling errors, confounding variables).

== Resources that Pair Well with Bootstrap:Data Science

- @link{https://www.nytimes.com/column/whats-going-on-in-this-graph, What's Going on in this Graph?} - weekly intriguing data visualizations by the New York Times

- @link{https://pudding.cool/, The Pudding} - fascinating, data-rich visual essays explaining ideas debated in culture

- @link{https://discourse.bootstrapworld.org/t/something-fun-for-the-classroom-hownotto/1459/9, How Not To} - friendly potshots at terrible Data Science, regularly posted to social media under the hashtag "HowNotTo"

- @link{https://www.autodesk.com/research/publications/same-stats-different-graphs, Same Stats, Different Graphs} - an illustration from Autodesk of why we must see the shape of data and not just focus on the descriptive statistics

- @link{http://guessthecorrelation.com/, Guess the Correlation} - a game-ified resource (built by Omar Wagih) for building intuition for correlation, based on randomly-generated scatterplots

- @link{https://www.geogebra.org/m/ZcVIxKtF, Sensitive r} - an applet from Geogebra that shows how changing a single point can change the correlation coefficient r


== Research Paper Files

Every student (or, ideally, every __pair__ of students) will need to save a copy of the @link{https://docs.google.com/document/d/1_ZEIgM4zvxI7JizViVFZojnpd3Yr2rYe8puPk8pjOcs/copy, Blank Research Paper}. A @link{pages/final-paper-rubric.adoc, Grading Rubric} is also available for the research paper.

@include{../lessons/choosing-your-dataset/fragments/dataset-table.adoc}

Students can also import their data into a @link{https://code.pyret.org/editor#share=12v7kzbxHt2LaSe2uI2d_OnssxtTNF0A8, Blank Starter File}. They will need to modify this file for use with their dataset, and @link{https://www.youtube.com/watch?v=K4n9hTSqcyw, this tutorial video} can walk them through it.

== Exercises and Solutions

@all-exercises
