= Booleans
++++
<style>
#content table .autonum::after { content: ')'; }
</style>
++++
*Boolean-producing expressions are yes-or-no questions and will always evaluate to either `true` (“yes”) or `false` (“no”).*

@vspace{1ex}

What will each of the expressions below evaluate to?

@vspace{1ex}

In order to try out the code, open the @starter-file{boolean}. Click on the column header that corresponds with the question number, choose `Edit formula` from the drop-down menu that appears, type the expression into the box, and click `Apply`. The first one has been done for you in the starter file.

[cols="1,3,.>2,.>2,1,3,.>2,.>2", frame="none", grid="none", stripes="none"]
|===
||								    		| *Prediction:*	| *Computer Returns:*
||                                			| *Prediction:*	| *Computer Returns:*

|@n|  `3 <= 4`    		| @fitb{}{}  | @fitb{}{@ifsoln{true}}
|@n|  `"a" > "b"` 		| @fitb{}{}  | @fitb{}{@ifsoln{false}}

|@n|  `3 = 2`				| @fitb{}{}	| @fitb{}{@ifsoln{false}
|@n|  `"a" < "b"`			| @fitb{}{}	| @fitb{}{@ifsoln{true}}

|@n|  `2 < 4`				| @fitb{}{}	| @fitb{}{@ifsoln{true}}
|@n|  `"a" = "b"`			| @fitb{}{}	| @fitb{}{@ifsoln{false}}

|@n|  `5 >= 5`			| @fitb{}{}	| @fitb{}{@ifsoln{true}}
|@n|  `"a" != "a"`		| @fitb{}{}	| @fitb{}{@ifsoln{false}}

|@n|  `4 >= 6`			| @fitb{}{}	| @fitb{}{@ifsoln{false}}
|@n|  `"a" >= "a"`		| @fitb{}{}	| @fitb{}{@ifsoln{true}}


|@n|  `3 != 3`			| @fitb{}{}	| @fitb{}{@ifsoln{false}}
|@n|  `"a" != "b"`		| @fitb{}{}	| @fitb{}{@ifsoln{true}}
|===

@vspace{1ex}

@n In your own words, describe what `<` does.
@fitb{}{@ifsoln{checks whether the first number is smaller than the second number, returns true if it is and false if it isn't}}

@vspace{1ex}

@n In your own words, describe what `>=` does.
@fitb{}{@ifsoln{checks whether the first number is greater than or equal to the second number, returns true if it is and false if it isn't}}

@vspace{1ex}

@n In your own words, describe what `!=` does.
@fitb{}{@ifsoln{checks whether the to numbers are unequal, returns true if they're unequal and false if they're equal}}

@vspace{1ex}

[cols="5, .>2, .>2", frame="none", grid="none", stripes="none"]
|===
|															 | *Prediction:*	| *Computer Returns:*

|@n `includes("cat", "catnap")`  | @fitb{}{}		| @fitb{}{@ifsoln{true}}
|@n `includes("catnap", "cat")`	 | @fitb{}{}		| @fitb{}{@ifsoln{false}}
|===

@vspace{1ex}

@n There are infinite numbers values out there (...-2,-1,0,-1,2... ) and infinite string values ("a", "aa", "aaa"...) But how many different _Boolean_ values are there?

@fitb{}{@ifsoln{2}}
