= CODAP Exploration

Make sure you’re logged into the @starter-file{animals} in CODAP. The purpose of this exploration is to familiarize yourself with some of CODAP's features. Feel free to experiment and try things out!

@n See if you can make a graph. What did you select in order to do so?

@fitb{}{@ifsoln{I clicked on the "Graph" icon in the upper left-hand corner of my screen}}

@fitb{}{}

@vspace{2ex}

@n Move the table. Move the graph. How do you move things in CODAP?

@fitb{}{@ifsoln{To move tables and graphs, I mouse over the top-most bar until my cursor turns into a hand. Then I can drag.}}

@fitb{}{}

@vspace{2ex}

@n Minimize and maximize the table and the graph. How do you do that?

@fitb{}{@ifsoln{ To minimize, I select the `-` in the upper right-hand corner of the graph or table. To maximize, I reselect the `-`.}}

@fitb{}{}

@vspace{2ex}

@n Drag an attribute (like `weight`, `name`, or `sex`) to a graph's axis - or use the drop-down menu that appears when you click on an axis. What happens?

@fitb{}{@ifsoln{ _The randomly positioned points move to the confirguration that matches the data on the animals table._}}

@fitb{}{}

@vspace{2ex}

@n Drag a second attribute (like `weight`, `name`, or `sex`) to the graph's other axis - or use the drop-down menu that appears when you click on an axis. What happens?

@fitb{}{@ifsoln{ The points move again, to the confirguration indicated by the two attributes on the animals table.}}

@fitb{}{}

@vspace{2ex}

@n Select the grey plus sign (+) in the upper right-hand corner of the Animals Table. Doing so will enable you to create a new attribute. Name your new attribute `test`.  Is the column populated or empty?

@fitb{}{@ifsoln{The column is empty.}}

@fitb{}{}

