= Strings and Numbers
++++
<style>
  #content { display: block !important; }
</style>
++++

- For each of three sections below, refer to the corresponding table in the @starter-file{strings-n-numbers}.
- Start with Table A. One by one, working from left to right, follow the directives at the top of each column. *_In order to follow the directives, you must first click the column name, and then choose "Edit Formula" from the drop-down menu that appears._* You will be typing into the "Edit Formula" box. (See images below.)

@vspace{1ex}

@left{@image{../images/drop-down.png, 450}} @right{@image{../images/type-your-name.png, 250}}

@vspace{1ex}


== Table A: Strings

_String values are always in quotes._

@n Click on `1. Type your name`. Type your name in the formula box and select `Apply.` What error message appears in this column? @fitb{}{}

@n Click on `2. Type your name in quotes`. Type your name with quotes in the formula box and select `Apply`. Why didn't you get an error this time?

@fitb{}{@ifsoln{I typed my name in quotation marks, so the computer recognized it as a string.}}

@n Click on `3....` Type your name with the opening quote, but _without the closing quote_, and select `Apply`. What do you think a "syntax error" is? 

@fitb{}{@ifsoln{A syntax error is an error where the computer cannot make sense of the code, e.g. missing commas, missing parentheses, unclosed strings.}}

@vspace{1ex}

== Table B: Numbers

For each of the columns in Table B, click on the header, type the specified expression into the formula box, and click `Apply`.

@n Type `42` (no quotes). Type a fraction. Type a decimal. Type an integer. Does anything surprise you about how numbers behave in CODAP?

@fitb{}{}

@star Click on any of the attribute names and select "Edit Attribute Properties" from the drop-down menu that appears. What happens when you change the _type_?

@fitb{}{}

@star How about when you change the _precision_?

@fitb{}{}

@vspace{1ex}

== Table C: Operators

__Just like math, CODAP has @vocab{operators} like `+`, `-`, `*` and `/`. It uses `^` for exponents (e.g. 2^3 is "2 to the 3rd power").__

@vspace{1ex}

For each of the columns in Table C, click on the header, type the specified expression into the Formula Box and then select `Apply`. 

@n What do you notice? Does CODAP know the order of operations? @fitb{}{@ifsoln{Yes, CODAP automatically applies the order of operations.}}

@fitb{}{}


