= Food Habits

@description{Students analyze their snacking habits in comparison with data on childhood obesity in the U.S.}

== The Issue

Childhood obesity is a major problem in the U.S. Many have called for food producers to provide consumers with nutritional information so that consumers can make wiser choices.  We’re going to explore some questions about snacking, which will help us to better understand the issue of childhood obesity.

== Objectives

Upon completing this project, you will understand how interpreting graphs can provide us with useful information. You will compare yourself to the U.S. population to find out how your snacking habits are similar in some ways and different in other ways.

== Phases of the Project

=== 1. Data Collection
There are two phases of data collection.

- Create a copy of @link{https://docs.google.com/forms/d/1PklP5FhpsWlUrQU6UaV0OKYxzq_Pz5YheLoiGs3yTeM/copy, this Google form} to record your snacking habits. You will complete the form every time you have a snack over a designated five-day period.
- Find graphs related to eating habits by conducting an onlin search using terms like, "What do Americans eat for snacks?"

=== 2. Asking a Meaningful Statistical Question
Once you have all of your data and have looked at several graphics online about America’s snacking habits, you will declare your statistical question for this project. Some suggestions are below, but feel free to develop your own based on your analysis of the data.

- What time of day do we eat the healthiest snacks?
- We know that snacks high in saturated fats are bad for you. Do high-fat snacks get unhealthy ratings? In general, how good would you say you are, as a class, at judging healthiness?
- When did you snack? How does this compare to the rest of the class?
- Typically, how healthy were your snacks? How does this compare to the class as a whole?
- Do snacks with high salt content also seem to have high fat? Is high fat associated with high calories? Are there any other associations you can spot?

=== 3. Sharing Results
You will create a slideshow sharing your results. Your presentation must include:

- A clear summary of your snacking habits, represented by plots, tables, photos, and paragraphs.

- A clear summary of America's snacking habits, represented by plots, tables, photos, and paragraphs.

- A strong statistical question based on the data that you collect.

- A clear explanation of your answer to that question, based on the data.

- A discussion of some of the challenges of this project, for instance: What made it hard to collect data? Did this affect the quality of data? What sort of snacks are you more likely to not enter?

(Based on Joy Straub's adaptation of the Food Habits project from @link{https://www.introdatascience.org/, IDS at UCLA})
