= Sampling and Inference

++++
<style>
.blankline {margin-top: 15px; margin-bottom: 10px; }
</style>
++++

@vspace{1ex}

@n Evaluate the `big-animals-table` in the Interactions Area. This is the _complete_ population of animals from the shelter! Below is a true statement about that population:

[.lesson-point]
The population is 47.7% fixed and 52.3% unfixed.

*Type each of the following lines into the Interactions Area and hit “Enter".*
----
random-rows(big-animals-table, 10)
random-rows(big-animals-table, 40)
----
@n What do you get?
@span{.blankline}

@n What is the contract for `random-rows`?
@span{.blankline}


@n What does the `random-rows` function do?

@span{.blankline}

@span{.blankline}

@n In the Definitions Area, define `small-sample` and `large-sample` to be these two random samples.

@vspace{2ex}

@n Make a `pie-chart` for the animals in each sample, showing percentages of fixed and unfixed.

- The percentage of fixed animals in the entire populations is @fitb{20ex}{*47.7%*}.
- The percentage of fixed animals in `large-sample` is @fitb{20ex}{}.
- The percentage of fixed animals in `large-sample` is @fitb{20ex}{}.

@vspace{2ex}

@n Make a `pie-chart` for the animals in each sample, showing percentages for each species.

- The percentage of tarantulas in the entire population is @fitb{20ex}{*roughly 5%*}.
- The percentage of tarantulas in `small-sample` is @fitb{20ex}{}.
- The percentage of tarantulas in `large-sample` is @fitb{20ex}{}.

@vspace{2ex}
 
@n Click "Run" to direct the computer to generate a different set of random samples of these sizes. Make a new `pie-chart` for each sample, showing percentages for each species.

- The percentage of tarantulas in the entire population is @fitb{20ex}{*roughly 5%*}.
- The percentage of tarantulas in `small-sample` is @fitb{20ex}{}.
- The percentage of tarantulas in `large-sample` is @fitb{20ex}{}.

@vspace{2ex}

@n Which repeated sample gave us a more accurate inference about the whole population? Why?

@span{.blankline}

@span{.blankline}
