= Image Scatterplots

@lesson-description{Image-scatter-plots expose deeper insight into subgroups within a population, motivating the need for more advanced analysis and adding if-expressions to students' programming toolkit.}

[@lesson-intro-table]
|===
@prereqs-stds{defining-functions}
| Lesson Goals
| Students will be able to...

* use if-then-else expressions in Pyret to make custom image scatterplots
* explain the behavior of a (specific) higher order function

| Student-facing Lesson Goals
|

* Let's explore functions that behave differently based on the input.

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/15xQX5hB78uUyXUTr-T36koBLgPADtoqECrZEEUZ1SzM/, Lesson Slides}
* @link{https://code.pyret.org/editor#share=1DeSbekzW7SMh4fnIN1_aVGYZu5EtRvRZ, Custom Animal Images Starter File}
* @link{https://code.pyret.org/editor#share=1ZupMVPWvVUOM0HCWyA7cRBghSLKxPWv1, Animals Starter File}


@material-links

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with
* All students should log into @link{https://code.pyret.org, CPO} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can @link{https://code.pyret.org/editor#share=1ZupMVPWvVUOM0HCWyA7cRBghSLKxPWv1, open a new one}

@lang-prereq
|===

== Intro to Image-Scatterplots @duration{15 minutes}

=== Overview

Students are introduced to their first `image-scatterplot`, which makes use of row lookups and `text` to label each dot with the name of the species. They then write code for a new `image-scatterplot`.

=== Launch

Have students turn to @printable-exercise{scatterplot-explore.adoc} and give them a few minutes to complete the questions using the @link{https://code.pyret.org/editor#share=1Yskwvzbe5CSMX3F1fveEOgrL3ms2cxHV&v=1904b2c, Image Scatterplot Starter File}.

[.lesson-instruction]
* What did you notice?
* What did you wonder?
* Why does `scatter-plot` take in 3 Strings, when there are only two axes?
* The contract for `image-scatter-plot` looks pretty different from other contracts we've seen.

[.indentedpara]
--
`image-scatter-plot {two-colons} (t {two-colons} Table, xs {two-colons} String, ys {two-colons} String, f {two-colons} (Row -> Image)) -> Image`
--

[.lesson-instruction]
* What is the Domain of `image-scatter-plot`?

_table, string, string and... what is that last part?... a function that consumes a Row and produces an Image!_

[.lesson-point]
In order to use the `image-scatter-plot` function, we have to first define a helper function that will lookup a Row and describe how to use the information it looked up to generate an Image.

=== Investigate

[.lesson-intstruction]
Before we move one, let's turn off the `scatterplot` in the program by putting a `#` at the start of line Have students complete @printable-exercise{image-scatterplot-explore.adoc}. In the process they will be asked to try to explain how the `image-scatter-plot` is generated and to write a new `Row -> Image` helper function in order to generate a second `image-scatter-plot`.

=== Synthesize

[.lesson-instruction]
* What Dataype is `species-tag`?
* What does `species-tag` do?
* How does this `image-scatter-plot` use `speciestag`?
* How did having the dots labeled with the species change your understanding of the data?

Make sure to direct the conversation _back to Data Science!_
__This scatterplot makes it clear that we may want to analyze each species separately, rather than grouping them all together!
__ In the next lesson, students will learn how to do just that.  What other scatter plots might this be useful for?

[.lesson-instruction]
* What was the first step for generating an `image-scatter-plot` with the animals' names?

== Image-Scatterplots with Piecewise Functions @duration{20 minutes}

=== Overview
Students discover how to use piecewise functions to change dot colors and sizes, how "dot appearance" can be used to show more data in a scatterplot, and why that would be valuable.

=== Launch
[.lesson-instruction]
* So far, we've seen `image-scatter-plot` label each point with a text image. What other ideas do you have for how to improve upon the blue dots generated by the `scatter-plot` function?

_Students might suggest using other colors, using letters, using numbers, using coordinates, using different shapes, using different sizes, etc._

[.lesson-instruction]
* Take a moment and make a prediction. How do you think the age of an animal impacts how long it takes to be adopted?
* Which of these scatterplots best matches your prediction?

Have students open the @link{https://code.pyret.org/editor#share=1SOLAau653CYFY05x45NustZ0-ejKGQF0&v=1904b2c, Image Scatterplots with Piecewise Functions Starter File} and turn to @printable-exercise{pages/species-color.adoc} to record their thinking about the file.

@span{.center}{@image{images/age-v-weeks-clustered.gif, "Age v. Weeks Scatterplot", 400}}

[.lesson-instruction]
* What do you Notice?
* What do you Wonder?
* How is this program similar to the last one we looked at?
* How is this code different from the program that made the `image-scatter-plot` with species labels?
* What does this new visualization tell us about the relationship between age and weeks?
* What other analysis would be helpful here?

=== Investigate

Have students turn to @printable-exercise{weight-dr.adoc}


Make sure they all write the Contract and Purpose Statement __first__ , and check in with their partner __and__ the teacher before proceeding.

Once they've got the Contract and Purpose Statement, have them come up with `examples:` for _each weight range_. Once again, have them check with a partner _and_ the teacher before finishing the page.

[.lesson-instruction]
Once another student _and_ the teacher has checked their work, have them type this function into their animals starter files, and use it to make an `image-scatter-plot` using `age` as the x-axis and `weeks` as the y-axis.

=== Synthesize



== Scatterplots with Custom Images

. Show students @link{https://code.pyret.org/editor#share=1DeSbekzW7SMh4fnIN1_aVGYZu5EtRvRZ, this code}, which uses `image-url` and `scale` to generate icons of animals.
. What do they Notice? What do they Wonder? How might this scatterplot change our analysis?
. How does using clip art help us to better understand the data?
. What risks might there be to using clip art in displays?
. We have seen a lot of different kinds of `image-scatter-plot` styles today. Brainstorm possible applications for `image-scatter-plot` in analyizing your dataset.

@opt-online-exercise{https://code.pyret.org/editor#share=1OUuVCsm320LzZtwsrS4TLTt_Gp7tQD2A&v=1904b2c, Image Scatterplots with Value Ranges}
////
(For now, the scatter plot is _purely_ to give students practice with contracts and displays. They are *not* expected to know much about scatter plots at this point.)
@schanzer - Do you still see this as true?
////

