= Exploring Data: Skulls from Maya Human Sacrifice

@description{In this lesson students will use quantitative and categorical data about human sacrifice as an entry point for learning about Maya society, but will recognize that learning about one practice of the Maya is not enough information to make a broader conclusion about who the Maya were as a people and what led to their downfall.}

@lesson-prereqs{}

@keywords{}

@add-to-lang{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* explore important details about Maya human sacrifice victims by examining data from skulls.
* define and understand variable types by examining two ways to record data about skulls from Maya human sacrifice

| Student-facing Lesson Goals
|


| Materials
|[.materials-links]

@material-links

| Preparation
|
* You'll need a measuring tape to demonstrate how to measure the circumference of a skull.
* _Optional: Bring a stuffed animal or doll as a prop whose head you can measure_
* Decide how you will engage students with the @link{https://docs.google.com/document/d/1cTlp4jNwc_2VYCWZ9Ckzf7Mg-GAQ8OE0VAtjDJqSCcQ/edit?usp=sharing, skull evidence}.
// Once we decide on whether or not we are going to cite sources for the skull images, convert the skull evidence to asciidoc. 8 to a page will probably work fine.
** Will they view it on a computer?
** Will you print a packet of the skull data for each pair of students to work with?
** Will you print and cut a pair of evidence cards for each pair of students to work with?

| Supplemental Resources
| @link{https://delval.edu/blog/hun-hunahpu-mayan-maize-god, The story of Hun Hunahpu} as told by Bridget Cornog ’24, a student at Delaware Valley University

|===

== Review: What do we already know about the Maya?

[.lesson-instruction]
Complete the @printable-exercise{do-now.adoc}

Yesterday, we looked at background information, written accounts from Landa and de Las Casas, a recent article about artifacts found in caves, and some of the images found in the cave!

[.lesson-instruction]
* Did you learn anything more about the Maya through discussions with family and friends?
* Do you have any new theories about:
** who the Maya sacrificed
** why their civilization collapsed
** how researchers can learn about what Maya society was like in the past

== What Can We Learn from Skulls? @duration{10 minutes}

=== Overview

=== Launch

There are some illustrations of human sacrifice in the codices, but not enough context for researchers to figure out exactly who was sacrificed, and for what purpose. This is why modern scientists seek to find answers in the bones of victims---but where can they find these bones?

[.lesson-point]
Besides books and written sources, historians and scientists can discover clues about ancient civilizations by digging up bones!

Some of the bones from human sacrifices have gradually been discovered by archaeologists, but many have remained hidden. Not long ago, Mexican researchers carefully studied documents of testimony by Maya natives who were tortured and interrogated hundreds of years ago by the Spanish priest de Landa. Based on clues from these centuries-old testimonies, the researchers made some educated guesses about locations of the Maya sacrifices. They set out with experienced scuba divers to some underwater caves in Mexico’s Yucatán peninsula.  Their quest led to an elaborate system of underground chambers, full of temples, murals, artifacts, and skeletons of human remains.

[.lesson-instruction]
--
One measurement archaelogists collect is the circumference of each skull they find.

* How could we measure the circumference of a skull? What tools would we need?
--

*Demonstrate how to measure the circumference of a skull using a tape measure.*

* The point of the demonstration is that when students are looking at the measurements of skulls in their dataset, they will know what the number is referring to.
* You might use a stuffed animal, a student, or perhaps you can measure the circumference of your own head?

[.lesson-point]
This brings us back to one of the unsolved puzzles of the Maya culture: Who got sacrificed in Maya rituals? Were they males or females? Were they old or young?

[.lesson-instruction]
* Why do you think it might be useful to know whether a skull is small or large?
** _It might tell us something about the age of the person._
* With your partner, brainstorm what other information might be useful to collect about the skulls archaeologists find.
* Complete the first 3 columns of the table at the top of @printable-exercise{skull-exam.adoc}.

Guide students through a discussion of the @vocab{variable} vocabulary words on the page, asking them to explain why `Age` is quantitative and `Sex` is categorical.

[.lesson-instruction]
Now that you know the difference between @vocab{quantitative} and @vocab{categorical} variables, work with your partner to complete the table in number 2 and then go back to the top of the page to complete the variable type column of the first table.

=== Investigate

[.lesson-instruction]
--
You and your partner have received a set of images and measurements of 20 skulls found scattered about a cave.

- Make a copy of this @online-exercise{https://docs.google.com/spreadsheets/d/1Kw0m4K2jMQAvAE0gb2f93_7HB52KgnxjluuCmVpamOE/edit?usp=sharing, Skull Data table}.
- Then follow the directions about how to collect and sort your data using google sheets on @printable-exercise{skull-explore.adoc}.
- When you're done, complete @printable-exercise{think-like-ds.adoc}
--

=== Synthesize
What conclusion(s) can you draw about the Maya based on the skull data you analyzed today? Support your claim with evidence.

Complete the @printable-exercise{homework.adoc} before our next class.
