= Exploring Data: Skulls from Human Sacrifice

@description{In this lesson students will use quantitative and categorical data about human sacrifice as an entry point for learning about ancient Maya society, but will recognize that learning about one practice of the ancient Maya is not enough information to make a broader conclusion about who they were as a people and what led to their downfall.}

@lesson-prereqs{maya-history}

@keywords{}

@add-to-lang{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* explore important details about the people sacrificed by the ancient Maya by examining data from skulls.
* define and understand variable types by examining two ways to record data about skulls from Maya human sacrifice
* read data tables to extract information contained in them
* identify a variable and be able to classify it as either quantitative or categorical
* understand that data values of variables can be collected with a sample
* enter data into Google Sheets
* sort data in Google Sheets

| Student-facing Lesson Goals
|

* Let's collect data from human skulls uncovered in archaeological digs!
* I can explain the difference between quantitative and categorical variables and use that understanding to identify whether real world variables are quantitative or categorical.
* I can enter and sort data in Google Sheets.

| Materials
|[.materials-links]

@material-links

| Preparation
|
* You'll need a soft (vinyl) measuring tape to demonstrate how to measure the circumference of a skull.
* _Optional: Bring a stuffed animal or doll as a prop whose head you can measure._
* Decide how you will engage students with the skull evidence.
// Once we decide on whether or not we are going to cite sources for the skull images, convert the skull evidence to asciidoc. 8 to a page will probably work fine.
** Will they view the 20 skulls on a computer?
** Will you print a packet of the skull data for each pair of students to work with?
** Will you print and cut a pair of evidence cards for each pair of students to work with?

| Supplemental Resources
| @link{https://delval.edu/blog/hun-hunahpu-mayan-maize-god, The story of Hun Hunahpu} as told by Bridget Cornog ’24, a Maya student of small animal science at Delaware Valley University

|===

== Review: What do we already know about the Maya? @duration{5-10 minutes}

[.lesson-instruction]
Complete the @printable-exercise{do-now.adoc}

Yesterday, we looked at background information, written accounts from de Landa and de Las Casas, a recent article about artifacts found in caves, and some of the images found in the cave!

[.lesson-instruction]
* Did you learn anything more about the ancient Maya through discussions with family and friends?
* Do you have any new theories about...
** who the ancient Maya sacrificed?
** why their civilization collapsed?
** how researchers can learn about what ancient Maya society was like?

== What Can We Learn from Skulls? @duration{40 minutes}

=== Overview
Students consider what kinds of data can be collected from skulls and learn to identify whether their variables are categorical or quantitative. Later they will learn to input and sort data in google sheets and use that data to make inferences about who the Maya sacrificed.

=== Launch

There are some illustrations of human sacrifice in the codices, but not enough context for researchers to figure out exactly who was sacrificed, and for what purpose. This is why modern scientists seek to find answers in the bones of victims---but where can they find these bones?

[.lesson-point]
Besides books and written sources, historians and scientists can discover clues about ancient civilizations by digging up bones!

Some of the bones from human sacrifices have gradually been discovered by archaeologists, but many have remained hidden. Not long ago, Mexican researchers carefully studied documents of testimony by Maya natives who were tortured and interrogated hundreds of years ago by the Spanish priest de Landa. Based on clues from these centuries-old testimonies, the researchers made some educated guesses about locations of the Maya sacrifices. They set out with experienced scuba divers to some underwater caves in Mexico’s Yucatán peninsula.  Their quest led to an elaborate system of underground chambers, full of temples, murals, artifacts, and skeletons of human remains.

[.lesson-instruction]
--
One measurement archaeologists collect is the circumference of each skull they find.

* How could we measure the circumference of a skull? What tools would we need?
* _Optional: How big would you guess the circumference of @fitb{5em}{} head is?_
--

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Demonstration: Measuring Skull Circumference}

The point of the demonstration is to make sure that all of your students understand what the numbers they'll be looking at in their datasets today actually describe. _Students will not need to do any measuring themselves today in order to complete the assignments, but, since most students could use more practice measuring - and are curious about themselves - we encourage you to give them the opportunity to find out the circumference of their own heads, by working with a partner or individually._
|
Wrap a tape measure from the front of the forehead, around the back of the head, back to the front until the tape measure touches its end.
|
Report (to the nearest quarter inch) how big the circumference of the head is.
|
You might measure a stuffed animal or your own head.
|===

[.lesson-instruction]
* Why do you think it might be useful to know whether a skull is small or large?
** _It might tell us something about the age of the person._
* With your partner, brainstorm what other information might be useful to collect about the skulls archaeologists find.
* Complete the first 3 columns of the table at the top of @printable-exercise{skull-exam.adoc}.

Guide students through a discussion of the @vocab{variable} vocabulary words on the page, asking them to explain why `Age` is quantitative and `Sex` is categorical.

[.lesson-instruction]
Now that you know the difference between @vocab{quantitative} and @vocab{categorical} variables, work with your partner to complete the table in number 2 and then go back to the top of the page to complete the variable type column of the first table.

=== Investigate

[.lesson-point]
One of the unsolved puzzles of the Maya culture: Who got sacrificed in Maya rituals? Were they males or females? Were they old or young?

[.lesson-instruction]
--
You and your partner have received a set of 20 skull images from an archaeological dig, along with their measurements (@handout{skull-evidence1.adoc}, @handout{skull-evidence2.adoc}, @handout{skull-evidence3.adoc}, @handout{skull-evidence4.adoc}, @handout{skull-evidence5.adoc})

- Make a copy of this @online-exercise{https://docs.google.com/spreadsheets/d/1Kw0m4K2jMQAvAE0gb2f93_7HB52KgnxjluuCmVpamOE/edit?usp=sharing, Skull Data table}.
- Then follow the directions about how to collect and sort your data using google sheets on @printable-exercise{skull-explore.adoc}.
- When you're done, complete @printable-exercise{think-like-ds.adoc}
--

=== Synthesize

* What conclusion(s) can you draw about the Maya based on the skull data you analyzed today? Support your claim with evidence.
* In today's @opt-printable-exercise{journal.adoc}, students are asked:
** What did we learn about the ancient Maya from the skull examination?
** Has your thinking changed at all about why the ancient Maya declined?
** What evidence did we examine?
** What data science skills did we learn?

@vspace{1ex}

_Optional Discussion to Preview Data Science ideas:_

_Imagine that you’ve found Maya necklaces, some made of jade and others made of jaguar teeth. The necklaces have different numbers of beads. In other words, the necklaces vary._

_In this case, there are two variables of interest: type of bead and how many beads._

* _Which variable is categorical? How do you know?_
** _Type of bead is categorical because it's not numerical._

_Type of bead is categorical, summarized by reporting fractions or proportions: for instance, maybe 4/10 of the necklaces are jade and 6/10 are made of jaguar teeth._

* _How could we express those fractions as decimals?_
** _4/10 = 0.4 and 6/10 = 0.6_

_Number of beads is quantitative, summarized by reporting the average: for instance, maybe the average number of beads on the necklaces is 35._

* _What does the average number of beads being 35 tell us about the necklaces?_
** _They could all be 35 beads long, but more likely some have fewer beads and some have more beads. We don't have enough information to know what the minimum or maximum number of beads on the necklaces is._

== Homework

* @printable-exercise{homework.adoc}




