= Functions Make Life Easier!

@description{Students discover that they can make their own functions.}

@lesson-prereqs{contracts-strings-images}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:
@objectives{
@objective{functions-what-changes}
@objective{functions-define}

| Student-Facing Lesson Goals
|

Let's learn how functions get defined!}
Let's use patterns to write some functions.

| Materials
|[.materials-links]


@material-links

| Key Points for the Facilitator
|
- This lesson represents a _big_ shift in thinking.  After some practice, students will not be limited to pre-existing functions!
|===

== There's Got to Be a Better Way!

=== Overview
@ifpathway{algebra, ok}{
Students have already searched for structure in a list of expressions in order to define values.
}
In this lesson, students will build their flexibility of thinking by engaging with multiple representations. Students will search for structures that are _dynamic_, meaning they change in a predictable way. This is the foundation for defining functions.

=== Launch
@slidestyle{Launch}

@teacher{
This is a fun lesson to make silly! Dramatically confess to your students, "I LOVE green triangles!"}

@lesson-instruction{In the Definitions Area write the code to make as many unique, solid, green triangles as you can in the next 2 minutes.}

@centered-image{images/i-love-green-triangles.jpg,  400}

@centered-image{images/green-triangle.jpg,  400}

@teacher{
Walk around the room and give positive feedback on the green triangles. When the time is up, ask for some examples of green triangles that they wrote and copy them to the board.
}

@slidebreak{Launch}

@indented{For example:}

@indented{@show{(code '(triangle  30  "solid" "green"))}}

@indented{@show{(code '(triangle  12  "solid" "green"))}}

@indented{@show{(code '(triangle 500  "solid" "green"))}}

@teacher{
Invite students to analyze the examples you recorded by posing the following questions:
}

@QandA{
@Q{Is there a pattern?}
@A{Yes, the code mostly stayed the same with one change each time.}
@Q{What stayed the same?}
@A{The function name `triangle`, "solid", "green".}
@Q{What changed?}
@A{The size of the `triangle`, or the Number input.}
@Q{How many of you typed out the code from scratch each time?}
@Q{How many triangles were you able to code in a minute?}
@A{Write this down so that you can compare to it later!}
}

=== Investigate
@slidestyle{Investigate}

@proglang allows us to define @vocab{values}. This lets us create "shortcuts" to reuse the same code over and over.

For example:
@show{(code '(define gt (triangle 65 "solid" "green")))} allows us to make the same solid, green triangle anywhere we want, just by writing `gt` - without having to write all of the code again and again. But... it makes the same green triangle _every_ time.

@lesson-point{
To make a shortcut that _changes_ such as creating solid, green triangles of a changing size, we need to define a @vocab{function}.
}

@slidebreak{Investigate}

Suppose we want to define a function called `gt`. When we give it a number, it makes a solid green triangle of whatever size we give it. 

@QandA{
@Q{What will @show{(code '(gt 5))} produce?}
@A{@show{(code '(triangle 5 "solid" "green"))}!}
}

@slidebreak{Investigate-RP}

@teacher{Select a student to _act out_ `gt`.}

@lesson-roleplay{Our volunteer's Name is "gt". They expect a Number, and they will produce an Image.

Just as with any acting career, this one will begin with a rehearsal. 

When I say, "*gt 5!*", you say, "*triangle 5 solid green!*"

Let's try it.
}

@teacher{
- Teacher: *gt 5!*
- Student: _@show{(code '(triangle 5 "solid" "green"))}!_ *Note: Have the actor ignore the punctuation, and just say "triangle 5 solid green!"*
- Teacher: *gt 20!*
- Student: _@show{(code '(triangle 20 "solid" "green"))}!_
- Teacher: *gt 200!*
- Student: _@show{(code '(triangle 200 "solid" "green"))}!_
- Teacher: *gt 99!*
- Student: _@show{(code '(triangle 99 "solid" "green"))}!_
}

@slidebreak{Investigate-RP}

@lesson-roleplay{
That was a great rehearsal. You're ready for the stage! 

Now it's the class' turn to give you cues! 

Who's got a `gt` expression for our actor?
}

@teacher{
Go around the room soliciting `gt` expressions from students until it's clear that everyone could run this script in their sleep.

Thank your volunteer.

Assuming they did a wonderful job, ask them: How did you get to be so speedy at building green triangles? You seemed so confident! _Ideally they'll tell you that they had good instructions and that it was easy to follow the pattern._
}

Just as we were able to give our volunteer instructions that let them take in `gt 20` and give us back @show{(code '(triangle 20 "solid" "green"))}, we can define any @vocab{function} we'd like in the *Definitions Area*.

=== Synthesize
@slidestyle{Synthesize}

@QandA{
@Q{How was `gt` sure what code to generate when all we gave them was the function name and a number?}
@A{The function only produced solid green triangles, so they followed the pattern and knew to used "solid" and "green" every time!}
}


== Identifying and Describing the Pattern

=== Overview
Students will look for what's changing in the examples, label it with a @vocab{variable} and use that information to write a function definition. Students will also think about how the @vocab{Domain} of `gt`differs from the @vocab{Domain} of `triangle`. By the end of the lesson they will have @vocab{defined} functions of their own design.

=== Launch
@slidestyle{Launch}

We need to program the computer to be as smart as our volunteer. But how do we do that? In order to define a function, we need to identify what's changing and what stays the same. 

@lesson-instruction{Take a look at the examples for `gt` below:

@show{(code '(gt 5))} &rarr; @show{(code '(triangle 5 "solid" "green"))}

@show{(code '(gt 10))} &rarr; @show{(code '(triangle 10 "solid" "green"))}

@show{(code '(gt 25))} &rarr; @show{(code '(triangle 25 "solid" "green"))}

@show{(code '(gt 100))} &rarr; @show{(code '(triangle 100 "solid" "green"))}

@show{(code '(gt 220))} &rarr; @show{(code '(triangle 220 "solid" "green"))}
}

@QandA{
@Q{What's changing?}
@A{The size. Everything else is the same in every single example!}
}

@teacher{
Highlight or circle the numbers in the gt column and in the triangle column to help students see that they're the only thing changing! Explain that we can define our function by replacing the numbers that change with a variable that describes them. In this case, `size` would be a logical variable.

@ifslide{You'll see an annotated version of these examples on the next slide, but on this slide you may still want to...}

Draw arrows to the two highlighted columns and label them with the word size. 

}

@slidebreak{LaunchC}

@ifslide{@centered-image{images/gt-examples.png}}

@slidebreak{LaunchC}

If we substitute `size` for the numbers that changed and keep everything else the same, it looks like this:

@center{@show{(code '(gt size))} &rarr; @show{(code '(triangle size "solid" "green"))}}

The way we write this in the editor is

@center{@show{(code '(define (gt size)(triangle size "solid" "green")))}}

@slidebreak{Launch}

@lesson-instruction{
- Turn to @printable-exercise{gt-domain-debate.adoc} and "decide and defend" who's correct:
  * Kermit: _The domain of `gt` is `Number, String, String`_ 
  * Oscar: _The domain of `gt` is `Number`_ 
}

@slidebreak{Launch}

In the case of `gt`, the domain was a number and that number stood for the `size` of the triangle we wanted to make. Whatever number we gave `gt` for the size of the triangle is the number our volunteer substituted into the `triangle` expression. Everything else stayed the same no matter what!

@QandA{
@Q{Why might someone think the domain for `gt` contains a Number and two Strings?}
@A{The function `gt` only needs one Number input because that's the only part that's changing. The function `gt` makes use of `triangle`, whose Domain is Number String String, but `gt` already knows what those strings should be.}
}

@slidebreak{Launch-DN}

@lesson-instruction{

- Open the @starter-file{gt}, save a copy of your own and click "Run".
- Evaluate @show{(code '(gt 10))} in the Interactions Area.
- Take one minute to see how many different green triangles you can make using the `gt` function.
}

@slidebreak{Launch}

@lesson-instruction{
- How many different green triangles were you able to make?
- How did making green triangles with `gt` compare to making them with your previous strategy?
}

=== Investigate
@slidestyle{Investigate-DN}

@teacher{
If you hammed it up and professed your love of green triangles in the first part of the lesson, explain to students that they have successfully defined a function to satisfy your love of green triangles... but other people have other favorite shapes and we need to be able to meet their needs, too.} 

Let's use what we've learned to define some other functions!

@lesson-instruction{
- What if we wanted to define a function `rs` to make solid red squares of whatever size we give them? 
  * Try it out on @printable-exercise{rs.adoc}.
- Add your new function definitions to your @starter-file{gt}.
  * Test them out.
- Once `rs` is working, move on to 
  * @printable-exercise{sun.adoc} 
  * @printable-exercise{define-your-own.adoc}
}

@teacher{
As students work, walk around the room and make sure that they are circling what changes in the examples and labeling it with a @vocab{variable} name that reflects what it represents.
}

@strategy{Connecting to Best Practices}{
Writing examples and identifying the variables lays the groundwork for writing the function, which is especially important as the functions get more complex.  It's like "showing your work" in math class. Don't skip this step!
}

=== Synthesize
@slidestyle{Synthesize}
- Why is defining functions useful to us as programmers?
- In math class we mostly see functions that consume numbers and produce numbers, but functions can consume values besides Numbers! What other data types did you see being consumed by these functions?
