= Balancing Function Growth and Axis Growth (Linear)

++++
<style>
/* Shrink vertical spacing on fitbs, and allow them to be smaller than normal */
.fitb, .fitbruby{padding-top: 1rem; min-width: unset !important; }

table { margin: 0 !important; }
td .autonum { padding-top: 0.7rem !important; }

.blanklines { line-height: 2rem !important; }

/* Don't eat up available vertical space with tables */
div#body.workbookpage table.FillVerticalSpace { height: unset; }

/*
  "Graph" tables provide a pure-CSS solution for all coordinate planes.

  They rely on a set up CSS variables, with reasonable defaults:
    --width and --height determine the size of plane. Defaults to 3in x 3x.
    --min-gap determines the minimum space between graphs. Defaults to 20px.

    --top_pct and --left_pct determine the origin's position (btw 0 and 1). Defaults to (0.5, 0.5).
    --minors determines how many "minor axes" (incl the one behind major). Defaults to 7.

    --x_label defaults to 'x'
    --y_label defaults to 'y'
*/
.graph{
  --min-gap: 10px;
}

.graph td {
  --width:    2.0in;
  --height:   1.3in;
  --left_pct: 0.08;
  --top_pct:  0.92;
  --x_label: 'x';
  --y_label: 'y';
}
table.graph td p:first-child { position: relative; text-align: right; }
.graph .fitb { border-color: gray; padding-top: 0; }
.graph td:nth-child(2) {
	background: none !important;
	width: unset !important;
}
.graph td:nth-child(2)::before, .graph td:nth-child(2)::after {
	content: unset !important;
}
.graph td:nth-child(2) * {
	position: unset !important;
	text-align: left !important;
}
.graph td li { margin-bottom: 7px !important; }

td { padding: 0 5px 0 0 !important; color: black !important; }
</style>
++++

////
- Import Desmos Styles
-
- This includes some inline CSS which loads the Desmos font,
- which includes special glyphs used for icons on Desmos.com
-
- It also defines the classname '.desmosbutton', which is used
- to style all demos glyphs
-
- Finally, it defines AsciiDoc variables for glyphs we use:
- {points}
- {caret}
- {magnifying}
- {wrench}
-
- Here's an example of using these:
- This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}

@link-instructions{
Make sure you're on *Slide 6: Balancing Growth (Linear)* of *Fitting Wealth-v-Health and Exploring Logarithmic Models*. +
Notice that both the x- and y-axis are be labeled with a sequence of numbers _(e.g. 0, 2, 4, 6 ...)_ 
}

@n The function @math{f} is @fitbruby{16em}{@ifsoln{Linear}}{Linear, Quadratic, Exponential, or Logarithmic}, and its slope is @fitb{2em}{@ifsoln{2}}. Which two points are plotted on @math{f}? @fitb{}{@ifsoln{@math{(1, 2)} and @math{(2, 4)}}}

@n What kind of growth do the sequences on these axes show? 
@hspace{3em}
@ifsoln-choice{Linear}    @hspace{1em}
Quadratic           @hspace{1em}
Exponential         @hspace{1em}
Logarithmic

== Faking a Change in Slope

What happens when we change the range of the y-values? Compare the two graphs.

[.FillVerticalSpace, cols="8a,1,8a", grid="none", frame="none"]
|===
| @center{@fitb{2em}{0} @math{< x <} @fitb{2em}{10} @hspace{3em} @fitb{2em}{0} @math{< y <} @fitb{2em}{10}}
@center{@image{../images/linear.png, 65%}}
|
| @center{@fitb{2em}{0} @math{< x <} @fitb{2em}{10} @hspace{3em} @fitb{2em}{0} @math{< y <} @fitb{2em}{5}}
@center{@image{../images/linear-scale.png, 65%}}
|===

@n Is the sequence used to label the y-axis still linear? @fitb{2em}{@ifsoln{Yes}} Are the two points on the line the same? @fitb{2em}{@ifsoln{Yes}} @hspace{1em} Is the slope of @math{f} the same? @fitb{2em}{@ifsoln{Yes}} How did the graph change, and why? @fitb{}{@ifsoln{The line *looks* steeper because we changed the scale, but all we did was "stretch" the y-axis}}

@n Could we have change the range of y-values on the visible graph AND still have it *look* like the original graph? Explain. @fitb{}{@ifsoln{We'd also have to change the range of the x-values.}}


== Faking a Change to Logarithmic

[.FillVerticalSpace, cols="3a,1a", frame="none", grid="none", options="noheader"]
|===
|
- Open "Graph Settings", then *open the "More Options" section* by clicking the triangle ([.desmosbutton]#{caret}#).
- *Change the y-axis* scale from `Linear` to `Logarithmic`. _(The y-axis labels should change to something like 0.1, 1, 10, 100...)_

@n What kind of growth does the sequence of numbers on the *y-axis* show _now?_  (circle one) +
@hspace{3em}
Linear 						@hspace{1em}
Quadratic 					@hspace{1em}
@ifsoln-choice{Exponential} @hspace{1em}
Logarithmic

@n Did our two points on the line change? @fitb{2em}{@ifsoln{No}} @hspace{1em} Did the slope of @math{f} change? @fitb{}{@ifsoln{No}}

@n Sketch the graph. How did it change, and why? @fitb{}{@ifsoln{It looks logarithmic!}}
|
[.graph, cols="1a", frame="none"]
!===
! *y-axis*: @fitb{auto}{Logarithmic}
!===

|===

@blanklines{1}{
@ifsoln{We "squished" the y-axis exponentially, which made the linear growth of @math{f} appear logarithmic}
}

== Faking a Change to Exponential

[.FillVerticalSpace, cols="3a,1a", frame="none", grid="none", options="noheader"]
|===
|
- Change the y-axis scale back to `Linear`, and the `x-axis` scale to `Logarithmic`.

@n What kind of growth does the sequence of numbers on the *x-axis* show _now?_ +
@hspace{3em}
Linear 						@hspace{1em}
Quadratic 					@hspace{1em}
@ifsoln-choice{Exponential} @hspace{1em}
Logarithmic

@n Did our two points on the line change? @fitb{2em}{@ifsoln{No}} @hspace{1em} Did the slope of @math{f} change? @fitb{}{@ifsoln{No}}

@n Sketch the graph. How did it change, and why? @fitb{}{@ifsoln{It looks exponential!}}

@blanklines{1}{
@ifsoln{We "squished" the x-axis exponentially, which made the linear growth of @math{f} appear exponential}
}

|
[.graph, cols="1a", frame="none"]
!===
! *x-axis*: @fitb{auto}{Logarithmic}
!===

|===

@n *Make a prediction:* What do you think will happen if _both axes_ are switched to `Logarithmic`? @fitb{}{@ifsoln{answers will vary...}} +
@fitb{}{}

@n Change both scales to `Logarithmic`. Was your prediction accurate? @fitb{2em}{}. @hspace{1em} What happened, and why? @fitb{}{} +
@fitb{}{@ifsoln{We "squished" both axes exponentially, so they balanced each other out and `f(x)` looks like a straight line.}}
