= Balancing Function Growth and Axis Growth (Logs and Exponents)

++++
<style>
/* Shrink vertical spacing on fitbs, and allow them to be smaller than normal */
.fitb, .fitbruby{padding-top: 1rem; min-width: unset !important; }

table { margin: 0 !important; }
td .autonum { padding-top: 0.7rem !important; }

.blanklines { line-height: 2rem !important; }

/*
  "Graph" tables provide a pure-CSS solution for all coordinate planes.

  They rely on a set up CSS variables, with reasonable defaults:
    --width and --height determine the size of plane. Defaults to 3in x 3x.
    --min-gap determines the minimum space between graphs. Defaults to 20px.

    --top_pct and --left_pct determine the origin's position (btw 0 and 1). Defaults to (0.5, 0.5).
    --minors determines how many "minor axes" (incl the one behind major). Defaults to 7.

    --x_label defaults to 'x'
    --y_label defaults to 'y'
*/
.graph{
  --min-gap: 10px;
}

.graph td {
  --width:    2.0in;
  --height:   1.6in;
  --left_pct: 0.08;
  --top_pct:  0.92;
  --x_label: 'x';
  --y_label: 'y';
}
table.graph td p:first-child { position: relative; text-align: right; }
.graph .fitb { border-color: gray; padding-top: 0; }
.graph td:nth-child(2) {
  background: none !important;
  width: unset !important;
}
.graph td:nth-child(2)::before, .graph td:nth-child(2)::after {
  content: unset !important;
}
.graph td:nth-child(2) * {
  position: unset !important;
  text-align: left !important;
}
.graph td li { margin-bottom: 7px !important; }

td { padding: 0 5px 0 0 !important; color: black !important; }
</style>
++++

////
- Import Desmos Styles
-
- This includes some inline CSS which loads the Desmos font,
- which includes special glyphs used for icons on Desmos.com
-
- It also defines the classname '.desmosbutton', which is used
- to style all demos glyphs
-
- Finally, it defines AsciiDoc variables for glyphs we use:
- {points}
- {caret}
- {magnifying}
- {wrench}
-
- Here's an example of using these:
- This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}

@link-instructions{
Make sure you're on *Slide 6: Changing Scale (Exponential and Logarithmic)* of *Fitting Wealth-v-Health and Exploring Logarithmic Models*.
}

- The folder for a logarithmic function @math{g} is shown in red, and the folder for @math{h} is "turned off". *Do not* turn it on yet!
- Both the x- and y-axis are be labeled with a sequence of numbers _(e.g. 0, 2, 4, 6 ...)_.

@n What kind of growth do the sequences on these axes show? (circle one) @hspace{6em}
@ifsoln-choice{Linear}    @hspace{1em}
Quadratic           @hspace{1em}
Exponential         @hspace{1em}
Logarithmic

@n The function @math{g} is @fitbruby{16em}{@ifsoln{Logarithmic}}{Linear, Quadratic, Exponential, or Logarithmic}, and its base is @fitb{3em}{@ifsoln{10}}. @hspace{1em} Which two points are plotted on @math{g}? @fitb{}{@ifsoln{@math{(1, 2)} and @math{(10, 4)}}}

- Click on the wrench button ([.desmosbutton]#{wrench}#) in the top-right corner of the Desmos graph to *open the "Graph Settings" window.*

@n The x-axis goes from @fitb{3em}{@ifsoln{~ -40}} ≤ @math{x} ≤ @fitb{3em}{@ifsoln{~ 40}} @hspace{3em} Can you change the scale to make @math{g} look linear? @fitb{3em}{@ifsoln{No}} @hspace{3em} Why or why not?

@blanklines{2}{
@ifsoln{No, because logarithms grow more slowly than linear functions. As long as the axis scales are linear, a logarithmic curve stays curved .}
}

== Balancing Logarithmic Growth

[.FillVerticalSpace, cols="3a,1a", grid="none", frame="none", options="noheader"]
|===
|
- Click on the wrench button ([.desmosbutton]#{wrench}#) and change the *x-axis* from `Linear` to `Logarithmic`

@n Did our two points on the line change? @fitb{2em}{@ifsoln{No}} @hspace{1em} How did the graph change? @fitb{}{@ifsoln{It turned straight! It looks linear!}} +

@n How did the graph change, and why? @fitb{}{@ifsoln{We "squished" the x-axis exponentially, which balanced out the logarithmic growth on the y-axis}} +
@fitb{}{}

@n *Make a prediction:* What would the graph look like with a `Linear` *x-axis* a `Logarithmic` *y-axis*?

|
[.graph, cols="1a", frame="none"]
!===
! x-axis: @fitb{auto}{Logarithmic}
!===

|===

@blanklines{2}{}

@n Try it out! Was your prediction accurate? @fitb{2em}{}. @hspace{1em} What happened, and why? @fitb{}{@ifsoln{The curve got "sharper". }} +
@fitb{}{@ifsoln{By "squishing" the y-axis, we only made the logarithmic growth appear stronger (it looks like we took the "log of the log!)")}}


== Balancing Exponential Growth

- Set the scale for both axes back to `Linear`.
- "Turn off" the folder for @math{g}, and "turn on" the folder for our exponential function @math{h}.

@n The function @math{h} is @fitbruby{16em}{@ifsoln{Exponential}}{Linear, Quadratic, Exponential, or Logarithmic}, and its base is @fitb{3em}{@ifsoln{2}}.  @hspace{1em} Which two points are plotted on @math{h}? @fitb{}{@ifsoln{@math{(1, 2)} and @math{(2, 4)}}}

@n Without switching either axis to `Logarithmic`, can we change the minimum and maximum @math{x} or @math{y} to make @math{h} look `Linear`? @fitb{}{@ifsoln{No}}

@n *Make a prediction:* Which axis should we switch to `Logarithmic`, in order to make @math{h} look `Linear`? @fitb{}{@ifsoln{We should switch the y-axis}}

@n Try it out! Was your prediction accurate? @fitb{2em}{}. @hspace{1em} What happened, and why? @fitb{}{@ifsoln{We "squished" the y-axis exponentially, which balanced out}} +
@fitb{}{@ifsoln{the exponential growth of @math{h}}}

@vspace{1ex}

- Change the *y-axis* back to `Linear`, and change the x-axis to `Logarithmic`

@n What happened to the graph of @math{h}, and why? @fitb{}{@ifsoln{The curve got "sharper". By "squishing" the x-axis, we only made the exponential growth}} +
@fitb{}{@ifsoln{appear stronger (it looks like we took the "exponent of the exponent!)")}}

@star Desmos has two choices for scale:

- `Linear` _(each interval is the same size as the one before it)_
- `Logarithmic` _(each interval is 10x larger than the one before it)_

If we wanted to make @math{h} appear linear *using the x-axis*, what kind of scale would we need? @fitb{}{}
@fitb{}{@ifsoln{The intervals on the x-axis would need to get _smaller_ by a factor of 10 to cancel out the exponential growth of @math{h}}} +
@fitb{}{@ifsoln{It would probably be called an `Exponential` scale.}}