= Fitting Logarithmic Models

++++
<style>

#content { display: block !important; }
div#body.workbookpage .studentAnswerShort { min-width: 30pt; } .studentAnswerMedium { min-width: 30pt !important;}

/* Shrink vertical spacing on fitbruby */
.fitbruby{padding-top: 1rem;}

</style>
++++

////
- Import Desmos Styles
-
- This includes some inline CSS which loads the Desmos font,
- which includes special glyphs used for icons on Desmos.com
-
- It also defines the classname '.desmosbutton', which is used
- to style all demos glyphs
-
- Finally, it defines AsciiDoc variables for glyphs we use:
- {points}
- {caret}
- {magnifying}
- {wrench}
-
- Here's an example of using these:
- This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}

@link-instructions{To complete this page you will need Desmos and the @starter-file{alg2-countries} open on your computer.}

@teacher{All numerical values on this page are provided for reference only! Definitions will vary as students will be fitting the curve by eye!}

@ifsoln{@vspace{1ex}}

== Fitting a Logarithmic Model @hspace{2em} __f(x) = a log~b~ x + k__
@link-instructions{You should be on *Slide 7: Wealth-v-Health (Logarithmic)* of *Fitting Wealth-v-Health and Exploring Logarithmic Models (Desmos)*.}

- The x-axis should labeled with a sequence of numbers that looks something like this: @hspace{1em} _20000, 40000, 60000, 80000, 10000, 120000..._ 


@n What kind of growth does the sequence on the x-axis show? (circle one) @ifnotsoln{@hspace{6em}} @ifsoln{@hspace{5em}}
@ifsoln-choice{Linear} 		@hspace{1em}
Quadratic 					@hspace{1em}
Exponential 				@hspace{1em}
Logarithmic

@n Use the sliders for @math{a} and @math{k} to make the best-fitting logarithmic model you can find. Write it below. _(Note: Pyret's `log` always uses @math{b = 10})_

@indented{
@ifsoln{*NOTE:* The answers to question 2 and 3 are just a sample - many other (similar) answers are valid!}
}

[cols="^1a", grid="none", frame="none", stripes="none"]
|===
|
@math{\text{logarithmic}(x) = }
@fitbruby{7em}{@ifsoln{7.2}}{log coefficient (a)}@math{\log_{10}(x) + }
@fitbruby{7em}{@ifsoln{45}}{vertical shift (k)}
@hspace{3em}
@show{(code '(define (logarithmic x) (+ (* (?ANS 7.2) (log x)) (?ANS 45))))}
|===




@n Define `logarithmic(x)` in the @starter-file{alg2-countries} to be this model, and fit it using `fit-model`.

@vspace{1ex}

@indented{
The error in the model is described by an @math{\text{S-value}} of about
@fitbruby{1em}{@ifsoln{5.79}}{S}
@fitbruby{4em}{@ifsoln{years}}{units}. @hspace{1em} I
@fitbruby{18em}{agree or disagree - not strong}{strongly agree, agree, disagree, strongly disagree} that this model is a good fit considering that
@fitbruby{14em}{@ifsoln{median life-expectancy}}{y-variable} in this dataset ranges from 
@fitbruby{6em}{@ifsoln{52.1}}{lowest y-value} to 
@fitbruby{6em}{@ifsoln{85.5}}{highest y-value}.
}

@vspace{1ex}

== Scaling the x-Axis

- Click on the wrench button ([.desmosbutton]#{wrench}#) in the top-right corner of the Desmos graph to *Open the "Graph Settings" window.*
- *Expand the "More Options" section* by clicking the triangle ([.desmosbutton]#{caret}#).
- *Change the x-axis scale* from `Linear` to `Logarithmic`. _(The x-axis labels should change to something like 100, 1000, @math{10^4}, @math{10^5}...)_

@n What kind of growth does the sequence on the x-axis show? (circle one) @ifnotsoln{@hspace{6em}} @ifsoln{@hspace{5em}}
Linear 							@hspace{1em}
Quadratic 						@hspace{1em}
@ifsoln-choice{Exponential} 	@hspace{1em}
Logarithmic

@n What is the shape of the point cloud, after changing the @math{x} scale to `Logarithmic`?  @ifnotsoln{@hspace{1em}} @ifsoln{{nbsp}} 
@ifsoln-choice{Linear} 	 	    @hspace{1em}
Quadratic 						@hspace{1em}
Exponential 					@hspace{1em}
Logarithmic

@n Adjust the sliders for @math{a} and @math{k} to improve the model. _Toggle back and forth between `logarithmic` and `linear` x-axis scales as you work._
@ifnotsoln{
@vspace{1ex}
@indented{When you are satisfied with your model, record both forms of the definition below.}
}

[cols="^1a", grid="none", frame="none", stripes="none"]
|===
|
@math{\text{logarithmic2}(x) = }
@fitbruby{7em}{@ifsoln{~12 to ~16}}{log coefficient (a)}@math{\log_{10}(x) + }
@fitbruby{7em}{@ifsoln{~8 to ~25}}{vertical shift (k)}
@hspace{1em}
@show{(code '(define (logarithmic2 x) (+ (* (?ANS 13 ) (log x)) (?ANS 18))))}
|===

@n In Pyret, define `logarithmic2(x)` to match this model.  Then use the `fit-model` function to find its @vocab{S-value}: @fitb{}{@ifsoln{less than 5 }}

@n How much
@fitbruby{5em}{@ifsoln{less}}{more / less }
error do we expect in predictions made using `logarithmic2` than with the `logarithmic` model?

@vspace{1ex}

@scrub{
A note for future authors:
- {&#8192;} is used below to add horizontal space.
- \text{} is used to make the words in the fraction use normal font.
}

@indented{
_Percent Change_ &#8192; = &#8192;
@math{
\frac{&#8192; \text{Difference} &#8192; \text{between} &#8192; \text{the} &#8192; \text{S-values}&#8192;}
{\text{S-value} &#8192; \text{for} &#8192; \text{logarithmic} &#8192; \text{model}}
\times 100 &#8192; = &#8192; }
@ifnotsoln{@math{\frac{\qquad}{\qquad}}}

We expect 
@fitb{4em}{} percent
@fitbruby{5em}{@ifsoln{less}}{ more / less }
error from predictions made with `logarithmic2` than with the `logarithmic` model!
}


@n Do we know for sure that either of these models is optimal? Explain. @fitb{}{@ifsoln{No! We just did our best using our eyes.}}

@fitb{}{}

@n Why does transforming the *x-axis* makes our data look linear? @fitb{}{@ifsoln{Answers will vary: The data is growing logarithmically}} +
@fitb{}{@ifsoln{and by transforming the x-axis exponentially, it can keep up with the growth. We're inverting the data. }} +
@fitb{}{@ifsoln{We're warping the scatter plot so the dots looks straight.}}
