= Functions for Tables (continued)

== count

@show{(contract "count" '("Table" "String") "Table")}

@n What is the Domain of `count`? @fitb{}{@ifsoln{Table, String}}

@n What is the Range of `count`? @fitb{}{@ifsoln{Table}}

@n What do you suspect the String in the Domain will describe? @fitb{}{@ifsoln{a column}}

@vspace{1ex}

*Suppose we wanted to know how many animals had 4 legs...*

Type @show{(code '(count animals-table "legs"))} into the Interactions Area and click "Enter"

@n What did the expression produce? @fitb{}{@ifsoln{a new table showing the counts for the number of animals with 0 legs, 3 legs, 4 legs and 8 legs}}

@n How many animals had 4 legs? @fitb{}{@ifsoln{29}}

@n Think of another question you might be able to answer with the `count` function.

@fitb{}{}

@n Fill in the blanks with the code you'd write.

@fitbruby{10em}{@ifsoln{count}}{function-name} (@fitbruby{20em}{@ifsoln{animals-table}}{table-name {two-colons} Table}, @fitbruby{15em}{@ifsoln{Answers will vary!}}{column-name {two-colons} String})

@n Tables that summarize data with a count are commonly used in the real world. Give two examples of where you've seen them before:

- Example 1: @fitb{}{@ifsoln{Answers will vary! Election Results, Survey Results, Fundraiser Results, etc. }}

- Example 2: @fitb{}{@ifsoln{Articles, Advertisements, Bills, etc.}}

@n Newscasters and journalists often incorporate data into their reporting. How else might they display this information, besides using a table?

@fitb{}{@ifsoln{bar charts, pictographs, infographics}}

== first-n-rows

@n Type @show{(code '(first-n-rows animals-table 5))}. What happens? @fitb{}{@ifsoln{It returns a new table with the first 5 rows from the `animals-table`}}

@n If we wanted a table of the first 3 rows of the `animals-table`, what code would you write? @fitb{}{@ifsoln{@show{(code '(first-n-rows animals-table 3))}}}

@n What is the Contract for `first-n-rows`? @fitb{}{@ifsoln{ `first-n-rows {two-colons} Table,  Number -> Table`}}

@vspace{1ex}

@star What happens when you type @show{(code '(first-n-rows (sort animals-table "pounds" true) 5))}?

@fitb{}{@ifsoln{It returns a new table with 5 rows of data for the lightest 5 animals in the `animals-table`.}}

@vspace{1ex}

[.indentedpara]
_Note: In this case, the output of `sort(animals-table, "pounds", true)` is the Table `first-n-rows` is taking in!_

@vspace{1ex}

@star &#9733; See if you can figure out how to compose the code that would generate a table of the 10 oldest animals!

@fitbruby{13em}{@ifsoln{first-n-rows}}{function-name} (@fitbruby{35em}{@ifsoln{sort(animals-table, "age", false)}}{Table}, @fitbruby{7em}{@ifsoln{10}}{Number})


