@comment{First line comment}

= Lesson C

@lesson-description{Lesson C teaches how to change LED light
bulbs. Prerequisites include statics, dynamics, with special
emphasis on angular momentum and torque.
}

@depends-on{lessonA,lessonB}

Big Idea of lesson goes here

[.left-header,cols="30a,70a"]
|===
|Lesson Goals
|Students will be able to:

* Goal #1
* Goal #2

|Student-Facing Goals
|
* I can...
* I can...
* I can...

|Key Points for the Facilitator
|
* Common student issues
* Pacing suggestions
* etc

|Prerequisites
|
* Previous lessons linked here

|Materials
|
* Links to printables, activities, etc., go here
|===

[.left-header,cols="30a,70a"]
|===
|Math Standards (CCSS)
|
* http://www.corestandards.org/Math/Practice/MP1[CCSS.MATH.PRACTICE.MP1],
Make sense of problems and persevere in solving them.
* http://www.corestandards.org/Math/Practice/MP2[CCSS.MATH.PRACTICE.MP2],
Reason abstractly and quantitatively.
* Other math standards.

|CS Standards (CSTA)
|
* CS Standards here.
|===


== Get Ready:

One sentence here.

== Launch: (time here)

Prose describing student task. About 3-4 sentences.

[.notice-box]
.Notice & Wonder
****
Ask students to take a minute to see what they *notice*.

Discuss as a group.

Ask students to take a minute to see what they *wonder*.

Share and discuss again.
****

2-3 more sentences of prose for the task, endpoint leading into
Explore section.

== Explore: (time here)

3-4 sentences of prose describing task.

@image{images/tbdek.jpg, tbdek,400,align="center"}


== Discuss: (time here)

* Guiding questions with responses here.
* And here.
* And here.
* etc.

[.strategy-box]
.Strategies for English Language Learners
****
MLR 8 -- Discussion Supports: As students discuss the guiding
questions, rephrase responses as questions and encourage
precision in the words being used to reinforce the meanings
behind some of the programming-specific language.
****

== Practice: (time here)

3-4 sentences of prose + images describing task.


[.physics-table,width="50%",cols="5a,5a",options="header"]
|===
|Miles drivien (mi)
|Costs ($)

|
|

|
|

|
|

|
|

|
|

|
|
|===

== Create/Apply: (15 minutes)

3-4 sentences of prose describing task.
