= Table Functions

@description{Students learn about functions that work with tables, allowing them to filter and build columns}

@lesson-prereqs{functions-examples-definitions, contracts-tables-displays}

@keywords{circles of evaluation, filter, filtering, sort, sorting, build, building}

@add-to-lang{sort, filter, build-column}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* filter tables according to different criteria, using helper functions
* add a column to a table using helper functions

| Student-facing Lesson Goals
|

* Let’s learn how transform one table into another.

| Materials
|[.materials-links]

@material-links

|===

== Review @duration{15 minutes}

=== Overview

Students practice carefully reading the contents of a starter file to review and gain comfort with row-consuming functions.

=== Launch

[.lesson-instruction]
- Load the @starter-file{table-functions}, go to the File menu, and click "Save a Copy".
- Hit "Run," then type `shapes-table` in the Interactions Area.
- The way this file defines a table is different from what we've encountered before. How is it different?
** Pyret also allows us to define Tables __in code__, rather than using a spreadsheet. This file defines the `shapes-table` one row at a time.

=== Investigate

[.lesson-instruction]
With your partner, take 5 minutes to complete @printable-exercise{pages/row-and-function-definitions.adoc}.

Once students have completed the activity, follow up to confirm understanding.

[.lesson-instruction]
* Who can explain what `is-red` does?
** _It looks up the color of the row, and checks if it is equal to the string `"red"`._
* Who can explain what `is-polygon` does?
** _It looks up the value in the `polygon` column._
* Who can explain what `is-triangle` does?
** _It checks if the value in the `name` column contains `"triangle"`._

Challenge students to use terminology like "looks up the value in the X column" when describing a lookup.

=== Synthesize

- Were you able to guess what the functions did before testing them out? What was your strategy for making an educated guess?
- What is the relationship between a _row definition_ and a _row-consuming function_?

== Filtering Rows, Building Columns @duration{35 minutes}

=== Overview
Students learn to filter the rows and add new columns to a table, using functions they can define themselves.

=== Launch
Select 6-8 students, each of whom will represent a unique Row of a dataset called “Students.”  Arrange them in a line at the front of the room.

Sometimes we want to *filter the rows* of a table by some criteria. In our animals dataset, for example, we might want to filter the table to show only the rows for dogs, or only the rows for cats older than 5. What are some ways to filter our table of students?

[.lesson-roleplay]
--
- I am going to select a volunteer who will play the role of… `filter`!
- I will hand the volunteer a function card from the @handout{pages/function-cards.adoc, Function Cards} set. (Choose your students and cards carefully! Some cards only work if you have at least one student with glasses, red hair, etc.)
- Next, `filter` will read the card carefully, making sure they understand what it will do for each "Row" (student!) in the "Table"... but they will __keep it a secret__.
- The volunteer playing Filter will walk from one student to the next, referring to the function (on the card) in order to determine if each student should step forward or step backward.

Here’s how that might look if `filter` chose a function card `has-glasses`.

- `filter` _stands in front of Student 1 and checks if they are wearing glasses._
- *`filter` to Student 1 (who wears glasses)*: Step forward. (Student 1 steps forward.)
- `filter` _stands in front of Student 2 and checks if they are wearing glasses._
- *`filter` to Student 2 (who does not wear glasses)*: Step back. (Student 2 steps back.)
--

Have your `filter` volunteer go through all their peers, applying their card to each one. Based on who stepped forward and backward, what was on the card? Repeat for several cards. Give the volunteer a round of applause!

=== Investigate
Pyret Tables have their own functions for filtering tables - and more! Let's explore some of these.

[.lesson-instruction]
Take 10 minutes to complete @printable-exercise{exploring-functions.adoc}

Confirm that students understand the following key ideas:

* `filter` consumes a Table and a _function that consumes Rows and produces Booleans_. It produces a new table containing only rows for which the function returns `true`.
* `build-column` consumes a Table, the name of a new column, and a _function that consumes Rows_. It produces a new table with that new column, and fills in the values by applying the function to every Row.

[.lesson-instruction]
How would you filter and build using the Animals Dataset? For practice, complete @printable-exercise{pages/what-table-do-we-get.adoc}.

=== Common Misconceptions
*Students often think that these functions _change_ the table!* In Pyret, all table functions produce a _brand new table_. If we want to save that table and use it later, we need to define it. For example: `cats = filter(animals-table, is-cat)`.

=== Synthesize
Using Table Functions is a _huge_ upgrade in our ability to analyze data!

- If the shelter is purchasing food for older cats, what filter would we write to determine how many cats to buy for?
- A dataset from Europe might list everything in metric (centimeters, kilograms, etc), so we could build a column to convert that to imperial units (inches, pounds, etc).
- A dataset about sports teams might include columns for how many games each team won and how many they lost, but it's more useful to build a column to see _what percentage of games_ those teams won.
