= Visualizing Relationships


- *Scatter Plots* can be used to show a relationship between two quantitative
columns. Each row in the dataset is represented by a point, with one column
providing the x-value and the other providing the y-value. The resulting “point
cloud” makes it possible to look for a relationship between those two columns.



- If the points in a scatter plot appear to follow a straight line, it is possible that a
linear relationship exists between those two columns. A number called a
*correlation* can be used to summarize this relationship.



- The correlation is *positive* if the point cloud slopes up as it goes farther to the
right. It is *negative* if it slopes down as it goes farther to the right. If the points are
tightly clustered around a line, it is a *strong* correlation. If they are loosely
scattered, it is a *weak* correlation.



- Points that are far above or below the cloud of points in a scatter plot are called
*outliers*.



- We graphically summarize this relationship by drawing a straight line through the
data cloud, so that the vertical distance between the line and each of the
points is as small as possible. This line is called the *line of
best fit* and allows us to
predict y-values based on x-values.


