= Which One Isn't Equivalent? Exponent Expressions

Identify the circle of evaluation in each row below that doesn’t evaluate to the same things as the others.

++++
<style>
.chosen::after { content: '❌' !important; }
.circleevalsexp { width: auto; }

/* for table cells with immediate .content children, which have immediate
 * .paragraph children: use flex to space them evenly and center vertically
*/
td > .content > .paragraph:has(.circleevalsexp) {
  display: flex;
  align-items: center;
  justify-content: space-around;
}
/* Allow the parent (.paragraph) to control the display of the child elements */
td > .content > .paragraph > p { display: contents; }
</style>
++++

[.FillVerticalSpace, cols="<.^1a,^.^22a",stripes="none", options="header"]
|===
| 	 | Circles of Evaluation

| @n
|
@show{(coe '(expt 2 4))}
@show{(coe '(* 2 (expt 2 3)))}
@show{(coe '(* 2 (* 2 (expt 2 2))))}
@ifsoln-choice{@show{(coe '(* 2 (* 2 (* 2 3))))}}

| @n
|
@ifsoln-choice{@show{(coe '(* (expt 2 3) 2))}}
@show{(coe '(* 2 (expt 3 2)))}
@show{(coe '(* (expt 3 2) 2))}
@show{(coe '(+ (expt  3 2) (expt 3 2)))}

| @n
|
@show{(coe '(* 6 (expt 2 2)))}
@show{(coe '(* 3 (* 2 (* 2 2))))}
@ifsoln-choice{@show{(coe '(* (expt 3 2) (expt 2 2)))}}
@show{(coe '(* (expt 2 3) 3))}

| @n
|
@show{(coe '(expt 5 2))}
@show{(coe '(* (+ 3 2) 5))}
@ifsoln-choice{@show{(coe '(expt (+ 3 2) 5))}}
@show{(coe '(expt (+ 3 2) 2))}

| @n
|
@show{(coe '(/ (expt 6 2) 4))}
@ifsoln-choice{@show{(coe '(- (expt 6 2) 3))}}
@show{(coe '((/ expt 3 3) 3))}
@show{(coe '(expt 3 2))}

| @n
|
@ifsoln-choice{@show{(coe '(* 3 (* 3 2)))}}
@show{(coe '(* (* 3 3) 3))}
@show{(coe '(* 3 (expt 3 2)))}
@show{(coe '(/ 3 (expt 3 4)))}
|===