= Functions: Contracts, Examples & Definitions

@description{Students learn to connect function descriptions across three representations: Contracts (a mapping between Domain and Range), Examples (a list of discrete inputs and outputs), and Definitions (symbolic).}

@lesson-prereqs{contracts}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* identify patterns where a function would be useful
* define their own function
* match examples, contracts, and definitions for the same function

| Student-Facing Lesson Goals
|

* Let's define our own functions, by writing contracts and examples to help us identify patterns.

| Materials
|[.materials-links]


@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links
* @lesson-link{project-function}

|===

== Three Representations of a Function @duration{55 minutes}

=== Overview
Students will practice describing functions using all 3 representations (in programming syntax), and test their code against the examples in the editor.

=== Launch

@lesson-instruction{
- Open the @starter-file{bc}. Look at the Contract, some Examples, and the Function Definition for `gt`.
- What do you Notice? What do you wonder?
}

We know that...

@n Every @vocab{function} has a @vocab{Contract}.

[.indentedpara]
@show{(contract "gt" '("Number" ) "Image")}

@n We can write @vocab{examples} illustrating how a @vocab{function} should work to help us identify the pattern.

[.indentedpara]
@image{images/examples.png, 400}

@n @vocab{Function definitions} replace whatever changes in the @vocab{examples} with a @vocab{variable} describing what changes.

[.indentedpara]
@image{images/gt-fun.png}

@lesson-instruction{
If we use the correct syntax, we can include all three of these function representations in our @ifproglang{pyret}{Pyret} @ifproglang{wescheme}{WeScheme} files. Let's take a look!

* Click "Run". @ifproglang{pyret}{ What message do you get back?
** _Looks shipshape, all 5 tests passed, mate!_
* What do you think that message means?
** _The editor has checked to see whether the 5 examples work with the function definition and they do!_
}
* Change
@ifproglang{pyret}{`gt(10) is triangle(10, "solid", "green")` to `gt(15) is triangle(15, "solid", "green")`}
@ifproglang{wescheme}{`(EXAMPLE (gt 10) (triangle 10 "solid" "green"))` to `(EXAMPLE (gt 10) (triangle 15 "solid" "green"))`}
* Click "Run". What happens?
** _The editor lets us know that the function doesn't match the examples so that we can fix our mistake!_
}

Examples not only help us to identify the pattern to define a function, they also let us double check that the functions we define do what we intend for them to do!

=== Investigate

@lesson-instruction{
Think about these three representations of functions by completing:

- @printable-exercise{match-examples-contracts.adoc}
- @printable-exercise{match-examples-definitions.adoc}
- @printable-exercise{create-contracts-examples.adoc}

For more practice, complete these Desmos card sort activities:

- @ifproglang{wescheme}{@opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/60aa50b7012000080d4136a0, Matching Examples & Contracts}}
@ifproglang{pyret}{@opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fc9328d18307e2e492ca0d8, Matching Examples & Contracts}}
- @ifproglang{pyret}{@opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fc536c0e2f06d0cd3992c68, Matching Examples & Function Definitions}}
@ifproglang{wescheme}{@opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/607b618988b17d447fe159e8?collections=5fece3d3e755260caa22904c, Matching Examples & Function Definitions}}
}

_There are many more materials for students to work with in the Additional Practice section at the end of the lesson!_

=== Synthesize

- What strategies did you use to match the @vocab{examples} with the @vocab{contracts}?
- What strategies did you use to match the @vocab{examples} with the @vocab{function definitions}?

== Defining bc and Other Functions

=== Overview
Using `gt` as an example, students will write the @vocab{Contract}, @vocab{examples}, and @vocab{definition} for several other @vocab{functions}.

=== Launch

@lesson-instruction{
- Turn to @printable-exercise{pages/contracts-examples-definitions.adoc}
- On the top half of the page, you will see the Contract, examples, and function definition for `gt`.
- Circle what is changing and label it with the word `size`.
- Using `gt` as a model, complete the Contract, examples and function definition for `bc`.
}

When students have completed the above steps, direct them to type the Contract, Examples and Definition into the Definitions Area. They will then click “Run”, and make sure all of the examples pass!

Check-in with students to gauge their confidence level. (Thumbs up? Thumbs to the side? Thumbs down?) How confident do students feel in writing the @vocab{Contract}, @vocab{examples} and @vocab{function definition} on their own if they were given a word problem about another shape function?

=== Investigate
@lesson-instruction{
- Complete @printable-exercise{pages/contracts-examples-definitions-stars.adoc}.
- Complete @printable-exercise{pages/contracts-examples-definitions-name.adoc}.
}

As students work, walk around the room and make sure that they are circling what changes in the @vocab{examples} and labeling it with a @vocab{variable} name that reflects what it represents.


@ifproglang{pyret}{
@strategy{
@span{.title}{Optional Project: Create Your Own Function}

In this lesson, students defined functions given a specific set of parameters. In @lesson-link{project-function}, students get additional practice thinking about functions before developing and defining a function of their own.}}

=== Synthesize

- How were each of the representations helpful?
- Why is it important to write examples in our code?

== Additional Exercises

- @opt-printable-exercise{pages/examples-same-contracts1.adoc}
- @opt-printable-exercise{pages/examples-same-contracts2.adoc}
- @opt-printable-exercise{pages/match-contracts-examples1.adoc}
- @opt-printable-exercise{pages/match-contracts-examples2.adoc}

