= Mood Generator

1) Open the Mood Generator starter file, and read throught the code you find there. This code contains new programming that you haven't seen yet! Take a moment to list everything you Notice, and then everything you Wonder...

@vspace{2ex}

[cols="^1,^1", options="header"]
|===
| *Notice* 		| *Wonder*
| (sample responses) I notice the usual imports at the top, including defining the animals table and the spreadsheet. I notice what looks like a function definition, but I see if/else in there
| (sample responses) I wonder what if/else are all about...
|===

@vspace{2ex}

2) Add another line of code to the definition, so that  `mood("mad")` produces the _same_ emoji as `mood("angry")`.

`else if (feeling == "mad"): "😡"`

@vspace{2ex}

3) Add *another example* to the  `examples:` section for "laughing", using the appropriate emoji.

`mood("laughing") is "😂"`

@vspace{2ex}

4) Come up with some new moods, and add them to the code. Make sure you include `examples:`!

(depends on student choice - look for missing quotes, new lines in the definition without lines in the examples, etc.)

@vspace{2ex}

6) In your own words, how do  `if`-expressions work in Pyret? Write your answer below.

@span{.blankline}{Every if-expression has a test, which contains a boolean expression. If the test is true, Pyret evaluates whatever comes after it.}

@span{.blankline}{Otherwise, it evaluates whatever comes after the  `else:`}

@span{.blankline}

@span{.blankline}

@vspace{2ex}

7) Write down at least 2 ways you could use `if`-expressions when analyzing the Animals Dataset.

@span{.blankline}

@span{.blankline}

@span{.blankline}

@span{.blankline}