= Functions Can Be Linear

++++
<style>
#content .small-table {max-width: 75%}
#content .graph-table img {width: 33%;}
</style>
++++

@description{Students explore the concept of slope and y-intercept in linear relationships, using function definitions as a third representation (alongside tables and graphs).}

@lesson-prereqs{}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* identify linear and non-linear graphs and tables
* identify the @vocab{slope} and @vocab{y-intercept} for a @vocab{linear relationship} shown as a @vocab{table} or @vocab{graph}
* match different representations of the same linear relationship

| Student-facing Lesson Goals
|

* Let's learn to tell the difference between linear and non-linear relationships in tables and graphs.
* Let's connect @vocab{graphs} to @vocab{tables} that describe the same @vocab{linear relationships}.
* Let's compute the @vocab{slope} and @vocab{y-intercept} from a table or graph of a linear relationship.

| Materials
|[.materials-links]

@material-links

| Key Points for the Facilitator
|

* Lines are made of points (try to avoid referring to "lines" as much as "collections of points")
* Linear functions can be represented as straight lines on a graph or as sequences that change at a constant rate in a table.
|===

== Simple Sequences and Straight Lines @duration{15 minutes}

=== Overview
Students explore the concept of _linearity_, as represented in tables and graphs.

=== Launch

[.lesson-instruction]
Complete Part 1 of @printable-exercise{notice-wonder-linearity.adoc} and Notice and Wonder about this table and graph.

[cols="^.^1a,^.^1a", grid="none", frame="none"]
|===

|

[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! 0
! 1 ! 2
! 2 ! 4
! 3 ! 6
! 4 ! 8
!===
| @image{images/2x.png}
|===

[.lesson-instruction]
- What do you *Notice?*
** _Although answers will vary, important observations include:_ 
** _each (x,y) pair on the table corresponds to a point on the graph_
** _both the x and y values in the table are increasing by consistent intervals_
** _the points on the graph are connected by a straight line._
- What do you *Wonder?*
- Complete Part 2 of @printable-exercise{notice-wonder-linearity.adoc} and consider the questions about these two data tables.

[cols="^.^1a,^.^1a", frame="none"]
|===
|

[.pyret-table.first-table,cols="^1,^1",options="header"]
!===
! x ! y
! 1 ! 2
! 2 ! 3
! 3 ! 4
! 4 ! 5
! 5 ! 6
!===

|
[.pyret-table.first-table,cols="^1,^1",options="header"]
!===
! x ! y
! 1 ! 20
! 2 ! 17
! 3 ! 14
! 4 ! 11
! 5 ! 8
!===

|===

[.lesson-instruction]
- What would the next (x,y) pairs be for these tables?
- What would the y-values be when x is 0?

We can think of the "x" column as counting the __order in which the y-values appear__ (1st value, 2nd value, etc). When we notice that x-values change at a _constant rate_ and the y-values also change at a _constant rate_, we know that if we were to plot those values on a graph, all of the points would fall on a straight line.

[.lesson-point]
*Linear Relationships* are sequences that change at a constant rate, or points forming a straight line on a graph.

The @vocab{line} representing the @vocab{linear relationship} would not only include the points represented in the @vocab{table}, but also **all of the coordinate pairs that satisfy the same rule**, including lots of points whose x and y values are fractions and decimals.

=== Investigate

[.lesson-instruction]
- Let's get some practice connecting tables and graphs on @printable-exercise{pages/match-tables-graphs.adoc}.
- Another option for additional practice is @online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fc25d458dcfcf0b92021b13, "Matching Tables to Graphs"}.

[.lesson-point]
@vocab{Axes} on a graph need an order. @vocab{Rows} in a table don't!

The points in a table are _discrete_. While ordering the rows in a table can make it easier for us to find the function,
they preserve their meaning if the rows are shuffled into a different order.

On a graph, the points on the x-axis _cannot_ be shuffled, because the x-axis must always be ordered. We can stretch the _scale_ of the axes to making the lines _look_ different, but the points will always be in the same order.

[.lesson-instruction]
Optional: For a challenge - matching tables and graphs with shuffled rows - complete @opt-printable-exercise{pages/match-tables-graphs2.adoc}.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Pedagogy Note}

To encourage students to look at the _points_ in the table and on the graph, it can be useful to change the @vocab{scale} of the graphs to prevent students from leaning on visual cues like "steepness" to bypass the learning objective.

It can also be useful to list the points in the table __out of order__, both to focus students' attention on the points and to drive home that rows do not have to be ordered!
|===

=== Synthesize
We've seen that linear relationships can be represented as tables and graphs. Tables only show us _some points_ on a line, whereas a line itself is made up of an _infinite_ number of points. While a table represents a _sample_ of some larger trend, the graph is a way of seeing the trend itself.

== Linear, Non-Linear, or Bust!  @duration{15 minutes}

=== Overview
Students deepen their understanding of linearity, by seeing counterexamples (non-linear relationships), as well as tables and graphs for which there is _no_ relationship.

=== Launch

Have students turn to @printable-exercise{graphs-all-linear.adoc}, where they'll Notice and Wonder about the six graphs below and consider the question,
*If all linear relationships can be shown as points on a graph, does that mean all graphs are linear?*

[.graph-table, stripes="none", frame="none"]
|===

| @image{images/constant-linear.png}
  @image{images/num-abs.png}
  @image{images/num-sqrt.png}

| @image{images/negative-linear.png}
  @image{images/positive-linear.png}
  @image{images/num-sqr.png}
|===

[.lesson-instruction]
- What do you *Notice?*
- What do you *Wonder?*

[.lesson-point]
Linear relationships in a graph always appear as straight lines

Three of the graphs above represent @vocab{linear relationships}, and three show other, non-linear relationships. As we can see, the linear graphs can go in lots of directions and non-linear relationships can follow patterns that aren't linear!

Have students turn to @printable-exercise{tables-all-linear.adoc}, where they'll Notice and Wonder about the six tables below and consider the question,
*If all linear relationships can be shown as tables, does that mean all tables are linear?*

[cols="^.^1a,^.^1a", frame="none"]
|===

|

[.sideways-pyret-table]
!===
! x ! -2 ! -1 !  0 !  1 !  2
! y ! -2 ! -3 ! -4 ! -5 ! -6
!===
|

[.sideways-pyret-table]
!===
! x ! 1 ! 2 ! 3 !  4 !  5
! y ! 1 ! 4 ! 9 ! 16 ! 25
!===

|

[.sideways-pyret-table]
!===
! x !  12 !  13 !  14 !  15 !  16
! y ! -12 ! -14 ! -16 ! -18 ! -20
!===

|

[.sideways-pyret-table]
!===
! x ! 5 ! 6 ! 7 ! 8 ! 9
! y ! 3 ! 3 ! 3 ! 3 ! 3
!===

|

[.sideways-pyret-table]
!===
! x !  1 !  2 !   3 !   4 !  5
! y ! 84 ! 94 ! 104 ! 114 ! 124
!===

|

[.sideways-pyret-table]
!===
! x ! -10 ! -9 ! -8 !  -7 ! -6
! y ! @math{\frac{-1}{10}} ! @math{\frac{-1}{9}} ! @math{\frac{-1}{8}} ! @math{\frac{-1}{7}} ! @math{\frac{-1}{6}}
!===

|===

[.lesson-instruction]
- What do you *Notice?*
- What do you *Wonder?*
- Can you figure out what the next (x,y) pair should be for each of them?
- Can you guess what the y-value for each table would be when x is 0?

[.lesson-point]
In a table representing a linear relationship, a change in the independent variable (typically graphed as x) corresponds to a proportional change in the dependent variable (typically graphed as y). When sequences change at a constant rate, the points will form a straight line on a graph.

Three of the tables above show @vocab{linear} relationships, and three show other, non-linear relationships. As we can see, the linear tables can have y-values that change by zero (no change), by a positive number (constant increase), or a negative number (constant decrease) as the x-values increase. The other tables may show patterns, but they aren't linear!

Sometimes there is __no function__ that will give us a particular table or graph! Take a look at the table and graph below. Can you predict the next two rows? Where will the next point be?

[cols="^.^1a,^.^1a", grid="none", frame="none"]
|===

|

[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! 13
! 1 ! -2
! 1 ! 16
! 3 ! 0
! 4 ! 54
!===
| @image{images/scatterplot.png}
|===

=== Investigate
[.lesson-instruction]
--
* Can you tell when a relationship is a linear function? A non-linear one? Not a function at all?
* Can someone remind us how to tell whether or not a graph represents a function? _It has to pass the vertical line test!_
--

Have students complete @printable-exercise{linear-nonlinear-bust.adoc}. For more (optional) practice, you can have them work with @opt-printable-exercise{linear-nonlinear-bust-graphs.adoc} and @opt-printable-exercise{linear-nonlinear-bust-graphs-2.adoc}.

=== Synthesize
Data has a "shape", and this shape can emerge when we look for patterns in that data. A @vocab{linear} function is one kind of pattern, and we can see it when viewing data as a table or a graph.

== Slope and y-Intercept from Tables @duration{20 minutes}

=== Overview
Students refine their understanding of linearity, identifying properties like @vocab{slope} and @vocab{y-intercept} in tables.

=== Launch

[.lesson-point]
All linear relationships are defined by slope and y-intercept.

Every linear relationship has two properties:

1) The sequence of y-values always changes at a constant rate - called @vocab{slope} - increasing or decreasing by the same amount for each change in the x-value.

2) The y-value when @math{x = 0} is called the @vocab{y-intercept}.

Have students turn to @printable-exercise{slope-int-tables-intro.adoc} and facilitate a discussion.

[.lesson-instruction]
--
Consider the first table on @printable-exercise{slope-int-tables-intro.adoc, the page}:

[.sideways-pyret-table]
|===
| x | -1 | 0 | 1 | 2 | 3 | 4
| y | -1 | 1 | 3 | 5 | 7 | 9
|===

* Compute how much y increases as x increases by 1. We call this the @vocab{slope}.
** _We can see that the y-values increase by 2 each time x increases by 1, giving us a @vocab{slope} of 2._
** _Some students may need an explicit demonstration of subtracting two adjacent y-values in order to recognize that they are changing by 2._
* Identify the @vocab{y-intercept} by finding the y-value when @math{x = 0}.
** _The @vocab{y-intercept} is 1._
* What strategies did you use to compute the slope and y-intercept?
** _Leave some time for group discussion of strategies!_
* Complete @printable-exercise{slope-int-tables-basic.adoc} for more practice with this before we move on to more complicated tables.
--

Life isn't always so simple!

- What if the table didn't include x = 0?
- What if the x-values didn't increase by 1?
- What if the x-values were __out of order__?
- What if we only had two random coordinate pairs?

[.lesson-instruction]
--
Consider the second table on @printable-exercise{slope-int-tables-intro.adoc, the page}:
[.sideways-pyret-table]
|===
| x |  2 | 5 | 8  | 11
| y |  3 | 9 | 15 | 21
|===
* Try extending the table and filling in the missing points to find the slope and y-intercept.
* What strategies did you use to extend the table?
--

How do we find the @vocab{slope} and @vocab{y-intercept} for these functions, _without_ having to sort or extend the table?

We can exploit the fact that all linear functions form _straight lines_, and a straight line can be defined with only __two points!__ That means it is always possible to compute @vocab{slope} and @vocab{y-intercept}, as long as we have two coordinate pairs!

[.lesson-instruction]
You can find the y-intercept by expanding the table and following the pattern to figure out the value of @math{y} when @math{x = 0}, but sometimes that's a lot of work! Take a few minutes to brainstorm about how we might compute the slope and y-intercept, using only points from the table.

Leave some time for group discussion...

@vspace{1ex}

*TO FIND THE SLOPE: Find any two pairs of values in the table, and divide the difference in y's by the difference in x's.*

This is an easy way to see the change in y __as a proportion__ of the change in x, which gives you the @vocab{slope} of the function.

This is often described as  @math{\frac{ChangeInY}{ChangeInX}} or @math{\frac{rise}{run}}.

@vspace{2ex}

[.sideways-pyret-table]
|===

| x | **3** | **20** | 5  |  9 | 1
| y | **5** | **56** | 11 | 23 | -1
|===

Taking the first two pairs of values in the the last table on @printable-exercise{slope-int-tables-intro.adoc, the page}, this gives us @math{\frac{56 - 5}{20 - 3}}. We can simplify that to @math{\frac{51}{17}}, for a slope of @math{3}.

@vspace{2ex}

We would get the same answer if we subtracted the coordinates in the opposite order... @math{\frac{5 - 56}{3 - 20} = \frac{-51}{-17} = 3}.

@vspace{2ex}

[.lesson-point]
Order matters!

We can use the two points in any order we wish, but we need to use the same order for our x's and y's. If we mixed up the order for this example, we'd get @math{\frac{56 - 5}{3 - 20} = \frac{51}{-17} = -3}.

[.lesson-instruction]
* Pick two other pairs of values from the third table and compute the @vocab{slope}. Did you get the same answer?
* Are there other strategies we could have used to find the slope?

@vspace{1ex}

_We'll talk more about how to find the y-intercept in the Defining Linear Functions lesson._

=== Investigate
Let's get some practice identifying the slope of a linear function in a table by completing @printable-exercise{slope-and-y-tables.adoc}

=== Synthesize
@vocab{Slope} and @vocab{y-intercept} form the essence of linear functions. If we can find them in a sample of data, we can make predictions that go outside that sample. For example: If we know a car is moving at a consistent speed, all we need to know is __where it is located at two points in time__ in order to figure out the speed, and to predict where it will be at any other point during its trip!

== Slope and y-Intercept from Graphs @duration{15 minutes}

=== Overview
Students refine their understanding of linearity, identifying properties like @vocab{slope} and @vocab{y-intercept} from graphs.

=== Launch
On a graph, the y-intercept is the value where the line "intercepts" the y-axis.

[cols="^1,^1"]
|===
|
@centered-image{images/y-intercept-diagonal.png}
|
@centered-image{images/y-intercept-horizontal.png}
|===

On a graph, the slope refers to both the "steepness" and "direction" of the line.

[cols="^1,^1, ^1"]
|===
| If it goes up as we go from left to right, the slope is *positive*.
| If it goes down as we go from left to right, the slope is *negative*.
| If it stays perfectly horizontal, the slope is *zero*.
| @centered-image{images/positive.png}
| @centered-image{images/negative.png}
| @centered-image{images/horizontal.png}
|===

We can compute the @vocab{slope} from a graph the same way we would with a table, by picking two points we know the exact coordinates of.

@centered-image{images/slope.png, 600}

=== Investigate
Let's get some practice identifying the slope and y-intercept of a linear function in a graph by completing @printable-exercise{slope-and-y-graphs.adoc}

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Pedagogy Note}

Some texts refer to "four ways to draw straight lines on a graph": sloping up and to the right, down and to the left, horizontal, or _vertical_. When thinking only in terms of straight lines on a graph, this is technically correct! However, just because we can draw those lines doesn't make them _functions_, and it doesn't mean they all have a defined slope!

Once students are comfortable computing slope, try having them compute the slope of a vertical line. They will quickly realize that this results in a zero in the denominator, which makes the slope _undefined_! This can be a good review of divide-by-zero and another lens for thinking about the vertical line test.
|===

=== Synthesize
We have learned how to find @vocab{slope} and @vocab{y-intercept} from tables and graphs of linear relationships. Check in with yourself and what we've learned today.

* Which representation do you feel more confident finding the slope from? Why?
* Which representation do you feel more confident finding the y-intercept from? Why?
Looking ahead, we will be learning about yet another representation of Linear Functions that you might find to be even more flexible and powerful.

Linear relationships are _everywhere_:

* "On average, for each extra gallon I pump into my tank, I can drive an additional 31 miles."
* "For each additional hour Carlo babysits, he earns 15 more dollars."
* "Each cockroach the lizard eats decreases the number of cockroaches in the house by one."
* "Every 10 additional people in line for the ride at the amusement park increases the wait time by 3 minutes."

What other linear relationships can you think of?

=== Additional Practice

Have students practice describing the stories that graphs tell:

- @opt-printable-exercise{story-graph.adoc}
- @opt-printable-exercise{story-graph2.adoc}
- @opt-printable-exercise{story-graph3.adoc}
- @opt-printable-exercise{story-graph-challenge.adoc}