= What Kind of Model? (Descriptions 2)

Decide whether each situation is best described by a linear, quadratic, or exponential function. +
*If the function is exponential:* @hspace{1em} What is the growth factor? @hspace{1em} Is it doubling (factor of 2)? @hspace{1em} Tripling (factor of 3)? @hspace{1em} Factor of 5? @hspace{1em} 10?

@vspace{1ex}
== High Fives
*Two students started a club. At every meeting, students in attendance must high-five each of the other students. Club membership has been growing steadily by one student each meeting.*

@n Is the function increasing or decreasing? @fitb{10em}{@ifsoln{Increasing}}

@n When the 2 students started the club (x=0), how many high-fives happened? @fitb{8em}{@ifsoln{1}}

@n How many high-fives happen at the subsequent meetings...

[cols="^.>1a,^.>1a,^.>1a,^.>1a", options="header"]
|===
| (3 students) +
x=1
| (4 students) +
x=2
| x=3
| x=4

| @ifsoln{3}
| @ifsoln{6}
| @ifsoln{10}
| @ifsoln{15} 				@ifnotsoln{@vspace{10ex}}
|===

@n What is the *form* of this function?  @hspace{3em}
linear &#9744; @hspace{3em}
@ifsoln-choice{quadratic}@ifnotsoln{&#9744;} @hspace{3em}
exponential&#9744;

@n *If it's exponential*,

@indented{
Fill in the blanks to write a function that shows the how many high-fives happen for a given number of students:

@math{f(x) = } @fitbruby{8em}{}{initial value @math{a}} @math{\times} @fitbruby{8em}{}{growth factor @math{b}} ^x^ @hspace{2em} + @hspace{2em} @fitbruby{8em}{}{horizontal asymptote @math{k}}

@vspace{1ex}

Is it exponential @hspace{2em} _growth_? &#9744;  @hspace{2em} or @hspace{2em} _decay_? &#9744;

}

== Going Viral
*A student posted a video of a dog doing a back flip into a pile of laundry, and the meme went viral! Each person that sees the meme falls in love with it, and shares it with 10 new friends.*

@n Is the function increasing or decreasing? @fitb{10em}{@ifsoln{Increasing}}

@n When the student posts it (x=0), how many total times has it been shared? @fitb{8em}{@ifsoln{1}}

@n How many times will it have been shared after...

[cols="^.>1a,^.>1a,^.>1a,^.>1a", options="header"]
|===
| (the next person shares) +
x=1
| (their friends share) +
x=2
| x=3
| x=4

| @ifsoln{@math{10 + 1 =} +
11}				
| @ifsoln{@math{11 \times 10 + 11 =} +
121}
.>| @ifsoln{1331}
.>| @ifsoln{14641} 			@ifnotsoln{@vspace{10ex}}
|===

@n What is the *form* of this function?  @hspace{3em}
linear &#9744; @hspace{3em} 
quadratic &#9744; @hspace{3em}  
@ifsoln-choice{exponential}@ifnotsoln{&#9744;}

@n *If it's exponential*,

@indented{
Fill in the blanks to write a function that shows how many times the meme has been shared after a given number of "share cycles":

@math{f(x) = } @fitbruby{8em}{@ifsoln{1}}{initial value @math{a}} @math{\times} @fitbruby{8em}{@ifsoln{(1 + 10)}}{growth factor @math{b}} ^x^ @hspace{2em} + @hspace{2em} @fitbruby{8em}{}{horizontal asymptote @math{k}}

@vspace{1ex}

Is it exponential @hspace{2em} @ifsoln-choice{_growth_?}@ifnotsoln{&#9744;}  @hspace{2em} or @hspace{2em} _decay_? &#9744;

}
