= What Kind of Model? (Descriptions)

++++
<style>
/* Push content to the top (instead of the default vertical distribution), which was leaving empty space at the top. */
#content { display: block !important; }
</style>
++++

Decide whether each situation is best described by a linear, {nbsp}quadratic, or exponential function. +
@hspace{1em} *If the function is exponential:* Identify the growth factor and the initial value.

@vspace{1ex}

== Car Values
*A particular kind of car sells for $32,000, and its resale value drops by 12.5% each year.*

@n Is the function increasing or decreasing? @fitb{10em}{@ifsoln{Decreasing}}

@n When the car is brand-new (x=0), how much is it worth? @fitb{8em}{@ifsoln{$32,000}}

@n How much is it worth after... 

[cols="^.>1a,^.>1a,^.>1a,^.>1a", options="header"]
|===
| (1 year) +
x=1
| (2 years) +
x=2
| x=3
| x =4

| @ifsoln{$28,000}
| @ifsoln{$24,500}
| @ifsoln{$21,437.50}
| @ifsoln{$18,757.81} @ifnotsoln{@vspace{10ex}}
|===

@n What is the *form* of this function?  @hspace{3em}
linear &#9744; @hspace{3em}
quadratic &#9744; @hspace{3em}
@ifsoln-choice{exponential}@ifnotsoln{&#9744;}

@n *If it's exponential*,

@indented{
Fill in the blanks to write a function that shows the value of the car after a given number of years:

@math{f(x) = } @fitbruby{8em}{@ifsoln{$32,000}}{initial value @math{a}} @math{\times} @fitbruby{8em}{@ifsoln{(1 - @math{1/8})}}{growth factor @math{b}} ^x^ @hspace{2em} + @hspace{2em} @fitbruby{8em}{}{horizontal asymptote @math{k}}

@vspace{1ex}

Is it exponential @hspace{2em} _growth_? &#9744;  @hspace{2em} or @hspace{2em} @ifsoln-choice{_decay_?} &#9744;

}

== Lemonade Stand
*Sally is selling lemonade, for $1.25 a glass in hopes of finally be able to get the power drill she's been wanting. She starts with $20 cash.*

@n Is the function increasing or decreasing? @fitb{10em}{@ifsoln{Increasing}}

@n When Sally starts the day (x=0), how many dollars does she have? @fitb{8em}{@ifsoln{$20}}

@n How many dollars will she have after...

[cols="^.>1a,^.>1a,^.>1a,^.>1a", options="header"]
|===
| (first sale) +
x=1
| (second sale) +
x=2
| x =3
| x = 4

| @ifsoln{20 + 1.25 = $21.25}
| @ifsoln{$22.50}
| @ifsoln{$23.75}
| @ifsoln{$25.00} 				@ifnotsoln{@vspace{10ex}}
|===

@n What is the *form* of this function?  @hspace{3em}
@ifnotsoln{&#9744;} @ifsoln-choice{linear} @hspace{3em}
&#9744;quadratic  @hspace{3em}
&#9744; exponential

@n *If it's exponential*,

@vspace{1ex}

@indented{
Fill in the blanks to write a function that shows how much Sally has saved after a given number of sales:

@math{f(x) = } @fitbruby{8em}{}{initial value @math{a}} @math{\times} @fitbruby{8em}{}{growth factor @math{b}} ^x^ @hspace{2em} + @hspace{2em} @fitbruby{8em}{}{horizontal asymptote @math{k}}

@vspace{1ex}

Is it exponential @hspace{2em} _growth_? &#9744;  @hspace{2em} or @hspace{2em} _decay_? &#9744;

}
