= Sense Making from Exponential Models: @math{f(x) = a(b)^x + k}

The exponential model we've defined is: @fitb{}{}

It tries to predict @fitbruby{20em}{}{y-variable} from @fitbruby{}{}{x-variable}

Because @math{b =} @fitb{10em}{}, we know that: 

- this model is for exponential @fitbruby{10em}{}{growth / decay} (@math{b} is @fitbruby{10em}{}{bigger / smaller} than 1)
- the @fitbruby{10em}{}{growth / decay} rate is @fitb{10em}{}
- the @fitbruby{10em}{}{growth / decay} factor is @fitb{10em}{}
- every time @fitbruby{15em}{}{x-variable} increases by one, the value of @fitbruby{15em}{}{y-variable} will be @fitbruby{15em}{}{multiplied / divided} by @fitb{}{} 


Because @math{a} is @fitb{8em}{}, each value of @fitbruby{15em}{}{y-variable} for any given @fitbruby{}{}{x-variable} value will be @fitb{3em}{} times @fitbruby{10em}{}{bigger / smaller} than it would be for the same @fitbruby{}{}{x-variable} value in the parent function @math{f(x) = b^x}.

Because @math{k =} @fitb{6em}{}, we know that:

- the model will sit @fitbruby{20em}{}{higher / lower / in the same position} on the graph than the parent model @math{f(x) = a(b)^x}
- the @fitbruby{12em}{}{horizontal / vertical} @vocab{asymptote} of the graph will be at @fitbruby{4em}{}{x / y} @math{=} @fitb{5em}{}
- the @vocab{y-intercept} will be at @math{y =} @fitbruby{10em}{}{@math{a + k}}

== S-value in Context

*This model was built from* data about 
@fitbruby{6em}{}{how many?}
@fitbruby{}{}{what?} +
whose 
@fitbruby{10em}{}{x-variable} ranged from
@fitbruby{10em}{}{x-min} to
@fitbruby{10em}{}{x-max}
@fitbruby{}{}{x-variable units} 

@vspace{1ex}

*Possible limitations of this model* include @fitb{}{}
@fitbruby{62em}{}{uneven distribution, high variability, small sample size, etc.}

@vspace{1ex}

*The error in the model* is described by an @vocab{S-value} of about
@fitbruby{5em}{}{S}
@fitbruby{8em}{}{y-units}. @hspace{1em} I
@fitbruby{18em}{}{strongly agree, agree, disagree, strongly disagree} that this model is a good fit considering that
@fitbruby{10em}{}{y-variable units} in this dataset range from
@fitbruby{10em}{}{lowest y-value} to
@fitbruby{10em}{}{highest y-value}