= Desmos directions

@link-instructions{Open @starter-file{fast-food-desmos}.}

- At the top of the expression panel on the left, you'll see a data table for each of our restaurants
- The table has columns for ID (@math{i}), Price (@math{p}), Fry Quality (@math{f}), and Burger Quality (@math{b})
- The 2-dimensional scatter plot you'll see at first shows the relationship between Price (Z) and Fry Quality (X)
- In-N-Out is represented in green, while the other restaurants are shown in blue

== Price v Fries

@right{@image{images/2-d-comparison-w-lines.png, 400}}

- Turn on the folder "Lines and Angle Calculation". A line will appear, pointing from the origin to the point for In-N-Out.
- Adjust the slider for @math{r_n}, showing the angle @math{θ} between In-N-Out and the other restaurants.
- By drawing rays from each point to the origin, we can measure the angle between them -- just as we did on paper.

@n In our Fries v. Price scatter plot, *which restaurant has the closest __angle similarity__ to In-N-Out*?


TODO:  Add a table where they record the angle measure for each restaurant to in-n-out. 

== Burgers v. Price

We can repeat the same process with our Burger v. Price scatter plot!

@lesson-instruction{
- Click  &#8635;   to reload the Desmos file and retrieve its initial settings.
- Then turn *on* the folder "Burgers v. Price". You'll see red points appear, lined up on the Z axis.
- Turn *off* the folder "Fries v. Price", to make the blue points disappear.
- Click on the "X" label on bottom axis, and slowly drag it to the left.
- This will rotate the 3D space, until you have a "flat" Z-Y plane with red dots on it.
}

TODO:  Add a table where they record the angle measure for each restaurant to in-n-out. 

@n In our Burgers v. Price scatter plot, *which restaurant has the closest __angle similarity__ to In-N-Out*?