= Diagramming Function Composition (2)

++++
<style>
#content .listingblock pre {padding: 0;}
#content .topTable tr:first-child td * { background-color: #f7f7f8; }
table table { border: none !important; }
</style>
++++

[.topTable, cols="1,1,1", stripes="none"]
|===
a|
```
m :: Number -> Number
Consumes a number, divides by 2 to produce the result
```
a|
```
r :: Number -> Number
Consumes a number, subtracts 5 to produce the result
```
a|
```
w :: Number -> Number
Consumes a number, adds 4 to produce the result
```
|
@math{ k(n) = n \div 2}
|
@math{ r(n) = n - 5 }
|
@math{ c(n) = n + 4 }
|===

For each function composition diagrammed below, translate it into the equivalent Circle of Evaluation for Order of Operations. +
Then write expressions for _both_ versions of the Circles of Evaluation, and evaluate them for @math{n = 7}. 

@do{
  (define comp1 '(r (k (c n))))
  (define expr1 '(-  (/ (+ n 4) 2) 5))

  (define comp2 '(c (r (k n))))
  (define expr2 '(+ (- (/ n 2) 5) 4))

  (define comp3 '(c (k (r n))))
  (define expr3 '(+ (/ (- n 5) 2) 4))

  (define comp4 '(k (r (c n))))
  (define expr4 '(/ (- (+ n 4) 5) 2))
}

[.FillVerticalSpace, cols="^.^1,^3,^6,^12a", options="header", stripes="none",frame="none"]
|===

|
| Function Composition
| Order of Operations
| Translate & Evaluate

|     @n
|     @show{(coe comp1)}
|     @showsoln{(coe expr1)}
|
[.FillVerticalSpace, cols=".^3,.^7"]
!===
! Composition: 			    ! @showsoln{(code comp1)}
! Operations: 			    ! @showsoln{(code expr1)}
! Evaluate for n = 7 	  ! @ifsoln{@math{r(k(c(7))) = 0.5}}

!===

|     @n
|     @show{(coe comp2)}
|     @showsoln{(coe expr2) }
|
[.FillVerticalSpace, cols=".^3,.^7"]
!===
! Composition: 			    ! @showsoln{(code comp2) }
! Operations: 			    ! @showsoln{(code expr2) }
! Evaluate for n = 7 	  ! @ifsoln{@math{c(r(k(7))) = 2.5 }}

!===

|     @n
|     @show{(coe comp3)}
|     @showsoln{(coe expr3) }
|
[.FillVerticalSpace, cols=".^3,.^7"]
!===
! Composition: 			    ! @showsoln{(code comp3) }
! Operations: 			    ! @showsoln{(code expr3) }
! Evaluate for n = 7 	  ! @ifsoln{@math{c(k(r(7))) = 5}}

!===

|     @n
|     @show{(coe comp4)}
|     @showsoln{(coe expr4) }
|
[.FillVerticalSpace, cols=".^3,.^7"]
!===
! Composition: 			    ! @showsoln{(code comp4) }
! Operations: 			    ! @showsoln{(code expr4) }
! Evaluate for n = 7 	  ! @ifsoln{@math{k(r(c(7))) = 3}}

!===
|===

