[.beta]
= Measuring Similarity

@description{
Students consider how arbitrary documents (in this case, songs and images) can be represented as points in space, and explore different ways to measure the "distance" between those documents using a spatial representation.
}

@lesson-prereqs{data-driven-algorithms}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives

| Student-facing Lesson Goals
|
- Let's think about ways to represent documents as points in space
- Let's think about how different measures of "distance" between these points can help us find documents that are "similar" to one another

| Materials
|[.materials-links]
@material-links


|===

== Categories, Attributes, and Dimensions

=== Overview

Students explore the idea of _dimensionality_ -- that virtually any category of thing can be defined as having a set of attributes (e.g. - Fast Food chains can be defined by _price_ and _quality_), and any member of that category can be graphed as a point in space (e.g. - plotting fast food restaurants on a _price-quality_ graph).

=== Launch
@slidebreak{LaunchR}
@right{@image{images/burger.jpg, 300}}
Which fast-food restaurant is the best, and why?

@teacher{Give students a minute to discuss}


@slidebreak{Launch}
When evaluating a fast food chain, you might care about a few different attributes (price, quality-of-fries, quality-of-nuggets, convenience, etc). Let's pick three:

[.data-table, cols="^.^1a, 4a, ^4a, ^4a, ^4a", options="header"]]
|===
| ID| Restaurant  | Price (1 = cheap)| Fries (5=best) | Burgers (10=best)
| 1 | McDonalds   | 1.45             | 4.6            | 5
| 2 | Burger King | 1.51             | 4.1            | 6
| 3 | Wendy's     | 1.47             | 4.5            | 7
| 4 | Five Guys   | 2.20             | 3.9            | 8
| 5 | Dairy Queen | 2.11             | 3.7            | 4
| 6 | In-N-Out    | 1.45             | 4.4            | 8
|===

*Pay attention to scale:* Both `Price` and `Fries` are based on a 1-5 scale. For `Price`, 1 is the best possible rating. For `Fries`, 5 is the highest possible rating. `Burger`, however, is based on a 1-10 scale!

(NOTE: These numbers are _totally made up_, and just used for the example!)

@slidebreak{Launch}

For now, let's focus on our attributes for `Price` and `Fries`.

@QandA{
@right{@image{images/price-v-fries-desmos.png, 300}}
Any two attributes define a 2-dimensional space, which we'll call "*Restaurant Space*". We can plot each of our examples in Restaurant Space.

@Q{What do you *Notice* about Restaurant Space?}
@A{Four of the restaurants are clustered around $1.25-$1.50, while the remaining two are much farther away from the group above $2.}
@A{Three of the restaurants all have very similar ratings for french fries, while the others are more spread out.}

@Q{Do you notice any trends or patterns in the data?}
@A{The more expensive places appear to have _worse_ fries!}
}


@slidebreak{Launch}

We can plot a lot of different things this way! For example, here's an example of "Car Space":

[.data-table, cols="^.^1a,4a,^3a,^3a,^3a,^3a", options="header"]
|===
| ID| Car         | HP   | MPG | Top-Speed  | 0-60 (sec)
| 1 | Camry       | 225  | 51  | 115        | 7.0
| 2 | Corvette    | 490  | 19  | 184        | 2.9
| 3 | Mini Cooper | 161  | 32  | 140        | 7.4
| 4 | Prius       | 194  | 57  | 112        | 7.2
| 5 | Cybertruck  | 600  | 79  | 120        | 4.1
|===

We could plot "Teacher Space", with axes for how `Strict` and how `Fair` each teacher is. We could plot "Sneaker Space" with axes for `Comfort` and `Style`. And so on, and so on..

@slidebreak{Launch}
@lesson-instruction{
- Pick a category that _you_ would like to plot!
- Complete the first section on @printable-exercise{plotting-categories.adoc}
}

@teacher{
Walk around the room and facilitate discussion. All the attributes should be quantitative, so be careful to reset students who are creating categorical columns. After a few minutes, have students share their categories, attributes, and ideas for measuring similarity.
}

=== Investigate
@slidebreak{Investigate}
@ifslide{
[.data-table, cols="^.^1a, 4a, ^4a, ^4a, ^4a", options="header"]]
|===
| ID| Restaurant  | Price (1 = cheap)| Fries (5=best) | Burgers (10=best)
| 1 | McDonalds   | 1.45             | 4.6            | 5
| 2 | Burger King | 1.51             | 4.1            | 6
| 3 | Wendy's     | 1.47             | 4.5            | 7
| 4 | Five Guys   | 2.20             | 3.9            | 8
| 5 | Dairy Queen | 2.11             | 3.7            | 4
| 6 | In-N-Out    | 1.45             | 4.4            | 8
|===
}
Suppose you're from California, and In-N-Out is your favorite burger chain! If you're on a road trip East, you'll going to have to settle for one of the other 5 places in our table. Based on this data, which of the other restaurants in our table is _most similar_ to In-N-Out, and why?

@teacher{Make sure you have students explain their thinking!}

@slidebreak{Investigate}

@lesson-instruction{
- Open the @starter-file{ai-fast-food}, and click "Run"
- What is the *table* called in this file?
- What *rows* are defined in this file?
}

@slidebreak{Investigate}
How could we measure the similarity between any the fast-food restaurants in this table? One possible answer is that we check to see if the values are _exactly equal_. We've provided a function that does just that:

@show{(contract "simple-similarity" '("Table" "String" "List<String>") "Table")}

This function _compares every row in the table_ to the Row with the given ID, checking to see if the specified columns are identical. For example:

@show{(code '(simple-similarity fast-food "6" (list "price")))}

@lesson-instruction{
- Try using `simple-similarity` with a variety of different columns
- Try using `simple-similarity` with a variety of different _restaurant IDs_
}

=== Synthesize
@slidebreak{Synthesize}
The `simple-similarity` function is like a spoiled toddler, who will only try a new restaurant if it's _exactly the same_ as In-N-Out.


@QandA{
@Q{Why did we get a 1 for In-N-Out?}
@A{Because In-N-Out is being compared to itself, and it *is* exactly the same!}

@Q{Why did `simple-similarity` using only the `price` column give a 1 for McDonalds, too?}
@A{McDonalds really does have the same `price` as In-N-Out}

@Q{This is definitely an simple way of measuring similarity! But is it a _useful_ way to measure similarity?}
@A{Not at all. We should at least be able to tell the difference between a restaurant that comes close (McDonald's) and a restaurant that's totally different (Outback Steakhouse)}
}

== Other Forms of Similarity

=== Overview
Students explore other forms of similarity, using Euclidean distance and angle measures.

=== Launch
@slidebreak{Launch}
Checking for perfect equality is not a very useful way to look for alternatives! Can we do better?

One option is to just measure the _distance between points_.

If we're just comparing based on Price (just one dimension), that's easy: plot the restaurants' prices on a number line, and find the one that's closest to In-N-Out.
@lesson-instruction{
- Complete the first section on @printable-exercise{distance-similarity.adoc}.
- Is there one clear answer? Why or why not?
}

@slidebreak{Launch}

@QandA{
@Q{When comparing restaurants in 1 dimension, was the "most similar restaurant" to In-N-Out the same for every dimension?}
@A{No - depending on the attribute, it could be Burger King, Five Guys, or Wendy's}

@Q{How can this be?}
@A{We have multiple, *independent* attributes for these restaurants! One restaurant might be the most similar to In-N-Out for fries, while another could be the most similar for price.}
@A{Being similar for one attribute doesn't mean a restaurant is going to be similar for all the others.}

@Q{Could we measure the distance in more than one dimension?}
@A{Yes! We could graph the points and use the distance formula.}
}

@teacher{If your students don't know the distance formula -- or could use a review -- take a look at our lesson on @lesson-link{distance, the distance formula and the Pythagorean Theorem.}}

@lesson-instruction{
- Complete @printable-exercise{distance-similarity.adoc}.
}

@slidebreak{Launch}
Pyret has a function for distance-similarity, too!

@show{(contract "distance-similarity" '("Table" "String" "List<String>") "Table")}

This function _compares every row in the table_ to the Row with the given ID, calculating the distance between the points specified by the columns. For example:

@show{(code '(distance-similarity fast-food "6" (list "price" "fries")))}

@lesson-instruction{
- Try calculating the `distance-similarity` using only the `Fries` column
- Try calculating the `distance-similarity` using `Fries` and `Burgers`
- Try comparing `in-n-out` to _itself_ using all the columns
- Try some other comparisons!
}

@slidebreak{Launch}
Our new `distance-similarity` formula is a huge improvement over `simple-similarity`! Now it's no longer an all-or-nothing situation: if In-N-Out isn't available, we can still find alternatives.

*But is it the _best_ way to measure similarity?* Not necessarily! There are a few problems here, and we'll use one as an example: our distance algorithm doesn't take _scales_ into account.  `fries` and `price` are both scored 1-to-5 and `burgers` are scored 1-to-10. The gap between a score of 9 and 10 for burgers is a larger "distance" than the one between a 4.0 and a 4.5 for fries.

=== Investigate
@slidebreak{InvestigateR}

@QandA{
@right{@image{images/burger-fry-blank.png, 250}}
Some restaurants specialize in burgers, while others are all about the fries.
@Q{Roughly where on the graph would you expect to see all the burger places plotted?}
@A{Top-Left}

@Q{Roughly where on the graph would you expect to see all the fry places plotted?}
@A{Bottom-Right}

@Q{Roughly where on the graph would you expect to see restaurants that are equally good (or bad!) at both?}
@A{Along the diagonal @math{y = x}}
}

@lesson-instruction{
Let's get comfortable working with another form of similarity!
- Complete @printable-exercise{angle-similarity.adoc}
}

@slidebreak{InvestigateR}
This worksheet introduces the idea of _angle similarity_: the angle formed by rays drawn from two points to the origin.

@QandA{
@ifslide{@right{@image{images/burger-fry-blank.png, 250}}}
@Q{In angle similarity, what would be the angle between two identical restaurants?}
@A{0°}

@Q{What is the *least similar* any two restaurants can be?}
@A{90°}
}

Let's experiment with angle similarity in our original dataset.

@slidebreak{Investigate}
--
@right{@image{images/2-d-comparison.png, 300}}

Let's explore another similarity measure using Desmos. Open @online-exercise{https://www.desmos.com/3D/lhqra70cje, Fast Food Ratings}.

- At the top of the expression panel on the left, you'll see a data table for each of our restaurants
- The table has columns for ID (@math{i}), Price (@math{p}), Fry Quality (@math{f}), and Burger Quality (@math{b})
- This 2-dimensional scatter plot shows the relationship between Price (Z) and Fry Quality (X)
- In-N-Out is represented in green, while the other restaurants are shown in blue
- We want to find the blue dot that's "most similar" to the green one
--

@slidebreak{Investigate}

@lesson-instruction{
- Turn on the folder "Lines and Angle Calculation". A line will appear, pointing from the origin to the point for In-N-Out.
- Adjust the slider for @math{r_n}, showing the angle @math{θ} between In-N-Out and the other restaurants.
}

By drawing rays from each point to the origin, we can measure the angle between them -- just as we did on paper. In our Fries v. Price scatter plot, *which restaurant has the closest __angle similarity__ to In-N-Out*?

@slidebreak{Investigate}
We can repeat the same process with our Burger v. Price scatter plot!

@lesson-instruction{
- Refresh the page to reset everything.
- Turn *on* the folder "Burgers v. Price". You'll see red points appear, lined up on the Z axis.
- Click on the "X" label on bottom axis, and slowly drag it to the left.
- Turn *off* the folder "Fries v. Price", to make the blue points disappear.
- This will rotate the 3D space, until you have a "flat" Z-Y plane with red dots on it.
}

In our Burgers v. Price scatter plot, *which restaurant has the closest __angle similarity__ to In-N-Out*?

=== Synthesize
@slidebreak{Synthesize}


== Similarity in Multiple Dimensions

=== Overview
Students take what they've learned about angle similarity, and apply it to the third dimension.

=== Launch
@slidebreak{Launch}

But what if we want to measure similarity, taking into account Price, Fry Quality, _and_ Burger Quality? How can we use all three?

@teacher{Solicit student responses!}

@lesson-instruction{
- Complete the first section on @printable-exercise{fast-food-3-dimensions.adoc}
- Be ready to share your thoughts!
}

@teacher{Give students ample time to share and discuss what's happening at the top of this page. It can be a very challenging, abstract idea to wrap one's head around. This is an excellent time to use visual aids, flashlights, etc. to get the idea across.
}

@slidebreak{Launch}
--
@right{@image{images/projection.webp, 300}}

This image represents a _projection_ of a 3D object into two, 2-dimensional planes. You can see that one shadow looks like a square and the other looks like a circle. Both are showing us a part of the story, and both are correct about the part they show. But the _real_ shape is 3-dimensional (3D).

The same is true for our dataset! Our restaurants are described by 3 different attributes, so our "restaurant space" really has three dimensions! Like the shadows in this image, our two scatter plots are just _projections_ of 3D points onto the Z-X and Z-Y planes.
--

=== Investigate
@slidebreak{Launch}
--
@right{@image{images/3-d-comparison-w-lines.png, 300}}

- Return to open @online-exercise{https://www.desmos.com/3D/lhqra70cje, Fast Food Ratings}
- Refresh the page to start from a clean slate
- *Turn on* "Fries v. Price" and "Fries v. Burgers v. Price".
- Can you rotate the 3D space so the orange points completely cover the blue "Fries v. Price" plot?
- Can you rotate the 3D space so the orange points completely cover the red "Burgers v. Price" plot?
- Now *turn off* the 2d scatter plots ("Fries v. Price" and "Burger v. Price"), leaving only the orange points.
- *Turn on* our "Lines and Angle Calculation"

Even in three dimensions, we can draw our lines and measure the angle distance!
--

@lesson-instruction{
- Complete the remainder of @printable-exercise{fast-food-3-dimensions.adoc}
}

@slidebreak{Investigate}

Of course, Pyret has a function for angle-similarity, too!

@show{(contract "angle-similarity" '("Table" "String" "List<String>") "Table")}

This function _compares every row in the table_ to the Row with the given ID, calculating the angle-similarity between the points specified by the columns. For example:

@show{(code '(angle-similarity fast-food "6" (list "price" "fries" "burgers")))}

@lesson-instruction{
- Try calculating the `angle-similarity` using only the `Fries` column
- Try calculating the `angle-similarity` using all the columns
- Try comparing `in-n-out` to _itself_ using all the columns
- Try some other comparisons!
}

@strategy{Angles?!}{

Yes, angles!

Did you know that geometry is at the heart of modern AI? This lesson shows how. The same angles that your students learn to compute in middle-school are sitting at the heart of the machine learning calculations that power so many things in the world today. Even the plagiarism detectors that might be checking their essays on angles... are computing angles. So if your students ask “When are we ever going to use this?”, you can tell them, “You already do, all the time.”

The plot thickens, especially if you have older students who have learned some trigonometry. In practice, real machine learning systems don't _quite_ use angles. Instead, they use the cosine of the angle. There are two reasons for this:

- The angle itself is a somewhat awkward value to work with. In contrast, the cosine has a nice numeric range, between -1 and 1, which makes it convenient to use in various other mathematical settings. (Specifically, it's used in a process called gradient descent.)

- It’s simpler to compute the cosine directly. In fact, inside Pyret, `angle-similarity` actually computes the cosine _first_, then converts the result into an angle!

For the purposes of this curriculum, you can ignore this difference. In particular, if your students have never even heard of the cosine, that's fine! For students who are familiar with cosine and curious to explore, the @starter-file{plagiarism} contains a `cosine-similarity function`.
}

=== Synthesize
@QandA{
@Q{Which three attributes from _your_ categories would you choose?}

@Q{It's obvious why `angle-similarity` works in two dimensions: you can use a protractor on a piece of paper if you have to! How could you explain why it still works in *three dimensions*?}
@A{All we need is two rays coming from the origin, forming a "V" shape like the bands in a slingshot. No matter how you turn and twist the "V", it will always define a plane on which we can use a protractor.}

@Q{Would the math still work in *four* dimensions? *Five*?}
@A{Let students discuss!}
}
