= Building Periodic Models

@description{Students investigate periodic relationships, first by deciphering the patterns in a dataset with perfect periodic (sinusoidal) behavior and then by looking at data about Carbon Dioxide, using an inquiry-based model involving hypothesizing, experimental and computational modeling, and sense-making. }

@lesson-prereqs{periodic1-exploring-rides}

@keywords{periodic, period, amplitude, frequency}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

- Read and interpret real-world data, presented in a scatter plot
- Recognize periodic behavior in tables and graphs
- Model periodic relationships using functions


| Student-facing Lesson Goals
|

- Let's use Pyret to model periodic relationships in data

| Materials
|[.materials-links]
@material-links

| Preparation
|
@preparation{
- Much of the exploration in this lesson hinges on a custom-built interactive Desmos activity. +
You will want to:
 * Open @starter-file{alg2-exploring-periodic-desmos}.
 * Make a link or code to share with your students.
 * Decide how you will share the link or code with students and, if you are using our Google Slides, add the appropriate link to the slide deck.
 * Set the pacing so that students are only able to interact with the first three slides. _(As the lesson progresses you will be directed to adjust the pacing or sync students to you so that they have access to relevant slides.)_
- _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions-alg2.adoc, _Here's what you need to do._}
}
|===


== Graphing Periodic Functions
@objective{periodic-situations}

=== Overview
Students are introduced to graphs of periodic functions, and they become familiar with the terminology to describe them.

=== Launch
Periodic models for sin and cos relationships have the basic form:

@center{@math{f(x) = a \sin(b(x - h)) + k} @hspace{1em} **OR** @hspace{1em} @math{g(x) = a \cos(b(x - h)) + k}}

Both @math{sin} and @math{cos} are closely related to one another, and each one can be expressed in terms of the other. We're going to investigate @math{sin} for now, but everything you learn will also apply to @math{cos}.

@QandA{
@Q{Many of the models we've studied had a coefficient added at the end of the definition. Thinking back to what you learned, what effect do you think @math{k} has on a periodic model?}
@A{It's the vertical shift - it moves the midline of the graph up and down the y-axis.}

@Q{What effect do you think each of the _other_ coefficients has on the model?}
@A{Some may recognize @math{h} as the horizontal shift, or @math{a} as some kind of multiplier that makes the peaks higher and the valleys lower}
}

=== Investigate

@teacher{Sync or pace students to __Slide 2: Modeling the Ferris Wheel Dataset (sin)__ of @starter-file{alg2-exploring-periodic-desmos}.}

@lesson-instruction{
- Let's return to the *Exploring Periodic Models Desmos file* to experiment with the coefficients of periodic models!
- You should now be on *Slide 2: Modeling the Ferris Wheel Dataset (sin)*.
- Adjust the sliders to fit this data. How close can you get?
- With your partner or group, complete @printable-exercise{graphing-models-a.adoc}, @printable-exercise{graphing-models-b.adoc}, and @printable-exercise{graphing-models-h.adoc}.
}

@teacher{As you debrief, give ample time for students to hear each other's thinking. Concepts like amplitude and frequency can be difficult to describe, and having students reach a consensus on their definition in their own words will help deepen their understanding.}

@slidebreak

=== Synthesize

- TODO

== Talking about Periodic Models

=== Overview
Students dig deeper into the _vocabulary_ for periodic functions, starting with their own words and gradually moving to a more formal understanding. They apply this understanding by returning to the Ferris Wheel problem from @lesson-link{periodic1-exploring-rides}.

=== Launch

Desmos is a great way to get some familiarity with what the various coefficients in a periodic function do. But can you describe what they do, in your own words?

@lesson-instruction{
- Then turn to @printable-exercise{vocab-from-diagram.adoc} and
see if you can come up with explanations for what each of the terms on this diagram refer to.
}

@slidebreak
@ifslide{@right{@image{images/wave-labeled-terms.png, 450}}}
@ifnotslide{@center{@image{images/wave-labeled-terms.png, 450}}}
*Peaks, Valleys and Midline*

When graphed over their period, periodic functions start at the @vocab{midline} and rise to a certain distance (the @vocab{amplitude}) above it. Then they drop to the same distance _below_ the @vocab{midline}, and rise back to it. This cycle then repeats over and over.

- @vocab{Peaks} - the highest points on the wave (also called @vocab{Crests})
- @vocab{Valleys} - the lowest points on the wave
- @vocab{Midline} - a horizontal line that falls halfway between the peaks and the valleys

NOTE: _Since periodic functions rise and fall repeatedly, there isn't a single maxima or minima, but math books sometimes refer to each peak and valley as a "local maxima" or "local minima"_

@slidebreak

==== Amplitude @math{a}

The distance from a peak or valley to the @vocab{midline}. A boat on the ocean will rise and fall according to the @vocab{amplitude} of the waves: high amplitude waves make the boat rise and fall _large distances_.

@slidebreak

==== @math{\text{Period} = 2\pi \over \text{frequency}}

The @vocab{period} is the distance over which the curve travels before it begins to repeat itself (one complete wave).

- It can be measured from peak to peak or from valley to valley.
- The @vocab{frequency} (@math{b}) is _how many cycles_ occur over a @math{2\pi} interval.

[.rideData, cols="^4a,^1a, ^1a", options="header", stripes="none"]
|===
|																			                                    | Period 		  | Frequency
| When @math{b = 1}															                          | @math{2\pi} | 1
| When the @vocab{period} is cut in half, the @vocab{frequency} _doubles_	| @math{\pi} 	| 2
| When the @vocab{period} doubles, the @vocab{frequency} is _cut in half_	| @math{4\pi}	| @math{1/2}
|===

Waves with a short @vocab{period} (high @vocab{frequency}) waves in the ocean make a boat rise and fall at _high speeds_.

@slidebreak

==== Horizontal Shift (@math{h})

In periodic functions, the @vocab{Horizontal Shift} is sometimes called the @vocab{Phase Shift}.

- When @math{h} < 0, it shifts the graph to the left.
- When @math{h} > 0, it shifts the graph to the right.

_Note: In the function definition @math{f(x) = a \sin(b(x - h)) + k}, when h is positive it looks like it's being subtracted._

==== Vertical shift (@math{k})

The vertical shift is the amount the function is shifted up or down
- When @math{k} < 0, the graph is shifted down.
- When @math{k} > 0, the graph is shifted up.


=== Investigate

@lesson-instruction{
- Now that you have a sense for what terms like @vocab{amplitude}, @vocab{frequency}, and @vocab{midline} mean, complete @printable-exercise{matching-periodic-descriptions.adoc} by matching the graphs of periodic functions to their written descriptions.
- What strategies did you use to match the graphs to the descriptions?
}

@slidebreak

@teacher{Sync or pace students to __Slides 2 through 4 of @starter-file{alg2-exploring-periodic-desmos}__.}

@lesson-instruction{
- Let's return to the *Exploring Periodic Models Desmos file*.
- You should still be on *Slide 2: Modeling the Ferris Wheel Dataset (sin)*.
- With your partner, complete @printable-exercise{modeling-ferris-wheel.adoc}, advancing to *Slide 3: Translating from sin to cos* and *Slide 4: Modeling the Ferris Wheel Dataset (cos)*.
}

@slidebreak

@lesson-instruction{
- Open the @starter-file{alg2-ferris-wheel}, and change the definitions of `f` and `g` to match the models defined on @printable-exercise{modeling-ferris-wheel.adoc}. How well do they fit?
}

@teacher{
*NOTE:* The altitude column of the Ferris Wheel dataset has been rounded to make it easier for students to use. This rounding will result in _some_ error in the model.
}

Suppose you needed to compute the model for a _different_ Ferris Wheel. Would you know how to use the radius and speed of the wheel to compute the model?

@lesson-instruction{
- Complete @printable-exercise{make-a-wheel.adoc} with your partner.
}

=== Synthesize
Periodic relationships involve repeating cycles. Like our Ferris wheel, they rise and fall along regular intervals. Can you come up with some examples of periodic relationships?

@teacher{
This can be a terrific out-of-seats activity:

- Have groups of students go to whiteboards/flipcharts, and write down their periodic relationship (e.g. - phases of the moon, tides, etc).
- Ask them what the period is, then the x-axis, then the y-axis. For example, phases of the moon has a period of roughly 1 month, so the x-axis might be days. For the y-axis, we could use "Percent of visible moon" or "number of lumens".
- Under that description, have them draw axes and their wave!
}

For each one:

- Can you estimate the _period_ of the relationship?
- Can you estimate the _amplitude?_
- Can you estimate the _midline_ and _vertical shift?_

@teacher{
You'll likely need to support students in thinking through what these terms mean in the context of their first example, to get the class started. Suppose a student volunteers "the temperature, because it gets cold in the winter and warm in the summer":

- The seasons change over the course of one year, so the period would be 365 days.
- The temperature in your area might fluctuate between 95° in the summer and 25° F in the winter. That's a range of 70° F, for an amplitude of 35° F.
- The @vocab{midline} and the vertical shift are at 60° F (25 + 35 = 60).
}
