(
 "VisualizingShapeOfData.pdf"
 "DesignRecipe.pdf"
 "SummarizingColumns.pdf"
 "ReadingHistograms.pdf"
 "MakingHistograms.pdf"
 "ShapeOfAnimalsDataset.pdf"
 "ShapeOfMyDataset.pdf"
 "WhatsOnYourMind.pdf"
 )
