= What can we Learn from Names?

++++
<style>
#content .forceShading { background-color: #f7f7f8; }
</style>
++++

The settlers named places after where they had lived before or people who owned parts of the land.

- “New York” is named after the town of York in England. 
- The neighborhood of “Stuyvesant” was named for Peter Stuyvesant, an early governor of the colony.  

The Native Americans, however, named land based on how they used it. 

- Some language experts say “Manhattan” meant “place to get timber for bows and arrows.” Others say the word meant “island,” “island of many hills,” or “place of general drunkenness.” 

Read this explanation of place names based on the book Changes in the Land: Native Americans, Colonists, and the Ecology of New England by William Cronon (pp 65-66): 

[.forceShading]
--
Abessah in Maine was the ‘clam bake place.’ Wabaquasset in Rhode Island was where Native American women could find ‘sticks for making mats.’ These names turned the landscape into a map which gave Native Americans important information to find the food they needed. Place-names were used to keep track of beaver dams, the rapids in rivers, oyster banks, egg-gathering spots, cranberry bogs, canoe-repairing places, and so on. 

Hammonasset Beach in Connecticut was named by Native Americans to describe their use of that land for farming: It means “where we dig holes in the ground.” Most Native American names, like the ones mentioned above, describe how the land could be used. A few of their names were about who could use the land. The name of Lake Chabunagungamaug in Massachusetts means “boundary fishing place.”
--


_Invent three descriptive names for places near your school, just as the Native Americans used to do. See if classmates or your teacher know exactly where you mean._ 

- Example: Place to Get Empanadas Near School
- Example: Street Where Kids Play Soccer on Saturdays

@n @fitb{}{}

@n @fitb{}{}

@n @fitb{}{}
