= Looking for Patterns
++++
<style>
#preamble_disabled { flex-grow: 0 !important; }
table { margin: 0 !important; }

/* Shrink vertical space for fitb */
.fitbruby{ padding-top: 1.1rem; }

.sketches .autonum { position: absolute; }
</style>
++++

@link-instructions{
Open the @starter-file{alg2-states}.
}

[cols="1a,1a", options="header", stripes="none", frame="none"]
|===
2+| What columns do you think might have a relationship? +
(_e.g. is the number of veterans related to the land-area? Is the population in 2010 related to the population in 2020?_)

| @n I think that @fitb{}{} +
might be related to @fitb{}{} +
because @fitb{}{} +
@fitb{}{}
| @n I think that @fitb{}{} +
might be related to @fitb{}{} +
because @fitb{}{} +
@fitb{}{}

|===

[cols="1a", options="header", stripes="none", frame="none"]
|===
| What do you predict the relationships will look like? (_e.g. Negative? Positive? Curves?_)
| Label the axes on the graphs below with your variables from 1 and 2. Then sketch how you imagine they might be related.
|===

[.sketches, cols="1a,1a", stripes="none", frame="none"]
|===
|@n @center{
	@image{../images/blank-first-quadrant.png, 175} +
	@vspace{1ex} +
	How confident are you in your prediction? +
_not at all_ @hspace{1em} _somewhat_ @hspace{1em} _very_
}
|@n @center{
	@image{../images/blank-first-quadrant.png, 175} +
	@vspace{1ex} +
	How confident are you in your prediction? +
_not at all_ @hspace{1em} _somewhat_ @hspace{1em} _very_
}
|===

@center{@show{(contract 'scatter-plot '("Table" (labels String) (explanatory String) (response String)) "Image")}}

[cols="1a,1a", options="header", stripes="none", frame="none"]
|===
2+| Use the Contract above to make a scatter plot for each relationship. +
_(Use `"state"` as the label, so that clicking on a point will show you which state you're looking at.)_

2+| If there's a pattern, describe it so that someone else could sketch it. What does it mean? If there isn't a pattern, what does _that_ mean?
  | @n @fitb{}{} +
       @fitb{}{}
  | @n @fitb{}{} +
       @fitb{}{}
|===

== More Relationships

Pyret allows us to generate many scatter plots, quite quickly! Take advantage of that to identify two relationships that appear to be strong. _Hint: If you're working in the Interactions Area of Pyret, you can hit the up arrow to bring back previously used lines of code._

@n There appears to be a @fitbruby{9em}{}{negative / positive / no} relationship between @fitbruby{14em}{}{explanatory variable (x-axis)} and @fitbruby{14em}{}{response variable (y-axis)}.

@n There appears to be a @fitbruby{9em}{}{negative / positive / no} relationship between @fitbruby{14em}{}{explanatory variable (x-axis)} and @fitbruby{14em}{}{response variable (y-axis)}.

@star What have you learned about our state and the others we decided to focus on?
