= Analyzing Trade Regions

@n Make a copy of @online-exercise{{https://docs.google.com/spreadsheets/d/1Kw9WA5aTzUcKUmtWldfZqhHBXKbOzBsURRXHExANPzY/edit?usp=sharing, Shipwreck Trade Region Data}.

@n Follow the directions in the file to create a pie chart of the data. 

Read off the chart to answer the following questions:

@n Which regions traded the most?

@fitb{}{}

@fitb{}{}

@n Which region was involved in more of the routes: the Netherlands or India?

@fitb{}{}

@vspace{1ex}

Knowing what the ships carried tells us what people wanted to buy and sell. It doesn’t tell us why those items were valuable. 

In the table below, you'll see several items from the cards. Complete the table by choosing a reason why people might have wanted the items from the list below (multiple items may have the same reason) and indicating where your evidence comes from (a card, general knowledge, etc.). 

[cols="1a,2a,2a"]
|===
|Item 			| Why People Wanted It 	| Evidence
|Ceramic jars	|						|
|Spices			|						|
|Tea 			|						|
|Silk			|						|
|Ceramic statues|						|
|===

Options for why people wanted the items:
* popular drink
* useful for clothing
* beautiful
* useful as medicine
* useful as containers

