= Collision Detection

@lesson-description{Students use function composition and the distance formula to detect when characters in their games collide.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-piecewise-functions}

| Lesson Goals
|Students will be able to:

* Explain how the distance formula is related to the Pythagorean theorem.
* Write a function for the distance formula.

| Student-Facing Lesson Goals
|
* I can explain how the distance formula is connected to the Pythagorean theorem.
* I can write a function that takes in 2 points and returns the distance between them.

| Materials
|

@ifproglang{wescheme}{
* Lesson slides template (@link{https://docs.google.com/presentation/d/1INT8koAGQcpUelRzGpvThViGSAVMdZYT08LHgqnQAzg/edit?usp=sharing, Google Slides})
* Sample game file - no distance lines (@link{https://www.wescheme.org/view?publicId=PJMfrSvGRl, WeScheme)}
* Sample game file - with distance lines (@link{https://www.wescheme.org/view?publicId=0bCivugY3P, WeScheme)}
}

@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1WVWq3JVFlq8OgpLGIUFQ9mR7DbADkgMxR8NYPhuPQN4/edit?usp=sharing, Lesson slides} (Google Slides)
* Sample game file - no distance lines (@link{https://code.pyret.org/editor#share=1g_3AqB4v6Jtq6TzcIHYNTkvlW9B6dLHS&v=882d33a, Pyret)}
* Sample game file - with distance lines (@link{https://code.pyret.org/editor#share=1y1eWn1YyDDqilj0MFqEpMy4egVh-G81W&v=882d33a, Pyret})
}
* @exercise-link{pages/Distance-Multiple-Representations.pdf, Multiple Representations} (PDF)

@ifproglang{wescheme}{
* Design Recipe: collide? (@workbook-link{pages/collide.adoc, original})
}
@ifproglang{pyret}{
* Design Recipe: is-collision (@workbook-link{pages/collide.adoc, original})
}

| Supplemental Resources
|
- Absolute Value (@link{https://teacher.desmos.com/activitybuilder/custom/58efa58b999d890619a5663e, Desmos })
- Absolute Value Inequality Illustrator (@link{https://www.geogebra.org/m/rq7uDucY, Geogebra })
- Absolute Value (@link{https://quizizz.com/admin/quiz/581c92bd3fa551e37a438264/absolute-value-preview, Quizizz })
- Distance Formula (@link{https://www.geogebra.org/m/DTeGM5U7, Geogebra })
- Distance Formula (@link{https://quizizz.com/admin/quiz/5876366405dad51d02b1beef/distance-formula, Quizizz })
- Pythagorean Theorem (@link{https://quizizz.com/admin/quiz/5828a9f82627ff7d77818381/pythagorean-theorem, Quizizz})
- Pythagorean Theorem (@link{https://www.geogebra.org/m/jFFERBdd#material/ZFTGX57r, Geogebra })

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Key Points for the Facilitator
|
* The distance formula is an excellent review of @vocab{Circles of Evaluation}. Have students work out the expression in small groups to foster discussion.

|===

== Warmup

Students should have their workbook, pencil, and be logged into
@ifproglang{wescheme}{ @link{https://www.wescheme.org, WeScheme     } }
@ifproglang{pyret}{    @link{https://code.pyret.org, code.pyret.org } }
on their computer.

== Collision Detection @duration{20 minutes}

=== Overview
Students once again see function composition at work, as they compose a simple inequality with the `distance` function they've created.

=== Launch
Knowing how far apart our characters are is the first step. We still need the computer to be asking: "True or False: is there a collision?"

=== Investigate
Using
@ifproglang{wescheme}{ @workbook-link{pages/collide.adoc, Design Recipe: collision?}, }
@ifproglang{pyret}{ @workbook-link{pages/collide.adoc, Design Recipe: is-collision}, }
have students write a function that takes in two coordinate pairs (four numbers) of two characters (x1, y1) and (x2, y2) and returns a @vocab{Boolean} as to whether or not the two characters have gotten within 50 @vocab{pixels} of each other.

=== Synthesize
- Explicitly point out that this function is easy to write because we can _re-use_ the distance function. 
- Connect this back to `profit`, `revenue`, `cost` and `onscreen` from previous lessons. Function composition is powerful!

== Additional Exercises: