= Absolute Value and Opposite

@description{Students use Circles of Evaluation to explore the effect of negation and absolute value on arithmetic and algebraic expressions.}

@lesson-prereqs{variables}

@keywords{Opposite, Absolute Value}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

@objectives
@objective{Define absolute value as a number's distance from zero on the number line.}
@objective{Recognize that two numbers are referred to as 'opposites' if they are the same distance from zero.}
@objective{Use Circles of Evaluation to analyze expressions with opposite and absolute value.}

| Student-facing Lesson Goals
|

* Let's use Circles of Evaluation to think about opposites.
* Let's use Circles of Evaluation to think about absolute value.


| Materials
|[.materials-links]
@material-links

| Preparation
|
@preparation{
* Draw or project a number line of the integers from -10 to 10. This will be the focal point of a lot of the conversation for today's lesson. 
}

| Key Points For The Facilitator
|
* The difference between absolute value and opposite can be subtle and confusing for students. Sometimes, given an input, they produce the same output - but at other times, their outputs differ.
|===

== Finding Opposites

=== Overview

Students are introduced to `negate`. Using this function, they create and evaluate Circles of Evaluation to explore the notion of @vocab{opposites}.


=== Launch
@slidebreak{Launch}

@teacher{Instruct students to draw a number line that spans from @math{-10} to @math{10}, or draw/project one at the front of the room.}

@QandA{
@Q{What number is the same distance from zero as @math{8}?}
@A{@math{-8}}
@Q{What number is the same distance from zero as @math{-3}?}
@A{@math{3}}
}

The pairs of numbers we've just identified are called @vocab{opposites} - two numbers that are the same distance from zero on the number line, with one negative and one positive.

@QandA{
@Q{What are some other pairs of opposites that you can identify?}
@A{Possible responses: @math{6.5} and @math{-6.5}; @math{4} and @math{-4}; @math{\frac {7}{3}} and @math{- \frac {7}{3}}.}
}

=== Investigate
@slidebreak{Investigate}

Operators always have two inputs and, in standard mathematical notation, they always go in the middle of their inputs. You've created a lot of Circles of Evaluation with operators at the top.

But what if we want to do something to just _one_ number? On which side does the operator go? Or what if we want to do something to _more than two_ numbers? Forcing the "verb" to always be in the middle really limits what we can do!

@slidebreak{Investigate}

@vocab{Functions} are very similar to operators... except that functions can have _any number_ of inputs!  If you've completed any of the programming explorations so far, then you are familiar with a wide variety of functions: `scale`, `rotate`, `beside`, etc.

Math has functions too, and they work the same way!

@slidebreak{Investigate}

Incorporating @vocab{functions} into our Circles of Evaluation makes them more powerful! With functions, we can diagram and interpret expressions that include opposites, absolute value, exponents, square roots, Booleans... the list goes on.

We can even _define our own functions_. This allows us to tell the computer to do whatever we want, and maybe even get the computer to do the same thing over and over again but with different inputs!

@teacher{Students learn to define functions in @proglang in our Algebra curriculum, during @lesson-link{functions-make-life-easier}.}

@slidebreak{Investigate}

The function used to represent "the opposite" is called `negate`. When we use `negate`, we include just one argument inside the Circle.

@slidebreak{InvestigateR}

@QandA{
@show{(coe '(negate 2))}
@Q{What does this Circle of Evaluation evaluate to?}
@A{The Circle evaluates to @math{-2}.}
}


@slidebreak{InvestigateR}

@QandA{
@show{(coe '(negate (negate 2)))}
@Q{What happens if we nest a negating Circle of Evaluation _inside of_ another negating Circle, like in the above Circle?}
@A{The opposite of the opposite of a number is the number itself, so it evaluates to @math{2}.}
}


@slidebreak{Investigate}

@QandA{
@Q{What do each of these Circles evaluate to?}
@A{@math{5}, @math{-5}, @math{5}, @math{-5}, and @math{5}}


[cols="^.^1,^.^1,^.^1,^.^1,^.^1", grid="none", stripes="none" frame="none"]
|===

| @show{(coe  '(negate -5))}

| @show{(coe  '(negate (negate -5)))}

| @show{(coe '(negate (negate 5)))}

| @show{(coe '(negate (negate (negate 5))))}

| @show{(coe '(negate (negate (negate -5))))}

|===

}

@slidebreak{Investigate}

@lesson-instruction{
- Practice applying `negate` on @printable-exercise{true-or-false-negate.adoc}. Evaluate each side of the @vocab{equation} to confirm if it is true or false.
- On @printable-exercise{true-or-false-negate-2.adoc}, explore Circles of Evaluation with @vocab{Variables}, and review previously explored properties (Identity, Commutative, Associative, and Distributive).
}

@slidebreak{Investigate}

When we want to show negation of a number or an expression, we just use a negative sign! So, while we can read @math{-45} by simply saying "negative 45," another way to read that value's name is by saying, "the opposite of 45."

Similarly, @math{-(x + m)} can be translated as "the opposite of the sum of @math{x} and @math{m}."

@strategy{Pedagogy Note: Can we call it "minus 45"?!}{
Precise language is crucial when dealing with this symbol: `-`.

In math we want students to read for _comprehension_, not just mechanically sounding out each symbol in order. We read the @vocab{arithmetic expression} @math{12 - 9} as "12 minus 9" _because subtraction is the "verb"_, not because the minus sign happens to be in the middle!

When we encounter a value such as @math{-20}, however, it is confusing and misleading to name that value "minus 5." Subtraction is not happening here - negation is! But if the teacher uses the "symbols in order" wording, it reinforces the lower level of reading comprehension for students.
}



=== Synthesize
@slidebreak{Synthesize}

@QandA{

@Q{Two opposites are 8 units apart from each other. What are they? Explain.}
@A{@math{4} and @math{-4}}

@Q{Two opposites are 42.5 units apart from each other. What are they? Explain.}
@A{@math{21.5} and @math{-21.5}}

@Q{Cia says that opposites are always negative. Are they right? Why?}
@A{No, opposites are not always negative. Positive numbers always have negative opposites - but negative numbers have positive opposites!}

@Q{We have learned that opposites are two numbers that are the same distance from zero on the number line, with one negative and one positive. Knowing this, what do you think is the opposite of zero?}
@A{Zero is its own opposite!}
}

== Absolute Value

=== Overview

Students consider the meaning of @vocab{absolute value}, and apply the concept to Circles of Evaluation using `abs`.

=== Launch
@slidebreak{Launch}

@lesson-instruction{
What is the distance between these two points on the number line: @math{-8} and @math{5}?
}

@teacher{Give students a minute to contemplate, and then invite them to verbally share their strategies. Record students' thinking on the board, annotating the number line. All strategies are welcome, with a special interest in any discussion that hones in on the idea of _the distance of a number from zero._}

We have a term for _the distance of a number from zero_ - it's @vocab{absolute value}.

@lesson-point{
Absolute value is the (positive) distance of a number from zero.
}

@slidebreak{Launch}

We annotate absolute value like this: @math{|x|}, with @math{x} being any given number. When we encounter an expression like @math{|x|}, we say "the absolute value of @math{x}."

Because _opposites_ are the same distance away from zero, they will always have the same absolute value. So, @math{|4| = 4} and @math{|-4| = 4}.


=== Investigate
@slidebreak{Investigate}

The @vocab{function} that we will use to represent absolute value is @show{(code 'abs)}. It can be used like any other operator that we put at the top of a Circle of Evaluation. As with `negate`, when we use @show{(code 'abs)}, we include just one argument inside the Circle of Evaluation.

@slidebreak{Investigate}

@QandA{
@Q{Let's try evaluating some Circles of Evaluation with `abs`! What does each of these Circles evaluate to?}
@A{@math{20}, @math{20}, @math{43}, @math{43}, @math{43}}

[cols="^.^1,^.^1,^.^1,^.^1,^.^1", grid="none", stripes="none", frame="none"]
|===
| @show{(coe  '(abs -20))}
| @show{(coe  '(abs 20))}
| @show{(coe '(abs (abs 43)))}
| @show{(coe  '(abs 43))}
| @show{(coe  '(abs -43))}
|===

}


@slidebreak{Investigate}

@lesson-instruction{
- On @printable-exercise{true-or-false-abs-val.adoc}, compare expressions with `abs` to expressions with `negate`
- On the bottom half of the page, determine whether variable equations featuring `negate` and `abs` are always, sometimes, or never true. Be sure to explain your response.
- Complete @printable-exercise{wodb-abs-val-negate.adoc}. Cross out any Circle of Evaluation that does *not* meet the condition stated on the left.
}


=== Synthesize
@slidebreak{Synthesize}

Think about the @vocab{algebraic expressions} @math{|h|} and @math{-h}.

@QandA{
@Q{What do we know about the outcomes of each of these expressions?}
@A{@math{|h|} is always positive or zero, while @math{-h} can be negative, zero, or positive.}

@Q{When do they produce the same outcome?}
@A{@math{-h} is positive when @math{h} is negative, and @math{-h} is negative when @math{h} is positive. As a result, @math{|h|} and @math{-h} produce the same outcome only when @math{h} is negative or zero.}

@Q{When do they produce different outcomes?}
@A{@math{|h|} and @math{-h} produce different outcomes when @math{h} is positive.}
}

== Programming Exploration: Rotations

=== Overview

Students explore with the `rotate` function to apply what they have learned about absolute value and negation.

=== Launch
@slidebreak{Launch-DN}

Today, we're going to think deeply about the `rotate` function in @proglang. In particular, what angles of rotation represent clockwise turns? Counter-clockwise? What does it mean to _reverse_ a rotation, and how can we represent such a reversal in @proglang?

@lesson-instruction{
- Open the @starter-file{negation}.
- Complete the first table on @printable-exercise{explore-rotate.adoc} by making a prediction for each Circle of Evaluation and then testing the code in @proglang.
- When you are done, write a few sentences summarizing what you observed.
}

@teacher{The opening table of the worksheet is a basic review of geometric rotations. For students who are unfamiliar with the concept of a 90-degree turn, a 180-degree half-turn, or a full 360-degree turn, this will be a necessary review. Feel free to spend as much time as needed reinforcing these concepts.}

@slidebreak{Launch}

You just explored angles of rotation. Let's review what you've learned.

@QandA{

@Q{What degree of rotation do we use to spin the image in a full circle, back to its starting point?}
@A{360}

@Q{Describe what a 180-degree turn looks like.}
@A{A 90-degree turn is a quarter turn, that rotates any image perpendicular to its starting position.}

@Q{Think about each of the rotations you just explored. Were the angles of rotation positive or negative? Were the turns clockwise or counter-clockwise?}
@A{The angles of rotation in the first table are positive and the turns were all counter-clockwise.}
}


=== Investigate
@slidebreak{Investigate}

@lesson-instruction{
- Complete the second table on @printable-exercise{explore-rotate.adoc}, making a prediction for each Circle of Evaluation and then testing the code in @proglang.
- When you're done, streamline the complicated code so that it produces an identical output without using `negate` or @show{(code 'abs)}.
}

@teacher{Referring to the first table on the page can be a helpful scaffold for students who are struggling.}


=== Synthesize
@slidebreak{Synthesize}

@QandA{

@Q{Rotating an image 45 degrees produces a different output than rotating an image -45 degrees. Rotating an image 180 degrees, however, produces the _same_ output as rotating that image -180 degrees. Explain why.}
@A{180 degrees is exactly half of one full rotation, so no matter which direction we rotate, we end up in the same position.}

@Q{Can you think of any other pairs of opposite angles of rotation that would produce an identical output?}
@A{540, 900, 1260...}
}
