= Reading Row and Function Definitions

++++
<style>
#content p { margin: 0; }
.paragraph { min-height: 0.33in; }
th { text-align: center !important; }
td .editbox { font-size: 0.75rem; }
td { padding: 0.5rem 0 !important; }
th { display: block !important; }
</style>
++++

Make sure you've opened the @starter-file{table-methods} on your computer.


@n What name is being defined on line 8?  @fitb{}{@ifsoln{animals-table}}

@n How many columns are listed?           @fitb{}{@ifsoln{8}}

@n What name is being defined on line 15? @fitb{}{@ifsoln{cat-row}}

@n Is `cat-row` a Number, String, Image or Row?   @fitb{}{@ifsoln{Row}}

@n Type `cat-row` into the Interactions Area. What do you get? @fitb{}{@ifsoln{the row for "Sasha"}}

@n A Contract for a function is written on line 32. What is its name? @fitb{}{@ifsoln{is-dog}}

@n What is its Domain?  @fitb{}{@ifsoln{Row}}

@n What is its Range? @fitb{}{@ifsoln{Boolean}}

@n All 3 of the examples on lines 38-40 do the same thing, at different levels of abstraction.  Think about what each example is doing and write a similar example using `dog-row`

[cols='1,1', options="header"]
|===
| Examples with `cat-row`
| Similar examples with `dog-row`

| `is-dog(cat-row) is false`
| @ifsoln{`is-dog(dog-row) is true`}
2+| __What is this example doing?__

| `is-dog(cat-row) is "cat" == "dog"`
| @ifsoln{`is-dog(dog-row) is "dog" == "dog"`}
2+| __What is this example doing?__

| `is-dog(cat-row) is cat-row["species"] == "dog"`
| @ifsoln{`is-dog(dog-row) is dog-row["species"] == "dog"`}
2+| __What is this example doing?__
|===

@n What other functions are defined here? @fitb{}{@ifsoln{_ `is-old`, `lookup-name`, `lookup-fixed`, etc_}}

@n Evaluate `is-dog(dog-row)`. What do you get? @fitb{}{@ifsoln{`true`}}

@n Evaluate `is-dog(cat-row)`. What do you get? @fitb{}{@ifsoln{`false`}}

@n What does `is-old` do? @fitb{}{@ifsoln{Looks up the age of the row, and asks if it is greater than 10}}

@n What does `lookup-name` do? @fitb{}{@ifsoln{looks up the value in the `name` column}}

@n What does `lookup-fixed` do? @fitb{}{@ifsoln{looks up the value in the `fixed` column}}

@n What does `label` do? @fitb{}{@ifsoln{prints the animal's name in red}}

@n What does `kilos` do? @fitb{}{@ifsoln{divides the pounds by 2.2}}
