= Reading Row and Function Definitions

++++
<style>
#content p { margin: 0; }
.paragraph { min-height: 0.33in; }
th { text-align: center !important; }
td .editbox { font-size: 0.75rem; }
td { padding: 0.5rem 0 !important; }
</style>
++++

Make sure you've opened the @starter-file{table-methods} on your computer.


@n What name is being defined on line 7?  @fitb{}{@ifsoln{_animals-table_}}

@n How many columns are listed?           @fitb{}{@ifsoln{_8_}}

@n What name is being defined on line 13? @fitb{}{@ifsoln{_cat-row_}}

@n Is `cat-row` a Number, String, Image or Row?   @fitb{}{@ifsoln{_Row_}}

@n Type `cat-row` into the Interactions Area. What do you get? @fitb{}{@ifsoln{_the row for "Sasha"_}}

@n On line 16, define `dog-row`. After clicking "Run", type `dog-row` into the Interactions Area to make sure it's a dog, do the same for `old-row` and `unfixed-row`.

@n A Contract for a function is written on line 24. What is its name? @fitb{}{@ifsoln{_is-dog_}}

@n What is its Domain?  @fitb{}{@ifsoln{_Row_}}

@n What is its Range? @fitb{}{@ifsoln{_Boolean_}}

@n All 3 of the examples on lines 28-32 achieve the same thing, at different levels of abstraction.  Think about what each example is doing and write a similar example using `dog-row`

[cols='1,1', options="header"]
|===
| Examples with `cat-row`
| Similar example with `dog-row`

| `is-dog(cat-row) is false`
| @ifsoln{`is-dog(dog-row) is true`}
2+| __What is this example doing?__

| `is-dog(cat-row) is "cat" == "dog"`
| @ifsoln{`is-dog(dog-row) is "dog" == "dog"`}
2+| __What is this example doing?__

| `is-dog(cat-row) is cat-row["species"] == "dog"`
| @ifsoln{`is-dog(dog-row) is dog-row["species"] == "dog"`}
2+| __What is this example doing?__
|===

@n What other functions are defined here? @fitb{}{@ifsoln{__ `is-old`, `lookup-name`, `lookup-fixed`, etc__}}

@n Evaluate `is-dog(dog-row)`. What do you get? @fitb{}{@ifsoln{`true`}}

@n Evaluate `is-dog(cat-row)`. What do you get? @fitb{}{@ifsoln{`false`}}

@n What does `is-old` do? @fitb{}{@ifsoln{_Looks up the age of the row, and asks if it is greater than 10_}}

@n What does `lookup-name` do? @fitb{}{@ifsoln{_looks up the value in the `name` column_}}

@n What does `lookup-fixed` do? @fitb{}{@ifsoln{_looks up the value in the `fixed` column_}}

@n What does `label` do? @fitb{}{@ifsoln{_prints the animal's name in red_}}

@n What does `kilos` do? @fitb{}{@ifsoln{_divides the pounds by 2.2_}}
