= Solving Word Problems

Being able to see functions as Contracts, Examples or Definitions is like having three powerful tools. These representations can be used together to solve word problems!

@vspace{1ex}

@n When reading a word problem, the first step is to figure out the  *Contract* for the function you want to build. Remember, a Contract must include the Name, Domain and Range for the function!

@vspace{1ex}

@n Then we write a *Purpose Statement*, which is a short note that tells us what the function _should do_. Professional programmers work hard to write good purpose statements, so that other people can understand the code they wrote!

@vspace{1ex}

@n Next, we write at least two  *Examples*. These are lines of code that show what the function should do for a _specific_ input. Once we see examples of at least two inputs, we can _find a pattern_ and see which parts are changing and which parts aren't.

@vspace{1ex}

@n To finish the Examples, we circle the parts that are changing, and label them with a short *variable name* that explains what they do.

@vspace{1ex}

@n Finally, we define the function itself! This is pretty easy after you have some examples to work from: we copy everything that didn't change, and replace the changeable stuff with the variable name!
