= Booleans and Filters (2)

++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
/* Cram everything to the top instead of distributing space equally */
#content { display: block !important; }
</style>
++++

== Booleans and Numbers

In the @starter-file{boolean}, open the Transformer called `filter-is-???`, pictured below. For each prompt below, you will select "Edit" in the Transformer, and then enter the specified Boolean expression. (Relevant boxes are highlighted in red in the image on the right.)

[cols="4, 10", frame="none", grid="none", stripes="none"]
|===


|
@image{../images/filter-is-blank.png, 300}

|

@n Click Edit. Change `Pounds=` so that it says `Pounds=32`. What happened? @fitb{}{}

@fitb{}{}

@vspace{1ex}

@n What would be a good *name* for a Transformer with the expression `Pounds<32`?

@fitb{}{}

@vspace{1ex}


@n What would be a good Purpose Statement for a Transformer with the expression `Pounds<32`? @fitb{}{}

|===

@n With your partner, test out each of the Booleans listed below, using *`Pounds` @fitb{1em}{} `32`* as the Transformer's expression.

- What happens if you put @math{=} in the blank? @fitb{}{}

- What happens if you put @math{>=} in the blank? @fitb{}{}

- What happens if you put @math{>=} in the blank? @fitb{}{}

- What happens if you put @math{!=} in the blank? @fitb{}{}

@vspace{1ex}

== Booleans and Strings

@n Click Edit. This time, type `Name>"Maple"` in the expression box. What happened? @fitb{}{}

@fitb{}{}

@vspace{1ex}

@n What do you predict will happen if you edit the expression so that it says `Name<="Maple"`? @fitb{}{}

@fitb{}{}

@n Try it out. Where you correct? @fitb{}{}

@n With your partner, test out each of the Booleans listed below, using `Name` @fitb{1em}{} `Maple` as the expression.

- What happens if you put `=` in the blank? @fitb{}{}

- What happens if you put `>=` in the blank? @fitb{}{}

- What happens if you put `>=` in the blank? @fitb{}{}

- What happens if you put `!=` in the blank? @fitb{}{}

@n Edit the Transformer's expression so that it says: `beginsWith(Name, "Sn")`. What happened? @fitb{}{}

@fitb{}{}

@n Now try this expression: `beginsWith(Name, "sn")`. What happened? Did you get the result you expected? @fitb{}{}

@fitb{}{}

@star Go back to @printable-exercise{booleans-with-filter.adoc} and use a different color pen to correct any questions (4-15) that you got wrong.
