= Materials for Teachers using Connected Mathematics (Grade 7)

++++
<style>
/* stuff we want to hide */
#footer, .acknowledgment, #savetodrive-div { display: none !important; }

body {
	margin: auto;
	color: 	black !important;
	width:	7.5in;
	height:	10in;
	-webkit-print-color-adjust: exact;
}

#header, #header *, h1 { background: none !important; color: black !important; }
h1, h2, .footer { font-size: 12pt; margin: 0px 6px; text-align: center !important; }
h1:before {
	content: url('../../images/Logo with Text.png');
 	display: block;
}
.ulist p, em, strong, #content { padding: 0 !important; margin: 0 !important; }
.funders { border: solid gray; border-width: 1px 0; margin: 10px 0; }

/* Table formatting */
table {
	order-collapse: separate;
	border-spacing: 2px 5px;
	border: none !important;
	margin-bottom: 1.75in;
	page-break-before: avoid;
}
tr th.tableblock, p { font-size: 1rem !important; margin: 0; }
tr th.tableblock { background: rgb(182, 215, 168); padding: 2px; }
table tr:nth-child(1) { background: rgb(207, 226, 243); }
table tr:nth-child(2) { background: rgb(255, 242, 204); }
table tr:nth-child(3) { background: rgb(249, 203, 156); }
table tr:nth-child(4) { background: rgb(226, 195, 242); }
table tr:nth-child(5) { background: rgb(242, 195, 195); }
table tr:nth-child(6) { background: rgb(168, 228, 237); }
table tr:nth-child(7) { background: rgb(234, 122, 122); }
tbody tr:nth-child(7) img { background: white; }
table tr td { padding: 5px; border: none !important; }

.footer { height: 1.3in; position: relative; margin: 10px auto; width: 7.5in; }
.footer img { height: 50px; margin: 5px; }

@media print {
	.footer {
		margin-top: -1.3in; /* always negate the height */
		bottom: 0 !important;
		page-break-before: always;
	}
}
</style>

++++

Like CMP3, Bootstrap is field-tested and research-validated, with a focus on deep exploration that supports and engages all kinds of learners.  Our integrated computing modules have been proven to support math transfer and can be mixed and matched to supplement what you’re already doing in your classroom. __Teaching 7th grade math with Bootstrap also addresses many CS Standards, including: 2-AP-1, 2-AP-10, 2-AP-11, 2-AP-13, 2-AP-14, 2-AP-17.__

@vspace{1ex}

[cols=".^1a,6a", stripes="none",options="header"]
|===
| *CMP Unit*
| *Integrated Computing Lessons that can extend the CMP3 Unit*


| *Looking for Pythagoras:* +
 _The Pythagorean Theorem_
| @span{.right}{@image{../../images/distance-formula.png, "", 110}}
*The Distance Formula*

- Looking for a new project to enrich your curriculum? Bootstrap:Algebra offers students the opportunity to program their own basic video games!
- Video Games use distance to determine whether a collision has occurred, offering an authentic application for using a formula that can feel abstract to students.
- This lesson offers lots of materials to scaffold connections between the Pythagorean Theorem and distance on the coordinate plane.
_These materials can be used without committing to the full video game project._


| *Butterflies, Pinwheels and Wallpaper:* +
 _Symmetry and Transformations_
| @span{.right}{@image{../../images/function-composition-3.png, "", 100}}
*Function Composition*

- Simple code allows students to experiment with rotating, scaling, and reflecting shapes, and images from the web.
- Practicing transformations with their own names is highly motivating.
- In seconds, students can adjust the degree of rotation, scale factor, etc. developing understanding from rapid feedback


| *Function Junction:* +
_Families of Functions_
| @span{.right}{@image{../../images/function-composition-2.png, "", 110}}
 *Function Composition*

- For many students, function compositions like f(g(h(x))) are wildly abstract.
- In Bootstrap, we use the Circles of Evaluation to make the structure of the math visible to students.
- In the programming environment, where students can layer functions to transform and compose images, function compositions find concrete and highly motivating applications.

|===

[.footer]
--
Excited to learn more? @link{http://bootstrapworld.org/materials/, Our materials} are free of charge, and we love training teachers to use them! @link{https://www.bootstrapworld.org/workshops/index.shtml, Sign up for a workshop} today!

[.funders]
Created with support from: @image{../../../../lib/images/nsf.png}

www.BootstrapWorld.org  |  contact@BootstrapWorld.org
--
