= Materials for Teachers using Connected Mathematics (Grade 7)

++++
<style>
@import url("../../../../lib/alignment.css");
</style>

++++

Like CMP3, Bootstrap is field-tested and research-validated, with a focus on deep exploration that supports and engages all kinds of learners.  Our integrated computing modules have been proven to support math transfer and can be mixed and matched to supplement what you’re already doing in your classroom. __Teaching 7th grade math with Bootstrap also addresses many CS Standards, including: 2-AP-1, 2-AP-10, 2-AP-11, 2-AP-13, 2-AP-14, 2-AP-17 2-AP-19, 2-AP-21, 2-DA-08.__

@vspace{1ex}

[cols=".^1a,6a", stripes="none",options="header"]
|===
| *CMP Unit*
| *Integrated Computing Lessons that can extend the CMP3 Unit*


| *Shapes and Designs:* +
 _Two Dimensional Geometry_
| @span{.right}{@image{../../images/making-shapes-from-code.png, "", 90}}
*Making Shapes from Code*

- Get your students coding with highly motivational image functions!
- Writing simple code to build a wide range of shapes of different colors and sizes, reinforces vocabulary for describing polygons.
- Triangle contracts gets students thinking about what information is required to describe a triangle and multiple ways of thinking about right-isosceles triangles

| *Accentuate the Negative:* +
 _Integers and Rational Numbers_
| @span{.right}{@image{../../images/order-of-operations.png, "", 90}}
*Order of Operations*

- Instead of a list of rules to memorize, we use the Circles of Evaluation to expose the structure of the math involved in evaluating expressions. Check it out! It’s a powerful tool.
- __These materials can be used without any programming.__

| *Stretching and Shrinking:* +
_Understanding Similarity_
| @span{.right}{@image{../../images/function-composition.png, "", 125}}
 *Function Composition*

- The Wumps are a powerful tool for understanding similarity and distortion.
And, for some students, plotting coordinates by hand is arduous!
- Looking for follow up materials that will engage students in thinking about scale factors with more immediate feedback? We’ve got you!
- Simple code allows students to experiment with scaling images (including shapes, their name, or any image from their google drive) up or down using scale factors and distorting images using scale-xy.

| *Comparing and Scaling:* +
_Ratios, Rates, Percent, Proportions_
| @span{.right}{@image{../../images/making-flags.png, "", 130}}
*Making Flags*

- Flags are an authentic application for ratios and scaling!
- Flags also offer our students a rare opportunity to connect to and share pride in their identities in math class.
- In this lesson, students write code both to scale and locate shapes on the coordinate grid to recreate an image of their choosing.
- Low-threshold and high-ceiling, students of all kinds of minds love building flags - some will make many! And they take great pride in seeing their flags and code hanging on classroom walls.

| *Moving Straight Ahead:* +
_Linear Relationships_

| @span{.right}{@image{../../images/linear-relationships.png, "", 160}}
*Linear Relationships*

- We offer an abundance of interactive materials to get students thinking about whether relationships represented in tables and graphs are linear.
- _No programming required_

@vspace{1ex}

*Defining Linear Relationships*

- These interactive materials invite students to investigate linear relationships in tables, graphs, & function definitions.


| *Filling and Wrapping:* +
_Three Dimensional Measurement_

| @span{.right}{@image{../../images/sa-rect-prism.png, "", 160}}
*Surface Area of a Rectangular Prism*

- This lesson engages students in identifying the relevant dimensions for finding the area of each of the faces of the prism, generating a printable set of rectangles, labeled with their dimensions, from which students physically construct paper models of their own prisms and calculate the surface area.
- Ultimately, students can use their model to generate a formula for calculating the surface area of a prism.

| *Samples and Populations:* +
_Making Comparisons and Predictions_
| @span{.right}{@image{../../images/rand-samp-t.png, "", 160}}
*Randomness and Sample Size* +

- Simple code allows students to quickly generate samples of various sizes from any dataset.
- In seconds, students can generate pie charts to see how the samples compare to each other and use them to make predictions about the full dataset.
- Students can test their predictions against findings from the full dataset.
|===

[.footer]
--
Excited to learn more? @link{http://bootstrapworld.org/materials/, Our materials} are free of charge, and we love training teachers to use them! @link{https://www.bootstrapworld.org/workshops/index.shtml, Sign up for a workshop} today!

[.funders]
Created with support from: @image{../../../../lib/images/nsf.png}

www.BootstrapWorld.org  |  contact@BootstrapWorld.org
--
