= Materials for Teachers using Connected Mathematics (Grade 6)

++++
<style>
body {
	margin: auto;
	color: 	black !important;
	width:	7.5in;
	border: solid 1px red;
	height:	10in;
	-webkit-print-color-adjust: exact;
}

/* stuff we want to hide */
#footer, .acknowledgment, #savetodrive-div { display: none !important; }
h1:before {
	content: url('../../images/Logo with Text.png');
 	display: block;
}
h1, h2, tfoot td { font-size: 12pt; margin: 0px 6px; text-align: center !important; }
.ulist p, em, strong, #content { padding: 0 !important; margin: 0 !important; }
.funders { border: solid gray; border-width: 1px 0; margin: 10px 0; }

/* Table formatting */
table { order-collapse: separate; border-spacing: 2px 5px; border: none !important; }
tr th.tableblock, p { font-size: 0.8rem !important; margin: 0; }
tr th.tableblock { background: rgb(182, 215, 168); padding: 2px; }
table tr:nth-child(1) { background: rgb(207, 226, 243); }
table tr:nth-child(2) { background: rgb(255, 242, 204); }
table tr:nth-child(3) { background: rgb(249, 203, 156); }
table tr:nth-child(4) { background: rgb(226, 195, 242); }
table tr:nth-child(5) { background: rgb(242, 195, 195); }
table tr:nth-child(6) { background: rgb(168, 228, 237); }
table tr:nth-child(7) { background: rgb(234, 122, 122); }
table tr td { padding: 5px; border: none !important; }

#header, #header *, h1 { background: none !important; color: black !important; }

/* Table footer will be used as our page footer */
tfoot, tfoot tr { background: none !important; }
tfoot { margin: 10px 0; }
tfoot td { padding: 0 !important; }
tfoot img { height: 50px; margin: 5px; }

tbody tr:last-child img { background: white; }

@media screen { table tr:before { content: none !important; }
@media print {
	@page { size: letter portrait !important; }
	tfoot { position: fixed !important; bottom: 0 !important; }
	table { page-break-before: avoid; }


	/* Which row to break? */
	table tr:nth-child(99):before {content:""; display: block; page-break-before: always;}
}
</style>
++++

Like CMP3, Bootstrap is field-tested and research-validated, with a focus on deep exploration that supports and engages all kinds of learners.  Our integrated computing modules have been proven to support math transfer and can be mixed and matched to supplement what you’re already doing in your classroom. __Teaching 6th grade math with Bootstrap also addresses many CS Standards, including: 2-AP-1, 2-AP-10, 2-AP-11, 2-AP-13, 2-AP-14, 2-AP-17.__

@vspace{1ex}

[cols=".^1a,6a", stripes="none",options="header, footer"]
|===
| *CMP Unit*
| *Integrated Computing Lessons that can extend the CMP3 Unit*


| *Prime Time:* +
 _Factors & Multiples_

| @span{.right}{@image{../../images/circle.png, "", 65}}
 *Order of Operations*

- Instead of a list of rules to memorize, we use the Circles of Evaluation to expose the structure of the math involved in evaluating expressions. Check it out! It’s a powerful tool.
- _Circles of Evaluation can be used without any programming!_

| *Covering & Surrounding:* +
 _2-Dimensional Measurement_
| @span{.right}{@image{../../images/shapes.png, "", 100}}

*Making Shapes from Code*

- Get your students coding with highly motivational image functions! Writing simple code to build a wide range of shapes of different colors and sizes, reinforces vocabulary for describing polygons.
- While this lesson does not focus on area and perimeter, for those looking to extend beyond the scope of the CMP3 unit, the function composition lesson offers an intuitive low-threshold, high-ceiling introduction to transformations.

@span{.right}{@image{../../images/surface-area.png, "", 100}}
*Surface Area of a Rectangular Prism*

- This lesson engages students in identifying the relevant dimensions for finding the area of each of the faces of the prism, generating a printable set of rectangles, labeled with their dimensions, from which students physically construct paper models of their own prisms and calculate the surface area. Ultimately, students can use their model to generate a formula for calculating the surface area of a prism.



| *Data About Us:* +
_Statistics and Data Analysis_

| @span{.right}{@image{../../images/boxplot2.png, "", 150}}
*Measures of Center*

- Simple code returns the mean, median, and mode(s) for any real world dataset, allowing for meaningful conversations about why we have to think carefully about which measure of center best represents a given dataset.

*Spread of a Dataset*

- Simple code generates 5 number summaries, box plots and/or histograms for any dataset, connecting this generally abstract concept to real world analysis.
2+| // footer row
Excited to learn more? @link{http://bootstrapworld.org/materials/, Our materials} are free of charge, and we love training teachers to use them! @link{https://www.bootstrapworld.org/workshops/index.shtml, Sign up for a workshop} today!

[.funders]
Created with support from: @image{../../../../lib/images/nsf.png}

www.BootstrapWorld.org  \|  contact@BootstrapWorld.org
|===
