= Materials for Teachers using Illustrative Mathematics (Grade 8)

++++
<style>
@import url("../../../../lib/alignment.css");
</style>

<style>
// override default colors, so that the 4th row has the
// same BG color as the 3rd, the 5th has the 4th, and so on
table tr:nth-child(4) { background: rgb(249, 203, 156); }
table tr:nth-child(5) { background: rgb(226, 195, 242); }
table tr:nth-child(6) { background: rgb(242, 195, 195); }
table tr:nth-child(7) { background: rgb(168, 228, 237); }

// make the rocket image background white
tr:nth-child(3) img { background: white; }
</style>
++++

Like IM, Bootstrap is field-tested and research-validated, with a focus on deep exploration that supports and engages all kinds of learners.  Our integrated computing modules have been proven to support math transfer and can be mixed and matched to supplement what you’re already doing in your classroom. __Teaching Algebra 1 with Bootstrap also addresses many CS Standards, including: 2-AP-1, 2-AP-10, 2-AP-11, 2-AP-13, 2-AP-14, 2-AP-17.__

@vspace{1ex}

[cols=".^1a,6a", stripes="none",options="header"]
|===
| *IM Unit*
| *Integrated Computing Lessons that can extend the IM Unit*


| @link{https://curriculum.illustrativemathematics.org/MS/teachers/3/1/index.html,*Rigid Transfromations and Congruence*}
| @span{.right}{@image{../../images/function-comp-3-transparent.png, "", 135}}

@link{https://www.bootstrapworld.org/materials/latest/en-us/courses/algebra-wescheme/lessons/function-composition/index.shtml,*Function Composition*}

- Simple code allows students to experiment with rotating, scaling, and reflecting images of shapes, text or anything from the web.
- Practicing transformations with their own names is highly motivating.
- In seconds, students can adjust the degree of rotation and get visual feedback on how the numbers transform the images.

| @link{https://curriculum.illustrativemathematics.org/MS/teachers/3/3/index.html,*Linear Relationships*}
| @span{.right}{@image{../../images/linear-relationships.png, "", 135}}

@link{https://www.bootstrapworld.org/materials/spring2021/en-us/courses/ok/lessons/ds-linearity/index.shtml, *Linear Relationships*}

- We offer an abundance of interactive materials to get students thinking about whether relationships represented in tables and graphs are linear.
- No programming required.

@vspace{1ex}

@link{https://www.bootstrapworld.org/materials/spring2021/en-us/courses/ok/lessons/ds-linearity-2/index.shtml, *Defining Linear Relationships*}

- Check out our interactive materials that invite students to investigate linear relationships in tables, graphs, and function definitions.

| @link{https://curriculum.illustrativemathematics.org/MS/teachers/3/5/index.html,*Functions and Volume*}

| @link{https://bootstrapworld.org/materials/latest/en-us/courses/algebra-wescheme/lessons/solving-word-problems/index.shtml,*Solving Word Problems*}
@span{.right}{@image{../../images/solving-word-problems3-transparent.png, "", 135}}

- Students solve a classic function word problem about the velocity and height of a rocket - and then write simple code to see the rocket blast off.
- Students can even modify the code to change the speed and direction of the rocket!

@vspace{1ex}

@link{https://bootstrapworld.org/materials/latest/en-us/courses/algebra-wescheme/lessons/restating-the-problem/index.shtml,*Restating the Problem*}

- Using the Design Recipe - a tool that empowers students both as coders and mathematicians - students solve word problems that interweave the development of the function concept with 3D geometry concepts.
- In our engaging and interactive computing context, students are offered many opportunities to analyze word problems and identify the domain, range, and other quantities.

| @link{https://curriculum.illustrativemathematics.org/MS/teachers/3/5/index.html,*Functions and Volume* (cont)}

| @link{https://bootstrapworld.org/materials/latest/en-us/courses/algebra-wescheme/lessons/piecewise-functions/index.shtml,*Piecewise Functions*}

- A fictional restaurant owner, Alice, solicits students’ help in improving some code used to calculate customers' bills. As students analyze the code, they dig into the concept of piecewise functions in a meaningful and engaging new context.
- Videogames rely on piecewise functions for player animation! The video game project offers an exciting opportunity to apply new and otherwise abstract mathematical knowledge.


| @link{https://curriculum.illustrativemathematics.org/MS/teachers/3/6/index.html,*Associations in Data*}
| @span{.right}{@image{../../images/scatterplots.png, "", 150}}

@link{https://bootstrapworld.org/materials/latest/en-us/courses/data-science/lessons/scatter-plots/index.shtml,*Scatter Plots*}

- Simple code allows students to quickly generate scatterplots from any dataset, allowing for lively discussion about trends observed.

@vspace{1ex}

@link{https://bootstrapworld.org/materials/latest/en-us/courses/data-science/lessons/correlations/index.shtml,*Correlations*}

- As a class, your students will search out correlations in a dataset, discussing and analyzing the form, direction, and strength of the linear relationships they see in the scatterplots they generate.
- Students repeat this process in a dataset of their choice, one that sparks their interest. Simple code enables students to use linear regression to quantify patterns in their dataset..
- Our data science curriculum leverages students' curiosity about the world around them to inspire real data analysis and original research. Individual lessons are impactful regardless of whether you opt to facilitate the culminating research project or not.



|===
[.footer]
--
Excited to learn more? @link{http://bootstrapworld.org/materials/, Our materials} are free of charge, and we love training teachers to use them! @link{https://www.bootstrapworld.org/workshops/index.shtml, Sign up for a workshop} today!

[.funders]
Created with support from: @image{../../../../lib/images/nsf.png}

www.BootstrapWorld.org  |  contact@BootstrapWorld.org
--
