= Materials for Teachers using Illustrative Mathematics (Grade 6)

++++
<style>
/* stuff we want to hide */
#footer, .acknowledgment, #savetodrive-div { display: none !important; }

body {
	margin: auto;
	color: 	black !important;
	width:	7.5in;
	height:	10in;
	-webkit-print-color-adjust: exact;
}

#header, #header *, h1 { background: none !important; color: black !important; }
h1, h2, .footer { font-size: 12pt; margin: 0px 6px; text-align: center !important; }
h1:before {
	content: url('../../images/Logo with Text.png');
 	display: block;
}
.ulist p, em, strong, #content { padding: 0 !important; margin: 0 !important; }
.funders { border: solid gray; border-width: 1px 0; margin: 10px 0; }

/* Table formatting */
table {
	order-collapse: separate;
	border-spacing: 2px 5px;
	border: none !important;
	margin-bottom: 1.75in;
	page-break-before: avoid;
}
tr th.tableblock, p { font-size: 1.25rem !important; margin: 0; }
tr th.tableblock { background: rgb(182, 215, 168); padding: 2px; }
table tr:nth-child(1) { background: rgb(207, 226, 243); }
table tr:nth-child(2) { background: rgb(255, 242, 204); }
table tr:nth-child(3) { background: rgb(249, 203, 156); }
table tr:nth-child(4) { background: rgb(226, 195, 242); }
table tr:nth-child(5) { background: rgb(242, 195, 195); }
table tr:nth-child(6) { background: rgb(168, 228, 237); }
table tr:nth-child(7) { background: rgb(234, 122, 122); }
tbody tr:nth-child(7) img { background: white; }
table tr td { padding: 5px; border: none !important; }

.footer { height: 1.3in; position: relative; margin: 10px auto; width: 7.5in; }
.footer img { height: 50px; margin: 5px; }

@media print {
	.footer {
		margin-top: -1.3in; /* always negate the height */
		bottom: 0 !important;
		page-break-before: always;
	}
}
</style>
++++

Like Illustrative Mathematics, Bootstrap is field-tested and research-validated, with a focus on deep exploration that supports and engages all kinds of learners.  Our integrated computing modules have been proven to support math transfer and can be mixed and matched to supplement what you’re already doing in your classroom. __Teaching 6th grade math with Bootstrap also addresses many CS Standards, including: 2-AP-1, 2-AP-10, 2-AP-11, 2-AP-13, 2-AP-14, 2-AP-17.__

@vspace{1ex}

[cols=".^1a,6a", stripes="none",options="header"]
|===
| *IM Unit*
| *Integrated Computing Lessons that can extend the IM Unit*


| *Area and Surface Area*
| @span{.right}{@image{../../images/making-shapes-from-code.png, "", 100}}


*Making Shapes from Code*

- Get your students coding with highly motivational image functions!
- Writing simple code to build a wide range of shapes of different colors and sizes, reinforces vocabulary for describing polygons.

*Surface Area of a Rectangular Prism*

- This lesson engages students in analyzing a rectangular prism to identify which dimensions are need to find the area of each face.
- Simple code generates a printable set of rectangles labeled with dimensions. Students use printouts to construct paper models of their prisms and calculate the surface area.
- Ultimately, students can use their model to generate a formula for calculating the surface area of a prism.

| *Introducing Ratios*
| @span{.right}{@image{../../images/making-flags.png, "", 110}}

*Making Flags*

- Flags are an authentic application for ratios and scaling!
- In this lesson, students write code both to scale and locate shapes on the coordinate grid to recreate an image of their choosing.
- Low threshold and high ceiling, students of all kinds of minds love building flags - some will make many! And they take great pride in seeing their flags and code hanging on classroom walls, a rare opportunity to connect to and share pride in their identity in math class.

| *Expressions and Equations*

| @span{.right}{@image{../../images/order-of-operations.png, "", 95}}

*Order of Operations*

- Instead of a list of rules to memorize, we use the Circles of Evaluation to expose the structure of the math involved in evaluating expressions. Check it out! It’s a powerful tool.
- Circles of Evaluation can be used without any programming!

| *Rational Numbers*
| @span{.right}{@image{../../images/coords-and-game-design.png, "", 185}}

*Coordinates and Game Design*

- Video game design offers an exciting and relevant new context for students to apply their knowledge of the coordinate plane.
- Students brainstorm what they want their own game to look like, and then design a screenshot of that game by assessing the ordered pair location of each character.

*Simple Inequalities*

- Simple code enables students to test solutions and non-solutions to inequalities,concretizing the concept by providing immediate visual feedback. The computer plots points provided by students in either green or red, depending on if those points make the inequality true or false.
- In the Sam the Butterfly lesson, students use what they know about inequalities to define the boundaries that will keep a video game character on the screen.

| *Data Sets and Distributions*
| @span{.right}{@image{../../images/measures-of-spread.png, "", 150}}

*Measures of Center*

- Simple code returns the mean, median, and mode(s) for any real world dataset, allowing for meaningful conversations about why we have to think carefully about which measure of center best represents a given dataset.

*Spread of a Dataset*

- Simple code generates 5-number summaries, box plots and/or histograms for any dataset, connecting this generally abstract concept to real world analysis.


|===

[.footer]
--
Excited to learn more? @link{http://bootstrapworld.org/materials/, Our materials} are free of charge, and we love training teachers to use them! @link{https://www.bootstrapworld.org/workshops/index.shtml, Sign up for a workshop} today!

[.funders]
Created with support from: @image{../../../../lib/images/nsf.png}

www.BootstrapWorld.org  |  contact@BootstrapWorld.org
--

