= Fast Functions

++++
<style>
/* Hide DR elements we want hidden */
.recipe_instructions, .recipe_title, .recipe_word_problem, .recipe_purpose_statement,
.studentAnswer::before, .studentAnswer::after  {
 	display: none !important;
}

.recipe{ min-height: 25pt; }
.recipe_contract span { margin-bottom: 0px; }
.keyword_only {height: 20pt;}

/* shade the contract */
.recipe_contract { background: #eee; }

/* maximize length of DR lines */
.recipe_example_body, .recipe_definition_body {width: 90%; min-width: 340pt !important;}
</style>
++++

There is space below to define four different functions, writing their Contracts, two examples, and the definition itself. The function `gt` - which makes solid green triangles of a given size - is provided as an example. Can you define `bc` as a function which makes solid blue circles of a given _radius?_

@include{fragments/gt.adoc}

@span{.sectionbreak}{}

@include{fragments/gold-star.adoc}

@span{.sectionbreak}{}

@include{fragments/blank-recipe.adoc}

@span{.sectionbreak}{}

@include{fragments/blank-recipe.adoc}
