= Matching Examples and Contracts

++++
<style>
td {height: 120pt;}
p { font-size: 0.9rem;}
div.circleevalsexp, .editbox, .cm-s-scheme {font-size: .75rem;}

td:first-child {border-bottom: 1pt solid gray !important;}

</style>
++++

@do{(define e1
   (code #:multi-line #t
"examples:
  f(\"pink\", 5) is star(5, \"solid\", \"pink\")
  f(\"blue\", 8) is star(8, \"solid\", \"blue\")
end"))

(define c1 (code "f :: String, Number -> Image"))

(define e2
   (code #:multi-line #t
"examples:
  f(1) is
    rectangle(1, 1, \"outline\", \"purple\")
  f(6) is
    rectangle(6, 6, \"outline\", \"purple\")
end"))

(define c2 (code "f :: Number -> Image"))

(define e3
   (code #:multi-line #t
"examples:
  f(\"Game Today!\") is
    text(\"Game Today!\", 50, \"red\")
  f(\"Go Team!\") is
    text(\"Go Team!\", 50, \"red\")
  f(\"Exit\") is
    text(\"Exit\", 50, \"red\")
end"))

(define c3 (code "f :: String -> Image"))

(define e4
   (code #:multi-line #t
"examples:
  f(5, \"outline\") is
    star(5, \"outline\", \"yellow\")
  f(15, \"solid\") is
    star(15, \"solid\", \"yellow\")
end"))

(define c4 (code "f :: Number, String -> Image"))

(define e5
   (code #:multi-line #t
"examples:
  f(5) is 5 / 2
  f(8) is 8 / 2
  f(900) is 900 / 2
end"))


(define c5 (code "f :: Number -> Number"))
}

Match each set of examples (left) with the contract that best describes it(right).

@vspace{1ex}
[cols="<.^10a,^.^2a,1,^.^1a,>.^7a",stripes="none",grid="none",frame="none", options="header"]
|===
|  Examples|                ||      |Contract
| @show{e5}| *1* @ifsoln{-A}|| *A*  | @show{c5}
| @show{e2}| *2* @ifsoln{-C}|| *B*  | @show{c3}
| @show{e1}| *3* @ifsoln{-E}|| *C*  | @show{c2}
| @show{e3}| *4* @ifsoln{-B}|| *D*  | @show{c4}
| @show{e4}| *5* @ifsoln{-D}|| *E*  | @show{c1}
|===
