= Dot Plots and Bar Charts in CODAP

Open the @starter-file{animals}. First, create a graph of randomly generated points by selecting the `Graph` icon, and then respond to the following prompts.

== Create Data Visualizations

@n Select the y-axis on your graph (where it says "Click here"). On the drop-down menu that appears, select `Fixed`. (_If you prefer, you may also drag the attribute name from the table to the y-axis._) What do you notice?

@fitb{}{@ifsoln{A horizontal dot plot forms, categorizing animals as fixed (true) and not fixed (false). The labels for the dot plot are on the y-axis.}}

@fitb{}{}

@vspace{1ex}

@n Now select the x-axis on your graph and select `Fixed`. How does the graph change?

@fitb{}{@ifsoln{The labels move from the y-axis to the x-axis, and the dots are stacked vertically.}}

@fitb{}{}

@vspace{1ex}

@n Select the `configuration` icon (which looks like a bar graph) to the right of the data visualization. Select `Fuse Dots into Bars`

@n Click the `ruler` icon to test `count` and `percentage`. What happens?

@fitb{}{@ifsoln{When I select "count," I see the number of animals represented by each bar. When I select "percentage," the percentage of }}

@fitb{}{@ifsoln{animals represented by each bar appears.}}

@vspace{1ex}


@n Now, make a bar chart showing how many animals there are of each species by changing the variable on the x-axis to `species`. How can reconfigure the bar chart as a dot plot?

@fitb{}{@ifsoln{Select the `configuration` menu again, and deselect `Fuse Dots into Bars`.}}

@fitb{}{}

@vspace{1ex}

== Numeric vs. Categorical Data Visualizations

@n Create a graph with `Weeks` on the x-axis. What intervals do you see on the x-axis? @fitb{}{@ifsoln{I see intervals of 5.}}

@n Now, click on `Weeks` so that a drop-down menu appears. From this drop-down menu, choose `Treat as Categorical`. How did the numbers on the x-axis change? (_Look closely!_)

@fitb{}{@ifsoln{From 1-10, there are intervals of 1. Then, the graphs jumps to 24 and then 30.}}

@fitb{}{}

@n Why do you think CODAP produced a graph with intervals on the x-axis that are _not_ evenly spaced?

@fitb{}{@ifsoln{CODAP is no longer interpreting `Weeks` as numerical data. Rather, it is creating many unique categories.}}

@fitb{}{}

@vspace{1ex}

@n As you've discovered, CODAP can view `Age` as numeric or categorical. In which mode can we `Fuse dots into bars`? Which kind of data is used for bar graphs?

@fitb{}{@ifsoln{We can fuse the points into bars when we treat `Age` as categorical. Bar charts show categorical data, classifying rather than measuring.}}

@fitb{}{}


