= Dot Plots and Bar Charts in a Nutshell

== Displaying Categorical Variables

* With a table open in CODAP, select the "graph" icon to produce a scatter plot of _randomly distributed_ data points.
* Drag attributes/columns to the axes (or select from a drop-down menu of attributes/columns by clicking the axes) to organize the data so that it is no longer randomly distributed.
* Once the data is organized, manipulate it further by selecting the graph menu icons:
	** *the ruler icon* provides options for calculating statistics such as mean, median, and standard deviation
	** for datasets with two variables, clicking the ruler icon will provide _additional_ statistical computations (such as a least squares line or regression line)
	** the *bar graph icon* allows new configurations of the data. Select this option to group data points into bins or create a bar for each point. If the data is numeric, clicking on the bar graph icon a second time (for instance, after data is grouped into bins) allows the creation of a histogram (by fusing the dots into bars).

@vspace{1ex}

== Exploring other Data Visualizations

@vspace{1ex}

Data Scientists use *data visualizations* to visualize information. You've probably seen some of these charts, graphs and plots yourselves! When it comes to visualizing @vocab{Categorical Data}, we often rely on *dot plots* and @vocab{bar charts}. (Pie charts display categorical data, too, but CODAP doesn't offer them largely because many find them @link{https://www.data-to-viz.com/caveat/pie.html, "challenging to read."})


@vspace{1ex}

When we want to create a data visualization in CODAP, it is important to consider the following: Which attributes on which axes? What type of data? What configuration?


@vspace{2ex}

*Bar charts* show the _count or percentage_ of rows in each category.

* Bar charts provide a visual representation of the frequency of values in a categorical column. 
* Bar charts have a bar for every category in a column.
* The more rows in a category, the taller the bar.
* Bars in a bar chart can be show in _any order_, without changing the meaning of the chart. However, bars are usually shown in some sensible order (bars for the number of orders for different t-shirt sizes might be presented in order of smallest to largest shirt).

