= Practice Plotting (2)

++++
<style>
td, th, .center { padding: 0 !important; vertical-align: middle; }
p { margin: 0 !important; }
.checklist li { margin: 0; padding: 0; }
</style>
++++

Use the @starter-file{animals} to create the following visualizations in CODAP. First, fill in the blanks and check all boxes that apply. Next, predict and sketch what the display will look like. Then, create the visualization in CODAP.

@vspace{1ex}

@n A bar chart showing the `species` of animals from the shelter.
[cols="1a,1a,1a", options="header"]
|===
|@center{*Column / Attribute*}
|@center{*Type of Data*}
|@center{*Configuration*}

|
@ifnotsoln{
@fitbruby{100%}{}{[column used as x-axis]}
@fitbruby{100%}{}{[column used as y-axis]}
}

@ifsoln{
@fitbruby{100%}{_species_}{[column used as x-axis]}
@fitbruby{100%}{_n/a_}{[column used as y-axis]}
}

|
@ifnotsoln{
* [ ] Numeric
* [ ] Categorical
}

@ifsoln{
* [ ] Numeric
* [x] Categorical
}

|
@ifnotsoln{
* [ ] Points
* [ ] Fuse dots into bars
* [ ] Bar for each point
* [ ] Group into bins
* [ ] No need to make a selection
}

@ifsoln{
* [ ] Points
* [x] Fuse dots into bars
* [ ] Bar for each point
* [ ] Group into bins
* [ ] No need to make a selection
}

|===


[.FillVerticalSpace, cols="^1a, ^1a", options="header"]
|===
|*Sketch the chart below:*
|*What do you think the visualization tells us?*

|
@ifsoln{
@image{../images/species-bar-chart.png, 200}
}

@ifnotsoln{ @vspace{20ex} }
|


@ifnotsoln{ @vspace{10ex} }

@ifsoln{
How many animals are cats, dogs, lizards, rabbits, snails, and tarantulas.
@vspace{5ex}

}

|===



@vspace{1ex}

@n A scatter-plot, using the animals `name` as the labels, `age` as the x-axis, and `pounds` as the y-axis, for all the animals from the shelter. _Note: The `Measure` menu has lots of options! On this page, we've included the two options that *create new visualizations*._

[cols="1a,1a,1a", options="header"]
|===
|@center{*Column / Attribute*}
|@center{*Type of Data*}
|@center{*Measure*}


|
@ifnotsoln{
@fitbruby{100%}{}{[column used as x-axis]}
@fitbruby{100%}{}{[column used as y-axis]}
@fitbruby{100%}{}{[(optional) column used for labels]}
}

@ifsoln{
@fitbruby{100%}{_age_}{[column used as x-axis]}
@fitbruby{100%}{_pounds_}{[column used as y-axis]}
@fitbruby{100%}{_name_}{[(optional) column used for labels]}
}

|
@ifnotsoln{
* [ ] Numeric
* [ ] Categorical
}

@ifsoln{
* [x] Numeric
* [ ] Categorical
}

|
@ifnotsoln{
* [ ] Box plot
* [ ] Least squares line
* [ ] No need to make a selection
}

@ifsoln{
* [ ] Box plot
* [ ] Least squares line
* [x] No need to make a selection
}

|===


[.FillVerticalSpace, cols="^1a, ^1a", options="header"]
|===
|*Sketch the chart below:*
|*What do you think the data visualization tells us?*

|
@ifsoln{
@image{../images/age-pounds-scatter-plot.png, 150}
}

@ifnotsoln{
@vspace{20ex}
}
|


@ifnotsoln{
@vspace{10ex}
}

@ifsoln{

The relationship between animals' age and weight.

}

|===
