= The Distance Formula

@lesson-description{Students apply their knowledge of the Pythagorean Theorem and Circles of Evaluation to develop a function for the distance formula.}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Explain how the distance formula is related to the Pythagorean theorem.
* Write a function for the distance formula.


|Student-Facing Lesson Goals
|
* I can explain how the distance formula is connected to the Pythagorean theorem.
* I can write a function that takes in 2 points and returns the distance between them.

|Key Points for the Facilitator
|
* The distance formula is an excellent review of Circles of Evaluation. Have students work out the expression in small groups to foster discussion.

|Prerequisites
|
* Students should be familiar with Circles of Evaluation.
* Students should be familiar with the Design Recipe.
* Students should have all other game functions working. (Game Pathway)

|Materials
|
* Lesson slides template (@link{https://docs.google.com/presentation/d/1nds3sEXmoGPQdACNomLOde89FFyjHowILDVGktGLLxQ/view, Google Slides})

* Notice And Wonder (@worksheet-link{workbook-pages/NoticeAndWonder.pdf, PDF}, @link{https://docs.google.com/document/d/1hNMUXcMRWgKllc7SOzzqaTR48RiWbXg8RvG9rtl3SuU/view, Google Doc})

* Design Recipe (@worksheet-link{workbook-pages/DesignRecipe1.pdf, PDF}, @link{https://docs.google.com/document/d/1GQw-EJAw54BK04SMp_4jPtGGt4IojsUA7oXfz9TRm8Y/view, Google Doc})

* Frayer Model (@worksheet-link{workbook-pages/FrayerModelDistance.pdf, PDF}, @link{https://docs.google.com/drawings/d/1mCJygY5elVQzy64zLLRyFVZ9-CkTnVYTBM3URnIfzEc/view, Google Doc})

////
Bootstrap Formative Assessments

* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb07bb4b8576069fdcef1, Bootstrap: Algebra - More Design Recipe Practice} (Desmos Activity)

Connection Activities

* @link{https://teacher.desmos.com/activitybuilder/custom/58efa58b999d890619a5663e, Absolute Value} (Desmos)
* @link{https://www.geogebra.org/m/rq7uDucY, Absolute Value Inequality Illustrator} (Geogebra)
* @link{https://quizizz.com/admin/quiz/581c92bd3fa551e37a438264/absolute-value-preview, Absolute Value} (Quizizz)
* @link{https://www.geogebra.org/m/DTeGM5U7, Distance Formula} (Geogebra)
* @link{https://quizizz.com/admin/quiz/5876366405dad51d02b1beef/distance-formula, Distance Formula} (Quizizz)
* @link{https://quizizz.com/admin/quiz/5828a9f82627ff7d77818381/pythagorean-theorem, Pythagorean Theorem} (Quizizz)
* @link{https://www.geogebra.org/m/jFFERBdd#material/ZFTGX57r, Pythagorean Theorem} (Geogebra)
////

|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Addressing (CCSSM)
|
* @std{8.G.B.7}

|Standards for Mathematical Practice (CCSSM)
|
* @std{MP.2}
|===


== Get Ready:

Students should have their workbook, contracts page, and a pencil.

== Launch: (5 min)

Have students play this @link{https://www.wescheme.org/view?publicId=PJMfrSvGRl, game file}.

[.notice-box]
.Notice and Wonder
****
What do you Notice? What do you Wonder?
****


== Discuss: (10 min)

* What seems to be missing from this game?
* Why are the characters moving by each other?
* How do you usually accumulate or lose points in a video game?
* What does it mean for characters to 'hit' one another? To collide?
* How will the computer know when the characters have collided?

Role-Play: Ask a volunteer to help role-play 2 characters colliding. Stand about 10 steps away from one another and side-step towards each other one step at a time, while asking, "Are we colliding, yet?"

Do this until students can clearly see it's when the 2 characters are 'touching' or 'at the same point.' Don't worry about clarifying the difference now, they will be able to see the differences with their own images very soon.

== Explore: line-length (10 min)

Have students explore using the `line-length` function in the Interactions window.

[.notice-box]
.Notice and Wonder
****
What do you Notice? What do you Wonder?
****


[.strategy-box]
.Extension
****
You can extend this `line-length` activity into a lesson on absolute value and have students program `line-length` themselves using `cond`.
****

== Explore: 2D distance(5 mins)

Have students open and play @link{https://www.wescheme.org/view?publicId=0bCivugY3P, this game file}.

[.notice-box]
.Notice and Wonder
****
What do you Notice? What do you Wonder?
****

== Discuss: (5 min)

* What kind of shapes do you see?
* What kind of triangle is it?
* What are the labels on the shapes?
* What side is missing the label?

Bring the discussion to closure by pointing out to students that the missing labeled side of the triangle is the hypotenuse of the right trangle and the legs are the difference in distances along the x and y axes of the characters. 

[.strategy-box]
.Extension
****
You can take this activity further by having students prove the distance formula by solving for the hypotenuse of a right triangle.
****

== Practice: (10 min)

Have students use this @worksheet-link{workbook-pages/FrayerModelDistance.pdf, Frayer Model} to model the distance formula with the Circles of Evaluation and translate it to code.

== Create/Apply: The Distance Formula(20 mins)

Have students write a function `distance` that takes in 2 coordinate pairs (4 numbers) of 2 characters (x1, y1) and (x2, y2) and returns the distance between those two points.

Students can test their `distance` function using Pythagorean Triples (such as (3, 4, 5) or (5, 12, 13) to make sure it's calculating the distance correctly.

== Create/Apply: collide? (20 mins)

Have students write a function 'collide?' that takes in 2 coordinate pairs (4 numbers) of 2 characters (x1, y1) and (x2, y2) and returns the whether or not the 2 characters have collided.

