= Challenges for update-player
++++
<style>
.studentAnswerShort,
.studentAnswerMedium,
.studentAnswerLong { min-width: 7rem; }

.obeyspaces {
  width: 100%;
  background: #f7f7f8;
  display: inline-block;
}
p .editbox { font-size: unset; }
</style>
++++

For each of the challenges below, see if you can come up with two EXAMPLEs of how it should work!

@vspace{1ex}

@n *Warping* -- Program one key to "warp" the player to a set location, such as the center of the screen.

@vspace{1ex}

@show{
(code '(EXAMPLE
       (update-player (?ANS 320) (?ANS "t")) (?ANS 240)
       (update-player (?ANS 100) (?ANS "t")) (?ANS 240)))
}

@vspace{2ex}

@n *Boundaries* -- Change `update-player` such that `PLAYER` cannot move off the top or bottom of the screen.

@vspace{1ex}

@show{
(code '(EXAMPLE
       (update-player (?ANS 480) (?ANS   "up")) (?ANS 480)
       (update-player (?ANS   0) (?ANS "down")) (?ANS 0)))
}

@vspace{2ex}

@n *Wrapping* -- Add code to `update-player` such that when `PLAYER` moves to the top of the screen, it reappears at the bottom, and vice versa.

@vspace{1ex}

@show{
(code '(EXAMPLE
       (update-player (?ANS 490) (?ANS   "up")) (?ANS 0)
       (update-player (?ANS -10) (?ANS "down")) (?ANS 480)))
}

@vspace{2ex}

@n *Hiding* -- Add a key that will make `PLAYER` seem to disappear, and reappear when the same key is pressed again.

@vspace{1ex}

@show{
(code '(EXAMPLE
       (update-player (?ANS  400) (?ANS "h")) (?ANS (*  400 -1))
       (update-player (?ANS -391) (?ANS "h")) (?ANS (* -391 -1))))
}
