= CODAP Exploration
++++
<style>
div#body.workbookpage .autonum { padding-top: 0.5rem; }
div#body.workbookpage .fitb { padding-top: 0.7rem;}
</style>
++++

This page will help you familiarize yourself with some of CODAP's features. Check off each item once you have completed it. Feel free to experiment and try things out! Make sure you’re logged into the @starter-file{animals} in CODAP before beginning.

== Tables in CODAP

@n A table of data is shown here, with the title at the top of the table. What is the title? @fitb{}{@ifsoln{Animals-Dataset-1.5.1}}

@n Move the table to a different location on the screen, then minimize the table (hints: Hovering your mouse over the title. What appears?).

@n Re-expand the minimized table, then add a row -- also called a _case_ -- to the table. (Hint: Click any of the Index numbers in the left-most column. Look at the menu that appears.) Can you delete that same row? (Note: CODAP will not let you delete an _empty_ case.)

@n Move the `Age` column so that it is between `Fixed` and `Legs`. Click on `Age` and choose "Sort Ascending (A→Z, 0→9)" from the drop-down menu that appears.

@n Now try "Sort Descending". How many animals have names that begin with S? @fitb{5em}{@ifsoln{6}}

@n Delete a column of the table. (Columns are sometimes called _attributes_.)

@n Use the "Undo" button in the upper right to get your column back. Do the keyboard shortcuts for Redo (`Ctrl-Y` on PC, `Cmd-Opt-Z` on Mac) and Undo (`Ctrl-Z` on PC, `Cmd-Z` on Mac) work in CODAP? @fitb{10em}{@ifsoln{Yes}}

@n Close the table. Get it back either by opening the drop-down menu that appears when you click on "Tables" in the upper left.

@n Create a new attribute. Is the column populated (filled in) or empty? @fitb{15em}{@ifsoln{Empty.}}

@n Name your new attribute. What name did you choose? @fitb{}{}



== Graphs in CODAP

@n Click on the "Graph" icon in the upper left-hand corner of the screen. _Note: When you first make a graph, the points are randomly positioned!_

@n How many dots appeared on the graph? (Hint: How many rows -- or _cases_ -- are on the table?) @fitb{}{@ifsoln{32}}

@n Click on a dot. What happens? @fitb{}{@ifsoln{I see information about the point.}}

@n Can you figure out a way to make _different_ information appear when you click on a dot? (Hint: You may need to move a column!)

@n Drag an attribute (like `Weight`, `Name`, or `Sex`) to one of the graph's axes -- or use the drop-down menu that appears when you click on an axis. Can you make the graph show _two_ attributes?

@n Double click on the background of your graph. What happens? @fitb{}{@ifsoln{The graph zooms in}}

@n Click on the "Rescale" icon (it looks like four arrows pointing in four different directions) to zoom back out and display all data again.

@n Once a graph shows two attributes, can you change it back to a graph with one attribute?

@n Click and drag any attribute name from the top of any column in the dataset to the center of the graph. When the graph region turns yellow, release the mouse. What happened? @fitb{}{@ifsoln{A color-coded legend was created!}}

== Matching

Complete the matching activity below to review what you discovered about graphs and tables in CODAP.

[cols=">.^5a,^.^2a,3,^.^1a,.^10a", stripes="none", grid="none", frame="none"]
|===
|  *In order to...* |  || | *I need to...*
| delete a table column
| *@n* @ifsoln{-C}
|| *A*
| click on an orange point


| move a table
| *@n* @ifsoln{-E}
|| *B*
| mouse over the title bar until a `-` button appears in the upper right-hand corner

| minimize a table
| *@n* @ifsoln{-B}
|| *C*
| select the attribute; from the drop-down menu that appears, select "Delete Attribute"

| create a new table column
| *@n* @ifsoln{-F}
|| *D*
| click the "Graph" icon in the upper left-hand corner of the screen

| create a graph of randomly configured points
| *@n* @ifsoln{-D}
|| *E*
| mouse over the title bar until the cursor turns into a hand

| identify information about a specific point
| *@n* @ifsoln{-A}
|| *F*
| make sure the table is selected, then click the grey plus sign
|===
