= Strings and Numbers (2)
++++
<style>
  #content { display: block !important; }
</style>
++++

== Task 3: Playing with Pounds

@vspace{1ex}

As an employee of the shelter, you want each of these animals to be adopted! You wonder if visitors to the shelter might prefer to receive each animal's weight in kilograms, or maybe rounded to the nearest whole number.

@n Before we play with pounds, let's make sure we understand how numbers work in CODAP. Create a new column, then follow the steps below, entering the specified information into the formula box.

- Type `42` (no quotes). Apply.

- Type a fraction. Apply.

- Type a decimal. Apply.

- Type an integer. Apply.

- Enter some expressions that include operators, such as `5 * (8 + 2)`.

Does anything surprise you about how numberse behave in CODAP? @fitb{}{}

@fitb{}{}


@n Click on the name of the column you created in the previous step. Name it `Kilograms`.  Note that to convert pounds to kilograms, we divide by 2.205. What will you enter in the formula box to populate this column with each animal's weight in kilograms? @fitb{}{}

@fitb{}{@ifsoln{`Pounds/2.205`}}

@n Create another new column. Rename it `Rounded Kilograms`. Here, you will use the function `round`, which returns the value of its input, rounded. Enter `round(Kilograms)` in the formula box. What place value did `round` round to? @fitb{}{@ifsoln{It rounded to the nearest whole number.}}

@n The `round` function has one required argument, and a second optional argument, which must be a Number. Experiment with adding a second argument to your formula for `Rounded Kilograms`. For instance, try entering `round(Kilograms, 1)`. Describe what happens.

@fitb{}{@ifsoln{The function rounds to the specified number of digits after the decimal point.}}

@fitb{}{}

@vspace{1ex}

== Task 4: You're the official CODAP expert at the shelter!

@vspace{1ex}

Now, everyone at the shelter comes to you now with their CODAP questions, given how successful you've been at using CODAP for shelter businses. You decide to spend some time playing around with more of the available functions, so you can help anyone who asks.

@n Enter `sqrt(16)` into the `Edit Formula` box. How many arguments does `sqrt` expect? @fitb{}{@ifsoln{_1_}}

@n What type of argument does the function `sqrt` expect? @fitbruby{30em}{@ifsoln{Number}}{Number? String? Boolean?}

@n What type of output does `sqrt` produce? @fitbruby{30em}{@ifsoln{Number}}{Number? String? Boolean?}

@n Which of these expressions will successfully populate a column? If you're not sure, try them out in @starter-file{animals}.

[cols="1,1,1"]
|===
| `sqrt(Weight)`
| @ifsoln-choice{`sqrt(Legs)`}
| `sqrt(Name)`
|===

@n Why will some of these expressions work and some generate errors? @fitb{}{@ifsoln{CODAP finds the square root when the attribute provided_}}

@fitb{}{@ifsoln{is numerical, but CODAP produces an error message when given a string, because it can only calculate the square root of a number. Weight is not a column in the dataset, so it generates an error as well!}}

@fitb{}{}
