= Method Chaining

@lesson-description{Students learn how to chain methods together, and define more sophisticated subsets. }

[@lesson-intro-table]
|===
@prereqs-stds{}
| Lesson Goals
| Students will be able to...

* Use method chaining to write more sophisticated analyses using less code
* Identify bugs introduced by chaining methods in the wrong order

| Student-Facing Lesson Goals
| I can...

 Materials
|
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|

| Relevant Standards
|
@worksheet-include{xtra/lang-prereq.adoc}
|===

== Chaining Methods (Time 30 minutes)

=== Overview
Students learn how to perform multiple table operations (sorting, filtering, building) in the same line of code.

=== Launch
Now that we are doing more sophisticated analyses, we might find ourselves writing the following code:
----
# get a table with the nametags of all the fixed animals, ordered by species
fixed = animals-table.filter(is-fixed)
fixed-with-nametags = fixed.build-column("tag", nametag)
result = fixed-with-nametags.order-by("species", true)
----

That's a lot of code, and it also requires us to come up with names for each intermediates step! Pyret allows table methods can be _chained together_, so that we can build, filter _and_ order a Table in one shot. For example:

----
# get a table with the nametags of all the fixed animals, ordered by species
result = animals-table.build-column("label", nametag).filter(is-fixed).order-by("species", true)
----

This code takes the `animals-table`, and builds a new column. According to our Contracts Page, `.build-column` produces a new Table, and that’s the Table whose `.filter` method we use. That method produces _yet another Table_, and we call that Table’s `order-by` method. The Table that comes back from that is our final result.


[.strategy-box]
.Teaching Tip
****
Use different color markers to draw _nested boxes_ around each part of the expression, showing where each Table came from.
****

It can be difficult to read code that has lots of method calls chained together, so we can add a line-break before each “`.`” to make it more readable. Here’s the exact same code, written with each method on its own line:

----
# get a table with the nametags of all the fixed animals, order by species
animals-table
  .build-column("label", nametag)
  .filter(is-fixed)
  .order-by("species", true)
----

[.lesson-point]
Order matters: Build, Filter, Order.

Suppose we want to build a column and then use it to filter our table. If we use the methods in the wrong order (trying to filter by a column that doesn’t exist yet), we might wind up crashing the program. Even worse, the program might work, but produce results that are incorrect!

=== Student-Facing Task Assessment
[.lesson-point]
When chaining methods, it’s important to build first, then filter, and then order.

How well do you know your table methods? Complete @worksheet-link{workbook-pages/chaining-methods.adoc} and @worksheet-link{workbook-pages/chaining-methods-order-matters.adoc} in your Student Workbook to find out.

== Collect
As our analysis gets more complex, method chaining is a great way to keep the code simple. But complex analysis also has more room for mistakes, so it’s critical to think carefully when we use it!