== Contract Practice 2

For each of the sets of examples, write the contract for the
function _above_ the examples.

1. ``++_________________: _________________________ -> ____________++``

  (EXAMPLE (third-root 16) (expt 16 1/3))
  (EXAMPLE (third-root 125) (expt 125 1/3))

2. ``++_________________: _________________________ -> ____________++``

  (EXAMPLE (sentence-length "hello" 5) (+ (string-length "hello") 5))
  (EXAMPLE (sentence-length "please" 2) (+ (string-length "please") 2))
  (EXAMPLE (sentence-length "goodbye" 10)
           (+ (string-length "goodbye") 10))

3. ``++_________________: _________________________ -> ____________++``

  (EXAMPLE (upside-down (triangle 50 "solid" "yellow"))
           (rotate 180 (triangle 50 "solid" "yellow")))
  (EXAMPLE (upside-down (star 150 "outline" "blue"))
           (rotate 180 (star 150 "outline" "blue")))

4. ``++_________________: _________________________ -> ____________++``

  (EXAMPLE (product-squared 5 6) (sqr (* 5 6)))
  (EXAMPLE (product-squared 10 17) (sqr (* 10 17)))
  (EXAMPLE (product-squared 2 5) (sqr (* 2 5)))

5. ``++_________________: _________________________ -> ____________++``

  (EXAMPLE (half-image "www.images.com/cat_image.jpg")
           (scale 0.5 (bitmap/url "www.images.com/cat_image.jpg")))
  (EXAMPLE (half-image "www.images.com/dog_image.jpg")
           (scale 0.5 (bitmap/url "www.images.com/dog_image.jpg")))

