= Teacher Resources for Math:6-8

== Let's Get Started
- *Online Community* [@link{https://discourse.bootstrapworld.org, Discourse}] -- Talk with other Bootstrap teachers, ask questions, and share ideas!
- *Remote Instruction* [@dist-link{ImplementationNotes.shtml, link}] -- specific recommendations for in-person v. remote instruction.
- *Poster Set for Classroom Walls* [@lesson-link{computing-needs-all-voices/pages/computing-pioneers.adoc, link}] -- This poster set features Pioneers in Computing and Mathematics. For greater impact, engage your students with these materials using our @lesson-link{computing-needs-all-voices} lesson.

== Exercises and Solutions
@all-exercises

== Notes, Slides, and Starter Files
@lesson-info

== Other Curricular Materials

- *Glossary* [@dist-link{Glossary.shtml?pathway=early-math, link}] -- All of the vocabulary words (and their definitions) used in this pathway.
- *Bilingual Glossary of Bootstrap Terms (English-Spanish)* [@dist-link{lib/bilingual-glossary.html, PDF}] -- For teachers with ELL/ESL students, we provide a bilingual glossary for all of the terms used across our curriculum library.

== Textbook Alignment

We offer alignment guides for several popular math textbooks, which make it easy to adopt Bootstrap as part of your normal scope and sequence. These guides are available for:

- Illustrative Math (Grade 6) -- [@link{../../../textbooks/IM-grade-6.html, HTML}, @link{../../../textbooks/IM-grade-6.pdf, PDF}]
- Illustrative Math (Grade 7) -- [@link{../../../textbooks/IM-grade-7.html, HTML}, @link{../../../textbooks/IM-grade-7.pdf, PDF}]
- Illustrative Math (Grade 8) -- [@link{../../../textbooks/IM-grade-8.html, HTML}, @link{../../../textbooks/IM-grade-8.pdf, PDF}]
- Illustrative Math (HS) -- [@link{../../../textbooks/IM-HS.html, HTML}, @link{../../../textbooks/IM-HS.pdf, PDF}]
- Connected Mathematics -- CMP3 (Grade 6) -- [@link{../../../textbooks/cmp-grade-6.html, HTML}, @link{../../../textbooks/cmp-grade-6.pdf, PDF}]
- Connected Mathematics -- CMP3 (Grade 7) -- [@link{../../../textbooks/cmp-grade-7.html, HTML}, @link{../../../textbooks/cmp-grade-7.pdf, PDF}]
- Connected Mathematics -- CMP3 (Grade 8) -- [@link{../../../textbooks/cmp-grade-8.html, HTML}, @link{../../../textbooks/cmp-grade-8.pdf, PDF}]


