[.beta]
= Supervised and Unsupervised Similarity

@description{
Students consider how arbitrary documents (in this case images) can be represented as points in space, and explore different ways to measure the "distance" between those documents using a spatial representation.
}

@lesson-prereqs{measuring-similarity}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives

| Student-facing Lesson Goals
|
- Let's think about ways to represent images as points in space


| Materials
|[.materials-links]
@material-links

|===


== Plotting Images in Space

=== Overview

Students explore ways in which images can be represented as points in space, and how similarity measures can be applied to find "similar" images.

=== Launch
@slidebreak{LaunchR}
@right{@image{images/image-search.png, 400}}

@link{https://images.google.com/, In Google Image Search}, you can drag a picture into the search box and have Google find other, _similar_ images.

@teacher{Give students a demo, using an image of your choice!}

@slidebreak{Launch}
When we asked Google to find images similar to this one, it came back with a lot of similar images! But the computer doesn't have eyes, and it doesn't have the human experience that informs how an image makes us feel.

So how does it even know what "similar" means?

@slidebreak{Launch}
@right{@image{images/computer-vision.jpg, 400}}
Modern ML models are capable of interpreting elements of an image ("person", "car", etc.). This belong to a class of Machine Learning algorithms called "Computer Vision", which relies heavily on more advanced -- and computationally intensive -- concepts that we won't cover here.

Can a @vocab{Data Driven Algorithm} help us re-create Google Image Search, even without the fancy Compute Vision tech?


=== Investigate
@slidebreak{Investigate}
Much like our fast-food restaurants, we can come up with lots of ways to describe an image using numbers:

- Width and height
- Brightness
- Vertical symmetry

What other numbers could be used to describe an image?

@slidebreak{Investigate}

@lesson-instruction{
- Open the @starter-file{ai-image}, and click "Run".
- Complete the first section of @printable-exercise{image-similarity.adoc}
}

@slidebreak{Investigate}

- The _luminance_ of an image is (roughly) a measure of how *bright* it is
- The _entropy_ of an image is (roughly) how *busy* it is

We can use these calculated values to create @vocab{attributes} for each of our images!

@slidebreak{Investigate}
@QandA{
@Q{A table is defined on lines 15-25. What is its name?}
@A{`images`}

@Q{What columns does it have?}
@A{`ID`, `img`, `rating`, and `tags`}

@Q{What are the rows?}
@A{It looks like they each have one of the images defined earlier, then the empty string for `rating` and `tag`}

@Q{What's going on in lines 27-30?}
@A{Some function is defined, which appears to shrink an image. Then it's used to transform the `img` column from `images`, creating a new table called `small-images`}

@Q{What's happening in lines 35-39?}
@A{Four Rows are being defined. All of them have a visible sun.}
}

@slidebreak{Investigate}

For your convenience, we've provided a function that will add all of these attributes (and more!) to the image table:

@center{@show{(contract "decorate-image-table" '("String") "Table")}}

This function consumes a table and the name of the column holding our images, then produces a new table with _all_ of our various attributes computed. Processing large images can be very computationally intensive, and using this function on the original `images` table will get frustrating unless you're on a powerful machine. For this lesson we'll use`small-images` to keep things snappy.

@lesson-instruction{
- Complete the rest of @printable-exercise{image-similarity.adoc}
}

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@right{@image{images/luminance-entropy.png, 300}}
Let's talk about the Luminance-Entropy Space you all created.
@Q{What clusters did you see?}
@A{Snowy mountains on the bottom-right}
@A{High-contrast images on the top-left}

@Q{Are the images with suns __high__-luminance? Why or why not?}
@A{They are surprisingly low luminance, but that makes sense because the part *not* lit by the sun is much darker in every image}

@Q{Are there any other axes that give us good clustering?}
@A{Responses will vary}

@Q{What other axes might we want?}
@A{Responses will vary - but sharp students will want axes for color}
}


== Unsupervised Learning and Bag-of-Words

=== Overview

Student apply what their similarity measures to something the decorated image model they've created.

=== Launch
@slidebreak{Launch}

You've just constructed a @vocab{model} for images, which captures certain information -- luminance, vertical symmetry, etc. -- and throws away the rest. We haven't asked humans to label which images have the sun, grass, or snow in them. Can we still do a decent image search, based solely on the machine-generated attributes? For example, could we choose one of our snow-covered mountains (like `"4"`) and have the computer produce the other (`"5"`)?

@slidebreak{LaunchR}
@ifslide{@right{@image{images/luminance-entropy.png}}}

@lesson-instruction{
- Complete the first section on @printable-exercise{unsupervised-learning.adoc}
}

Luminance-Entropy Space is pretty good for this search, because both of the snowy images are already clustered together, away from the rest.

@center{@show{(code '(angle-similarity decorated2 "4" (list "entropy", "luminance")))}}

Was `simple-similarity` useful? How about `distance-similarity`?

@slidebreak{LaunchR}
@ifslide{@right{@image{images/luminance-entropy.png}}}

It would be really nice to have axes for each color, so we could see how Red, Green, and Blue each image is. If we used `green` as an axis, those grassy images would definitely stand out in that dimension!

@QandA{
Let's take a closer look at `decorated2`, and see if there's anything we can use here.
@Q{What is the `color-names` column about?}
@A{It's the dominant color for every pixel in the image}

@Q{How could we generate numbers from the `color-names` columns?}
@A{Answers will vary, but hopefully students will suggest counting the occurrences of each color}
}

@slidebreak{Launch}
*We could count the number of reds, greens and blues in `color-names`!*

We don't really care about the _order_ of those words - we just want to know how many pixels are red-dominant, green-dominant, or blue-dominant!

In the Definitions Area, define a new table:

@show{(code '(define decorated-bag (add-bag-cols decorated "color-names")))}

What did you get back?

=== Investigate
@slidebreak{InvestigateR}
@right{@image{images/bag-of-colors.png, 150}}

Without the order of the words, it's as if we just put all the words into a sack and shook it. The information about _frequency_ of each word is still there, but we've lost the order. Machine Learning Engineers call this a @vocab{bag-of-words model}.

@lesson-instruction{
- Complete the second section on @printable-exercise{unsupervised-learning.adoc}
- What axes would you use to get the best clustering?
- Be ready to share your answer!
}


@slidebreak{InvestigateR}
@right{@image{images/luminance-entropy-green.png, 300}}
Luminance-Green Space was great for finding our grassy images, but not as good for the snowy ones. We want our Image Search to work for _both_ kids of images!

We know that the grassy images cluster along the `"green"` axis, and the snowy ones cluster along the `"blue"` axis. Blue-Green Space is a good candidate for solving our problem! But then a user might want to search for pictures with the sun...

@slidebreak{InvestigateR}
@ifslide{@right{@image{images/luminance-entropy-green.png, 300}}}

Think back to our burger-and-fries example: there _may_ be other clusters in other dimensions. We just cant see them because we're only looking in 2 dimensions! There's no reason we can't add all three dimensions here, or four, or five, etc!

Our image scatter plots for Luminance-Green and Luminance-Entropy are just _projections_ of higher-dimensional data.

@lesson-instruction{
- Suppose we want to find images similar to Image 7. What columns would be most useful?
- Complete @printable-exercise{unsupervised-learning.adoc}!
}

=== Synthesize
@slidebreak{Synthesize}

@QandA{
@Q{Which columns were most helpful to your search results?}
@Q{Were there any columns that didn't seem to affect the search results?}
@Q{Were any columns actually _harmful?_}
}

== Supervised Learning

=== Overview
Having seeing the power -- and limits -- of unsupervised learning, students explore what it means to pair machine-learning algorithms with human-tagged data. They learn about centroids and the connection to measures of center, and use that concept to build recommendation systems and tag-based testing of images.


=== Launch
@slidebreak{Launch}

...limitations of the system...

(1) can only find similarity to one document...
(2) it doesn't actually know about human experience so it's limited......

@slidebreak{Launch}

Suns are hard in this dataset, because they're so different. What we want is something that connects _all_ the suns.


=== Investigate
@slidebreak{Investigate}

@lesson-instruction{
Calculate the sun centroid on @printable-exercise{supervised-learning.adoc}
}


@slidebreak{InvestigateR}
@right{@image{images/centroid.png}}

We've created a function in Pyret to calculate centroids for you:

@show{(contract "add-centroid" '(Table, String, List<String>) "Table")}

Calculate the sun-centroid in Pyret:

@show{(code '(add-centroid decorated2 "sun" (list: 0, 6, 7, 8)))}

@slidebreak{Investigate}
The whole centroid thing is powerful, because now we can add human information.

- We can find a centroid for all the _liked_ images, and make better recommendations.
- We can find a centroid for all the images with a tag, and use that to find other images that haven't been tagged

@show{(contract "likes" '(Table) "List<String>")}
@show{(contract "dislikes" '(Table) "List<String>")}
@show{(contract "tagged" '(Table String) "List<String>")}


@slidebreak{Investigate}
What will each of these do?

@show{(coe (add-centroid decorated2 "liked" (likes decorated2)))}
@show{(coe (add-centroid decorated2 "disliked" (dislikes decorated2)))}
@show{(coe (add-centroid decorated2 "sun" (tagged decorated2 "sun")))}

@lesson-instruction{
Do more stuff on @printable-exercise{supervised-learning.adoc}
}

@slidebreak{Investigate}
A recommendation system is just similarity-to-liked - similarity-to-disliked.

@slidebreak{Investigate}
Image search is just similarity-to-tagged.

=== Synthesize