= Exploring Displays

Use your contracts page and the Animals Starter File to make each type of display below in code.pyret.org. Fill in the information below for each chart you make and be sure to add examples of the code you use to your contracts page!

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Pie Charts | Bar Charts
| @vspace{38ex} Sketch a pie chart here | @vspace{38ex} Sketch a bar chart here
| 
--
@span{.left}{
Pie charts are constructed from @fitb{1ex}{1} column(s), and show *categorical* data.

@vspace{1ex}

@span{.left}{What do you think this display tells us?

@vspace{1ex}

@fitb{55ex}{}

@vspace{1ex}

@fitb{55ex}{}
}
--

| 
--
@span{.left}{
Bar charts are constructed from @fitb{3ex}{} column(s), and show @fitb{28ex}{} data.

@vspace{1ex}
@span{.left}{What do you think this display tells us?

@vspace{1ex}

@fitb{55ex}{}

@vspace{1ex}

@fitb{55ex}{}
}
--
|===

@vspace{3ex}

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Box Plots | Histograms
| @vspace{38ex} Sketch a box plot here | @vspace{38ex} Sketch a histogram here
| 
--
@span{.left}{
Box plots are constructed from @fitb{3ex}{} column(s), and show @fitb{28ex}{} data.

@vspace{1ex}

@span{.left}{What do you think this display tells us?

@vspace{1ex}

@fitb{55ex}{}

@vspace{1ex}

@fitb{55ex}{}
}
--

| 
--
@span{.left}{
Histograms are constructed from @fitb{3ex}{} column(s), and show @fitb{28ex}{} data.

@vspace{1ex}

@span{.left}{What do you think this display tells us?

@vspace{1ex}

@fitb{55ex}{}

@vspace{1ex}

@fitb{55ex}{}
}
--
|===
