= Exploring Displays

For each type of display, fill in the information below.

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Pie Charts | Bar Charts
| @vspace{38ex} Sketch a pie chart here | @vspace{38ex} Sketch a bar chart here
| 
--
@span{.left}{
Pie charts are constructed from @fitb{1ex}{1} column(s), and show *categorical* data.
What do you think this display tells us?
@fitb{55ex}{}
@fitb{55ex}{}
@fitb{55ex}{}
}
--

| 
--
@span{.left}{
Bar charts are constructed from @fitb{3ex}{} column(s), and show @fitb{28ex}{} data.
What do you think this display tells us?
@fitb{55ex}{}
@fitb{55ex}{}
@fitb{55ex}{}
}
--
|===

@vspace{3ex}

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Box Plots | Histograms
| @vspace{38ex} Sketch a box plot here | @vspace{38ex} Sketch a histogram here
| 
--
@span{.left}{
Box plots are constructed from @fitb{3ex}{} column(s), and show @fitb{28ex}{} data.
What do you think this display tells us?
@fitb{55ex}{}
@fitb{55ex}{}
@fitb{55ex}{}
}
--

| 
--
@span{.left}{
Histograms are constructed from @fitb{3ex}{} column(s), and show @fitb{28ex}{} data.
What do you think this display tells us?
@fitb{55ex}{}
@fitb{55ex}{}
@fitb{55ex}{}
}
--
|===
