= Exploring Periodic Functions
////
* Import Desmos Styles
*
* This includes some inline CSS which loads the Desmos font,
* which includes special glyphs used for icons on Desmos.com
*
* It also defines the classname '.desmosbutton', which is used
* to style all demos glphys
*
* Finally, it defines AsciiDoc variables for glyphs we use:
* {points}
* {caret}
* {magnifying}
* {wrench}
*
* Here's an example of using these:
* This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}

For this page, you'll need to load @starter-file{alg2-exploring-periodic-desmos} open on your computer.

Periodic models with @math{sin} have the form @math{f(x) = a \sin(b(x - d)) + c}. You will find this function on your screen in Desmos, along with four sliders for @math{a}, @math{b}, @math{c}, and @math{d}.

== Amplitude

@n The graph of the @math{f} goes up and down, going as high as @fitb{2em}{@ifsoln{10}} and as low as @fitb{2em}{@ifsoln{-10}}. On the left, the slider for @math{a} is set to @fitb{2em}{@ifsoln{10}}.

@n *Try adjusting the slider for @math{a}*. How does that affect the graph of the function? @fitb{}{} +
@fitb{}{@ifsoln{Higher values of @math{a} make the waves reach higher and lower extremes. Lower values make the peaks and valleys shorter}}

