= Exploring Periodic Data
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
td:last-child { padding-top: 0; padding-bottom: 0; }
td { color: inherit !important; }
body .center { padding: 0; }
</style>
++++
_For this page, you'll need to have the @starter-file{alg2-covid} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you._

Your physics teacher comes back from a trip to England and keeps raving about some amazing ride they took. The class keeps asking them for details: was it a rollercoaster? bumper cars? Being a teacher, they decide to turn your casual curiosity into a _learning experience_, and shares some data they recorder from their smart watch:

TODO: Image https://openclipart.org/detail/333810/ferris-wheel-isolated


[cols=1a,1a]
|===
| `time` (ft)   | `height` (ft)
| 0             | 0
| 7.5           | 225
| 15            | 450
| 22.5          | 225
| 30            | 0
| 37.5          | 225
| 45            | 450
| 52.5          | 225
| 60            | 0
|===

@n What do you Notice about this data? @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n What do you Wonder? @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@ There's a clear relationship between `time` and `height`. Is it Linear? Quadratic? Something else?

TODO - make scatter plot, then line plot
