= Exploring Periodic Data
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
td { padding: 0 !important; }
table table td { color: inherit !important; padding: 5px 0 !important; }
body .center { padding: 0; }
.directions p { line-height: 1.75 !important; }
.fitb { min-width: 2em; }
</style>
++++

@vspace{1ex}

[cols="<.<1a,>.^2a", grid="none", frame="none"]
|===
|
[cols="^1a,^1a", options="header"]
!===
! `time` (minutes)  ! `altitude` (feet)
!  0				!   5.0
!  5				!  55.0
! 10				! 154.9
! 15				! 205.0
! 20				! 155.2
! 25				!  55.2
! 30				!   5.0
! 35				!  54.7
! 40				! 154.6
! 45				! 205.0
! 50				! 155.5
! 55				!  55.5
! 60				!   5.0
!===

|
@ifnotsoln{ @image{../images/blank-scatter-plot.png, 450} }
@ifsoln{    @image{../images/rides-combined-plot.png, 450} }
|===

@n What do you Notice about the data in the table? @fitb{}{@ifsoln{Time keeps going up, but altitude goes up and down, over and over. Altitude goes from}} +
@fitb{}{@ifsoln{5 feet to 205 feet, then back down and up again. It takes 30m for the altitude to return to the high or low point}} +
@fitb{}{}

@n What do you Wonder? @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n The ride goes from @fitb{4em}{@ifsoln{5}}feet (lowest) to @fitb{4em}{@ifsoln{205}}feet (highest) in @fitb{4em}{@ifsoln{15}}minutes, then takes @fitb{4em}{@ifsoln{15}}minutes to go back down.

@n The ride reaches its highest point every @fitb{4em}{@ifsoln{30}}minutes, and its lowest point every @fitb{4em}{@ifsoln{30}}minutes.

@vspace{1ex}

@center{*Plot each of the points in the table (left) on the coordinate plane (right) to create @vocab{scatter plot}.*}

@center{*Use your contracts table to create a @vocab{line graph}, then update your scatter plot to turn it into a line graph*}

@n Do you see a relationship between `time` and `altitude`? Why or why not? If you do, what *kind* of relationship is it (linear, exponential, etc.)? @fitb{}{@ifsoln{Yes - there's definitely a pattern here, but it doesn't look linear, quadratic, exponential, or logarithmic!}} +
@fitb{}{} +
@fitb{}{}

@n What kind of ride do you think your teacher was on, and why? @fitb{}{@ifsoln{a Ferris wheel, because that's the only kind of ride that goes up and down}} +
@fitb{}{@ifsoln{at regular intervals}} +
@fitb{}{}
