= Graphing Periodic Models: Frequency (𝐵)

++++
<style>
.FillVerticalSpace { grid-gap: 40px; margin: 25px 0; }

td {
  border: none !important;
  background-image:
    linear-gradient(lightblue 2px, transparent 2px),
    linear-gradient(270deg, lightblue 2px, transparent 2px),
    linear-gradient(rgba(150, 150, 150, .3) 1px, transparent 0px),
    linear-gradient(270deg, rgba(150, 150, 150, .3) 1px, transparent 1px);
  background-size: 300px 300px, 300px 300px, 50px 50px, 50px 50px;
  background-position: -150px 135px;
  max-height: 3.2in;
  max-width: 3.2in;

}

td p.tableblock { position: absolute; }

/* Add labels for axes */
td::before, td::after { display: flex; font-style: italic; }
td::before {
  content: 'y';
  justify-content: center;
  align-items: center;
  margin-right: 2em;
  margin-top: -10em;
    -webkit-transform:rotate(270deg);
    -moz-transform:rotate(270deg);
    -o-transform: rotate(270deg);
    -ms-transform:rotate(270deg);
    transform: rotate(270deg);
}
td::after {
  content: 'x';
  align-items: start;
  justify-content: right;
  margin-top: 2em;
  margin-right: -0.5em;
}
</style>
++++
The standard form of a periodic model is @math{f(x) = a sin(b⋅(x - h)) + k}. On this page, we'll explore the role of @vocab{amplitude} @math{a} in periodic functions. @link-instructions{Open the Desmos File *Exploring Periodic Functions*. You should be on *Slide 2: Graphing Periodic Models* and see four sliders for @math{a}, @math{b}, @math{h}, and @math{k}.}

@n Setting *@math{a=1}, @math{h=0}, and @math{k=0}*, change @math{b} to 4, 2, 1, and 0.5, graphing each curve below. **For each curve, label the two highest points to the RIGHT of the origin.**

[.FillVerticalSpace, cols="1,1", frame="none"]
|===
| @math{b=4}  | @math{b=2}
| @math{b=1}  | @math{b=0.5}
|===

*The distance between two adjacent @vocab{peaks} or @vocab{troughs} is called the @vocab{period}: the interval over which the pattern repeats itself.*

@n What is the @vocab{period}
             when *@math{b=4}*?   @fitb{6em}{@ifsoln{@math{pi}}}
@hspace{1em} when *@math{b=2}*?   @fitb{6em}{@ifsoln{@math{pi}}}
@hspace{1em} When *@math{b=1}*?   @fitb{6em}{@ifsoln{@math{2pi}}}
@hspace{1em} When *@math{b=0.5}*? @fitb{}{@ifsoln{@math{4pi}}}

@n As the @vocab{frequency} (@math{b}) goes UP, the @vocab{period} @fitb{11em}{@ifsoln{decreases / goes down}}. @hspace{1em} As the @vocab{frequency} (@math{b}) goes DOWN, the @vocab{period} @fitb{}{@ifsoln{increases / goes up}}
