= Graphing Periodic Models: Horizontal/Phase Shift (𝒽)

++++
<style>
.graph td {
  width: 3.2in;
  height: 3in;
}
.graph td::before { left: 47% !important; }
.graph td::after { top: 47% !important; }
</style>
++++

The standard form of a periodic model is @math{f(x) = a sin(b⋅(x - h)) + k}. On this page, we'll explore the role of @vocab{amplitude} @math{a} in periodic functions. @link-instructions{Open the Desmos File *Exploring Periodic Functions*. You should be on *Slide 2: Graphing Periodic Models* and see four sliders for @math{a}, @math{b}, @math{h}, and @math{k}.}

@n Setting *@math{a=1}, @math{b=1}, and @math{k=0}*, change the value of @math{h} to @math{-\pi}, @math{\pi}, and @math{\pi/2} (roughly 1.57), graphing each curve in the squares below. **For each curve, label the two coordinates where the function crosses the x-axis closest to the origin**

[.FillVerticalSpace.graph, cols="1,1", frame="none"]
|===
| @math{h=-\pi} | @math{h=\pi}  | @math{h=\pi/2}  | @math{h=1{1 \over 2}\pi}
|===

@n Describe the change in the graph when @math{h} _increases_: @fitb{}{@ifsoln{the graph shifts right}}

@n Describe the change in the graph when @math{h} _decreases_: @fitb{}{@ifsoln{the graph shifts left}}

@n Describe the change in the graph when @math{h} changes by multiples of @math{2\pi}: @fitb{}{@ifsoln{the graph doesn't change!}} +
@fitb{}{}
