= Graphing Periodic Models: Frequency (𝐵)

++++
<style>
.graph td {
  width: 3.2in;
  height: 3in;
}
.graph td::before { left: 47% !important; }
.graph td::after { top: 47% !important; }
</style>
++++

The standard form of a periodic model is @math{f(x) = a sin(b⋅(x - h)) + k}. On this page, we'll explore the role of @vocab{amplitude} @math{a} in periodic functions. @link-instructions{Open the Desmos File *Exploring Periodic Functions*. You should be on *Slide 2: Graphing Periodic Models* and see four sliders for @math{a}, @math{b}, @math{h}, and @math{k}.}

@n Setting *@math{a=1}, @math{h=0}, and @math{k=0}*, change @math{b} to 4, 2, 1, and 0.5, graphing each curve below. **For each curve, label the two highest points to the RIGHT of the origin.**

[.FillVerticalSpace.graph, cols="1,1", frame="none"]
|===
| @math{b=4}  | @math{b=2}
| @math{b=1}  | @math{b=0.5}
|===

*The distance between two adjacent @vocab{peaks} or @vocab{troughs} is called the @vocab{period}: the interval over which the pattern repeats itself.*

@n What is the @vocab{period}
             when *@math{b=4}*?   @fitb{6em}{@ifsoln{@math{pi}}}
@hspace{1em} when *@math{b=2}*?   @fitb{6em}{@ifsoln{@math{pi}}}
@hspace{1em} When *@math{b=1}*?   @fitb{6em}{@ifsoln{@math{2pi}}}
@hspace{1em} When *@math{b=0.5}*? @fitb{}{@ifsoln{@math{4pi}}}

@n As the @vocab{frequency} (@math{b}) goes UP, the @vocab{period} @fitb{11em}{@ifsoln{decreases / goes down}}. @hspace{1em} As the @vocab{frequency} (@math{b}) goes DOWN, the @vocab{period} @fitb{}{@ifsoln{increases / goes up}}
