= Modeling the Ferris Wheel Data
++++
<style>
.studentAnswerMedium { min-width: 70pt !important; }
.studentAnswerLong { min-width: 96pt !important; }
.codetwo { background: none; }
table { margin-top: 5px; }
table tr td { padding: .3em .625em; }
</style>
++++
////
* Import Desmos Styles
*
* This includes some inline CSS which loads the Desmos font,
* which includes special glyphs used for icons on Desmos.com
*
* It also defines the classname '.desmosbutton', which is used
* to style all demos glphys
*
* Finally, it defines AsciiDoc variables for glyphs we use:
* {points}
* {caret}
* {magnifying}
* {wrench}
*
* Here's an example of using these:
* This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}

== Modeling with @math{sin}

For this section, you'll need to load @starter-file{alg2-exploring-periodic-desmos} opened to the __second__ slide ("Modeling the Ferris Wheel Dataset (sin)").

You'll find the data from the Ferris Wheel plotted in red, along with a basic periodic model of the form @math{f(x) = a \sin(b(x - d)) + c}.

@n Use the sliders to estimate the best periodic fit.

@n The @vocab{peaks} are at @fitbruby{8em}{@ifsoln{205}}{feet}, @vocab{troughs} are at @fitbruby{8em}{@ifsoln{5}}{feet}, @vocab{midline} is at @fitbruby{8em}{@ifsoln{105}}{feet} and the @vocab{amplitude} is @fitbruby{7em}{@ifsoln{100}}{feet}

@n The @vocab{period} of the data is @fitbruby{10em}{@ifsoln{30}}{minutes}. @hspace{3em} If @math{\mbox{period} = {2\pi \over \mbox{frequency}}}, what is the @vocab{frequency}? @fitbruby{10em}{@ifsoln{0.209}}{cycles per minute}

@n Adjust the slider for horizontal shift to find the best fit, then write your model below in Function and Pyret notation. **Express @math{d} in terms of @math{pi}.**

[cols="1a, .>10a", frame="none", stripes="none"]
|===
| *Function Notation*
|
@hspace{2em}
@math{f(x) =} @fitbruby{70pt}{@ifsoln{100}}{amplitude} @math{\times}
@math{sin}(
 @fitbruby{70pt}{@ifsoln{0.209}}{frequency} (x - @fitbruby{70pt}{@ifsoln{@math{2.375pi}}}{h-shift})
) + @fitbruby{70pt}{@ifsoln{105}}{v-shift}

| @vspace{1ex} +
*Pyret Notation*
|
@show{(code '(define (f x) (+ (* (?ANS 100) (sin (* (?ANS 0.21) (- x (?ANS (* 2.375 PI)))))) (?ANS 105))))}
|===

== Translating from @math{sin} to @math{cos}

For this section, you'll need to switch to the _third_ slide ("Translating from sin to cos"). You'll see a function f(x) defined here graphed in red, which uses @math{cos} instead of @math{sin}.

@n Adjust the sliders so that the function @math{g} perfectly overlaps the function @math{f}. What is the value of @math{a}? @fitb{5em}{@ifsoln{10}} @math{b}? @fitb{5em}{@ifsoln{1}} @math{c}? @fitb{}{@ifsoln{2}}

@n What was the value of @math{d}, expressed as a decimal? @fitb{12em}{@ifsoln{~1.570796...}} What was the value of @math{d}, expressed a fraction of @math{pi}? @fitb{}{@ifsoln{@math{pi/2}}}

@n Change the definition of @math{f} in Desmos to use two different amplitudes, frequencies, and/or vertical shifts. Write down both variations in the table below, and then adjust the definition of @math{g} to match.

[cols="10a,10a,5a"]
|===
| *Function using @math{sin}* | *Function using @math{cos}* | **Vertical Shift @math{d}**
| @math{f(x) =}               | @math{g(x) =}               |
| @math{f(x) =}               | @math{g(x) =}               |
|===

@n Do you think that all basic cosine functions can be expressed as sine functions? Why or why not? @fitb{}{} +
@fitb{}{}

== Modeling with @math{cos}
To see how this applies to the Ferris Wheel, switch to the _fourth_ slide ("Modeling the Ferris Wheel Dataset (cos)").


@n Translate your @math{sin}-based model to a @math{cos}-based one. Express the horizontal shift in terms of @math{pi}.

[cols="1a, .>10a", frame="none", stripes="none"]
|===
| *Function Notation*
|
@hspace{2em}
@math{g(x) =} @fitbruby{70pt}{@ifsoln{100}}{amplitude} @math{\times}
@math{cos}(
 @fitbruby{70pt}{@ifsoln{0.21}}{frequency} (x - @fitbruby{70pt}{@ifsoln{@math{4.75pi}}}{h-shift})
) + @fitbruby{70pt}{@ifsoln{105}}{v-shift}

| @vspace{1ex} +
*Pyret Notation*
|
@show{(code '(define (g x) (+ (* (?ANS 100) (cos (* (?ANS 0.209) (- x (?ANS (* 4.75 PI)))))) (?ANS 105))))}
|===
