= Reasoning about Unit Clocks
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
td { padding: 0 !important; height: 20pt; }
table { cell-spacing: 10px; }
body .center { padding: 0; }
.directions p { line-height: 1.75 !important; }
.fitb { min-width: 2em; }
</style>
++++

The questions on this page deal with a _unit clock_ (shown below, on the right). A point (x, y) sits on the circumference of the clock. A radius of length 1, extending from the center to (x, y), forms an angle @math{θ} with the x-axis. As time passes, the point (x, y) rotates around the circle.

[cols="<.<9a,1,>.^5a", grid="none", frame="none"]
|===
|
@n What are the coordinates of the *center* of the clock? @fitb{}{@ifsoln{(0, 0)}}

@n How long is the *hypotenuse* of the right-triangle formed by x, y, and @math{r}? @fitb{}{@ifsoln{1}}

@vspace{1ex}

@n At what times is @math{x} the largest? @fitb{5em}{3 and 9} @hspace{1em} What about @math{y}? @fitb{}{12 and 6}

@n @math{x^2 + y^2 = } @fitb{4em}{@ifsoln{1}} for every possible value of @math{x} and @math{y} on the circumference.

@vspace{1ex}

@n At 12:00, @math{(x, y)} is at (0, 1). *Fill in @math{(x, y)} for 3, 6 and 9 o'clock in the table below.*

|
| @image{../images/unit-circle-clock.png}
|===

@define{leg}{@math{\sqrt{2}/2}}

[cols="^.^1a, ^.^1a, ^.^1a"]
|===
| 		"Time"	| x-coordinate 		| y-coordinates

| 		 12:00	|       0     		|      1
|		  1:30	| @ifsoln{ @leg}	| @ifsoln{ @leg}
|  		  3:00	| @ifsoln{  1  }   	| @ifsoln{  0  }
|@ifsoln{ 4:30}	| @ifsoln{ @leg}	| @ifsoln{-@leg}
|  		  6:00	| @ifsoln{  0  }   	| @ifsoln{ -1  }
|@ifsoln{ 7:30}	| @ifsoln{-@leg}	| @ifsoln{-@leg}
|  		  9:00	| @ifsoln{ -1  } 	| @ifsoln{  0  }
|@ifsoln{10:30}	| @ifsoln{-@leg}	| @ifsoln{ @leg}
| 		 12:00	|       0     		|      1
|===

@n At 1:30, the right triangle formed by x, y, and @math{r} has an angle of @fitb{3em}{@ifsoln{45°}}, @math{x =} @fitb{11em}{@ifsoln{@math{\sqrt{2}\over 2} or 0.7071}} and @math{y =} @fitb{}{@ifsoln{@math{\sqrt{2}\over 2} or 0.7071}}

@n At what _other_ times does this occur? @fitb{10em}{@ifsoln{4:30, 7:30 and 10:30}} **Fill in the empty cells of the table above for each of these times!**

@vspace{1ex}

@center{The graph below has _length_ on the y-axis (from -1 to 1), and _hours_ on the x-axis.}

@n **What is the relationship between @math{\mbox{Time}} and @math{x}?** Draw a dot to mark the value of *@math{x}* at each of the times from the table above, then connect the dots with a *solid* line to graph the function _x(time)_.

@n **What is the relationship between @math{\mbox{Time}} and @math{y}?** Draw a dot to mark the value of *@math{y}* at each of the times from the table above, then connect the dots with a *dashed* line to graph the function _y(time)_.

@vspace{1ex}

@ifnotsoln{@image{../images/clock-graph.png}}
@ifsoln{@image{../images/clock-graph-soln.png}}

@n Open the first slide in @starter-file{alg2-exploring-periodic-desmos}, "turn on" the @math{x(time)} folder, and compare the graph to the one you drew.

@n Turn off that first folder, and turn on the one for @math{y(time)}. Compare the graph to your own.
