= Reasoning about Unit Clocks
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
td { padding: 0 !important; height: 20pt; }
table { cell-spacing: 10px; }
body .center { padding: 0; }
.directions p { line-height: 1.75 !important; }
.fitb { min-width: 2em; }
.autonum { padding-top: 0.75rem !important; }

/* the .fitb's on this page that contain MathJax inside their solutions need their top-padding clipped */
.fitb:has(.solution .MathJax) { padding-top: 0; }

</style>
++++

The questions on this page deal with a _unit clock_ (shown below, on the right). A point (A, B) sits on the circumference of the clock. A radius of length 1, extending from the center to (A, B), forms an angle @math{θ} with the x-axis. As time passes, the point (A, B) rotates around the circle.

[cols="<.<9a,1,>.4a", grid="none", frame="none"]
|===
|
@n What are the coordinates of the *center* of the clock? @fitb{}{@ifsoln{(0, 0)}}

@n How long is the *hypotenuse* of the right-triangle formed by A, B, and @math{r}? @fitb{}{@ifsoln{1}}

@n Identify the x and y-coordinates for (A, B) at 3, 6 and 9 o'clock and add them to the table below. (The coordinates for 12 o'clock have been done for you!)

@n On the graph below, draw a *dot* for each value in the A column, using the _time_ as the x-coordinate and the value of A as the y-coordinate. Use a *pencil* to connect these dots.

@n On the graph below, draw a *star* for each value in the B column, using the _time_ as the x-coordinate and the value of B as the y-coordinate. Use a *pencil* to connect these stars.

@n On the clock to the right, what time is the hand pointing to at (A,B)? @fitb{4em}{@ifsoln{1:30}}. +
At this time, @math{A = B}. In the space below, compute the value of @math{A} and @math{B}.

|
| @image{../images/unit-circle-clock.png}
|===

@define{leg}{@math{\sqrt{2}/2}}

[cols="^.^1a, ^.^1a, ^.^1a", options="header"]
|===
| "Time"| @math{A} (x-distance)| @math{B} (y-distance)
| 12:00	|       0     		|      1
| 1:30	| @ifsoln{ @leg}	| @ifsoln{ @leg}
| 3:00	| @ifsoln{  1  }   	| @ifsoln{  0  }
| 4:30	| @ifsoln{ @leg}	| @ifsoln{-@leg}
| 6:00	| @ifsoln{  0  }   	| @ifsoln{ -1  }
| 7:30	| @ifsoln{-@leg}	| @ifsoln{-@leg}
| 9:00	| @ifsoln{ -1  } 	| @ifsoln{  0  }
| 10:30	| @ifsoln{-@leg}	| @ifsoln{ @leg}
| 12:00	|       0     		|      1
|===

@n Fill in the values of @math{A} and @math{B} at 4:30, 7:30, and 10:30.

@n Mark the new coordinates for @math{A} with *dots* in the graph below, then adjust your A-line so it passes through them.

@n Mark the new coordinates for @math{A} with *stars* in the graph below, then adjust your B-line so it passes through them.

@vspace{1ex}

@ifnotsoln{@image{../images/clock-graph.png}}
@ifsoln{@image{../images/clock-graph-soln.png}}

@vspace{1ex}

@link-instructions{Open the Desmos File *Exploring Periodic Functions*. You should be on *Slide 1: Unit Clocks*.}

@n "Turn on" the `x(time)` folder, and compare the graph to your own graph of `A`. Do they match?

@n Turn off that first folder, and turn on the one for `y(time)`. Compare the graph to your own graph of `B`. Do they match?
