= Exploring the Countries Dataset

For this page, you'll need to the  @online-exercise{https://code.pyret.org/editor#share=1StX6mmWMYPQOpH8ab1WiAlvPYeMlMEAD, Countries of the World Starter File} open on your computer. If you haven't already, select **Save a Copy** from the "File" menu to make a copy of the file that's just for you.

@n Click "Run", and evaluate `countries-table` in the Interactions Area. Take a close look at each column, and make sure you understand what they mean.

@n This file contains some code that you may not have seen before! On lines 10 and 11, the variables `afghanistan` and `albania` are defined. Try typing these into the Interactions Area. What do they evaluate to?

@fitb{}{@ifsoln{Rows for two countries in the table}}

@vspace{1ex}

The countries table has a column for GDP ("how much a country makes") and another for population ("how many people there are"). **We want to use these columns to compute how much __each person makes, on average__ - also known as the per-capita gdp.**

@n Compute the per-capita gdp for Angola. Show your work: @fitb{}{}

@n Read lines 17-22, where a new function is defined. Use this function in the Interactions Area, by typing `pc-income(angola)`. What do you think this function does?

@fitb{}{@ifsoln{it computes the per-capita income of a country by dividing gdp by population}}

@fitb{}{}

@fitb{}{}

@n This code also defines a new Table using a function called `build-column`. Read lines 24 and 25, then evaluate `countries2` in the Interactions Area. What does `build-column` do?

@fitb{}{@ifsoln{it makes a new table, taking the old one and adding a column called `income`}}

@fitb{}{@ifsoln{it fills this column using the `pc-income` function}}

@fitb{}{}


@n Make a scatter plot showing the relationship between `income` and `median-lifespan`. Do you see a correlation? Describe it, in terms of linear/nonlinear and strong/weak.

@fitb{}{@ifsoln{There seems to be a moderate or strong, nonlinear correlation}}

@fitb{}{}

@n What's the best model you can build? In the table below, record your models and the @math{R^2} values you got for them.

[.FillVerticalSpace, cols="^1a, ^1a", options="header"]
|===
| Model (Function or Pyret Notation - whatever you prefer!)   | @math{R^2}
|                                                             |
|===
