= Defining Values

@description{Students learn to improve readability, performance and maintanability of code by defining values that repeat in code, just as we would define variables in math.}

@lesson-prereqs{contracts}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to:

* Define @vocab{values} of various types
* Simplify a complex expression by replacing repeated parts with defined names,
* Explain why @vocab{variable}s are useful in math and programming

| Student-facing Goals
|
* Let's learn how to clean up complex code by defining @vocab{values} for repeated expressions
* Let's learn why @vocab{variables} are useful in math and programming

| Materials
|[.materials-links]

@material-links

| Key Points For The Facilitator
|
* Learning how to define values is a big milestone! It will be used consistently throughout other lessons, so be sure to give students plenty of time to practice this new skill.
* Check frequently for understanding of @vocab{data types} and @vocab{Contract}s during this lesson and throughout subsequent lessons.
|===

== What's in Common? @duration{30 minutes}

=== Overview
This activity introduces the problem with duplicate code, leveraging *Mathematical Practice 7 - Identify and Make Use of Structure*. Students identify a common structure in a series of expressions, and discover how to bind that expression to a name that can be re-used.

@ifproglang{pyret}{Note that in Pyret definitions work the way variable substitution does in math, as opposed to variable assignment you may have seen in other programming languages.}

=== Launch

Invite students to take a look at the expressions below:

@ifproglang{wescheme}{

```
(star 50 "solid" "green")
(scale 3 (star 50 "solid" "green"))
(scale .5 (star 50 "solid" "green"))
(rotate 45 (star 50 "solid" "green"))
(rotate 45 (scale 3 (star 50 "solid" "green")))
```
}

@ifproglang{pyret}{
```
star(50, "solid", "green")
scale(3, star(50, "solid", "green"))
scale(0.5, star(50, "solid", "green"))
rotate(45, star(50, "solid", "green"))
rotate(45, scale(3, star(50, "solid", "green")))
```
}

[.lesson-instruction]
- What code do they all have in common?
** @ifproglang{wescheme}{`(star 50 "solid" "green")`}@ifproglang{pyret}{`star(50, "solid", "green")`}
- What would happen if you were asked to change the color of all the stars to gold?
** _We'd have to change the color everywhere it appeared._

[.lesson-point]
Duplicate code is almost always bad!

There are lots of potential problems with duplicate code:

- *Readability:* The more code there is, the harder it can be to read.
- *Performance:* Why re-evaluate the same code a dozen times, when we can evaluate it _once_ and use the result as many times as we need?
- *Maintainability:* Suppose we needed to change the size of the stars in the examples above. We would have to make sure every line is changed, which leaves a lot of room for error.

Since we're using that star over and over again, wouldn't it be nice if we could define a "nickname" for that code, and then use the nickname over and over in place of the expression? And then, if we wanted to change something about all of the stars, we would only have to make the change once, in the definition.

--
You already know how to do this in math:

[.indentedpara]
@math{x = 4} _defines_ the nickname @math{x} to be the value 4.
--

@ifproglang{wescheme}{
--
WeScheme uses the word "define" to make this even clearer!

[.indentedpara]
We can type `(define x 4)` to define `x` to be the value 4.
--
}

@ifproglang{pyret}{
--
Pyret is no different!

[.indentedpara]
We type `x = 4` to define `x` to be the value 4.
--
}

Once we've defined `x` to be the value 4 and clicked "Run", anytime we use `x`, the computer will remember that it is _defined_ as 4.  We can _use_ that definition to get an answer. For example, @math{x + 2} will evaluate to 6.

Of course, the whole point of defining a value is so that it sticks around and can be used later! That's why programmers put their definitions on the _left-hand side_, known as the *Definitions Area*.

=== Investigate

[.lesson-instruction]
- Open the @starter-file{defining-values} and complete @printable-exercise{pages/defining-values-explore.adoc} with your partner.
- Add some definitions of your own in the Definitions Area. Be sure to click "Run" again before you try testing them out.
- Complete @printable-exercise{which-value-to-define.adoc}.

=== Synthesize

- What data types can we define values for?
** _All of them - Number, String, Image_
- What values did you decide to define? When might they be useful?


[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Support for English Language Learners}

MLR 8 - Discussion Supports: As students discuss, rephrase responses as questions and encourage precision in the words being used to reinforce the meanings behind some of the programming-specific language, such as "define" and "value".
|===

== Using Defined Values

=== Overview
Now that we know _how_ to define values, we've got two more things to consider:

* When it would be _useful_ to define them?
* How do we _use_ them once we've defined them?

=== Launch

[.lesson-instruction]
Complete @printable-exercise{chinese-flag.adoc}.

Note: The above worksheet will direct students to open the @starter-file{flags-china} once they complete the first half of the questions.

=== Investigate

[.lesson-instruction]
--
- Open a new file in @starter-file{editor} and name it `sunny`, then turn to @printable-exercise{pages/coe-why-define-values.adoc}
- The first row of the table has been completed for you. What is happening in that first row?
** _The original Circle of Evaluation has been simplified by using a defined value `sunny`._
- What code is being replaced by `sunny`?
** @show{(code '(radial-star 30 20 50 "solid" "yellow"))}
- Write the code on the line provided in question 2. Then type it into the Interactions Area and click "Run".
- Define the value `sunny` in the Definitions Area.
- Complete the page and test your code in the editor.
--

=== Synthesize

- Why is defining values useful?
** _Defining values allows the programmer to reuse code and make changes easily. It allows us to more easily use elements inside other functions, and it saves time!_

== Additional Exercises

* @printable-exercise{pages/writing-code-using-defined-values.adoc}
@ifproglang{wescheme}{
* @opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5ff46882e3b4660c751f707e?collections=5fbecc2b40d7aa0d844956f0, Matching Code to Images using overlay & put-image}
}
@ifproglang{pyret}{
* @opt-online-exercise{https://teacher.desmos.com/activitybuilder/custom/5fc90f1289c78e0d2a5bccfc, Matching Code to Images using overlay & put-image}
}

