= Visualizing the "Shape" of Data

@description{Students explore the concept of "shape", using histograms to determine whether a dataset has skewness, and what the direction of the skewness means. They apply this knowledge to the Animals Dataset, and then to their own.}

@lesson-prereqs{histograms}

@keywords{histogram, bin, interval}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* Create histograms for variables in the Animals Dataset
* Describe the distribution of quantitative columns of the Animals Dataset, using proper terminology.

| Student-facing Lesson Goals
|

* Let's investigate what the shape of a histogram can tell us about the data.

| Materials
|[.materials-links]

@material-links

| Preparation
|
* All students should log into @starter-file{program-list} and open their saved "Animals Starter File". If they don't have the file, they can open a new one from @starter-file{animals}.

|===


== Describing Shape @duration{30 minutes}

=== Overview
This activity focuses on _describing shape_ based on a @vocab{histogram}. Students learn about "left skewed", "right skewed", and "symmetric" data, and what those descriptions tell us about a dataset.

=== Launch

@vocab{Shape} is one way to quickly describe what values are more or less common in a dataset. Some might occur very frequently, while others are rare. This description is a called a @vocab{distribution}, because it shows where data points are clustered together or spread thin. Data Scientists spend a lot of time looking at data displays to examine their shape! If all you look at is the numbers, you lose a lot of insight into your dataset.
 (@link{https://www.research.autodesk.com/publications/same-stats-different-graphs-generating-datasets-with-varied-appearance-and-identical-statistics-through-simulated-annealing/, This page from Autodesk} is a wonderful example!)

@lesson-point{
Histograms create __fixed-size__ bins, which contain varying numbers of data points.
}

@right{@image{images/skew-right.png,  300}}

We can think of the data being "squeezed" into these fixed bins, like globs of pizza dough being pushed into tubes. When there isn't much data that fits into a bin, the tube is mostly empty. But when lots of data points fall within a bin, the dough stacks up in the tube. This is why the height of a histogram bar tells us how much data is "squeezed" into that bin!

Consider the image on the right: most of the data points are clustered on the left side, and it contains a few unusually high values way off to the right. But how do we describe this shape, and what does it mean?

Let's look at some real-world examples of the most common shapes:

**1. Skewed right, or high outliers.**

@right{@image{images/right-w-foot.png, 300}}

In a distribution that is @vocab{skewed right}, values are clumped around what’s typical, but they trail off to the right with a few unusually high values. We see this shape often in the real world, because there are many variables -- like “income” or “time spent on the phone” -- for which a few individuals have unusually high values, which aren’t balanced out by unusually low values (things like “income” and “phone time” can’t be less than zero). Examples:

- Age when a woman in the U.S. gives birth would be skewed right or have high outliers. A few women would be much older (40+ years) than the average age of 26 (check the tabloids!), but none of them could be even close to 40 years _below_ average to balance things out!
- A dataset of earnings almost always shows right skewness or high outliers, because there are usually a few values that are so far above average, they can’t be balanced out by any values that are so far below average. (Earnings can’t be negative.)

A skew-right distibution will look like the toes on your right foot!

**2. Skewed left: low outliers.**

@right{@image{images/left-w-foot.png, 300}}

In a distribution that is @vocab{skewed left}, values are clumped around what’s typical, but they trail off to the left with a few unusually low values. Examples:

- Most adults will have close to a full set of 32 teeth, but a few hockey players might have a very small number of teeth. We won’t get anyone in our dataset who has 10 or 20 _extra_ teeth in their mouths!
- If the school cafeteria mostly buys canned goods in large commercial sizes, but buys a few items in household sizes, then if we looked at the ounces per can we’d see a shape that has left skewness and/or low outliers.

A skew-left distibution will look like the toes on your left foot!

**3. Symmetric: values are balanced on either side of the middle.**

@right{@image{images/symmetric.png, 300}}
In a @vocab{symmetric} distribution, it’s just as likely for the variable to take a value a certain distance below the middle as it is to take a value that same distance above the middle. Examples:

- It’s just as likely for a newborn baby to be a certain number of ounces below @vocab{average} weight as it is to be that number of ounces above average weight.
- At many restaurants, the busiest dinner time is around 7pm. But there are always a few people who want to eat earlier or later.

=== Investigate
[.lesson-instruction]
--
- Make a histogram for the pounds column in the animals table, sorting the animals into 20-pound bins.
** __Students should enter the code: @show{(code '(histogram animals-table "name" "pounds" 20))}__
- Would you describe the shape of your histogram as being skewed left, skewed right, or symmetric?
** _The histogram is skewed left._
- Which one of these statements is justified by the histogram’s shape? (1) A few of the animals were unusually light, (2) A few of the animals were unusually heavy, or (3) It was just as likely for an animal to be a certain amount below or above average weight.
** _The statement "a few of the animals were unusually heavy" is the only one that applies, given the histogram's shape._
- Try bins of 1-pound intervals, then 100-pound intervals. Which of these three histograms best satisfies our rule of thumb?
** _Our rule of thumb is that a histogram should have between 5–10 bins. The first histogram we made - with 20-pound bins - had a total of ten bins, so it best satisfies our rule._
- On @printable-exercise{pages/identifying-shape-histograms.adoc}, describe the shape of the histograms you see there.
- On @printable-exercise{pages/shape-of-animals-dataset.adoc}, describe the pounds histogram and another one you make yourself. When writing down what you notice, try to use the language Data Scientists use, discussing both skew and outliers.
--

*Outliers... do they stay or do they go?*

@right{@image{images/height-outlier.png, 300}}

Suppose we survey the heights of 12 year olds, and almost all values are clustered between 50-70in. There's a very low outlier, however, at 6in. __Is there really a 6in tall 12 year old?__ Probably not! This could very well be a typo (maybe someone meant to type "60" instead of "6"?). "Junk" data is harmful, because it can drastically change your results!

Suppose we survey the number of minutes it takes for fans to find their seats at a stadium, and almost all values are clustered between 4-16 minutes.

@right{@image{images/stadium-outlier.png, 300}}

There's a very high outlier, however, at 35 minutes. __Did it really take someone 35m to find their seat?__ Well, that's very possible! Maybe it's someone who takes a long time getting up stairs, or someone who had to go far out of their way to use the wheelchair ramp!

An outlier can be "junk" data that you need to throw away as part of your analysis, or it could be a really important part of your analysis! As a data scientist, *an outlier is a reason to look closer*. And whether you decide to keep or remove it from your dataset, make sure you *explain your reasons* in your write-up!

[.lesson-instruction]
Turn to @printable-exercise{pages/outliers-discussion.adoc}, and reflect on whether an outlier should be preserved or removed for analysis.

@strategy{
@span{.title}{What Shape Makes Sense?}

If time allows, here's a great way to get students walking around and thinking more deeply about distributions!

Using flip-chart paper or whiteboard space, designate poster-sized regions around the classroom titled "Symmetric", "Skew Left", and "Skew Right". You may want to have 2-3 of each, depending on the number of students and size of the classroom. Divide the class into teams, such that each group takes a region of the room.

Each team looks at the region they're in front of, and must (a) draw a histogram with that shape and (b) __brainstorm a sample that would likely result in that distribution__. Once each team has completed the task, the teams rotate to the next poster and brainstorm another sample. They complete this until every team has come up with at least one unique example for symmetric, skew left, and skew right distributions.
}


=== Synthesize
Discuss as a class, making sure students agree on the description of the shape.

Histograms are a powerful way to display a dataset and see its @vocab{shape}. But shape is just one of three key aspects that tell us what’s going on with a @vocab{quantitative} column of a dataset. We will also want to learn about center and spread!


== Data Exploration Project (Visualizing Shape) @duration{flexible}

=== Overview

Students apply what they have learned about visualizing shape to the histograms they have created for their chosen dataset. They will add to their @starter-file{exploration-project} a more detailed interpretation of their histograms using new vocabulary. To learn more about the sequence and scope of the Exploration Project, visit @lesson-link{project-data-exploration}.

=== Launch

Let’s review what we have learned about visualizing the shape of data.

[.lesson-instruction]
- Describe a histogram that is _skewed right_. Are its outliers high or low?
** _Values are clumped around what's typical, with low outliers._
- Describe a histogram that is _skewed left_. Are its outliers high or low?
** _Values are clumped around what's typical, with high outliers._
- Describe a histogram that is symmetric.
** _It’s just as likely for the variable to take a value a certain distance below the middle as it is to take a value that same distance above the middle._

=== Investigate

Let’s connect what we know about visualizing the shape of the data to the histograms we created for your chosen dataset.

[.lesson-instruction]
- *It’s time to add to your @starter-file{exploration-project}.*
- For each of the histograms that you have added, edit and / or expand upon the interpretations you provided during the @lesson-link{histograms} lesson.
- Be sure to integrate the new vocabulary we have learned, including: @vocab{shape}, @vocab{skewed left}, @vocab{skewed right}, and @vocab{symmetric}.
- Describe what this shape tells you about the quantitative column you chose.


=== Synthesize
Share your findings!

What @vocab{shape} did you notice in your histograms?

Did you discover anything surprising or interesting about your dataset?

When your compared your findings with others, did they make any interesting discoveries?

@scrub{
////

== Additional Exercises

- Project: @opt-printable-exercise{pages/word-length.adoc} - A mini-project in which students use a histogram to plot the length of words in different texts.
////
}
