= Visualizing the "Shape" of Data

@description{Students explore the concept of "shape", using histograms to determine whether a dataset has skewness, and what the direction of the skewness means. They apply this knowledge to the Animals Dataset, and then to their own.}

@lesson-prereqs{histograms}

@keywords{histogram, bin, interval}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

@objectives

| Student-facing Lesson Goals
|

- Let's learn about different histogram distributions.
- Let's investigate what the shape of a histogram can tell us about the data.

| Materials
|[.materials-links]

@material-links

|===


== Describing Shape @duration{30 minutes}

@objective{peaks-clusters-gaps}
@objective{skew-or-symmetric}
@objective{bar-chart-v-histogram}

=== Overview

This activity focuses on _describing shape_ from a @vocab{histogram}. Students explore shape by considering symmetry, peaks, clusters, and skew.

=== Launch

@QandA{
Your teacher will give you and your partner an envelope containing lettered histogram cards. Lay out the cards in front of you.

@Q{What do you Notice about the histograms? You can describe something you notice about the group, a sub-group, or even one histogram in particular.}

@Q{What do you Wonder about the histograms?}
}

Let's sort some histograms!

@lesson-instruction{
- With your partner, use the histogram cards to sort the cards into two piles: histograms that are roughly symmetrical, and histograms that are not roughly symmetrical.
- Be prepared to share your groupings with the class.
}

@teacher{
If students are not familiar with the concept of "symmetry", spend some time briefly explaining that it exists when the halves of the histogram are symmetrical. Ensure that students agree on which histograms are symmetrical and which ones are not.
}


=== Investigate

@lesson-instruction{
- With your partner, use the histogram cards to complete @printable-exercise{sorting-histograms.adoc}.
- We will pause for discussion after you complete the first section.
}

@teacher{
As you circulate: (1) make note of the different grouping strategies used by different students to foster group discussion, and (2) encourage students to use appropriate vocabulary (i.e., peak, cluster, gap).
}

Let's debrief.

@QandA{
@Q{How did you group your symmetrical histograms?}
@A{Responses will vary. Students may have grouped their histograms by the number of peaks, the number of gaps, or the location of the center. There are no wrong answers here.}

@Q{How can you determine what's typical of a symmetrical histogram?}
}

@lesson-instruction{
- With your partner, complete the second section of @printable-exercise{sorting-histograms.adoc}.
}

@QandA{
@Q{How did you group your symmetrical histograms?}
@A{Possible groupings: no peaks, 1 peak, 2 peaks; 1 gap, no gaps; and center at X, center at Y.}

@Q{How can you determine what's typical of a symmetrical histogram?}
@A{The center of a symmetrical histogram is the line of symmetry. A common misconception is arguing that the center of the axis is the center of the histogram; students must also consider the range of the histogram.}
}

You probably noticed that some histograms trail off to the left, and others trail off to the right. Statisticians refer to this trailing as "skew". Lets compare the skew-left, skew-right, and symmetric histograms.



[cols="^.^1a,^.^1a,^.^1a", options="header"]
|===

| Symmetric | Skew-left 							| Skew-right

| @image{images/symmetric.png, 150 }| @image{images/left-w-foot.png, 150}  | @image{images/right-w-foot.png, 150}

| Values are balanced on either side of the center.

| Values are clumped around what's typical, but trail off to the right.

| Values are clumped around what's typical, but trail off to the left.

|===

Skew-left distributions look like the toes on your left foot, and skew-right distributions look like the toes on your right foot!

@vocab{Shape} is useful because it enables us to quickly identify and describe trends in data. *Shape is also one of a few key features that sets histograms apart from bar charts!* Let's explore this concept further.

@lesson-instruction{
Complete @printable-exercise{bar-chart-v-histogram.adoc}.
}

@teacher{
@printable-exercise{bar-chart-v-histogram.adoc} surfaces two common student misconceptions about bar graphs that @citation{whittaker-jacobbe-2017, "Whittaker and Jacobbe (2017)" } cite in their research. First, students commonly fail to understand that skew is associated with *distributions of quantitative variables*. This is why a bar graph with its bars arranged in increasing or decreasing order does not display a skewed distribution. Students also commonly believe that the category with the greatest value represents a majority of the responses. In this dataset, that is not the case: the bar representing the college of science does not represent more than half of the students.
}

Because a bar chart displays categorical data, we can order the bars anyway that we wish. That is not the case with histograms: since quantitative data must follow a natural order, a histogram's bars cannot be re-ordered.


=== Synthesize

@QandA{

@Q{Envision a skew-left histogram. Where do you think its outliers are? Explain how you know.}

@Q{Why do histograms have shape but bar graphs do not?}
}

== Interpreting Shape

@objective{histogram-shape}

=== Overview

Students consider what different distributions tell us about a dataset, connecting different scenarios with different data visualizations.

=== Launch

We now have the terminology needed to describe histogram shape. But what can we actually conclude about a dataset based on a histogram's shape?

@lesson-instruction{

Let's consider two different scenarios:

- The average US woman gives birth around age 26, but some do even after 45! Children do not give birth.

- Most adults have close to a full set of 32 teeth, but a few hockey players might have a very small number of teeth. No one has more than 32 teeth.

*Let's draw a rough sketch of what we think the histogram for each of these scenarios might look like.*}

@teacher{
Invite a student to the board to draw a rough sketch of each scenario. Invite the students to describe how they decided where to draw the clusters, peaks, and outliers.}

@QandA{
@Q{Which of the above scenarios describes a left skew? Explain.}
@A{The scenario about women's ages describes a left skew. Most of the data is clustered around 26, but there is also data further on the right, all the way up to 45. There is no data around, say, age 7.}

@Q{Which of the above scenarios describes a right skew? Explain.}
@A{The scenario about teeth describes a right skew. Most of the data is clustered around 32 with a few outliers further to the left.}
}

@lesson-instruction{
- With a partner, complete @printable-exercise{use-shape-to-interpret.adoc}.
- Just like we did during the warm up, you will sketch rough histograms, make a decision their shape, and then interpret the data.
}

=== Investigate

@teacher{

There is some setup required for the interactive activity that follows.

- You will need flip chart paper, tape, and markers.
- Divide your class into teams of three. All around your classroom, tape flip chart paper to the wall--one poster per team of three students.
- On each piece of flip chart paper, write "Skew Left", "Skew Right", or "Symmetric", and then draw lines to divide the paper horizontally into three equal sections.
}

@lesson-instruction{
- Your teacher has instructed you and your group to stand in front of a blank poster that says "Symmetric", "Skew Left", or "Skew Right" at the top.
- With your group, draw a histogram that matches the shape assigned to you in the top section of the poster.
}

@teacher{Once all students have drawn their histograms, direct them to rotate to the next poster of a different shape.}

@lesson-instruction{
- You are now standing in front of a poster that identifies a shape and also includes a histogram of that shape.
- In the second horizontal section of the poster, write a scenario or describe a dataset that would result in that distribution.
- Leave the third section of the poster blank. We will use it another day!
- Take a few minutes to walk around the classroom and read the scenarios your peers developed. Return to your seat when you have had a chance to see all of the posters.
}

@teacher{
Spend some time debriefing with students, using the prompts below. Responses will vary for each group of students.
}

@QandA{
@Q{Did all of the scenarios your classmates developed correctly represent the given shape?}

@Q{Did you notice any especially creative scenarios? Any surprising scenarios?}

@Q{Were there any scenarios that were represented more than once? Why do you think those scenarios were popular?}
}

@teacher{
The third section of the posters will remain blank today. Students will complete this section in the future when they learn about @lesson-link{box-plots}.
}

=== Synthesize

@QandA{
@Q{What strategies did your group use in brainstorming scenarios to match histogram shape?}
@Q{For which distributions was it easiest to come up with an example?}
@Q{For which distributions was it hardest to come up with an example?}
}



== Histograms and Measures of Center

@objective{histograms-and-measures-of-center}

=== Overview

Students combine apply their knowledge histograms, measures of center, and shape.

=== Launch

Can you compute and interpret different measures of center from a histogram? Let's try it.

@QandA{
The histogram below shows the number of children per home in the Broadmoor neighborhood.

@image{images/number-children.png, 350}

@Q{What is the median number of children per home?}
@A{1. Students may mistakenly attempt to find the midpoint of the values on the horizontal axis, indicating that they connect median with “middle”, but misunderstand _what_ middle value to find. In this case, all of the raw data is available in the histogram.
}

@Q{What is the mean number of children per home?}
@A{Approximately 2.04. Note that students may attempt to use the “add up and divide” algorithm with inappropriate data values from the display. Students may mistakenly compute the mean height of the bars, or the mean of values on the horizontal axis.}
}

@teacher{Students often cannot compute measures of center from histograms because they _lack attention to the context of the data_. Cooper and Shore (2008) suggest that when students are confused, simply ask "What are the data?" to help reorient and redirect students. Similarly, urge students to discuss and defend their responses.}


=== Investigate

@lesson-instruction{
- Work with a partner to complete @printable-exercise{histograms-moc.adoc}.
- Which problem was the most challenging? Why did you find it challenging?
}

@teacher{
Discuss solutions with students. Highlight for students the misconceptions revealed by common incorrect responses. For instance, choosing "the modes are roughly the same" for the the first problem suggests that students understand the concept of mode, but looked at bar height (indicating frequency) instead of considering the value on the x-axis.
}



=== Synthesize

@QandA{
@Q{How was interpreting mean, median, and mode from a histogram different than computing it from a raw dataset?}
@A{Responses will vary. Students should explain that they needed to understand the meaning of the bar height and the values on the x-axis in order to arrive at correct measures of center.}

@Q{Describe how the relationship between mean and median can help you draw a conclusion about the skewness of a histogram?}
@A{When the mean is greater than the median, outliers on the right cause the display to be skewed right. When the mean is less than the median, outliers on the left cause the histogram to be skewed left. }
}



== Data Exploration Project (Visualizing Shape) @duration{flexible}

=== Overview

Students apply what they have learned about visualizing shape to the histograms they have created for their chosen dataset. They will add to their @starter-file{exploration-project} a more detailed interpretation of their histograms using new vocabulary. 

@teacher{Visit @lesson-link{project-data-exploration} to learn more about the sequence and scope. Teachers with time and interest can build on the exploration by inviting students to take a deep dive into the questions they develop with our @lesson-link{project-research-paper}.
}

=== Launch

Let’s review what we have learned about visualizing the shape of data.

@QandA{
@Q{Describe a histogram that is _skewed right_. Are its outliers high or low?}
@A{Values are clumped around what's typical, with low outliers.}

@Q{Describe a histogram that is _skewed left_. Are its outliers high or low?}
@A{Values are clumped around what's typical, with high outliers.}

@Q{Describe a histogram that is symmetric.}
@A{It’s just as likely for the variable to take a value a certain distance below the middle as it is to take a value that same distance above the middle.}
}

=== Investigate

Let’s connect what we know about visualizing the shape of the data to the histograms we created for your chosen dataset.

@lesson-instruction{
- Open your chosen dataset starter file in @proglang.
- For this analysis, you'll want to look at the Data Cycle that you completed during the Histograms lesson.
- Recreate the histograms that you made before. Now, edit and expand your discussion so that it uses the new vocabulary that you've used.
}

@teacher{@opt{If your students who need a fresh copy of the Data Cycle template, distribute @opt-printable-exercise{data-cycle-quantitative.adoc}.}}

@slidebreak

@lesson-instruction{
*It’s time to add to your @starter-file{exploration-project}.*

- For each of the histograms that you have added, edit and / or expand upon the interpretations you provided during the Histograms lesson.
- Be sure to integrate the new vocabulary we have learned, including: @vocab{shape}, @vocab{skewed left}, @vocab{skewed right}, and @vocab{symmetric}.
- Describe what this shape tells you about the quantitative column you chose.
}

=== Synthesize

@teacher{Have students share their findings.}

- What @vocab{shape}s did you notice in your histograms?
- Did you discover anything surprising or interesting about your dataset?
- Were there any surprises when you compared your findings with other students?

@scrub{
////
== Additional Exercises

- Project: @opt-printable-exercise{word-length.adoc} - A mini-project in which students use a histogram to plot the length of words in different texts.
////
}
