= Tree Diagrams

++++
<style>
.fitb{ line-height: 3em !important; text-align: left; }
</style>
++++

Luigi's menu includes Lasagna, Pizza, Chicken, Ravioli, Soup and Ziti. Below is a *partial* tree diagram showing someone's first three courses: Chicken, Lasagna and Ravioli. 

@span{.center}@image{../images/tree-practice.png}

@vspace{20ex} 

1) Draw the tree for all possible 4th-course choices after Ravioli.

2) By starting at the top and walking to each endpoint of the tree, we can find all the course-lists. On the lines below, two lists of courses from this tree are written for you. __Complete the list.__

@fitb{100ex}{C-L-R-L, C-L-R-P, }

@fitb{100ex}{}

@fitb{100ex}{}

@vspace{5ex} 

3) Two friends each want to go a different movie. They decide to flip a coin 3 times, and go with the best 2-out-of-3. Draw the tree diagram for all possible permutations below:

@vspace{20ex} 



4) By walking the tree you drew, list all possible permutations on the lines below.

@fitb{100ex}{}

@fitb{100ex}{}