= Sorting Box Plots

== Grouping Option #1

Identify two or three logical and related groupings that you could use to sort each of the box plot cards.

@n Group 1 name: @fitb{15em}{} @hspace{1ex} Cards that belong in Group 1: @fitb{}{}

@n Group 2 name: @fitb{15em}{} @hspace{1ex} Cards that belong in Group 2: @fitb{}{}

@n Group 3 name: @fitb{15em}{} @hspace{1ex} Cards that belong in Group 3: @fitb{}{}


@n Why are these groupings useful? What can you learn about a box plot based on the feature that you've chosen to focus on?  @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Can you divide any of the groups you created into sub-groups? Explain. @fitb{}{}

@fitb{}{}


== Grouping Option #2

Identify two or three logical and related groupings that you could use to sort each of the box plot cards.

@n Group 1 name: @fitb{15em}{} @hspace{1ex} Cards that belong in Group 1: @fitb{}{}

@n Group 2 name: @fitb{15em}{} @hspace{1ex} Cards that belong in Group 2: @fitb{}{}

@n Group 3 name: @fitb{15em}{} @hspace{1ex} Cards that belong in Group 3: @fitb{}{}


@n Why are these groupings useful? What can you learn about a box plot based on the feature that you've chosen to focus on?  @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Can you divide any of the groups you created into sub-groups? Explain. @fitb{}{}

@fitb{}{}

== Grouping Option #3

Identify two or three logical and related groupings that you could use to sort each of the box plot cards.

@n Group 1 name: @fitb{15em}{} @hspace{1ex} Cards that belong in Group 1: @fitb{}{}

@n Group 2 name: @fitb{15em}{} @hspace{1ex} Cards that belong in Group 2: @fitb{}{}

@n Group 3 name: @fitb{15em}{} @hspace{1ex} Cards that belong in Group 3: @fitb{}{}


@n Why are these groupings useful? What can you learn about a box plot based on the feature that you've chosen to focus on?  @fitb{}{}

@fitb{}{}

@fitb{}{}

@n Can you divide any of the groups you created into sub-groups? Explain. @fitb{}{}

@fitb{}{}
