= Correlations

@lesson-description{Students begin to interpret scatter plots, and search for correlations in their dataset.}

[@lesson-intro-table]
|===
@prereqs-stds{}
| Lesson Goals
| Students will be able to...

* explain what a line of best fit is, and discuss it in terms of direction and strength
* draw a line of best fit on a scatter plot

| Student-Facing Lesson Goals
| I can...

| Materials
|
* Computer for each student (or pair), with access to the internet
* link:{pathwayrootdir}/workbook/workbook.pdf[Student workbook], and something to write with

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
| @link{http://tylervigen.com/, Spurious Correlations}

| Relevant Standards
|
@worksheet-include{xtra/lang-prereq.adoc}
|===

== Correlations have _Direction_ @duration{20 minutes}

=== Overview
Students learn about the line of best fit, and what it means for the slope of the line to positive or negative.

=== Launch
The mean, median, and mode are three difference ways to measure the “center” of a dataset in one dimension. Each represents a different way to collapse a bunch of points on a number line into a single, summary value. If the “center” of points on a _one dimensional_ number line is a single point, what is the “center” of points in a _two-dimensional_ cloud, which cluster around a line?

What we need to do is find a _line_ -- called a @vocab{line of best fit}, or a “regression line” -- that is at the center of this cloud. Each point in our scatter plot “pulls” on the line, with points above the line yanking it up and points below the line dragging it down. Points that are really far away -- our @vocab{outliers} and our influential observations -- pull with more force than those that are close to the line. 

If the line has a positive slope, the correlation is positive. If it has a negative slope, the correlation is negative. Given a value on the x-axis, this line allows us to “predict” what the corresponding value on the y-axis might be. This allows us to make predictions based on our data.

[.lesson-point]
Correlations have _direction_: they can be positive or negative.

* A *positive correlation* means that the variable on the y-axis increases as the variable on the x-axis goes up. For example, “the older the animal, the more weeks it generally takes to get adopted”.
* A *negative correlation* means that the variable on the y-axis decreases as the variable on the x-axis goes down. For example, “the longer an animal is at the shelter, the less they generally weigh”.

Was there a correlation in the pounds-vs-weeks scatter plot? If so, is it positive or negative? What correlations, if any, did students see in the other scatterplots they created?

=== Investigate

[.lesson-instruction]
* Turn to @worksheet-link{workbook-pages/drawing-predictors.adoc}.
* In the first column, draw a @vocab{line of best fit} through each of the scatter plots. 
* In the second column, circle whether the slope of the line - the correlation - is positive or negative.

=== Student Misconceptions
It is useful to ask students probing questions, to help erase misconceptions here. Some examples:

* Would it be possible to have a line that is _below_ all the points? (no)
* Would it be possible to have a line that is _above_ all the points? (no)
* Would it be possible to have a line with more points on one side than the other? (yes)

=== Collect
Have students share their answers. 

== Correlations have _Strength_ @duration{20 minutes}

=== Overview
Students learn about strength, as a property of correlations.


=== Launch
Suppose you have two identical lines of best fit, but the point clouds around them are different. For one scatter plot, all the of the points are pretty tightly packed around the line. For the other, they are really spread out. If both correlations have the same direction, should we treat them the same way?

[.lesson-point]
Correlations have _strength_: they can be strong or weak.

* If the cloud is tightly packed, there is a _strong correlation_.
* If the cloud is loosely scattered, there is a _weak correlation_.
* If the points are all over the place, with no tendency to rise or fall from left to right, there may be _no correlation_.

Even if the slope and direction of the line are identical, the _strength_ of a correlation tells us how much one variable predicts another.

[.lesson-point]
Correlation does NOT imply causation.

If two quantities are _correlated_, it doesn’t mean that one _causes_ the other! For example, @link{http://tylervigen.com/view_correlation?id=7, a study found that there is a strong correlation between the number of people who become tangled in their own bedsheets each year and the amount of cheese consumed that year}. It happens that both of those values have been increasing over the past decade, but there is no causal relationship between them!


=== Investigate
[.lesson-instruction]
For each line you drew on @worksheet-link{workbook-pages/drawing-predictors.adoc}, determine the direction and strength of the correlation by circling the words that describe it.

=== Collect
Have students discuss and share their answers.

== Correlations in Your Dataset @duration{flexible}

=== Overview
Students search for correlations in their dataset.

=== Launch
What correlations do you think there are in your dataset? Would you like to investigate a subset of your data to find those correlations?

=== Investigate
[.lesson-instruction]
Brainstorm a few possible correlations that you might expect to find in your dataset, and make some scatter plots to investigate.

[.lesson-instruction]
Turn to @worksheet-link{workbook-pages/correlations-in-my-dataset.adoc}, and list three correlations you’d like to search for.

=== Collect
Have students share back their correlations, and why they expect to find them.

After looking at the scatter plot for our animal shelter, do students still agree with the claim on @worksheet-link{ds-correlations/workbook-pages/disproving-claim.adoc}? (Perhaps they need more information, or to see the analysis broken down separately by animal!)

But how do we know if a correlation is strong enough to be _useful_? Eyeballing charts isn’t good enough. In the next lesson, students learn how a correlation is measured via linear regression, and get a feel for strength of a relationship based on a single number.