= Using Transformers: Sort, Filter, Transform Attribute, Build Attribute

*Transformers* allow us to transform datasets to produce new, distinct output datasets, instead of modifying the original input dataset itself. We use them to manipulate tables and enable low-stakes "what if?" exploration.

- In this course, we'll be using a variety of Transformers.

** `Filter` - We must provide `Filter` with an expression that evaluates to either true or false. `Filter` then produces a copy of the input dataset that only has the cases for which the formula was true.
** `Transform Attribute` - We provide `Transform Attribute` with an attribute to transform, a new name for the transformed attribute, and an expression to apply to each row. The `Transform Attribute` replaces the value of the designated attribute with the result of the expression. `Transform Attribute` produces a copy of the input dataset with the designated row transformed.
** `Build Attribute` - We provide an expression that is used to calculate an attribute's new values. `Build Attribute` produces a copy of the input dataset with the new attribute added.

// ** `Sort` - We must provide `Sort` with a dataset, a sort method (we'll focus on sorting by attribute in this course), and a sort direction. `Sort` produces a copy of the input dataset, with cases sorted by the selected attribute.//

- Each of the above Transformers is attached to a unique expression. It's important to get the expression just right, or the Transformer will produce an error. Strings belong inside quotation marks, but Booleans do not!

*Order Matters!* Transformers must be applied in the appropriate order given the dataset. For example, trying to filter a table by a column that hasn’t been built will result in an error.
