= Properties of Functions
@description{Students learn about the properties of functions.}

@lesson-prereqs{}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to:

* Test whether or not a graph is a function using the vertical line test.

| Student-Facing Lesson Goals
|
* I can identify which graphs are functions and which aren't using the vertical line test.

| Materials
|[.materials-links]
@ifproglang{wescheme}{
* @link{https://docs.google.com/presentation/d/1uDxsuY87FFkeMowOOU6WImTdfeQLaJm8iEroE6nDsmY/, Lesson Slides}
}
@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/10mZzi6_jEIcAd4v9zdFiGHij_PNc98d3myeoLNUuuYM/, Lesson Slides}
}

@material-links

| Preparation
|
@preparation

@lang-prereq

|===

== Functions Have Exactly One Output for Each Input @duration{20 minutes}

=== Overview

=== Launch
Functions allow humans to instruct machines to do work for us. Whereas humans are flexible and can make game-time decisions about all sorts of things, machines need to be programmed to know what to do with whatever comes there way. For example, a safe human driver will slow down as they approach a curve or see brake lights up ahead, but if a car's cruise control has been set at 60mph, a human will have to turn off the cruise control in order to slow down the vehicle if there's a reason not to go 60mph anymore.  Similarly, a vending machine can be programmed to release a granola bar if the granola bar button is pushed and the corresponding amount of money is supplied, but it can't decide which kind of snack we'd like to eat this afternoon.

=== Investigate

=== Common Misconceptions

=== Synthesize

== Identifying Functions on a Graph @duration{30 minutes}

=== Overview

=== Launch

=== Investigate

=== Synthesize
