= Bootstrap: Game Design

_These materials are for programming in Pyret. Looking for the Game Design materials for @dist-link{courses/game-design-wescheme/, WeScheme}?_

@pathway-logo

Students will use their creativity to design a simple three character game in which:

- linear functions animate characters
- inequalities keep characters on the screen
- collisions and score changes are determined using the Pythagorean Theorem
- piecewise functions customize movement

*The lessons outlined below are the ones considered essential for video game creation.* 

- 🎮 indicates that a lesson is focus directly on the @starter-file{game, "Game Starter File"}. +
- The other lessons in the list are prerequisites for these lessons, in which students build the skills they'll need to work on various pieces of the game code. 

A more detailed overview, including a student-facing rubric, can be found @lesson-link{project-video-game, here}.

_In @link{https://bootstrapworld.org/materials/algebra/, "Bootstrap:Algebra"} and @link{https://bootstrapworld.org/materials/data-science/, "Bootstrap:Data Science"}, we offer many additional lessons where students can develop their math and coding skills.  We encourage you to integrate additional lessons that meet your students' needs!_

@pathway-lessons

@workbooks

@other-resources














