= Exploring Displays

++++
<style>
#content .fitb{ margin-top: 1ex !important; width: 26em; min-width: 1.5em; }
#content tbody tr:first-child { height: 2.5in; }
#content img { max-height: 2in !important; display: block;}
</style>
++++

Using the @link{https://codap.concord.org/app/static/dg/en/cert/index.html#shared=https%3A%2F%2Fcfm-shared.concord.org%2FeZEwgF1qSm396MC6CNM9%2Ffile.json, Animals Dataset} in CODAP, make each type of display below. Then sketch the displays and answer the questions.

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Bar Charts
| Bar Charts

| @ifsoln{@image{pie-chart.png}} Sketch a bar chart here.
| @ifsoln{@image{bar-chart.png}} Sketch a bar chart here.

|
--
@span{.left}{
Displays @fitb{1em}{@ifsoln{_1_}} column(s)
of @fitb{9em}{@ifsoln{_categorical_}} data. +
What does this display tell us?
@fitb{}{@ifsoln{_The proportion in which values in a categorical_}}
@fitb{}{@ifsoln{_column are represented - including categories_}}
@fitb{}{@ifsoln{_that are NOT represented_}}
@fitb{}{}
}
--

|--
@span{.left}{
Displays @fitb{1em}{@ifsoln{_1_}} column(s)
of @fitb{9em}{@ifsoln{_categorical_}} data. +
What does this display tell us?
@fitb{}{@ifsoln{_The proportion in which values in a categorical_}}
@fitb{}{@ifsoln{_column are represented - including categories_}}
@fitb{}{@ifsoln{_that are NOT represented_}}
@fitb{}{}
}
--
|===

[cols="^1a,^1a",stripes="none",options="header"]
|===
| Box Plots
| Histograms

| @ifsoln{@image{box-plot.png}} Sketch a box plot here
| @ifsoln{@image{histogram.png}} Sketch a histogram here

|
--
@span{.left}{
Displays @fitb{1em}{@ifsoln{_1_}} column(s)
of @fitb{9em}{@ifsoln{_quantitative_}} data. +
What do you think this display tells us?
@fitb{}{@ifsoln{_The range of quantitative values in the bottom quarter,_}}
@fitb{}{@ifsoln{_top quarter, and the middle quarters. This tells_}}
@fitb{}{@ifsoln{_us something about the spread of the data_}}
@fitb{}{}
}
--

|
--
@span{.left}{
Displays @fitb{1em}{@ifsoln{_1_}} column(s) of
@fitb{9em}{@ifsoln{_quantitative_}} data. +
What do you think this display tells us?
@fitb{}{@ifsoln{_How many values in a quantitative column fall into_}}
@fitb{}{@ifsoln{_equally-sized bins. This tells us something about_}}
@fitb{}{@ifsoln{_the spread of the data._}}
@fitb{}{}
}
--
|===
