= Order of Operations (Circles of Evaluation)

@lesson-description{Students learn to model arithmetic expressions with the visual tool for order of operations and function composition known as Circles of Evaluation.}

[.left-header, cols="20a, 80a", stripes=none]
|===
| Lesson Goals
| Students will be able to:

* Model an arithmetic expression using The Circles of Evaluation.
* Translate Circles of Evaluation into Racket code.

|Student-facing Goals
|
* I can write the Circles of Evaluation for a given arithmetic expression.
* I can translate a Circle of Evaluation model into Racket code.
* I can use numbers and operations in the WeScheme programming environment.

|Key Points For The Facilitator
|
* Drive home the idea to students that the errors are there to help and are very informative.

* After working with the Circles of Evaluation for a bit, ask students whether they create the Circles from the 'Inside-Out' or from the 'Outside-In.'  After they've given their responses, have them practice using the OTHER way.

* Point out that up until now, we didn't have a visual spatial model for Order of Operations. Ask students to compare the Circles to previous methods they've learned(PEMDAS, GEMAS, etc..)


|Prerequisites
|
* Students should have knowledge of general arithmetic and the order of operations.


|Materials
|

* @link{https://docs.google.com/presentation/d/16ZKAYkRX3pMPd65dFwsu_opuihhu32sK7C3EpLbKxbs/view, Google Slides} for this lesson
(Frayer Model - Order of Operations (@worksheet-link{workbook-pages/OrderOfOperations1-FrayerModelTemplate.pdf, PDF}, @link{https://docs.google.com/drawings/d/1mCJygY5elVQzy64zLLRyFVZ9-CkTnVYTBM3URnIfzEc/view, Google Doc}) 

Bootstrap Formative Assessments

* @link{https://quizizz.com/admin/quiz/5cdcb223862fd8001a135579, Bootstrap: Algebra - Coordinates, Circles of Evaluation, & Code} (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb288f41b366950eba1e1, Bootstrap:Algebra - Data Types & Circles of Evaluation} (Desmos Activity)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb336f41b366950eba420, Bootstrap:Algebra - Circles of Evaluation Review(Blank Template)} (Desmos Activity)
* @link{https://quizizz.com/admin/quiz/5cdcb3907f8c98001a203c1b, Bootstrap:Algebra - Contracts, Domain/Range, Data Types, & Functions } (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/5cdcb3f555e3fb606a1f1ba2, Bootstrap:Algebra - Data Types, Circles of Evaluation, and Contracts} (Desmos Activity)

Connecting Activities

* @link{https://quizizz.com/admin/quiz/5bd690b3784210001af2588c, Order of Operations} (Quizizz)
* @link{https://teacher.desmos.com/activitybuilder/custom/57ae458a697f767c75597801, Twin Puzzles - Order of Operations} (Desmos)

|===

[.left-header, cols="20a, 80a", stripes=none]
|===
|Approaching (CCSSM)
|

* @std{HSA.SSE.A.2}
* @std{HSA.SSE.B}

|Standards of Mathematical Practice
|
* @std{MP.1}
* @std{MP.2}

|===


== Get Ready: 

Students should be logged into @link{https://www.wescheme.org, WeScheme}.

== Launch: (8 mins)
Option 1: Watch the @link{https://www.youtube.com/watch?v=y9h1oqv21Vs, PEMDAS is wrong} video with students then ask students what they thought of the video and what they think/know of PEMDAS.
 (Suggestion: watch the video at 0.5 speed because they talk really fast).  

Option 2: Have students evaluate the expression in the image below and gather a few responses from the students.  Discuss some of the issues mentioned in this Slate article, @link{https://slate.com/technology/2013/03/facebook-math-problem-why-pemdas-doesnt-always-give-a-clear-answer.html, What Is the Answer to That Stupid Math Problem on Facebook?}.

[.text-center]
Stupid Math Problem on Facebook

@image{images/OrderOfOperationsFB.png, Facebook Math Problem, 400, align="center"}
                                                 



== Explore: (5 mins) Let There Be Numbers!
Have students log into @link{https://www.wescheme.org, WeScheme} and explore numbers in WeScheme in the Interactions window.

[.notice-box]
.Notice & Wonder
**** 
In pairs, students will each try entering a variety of numbers in WeScheme, then together they will write down what they notice and what they wonder.
****


== Discuss: (5 mins)
* What type of numbers did you try?
* What did you notice? What did you wonder?
* Did anyone try any irrational numbers? (Ex: pi or e)
* Did you get any error messages?

== Discuss: (7 mins)
* Did anyone try to Add/Subtract/Multiply/Divide numbers? 
* What was the Error Message? 
* How can we Add/Subtract/Multiply/Divide in WeScheme?

=== Direct Instruction:
At this point, you’ll provide some direct instruction on the Circles of Evaluation & Contracts and how to:

* Create a Circle of Evaluation from an expression.
* Convert a Circle of Evaluation into Racket.
* Write the Contract of a function (Name, Domain, & Range).
* Write the 6 contracts for `+`, `-`, `*`, `/`, `sqr`, and `sqrt` into the Contracts page.


[.text-center]
Circles of Evaluation

@image{images/CoE1.png, Circle of Evaluations, 400, align="center"}
                                          

[.text-center]
Contracts

@image{images/Contracts.png, Contracts, 400, align="center"}

== Practice: (5 mins)  Add/Subtract/Multiply/Divide
Have students practice adding, subtracting, multiplying, and dividing using the 6 functions(`+`, `-`, `*`, `/`, `sqr`, `sqrt`).

== Talking Points

* Do spaces matter when typing in functions?
* Does the order of the numbers matter in the functions? Which functions?
* What do the error messages tell us? 

== Discuss: (10 mins) - Circles of Evaluation w/More than 1 expression

=== Inquiry Based Instruction:
At this point, you’ll provide some Inquiry Based instruction on the Circles of Evaluation with more than 1 expression:

* How  would we model 2*(3+8) with Circle of Evaluation?
* Does the order matter if I put the 2 first or second in the circle for `*`?
* Why is it ok for multiplication to take in a number, 2, and a circle for the 2nd input?(Range of addition is a number)
* What does the code look like?
* What connections do you see between the expression, circle, and code?
* What can you tell students if they don’t know where to start? (Start with 3+8 then connect it to the `*`)
* Model using the Bug that crawls through the Circle 
* Model using Color Coordination

[.text-center]
Circles of Evaluation 
[.text-center]
w/more than 1 expression

@image{images/CoE2.png, Circle of Evaluations, 400, align="center"}



== Practice: (10 mins)  Practice
Have students practice the Circles of Evaluation and Racket by putting expressions all around the room and having them:
Convert the expression into Circles of Evaluation.
Convert the Circle of Evaluation model into Racket Code.
Once the teacher has approved of both models, have them enter the code into WeScheme to test it out.




== Create/Apply: (15 mins) Create Your Own Circles of Evaluation - Frayer Model

Students will create a Create Your Own Circle of Evaluation based on an Expression they’ve created using at least 4 of the 6 functions:
            `+`, `-`, `*`, `/`, `sqr`, `sqrt`.

Using @worksheet-link{workbook-pages/OrderOfOperations1-FrayerModelTemplate.pdf, this Frayer Model}, Create the Code that represents this Circle, translate this into Racket Code, Evaluate using PEMDAS, and then Compare and Contrast the 3 methods.

[.strategy-box]
.Strategies For English Language Learners
****
MLR 7 - Compare and Connect: Gather students Frayer Models to highlight and analyze a few of them as a class, asking students to compare and connect different models of the Circles of Evaluation/Code/PEMDAS. 
****




