= Coding and Designing the Alaskan Flag
++++
<style>
img { margin-right: 1ex; }

/* Push content to the top (instead of the default vertical distribution), which was leaving empty space at the top. */
#content { display: block !important; }
</style>
++++

@link-instructions{
Open the @opt-starter-file{flags-ak}. 
Click run and type "alaska" to see an image of the flag of Alaska. 
}

== Exploring the Code

@n How many images are defined in the code? @fitb{}{@ifsoln{3}}

@n How many images are placed using `translate` in order to generate the flag? @fitb{}{@ifsoln{8}}

@n Why do your answers to these questions differ? @fitb{}{}

@fitb{}{@ifsoln{Images of the `small` star are used 7 times!}}

@n The code for the flag could have been written without defining any images. What are some reasons why defining images makes the code easier to work with?

@fitb{}{@ifsoln{It's more readable - it's easy to see what repeats.}}

@fitb{}{@ifsoln{If we wanted to make a change to the `small` star we wouldn't have to change it in 7 places!}}


== The Story of the Flag of Alaska

@vspace{1ex}

@left{@image{../images/benny-benson.jpeg, 300}} The Alaska state flag is based on a design created in 1926 for a Territory-wide contest for schoolchildren. The thirteen-year-old seventh-grade designer was Benny Benson from the Aleutian Islands. _(At the time, Alaska was not yet a state; it had been a US Territory since the land was purchased from Russia in 1867.)_
 +
 @vspace{1ex}
 +
 On the design submission, Benny had written the following explanation:
 +
 @vspace{1ex}
 +
 _"The blue field is for the Alaska sky and the forget-me-not, an Alaska flower._
 + 
 _The North Star is for the future of the state of Alaska, the most northerly in the Union._
 + 
 _The dipper is for the Great Bear — symbolizing strength."_ +
 @vspace{1ex}
 +
 Benny's flag was officially adopted by the legislature in 1927. 
 +
 @vspace{1ex}
 +
 Alaska was officially recognized as a state on January 3, 1959.
 +
 @n How old was Benny when Alaska achieved statehood? +
 @fitb{}{@ifsoln{46. (If anyone asks, his birthday was September 12.)}}
 +
 @vspace{2ex}
 +
 @n Think of someone you know who is old enough to remember 1959. (Your teacher is not old enough!). Find a time this week to visit or call and ask them if they remember anything about when Alaska became a state! Record what you learn below.

@fitb{}{@ifsoln{This author's relative was 10 in 1959 and remembers reading about it in the weekly paper they got at school in Pennsylvania!}}

@fitb{}{}
