= Decomposing Flags

++++
<style>
#content img { border: solid 1px black; }
#content .centered-image { margin-bottom: 10px; }
#content td * { padding: 0; margin: 0; text-align: center; vertical-align: middle; }
#content tr { height: 2.3rem; font-size: 0.9rem; }
td .autonum:after { content: ") " !important; }
</style>
++++

Each of the flags below is shown with their width and height. Identify the shapes that make up each flag. Use the flag’s dimensions to estimate the dimensions of the different shapes. Then estimate the x and y coordinates for the point at which the center of each shape should be located on the flag. _Hint: The bottom left corner of each flag is at (0,0) and the top right corner is given by the flags dimensions._



[.FillVerticalSpace, cols="^1a,^1a", stripes="none", frame="none"]
|===

| *Cameroon* (450 x 300)
@centered-image{../images/Cameroon.png}
[cols="2a,2a,1a,1a,1a,1a",options="header"]
!===
! shape:				! 	color: 	 	  ! 	width: 		! 	height:     ! x				! y
! @ifsoln{rectangle}	! @ifsoln{green}  ! @ifsoln{150}  	! @ifsoln{300} 	! @ifsoln{75} 	! @ifsoln{150}
! @ifsoln{rectangle}	! @ifsoln{red}	  ! @ifsoln{150}  	! @ifsoln{300} 	! @ifsoln{225} 	! @ifsoln{150}
! @ifsoln{star}			! @ifsoln{yellow} ! @ifsoln{30}  	! @ifsoln{n/a}	! @ifsoln{225}	! @ifsoln{150}
! @ifsoln{rectangle} 	! @ifsoln{yellow} ! @ifsoln{450} 	! @ifsoln{300} 	! @ifsoln{n/a}	! @ifsoln{n/a}
!===

| *Chile* (420 x 280)
@centered-image{../images/Chile.png}
[cols="2a,2a,1a,1a,1a,1a",options="header"]
!===
! shape:			 ! color: 			! width: 		! height: 		! x				! y
! @ifsoln{square}	 ! @ifsoln{blue}	! @ifsoln{140}  ! @ifsoln{140}	! @ifsoln{70} 	! @ifsoln{210}
! @ifsoln{rectangle} ! @ifsoln{white}	! @ifsoln{280}  ! @ifsoln{140} 	! @ifsoln{350} 	! @ifsoln{210}
! @ifsoln{star}		 ! @ifsoln{white}	! @ifsoln{30}  	! @ifsoln{n/a}  ! @ifsoln{70}	! @ifsoln{210}
! @ifsoln{rectangle} ! @ifsoln{red}		! @ifsoln{420}	! @ifsoln{280}	! @ifsoln{n/a}	! @ifsoln{n/a}

!===

| *Panama* (300 x 200)
@centered-image{../images/Panama.png}
[cols="2a,2a,1a,1a,1a,1a",options="header"]
!===
! shape:			 ! color: 			! width: 		! height: 		! x				! y
! @ifsoln{rectangle} ! @ifsoln{blue}	! @ifsoln{150}  ! @ifsoln{100} 	! @ifsoln{75} 	! @ifsoln{50}
! @ifsoln{rectangle} ! @ifsoln{red}		! @ifsoln{150}  ! @ifsoln{100} 	! @ifsoln{225} 	! @ifsoln{150}
! @ifsoln{star}		 ! @ifsoln{blue}	! @ifsoln{30}  	! @ifsoln{n/a}	! @ifsoln{75}	! @ifsoln{150}
! @ifsoln{star}		 ! @ifsoln{red}		! @ifsoln{30}	! @ifsoln{n/a} 	! @ifsoln{225}	! @ifsoln{50}
! @ifsoln{rectangle} ! @ifsoln{white}	! @ifsoln{300}	! @ifsoln{200}	! @ifsoln{n/a}	! @ifsoln{n/a}
!===

| *Norway* (330 x 240)
@centered-image{../images/Norway.png}
[cols="2a,2a,1a,1a,1a,1a",options="header"]
!===
! shape:			 ! color: 				! width: 		! height: 		! x				! y
! @ifsoln{rectangle} ! @ifsoln{dark blue}	! @ifsoln{330}  ! @ifsoln{30} 	! @ifsoln{165} 	! @ifsoln{120}
! @ifsoln{rectangle} ! @ifsoln{dark blue}	! @ifsoln{30} 	! @ifsoln{240} 	! @ifsoln{120} 	! @ifsoln{120}
! @ifsoln{rectangle} ! @ifsoln{white}		! @ifsoln{330}  ! @ifsoln{60}	! @ifsoln{165}	! @ifsoln{120}
! @ifsoln{rectangle} ! @ifsoln{white}		! @ifsoln{60}	! @ifsoln{240} 	! @ifsoln{120}	! @ifsoln{120}
! @ifsoln{rectangle} ! @ifsoln{red}			! @ifsoln{330}	! @ifsoln{240}	! @ifsoln{n/a}	! @ifsoln{n/a}
!===

|===
