= Predicting Steering Angle from Curve _and_ Skew

++++
<style>
/* custom positioning for subscript */
div#body sub { position: relative; bottom: 0.1em; }

div#body img { height: 220px; width: 480px; }

.editbox { background: none !important; }
</style>
++++

Make sure you have @online-exercise{https://www.desmos.com/3d/omnchml87a, Curve v. Skew v. Steering Angle} open in Desmos.

== Working in 3 Dimensions

@centered-image{../images/3d-planes.webp}

@n Adjust the sliders to find a good fit for this data. @math{m_{skew}}: @fitb{15em}{@ifsoln{should be between -2 and -3}} and @math{b}: @fitb{}{@ifsoln{should be between 30 and 45}}.

@n Drag any point in the `Skew v. Steering Angle (purple)` scatter plot. What do you see? @fitb{}{} +
@blanklines{2}{@ifsoln{It's a 3D chart! The purple points are all flattened against the steering-curve plane. All the curve-values are zero. There's a purple plane that rises and falls with changes to @math{b} and @math{m_{skew}}.}}

@n *Return the sliders to zero*, then click the folder icon to "turn on" the `Curve v. Steering Angle (blue)` scatter plot. What do you see? @fitb{}{} +
@fitb{}{@ifsoln{The blue points are flattened against the perpendicular plane. All the skew-values are zero.}}

*Rotate the cube* so that you are looking straight at the blue scatter plot.

@n Adjust the sliders to find a good fit for this data. @math{m_{skew}}: @fitb{15em}{@ifsoln{should be between 15 and 20}} and @math{b}: @fitb{}{@ifsoln{should be between -30 and -10}}.

@n *Return the sliders to zero*, then "turn on" the `Curve v. Skew v. Steering Angle (orange)` folder and spin the cube. What do you see? @fitb{}{@ifsoln{The points are in 3D!}} +
@blanklines{2}{@ifsoln{The purple and blue plots are just "projections" (shadows) of the 3D data onto each 2D plane.}}

@n Fill in the blanks in the image above, showing which variable goes on each axis and which data is projected onto each plane.

== Fitting a 3D Model

@n "Turn off" the 2d projections (blue and purple). Adjust all three sliders to find the *plane of best fit* for this data. (HINT: use the slopes you already found!)

@n Use your slider estimates to fill in the function notation and Pyret code below:

`fun steering-angle(r): (`
@fitbruby{4.5em}{@ifsoln{20}}{@math{m_{curve}}}
`* r["curve"]) + (`
@fitbruby{4.5em}{-2.5}{@math{m_{skew}}}
`* r["skew"]) +`
@fitbruby{4.5em}{0}{@math{b}}
`end`

