= Changing the Scale

@description{Students explore changing the scale on the axes from linear (intervals are consistent) to logarithmic (each interval is exponentially larger than the last).}

@lesson-prereqs{logarithmic2-building-models}

@keywords{logarithm, base}

@add-to-lang{log-base, build-column}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

- Model logarithmic relationships using functions

| Student-facing Lesson Goals
|

- Let's use Pyret to model logarithmic relationships in data


| Materials
|[.materials-links]
@material-links


| Preparation
| 
@preparation{
- Much of the exploration in this lesson hinges on the same custom-built interactive Desmos activity we introduced in @lesson-link{logarithmic1-exploring-wealth-health}.
 * Set the pacing so that students are synced to you and only able to interact with the slide for the lesson section you are working on.
 * Decide how you will share the link or code with students and, if you are using our Google Slides, add the appropriate link to the slide deck.
 * If you don't already have a code, or you want to share a new one, you will first want to:
 *** Open @starter-file{alg2-log-desmos}.
 *** Make a link or code to share with your students.
- _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions-alg2.adoc, _Here's what you need to do._}
}

|===


== Changing the Scale (Sequences and Curves)
@objective{logarithms-growth}
@objective{logarithms-exponents}

=== Overview
Students plot a logarithmic sequence as points on a number line, and explore how changing the intervals to grow exponentially appears to "linearize" the points.

=== Launch

Consider an exponential sequence, with a growth factor of 3: @hspace{1em} @big{@math{1, 3, 9, 27}...}

@QandA{
@Q{What are the next 2 numbers in the sequence?}
@A{81, 243...}

@Q{What does it mean that the @vocab{growth factor} of this sequence is 3?}
@A{The values are doubling.}

@Q{Why is the first number 1, when everything else is even?}
@A{Because the number in the "zero position" is @math{3^0}, which is 1}

@Q{What would this sequence look like, if graphed on the x-axis? The y-axis?}
@A{Points bunched together near the origin, then rapidly spreading out as we move farther and father away}
@A{x-axis: +
@image{images/num-line-h.png, 400}}
@A{y-axis: +
@image{images/num-line-v.png, 50}}
}

@slidebreak

@ifslide{
[cols="^.^8,^.^1", frame="none", options="header"]
|===
| x-axis						| y-axis
| @image{images/num-line-h.png} | @image{images/num-line-v.png}
|===
}

=== Investigate


@teacher{Sync or pace students to *Slide 5: Changing Scale* of @starter-file{alg2-log-desmos}.}

@lesson-instruction{
- Return to the *Fitting Wealth-v-Health and Exploring Logarithmic Models Desmos file*.
- You should now be on *Slide 5: Changing Scale*.
- Use it to complete the first section of @printable-exercise{changing-scale-linear-logarithmic.adoc}.
}

@slidebreak

When we changed the scale of the y-axis from `Linear` to `Logarithmic`, our intervals went from growing linearly to growing exponentially. This is like stretching and squishing our number line, so that each interval represents 10x the length of the interval before it.

Our y-values are still growing exponentially! But now that the intervals are _also_ growing exponentially, this growth is cancelled out visually.

@slidebreak

@lesson-instruction{
- Complete the second section of @printable-exercise{changing-scale-linear-logarithmic.adoc}.
- Talk with your partner and/or other students nearby, to come up with an explanation of what is going on.
- Then tackle the challenge questions below:
}

@QandA{
@Q{Hide everything but the linear function @math{g(x)}. Change the x-axis to `Logarithmic`, but keep the y-axis `Linear`. What happens to the graph? Why?}
@A{The linear graph looks exponential!}
@A{The x-values are still growing linearly, but with the x-_intervals_ growing exponentially it appears to go "right" more slowly than it goes "up".}

@Q{Now change _both_ the x-axis and the y-axis to `Logarithmic`. What happens to the graph? Why?}
@A{The line appears linear!}
@A{Since the intervals are growing at identical rates, the "squish" and the "stretch" cancel each other out.}
}


=== Synthesize
@QandA{
@Q{Why did changing the y-axis to `Logarithmic` make our exponential curve look linear?}
@A{We squished/stretched the y-axis, but kept the x-axis linear. Since the y-values of the curve were growing exponentially, making the y-_intervals_ grow exponentially cancelled out that growth relative to the x-values.}

@Q{Why did changing the *y*-axis to `Logarithmic` make our linear curve look logarithmic?}
@A{The y-values are still growing linearly, but with the y-_intervals_ growing exponentially it appears to go "up" more slowly than it goes "right".}

@Q{We changed the y-axis to be logarithmic, to make our exponential curve look linear. Is there a _different_ way we could have linearized that curve, by changing the _x_-axis?}
@A{If we changed the x-axis to grow _exponentially_, it would have cancelled out the growth in the same way! Unfortunately, this is impossible in Desmos. (But not in Pyret!)}
}

== Changing the Scale to Fit a Model
@objective{model-fit-function}
@objective{logarithms-exponents}

=== Overview
Students take what they've learned about changing the scale, and apply it to their scatter plots of income v. lifespan.

=== Launch

@teacher{Sync or pace students to *Slide 6: Wealth-v-Health (Logarithmic)* of @starter-file{alg2-log-desmos}.}

@lesson-instruction{
- Let's return to the *Fitting Wealth-v-Health and Exploring Logarithmic Models Desmos file*, and open @starter-file{alg2-countries}.
- You should now be on the Slide 6: "Wealth-v-Health (Logarithmic)".
- Use it to complete the first section of @printable-exercise{fitting-logarithmic-models.adoc}.
}

@QandA{
@Q{What values did you come up with for @math{a} and @math{k} in your best-guess logarithmic model?}
@A{Record different students' responses for @math{a} and @math{k} on the board.}

@Q{How do your @math{a} and @math{k} values compare with those of other students'? Are they very similar or very different?}

@Q{What were the @math{S} values for these models?}
}

@slidebreak

Trial-and-error only gets us so far, and it's not clear that we would ever stumble upon the optimal model. 

*We need something like Pyret's `lr-plot`, which uses computational methods to find the optimal model.*

Unfortunately, `lr-plot` only finds _linear_ models in data with _linear_ relationships.

Data Scientists often use transformations to stretch their data into shapes that are easier to work with, and then reverse the transformation when they are done. If only we could _transform_ this data to make it appear linear. Then we could use `lr-plot` to fit the optimal model, and then reverse the transformation to get the optimal logarithmic model!

=== Investigate

@lesson-instruction{
- Complete the last section of @printable-exercise{fitting-logarithic-models.adoc}.
- Be ready to share your logarithmic model, and your answer to the last question!
}

@teacher{
Students will be switching the x-axis of their graph from linear to logarithmic in this section. Make sure they are toggling back and forth between the two views as they look for the best-fitting model.
}

@slidebreak

@QandA{
@Q{A person running on a treadmill doesn't change location. Why not?}
@A{Their forward movement is balanced by the backwards movement of the treadmill.}

@Q{If they run faster and faster, what needs to happen to the treadmill to keep them in the same place?}
@A{The treadmill needs to go faster as well. As long as the treadmill speed increases at the same rate as the runner, they will balance one another's growth.}

@Q{How is the treadmill example comparable to what we've done with our x-axis transformation?}
@A{We are speeding up the growth intervals on the x-axis to "keep up with" the speed of growth in the data so that we can see the pattern better.}
}

We made the x-axis grow faster and "squish" the dots so the function appears to grow more slowly "to the right" than it grows "up". By _transforming the x-axis_ to grow exponentially, we are squashing the coordinate plane so that each interval on the x-axis represents 10x the growth in `pc-gdp` as the one before it. This balances out the logarithmic growth in `median-lifespan`, and warps our logarithmic model so the curved looks like linear.

++++
<style>
/* squish the list items inside the shortListItems box */
.shortListItems ol p { margin: 0 }
</style>
++++
[.shortListItems]
@strategy{Undoing a Log by taking the...Log?}{

Relationships in our scatter plot represent a _ratio of growth_ between two quantities. Consider a simple ratio like 1:3. This means the first quantity grows by one third _with respect to the other_. It can by turned into 1:1 in two ways:

1. Transform the *first* quantity (_multiply_ by 3)
2. Transform the *second* quantity (_divide_ by 3)

In our scatter plot, the ratio is the growth in `median-lifespan` v. the growth in `pc-gdp`. The growth of one is logarithmic _with respect to the growth of the other_. This means there are two ways to linearize the data:

1. Transform the *x-axis* to match the *y* (take the _log_)
2. Transform the *y-axis* to match the *x* (raise to an _exponent_)

We've chosen the first option because _Desmos doesn't offer an exponential transformation of the axes_. There's no way to even let kids experiment, without jumping straight to Pyret! Another reason is that the range of the `median-lifespan` data is so small (52-85 years) relative to the range of `pc-gdp` (600-144,000 dollars) that the transformation has less of an effect on the y-axis than it does on the x-axis!

While the treadmill/ratio analogy doesn't cover inverses in any real depth, the treadmill analogy opens the door to discussing how one kind of change can "cancel out" or "undo" another. We are working to add additional material on inverse functions to our Algebra 2 materials, and hope to release them in the coming year!
}

=== Synthesize

- How does seeing the point cloud as linear help us think about logarithmic growth?
- Transforming the axes only makes things _look_ linear - the actual points haven't changed at all, and we still can't use linear regression to find the best logarithmic model... Can you think of a way we could transform the _data_, instead of the axes?

@slidebreak

Linear regression allows us to find the *computationally optimal model*, not just a model that "fit really well."

@QandA{
@Q{In this project, do we know whether or not our model is the _best?_}
@A{We _do_ know!}

@Q{How do you know?}
@A{By linearizing the data and applying linear regression, we were able to find the optimal model for the transformed dataset. When the transformation is reversed, the optimal linear model becomes the optimal logarithmic one.}
}
