= Inverting Logarithms with Exponentials

@description{Students explore changing the scale on the axes from linear (intervals are consistent) to logarithmic (each interval is exponentially larger than the last).}

@lesson-prereqs{logarithmic2-building-models}

@keywords{logarithm, base}

@add-to-lang{log-base, build-column}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|

- Let's use Desmos to visually fit logarithmic models for our data and test how well they fit in Pyret.


| Materials
|[.materials-links]
@material-links


| Preparation
| 
@preparation{
- Much of the exploration in this lesson hinges on the same custom-built interactive Desmos activity we introduced in @lesson-link{logarithmic1-exploring-wealth-health}.
 * Set the pacing so that students are synced to you and only able to interact with the slide for the lesson section you are working on.
 * Decide how you will share the link or code with students and, if you are using our Google Slides, add the appropriate link to the slide deck.
 * If you don't already have a code, or you want to share a new one, you will first want to:
 *** Open @starter-file{alg2-log-desmos}.
 *** Make a link or code to share with your students.
- _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions-alg2.adoc, _Here's what you need to do._}
}

|===


== Balancing Growth: Functions and Axes
@objective{logarithms-growth}
@objective{logarithms-exponents}

=== Overview
Students deepen their understanding of functions as a "ratio of growth", by experimenting with Desmos's `Linear` and `Logarithmic` settings for x- and y-axes. These settings change the way the axis intervals grow, resulting in @vocab{inverse} behavior in the graph. The logarithmic setting results in _exponentially-increasing_ intervals, which warp the graph of functions in interesting ways! Students explore these changes on a variety of functions.

=== Launch
@slidestyle{Launch}

You've probably heard people talk about the slope of a line as "rise over run", or "rate of change". Both of these terms have to do with _comparing one variable to another_. On a graph where one variable is on the y-axis and the other is on the x-axis, that means _comparing the growth in one axis to growth in another_. 

@slidebreak{Launch}

In a linear function, the growth of the function is @vocab{proportional} to the growth of the input. For example, in the line @math{f(x) = x}, the growth of @math{f(x)} is _exactly the same_ as the growth of @math{x}. 

@QandA{
@Q{What is the slope of the function @math{f(x) = x}?}
@A{The slope is 1.}

@Q{If the growth of @math{f(x)} is _twice_ the growth of @math{x}, what is the slope of that line?}
@A{The slope is 2.}

@Q{If the growth of @math{f(x)} is _one-third_ the growth of @math{x}, what is the slope of that line?}
@A{The slope is @math{\frac{1}{3}}}.
}

@slidebreak{Launch}
*Proportional growth is linear growth.*

@ifnotslide{@right{@image{images/empty-axes.png, 250}}}
When we think about quadratic, exponential, or logarithmic growth, that just means that the variable graphed on the y-axis is growing more than just _proportionally_ - it's growing "quadratically", "exponentially", "logarithmically", etc. That's what makes all these different-shaped curves!

@slidebreak{LaunchR}
@ifslide{@right{@image{images/empty-axes.png, 250}}}
You've graphed all of these lines and curves on axes that grow *linearly*: the tick marks along the x- and y-axis always grow in equal intervals.

But...who says the _axes have to grow linearly?_

@teacher{Sync or pace students to *Slide 5: Balancing Growth (Linear)* of @starter-file{alg2-log-desmos}.}

@slidebreak{Launch}

@lesson-instruction{
- Return to the *Fitting Wealth-v-Health and Exploring Logarithmic Models Desmos file*.
- You should now be on *Slide 5: Balancing Growth (Linear)*.
- Use it to complete the _first two sections_ of @printable-exercise{balancing-growth-linear.adoc}.
}

=== Investigate
@slidestyle{InvestigateR}

@right{@image{images/linear-to-logarithmic.png, 250}}
When we changed the scale of the y-axis from `Linear` to `Logarithmic`, our y-intervals went from growing linearly to growing exponentially: _each interval on the y-axis represents 10x the length of the interval before it._

@slidebreak{Investigate}
Our x-intervals are still growing linearly, so this has the effect of grabbing the top and bottom sides of the graph and "squishing" it. For our function to appear to increase by one inch on the y-axis, it actually needs to increase 10x as much as the inch before it!

With the y-axis appearing to grow more slowly than the x, our linear function "bends" down and looks logarithmic!

@slidebreak{Investigate}

@lesson-instruction{
- Reset both axes back to linear!
- Complete the rest of @printable-exercise{balancing-growth-linear.adoc}
}

@slidebreak{Investigate}
When we changed the scale of the x-axis from `Linear` to `Logarithmic`, our x-intervals went from growing linearly to growing exponentially.

Our y-intervals are still growing linearly, so this has the effect of grabbing the left and right sides of the graph and "squishing" it. For our function to appear to increase by one inch on the x-axis, it actually needs to increase 10x as much as the inch before it!

@slidebreak{InvestigateR}

@QandA{
@right{@image{images/linear-to-exponential.png, 250}}
@Q{Why did changing the *x*-axis to `Logarithmic` make our linear curve look exponential?}
@A{With the x-axis appearing to grow more slowly than the y, our linear function "bends" up and looks exponential!}
}

@slidebreak{Investigate}

The key here is to think in terms of *relative growth*: the scale of one axis _relative to the other_  balances out the growth of @math{f(x)} _relative to_ @math{x}.

@slidebreak{Investigate}

@QandA{
@Q{Why did changing both axes to `Logarithmic` make the line look normal again?}
@A{Since both axes were growing proportionally to each other (linearly!), the growth on each axis is balanced and we can see the original shape of the line.}

@Q{What do you think these transformations would to do to a _logarithmic_ function? An _exponential_ function? }
@A{Solicit some answers} 
}

@slidebreak{Investigate-DN}

@teacher{Sync or pace students to *Slide 6: Balancing Growth (Logs and Exponents)* of @starter-file{alg2-log-desmos}.}

@lesson-instruction{
- Turn to @printable-exercise{balancing-growth-log-and-exp.adoc}, and complete the _first section_.
}

@slidebreak{Investigate}
@QandA{
@Q{Why did changing the x-axis to `Logarithmic` make our logarithmic curve look linear?}
@A{We squished the x-axis, but kept the y-axis linear. Since the y-intervals were growing exponentially relative to the x-intervals, that growth canceled out the logarithmic growth of @math{g}.}

@Q{Why did changing the y-axis to `Logarithmic` make our logarithmic curve look sharper?}
@A{Instead of canceling out the logarithmic growth of the function, we took the "log of the log" - making the effect even sharper.}
}

@slidebreak{Investigate}

@lesson-instruction{
- Complete @printable-exercise{balancing-growth-log-and-exp.adoc}.
}

=== Synthesize
@slidestyle{Synthesize}

@QandA{
The last question on @printable-exercise{balancing-growth-log-and-exp.adoc} asks us how we might make the function @math{h} appear linear, by re-scaling _only_ the x-axis. 

@Q{Desmos gives us two choices for how our intervals grow on the x-axis. What are they?}
@A{Linear (each interval is the same size as the last)}
@A{Logarithmic (each interval is 10x larger than the last)}

@Q{If we wanted to make our exponential function @math{h} appear linear, how would we want the intervals on the x-axis to grow?}
@A{We would need it to "undo" or "cancel out" the logarithmic growth of @math{g}, so we want each interval on the x-axis to be 10x smaller than the one before it.}
@A{Desmos would probably call this "Exponential" scale}

@Q{We made our logarithmic function @math{g} appear linear by changing the x-axis to `Logarithmic`. If we wanted to use the y-axis instead, what kind of scale would it need to be?}
@A{We would need it to "undo" or "cancel out" the exponential growth of @math{h}, so we want each interval on the y-axis to be 10x smaller than the one before it.}

@Q{How might changing the scale help us find a better *logarithm of best fit* for our dataset?}
@A{It's easier to eyeball a line of best fit than a log of best fit, and changing the scale will make the relationship looks linear}
}

@slidebreak{Synthesize}

Desmos is a powerful tool for many things, but it also has many limitations. This is where a programming language comes in handy! We can write code that transforms the axes any way we want: exponentially, quadratically, etc. 

But how does changing the scale help us fit a model?

== Changing the Scale to Fit a Model
@objective{model-fit-function}
@objective{logarithms-exponents}

=== Overview
Students take what they've learned about changing the scale, and apply it to their scatter plots of income v. lifespan.

=== Launch
@slidestyle{Launch-DN}

@teacher{Sync or pace students to *Slide 7: Wealth-v-Health (Logarithmic)* of @starter-file{alg2-log-desmos}.}

@lesson-instruction{
- Let's apply what we've learned about changing scale to our data!
- In order to complete the first section of @printable-exercise{fitting-logarithmic-models.adoc}, you'll need to:
  * Return to the *Fitting Wealth-v-Health and Exploring Logarithmic Models Desmos file*. You should now be on Slide 7: "Wealth-v-Health (Logarithmic)".
  * Open the @starter-file{alg2-countries}.
}

@slidebreak{Launch}

@QandA{
@Q{What values did you come up with for @math{a} and @math{k} in your best-guess logarithmic model?}
@A{Record different students' responses for @math{a} and @math{k} on the board.}

@Q{How do your @math{a} and @math{k} values compare with those of other students'? Are they very similar or very different?}

@Q{What were the @math{S} values for these models?}
}

@slidebreak{Launch}

Trial-and-error only gets us so far, and it's not clear that we would ever stumble upon the optimal model. We need something like Pyret's `lr-plot`, which uses computational methods to find the optimal model.

@lesson-point{
Data Scientists often use transformations to stretch their data into shapes that are easier to work with, and then reverse the transformation when they are done. 
}

If only we could _transform_ this data to make it appear linear... Then we could use `lr-plot` to fit the optimal model, and reverse the transformation to get the optimal @vocab{logarithmic model}!

=== Investigate
@slidestyle{Investigate}

@lesson-instruction{
- Complete the last section of @printable-exercise{fitting-logarithmic-models.adoc}.
- Be ready to share your logarithmic model, and your answer to the last question!
}

@teacher{
Students will be switching the x-axis of their graph from linear to logarithmic in this section. Make sure they are toggling back and forth between the two views as they look for the best-fitting model.
}

@slidebreak{Investigate}

@vspace{1ex}

It's all about balancing rates of change...

@QandA{
@Q{A person running on a treadmill doesn't change location. Why not?}
@A{Their forward movement is balanced by the backwards movement of the treadmill.}

@Q{If they run faster and faster, what needs to happen to the treadmill to keep them in the same place?}
@A{The treadmill needs to go faster as well. As long as the treadmill speed increases at the same rate as the runner, they will balance one another's growth.}

@Q{How is the treadmill example comparable to what we've done with our x-axis transformation?}
@A{We are speeding up the growth intervals on the x-axis to "keep up with" the speed of growth in the data so that we can see the pattern better.}
}

@slidebreak{Investigate}

By _transforming the x-axis_ to grow exponentially, we squashed the coordinate plane so that each interval on the x-axis represents 10x the growth in `pc-gdp` as the one before it. This balances out the logarithmic growth in `median-lifespan`, and warps our logarithmic model so that the curve looks like linear.

@slidebreak{Investigate}

@QandA{
@Q{How did changing the scale impact the quality of your model?  Were you able to get a better @vocab{S-value} with the `logarithmic2` model you made on the logarithmic scale than with the `logarithmic` model you made on the linear scale?}
@A{Answers will vary.}
}


++++
<style>
/* squish the list items inside the shortListItems box */
.shortListItems ol p { margin: 0 }
</style>
++++
[.shortListItems]
@strategy{Undoing a Log by taking the...Log?}{

Relationships in our scatter plot represent a _ratio of growth_ between two quantities. Consider a simple ratio like 1:3. This means the first quantity grows by one third _with respect to the other_. It can by turned into 1:1 in two ways:

1. Transform the *first* quantity (_multiply_ by 3)
2. Transform the *second* quantity (_divide_ by 3)

In our scatter plot, the ratio is the growth in `median-lifespan` v. the growth in `pc-gdp`. The growth of one is logarithmic _with respect to the growth of the other_. This means there are two ways to @vocab{linearize} the data:

1. Transform the *x-axis* to match the *y* (take the _log_)
2. Transform the *y-axis* to match the *x* (raise to an _exponent_)

We've chosen the first option because _Desmos doesn't offer an exponential transformation of the axes_. There's no way to even let kids experiment, without jumping straight to Pyret! Another reason is that the range of the `median-lifespan` data is so small (52-85 years) relative to the range of `pc-gdp` (600-144,000 dollars) that the transformation has less of an effect on the y-axis than it does on the x-axis!

While the treadmill/ratio analogy doesn't cover inverses in any real depth, the treadmill analogy opens the door to discussing how one kind of change can "cancel out" or "undo" another. We are working to add additional material on inverse functions to our Algebra 2 materials, and hope to release them in the coming year!
}

=== Synthesize
@slidestyle{Synthesize}

@QandA{
@Q{How does seeing the point cloud as linear help us think about logarithmic growth?}
@A{It's more straight forward to try to visually fit a line than it is to visually fit a curve.}

@Q{Transforming the axes only makes things _look_ linear - the actual points haven't changed at all, and we still can't use linear regression to find the best logarithmic model... Can you think of a way we could transform the _data_, instead of the axes?}
@A{Give students a chance to share their ideas, but no need to answer the question. That's what @lesson-link{logarithmic4-linearization} is all about!}
}

@slidebreak{Synthesize}

Linear regression allows us to find the *computationally optimal model*, not just a model that "fit really well."

@QandA{
@Q{In this project, do we know whether or not our model is the _best?_}
@A{We _do_ know!}

@Q{How do you know?}
@A{By linearizing the data and applying linear regression, we were able to find the optimal model for the transformed dataset. When the transformation is reversed, the optimal linear model becomes the optimal logarithmic one.}
}
