= Building Exponential Models

@description{Students investigate exponential relationships in data about Covid spread, using an inquiry-based model involving hypothesizing, experimental and computational modeling, and sense-making. They are introduced to table transformations and inverse functions, which are used to fit exponential models onto nonlinear data.}

@lesson-prereqs{exponential1-exploring-covid}

@keywords{exponential, quadratic, square, coefficient}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

-

| Student-facing Lesson Goals
|

-

| Materials
|[.materials-links]
@material-links

| Preparation
| 
@preparation{
- Much of the exploration in this lesson hinges on a custom-built interactive Desmos activity. + 
You will want to:
 * Open @starter-file{alg2-covid-desmos}.
 * Make a link or code to share with your students.
 * Decide how you will share the link or code with students and, if you are using our Google Slides, add the appropriate link to the slide deck.
 * Set the pacing so that students are synced to you and only able to interact with the slide for the lesson section you are working on.
- _If you're a first-time Desmos user, fear not!_ @dist-link{pages/desmos-instructions-alg2.adoc, _Here's what you need to do._}
}
|===


== Exponential Sequences
@objective{exponentials-growth}

=== Overview
Having identified that the Covid scatter plot appears neither linear nor quadratic, students learn about characteristics of exponential functions in tabular form.

=== Launch

++++
<style>
.growth td { padding: 0; }
</style>
++++

Let's review what we know about the behavior of the models we've seen so far:

@right{@image{images/difference-table-linear.png}}Remember that *linear functions* grow by _fixed intervals,_ so the rate of change is _constant_. In the table shown here, each time the x-value increases by 1, we see that the y-value increases by 2. This is true for any set of equal-sized intervals: a line needs to slope up or down at a constant rate in order to be a straight line! +
*If the "growth" is constant, the relationship is linear.*

@clear
@slidebreak

@right{@image{images/difference-table-quadratic.png}}*Quadratic functions* grow by intervals that _increase by fixed amounts!_ In the table to the right, the blue arrows show a differently-sized jump between identical intervals, meaning _the function is definitely not linear!_ However, if we take a look at the _difference between those differences_(shown in red), we're back to constant growth! +
*If the "growth of the growth" is constant, the relationship is quadratic.*

@clear

@vocab{Exponential functions} grow even faster than quadratics.

@slidebreak

@right{@image{images/difference-table-exponential-1.png}}When we calculate the growth between the y-values, we can immediately tell it's not linear. When we try to calculate the "growth of the growth", we see that it's not quadratic either. +
{empty} +
If we calculate the "growth of the _growth of the growth_" (shown in green)... we still haven't found a constant... but we should notice that each of these "growths" just repeats the original pattern of y-values! We could calculate the third difference, fourth difference, and so on - and never reach a stopping point. +
{empty} +
Exponential functions grow so rapidly that looking for "what is _added_ to y?" isn't helpful at all. +
{empty} +

=== Investigate

@right{@image{images/difference-table-exponential-2.png}} +
In order to talk about the growth of an exponential function we need to identify the @vocab{growth factor} by asking ourselves "what is y being _multiplied_ by?" +
{empty} +
*In this case, we can see that the y-values are doubling each time*, so the @vocab{growth factor} is 2!
@clear
@slidebreak

@lesson-instruction{
- Turn to @printable-exercise{classifying-tables.adoc}, and decide what kind of pattern is represented in each table.
- For each table that is growing exponentially, identify the @vocab{growth factor}.
}

=== Synthesize

- TODO

== Exponential Graphs
@objective{exponentials-graph}

=== Overview
Students learn about characteristics of exponential functions in graphical, and function notation form.


=== Launch

Exponential Functions can be written in the form: @math{f(x) = ab^{(x-h)} + k}

Most textbooks only present exponential functions with a horizontal shift of zero. When h=0, we can safely remove it and use this simplified form of the equation: @math{f(x) = ab^x + k}.

@teacher{
@opt{Advance your teacher dashboard of @starter-file{alg2-covid-desmos} to the second slide ("How does horizontal shift transform exponential functions?") and give students a chance to reinforce their understanding of @math{h}-values from other models by connecting it to exponential functions.
}}

=== Investigate

Let's explore what each coefficient of @math{f(x) = ab^x + k} means!

@teacher{
Make sure you've advanced your teacher dashboard of @starter-file{alg2-covid-desmos} to the third slide ("Exploring Exponential Functions") so that students are looking at the correct screen.

Decide whether you want to debrief this activity with your class after each section or at the end.
}

@lesson-instruction{
- Let's return to the *Modeling Covid Spread Desmos file*.
- You should now be on the third slide ("Exploring Exponential Functions").
- Use it to complete @printable-exercise{graphing-models.adoc}.
}

@teacher{
Invite students to consider what new information they have gained by looking at graphical representations rather than tables.
}

@slidebreak

==== Base @math{b}

*The base of an exponential function (@math{b})* must *always be positive*, because exponential functions grow and decay uniformly. 

@indented{_A negative @math{b} would bounce from one side of the y-axis to another._ +
_And, when raised to a fractional power, negative values of @math{b} might also lead to things like_ @math{\sqrt{-2}}!}

[cols="3a,2a,3a", stripes="none", options="header"]
|===
^| Exponential Growth
^| Flat
^| Exponential Decay

^| @image{images/growth.png, 150}
^| @image{images/flat.png, 150}
^| @image{images/decay.png, 150}

| @center{@math{b > 1}} 

- When the base is *larger* than 1, it's called the @vocab{growth factor}, since it determines how quickly the output of function grows.
- The function will start flat and then grow by the "percentage greater than 1". 
- A base of @math{1.25} (or @math{1 + 0.25}) will grow by @math{25%} each time @math{x} grows by 1.

| @center{@math{b = 1}} 

- If the base were *equal* to 1, the function would stay flat without any growth at all (raising 1 to _any_ power will always produce 1!).

| @center{@math{0 < b < 1}} 

- When the base is *smaller* than 1, it's called the @vocab{decay factor}, since it determines how quickly the output of the function drops.
- The function will drop quickly by the "amount less than 1" and then level out close to a horizontal line.
- A base of @math{0.25} (or @math{1 - 0.75}) will shrink by @math{75%} each time @math{x} grows by 1.
|===

@slidebreak

==== Vertical Shift...and Horizontal Asymptote @math{k}

The equation of the horizontal line that an exponential function approaches will always be @math{y = k}. This horizontal line is called an @vocab{asymptote}.

*Adjusting @math{k} shifts the asymptote up and down*, along with the rest of the exponential curve that approaches it.

@slidebreak

==== Initial Value @math{a}

*In exponential function definitions the y-intercept is not represented by a single value (as it would be for linear and quadratic functions).*

Since any value raised to the power of zero is 1, when @math{x = 0} in exponential equations, part of the exponential term _remains_, so we can't just cross out the other terms and look at the constant term.

For example, the y-intercept for the function below will not be 3 (as you might have expected it to be).
- @math{f(x) = 4(2^x) + 3}
- @math{f(0) = 4(2^0) + 3} +
@hspace{2em} @math{= 4(1) + 3 } +
@hspace{2em} @math{= 7}

@QandA{
@Q{So what _is_ the y-intercept of an exponential function?}
@A{Give students time to discuss...}
}

@slidebreak

*The y-intercept of an exponential function is @math{a + k}*!

- If @math{k} is "missing", the coefficient @math{a} is the initial value where @math{x = 0}.
- If @math{a} is "missing", the value of the coefficient is @math{1}.
- If we don't see @math{a} or @math{k} in an exponential equation, the y-intercept of the function is 1.

@lesson-instruction{
- Turn to @printable-exercise{classifying-plots.adoc}, and decide whether the shape of the scatter plot suggests a linear, quadratic, or exponential relationship.
}

=== Synthesize
- TODO

== Recognizing Exponential Relationships
@objective{model-fit-function}
@objective{exponential-situations}

=== Overview
- TODO

=== Launch

*@vocab{Exponential growth} and @vocab{exponential decay} show up all the time!*

@QandA{
Suppose you deposit $100 in a savings account, earning 3% interest each year.
@Q{How much money would be there after 1 year?}
@A{$103, because 3% of $100 is $3}
@Q{How much is there after 2 years?}
@A{$106.90, because 3% of $103 is $3.90}
@Q{After 3 years?}
@A{$109.27}
}

Every year there's a little more money to grow, and the total grows faster than the year before. If you start saving early, that $100 will grow into a lot more money down the road!

@slidebreak

@ifslide{*@vocab{Exponential growth} and @vocab{exponential decay} show up all the time!*}

- Most cells (e.g. bacteria, the cells in a growing fetus, etc.) divide every few hours, doubling the number of cells each time. A single cell will split into 2, those 2 cells will split to become 4, then 8, then 16, etc: the function @math{\text{cells}(\text{hours})} grows exponentially. +

- Unstable atomic nucleus decay into stable nuclei over time, emitting ionizing radiation as a byproduct. We use the term _half-life_ to refer to the length of time it takes for 50% of the atomic nuclei in a radioactive sample to decay: the function @math{\text{unstable-atoms}(\text{half-lives})} decays exponentially.


@slidebreak

If you've ever heard of something called "interest rate", then you know that sometimes we want to think in terms of percentages instead of factors. When your savings account has a 3% interest rate, it means your money is _growing by 3%_ - a @vocab{growth factor} of 1.03.

Converting between *growth rate* and growth factor is easy:

@center{@big{@math{b = 1 + r}}}

If a $50,000 car loses 20% of its value each year, the growth rate is @math{-20%}. Modeling this with an exponential function would mean a growth rate @math{b} of @math{1 - .20 = .80}, for a function @math{\text{value}(\text{years}) = $50,000 * (1 + -.20)^{years} = $50,000(.80)^{years}}.

@slidebreak

@teacher{
In the following activities, students will:

- identify whether various plots, scenarios, and definitions represent linear, quadratic, or exponential functions
- think about and apply their knowledge of growth, decay, initial value, and growth factor

Decide whether you'd like to pull your class back together to discuss after each activity or once they've completed all three.
}

=== Investigate
@lesson-instruction{
- Let's practice identifying linear, quadratic, and exponential growth. With your partner, complete:
  * @printable-exercise{classifying-defs.adoc}
  * @printable-exercise{classifying-descriptions.adoc}
- @opt{For more practice, complete @opt-printable-exercise{classifying-descriptions-2.adoc}}
}

@QandA{
- What strategies did you use to decide if a function was linear, quadratic, or exponential?
- When a function was exponential, how did you recognize whether it was growing or decaying?
- What new insights did you gain about exponential functions by thinking about them in real-world scenarios?
}

@teacher{
Have students share their answers, asking them to notice and wonder about the sequences for the exponential examples. How are these sequences growing or decaying? How is that growth or decay different from what they've seen before?
}

@strategy{Optional Activity: Guess the Model!}{

1. Divide students into teams of 2-4, and have each team come up with an exponential, real-world scenario, then have them write down an exponential function that fits this scenario on a sticky note. Make sure no one else can see the function!
2. On the board or some flip-chart paper, have each team draw a _scatter plot_ for which their exponential function is best fit. They should only draw the point cloud - _not the function itself!_ Finally, students title their scatter plot to describe their real-world scenario (e.g. - "money in a savings account vs. years").
3. Have teams switch places or rotate, so that each team is in front of another team's scatter plot. Have them figure out the original function, write their best guess on a sticky note, and stick it next to the plot.
4. Have teams return to their original scatter plot, and look at the model their colleagues guessed. How close were they? What strategies did the class use to figure out the model?

- The coefficients can be constrained to make the activity easier or harder. For example, limiting these coefficients to whole numbers, positive numbers, etc.
- To extend the activity, have the teams continue rotating so that each group adds their sticky note for the best-guess model. Then do a gallery walk so that students can reflect: were the models all pretty close? All over the place? Were the guesses for one coefficient grouped more tightly than the guesses for another?
}

=== Synthesize

- You looked at several different representations of exponential functions: tables, graphs, descriptions, and equations.
- Which representation was the _most_ useful for you? Why?
- Which representation was the _least_ useful for you? Why?

