= Method Chaining

@ifproglang{pyret}{
@description{Students learn how to chain Methods together, and define more sophisticated subsets.}
}

@ifproglang{codap}{
@description{Students learn how to chain Transformers together, and define more sophisticated subsets.}
}

@lesson-prereqs{functions-dr, table-methods}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* Use chaining to write more sophisticated analyses using @ifproglang{pyret}{less code} @ifproglang{codap}{fewer clicks}

* Identify bugs introduced by chaining @ifproglang{pyret}{methods} @ifproglang{codap}{Transformers} in the wrong order

| Student-facing Lesson Goals
|

@ifproglang{pyret}{
* Let's practice writing functions and combining methods.
}
@ifproglang{codap}{
* Let's practice combining Transformers together.
}

| Materials
|[.materials-links]

@material-links

| Preparation
|
@ifproglang{pyret}{* All students should log into @link{https://code.pyret.org, CPO} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can @link{https://code.pyret.org/editor#share=1ZupMVPWvVUOM0HCWyA7cRBghSLKxPWv1, open a new one}}

|===

== Design Recipe Practice @duration{25 minutes}

=== Overview
Students practice more of what they learned in the previous lesson, applying the Design Recipe to make @ifproglang{codap}{Transformers with unique expressions} @ifproglang{pyret}{table functions} that operate on rows of the Animals Dataset. These become the basis of the chaining activity that follows.

=== Launch
The Design Recipe is a powerful tool for solving problems by writing @ifproglang{pyret}{functions} @ifproglang{codap}{expressions}. It's important for this to be like second nature, so let's get some more practice using it.

=== Investigate
[.lesson-instruction]
- Open your saved @starter-file{animals}.
- Define the @ifproglang{pyret}{functions} @ifproglang{codap}{Transformers and  expressions} on @printable-exercise{pages/design-recipe-1.adoc} and @printable-exercise{pages/design-recipe-2.adoc}.


[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Optional: Combining Booleans}

Suppose we want to build a table of Animals that are fixed _and_ old, or a table of animals that are cats _or_ dogs?

By using the `and` and `or` operators, we can _combine_ boolean tests @ifproglang{codap}{on a single Transformer, like `Filter`.} @ifproglang{pyret}{, as in: `(1 > 2) and ("a" == "b")`} @ifproglang{codap}{Once we've opened the `Filter` Transformer, we would tell CODAP to keep all rows that satisfy `Species = "cat" and Species = "dog"`}. This is handy for more complex programs! For example, we might want to ask if a character in a video game has run out of health points _and_ if they have any more lives. We might want to know if someone’s ZIP Code puts them in Texas or New Mexico. When you go out to eat at a restaurant, you might ask what items on the menu have meat and cheese.

@ifproglang{pyret}{For many of the situations where you might use `and`, there's actually a much more powerful mechanism you can use, called "Method Chaining"!} @ifproglang{codap}{When we want to chain together _different_ Transformers, however, this strategy will not work. We'll need to find another way!}
|===

=== Synthesize
- Did you find yourselves getting faster at using the Design Recipe?
- What patterns or shortcuts are you noticing, when you use the Design Recipe?

== Chaining @duration{25 minutes}

=== Overview
Students learn how to compose multiple table operations (sorting, filtering, building) on the same table - a technique called "chaining".


=== Launch
@ifproglang{pyret}{
Now that we are doing more sophisticated analyses, we might write the following:
```
# get a table with the nametags of all
# the fixed animals, ordered by species
with-labels = animals-table.build-column("labels", nametag)
fixed-with-labels = with-nametags.filter(is-fixed)
result = fixed-with-labels.order-by("species", true)
```

That's a lot of code, and it also requires us to come up with names for each intermediate step! Pyret allows table methods to be _chained together_, so that we can build, filter _and_ order a Table in one shot. For example:

```
# get a table with the nametags of all
# the fixed animals, ordered by species
result = animals-table.build-column("labels", nametag).filter(is-fixed).order-by("species", true)
```

This code takes the `animals-table`, and builds a new column called `label`. `.build-column` produces a new Table...and we that Table's whose `.filter` method. `.filter` produces _yet another Table_ (of all fixed animals) and we call _that_ Table’s `order-by` method. The Table produced by `.order-by` is our final result.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Teaching Tip}

Use different color markers to draw _nested boxes_ around each part of the expression, showing where each Table came from.
|===

It can be difficult to read code that has lots of method calls chained together, so we can add a line-break before each “`.`” to make it more readable. Here’s the exact same code, written with each method on its own line:

```
# get a table with the nametags of all
# the fixed animals, order by species
animals-table
  .build-column("label", nametag)
  .filter(is-fixed)
  .order-by("species", true)
```
}
@ifproglang{codap}{
Now that we are doing more sophisticated analyses, we might find ourselves in a situation where we want to use a series of Transformers!

Suppose a journalist comes to the shelter who wants to write a story about a successful pet adoption -- but she has a very specific set of criteria. The reporter wants to report on the adoption of an animal that weighs no more than 9 kilograms. She also wants to review an updated copy of the dataset each week (reflecting changes to the shelter's population) before making a decision about which animal to showcase.

In CODAP, we can use the result of one Transformer as the dataset for another Transformer! To help the journalist, you decide that you want to use *two* Transformers: _Build Attribute_ and _Filter_. But in which order?

[.lesson-instruction]
- The _Build Attribute_ Transformer we must define uses this formula: `pounds/2.205`. It also requires that we provide a name for our new attribute, such as `kilograms`.
- The _Filter_ Transformer that we must define uses this formula: `kilograms<9`.
- Which of the two above Transformers should we apply _first_, `weight-in-kg` or `filter-if-light`?
- What do you predict will happen if we apply them in the wrong order? Why?

A perk of applying Transformers, rather than manipulating the dataset, is that any updates made to the original dataset will flow through the chain. As you chain together Transformers, it is important to remember the following:
}
[.lesson-point]
Order matters: Build / Transform, Filter, Sort.

Suppose we want to build a column and then use it to filter our table. If we use the @ifproglang{pyret}{methods} @ifproglang{codap}{Transformers} in the wrong order (trying to filter by a column that doesn’t exist yet), we might wind up crashing the program. Even worse, the program might work, but produce results that are incorrect!

@ifproglang{codap}{

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Tip: Saving Transformers and Renaming Tables}

Saving a particular configuration of a Transformer is useful so that the Transformer can be easily accessed in the future. When we save a Transformer, we want to give it a useful name and purpose statement for ease of use later.

We also encourage students to rename tables descriptively. By the end of this exercise, the table students create will have quite a lengthy name: `(Sort(Filter(BuildAttribute(Animals-Dataset))))`. That's a lot of parentheses! As an alternative, students might consider using the following table names in this activity: `animals-in-kg`, followed by `light-animals-in-kg`, and then `ordered-light-animals-in-kg`.
|===

}
=== Investigate
[.lesson-point]
When chaining @ifproglang{pyret}{methods} @ifproglang{codap}{Transformers}, it’s important to build @ifproglang{codap}{and transform }first, then filter, and then order.

How well do you know your table methods? Complete @printable-exercise{pages/chaining-methods.adoc} and @printable-exercise{pages/chaining-methods-order-matters.adoc} in to find out.


=== Synthesize
Ask students about their answers to @printable-exercise{pages/chaining-methods-order-matters.adoc}. Which ones produce an error? Why do will they produce an error, and how can this be fixed?

As our analysis gets more complex, chaining is a great way to re-use code we've already written. And less code means a smaller chance of bugs.

@ifproglang{codap}{

== Additional Exercises
- @opt-printable-exercise{pages/chaining-methods-table-transformations.adoc}

}
