= Method Chaining

@ifproglang{pyret}{
@description{Students learn how to chain Methods together, and define more sophisticated subsets.}
}

@ifproglang{codap}{
@description{Students learn how to chain Transformers together, and define more sophisticated subsets.}
}

@lesson-prereqs{defining-table-functions}

@keywords{}

[@lesson-intro-table]
|===
| Lesson Goals
| Students will be able to...

* Use method chaining to write more sophisticated analyses using @ifproglang{pyret}{less code} @ifproglang{codap}{fewer clicks}

* Identify bugs introduced by chaining @ifproglang{pyret}{methods} @ifproglang{codap}{Transformers} in the wrong order

| Student-facing Lesson Goals
|

@ifproglang{pyret}{
* Let's practice writing functions and combining methods.
}
@ifproglang{codap}{
* Let's practice combining Transformers together.
}

| Materials
|[.materials-links]
@ifproglang{pyret}{
* @link{https://docs.google.com/presentation/d/1jBoQJfEf8-SuAEEu3Y-u_aYdEEjAQEjOM4G-kv6I9y4/, Lesson Slides}
}
@ifproglang{codap}{
* @link{https://docs.google.com/presentation/d/1xL947djoE8HWIQhBbTPoZtBWDDZ_MHdhuVGGs9jBOU8/edit?usp=sharing, Lesson Slides}
}

@material-links

| Preparation
|
@ifproglang{pyret}{* All students should log into @link{https://code.pyret.org, CPO} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can @link{https://code.pyret.org/editor#share=1ZupMVPWvVUOM0HCWyA7cRBghSLKxPWv1, open a new one}}

@preparation

|===

== Design Recipe Practice @duration{25 minutes}

=== Overview

Students practice more of what they learned in the previous lesson, applying the Design Recipe to make @ifproglang{codap}{Transformers with unique expressions} @ifproglang{pyret}{table functions} that operate on rows of the Animals Dataset. These become the basis of the chaining activity that follows.

=== Launch
The Design Recipe is a powerful tool for solving problems by writing @ifproglang{pyret}{functions} @ifproglang{codap}{formula expressions}. It's important for this to be like second nature, so let's get some more practice using it with the @starter-file{animals}.

=== Investigate
[.lesson-instruction]
Define the @ifproglang{pyret}{Compute functions on} @ifproglang{codap}{Transformers and formula expressions on} @printable-exercise{pages/design-recipe-1.adoc} and @printable-exercise{pages/design-recipe-2.adoc}.


[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Optional: Combining Booleans}

Suppose we want to build a table of Animals that are fixed _and_ old, or a table of animals that are cats _or_ dogs?

By using the `and` and `or` operators, we can _combine_ boolean tests @ifproglang{codap}{on a single Transformer, like `Filter`.} @ifproglang{pyret}{, as in: `(1 > 2) and ("a" == "b")`} @ifproglang{codap}{Once we've opened the `Filter` Transformer, we would tell CODAP to keep all rows that satisfy `Species = "cat" and Species = "dog"`}. This is handy for more complex programs! For example, we might want to ask if a character in a video game has run out of health points _and_ if they have any more lives. We might want to know if someone’s ZIP Code puts them in Texas or New Mexico. When you go out to eat at a restaurant, you might ask what items on the menu have meat and cheese.

@ifproglang{pyret}{For many of the situations where you might use `and`, there's actually a much more powerful mechanism you can use, called "Method Chaining"!} @ifproglang{codap}{When we want to chain together _different_ Transformers, however, this strategy will not work. We'll need to find another way!}
|===



=== Synthesize
Did students find themselves getting faster at using the Design Recipe? Can students share any patterns they noticed, or shortcuts they used?

== Chaining @duration{25 minutes}

=== Overview
Students learn how to compose multiple table operations (sorting, filtering, building) on the same table - a technique called "chaining".


=== Launch
@ifproglang{pyret}{
Now that we are doing more sophisticated analyses, we might find ourselves writing the following code:
----
# get a table with the nametags of all the fixed animals, ordered by species
with-labels = animals-table.build-column("labels", nametag)
fixed-with-labels = with-nametags.filter(is-fixed)
result = fixed-with-labels.order-by("species", true)
----

That's a lot of code, and it also requires us to come up with names for each intermediate step! Pyret allows table methods to be _chained together_, so that we can build, filter _and_ order a Table in one shot. For example:

----
# get a table with the nametags of all the fixed animals, ordered by species
result = animals-table.build-column("labels", nametag).filter(is-fixed).order-by("species", true)
----

This code takes the `animals-table`, and builds a new column. According to our Contracts Page, `.build-column` produces a new Table, and that’s the Table whose `.filter` method we use. That method produces _yet another Table_, and we call that Table’s `order-by` method. The Table that comes back from that is our final result.


[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Teaching Tip}

Use different color markers to draw _nested boxes_ around each part of the expression, showing where each Table came from.
|===

It can be difficult to read code that has lots of method calls chained together, so we can add a line-break before each “`.`” to make it more readable. Here’s the exact same code, written with each method on its own line:

----
# get a table with the nametags of all the fixed animals, order by species
animals-table
  .build-column("label", nametag)
  .filter(is-fixed)
  .order-by("species", true)
----
}
@ifproglang{codap}{
Now that we are doing more sophisticated analyses, we might find ourselves in a situation where we want to use a series of Transformers!

Let’s say that a journalist comes to the shelter. She wants to write a story about a successful pet adoption--but she has a very specific set of criteria. The reporter wants to report on the adoption of an animal that weighs no more than 9 kilograms. She wants to consider all eligible animals in order from lightest to heaviest.

This reporter also informs you that it might take some time for her to find the perfect pet adoption scenario. Until she finds what she’s looking for, she wants a weekly updated list of the pets who meet her criteria.

Let's break down the reporter's specifications:
[.lesson-instruction]
- Give the weight in kilograms.
- Include only animals that weigh no more than 9 kilograms.
- Order weight in kilograms from lightest to heaviest.
- Update the table weekly to reflect the changing population of the shelter. (In other words, if an animal is removed from or added to the shelter's dataset, we want the reporter's spreadsheet to change as well.)

The journalist has a lot of needs!

Fortunately, in CODAP, we can use the result of one Transformer as an input to another. In other words: Transformers can be chained, resulting in a sequence of datasets, each a transformed version of the previous. Any updates made to an input dataset will flow through and affect its outputs. If you have a chain of transformed datasets and you change the original dataset, the updates will flow through the chain.

As you chain together Transformers, it is important to remember the following:
}
[.lesson-point]
Order matters: Build / Transform, Filter, Sort.

Suppose we want to build a column and then use it to filter our table. If we use the @ifproglang{pyret}{methods} @ifproglang{codap}{Transformers} in the wrong order (trying to filter by a column that doesn’t exist yet), we might wind up crashing the program. Even worse, the program might work, but produce results that are incorrect!

@ifproglang{codap}{

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Tip: Saving Transformers and Renaming Tables}

Saving a particular configuration of a Transformer is useful so that the Transformer can be easily accessed in the future. When we save a Transformer, we want to give it a useful name and purpose statement. Just as functions in algebra can be re-used with multiple inputs, Transformers can be re-used with multiple tables.

We also encourage students to rename tables descriptively. By the end of this exercise, the table students create will have quite a lengthy name: `(Sort(Filter(BuildAttribute(Animals-Dataset))))`. That's a lot of parentheses! As an alternative, student might consider using the following table names in this activity: `animals-in-kg`, followed by `light-animals-in-kg`, and then `ordered-light-animals-in-kg`.
|===

Let’s go through how we might meet the journalist’s needs.

- Give the weight in kilograms.

For this step, we’ll use `Build Attribute`, which makes a new copy of the dataset, adding a column for weight in kilograms. Name the Transformer `build-weight-kg`, and name the new attribute `weight-kg`. As you write your expression, remember that to get from pounds to kilograms, we divide by 2.205. Note: If you prefer, using `Transform Attribute` would work here as well.

- Include only animals that weigh no more than 9 kilograms.

Now, open the `Filter` Transformer, and name it `filter-if-light`. We aren't finding the light animals from the original dataset, however; that wouldn't work because all weights are listed in _pounds_ there! We must filter the dataset we created in the _previous_ step. In the dropdown menu of datasets, select the dataset named `(BuildAttribute(Animals-Dataset))`. Now, enter the appropriate expression that will keep all animals that are no more than 9 kilograms.

- Order weight in kilograms from lightest to heaviest.

Open the `Sort` Transformer. Name the Transformer appropriately - perhaps `order-by-weight`. Again, the dataset we want to sort is _not_ the original animals dataset. Rather, we need to sort the now _twice-transformed_ table! Look closely at table names provided in the dropdown menu to ensure that you're choosing the correct one.

- Update the table weekly to reflect the changing population of the shelter.

Because we’re using Transformers, each time the Animals Table is updated, the journalist’s table will be updated, too! Try adding or removing a row from the original table and observe the ripple effect in your chained tables.
}
=== Investigate
[.lesson-point]
When chaining @ifproglang{pyret}{methods} @ifproglang{codap}{Transformers}, it’s important to build @ifproglang{codap}{and transform }first, then filter, and then order.

How well do you know your table methods? Complete @printable-exercise{pages/chaining-methods.adoc} and @printable-exercise{pages/chaining-methods-order-matters.adoc} in your Student Workbook to find out.


=== Synthesize
Ask students about their answers to @printable-exercise{pages/chaining-methods-order-matters.adoc}. Which ones produce an error? Why do will they produce an error, and how can this be fixed?

As our analysis gets more complex, chaining is a great way to re-use work we've already done. And less duplicate work means a smaller chance of bugs. Chaining is a powerful way to work, so it’s critical to think carefully when we use it!


== Additional Exercises
- @opt-printable-exercise{pages/chaining-methods-table-transformations.adoc}
