[.landscape]
= Contracts

Contracts tell us how to use a function. e.g.  `ellipse {two-colons} Number, Number, String, String -> Image` tells us that the name of the function is  `ellipse`, and that it takes four inputs (two  Numbers and two Strings). From the contract, we know  `(ellipse 100 50 "outline" "teal")` will evaluate to an Image.

[.contracts-table, cols="4,1,10,1,2", options="header", grid="rows"]
|===

| Name
|
| Domain
|
| Range

| `;` `circle`
| `{two-colons}`
| @ifsoln{`Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{ `_(circle 45 "outline" "darkgreen")_`}

| `;` `square`
| `{two-colons}`
| @ifsoln{`Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_(square 70 "outline" "lightblue")_`}

| `;` `rectangle`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_(rectangle 20 80 "solid" "gold")_`}

| `;` `text`
| `{two-colons}`
| @ifsoln{`String, Number, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_(text "I'm thankful for..." 50 "brown")_`}

| `;` `ellipse`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_(ellipse 70 30 "outline" "red")_`}

| `;` `regular-polygon`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_(regular-polygon  40 8 "solid" "red")_`}

| `;` `rhombus`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_(rhombus 20 50 "solid" "turquoise")_`}

| `;` `right-triangle`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_(right-triangle 20 50 "outline" "black")_`}

| `;` `isosceles-triangle`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_(isosceles-triangle 100 30 "solid" "black")_`}

| `;` `radial-star`
| `{two-colons}`
| @ifsoln{`Number, Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_(radial-star  17 50 10 "solid" "orange")_`}

|===

