= Trends in Food and Farming

@description{Students learn about the rise of railroads and refrigerated train cars and the shifts in food production/consumption which they enabled.}

@lesson-prereqs{}

@keywords{}

@add-to-lang{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* use data to explain how the invention of the refrigerated railroad car impacted where people lived and how they grew and transported their food starting in 1800.
* create line charts.
* read trends from line charts.
* synthesize data across two line charts.

| Student-facing Lesson Goals
|

* Let's

| Materials
|[.materials-links]

@material-links

|===

== xyz

Complete the @printable-exercise{do-now.adoc}

=== Overview

=== Launch

=== Investigate

=== Synthesize

0-3 minutes—Do Now:
Students enter the classroom silently and complete their Do Now.

3-4 minutes—Pair-Share:
Prompt students to complete a Turn and Talk to share answers with their neighbor: “Before we begin, please share your answers with your neighbor.”

4-5 minutes—Share Out:
Call on select students to share out while revealing correct answers under the document camera. Do not get into deeper questions about trends, as that comes later.

5-7 minutes—Recap the Unit and Yesterday:
“Welcome Back, New York Times reporters! Today, we will be diving into the fifth day of our Data Science Unit and remember we are attempting to discover the answers to our big unit questions: How has the way Americans get food changed from the time of early Native Americans up until now? Does the way we eat now seem better or worse than before?”

“Yesterday, we saw how land, population sizes, and jobs have changed in North America from the 1600s to now. We saw how the Native American population decreased while European settlers and immigrants increased. We also saw that recently, fewer people were coming to America to farm.”
7-9 minutes—Homework Check:
“Before we move on, let’s see how you did on your homework!”

Reveal correct answers quickly under the document camera while calling on selected students.

“Awesome! We will continue to use your graphing skills today!
9-14 minutes—New Vocabulary
“To start off today, let’s begin by revisiting the charts you saw on your Do Now. What do these charts show us?” Allow students to share out.

“What you are starting to describe to me is the idea of trends in data science. A trend in a line chart tells if something is increasing or decreasing over time.” Students should record trend in their notebooks.

“With your partner, what trend do you see in each chart?” Allow students to work together with their partner and record what they think the trend is.

Students share out, then Stamp for Understanding by revealing the answer in PPT.

14-15 minutes—Frame the Day:
“This leads us to our big question of today: If America’s proportion of farmers is decreasing while the population size is increasing, where is all our food coming from? We are going to head out to look at some evidence found at the National Museum of American History to see what clues we can find. How do we still have enough food? Let’s begin!”
15-18 minutes—Background Knowledge
Use slides 9-13 to provide background knowledge to students.
Slide 9: In 1804, the railroad is invented.
Slide 10: By 1880s railroads had been built across the U.S.
Slide 11: Cattle for beef could be shipped around the country in stock cars, so farms could be farther away.
Slide 12: In the 1850s the refrigerator car was invented. This was a huge deal for farmers.
Pause to ask students why they think this might be a big deal.

18-25 minutes—Video
Slide 13: Why was this invention so great? Let’s watch this video made in 1954 (over 65 years ago!) to see why everyone thought this was such a big deal. Answer the questions on your paper as we watch.

Play the first 4-5 minutes of the video.

Pause after 2:15 to answer questions 1 &2. Then, continue. Check answer 3 at the end.
25-27 minutes—Frame Activity & Directions:
“Let’s now use your knowledge of line charts, trends, and railroads to see if we can identify trends in what was shipped in the railroad industry after the invention of the refrigerator car.”

“The following table shows how many tons of cattle and how many tons of prepared beef (meat from butchered cows) were carried on the railroads from 1882 through 1886. (A ton is 2000 pounds.) We are going to use Google Sheets to create line charts to see the trends in the amount of live cattle vs. prepared beef shipped on railroads during this time.

After we have created your charts on the computer, draw them below and answer the questions.”

27-33 minutes—Work Time:
Teacher may choose to model creating the first line chart together as a class. Then, students may create the second one in partners and answer the questions.

Students work together while the teacher circulates.

33-35 minutes—Stamp for Understanding:
Use slides to reveal the correct answers for the trends.

Ask students to share their thoughts about the final question: “Think about the two trends together. What do they suggest about how Americans were getting food?”

Stamp: “Yes! This means we must have been growing our food far away and shipping it into the cities! Even fresh produce and meats could be sent long distances by train, thanks to refrigerator cars.”
35-36 minutes—Framing of Activity:
“It’s time for your final challenge! Read the following text with your partner and then answer the questions. I should hear you whisper-reading together first!”

36-39 minutes—Work Time:
Students work together while the teacher circulates.

39-40 minutes—Stamp for Understanding:
Use Doc Cam to reveal the correct answers for the trends.

Stamp: As the SIZE of farms increased over time, the NUMBER of farms decreased.
40-44 minutes—Evidence Journal:
“It’s time to summarize your findings for today! Make sure to restate the question, answer in complete sentences, and show what you know!

“Turn to your evidence journal and begin: Agree or Disagree? The invention of the refrigerated railroad car changed farming in America. Give 2 pieces of evidence to back up your answer.”

44-45 minutes—Homework Overview:
Tonight your homework is to explore trends in how many Americans were living in cities over the past couple hundred years.

