= Compound Inequalities: Solutions & Non-Solutions

++++
<style>
.fitb{min-width: 3.5em;}
td{height: 4ex;}
td:first-child{padding: 0 !important;}
</style>
++++

For each Compound Inequality listed below, identify 4 _solutions_ and 4 _non-solutions_.  _If there are *no solutions* or the solution set includes *all real numbers* you can write that instead of making a list._

* Solutions for @vocab{intersections}, which use *and* will make both of the expressions `true`.

* Solutions for @vocab{unions}, which use *or* will make at least one of the expressions `true`.

Pay special attention to the numbers in the sample expression! Challenge yourself to use negatives, positives, fractions, decimals, etc. for your `x` values.

[.center]
_The first two have been done for you - Answers will vary!_

[cols="^.^5a, ^.^8, ^.^8", options="header", frame="none"]
|===
| Expression
| 4 solutions that evaluate to `true`
| 4 non-solutions that evaluate to `false`

| `x > 5` and `x < 15`
| **6, 9.5, 12, 14.9**
| **-2, 5, 15, 16.1**

| `x > 5` or `x < 15`
| **All real numbers**
| **No non-solutions**

| `x <= -2` and `x > 7`
| @ifsoln{ _No solution_ 		}
| @ifsoln{ _All real numbers_ 	}

| `x <= -2` or `x > 7`
| @ifsoln{ -2, -3.6, 8, 1000 	}
| @ifsoln{ 7, -1, 0, 5 			}

| `x < 3.5` and `x > -4`
| @ifsoln{ -3.5, 0, 1, 3 		}
| @ifsoln{ 3.5, -4, -8, 400 	}

| `x < 3.5` or `x > -4`
| @ifsoln{ _All real numbers_ 	}
| @ifsoln{ _No non-solutions_ 	}

| `x >= -1` and `x > -5`
| @ifsoln{ -1, 0, 23, 400 		}
| @ifsoln{ -3, -5, -10, -542 	}

| `x >= -1` or `x > -5`
| @ifsoln{ -4.5, -3, -1, 100 	}
| @ifsoln{ -5, -6, -28, -1000 	}

| `x < -4` and `x > 2`
| @ifsoln{ _No solution_ 		}
| @ifsoln{ _All real numbers_ 	}

|===

@vspace{1ex}

@n Could there ever be a union with _no solutions_? Explain your thinking.

@ifsoln{_No. The solution set for each inequality includes a subset of the real numbers and the union of two inequalities will include more than the numbers in either of those subsets._
}

@ifnotsoln{
@span{.blankline}{}

@span{.blankline}{}
}

@vspace{5ex}

@n Could there ever be an intersection whose solution is _all real numbers_? Explain your thinking.

@ifsoln{_No. The solution set for each inequality includes a subset of the real numbers, so the list of numbers where the subsets overlap couldn't possibly include all of the real numbers._
}


@ifnotsoln{
@span{.blankline}{}

@span{.blankline}{}
}
