= Analyzing Survey Results When Data is Dirty
++++
<style>
div#body:not(.LessonPlan) p { min-height: 2rem; }
</style>
++++

@link-instructions{
These questions are designed to accompany the @starter-file{fav-desserts}.
}

@n Paolo made a @ifproglang{pyret}{`pie-chart`}@ifproglang{codap}{`dot plot`} of the `dessert` column and was surprised to discover that *Fruit* was the most popular dessert among 8th graders!

@vspace{1ex}

Make the @ifproglang{pyret}{`pie-chart`}@ifproglang{codap}{`dot plot`} in @proglang to see what he's looking at. Why is this display misleading? How is the data "dirty"?

@fitb{}{@ifsoln{Chocolate and Ice Cream are more popular, but with so many different spelling and capitalization differences}}

@fitb{}{@ifsoln{they show up as many, less-popular different desserts}}

@fitb{}{}

@fitb{}{}


@n What ideas do you have for how the survey designer could have made sure that the data in the `dessert` column would have been cleaner?

@fitb{}{@ifsoln{Change the question so that it is multiple choice rather than open response.}}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n Make a data visualization showing the ages of the 8th graders surveyed. What "dirty" data problems do you spot and how are they misleading?

@fitb{}{@ifsoln{One 8th grader is 41 years old -- that can't be right!}}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n What ideas do you have for how the survey designer could have made sure that the data in the `age` column would have been cleaner?

@fitb{}{@ifsoln{Put limits on possible values for age}}

@fitb{}{}

@fitb{}{}


@n Experiment with making data visualizations for other columns. What other issues can you spot? What other suggestions do you have for how the survey could have been improved?

@fitb{}{@ifsoln{Answers will vary.}}

@fitb{}{@ifsoln{Students may notice that the `gender-id` column has too many variations in spelling and capitalization to be useful.}}

@fitb{}{}

@fitb{}{}
