= Analyzing Survey Results When Data is Dirty
++++
<style>
div#body:not(.LessonPlan) p { min-height: 2rem; }
</style>
++++

@link-instructions{
These questions are designed to accompany the @starter-file{fav-desserts}.
}

@n Paolo made a @ifproglang{pyret}{`pie-chart`}@ifproglang{codap}{`dot plot`} of the `dessert` column and was surprised to discover that *Fruit* was the most popular dessert among 8th graders!

@vspace{1ex}

Make the @ifproglang{pyret}{`pie-chart`}@ifproglang{codap}{`dot plot`} in @proglang to see what he's looking at. Why is this display misleading? How is the data "dirty"?

@blanklines{4}{
@ifsoln{Chocolate and Ice Cream are more popular, but with so many different spelling and capitalization differences they show up as many, less-popular different desserts}
}


@n What ideas do you have for how the survey designer could have made sure that the data in the `dessert` column would have been cleaner?

@blanklines{4}{
@ifsoln{Change the question so that it is multiple choice rather than open response.}
}


@n Make a data visualization showing the ages of the 8th graders surveyed. What "dirty" data problems do you spot and how are they misleading?

@blanklines{4}{
@ifsoln{One 8th grader is 41 years old -- that can't be right!}
}

@n What ideas do you have for how the survey designer could have made sure that the data in the `age` column would have been cleaner?

@blanklines{3}{
@ifsoln{Put limits on possible values for age}
}


@n Experiment with making data visualizations for other columns. What other issues can you spot? What other suggestions do you have for how the survey could have been improved?

@blanklines{4}{@ifsoln{*Answers will vary.* Students may notice that the `gender-id` column has too many variations in spelling and capitalization to be useful.}
}
