= Which Rows? Which Columns?
++++
<style>
table { border-collapse: collapse !important; }
td 	  { padding: 0 !important; }
tr 	  { border-bottom: dashed 1px gray; height: 1in; }
tr:last-of-type { border-bottom: none; }
p { position: relative; margin: 0 !imporant;}
.tooltip img { width: 75px; }
</style>
++++

For each question about the animals dataset below, identify the type of question and fill in the Rows and Columns needed to answer it.

[cols="^.^1, ^.^3, .^20", frame="none", grid="none", stripes="none"]
|===
| @n
| @image{../images/AskQuestions.png, "Ask Questions icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ What question do you have? @fitb{20em}{How old is Boo-boo?}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ What type of question is this? (circle one) @hspace{1.5em} @ifsoln{*Lookup*} @ifnotsoln{_Lookup_} @hspace{1.5em} _Arithmetic_ @hspace{1.5em} _Statistical_


| @n
| @image{../images/ConsiderData.png, "Consider Data icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ Rows: @fitbruby{30em}{}{Just the cats, fixed rabbits, etc.}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ Column(s): @fitbruby{28em}{}{age, weight-in-kilograms, weeks, etc.}
|===

@span{.sectionbreak}{}

[cols="^.^1, ^.^3, .^20", frame="none", grid="none", stripes="none"]
|===
| @n
| @image{../images/AskQuestions.png, "Ask Questions icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ What question do you have? @fitb{20em}{Are there more cats than dogs in the shelter?}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ What type of question is this? (circle one) @hspace{1.5em} _Lookup_ @hspace{1.5em} @ifsoln{*Arithmetic*} @ifnotsoln{_Arithmetic_} @hspace{1.5em} _Statistical_

| @n
| @image{../images/ConsiderData.png, "Consider Data icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ Rows: @fitbruby{30em}{}{Just the cats, fixed rabbits, etc.}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ Column(s): @fitbruby{28em}{}{age, weight-in-kilograms, weeks, etc.}
|===

@span{.sectionbreak}{}

[cols="^.^1, ^.^3, .^20", frame="none", grid="none", stripes="none"]
|===
| @n
| @image{../images/AskQuestions.png, "Ask Questions icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ What question do you have? @fitb{20em}{Do cats get adopted faster than dogs?}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ What type of question is this? (circle one) @hspace{1.5em} _Lookup_ @hspace{1.5em} _Arithmetic_ @hspace{1.5em} @ifsoln{*Statistical*}  @ifnotsoln{_Statistical_}

| @n
| @image{../images/ConsiderData.png, "Consider Data icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ Rows: @fitbruby{30em}{}{Just the cats, fixed rabbits, etc.}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ Column(s): @fitbruby{28em}{}{age, weight-in-kilograms, weeks, etc.}
|===

@span{.sectionbreak}{}

[cols="^.^1, ^.^3, .^20", frame="none", grid="none", stripes="none"]
|===
| @n
| @image{../images/AskQuestions.png, "Ask Questions icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ What question do you have? @fitb{20em}{Which animals has the most legs?}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ What type of question is this? (circle one) @hspace{1.5em} _Lookup_ @hspace{1.5em} @ifsoln{*Arithmetic*} @ifnotsoln{_Arithmetic_} @hspace{1.5em} _Statistical_

| @n
| @image{../images/ConsiderData.png, "Consider Data icon"}
|
// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +a.+ Rows: @fitbruby{30em}{}{Just the cats, fixed rabbits, etc.}

// wrap this in +...+ so that asciidoctor doesn't try to manage lists for us
@hspace{1em} +b.+ Column(s): @fitbruby{28em}{}{age, weight-in-kilograms, weeks, etc.}
|===
