= Functions with Lookups

[.linkInstructions]
Open the @starter-file{row-functions} on your computer, save a copy, and *Click "Run"*!

@n Write the code to lookup the value of the `age` column for each of the rows listed (the first one has been completed for you).

[cols="1a,4a", options="header"]
|===
| row           | code to lookup the value of the `age` column
| `cat-row`     | `cat-row["age"]`
| `dog-row`   	| @ifsoln{`dog-row["age"]`}
| `old-row`     | @ifsoln{`old-row["age"]`}
|===

@n Write the code that uses the `triangle` function to draw a solid, green triangle whose size is 5 times the _age_ of the animal (the first one has been completed for you).

[cols="1a,4a", options="header"]
|===
| row           | code to draw a triangle using 5 times the "age" of the row as the radius
| `cat-row`     | `triangle(5 * cat-row["age"], "solid", "green")`
| `dog-row`   	| @ifsoln{`triangle(5 * dog-row["age"], "solid", "green")`}
| `old-row`     | @ifsoln{`triangle(5 * old-row["age"], "solid", "green")`}
|===

@n Check with your partner or another student to confirm that your code matches.

@n What is the name of the animal defined in `old-row`? @fitb{6em}{@ifsoln{Felix}} How many years old are they? @fitb{}{@ifsoln{16}}

@n How large would you expect their triangle to be? @fitb{}{@ifsoln{80}}

@vspace{1ex}

== age-dot

[.linkInstructions]
Scroll down in the @starter-file{row-functions} until you find the Contract, Examples and Definition for `age-dot`.

@n What is the Domain of this function? @fitb{6em}{@ifsoln{Row}} The Range? @fitb{6em}{@ifsoln{Image}} How many examples does this function have? @fitb{}{@ifsoln{4}}

@n According to the *comment* below the Contract, what should this function should do, when given a Row? @fitb{}{}

@n Look at the first two examples. How do they satisfy the Contract?

@fitb{}{@ifsoln{Both examples show the function consuming one argument, and the Domain has one thing in it}}

@vspace{1ex}

_These examples show us exactly what should be produced for `cat-row` and `dog-row` - the two Rows representing "Sasha" and "Toggle", based on their `age` (`1` and `3`). But they don't show us how the computer should look up the `age` from from the row!_

@n The last two examples do the same thing as the first two examples, but the numbers `3` and `1` have been replaced! + 
Where do they get the numbers from?

@fitb{}{@ifsoln{The numbers have been replaced by Row Lookups}}

@vspace{1ex}

@n How is the definition for the `age-dot` function connected to our examples?

@fitb{}{@ifsoln{The definition follows the pattern of the examples.}}

@fitb{}{}

@n Add an example for `old-row` to match first pair of examples (using the actual number of age). Then add an example for the second pair (using a lookup).

@star Choose one more row that's defined at the top of the file, and add examples for that as well.
