[[questions]]
type = ""
# The prompt we want to use (can be a multi-line string!)
prompt.prompt = """
"""
# The correct choice
answer.answer = ""

# NOTE: By default, the answer and distractor list are shuffled
# randomly! 
# To enforce an order, uncomment the line below to specify where
# the correct answer appears and to use the distractors in the
# order they are written
# prompt.answerIndex = 1
prompt.distractors = [
]
# Specify the path to the image (normally in the same folder)
# NOTE: doesn't work yet!
# image = "question1.png"

# This will add an extra string of text at the bottom of the question.
# Some questions might need some extra explanation
context = """
"""
