= Scatter Plots

@description{Students investigate scatter plots as a method of visualizing the relationship between two quantitative variables. In the programming environemt, points on the scatter plot can be labelled with a third variable!}

@lesson-prereqs{displaying-categorical-data}

@keywords{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* consider explanatory and response roles of variables​
* make scatter plots by hand, given a list of (x,y) pairs
* make scatter plots using Pyret
* identify a possible linear relationship by looking at a point cloud
* Consider unusual observations in a scatter plot

| Student-facing Lesson Goals
|

@ifproglang{pyret}{
* Let's use Pyret to create scatter plots of data.
}

| Materials
|[.materials-links]
* @link{https://docs.google.com/presentation/d/1Hi4kxcW_j7pD9v0ByYTqbt7ZEFF4-tVGZxY6BxO6rmQ/, Lesson Slides}
@material-links

| Preparation
|
* All students should log into @link{https://code.pyret.org, code.pyret.org (CPO)} and open the "Animals Starter File" they saved from the prior lesson. If they don't have the file, they can open a new @starter-file{animals}.

| Key Points For The Facilitator
|
* Make sure students understand what a scatter plot with _no_ relationship looks like.
* Point out that randomly sampling a few points from a population with a pattern may not expose that pattern! _Sample size matters!_
* Emphasize the importance of students using their eyes - it's not just about the numbers.

|===

== Making Scatter Plots @duration{20 minutes}

=== Overview
Students are introduced to questions that ask about __the relationship between one quantitative column and another.__

They explore @vocab{scatter plots}, which are visualizations that show the relationship between two quantitative variables. They learn how to construct scatter plots by hand, and in Pyret.

=== Launch
[.lesson-instruction]
- Do you think that younger animals get adopted faster? Why or why not?
- What kind of display would be helpful here?

Pie and Bar charts help us see the _frequency_ of values in a _categorical_ column. There are other displays, like histograms and box-plots, that help us explore the _distribution_ of values in a _quantitative_ column.

But what we really want is a display that will help us search for a relationship between *two* quantitative columns, and that's exactly what scatter plots do.

[.lesson-point]
Scatter plots plot one column on the x-axis, and the other on the y-axis

Before we can draw a @vocab{scatter plot}, we have to make an important decision: which variable is @vocab{explanatory} and which is @vocab{response}? In this case, are we suspecting that an animal’s weight can explain how long it takes to be adopted, or that how long it takes to be adopted can explain how much an animal weighs?

The first one makes sense, and reflects our suspicion that age plays a role in adoption time. It's customary to use the horizontal axis for our explanatory variable and the vertical axis for the response variable. Each row in the data set will be a point on the scatter plot with `age` for x and `weeks` for y.

=== Investigate
We will produce our scatter plot by graphing each animal’s `age` and `weeks` values as a point on the x and y axes.

[.lesson-instruction]
Complete @printable-exercise{pages/creating-scatterplot.adoc} in your Student Workbook.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{Teaching Tip}

As an alternative to plotting the small table, assign a handful of rows from the _full table_ to each student and them plot those animals on the board. This can be done collaboratively, resulting in a whole-class scatterplot!
|===


[.lesson-instruction]
* Open your “Animals Starter File”. (If you do not have this file, or if something has happened to it, you can always make a new copy @starter-file{animals}.)
* Make a scatter plot that displays the relationship between age and adoption time.
* Are there any patterns or trends that you see here?

=== Synthesize
Have students report back on their findings, both on the computer and on @printable-exercise{pages/creating-scatterplot.adoc}.

@right{@image{images/no-relationship.png, "A scatter plot with no relationship", 250}} Scatter plots show us a collection of points, arranged along two axes. If there's a relationship between these axes, we'll see clumps and clouds of points in the graph. But what will it look like if there's _no relationship at all?_ The image on the right shows a collection of points, with no pattern.

Think back to our discussion of random sampling and statistical inference. If we picked two random animals out of this table and plotted them, we might not see any pattern at all. We might not see a partner if we selected four animals, or even six. But as our sample size increases, the chance of us _missing_ a pattern gets smaller and smaller.

* What pattern do you see?
* Are there any points that seem unusual? Why?

== The Data Cycle @duration{15 minutes}

=== Overview
Students apply what they've learned about scatter plots to the Data Cycle, using it to answer questions about relationships in the animals dataset.

=== Launch
What other factors might contribute how long an animal takes to get adopted? Many apartment buildings do not allow large breeds of dogs, and have a limit on how heavy a tenant's dog can be.

[.lesson-instruction]
Take a look at the animals dataset, either in your workbook or on the @link{https://docs.google.com/spreadsheets/d/1VeR2_bhpLvnRUZslmCAcSRKfZWs_5RNVujtZgEl6umA/edit, google sheet}. Do you think there's a relationship between `weight` and `weeks` in this table? Why or why not?

Let's use the Data Cycle to explore whether there's a connection between weight and adoption time.

=== Investigate
[.lesson-instruction]
Complete the first Data Cycle on @printable-exercise{pages/data-cycle-scatter-plot.adoc}.

- What did you find when you looked at the scatter-plot?
- Does there appear to be a pattern or trend?
- What might be problematic about including every species in the same scatter plot of weight?
- What followup questions do you have?

[.lesson-instruction]
Write your question in the second Data Cycle on @printable-exercise{pages/data-cycle-scatter-plot.adoc}, and complete the Data Cycle for your new question.

=== Synthesize
We’ve got a lot of tools in our toolkit that help us think about an entire _column_ of a dataset:

- We have ways to find measures of center and spread for a given quantitative column.
- We have visualizations that let us see the shape of values in a quantitative column.
- We have visualizations that let us see frequencies or percentages in a categorical column.

What columns is this question asking about?


== Looking for Trends @duration{20 minutes}

=== Overview
Students are asked to identify patterns in their scatter plots. This activity builds towards the idea of _linear associations_, but does not go into depth (as as a later lesson on correlations does).

=== Launch

Shown below is a scatter plot of the relationships between the animals' `pounds` and the number of `weeks` it takes to be adopted.

@centered-image{images/pounds-v-weeks.png, "A scatter plot of Pounds v. Weeks"}

@clear

[.lesson-instruction]
* Can you see a “cloud” around which the points are clustered?
* Does the number of weeks to adoption seem to go up or down as the weight increases?
* Are there any points that “stray from the pack”? Which ones?

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{Teaching Tip}

Project the scatter plot at the front of the room, and have students come up to the plot to point out their patterns.
|===

A straight-line pattern in the cloud of points suggests a linear relationship between two columns. If we can pinpoint a line around which the points cluster (as we’ll do in a future lesson), it would be useful for making predictions. For example, our line might predict how many `weeks` a new dog would wait to be adopted, if it weighs 68 `pounds`.

Do any data points seem unusually far away from the main cloud of points? Which animals are those? These points are called *unusual observations*. Unusual observations in a scatter plot are like outliers in a histogram, but more complicated because it’s the _combination_ of x and y values that makes them stand apart from the rest of the cloud.

[.lesson-point]
Unusual observations are _always_ worth thinking about

- Sometimes they’re just random. Felix seems to have been adopted quickly, considering how much he weighs. Maybe he just met the right family early, or maybe we find out he lives nearby, got lost and his family came to get him. In that case, we might need to do some deep thinking about whether or not it’s appropriate to remove him from our dataset.
- Sometimes they can give you a deeper insight into your data. Maybe Felix is a special, popular (and heavy!) breed of cat, and we discover that our dataset is missing an important column for breed!
- Sometimes unusual observations are the points we are looking for! What if we wanted to know which restaurants are a good value, and which are rip-offs? We could make a scatter plot of restaurant reviews vs. prices, and look for an observation that’s high above the rest of the points. That would be a restaurant whose reviews are _unusually good_ for the price. An observation way below the cloud would be a really bad deal.

=== Investigate

[.lesson-point]
It's not just about the numbers!

In the image below, we can see a few numerical measures on the right that hardly change at all. Meanwhile, the patterns in the scatter plot vary wildly, between a circular pattern and no pattern at all!

@image{images/CloudToCircle.gif, "An animation, showing random point clouds shifting into circular patterns, all with means and standard deviations that are identical to the second decimal"}

Data Scientists and Statisticians use their eyes all the time. Sometimes there's a pattern hiding in the data, which can't be seen just be focusing on numbers and measures. Until we really look at the _shape_ of the data, we aren't seeing the whole picture. (Optional: this animation is from Autodesk, which has an amazing page showing off how similar numbers can be generated from radically different scatterplots. If time allows, have students explore some of the visualizations on the @opt-online-exercise{https://www.autodesk.com/research/publications/same-stats-different-graphs, Autodesk website}!)

[.lesson-instruction]
--
For practice, consider each of the following relationships, always expressed as "response variable vs explanatory variable". First think about whether you'd expect the variables to be related, then make the scatterplot to see if your hunch seems correct. If you see any *unusual observations*, try to explain them!

- The `pounds` of an animal vs its `age`.
- The number of `weeks` for an animal to be adopted vs its number of `legs`
- The number of `legs` vs the `age` of an animal.
- Do you see a linear (straight-line) relationship in any of these, evidenced by a cloud of points that’s clearly rising or falling from left to right? Are there any unusual observations?
--

=== Synthesize
Debrief, showing the plots on the board. Make sure students see plots for which there is no relationship, like the last one!

It might be tempting to go straight into making a scatter plot to explore how weeks to adoption may be affected by age. But different animals have very different lifespans! A 5-year-old tarantula is still really young, while a 5-year-old rabbit is fully grown. With differences like this, it doesn’t make sense to put them all on the same scatter plot. By mixing them together, we may be _hiding_ a real relationship, or creating the illusion of a relationship that isn’t really there! What should we do to explore this theory?
