= Contracts: Making Tables and Displays

@description{Students learn about functions for sorting and counting data in tables, then are introduced to one-variable displays.}

@lesson-prereqs{ds-intro, simple-data-types}

@keywords{pie chart, bar chart, histogram, box plot, data displays, count, sort, contract, function}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* sort & count columns of data in the programming environment
* make pie charts, bar charts, histograms and box plots in Pyret
* understand how to read contracts for any Pyret function

| Student-facing Lesson Goals
|
* Let's learn some functions for counting and sorting data.
* Let's learn how to make data displays in Pyret!

| Materials
|[.materials-links]
@material-links

|===

== Functions for Working with Tables @duration{20 minutes}

=== Overview

Students will be introduced to functions for working with tables, including: @show{(code 'sort)},  @show{(code 'count)} and @show{(code 'first-n-rows)}. In the process they will review simple @vocab{data types} and be introduced to @vocab{contracts} for describing the @vocab{Domain} and @vocab{Range} of any function.

If you have time and interest in digging deeper into contracts, we have a @lesson-link{contracts, whole lesson focused on contracts for image-producing functions}, which students find highly motivating!

=== Launch

[.lesson-instruction]
--
- Open the @starter-file{animals} and click "Run".
- In the Interactions Window on the right type `animals-table` and hit "Enter" to see the default view of the table.
- What do you Notice? (sample answers below)
** _We only see the first 10 rows of the table and would have to click to see the remaining 22 rows._
** _The animals aren't listed in any particular order._
- What do you Wonder? (sample answers below)
** _Is it possible to alphabetize the list, or sort it in other ways?_
--

(If this is the first time your students are seeing a table in @starter-file{editor}, you may also want to acknowledge line 7 of the Definitions area, where `animals-table` is defined along with the names of the 8 columns.)


=== Investigate

[.lesson-instruction]
Have students turn to @printable-exercise{functions-for-tables.adoc} and complete numbers 1-6.

- What did these `sort` expressions do?
** _They took in the `animals-table`, the "Name" column, and true or false... producing a new table, sorted alphabetically (A-Z for true and Z-A for false)_
- Just below question 6, we see the contract for `sort`
- What does it mean that the Domain of `sort` is Table, String, Boolean?
** _The functions needs a Table, a String (describing a column), and a Boolean (an order to sort the column by) in order to do its job._
- What does it mean that the Range of `sort` is Table?
** _The function produces a new table._

[.lesson-instruction]
Have students complete question 7-10.

- How did `sort` work with quantitative columns?
** _true sorted the values from least to greatest. false sorted the values from biggest to smallest._
- What new questions did you think of that could be answered using `sort`?

[.lesson-instruction]
Have students complete @printable-exercise{functions-for-tables-cont.adoc}, working with the `count` and `first-n-rows` functions.

=== Synthesize

- How is the function of `count` different from `sort`?
** `sort` _made a new table that was reordered_
** `count` _made a new table that summarized the data from a column of the original table!_
- How does the function `first-n-rows` work?
** _It makes a new smaller table with the number of rows you type into the expression._
- Does anyone have any questions about the functions or expressions you've worked with today?
- Where have you seen tables summarizing counts in the real world?
- How else do journalists and newscasters display summaries of data besides in tables?
** _Ideally someone will say bar charts!_

== A Visual Scaffold for Putting Functions Together

=== Overview

Students learn to work with more than one function at once, by way of Circles of Evaluation, a visual representation of the underlying structure.

=== Launch

What if we wanted to see the ten youngest animals? How could the `first-n-rows` and `sort` functions work together? What order should we use the functions in?

=== Investigate

One way to organize our thoughts is to diagram what we want to do, using the Circles of Evaluation. The rules are simple:

1) Every Circle must have one - and only one! - function, written at the top.

2) The arguments of the function are written left-to-right, in the middle of the Circle.

Values like Numbers, String, and Booleans are still written by themselves. It’s only when we want to _use a function_ that we need to draw a Circle, and write the values inside from left-to-right.

3) Circles can contain other Circles!


If we want to see the ten youngest animals, our diagram would look like this.

@do{
(define exp1 '(first-n-rows (sort animals-table "age" true) 10))
}

@show{(coe exp1)}

To convert a Circle of Evaluation into code, we start at the outside and work our way in. After each function we write a pair of parentheses, and then convert each argument inside the Circle. The code for this Circle of Evaluation would be: 

@show{(code exp1)}

If we wanted to get extra fancy and see the species count for the youngest ten animals, we could add another layer to our Circle of Evaluation.

@do{
(define exp2 '(count (first-n-rows (sort animals-table "age" true) 10) "species"))
}

@show{(coe exp2)}

That would translate to the following code:

@show{(code exp2)}

[.lesson-instruction]
--
- Turn to @printable-exercise{coe-sort-count.adoc}. 
- Draw circles of evaluation and write code for each of the given scenarios. 
- Then test your code out in @starter-file{animals}.
--

=== Synthesize

- What did you Notice?
- What did you wonder?

== Functions for Making Displays @duration{20 minutes}

=== Overview

Students will be introduced to functions for making one-variable displays in Pyret, including: @show{(code 'pie-chart)}, @show{(code 'bar-chart)}, @show{(code 'box-plot)} and @show{(code 'histogram)}.

The goal here is for students to become familiar with __using contracts to write expressions that will produce displays__. Knowing how to _make_ a histogram doesn't mean a student really understands histograms! We have dedicated, in-depth lessons that focus on each display mentioned in this lesson:

* @lesson-link{bar-and-pie-charts}
* @lesson-link{histograms}
* @lesson-link{histograms2}
* @lesson-link{box-plots}

We also have dedicated lessons for other displays not mentioned here, such as @lesson-link{scatter-plots}, @lesson-link{linear-regression}, @lesson-link{advanced-displays}, etc.

=== Launch

The `count` function summarized the data for a single variable in a new table. But the same information could be communicated as a picture! This is called data visualization, and Pyret has functions that can make displays for us!

=== Investigate

[.lesson-instruction]
--
- Turn to @printable-exercise{exploring-displays-alt.adoc}.
- Let's look at the first function together.
- What is the name of the function?
** _bar-chart_
- What is the Domain of the function?
** _Table, String_
- What is the Range of the function?
** _Image!_
- Take a minute and see if you and your partner can write an expression that will generate a `bar-chart` and give me a thumbs up when you have one building.
- Did `bar-chart` consume a categorical or quantitative column of data?
** _categorical_
- What does the resulting display tell us?
- Make a sketch of the display you just built in Pyret.
- Then work to complete the page, generating each of the other 3 displays. Some of them may be new to you - you are not expected to be an expert in them yet, but you should be able to figure out how to use the contract to get them building!
--

=== Synthesize

- Which displays worked with categorical data?
** _pie-chart & bar-chart_
- Why might you choose a bar chart over a pie chart or vice versa?
** `pie-chart` _only makes sense when you have the full picture, since it's representing the proportion of the whole_
** `bar-chart` _shows the count_
- How are bar charts and histograms different?
** `bar-chart` _summarizes @vocab{categorical} data. Each bar represents the count of a specific category._
** `histogram` _displays the distribution of @vocab{quantitative} data across the range._

== Making More Specific Displays 

=== Overview

Just as we could use Circles of Evaluation with `sort`, `count`, and `first-n-rows`, we can put them to work to help us write code to build more specific displays.

=== Launch

Sometimes we want to drill down into the data and make a display that focuses on a subset of the values.

=== Investigate

Turn to @printable-exercise{coe-displays.adoc} and apply Circles of Evaluation to figure out the code for building more specific displays. 

Displays are often most interesting when compared with other displays. For example, we may want to see how the age range of the animals adopted quickly compares to the age range of all the animals or of the animals that were adopted slowly. Consider what you might compare each of these displays against.