= Finding the Best Split: The Algorithm
++++
<style>
div#body #preamble_disabled { flex-grow: 0 !important; }
div#body .fitb { min-width: 2em !important; }
div#body { --blank-pitch: calc(0.7em + 1em); }
div#body table.fit-content tr td { padding: 0.3em 0.625em !important; }
div#body table { margin: 0 !important; }

div#body .sectionbody > .paragraph:first-child .autonum { padding-top: 2px !important; }
</style>
++++


@n Evaluate `image-dot-plot(training, "tail", animal-img)`, and use the chart to answer the following questions...

@n *When `r["tail"] == true`...*
@hspace{2em} Which species is/are most common, and would make the best prediction? @fitb{}{@ifsoln{cats}}

@hspace{2em}_If our classifier predicts @fitbruby{15em}{@ifsoln{cat}}{most common species *with* tails}, it will be correct @fitbruby{7em}{@ifsoln{5}}{# of that species} out of @fitbruby{8em}{@ifsoln{11}}{# of animals with tails} times._

@n *When `r["tail"] == false`...* Which species would make the best prediction? @fitb{}{@ifsoln{snails and tarantulas}}

@hspace{2em}_If our classifier predicts @fitbruby{15em}{@ifsoln{tarantula or snail}}{most common species *without* tails}, it will be correct @fitbruby{7em}{@ifsoln{2}}{# of that species} out of @fitbruby{8em}{@ifsoln{4}}{# of animals with tails} times._

== Categorical Splits
@n The first row in the table below uses the answers for 1 and 2 (above). _To fill in the rest of the table_, use `image-dot-plot` to see the distribution of `mammal`, `tail`, `swims` and `sex`.

[%autowidth, cols="^,^,^,^", frame="none", stripes="none", options="header"]
|===
| Split on
| "yes" leaf (most common)
| "no" leaf (most common)
| # Correct

| `r["tail"] == true`
| "cat" (5 correct out of 11)
| "snail" or "tarantula" (2 correct out of 4)
| 7

| `r["mammal"] == true`
| @ifsoln{"cat" (5 of 9)}
| @ifsoln{"snail" or "tarantula" (2 of 4)}
| @ifsoln{7}

| `r["swims"] == true`
| @ifsoln{"dog" (4 of 6)}
| @ifsoln{"cat" (4 of 9)}
| @ifsoln{8}

| `r["sex"] == "hermaphrodite"`
| @ifsoln{"snail" (2 of 2)}
| @ifsoln{"cat" (5 of 13)}
| @ifsoln{6}

| `r["sex"] == "female"`
| @ifsoln{"cat" (3 of 7)}
| @ifsoln{"dog" or "snail" or "cat" (2 of 8)}
| @ifsoln{6}
|===

== Quantitative Splits
@n Complete the table below, using `image-dot-plot` to see the distribution of `pounds`.

[%autowidth, cols="^,^,^,^", frame="none", stripes="none", options="header"]
|===
| Split on
| "yes" leaf
| "no" leaf
| # Correct

| `r["pounds"] > 2`
| "cat" (5 of 11)
| "snail" or "tarantula" (2 of 4)
| 7

| `r["pounds"] > 6`
| @ifsoln{"cat" or "dog" (4 of 9)}
| @ifsoln{"snail" or "tarantula" (2 of 4)}
| @ifsoln{6}

| `r["pounds"] > 9.5`
| @ifsoln{"dog" (4 of 5)}
| @ifsoln{"cat" (4 of 10)}
| @ifsoln{8}
|===

== Completing the Tree

@n *Which split(s) will make the best root node?* Choose your split and explain your choice: @fitb{}{@ifsoln{`r["swims"] == true` or `r["pounds"] > 9.5` both lead to the most correct classifications}} +
@fitb{}{}

@n Fill in the root at the top of the tree below, and label the edges with the number of animals in each sub-group. Place a check next to each row of the table that your split predicts correctly.

[cols="3a, 2a", frame="none", border="none", grid="none"]
|===
|
[.data-table, cols="1,^1,^1,^1,^1,^1,^1", stripes="none", options="header"]
!===
! name 			! species	 ! sex				! pounds! tail	! mammal! swims
! "Firepaw"		! "cat" 	 ! "male"			!  9.5	! TRUE	! TRUE	! FALSE
! "Leafpool"	! "cat" 	 ! "female"			! 10.6 	! TRUE	! TRUE	! FALSE
! "Shadestar"	! "cat" 	 ! "female"			!  9.0 	! TRUE	! TRUE	! TRUE
! "Bramble"		! "cat" 	 ! "female"			!  4.1 	! TRUE	! TRUE	! FALSE
! "Brick"		! "cat" 	 ! "male" 			!  8.5 	! TRUE	! TRUE	! FALSE
! "Frisky"		! "dog" 	 ! "female"			!  9.6	! TRUE	! TRUE	! TRUE
! "Socks"		! "dog" 	 ! "female"			! 10.0 	! TRUE	! TRUE	! TRUE
! "stripes"		! "dog" 	 ! "male" 			! 11.1 	! TRUE	! TRUE	! TRUE
! "Snickers"	! "dog" 	 ! "male" 			! 10.3 	! TRUE	! TRUE	! TRUE
! "Bruni"		! "lizard" 	 ! "female" 		!  8.2 	! TRUE	! FALSE	! TRUE
! "Jesús"		! "lizard"	 ! "male" 			!  3.5 	! TRUE	! FALSE	! FALSE
! "Gary"		! "snail"	 !"hermaphrodite"	!  0.02 ! FALSE	! FALSE	! FALSE
! "Turbo"		! "snail"	 !"hermaphrodite"	!  0.03 ! FALSE	! FALSE	! FALSE
! "Charlotte"	! "tarantula"! "male" 			!  0.35 ! FALSE	! FALSE	! FALSE
! "Webs"		! "tarantula"! "female" 		!  0.4  ! FALSE	! FALSE	! FALSE
!===

|
@image{../images/empty-tree.png}
|===
