= What Does the Code Do?

@link-instructions{For this page, you'll need to open the @starter-file{decision-tree} on your computer and click "Run".}

== Defining our `tail-classifier` Function
*Focus on lines 16-27 in the Definitions Area.* +
Take a moment to read the code for `tail-classifier` carefully and discuss it with your partner. Use the @vocab{decision tree} diagram to guide you.

[cols="^.^1a,^3a", frame="none", grid="none"]
|===
| @image{../images/tail-classifier-tree-2.png}
|
```
# tail-classifier :: Row -> String
# consumes an animal, and predicts the species
fun tail-classifier(r):
  if r["tail"] == true:
    "cat"
  else:
    "snail"
  end
end
```
|===

@n What do you *Notice* about this code? What do you *Wonder*? @fitb{}{@ifsoln{It starts with a contract and purpose statement.}} +
@blanklines{1}{@ifsoln{This code uses a bunch of code we've never seen before like `if` and `else`. I see `end` twice. I see a row accessor `r["tail"]`.}}

@n What code should we write to look up the value in the `"tail"` column of a row? @fitb{}{@ifsoln{`r["tail"]`}}

@n What does this part of the function definition do `if r["tail"] == true: "cat"`? @fitb{}{} +
@blanklines{1}{@ifsoln{It checks to see whether the value in the `"tail"` column is `true`, and, if it is, it classifies the animal as a `"cat"`.}}

@n What does this part of the function definition do `else: "snail"`? @fitb{}{} +
@blanklines{1}{@ifsoln{It checks to see whether the value in the `"tail"` column is `true`, and, if it says anything other than `true`, it classifies the animal as a `"snail"`.}}

== Defining Rows
*Focus on lines 30-34 in the Definitions Area.*

@n What do you think `firepaw = row-n(training, 0)` does?  @fitb{}{@ifsoln{defines `firepaw` as the first row in the table}}

@n Type `firepaw` into the Interactions area. Why are some of the cells darker than others? @fitb{}{} +
@blanklines{1}{@ifsoln{The darker cells are the column titles and the lighter cells are the values for those columns from the first row of the table.}}

@n On line 20 of the Definitions Area, define `frisky` to be the sixth row of the table. Then click "Run" again to load the code.

@n Evaluate `firepaw["swims"]`. What did you get? @fitb{2em}{@ifsoln{false}} Where did that come from? @fitb{}{@ifsoln{the cell in the "swims" column of the firepaw row}}

@n What code would tell me if `frisky` is a mammal? @fitb{15em}{@ifsoln{`firepaw["mammal"]`}}. Test it out.

== Some helpful Functions
*Focus on lines 36-58 in the Definitions Area.*

@n What do you think `dog-img = text("🐶", 20, "black")` does? @fitb{}{@ifsoln{defines `dog` as a dog emoji}}

@n Evaluate `dog-img` in the Interactions Area. What did you get? @fitb{}{@ifsoln{a dog emoji}}

@n What does `animal-img(firepaw)` evaluate to? @fitb{10em}{@ifsoln{a cat emoji}} `animal-img(frisky)`? @fitb{}{@ifsoln{a dog emoji}}

@n In the Interactions Area, evaluate `image-dot-plot(training, "tail", animal-img)`. What happens? @fitb{}{}
@blanklines{1}{
@ifsoln{A dot plot appeared using emojis (dog, cat, lizard, etc) instead of dots to represent each animal. They are sorted by which do and don't have a tail.}
} 

@n Type `classify(training, "species", tail-classifier)` in the Interactions Area. What happens? @fitb{}{} +
@blanklines{1}{@ifsoln{We get a table with two new columns: one for predicted species and another that indicates whether or not the prediction is correct.}}

@star Make sure you know how to use `image-dot-plot` to see the distribution of the animals based on `sex`, `mammal`, `tail`, and `swims`.
