= Circles of Evaluation: Distance between (0, 2) and (4, 5)

++++
<style>
#content .editbox{width: auto;}
#content .MathJax{display: inline; }
#content .compare tbody tr { height: 6rem; }
body .big .mathunicode { font-size: 1.5em !important; color: black; }
body .big .mathunicode sup { top: -1em; font-size: 10px; }
body .big .mathunicode .overbar { margin-left: 0.5px; }
td { padding: 0 0.5rem !important; }
</style>
++++

The distance between @math{x_{1}} and @math{x_{2}} is computed by @show{(code '(line-length x2 x1))}. The distance between @math{y_{2}} and @math{y_{1}} is computed by @show{(code '(line-length y2 y1))}. Below is the equation to compute the hypotenuse of a right triangle with legs the lengths of those distances:

[.center.big]
@math{\sqrt{\mbox{line-length}(x_{2}, x_{1})^2 + \mbox{line-length}(y_{2}, y_{1})^2}}

Suppose your player is at *(0, 2)* and a character is at *(4, 5)*. What is the distance between them?

*1. Identify the values of @math{x_{1}}, @math{y_{1}}, @math{x_{2}}, and @math{y_{2}}*

[cols="^.<1a,^.<1a,^.<1a,^.<1a", stripes="none"]
|===
| @math{x_{1}} | @math{y_{1}} | @math{x_{2}} | @math{y_{2}}

| _(x-value of 1st point)_
| _(y-value of 1st point)_
| _(x-value of 2nd point)_
| _(y-value of 2nd point)_

| @vspace{4ex}
|
|
|

|===

@vspace{1ex}

The equation to compute the distance between these points is:

[.center.big]
@math{\sqrt{\mbox{line-length}(4, 0)^2 + \mbox{line-length}(5, 2)^2}}

*2. Translate the expression above, for (0,2) and (4,5) into a Circle of Evaluation below*.

_Hint: In our programming language @show{(code 'sqr)} is used for @math{x^2} and @show{(code 'sqrt)} is used for @math{\sqrt{x}}_

@vspace{1ex}

[.center]
@image{../images/coe-distance2.png, 550}

@vspace{1ex}

*3. Convert the Circle of Evaluation to Code below*.

@ifnotsoln{
@fitb{}{}

@fitb{}{}
}

@showsoln{(code '(sqrt (+ (sqr (line-length 4 0)) (line-length 5 2))))}
