= Scatterplot - Explore

++++
<style>
#content tbody tr { height: 2in; }
</style>
++++

[.center]
`scatter-plot(animals-table, "species", "pounds", "weeks")`
@span{.center}{@image{../images/pounds-v-weeks.png,"",350}}

[cols="^1,^1", options="header"]
|===
| *What do you notice?* | What do you wonder?
|						|
|===

@n What information is included in the code that is not represented in the display?

@span{.blankline}

@n Open the @link{https://code.pyret.org/editor#share=1Yskwvzbe5CSMX3F1fveEOgrL3ms2cxHV&v=1904b2c, Species Starter File} & click run. How does the _interactive chart_ use the `species` data?

@span{.blankline}

@n Find the contract for `image-scatter-plot` on line 19. What is its Domain?

@span{.blankline}

@n How is this Domain different from other functions we've seen?

@span{.blankline}

@n _Let's test it out!_ Type `image-scatter-plot(animals-table, "pounds", "weeks", speciestag)` into the interactions area. Describe the image you see.

@span{.blankline}

@n What can you learn from this new display that you could not learn from the original image?

@span{.blankline}

@n In your own words, explain how the program generates this `image-scatter-plot`.

@span{.blankline}

@span{.blankline}

@n Make a new `image-scatter-plot`, still comparing pounds and weeks to adoption, but labeling each point with the name of the animal instead of its species. Write down the code of the new helper function you added to the file?

@span{.blankline}


