= Mood Generator

++++
<style>
#content tbody tr { height: 4in; }
</style>
++++

@n Open the @link{https://code.pyret.org/editor#share=1ymyvlI7RTtq8lHh4VH3x1N3WlcZB650j, "Mood Generator Starter File"}, and read throught the code you find there. This code contains new programming that you haven't seen yet! Take a moment to list everything you Notice, and then everything you Wonder...

@vspace{2ex}

[cols="^1,^1", options="header"]
|===
| *Notice* 		| *Wonder*
| @ifsoln{_(sample responses) I notice the usual imports at the top, including defining the animals table and the spreadsheet. I notice what looks like a function definition, but I see if/else in there_}
| @ifsoln{(sample responses) I wonder what if/else are all about...}

|===

@vspace{2ex}

@n Add another line of code to the definition, so that  `mood("mad")` produces the _same_ emoji as `mood("angry")`.

@ifsoln{`else if (feeling == "mad"): "😡"`}

@vspace{2ex}

@n Add *another example* to the  `examples:` section for "laughing", using the appropriate emoji. (To bring up the emojis on your computer, type `Cmd-Ctrl-Space` on a Mac, or `Windows-Period` on Windows 10)

@ifsoln{`mood("laughing") is "😂"`}

@vspace{2ex}

@n Come up with some new moods, and add them to the code. Make sure you include `examples:`!

@ifsoln{_(depends on student choice - look for missing quotes, new lines in the definition without lines in the examples, etc.)_}

@vspace{2ex}

@n In your own words, how do  if-expressions work in Pyret? Write your answer below.

@span{.blankline}{@ifsoln{_Every if-expression has a test, which contains a boolean expression. If the test is true, Pyret evaluates whatever comes after it._}}

@span{.blankline}{@ifsoln{_Otherwise, it evaluates whatever comes after the  `else:`_}

@span{.blankline}

@span{.blankline}

@vspace{2ex}

@n Write down at least 2 ways you could use if-expressions when analyzing the Animals Dataset.

@span{.blankline}

@span{.blankline}

@span{.blankline}

@span{.blankline}
