= Page A 3

@showsoln{'(+ x 9) }

@ifsoln{I am in solutions only!}

@ifnotsoln{I am in student-version only!}

@show{(sexp->code '(string=? "ab" "ab"))}

@show{(sexp->code '(string<? "ab" "ab"))}

@show{(sexp->code '(string>? "ab" "ab"))}

@show{(sexp->code '(<> 1 2))}

@show{(contract "scale/xy" '("Number" "Number" "Image") "Image")}
@show{(contract "scale/xy" '("Number" "Number" "Image") "Image")}

@show{(contracts "scale/xy" '("Number" "Number" "Image") "Image"
 "scale/xy" '("Number" "Number" "Image") "Image")}

Dolorem et temporibus illo a. Ullam ut nostrum non mollitia natus
iusto consequatur nisi. Dolorem quo suscipit voluptatem nihil
nihil voluptatem consequatur. Perspiciatis et facere est
voluptatem consectetur. Consequuntur voluptatibus sint possimus.
Est impedit ipsam qui neque sit.

Ipsam illum tempora nostrum autem. Deserunt magni laudantium
praesentium ipsa ipsum. Voluptatem et ipsa eos voluptatibus ex.
Neque et aliquam qui.

Magni inventore dolore sunt quam et blanditiis. Deleniti ipsum
reprehenderit corporis. Error saepe modi eos ad unde. Nemo neque
quis iusto eaque rerum nobis. Molestias non expedita ipsa rem cum
sequi.
