= The Multiplicative Inverse Property

@description{Students develop a more nuanced interpretation of the Commutative and Associative Properties as a result of their exploration of the inverse relationship between multiplication and division.}

@lesson-prereqs{associative-property}

@keywords{Associative Property, Commutative Property}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

@objectives
@objective{Recognize that dividing by @math{x} is the same as multiplying by @math{\frac{1}{x}}.}
@objective{Acknowledge _flexibility_ in the Order of Operations.}

| Student-facing Lesson Goals
|

- Let's explore the inverse relationship between multiplication and division.

| Materials
|[.materials-links]
@material-links

| Key Points For The Facilitator
|
- This lesson is all about _mathematical flexibility_, and may challenge preexisting ideas about arithmetic. For students who've had a mostly procedural introduction to mathematics - or who have high math anxiety - the flexibility introduced by this lesson can be intimidating!
- Embrace an open mind and expect the same of your students, and be attentive to their emotional response as the lesson progresses. If students are getting anxious, they will not be able to concentrate and focus on the content.
- This lesson digs into multiplication and division of unit fractions and whole numbers, emphasizing _structure_ over computation.
- This lesson has a similar structure as @lesson-link{additive-inverse}. Students may benefit from looking back at the pages they completed during that lesson.
|===

== The Multiplicative Inverse Property

=== Overview

Students discover the Multiplicative Inverse Property, which tells us that multiplying a number and its reciprocal always produces one.

=== Launch

The Commutative and Associative Properties help us re-order expression to make them easier to think about and solve. We also know that these properties apply to multiplication, but _not_ division.

... but what if there was a way to _rewrite_ division as multiplication? Then we could apply the Commutative and Associative Properties to division expressions, too! Let’s explore this idea with a game.

@teacher{Draw the following table on the board.}


[cols="^1,^1", options="header"]
|===
| Starting Value		| Reciprocal
| @vspace{3ex}			|
|===

@slidebreak

I'm going to write a number in the left-hand column. You are going to tell me the @vocab{reciprocal} - or the  value I should _multiply_ my starting number by to get a product of 1. I'll record your response in the right-hand column.

@QandA{
@Q{The first number is @math{\frac{1}{2}}. What can I use to multiply that and get 1?}
@Q{The next number is @math{\frac{1}{3}}. What can I use to multiply that and get 1?}
@Q{How about @math{\frac{1}{100}}?}
@Q{How about @math{10}?}
@Q{What's another pair of numbers - a fraction and a whole number - that multiply together to produce 1?}
}

@teacher{Allow a variety of students to share. Record responses on the table.}

@slidebreak

These number pairs all represent @vocab{reciprocals}. The reciprocal of a real number @math{n} is @math{\frac{1}{n}}. These number pairs are also illustrative of the @vocab{Multiplicative Inverse Property}: when we multiply them together, we always end up with a product of @math{1}.

@lesson-point{
The @vocab{Multiplicative Inverse Property} tells us that multiplying a number by its @vocab{reciprocal} always produces one.
}

Every number - except zero - has a reciprocal.

@teacher{A fun challenge question: why doesn't zero have a reciprocal}

=== Investigate

@lesson-instruction{
- Turn to @printable-exercise{multiplicative-inverse.adoc}.
- In the first section, practice finding reciprocals and write them in the space provided.
- Then, fill in the missing number to complete the equations. Some equations use mathematical notation and some use Circles of Evaluation.
}

=== Synthesize

- Can you think of a way to visually represent that a number multiplied by its reciprocal produces one?
- How would you explain the Multiplicative Inverse Property to another student?

== Multiplication and Division: Inverse Operations

=== Overview

Students rewrite multiplication expressions as division, and division expressions as multiplication by applying their knowledge of the @vocab{Multiplicative Inverse Property}.

=== Launch

Now that we understand what a reciprocal is, we are ready to think about how we can put it to use. Perhaps it can make some computations simpler?

@lesson-instruction{
- Complete @printable-exercise{discover-inverse.adoc}.
- When you're finished, complete @printable-exercise{discover-inverse-cont.adoc}.
}

@QandA{What did you notice about the multiplicative inverse and its value when doing mental computation?}

@slidebreak

Hopefully, you discovered two big ideas:

- Dividing by @math{x} produces the same result as multiplying by its reciprocal, @math{\frac{1}{x}}.
- Dividing by @math{\frac{1}{x}} produces the same result as multiplying by its reciprocal, @math{x}.

In other words, when you see multiplication or division by a unit fraction (a fraction with a numerator of @math{1}), there is likely a path forward using *mental computation only*. Understanding how the reciprocal can help us to write equivalent expressions can often make computation much simpler!

=== Investigate

@teacher{Now, students are ready to continue their exploration of multiplication as the inverse of division, while also integrating and applying their knowledge of the Commutative and Associative Properties of Multiplication.}

@lesson-instruction{
Complete @printable-exercise{wodb.adoc}.
}

@teacher{Invite students to share which problems were most challenging, and which ones felt simple. Have students share strategies for determining equivalence.}

=== Synthesize

@QandA{
@Q{Claire and Soraya want to write an equivalent expression for @math{45 \div 9}. Claire studies the expression and announces that, because it involves division, the Commutative Property cannot be applied. Is she correct?}
@Q{Soraya grabs a pencil and writes the following: @math{45 \times \frac{1}{9}}. She says, "There! I fixed it. Now we can apply the Commutative Property." Explain what Soraya did. Is she correct?}
@A{Sample response: Instead of dividing by 9, Soraya is multiplying by the reciprocal. Yes, Soraya has written an equivalent expression and can apply the Commutative Property - but the computation will not be any simpler.}
}

== Is the Order of Operations Universal?

=== Overview

Students learn an algorithm taught in Kenya, which is used for solving certain types of problems. They then compare and contrast it with an algorithm they have likely seen before. They discover that the @vocab{Commutative Property} and @vocab{Associative Property} are more powerful than they initially thought!

=== Launch

@lesson-instruction{
- Consider this expression: @math{100 \times 20 \div 5}
- Rewrite the expression - either by adding parentheses or drawing a Circle of Evaluation - to show your process for solving.
}

@QandA{
@Q{What do we get when we simplify the expression to a single value?}
@A{400}
@Q{How did you arrive at your answer?}
}

@teacher{Invite students to share their responses. If your students have spent any time at all studying the order of operations, they will notice both multiplication and division in the expression. From there, they will likely conclude that they must work from left to right to arrive at a correct result.}

@slidebreak

@QandA{
The solving strategy most commonly used can be represented by this Circle of Evaluation:
@show{(coe '(/ (* 100 20) 5))}

Did anyone use a different method?
}

@teacher{If there is a brave student who opted to divide _before_ multiplying, invite them to share their method and then ask other students to weigh in. If all students worked left to right, ask students to evaluate the Circle of Evaluation below and then assess if it is equivalent to the Circle of Evaluation, above. (Spoiler alert: It is!)}

@slidebreak

@QandA{Does the solving strategy represented below work?
@show{(coe '(* 100 (/ 20 5)))}}

@slidebreak

We’ve learned that the Associative Property applies for expressions with only multiplication... not multiplication _and_ division. Many of us have also learned that when an expression includes multiplication and division, we must work from left to right. *So… what’s going on!?*

=== Investigate

In Kenya, students are taught that in expressions like @math{100 \times 20 \div 5}, they must divide first... and then multiply! But does it actually work, _every_ time? Let’s investigate.

@slidebreak

@lesson-instruction{
@right{@image{images/kenya-flag.png, 150}}

- Turn to @printable-exercise{divide-first-or-left-to-right.adoc}.
- There, you will test out the "Kenya algorithm" on several different expressions to see if dividing and then multiplying produces the correct result every time.}

@QandA{
@Q{What do you Notice? What do you Wonder?}
@Q{Why are we able to change the groupings for an expression like @math{100 \times 20 \div 5} ... but _not_ for an expression like @math{100 \div 20 \div 5}?}
@Q{Why does the "Kenya algorithm" work? (Hint: Think about the @vocab{Multiplicative Inverse Property}!)}
@A{We can rewrite any division expression as multiplication by the reciprocal. Once we transform a division expression into a multiplication expression, we can apply the Commutative and Associative Properties freely!}
}

@teacher{Encourage students to think deeply about why this algorithm works – and if you’d like, invite them to consider and discuss why students all across the country are typically taught just one algorithm when, typically, there are an abundance to choose from!}

@slidebreak

@QandA{
Let's put our new knowledge to use! Scan each expression to determine the simplest solving strategy, then compute mentally.

@Q{ @math{114 \times 17 \div 17}}
@A{Solution: @math{114}}

@Q{@math{15 \times 3 \div 15}}
@A{Solution: @math{3}}

@Q{@math{2 \times 16 \times \frac{1}{27} \times 27}}
@A{Solution: @math{105}}
}


=== Synthesize

- How did it feel to scan the problem, choose your strategy, and then solve mentally?
- Did you like this new approach - or do you prefer solving from left to right?
- Knowledge of inverse operations creates _more_ opportunities to apply the @vocab{Commutative Property} and the @vocab{Associative Property}? Explain why this is the case.
- Do you think the Order of Operations is universal? Why or why not?
- Can you think of any other examples - they can be math-related or not! - of when you thought there was just one way to do something... and then learned that you were wrong?


== Programming Exploration: The Multiplicative Inverse

=== Overview

Students apply their knowledge of examples in @proglang to think about multiplication and division as inverse operations.

=== Launch

@lesson-instruction{
- Complete question 1 on @printable-exercise{examples-multiplicative.adoc}. We'll test these examples in @proglang soon!
- Which examples did you predict would fail, and why?
}

@teacher{Lead a discussion where students share their thinking and strategies for predicting if the examples will pass or fail.}

@slidebreak

@lesson-instruction{
- Let's see if your predictions are right! Open the @starter-file{multiplicative-inverse} and click "Run".
- With your partner, answer questions 2 and 3 on @printable-exercise{examples-multiplicative.adoc}.
}

@teacher{Debrief with students to ensure that they are looking at the messages that appear in @proglang. This activity not only provides practice thinking about the multiplicative inverse; it also gives students exposure to tests - bits of code used to verify that code is working as we would expect. Examples and tests are widely used in programming! We explore examples in greater depth in @lesson-link{functions-examples-definitions}.}

=== Investigate

Let's revisit our conversation about solving left-to-right... or right-to-left.

@lesson-instruction{
- Complete question 4 on @printable-exercise{examples-multiplicative.adoc}.
- Once you've made your predictions, open the @starter-file{multiplicative-inverse-2} and click "Run".
- Finish the worksheet, considering why _some_ examples passed and others did not - even though all examples had a similar structure.}

@teacher{Students should observe that when multiplication precedes division, they can solve in any order. When division precedes multiplication, however, they must divide *first*. }

=== Synthesize

- What did this programming exploration teach you about @proglang and examples?
- What did this programming exploration teach you about the multiplicative inverse?
