= Using Displays to Compare Foods Eaten (Part 2)

DATA ANALYSIS:
Decide whether each statement in the following table is “True” or “False.” Answer “Can’t Tell” if the pie charts don’t give us enough information. 

[cols="4,1,1,1"]
|===
|The New England Native Americans ate more grain than any other kind of food.
|True         |False         |Can’t Tell

|Half of what the Native Americans ate was turkey.
|True         |False         |Can’t Tell

|Modern food is healthier than what Native Americans ate.
|True         |False         |Can’t Tell

|In America today, we eat roughly the same amounts of grain and protein.
|True         |False         |Can’t Tell

|Native Americans ate hardly any dairy products or added fats and sugars.
|True         |False         |Can’t Tell
|===

GENERATING THEORIES: 
Pick one difference from the pie charts of the Native Americans’ and the modern U.S. diets. Can you think of any reasons for that difference?

@n One interesting difference... @fitb{}{}

@fitb{}{}

@n What might have caused it?

@fitb{}{}

@fitb{}{}


TURN AND TALK: Share with a partner the difference you picked and what might have caused it. Discuss whether there are other possible causes for the differences you each picked. 

@n Record your the difference your partner picked and any new reasons that you come up with together.

@fitb{}{}

@fitb{}{}

@fitb{}{}
