= Creating Functions 1

@lesson-description{Students learn why and how to create their own functions.}


[.left-header,cols="20a,80a", stripes=none]
|===
|Lesson Goals
|Students will be able to:

* Describe the usefulness of functions
* Create their own functions and examples given the parameters


|Student-Facing Lesson Goals
|
* I can explain why a function is useful to someone else.
* I can plan and create my own function with examples.


|Key Points for the Facilitator
|
* This lesson represents a big shift in thinking.  After some practice, students will not be limited to pre-existing functions.
* Take plenty of time for the Design Recipe as students will return to it frequently. 


|Prerequisites
|

* Students should be familiar with Circles of Evaluation.

|Materials
|

* @link{https://docs.google.com/presentation/d/1gPY40bnT1J8Or147mcUd6oPh_W_Ugf-gJs5Va3FN4vk/view, Google Slides} for this lesson.
* Fast Functions worksheet (@worksheet-link{workbook-pages/FastFunctions1.pdf, PDF}, @link{https://docs.google.com/document/d/1zxq7TYX76y6DFwdF2DCuN1nnLAmbD33Sua1QhhmOYH8/edit?usp=sharing, Google Doc})
* Circles of Evaluation Mapping worksheet (@worksheet-link{workbook-pages/MappingExamplesWithCoE1.pdf, PDF},https://docs.google.com/document/d/1EDLbNC9C62Z-kf9jGZzbaRRRj8Ni_Gbz2f14kp30COU/edit?usp=sharing, Google Doc})

Bootstrap Formative Assessments

* @link{https://teacher.desmos.com/activitybuilder/custom/5a15e27ee904510a5a9a0faa, Unit 3 Bootstrap Algebra Review}

Connecting Activities

* @link{https://teacher.desmos.com/expressions, Expression Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/modeling, Mathematical Modeling Bundle} (Desmos Activities)
* @link{https://quizizz.com/admin/quiz/576d1e5f91cb32ef5fc67529/variables-and-expressions, Variables and Expressions} (Quizizz)
* @link{https://teacher.desmos.com/functions, Functions Bundle} (Desmos Activities)
* @link{https://teacher.desmos.com/polygraph/custom/560ad28e9e65da5615091edb,
Functions & Relations} (Desmos Polygraph Activity)
* @link{https://quizizz.com/admin/quiz/582b7390e8e0c0c201647d9d/functions, Functions} (Quizizz)
* @link{https://quizizz.com/admin/quiz/582f0e34b805cc5c6608d326/function-notation, Function Notation} (Quizizz)
 
|===

[.left-header,cols="20a,80a", stripes=none]
|===
|Math Standards (CCSS)
|
* @link{http://www.corestandards.org/Math/Practice/MP2, CCSS.MATH.PRACTICE.MP2},
Reason abstractly and quantitatively.
* 7.EE.B @{7.EE.B}
* 7.EE.B.3 @{7.EE.B.3}
* 7.EE.B.4 @{7.EE.B.4}
* HSA.SSE.A.1 @{HSA.SSE.A.1}
* HSA.SSE.A.2 @{HSA.SSE.A.2}
* HSF.BF.A @{HSF.BF.A}
* HSF.IF.A.1 @{HSF.IF.A.1}

|CS Standards (CSTA)
|
* CS Standards here.
|===


== Get Ready:

Students should have their workbook, pencil, and be logged into WeScheme on their computer.

== Launch: (5 min)
Confess to your students, "I LOVE GREEN Triangles." Challenge them use the Definitions window to make as many DIFFERENT solid green triangles appear in 2 minutes.

Walk around the room and compliment the students on making you happy with all of the green triangles.  After the 2 minutes, ask for some examples of green triangles that they wrote(Be specific and attend to precision with the syntax).

[.text-center]
I Love Green Triangles

@image{images/ILoveGreenTriangles.jpg, I Love Green Triangles, 400, align="center"}

@image{images/GreenTriangle.jpg, I Love Green Triangles, 400, align="center"}

[.notice-box]
.Notice and Wonder
****
Point students to the various lines of code you've written on the board and ask them.
What do you notice?  What do you wonder?
****

== Discuss: (5 min)

* Was their a pattern?
* What stayed the same?
* What changed?
* What strategy did you use to create many different triangles?
* Is their a shortcut that can save us some time?


=== Inquiry Based Instruction(10 min) 
Introduce the concept of `define` to define a function when there is a lot of repetition in the code you want to use but only 1 or a few things that are changing.

Word Problem: Write a function called `green-triangle` that takes in number and produces a solid, green triangle of that given size.

Have students follow on this Fast Function handout and walk them through defining `green-triangle` first and let them know this is the 2nd biggest concept in Bootstrap:Algebra (after the Circles of Evaluation) and is a precursor to what will be known as The Design Recipe.

Keypoints:

* Stress to students that writing the examples is like 'showing your work' in math class.
* After writing the two examples, ask students what they notice? What stays the same? What is changing?
* Have students circle what is changing and label it with a proper variable name? (Example: 'size')

`(EXAMPLE (green-triangle 100) (triangle 100, "solid", "green"))`
`(EXAMPLE (green-triangle 30) (triangle 30, "solid", "green"))`
`(define (green-triangle size) (triangle size, "solid", "green"))`


== Explore: (5 min)

Now that students have defined `green-triangle` have them save their program as 'Creating Functions' and test out their newly created function in the Interactions window.

== Discuss: (10 min)

* What is the domain for `green-triangle`?
* Why might someone think the domain for `green-triangle` is `Number String String`?

Introduce the concept of creating Circle of Evaluation mapping for EXAMPLEs

* Have students complete the @worksheet-link{workbook-pages/MappingExamplesWithCoE1.pdf, Circle of Evaluation mapping} worksheet.

== Practice: (10 min)

Word Problem: Write a function called `gold-star` that takes in number and produces a solid, gold star of that given size.

* Write 2 examples and the definition of `gold-star` on the 'Fast Functions' handout.
* Complete the @worksheet-link{workbook-pages/FastFunctions1.pdf, Fast Functions} worksheet for the `gold-star` example.

== Create/Apply: (15 min)

Create/Apply task

Word Problem: Design a Word Problem(similar to the 2 above) that creates a function that takes in 1 variable and returns a shape(choose any of the shape functions available).

* Write 2 examples and the definition of your function
* Complete the Circles of Evaluation mapping for the examples of your function.



