= Meet Soekia!

Respond to the prompts below by interacting with @link{https://bootstrapworld.org/SoekiaGPT/}

== Documents

The green _Documents_ panel is where the training corpus lives.

@n How many documents are there in this particular corpus? @fitb{}{@ifsoln{12}}

@n Give the title of one of the documents: @fitb{}{@ifsoln{THE EMPEROR'S NEW CLOTHES}}

@n Click one of the small pencil icons. What do you see?  @fitb{}{@ifsoln{We can see the entire fairy tale.}}

@fitb{}{@ifsoln{If you scroll to the bottom, there is a word count for each fairy tale.}}

_(Click outside of the document to get back to the main screen.)_

@n What else do you Notice about the _Documents_ panel? What do you Wonder? 

@blanklines{4}{
@ifsoln{*Possible Noticings:* The colors of the documents correspond with the ones I saw in the _Text Generation_ panel. Each document has maximum of 20,000 characters. I can delete documents by clicking the trash can icon. There is sometimes a green bar on the documents. *Possible Wonderings:* Can I change the training corpus? Why have I never heard of some of the fairy tales?
}
}

== N-Grams

The orange _N-grams_ panel is where Soekia lists out possible n-grams and their frequency of occurrence within the training corpus. The default setting ("3rd") produces a list of every trigram that appears in the training corpus. 

@n The most common trigram appears at the top of the list. Click on it. What do you learn? @fitb{}{@ifsoln{I can see how many times the trigram appears,}}

@fitb{}{@ifsoln{and in which documents.}}

@n Click the red "Create N-grams" button on the right side of the N-Grams panel. What happens? Hint: Look at what happens in the _Documents_ panel after clicking the button. 

@blanklines{2}{
@ifsoln{The processing of each document is animated by a red circle appearing on it, one after another.
}
}

@n Take a minute to explore the N-Grams Panel, by scrolling through the list of N-Grams and clicking on some other examples. What do you Notice? What do you Wonder? 

@blanklines{3}{
@ifsoln{
*Possible Noticings:* Punctuation counts as a word! The green bar under each trigram indicates how often it appears in the corpus. The most common trigram appears almost as twice as frequently as the next most common trigram. Soekia interprets punctuation marks as words. *Possible Wonderings:* Why does Soekia interpret a line break (>) as a word? Why do individual 5-grams appear so much less frqeuently than individual unigrams?
}
}

== Suggested words

In the _Suggested words_ panel, Soekia offers possible completions for different inputs.

@n Click on one of the suggestions. What information appears? @fitb{}{@ifsoln{We learn how many times the suggestion is used in the training corpus, }}

@fitb{}{@ifsoln{and in which document it appears.}}

@n Click the "Customize Selections" button. Set a *low* temperature then click the right-facing arrow to tell a fairy tale. Once a few sentences have appeared, read your story and rate it: @hspace{2em} _It makes no sense._ @hspace{2em} _It sort of makes sense?_ @hspace{2em} _Wow! It makes sense!_

@n Click the trash can icon to delete the story. Now, set the temperature to *high*, and click the right-facing arrow to tell another fairy tale. After a few sentences, read it and rate it:  @hspace{2em} _It makes no sense._ @hspace{2em} _It sort of makes sense?_ @hspace{2em} _Wow! It makes sense!_

@n What do you Notice about the _Suggested words_ panel? What do you Wonder about the _Suggested words_ panel? @

@blanklines{4}{
@ifsoln{Possible Noticings: The _Suggested words_ panel updates automatically as Soekia generates text. Soekia often suggests a 5-gram and the shorter n-grams that are contained within that 5-gram (e.g., "the wind in the trees", "wind in the trees", "in the trees" and "trees"). Possible Wonderings: What are the different ways that I can customize the selection? How does changing the temperature affect the output?
}
}