= Describe and Define Your Own Functions!
++++
<style>
/*********************************
 * Additional CSS fixes for https://github.com/bootstrapworld/curriculum/issues/920
 * May need to be moved to shared.css, and tested
 */
.studentAnswerLong { min-width: 67% !important; }
.studentAnswerShort{ min-width: 4em; }
.studentAnswerMedium{ min-width: 7em !important; }
.autonum { padding-top: 1ex !important; }
</style>
++++
@n *Let's define a function* @fitb{10em}{} *to generate...*

@fitb{}{}

If I say @fitb{10em}{}, what would our actor need to say? @fitb{}{}

@vspace{1ex}

Let's write a few more examples:

@show{(code '((?FITB 5em) (?FITB 10em)))} &rarr; @show{(code '((?FITB 6em) (?FITB 24em)))}

@show{(code '((?FITB 5em) (?FITB 10em)))} &rarr; @show{(code '((?FITB 6em) (?FITB 24em)))}

@show{(code '((?FITB 5em) (?FITB 10em)))} &rarr; @show{(code '((?FITB 6em) (?FITB 24em)))}

What changes in these examples? Name your variable(s):  @fitb{}{}

@vspace{1ex}

Let's define our function using the variable.

@show{(code '(define ((?ANS name) (?ANS variables)) (?ANS the-body-of-the-function)))}

@vspace{1ex}

@n *Let's define a function* @fitb{10em}{} *to generate...*

@fitb{}{}

If I say @fitb{10em}{}, what would our actor need to say? @fitb{}{}

@vspace{1ex}

Let's write a few more examples:

@show{(code '((?FITB 5em) (?FITB 10em)))} &rarr; @show{(code '((?FITB 6em) (?FITB 24em)))}

@show{(code '((?FITB 5em) (?FITB 10em)))} &rarr; @show{(code '((?FITB 6em) (?FITB 24em)))}

@show{(code '((?FITB 5em) (?FITB 10em)))} &rarr; @show{(code '((?FITB 6em) (?FITB 24em)))}

What changes in these examples? Name your variable(s):  @fitb{}{}

@vspace{1ex}

Let's define our function using the variable.

@show{(code '(define ((?ANS name) (?ANS variables)) (?ANS the-body-of-the-function)))}

@vspace{1ex}

@n *Let's define a function* @fitb{10em}{} *to generate...*

@fitb{}{}

If I say @fitb{10em}{}, what would our actor need to say? @fitb{}{}

Let's write a few more examples:

@show{(code '((?FITB 5em) (?FITB 10em)))} &rarr; @show{(code '((?FITB 6em) (?FITB 24em)))}

@show{(code '((?FITB 5em) (?FITB 10em)))} &rarr; @show{(code '((?FITB 6em) (?FITB 24em)))}

@show{(code '((?FITB 5em) (?FITB 10em)))} &rarr; @show{(code '((?FITB 6em) (?FITB 24em)))}

What changes in these examples? Name your variable(s):  @fitb{}{}

@vspace{1ex}

Let's define our function using the variable.

@show{(code '(define ((?ANS name) (?ANS variables)) (?ANS the-body-of-the-function)))}

@vspace{1ex}

@n Add your new function definitions to your @starter-file{gt} and test them out!
