= Defining Functions in a Nutshell

Functions can be viewed in _multiple representations_.

@vspace{1ex}

== Contract and Purpose

You already know one of them: @vocab{Contracts}, which specify the Name, Domain, and Range of a function. Contracts are a way of thinking of functions as a _mapping_ between one set of data and another. For example, a mapping from Numbers to Strings:

@vspace{1ex}

@show{(contract 'f '("Number") "String")}

@vspace{1ex}

== Examples

The goal of the @vocab{Examples} step is to _find the pattern_ that represents what the function does.

Examples are essentially input-output tables, showing what the functions does with a list of specific inputs:

[cols="1,1", stripes="none", options="header"]
|===
| How @math{f} is used 	| What @math{f} does
| f(1)					| @math{1 + 2}
| f(2)					| @math{2 + 2}
| f(3)					| @math{3 + 2}
| f(4)					| @math{4 + 2}

|===

In our programming language, we write these columns as code:

@ifproglang{wescheme}{
```
(EXAMPLE (f 1) (+ 1 2))
(EXAMPLE (f 2) (+ 2 2))
(EXAMPLE (f 3) (+ 3 2))
(EXAMPLE (f 4) (+ 4 2))
```
}
@ifproglang{pyret}{
```
examples:
  f(1) is 1 + 2
  f(2) is 2 + 2
  f(3) is 3 + 2
  f(4) is 4 + 2
end
```
}

== Definition
The final step in the Design Recipe is to _generalize the pattern_ we see in our examples by writing a formal *function definition*. To do this we replace the inputs with @vocab{variables} that can work with any input.

In the example below, the definition for the examples above is written in both math and code:

@vspace{1ex}

@indented{@math{f(x) = x + 2} @hspace{3em} @show{ (code '(define (f x) (+ x 2)) )} }

@vspace{1ex}

== Look for connections between these three representations!

- The function name is always the same, whether looking at the Contract, Examples, or Definition.
- The number of inputs in the Examples is always the same as the number of types in the Domain, which is always the same as the number of variables in the Definition.
- The "what the function does" pattern in the Examples is almost the same in the Definition, but with specific inputs replaced by variables.
