= Sort Transformer
++++
<style>
body.workbookpage td .autonum::after { content: ')' !important; }
/* Cram everything to the top instead of distributing space equally */
#content { display: block !important; }
</style>
++++

Make sure you’re logged into the @starter-file{animals} in CODAP. Select the Plugins icon, then choose Transformers.

@vspace{1ex}

== Create, Apply and Save a Sort Transformer (Step by Step)


[cols="5, 10", frame="none", grid="none", stripes="none"]
|===

|
@image{../images/sort-ui-annotated.png, 350}

|

@vspace{1ex}

@n We're going to create a Transformer that will sort the animals alphabetically by name. Select Sort from the drop-down menu.

@vspace{1ex}

@n Give your Transformer a descriptive name. Type it in.

@vspace{1ex}

@n Which dataset do you want CODAP to apply this Transformer to? Select it from the drop-down menu.

@vspace{1ex}

@n We're going to sort "By Attribute," which should already be selected from the "Sort Method" drop-down menu.

@vspace{1ex}

@n Which attribute should we sort by? @fitb{}{@ifsoln{name}}

@n Which direction will you select? Why? @fitb{}{@ifsoln{"Ascending" sorts from A to Z, so I will select that.}}

@n Apply the Transformer. What happens? @fitb{}{@ifsoln{A copy of the original dataset is created.}}

|===

@n You may have noticed that this Transformer does not require a contract or purpose statement! Why do you think that is?

@fitb{}{}

@fitb{}{}

@vspace{2ex}



