= Analyzing Survey Results When Data is Dirty
++++
<style>
body:not(.LessonPlan) p { min-height: 2rem; }
</style>
++++

These questions are designed to accompany the @starter-file{fav-desserts}.

@vspace{1ex}

@n Paolo made a `pie-chart` of the `dessert` column and was suprised to discover that *Fruit* was the most popular dessert among 8th graders! Make the `pie-chart`. Why is this pie-chart misleading? How is the data "dirty"?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

@n What ideas do you have for how the survey designer could have made sure that the data in the `dessert` column would have been cleaner?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

@n Shani made a `bar-chart` of the `gender-id` column. In her analysis she stated that the most common gender identity among eighth graders in her class is male. Make the `pie-chart`. Do you agree? Why or Why Not?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

@n Make a chart showing the ages of the 8th graders surveyed. What "dirty" data problems do you spot and how are they misleading?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@vspace{1ex}

@n What ideas do you have for how the survey designer could have made sure that the data in the `age` column would have been cleaner?

@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}
