= Surface Area of a Prism - More than One Way

Students in Mr. Grattan's class were asked to write code that would calculate the surface area of this rectangular prism. +
Help them convert their strategies into algebraic expressions and code, and double check that each strategy works.

@centered-image{../images/rect-prism-abc.png, 400}

@n Della says, "Just find the area of the top, bottom, left, right, front and back and add them all together!" *Will it work?* @fitb{}{@ifsoln{yes}}

- Algebraic Expression: @fitb{}{@math{AB + AB + BC + BC + AC + AC = 2AB + 2BC + 2AC}}
- Code: @fitb{}{@showsoln{(code '(+ (+ (+ (+ (+ (* A B) (* A B)) (* B C) ) (* B C) ) (* A C) ) (* A C) ))}}


@n Orion says, "Just find the area of the front, top and right faces, add them together, and double the sum." *Will it work?* @fitb{}{@ifsoln{yes}}

- Algebraic Expression: @fitb{}{@ifsoln{@math{2(AB + BC + AC)}}}
- Code: @fitb{}{@showsoln{(code '(* 2 (+( + (* A B) (* B C)) (* A C))))}}

@n Jules says, "Double the area of the front, double the area of the top, double the area of the side. Then add them up." *Will it work?* @fitb{}{@ifsoln{yes}}

- Algebraic Expression: @fitb{}{@ifsoln{@math{2AB + 2BC + 2AC}}}
- Code: @fitb{}{@showsoln{(code '(+ ( + (* (* A B) 2) (* (* B C)2)) (* (* A C)2)))}}

@n Tate says, "Just multiply the length times the width times the height and double their product." *Will it work?* @fitb{}{@ifsoln{no}}

- Algebraic Expression: @fitb{}{@ifsoln{@math{2ABC}}}
- Code: @fitb{}{@showsoln{(code '(* 2(* (* A B) C)))}}

@n Can you think of one other way to find the surface area of the prism?

- Description: @fitb{}{@ifsoln{Answers will vary - here's one possibility}}
@fitb{}{@ifsoln{Find the perimeter of the base and multiply it by the height. Then add the top and bottom.}}
- Algebraic Expression: @fitb{}{@ifsoln{@math{2(A + B) * C + 2AB}}}
- Code: @fitb{}{@showsoln{(code '(+ (* (* (+ A B) 2) C) (* 2(* A B))))}}

@n Whose strategy do you like best? @fitb{}{@ifsoln{Answers will vary}} +
@hspace{3em} Why? @fitb{}{} +
@fitb{}{} +
@fitb{}{}

