= What Kind of Model? (Descriptions)

++++
<style>
/* Shrink Images */
#content img {width: 75%; height: 75%;}

/* Make autonums inside tables look consistent with those outside */
body.workbookpage td .autonum:after { content: ')'; }

table { font-weight: bold; }
table table {0.25in 0; font-weight: normal; }
</style>
++++

Decide whether each situation describes a quadratic, exponential, or logarithmic function. *HINT:* draw a table and plug in some points!

@vspace{1ex}

[.FillVerticalSpace, cols="1a", frame="none", stripes="none", grid="none"]
|===
|
@n Earthquakes release enormous amounts of energy, which we can compare to the energy released by blowing up pounds of dynamite. For example, @math{\text{richter}(12,000) = 4.0}, meaning that the force of blowing up 12,000 pounds of dynamite produces a 4.0 on the Richter scale!

@math{\text{richter}(400,000) = 5.0}, @math{\text{richter}(12,540,000) = 6.0}, and @math{\text{richter}(398,000,000) = 7.0}.

.^|
[cols="^1a,^1a,^1a",stripes="none",frame="none",grid="none"]
!===
! Quadratic
! Exponential
! @ifsoln-choice{Logarithmic}
!===

|
@n A car accelerates at a constant rate of 5mph/s. After 1 second, @math{\text{distance}(1) = 2.5\text{miles}}.

@math{\text{distance}(2) = 10}, @math{\text{distance}(3) = 22.5}, and @math{\text{distance}(4) = 40}

.^|
[cols="^1a,^1a,^1a",stripes="none",frame="none",grid="none"]
!===
! @ifsoln-choice{Quadratic}
! Exponential
! Logarithmic
!===

|
@n Moore's law says that the number of transistors in a microprocessor will double roughly every 1.5 years. Starting with 16 transistors, how many years will it take to reach 4,294,967,296 transistors?

.^|
[cols="^1a,^1a,^1a",stripes="none",frame="none",grid="none"]
!===
! Quadratic
! Exponential
! @ifsoln-choice{Logarithmic}
!===

|
@n The population of a colony of bacteria can double every 20 minutes, as long as there is enough space and food. Starting with 1 bacteria, @math{f(20) = 2}, @math{f(40) = 4}, @math{f(60) = 8}, @math{f(80) = 16}...

.^|
[cols="^1a,^1a,^1a",stripes="none",frame="none",grid="none"]
!===
! Quadratic
! @ifsoln-choice{Exponential}
! Logarithmic
!===

|
@n Sequan puts $100 in a savings account, earning 4% interest. After a year, @math{\mbox{savings(1) = $104}}.

@math{\mbox{savings(2) = $108.16}}, @math{\mbox{savings(2) = $112.49}}...


.^|
[cols="^1a,^1a,^1a",stripes="none",frame="none",grid="none"]
!===
! Quadratic
! @ifsoln-choice{Exponential}
! Logarithmic
!===


|
@n If the _width and length_ of a rectangle doubles, how much does the _area_ change?

.^|
[cols="^1a,^1a,^1a",stripes="none",frame="none",grid="none"]
!===
! @ifsoln-choice{Quadratic}
! Exponential
! Logarithmic
!===
|===


