= Graphing Logarithmic Models:  __f(x) = a log~b~ x + k__
////
* Import Desmos Styles
*
* This includes some inline CSS which loads the Desmos font,
* which includes special glyphs used for icons on Desmos.com
*
* It also defines the classname '.desmosbutton', which is used
* to style all demos glphys
*
* Finally, it defines AsciiDoc variables for glyphs we use:
* {points}
* {caret}
* {magnifying}
* {wrench}
*
* Here's an example of using these:
* This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}
++++
<style>
/* This page is TIGHT. Shrink the line-height to make it fit. :-( */
body:not(.LessonPlan, .narrativepage) p { line-height: 1; }

/* Make autonums inside tables look consistent with those outside */
.autonum { font-weight: bold; padding-top: 2px !important; }
.autonum:after { content: ')' !important; }

/* Cut the padding under each section */
.sect1 { padding: 0 !important; }

/*
  "Graph" tables provide a pure-CSS solution for all coordinate planes.

  They rely on a set up CSS variables, with reasonable defaults:
    --width and --height determine the size of plane. Defaults to 3in x 3x.
    --min-gap determines the minimum space between graphs. Defaults to 20px.

    --top_pct and --left_pct determine the origin's position (btw 0 and 1). Defaults to (0.5, 0.5).
    --minors determines how many "minor axes" (incl the one behind major). Defaults to 7.

    --x_label defaults to 'x'
    --y_label defaults to 'y'
*/
.graph {
  --width:    2.0in;
  --height:   1.4in;
  --left_pct: 0.10;
  --top_pct:  0.85;
  --minors:   8.0;
}
</style>
++++

@link-instructions{
Use this page with *Slide 4: Exploring Logarithmic Functions* of *Fitting Wealth-v-Health and Exploring Logarithmic Models (Desmos)*.

- The *blue curve* is the graph of @math{h(x) = 1 \log_{2} x + 0}. Its constants will remain set at @math{a=1}, @math{b=2}, and @math{k=0}.
- You can modify the *red curve* @math{g(x)} (which is hiding behind @math{h(x)}!) by changing its coefficients: @math{a}, @math{b}, and @math{k}.
}

== Base @math{b}
@link-instructions{Keep *k* at @math{0} and *a* at @math{1}. Change the value of *b* as indicated on each grid below.}

@n Sketch each graph and *label the coordinates where @math{x = 1}, @math{y = 1}, @math{y = 2} and @math{y = 3}*.


[.FillVerticalSpace.graph, cols="1,1,1", frame="none"]
|===
| @math{b = 3} | @math{b = 5}  | @math{b = 10}
|===

@n How does the value of @math{b} impact the shape of a logarithmic function? @fitb{}{@ifsoln{@math{b} determines how sharply the curve grows}}

@n What connections can you draw between the value of @math{b} and exponents? @fitb{}{@ifsoln{The output y is whatever}} +
@fitb{}{@ifsoln{exponent the base must be raised to in order to equal x}}

== Vertical Shift @math{k}
@link-instructions{Set *a* to @math{1} and *b* to @math{2}. Change the value of *k* as indicated on each grid below.}

@n Sketch each graph and *label the coordinate where @math{x = 1}*.

[.FillVerticalSpace.graph, cols="1,1,1", frame="none"]
|===
| @math{k = -10} | @math{k = 0}  | @math{k = 10}
|===

@n How does the value of @math{k} impact the shape of a logarithmic function? @fitb{}{@ifsoln{@math{k} shifts the curve up (positive k) or down (negative k),}} +

@n Why does @math{y = k} when @math{x = 1}? @fitb{}{@ifsoln{Anything to the power of 0 is 1, so whatever the base is it must be raised to zero, and zero + k = k}}

== Logarithmic Coefficient @math{a}
@link-instructions{Set *k* to @math{0} and *b* to @math{10}, then zoom out out so you can see as far as @math{x = 1,000}.}

Change @math{h(x)} to @math{h(x) = 1 \log_{10} (x) + 0} so that the blue curve lands on top of the red curve.

@n In each graph, *label the coordinates where @math{x = 10} and @math{x = 100} and @math{x = 1000}.*

[.FillVerticalSpace.graph, cols="1,1,1", frame="none"]
|===
| @math{a = -2} | @math{a = 0}  | @math{a = 2}
|===

@n What is the value of @math{x} when @math{1\log_{2}(x) = 4}? @fitb{5em}{@ifsoln{16}} @hspace{1em} What about when @math{2 \log_{4}(x) = 4}? @fitb{5em}{@ifsoln{16}} @hspace{1em} When @math{3 \log_{8}(x) = 4}? @fitb{}{@ifsoln{16}}

@star How are @math{a} and @math{b} related? @fitb{}{@ifsoln{A log with base @math{b^a} is equal to @math{a \times log_b}}}
