= Graphing Logarithmic Models: {nbsp}{nbsp} __f(x) = a log~b~ x + k__
////
* Import Desmos Styles
*
* This includes some inline CSS which loads the Desmos font,
* which includes special glyphs used for icons on Desmos.com
*
* It also defines the classname '.desmosbutton', which is used
* to style all demos glyphs
*
* Finally, it defines AsciiDoc variables for glyphs we use:
* {points}
* {caret}
* {magnifying}
* {wrench}
*
* Here's an example of using these:
* This is a wrench icon in desmos: [.desmosbutton]#{wrench}#
////

@include{fragments/desmos.adoc}
++++
<style>
/* Make autonums inside tables look consistent with those outside */
.autonum { font-weight: bold; padding-top: 2px !important; }
.autonum:after { content: ')' !important; }

/* Cut the padding under each section */
.sect1 { padding: 0 !important; }

/*
  "Graph" tables provide a pure-CSS solution for all coordinate planes.

  They rely on a set up CSS variables, with reasonable defaults:
    --width and --height determine the size of plane. Defaults to 3in x 3x.
    --min-gap determines the minimum space between graphs. Defaults to 20px.

    --top_pct and --left_pct determine the origin's position (btw 0 and 1). Defaults to (0.5, 0.5).
    --minors determines how many "minor axes" (incl the one behind major). Defaults to 7.

    --x_label defaults to 'x'
    --y_label defaults to 'y'
*/
.graph {
  --width:    2.0in;
  --height:   1.4in;
  --left_pct: 0.10;
  --top_pct:  0.85;
  --minors:   8.0;
}

p.tableblock:has(.solution) {
  left: 0px !important;
  top:  0px !important;
  background: transparent !important;
}
</style>
++++
@link-instructions{
For this page, you'll need to have *Fitting Wealth-v-Health and Exploring Logarithmic Models (Desmos)* open to *Slide 4: Exploring Logarithmic Functions*.
}

The curve you'll see is the graph of {nbsp}@math{r(x)}, an logarithmic function. Another, *identical* curve {nbsp}@math{s(x)}{nbsp} is hiding behind it. +
@n Use the starting values of @math{a}, @math{b}, and @math{k} in Desmos to complete the following equation: {nbsp} @math{r(x) = s(x) = } 
@fitbruby{2em}{@ifsoln{1}}{@math{a}}
(@fitbruby{2em}{@ifsoln{2}}{@math{b}}) @math{^x +}
@fitbruby{2em}{@ifsoln{0}}{@math{k}} 

== Base {nbsp}@math{b}
@link-instructions{Keep {nbsp} *k*{nbsp} at {nbsp}@math{0}{nbsp} and {nbsp} *a*{nbsp} at {nbsp}@math{1}. Change the value of {nbsp} *b*{nbsp} as indicated on each grid below.}

@n Sketch each graph and *label the coordinates where {nbsp}@math{x = 1}, {nbsp}@math{y = 1}, {nbsp}@math{y = 2} and {nbsp}@math{y = 3}*.


[.FillVerticalSpace.graph, cols="1,1,1", frame="none", options="noheader"]
|===
| @math{b = 3}

  @ifsoln{@image{../images/1log_3(x)+0.png}}
| @math{b = 5}

  @ifsoln{@image{../images/1log_5(x)+0.png}}
| @math{b = 10}

  @ifsoln{@image{../images/1log_10(x)+0.png}}
|===

@n How does the value of {nbsp}@math{b}{nbsp} impact the shape of a logarithmic function? @fitb{}{@ifsoln{@math{b} determines how sharply the curve grows}}

@n What connections can you draw between the value of {nbsp}@math{b}{nbsp} and exponents? @fitb{}{@ifsoln{The output y is whatever}} +
@fitb{}{@ifsoln{exponent the base must be raised to in order to equal x}}

== Vertical Shift {nbsp}@math{k}
@link-instructions{Set {nbsp} *a*{nbsp} to {nbsp}@math{1}{nbsp} and {nbsp} *b*{nbsp} to {nbsp}@math{2}. Change the value of {nbsp} *k*{nbsp} as indicated on each grid below.}

@n Sketch each graph and *label the coordinate where {nbsp}@math{x = 1}*.

[.FillVerticalSpace.graph, cols="1,1,1", frame="none", options="noheader"]
|===
| @math{k = -5}

  @ifsoln{@image{../images/1log_2(x)-5.png}}
| @math{k = 0}

  @ifsoln{@image{../images/1log_2(x)+0.png}}

| @math{k = 5}

  @ifsoln{@image{../images/1log_2(x)+5.png}}
|===

@n How does the value of {nbsp}@math{k}{nbsp} impact the shape of a logarithmic function? @fitb{}{@ifsoln{@math{k} shifts the curve up (positive k) or down (negative k),}} +

@n Why does {nbsp}@math{y = k}{nbsp} when {nbsp}@math{x = 1}? @fitb{}{@ifsoln{Anything to the power of 0 is 1, so whatever the base is it must be raised to zero, and zero + k = k}}

== Logarithmic Coefficient {nbsp}@math{a}
@link-instructions{Set {nbsp} *k*{nbsp} to {nbsp}@math{0}{nbsp} and {nbsp} *b*{nbsp} to {nbsp}@math{10}{nbsp}, then zoom out out so you can see as far as {nbsp}@math{x = 1,000}.}

Change {nbsp}{nbsp}@math{h(x)}{nbsp}{nbsp} to {nbsp}{nbsp}@math{h(x) = 1 \log_{10} (x) + 0}{nbsp}{nbsp} so that the blue curve lands on top of the red curve.

@n In each graph, *label the coordinates where {nbsp}@math{x = 10} and {nbsp}@math{x = 100} and {nbsp}@math{x = 1000}.*

[.FillVerticalSpace.graph, cols="1,1,1", frame="none", options="noheader"]
|===
| @math{a = 2}

  @ifsoln{@image{../images/-2log_10(x)+0.png}}
| @math{a = 4}

  @ifsoln{@image{../images/0log_10(x)+0.png}}
| @math{a = 2}

  @ifsoln{@image{../images/2log_10(x)+0.png}}
|===

@n What is the value of {nbsp}@math{x}{nbsp} when {nbsp}@math{1\log_{2}(x) = 4}? @fitb{5em}{@ifsoln{16}} @hspace{1em} What about when {nbsp}@math{2 \log_{4}(x) = 4}? @fitb{5em}{@ifsoln{16}} @hspace{1em} When {nbsp}@math{3 \log_{8}(x) = 4}? @fitb{}{@ifsoln{16}}

@star How are {nbsp}@math{a}{nbsp} and {nbsp}@math{b}{nbsp} related? @fitb{}{@ifsoln{A log with base @math{b^a} is equal to @math{a \times log_b}}}
