= Swapping the Axes: Notice and Wonder

++++
<style>
/* Add a top-margin to tables */
table { margin-top: 1ex; }

table:last-child img { height: 1.8in; }
</style>
++++

The scatter plots below were made with the same data... we just _swapped_ the x- and y-axes.

- The first scatter plot shows an *exponential relationship*: the number of Covid Infections as a function of Days
- The second scatter plot shows a *logarithmic relationship*: Days as a function of Infections

[cols="^1a,^1a", options="header", stripes="none"]
|===
| Days → Infections
| Infections → Days

| @image{../images/MA-covid.png}
| @image{../images/MA-covid-flipped.png}

<| @n What question might you answer from this graph? +
@ifsoln{How many positive cases do we predict after @math{x} days?}
@ifnotsoln{@vspace{5ex}}
<| @n What question might you answer from this graph?
@ifsoln{How many days do we predict until we pass @math{y} cases?}
|===

@vspace{1ex}

[.FillVerticalSpace,cols="^1a,^1a", options="header"]
|===
| What do you Notice?
| What do you Wonder?
| @ifsoln{
- Answers will vary.
- The exponential relationship rises slowly at first, then quickly.
- The logarithmic relationship rises quickly at first, then slowly.
- They are reflections of each other across a diagonal line.
}
|
@ifsoln{
- Why would growth get faster or slower?
- Can you flip the axes for any dataset?
- Why is there that little break in the curve?
- What is the form of a logarithmic function?
}

|===

@n This third scatter plot is our current dataset. Which of the scatter plots above does it resemble?

[cols="^1a,^.^1a", frame="none"]
|===
| @image{../images/wealth-health.png}
| _Days → Infections_

@vspace{10ex}

@ifsoln-choice{_Infections → Days_}
|===
