[.landscape]
= Clustering Explained

++++
<style>
.solution { white-space: nowrap; }
.sectionbody { height: 1.75in; }
/*
	For nested tables on this page (all of which have 3 col),
	set column width to automatically fit the content
*/
table .FillVerticalSpace {
	grid-template-columns: repeat(3, auto) !important;
}
</style>
++++

== With Centroids 1, 100, and 500

Discuss this section as a class with your teacher.

[.FillVerticalSpace, cols="8a,^.^1,8a, 16", grid="none", frame="none"]
|===
|

[.FillVerticalSpace, cols=">.^1,.^3,<.^1"]
!===
! Centroid		! Observations			! Mean

! 1	 			! 1, 2, 3, 4, 5, 6, 7 	! 4
! 100			! 87, 111				! 99
! 500			! 512					! 512
!===

| @span{.arrow}{⟶}

|
[.FillVerticalSpace, cols=">.^1,.^3,<.^1"]
!===
! Centroid		! Observations			! Mean

! 4	 			! 1, 2, 3, 4, 5, 6, 7 	! 4
! 99			! 87, 111				! 99
! 512			! 512					! 512
!===

| We start with our initial guesses of centroids.

@vspace{1ex}

For each value, we find which centroid it’s closest to. That will be its temporary cluster.

@vspace{1ex}

Once we have assigned each value to a cluster, we recompute the cluster’s centroid based on the values that ended up in that cluster.
|===


== With Centroids 1, 10, and 100
Fill in the missing values to see the final centroids.

[.FillVerticalSpace, cols="8a,^.^1,8a,^.^1,8a,^.^1,8a", grid="none", frame="none"]
|===
|
[.FillVerticalSpace, cols=">.^1,.^2,<.^1"]
!===
! Centroid		! Observations		! Mean

! 1 			! 1, 2, 3, 4, 5 	! 3
! 10			! 6, 7				! 6.5
! 100			! 87, 111, 512		! 233.6
!===

| @span{.arrow}{⟶}
|
[.FillVerticalSpace, cols=">.^1,.^2,<.^1"]
!===
! Centroid		! Observations		! Mean

! 3		 		! 1, 2, 3, 4, 5 	! @ifsoln{2.5}
! 6.5			! 6, 7, 87, 111		! @ifsoln{43.2}
! 236.6			! 512				! 512
!===

| @span{.arrow}{⟶}

|
[.FillVerticalSpace, cols=">.^1,.^2,<.^1"]
!===
! Centroid		! Observations					! Mean

! @ifsoln{2.5}	! @ifsoln{1, 2, 3, 4, 5, 6, 7} 	! @ifsoln{4}
! @ifsoln{43.2}	! @ifsoln{87, 111}				! @ifsoln{99}
! 512			! @ifsoln{512}	 				! @ifsoln{512}
!===

| @span{.arrow}{⟶}

|
[.FillVerticalSpace, cols=">.^1,.^2,<.^1"]
!===
! Centroid		! Observations					! Mean

! @ifsoln{4} 	! @ifsoln{1, 2, 3, 4, 5, 6, 7} 	! @ifsoln{4}
! @ifsoln{99}	! @ifsoln{87, 111}				! @ifsoln{99}
! @ifsoln{512}	! @ifsoln{512}					! @ifsoln{512}
!===
|===


== With Centroids 1, 2, and 3
Fill in the missing values to see the final centroids.

[.FillVerticalSpace, cols="8a,^.^1,8a,^.^1,8a,^.^1,8a", grid="none", frame="none"]
|===

|
[.FillVerticalSpace, cols=">.^1,.^5,<.^1"]
!===
! Centroid		! Observations					! Mean

! 1 			! 1  							!
! 2				! 2	 							!
! 3				! @ifsoln{3, 4, 5, 6, 7, 87, 111, 512}	!
!===

| @span{.arrow}{⟶}

|
[.FillVerticalSpace, cols=">.^1,.^6,<.^1"]
!===
! Centroid			! Observations				! Mean

! @ifsoln{1}		! @ifsoln{1}  				! @ifsoln{1}
! @ifsoln{2}	 	! @ifsoln{2, 3, 4, 5, 6, 7}	! @ifsoln{4.5}
! @ifsoln{91.875}	! @ifsoln{87, 111, 512}		! @ifsoln{236.6}
!===

| @span{.arrow}{⟶}

|
[.FillVerticalSpace, cols=">.^1,.^6,<.^1"]
!===
! Centroid		! Observations						! Mean

! @ifsoln{1}	! @ifsoln{1, 2} 	 				! @ifsoln{1.5}
! @ifsoln{4.5}	! @ifsoln{3, 4, 5, 6, 7, 87, 111}	! @ifsoln{31.86}
! @ifsoln{236.6}! @ifsoln{512}	 					! @ifsoln{512}
!===

| @span{.arrow}{⟶}

|
[.FillVerticalSpace, cols=">.^1,.^6,<.^1"]
!===
! Centroid			! Observations					! Mean

! @ifsoln{1.5}	 	! @ifsoln{1, 2, 3, 4, 5, 6, 7} 	! @ifsoln{4}
! @ifsoln{31.86}	! @ifsoln{87, 111}				! @ifsoln{99}
! @ifsoln{512}		! @ifsoln{512}					! @ifsoln{512}
!===

|===

