= Interpreting Spread

// use double-space before the *bold* text to address a text-kerning bug in wkhtmltopdf 0.12.5 (with patched qt)
Consider the following dataset, representing the annual income of ten people (note: $65k means $65,000, etc.):

  $65k, $12k, $14k, $280k, $15k, $22k, $45k, $34k, $45k, $175k

1) In the space below, rewrite this dataset in  *sorted order*.

@vspace{2ex}

2) In the table below, compute the  *measures of center* for this dataset.

[cols="^1a,^1a,^1a",options='header']
|===
| Mean (Average) | Median | Mode(s)
|				 |		  | @vspace{3ex}
|===

3) In the table below, compute the  *five number summary* of this dataset.

[cols="^1a,^1a,^1a,^1a,^1a",options='header']
|===

| Minimum | Q1 | Q2 (Median) | Q3 | Maximum

|||||@vspace{3ex}
|===

4) On the number line below, draw a  *box plot* for this dataset.

@centered-image{numline.svg, "", 800}

5) The following statements are _correct_ ... but misleading. Write down the reason why.

[cols="2a,5a"]

|===
| Statement | Why it’s misleading

| “They’re rich! The average person makes more than $70k dollars!” |@vspace{10ex}

| “It’s a middle-income list: the most common salary is $45k/yr!” |@vspace{10ex}

| “This group is really diverse, with people making as little as 12k and as much as $280k!” |@vspace{10ex}
|===

