= Vicki Hanson

++++
<style>
@import url("../../../lib/pioneers.css");
</style>
++++

[.posterImage]
@image{../images/vicki-hanson.png}

[.credit]
Image cartoonized using vanceai.com

[.name]
Vicki Hanson

[.title]
Human-Computer Interaction, Accessiblitiy

[.text]
Hanson's research focuses on human-computer interaction (HCI), meaning she spends time observing the ways humans interact with computers. She is also interested in accessibility and thinks about how to design technology that is usable by people with disabilities. Hanson is responsible for helping develop a browser extension that allows people with visual, motor, and cognitive disabilities to modify Web content on the fly to meet their needs. She also helped develop the world's first fully accessibly 3D virtual world! In 2018, Hanson was named the first female CEO of the Association for Computing Machinery (ACM), the world's largest scientific and educational computing society. 

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. FREE, research-driven, integrated Computer Science & Data Science modules for Math, Science, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
