= Problem Decomposition

@lesson-description{Students take a closer look at how functions can work together by investigating the relationship between revenue, cost, and profit.}

[@lesson-intro-table]
|===
@prereqs-stds{alg-restating-the-problem}
| Lesson Goals
| Students will be able to:

* Explain the benefits and drawbacks of functions that depend on each other.
* Write a @vocab{function} that explicitly uses another function.

| Student-Facing Lesson Goals
|
* I can explain the benefits and drawbacks of functions that use other functions.
* I can write a function that uses another function.

| Materials
|
* Design Recipe: revenue (@workbook-link{pages/revenue.adoc, PDF})
* Design Recipe: cost (@workbook-link{pages/cost.adoc, PDF})
* Design Recipe: profit (@workbook-link{pages/profit.adoc, PDF})

Bootstrap Formative Assessments

* Bootstrap: Algebra - Coordinates, Circles of Evaluation, & Code (@link{https://quizizz.com/admin/quiz/5cdcb223862fd8001a135579, Quizizz})
* Bootstrap:Algebra - Data Types & Circles of Evaluation (@link{https://teacher.desmos.com/activitybuilder/custom/5cdcb288f41b366950eba1e1, Desmos Activity})
* Bootstrap:Algebra - Circles of Evaluation Review(Blank Template) (@link{https://teacher.desmos.com/activitybuilder/custom/5cdcb336f41b366950eba420, Desmos Activity})
* Bootstrap:Algebra - Contracts, Domain/Range, Data Types, & Functions (@link{https://quizizz.com/admin/quiz/5cdcb3907f8c98001a203c1b, Quizizz})
* Bootstrap:Algebra - Data Types, Circles of Evaluation, and Contracts (@link{https://teacher.desmos.com/activitybuilder/custom/5cdcb3f555e3fb606a1f1ba2, Desmos Activity })

| Preparation
|
* Make sure all materials have been gathered
* Decide how students will be grouped in pairs

| Supplemental Resources
|
- Function Composition Dynamic Illustrator I (@link{https://www.geogebra.org/m/nqymeFc4, Geogebra } )
- Composition of Functions (@link{https://www.geogebra.org/m/h3qdzW3W, Geogebra Quiz } )
- Composition of Functions 2 (@link{https://quizizz.com/admin/quiz/58a61a2cf0b089151011ef50/composition-of-functions, Quizizz } )

| Key Points for the Facilitator
|
* There are several ways to write the profit function - use this opportunity for discussion and to promote higher-order critical thinking.
* If students are struggling with understanding the basis of the problem, start by coming up with examples of cost and revenue.  If Sally sells one glass, what is her total revenue?  How much does it cost her to produce that one glass?
* Ensure students understand the difference between "revenue" and "profit", and that "cost" refers to the cost of making the lemonade, not the amount Sally is charging.

|===

== Warmup

Students should have their workbook, pencil, and be logged into
@ifproglang{wescheme}{ @link{https://www.wescheme.org, WeScheme     } }
@ifproglang{pyret}{    @link{https://code.pyret.org, code.pyret.org } }
and have their workbooks with a pen or pencil.

== Problem Decomposition @duration{45 minutes}

=== Overview
Students are introduced to word problems that can be broken down into _multiple_ problems, the solutions to which can be composed to solve other problems. They adapt the Design Recipe to handle this situation.

=== Launch
Display the following image:

@centered-image{images/LemonadeStand.png, Lemonade Stand Ideas, 400, align="center"}

[.notice-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Notice and Wonder}

What do you notice?  What do you wonder?
|===

This lemonade stand is selling lemonade for $1.75 a glass! But for every glass they sell, there's some cost for sugar, lemons and water. 

- Every glass sold brings in $1.75 in *revenue*
- Every glass sold costs $0.30 in *costs*, such as lemonds, sugar and water
- Every glass sold brings in some amount of *profit*: it costs a certain amount to make, but it brings in another amount in revenue

=== Investigate

Students form groups and brainstorm their ideas for functions.  Students can use any strategies they've learned so far.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===
|
@span{.title}{Strategies for English Language Learners}

MLR 7 - Compare and Connect
There are several correct ways to write the functions needed for Sally's Lemonade.  Have students compare methods and develop understanding and language related to mathematical representation and methods.  What are the advantages of the different solutions?  What are some drawbacks?
|===

- *What is the difference between _revenue_ and _profit_?*
_Revenue is the total amount of money that comes in, profit is the remaining money after cost has been subtracted._

- *How could Sally _increase_ her profits?*
_By decreasing her costs, raising her prices (which increases revenue), by selling more lemonade._

- *What is the _relationship_ between profit, cost, and revenue?*
_Profit = Revenue - Cost_

[.lesson-instruction]
Students work with their partners to develop their function models for
@workbook-link{pages/revenue.adoc, revenue}, @workbook-link{pages/cost.adoc, cost}, and @workbook-link{pages/profit.adoc, profit}, using the Design Recipe.

While students are working, walk the room and gauge student understanding.  There is more than one correct way to write the profit function.  Encourage discussion between students and push students to develop their thinking on the advantages and disadvantages of each correct solution.

=== Synthesis
- How many different ways could we have written `profit`?
- Which way is "best", and why?
- If lemons gets more expensive, which way requires the least amount of change?
- If sugar gets less expensive, which way requires the least amount of change?
- After considering the previous two questions, which way is "best"? Is that different from what you answered before? If so, why?

== Additional Exercises:

