= “Trust, but verify…”

A “helpful” Data Scientist gives you access to the following functions:

@show{(contract
  "old-dogs-nametags" '("Table") "Table"
  "consumes a table of animals, and produces a table containing only dogs 5 years or older, with an extra column showing their name in red"
)}

You can use the function, _but you can’t see the code for it!_ *How do you know if you
can trust their code?*

1) What qualities would a verification subset need to have?

@span{.blankline}{
  @ifsoln{At least one of each species, to make sure non-dogs are filtered out}
}

@span{.blankline}{
  @ifsoln{Animals - especially dogs - whose ages are both ≥ and < than 5}
}

@span{.blankline}{
  @ifsoln{At least two old dogs with different names}
}

@span{.blankline}{}

@span{.blankline}{}

@span{.blankline}{}

@vspace{2ex}

2) Create your verification subset! In the space below, list the name and index of
each animal in your subset.

[cols='1',options='header']
|===
|Name
|@vspace{4ex}
|@vspace{4ex}
|@vspace{4ex}
|@vspace{4ex}
|@vspace{4ex}
|@vspace{4ex}
|@vspace{4ex}
|@vspace{4ex}
|===

