[.landscape]
= Contracts

Contracts tell us how to use a function. For example: `num-min {two-colons} (a {two-colons} Number, b {two-colons} Number) -> Number` tells us that the name of the function is  `num-min`, it takes two inputs (both Numbers), and it evaluates to a  `Number`. From the Contract, we know  `num-min(4, 6)` will evaluate to a  `Number`. *Use the blank line under each Contract for notes or sample code for that function!*

[.contracts-table, cols="4,1,10,1,2", options="header", grid="rows"]
|===
|Name||Domain||Range

| `pie-chart-summarized`
| `{two-colons}`
| `(t {two-colons} Table, labels {two-colons} String, values {two-colons} String)`
| `->`
| `Image`
5+|`_pie-chart-summarized(animals-table, "age", "pounds")_`

| `put-image`
| `{two-colons}`
| `Image, Number, Number, Image`
| `->`
| `Image`
5+|`_put-image(star(30, "solid", "red"), 50, 150, rectangle(300, 200, "outline", "black"))_`

| `radial-star`
| `{two-colons}`
| @ifsoln{`Number, Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_radial-star(17, 50, 10, "solid", "orange")_`}

| `random-rows`
| `{two-colons}`
| `(t {two-colons} Table, num-rows {two-colons} Number)`
| `->`
| `Table`
5+|`_random-rows(animals-table, 5)_`

| `rectangle`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_rectangle(20, 80, "solid", "gold")_`}

| `regular-polygon`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_regular-polygon(40, 8, "solid", "red")_`}

| `rhombus`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_rhombus(20, 50, "solid", "turquoise")_`}

| `right-triangle`
| `{two-colons}`
| @ifsoln{`Number, Number, String, String`}
| `->`
| @ifsoln{`Image`}
5+| @ifsoln{`_right-triangle(20, 50, "outline", "black")_`}

| `rotate`
| `{two-colons}`
| `Number, Image`
| `->`
| `Image`
5+|`_rotate(35, rectangle(30, 80, "solid", "purple"))_`

|===
