[.landscape]
= Contracts

Contracts tell us how to use a function. For example: `num-min {two-colons} (a {two-colons} Number, b {two-colons} Number) -> Number` tells us that the name of the function is  `num-min`, it takes two inputs (both Numbers), and it evaluates to a  `Number`. From the contract, we know  `num-min(4, 6)` will evaluate to a  `Number`. *Use the blank line under each contract for notes or sample code for that function!*

[.contracts-table, cols="4,1,10,1,2", options="header", grid="rows"]
|===
|Name||Domain||Range

| `median`
| `{two-colons}`
| `Table, String`
| `->`
| `Number`
5+|`_median(animals-table, "age")_`

| `modes`
| `{two-colons}`
| `Table, String`
| `->`
| `List<Number>`
5+|`_modes(animals-table, "age")_`


| `modified-box-plot`
| `{two-colons}`
| `Table, String)`
| `->`
| `Image`
5+|`_modified-box-plot(animals-table, "age")_`

| `num-max`
| `{two-colons}`
| `Number, Number`
| `->`
| `Number`
5+|`_num-max(80, 20)_`

| `num-min`
| `{two-colons}`
| `Number, Number`
| `->`
| `Number`
5+|`_num-min(80, 20)_`

| `num-sqr`
| `{two-colons}`
| `Number`
| `->`
| `Number`
5+|`_num-sqr(9)_`

| `num-sqrt`
| `{two-colons}`
| `Number`
| `->`
| `Number`
5+|`_num-sqrt(25)_`

| `overlay`
| `{two-colons}`
| `Image, Image`
| `->`
| `Image`
5+|`_overlay(star(30, "solid", "gold"),circle(30, "solid", "blue"))_`

| `pie-chart`
| `{two-colons}`
| `Table, String`
| `->`
| `Image`
5+|`_pie-chart(animals-table, "species"_`)

|===
