= Testing and Comparing Decision Trees

++++
<style>
/* Format autonumbering inside the table correctly */
table .autonum::after { content: ')' !important; }
</style>
++++

Determine how each of these trees would categorize the items below. Explain your responses.

[cols="1a,1a", stripes="none", frame="none"]
|===
| @centered-image{../images/tree4.png, 335}
| @centered-image{../images/tree3.png, 300}

|
@n butter knife @fitb{}{@ifsoln{"knife"}}

@fitb{}{}

@n chopstick @fitb{}{@ifsoln{"spoon"}} +
@fitb{}{}

@n spork @fitb{}{@ifsoln{"fork"}} +
@fitb{}{}

|
@n butter knife @fitb{}{@ifsoln{"knife"}}

@fitb{}{}

@n chopstick @fitb{}{@ifsoln{"fork or spoon"}} +
@fitb{}{}

@n spork @fitb{}{@ifsoln{"fork or spoon"}} +
@fitb{}{}

|===


@n What do you Notice about the two decision trees above? +
@fitb{}{@ifsoln{The trees are different because the "not flat" branch of the tree on the right terminates with "mug or cup".}} +
@fitb{}{}

@n What do you Wonder about the two decision trees? +
@fitb{}{} +
@fitb{}{} +

@n Which decision tree (above) would make predictions more efficiently? Explain. +
_Hint: A program is *efficient* when it performs a task with minimal time, memory, energy or data._

@fitb{}{@ifsoln{The decision tree on the right. There are fewer decisions to make!}}

@fitb{}{}

@n Which decision tree (above) would make predictions more accurately? Explain. +

@fitb{}{}

@fitb{}{}
