= Building Linear Models

@description{Students use linear models to investigate the relationship between college enrollment and median income in demographic data about US states.}

@lesson-prereqs{linear1-exploring-states}

@keywords{linear, slope, intercept, slope-intercept}

@add-to-lang{}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...
@objectives

| Student-facing Lesson Goals
|

- Let's build linear models to help us make predictions.


| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|[.materials-links]
@opt-material-links


| Key Points For The Facilitator
|
- There is no need to have students save the @starter-file{alg2-states-intro} used in this lesson. When we're ready for students to start saving things in a future lesson, we'll refer them to a different starter file that pulls data from the same spreadsheet and has more details in the Definitions Area to save you time.

| Preparation
|
@preparation{
- Heads up: The first section of this lesson is optional review, so @opt-printable-exercise{def-2-points.adoc} is not included in the workbook.
}

|===

== Optional Review: Two Points and a Line
@objective{slope-from-points}

=== Overview

In the next section of this lesson, students are asked to write the Slope-Intercept form of the line, given two points in our states dataset. To prep them for success, this section is an opportunity for students to review what they already know about linear functions and the process of finding the equation of a line from a table and then practice writing linear functions, given two points on the line.

=== Launch

Before we learn to fit linear models to scatter plots, let's review. *What do you remember about linear functions?*

@teacher{
We'd expect students to be able to surface much of the following:

- Linear functions look like straight lines.
- Vertical lines are not functions, because their slope is undefined as a result of their horizontal change being zero.
- The steepness of a line can be described by its @vocab{slope} (or _constant_ @vocab{rate of change}).
- The @vocab{slope} can be calculated from any two points.
- Students may remember the @vocab{slope} as @math{\frac{change \; in \; y}{change \; in \; x}} or @math{{rise}\over{run}} or @math{\frac{y_2 - y_1}{x_2 - x_1}}.
- The point where the line crosses the y-axis is called the @vocab{y-intercept} or vertical shift.
- The x-coordinate of the @vocab{y-intercept} always starts with zero, e.g. @math{(0, y)}.
- Diagonal lines have both a @vocab{y-intercept} and an @vocab{x-intercept}.
- Horizontal lines have a constant rate of change of zero.
}

[cols=".^2a,^.^1a", grid="none", frame="none"]
|===
|Linear relationships grow by fixed amounts, meaning that the difference between two y-values will always be the same over identical horizontal intervals. In the table shown to the right, you can see arrows pointing out the "jumps" between y-values for x-intervals of 1. Each jump is the same size: +2.
|@image{images/difference-table-linear.png}
|===

@lesson-point{
If the rate of change is constant, the relationship is linear.
}

@QandA{
@Q{Try comparing intervals of 2, instead of intervals of 1.}
@Q{Is the difference between y-values from @math{x=1} to @math{x=3} the same as the difference between y-values from @math{x=2} to @math{x=4}?}
@A{Yes. When x increases by 2, y increases by 4.}
@Q{What is the y-value when @math{x=0?}}
@A{By following the pattern of the blue arrows backwards, we can subtract 2 and arrive at @math{y=3}}
@Q{What is the slope of this line?}
@A{2. It's another word for the rate of change. The arrows show that y increases by 2 as x increases by 1.}
@Q{What equation would describe the linear relationship we observe in this table?}
@A{Knowing the y-intercept and the "size of the growth", we can tell that the equation of this line is @math{f(x) = 2x + 3}.}
}

=== Investigate

Complete @opt-printable-exercise{def-2-points.adoc}.

=== Synthesize

@QandA{
@Q{Given two points from a line, what steps are involved in writing the point-slope form of the line?}
@A{Compute the slope.}
@A{Substitute the slope and the coordinates of the point into @math{y = mx + b} and compute the y-intercept.}
@A{Write the point-slope form of the line using the slope and y-intercept we computed.}
}


== The Alaska-Alabama Model
@objective{model-interpret-residuals}
@objective{model-predictions}

=== Overview

Building on prior knowledge of linear functions, students learn to find the line of best fit to model the relationship in a scatter plot that looks linear.

=== Launch

@lesson-instruction{
- Return to Pyret and the @starter-file{alg2-states-intro}.
- Make a scatter plot showing the relationship between `pct-college-or-higher` and `median-income`, using `state` for the labels.
@ifslide{
- What do you notice about the @vocab{Form} of this scatter plot? What pattern do you see?}
}

@slidebreak

@ifslide{@right{@image{images/college-v-income.png}}
This scatter plot appears to show a positive, linear relationship: +
_States with higher percentages of college graduates tend to have higher median household incomes._
}
@ifnotslide{@center{@image{images/college-v-income.png, 450}}}

@slidebreak

@QandA{
@Q{What do you notice about the @vocab{Form} of this scatter plot? What pattern do you see?}
@A{This scatter plot appears to show a positive, linear relationship: +
_States with higher percentages of college graduates tend to have higher median household incomes._}
}

@teacher{
@right{@image{images/pyret-window.png, 150}}As students make predictions in response to the questions below, let them discuss and explain their thinking.

- If possible, mark off a single point for each of the hypothetical percentages, then connect those points to show a straight line.
- Note that some of these new points would require changing the x-min, x-max, y-min and/or y-max of our scatter plot, which we can do by typing in the cells on the right side of the scatter plot and clicking "Redraw".
}

@QandA{
Suppose the United States were to add a new state. +
_Based on the data for the existing 50 states (plus DC!)..._

@Q{What median household income would you predict, if exactly 30% of the new state's citizens had attended college?}
@A{Answers will vary. But should be above 50,000 and below 60,000}

@Q{What would you predict if 20% had attended college?}
@A{Answers will vary. But should be around 40,000}

@Q{If 40% had attended college?}
@A{Answers will vary. But should be upwards of 65,000}
}

@lesson-point{
When we see patterns in data, we can use those patterns to _make predictions_.
}

=== Investigate

We can draw a line to model all the possible predictions at once and then we can write a function to describe it!

In this case, we're looking for a model of the relationship between college enrollment and income.

@big{@center{@math{\text{median-income}(\text{pct-college}) = m \times \text{pct-college} + b}}}

We want to know: Are there values of @math{m} and @math{b} that will fit the data well?

@slidebreak

@lesson-instruction{
- If we have two points, we know how to write the point-slope form of the line. Let's find the model that passes through our first two points: Alabama and Alaska!
- Complete the first section of @printable-exercise{model-college-v-income-1.adoc}.
}

@teacher{
@opt{If your students could use more support for finding the equation of the line between two points, direct them to the scaffolded version of @opt-printable-exercise{model-college-v-income-1-scaffolded.adoc} instead.}
}

@slidebreak

@teacher{
Confirm that students were able to successfully compute slope and y-intercept, define and test `al-ak(x)` in Pyret, and test how well `al-ak(x)` predicted several states' median income given the percentage of the population with at least a college degree.
}

@QandA{
@Q{Why wasn't the Alaska-Alabama model a good fit for the rest of the data?}
@A{Because Alaska is an outlier that falls pretty far above the line of best fit.}
}

@lesson-instruction{
- Can you identify two other states we could have built a better model from?
- Record your thinking on the last section of @printable-exercise{model-college-v-income-1.adoc}. You'll want to remember them for later!
}

=== Synthesize

@QandA{
@Q{Why do people build models for datasets?}
@A{So they can make predictions using the patterns they see.}

@Q{What advice do you have for someone looking to build a model for a dataset?}
@A{Pick 2 points that feel representative of the trend.}
}
