= Variables and Code (Associative Property)

++++
<style>
	/* Make autonums inside tables look consistent with those outside */
table .autonum::after { content: ')' !important;}
</style>
++++

@n Open @starter-file{variables-code2}. On the table below, record your Noticings and Wonderings about what you see there. Consider how this starter file is different from @starter-file{variables-code}. *Don't hit "Run" yet!*

[.FillVerticalSpace,cols="^1, ^1", stripes="none", options="header"]
|===
| Notice 	| Wonder
|			|
|===

@n Based on what you see in the Definitions Window (left side), predict what will happen when you hit "Run" by circling your choice below.

[cols="^.^1,^.^1,^.^1,^.^1", stripes="none"]
|===

@ifproglang{pyret}{
| Looks shipshape, all 4 tests passed, mate!
| 3 tests passed, 1 test failed
| 2 tests passed, 2 tests failed
| 1 test passed, 3 tests failed
}

@ifproglang{wescheme}{
| All examples pass
| 3 examples pass, 1 fails
| 2 examples pass, 2 fail
| 1 example passes, 3 fail
}

|===

@n Explain how you made your prediction (above). @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n Click "Run". Were you correct? @fitb{5em}{} Explain. @fitb{}{@ifsoln{After hitting "Run", we discover that 3 tests passed and 1 test (example 3) failed.}}

@fitb{}{@ifsoln{Test 3 fails because @math{(1 - 1) - 1}, which evaluates to -1, is not equivalent to @math{1 - (1 - 1)}, which evaluates to 0.}}

@fitb{}{}

@n Give four sets of values for `a`, `b` and `c` that will cause _both_ example 3 and example 4 to fail. Try them out!

@hspace{1em} `a` = @fitb{2em}{}
@hspace{1em} `b` = @fitb{2em}{}
@hspace{1em} `c` = @fitb{2em}{}
@hspace{6em}
			 `a` = @fitb{2em}{}
@hspace{1em} `b` = @fitb{2em}{}
@hspace{1em} `c` = @fitb{2em}{}
@hspace{2em}

@hspace{1em} `a` = @fitb{2em}{}
@hspace{1em} `b` = @fitb{2em}{}
@hspace{1em} `c` = @fitb{2em}{}
@hspace{6em}
			 `a` = @fitb{2em}{}
@hspace{1em} `b` = @fitb{2em}{}
@hspace{1em} `c` = @fitb{2em}{}
@hspace{2em}

@n Are there any sets of values for `a`, `b`, and `c` that will cause example 1 or example 2 to fail? If so, list them here: @fitb{}{@ifsoln{No.}}

@n Are any of the examples true *every time*, no matter what values we use for `a`, `b`, and `c`? If so, which ones? @fitb{}{@ifsoln{No.}}

@n Are any of the examples true *some of the time*, depending on what values we use for `a`, `b`, and `c`? If so, which ones? @fitb{}{@ifsoln{Yes, examples 3 and 4.}}

@n Deena wants to edit the starter file's code so that when she hits "Run", all four tests pass. She suggests changing all the values of the variables so that `a`, `b`, and `c` are each equal to zero. Do you agree with her idea? _Before deciding, feel free to test out the idea!_ Explain.

@fitb{}{@ifsoln{Deena's idea will not. When we test Deena's idea, examples 1, 2, and 3 pass, but example 4 fails }}

@fitb{}{@ifsoln{because we cannot divide by zero.}}

@fitb{}{}

@star Can you think of any values for `a`, `b`, and `c` that will result in all four tests passing? @fitb{}{} +
@fitb{}{} +
@fitb{}{}


