[.landscape]
= Which One Isn't Equivalent? Variables

++++
<style>
.chosen::after { content: '❌' !important; }
div.circleevalsexp { width: auto; }

/* for table cells with immediate .content children, which have immediate
 * .paragraph children: use flex to space them evenly and center vertically
*/
td > .content > .paragraph {
  display: flex;
  align-items: center;
  justify-content: space-around;
}
</style>
++++

[.FillVerticalSpace, cols="<.^1a,^.^20a,^.^14a",stripes="none", options="header"]
|===
|    
| Cross out the expression that is NOT equivalent to the others.
| Justify your choice.

| @n
|
@show{(coe '(/ (+ 2 m) (+ 5 p)))}
@show{(coe '(/ (+ m 2) (+ 5 p)))}
@ifsoln-choice{@show{(coe '(/ (+ 5 p) (+ 2 m)))}}
@show{(coe '(/ (+ m 2) (+ p 5)))}
| @ifsoln{The 3rd circle incorrectly treats division as commutative}

| @n
|
@show{(coe '(+ (* t u) v))}
@show{(coe '(+ (* u t) v))}
@show{(coe '(+ v (* t u)))}
@ifsoln-choice{@show{(coe '(+ t (* u v)))}}
| @ifsoln{All but the 4th circle use commutative operations, so they are equivalent}

| @n
|
@show{(coe '(* (+ b c) (- f g)))}
@show{(coe '(* (- f g) (+ b c)))}
@show{(coe '(* (+ c b) (- f g)))}
@ifsoln-choice{@show{(coe '(* (+ b c) (- g f)))}}
| @ifsoln{The 4th circle changes the order of terms being subtracted, so it is not equivalent.}

| @n
|
@show{(coe '(* 3 (+ (+ h w) 4)))}
@show{(coe '(* (+ (+ h w) 4) 3))}
@ifsoln-choice{@show{(coe '(* (+ h w) (+ 4 3)))}}
@show{(coe '(* 3 (+ 4 (+ h w))))}
| @ifsoln{All but the 3rd circle involve a sum being tripled.}

| @n
|
@show{(coe '(/ (+ m a) (+ t h)))}
@show{(coe '(/ (+ a m) (+ t h)))}
@ifsoln-choice{@show{(coe '(/ (+ t h) (+ m a)))}}
@show{(coe '(/ (+ a m) (+ h t)))}
| @ifsoln{The 3rd circle incorrectly treats division as commutative}

|===


