= Youth Skull Circumference

++++
<style>
#content .forceShading { background-color: #f7f7f8; }
</style>
++++

For every skull marked “child” in the age group column, the sex is “unsure”.  Is this coincidence, or an error in our data?

@vspace{1ex}

To dig into the question, Ms. Trementozzi's class collected data about the circumferences of their own heads.

[cols="1a, 1a, 1a, 1a, 1a", options="header"]
|===
| Group 1 
| Group 2
| Group 3
| Group 4
| Group 5

| 
Boy: in 

Boy: in

Girl: in

Boy: in 

Girl: in

|

Boy: in

Girl: in

Boy: in 

Girl: in

Girl: in

|
|
|
|===

@vspace{1ex}

[.forceShading]
--
@vocab{Average}: the sum of all numbers in a data set, divided by how many there are.
--

@vspace{1ex}
For each group, find the average head circumference for girls and the average head circumference for boys.

[cols="1a, 1a, 1a, 1a, 1a, 1a", options="header"]
|===
| 
| Group 1 
| Group 2
| Group 3
| Group 4
| Group 5

| *girl average:*
|
|
|
|
|

| *boy average:*
|
|
|
|
|

|===

@vspace{1ex}

@n Would it make sense to put this data into a pie chart? Why or why not?

@fitb{}{}

@fitb{}{}








