= Analysis of Research Plan Predicted Outcomes

Respond to the prompts below with your partner.

@n How will the validity of your conclusions be impacted by *Selection Bias*?@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n What could you change to minimize *Selection Bias*?@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n How will the validity of your conclusions be impacted by *Bias in the Study Design*?@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}

@n What could you change to minimize *Bias in the Study Design*?@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n How will the validity of your conclusions be impacted by *Poor Choice of Summary Data*?@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n What could you change to minimize *Poor Choice of Summary Data*?@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}



@n How will the validity of your conclusions be impacted by *Confounding Variables*?@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}


@n What could you change to minimize *Confounding Variables*?@fitb{}{}

@fitb{}{}

@fitb{}{}

@fitb{}{}





