= Evolution of College Admissions (UC vs Other Public Schools)

- This dataset includes data from the common datasets of all 9 colleges in the UC system and 2 colleges from the CSU system
- This dataset can be used to analyze the future of college admissions and whether UCs have found a way to increase diversity at schools despite the affirmative action ban.
- This  dataset has a limited number of categories, making it accessible to any student.
- The columns of this dataset are defined to allow students to start analysis without much additional coding.  I would not recommend taking too many random subsets of data since the analysis hinges on the examination of schools over time. Random sets may result in some unnecessary holes in the data.
- *Column Titles:* College + Year, College, Year, Admission Rate, Most Dominant Race, Percentage of Most Dominant Race, Percentage of Whites, Percentage of Asians, Percentage of Blacks/Latinos/Native Americans, GPA (average), Percentage of In-State Enrollees, UC?, Weighted GPA?
- *Have students...*
  * *define a function* that calculates the difference between the percentage of the most dominant ethnicity and the underrepresented ethnicities for a row.
  * *define a function* that takes in a row and a threshold and returns whether the average GPA of that row exceeds the threshold.
- *Heads Up*
  * Because of the COVID pandemic, 2020 data from each of the schools may skew from the general trend.
  * There is a large chunk of UC Irvine data missing because the GPA was not reported from those schools/the common dataset was missing.
  * All non-UC percentages except for the in-state percentage are hand-calculated.
  * There is a noticeable negative correlation between the year and admission rates and a positive correlation between the year and average GPA.
  * For UCs, there is a negative correlation between the year and in-state percentage.
  * For UCs, there is a positive correlation between the year and underrepresented ethnicities percentage.

