= World Cities: Proximity to Ocean

- This dataset looks at the 5000 most populous (as of 2020) cities in the world and their geographical information, such as elevation, country, continent, and distance from the nearest shoreline. The data comes from various sources, including the World Cities Database (for cities and population), the National Centers for Environmental Information (for worlds shoreline), JohnSnowLabs (for each country's continent), and the World bank (for country GDP per capita). 
- This dataset has a limited number of categories, making it accessible to any student.
- The columns of this dataset are defined to allow students to start analysis without much additional coding.
- *Column Titles:* Name, Country, Population (2020), Continent, Elevation (m), Distance to Shore (km), GDP per Capita ($) 2017. This refers to the country's GDP per capita.
- *Have students...*
  * *define a function* is-poverty, which returns true if a city's GDP per capita is below $15,000.
  * *define a function* is-climate-change-prone, which returns true if a city's distance from shore is less than 20km and elevation is less than 10m.
  * *define a function* is-metropolis, which returns true if a city's population is above 1 million dollars and GDP per capita is above $10,000.

