= Gerrymandering

- This dataset looks at the 2018 United States House of Representatives elections. It includes state-wise population and voter turnout data, as well as columns comparing the percentage of votes a particular party recieved with the number of seats they won.
- This dataset has a huge number of columns that will excite
some students and may overwhelm others.
- The columns of this dataset are defined to allow students to start analysis without much additional coding.
- *Column Titles:* Population, %Turnout, %Vote Democrat, %Vote Republican, Total Seats, Democrat Seats, Republican Seats, %Seats Democrat, %Seats Republican, Winning Party, Seats match vote (Computed for each state by multiplying %Vote Democrat and %Vote Republican by the Total Seats for that state. If the resultant "expected" number of seats can be rounded up or down to match the data in both the Democrat Seats and Republican Seats columns respectively, this field is true. Else false.)
- *Have students...*
  * *define a function* majority-turnout, which returns true if a state has a voter turnout of more than 50%.
  * *define a function* num-votes-dem, which returns the number of people who voted for Democratic party candidates in a given state.
  * *define a function* victory-margin, which returns the number of votes the winning party in a particular state won by. 
  * *define a function* expected-seats-rep, which returns the number of seats you would expect Republican party candidates to win given the percentage of votes they received in a particular state.
  * *define a function* flipped-winner, which returns true if the party that recieved the majority of votes did not win the majority of seats in a given state.
- *Heads Up:* Before computing the number of people who voted for either party, the state's population would have to be multiplied by the percentage voter turnout.
