= U.S. Jobs

This dataset includes data about 140 occupations in the U.S. in 2019.
For each occupation, this dataset records its occupation type, total number of employees, percentage of non-white employees, percentage of female employees, typical entry level educational requirement, annual median wage, weekly median wage, and female weekly median wage.

- This dataset has a huge number of columns that will excite some students and may overwhelm others.

- The columns of this dataset require calculations to convert data before students start making graphs.


**Column Titles:** Occupation, Occupation Type, Total Number of Employees, Percentage of Non-white Employees, Percentage of Female Employees, Typical Entry Level Educational Requirement, Annual Median Wage, Weekly Median Wage, Female Weekly Median Wage

*Have students...*

- *define a function* gender-wage-gap, which computes the numerical difference
	between female employees' weekly median wage and all employees' weekly median wage.
- *define a function* female-wage-is-lower, which returns true if an occupation offers
	female employees a wage comparatively lower wage.

*Heads Up*

- Columns list the median wage for all employees and median wage for female employees. In order to look into gender income equality, wage gap would need to be calculated.

- *Outlier to be aware of:* Occupation veterinarian offers significantly higher wage for female employees.
