= IGN Game Review

- This dataset focuses on @link{https://www.ign.com/reviews/games, video game reviews} from 2017-2018.
- *Column Titles:* title, playstation, xbox, nintendo, pc, other, score, genre, editors-choice, release-year, release-month
- Since many titles are available for more than one platform, columns like `playstation` and `pc` are all Booleans. This also makes it easy to create grouped samples, via simple filter functions that merely look up the value of a particular column.
- *Have Students...*
  * explore whether game studios tend to release their highest-rated games around certain months of the year.
  * define filter functions like `is-xbox` or `is-pc`, to create grouped samples of platform-specific reviews and search for differences between platforms.
- *Heads Up*
  * Scatter plots for this dataset may be surprising, because IGN used whole numbers (4, 5, 6, etc.) for most of their ratings. As a result, most of the dots on the scatter plot are "clumped" along whole numbers.
  * Interesting enough, IGN switched to allow decimal ratings in some years (4.1, 4.5, 4.6, etc.), which results in some wildly different distributions. Can students find this difference by looking at the scatter plot? Can they uncover the reason (IGN's shift in scoring) by looking online?
