= Global Waste by Country 

- This dataset includes data from 174 countries that indicates their annual waste production as well as basic societal statistics that are associated with waste production.
- The dataset also includes the global region of countries, as well as a few basic indicators of national waste management practices.
- This dataset has a limited number of categories, making it accessible to any student.
- The columns of this dataset are defined to allow students to start analysis without much additional coding.
- This dataset is good for finding linear associations between two variables. Many of the variables are positively correlated with solid municipal waste production (total and per capita).
- *Column Titles:*
Name, Region, Economic Development, GDP per Capita (USD), Total Municipal Solid Waste per Year (tons), Population, Hazardous Waste per Year (tons), Has national agency for enforcing solid waste laws, Has national law governing solid waste management, MSW per Capita (tons/people), Hazardous Waste per Capita (tons/people), Percent Urban, Urbanization Rate, Human Development Index, Adult Obesity Rate by BMI
- *Have students...*
  * *define a function* urban-msw-trend, which takes two country names and returns true if the one with a greater MSW per capita also has a greater urban percentage, and has an increasing urbanization rate.
  * *define a function* number-urban, which computes the total amount of people within a country living in urban areas.
  * *define a function* total-gdp, which computes the total GDP of a country.
  * *define a function* number-of-subgroup, that takes a column and string, and determines how many times that string occurs as a value in that column. Use this function to determine how many countries in the dataset are in Sub-Saharan Africa, and how many have economies in transition.
- *Heads Up*
  * Strong Correlations: Urban percent and MSW per capita, Obesity Rate and MSW per capita, Population and MSW, Urban percent and HDI
  * *Outlier to be aware of:* Ukraine has an extremely high hazardous waste output. This value is from the World Bank dataset so it should be reputable, but from further research it does not seem to be indicative of the average annual hazardous waste output for Ukraine.
  * *Outlier to be aware of:* Island nations of Oceania tend to have much higher obesity rates than any other countries in the dataset.