= Health by U.S. County 2021

- This dataset includes data from 2906 counties in the United States from https://www.countyhealthrankings.org/ and is focused on indicators of the mental and physical health condition of these counties in 2021.
- This dataset has a huge number of columns that will excite some students and may overwhelm others.
- The columns of this dataset are defined to allow students to start analysis without much additional coding.
- *Column Titles:*
FIPS, County, State, % Fair or Poor Health, Average Number of Physically Unhealthy Days, Average Number of Mentally Unhealthy Days, % Smokers, % Adults with Obesity, % Physically Inactive, % Excessive Drinking, % Uninsured, % Completed High School, % Some College, % Unemployed, % Children in Poverty, 80th Percentile Income, 20th Percentile Incomer, Income Ratio, % Children in Single-Parent Households, Presence of Water Violation, % Severe Housing Problem, % Long Commute -- Drives Alone
- *Have students...*
  * *define a function* is-in-ca, which returns “true” if a county belongs to California
  * *define a function* violate-water, which returns “true” if a county has water violation
  * *define a function* mentally-unhealthy, which returns “true” if a county has greater mentally unhealthy days than physically unhealthy days
  * Students are encouraged to investigate the correlation between Average Number of Physically Unhealthy Days and % Smokers/% Adults with Obesity/% Physically Inactive/% Excessive Drinking.
  * Students are encouraged to investigate the correlation between Average Number of Mentally Unhealthy Days and Income Ratio/% Children in Single-Parent Households/ Severe Housing Problem, % Drive Alone to Work/% Long Commute -- Drives Alone.
- *Outliers to be aware of:*
  * There exists one state with only 21% completing high school and 1% attending college, a percentage significantly below all other counties included in the dataset.
- *Strong Correlations to be aware of:*
  * There exists a strong positive correlation between Average Number of Physically Unhealthy Days and Average Number of Mentally Unhealthy Days.
  * There exists a very strong positive correlation between % Completed High School and % Some College.
- *Heads Up*
  * All numbers in the dataset do not show their fractional parts, but they are not necessarily positive integers.
