[.landscape]
= Mapping Examples with Circles of Evaluation

++++
<style>
table tbody tr { height: 2.2in; }
table tbody td { position: relative; padding: 0 !important; }
td p { margin: 0 !important; }
table tbody td .content { width: 100%; height: 100%; position: absolute; padding: 0.5em; }
table td:nth-child(2n+1) .paragraph:last-child { position: absolute; bottom: 0; }
</style>
++++

@n Write the Contract and Purpose for `gt` on the line below.

@n Draw Circles of Evaluation examples for `gt` below, showing both _how the function is used_ and then _what it does with an input_. Then translate those Circles into code. _The Circles of Evaluation for the first example are done for you._

Contract: @fitb{}{@showsoln{(contract 'gt '(Number) "Image")}}

Purpose Statement: @fitb{}{}

[cols="7a,^.^1a,10a", stripes="none", options="header"]
|===
| If I type...
| &rarr;
| It should map to...

| *Circle of Evaluation*

@show{(coe '(gt 75))}

*Code:* @fitb{}{@showsoln{(code '(gt 75))}}

|&rarr;
|*Circle of Evaluation:*

@show{(coe '(triangle 75 "solid" "green"))}

Code: @fitb{}{@showsoln{(code '(triangle 75 "solid" "green"))}}

|*Circle of Evaluation*

@showsoln{(coe '(gt 120))}

*Code:* @fitb{}{@showsoln{(code '(gt 120))}}
|&rarr;
|*Circle of Evaluation:*

@showsoln{(coe '(triangle 120 "solid" "green"))}

*Code:* @fitb{}{@showsoln{(code '(triangle 120 "solid" "green"))}}

|===
