= How Tables Fail the Vertical Line Test

++++
<style>
  img { max-width: 200px; }
</style>
++++

@n Each of the graphs below is also represented by a table. Use the vertical line test to determine whether or not each graph represents a function.

[cols="^.^1a,^.^1a,^.^1a"]
|===
|@centered-image{../images/g4.png, "Scatter plots with the following points: (-2,1), (-1,2), (1,0), (1,-1), (2,1)"}
|@centered-image{../images/g2.png, graph of a parabola opening upward}
|@centered-image{../images/g3.png, "v-shaped graph opening to the right"}
| *Function* or *Not a Function*?			| *Function* or *Not a Function*			| *Function* or *Not a Function*|
[.sideways-pyret-table]
!===
! x ! -2 ! -1 ! 1 ! 1   ! 2
! y ! 1  ! 2  ! 0 ! -1  ! 1
!===
|
[.sideways-pyret-table]
!===
! x ! -2 ! -1 ! 0 ! 1 ! 2
! y ! 4  ! 1  ! 0 ! 1 ! 4
!===
|
[.sideways-pyret-table]
!===
! x ! 2 ! 1 ! 0 ! 1  ! 2
! y ! 2 ! 1 ! 0 ! -1 ! -2
!===
|===

@n For each graph that failed the vertical line test, label the offending points with their coordinates.

@n Find the same coordinates in the table below the graph and circle or highlight them.

@n What do the tables of the non-functions have in common? What could you look for in other tables to identify whether or not they could represent a function?

@vspace{15ex}

@n Use the process you just described to determine whether each table below could represent a function. Circle or highlight the points that would end up on the same vertical line.

[cols="1a,1a,1a,1a", grid="none", frame="none"]
|===
|
[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! -2
! 1 ! -2
! 2 ! -2
! 3 ! -2
! 4 ! -2
!===
|
[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 0 ! -2
! 1 ! 1
! 2 ! 4
! 3 ! 7
! 3 ! 10
!===
|
[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x  ! y
! 0  ! 3
! 1  ! 4
! -1 ! 5
! 2  ! 6
! -2  ! 7
!===
|
[.pyret-table.first-table,cols="1,1",options="header"]
!===
! x ! y
! 1 ! 0
! 0 ! 1
! 1 ! 2
! 2 ! 3
! 3 ! 4
!===
| *Function* or *Not*?
| *Function* or *Not*?
| *Function* or *Not*?
| *Function* or *Not*?
|===
