= Practicing Contracts: Domain & Range

@vspace{1ex}

Consider the following contract:

----
is-beach-weather :: Number, String -> Boolean
----

@n What is the *Name* of this function? @fitb{25em}{@show{(if *solutions-mode?* "_is-beach-weather_" "")}}

@n How many arguments are in this function's  *Domain*? @fitb{18em}{@show{(if *solutions-mode?* "_2_" "")}}

@n What is the *type* of this function's  *first argument*? @fitb{18em}{@show{(if *solutions-mode?* "_Number_" "")}}

@n What is the *type* of this function's  *second argument*? @fitb{17em}{@show{(if *solutions-mode?* "_String_" "")}}

@n What is the *Range* of this function? @fitb{25em}{@show{(if *solutions-mode?* "_Boolean_" "")}} 

@vspace{1ex}

@n Circle the expression below that shows the correct application of this function, based on its contract.

@vspace{1ex}

A. @show{(sexp->code `(is-beach-weather 70 90))}

B. @show{(sexp->code `(is-beach-weather 80 100 "cloudy"))}

C. @show{(sexp->code `(is-beach-weather "sunny" 90))}

D.@show{(if *solutions-mode?* "***" "")} @show{(sexp->code `(is-beach-weather 90 "stormy weather"))} 

@vspace{1ex}

Consider the following contract:

----
cylinder :: Number, Number, String -> Image
----

@n What is the *Name* of this function? @fitb{26em}{@show{(if *solutions-mode?* "_radius_" "")}}

@n How may arguments are in this function's *Domain*? @fitb{18em}{@show{(if *solutions-mode?* "_3_" "")}}

@n What is the *type* of this function's *first argument*? @fitb{18em}{@show{(if *solutions-mode?* "_Number_" "")}}

@n What is the *type* of this function's *second argument*? @fitb{17em}{@show{(if *solutions-mode?* "_Number_" "")}}

@n What is the *type* of this function's *third argument*? @fitb{18em}{@show{(if *solutions-mode?* "_String_" "")}}

@n What is the *Range* of this function? @fitb{25em}{@show{(if *solutions-mode?* "_Image_" "")}}.

@vspace{1ex}

@n Below, circle which expression is the correct application of this function, based on its contract.

@vspace{1ex}

A. @show{(sexp->code `(cylinder "red" 10 60))}

B. @show{(sexp->code `(cylinder 30 "green"))}

C. @show{(if *solutions-mode?* "***" "")} @show{(sexp->code `(cylinder 10 25 "blue"))}

D. @show{(sexp->code `(cylinder 14 "orange" 25))}
