= Triangle Contracts (SAS & ASA)

++++
<style>
td, #content .forceShading { font-size: 0.85rem !important; }
#content p { font-size: 0.9rem; margin: 0;}
#content .listingblock .highlight { padding: 0; }
.forceShading {background: #f7f7f8;}
</style>
++++

Type each expression (left) below into the editor and match it to the image it creates (right).

[cols="^.^18a,^.^1,3,^.^1,^.^8a",stripes="none",grid="none",frame="none", options="header"]
|===
| Expression
|||
| Image

| @show{(sexp->code '(triangle-sas 120 45 70 "solid" "black"))}
| *@n* || *A*
| @centered-image{../images/sas-120-90-70.png}

| @show{(sexp->code '(triangle-sas 120 90 70 "solid" "black"))}
| *@n* || *B*
| @centered-image{../images/sas-120-135-70.png}

| @show{(sexp->code '(triangle-sas 120 135 70 "solid" "black"))}
| *@n* || *C*
| @centered-image{../images/sas-70-135-120.png}

| @show{(sexp->code '(triangle-sas 70 135 120 "solid" "black"))}
| *@n* || *D*
| @centered-image{../images/sas-120-45-70.png}
|===

Think about how you would describe each of the arguments that @show{(sexp->code 'triangle-sas)} takes in to someone who'd never used the function before and annotate the contract below using descriptive variable names.

@vspace{1ex}

[.forceShading]
--
@show{(sexp->code 'triangle-sas)}`{two-colons} (`

[.indentedpara]
@fitb{25em}{} `{two-colons} Number,`
@fitb{25em}{} `{two-colons} Number,`
@fitb{25em}{} `{two-colons} Number,`
@fitb{25em}{} `{two-colons} String,`
@fitb{25em}{} `{two-colons} String`

`) -> Image`
--

@vspace{1ex}

Add examples of each of the triangle functions we've explored to your contracts page.

@vspace{1ex}

If you have time, experiment with the @show{(sexp->code 'triangle-asa)} function.

[.forceShading]
@show{(sexp->code 'triangle-asa)}`{two-colons} (`
```
	left-angle :: Number,
	left-side :: Number,
	bottom-angle :: Number,
	style :: String
	color :: String

) -> Image
```
