= Adding Collisions

@description{Students use the distance formula and their data structures to determine when two or more characters in their games have collided. They extend their `update` handlers to generate a new structure that represents the game after a collision has occurred.}

[@lesson-intro-table]
|===
@lesson-prereqs{re-build-your-own-animation}

| Lesson Goals
|
@objectives
@objective{Add collision-detection to a reactor-based game}

| Materials
|[.materials-links]
@material-links

| Supplemental Materials
|
- Cutouts of Cat and Dog images
- Cutouts of Pythagorean Theorem packets [link:images/pythag1.png[1], link:images/pythag2.png[2] -- 1 per cluster


|===

== Collision Detection

=== Overview
Students implement a simple Boolean-producing function, which composes with the distance function they implemented.

=== Launch
Once we know how to calculate the distance between two points, what do we do with it? How does that help us implement collision in our games?

@lesson-instruction{
How close should your danger and your player be, before they hit each other?
}

@slidebreak

@lesson-instruction{
- Turn to @printable-exercise{is-collision.adoc} you’ll find the Word Problem for `is-collision`.
- Fill in the Contract, two examples, and then write the code. Remember: you WILL need to make use of the `distance` function you just wrote!
- When you’re done, type it into your game, underneath `distance`.
}

@slidebreak

Now that you have a function which will check whether two things are colliding, you can use it in your game! For extra practice, You can also implement collision detection in this @starter-file{ninja-cat-collisions}.

This is the program we’ll be altering for this lesson. In Ninja Cat, when the cat collides with the dog, we want to put the dog offscreen so that it can come back to attack again.

=== Investigate
@lesson-instruction{
Out of the major functions in the game (`next-state-tick`, `draw-state`, or `next-state-key`), which do you think you’ll need to edit to handle collisions, changing the `GameState` when two characters collide?
}

We’ll need to make some more `if` branches for `next-state-tick`.

@slidebreak

@QandA{
@Q{How could you check whether the cat and dog are colliding? Have you written a function to check that?}
@Q{What do the inputs need to be?}
@Q{How do you get the `playery` out of the `GameState`? `playerx`?}
@Q{How do you get the `dangerx` out of the `GameState`? `dangery`?}
}

@slidebreak

```
if is-collision(
  g.playerx,
  g.playery,
  g.dangerx,
  g.dangery):   ...result...
```

Remember that `next-state-tick` produces a GameState, so what function should come first in our result?

@slidebreak
```
if is-collision(
  g.playerx,
  g.playery,
  g.dangerx,
  g.dangery):
game(
  ...playerx...,
  ...playery...,
  ...dangerx...,
  ...dangery...,
  ...dangerspeed...
  ...targetx...
  ...targety...
  ...targetspeed...)
```

@slidebreak

@QandA{
@Q{What should happen when the cat and dog collide?}
@Q{Can you think of a number that puts the dog off the screen on the left side?}
@Q{What about the dog’s y-coordinate?}
}

We could choose a number and always place it at the same y-coordinate each time, but then the game would be really easy! To make it more challenging, we’d like the dog to appear at a random y-coordinate each time it collides with the cat. Thankfully, Pyret has a function which produces a random number between zero and its input:

@show{ (contract "random" '("Number") "Number" )}


@slidebreak

```
if is-collision(
  g.playerx,
  g.playery,
  g.dangerx,
  g.dangery):
game(
  g.playerx,
  200,
  random(480),
  0,
  0,
  g.targetx,
  g.targety,
  g.targetspeed)
```

Collision detection must be part of the next-state-tick function because the game should be checking for a collision each time the GameState is updated, on every tick.

@teacher{Students may assume that draw-state should handle collision detection, but point out that the Range of draw-state is an Image, and their function must return a new GameState in order to set the locations of the characters after a collision.}

@slidebreak

@lesson-instruction{
Once you’ve finished, write another branch to check whether the player and the target have collided. *Challenges:*

- Change your first condition so that the danger gets reset only when the player and danger collide AND the cat is jumping. (What must be true about the player’s y-coordinate for it to be jumping?)
- Add another condition to check whether the player has collided with the danger while the player is on the ground. This could be a single expression within `next-state-tick`, or you can write a @vocab{helper function} called `game-over` to do this work, and use it in other functions as well (maybe the GameState is drawn differently once the game is over.)
}
