= Modeling Recent Carbon Dioxide Levels (continued)
++++
<style>
/* Make autonums inside tables look consistent with those outside */
td .autonum::after { content: ')' !important; }

/* Tweak table display */
td { padding: 0 5px !important; }
td .codetwo { color: black; background: none; }
table table td { color: inherit !important; padding: 3px 0 !important; }
body .center { padding: 0; }
.directions p { line-height: 1.75 !important; }
table+.paragraph .autonum {padding-top: 0; }

/* Shorten fill in the blanks, and give fitbrubies more vertical space */
.fitb, .fitbruby { min-width: 2em; }
.indentedpara .fitbruby { padding-top: 0.8rem; }
.studentAnswerMedium { min-width: 65pt !important; }
.fitbruby{ margin-bottom: 1rem; }
.ruby { bottom: -13px !important; }
</style>
++++


@define{COtwo}{@math{\text{CO}_2}}
@do{
(define-values (hi lo lo-dateA lo-dateB) (values 424 415.74 2022.708 2023.708))
(define p (abs (- lo-dateA lo-dateB)))
(define a 4.13)
(define b 6.28)
(define k 419.87)
(define h 2023.1)
(define h-cos 2023.35)
}

@define{hi}{@show{hi}}
@define{lo}{@show{lo}}
@define{lo-dateA}{@show{lo-dateA}}
@define{lo-dateB}{@show{lo-dateB}}
@define{p}{@show{(round p)}}
@define{a}{@show{a}}
@define{b}{@show{b}}
@define{k}{@show{k}}
@define{h}{@show{h}}
@define{h-cos}{@show{h-cos}}


@link-instructions{
This page relies on the @starter-file{alg2-co2}. Make sure you have it open on your computer!
}

== Define Your Periodic Model

@n Define a periodic model using the values you computed for @math{a}, @math{k}, @math{h} and @math{b} on @printable-exercise{modeling-recent-co2.adoc}.

@teacher{Students horizontal shift estimates may vary slightly from this function definition.}

@vspace{1ex}

[cols="1a, .^12a", frame="none", stripes="none"]
|===
| *Function Notation*
|

@math{periodic-sin(x) =}
@fitbruby{70pt}{(@ifsoln{@a}}{amplitude (@math{a})} {nbsp} @math{\times} {nbsp} @math{sin}(
@fitbruby{70pt}{@ifsoln{@b}}{frequency (@math{b})} @math{(x -}
@fitbruby{70pt}{@ifsoln{@h}}{horizontal shift (@math{h})} ))) {nbsp} @math{+} {nbsp}
@fitbruby{70pt}{@ifsoln{@k}}{vertical shift (@math{k})}

| @vspace{1ex} +
*Pyret Notation*
|
@show{(code `(define (periodic-sin x) (+ (* (?ANS ,a) (sin (* (?ANS ,b) (- x (?ANS ,h))))) (?ANS ,k))))}
|===

@vspace{1ex}

@n Then update the `periodic-sin` function definition in your starter file to match what you've just written.

@vspace{1ex}

@star Try translating the definition you wrote for `periodic` so that it uses  @math{\text{cosine}}  instead of @math{\text{sine}}:

@vspace{1ex}

[cols="1a, .^12a", frame="none", stripes="none"]
|===
|*Function Notation*
|

@math{periodic-cos(x) =}
@fitbruby{70pt}{@ifsoln{@a}}{amplitude (@math{a})} {nbsp} @math{\times} {nbsp} @math{cos}(
@fitbruby{70pt}{@ifsoln{@b}}{frequency (@math{b})} @math{(x -}
@fitbruby{70pt}{@ifsoln{@h-cos}}{horizontal shift (@math{h})})) {nbsp} @math{+} {nbsp}
@fitbruby{70pt}{@ifsoln{@k}}{vertical shift (@math{k})}

| @vspace{1ex} +
*Pyret Notation*
|
@show{(code `(define (periodic-cos x) (+ (* (?ANS ,a) (cos (* (?ANS ,b) (- x (?ANS ,h-cos))))) (?ANS ,k))))}
|===

@vspace{1ex}
== Fit Your Periodic Model to the Data

@n Use `fit-model` to fit your `periodic` model to the data in the `recent-table`. What S-value do you get? @fitb{}{@ifsoln{Answers will vary slightly.  ~1.2 }}

@vspace{1ex}

[cols="9a,1,10a", grid="none",frame="none"]
|===
| @n On the scatter plot below, make a sketch of what you see in pyret showing how the `periodic` model fits the data. +

@vspace{1ex}

@image{../images/recent-pyret-scatter.png}
|
| @n Then fill in the blanks below to tell us what the model means. +
@vspace{1ex} +
_Between the end of 2022 and 2023, the amount of @math{CO_2} in the air fluctuated between @fitbruby{6em}{@ifsoln{415.74}}{lowest} and @fitbruby{6em}{@ifsoln{424}}{highest} parts-per-million. This pattern appears to be @vocab{periodic}, with an amplitude of @fitbruby{6em}{@ifsoln{4.13}}{amplitude} rising and falling around a @vocab{midline} of @fitbruby{6em}{@ifsoln{419.87}}{midline}. We expect this pattern to repeat every @fitbruby{4em}{@ifsoln{1}}{period} @fitbruby{5em}{@ifsoln{year}}{x-units}. The error in the model is described by an @vocab{S-value} of about @fitbruby{1em}{@ifsoln{1.2}}{S}@fitbruby{8em}{@ifsoln{ppm}}{y-units}. @hspace{1em} I
@fitbruby{18em}{@ifsoln{agree}}{strongly agree, agree, disagree, strongly disagree}
that this model is a good fit considering that
@fitbruby{8em}{@ifsoln{altitude}}{y-variable} in this dataset ranges from about
@fitbruby{8em}{@ifsoln{416 ppm}}{lowest y-value} to @fitbruby{8em}{@ifsoln{424 ppm}}{highest y-value}._
|===

