= Exploring the Covid Dataset
++++
<style>
/* Make sure autonums that appear inside tables have the closing paren */
body.workbookpage td .autonum::after { content: ')' !important; }

/* Tweak table formatting */
td:last-child { padding-top: 0; padding-bottom: 0; }
td { color: inherit !important; }
body .center { padding: 0; }
</style>
++++

@link-instructions{
For this page, you'll need to have the @starter-file{alg2-covid} open on your computer. If you haven't already, select *Save a Copy* from the "File" menu to make a copy of the file that's just for you.
}

@n Take a look at the Definitions Area and find the "Notes on Columns". What is the start date for the data in this table? @fitb{}{@ifsoln{June 9, 2020}}

@n Click "Run", and evaluate `covid-table` in the Interactions Area. What do you notice? @fitb{}{}

@fitb{}{@ifsoln{There is data for the number of positive COVID cases each day for 6 states (CT, MA, ME, NH, VT, RI)}}

@n Evaluate `MA1` in the Interactions Area. What does it return? @fitb{}{@ifsoln{A single row of the table.}}

@n Evaluate `CT1`. What information do you learn? @fitb{}{@ifsoln{1 day after 6/10/20, the state of Connecticut had 44347 total positive covid cases.}}

@n Evaluate `NH1`. Why is it "unbound" and how could we make it work? @fitb{}{@ifsoln{There are only definitions for `MA1`, `CT1` and `ME1`}}

@n Define three new Rows called `NH1`, `RI1` and `VT1`, for New Hampshire, Rhode Island and Vermont. Click "Run" and test them out.

@hspace{3em}+a.+ How many people in *Vermont* had tested positive by June 10th, 2020? @fitb{}{@ifsoln{1092}} +
@hspace{3em}+b.+ How many people in *New Hampshire* tested positive by June 10th, 2020? @fitb{}{@ifsoln{5178}} +
@hspace{3em}+c.+ How many people in *Rhode Island* tested positive by June 10th, 2020? @fitb{}{@ifsoln{15855}}

@n In Pyret, make a scatter plot from `covid-table` showing the relationship between `day` and `positive`, and using `state` as your labels. Sketch the resulting scatter plot below.
[.FillVerticalSpace, cols="^.^2a,.^1a", options="grid",stripes="none",frame="none"]
|===
|

@ifnotsoln{@image{../images/covid-grid.png, 400}}
@ifsoln{@image{../images/positive-v-day.png}} 

|
--
@n In which state did the number of cases grow _fastest_?

@fitb{}{@ifsoln{MA}}

@vspace{5ex}

@n In which state did the number of cases grow _slowest_?

@fitb{}{@ifsoln{VT}}

@vspace{5ex}

@n Are these strong or weak relationship(s)?

@fitb{}{@ifsoln{strong}}
--
|===

@n What do you *Notice?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}

@n What do you *Wonder?* @fitb{}{} +
@fitb{}{} +
@fitb{}{}
