#lang racket

(provide *glossary-list*)

#|
Glossary for terminology used in the notes.  The first entry of each entry can be either
a single string or a list of keys that map to the same definition.
If a list of keys is provided, the generated glossary will use the first in the list
when it prints out the glossary for a particular unit
|#

(define *glossary-list*
  '( 
    (#| accessor functions |# "funciones de acceso" "funciones para extraer valores de una estructura de datos")
    (#| apply |# "aplicando" "use una función dada en algunas entradas")
    (#| argument |# ("argumento" "argumentos") "las entradas de una función, las expresiones de los argumentos siguen el nombre de una función")
    (#| ascending |# "ascendente" "un orden de valores en lo cual los más bajos aparecen primero y los más grandes aparecen después")
    (#| average, mean |# "el promedio" "Un número que representa el centro o valor 'típico' en un conjunto de datos. Resultado que se obtiene al dividir la suma de varias cantidades por el número de sumandos.")
    (#|  |# ("eje" "ejes") "A number line on a scatter plot, used to place points that represent pairs of values in data sets")
    (#| bar chart |# "gráfico de barras" "a display of categorical data that uses bars positioned over category values; each bar’s height reflects the count or percentage of data values in that category")
    (#| bin |# ("intervalo" "intervalos") "un rango al que pueden pertenecer los valores de un conjunto de datos; hay una barra en un histograma por intervalo")
    (#| Boolean |# "booleano" "un tipo de datos con dos valores: true y false")
    (#| boxplot |# ("diagrama de caja" "diagrama de caja y bigotes") "El diagrama de caja (también conocido como diagrama de caja y bigotes) es una forma de mostrar la distribución de datos basada en el resumen de cinco números: mínimo (el valor más bajo), primer cuartil, mediana, tercer cuartil y máximo (el valor más alto).")
    (#| calling |# ("llamada" "llamadas") "Utilizando una función dándole entradas")
    (#| category |# ("category" "categories") "the set of possible values that a value in a categorical data set can have")
    (#| categorial data |# "categorical data" "kind of data with a value that has a fixed number of possible values")
    (#| circle of evaluation |# "círculo de evaluación" "un diagrama de la estructura de una expresión (aritmética o código)")
    (#| clause |# "cláusula" "una pregunta y su respuesta correspondiente en una expresión condicional")
    (#| chart |# ("chart" "charts") "visual reprsentations of how values in a data set are distributed")
    (#| column |# ("column" "columns") "set of values in a table of a particular type.  Every row has exactly 1 element in every column")
    (#| combination |# ("combination" "combinations") "the number of possible arrangements in a collection of items where the order of the selection does NOT matter. (ABC and CBA would be considered the same combination)")
    (#| conditional |# "condicional" "una expresión de código hecha de preguntas y respuestas")
    (#| constructor |# "función constructor" "La función que crea una estructura de datos particular")
    (#| contract |# "contrato" "una declaración del nombre, dominio y rango de una función")
    (#| contract error |# ("contract error" "contract errors") "errors where the code makes sense, but uses a function with the wrong number or type of arguments")
    (#| correlation |# ("correlation" "correlations") "A relationship between two data sets")
    (#| data block |# "data block" "Code that lists the name, constructor(s), and field(s) of a data structure")
    (#| data row |# ("data row" "data rows") "an individual, structured piece of data in a dataset")
    (#| data science |# "data science" "The study of using data to answer questions about the world")
    (#| dataset |# ("dataset" "datasets") "a collection of related information that is composed of separate elements, but can be manipulated as a unit by a computer")
    (#| data structure |# ("estructura de datos" "estructuras de datos") "Un grupo de valores que se pueden devolver como un único tipo de datos")
    (#| data type |# ("tipo de datos" "tipos de datos") "Una manera de clasificar valores, como: Número, Cadena, Imagen o Booleano")
    (#| debug |# "debug" "to find and fix errors in one's code")
    (#| define |# "definir" "asociar un nombre descriptivo con un valor")
    (#| definitions area |# "área de definiciones" "el cuadro de texto en el Editor, donde se escriben definiciones de valores y funciones")
    (#| descending |# "descending" "an order in which higher values appear first, and lower values appear after")
    (#| design recipe |# "receta de diseño" "una secuencia de pasos que ayuda a las personas a documentar, probar y escribir funciones")
    (#| direction |# "direction" "of a relationship between two quantitative variables: whether they tend to increase together, or if as one goes up the other tends to go down")
    (#| domain |# "dominio" "el tipo de datos que espera una función")
    (#| dot accessors |# "dot-accessors" "Una manera de extraer valores de una estructura de datos")
    (#| driver |# "driver" "in pair programming, the person who is doing the typing")
    (#| edge |# ("edge" "edges") "the line segments where the faces of solid figures meet in each of the three dimensions.")
    (#| editor |# "editor" "software en el que se puede escribir y evaluar código")
    (#| entry |# ("entry" "entries") "a single value in a table, belonging to a particular row and column")
    (#| error message |# ("mensaje de error" "mensajes de error") "información del equipo sobre errores en el código")
    (#| evaluate |# "evaluar" "realizar el cálculo en una expresión, producir una respuesta")
    (#| evaluates to |# ("equivale a" "equivale") "el resultado de calcular una expresión")
    (#| event |# "eventos" "algo que sucede fuera de un programa en ejecución, al que el programa puede responder")
    (#| event-based programming |# "programacion basada en eventos" "un estilo de programación en el que se escriben todas las funciones para responder a los clics del ratón, pulsaciones de teclas, etc.")
    (#| examples |# "ejemplos" "muestra el uso de una función en entradas específicas y el cálculo que debe realizar la función en esas entradas")
    (#| examples block |# "examples block" "Pyret code that lists examples starting with 'examples:' and ends with 'end'")
    (#| expression |# ("expresión" "expresiones") "un cálculo escrito en las reglas de algún lenguaje (como aritmética, código o un Círculo de Evaluación)")
    (#| extend |# ("extend" "extending" "extends") "a table query that creates a table with new column(s), whose entries are computed with an expression")
    (#| extract |# "extract" "to construct a list using data from a particular column in a table")
    (#| face |# ("face" "faces") "the shapes on the outside of a figure")
    (#| field |# "field" "A part of a data structure that has a name and holds a single value of a specified datatype")
    (#| form |# "form" "of a relationship between two quantitative variables: whether the two variables together vary linearly or in some other way")
    (#| function |# ("función" "funciones") "un objeto matemático que toma en algunas entradas y produce una salida")
    (#| function block |# "function block" "Pyret code that names a function, lists its variables, and states the expression to compute when the function is used")
    (#| function definition |# "definición de función" "que designa una función, enumera sus variables e indica la expresión a calcular cuando se utiliza la función")
    (#| frequency |# ("frequency" "frequencies") "how often a particular value appears in a data set")
    (#| frequency bar chart |# ("frequency bar chart" "frequency bar charts") "A bar chart in which each the length of each bar corresponds to the frequency of a particular value")
    (#| grouped sample |# ("grouped sample" "grouped samples") "a non-random subset of individuals chosen from a larger set, where the individuals belong to a specific group")
    (#| handler |# "handler" "Connects an event (like a tick or keypress) and a function within a reactor")
    (#| header |# ("header" "headers") "the titles of each column of a table, usually shown at the top")
    (#| helper function |# "función auxiliar" "Una función invocada desde otras funciones con el propósito de realizar una tarea concreta requerida por éstas" "operador")
    (#| histogram |# ("histograma" "histogramas") "Un gráfico de barras de frecuencia especial en el que cada barra cuenta la frecuencia de los valores que aparecen en un cierto intervalo.")
    (#| horizontal axis |# "eje horizontal" "eje en un diagrama de dispersión que va de izquierda a derecha")
    (#| hypotenuse |# "hipotenusa" "el lado opuesto al ángulo de 90 grados en un triángulo rectángulo")
    (#| identifier column |# "identifier column" "a column of unique values which identify all the individual rows (e.g. - student IDs, SSNs, etc)")
    (#| image |# "imagen" "un tipo de datos para imágenes")
    (#| instance |# "instancias" "valores específicos de datos")
    (#| interactions area |# "área de interacciones" "el cuadro de texto a la derecha en el Editor, donde se ingresan las expresiones para ser evaluadas")
    (#| interquartile range |# "interquartile range" "The interquartile range (IQR) is a measure of variability, based on dividing a data set into four quartiles. The values that divide each part are called the first (Q1), second (Q2), and third quartiles (Q3)")
    (#| intersection |# ("intersection" "intersections") "the set of values that makes both inequalities true")    
    (#| legal expression |# "expresión legal" "expresión que sigue las Reglas de Código para un lenguaje de programación")
    (#| library |# ("library" "libraries") "A collection of functions that can be made available to our program by using include")
    (#| linear |# ("linear" "linear relationship") "a rule that computes one quantity from another, which can be graphed as straight line or written as a sequence of numbers that change at a constant rate")
    (#| linear regression |# "linear regression" "a linear approach for modeling the relationship between a dependent variable, and one or more explanatory variables")
    (#| line of best fit |# ("line of best fit" "lines of best fit") "a straight line that best represents the data on a scatter plot")
    (#| list |# ("list" "lists") "a data structure containing a sequence of values")
    (#| mathematical expression |# "expresión matemática" "un cálculo en aritmética")
    (#| mean, average |# ("mean" "average") "a representation of the center, or 'typical' value in a set of numbers, calculated as the sum of those numbers divided by the number of values.")
    (#| median |# "mediana" "el elemento intermedio de un conjunto de datos cuantitativos ordenados.")
    (#| method |# "method" "a function that is only associated with an instance of a datatype, which consumes inputs and produces an output based on that instance")
    (#| mode |# ("moda" "modas") "el valor (o valores) que ocurren con mayor frecuencia en un conjunto de datos")
    (#| name |# "nombre" "cómo nos referimos a una función o valor definido en un idioma (ejemplos: +, *, estrella, círculo)")
    (#| navigator |# "navigator" "in pair programming, the person who has their eyes on the screen helping the driver")
    (#| negative correlation |# "negative correlation" "relationship in which one variable increases as the other decreases, and vice versa")
    (#| normal, normal distribution |# ("normal" "normal distribution") "A normal distribution has a particular symmetric shape that bulges in the middle and tapers at the ends.")
    (#| nonlinear |# "nonlinear" "a pattern that is not a straight line when it is graphed")
    (#| number |# "number" "a data type representing a real number")
    (#| operator |# ("operador" "operadores") "un símbolo que manipula dos números y produce un resultado")
    (#| order |# ("order" "orders" "ordering") "An arrangement of data according to some pattern")
    (#| outlier |# ("valore atípico" "valores atípicos") "observaciones cuyos valores son muy diferentes a las otras observaciones del mismo grupo de datos, quizás debido a un error experimental. Los valores atípicos también pueden ser indicativos de datos pertenecientes a una población diferente del resto de las muestras establecidas.")
    (#| permutation |# ("permutation" "permutations") "the number of possible arrangements in a collection of items where the order of the selection matters (ABC and CBA would be considered different permutations)")
    (#| piecewise functions |# "funciones por trozos" "una función que calcula diferentes expresiones basadas en su entrada")
    (#| pie chart |# "gráfico circular" "Un gráfico donde el tamaño de cada sector circular corresponde a un valor en el conjunto de datos. Un recurso estadístico que se utiliza para representar porcentajes y proporciones")
    (#| pixel |# ("pixel" "pixels") "the smallest unit that makes up a digital image. The more pixels, the more detailed an image or video can appear.")
    (#| positive correlation |# "correlación positiva" " una relación en la que los valores de ambas variables tienden a aumentar juntos")
    (#| predictor |# "predictor" "a function which, given a value from one data set, tries to predict a related value in a different data set")
    (#| produce |# "producen" "para calcular un valor de una expresión")
    (#| programming language |# "lenguaje de programación" "un conjunto de reglas para escribir código que una computadora puede evaluar")
    (#| purpose statement |# "declaración de propósito" "una breve descripción de lo que hace una función")
    (#| quantitative data |# "datos cuantitativos" "datos con valores que miden alguna cantidad; puede no tener un número fijo de valores posibles")
    (#| quartiles |# "cuartiles" "valores que dividen una muestra de datos en cuatro partes iguales")
    (#| r-value |# ("r" "r-value") "a number between −1 and 1 that measures the direction and strength of a linear relationship between two quantitative variables (also known as correlation value)")
    (#| r-squared |# ("r-squared") "a number between 0 and 1 that measures the strength of association between two variables")
    (#| random samples |# ("random sample" "random samples") "a subset of individuals chosen from a larger set, such that each individual has the same probability of being chosen")
    (#| range |# "rango" "el tipo de datos que produce una función o la diferencia entre el valor más alto y el más bajo")
    (#| range of a dataset |# "range of a dataset" "the distance between minimum and maximum values")
    (#| rate |# "rate" "A comparison of two related quantities")
    (#| reactor |# "reactor" "A value that contains a current state, and functions for updating, drawing, and interacting with that state")
    (#| rectangular prism |# ("rectangular prism" "rectangular prisms") "a solid figure which has 6 faces, all of which are rectangular")
    (#| refactor |# ("refactor" "refactoring") "The process of changing the style or structure of a program's code, without changing the program's behavior")
    (#| rows |# ("fila" "filas") "elementos horizontales en una tabla, que consisten en algún grupo de valores; cada tabla es una colección de filas")
    (#| sample |# ("sample" "samples") "a set of individuals or objects collected or selected from a statistical population by a defined procedure")
    (#| sample instances |# "sample instances" "A collection of single instances, or also used to describe illustrative instances that we use to provide examples of a data structure")
    (#| scatter plot |# "gráfico de dispersión"  "Un gráfico donde los puntos se colocan en los ejes según pares de valores.")
    (#| select |# ("select" "selects" "selecting") "a query that creates a table containing only a subset of a specified table's columns")
    (#| shape |# "shape" "The aspect of a dataset that tells which values are more or less common")
    (#| sieve |# "sieve" "a table query that creates a table containing only rows that satisfy a boolean expression")
    (#| skew |# ("skew" "skewness") "lack of balance in a dataset’s shape, arising from more values that are unusually low or high. Such values tend to trail off, rather than be separated by a gap (as with outliers).")
    (#| skewed left |# ("skewed left" "skew left" "left skew") "A distribution is skewed left if there are a few values that are fairly low compared to the bulk of data values. A display of the data will show a longer tail to the left.")
    (#| skewed right |# ("skewed right" "skew right" "right skew") "A distribution is skewed right if there are a few values that are fairly high compared to the bulk of data values. A display of the data will show a longer tail to the right.")
    (#| slope |# "slope" "the steepness of a straight line on a graph")
    (#| spread |# "spread" "the extent to which values in a dataset vary, either from one another or from the center")
    (#| state |# "state" "The value of a changing system at any point in time (ie - a stoplight can be in the 'red', 'yellow' or 'green' state). In Pyret, the state of a Reactor is it's current value.")
    (#| statistical inference |# "statistical inference" "using information from a sample to draw conclusions about the larger population from which the sample was taken")
    (#| string |# ("cadena" "cadenas") "cualquier secuencia de caracteres entre comillas (ejemplos: \"hello\", \" 42\", \"esto es una cadena! \")")
    (#| surface area |# "surface area" "the sum of the areas of the faces of a polyhedron or the total area that the surface of a solid object occupies")
    (#| symmetric |# ("symmetric" "symmetric distribution") "A symmetric distribution has a balanced shape, showing that it's just as likely for the variable to take lower values as higher values.")
    (#| syntax |# "sintaxis" "El conjunto de reglas que define un lenguaje, ya sea que se hable, se escriba o se programe.")
    (#| syntax error |# ("syntax error" "syntax errors") "errors where the computer cannot make sense of the code (e.g. - missing commas, parentheses, unclosed strings)")
    (#| table |# ("tabla de datos") "una colección de datos organizados en filas y columnas.")
    (#| table plan |# "table plan" "A sequence of steps that helps people write code for several table queries, in order to solve a problem")
    (#| table query |# ("table query" "table queries") "An expression that consumes tables and creates a new table object")
    (#| threats to validity |# "threats to validity" "factors that can undermine the conclusion of a study")
    (#| union |# "union" "the set of values that makes either or both of a set of inequalities true")
    (#| unit test |# "unidad de prueba" "un ejemplo que muestra el uso de una función con un valor o valores específicos y la respuesta que debe producir")
    (#| value |# ("valor" "valores") "una pieza específica de datos, como 5 o \" hello \"")
    (#| variable |# "variable" "algo que cambia")
    (#| variable name |# "nombre de variable" "nombre de la información que puede ser diferente cada vez que se utiliza una función")
    (#| vertical axis |# "eje vertical" "El eje en un gráfico de dispersión que corre arriba y abajo")
    ))
