= Frederick Jones

++++
<style>
@import url("../../../lib/pioneers.css");
</style>
++++

[.posterImage]
@image{../images/frederick-jones.png}

[.name]
Frederick Jones

[.title]
Inventor, Entrepreneur

[.text]
Jones was a prolific early 20th century Black inventor who helped to revolutionize both the cinema and refrigeration industries. Born in Ohio, he was raised by a priest after his mom died when he was 9. Jones started working as a mechanic's helper at 16 and by 19 had built and driven several cars in racing exhibitions. After serving in France during WWI, he moved to Minnesota and began his study of electronics, eventually building a transmitter for a local radio station. He went on to earn over 60 patents, including an automatic movie ticket distribution machine, the first process that enabled movie projectors to play back recorded sound, a unit for storing blood serum for transfusions, and a refrigeration system for trucks that prevented food from spoiling during long cross-country drives. During the 1950s, he was a consultant to the U.S. Department of Defense and the U.S. Bureau of Standards.

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. FREE, research-driven, integrated Computer Science & Data Science modules for Math, Science, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
