= Grace Hopper

++++
<style>
@import url("../../../lib/pioneers.css");
</style>
++++

[.posterImage]
@image{../images/grace-hopper.png}

[.name]
Grace Hopper

[.title]
Computer Programmer, Inventor, Professor, US Navy Rear Admiral

[.text]
As a child, Hopper loved taking apart household goods and putting them back together again. Given her love of problem-solving, no one was surprised when she earned her Masters and PhD in mathematics from Yale, and then became a professor at Vassar. During WWII she joined the Navy WAVES (Women Accepted for Voluntary Emergency Service), where she worked on the Mark 1 - an early prototype of the very first electronic computer. While working on the Mark I, Hopper coined the word “bug” (apparently after a moth found its way into her computer) to describe a computer malfunction! Hopper devised the theory of machine-independent programming languages and managed the development of one the first COBOL compilers, converting English terms into machine code understood by computers. The COBOL programming language is still in use today!

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. FREE, research-driven, integrated Computer Science & Data Science modules for Math, Science, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
