= Guillermo Camarena

++++
<style>
/* hide/adjust template elements */
h1, #savetodrive-div, .acknowledgment { display: none !important; }
#content {
	margin: 0;
	padding: 0;
	height: 100% !important;
	position: absolute;
	text-align: center !important;
}

.posterImage {
	max-width: 		6.5in;
	border-radius: 	20px;
	border: 		20px solid black;
	display: 		inline-block;
}
.posterImage p { margin: 0; padding: 0; }
.posterImage img { width: 100%; max-width: 5.5in; }

.name p, .title p, .text p {
	font-weight: 	bold  !important;
	font-family: 	Helvetica  !important;
	width: 			100% !important;
	font-size:		10pt;
}
.name p  { font-size: 40pt !important; }
.title p { font-size: 16pt !important; }
.text p  { font-weight: normal !important; text-align: left; }

.footer img { float: right; width: 200px; }
.footer { font-size: 9pt; position: absolute; bottom: 0; background: white; }
</style>
++++

[.posterImage]
@image{../images/guillermo-camarena.png}

[.name]
GUILLERMO CAMARENA

[.title]
ELECTRICAL ENGINEER, INVENTOR

[.text]
In 1939, Guillermo Gonzalez Camarena independently developed the first Trichromatic Field Sequential System for color transmission for television, which was based on three colors - red, green and blue. He patented his color television system in 1940, at age 23. During his childhood in Mexico, Camarena loved to tinker and invent toys powered by electricity - including a radio transmitter at age 8 and a hobby radio at age 12. Camarena also loved music and folklore, and in fact composed his own songs. His best-known song is called "Rio Colorado," and the royalties he collected for it allowed him to develop his color TV system.

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. We offer FREE, research-driven, integrated Computer Science modules for Math, Physics, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
