= Jerry Lawson

++++
<style>
@import url("../../../lib/pioneers.css");
</style>
++++

[.posterImage]
@image{../images/jerry-lawson.png}

[.name]
Jerry Lawson

[.title]
Electronic Engineer, Video games

[.text]
Long before PlayStation, X-Box, and Wii hit the scene, Lawson made it possible to play video games at home! His first grade teacher in Brooklyn suggested that he could be the next George Washington Carver and he remembers thinking, "I want to be a scientist. I want to be something.”  As a teenager, he earned money repairing televisions, gained an amateur ham radio license and built his own station at home. In 1976, Lawson led the team of engineers that developed "The Fairchild Channel F," the first console with removable cartridges, allowing users to have a library of games. Lawson and Ron Jones were the sole Black members of the Homebrew Computer Club, a group of early computer hobbyists and entrepreneurs, including Apple Computer founders Steve Jobs and Steve Wozniak, that played an influential role in the development of the microcomputer revolution and the rise of that aspect of Silicon Valley.

[.footer]
--
@image{../images/EquityScaleRigor.png}

This poster is brought to you by Bootstrap as part of our “Pioneers in Computing and Mathematics” poster library. FREE, research-driven, integrated Computer Science & Data Science modules for Math, Science, Business and Social Studies classes, grades 5-12 at @link{https://www.BootstrapWorld.org, BootstrapWorld.org}.
--
