[.beta]
= Exploring Exponential Models

@description{Students investigate exponential relationships in data about Covid spread, using an inquiry-based model, involving hypothesizing, experimental and computational modeling, and sense-making. They are introduced to table transformations and inverse functions, which are used to fit exponential models onto nonlinear data.}

@lesson-prereqs{exploring-quadratic-models, lookups}

@keywords{exponential, quadratic, square, coefficient}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Read and interpret real-world data, presented in a scatter plot
* Recognize exponential growth in tables and graphs
* Model exponential relationships using functions


| Student-facing Lesson Goals
|

* Let's use Pyret to model exponential relationships in data
* Let's use Pyret to filter a dataset into subsets

| Materials
|[.materials-links]
@material-links

| Preparation
|
* All students should log into @online-exercise{program-list}.

|===

== Filtering {amp} Simpson's Paradox @duration{45 minutes}

=== Overview
Students explore the @starter-file{alg2-covid}, and discover that some scatter plots show __multiple__ correlations, instead of just one. This motivates a brief discussion of Simpson's Paradox, and teaches them to filter their dataset into grouped samples.

=== Launch
Starting in 2019, Covid spread across the globe. Most of us heard terms like "flatten the curve" and "infection rate" in videos and on the news.

Even in 2020, very few people could have predicted the impact it would have on the world. But Data Scientists who were looking at the data knew differently. Let's take a look at some of that data!

[.lesson-instruction]
- Open the @starter-file{alg2-covid}. This data looks at the Covid infection rates for New England states from summer 2020 until the end of the year.
- From the File menu, select "Save a Copy", and click "Run."
- Working in pairs or small groups, complete @printable-exercise{exploring-covid.adoc}.

@teacher{_Note: This dataset is @link{https://docs.google.com/spreadsheets/d/1T73KS2IUU1kkG1SY4Ac7EU9Lj-ev1U9vzM_txSYcUhE/, available for all 50 states (and Washington, D.C!)}, but for pedagogical purposes we've written the starter file to pull only data from New England._
}

@center{@image{images/multiple-models.png}}

[.lesson-instruction]
--
Discuss in groups or pairs, and prepare to share out to the class:

- Based on the look of the scatter plot you just made, do you think there's a strong correlation here?
- If we fit a curve or straight line to this data, do you think it would have a high @math{R^2}-value?
--

The scatterplot you made doesn't look much like a scatterplot all! It looks like someone took a marker and drew in five different curvy lines. While it's clear that there are strong patterns in the data, these patterns are so distinct from one another that there isn't really one, single model that fits them all. Each relationship appears very strong, almost as if there is _more than one model_ here.

@teacher{Review student answers to confirm that students have made a number of observations:

* There is _more than one_ relationship in this dataset
* Every relationship seems extremely strong
* Most/all relationships appear non-linear}

With all these clear, tight lines, we might think this would be a dataset with a very strong correlation. Unfortunately, that's not what we see when we group all the data together!

Datasets like these are impossible to model all at once, because there will always be lots of points that are far from any single function. But it's not that there's _no correlation_. Instead, we have several sub-groups each with their own _very strong correlations._

[.lesson-point]
Simpson's Paradox: visible trends in sub-groups _disappear_ or even _reverse_ when the groups are combined.

@right{@image{images/Simpsons_animation.gif, 300}}
Normally we think that "more data means more power!", and that the more data we include in our sample the more clearly we'll see any potential correlations. But in certain circumstances - like in our Covid dataset - the correlations in our sub-groups cancel each other out when we put the groups together. This is called Simpson's Paradox.

=== Investigate

[.lesson-instruction]
--
A travel agency wants to know whether they serve more people 35 and over, or travelers under 35. They looked at their booking records, grouped by city:

[cols="2a,^1a,^1a,^1a", options="header", width="80%"]
|===
| City  		| # Tourists 	| % 35 and over	| % Under 35
| Marrakesh		| 160			| 30%			|  70%
| Istanbul		| 200			| 20%			|  80%
| Punta Cana 	| 204			| 25%			|  75%
| Goa			| 450			| 46%			|  54%
| Sarasota		| 676			| 75%			|  25%
|===

// in the slide deck, we should show students the table without the Tourists column... then advance the slide, and include the Tourist column //

Which group do you think the agency serves more? Why?

@optional If your students need printed copies of this table, you can use @opt-printable-exercise{travel-data.adoc}.

--
@teacher{Have students discuss in pairs or small groups. Invite students to share their thoughts. Most likely they will say it's the under-35 crowd, because they are the bigger group in almost every city.}

**Most of the agency's clients are 35 and over!**

How is this possible? We can see a clear trend when _comparing_ within cities: the under-35 crowd dominates every city except Sarasota. When aggregating all of the data together, _the number of tourists in each city matters_. Sarasota was our outlier, but it also makes up the largest portion of all tourists!

We can see the same phenomenon in our Covid data. There is a strong relationship that we can clearly see _within_ each group, but that relationship is really weak when we lump all the groups together. (Learn more about Simpson's Paradox at @link{https://en.wikipedia.org/wiki/Simpson%27s_paradox, Wikipedia}.)

[.lesson-instruction]
- We need to break the Covid data up into _grouped samples_, so that all of the data for Rhode Island is in one table, all of the data for Maine is in another, etc.
- How is a grouped sample different from a random sample?
** _A grouped sample is a non-random subset chosen from a larger set. Grouped samples are non-random by design!_
- Working in pairs or small groups, complete @printable-exercise{filtering-by-state.adoc}.
- You just used the `filter` function. How does the `filter` function work?
** __The `filter` function consumes a Table and **a helper function!** The helper function is used on every Row of the Table, producing true or false. The `filter` function takes all the Rows for which the helper produced true, and combines them all into a new table.__

@teacher{@optional While filtering is introduced in this lesson, the primary goal is for students to explore exponential functions. If your students need more practice with filtering - or wish to filter their own datasets - we recommend checking out the @lesson-link{filtering-and-building} lesson.}


=== Common Misconceptions
It's extremely common for students to think that filtering a table _changes the original table_. This is NOT how it works in Pyret! Instead, the `filter` function always produces a _new_ table, containing only the Rows for which the supplied function evaluates to `true`.

=== Synthesize
- In what other situations would it be useful to filter a dataset?
- Can you think of other examples where Simpson's Paradox might arise?

** _When comparing one country's schools to another's, a researcher finds that students living in poverty in country A outperform students living in poverty in country B. They also find that the wealthy students in A outperform their wealthy peers in B. In fact, for every income level, country A outperforms country B! But if country B has less child poverty overall, it will still outperform A._
** _Another, thoroughly-explained example involving soft drinks can be found @link{https://towardsdatascience.com/simpsons-paradox-and-interpreting-data-6a0443516765, on this web page}._


== Looking for Patterns	@duration{45 minutes}

=== Overview

Students explore their newly-filtered `MA-table` dataset, trying to fit different kinds of models to it. This section makes heavy use of interactive slider activities we've built in Desmos to support open-ended experimentation.

=== Launch

[.lesson-instruction]
- Open the @starter-file{alg2-covid}.
- Make a scatter-plot showing the Covid infection rate for Massachusetts.
- What kind of model do you think would fit this best?

[.strategy-box, cols="1a", grid="none", stripes="none"]
|===

|
@span{.title}{Why just New England, starting from June 9th?!?}

We have _artificially constrained this dataset_, showing only the data from June 9th to December 26th, 2020. We've made this choice in order to showcase the most purely-exponential behavior of the infection curve, for the sake of this lessons' math learning goals.

For students who are farther along, we recommend showing them _all_ the data through 2020, starting in January rather than June. The first portion of the infection curve shows a gradual, linear growth pattern before exploding in the Fall of 2020. This is _polynomial_ behavior, where a linear term dominates when the exponential term is small.

Based on the strength of your students, we encourage you to choose the data that best fits your learning goals. You may also wish to return to full dataset later on, once students are comfortable with polynomial functions.

To use all available data, open the @starter-file{alg2-covid} and change the source sheet on line 7 from `"New England"` to `"All"`
|===


=== Investigate

[.lesson-instruction]
Complete @printable-exercise{linear-models.adoc}, using the first slide of @starter-file{alg2-covid-desmos}.

Linear models capture _straight-line relationships_, where one quantity varies proportionally based on another. In linear models, we expect the response variable to grow by equal amounts over equal intervals in the explanatory variable.

[.lesson-instruction]
Are linear models a good fit for this data? Why or why not?

@teacher{Have students share their resulting models. Which one fits best?}

@right{@image{images/MA-covid-linear.png, 300}} If we make the line go from the start to the peak of the curve, almost all of the points bulge out below our line of best fit. If we make the line hit the bottom of the curve, all the points fall above it. Splitting the difference (orange line) is better than both of those options, and we might even get a pretty good @math{R^2}! But ultimately, straight-line, linear models just don't behave like this curve, and we'll never get the _best-possible fit_ with them.  **It's growing too fast to be fit with a linear model that grows at a constant rate!**

[.lesson-instruction]
- Complete @printable-exercise{quadratic-models.adoc}, using the second slide of @starter-file{alg2-covid-desmos}.
- Are quadratic models a good fit for this data? Why or why not?

@teacher{Have students share their resulting models. Which one fits best?}

Quadratic models capture _parabolic relationships_, where one quantity varies based on the square of another. In quadratic models, we expect the response variable to grow by differing amounts over equal intervals in the explanatory variable.

@right{@image{images/MA-covid-quadratic.png, 300}} Quadratic models change their rate of growth over time, which definitely makes them a better fit for this data than linear ones. It's very likely we could find a quadratic model with a pretty good @math{R^2} value! But this data starts out almost flat and then suddenly takes off like a rocket - quadratic models just don't have that kind of explosive growth, so our model will never be as good as it _could_ be.

=== Synthesize

- Do you think the data for MA shows a linear relationship? Why or why not?
- Do you think this data shows a quadratic relationship? Why or why not?
- Do you think this data shows some other kind of relationship? Why or why not?

== Exponential Functions @duration{55 minutes}

=== Overview
Having identified that the Covid scatter plot is neither linear nor quadratic, students learn about characteristics of exponential functions in tabular, graphical, and function notation form.

=== Launch

++++
<style>
.growth td { padding: 0; }
</style>
++++

Let's review what we know about the behavior of the models we've seen so far:

[.growth, cols="15a,^.^5a", grid="none", frame="none", stripes="none"]
|===

| Remember that linear functions grow by _fixed intervals,_ so the rate of change is _constant_. In the table shown here, each time the x-value increases by 1, we see that the y-value increases by 2. This is true for any set of equal-sized intervals: a line needs to slope up or down at a constant rate in order to be a straight line! +
**If the "growth" is constant, the relationship is linear.**

| @image{images/difference-table-linear.png}

| Quadratic functions grow by intervals that _increase by fixed amounts!_ In the table to the right, the blue arrows show a differently-sized jump between identical intervals, meaning _the function is definitely not linear!_ However, if we take a look at the _difference between those differences_(shown in red), we're back to constant growth! + 
**If the "growth of the growth" is constant, the relationship is quadratic.**

| @image{images/difference-table-quadratic.png}

|===


There is, however, a class of functions that grows even faster than quadratics: @vocab{exponential functions}.


[.growth, cols="15a,^.^5a", grid="none", frame="none", stripes="none"]
|===

| If we try to calculate the growth between the y-values, we can immediately tell it's not linear. But then if we try to calculate the "growth of the growth", we see that it's not quadratic either. Even if we calculate the "growth of the __growth of the growth__" (shown in green)... we still haven't found a constant. In fact, each of these "growths" just repeats the original pattern of y-values! Something is making this function grow so fast that our attempt to calculate the rate of change fails to simplify anything.

| @image{images/difference-table-exponential-1.png}

| Exponential functions grow so rapidly that looking for "what is _added_ to y?" isn't helpful at all. The only way to talk about their growth is to start noticing "what is y being _multiplied_ by?"

*In this case, we can see that the y-values are doubling each time!*

|
@image{images/difference-table-exponential-2.png}
|===


[.lesson-instruction]
- Complete @printable-exercise{classifying-tables.adoc}
- Be ready to discuss your answers with the class!

=== Investigate

We generally write exponential functions like this: @math{f(x)=ab^x + k}. +
Let's explore what each coefficient means!

[.lesson-instruction]
Use the third slide of @starter-file{alg2-covid-desmos} to complete the first section ("base") of @printable-exercise{graphing-models.adoc}.

@teacher{
Review students answers, and then debrief via class discussion. Invite students to consider what new information they have gained by looking at graphical representations rather than tables.}

*The base of an exponential function (@math{b})* must *always be positive*, because exponential functions grow and decay uniformly. A negative @math{b} would bounce from one side of the y-axis to another. When raised to a fractional power, negative values of @math{b} might also lead to things like @math{\sqrt{-2}}!

[cols="^3a,^3a,^3a", stripes="none", options="header"]
|===
| Exponential Growth
| Flat
| Exponential Decay

| @image{images/growth.png, 150}
| @image{images/flat.png, 150}
| @image{images/decay.png, 150}

| @math{b > 1} +
When the base is *larger* than 1, the function starts out flat and then grows by the "percentage greater than 1". A base of 1.25 - or @math{(1 + 0.25)} - will grow by 25% each time @math{x} grows by 1. This percentage is called the @vocab{growth factor}, since it determines how quickly the function grows.

| @math{b = 1} +
When the base is equal to 1, the function stays flat without any growth of all (raising 1 to _any_ power will always produce 1!).

| @math{0 < b < 1} +
When the base is *smaller* than 1, the function shrinks by the "amount less than 1". A base of 0.25 - or @math{(1 - 0.75)} - will shrink by 75% each time @math{x} grows by 1. This percentage is called the @vocab{decay factor}, since it determines how quickly the function shrinks.
|===

[.lesson-instruction]
Use the third slide of @starter-file{alg2-covid-desmos} to complete the second section ("vertical shift") of @printable-exercise{graphing-models.adoc}.

An exponential function with a growth factor will always start close to a horizontal line, then gradually shoot up to ever-increasing values. An exponential function with a decay factor will drop quickly, then level out close to a horizontal line. This horizontal line is called an @vocab{asymptote}, and the equation of the line will always be @math{y = k}. 

*Adjusting @math{k} shifts the asymptote up and down*, along with the rest of the exponential curve that approaches it.

[.lesson-instruction]
Use the third slide of @starter-file{alg2-covid-desmos} to complete the last section ("initial value") of @printable-exercise{graphing-models.adoc}.

*The y-intercept appears _differently_ in exponential function definitions than in linear and quadratic definitions!*

* In both linear and quadratic functions, we could cross out the linear or quadratic term when @math{x = 0} (because anything multiplied by zero is zero) and the constant term being added or subtracted in the equation was our y-intercept. 
* But, because any value raised to the power of zero is 1, when @math{x = 0} in exponential equations, part of the exponential term _remains_, for example: @hspace{2em} @math{4(2^0) = 4(1) = 4}. 
* As a result, *the y-intercept of an exponential function is @math{a + k}*.
* When there is no @math{k}-term being added or subtracted, the coefficient @math{a} is the initial value where @math{x = 0}. 
* And, if @math{a} is "missing", the value of the coefficient is @math{1} (After all, @math{1(2^x) = 2^x}!). +
That means that if we don't see @math{a} or @math{k} in an exponential equation, the y-intercept of the function is 1.

@vocab{Exponential growth} and @vocab{exponential decay} show up all the time!

- Most cells (e.g. bacteria, the cells in a growing fetus, etc) divide every few hours, doubling the number of cells each time. A single cell will split into 2, those 2 cells will split to become 4, which will become 8, then 16, and so on.
- Unstable particles degrade into stable particles over time, emitting radiation as a biproduct. We use the term _half-life_ to refer to the length of time it takes for 50% of the particles in a sample to become stable, leaving behind the other half as radiation-emitting material.
- Money in a savings account grows by a certain percentage each year. 3% growth on $100 would turn into $103. The next year that would become $106.09. And the next year $109.27. Every year there's a little more money to grow. If you start saving early, the account will grow into quite a lot more money down the road.

@teacher{In the following two activities, students will decide whether various scenarios and definitions represent quadratic, linear, or exponential functions. They will also have opportunities to think about and apply their knowledge of growth, decay, initial value, and growth factor.}

[.lesson-instruction]
- Complete @printable-exercise{classifying-descriptions.adoc}.
- What strategies did you use to decide if a function was linear, quadratic, or exponential?
- What new insights did you gain about exponential functions by thinking about them in real-world scenarios?

@teacher{Have students share their answers, asking them to notice and wonder about the sequences for the exponential examples. How are these sequences growing or decaying? How is that growth or decay different from what they've seen before? }

[.lesson-instruction]
- Complete @printable-exercise{classifying-defs.adoc}.
- What strategies did you use to decide if a function was linear, quadratic, or exponential?
- What new insights did you gain about exponential functions by thinking about their definitions?

@teacher{As students discuss their answers, pay special attention to their use of vocabulary when describing the initial value and the growth factor.}

=== Synthesize

- You looked at several different representations of exponential functions: tables, graphs, descriptions, and equations.
- Which representation was the most useful for you? Why?
- Which representation was the least useful for you? Why?


== Fitting Exponential Models 	@duration{30 minutes}

=== Overview

Students extend their sampling techniques to exponential relationships. Students continue experimenting in Desmos, but eventually switch back to Pyret to formalize their understanding.

=== Launch

Now that you're familiar with exponential functions, let's use them to model this Covid data!

@teacher{Direct students to create a scatter plot showing the change in positive Covid cases for `MA-Table`. Then, support them in making educated guesses about the values of @math{a}, @math{b}, and @math{k}. Have students respond to the discussion questions below in pairs or small groups.}

[.lesson-instruction]
--
- Does your scatter plot show exponential growth or exponential decay?
** _The scatter plot shows growth. The "hockey stick" is pointing up, meaning that positive cases are increasing._
- Can we make any conclusions about the value of @math{b}? Explain.
** _Because we see exponential growth, we know that @math{b} must be greater than one._
- Can we make any conclusions about the value of @math{k}?
- Can we make any conclusions about the value of @math{a}? Explain.
** _@math{a} must be positive, because the curve is consistently above @math{k}._
--


=== Investigate

@teacher{In the next activity, students use Desmos to find promising exponential models, and then fit the model programmatically in Pyret!}

[.lesson-instruction]
- Open to the fourth slide of @starter-file{alg2-covid-desmos}, and complete @printable-exercise{exponential-models.adoc}.
- Is an exponential model a good fit for this data? Why or why not?

@star @optional Build models for _other states_. How do the coefficients differ from state to state? What differences between states could explain the different values of the coefficients?

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{Precision v. Efficiency in Computation}

On @printable-exercise{exponential-models.adoc} you'll see a note about the use of `~1` to tell Pyret to prioritize speed over precision. Unlike most calculators that students will engage with, Pyret usually prioiritizes precision.

In a math classroom, this is the difference between @math{\frac {2}{3}} rendering as @math{ 0.\overline{666}} or being rounded to 0.666666667.

In data processing, opting to round for speed over preserving precision can have ethical or technical consequences. For example:

1) When calculating a path over an extremely long distance, missing decimal places could result in the Mars Rover missing its destination.

2) For an extremely large population like China, rounding to 10 decimal places might result in discounting an entire subpopulation.

|===

=== Synthesize

- What makes exponential models different from the linear and quadratic models you've seen before?
- How would you describe the shape of the three models you've seen so far (Linear, Quadratic, and Exponential)?
- Is it always okay for Data Scientists to round off their numbers to speed up computation? Why or why not?


