[.beta]
= Exploring Exponential Models

@description{Students investigate exponential relationships in data about Covid spread, using an inquiry-based model of sense-making, hypothesizing, modeling and testing. They are introduced to table transformations and inverse functions, which are used to fit exponential models onto nonlinear data.}

@lesson-prereqs{exploring-quadratic-models}

@keywords{exponential, quadratic, square, coefficient}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Read and interpret real-world data, presented in a scatter plot
* Model exponential relationships using functions

| Student-facing Lesson Goals
|

* Let's use Pyret to model exponential relationships in data
* Let's use Pyret to filter a dataset into subsets

| Materials
|[.materials-links]
@material-links

| Preparation
|
* All students should log into @online-exercise{program-list}.

|===

== Filtering {amp} Simpson's Paradox

=== Overview
Students explore the @starter-file{alg2-covid}, and discover that some scatter plots show __multiple__ trends instead of just one! This motivates a brief discussion of Simpson's Paradox, and teaches them to filter their dataset into grouped samples.

=== Launch

Starting in 2019, Covid spread across the globe. Most of us heard terms like "flatten the curve" and "infection rate" more than we ever thought possible. Even in 2020, very few people could have predicted the impact it would have on the world.

But Data Scientists who were looking at the data knew differently. Let's take a look at some of that data!

[.lesson-instruction]
- Open the @starter-file{alg2-covid}. This data looks at the Covid infection rates for New England states from summer 2020 until the end of the year.
- From the File menu, select "Save a Copy", and click "Run"
- Working in pairs or small groups, complete @printable-exercise{exploring-covid.adoc}

@teacher{This dataset is @link{https://docs.google.com/spreadsheets/d/1T73KS2IUU1kkG1SY4Ac7EU9Lj-ev1U9vzM_txSYcUhE/, available for all 50 states (and Washington, D.C!)}, but for pedagogical purposes we've written the starter file to pull only data from New England.
}

@center{@image{images/multiple-models.png}}

The scatterplot we just produced doesn't look much like a scatterplot all! It looks like someone took a blue marker and drew in five different curvy lines. While it's clear that there are strong patterns in the data, these patterns are so distinct from one another that there isn't really one, single model that fits them all. Each relationship appears very strong, almost as if there is _more than one model_ here.

@teacher{Review student answers to confirm that students have made a number of observations:

* There is _more than one_ relationship in this dataset
* Every relationship seems extremely strong
* Most/all relationships appear non-linear}

=== Investigate

[.lesson-instruction]
--
Discuss in groups or pairs, and prepare to share out to the class:

- Based on the look of this scatter plot, do you think there's a strong correlation here?
- If we fit a model to this data, would it have a high @math{r}-value?
--

With all these clear, tight lines, we might think this would be a dataset with a very strong correlation. Unfortunately, that's not true at all.

Datasets like these are impossible to model all at once, because there will always be lots of points that are far from any single function. But it's not that there's _no correlation_. Instead, we have several sub-groups each with their own _very strong correlations._

[.lesson-point]
Simpson's Paradox: visible trends in sub-groups _disappear_ or even _reverse_ when the groups are combined.

@right{@image{images/Simpsons_animation.gif, 300}}
Normally we think that "more data means more power!", and that the more data we include in our sample the more clearly we'll see any potential correlations. But in certain circumstances - like in our Covid dataset - the correlations in our sub-groups cancel each other out when we put the groups together. This is called Simpson's Paradox, and you can @link{https://en.wikipedia.org/wiki/Simpson%27s_paradox, learn more at Wikipedia}.

**For Example:** School A and B both have basketball teams. The 6 foot kids on School A's team are better than the 6 foot kids on School B's team. The 5'10" kids from School A are also better than 5' 10" kids from School B. In fact, at every height, the kids from School A are better than the kids from School B. __But School B's team is better than School A.__

* How is this possible?
** School B has __more tall kids__ than School A!

[.lesson-instruction]
- We need to break this dataset up into _grouped samples_, so that all of the data for Rhode Island is in one table, all of the data for Maine is in another, etc.
- Working in pairs or small groups, complete @printable-exercise{filtering-by-state.adoc}.

@teacher{
The term "Grouped Samples" is used instead of "Random Samples". Grouped samples are non-random by design!
}

How does the `filter` function work?

__The `filter` function consumes a Table and **a helper function!** The helper function is used on every Row of the Table, producing true or false. The `filter` function takes all the Rows for which the helper produced true, and combines them all into a new table.__

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{More Practice with Filtering}

While filtering is introduced in this lesson, the primary goal is about exponential functions. If your students need more practice with filtering - or wish to filter their own datasets - we recommend checking out the @lesson-link{filtering-and-building} lesson.
|===


=== Common Misconceptions
It's extremely common for students to think that filtering a table _changes the original table_. This is NOT how it works in Pyret! Instead, the `filter` function always produces a _new_ table, containing only the Rows for which the supplied function evaluates to `true`.

=== Synthesize
- In what other situations would it be useful to filter a dataset?
- Can you think of other examples where Simpson's Paradox might arise?

** _When comparing one country's schools to another's, a researcher finds that poor students in country A outperform poor students in country B. They also find that the rich students in A outperform their wealthy peers in B. In fact, for every income level, A outperforms B! But if B has less child poverty overall, it will still outperform A._
** _Another, thoroughly-explained example involving soft drinks can be found @link{https://towardsdatascience.com/simpsons-paradox-and-interpreting-data-6a0443516765, on this web page}._


== Looking for Patterns

=== Overview

Students explore their newly-filtered `MA-table` dataset, trying to fit different kinds of models to it. This section makes heavy use of @link{https://www.Desmos.com, Desmos}, which is an excellent tool for open-ended experimentation.

=== Launch

[.lesson-instruction]
- Open @starter-file{alg2-covid}.
- Make a scatter-plot showing the Covid infection rate for Massachusetts.
- What kind of model do you think would fit this best?

[.strategy-box, cols="1a", grid="none", stripes="none"]
|===

|
@span{.title}{Why are we starting from June 9th?!?}

We have _artificially constrained this dataset_, showing only the data from June 9th to December 26th, 2020. We've made this choice in order to showcase the most purely-exponential behavior of the infection curve, for the sake of this lessons' math learning goals.

For students who are farther along, we recommend showing them _all_ the data through 2020, starting in January rather than June. The first portion of the infection curve shows a gradual, linear growth pattern before exploding in the Fall of 2020. This is _polynomial_ behavior, where a linear term dominates when the exponential term is small.

Based on the strength of your students, we encourage you to choose the data that best fits your learning goals. You may also wish to return to @link{https://docs.google.com/spreadsheets/d/1T73KS2IUU1kkG1SY4Ac7EU9Lj-ev1U9vzM_txSYcUhE/,the __full__ dataset} later on, once students are comfortable with polynomial functions.
|===


=== Investigate

[.lesson-instruction]
Complete @printable-exercise{linear-models.adoc}, using @starter-file{alg2-covid-desmos-l}.

Linear models capture _straight-line relationships_, where one quantity varies proportionally based on another. In linear models, we expect the response variable to grow by equal amounts over equal intervals in the explanatory variable.

[.lesson-instruction]
Class discussion: Are linear models a good fit for this data? Why or why not?

@teacher{Have students share their resulting models. Which one fits best?}

@right{@image{images/MA-covid-linear.png, 300}} If we make the line go from the start to the peak, almost all of the points bulge out below our line of best fit. If we make the line fit the bulge, all the points fall above it. We always have either too many points _below_ the line in the middle or to many point _above_ the line at the ends. **It's growing too fast to be fit with a linear model that grows at a constant rate!**

[.lesson-instruction]
Complete @printable-exercise{quadratic-models.adoc}, using @starter-file{alg2-covid-desmos-q}.

Quadratic models capture _parabolic relationships_, where one quantity varies based on the square of another. In quadratic models, we expect the response variable to grow by differing amounts over equal intervals in the explanatory variable.

[.lesson-instruction]
Class discussion: Are quadratic models a good fit for this data? Why or why not?

@teacher{Have students share their resulting models. Which one fits best?}

@right{@image{images/MA-covid-quadratic.png, 300}} Quadratic models change their rate of growth over time, which definitely makes them a better fit for this data than linear ones. But they still don't have the explosive growth we need to model this data, which starts out incredibly slow and then suddenly takes off like a rocket.

=== Synthesize

- Do you think the data for MA shows a linear relationship? Why or why not?
- Do you think this data shows a quadratic relationship? Why or why not?
- Do you think this data shows some other kind of relationship? Why or why not?

== Exponential Functions

=== Overview
Having identified that the covid scatter plot is neither linear nor quadratic, students learn about characteristics of exponential functions in graphical, tabular, and function notation form.

=== Launch
We can rule out linear and quadratic functions for this pattern. None of them exhibit the behavior of growing really slowly for a while, and then taking off like a rocket.

- Linear functions grow by fixed intervals. That means they don't grow very quickly, and they grow at the same (slow) speed regardless of the value of x.
- Quadratic relationships grow by intervals that increase...by fixed amounts. That means they grow faster and faster as x increases, but the _rate_ that growth is fixed.

There is, however, a class of functions that grow even faster than quadratics: @vocab{exponential functions}.

[.lesson-instruction]
- Open @starter-file{alg2-exploring-exponentials} in Desmos.
- Use Desmos to complete @printable-exercise{graphing-models.adoc}.

@teacher{
Review students answers, focusing on the following takeaways:

- Vertical shift (@math{k}) refers to the point where the line levels out. Adjusting this value shifts the curve up and down.
- Base (@math{b}) must be positive (!), and determines whether the function growth is positive (@math{b > 1}), flat (@math{b = 1}), or negative (@math{b < 1}).
}

[.lesson-point]
--
Exponential functions grow by equal *factors*, (multiplying by _n_ each time).
--

- When @math{b > 1}, this growth is _positive_. A base of 2 means _y_ will double for every increment of _x_. This is called @vocab{exponential growth}.
- When @math{b < 1}, this growth is _negative_. A base of 0.5 means _y_ will drop by half for every increment of _x_. This is called @vocab{exponential decay}.

Exponential growth and decay show up all the time!

- Most cells (e.g. - bacteria, the cells in a growing fetus, etc) divide every few hours, doubling the number of cells each time. A single cell will turn into 2, then those 2 will turn into 4, then 8, then 16, and so on.
- Unstable particles degrade into stable particles over time, emitting radiation as a biproduct. We use the term _half-life_ to refer to the length of time it takes for 50% of the particles in a sample to become stable, leaving behind the other half as radiation-emitting material.
- Money in a savings account grows by a certain percentage each year, meaning every year there's that much more money to grow. If you start saving just a few dollars every month, the account will start growing so quickly that you'll have a lot of money down the road.


[.lesson-instruction]
- Complete @printable-exercise{classifying-descriptions.adoc}
- Be ready to discuss your answers with the class!

@teacher{Have students share their answers, asking them to notice and wonder about the sequences for the exponential examples. How are these sequences growing or decaying? How is that growth or decay different from what they've seen before?}

=== Investigate
You've identified one exponential pattern in a graph: it grows really slowly for a while, then explodes sharply upward. Can you tell the difference between linear, quadratic, and exponential graphs?

[.lesson-instruction]
- Complete @printable-exercise{classifying-plots.adoc}
- Be ready to discuss your answers with the class!

@teacher{Have students share their answers. Encourage them to talk about where the exponential functions suddenly shoot up, asking them to identify the approximate x-value where that occurs.}

Since exponential sequences grow by equal factors, the rate of growth gets bigger and bigger by equal leaps (e.g. - doubling each time, tripling each time, etc). Can you tell the difference between linear, quadratic, and exponential growth of a sequence?

[.lesson-instruction]
- Complete @printable-exercise{classifying-tables.adoc}
- Be ready to discuss your answers with the class!

@teacher{Have students share their answers. For exponential functions, it's especially important to have students discuss whether the function is doubling, tripling, etc. This foreshadows the idea of a _growth factor_ for exponential relationships.}

[.lesson-point]
Exponential models have the form @math{y = ab^x + k}

- The term @math{b} specifies the _growth factor_ for the function. This is the term you found for the exponential sequences on @printable-exercise{classifying-tables.adoc}.

- The term @math{a} is the _initial value_, which is the value of the function when @math{x=0}. Looking back at the the exponential relationships on @printable-exercise{classifying-tables.adoc}, what was the initial value - @math{a} - for each one?

- The term @math{k} is something we've seen before: it's the _vertical shift_ of the function, which moves the curve up or down.

[.lesson-instruction]
- Complete @printable-exercise{classifying-defs.adoc}
- Be ready to discuss your answers with the class!

@teacher{Have students share their answers. Pay special attention to their use of vocabulary when describing the initial value and the growth factor.}

=== Synthesize

Can you think of other examples of exponential relationships?

== Fitting Exponential Models

=== Overview

Students extend their sampling techniques to exponential relationships. Students continue experimenting in Desmos, but eventually switch back to Pyret to formalize their understanding.

=== Launch
Now that you're familiar with exponential functions, let's use them to model this covid data!

[.lesson-instruction]
--
- Make a scatter plot showing the change in positive covid cases for `MA-Table`
- Discuss in pairs or groups: Can we make any educated guesses about the values of @math{a}, @math{b} and @math{k}?
--

* Is this showing exponential growth or decay?
** Growth, because the "hockey stick" is pointing up (positive cases is _increasing_)
* What does that tell us about @math{b}?
** It has to be greater than 1
* Is our value of @math{a} positive or negative?
** Positive
* How do you know?
** The line is consistently above @math{k}

=== Investigate

[.lesson-instruction]
- Complete @printable-exercise{exponential-models.adoc}.
- Class discussion: Are exponential models a good fit for this data? Why or why not?

@star @optional build models for _other states_. How do the coefficients differ from state to state? What differences between states could explain the different values of the coefficients?

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{Precision v. Efficiency in Computation}

On @printable-exercise{exponential-models.adoc} you'll see a note about the use of `~1` to tell Pyret to prioritize speed over precision. Unlike most calculators that students will engage with, Pyret usually prioiritizes precision.

In a math classroom, this is the difference between @math{\frac {2}{3}} rendering as @math{ 0.\overline{666}} or being rounded to 0.666666667.

In data processing, opting to round for speed over preserving precision can have ethical or technical consequences. For example:

1) When calculating a path over an extremely long distance, missing decimal places could result in the Mars Rover missing its destination.

2) For an extremely large population like China, rounding to 10 decimal places might result in discounting an entire subpopulation.

|===

=== Synthesize

- What makes exponential models different from the linear and quadratic models you've seen before?
- How would you describe the shape of the three models you've seen so far (Linear, Quadratic, and Exponential)?
- Is it always ok for Data Scientists to round off their numbers to speed up computation? Why or why not?

////
== Additional Exercises

- @opt-printable-exercise{grading-models.adoc}
////
