name: Deploy Fall Materials
on:
  schedule:
    # run at minute 0, hour 0, on the 15th of June
    # ? means "ignore the day of the week"
    - cron: 0 0 15 JUN ?

jobs:
  create_issue:
    name: Deploy Fall Materials
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Deploy Fall Materials
          ASSIGNEES: schanzer
          LABELS: Infrastructure
          BODY: Do some testing of slide images and links

          PINNED: false
          CLOSE_PREVIOUS: false
