= Advanced Displays
++++
<style>
body code { line-height: 16px !important; }
</style>
++++
== Functions as Data

**You've learned that functions are __machines that consume and produce data__.** +

- In the real world, we see machines consume things to produce things all the time:
  * bulbs consume electricity and produce light
  * toasters consume bread and produce toast
- **Sometimes, machines consume other machines:**
  * the stereo from your car could be swapped out for a new one with more features. Each stereo is a machine!
  * a blender or kitchen mixer might have different attachments. Each attachment is a machine of its own!

This is true of function machines in math and programming, as well!
By now you've learned plenty of data types (e.g. - Numbers, Strings, Images, Booleans, Rows and Tables).

@vspace{1ex}

**Functions can be their own kind of data type!**

- Imagine a function `species-dot`, that consumes a Row from the Animals Dataset, and produces a different-colored square depending on the species.
- What if we used `species-dot` to customize the dots on our scatterplot, instead of using the same blue dot for each animal? +
@hspace{1em} __In this example, we'd be using the `species-dot` function as an input to our `scatter-plot` function!__

Here are the Contracts for some special display **functions that consume functions**, including the scatterplot we just described:

@vspace{1ex}

@indented{
@show{(contracts
  '("image-scatter-plot" ("Table" "String" "String" "(Row -> Image)") "Image")
  '("image-histogram" ("Table" "String" "Number" "(Row -> Image)") "Image")
  '("image-bar-chart" ("Table" "String" "(Row -> Image)") "Image")
  '("image-pie-chart" ("Table" "String" "(Row -> Image)") "Image")
)}
}

Look carefully at the last argument in each Domain. In each case, **the function consumes a Row and produces an Image**.

== Piecewise Functions

Functions always apply a particular rule to their input. +

- In an earlier lesson, you saw how `gt` always draws a solid, green triangle using the input as the size.
- In the `species-dot` example above, there's no single rule that will generate a different color for each species. +

**We need a way for functions to change rules, depending on their input.**

@vspace{1ex}

**Piecewise Functions** are functions that can behave one way for part of their Domain, and another way for a different part.

- Piecewise functions are divided into "pieces".
- Each piece has two parts: the "if" and the "then".
- This tells the computer _when_ to apply each rule, and _what_ the rule is.

In our `species-dot` example, our function might draw black squares when the input is a dog, but orange squares when the input is a cat.  +
The function definition would look like this:

[.indentedpara]
--
```
# species-dot :: (Row) -> Image
fun species-dot(r):
  if      (r["species"] == "dog"):       square(5, "solid", "black")
  else if (r["species"] == "cat"):       square(5, "solid", "orange")
  else if (r["species"] == "rabbit"):    square(5, "solid", "pink")
  else if (r["species"] == "tarantula"): square(5, "solid", "red")
  else if (r["species"] == "lizard"):    square(5, "solid", "green")
  end
end
```
--
