= species-tag
++++
<style>
/* Push content to the top (instead of the default vertical distribution), which was leaving empty space at the top. */
#content { display: block !important; }
</style>
++++

@include{fragments/baby-dr-styling.adoc}

_To help you with this page, we've re-printed the Contract for the `text` function, and an example of how to use it._ 

(Remember, you can always refer to the @dist-link{Contracts.shtml, Contracts Pages}. @pathway-only{_If you're working with a printed workbook, they are included in the back._})

@vspace{2ex}

@show{(contract 'text '((message String) (size Number) (color String)) "Image")}

@show{(code '(text "hello" 24 "green"))}


@n On the three lines below, write the code to lookup the value of the `species` column from `dog-row`, `old-row`, and `young-row`.

@fitb{}{@ifsoln{`dog-row["species"]`}}

@fitb{}{@ifsoln{`old-row["species"]`}}

@fitb{}{@ifsoln{`young-row["species"]`}}


@n On the three lines below, write the code that uses the `text` function to show the species of those same three rows in _red, 15px letters_.

@fitb{}{@ifsoln{`text(dog-row["species"], 15, "red")`}}

@fitb{}{@ifsoln{`text(old-row["species"], 15, "red")`}}

@fitb{}{@ifsoln{`text(young-row["species"], 15, "red")`}}

@n Check with your partner or another student. Do you have the same code? Why or why not?

[.big]
@center{_Instead of writing this out over and over for each animal, let's define a function to do it for us!_}

== Defining the Function

@design-recipe-exercise{ "species-tag"
"Define a function called `species-tag`, which takes in a row from the Animals Table and draws its name in red, 15px letters. _HINT: Use of the rows from above in your examples!_"
#:assess-design-recipe #f
#:headless? #t
#:show-funname-contract? #t
#:domain-list '(Row)
#:show-domains? #t
#:range "Image"
#:show-range? #t
#:purpose "Consumes an animal Row, and draws the species of the animal in red, 15px letters."
#:show-purpose? #f
#:num-examples 2
#:example-list '((dog-row "text(dog-row[\"species\"], 15, \"red\")")
                 (old-row "text(old-row[\"species\"], 15, \"red\")"))
#:show-examples '(#f #f)
#:param-list '(r)
#:show-funname-defn? #t
#:show-params? #f
#:body "text(r[\"species\"], 15, \"red\")"
#:show-body? #f
#:grid-lines? #f
}
