++++
<style>
body {
	border: solid 1px blue;
	margin: auto;
	width: 8.5in;
	height: 11in;
}
#content { padding: 0; width: 7.5in; height: 10in; margin: auto !important}
#footer, .acknowledgment { display: none; }
em, strong { margin: 0 !important; }
h1 { text-align: center; width: 100%;}
h1:before {
	content: url('../../images/Logo with Text.png');
 	display: block;
}
h2 { background: none !important; color: black  !important; font-size: 1em  !important; }
p { font-size: 0.8rem !important; }
table { order-collapse: separate; border-spacing: 0 5px; border: none !important; }
table tr:nth-child(1) { background: lightgreen; }
table tr:nth-child(2) { background: lightblue; }
table tr:nth-child(3) { background: lightyellow; }
table tr:nth-child(4) { background: orange; }
table tr td { padding: 5px; border: none !important; }

.funders img { height: 35px; margin: 5px 10px; }
</style>
++++
= Materials for Teachers using Connected Mathematics (Grade 6)

Like CMP3, Bootstrap is field-tested and research-validated, with a focus on deep exploration that supports and engages all kinds of learners.  Our integrated computing modules have been proven to support math transfer and can be mixed and matched to supplement what you’re already doing in your classroom.

[cols="1a,7a", stripes="none"]
|===
| *CMP Unit*
| *Bootstrap’s Integrated Computing Lessons that can extend the CMP3 Unit*



| *Prime Time:* +
 _Factors & Multiples_

| @span{.right}{@image{../../images/circle.png, "", 65}}
 *Order of Operations* +
Instead of a list of rules to memorize, we use the Circles of Evaluation to expose the structure of the math involved in evaluating expressions. Check it out! It’s a powerful tool.
@vspace{1ex}
_Circles of Evaluation can be used without any programming!_



| *Covering & Surrounding:* +
 _2-Dimensional Measurement_
| @span{.right}{@image{../../images/shapes.png, "", 100}}

*Making Shapes from Code*

- Get your students coding with highly motivational image functions!
- Writing simple code to build a wide range of shapes of different colors and sizes, reinforces vocabulary for describing polygons.
- While this lesson does not focus on area and perimeter, for those looking to extend beyond the scope of the CMP unit, the function composition lesson offers an intuitive low threshold high ceiling introduction to transformations.

*Surface Area of a Rectangular Prism*
@span{.right}{@image{../../images/surface-area.png, "", 250}}

- This lesson engages students in identifying the relevant dimensions for finding the area of each of the faces of the prism, generating a printable set of rectangles, labeled with their dimensions, from which students physically construct paper models of their own prisms and calculate the surface area.
- Ultimately, students can use their model to generate a formula for calculating the surface area of a prism.



| *Data About Us:* +
_Statistics and Data Analysis_

| @span{.right}{@image{../../images/boxplot.png, "", 150}}
*Measures of Center*
Simple code returns the mean, median, and mode(s) for any real world dataset, allowing for meaningful conversations about why we have to think carefully about which measure of center best represents a given dataset.

*Spread of a Dataset*
Simple code generates 5 number summaries, box plots and/or histograms for any dataset, connecting this generally abstract concept to real world analysis.
|===

Excited to learn more? @link{http://bootstrapworld.org/materials/, Our materials} are free of charge. And we love training teachers to use them! @link{https://www.bootstrapworld.org/workshops/index.shtml, Sign up for a workshop} today!

@vspace{1ex}

== Created with partial support from:
[.funders]
--
@image{../../../../lib/images/nsf.png}
@image{../../../../lib/images/google.png}
@image{../../../../lib/images/janest.png}
@image{../../../../lib/images/microsoft.png}
@image{../../../../lib/images/bloomberg.png}
@image{../../../../lib/images/infosys.png}
--
