= Video Game Project

++++
<style>
h3 { margin-top: 3ex; }
.autonum:after { content: '.'; }
</style>
++++

@comment{
--
*THIS DESCRIPTION IS FOR THE MOUSE OVER TEXT ON THE BUTTON*
@description{Students build a videogame of their own design! Every game must have a player (their avatar), a danger (something to avoid), and a target (something to chase). Students build their world using function composition, animate their characters through linear functions, detect boundaries with compound inequalities, and detect collisions with the distance formula. This project can be extended into more complex movement (quadratic, exponential, trigonometric) and "cheat codes".}
--
}

@link{video-game-rubric.html, Project Rubric}

This Project is the capstone project of Bootstrap:Algebra and provides students with a lot of concrete answers to the question, *"When am I ever going to use this?!"*

Coordinates, scale factors, inequalities, functions, the distance formula, and piecewise functions are all really useful when you're making a video game!

== The process of Making a Video Game

All of the steps for completing this project have been integrated into Bootstrap lessons.

* If you follow the lesson order for Bootstrap:Algebra, students will work on pieces of this project throughout.

* Some teachers choose to save this project for the end, whether because that makes access to computers easier or because they love taking advantage of high student engagement at a particularly tricky of the school year.  _If students are already comfortable with algebra (including the Pythagorean Theorem), Circles of Evaluation, Simple Datatypes, Contracts, and Functions, they'll be able to complete their video games in about a week._

=== Breaking it into Bite-sized Pieces
As outlined below, the large body of code in the @starter-file{game} is broken into sections, each of which corresponds to a lesson with scaffolded activities that conclude with editing a section of the game code.

Students work in pairs to edit the code to get their game working and make it their own.


[cols="1a, 1a, 1a" options="header", stripes="none"]
|===
| *Game Section:*	| *Corresponding Lesson:* | *Scaffolded Pages*
| @n Game title
|
@link{../../../../lessons/coordinates, Coordinates and Game Design}
@link{../../../../lessons/making-game-images, Making Game Images}
| @link{../../../../lessons/coordinates/pages/BrainstormGame.adoc, Brainstorm Your Videogame}

| @n Making the Danger and the Target Move:
| @link{.../lessons/functions-for-character-animation, Functions for Character Animation}

| @ifproglang{pyret}{@link{../../../../lessons/functions-for-character-animation/pages/character-animation-dr.html, Target and Danger Movement}} @ifproglang{wescheme}{@link{../../../../lessons/functions-for-character-animation-wescheme/pages/character-animation-dr.html, Target and Danger Movement}}

| @n Making the Danger and the Target Come Back Again:
| @link{../../../../lessons/inequalities3-sam, Sam the Butterfly - Applying Inequalities}
|
* @ifproglang{pyret}{@link{../../../../lessons/inequalities3-sam/pages/left-and-right.html, Left and Right}} @ifproglang{wescheme}{@link{../../../../lessons/inequalities3-sam-wescheme/pages/left-and-right.html, Left and Right}}

* @ifproglang{pyret}{@link{../../../../lessons/inequalities3-sam/pages/onscreen.html, is-onscreen}} @ifproglang{wescheme}{@link{../../../../lessons/inequalities3-sam-wescheme/pages/onscreen.html, onscreen?}}

| @n Get our Player moving!
| @ifproglang{pyret}{@link{../../../../lessons/player-animation, Player Animation}} @ifproglang{wescheme}{@link{../../../../lessons/player-animation-weschene, Player Animation}}
| @ifproglang{pyret}{@link{../../../../lessons/player-animation/pages/update-player.html, update-player}} @ifproglang{wescheme}{@link{../../../../lessons/player-animation-wescheme/pages/update-player.html, update-player}}

| @n Collisions:
| @ifproglang{pyret}{@link{../../../../lessons/inequalities-collision, Collision Detection - Distance and Inequality}} @ifproglang{wescheme}{@link{../../../../lessons/inequalities-collision-wescheme, Collision Detection - Distance and Inequality}}

| @ifproglang{pyret}{@link{../../../../lessons/inequalities-collision/pages/collide.html, Collision Detection}} @ifproglang{wescheme}{@link{../../../../lessons/inequalities-collision-wescheme/pages/collide.html, Collision Detection}}
|===

=== Students will be able to...

* recognize meaningful applications of inequalities, functions, and the distance formula, answering the all important questions, "When will I ever use...?!"
* express their creativity through the design of a game context
* take pride in having coded their first video game!
* share their completed videogame with friends and family to play!
