[.beta]
= Exploring Quadratic Models

@description{Students investigate quadratic relationships in data about Fuel Efficiency, using an inquiry-based model, involving hypothesizing, experimental and computational modeling, and sense-making.}

@lesson-prereqs{exploring-linear-models}

@keywords{quadratic, square, coefficient}

[@lesson-intro-table]
|===

| Lesson Goals
| Students will be able to...

* Read and interpret real-world data, presented in a scatter plot
* Model quadratic relationships using functions

| Student-facing Lesson Goals
|

* Let's use Pyret to model quadratic relationships in data


| Materials
|[.materials-links]
@material-links

| Preparation
|
* All students should pull up their @online-exercise{program-list} and, open the @starter-file{alg2-fuel-efficiency}.

| Key Points For The Facilitator
|
* Unlike linear functions, which are governed by slope and y-intercept, quadratic functions are governed by the bevahior of _three_ factors.
* Students should gain an intuition for these factors by playing with them first in Desmos, then use them to fit a model in Pyret.
|===

== Looking for Patterns @duration{45 minutes}

=== Overview
Students explore the @starter-file{alg2-fuel-efficiency}, and create scatter plots to search for relationships between columns. They share and discuss their findings with the class, discovering the limitations of linear models.

=== Launch

The questions below are intended to spark student interest in _fuel efficiency_, which students will explore in this lesson.

[.lesson-instruction]
- Since 1992, there have been laws about what information must be printed onto the labels of cars for sale. What do you think consumers should know about cars they are considering buying?
- Have you heard the term "fuel efficiency" before? What do you know about fuel efficiency?
** _Fuel efficiency is the number of miles that a car can travel per gallon. Since 2013, labels on cars for sale must include: fuel efficiency, energy use, fuel cost, and environmental impact._
- What factors influence fuel efficiency?
** _Possible responses: Efficient driving (e.g., gradual acceleration and braking, using cruise control), car maintenance, planning / combining trips, choosing a more fuel efficient vehicle, avoiding carrying excess weight in a vehicle._
- Do you think the speed at which you drive influences fuel efficiency? Why or why not?
- At what speeds do you predict that fuel efficiency is the best? The worst?
** _Invite students to share and explain their responses._

In this lesson, we'll learn more about the relationship between fuel efficiency and the speed a car is travelling. First, we'll explore a dataset and see if this relationship is linear.

[.lesson-instruction]
- Open the @starter-file{alg2-fuel-efficiency}
- From the File menu, select "Save a Copy", and click "Run".
- Working in pairs or small groups, complete the first section of @printable-exercise{pages/exploring-mpg.adoc}.

=== Investigate

@center{@image{images/fuel-efficiency-quadratic.png}}

There's definitely a relationship here. But we know that the best-possible linear model isn't very good!

[cols="^.^1a,^.^1a,^.^1a", frame="none", stripes="none"]
|===
| We could build linear models that fit the increasing half of the data...
| We could build linear models that fit the decreasing half of the data...
| We could build linear models that try to split the difference...

| @image{images/fuel-efficiency-linear1.png}
| @image{images/fuel-efficiency-linear2.png}
| @image{images/fuel-efficiency-linear3.png}
|===

...but all of them are so far away from so many points, and our @vocab{R&sup2;} is pretty bad.

[.lesson-instruction]
- Complete the rest of @printable-exercise{pages/exploring-mpg.adoc}. Be ready to share back and describe the curve you drew.
- When you're driving, what speed will save you the most money on gas?

Even though some cars are more efficient than others, fuel efficiency generally increases from 15mph to around 40-55mph. After that, fuel efficiency _decreases!_

@teacher{Review student answers to confirm that students see a _nonlinear_ relationship in the dataset with a relatively strong correlation. Students should generally agree that the relationship is better fit by a curve, with efficiency peaking _roughly_ at 45mpg.  **Make sure students have agreed on this vertex**, as its location is important for the next activity!

Have students share their curves, encouraging them to identify where they "peak" and where they cross the x-axis. These locations will be important anchor concepts on which to build in the next section. (One option for facilitating sharing is to project the scatter plot on a whiteboard and have students come up and draw all of their curves on it).
}

=== Synthesize

- Why don't linear models work to model the relationship between fuel efficiency and speed?
- What kinds of curves did you draw that fit better?
- Are there any mathematical functions that look like those curves?

== Quadratic Functions @duration{45 minutes}

=== Overview
Students are introduced to quadratic functions. They become familiar with scenarios involving quadratics and terminology to describe parabolas. They also learn how to identify quadratic sequences, and then explore each of the coefficients in Vertex Form.

=== Launch
Linear models are great for fitting simple relationships. But the real world isn't so simple, and _linear models are often just too primitive_ to handle that complexity.

Relationships like the one in the fuel efficiency scatter plot are best described by a _curve_. Today, we will learn about one kind of curved model called a quadratic model.  Graphs of quadratic relationships are often described as "u-shaped" or "looking like an arch". More formally, mathematicians and data scientists call these kinds of curves @vocab{parabolas}.

We observed what appeared to be a @vocab{quadratic relationship} between speed and fuel efficiency, where fuel-efficiency increased up to a certain speed, then decreased again.

There are lots of relationships that change direction like this! For example, when an athlete is young, they improve as they get stronger and more skilled. But as they age, they begin to lose their speed and strength.

In some relationships, the curve goes the other way - decreasing, bottoming out, and then beginning to rise again, like the height of a bird catching a fish at the surface of the ocean and flying away with it.

[.lesson-instruction]
* Can you think of any other real-world relationships that quadratic functions might do a good job of modeling?
** _A ball dropped from a tall building will get faster and faster as it falls._
** _Many nutrients are good for you, and the more you take the healthier you are...up to a point. After that, too much of a mineral or vitamin can cause problems._
** _A ball thrown in the air will rise quickly, slow down, peak, and then begin to fall._
** _The temperature of a puddle will warm and then cool over the course of the day._
** _The length of a shadow is long in the morning and shortens til the sun is overhead, after which it slowly lengthens til the sun sets._
* Turn to @printable-exercise{classifying-descriptions.adoc} and practice identifying whether the scenarios are best modeled ny linear or quadratic relationships.

=== Investigate
Although the examples we just discussed include the characteristic rising and falling or falling and rising of the parabola, we might encounter datasets that include only the _rising_ part of the parabola or only the _falling_ part.

But what if we only have a list of x-y pairs showing only one part of the parabola? +
**How can we identify quadratic relationships from a sequence of numbers?**

@right{@image{images/difference-table-linear.png}} Remember that linear functions grow by _fixed intervals,_ so the rate of change is _constant_. In the table shown here, each time the x-value increased by 1, we saw that the y-value increased by 2. This is true for any set of equal-sized intervals: a line needs to slope up or down at a constant rate in order to be a straight line! +
@vspace{1ex} +
**If the rate of growth is constant, the relationship is linear.**

@clear

@right{@image{images/difference-table-quadratic.png}} Quadratic functions grow by intervals that _increase by fixed amounts!_ In the table to the right, the blue arrows show a differently-sized jump between identical intervals time, meaning _the function is definitely not linear!_ However, if we take look at the _difference between those differences_(shown in red), we're back to constant growth! +
@vspace{1ex} +
**If the "growth of the growth" is constant, the relationship is quadratic.**

@clear

[.lesson-instruction]
--
Turn to @printable-exercise{classifying-tables.adoc}. One of the first two tables (below) shows a linear progression, while the other shows a quadratic progression.

[cols="^.^1a,^.^15a", frame="none", stripes="none"]
|===
| @n
|
[.sideways-pyret-table]
!===
! x !  0 ! 1 ! 2  !  3 !  4 ! 5  ! 6
! y !  5 ! 6 ! 9  ! 14 ! 21 ! 24 ! 27
!===

| @n
|
[.sideways-pyret-table]
!===
! x !  0 ! 1 ! 2  ! 3 !  4 ! 5  ! 6
! y !  0 ! 3 ! 6  ! 9 ! 12 ! 15 ! 18
!===
|===

- Which table is quadratic? Which one is linear? What do you Notice? What do you Wonder?
** _The first table is quadratic, and the second table is linear. Invite students to share their Noticings and Wonderings._
- Identify whether each of the remaining tables on @printable-exercise{classifying-tables.adoc} is quadratic, linear or neither.
- Use the space to the right of the table to show any computations or work that you deem useful.
--

@teacher{Debrief with students and allow them to share the different strategies that they used. Note: When looking at real-world datasets that can be modeled by linear or quadratic functions, these patterns will not be evident in the tables, becuase the points won't fit the function perfectly!}

When we graph these points on a plane, they draw our @vocab{parabola}. As we work with parabolas - and eventually fit them to our Fuel Efficiency dataset - we need to know how to talk about and describe them. *Let's define the parts of a parabola together.*

[.lesson-instruction]
- Linear relationships can be described with terms like "slope" and "y-intercept". But what about quadratic relationships? Do parabolas have slope?
** _No. They curve because they *do not* have a constant rate of change._
- Do all parabolas have y-intercepts?
** _No. Some do and some don't!_
- Can you point out or describe other important parts of a parabola?
** _Even without knowing the names for these things, students might point to the vertex, the axis of symmetry, etc._

@teacher{Invite students to share what they know or can infer about a parabola's parts. If needed, provide the definitions on the table below, which refer to specific points on a parabola.}

[cols="^.^3a,^.^3a,^.^3a", options="header", stripes="none"]
|===

| Vertex

| y-intercept

| x-intercept

| @image{images/opens.png, 250}

| @image{images/y-intercept.png, 200}

| @image{images/roots.png, 250}

|

The point at which a parabola "changes direction" and goes from climbing to sinking (or vice versa).

|
Like linear models, parabolas always cross the y-axis once when @math{x=0}.

|
Also known as @vocab{roots} or @vocab{zeros}. A quadratic function can cross the x-axis once, twice, or not at all.

|===


There are two more specific terms that we can use to describe a parabola's vertex:

- The @vocab{maxima} is the vertex of a parabola that "opens up."
- The @vocab{minima} is the vertex of a parabola that "opens down."

Every parabola also has an @vocab{axis of symmetry}, an imaginary vertical line through the @vocab{vertex} that splits the curve into two congruent parts that mirror each other.

[.lesson-instruction]
Turn to @printable-exercise{parabolas.adoc} to apply our new terminology by sketching and labelling some graphs.

=== Synthesize

* What key characteristics of a scatter plot would provide the clue that we should look for a quadratic model rather than a linear model?
* Why do some parabolas have roots and others don't?
** _The location of the minima or maxima in relationship to the x-axis determines the number of roots._
* What is the difference between a minima and a maxima?
** _A minima is the vertex of a parabola that opens up, while a maxima is the vertex of a parabola that opens down._

== Fitting Quadratic Models @duration{45 minutes}

=== Overview
Students work with the vertex form to fit a quadratic model for the Fuel Efficiency dataset. They extend the model-fitting techniques from the @lesson-link{exploring-linear-models} lesson into quadratic relationships.

=== Launch

We just examined a series of quadratic and linear functions that looked a lot like the ones you might find in an Algebra 2 textbook: clean and predictable. Real-world data, however, is messy! Let's return to our @starter-file{alg2-fuel-efficiency} to dig into that messiness.

[.lesson-instruction]
- A scatter plot of the fuel efficiency data has the familiar "rise and fall" pattern of a parabola... but there appears to be a "dip" around 40mph.
- Does that mean we shouldn't use a quadratic model for the relationship between speed and fuel efficiency? Why or why not?
** _Have students discuss and share back with the class._
** _If necessary, remind students that *models are - by definition - approximations of the real world*._

The existence of a "dip" like this is normal in real data, but it doesn't mean that the overall shape of this relationship isn't quadratic. There's no such thing as a perfect model!

=== Investigate
Let's *try to build the best possible quadratic model we can for our Fuel Efficiency dataset.*

One form of a quadratic model looks like this: @math{f(x)=a(x−h)^2+k}

What do each of these coefficients mean for our model?

[.lesson-instruction]
- Open @starter-file{alg2-exploring-quadratics-desmos}.
- Use the Desmos file to complete @printable-exercise{graphing-models.adoc}

* How do you translate a parabola left and right?
** Change the value of @math{h}
* How do you translate a parabola up and down?
** Change the value of @math{k}
* How do you make a parabola "narrower" or "wider"?
** Change the value of @math{a}

We know that @math{h} in the speed-v-fuel efficiency model is the x-coordinate of our vertex, and that the @vocab{vertex} of our efficiency curve is predicted at roughly @math{45mph}. All we need to do is figure out @math{a} and @math{k}!

@teacher{Before we focus on that, we need to learn about a new Pyret function `num-sqr`.}

[.lesson-instruction]
Return to @starter-file{alg2-fuel-efficiency} and work through @printable-exercise{model-speed-v-mpg.adoc}.

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{Going Deeper: Interaction Effects}

We often think about variables of a model being _independent_ from one another, each contributing a little to the outcome we are measuring. But sometimes one input will amplify the result of another input, meaning their combined contribution is greater than the sum of their separate contributions.

A quadratic relationship often means that one or more variables is _interacting_ with another variable. In our miles-per-gallon example, it turns out that a linear increase in speed has a _more than linear effect_ on mpg!
|===

=== Synthesize

* What was the highest @math{R^2} you were able to get? 
* What did you figure out about how adjusting @math{a} changed the shape of the parabola?
** The _sign_ of @math{a} determines whether the parabola opens up (@math{a > 0}), opens down (@math{a < 0}), or exist as a straight line (@math{a = 0}) Negative @math{a} made the parabola open down. The _magnitude_ of @math{a} determines how "tight" or "steep" the parabola is, with larger magnitudes creating tighter parabolas and values closer to zero creating wider ones.

== Additional Exercises

- @opt-printable-exercise{classifying-defs.adoc}
- @opt-printable-exercise{match-graph-f.adoc} 
- @opt-printable-exercise{match-graph-v.adoc}

[.strategy-box, cols="1", grid="none", stripes="none"]
|===

|
@span{.title}{Coming Soon!}

We are working on collecting more datasets that can be modeled with quadratic functions so that we can offer students more practice with building quadratic models and engage them in thinking about which form is most efficient to start with depending on the available data.  
|===
