= Identifying Slope and y-intercept in Definitions

++++
<style>
#content table {background: transparent; margin: 0px; padding: 5px 20px;}
#content td, th {height: 14ex !important; text-align: center !important;}
#content table td p {white-space: pre-wrap; margin: 0px;}
</style>
++++

The following function definitions are written in math notation and in Pyret. Can you identify their *slope* and *y-intercept*? 

[cols="^.^1a,^.^15a,^.^1a,^.^15a", frame="none", stripes="none"]
|===
| *@n*
| @math{a(b) = 10b - \frac{2}{5}}
|
| 
slope:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{@math{\frac{2}{5}}} }

y-intercept: @fitb{10ex}{10}


| *@n*
| `fun c(d) = (7.5 * d) + 22 end`
|
|
slope:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{7.5} }

y-intercept:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{22} }



| *@n*
| @math{e(f) = \frac{3}{4}f + 19}
|
|
slope:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{@math{\frac{3}{4}}} }

y-intercept:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{} }



| *@n*
| `fun g(h): 20 - (16 * h) end`
|
|
slope:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{-16} }


y-intercept:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{20} }



| *@n*
| @math{f(x) = 91 + 4x}
|
|
slope:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{4} }

y-intercept:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{91} }



| *@n*
| `fun i(j): -15 + (1.5 * j) end`
|
|
slope:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{1.5} }

y-intercept:
@ifnotsoln{@fitb{10ex}{}}
@ifsoln{@fitb{10ex}{-15} }
|===
